### S3: **Part I - Gene Predcition fro Bacteria**

#### **Utils**

In [1]:
import os, requests
from tqdm import tqdm
import pandas as pd

#### **Data extraction**

In [2]:
!wget -c -P ./Data/ https://ftp.ncbi.nih.gov/genomes/genbank/bacteria/assembly_summary.txt

--2025-01-25 23:49:12--  https://ftp.ncbi.nih.gov/genomes/genbank/bacteria/assembly_summary.txt
Resolving ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)... 130.14.250.10, 130.14.250.11, 130.14.250.31, ...
Connecting to ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)|130.14.250.10|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1154162486 (1.1G), 41723389 (40M) remaining [text/plain]
Saving to: ‘./Data/assembly_summary.txt’

assembly_summary.tx 100%[+++++++++++++++++++>]   1.07G  11.3MB/s    in 3.5s

2025-01-25 23:49:17 (11.3 MB/s) - ‘./Data/assembly_summary.txt’ saved [1154162486/1154162486]

In [2]:
assembly_summary = pd.read_csv('./Data/assembly_summary.txt', sep='\t', skiprows=1)
assembly_summary.head(5)

/tmp/ipykernel_4125092/3668181553.py:1: DtypeWarning: Columns (5,6,34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  assembly_summary = pd.read_csv('./Data/assembly_summary.txt', sep='\t', skiprows=1)

,#assembly_accession,bioproject,biosample,wgs_master,refseq_category,taxid,species_taxid,organism_name,infraspecific_name,isolate,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
0,GCA_036600855.1,PRJNA1051366,SAMN38772065,JBAFXD000000000.1,na,7,7,Azorhizobium caulinodans,strain=CNM20190194,na,...,0.0,171.0,171.0,na,na,NaN,0,0,0,na
1,GCA_036600875.1,PRJNA1051366,SAMN38772066,JBAFXC000000000.1,na,7,7,Azorhizobium caulinodans,strain=CNM20190462,na,...,0.0,171.0,171.0,na,na,NaN,0,0,0,na
2,GCA_036600895.1,PRJNA1051366,SAMN38772064,JBAFXE000000000.1,na,7,7,Azorhizobium caulinodans,strain=CNM20190156,na,...,0.0,260.0,260.0,na,na,NaN,0,0,0,na
3,GCA_036600915.1,PRJNA1051366,SAMN38772067,JBAFXF000000000.1,na,7,7,Azorhizobium caulinodans,strain=CNM20220104,na,...,0.0,135.0,135.0,na,na,NaN,0,0,0,na
4,GCA_019958295.1,PRJNA755163,SAMN20395209,JAIOWO000000000.1,na,9,9,Buchnera aphidicola,strain=Tabriz.4,na,...,0.0,1224.0,1224.0,NCBI,NCBI Prokaryotic Genome Annotation Pipeline (P...,2021-09-08,1179,1050,104,na

In [3]:
assembly_summary.columns

Index(['#assembly_accession', 'bioproject', 'biosample', 'wgs_master',
       'refseq_category', 'taxid', 'species_taxid', 'organism_name',
       'infraspecific_name', 'isolate', 'version_status', 'assembly_level',
       'release_type', 'genome_rep', 'seq_rel_date', 'asm_name',
       'asm_submitter', 'gbrs_paired_asm', 'paired_asm_comp', 'ftp_path',
       'excluded_from_refseq', 'relation_to_type_material',
       'asm_not_live_date', 'assembly_type', 'group', 'genome_size',
       'genome_size_ungapped', 'gc_percent', 'replicon_count',
       'scaffold_count', 'contig_count', 'annotation_provider',
       'annotation_name', 'annotation_date', 'total_gene_count',
       'protein_coding_gene_count', 'non_coding_gene_count', 'pubmed_id'],
      dtype='object')

In [4]:
assembly_summary.assembly_level.unique()

array(['Contig', 'Complete Genome', 'Scaffold', 'Chromosome', '9971912',
       '76'], dtype=object)

In [5]:
assembly_summary[assembly_summary['assembly_level'] == "Complete Genome"].shape

(65397, 38)

In [6]:
assembly_summary.shape

(2487118, 38)

In [7]:
na_count = (assembly_summary['ftp_path'] == "na").sum()
na_count

332

In [8]:
assembly_summary.assembly_level.value_counts()

assembly_level
Contig             2039590
Scaffold            373366
Complete Genome      65397
Chromosome            8763
9971912                  1
76                       1
Name: count, dtype: int64

In [9]:
assembly_summary.assembly_type.value_counts()

assembly_type
haploid    2487116
na               1
Name: count, dtype: int64

In [10]:
assembly_summary.annotation_date.isna().sum()

536392

#### **Focus on annotated data**

In [11]:
annotated_summary = assembly_summary[~assembly_summary['annotation_date'].isna()]
annotated_summary.shape

(1950726, 38)

In [12]:
annotated_summary = annotated_summary[annotated_summary['assembly_level'] == "Contig"]
annotated_summary.shape

(1690257, 38)

In [13]:
annotated_summary.organism_name.unique()

array(['Buchnera aphidicola', 'Dictyoglomus thermophilum',
       'Methylophilus methylotrophus', ...,
       'Campylobacter sp. VTCC 70190', 'Nocardia sp. KC 131',
       'Flavobacterium sp. C3NV'], dtype=object)

In [14]:
len(annotated_summary.organism_name.unique())

43694

In [15]:
count_hyphomonas = (annotated_summary['organism_name'] == 'Hyphomonas sp.').sum()
print(f"Number of rows with organism_name 'Hyphomonas sp.': {count_hyphomonas}")

Number of rows with organism_name 'Hyphomonas sp.': 49

#### **Downloading genome file**

In [16]:
for i, row in annotated_summary.iterrows():
    path = row['ftp_path']
    print(row)
    break

#assembly_accession                                            GCA_019958295.1
bioproject                                                         PRJNA755163
biosample                                                         SAMN20395209
wgs_master                                                   JAIOWO000000000.1
refseq_category                                                             na
taxid                                                                        9
species_taxid                                                                9
organism_name                                              Buchnera aphidicola
infraspecific_name                                             strain=Tabriz.4
isolate                                                                     na
version_status                                                          latest
assembly_level                                                          Contig
release_type                                                             Major
genome_rep                                                                Full
seq_rel_date                                                        2021-09-13
asm_name                                                          ASM1995829v1
asm_submitter                                  Tabriz University, Tabriz, Iran
gbrs_paired_asm                                                             na
paired_asm_comp                                                             na
ftp_path                     https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/0...
excluded_from_refseq                                       fragmented assembly
relation_to_type_material                                                   na
asm_not_live_date                                                   na
assembly_type                                                          haploid
group                                                                 bacteria
genome_size                                                           657623.0
genome_size_ungapped                                                  657623.0
gc_percent                                                                27.5
replicon_count                                                             0.0
scaffold_count                                                          1224.0
contig_count                                                            1224.0
annotation_provider                                                       NCBI
annotation_name              NCBI Prokaryotic Genome Annotation Pipeline (P...
annotation_date                                                     2021-09-08
total_gene_count                                                          1179
protein_coding_gene_count                                                 1050
non_coding_gene_count                                                      104
pubmed_id                                                                   na
Name: 4, dtype: object

In [18]:
lf = assembly_summary[assembly_summary['asm_name'] == "ASM973039v1"]
lf

,#assembly_accession,bioproject,biosample,wgs_master,refseq_category,taxid,species_taxid,organism_name,infraspecific_name,isolate,...,replicon_count,scaffold_count,contig_count,annotation_provider,annotation_name,annotation_date,total_gene_count,protein_coding_gene_count,non_coding_gene_count,pubmed_id
14511,GCA_009730395.1,PRJNA231221,SAMN11056450,na,reference genome,195,195,Campylobacter coli,strain=FDAARGOS_735,na,...,2.0,2.0,2.0,NCBI,NCBI Prokaryotic Genome Annotation Pipeline (P...,2019-11-22,1760,1663,56,na

In [19]:
lf['assembly_level']

14511    Complete Genome
Name: assembly_level, dtype: object

In [23]:
lf['#assembly_accession'] == "GCA_009730395.1"

14511    True
Name: #assembly_accession, dtype: bool

In [32]:
a = lf.iloc[0]['ftp_path']
a

'https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/009/730/395/GCA_009730395.1_ASM973039v1'

In [16]:
storage_folder = "./Data/RawContig/"
failure_log_path = "./Data/failure.log"
os.makedirs(os.path.dirname(failure_log_path), exist_ok=True)

def log_failure(file_base_name):
    with open(failure_log_path, "a") as log_file:
        log_file.write(f"{file_base_name}\n")

def download_file(url, save_path):
    try:
        response = requests.get(url)
        response.raise_for_status()
        with open(save_path, 'wb') as file:
            file.write(response.content)
    except requests.exceptions.RequestException as e:
        print(f"Error downloading the file: {e}")

<!--
# files to download
    files_to_download = [
        "genomic.fna.gz",
        "genomic.gff.gz",
        
        "ani_contam_ranges.tsv",
        "ani_report.txt",
        "assembly_report.txt",
        "assembly_stats.txt",
        "cds_from_genomic.fna.gz",
        "fcs_report.txt",
        "feature_count.txt.gz",
        "feature_table.txt.gz",
        
        "genomic.gbff.gz",
        
        "genomic.gtf.gz",
        "protein.faa.gz",
        "protein.gpff.gz",
        "rna_from_genomic.fna.gz",
        "translated_cds.faa.gz",
        "wgsmaster.gbff.gz"
    ]
-->

In [ ]:
annotated_summary_ = annotated_summary#.iloc[38526:]
for i, row in tqdm(annotated_summary_.iterrows(), desc="Retreiveing data", nrows=100):
    path = row['ftp_path']
    folder_name = f"{row['#assembly_accession']}_{row['asm_name']}"
    folder_path = os.path.join(storage_folder, folder_name)
    
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
    else:
        print(f"Folder '{folder_name}' already exists. Skipping...")
        continue

    # files to download
    files_to_download = [
        "genomic.fna.gz",
        "genomic.gff.gz",
    ]
    for file_name in files_to_download:
        file_base_name = path.split('/')[-1]
        file_url = os.path.join(path, file_base_name) + "_" + file_name
        output_file_path = os.path.join(folder_path, file_name)
        if os.path.exists(output_file_path):
            continue
        try:
            download_file(file_url, output_file_path)
        except Exception as e:
            print(f"Failed to download {file_name}: {e}")
            log_failure(file_base_name)
            if os.path.exists(folder_path) and not os.listdir(folder_path):
                os.rmdir(folder_path)
    #break

Retreiveing data: 1348it [00:01, 1271.58it/s]

Folder 'GCA_019958295.1_ASM1995829v1' already exists. Skipping...
Folder 'GCA_029005255.1_ASM2900525v1' already exists. Skipping...
Folder 'GCA_008244535.1_ASM824453v1' already exists. Skipping...
Folder 'GCA_026418735.1_ASM2641873v1' already exists. Skipping...
Folder 'GCA_039630455.1_ASM3963045v1' already exists. Skipping...
Folder 'GCA_008015785.1_ASM801578v1' already exists. Skipping...
Folder 'GCA_019654935.1_ASM1965493v1' already exists. Skipping...
Folder 'GCA_019655395.1_ASM1965539v1' already exists. Skipping...
Folder 'GCA_033719835.1_ASM3371983v1' already exists. Skipping...
Folder 'GCA_020216695.1_ASM2021669v1' already exists. Skipping...
Folder 'GCA_025397935.1_ASM2539793v1' already exists. Skipping...
Folder 'GCA_031456735.1_ASM3145673v1' already exists. Skipping...
Folder 'GCA_900457065.1_57675_D02' already exists. Skipping...
Folder 'GCA_007197645.1_ASM719764v1' already exists. Skipping...
Folder 'GCA_007991095.1_ASM799109v1' already exists. Skipping...
Folder 'GCA_023195975.1_ASM2319597v1' already exists. Skipping...
Folder 'GCA_013116805.1_ASM1311680v1' already exists. Skipping...
Folder 'GCA_013116825.1_ASM1311682v1' already exists. Skipping...
Folder 'GCA_013116835.1_ASM1311683v1' already exists. Skipping...
Folder 'GCA_013116865.1_ASM1311686v1' already exists. Skipping...
Folder 'GCA_017302985.1_ASM1730298v1' already exists. Skipping...
Folder 'GCA_900109545.1_IMG-taxon 2693429895 annotated assembly' already exists. Skipping...
Folder 'GCA_003243425.1_ASM324342v1' already exists. Skipping...
Folder 'GCA_002343915.1_ASM234391v1' already exists. Skipping...
Folder 'GCA_011322875.1_ASM1132287v1' already exists. Skipping...
Folder 'GCA_011361725.1_ASM1136172v1' already exists. Skipping...
Folder 'GCA_001589215.1_sce703.1' already exists. Skipping...
Folder 'GCA_001589295.1_sce163.1' already exists. Skipping...
Folder 'GCA_002748255.1_ASM274825v1' already exists. Skipping...
Folder 'GCA_035539515.1_ASM3553951v1' already exists. Skipping...
Folder 'GCA_014378125.1_ASM1437812v1' already exists. Skipping...
Folder 'GCA_018002775.1_ASM1800277v1' already exists. Skipping...
Folder 'GCA_003789105.1_ASM378910v1' already exists. Skipping...
Folder 'GCA_040549365.1_ASM4054936v1' already exists. Skipping...
Folder 'GCA_014378155.1_ASM1437815v1' already exists. Skipping...
Folder 'GCA_015069865.1_ASM1506986v1' already exists. Skipping...
Folder 'GCA_016125585.1_ASM1612558v1' already exists. Skipping...
Folder 'GCA_017418455.1_ASM1741845v1' already exists. Skipping...
Folder 'GCA_017999465.1_ASM1799946v1' already exists. Skipping...
Folder 'GCA_019636175.1_ASM1963617v1' already exists. Skipping...
Folder 'GCA_021741355.1_ASM2174135v1' already exists. Skipping...
Folder 'GCA_023146535.1_ASM2314653v1' already exists. Skipping...
Folder 'GCA_028291055.1_ASM2829105v1' already exists. Skipping...
Folder 'GCA_028291125.1_ASM2829112v1' already exists. Skipping...
Folder 'GCA_028291265.1_ASM2829126v1' already exists. Skipping...
Folder 'GCA_029866155.1_ASM2986615v1' already exists. Skipping...
Folder 'GCA_030645575.1_ASM3064557v1' already exists. Skipping...
Folder 'GCA_030652755.1_ASM3065275v1' already exists. Skipping...
Folder 'GCA_030654405.1_ASM3065440v1' already exists. Skipping...
Folder 'GCA_030655455.1_ASM3065545v1' already exists. Skipping...
Folder 'GCA_030678995.1_ASM3067899v1' already exists. Skipping...
Folder 'GCA_030680355.1_ASM3068035v1' already exists. Skipping...
Folder 'GCA_030683005.1_ASM3068300v1' already exists. Skipping...
Folder 'GCA_035254145.1_ASM3525414v1' already exists. Skipping...
Folder 'GCA_035563875.1_ASM3556387v1' already exists. Skipping...
Folder 'GCA_035564285.1_ASM3556428v1' already exists. Skipping...
Folder 'GCA_035564305.1_ASM3556430v1' already exists. Skipping...
Folder 'GCA_035565495.1_ASM3556549v1' already exists. Skipping...
Folder 'GCA_035627755.1_ASM3562775v1' already exists. Skipping...
Folder 'GCA_040508925.1_ASM4050892v1' already exists. Skipping...
Folder 'GCA_041674445.1_ASM4167444v1' already exists. Skipping...
Folder 'GCA_002928395.1_ASM292839v1' already exists. Skipping...
Folder 'GCA_002928465.1_ASM292846v1' already exists. Skipping...
Folder 'GCA_002928515.1_ASM292851v1' already exists. Skipping...
Folder 'GCA_002928735.1_ASM292873v1' already exists. Skipping...
Folder 'GCA_002928955.1_ASM292895v1' already exists. Skipping...
Folder 'GCA_009026145.1_ASM902614v1' already exists. Skipping...
Folder 'GCA_013141015.1_ASM1314101v1' already exists. Skipping...
Folder 'GCA_013821915.1_ASM1382191v1' already exists. Skipping...
Folder 'GCA_013822135.1_ASM1382213v1' already exists. Skipping...
Folder 'GCA_014379315.1_ASM1437931v1' already exists. Skipping...
Folder 'GCA_016716675.1_ASM1671667v1' already exists. Skipping...
Folder 'GCA_016793445.1_ASM1679344v1' already exists. Skipping...
Folder 'GCA_017512425.1_ASM1751242v1' already exists. Skipping...
Folder 'GCA_019744875.1_ASM1974487v1' already exists. Skipping...
Folder 'GCA_019748215.1_ASM1974821v1' already exists. Skipping...
Folder 'GCA_019751875.1_ASM1975187v1' already exists. Skipping...
Folder 'GCA_019753045.1_ASM1975304v1' already exists. Skipping...
Folder 'GCA_019912585.1_ASM1991258v1' already exists. Skipping...
Folder 'GCA_020852195.1_ASM2085219v1' already exists. Skipping...
Folder 'GCA_024230315.1_ASM2423031v1' already exists. Skipping...
Folder 'GCA_030680255.1_ASM3068025v1' already exists. Skipping...
Folder 'GCA_030681995.1_ASM3068199v1' already exists. Skipping...
Folder 'GCA_033765145.1_ASM3376514v1' already exists. Skipping...
Folder 'GCA_035517115.1_ASM3551711v1' already exists. Skipping...
Folder 'GCA_035538995.1_ASM3553899v1' already exists. Skipping...
Folder 'GCA_035547255.1_ASM3554725v1' already exists. Skipping...
Folder 'GCA_035548195.1_ASM3554819v1' already exists. Skipping...
Folder 'GCA_035555755.1_ASM3555575v1' already exists. Skipping...
Folder 'GCA_035572195.1_ASM3557219v1' already exists. Skipping...
Folder 'GCA_035581405.1_ASM3558140v1' already exists. Skipping...
Folder 'GCA_035627215.1_ASM3562721v1' already exists. Skipping...
Folder 'GCA_035687085.1_ASM3568708v1' already exists. Skipping...
Folder 'GCA_035687305.1_ASM3568730v1' already exists. Skipping...
Folder 'GCA_036262015.1_ASM3626201v1' already exists. Skipping...
Folder 'GCA_036277375.1_ASM3627737v1' already exists. Skipping...
Folder 'GCA_036396665.1_ASM3639666v1' already exists. Skipping...
Folder 'GCA_036443365.1_ASM3644336v1' already exists. Skipping...
Folder 'GCA_036445195.1_ASM3644519v1' already exists. Skipping...
Folder 'GCA_036445495.1_ASM3644549v1' already exists. Skipping...
Folder 'GCA_036445975.1_ASM3644597v1' already exists. Skipping...
Folder 'GCA_036447865.1_ASM3644786v1' already exists. Skipping...
Folder 'GCA_036448635.1_ASM3644863v1' already exists. Skipping...
Folder 'GCA_036478695.1_ASM3647869v1' already exists. Skipping...
Folder 'GCA_036481195.1_ASM3648119v1' already exists. Skipping...
Folder 'GCA_036555365.1_ASM3655536v1' already exists. Skipping...
Folder 'GCA_036559705.1_ASM3655970v1' already exists. Skipping...
Folder 'GCA_036560245.1_ASM3656024v1' already exists. Skipping...
Folder 'GCA_036560525.1_ASM3656052v1' already exists. Skipping...
Folder 'GCA_037201465.1_ASM3720146v1' already exists. Skipping...
Folder 'GCA_039933175.1_ASM3993317v1' already exists. Skipping...
Folder 'GCA_040079945.1_ASM4007994v1' already exists. Skipping...
Folder 'GCA_040080075.1_ASM4008007v1' already exists. Skipping...
Folder 'GCA_040080375.1_ASM4008037v1' already exists. Skipping...
Folder 'GCA_040080465.1_ASM4008046v1' already exists. Skipping...
Folder 'GCA_040080695.1_ASM4008069v1' already exists. Skipping...
Folder 'GCA_040348875.1_ASM4034887v1' already exists. Skipping...
Folder 'GCA_040509255.1_ASM4050925v1' already exists. Skipping...
Folder 'GCA_040509435.1_ASM4050943v1' already exists. Skipping...
Folder 'GCA_040510495.1_ASM4051049v1' already exists. Skipping...
Folder 'GCA_040513135.1_ASM4051313v1' already exists. Skipping...
Folder 'GCA_041659645.1_ASM4165964v1' already exists. Skipping...
Folder 'GCA_041659825.1_ASM4165982v1' already exists. Skipping...
Folder 'GCA_041674905.1_ASM4167490v1' already exists. Skipping...
Folder 'GCA_013626205.1_ASM1362620v1' already exists. Skipping...
Folder 'GCA_002683615.1_ASM268361v1' already exists. Skipping...
Folder 'GCA_002684195.1_ASM268419v1' already exists. Skipping...
Folder 'GCA_002689395.1_ASM268939v1' already exists. Skipping...
Folder 'GCA_002692925.1_ASM269292v1' already exists. Skipping...
Folder 'GCA_002695465.1_ASM269546v1' already exists. Skipping...
Folder 'GCA_002695785.1_ASM269578v1' already exists. Skipping...
Folder 'GCA_002700305.1_ASM270030v1' already exists. Skipping...
Folder 'GCA_002709595.1_ASM270959v1' already exists. Skipping...
Folder 'GCA_002710445.1_ASM271044v1' already exists. Skipping...
Folder 'GCA_002716205.1_ASM271620v1' already exists. Skipping...
Folder 'GCA_002722805.1_ASM272280v1' already exists. Skipping...
Folder 'GCA_003331325.1_ASM333132v1' already exists. Skipping...
Folder 'GCA_013791775.1_ASM1379177v1' already exists. Skipping...
Folder 'GCA_013823385.1_ASM1382338v1' already exists. Skipping...
Folder 'GCA_013824195.1_ASM1382419v1' already exists. Skipping...
Folder 'GCA_016124495.1_ASM1612449v1' already exists. Skipping...
Folder 'GCA_016125515.1_ASM1612551v1' already exists. Skipping...
Folder 'GCA_016765355.1_ASM1676535v1' already exists. Skipping...
Folder 'GCA_017640815.1_ASM1764081v1' already exists. Skipping...
Folder 'GCA_020425295.1_ASM2042529v1' already exists. Skipping...
Folder 'GCA_020638455.1_ASM2063845v1' already exists. Skipping...
Folder 'GCA_020638515.1_ASM2063851v1' already exists. Skipping...
Folder 'GCA_024743015.1_ASM2474301v1' already exists. Skipping...
Folder 'GCA_024743155.1_ASM2474315v1' already exists. Skipping...
Folder 'GCA_030681215.1_ASM3068121v1' already exists. Skipping...
Folder 'GCA_030695315.1_ASM3069531v1' already exists. Skipping...
Folder 'GCA_033720055.1_ASM3372005v1' already exists. Skipping...
Folder 'GCA_039769005.1_ASM3976900v1' already exists. Skipping...
Folder 'GCA_039943795.1_ASM3994379v1' already exists. Skipping...
Folder 'GCA_039965035.1_ASM3996503v1' already exists. Skipping...
Folder 'GCA_039965765.1_ASM3996576v1' already exists. Skipping...
Folder 'GCA_039966835.1_ASM3996683v1' already exists. Skipping...
Folder 'GCA_039968645.1_ASM3996864v1' already exists. Skipping...
Folder 'GCA_039980365.1_ASM3998036v1' already exists. Skipping...
Folder 'GCA_039988555.1_ASM3998855v1' already exists. Skipping...
Folder 'GCA_039990455.1_ASM3999045v1' already exists. Skipping...
Folder 'GCA_040119175.1_ASM4011917v1' already exists. Skipping...
Folder 'GCA_040119225.1_ASM4011922v1' already exists. Skipping...
Folder 'GCA_040216775.1_ASM4021677v1' already exists. Skipping...
Folder 'GCA_040222895.1_ASM4022289v1' already exists. Skipping...
Folder 'GCA_040223555.1_ASM4022355v1' already exists. Skipping...
Folder 'GCA_040226305.1_ASM4022630v1' already exists. Skipping...
Folder 'GCA_041398365.1_ASM4139836v1' already exists. Skipping...
Folder 'GCA_041398385.1_ASM4139838v1' already exists. Skipping...
Folder 'GCA_041398405.1_ASM4139840v1' already exists. Skipping...
Folder 'GCA_041398425.1_ASM4139842v1' already exists. Skipping...
Folder 'GCA_041398445.1_ASM4139844v1' already exists. Skipping...
Folder 'GCA_041398465.1_ASM4139846v1' already exists. Skipping...
Folder 'GCA_041398485.1_ASM4139848v1' already exists. Skipping...
Folder 'GCA_003751345.1_ASM375134v1' already exists. Skipping...
Folder 'GCA_003963445.1_UV5' already exists. Skipping...
Folder 'GCA_004339465.1_ASM433946v1' already exists. Skipping...
Folder 'GCA_007997115.1_ASM799711v1' already exists. Skipping...
Folder 'GCA_008274645.2_ASM827464v2' already exists. Skipping...
Folder 'GCA_004292915.1_ASM429291v1' already exists. Skipping...
Folder 'GCA_004293985.1_ASM429398v1' already exists. Skipping...
Folder 'GCA_040543585.1_ASM4054358v1' already exists. Skipping...
Folder 'GCA_013822725.1_ASM1382272v1' already exists. Skipping...
Folder 'GCA_013822735.1_ASM1382273v1' already exists. Skipping...
Folder 'GCA_021300155.1_ASM2130015v1' already exists. Skipping...
Folder 'GCA_021736575.1_ASM2173657v1' already exists. Skipping...
Folder 'GCA_025459245.1_ASM2545924v1' already exists. Skipping...
Folder 'GCA_035525355.1_ASM3552535v1' already exists. Skipping...
Folder 'GCA_037137495.1_ASM3713749v1' already exists. Skipping...
Folder 'GCA_040080875.1_ASM4008087v1' already exists. Skipping...
Folder 'GCA_040218455.1_ASM4021845v1' already exists. Skipping...
Folder 'GCA_002967715.1_ASM296771v1' already exists. Skipping...
Folder 'GCA_002967725.1_ASM296772v1' already exists. Skipping...
Folder 'GCA_002967755.1_ASM296775v1' already exists. Skipping...
Folder 'GCA_002967765.1_ASM296776v1' already exists. Skipping...
Folder 'GCA_003044115.1_ASM304411v1' already exists. Skipping...
Folder 'GCA_002083055.2_ASM208305v2' already exists. Skipping...
Folder 'GCA_002995865.1_ASM299586v1' already exists. Skipping...
Folder 'GCA_002995885.1_ASM299588v1' already exists. Skipping...
Folder 'GCA_002995905.1_ASM299590v1' already exists. Skipping...
Folder 'GCA_002995915.1_ASM299591v1' already exists. Skipping...
Folder 'GCA_002995935.1_ASM299593v1' already exists. Skipping...
Folder 'GCA_002995965.1_ASM299596v1' already exists. Skipping...
Folder 'GCA_002995985.1_ASM299598v1' already exists. Skipping...
Folder 'GCA_002996005.1_ASM299600v1' already exists. Skipping...
Folder 'GCA_002996025.1_ASM299602v1' already exists. Skipping...
Folder 'GCA_002996045.1_ASM299604v1' already exists. Skipping...
Folder 'GCA_002996065.1_ASM299606v1' already exists. Skipping...
Folder 'GCA_002996085.1_ASM299608v1' already exists. Skipping...
Folder 'GCA_002996105.1_ASM299610v1' already exists. Skipping...
Folder 'GCA_002996125.1_ASM299612v1' already exists. Skipping...
Folder 'GCA_002996145.1_ASM299614v1' already exists. Skipping...
Folder 'GCA_002996165.1_ASM299616v1' already exists. Skipping...
Folder 'GCA_002996175.1_ASM299617v1' already exists. Skipping...
Folder 'GCA_002996185.1_ASM299618v1' already exists. Skipping...
Folder 'GCA_002996225.1_ASM299622v1' already exists. Skipping...
Folder 'GCA_002996245.1_ASM299624v1' already exists. Skipping...
Folder 'GCA_002996265.1_ASM299626v1' already exists. Skipping...
Folder 'GCA_002996275.1_ASM299627v1' already exists. Skipping...
Folder 'GCA_002996285.1_ASM299628v1' already exists. Skipping...
Folder 'GCA_002996305.1_ASM299630v1' already exists. Skipping...
Folder 'GCA_002996345.1_ASM299634v1' already exists. Skipping...
Folder 'GCA_002996365.1_ASM299636v1' already exists. Skipping...
Folder 'GCA_002996385.1_ASM299638v1' already exists. Skipping...
Folder 'GCA_002996395.1_ASM299639v1' already exists. Skipping...
Folder 'GCA_002996405.1_ASM299640v1' already exists. Skipping...
Folder 'GCA_002996445.1_ASM299644v1' already exists. Skipping...
Folder 'GCA_002996465.1_ASM299646v1' already exists. Skipping...
Folder 'GCA_002996475.1_ASM299647v1' already exists. Skipping...
Folder 'GCA_002996485.1_ASM299648v1' already exists. Skipping...
Folder 'GCA_002996525.1_ASM299652v1' already exists. Skipping...
Folder 'GCA_002996545.1_ASM299654v1' already exists. Skipping...
Folder 'GCA_002996565.1_ASM299656v1' already exists. Skipping...
Folder 'GCA_002996585.1_ASM299658v1' already exists. Skipping...
Folder 'GCA_002996605.1_ASM299660v1' already exists. Skipping...
Folder 'GCA_002996625.1_ASM299662v1' already exists. Skipping...
Folder 'GCA_002996645.1_ASM299664v1' already exists. Skipping...
Folder 'GCA_002996685.1_ASM299668v1' already exists. Skipping...
Folder 'GCA_002996705.1_ASM299670v1' already exists. Skipping...
Folder 'GCA_002996715.1_ASM299671v1' already exists. Skipping...
Folder 'GCA_002996745.1_ASM299674v1' already exists. Skipping...
Folder 'GCA_002996785.1_ASM299678v1' already exists. Skipping...
Folder 'GCA_002996795.1_ASM299679v1' already exists. Skipping...
Folder 'GCA_002996845.1_ASM299684v1' already exists. Skipping...
Folder 'GCA_002996865.1_ASM299686v1' already exists. Skipping...
Folder 'GCA_002996895.1_ASM299689v1' already exists. Skipping...
Folder 'GCA_002996925.1_ASM299692v1' already exists. Skipping...
Folder 'GCA_002996965.1_ASM299696v1' already exists. Skipping...
Folder 'GCA_002996985.1_ASM299698v1' already exists. Skipping...
Folder 'GCA_002997025.1_ASM299702v1' already exists. Skipping...
Folder 'GCA_002997045.1_ASM299704v1' already exists. Skipping...
Folder 'GCA_002997065.1_ASM299706v1' already exists. Skipping...
Folder 'GCA_002997085.1_ASM299708v1' already exists. Skipping...
Folder 'GCA_002997105.1_ASM299710v1' already exists. Skipping...
Folder 'GCA_002997145.1_ASM299714v1' already exists. Skipping...
Folder 'GCA_002997165.1_ASM299716v1' already exists. Skipping...
Folder 'GCA_002997185.1_ASM299718v1' already exists. Skipping...
Folder 'GCA_002997205.1_ASM299720v1' already exists. Skipping...
Folder 'GCA_002997245.1_ASM299724v1' already exists. Skipping...
Folder 'GCA_002997265.1_ASM299726v1' already exists. Skipping...
Folder 'GCA_002997285.1_ASM299728v1' already exists. Skipping...
Folder 'GCA_021043425.1_ASM2104342v1' already exists. Skipping...
Folder 'GCA_021043435.1_ASM2104343v1' already exists. Skipping...
Folder 'GCA_021043465.1_ASM2104346v1' already exists. Skipping...
Folder 'GCA_021043485.1_ASM2104348v1' already exists. Skipping...
Folder 'GCA_021043505.1_ASM2104350v1' already exists. Skipping...
Folder 'GCA_021043525.1_ASM2104352v1' already exists. Skipping...
Folder 'GCA_021043535.1_ASM2104353v1' already exists. Skipping...
Folder 'GCA_021043555.1_ASM2104355v1' already exists. Skipping...
Folder 'GCA_021043585.1_ASM2104358v1' already exists. Skipping...
Folder 'GCA_021043615.1_ASM2104361v1' already exists. Skipping...
Folder 'GCA_021043645.1_ASM2104364v1' already exists. Skipping...
Folder 'GCA_021043665.1_ASM2104366v1' already exists. Skipping...
Folder 'GCA_021043705.1_ASM2104370v1' already exists. Skipping...
Folder 'GCA_021043735.1_ASM2104373v1' already exists. Skipping...
Folder 'GCA_021043745.1_ASM2104374v1' already exists. Skipping...
Folder 'GCA_021043785.1_ASM2104378v1' already exists. Skipping...
Folder 'GCA_021043805.1_ASM2104380v1' already exists. Skipping...
Folder 'GCA_021043825.1_ASM2104382v1' already exists. Skipping...
Folder 'GCA_021043845.1_ASM2104384v1' already exists. Skipping...
Folder 'GCA_021043865.1_ASM2104386v1' already exists. Skipping...
Folder 'GCA_021043875.1_ASM2104387v1' already exists. Skipping...
Folder 'GCA_021043905.1_ASM2104390v1' already exists. Skipping...
Folder 'GCA_021043925.1_ASM2104392v1' already exists. Skipping...
Folder 'GCA_021043935.1_ASM2104393v1' already exists. Skipping...
Folder 'GCA_021043965.1_ASM2104396v1' already exists. Skipping...
Folder 'GCA_021043985.1_ASM2104398v1' already exists. Skipping...
Folder 'GCA_021044005.1_ASM2104400v1' already exists. Skipping...
Folder 'GCA_021044045.1_ASM2104404v1' already exists. Skipping...
Folder 'GCA_021044055.1_ASM2104405v1' already exists. Skipping...
Folder 'GCA_021044065.1_ASM2104406v1' already exists. Skipping...
Folder 'GCA_021044085.1_ASM2104408v1' already exists. Skipping...
Folder 'GCA_021044125.1_ASM2104412v1' already exists. Skipping...
Folder 'GCA_021044145.1_ASM2104414v1' already exists. Skipping...
Folder 'GCA_021044165.1_ASM2104416v1' already exists. Skipping...
Folder 'GCA_021044175.1_ASM2104417v1' already exists. Skipping...
Folder 'GCA_021044185.1_ASM2104418v1' already exists. Skipping...
Folder 'GCA_021044225.1_ASM2104422v1' already exists. Skipping...
Folder 'GCA_021044245.1_ASM2104424v1' already exists. Skipping...
Folder 'GCA_021044255.1_ASM2104425v1' already exists. Skipping...
Folder 'GCA_021044285.1_ASM2104428v1' already exists. Skipping...
Folder 'GCA_021044295.1_ASM2104429v1' already exists. Skipping...
Folder 'GCA_021044325.1_ASM2104432v1' already exists. Skipping...
Folder 'GCA_021044335.1_ASM2104433v1' already exists. Skipping...

Retreiveing data: 2699it [00:01, 2800.36it/s]

Folder 'GCA_004806575.1_PDT000381378.1' already exists. Skipping...
Folder 'GCA_004806595.1_PDT000380242.2' already exists. Skipping...
Folder 'GCA_004806655.1_PDT000381382.1' already exists. Skipping...
Folder 'GCA_004806775.1_PDT000382847.1' already exists. Skipping...
Folder 'GCA_004807235.1_PDT000381373.1' already exists. Skipping...
Folder 'GCA_004807255.1_PDT000381372.1' already exists. Skipping...
Folder 'GCA_004807375.1_PDT000381384.1' already exists. Skipping...
Folder 'GCA_004807415.1_PDT000381375.1' already exists. Skipping...
Folder 'GCA_004807455.1_PDT000382629.1' already exists. Skipping...
Folder 'GCA_004807475.1_PDT000382626.1' already exists. Skipping...
Folder 'GCA_004807485.1_PDT000381386.1' already exists. Skipping...
Folder 'GCA_004807535.1_PDT000382630.1' already exists. Skipping...
Folder 'GCA_004807555.1_PDT000382858.1' already exists. Skipping...
Folder 'GCA_004808215.1_PDT000382624.1' already exists. Skipping...
Folder 'GCA_004808235.1_PDT000382631.1' already exists. Skipping...
Folder 'GCA_004808275.1_PDT000382632.1' already exists. Skipping...
Folder 'GCA_004808315.1_PDT000382633.1' already exists. Skipping...
Folder 'GCA_004808355.1_PDT000382636.1' already exists. Skipping...
Folder 'GCA_004808375.1_PDT000382634.1' already exists. Skipping...
Folder 'GCA_004808475.1_PDT000384493.1' already exists. Skipping...
Folder 'GCA_004808495.1_PDT000384516.1' already exists. Skipping...
Folder 'GCA_004808615.1_PDT000384494.1' already exists. Skipping...
Folder 'GCA_004808655.1_PDT000384537.1' already exists. Skipping...
Folder 'GCA_004808665.1_PDT000384520.1' already exists. Skipping...
Folder 'GCA_004808695.1_PDT000384508.1' already exists. Skipping...
Folder 'GCA_004808735.1_PDT000384517.1' already exists. Skipping...
Folder 'GCA_004808755.1_PDT000384521.1' already exists. Skipping...
Folder 'GCA_004808815.1_PDT000384569.1' already exists. Skipping...
Folder 'GCA_004808875.1_PDT000384827.1' already exists. Skipping...
Folder 'GCA_004808915.1_PDT000384864.1' already exists. Skipping...
Folder 'GCA_004808975.1_PDT000384847.1' already exists. Skipping...
Folder 'GCA_004809015.1_PDT000384883.1' already exists. Skipping...
Folder 'GCA_004809395.1_PDT000384504.1' already exists. Skipping...
Folder 'GCA_004809435.1_PDT000384505.1' already exists. Skipping...
Folder 'GCA_004809455.1_PDT000384507.1' already exists. Skipping...
Folder 'GCA_004809515.1_PDT000384523.1' already exists. Skipping...
Folder 'GCA_004809555.1_PDT000384528.1' already exists. Skipping...
Folder 'GCA_004809575.1_PDT000384535.1' already exists. Skipping...
Folder 'GCA_004809595.1_PDT000384530.1' already exists. Skipping...
Folder 'GCA_004809655.1_PDT000384567.1' already exists. Skipping...
Folder 'GCA_004809675.1_PDT000384553.1' already exists. Skipping...
Folder 'GCA_004809695.1_PDT000384546.1' already exists. Skipping...
Folder 'GCA_004809735.1_PDT000384552.1' already exists. Skipping...
Folder 'GCA_004809775.1_PDT000384544.1' already exists. Skipping...
Folder 'GCA_004809795.1_PDT000384548.1' already exists. Skipping...
Folder 'GCA_004809895.1_PDT000384836.1' already exists. Skipping...
Folder 'GCA_004809915.1_PDT000384839.1' already exists. Skipping...
Folder 'GCA_004809935.1_PDT000384834.1' already exists. Skipping...
Folder 'GCA_004809955.1_PDT000384837.1' already exists. Skipping...
Folder 'GCA_004809995.1_PDT000384841.1' already exists. Skipping...
Folder 'GCA_004810035.1_PDT000384844.1' already exists. Skipping...
Folder 'GCA_004810075.1_PDT000384856.1' already exists. Skipping...
Folder 'GCA_004810095.1_PDT000384857.1' already exists. Skipping...
Folder 'GCA_004810115.1_PDT000384860.1' already exists. Skipping...
Folder 'GCA_004810135.1_PDT000384854.1' already exists. Skipping...
Folder 'GCA_004810175.1_PDT000384855.1' already exists. Skipping...
Folder 'GCA_004810195.1_PDT000384858.1' already exists. Skipping...
Folder 'GCA_004810235.1_PDT000384863.1' already exists. Skipping...
Folder 'GCA_004810295.1_PDT000384891.1' already exists. Skipping...
Folder 'GCA_004810335.1_PDT000384888.1' already exists. Skipping...
Folder 'GCA_004810375.1_PDT000384894.1' already exists. Skipping...
Folder 'GCA_004810395.1_PDT000384895.1' already exists. Skipping...
Folder 'GCA_004810535.1_PDT000384896.1' already exists. Skipping...
Folder 'GCA_004810555.1_PDT000384897.1' already exists. Skipping...
Folder 'GCA_004810575.1_PDT000385011.1' already exists. Skipping...
Folder 'GCA_004810655.1_PDT000386216.1' already exists. Skipping...
Folder 'GCA_004810715.1_PDT000384898.1' already exists. Skipping...
Folder 'GCA_004810725.1_PDT000384901.1' already exists. Skipping...
Folder 'GCA_004810755.1_PDT000384909.1' already exists. Skipping...
Folder 'GCA_004810835.1_PDT000385025.1' already exists. Skipping...
Folder 'GCA_004810875.1_PDT000386701.1' already exists. Skipping...
Folder 'GCA_004810935.1_PDT000385022.1' already exists. Skipping...
Folder 'GCA_004810955.1_PDT000385018.1' already exists. Skipping...
Folder 'GCA_004811055.1_PDT000386221.1' already exists. Skipping...
Folder 'GCA_004811075.1_PDT000386215.1' already exists. Skipping...
Folder 'GCA_004811135.1_PDT000386206.1' already exists. Skipping...
Folder 'GCA_004811175.1_PDT000386706.1' already exists. Skipping...
Folder 'GCA_004811235.1_PDT000386208.1' already exists. Skipping...
Folder 'GCA_004811275.1_PDT000386704.1' already exists. Skipping...
Folder 'GCA_004811295.1_PDT000386224.1' already exists. Skipping...
Folder 'GCA_004811335.1_PDT000386225.1' already exists. Skipping...
Folder 'GCA_004811345.1_PDT000386226.1' already exists. Skipping...
Folder 'GCA_004811395.1_PDT000386227.1' already exists. Skipping...
Folder 'GCA_004811455.1_PDT000386707.1' already exists. Skipping...
Folder 'GCA_004811515.1_PDT000386980.1' already exists. Skipping...
Folder 'GCA_004811595.1_PDT000386700.1' already exists. Skipping...
Folder 'GCA_004811615.1_PDT000388086.1' already exists. Skipping...
Folder 'GCA_004811635.1_PDT000386699.1' already exists. Skipping...
Folder 'GCA_004811735.1_PDT000387419.1' already exists. Skipping...
Folder 'GCA_004811775.1_PDT000387417.1' already exists. Skipping...
Folder 'GCA_004811805.1_PDT000387141.1' already exists. Skipping...
Folder 'GCA_004811895.1_PDT000387156.1' already exists. Skipping...
Folder 'GCA_004812035.1_PDT000387130.1' already exists. Skipping...
Folder 'GCA_004812055.1_PDT000387450.1' already exists. Skipping...
Folder 'GCA_004812095.1_PDT000388089.1' already exists. Skipping...
Folder 'GCA_004812175.1_PDT000387129.1' already exists. Skipping...
Folder 'GCA_004812215.1_PDT000387145.1' already exists. Skipping...
Folder 'GCA_004812315.1_PDT000387142.1' already exists. Skipping...
Folder 'GCA_004812355.1_PDT000387146.1' already exists. Skipping...
Folder 'GCA_004812435.1_PDT000387150.1' already exists. Skipping...
Folder 'GCA_004812475.1_PDT000387151.1' already exists. Skipping...
Folder 'GCA_004812515.1_PDT000387148.1' already exists. Skipping...
Folder 'GCA_004812525.1_PDT000387152.1' already exists. Skipping...
Folder 'GCA_004812555.1_PDT000387164.1' already exists. Skipping...
Folder 'GCA_004812575.1_PDT000387169.1' already exists. Skipping...
Folder 'GCA_004812595.1_PDT000387412.1' already exists. Skipping...
Folder 'GCA_004812875.1_PDT000387428.1' already exists. Skipping...
Folder 'GCA_004812955.1_PDT000387436.1' already exists. Skipping...
Folder 'GCA_004813055.1_PDT000388094.1' already exists. Skipping...
Folder 'GCA_004813135.1_PDT000388098.1' already exists. Skipping...
Folder 'GCA_004813215.1_PDT000388085.1' already exists. Skipping...
Folder 'GCA_004813235.1_PDT000388795.1' already exists. Skipping...
Folder 'GCA_004813535.1_PDT000387742.1' already exists. Skipping...
Folder 'GCA_004813595.1_PDT000387745.1' already exists. Skipping...
Folder 'GCA_004813615.1_PDT000387654.2' already exists. Skipping...
Folder 'GCA_004813635.1_PDT000388057.1' already exists. Skipping...
Folder 'GCA_004813655.1_PDT000388067.1' already exists. Skipping...
Folder 'GCA_004813675.1_PDT000388051.1' already exists. Skipping...
Folder 'GCA_004813695.1_PDT000388069.1' already exists. Skipping...
Folder 'GCA_004813715.1_PDT000388081.1' already exists. Skipping...
Folder 'GCA_004813735.1_PDT000388073.1' already exists. Skipping...
Folder 'GCA_004813755.1_PDT000388083.1' already exists. Skipping...
Folder 'GCA_004813775.1_PDT000388102.1' already exists. Skipping...
Folder 'GCA_004813795.1_PDT000388784.1' already exists. Skipping...
Folder 'GCA_004813815.1_PDT000388100.1' already exists. Skipping...
Folder 'GCA_004813855.1_PDT000388788.1' already exists. Skipping...
Folder 'GCA_004813895.1_PDT000388791.1' already exists. Skipping...
Folder 'GCA_004813935.1_PDT000388789.1' already exists. Skipping...
Folder 'GCA_004813995.1_PDT000388801.1' already exists. Skipping...
Folder 'GCA_004814035.1_PDT000388798.1' already exists. Skipping...
Folder 'GCA_004814135.1_PDT000388842.1' already exists. Skipping...
Folder 'GCA_004814455.1_PDT000389823.1' already exists. Skipping...
Folder 'GCA_004814475.1_PDT000389456.1' already exists. Skipping...
Folder 'GCA_004814655.1_PDT000390727.1' already exists. Skipping...
Folder 'GCA_004814835.1_PDT000388806.1' already exists. Skipping...
Folder 'GCA_004815495.1_PDT000389449.1' already exists. Skipping...
Folder 'GCA_004815655.1_PDT000389486.1' already exists. Skipping...
Folder 'GCA_004815675.1_PDT000389484.1' already exists. Skipping...
Folder 'GCA_004815695.1_PDT000389614.1' already exists. Skipping...
Folder 'GCA_004815715.1_PDT000389482.1' already exists. Skipping...
Folder 'GCA_004815765.1_PDT000389608.1' already exists. Skipping...
Folder 'GCA_004816215.1_PDT000390733.1' already exists. Skipping...
Folder 'GCA_004816235.1_PDT000390732.1' already exists. Skipping...
Folder 'GCA_004816255.1_PDT000390734.1' already exists. Skipping...
Folder 'GCA_004816295.1_PDT000390736.1' already exists. Skipping...
Folder 'GCA_004816315.1_PDT000390739.1' already exists. Skipping...
Folder 'GCA_004816375.1_PDT000390741.1' already exists. Skipping...
Folder 'GCA_004816435.1_PDT000390752.1' already exists. Skipping...
Folder 'GCA_004816515.1_PDT000391437.1' already exists. Skipping...
Folder 'GCA_004816695.1_PDT000391781.1' already exists. Skipping...
Folder 'GCA_004816735.1_PDT000390759.1' already exists. Skipping...
Folder 'GCA_004816775.1_PDT000390751.1' already exists. Skipping...
Folder 'GCA_004816855.1_PDT000390748.1' already exists. Skipping...
Folder 'GCA_004816895.1_PDT000391438.1' already exists. Skipping...
Folder 'GCA_004817135.1_PDT000390769.1' already exists. Skipping...
Folder 'GCA_004817175.1_PDT000391604.1' already exists. Skipping...
Folder 'GCA_004817395.1_PDT000391465.1' already exists. Skipping...
Folder 'GCA_004817415.1_PDT000391478.1' already exists. Skipping...
Folder 'GCA_004817455.1_PDT000390747.1' already exists. Skipping...
Folder 'GCA_004817495.1_PDT000390746.1' already exists. Skipping...
Folder 'GCA_004817515.1_PDT000390762.1' already exists. Skipping...
Folder 'GCA_004817675.1_PDT000391779.1' already exists. Skipping...
Folder 'GCA_004817695.1_PDT000391737.1' already exists. Skipping...
Folder 'GCA_004817815.1_PDT000391760.1' already exists. Skipping...
Folder 'GCA_004817835.1_PDT000391768.1' already exists. Skipping...
Folder 'GCA_004817915.1_PDT000391769.1' already exists. Skipping...
Folder 'GCA_004817935.1_PDT000391771.1' already exists. Skipping...
Folder 'GCA_004817975.1_PDT000391773.1' already exists. Skipping...
Folder 'GCA_004818035.1_PDT000391784.1' already exists. Skipping...
Folder 'GCA_004818095.1_PDT000391776.1' already exists. Skipping...
Folder 'GCA_004818155.1_PDT000391786.1' already exists. Skipping...
Folder 'GCA_004818175.1_PDT000391789.1' already exists. Skipping...
Folder 'GCA_004818195.1_PDT000391847.1' already exists. Skipping...
Folder 'GCA_004818215.1_PDT000391803.1' already exists. Skipping...
Folder 'GCA_004818235.1_PDT000391791.1' already exists. Skipping...
Folder 'GCA_004818255.1_PDT000391808.1' already exists. Skipping...
Folder 'GCA_004818295.1_PDT000391807.1' already exists. Skipping...
Folder 'GCA_004818495.1_PDT000392116.1' already exists. Skipping...
Folder 'GCA_004818535.1_PDT000393248.1' already exists. Skipping...
Folder 'GCA_004818595.1_PDT000392565.1' already exists. Skipping...
Folder 'GCA_004818635.1_PDT000392548.1' already exists. Skipping...
Folder 'GCA_004818655.1_PDT000392576.1' already exists. Skipping...
Folder 'GCA_004818755.1_PDT000393247.1' already exists. Skipping...
Folder 'GCA_004818795.1_PDT000403429.1' already exists. Skipping...
Folder 'GCA_004818875.1_PDT000392547.1' already exists. Skipping...
Folder 'GCA_004818915.1_PDT000392551.1' already exists. Skipping...
Folder 'GCA_004818955.1_PDT000393253.1' already exists. Skipping...
Folder 'GCA_004818975.1_PDT000392549.1' already exists. Skipping...
Folder 'GCA_004819015.1_PDT000392566.1' already exists. Skipping...
Folder 'GCA_004819035.1_PDT000392579.1' already exists. Skipping...
Folder 'GCA_004819165.1_PDT000392578.1' already exists. Skipping...
Folder 'GCA_004819205.1_PDT000404717.1' already exists. Skipping...
Folder 'GCA_004819245.1_PDT000392539.1' already exists. Skipping...
Folder 'GCA_004819305.1_PDT000393025.1' already exists. Skipping...
Folder 'GCA_004819325.1_PDT000392541.1' already exists. Skipping...
Folder 'GCA_004819405.1_PDT000392538.1' already exists. Skipping...
Folder 'GCA_004819425.1_PDT000392544.1' already exists. Skipping...
Folder 'GCA_004819465.1_PDT000393806.1' already exists. Skipping...
Folder 'GCA_004819475.1_PDT000392553.1' already exists. Skipping...
Folder 'GCA_004819505.1_PDT000393254.1' already exists. Skipping...
Folder 'GCA_004819525.1_PDT000393256.1' already exists. Skipping...
Folder 'GCA_004819565.1_PDT000392559.1' already exists. Skipping...
Folder 'GCA_004819625.1_PDT000392561.1' already exists. Skipping...
Folder 'GCA_004819645.1_PDT000392568.1' already exists. Skipping...
Folder 'GCA_004819665.1_PDT000392560.1' already exists. Skipping...
Folder 'GCA_004819745.1_PDT000392569.1' already exists. Skipping...
Folder 'GCA_004819925.1_PDT000392575.1' already exists. Skipping...
Folder 'GCA_004819945.1_PDT000392573.1' already exists. Skipping...
Folder 'GCA_004819985.1_PDT000392591.1' already exists. Skipping...
Folder 'GCA_004820005.1_PDT000392588.1' already exists. Skipping...
Folder 'GCA_004820025.1_PDT000392587.1' already exists. Skipping...
Folder 'GCA_004820045.1_PDT000403416.1' already exists. Skipping...
Folder 'GCA_004820105.1_PDT000382587.2' already exists. Skipping...
Folder 'GCA_004820145.1_PDT000392592.1' already exists. Skipping...
Folder 'GCA_004820165.1_PDT000391699.2' already exists. Skipping...
Folder 'GCA_004820185.1_PDT000393243.1' already exists. Skipping...
Folder 'GCA_004820225.1_PDT000391707.2' already exists. Skipping...
Folder 'GCA_004820245.1_PDT000393242.1' already exists. Skipping...
Folder 'GCA_004820365.1_PDT000403434.1' already exists. Skipping...
Folder 'GCA_004820505.1_PDT000394778.1' already exists. Skipping...
Folder 'GCA_004820885.1_PDT000403205.1' already exists. Skipping...
Folder 'GCA_004821005.1_PDT000403425.1' already exists. Skipping...
Folder 'GCA_004821105.1_PDT000403427.1' already exists. Skipping...
Folder 'GCA_004821125.1_PDT000403437.1' already exists. Skipping...
Folder 'GCA_004821145.1_PDT000403687.1' already exists. Skipping...
Folder 'GCA_004821185.1_PDT000404340.1' already exists. Skipping...
Folder 'GCA_004821245.1_PDT000404770.1' already exists. Skipping...
Folder 'GCA_004821285.1_PDT000404731.1' already exists. Skipping...
Folder 'GCA_004821365.1_PDT000404791.1' already exists. Skipping...
Folder 'GCA_004821385.1_PDT000404795.1' already exists. Skipping...
Folder 'GCA_004821405.1_PDT000404720.1' already exists. Skipping...
Folder 'GCA_004821425.1_PDT000404732.1' already exists. Skipping...
Folder 'GCA_004821445.1_PDT000404741.1' already exists. Skipping...
Folder 'GCA_004821625.1_PDT000404774.1' already exists. Skipping...
Folder 'GCA_004821645.1_PDT000404778.1' already exists. Skipping...
Folder 'GCA_004821665.1_PDT000404785.1' already exists. Skipping...
Folder 'GCA_004821705.1_PDT000404783.1' already exists. Skipping...
Folder 'GCA_004821745.1_PDT000404799.1' already exists. Skipping...
Folder 'GCA_004821775.1_PDT000407283.1' already exists. Skipping...
Folder 'GCA_004821805.1_PDT000404804.1' already exists. Skipping...
Folder 'GCA_004821905.1_PDT000404803.1' already exists. Skipping...
Folder 'GCA_004821985.1_PDT000406604.1' already exists. Skipping...
Folder 'GCA_004822045.1_PDT000406683.1' already exists. Skipping...
Folder 'GCA_004822205.1_PDT000405520.1' already exists. Skipping...
Folder 'GCA_004822225.1_PDT000406591.1' already exists. Skipping...
Folder 'GCA_004822265.1_PDT000406596.1' already exists. Skipping...
Folder 'GCA_004822275.1_PDT000406598.1' already exists. Skipping...
Folder 'GCA_004822325.1_PDT000406592.1' already exists. Skipping...
Folder 'GCA_004822345.1_PDT000406608.1' already exists. Skipping...
Folder 'GCA_004822425.1_PDT000406755.1' already exists. Skipping...
Folder 'GCA_004822465.1_PDT000406606.1' already exists. Skipping...
Folder 'GCA_004822485.1_PDT000406595.1' already exists. Skipping...
Folder 'GCA_004822545.1_PDT000406611.1' already exists. Skipping...
Folder 'GCA_004822565.1_PDT000406609.1' already exists. Skipping...
Folder 'GCA_004822625.1_PDT000406698.1' already exists. Skipping...
Folder 'GCA_004823225.1_PDT000407290.1' already exists. Skipping...
Folder 'GCA_004823265.1_PDT000406610.1' already exists. Skipping...
Folder 'GCA_004823305.1_PDT000404812.1' already exists. Skipping...
Folder 'GCA_004823325.1_PDT000392595.1' already exists. Skipping...
Folder 'GCA_004823445.1_PDT000407305.1' already exists. Skipping...
Folder 'GCA_004823725.1_PDT000407296.1' already exists. Skipping...
Folder 'GCA_004823825.1_PDT000409500.1' already exists. Skipping...
Folder 'GCA_004823845.1_PDT000409495.1' already exists. Skipping...
Folder 'GCA_004824085.1_PDT000409514.1' already exists. Skipping...
Folder 'GCA_004824185.1_PDT000409520.1' already exists. Skipping...
Folder 'GCA_004824505.1_PDT000409161.1' already exists. Skipping...
Folder 'GCA_004824605.1_PDT000409483.1' already exists. Skipping...
Folder 'GCA_004824625.1_PDT000409490.1' already exists. Skipping...
Folder 'GCA_004824635.1_PDT000409488.1' already exists. Skipping...
Folder 'GCA_004824665.1_PDT000409484.1' already exists. Skipping...
Folder 'GCA_004824695.1_PDT000409487.1' already exists. Skipping...
Folder 'GCA_004824805.1_PDT000409493.1' already exists. Skipping...
Folder 'GCA_004824885.1_PDT000409523.1' already exists. Skipping...
Folder 'GCA_004824905.1_PDT000409529.1' already exists. Skipping...
Folder 'GCA_004825185.1_PDT000411122.1' already exists. Skipping...
Folder 'GCA_004825225.1_PDT000411054.1' already exists. Skipping...
Folder 'GCA_004825245.1_PDT000411132.1' already exists. Skipping...
Folder 'GCA_004825305.1_PDT000411135.1' already exists. Skipping...
Folder 'GCA_004825325.1_PDT000411162.1' already exists. Skipping...
Folder 'GCA_004825405.1_PDT000411121.1' already exists. Skipping...
Folder 'GCA_004825425.1_PDT000411163.1' already exists. Skipping...
Folder 'GCA_004825445.1_PDT000411136.1' already exists. Skipping...
Folder 'GCA_004825455.1_PDT000411139.1' already exists. Skipping...
Folder 'GCA_004825525.1_PDT000411140.1' already exists. Skipping...
Folder 'GCA_004825545.1_PDT000411158.1' already exists. Skipping...
Folder 'GCA_004825625.1_PDT000411124.1' already exists. Skipping...
Folder 'GCA_004825725.1_PDT000411936.1' already exists. Skipping...
Folder 'GCA_004825845.1_PDT000411920.1' already exists. Skipping...
Folder 'GCA_004825925.1_PDT000411967.1' already exists. Skipping...
Folder 'GCA_004825965.1_PDT000412079.1' already exists. Skipping...
Folder 'GCA_004826045.1_PDT000411969.1' already exists. Skipping...
Folder 'GCA_004826125.1_PDT000411940.1' already exists. Skipping...
Folder 'GCA_004826165.1_PDT000412273.1' already exists. Skipping...
Folder 'GCA_004826225.1_PDT000411948.1' already exists. Skipping...

Retreiveing data: 4070it [00:02, 4265.41it/s]

Folder 'GCA_004900175.1_PDT000477201.1' already exists. Skipping...
Folder 'GCA_004900455.1_PDT000477183.1' already exists. Skipping...
Folder 'GCA_004900475.1_PDT000477182.1' already exists. Skipping...
Folder 'GCA_004900495.1_PDT000477181.1' already exists. Skipping...
Folder 'GCA_004900535.1_PDT000477186.1' already exists. Skipping...
Folder 'GCA_004900575.1_PDT000477189.1' already exists. Skipping...
Folder 'GCA_004900595.1_PDT000477187.1' already exists. Skipping...
Folder 'GCA_004900615.1_PDT000477190.1' already exists. Skipping...
Folder 'GCA_004900655.1_PDT000477192.1' already exists. Skipping...
Folder 'GCA_004900755.1_PDT000477209.1' already exists. Skipping...
Folder 'GCA_004900835.1_PDT000477204.1' already exists. Skipping...
Folder 'GCA_004900915.1_PDT000477212.1' already exists. Skipping...
Folder 'GCA_004900995.1_PDT000477220.1' already exists. Skipping...
Folder 'GCA_004901075.1_PDT000477222.1' already exists. Skipping...
Folder 'GCA_004901115.1_PDT000477225.1' already exists. Skipping...
Folder 'GCA_004901195.1_PDT000477237.1' already exists. Skipping...
Folder 'GCA_004901215.1_PDT000477245.1' already exists. Skipping...
Folder 'GCA_004901315.1_PDT000477258.1' already exists. Skipping...
Folder 'GCA_004901375.1_PDT000477250.1' already exists. Skipping...
Folder 'GCA_004901435.1_PDT000477251.1' already exists. Skipping...
Folder 'GCA_004901475.1_PDT000477253.1' already exists. Skipping...
Folder 'GCA_004901485.1_PDT000477257.1' already exists. Skipping...
Folder 'GCA_004901555.1_PDT000477278.1' already exists. Skipping...
Folder 'GCA_004901575.1_PDT000477277.1' already exists. Skipping...
Folder 'GCA_004901655.1_PDT000478359.1' already exists. Skipping...
Folder 'GCA_004901755.1_PDT000478360.1' already exists. Skipping...
Folder 'GCA_004901795.1_PDT000478362.1' already exists. Skipping...
Folder 'GCA_004901995.1_PDT000478382.1' already exists. Skipping...
Folder 'GCA_004902255.1_PDT000477198.1' already exists. Skipping...
Folder 'GCA_004902435.1_PDT000428457.1' already exists. Skipping...
Folder 'GCA_004902475.1_PDT000422210.1' already exists. Skipping...
Folder 'GCA_004902495.1_PDT000428404.1' already exists. Skipping...
Folder 'GCA_004902575.1_PDT000423069.1' already exists. Skipping...
Folder 'GCA_004902615.1_PDT000428385.1' already exists. Skipping...
Folder 'GCA_004902665.1_PDT000422106.1' already exists. Skipping...
Folder 'GCA_004902775.1_PDT000428931.1' already exists. Skipping...
Folder 'GCA_004902785.1_PDT000428409.1' already exists. Skipping...
Folder 'GCA_004902815.1_PDT000422194.1' already exists. Skipping...
Folder 'GCA_004902855.1_PDT000424660.1' already exists. Skipping...
Folder 'GCA_004902875.1_PDT000423072.1' already exists. Skipping...
Folder 'GCA_004902895.1_PDT000424659.1' already exists. Skipping...
Folder 'GCA_004902915.1_PDT000422197.1' already exists. Skipping...
Folder 'GCA_004902975.1_PDT000428933.1' already exists. Skipping...
Folder 'GCA_004902995.1_PDT000424672.1' already exists. Skipping...
Folder 'GCA_004903015.1_PDT000424674.1' already exists. Skipping...
Folder 'GCA_004903035.1_PDT000428370.1' already exists. Skipping...
Folder 'GCA_004903055.1_PDT000428346.1' already exists. Skipping...
Folder 'GCA_004903075.1_PDT000428474.1' already exists. Skipping...
Folder 'GCA_004903095.1_PDT000428454.1' already exists. Skipping...
Folder 'GCA_004903155.1_PDT000428396.1' already exists. Skipping...
Folder 'GCA_004903175.1_PDT000428492.1' already exists. Skipping...
Folder 'GCA_004903295.1_PDT000428930.1' already exists. Skipping...
Folder 'GCA_004904475.1_PDT000422080.1' already exists. Skipping...
Folder 'GCA_004904995.1_PDT000430088.1' already exists. Skipping...
Folder 'GCA_004905315.1_PDT000430082.1' already exists. Skipping...
Folder 'GCA_004905595.1_PDT000430276.1' already exists. Skipping...
Folder 'GCA_004905695.1_PDT000430288.1' already exists. Skipping...
Folder 'GCA_004905795.1_PDT000430708.1' already exists. Skipping...
Folder 'GCA_004905835.1_PDT000432250.1' already exists. Skipping...
Folder 'GCA_004905915.1_PDT000432244.1' already exists. Skipping...
Folder 'GCA_004906155.1_PDT000434011.1' already exists. Skipping...
Folder 'GCA_004906455.1_PDT000479769.1' already exists. Skipping...
Folder 'GCA_004906555.1_PDT000479712.1' already exists. Skipping...
Folder 'GCA_004906675.1_PDT000479472.1' already exists. Skipping...
Folder 'GCA_004906715.1_PDT000479449.1' already exists. Skipping...
Folder 'GCA_004906775.1_PDT000479667.1' already exists. Skipping...
Folder 'GCA_004906795.1_PDT000479474.1' already exists. Skipping...
Folder 'GCA_004906815.1_PDT000479782.1' already exists. Skipping...
Folder 'GCA_004906835.1_PDT000479714.1' already exists. Skipping...
Folder 'GCA_004906875.1_PDT000479785.1' already exists. Skipping...
Folder 'GCA_004906895.1_PDT000479773.1' already exists. Skipping...
Folder 'GCA_004907115.1_PDT000479444.1' already exists. Skipping...
Folder 'GCA_004907195.1_PDT000479632.1' already exists. Skipping...
Folder 'GCA_004907335.1_PDT000479665.1' already exists. Skipping...
Folder 'GCA_004907355.1_PDT000479719.1' already exists. Skipping...
Folder 'GCA_004907435.1_PDT000479781.1' already exists. Skipping...
Folder 'GCA_004907455.1_PDT000479498.1' already exists. Skipping...
Folder 'GCA_004907575.1_PDT000479492.1' already exists. Skipping...
Folder 'GCA_004907705.1_PDT000479720.1' already exists. Skipping...
Folder 'GCA_004907735.1_PDT000479656.1' already exists. Skipping...
Folder 'GCA_004907795.1_PDT000479774.1' already exists. Skipping...
Folder 'GCA_004907815.1_PDT000479748.1' already exists. Skipping...
Folder 'GCA_004907855.1_PDT000479745.1' already exists. Skipping...
Folder 'GCA_004907895.1_PDT000479744.1' already exists. Skipping...
Folder 'GCA_004907915.1_PDT000479775.1' already exists. Skipping...
Folder 'GCA_004907935.1_PDT000479790.1' already exists. Skipping...
Folder 'GCA_004907955.1_PDT000479771.1' already exists. Skipping...
Folder 'GCA_004907975.1_PDT000479788.1' already exists. Skipping...
Folder 'GCA_004908015.1_PDT000479787.1' already exists. Skipping...
Folder 'GCA_004908455.1_PDT000479454.1' already exists. Skipping...
Folder 'GCA_004908475.1_PDT000479458.1' already exists. Skipping...
Folder 'GCA_004908495.1_PDT000479457.1' already exists. Skipping...
Folder 'GCA_004908555.1_PDT000479455.1' already exists. Skipping...
Folder 'GCA_004908695.1_PDT000479463.1' already exists. Skipping...
Folder 'GCA_004908815.1_PDT000479649.1' already exists. Skipping...
Folder 'GCA_004908895.1_PDT000479648.1' already exists. Skipping...
Folder 'GCA_004908935.1_PDT000479650.1' already exists. Skipping...
Folder 'GCA_004908975.1_PDT000479658.1' already exists. Skipping...
Folder 'GCA_004908995.1_PDT000479659.1' already exists. Skipping...
Folder 'GCA_004909135.1_PDT000479686.1' already exists. Skipping...
Folder 'GCA_004909195.1_PDT000479697.1' already exists. Skipping...
Folder 'GCA_004909215.1_PDT000479723.1' already exists. Skipping...
Folder 'GCA_004909235.1_PDT000479726.1' already exists. Skipping...
Folder 'GCA_004909275.1_PDT000479705.1' already exists. Skipping...
Folder 'GCA_004909355.1_PDT000479738.1' already exists. Skipping...
Folder 'GCA_004909385.1_PDT000479706.1' already exists. Skipping...
Folder 'GCA_004909415.1_PDT000479751.1' already exists. Skipping...
Folder 'GCA_004909435.1_PDT000479755.1' already exists. Skipping...
Folder 'GCA_004909515.1_PDT000479760.1' already exists. Skipping...
Folder 'GCA_004909535.1_PDT000479778.1' already exists. Skipping...
Folder 'GCA_004909555.1_PDT000479763.1' already exists. Skipping...
Folder 'GCA_004909585.1_PDT000479767.1' already exists. Skipping...
Folder 'GCA_004909635.1_PDT000479895.1' already exists. Skipping...
Folder 'GCA_004909655.1_PDT000479893.1' already exists. Skipping...
Folder 'GCA_004909715.1_PDT000479896.1' already exists. Skipping...
Folder 'GCA_004909895.1_PDT000479768.1' already exists. Skipping...
Folder 'GCA_004910015.1_PDT000480661.1' already exists. Skipping...
Folder 'GCA_004910205.1_PDT000479970.1' already exists. Skipping...
Folder 'GCA_004910255.1_PDT000479971.1' already exists. Skipping...
Folder 'GCA_004910375.1_PDT000482413.1' already exists. Skipping...
Folder 'GCA_004911595.1_PDT000479978.1' already exists. Skipping...
Folder 'GCA_004912295.1_PDT000482470.1' already exists. Skipping...
Folder 'GCA_004912335.1_PDT000482424.1' already exists. Skipping...
Folder 'GCA_004912355.1_PDT000482465.1' already exists. Skipping...
Folder 'GCA_004912635.1_PDT000482475.1' already exists. Skipping...
Folder 'GCA_004912715.1_PDT000482744.1' already exists. Skipping...
Folder 'GCA_004912855.1_PDT000482468.1' already exists. Skipping...
Folder 'GCA_004912895.1_PDT000482771.1' already exists. Skipping...
Folder 'GCA_004912995.1_PDT000482464.1' already exists. Skipping...
Folder 'GCA_004913015.1_PDT000482463.1' already exists. Skipping...
Folder 'GCA_004913075.1_PDT000482478.1' already exists. Skipping...
Folder 'GCA_004913095.1_PDT000482760.1' already exists. Skipping...
Folder 'GCA_004913115.1_PDT000482485.1' already exists. Skipping...
Folder 'GCA_004913135.1_PDT000482490.1' already exists. Skipping...
Folder 'GCA_004913175.1_PDT000482489.1' already exists. Skipping...
Folder 'GCA_004913195.1_PDT000482761.1' already exists. Skipping...
Folder 'GCA_004913235.1_PDT000482757.1' already exists. Skipping...
Folder 'GCA_004913335.1_PDT000482772.1' already exists. Skipping...
Folder 'GCA_004913375.1_PDT000482742.1' already exists. Skipping...
Folder 'GCA_004913475.1_PDT000482748.1' already exists. Skipping...
Folder 'GCA_004913515.1_PDT000483163.1' already exists. Skipping...
Folder 'GCA_004913525.1_PDT000482773.1' already exists. Skipping...
Folder 'GCA_004913555.1_PDT000482753.1' already exists. Skipping...
Folder 'GCA_004913595.1_PDT000482752.1' already exists. Skipping...
Folder 'GCA_004913655.1_PDT000483164.1' already exists. Skipping...
Folder 'GCA_004913735.1_PDT000482765.1' already exists. Skipping...
Folder 'GCA_004913875.1_PDT000482766.1' already exists. Skipping...
Folder 'GCA_004913895.1_PDT000482770.1' already exists. Skipping...
Folder 'GCA_004914015.1_PDT000483162.1' already exists. Skipping...
Folder 'GCA_004914035.1_PDT000483159.1' already exists. Skipping...
Folder 'GCA_004914055.1_PDT000483160.1' already exists. Skipping...
Folder 'GCA_004914115.1_PDT000482422.1' already exists. Skipping...
Folder 'GCA_004914135.1_PDT000482420.1' already exists. Skipping...
Folder 'GCA_004914415.1_PDT000483391.1' already exists. Skipping...
Folder 'GCA_004914475.1_PDT000483461.1' already exists. Skipping...
Folder 'GCA_004914655.1_PDT000483393.1' already exists. Skipping...
Folder 'GCA_004914675.1_PDT000483483.1' already exists. Skipping...
Folder 'GCA_004914695.1_PDT000483479.1' already exists. Skipping...
Folder 'GCA_004914775.1_PDT000484155.1' already exists. Skipping...
Folder 'GCA_004915015.1_PDT000483950.1' already exists. Skipping...
Folder 'GCA_004915215.1_PDT000483467.1' already exists. Skipping...
Folder 'GCA_004915255.1_PDT000483468.1' already exists. Skipping...
Folder 'GCA_004915415.1_PDT000484070.1' already exists. Skipping...
Folder 'GCA_004915455.1_PDT000483490.1' already exists. Skipping...
Folder 'GCA_004915515.1_PDT000483491.1' already exists. Skipping...
Folder 'GCA_004915535.1_PDT000483492.1' already exists. Skipping...
Folder 'GCA_004915615.1_PDT000484169.1' already exists. Skipping...
Folder 'GCA_004915815.1_PDT000483476.1' already exists. Skipping...
Folder 'GCA_004916155.1_PDT000484147.1' already exists. Skipping...
Folder 'GCA_004916235.1_PDT000484159.1' already exists. Skipping...
Folder 'GCA_004916255.1_PDT000484151.1' already exists. Skipping...
Folder 'GCA_004916315.1_PDT000484162.1' already exists. Skipping...
Folder 'GCA_004916355.1_PDT000484167.1' already exists. Skipping...
Folder 'GCA_004916365.1_PDT000484166.1' already exists. Skipping...
Folder 'GCA_004916395.1_PDT000483486.1' already exists. Skipping...
Folder 'GCA_004916455.1_PDT000483477.1' already exists. Skipping...
Folder 'GCA_004916615.1_PDT000459811.1' already exists. Skipping...
Folder 'GCA_004916675.1_PDT000479626.1' already exists. Skipping...
Folder 'GCA_004916695.1_PDT000483489.1' already exists. Skipping...
Folder 'GCA_004916795.1_PDT000457450.1' already exists. Skipping...
Folder 'GCA_004923655.1_PDT000048243.2' already exists. Skipping...
Folder 'GCA_004923675.1_PDT000048224.2' already exists. Skipping...
Folder 'GCA_004923835.1_PDT000051325.2' already exists. Skipping...
Folder 'GCA_004923855.1_PDT000051328.2' already exists. Skipping...
Folder 'GCA_004923875.1_PDT000051333.2' already exists. Skipping...
Folder 'GCA_004923915.1_PDT000051335.2' already exists. Skipping...
Folder 'GCA_004923955.1_PDT000060317.2' already exists. Skipping...
Folder 'GCA_004923975.1_PDT000061232.2' already exists. Skipping...
Folder 'GCA_004923995.1_PDT000061235.2' already exists. Skipping...
Folder 'GCA_004924115.1_PDT000061243.2' already exists. Skipping...
Folder 'GCA_004924455.1_PDT000086104.2' already exists. Skipping...
Folder 'GCA_004924495.1_PDT000062727.2' already exists. Skipping...
Folder 'GCA_004924515.1_PDT000051332.2' already exists. Skipping...
Folder 'GCA_004924575.1_PDT000062732.2' already exists. Skipping...
Folder 'GCA_004924655.1_PDT000060320.2' already exists. Skipping...
Folder 'GCA_004924695.1_PDT000061214.2' already exists. Skipping...
Folder 'GCA_004924835.1_PDT000061222.2' already exists. Skipping...
Folder 'GCA_004924895.1_PDT000086115.2' already exists. Skipping...
Folder 'GCA_004924955.1_PDT000061223.2' already exists. Skipping...
Folder 'GCA_004925055.1_PDT000061249.2' already exists. Skipping...
Folder 'GCA_004925135.1_PDT000062711.2' already exists. Skipping...
Folder 'GCA_004925155.1_PDT000062721.2' already exists. Skipping...
Folder 'GCA_004925235.1_PDT000062724.2' already exists. Skipping...
Folder 'GCA_004925255.1_PDT000062725.2' already exists. Skipping...
Folder 'GCA_004925275.1_PDT000062734.2' already exists. Skipping...
Folder 'GCA_004925355.1_PDT000062726.2' already exists. Skipping...
Folder 'GCA_004925795.1_PDT000101458.2' already exists. Skipping...
Folder 'GCA_004926155.1_PDT000101453.2' already exists. Skipping...
Folder 'GCA_004926555.2_PDT000045903.6' already exists. Skipping...
Folder 'GCA_004926575.1_PDT000081835.2' already exists. Skipping...
Folder 'GCA_004926655.1_PDT000045906.3' already exists. Skipping...
Folder 'GCA_004926815.1_PDT000085746.2' already exists. Skipping...
Folder 'GCA_004926825.1_PDT000085748.2' already exists. Skipping...
Folder 'GCA_004926855.1_PDT000085758.2' already exists. Skipping...
Folder 'GCA_004926875.1_PDT000085755.2' already exists. Skipping...
Folder 'GCA_004926895.1_PDT000085759.2' already exists. Skipping...
Folder 'GCA_004927115.1_PDT000087498.2' already exists. Skipping...
Folder 'GCA_004927175.1_PDT000087459.2' already exists. Skipping...
Folder 'GCA_004927195.1_PDT000087483.2' already exists. Skipping...
Folder 'GCA_004927215.1_PDT000092885.2' already exists. Skipping...
Folder 'GCA_004927235.1_PDT000087479.2' already exists. Skipping...
Folder 'GCA_004927295.1_PDT000092883.2' already exists. Skipping...
Folder 'GCA_004927875.1_PDT000095661.2' already exists. Skipping...
Folder 'GCA_004927935.1_PDT000088581.3' already exists. Skipping...
Folder 'GCA_004927955.1_PDT000088582.3' already exists. Skipping...
Folder 'GCA_004927995.1_PDT000095392.2' already exists. Skipping...
Folder 'GCA_004928065.1_PDT000096687.2' already exists. Skipping...
Folder 'GCA_004928335.1_PDT000100761.2' already exists. Skipping...
Folder 'GCA_004928355.1_PDT000100762.2' already exists. Skipping...
Folder 'GCA_004928375.1_PDT000100760.2' already exists. Skipping...
Folder 'GCA_004928415.1_PDT000100961.2' already exists. Skipping...
Folder 'GCA_004928455.1_PDT000100951.2' already exists. Skipping...
Folder 'GCA_004928715.1_PDT000100967.2' already exists. Skipping...
Folder 'GCA_004928775.1_PDT000101469.2' already exists. Skipping...
Folder 'GCA_004928795.1_PDT000101467.2' already exists. Skipping...
Folder 'GCA_004928815.1_PDT000101459.2' already exists. Skipping...
Folder 'GCA_004928835.1_PDT000100973.2' already exists. Skipping...
Folder 'GCA_004928855.1_PDT000101481.2' already exists. Skipping...
Folder 'GCA_004928875.1_PDT000101472.2' already exists. Skipping...
Folder 'GCA_004928995.1_PDT000102868.2' already exists. Skipping...
Folder 'GCA_004929035.1_PDT000102854.2' already exists. Skipping...
Folder 'GCA_004929075.1_PDT000102836.2' already exists. Skipping...
Folder 'GCA_004929085.1_PDT000102860.2' already exists. Skipping...
Folder 'GCA_004929135.1_PDT000104882.2' already exists. Skipping...
Folder 'GCA_004929145.1_PDT000103510.2' already exists. Skipping...
Folder 'GCA_004929215.1_PDT000104891.2' already exists. Skipping...
Folder 'GCA_004929235.1_PDT000104897.2' already exists. Skipping...
Folder 'GCA_004929255.1_PDT000104893.2' already exists. Skipping...
Folder 'GCA_004929275.1_PDT000104888.2' already exists. Skipping...
Folder 'GCA_004929355.1_PDT000104949.2' already exists. Skipping...
Folder 'GCA_004929415.1_PDT000104956.2' already exists. Skipping...
Folder 'GCA_004929455.1_PDT000104964.2' already exists. Skipping...
Folder 'GCA_004929495.1_PDT000104963.2' already exists. Skipping...
Folder 'GCA_004929515.1_PDT000104961.2' already exists. Skipping...
Folder 'GCA_004929535.1_PDT000104965.2' already exists. Skipping...
Folder 'GCA_004929675.1_PDT000113250.2' already exists. Skipping...
Folder 'GCA_004929735.1_PDT000113252.2' already exists. Skipping...
Folder 'GCA_004929755.1_PDT000108172.2' already exists. Skipping...
Folder 'GCA_004929785.1_PDT000105850.2' already exists. Skipping...
Folder 'GCA_004929815.1_PDT000112895.2' already exists. Skipping...
Folder 'GCA_004929835.1_PDT000105047.2' already exists. Skipping...
Folder 'GCA_004929855.1_PDT000105048.2' already exists. Skipping...
Folder 'GCA_004929875.1_PDT000105840.2' already exists. Skipping...
Folder 'GCA_004929895.1_PDT000104984.2' already exists. Skipping...
Folder 'GCA_004929935.1_PDT000104983.2' already exists. Skipping...
Folder 'GCA_004929975.1_PDT000113256.2' already exists. Skipping...
Folder 'GCA_004929995.1_PDT000113263.2' already exists. Skipping...
Folder 'GCA_004930055.1_PDT000113242.2' already exists. Skipping...
Folder 'GCA_004930095.1_PDT000113257.2' already exists. Skipping...
Folder 'GCA_004930155.1_PDT000113265.2' already exists. Skipping...
Folder 'GCA_004930175.1_PDT000104970.2' already exists. Skipping...
Folder 'GCA_004930195.1_PDT000113246.2' already exists. Skipping...
Folder 'GCA_004930215.1_PDT000107196.2' already exists. Skipping...
Folder 'GCA_004930235.1_PDT000113259.2' already exists. Skipping...
Folder 'GCA_004930255.1_PDT000111399.2' already exists. Skipping...
Folder 'GCA_004930335.1_PDT000104975.2' already exists. Skipping...
Folder 'GCA_004930475.1_PDT000113267.2' already exists. Skipping...
Folder 'GCA_004930515.1_PDT000113271.2' already exists. Skipping...
Folder 'GCA_004930955.1_PDT000113254.2' already exists. Skipping...
Folder 'GCA_004930975.1_PDT000107178.2' already exists. Skipping...
Folder 'GCA_004931455.1_PDT000113551.2' already exists. Skipping...
Folder 'GCA_004931535.1_PDT000113579.2' already exists. Skipping...
Folder 'GCA_004931575.1_PDT000113580.2' already exists. Skipping...
Folder 'GCA_004931615.1_PDT000115056.2' already exists. Skipping...
Folder 'GCA_004931635.1_PDT000115061.2' already exists. Skipping...
Folder 'GCA_004931755.1_PDT000115065.2' already exists. Skipping...
Folder 'GCA_004931815.1_PDT000115093.2' already exists. Skipping...
Folder 'GCA_004931895.1_PDT000128701.2' already exists. Skipping...
Folder 'GCA_004932015.1_PDT000138028.2' already exists. Skipping...
Folder 'GCA_004932055.1_PDT000138026.2' already exists. Skipping...
Folder 'GCA_004932115.1_PDT000128691.2' already exists. Skipping...
Folder 'GCA_004932135.1_PDT000128686.2' already exists. Skipping...
Folder 'GCA_004932155.1_PDT000134770.2' already exists. Skipping...
Folder 'GCA_004932175.1_PDT000128712.2' already exists. Skipping...

Retreiveing data: 5416it [00:02, 5309.13it/s]

Folder 'GCA_005004335.1_PDT000218738.2' already exists. Skipping...
Folder 'GCA_005004355.1_PDT000188933.2' already exists. Skipping...
Folder 'GCA_005004415.1_PDT000199507.2' already exists. Skipping...
Folder 'GCA_005004435.1_PDT000219921.2' already exists. Skipping...
Folder 'GCA_005004515.1_PDT000226430.2' already exists. Skipping...
Folder 'GCA_005004555.1_PDT000219330.2' already exists. Skipping...
Folder 'GCA_005004615.1_PDT000200501.2' already exists. Skipping...
Folder 'GCA_005004735.1_PDT000226405.2' already exists. Skipping...
Folder 'GCA_005004775.1_PDT000199589.2' already exists. Skipping...
Folder 'GCA_005004935.1_PDT000175410.2' already exists. Skipping...
Folder 'GCA_005004955.1_PDT000204949.2' already exists. Skipping...
Folder 'GCA_005004985.1_PDT000200475.2' already exists. Skipping...
Folder 'GCA_005005015.1_PDT000200413.2' already exists. Skipping...
Folder 'GCA_005005035.1_PDT000205026.2' already exists. Skipping...
Folder 'GCA_005005055.1_PDT000237652.2' already exists. Skipping...
Folder 'GCA_005005075.1_PDT000238434.2' already exists. Skipping...
Folder 'GCA_005005095.1_PDT000239737.2' already exists. Skipping...
Folder 'GCA_005005115.1_PDT000206879.2' already exists. Skipping...
Folder 'GCA_005005145.1_PDT000174448.2' already exists. Skipping...
Folder 'GCA_005005615.1_PDT000203816.2' already exists. Skipping...
Folder 'GCA_005005655.1_PDT000201925.2' already exists. Skipping...
Folder 'GCA_005005675.1_PDT000205630.2' already exists. Skipping...
Folder 'GCA_005005695.1_PDT000205647.2' already exists. Skipping...
Folder 'GCA_005005715.1_PDT000206366.2' already exists. Skipping...
Folder 'GCA_005005735.1_PDT000206361.2' already exists. Skipping...
Folder 'GCA_005005755.1_PDT000206373.2' already exists. Skipping...
Folder 'GCA_005005775.1_PDT000233115.2' already exists. Skipping...
Folder 'GCA_005005795.1_PDT000187588.2' already exists. Skipping...
Folder 'GCA_005005835.1_PDT000238448.2' already exists. Skipping...
Folder 'GCA_005005855.1_PDT000188445.2' already exists. Skipping...
Folder 'GCA_005005905.1_PDT000187593.2' already exists. Skipping...
Folder 'GCA_005006095.1_PDT000206878.2' already exists. Skipping...
Folder 'GCA_005006135.1_PDT000199588.2' already exists. Skipping...
Folder 'GCA_005006195.1_PDT000199543.2' already exists. Skipping...
Folder 'GCA_005006215.1_PDT000199558.2' already exists. Skipping...
Folder 'GCA_005006235.1_PDT000215807.2' already exists. Skipping...
Folder 'GCA_005006255.1_PDT000205045.2' already exists. Skipping...
Folder 'GCA_005006315.1_PDT000215812.2' already exists. Skipping...
Folder 'GCA_005006375.1_PDT000210845.2' already exists. Skipping...
Folder 'GCA_005006395.1_PDT000215810.2' already exists. Skipping...
Folder 'GCA_005006415.1_PDT000215815.2' already exists. Skipping...
Folder 'GCA_005006435.1_PDT000224303.2' already exists. Skipping...
Folder 'GCA_005006455.1_PDT000218421.2' already exists. Skipping...
Folder 'GCA_005006475.1_PDT000224298.2' already exists. Skipping...
Folder 'GCA_005006535.1_PDT000219327.2' already exists. Skipping...
Folder 'GCA_005006575.1_PDT000219332.2' already exists. Skipping...
Folder 'GCA_005007075.1_PDT000227880.2' already exists. Skipping...
Folder 'GCA_005007215.1_PDT000218632.2' already exists. Skipping...
Folder 'GCA_005007275.1_PDT000227928.2' already exists. Skipping...
Folder 'GCA_005007315.1_PDT000245371.2' already exists. Skipping...
Folder 'GCA_005009535.1_PDT000220757.2' already exists. Skipping...
Folder 'GCA_005009575.1_PDT000224962.2' already exists. Skipping...
Folder 'GCA_005009635.1_PDT000215811.2' already exists. Skipping...
Folder 'GCA_005009675.1_PDT000215806.2' already exists. Skipping...
Folder 'GCA_005009695.1_PDT000220804.2' already exists. Skipping...
Folder 'GCA_005009735.1_PDT000215791.2' already exists. Skipping...
Folder 'GCA_005009755.1_PDT000224979.2' already exists. Skipping...
Folder 'GCA_005009775.1_PDT000237049.2' already exists. Skipping...
Folder 'GCA_005009795.1_PDT000219372.2' already exists. Skipping...
Folder 'GCA_005009835.1_PDT000224364.2' already exists. Skipping...
Folder 'GCA_005009875.1_PDT000227951.2' already exists. Skipping...
Folder 'GCA_005009935.1_PDT000236989.2' already exists. Skipping...
Folder 'GCA_005009955.1_PDT000227956.2' already exists. Skipping...
Folder 'GCA_005009975.1_PDT000237002.2' already exists. Skipping...
Folder 'GCA_005009995.1_PDT000199911.2' already exists. Skipping...
Folder 'GCA_005010015.1_PDT000181042.2' already exists. Skipping...
Folder 'GCA_005010035.1_PDT000199993.2' already exists. Skipping...
Folder 'GCA_005010055.1_PDT000199941.2' already exists. Skipping...
Folder 'GCA_005010075.1_PDT000200028.2' already exists. Skipping...
Folder 'GCA_005010095.1_PDT000201966.2' already exists. Skipping...
Folder 'GCA_005010105.1_PDT000206372.2' already exists. Skipping...
Folder 'GCA_005010135.1_PDT000218175.2' already exists. Skipping...
Folder 'GCA_005010155.1_PDT000201976.2' already exists. Skipping...
Folder 'GCA_005010175.1_PDT000203059.2' already exists. Skipping...
Folder 'GCA_005010195.1_PDT000244820.2' already exists. Skipping...
Folder 'GCA_005010215.1_PDT000226052.2' already exists. Skipping...
Folder 'GCA_005010235.1_PDT000226057.2' already exists. Skipping...
Folder 'GCA_005010245.1_PDT000244805.2' already exists. Skipping...
Folder 'GCA_005010275.1_PDT000226114.2' already exists. Skipping...
Folder 'GCA_005010335.1_PDT000206382.2' already exists. Skipping...
Folder 'GCA_005010395.1_PDT000220763.2' already exists. Skipping...
Folder 'GCA_005010415.1_PDT000219239.2' already exists. Skipping...
Folder 'GCA_005010435.1_PDT000220798.2' already exists. Skipping...
Folder 'GCA_005011355.1_PDT000244890.2' already exists. Skipping...
Folder 'GCA_005011375.1_PDT000244855.2' already exists. Skipping...
Folder 'GCA_005011395.1_PDT000244912.2' already exists. Skipping...
Folder 'GCA_005011415.1_PDT000250573.2' already exists. Skipping...
Folder 'GCA_005011435.1_PDT000244875.2' already exists. Skipping...
Folder 'GCA_005011455.1_PDT000250541.2' already exists. Skipping...
Folder 'GCA_005011475.1_PDT000258464.2' already exists. Skipping...
Folder 'GCA_005011495.1_PDT000250588.2' already exists. Skipping...
Folder 'GCA_005011515.1_PDT000199529.2' already exists. Skipping...
Folder 'GCA_005011535.1_PDT000199539.2' already exists. Skipping...
Folder 'GCA_005011555.1_PDT000250591.2' already exists. Skipping...
Folder 'GCA_005011575.1_PDT000199591.2' already exists. Skipping...
Folder 'GCA_005011595.1_PDT000200400.2' already exists. Skipping...
Folder 'GCA_005011615.1_PDT000200397.2' already exists. Skipping...
Folder 'GCA_005011635.1_PDT000200407.2' already exists. Skipping...
Folder 'GCA_005011655.1_PDT000200415.2' already exists. Skipping...
Folder 'GCA_005011675.1_PDT000245291.2' already exists. Skipping...
Folder 'GCA_005011695.1_PDT000200447.2' already exists. Skipping...
Folder 'GCA_005011735.1_PDT000237018.2' already exists. Skipping...
Folder 'GCA_005011755.1_PDT000199980.2' already exists. Skipping...
Folder 'GCA_005011775.1_PDT000237023.2' already exists. Skipping...
Folder 'GCA_005011785.1_PDT000237028.2' already exists. Skipping...
Folder 'GCA_005011835.1_PDT000199970.2' already exists. Skipping...
Folder 'GCA_005011875.1_PDT000200030.2' already exists. Skipping...
Folder 'GCA_005011935.1_PDT000200025.2' already exists. Skipping...
Folder 'GCA_005013635.1_PDT000181050.2' already exists. Skipping...
Folder 'GCA_005013655.1_PDT000199884.2' already exists. Skipping...
Folder 'GCA_005013675.1_PDT000175419.2' already exists. Skipping...
Folder 'GCA_005013735.1_PDT000249299.2' already exists. Skipping...
Folder 'GCA_005013775.1_PDT000249152.2' already exists. Skipping...
Folder 'GCA_005013835.1_PDT000249304.2' already exists. Skipping...
Folder 'GCA_005013855.1_PDT000200040.2' already exists. Skipping...
Folder 'GCA_005013875.1_PDT000245312.2' already exists. Skipping...
Folder 'GCA_005013895.1_PDT000245317.2' already exists. Skipping...
Folder 'GCA_005013935.1_PDT000187939.2' already exists. Skipping...
Folder 'GCA_005013955.1_PDT000257769.2' already exists. Skipping...
Folder 'GCA_005013995.1_PDT000181043.2' already exists. Skipping...
Folder 'GCA_005014035.1_PDT000181045.2' already exists. Skipping...
Folder 'GCA_005014095.1_PDT000231624.2' already exists. Skipping...
Folder 'GCA_005014155.1_PDT000224973.2' already exists. Skipping...
Folder 'GCA_005014175.1_PDT000222896.2' already exists. Skipping...
Folder 'GCA_005014215.1_PDT000199949.2' already exists. Skipping...
Folder 'GCA_005014235.1_PDT000226058.2' already exists. Skipping...
Folder 'GCA_005014355.1_PDT000244804.2' already exists. Skipping...
Folder 'GCA_005014435.1_PDT000237091.2' already exists. Skipping...
Folder 'GCA_005014595.1_PDT000199959.2' already exists. Skipping...
Folder 'GCA_005014655.1_PDT000199141.2' already exists. Skipping...
Folder 'GCA_005014735.1_PDT000220803.2' already exists. Skipping...
Folder 'GCA_005014775.1_PDT000244886.2' already exists. Skipping...
Folder 'GCA_005014795.1_PDT000199994.2' already exists. Skipping...
Folder 'GCA_005014815.1_PDT000226068.2' already exists. Skipping...
Folder 'GCA_005014895.1_PDT000220808.2' already exists. Skipping...
Folder 'GCA_005014995.1_PDT000222911.2' already exists. Skipping...
Folder 'GCA_005015135.1_PDT000226063.2' already exists. Skipping...
Folder 'GCA_005015175.1_PDT000215797.2' already exists. Skipping...
Folder 'GCA_005015255.1_PDT000219329.2' already exists. Skipping...
Folder 'GCA_005015355.1_PDT000226041.2' already exists. Skipping...
Folder 'GCA_005015395.1_PDT000250582.2' already exists. Skipping...
Folder 'GCA_005015425.1_PDT000208499.2' already exists. Skipping...
Folder 'GCA_005015475.1_PDT000224340.2' already exists. Skipping...
Folder 'GCA_005015495.1_PDT000250557.2' already exists. Skipping...
Folder 'GCA_005015535.1_PDT000259557.2' already exists. Skipping...
Folder 'GCA_005015595.1_PDT000259634.2' already exists. Skipping...
Folder 'GCA_005015615.1_PDT000273666.2' already exists. Skipping...
Folder 'GCA_005015655.1_PDT000273726.2' already exists. Skipping...
Folder 'GCA_005015675.1_PDT000244896.2' already exists. Skipping...
Folder 'GCA_005015695.1_PDT000273670.2' already exists. Skipping...
Folder 'GCA_005015715.1_PDT000222886.2' already exists. Skipping...
Folder 'GCA_005015975.1_PDT000244961.2' already exists. Skipping...
Folder 'GCA_005016015.1_PDT000205048.2' already exists. Skipping...
Folder 'GCA_005016035.1_PDT000244916.2' already exists. Skipping...
Folder 'GCA_005016055.1_PDT000208489.2' already exists. Skipping...
Folder 'GCA_005016115.1_PDT000224305.2' already exists. Skipping...
Folder 'GCA_005016875.1_PDT000227902.2' already exists. Skipping...
Folder 'GCA_005016915.1_PDT000227046.2' already exists. Skipping...
Folder 'GCA_005016935.1_PDT000225837.2' already exists. Skipping...
Folder 'GCA_005016955.1_PDT000227912.2' already exists. Skipping...
Folder 'GCA_005016975.1_PDT000227036.2' already exists. Skipping...
Folder 'GCA_005016995.1_PDT000219248.2' already exists. Skipping...
Folder 'GCA_005017015.1_PDT000208224.2' already exists. Skipping...
Folder 'GCA_005017035.1_PDT000227942.2' already exists. Skipping...
Folder 'GCA_005017055.1_PDT000232716.2' already exists. Skipping...
Folder 'GCA_005017075.1_PDT000209793.2' already exists. Skipping...
Folder 'GCA_005017115.1_PDT000262029.2' already exists. Skipping...
Folder 'GCA_005017135.1_PDT000213297.2' already exists. Skipping...
Folder 'GCA_005017155.1_PDT000232703.2' already exists. Skipping...
Folder 'GCA_005017175.1_PDT000262024.2' already exists. Skipping...
Folder 'GCA_005017195.1_PDT000219308.2' already exists. Skipping...
Folder 'GCA_005017215.1_PDT000227947.2' already exists. Skipping...
Folder 'GCA_005017235.1_PDT000219303.2' already exists. Skipping...
Folder 'GCA_005017375.1_PDT000226115.2' already exists. Skipping...
Folder 'GCA_005017395.1_PDT000235442.2' already exists. Skipping...
Folder 'GCA_005017415.1_PDT000226080.2' already exists. Skipping...
Folder 'GCA_005017435.1_PDT000224980.2' already exists. Skipping...
Folder 'GCA_005017455.1_PDT000222893.2' already exists. Skipping...
Folder 'GCA_005017555.1_PDT000244813.2' already exists. Skipping...
Folder 'GCA_005017595.1_PDT000244950.2' already exists. Skipping...
Folder 'GCA_005017615.1_PDT000250554.2' already exists. Skipping...
Folder 'GCA_005017635.1_PDT000250589.2' already exists. Skipping...
Folder 'GCA_005017655.1_PDT000250574.2' already exists. Skipping...
Folder 'GCA_005017695.1_PDT000244980.2' already exists. Skipping...
Folder 'GCA_005017715.1_PDT000206380.2' already exists. Skipping...
Folder 'GCA_005017725.1_PDT000201974.2' already exists. Skipping...
Folder 'GCA_005017775.1_PDT000205644.2' already exists. Skipping...
Folder 'GCA_005018515.1_PDT000220816.2' already exists. Skipping...
Folder 'GCA_005018555.1_PDT000244904.2' already exists. Skipping...
Folder 'GCA_005018575.1_PDT000220806.2' already exists. Skipping...
Folder 'GCA_005018615.1_PDT000226044.2' already exists. Skipping...
Folder 'GCA_005018795.1_PDT000237030.2' already exists. Skipping...
Folder 'GCA_005018815.1_PDT000237042.2' already exists. Skipping...
Folder 'GCA_005018835.1_PDT000245275.2' already exists. Skipping...
Folder 'GCA_005018855.1_PDT000250585.2' already exists. Skipping...
Folder 'GCA_005018875.1_PDT000254348.2' already exists. Skipping...
Folder 'GCA_005018935.1_PDT000244969.2' already exists. Skipping...
Folder 'GCA_005018955.1_PDT000245280.2' already exists. Skipping...
Folder 'GCA_005019595.1_PDT000237010.2' already exists. Skipping...
Folder 'GCA_005019615.1_PDT000237005.2' already exists. Skipping...
Folder 'GCA_005019635.1_PDT000244864.2' already exists. Skipping...
Folder 'GCA_005019655.1_PDT000226049.2' already exists. Skipping...
Folder 'GCA_005019715.1_PDT000193509.2' already exists. Skipping...
Folder 'GCA_005019735.1_PDT000236219.2' already exists. Skipping...
Folder 'GCA_005019775.1_PDT000236231.2' already exists. Skipping...
Folder 'GCA_005019795.1_PDT000263953.2' already exists. Skipping...
Folder 'GCA_005019815.1_PDT000262634.2' already exists. Skipping...
Folder 'GCA_005019835.1_PDT000262619.2' already exists. Skipping...
Folder 'GCA_005019845.1_PDT000208344.2' already exists. Skipping...
Folder 'GCA_005019875.1_PDT000237888.2' already exists. Skipping...
Folder 'GCA_005019895.1_PDT000218564.2' already exists. Skipping...
Folder 'GCA_005019915.1_PDT000218544.2' already exists. Skipping...
Folder 'GCA_005019955.1_PDT000262589.2' already exists. Skipping...
Folder 'GCA_005019975.1_PDT000222105.2' already exists. Skipping...
Folder 'GCA_005019995.1_PDT000221261.2' already exists. Skipping...
Folder 'GCA_005020015.1_PDT000262629.2' already exists. Skipping...
Folder 'GCA_005020035.1_PDT000262576.2' already exists. Skipping...
Folder 'GCA_005020075.1_PDT000225574.2' already exists. Skipping...
Folder 'GCA_005020095.1_PDT000234007.2' already exists. Skipping...
Folder 'GCA_005020115.1_PDT000266109.2' already exists. Skipping...
Folder 'GCA_005020175.1_PDT000208223.2' already exists. Skipping...
Folder 'GCA_005020195.1_PDT000193624.2' already exists. Skipping...
Folder 'GCA_005020225.1_PDT000193619.2' already exists. Skipping...
Folder 'GCA_005020255.1_PDT000204937.2' already exists. Skipping...
Folder 'GCA_005020295.1_PDT000236271.2' already exists. Skipping...
Folder 'GCA_005020315.1_PDT000239252.2' already exists. Skipping...
Folder 'GCA_005020355.1_PDT000193649.2' already exists. Skipping...
Folder 'GCA_005020375.1_PDT000192376.2' already exists. Skipping...
Folder 'GCA_005020395.1_PDT000236261.2' already exists. Skipping...
Folder 'GCA_005020455.1_PDT000192393.2' already exists. Skipping...
Folder 'GCA_005020475.1_PDT000213278.2' already exists. Skipping...
Folder 'GCA_005020555.1_PDT000263951.2' already exists. Skipping...
Folder 'GCA_005020575.1_PDT000262569.2' already exists. Skipping...
Folder 'GCA_005020595.1_PDT000221234.2' already exists. Skipping...
Folder 'GCA_005020695.1_PDT000257638.2' already exists. Skipping...
Folder 'GCA_005020735.1_PDT000239217.2' already exists. Skipping...
Folder 'GCA_005020755.1_PDT000222124.2' already exists. Skipping...
Folder 'GCA_005020795.1_PDT000229963.2' already exists. Skipping...
Folder 'GCA_005020835.1_PDT000245168.2' already exists. Skipping...
Folder 'GCA_005020875.1_PDT000245258.2' already exists. Skipping...
Folder 'GCA_005020935.1_PDT000234002.2' already exists. Skipping...
Folder 'GCA_005020955.1_PDT000221251.2' already exists. Skipping...
Folder 'GCA_005021035.1_PDT000222119.2' already exists. Skipping...
Folder 'GCA_005021075.1_PDT000230846.2' already exists. Skipping...
Folder 'GCA_005021095.1_PDT000262578.2' already exists. Skipping...
Folder 'GCA_005021175.1_PDT000268212.2' already exists. Skipping...
Folder 'GCA_005021185.1_PDT000266393.2' already exists. Skipping...
Folder 'GCA_005021395.1_PDT000250646.2' already exists. Skipping...
Folder 'GCA_005021475.1_PDT000221262.2' already exists. Skipping...
Folder 'GCA_005021495.1_PDT000233996.2' already exists. Skipping...
Folder 'GCA_005021535.1_PDT000234003.2' already exists. Skipping...
Folder 'GCA_005021615.1_PDT000221257.2' already exists. Skipping...
Folder 'GCA_005021675.1_PDT000229967.2' already exists. Skipping...
Folder 'GCA_005021805.1_PDT000213331.2' already exists. Skipping...
Folder 'GCA_005021835.1_PDT000245178.2' already exists. Skipping...
Folder 'GCA_005021855.1_PDT000232691.2' already exists. Skipping...
Folder 'GCA_005021895.1_PDT000221247.2' already exists. Skipping...
Folder 'GCA_005021955.1_PDT000245026.2' already exists. Skipping...
Folder 'GCA_005021975.1_PDT000233999.2' already exists. Skipping...
Folder 'GCA_005022035.1_PDT000234009.2' already exists. Skipping...
Folder 'GCA_005022255.1_PDT000222122.2' already exists. Skipping...
Folder 'GCA_005022295.1_PDT000236258.2' already exists. Skipping...
Folder 'GCA_005022315.1_PDT000230844.2' already exists. Skipping...
Folder 'GCA_005022335.1_PDT000245043.2' already exists. Skipping...
Folder 'GCA_005022355.1_PDT000239224.2' already exists. Skipping...
Folder 'GCA_005022375.1_PDT000245038.2' already exists. Skipping...
Folder 'GCA_005022415.1_PDT000236230.2' already exists. Skipping...
Folder 'GCA_005022455.1_PDT000237887.2' already exists. Skipping...
Folder 'GCA_005022495.1_PDT000235923.2' already exists. Skipping...
Folder 'GCA_005022515.1_PDT000229964.2' already exists. Skipping...
Folder 'GCA_005022535.1_PDT000236255.2' already exists. Skipping...
Folder 'GCA_005022555.1_PDT000236215.2' already exists. Skipping...
Folder 'GCA_005022575.1_PDT000245080.2' already exists. Skipping...
Folder 'GCA_005022635.1_PDT000178463.3' already exists. Skipping...
Folder 'GCA_005023195.1_PDT000257643.2' already exists. Skipping...
Folder 'GCA_005023215.1_PDT000245122.2' already exists. Skipping...
Folder 'GCA_005023265.1_PDT000245157.2' already exists. Skipping...
Folder 'GCA_005023295.1_PDT000245116.2' already exists. Skipping...
Folder 'GCA_005023335.1_PDT000257645.2' already exists. Skipping...
Folder 'GCA_005023415.1_PDT000245203.2' already exists. Skipping...
Folder 'GCA_005024215.1_PDT000213340.2' already exists. Skipping...
Folder 'GCA_005024235.1_PDT000262605.2' already exists. Skipping...
Folder 'GCA_005024255.1_PDT000215563.2' already exists. Skipping...
Folder 'GCA_005024275.1_PDT000208346.2' already exists. Skipping...
Folder 'GCA_005024295.1_PDT000213295.2' already exists. Skipping...
Folder 'GCA_005024325.1_PDT000262583.2' already exists. Skipping...
Folder 'GCA_005024355.1_PDT000221253.2' already exists. Skipping...
Folder 'GCA_005024435.1_PDT000218571.2' already exists. Skipping...
Folder 'GCA_005024555.1_PDT000239226.2' already exists. Skipping...
Folder 'GCA_005024565.1_PDT000235953.2' already exists. Skipping...
Folder 'GCA_005024785.1_PDT000226568.2' already exists. Skipping...
Folder 'GCA_005024845.1_PDT000227458.2' already exists. Skipping...
Folder 'GCA_005024925.1_PDT000232689.2' already exists. Skipping...
Folder 'GCA_005024945.1_PDT000232522.2' already exists. Skipping...

Retreiveing data: 6760it [00:02, 5941.83it/s]

Folder 'GCA_005096995.1_PDT000087458.2' already exists. Skipping...
Folder 'GCA_005097055.1_PDT000086122.2' already exists. Skipping...
Folder 'GCA_005097095.1_PDT000087467.2' already exists. Skipping...
Folder 'GCA_005097175.1_PDT000087480.2' already exists. Skipping...
Folder 'GCA_005097305.1_PDT000094888.2' already exists. Skipping...
Folder 'GCA_005097485.1_PDT000095382.2' already exists. Skipping...
Folder 'GCA_005097505.1_PDT000095381.2' already exists. Skipping...
Folder 'GCA_005097525.1_PDT000095385.2' already exists. Skipping...
Folder 'GCA_005097705.1_PDT000095393.2' already exists. Skipping...
Folder 'GCA_005097745.1_PDT000096694.2' already exists. Skipping...
Folder 'GCA_005097785.1_PDT000096707.2' already exists. Skipping...
Folder 'GCA_005097825.1_PDT000096698.2' already exists. Skipping...
Folder 'GCA_005097925.1_PDT000096681.2' already exists. Skipping...
Folder 'GCA_005097945.1_PDT000096705.2' already exists. Skipping...
Folder 'GCA_005098005.1_PDT000096708.2' already exists. Skipping...
Folder 'GCA_005098085.1_PDT000100758.2' already exists. Skipping...
Folder 'GCA_005098145.1_PDT000100763.2' already exists. Skipping...
Folder 'GCA_005098185.1_PDT000100966.2' already exists. Skipping...
Folder 'GCA_005098205.1_PDT000100972.2' already exists. Skipping...
Folder 'GCA_005098225.1_PDT000100956.2' already exists. Skipping...
Folder 'GCA_005098245.1_PDT000101449.2' already exists. Skipping...
Folder 'GCA_005098265.1_PDT000100976.2' already exists. Skipping...
Folder 'GCA_005098305.1_PDT000101468.2' already exists. Skipping...
Folder 'GCA_005098365.1_PDT000101454.2' already exists. Skipping...
Folder 'GCA_005098385.1_PDT000104885.2' already exists. Skipping...
Folder 'GCA_005098405.1_PDT000104880.2' already exists. Skipping...
Folder 'GCA_005098445.1_PDT000101482.2' already exists. Skipping...
Folder 'GCA_005098485.1_PDT000101478.2' already exists. Skipping...
Folder 'GCA_005098525.1_PDT000101485.2' already exists. Skipping...
Folder 'GCA_005098565.1_PDT000101487.2' already exists. Skipping...
Folder 'GCA_005098785.1_PDT000101488.2' already exists. Skipping...
Folder 'GCA_005098795.1_PDT000104877.2' already exists. Skipping...
Folder 'GCA_005098845.1_PDT000125863.2' already exists. Skipping...
Folder 'GCA_005098855.1_PDT000126365.2' already exists. Skipping...
Folder 'GCA_005098895.1_PDT000125859.2' already exists. Skipping...
Folder 'GCA_005098965.1_PDT000128715.2' already exists. Skipping...
Folder 'GCA_005098985.1_PDT000129593.2' already exists. Skipping...
Folder 'GCA_005099005.1_PDT000128945.2' already exists. Skipping...
Folder 'GCA_005099025.1_PDT000128938.2' already exists. Skipping...
Folder 'GCA_005099065.1_PDT000128713.2' already exists. Skipping...
Folder 'GCA_005099125.1_PDT000128709.2' already exists. Skipping...
Folder 'GCA_005099145.1_PDT000128708.2' already exists. Skipping...
Folder 'GCA_005099165.1_PDT000128720.2' already exists. Skipping...
Folder 'GCA_005099185.1_PDT000128934.2' already exists. Skipping...
Folder 'GCA_005099205.1_PDT000128957.2' already exists. Skipping...
Folder 'GCA_005099225.1_PDT000128716.2' already exists. Skipping...
Folder 'GCA_005099245.1_PDT000128690.2' already exists. Skipping...
Folder 'GCA_005099265.1_PDT000128961.2' already exists. Skipping...
Folder 'GCA_005099325.1_PDT000131060.2' already exists. Skipping...
Folder 'GCA_005099365.1_PDT000133427.2' already exists. Skipping...
Folder 'GCA_005099425.1_PDT000133497.2' already exists. Skipping...
Folder 'GCA_005099865.1_PDT000134603.2' already exists. Skipping...
Folder 'GCA_005100765.1_PDT000104907.2' already exists. Skipping...
Folder 'GCA_005100945.1_PDT000128698.2' already exists. Skipping...
Folder 'GCA_005100985.1_PDT000104878.2' already exists. Skipping...
Folder 'GCA_005101065.1_PDT000104881.2' already exists. Skipping...
Folder 'GCA_005101085.1_PDT000113272.2' already exists. Skipping...
Folder 'GCA_005101125.1_PDT000113249.2' already exists. Skipping...
Folder 'GCA_005101225.1_PDT000128680.2' already exists. Skipping...
Folder 'GCA_005101245.1_PDT000104910.2' already exists. Skipping...
Folder 'GCA_005101405.1_PDT000104890.2' already exists. Skipping...
Folder 'GCA_005101505.1_PDT000128707.2' already exists. Skipping...
Folder 'GCA_005101525.1_PDT000104903.2' already exists. Skipping...
Folder 'GCA_005101705.1_PDT000104873.2' already exists. Skipping...
Folder 'GCA_005101725.1_PDT000134199.2' already exists. Skipping...
Folder 'GCA_005101745.1_PDT000104908.2' already exists. Skipping...
Folder 'GCA_005101825.1_PDT000113255.2' already exists. Skipping...
Folder 'GCA_005101905.1_PDT000128697.2' already exists. Skipping...
Folder 'GCA_005102055.1_PDT000134204.2' already exists. Skipping...
Folder 'GCA_005102165.1_PDT000113270.2' already exists. Skipping...
Folder 'GCA_005102205.1_PDT000115070.2' already exists. Skipping...
Folder 'GCA_005102305.1_PDT000104905.2' already exists. Skipping...
Folder 'GCA_005102325.1_PDT000128699.2' already exists. Skipping...
Folder 'GCA_005102565.1_PDT000104895.2' already exists. Skipping...
Folder 'GCA_005102605.1_PDT000104892.2' already exists. Skipping...
Folder 'GCA_005102715.1_PDT000104900.2' already exists. Skipping...
Folder 'GCA_005102785.1_PDT000104966.2' already exists. Skipping...
Folder 'GCA_005103105.1_PDT000115123.2' already exists. Skipping...
Folder 'GCA_005103665.1_PDT000138833.2' already exists. Skipping...
Folder 'GCA_005103845.1_PDT000139247.2' already exists. Skipping...
Folder 'GCA_005104185.1_PDT000141072.2' already exists. Skipping...
Folder 'GCA_005104685.1_PDT000144106.2' already exists. Skipping...
Folder 'GCA_005104805.1_PDT000144101.2' already exists. Skipping...
Folder 'GCA_005105065.1_PDT000143847.2' already exists. Skipping...
Folder 'GCA_005105245.1_PDT000146679.2' already exists. Skipping...
Folder 'GCA_005105735.1_PDT000146674.2' already exists. Skipping...
Folder 'GCA_005105885.1_PDT000144579.2' already exists. Skipping...
Folder 'GCA_005105985.1_PDT000145236.2' already exists. Skipping...
Folder 'GCA_005106005.1_PDT000145238.2' already exists. Skipping...
Folder 'GCA_005106105.1_PDT000145235.2' already exists. Skipping...
Folder 'GCA_005106185.1_PDT000144572.2' already exists. Skipping...
Folder 'GCA_005106305.1_PDT000144577.2' already exists. Skipping...
Folder 'GCA_005106325.1_PDT000144582.2' already exists. Skipping...
Folder 'GCA_005106335.1_PDT000144584.2' already exists. Skipping...
Folder 'GCA_005106845.1_PDT000147392.2' already exists. Skipping...
Folder 'GCA_005106965.1_PDT000148336.2' already exists. Skipping...
Folder 'GCA_005107065.1_PDT000148348.2' already exists. Skipping...
Folder 'GCA_005107085.1_PDT000148349.2' already exists. Skipping...
Folder 'GCA_005107385.1_PDT000148694.2' already exists. Skipping...
Folder 'GCA_005107545.1_PDT000148740.2' already exists. Skipping...
Folder 'GCA_005107945.1_PDT000147401.2' already exists. Skipping...
Folder 'GCA_005108065.1_PDT000147395.2' already exists. Skipping...
Folder 'GCA_005108085.1_PDT000147389.2' already exists. Skipping...
Folder 'GCA_005108145.1_PDT000147397.2' already exists. Skipping...
Folder 'GCA_005108165.1_PDT000147399.2' already exists. Skipping...
Folder 'GCA_005108185.1_PDT000147414.2' already exists. Skipping...
Folder 'GCA_005108285.1_PDT000148720.2' already exists. Skipping...
Folder 'GCA_005108325.1_PDT000146676.2' already exists. Skipping...
Folder 'GCA_005108385.1_PDT000150596.2' already exists. Skipping...
Folder 'GCA_005108525.1_PDT000150608.2' already exists. Skipping...
Folder 'GCA_005108965.1_PDT000149739.2' already exists. Skipping...
Folder 'GCA_005109005.1_PDT000149772.2' already exists. Skipping...
Folder 'GCA_005109025.1_PDT000149751.2' already exists. Skipping...
Folder 'GCA_005109045.1_PDT000149791.2' already exists. Skipping...
Folder 'GCA_005109065.1_PDT000149630.2' already exists. Skipping...
Folder 'GCA_005109265.1_PDT000149793.2' already exists. Skipping...
Folder 'GCA_005109345.1_PDT000149816.2' already exists. Skipping...
Folder 'GCA_005109765.1_PDT000150628.2' already exists. Skipping...
Folder 'GCA_005109805.1_PDT000150650.2' already exists. Skipping...
Folder 'GCA_005109825.1_PDT000150629.2' already exists. Skipping...
Folder 'GCA_005109865.1_PDT000150630.2' already exists. Skipping...
Folder 'GCA_005109925.1_PDT000150643.2' already exists. Skipping...
Folder 'GCA_005109945.1_PDT000150647.2' already exists. Skipping...
Folder 'GCA_005109965.1_PDT000150651.2' already exists. Skipping...
Folder 'GCA_005109995.1_PDT000150654.2' already exists. Skipping...
Folder 'GCA_005110045.1_PDT000150655.2' already exists. Skipping...
Folder 'GCA_005110425.1_PDT000151169.2' already exists. Skipping...
Folder 'GCA_005110565.1_PDT000152149.2' already exists. Skipping...
Folder 'GCA_005110605.1_PDT000150928.2' already exists. Skipping...
Folder 'GCA_005111525.1_PDT000154193.2' already exists. Skipping...
Folder 'GCA_005111725.1_PDT000159087.2' already exists. Skipping...
Folder 'GCA_005111805.1_PDT000154143.2' already exists. Skipping...
Folder 'GCA_005111825.1_PDT000153099.2' already exists. Skipping...
Folder 'GCA_005111965.1_PDT000162836.2' already exists. Skipping...
Folder 'GCA_005112125.1_PDT000157627.2' already exists. Skipping...
Folder 'GCA_005112145.1_PDT000153094.2' already exists. Skipping...
Folder 'GCA_005112165.1_PDT000154139.2' already exists. Skipping...
Folder 'GCA_005112185.1_PDT000157631.2' already exists. Skipping...
Folder 'GCA_005112205.1_PDT000162825.2' already exists. Skipping...
Folder 'GCA_005112245.1_PDT000153106.2' already exists. Skipping...
Folder 'GCA_005112345.1_PDT000162835.2' already exists. Skipping...
Folder 'GCA_005112405.1_PDT000157641.2' already exists. Skipping...
Folder 'GCA_005112445.1_PDT000153102.2' already exists. Skipping...
Folder 'GCA_005112775.1_PDT000154194.2' already exists. Skipping...
Folder 'GCA_005113005.1_PDT000159069.2' already exists. Skipping...
Folder 'GCA_005113115.1_PDT000159084.2' already exists. Skipping...
Folder 'GCA_005113165.1_PDT000159078.2' already exists. Skipping...
Folder 'GCA_005113185.1_PDT000159073.2' already exists. Skipping...
Folder 'GCA_005113245.1_PDT000159083.2' already exists. Skipping...
Folder 'GCA_005113325.1_PDT000162361.2' already exists. Skipping...
Folder 'GCA_005113335.1_PDT000159088.2' already exists. Skipping...
Folder 'GCA_005113485.1_PDT000162366.2' already exists. Skipping...
Folder 'GCA_005113505.1_PDT000162369.2' already exists. Skipping...
Folder 'GCA_005113585.1_PDT000162528.2' already exists. Skipping...
Folder 'GCA_005113685.1_PDT000162538.2' already exists. Skipping...
Folder 'GCA_005113705.1_PDT000162539.2' already exists. Skipping...
Folder 'GCA_005113765.1_PDT000162548.2' already exists. Skipping...
Folder 'GCA_005113805.1_PDT000162551.2' already exists. Skipping...
Folder 'GCA_005113825.1_PDT000162545.2' already exists. Skipping...
Folder 'GCA_005113955.1_PDT000162733.2' already exists. Skipping...
Folder 'GCA_005114085.1_PDT000162816.2' already exists. Skipping...
Folder 'GCA_005114105.1_PDT000162739.2' already exists. Skipping...
Folder 'GCA_005114205.1_PDT000162817.2' already exists. Skipping...
Folder 'GCA_005114345.1_PDT000167761.2' already exists. Skipping...
Folder 'GCA_005114385.1_PDT000167778.2' already exists. Skipping...
Folder 'GCA_005114485.1_PDT000173566.2' already exists. Skipping...
Folder 'GCA_005114665.1_PDT000167770.2' already exists. Skipping...
Folder 'GCA_005114685.1_PDT000167783.2' already exists. Skipping...
Folder 'GCA_005114705.1_PDT000168392.2' already exists. Skipping...
Folder 'GCA_005114845.1_PDT000168393.2' already exists. Skipping...
Folder 'GCA_005114945.1_PDT000168406.2' already exists. Skipping...
Folder 'GCA_005115025.1_PDT000168417.2' already exists. Skipping...
Folder 'GCA_005115085.1_PDT000168416.2' already exists. Skipping...
Folder 'GCA_005115125.1_PDT000168421.2' already exists. Skipping...
Folder 'GCA_005115145.1_PDT000168426.2' already exists. Skipping...
Folder 'GCA_005115545.1_PDT000171765.2' already exists. Skipping...
Folder 'GCA_005116105.1_PDT000173580.2' already exists. Skipping...
Folder 'GCA_005116125.1_PDT000173573.2' already exists. Skipping...
Folder 'GCA_005116285.1_PDT000173576.2' already exists. Skipping...
Folder 'GCA_005116305.1_PDT000173581.2' already exists. Skipping...
Folder 'GCA_005116425.1_PDT000174420.2' already exists. Skipping...
Folder 'GCA_005117185.1_PDT000174433.2' already exists. Skipping...
Folder 'GCA_005117305.1_PDT000174447.2' already exists. Skipping...
Folder 'GCA_005117365.1_PDT000175669.2' already exists. Skipping...
Folder 'GCA_005117425.1_PDT000174441.2' already exists. Skipping...
Folder 'GCA_005117555.1_PDT000176556.2' already exists. Skipping...
Folder 'GCA_005117655.1_PDT000176291.2' already exists. Skipping...
Folder 'GCA_005117695.1_PDT000176559.2' already exists. Skipping...
Folder 'GCA_005117715.1_PDT000176560.2' already exists. Skipping...
Folder 'GCA_005117735.1_PDT000176293.2' already exists. Skipping...
Folder 'GCA_005117815.1_PDT000176570.2' already exists. Skipping...
Folder 'GCA_005117895.1_PDT000176283.2' already exists. Skipping...
Folder 'GCA_005117915.1_PDT000176572.2' already exists. Skipping...
Folder 'GCA_005117955.1_PDT000176286.2' already exists. Skipping...
Folder 'GCA_005117975.1_PDT000176562.2' already exists. Skipping...
Folder 'GCA_005117995.1_PDT000176258.2' already exists. Skipping...
Folder 'GCA_005118055.1_PDT000176565.2' already exists. Skipping...
Folder 'GCA_005118205.1_PDT000187677.2' already exists. Skipping...
Folder 'GCA_005118225.1_PDT000187689.2' already exists. Skipping...
Folder 'GCA_005118305.1_PDT000473116.1' already exists. Skipping...
Folder 'GCA_005118365.1_PDT000473128.2' already exists. Skipping...
Folder 'GCA_005118565.1_PDT000187718.2' already exists. Skipping...
Folder 'GCA_005118605.1_PDT000187628.2' already exists. Skipping...
Folder 'GCA_005118615.1_PDT000189069.2' already exists. Skipping...
Folder 'GCA_005118645.1_PDT000189076.2' already exists. Skipping...
Folder 'GCA_005118665.1_PDT000189077.2' already exists. Skipping...
Folder 'GCA_005118685.1_PDT000189078.2' already exists. Skipping...
Folder 'GCA_005118725.1_PDT000189089.2' already exists. Skipping...
Folder 'GCA_005118805.1_PDT000189083.2' already exists. Skipping...
Folder 'GCA_005119165.1_PDT000473050.2' already exists. Skipping...
Folder 'GCA_005119205.1_PDT000472941.2' already exists. Skipping...
Folder 'GCA_005119245.1_PDT000472989.2' already exists. Skipping...
Folder 'GCA_005119285.1_PDT000473051.2' already exists. Skipping...
Folder 'GCA_005119405.1_PDT000484783.1' already exists. Skipping...
Folder 'GCA_005119465.1_PDT000484774.1' already exists. Skipping...
Folder 'GCA_005119565.1_PDT000199669.2' already exists. Skipping...
Folder 'GCA_005119605.1_PDT000189123.2' already exists. Skipping...
Folder 'GCA_005119785.1_PDT000190576.2' already exists. Skipping...
Folder 'GCA_005119825.1_PDT000190596.2' already exists. Skipping...
Folder 'GCA_005120025.1_PDT000199639.2' already exists. Skipping...
Folder 'GCA_005120085.1_PDT000199634.2' already exists. Skipping...
Folder 'GCA_005120105.1_PDT000199649.2' already exists. Skipping...
Folder 'GCA_005120145.1_PDT000199674.2' already exists. Skipping...
Folder 'GCA_005120165.1_PDT000441558.2' already exists. Skipping...
Folder 'GCA_005120185.1_PDT000226074.3' already exists. Skipping...
Folder 'GCA_005120265.1_PDT000388811.1' already exists. Skipping...
Folder 'GCA_005120405.1_PDT000184337.2' already exists. Skipping...
Folder 'GCA_005120845.1_PDT000185503.2' already exists. Skipping...
Folder 'GCA_005120925.1_PDT000187330.2' already exists. Skipping...
Folder 'GCA_005120945.1_PDT000187320.2' already exists. Skipping...
Folder 'GCA_005121025.1_PDT000441560.2' already exists. Skipping...
Folder 'GCA_005121235.1_PDT000495252.1' already exists. Skipping...
Folder 'GCA_005121385.1_PDT000485396.1' already exists. Skipping...
Folder 'GCA_005121425.1_PDT000485411.1' already exists. Skipping...
Folder 'GCA_005121445.1_PDT000486203.1' already exists. Skipping...
Folder 'GCA_005121465.1_PDT000484843.1' already exists. Skipping...
Folder 'GCA_005121485.1_PDT000485392.1' already exists. Skipping...
Folder 'GCA_005121525.1_PDT000485419.1' already exists. Skipping...
Folder 'GCA_005121565.1_PDT000484848.1' already exists. Skipping...
Folder 'GCA_005121585.1_PDT000486198.1' already exists. Skipping...
Folder 'GCA_005121605.1_PDT000484839.1' already exists. Skipping...
Folder 'GCA_005121625.1_PDT000486207.1' already exists. Skipping...
Folder 'GCA_005121645.1_PDT000485431.1' already exists. Skipping...
Folder 'GCA_005121665.1_PDT000485421.1' already exists. Skipping...
Folder 'GCA_005121725.1_PDT000489293.1' already exists. Skipping...
Folder 'GCA_005121745.1_PDT000485672.1' already exists. Skipping...
Folder 'GCA_005121885.1_PDT000489275.1' already exists. Skipping...
Folder 'GCA_005121945.1_PDT000485728.1' already exists. Skipping...
Folder 'GCA_005121985.1_PDT000485885.1' already exists. Skipping...
Folder 'GCA_005122005.1_PDT000485887.1' already exists. Skipping...
Folder 'GCA_005122045.1_PDT000485899.1' already exists. Skipping...
Folder 'GCA_005122085.1_PDT000485891.1' already exists. Skipping...
Folder 'GCA_005122125.1_PDT000486187.1' already exists. Skipping...
Folder 'GCA_005122165.1_PDT000486194.1' already exists. Skipping...
Folder 'GCA_005122185.1_PDT000486212.1' already exists. Skipping...
Folder 'GCA_005122285.1_PDT000486222.1' already exists. Skipping...
Folder 'GCA_005122305.1_PDT000486229.1' already exists. Skipping...
Folder 'GCA_005122325.1_PDT000486237.1' already exists. Skipping...
Folder 'GCA_005122445.1_PDT000486242.1' already exists. Skipping...
Folder 'GCA_005122465.1_PDT000486266.1' already exists. Skipping...
Folder 'GCA_005122505.1_PDT000486256.1' already exists. Skipping...
Folder 'GCA_005122525.1_PDT000486319.1' already exists. Skipping...
Folder 'GCA_005122565.1_PDT000489245.1' already exists. Skipping...
Folder 'GCA_005122665.1_PDT000486379.1' already exists. Skipping...
Folder 'GCA_005122825.1_PDT000486377.1' already exists. Skipping...
Folder 'GCA_005122845.1_PDT000486406.1' already exists. Skipping...
Folder 'GCA_005122905.1_PDT000486903.1' already exists. Skipping...
Folder 'GCA_005122945.1_PDT000486403.1' already exists. Skipping...
Folder 'GCA_005122985.1_PDT000486424.1' already exists. Skipping...
Folder 'GCA_005123125.1_PDT000487543.1' already exists. Skipping...
Folder 'GCA_005123265.1_PDT000487859.1' already exists. Skipping...
Folder 'GCA_005123405.1_PDT000489256.1' already exists. Skipping...
Folder 'GCA_005123505.1_PDT000490960.1' already exists. Skipping...
Folder 'GCA_005123565.1_PDT000490939.1' already exists. Skipping...
Folder 'GCA_005123585.1_PDT000489276.1' already exists. Skipping...
Folder 'GCA_005123605.1_PDT000489285.1' already exists. Skipping...
Folder 'GCA_005123625.1_PDT000489258.1' already exists. Skipping...
Folder 'GCA_005123685.1_PDT000489287.1' already exists. Skipping...
Folder 'GCA_005123705.1_PDT000490965.1' already exists. Skipping...
Folder 'GCA_005123805.1_PDT000494347.1' already exists. Skipping...
Folder 'GCA_005123845.1_PDT000494386.1' already exists. Skipping...
Folder 'GCA_005123905.1_PDT000494404.1' already exists. Skipping...
Folder 'GCA_005123985.1_PDT000494455.1' already exists. Skipping...
Folder 'GCA_005124005.1_PDT000494452.1' already exists. Skipping...
Folder 'GCA_005124025.1_PDT000494458.1' already exists. Skipping...
Folder 'GCA_005124045.1_PDT000494442.1' already exists. Skipping...
Folder 'GCA_005124125.1_PDT000494463.1' already exists. Skipping...
Folder 'GCA_005124185.1_PDT000494622.1' already exists. Skipping...
Folder 'GCA_005124205.1_PDT000494465.1' already exists. Skipping...
Folder 'GCA_005124225.1_PDT000494620.1' already exists. Skipping...
Folder 'GCA_005124245.1_PDT000494627.1' already exists. Skipping...
Folder 'GCA_005124265.1_PDT000494621.1' already exists. Skipping...
Folder 'GCA_005124285.1_PDT000494625.1' already exists. Skipping...
Folder 'GCA_005124325.1_PDT000494894.1' already exists. Skipping...

Retreiveing data: 8095it [00:02, 6294.91it/s]

Folder 'GCA_005199875.1_PDT000162401.2' already exists. Skipping...
Folder 'GCA_005199955.1_PDT000312770.2' already exists. Skipping...
Folder 'GCA_005199995.1_PDT000307269.2' already exists. Skipping...
Folder 'GCA_005200195.1_PDT000315431.2' already exists. Skipping...
Folder 'GCA_005200315.1_PDT000310567.2' already exists. Skipping...
Folder 'GCA_005200365.1_PDT000320028.2' already exists. Skipping...
Folder 'GCA_005200415.1_PDT000485479.1' already exists. Skipping...
Folder 'GCA_005200555.1_PDT000484834.1' already exists. Skipping...
Folder 'GCA_005200575.1_PDT000484841.1' already exists. Skipping...
Folder 'GCA_005200595.1_PDT000484781.1' already exists. Skipping...
Folder 'GCA_005200635.1_PDT000484796.1' already exists. Skipping...
Folder 'GCA_005201015.1_PDT000138027.3' already exists. Skipping...
Folder 'GCA_005201155.1_PDT000162541.2' already exists. Skipping...
Folder 'GCA_005201175.1_PDT000149770.2' already exists. Skipping...
Folder 'GCA_005201195.1_PDT000148891.2' already exists. Skipping...
Folder 'GCA_005201255.1_PDT000171755.2' already exists. Skipping...
Folder 'GCA_005201295.1_PDT000162537.2' already exists. Skipping...
Folder 'GCA_005201355.1_PDT000162363.2' already exists. Skipping...
Folder 'GCA_005201695.1_PDT000149771.2' already exists. Skipping...
Folder 'GCA_005201715.1_PDT000150613.2' already exists. Skipping...
Folder 'GCA_005201755.1_PDT000150602.2' already exists. Skipping...
Folder 'GCA_005202015.1_PDT000162534.2' already exists. Skipping...
Folder 'GCA_005202095.1_PDT000150641.2' already exists. Skipping...
Folder 'GCA_005202255.1_PDT000484814.1' already exists. Skipping...
Folder 'GCA_005202375.1_PDT000485723.1' already exists. Skipping...
Folder 'GCA_005202415.1_PDT000485441.1' already exists. Skipping...
Folder 'GCA_005202515.1_PDT000485715.1' already exists. Skipping...
Folder 'GCA_005202525.1_PDT000162368.2' already exists. Skipping...
Folder 'GCA_005202555.1_PDT000485612.1' already exists. Skipping...
Folder 'GCA_005202595.1_PDT000484788.1' already exists. Skipping...
Folder 'GCA_005202695.1_PDT000485473.1' already exists. Skipping...
Folder 'GCA_005202755.1_PDT000485502.1' already exists. Skipping...
Folder 'GCA_005202815.1_PDT000485636.1' already exists. Skipping...
Folder 'GCA_005202855.1_PDT000485617.1' already exists. Skipping...
Folder 'GCA_005202895.1_PDT000484847.1' already exists. Skipping...
Folder 'GCA_005202955.1_PDT000144576.2' already exists. Skipping...
Folder 'GCA_005202995.1_PDT000485508.1' already exists. Skipping...
Folder 'GCA_005203155.2_PDT000233689.3' already exists. Skipping...
Folder 'GCA_005203195.1_PDT000190078.2' already exists. Skipping...
Folder 'GCA_005203255.1_PDT000224354.2' already exists. Skipping...
Folder 'GCA_005203305.1_PDT000199908.2' already exists. Skipping...
Folder 'GCA_005203355.1_PDT000231606.2' already exists. Skipping...
Folder 'GCA_005203415.1_PDT000485528.1' already exists. Skipping...
Folder 'GCA_005203435.1_PDT000485655.1' already exists. Skipping...
Folder 'GCA_005203495.1_PDT000485614.1' already exists. Skipping...
Folder 'GCA_005203575.1_PDT000199521.2' already exists. Skipping...
Folder 'GCA_005203655.1_PDT000485626.1' already exists. Skipping...
Folder 'GCA_005203735.1_PDT000485484.1' already exists. Skipping...
Folder 'GCA_005203755.1_PDT000220758.2' already exists. Skipping...
Folder 'GCA_005203775.1_PDT000216086.2' already exists. Skipping...
Folder 'GCA_005203855.1_PDT000485451.1' already exists. Skipping...
Folder 'GCA_005203895.1_PDT000226077.2' already exists. Skipping...
Folder 'GCA_005203915.1_PDT000224982.2' already exists. Skipping...
Folder 'GCA_005203995.1_PDT000219301.2' already exists. Skipping...
Folder 'GCA_005204055.1_PDT000485642.1' already exists. Skipping...
Folder 'GCA_005204095.1_PDT000485490.1' already exists. Skipping...
Folder 'GCA_005204175.1_PDT000201916.2' already exists. Skipping...
Folder 'GCA_005204195.1_PDT000484782.1' already exists. Skipping...
Folder 'GCA_005204235.1_PDT000484840.1' already exists. Skipping...
Folder 'GCA_005204295.1_PDT000485657.1' already exists. Skipping...
Folder 'GCA_005204435.1_PDT000485706.1' already exists. Skipping...
Folder 'GCA_005204955.1_PDT000205643.2' already exists. Skipping...
Folder 'GCA_005204995.1_PDT000201921.2' already exists. Skipping...
Folder 'GCA_005205155.1_PDT000245349.2' already exists. Skipping...
Folder 'GCA_005205175.2_PDT000231607.3' already exists. Skipping...
Folder 'GCA_005205215.1_PDT000201934.2' already exists. Skipping...
Folder 'GCA_005205335.1_PDT000244846.2' already exists. Skipping...
Folder 'GCA_005205375.1_PDT000227023.2' already exists. Skipping...
Folder 'GCA_005205415.1_PDT000227944.2' already exists. Skipping...
Folder 'GCA_005205435.1_PDT000235884.2' already exists. Skipping...
Folder 'GCA_005205455.1_PDT000227879.2' already exists. Skipping...
Folder 'GCA_005205465.1_PDT000227949.2' already exists. Skipping...
Folder 'GCA_005205615.1_PDT000485532.1' already exists. Skipping...
Folder 'GCA_005205655.1_PDT000485733.1' already exists. Skipping...
Folder 'GCA_005205775.1_PDT000181055.2' already exists. Skipping...
Folder 'GCA_005205815.1_PDT000199964.2' already exists. Skipping...
Folder 'GCA_005205855.1_PDT000226047.2' already exists. Skipping...
Folder 'GCA_005205915.1_PDT000181153.2' already exists. Skipping...
Folder 'GCA_005205935.1_PDT000220819.2' already exists. Skipping...
Folder 'GCA_005205955.1_PDT000244831.2' already exists. Skipping...
Folder 'GCA_005206015.1_PDT000244953.2' already exists. Skipping...
Folder 'GCA_005206035.1_PDT000235430.2' already exists. Skipping...
Folder 'GCA_005206075.1_PDT000204941.2' already exists. Skipping...
Folder 'GCA_005206085.1_PDT000244936.2' already exists. Skipping...
Folder 'GCA_005206275.1_PDT000205653.2' already exists. Skipping...
Folder 'GCA_005206285.1_PDT000245367.2' already exists. Skipping...
Folder 'GCA_005206355.1_PDT000181033.2' already exists. Skipping...
Folder 'GCA_005206375.1_PDT000250578.2' already exists. Skipping...
Folder 'GCA_005206395.1_PDT000200026.2' already exists. Skipping...
Folder 'GCA_005206415.1_PDT000259608.2' already exists. Skipping...
Folder 'GCA_005206435.1_PDT000181149.2' already exists. Skipping...
Folder 'GCA_005206455.1_PDT000199566.2' already exists. Skipping...
Folder 'GCA_005206495.1_PDT000199596.2' already exists. Skipping...
Folder 'GCA_005206575.1_PDT000238357.2' already exists. Skipping...
Folder 'GCA_005206615.1_PDT000199918.2' already exists. Skipping...
Folder 'GCA_005206635.1_PDT000200432.2' already exists. Skipping...
Folder 'GCA_005206655.1_PDT000200405.2' already exists. Skipping...
Folder 'GCA_005206695.1_PDT000199975.2' already exists. Skipping...
Folder 'GCA_005206875.1_PDT000205650.2' already exists. Skipping...
Folder 'GCA_005206895.1_PDT000175434.2' already exists. Skipping...
Folder 'GCA_005207115.1_PDT000226065.2' already exists. Skipping...
Folder 'GCA_005207195.1_PDT000218900.2' already exists. Skipping...
Folder 'GCA_005207255.1_PDT000244903.2' already exists. Skipping...
Folder 'GCA_005207335.1_PDT000244848.2' already exists. Skipping...
Folder 'GCA_005207435.1_PDT000259636.2' already exists. Skipping...
Folder 'GCA_005207455.1_PDT000226084.2' already exists. Skipping...
Folder 'GCA_005207575.1_PDT000225834.2' already exists. Skipping...
Folder 'GCA_005207615.1_PDT000222849.2' already exists. Skipping...
Folder 'GCA_005207635.1_PDT000227941.2' already exists. Skipping...
Folder 'GCA_005207655.1_PDT000224312.2' already exists. Skipping...
Folder 'GCA_005207675.1_PDT000227043.2' already exists. Skipping...
Folder 'GCA_005207775.1_PDT000203812.2' already exists. Skipping...
Folder 'GCA_005207795.1_PDT000244897.2' already exists. Skipping...
Folder 'GCA_005207815.1_PDT000200442.2' already exists. Skipping...
Folder 'GCA_005207855.1_PDT000199943.2' already exists. Skipping...
Folder 'GCA_005207875.1_PDT000245348.2' already exists. Skipping...
Folder 'GCA_005207935.1_PDT000219299.2' already exists. Skipping...
Folder 'GCA_005207955.1_PDT000199469.2' already exists. Skipping...
Folder 'GCA_005208015.1_PDT000174451.2' already exists. Skipping...
Folder 'GCA_005208115.1_PDT000181049.2' already exists. Skipping...
Folder 'GCA_005208155.1_PDT000181154.2' already exists. Skipping...
Folder 'GCA_005208175.1_PDT000206866.2' already exists. Skipping...
Folder 'GCA_005208255.1_PDT000219331.2' already exists. Skipping...
Folder 'GCA_005208395.1_PDT000217354.2' already exists. Skipping...
Folder 'GCA_005208475.1_PDT000193630.2' already exists. Skipping...
Folder 'GCA_005208575.1_PDT000218640.2' already exists. Skipping...
Folder 'GCA_005208615.1_PDT000187716.2' already exists. Skipping...
Folder 'GCA_005208635.1_PDT000171763.2' already exists. Skipping...
Folder 'GCA_005208675.1_PDT000208217.2' already exists. Skipping...
Folder 'GCA_005208815.1_PDT000195221.2' already exists. Skipping...
Folder 'GCA_005208875.1_PDT000273672.2' already exists. Skipping...
Folder 'GCA_005208895.1_PDT000266344.2' already exists. Skipping...
Folder 'GCA_005208955.1_PDT000486380.1' already exists. Skipping...
Folder 'GCA_005208975.1_PDT000277697.2' already exists. Skipping...
Folder 'GCA_005209025.1_PDT000300076.2' already exists. Skipping...
Folder 'GCA_005209135.1_PDT000283679.2' already exists. Skipping...
Folder 'GCA_005209175.1_PDT000276007.2' already exists. Skipping...
Folder 'GCA_005209335.1_PDT000276322.2' already exists. Skipping...
Folder 'GCA_005209415.1_PDT000486412.1' already exists. Skipping...
Folder 'GCA_005209515.1_PDT000486413.1' already exists. Skipping...
Folder 'GCA_005209575.1_PDT000486425.1' already exists. Skipping...
Folder 'GCA_005209595.1_PDT000276409.2' already exists. Skipping...
Folder 'GCA_005209675.1_PDT000203060.2' already exists. Skipping...
Folder 'GCA_005209735.1_PDT000273647.2' already exists. Skipping...
Folder 'GCA_005209835.1_PDT000486218.1' already exists. Skipping...
Folder 'GCA_005209855.1_PDT000315085.2' already exists. Skipping...
Folder 'GCA_005209915.1_PDT000266314.2' already exists. Skipping...
Folder 'GCA_005210015.1_PDT000485902.1' already exists. Skipping...
Folder 'GCA_005210115.1_PDT000486265.1' already exists. Skipping...
Folder 'GCA_005210245.1_PDT000219294.2' already exists. Skipping...
Folder 'GCA_005210315.1_PDT000486428.1' already exists. Skipping...
Folder 'GCA_005210445.1_PDT000283534.2' already exists. Skipping...
Folder 'GCA_005210485.1_PDT000486385.1' already exists. Skipping...
Folder 'GCA_005210545.1_PDT000486426.1' already exists. Skipping...
Folder 'GCA_005210645.1_PDT000303638.2' already exists. Skipping...
Folder 'GCA_005210665.1_PDT000486381.1' already exists. Skipping...
Folder 'GCA_005210805.1_PDT000486258.1' already exists. Skipping...
Folder 'GCA_005210825.1_PDT000487551.1' already exists. Skipping...
Folder 'GCA_005210965.1_PDT000486411.1' already exists. Skipping...
Folder 'GCA_005211005.1_PDT000244943.2' already exists. Skipping...
Folder 'GCA_005211055.1_PDT000494328.1' already exists. Skipping...
Folder 'GCA_005211085.1_PDT000492530.1' already exists. Skipping...
Folder 'GCA_005211125.1_PDT000465137.1' already exists. Skipping...
Folder 'GCA_005211305.1_PDT000485901.1' already exists. Skipping...
Folder 'GCA_005211405.1_PDT000486188.1' already exists. Skipping...
Folder 'GCA_005211445.1_PDT000486204.1' already exists. Skipping...
Folder 'GCA_005211485.1_PDT000487548.1' already exists. Skipping...
Folder 'GCA_005211545.1_PDT000486197.1' already exists. Skipping...
Folder 'GCA_005211625.1_PDT000494343.1' already exists. Skipping...
Folder 'GCA_005211745.1_PDT000494291.1' already exists. Skipping...
Folder 'GCA_005211785.1_PDT000494351.1' already exists. Skipping...
Folder 'GCA_005211865.1_PDT000486382.1' already exists. Skipping...
Folder 'GCA_005211885.1_PDT000494280.1' already exists. Skipping...
Folder 'GCA_005211945.1_PDT000486889.1' already exists. Skipping...
Folder 'GCA_005212085.1_PDT000273667.2' already exists. Skipping...
Folder 'GCA_005212105.1_PDT000274585.2' already exists. Skipping...
Folder 'GCA_005212125.1_PDT000271715.2' already exists. Skipping...
Folder 'GCA_005212165.1_PDT000273642.2' already exists. Skipping...
Folder 'GCA_005212205.1_PDT000273019.2' already exists. Skipping...
Folder 'GCA_005212265.1_PDT000310869.2' already exists. Skipping...
Folder 'GCA_005212315.1_PDT000293246.2' already exists. Skipping...
Folder 'GCA_005212365.1_PDT000316063.2' already exists. Skipping...
Folder 'GCA_005212425.1_PDT000303018.2' already exists. Skipping...
Folder 'GCA_005212445.1_PDT000300798.2' already exists. Skipping...
Folder 'GCA_005212525.1_PDT000262114.2' already exists. Skipping...
Folder 'GCA_005212545.1_PDT000486373.1' already exists. Skipping...
Folder 'GCA_005212565.1_PDT000486201.1' already exists. Skipping...
Folder 'GCA_005212625.1_PDT000227016.2' already exists. Skipping...
Folder 'GCA_005212685.1_PDT000486376.1' already exists. Skipping...
Folder 'GCA_005212735.1_PDT000495257.1' already exists. Skipping...
Folder 'GCA_005212755.1_PDT000495306.1' already exists. Skipping...
Folder 'GCA_005212775.1_PDT000274575.2' already exists. Skipping...
Folder 'GCA_005212795.1_PDT000273657.2' already exists. Skipping...
Folder 'GCA_005212815.1_PDT000495294.1' already exists. Skipping...
Folder 'GCA_005212835.1_PDT000276352.2' already exists. Skipping...
Folder 'GCA_005212935.1_PDT000308370.2' already exists. Skipping...
Folder 'GCA_005213075.1_PDT000300091.2' already exists. Skipping...
Folder 'GCA_005213095.1_PDT000293393.2' already exists. Skipping...
Folder 'GCA_005213115.1_PDT000494284.1' already exists. Skipping...
Folder 'GCA_005213195.1_PDT000244829.2' already exists. Skipping...
Folder 'GCA_005213255.1_PDT000305754.2' already exists. Skipping...
Folder 'GCA_005213335.1_PDT000494443.1' already exists. Skipping...
Folder 'GCA_005213395.1_PDT000494905.1' already exists. Skipping...
Folder 'GCA_005213415.1_PDT000494459.1' already exists. Skipping...
Folder 'GCA_005213475.1_PDT000494324.1' already exists. Skipping...
Folder 'GCA_005213515.1_PDT000494462.1' already exists. Skipping...
Folder 'GCA_005213535.1_PDT000495073.1' already exists. Skipping...
Folder 'GCA_005213605.1_PDT000495075.1' already exists. Skipping...
Folder 'GCA_005213615.1_PDT000494911.1' already exists. Skipping...
Folder 'GCA_005213645.1_PDT000495152.1' already exists. Skipping...
Folder 'GCA_005213665.1_PDT000495159.1' already exists. Skipping...
Folder 'GCA_005213705.1_PDT000495162.1' already exists. Skipping...
Folder 'GCA_005213785.1_PDT000495315.1' already exists. Skipping...
Folder 'GCA_005213845.1_PDT000495360.1' already exists. Skipping...
Folder 'GCA_005213965.1_PDT000494331.1' already exists. Skipping...
Folder 'GCA_005213985.1_PDT000495338.1' already exists. Skipping...
Folder 'GCA_005214045.1_PDT000494283.1' already exists. Skipping...
Folder 'GCA_005214065.1_PDT000494302.1' already exists. Skipping...
Folder 'GCA_005214075.1_PDT000494325.1' already exists. Skipping...
Folder 'GCA_005214145.1_PDT000494294.1' already exists. Skipping...
Folder 'GCA_005214165.1_PDT000494295.1' already exists. Skipping...
Folder 'GCA_005214205.1_PDT000494373.1' already exists. Skipping...
Folder 'GCA_005214225.1_PDT000494444.1' already exists. Skipping...
Folder 'GCA_005214245.1_PDT000494449.1' already exists. Skipping...
Folder 'GCA_005214285.1_PDT000494446.1' already exists. Skipping...
Folder 'GCA_005214325.1_PDT000231619.2' already exists. Skipping...
Folder 'GCA_005214365.1_PDT000222910.2' already exists. Skipping...
Folder 'GCA_005214565.1_PDT000244918.2' already exists. Skipping...
Folder 'GCA_005214725.1_PDT000219252.2' already exists. Skipping...
Folder 'GCA_005214745.1_PDT000244873.2' already exists. Skipping...
Folder 'GCA_005214905.1_PDT000215792.2' already exists. Skipping...
Folder 'GCA_005214945.1_PDT000227952.2' already exists. Skipping...
Folder 'GCA_005214985.1_PDT000491016.1' already exists. Skipping...
Folder 'GCA_005215005.1_PDT000490983.1' already exists. Skipping...
Folder 'GCA_005215045.1_PDT000220761.2' already exists. Skipping...
Folder 'GCA_005215285.1_PDT000245337.2' already exists. Skipping...
Folder 'GCA_005215305.1_PDT000244824.2' already exists. Skipping...
Folder 'GCA_005215325.1_PDT000199136.2' already exists. Skipping...
Folder 'GCA_005215345.1_PDT000175414.2' already exists. Skipping...
Folder 'GCA_005215405.1_PDT000224963.2' already exists. Skipping...
Folder 'GCA_005215425.1_PDT000201969.2' already exists. Skipping...
Folder 'GCA_005215465.1_PDT000219380.2' already exists. Skipping...
Folder 'GCA_005215515.1_PDT000172077.3' already exists. Skipping...
Folder 'GCA_005215665.1_PDT000224965.2' already exists. Skipping...
Folder 'GCA_005215685.1_PDT000220800.2' already exists. Skipping...
Folder 'GCA_005215725.1_PDT000250559.2' already exists. Skipping...
Folder 'GCA_005215745.1_PDT000203813.2' already exists. Skipping...
Folder 'GCA_005215765.1_PDT000244821.2' already exists. Skipping...
Folder 'GCA_005215805.1_PDT000259559.2' already exists. Skipping...
Folder 'GCA_005215885.1_PDT000491671.1' already exists. Skipping...
Folder 'GCA_005215925.1_PDT000492004.1' already exists. Skipping...
Folder 'GCA_005215965.1_PDT000494400.1' already exists. Skipping...
Folder 'GCA_005215985.1_PDT000491360.1' already exists. Skipping...
Folder 'GCA_005216165.1_PDT000219242.2' already exists. Skipping...
Folder 'GCA_005216305.1_PDT000494466.1' already exists. Skipping...
Folder 'GCA_005216345.1_PDT000489257.1' already exists. Skipping...
Folder 'GCA_005216445.1_PDT000490985.1' already exists. Skipping...
Folder 'GCA_005216625.1_PDT000491345.1' already exists. Skipping...
Folder 'GCA_005216665.1_PDT000491657.1' already exists. Skipping...
Folder 'GCA_005216805.1_PDT000496145.1' already exists. Skipping...
Folder 'GCA_005216885.1_PDT000495108.1' already exists. Skipping...
Folder 'GCA_005216925.1_PDT000495161.1' already exists. Skipping...
Folder 'GCA_005216945.1_PDT000495110.1' already exists. Skipping...
Folder 'GCA_005217005.1_PDT000495313.1' already exists. Skipping...
Folder 'GCA_005217035.1_PDT000495163.1' already exists. Skipping...
Folder 'GCA_005217065.1_PDT000495278.1' already exists. Skipping...
Folder 'GCA_005217085.1_PDT000495357.1' already exists. Skipping...
Folder 'GCA_005217965.1_PDT000473032.2' already exists. Skipping...
Folder 'GCA_005217985.1_PDT000473112.2' already exists. Skipping...
Folder 'GCA_005218025.1_PDT000468639.2' already exists. Skipping...
Folder 'GCA_005218045.1_PDT000472964.2' already exists. Skipping...
Folder 'GCA_005218125.1_PDT000472944.2' already exists. Skipping...
Folder 'GCA_005218145.1_PDT000473129.2' already exists. Skipping...
Folder 'GCA_005218205.1_PDT000495295.1' already exists. Skipping...
Folder 'GCA_005218325.1_PDT000495253.1' already exists. Skipping...
Folder 'GCA_005218385.1_PDT000495840.1' already exists. Skipping...
Folder 'GCA_005218465.1_PDT000495865.1' already exists. Skipping...
Folder 'GCA_005218485.1_PDT000496105.1' already exists. Skipping...
Folder 'GCA_005218545.1_PDT000496129.1' already exists. Skipping...
Folder 'GCA_005218565.1_PDT000496142.1' already exists. Skipping...
Folder 'GCA_005218585.1_PDT000494892.1' already exists. Skipping...
Folder 'GCA_005218605.1_PDT000496126.1' already exists. Skipping...
Folder 'GCA_005218625.1_PDT000494908.1' already exists. Skipping...
Folder 'GCA_005218665.1_PDT000494301.1' already exists. Skipping...
Folder 'GCA_005218765.1_PDT000489288.1' already exists. Skipping...
Folder 'GCA_005218785.1_PDT000494317.1' already exists. Skipping...
Folder 'GCA_005218825.1_PDT000495273.1' already exists. Skipping...
Folder 'GCA_005218865.1_PDT000495263.1' already exists. Skipping...
Folder 'GCA_005218885.1_PDT000495262.1' already exists. Skipping...
Folder 'GCA_005218905.1_PDT000489294.1' already exists. Skipping...
Folder 'GCA_005218945.1_PDT000494321.1' already exists. Skipping...
Folder 'GCA_005219005.1_PDT000494309.1' already exists. Skipping...
Folder 'GCA_005219025.1_PDT000489273.1' already exists. Skipping...
Folder 'GCA_005219065.1_PDT000490274.1' already exists. Skipping...

Retreiveing data: 9439it [00:02, 6507.78it/s]

Folder 'GCA_005311525.1_PDT000333818.1' already exists. Skipping...
Folder 'GCA_005311595.1_PDT000333106.1' already exists. Skipping...
Folder 'GCA_005311685.1_PDT000332591.1' already exists. Skipping...
Folder 'GCA_005311725.1_PDT000332590.1' already exists. Skipping...
Folder 'GCA_005311745.1_PDT000333876.1' already exists. Skipping...
Folder 'GCA_005311825.1_PDT000332611.1' already exists. Skipping...
Folder 'GCA_005311865.1_PDT000332582.1' already exists. Skipping...
Folder 'GCA_005311885.1_PDT000332605.1' already exists. Skipping...
Folder 'GCA_005311925.1_PDT000332613.1' already exists. Skipping...
Folder 'GCA_005312005.1_PDT000332616.1' already exists. Skipping...
Folder 'GCA_005312105.1_PDT000332614.1' already exists. Skipping...
Folder 'GCA_005312145.1_PDT000332618.1' already exists. Skipping...
Folder 'GCA_005312165.1_PDT000332609.1' already exists. Skipping...
Folder 'GCA_005312185.1_PDT000332592.1' already exists. Skipping...
Folder 'GCA_005312205.1_PDT000333822.1' already exists. Skipping...
Folder 'GCA_005312225.1_PDT000333879.1' already exists. Skipping...
Folder 'GCA_005312285.1_PDT000332602.1' already exists. Skipping...
Folder 'GCA_005312305.1_PDT000332610.1' already exists. Skipping...
Folder 'GCA_005312365.1_PDT000333823.1' already exists. Skipping...
Folder 'GCA_005312405.1_PDT000332623.1' already exists. Skipping...
Folder 'GCA_005312425.1_PDT000332626.1' already exists. Skipping...
Folder 'GCA_005312505.1_PDT000332624.1' already exists. Skipping...
Folder 'GCA_005312525.1_PDT000332631.1' already exists. Skipping...
Folder 'GCA_005312545.1_PDT000332627.1' already exists. Skipping...
Folder 'GCA_005312605.1_PDT000332634.1' already exists. Skipping...
Folder 'GCA_005312645.1_PDT000333800.1' already exists. Skipping...
Folder 'GCA_005312925.1_PDT000333665.1' already exists. Skipping...
Folder 'GCA_005313025.1_PDT000333666.1' already exists. Skipping...
Folder 'GCA_005313145.1_PDT000333802.1' already exists. Skipping...
Folder 'GCA_005313225.1_PDT000333803.1' already exists. Skipping...
Folder 'GCA_005313245.1_PDT000333804.1' already exists. Skipping...
Folder 'GCA_005313305.1_PDT000333809.1' already exists. Skipping...
Folder 'GCA_005313325.1_PDT000333807.1' already exists. Skipping...
Folder 'GCA_005313345.1_PDT000333814.1' already exists. Skipping...
Folder 'GCA_005313385.1_PDT000333828.1' already exists. Skipping...
Folder 'GCA_005313425.1_PDT000333834.1' already exists. Skipping...
Folder 'GCA_005313445.1_PDT000333832.1' already exists. Skipping...
Folder 'GCA_005313505.1_PDT000333829.1' already exists. Skipping...
Folder 'GCA_005313525.1_PDT000333838.1' already exists. Skipping...
Folder 'GCA_005313585.1_PDT000333837.1' already exists. Skipping...
Folder 'GCA_005313625.1_PDT000333842.1' already exists. Skipping...
Folder 'GCA_005313645.1_PDT000333858.1' already exists. Skipping...
Folder 'GCA_005313665.1_PDT000333851.1' already exists. Skipping...
Folder 'GCA_005313745.1_PDT000333867.1' already exists. Skipping...
Folder 'GCA_005313765.1_PDT000333868.1' already exists. Skipping...
Folder 'GCA_005314045.1_PDT000333886.1' already exists. Skipping...
Folder 'GCA_005314065.1_PDT000333889.1' already exists. Skipping...
Folder 'GCA_005314125.1_PDT000333892.1' already exists. Skipping...
Folder 'GCA_005314185.1_PDT000333893.1' already exists. Skipping...
Folder 'GCA_005314205.1_PDT000333894.1' already exists. Skipping...
Folder 'GCA_005314265.1_PDT000333898.1' already exists. Skipping...
Folder 'GCA_005314345.1_PDT000333841.1' already exists. Skipping...
Folder 'GCA_005314385.1_PDT000333844.1' already exists. Skipping...
Folder 'GCA_005314405.1_PDT000333843.1' already exists. Skipping...
Folder 'GCA_005314545.1_PDT000333826.1' already exists. Skipping...
Folder 'GCA_005314605.1_PDT000333815.1' already exists. Skipping...
Folder 'GCA_005314625.1_PDT000333830.1' already exists. Skipping...
Folder 'GCA_005314645.1_PDT000333810.1' already exists. Skipping...
Folder 'GCA_005314705.1_PDT000333813.1' already exists. Skipping...
Folder 'GCA_005315025.1_PDT000065195.4' already exists. Skipping...
Folder 'GCA_005315265.1_PDT000067209.4' already exists. Skipping...
Folder 'GCA_005315345.1_PDT000067210.4' already exists. Skipping...
Folder 'GCA_005315465.1_PDT000067771.4' already exists. Skipping...
Folder 'GCA_005315525.4_PDT000069304.8' already exists. Skipping...
Folder 'GCA_005316185.1_PDT000336848.1' already exists. Skipping...
Folder 'GCA_005316205.1_PDT000336847.1' already exists. Skipping...
Folder 'GCA_005316385.1_PDT000337167.1' already exists. Skipping...
Folder 'GCA_005316425.1_PDT000337173.1' already exists. Skipping...
Folder 'GCA_005316445.1_PDT000337169.1' already exists. Skipping...
Folder 'GCA_005316465.1_PDT000337171.1' already exists. Skipping...
Folder 'GCA_005316485.1_PDT000337176.1' already exists. Skipping...
Folder 'GCA_005316505.1_PDT000337170.1' already exists. Skipping...
Folder 'GCA_005316645.1_PDT000337209.1' already exists. Skipping...
Folder 'GCA_005316745.1_PDT000337201.1' already exists. Skipping...
Folder 'GCA_005316765.1_PDT000337202.1' already exists. Skipping...
Folder 'GCA_005316805.1_PDT000337216.1' already exists. Skipping...
Folder 'GCA_005316825.1_PDT000337212.1' already exists. Skipping...
Folder 'GCA_005316865.1_PDT000337200.1' already exists. Skipping...
Folder 'GCA_005316925.1_PDT000337218.1' already exists. Skipping...
Folder 'GCA_005317025.1_PDT000337208.1' already exists. Skipping...
Folder 'GCA_005317065.1_PDT000337214.1' already exists. Skipping...
Folder 'GCA_005317085.1_PDT000337199.1' already exists. Skipping...
Folder 'GCA_005317105.1_PDT000337215.1' already exists. Skipping...
Folder 'GCA_005317145.1_PDT000337909.1' already exists. Skipping...
Folder 'GCA_005317285.1_PDT000337210.1' already exists. Skipping...
Folder 'GCA_005317345.1_PDT000338217.1' already exists. Skipping...
Folder 'GCA_005317465.1_PDT000340560.1' already exists. Skipping...
Folder 'GCA_005317565.1_PDT000338854.1' already exists. Skipping...
Folder 'GCA_005317585.1_PDT000338220.1' already exists. Skipping...
Folder 'GCA_005317605.1_PDT000338872.1' already exists. Skipping...
Folder 'GCA_005317665.1_PDT000338709.1' already exists. Skipping...
Folder 'GCA_005317685.1_PDT000339294.1' already exists. Skipping...
Folder 'GCA_005317825.1_PDT000340562.1' already exists. Skipping...
Folder 'GCA_005317845.1_PDT000338218.1' already exists. Skipping...
Folder 'GCA_005317885.1_PDT000340557.1' already exists. Skipping...
Folder 'GCA_005317965.1_PDT000339265.1' already exists. Skipping...
Folder 'GCA_005317985.1_PDT000339301.1' already exists. Skipping...
Folder 'GCA_005318065.1_PDT000338701.1' already exists. Skipping...
Folder 'GCA_005318105.1_PDT000338866.1' already exists. Skipping...
Folder 'GCA_005318125.1_PDT000339264.1' already exists. Skipping...
Folder 'GCA_005318185.1_PDT000340558.1' already exists. Skipping...
Folder 'GCA_005318205.1_PDT000338704.1' already exists. Skipping...
Folder 'GCA_005318245.1_PDT000338213.1' already exists. Skipping...
Folder 'GCA_005318265.1_PDT000339300.1' already exists. Skipping...
Folder 'GCA_005318365.1_PDT000339267.1' already exists. Skipping...
Folder 'GCA_005318405.1_PDT000338219.1' already exists. Skipping...
Folder 'GCA_005318425.1_PDT000339296.1' already exists. Skipping...
Folder 'GCA_005318505.1_PDT000338384.1' already exists. Skipping...
Folder 'GCA_005318565.1_PDT000339261.1' already exists. Skipping...
Folder 'GCA_005318585.1_PDT000339263.1' already exists. Skipping...
Folder 'GCA_005318605.1_PDT000338909.1' already exists. Skipping...
Folder 'GCA_005318705.1_PDT000338389.1' already exists. Skipping...
Folder 'GCA_005318725.1_PDT000338211.1' already exists. Skipping...
Folder 'GCA_005318745.1_PDT000338214.1' already exists. Skipping...
Folder 'GCA_005318805.1_PDT000339269.1' already exists. Skipping...
Folder 'GCA_005318925.1_PDT000339273.1' already exists. Skipping...
Folder 'GCA_005319005.1_PDT000339278.1' already exists. Skipping...
Folder 'GCA_005319045.1_PDT000339277.1' already exists. Skipping...
Folder 'GCA_005319105.1_PDT000339279.1' already exists. Skipping...
Folder 'GCA_005319165.1_PDT000339280.1' already exists. Skipping...
Folder 'GCA_005319205.1_PDT000339282.1' already exists. Skipping...
Folder 'GCA_005319305.1_PDT000339302.1' already exists. Skipping...
Folder 'GCA_005319345.1_PDT000339310.1' already exists. Skipping...
Folder 'GCA_005319385.1_PDT000339315.1' already exists. Skipping...
Folder 'GCA_005319405.1_PDT000339312.1' already exists. Skipping...
Folder 'GCA_005319425.1_PDT000339316.1' already exists. Skipping...
Folder 'GCA_005319505.1_PDT000339319.1' already exists. Skipping...
Folder 'GCA_005319525.1_PDT000339308.1' already exists. Skipping...
Folder 'GCA_005319585.1_PDT000339306.1' already exists. Skipping...
Folder 'GCA_005319605.1_PDT000339305.1' already exists. Skipping...
Folder 'GCA_005319665.1_PDT000340092.1' already exists. Skipping...
Folder 'GCA_005319685.1_PDT000340091.1' already exists. Skipping...
Folder 'GCA_005319725.1_PDT000340397.1' already exists. Skipping...
Folder 'GCA_005319745.1_PDT000340404.1' already exists. Skipping...
Folder 'GCA_005319765.1_PDT000340093.1' already exists. Skipping...
Folder 'GCA_005319805.1_PDT000340408.1' already exists. Skipping...
Folder 'GCA_005319825.1_PDT000340405.1' already exists. Skipping...
Folder 'GCA_005319845.1_PDT000340409.1' already exists. Skipping...
Folder 'GCA_005320465.1_PDT000340538.1' already exists. Skipping...
Folder 'GCA_005320565.1_PDT000340543.1' already exists. Skipping...
Folder 'GCA_005320585.1_PDT000340541.1' already exists. Skipping...
Folder 'GCA_005320605.1_PDT000340544.1' already exists. Skipping...
Folder 'GCA_005320645.1_PDT000340546.1' already exists. Skipping...
Folder 'GCA_005320665.1_PDT000340548.1' already exists. Skipping...
Folder 'GCA_005320685.1_PDT000340566.1' already exists. Skipping...
Folder 'GCA_005320745.1_PDT000340570.1' already exists. Skipping...
Folder 'GCA_005320805.1_PDT000340552.1' already exists. Skipping...
Folder 'GCA_005320885.1_PDT000340556.1' already exists. Skipping...
Folder 'GCA_005320965.1_PDT000340567.1' already exists. Skipping...
Folder 'GCA_005320985.1_PDT000340555.1' already exists. Skipping...
Folder 'GCA_005321005.1_PDT000340550.1' already exists. Skipping...
Folder 'GCA_005321025.1_PDT000340581.1' already exists. Skipping...
Folder 'GCA_005321095.1_PDT000340579.1' already exists. Skipping...
Folder 'GCA_005321125.1_PDT000340584.1' already exists. Skipping...
Folder 'GCA_005321245.1_PDT000340590.1' already exists. Skipping...
Folder 'GCA_005321305.1_PDT000340593.1' already exists. Skipping...
Folder 'GCA_005321325.1_PDT000340594.1' already exists. Skipping...
Folder 'GCA_005321345.1_PDT000340596.1' already exists. Skipping...
Folder 'GCA_005321385.1_PDT000340597.1' already exists. Skipping...
Folder 'GCA_005321465.1_PDT000340850.1' already exists. Skipping...
Folder 'GCA_005321485.1_PDT000340601.1' already exists. Skipping...
Folder 'GCA_005321505.1_PDT000340787.1' already exists. Skipping...
Folder 'GCA_005321585.1_PDT000339299.1' already exists. Skipping...
Folder 'GCA_005321705.1_PDT000339304.1' already exists. Skipping...
Folder 'GCA_005322045.1_PDT000340970.1' already exists. Skipping...
Folder 'GCA_005322385.1_PDT000341262.1' already exists. Skipping...
Folder 'GCA_005322585.1_PDT000343446.1' already exists. Skipping...
Folder 'GCA_005322615.1_PDT000343415.1' already exists. Skipping...
Folder 'GCA_005322645.1_PDT000343463.1' already exists. Skipping...
Folder 'GCA_005322665.1_PDT000343433.1' already exists. Skipping...
Folder 'GCA_005322685.1_PDT000343461.1' already exists. Skipping...
Folder 'GCA_005322705.1_PDT000341544.1' already exists. Skipping...
Folder 'GCA_005322745.1_PDT000343513.1' already exists. Skipping...
Folder 'GCA_005322755.1_PDT000343591.1' already exists. Skipping...
Folder 'GCA_005322785.1_PDT000343560.1' already exists. Skipping...
Folder 'GCA_005322805.1_PDT000343451.1' already exists. Skipping...
Folder 'GCA_005322825.1_PDT000343512.1' already exists. Skipping...
Folder 'GCA_005322845.1_PDT000343445.1' already exists. Skipping...
Folder 'GCA_005322865.1_PDT000343593.1' already exists. Skipping...
Folder 'GCA_005322885.1_PDT000343430.1' already exists. Skipping...
Folder 'GCA_005322925.1_PDT000343559.1' already exists. Skipping...
Folder 'GCA_005322945.1_PDT000341537.1' already exists. Skipping...
Folder 'GCA_005322965.1_PDT000343550.1' already exists. Skipping...
Folder 'GCA_005322985.1_PDT000343588.1' already exists. Skipping...
Folder 'GCA_005323005.1_PDT000343500.1' already exists. Skipping...
Folder 'GCA_005323025.1_PDT000343412.1' already exists. Skipping...
Folder 'GCA_005323045.1_PDT000343549.1' already exists. Skipping...
Folder 'GCA_005323065.1_PDT000343539.1' already exists. Skipping...
Folder 'GCA_005323085.1_PDT000343533.1' already exists. Skipping...
Folder 'GCA_005323105.1_PDT000343594.1' already exists. Skipping...
Folder 'GCA_005323125.1_PDT000343601.1' already exists. Skipping...
Folder 'GCA_005323145.1_PDT000343414.1' already exists. Skipping...
Folder 'GCA_005323155.1_PDT000343595.1' already exists. Skipping...
Folder 'GCA_005323185.1_PDT000343589.1' already exists. Skipping...
Folder 'GCA_005323205.1_PDT000343515.1' already exists. Skipping...
Folder 'GCA_005323245.1_PDT000343457.1' already exists. Skipping...
Folder 'GCA_005323265.1_PDT000343495.1' already exists. Skipping...
Folder 'GCA_005323285.1_PDT000343443.1' already exists. Skipping...
Folder 'GCA_005323305.1_PDT000343598.1' already exists. Skipping...
Folder 'GCA_005323325.1_PDT000343504.1' already exists. Skipping...
Folder 'GCA_005323345.1_PDT000343605.1' already exists. Skipping...
Folder 'GCA_005323365.1_PDT000343426.1' already exists. Skipping...
Folder 'GCA_005323385.1_PDT000343618.1' already exists. Skipping...
Folder 'GCA_005323405.1_PDT000343617.1' already exists. Skipping...
Folder 'GCA_005323485.1_PDT000343540.1' already exists. Skipping...
Folder 'GCA_005323565.1_PDT000343604.1' already exists. Skipping...
Folder 'GCA_005323585.1_PDT000343599.1' already exists. Skipping...
Folder 'GCA_005323625.1_PDT000343535.1' already exists. Skipping...
Folder 'GCA_005323655.1_PDT000343460.1' already exists. Skipping...
Folder 'GCA_005323675.1_PDT000343739.1' already exists. Skipping...
Folder 'GCA_005323775.1_PDT000343710.1' already exists. Skipping...
Folder 'GCA_005323815.1_PDT000343728.1' already exists. Skipping...
Folder 'GCA_005323835.1_PDT000345383.1' already exists. Skipping...
Folder 'GCA_005323855.1_PDT000343715.1' already exists. Skipping...
Folder 'GCA_005323875.1_PDT000343711.1' already exists. Skipping...
Folder 'GCA_005323895.1_PDT000343719.1' already exists. Skipping...
Folder 'GCA_005323915.1_PDT000343713.1' already exists. Skipping...
Folder 'GCA_005323975.1_PDT000343706.1' already exists. Skipping...
Folder 'GCA_005324055.1_PDT000345334.1' already exists. Skipping...
Folder 'GCA_005324075.1_PDT000343703.1' already exists. Skipping...
Folder 'GCA_005324135.1_PDT000345337.1' already exists. Skipping...
Folder 'GCA_005324255.1_PDT000343705.1' already exists. Skipping...
Folder 'GCA_005324375.1_PDT000343672.1' already exists. Skipping...
Folder 'GCA_005324515.1_PDT000345380.1' already exists. Skipping...
Folder 'GCA_005324595.1_PDT000343733.1' already exists. Skipping...
Folder 'GCA_005324615.1_PDT000343683.1' already exists. Skipping...
Folder 'GCA_005324675.1_PDT000343718.1' already exists. Skipping...
Folder 'GCA_005324745.1_PDT000343702.1' already exists. Skipping...
Folder 'GCA_005324775.1_PDT000343712.1' already exists. Skipping...
Folder 'GCA_005324795.1_PDT000343742.1' already exists. Skipping...
Folder 'GCA_005324855.1_PDT000320158.3' already exists. Skipping...
Folder 'GCA_005324995.1_PDT000344079.1' already exists. Skipping...
Folder 'GCA_005325035.1_PDT000345387.1' already exists. Skipping...
Folder 'GCA_005325055.1_PDT000345386.1' already exists. Skipping...
Folder 'GCA_005325115.1_PDT000343701.1' already exists. Skipping...
Folder 'GCA_005325135.1_PDT000343763.1' already exists. Skipping...
Folder 'GCA_005325195.1_PDT000344093.1' already exists. Skipping...
Folder 'GCA_005325215.1_PDT000344083.1' already exists. Skipping...
Folder 'GCA_005325275.1_PDT000345385.1' already exists. Skipping...
Folder 'GCA_005325295.1_PDT000344096.1' already exists. Skipping...
Folder 'GCA_005325315.1_PDT000345388.1' already exists. Skipping...
Folder 'GCA_005325335.1_PDT000344105.1' already exists. Skipping...
Folder 'GCA_005325455.1_PDT000344120.1' already exists. Skipping...
Folder 'GCA_005325475.1_PDT000344150.1' already exists. Skipping...
Folder 'GCA_005325535.1_PDT000344163.1' already exists. Skipping...
Folder 'GCA_005325555.1_PDT000344114.1' already exists. Skipping...
Folder 'GCA_005325595.1_PDT000344167.1' already exists. Skipping...
Folder 'GCA_005325635.1_PDT000344170.1' already exists. Skipping...
Folder 'GCA_005325655.1_PDT000344158.1' already exists. Skipping...
Folder 'GCA_005325795.1_PDT000345183.1' already exists. Skipping...
Folder 'GCA_005325835.1_PDT000345187.1' already exists. Skipping...
Folder 'GCA_005325875.1_PDT000345188.1' already exists. Skipping...
Folder 'GCA_005325915.1_PDT000345201.1' already exists. Skipping...
Folder 'GCA_005325935.1_PDT000345202.1' already exists. Skipping...
Folder 'GCA_005326085.1_PDT000345340.1' already exists. Skipping...
Folder 'GCA_005326245.1_PDT000345349.1' already exists. Skipping...
Folder 'GCA_005326265.1_PDT000345346.1' already exists. Skipping...
Folder 'GCA_005326365.1_PDT000345350.1' already exists. Skipping...
Folder 'GCA_005326405.1_PDT000345352.1' already exists. Skipping...
Folder 'GCA_005326485.1_PDT000345359.1' already exists. Skipping...
Folder 'GCA_005326565.1_PDT000345365.1' already exists. Skipping...
Folder 'GCA_005326585.1_PDT000345362.1' already exists. Skipping...
Folder 'GCA_005326645.1_PDT000345367.1' already exists. Skipping...
Folder 'GCA_005326685.1_PDT000345366.1' already exists. Skipping...
Folder 'GCA_005326825.1_PDT000345392.1' already exists. Skipping...
Folder 'GCA_005326905.1_PDT000345395.1' already exists. Skipping...
Folder 'GCA_005326925.1_PDT000345377.1' already exists. Skipping...
Folder 'GCA_005326965.1_PDT000345379.1' already exists. Skipping...
Folder 'GCA_005327065.1_PDT000345404.1' already exists. Skipping...
Folder 'GCA_005327105.1_PDT000345407.1' already exists. Skipping...
Folder 'GCA_005327125.1_PDT000345405.1' already exists. Skipping...
Folder 'GCA_005327225.1_PDT000345412.1' already exists. Skipping...
Folder 'GCA_005327265.1_PDT000345410.1' already exists. Skipping...
Folder 'GCA_005327365.1_PDT000344297.1' already exists. Skipping...
Folder 'GCA_005327425.1_PDT000344301.1' already exists. Skipping...
Folder 'GCA_005327465.1_PDT000344295.1' already exists. Skipping...
Folder 'GCA_005327525.1_PDT000344300.1' already exists. Skipping...
Folder 'GCA_005327835.1_PDT000345428.1' already exists. Skipping...
Folder 'GCA_005327875.1_PDT000345432.1' already exists. Skipping...
Folder 'GCA_005327995.1_PDT000345437.1' already exists. Skipping...
Folder 'GCA_005328085.1_PDT000345444.1' already exists. Skipping...
Folder 'GCA_005328195.1_PDT000345447.1' already exists. Skipping...
Folder 'GCA_005328235.1_PDT000345451.1' already exists. Skipping...
Folder 'GCA_005328295.1_PDT000345454.1' already exists. Skipping...
Folder 'GCA_005328355.1_PDT000345458.1' already exists. Skipping...
Folder 'GCA_005328375.1_PDT000345459.1' already exists. Skipping...
Folder 'GCA_005328395.1_PDT000345460.1' already exists. Skipping...
Folder 'GCA_005328475.1_PDT000345468.1' already exists. Skipping...
Folder 'GCA_005328495.1_PDT000345466.1' already exists. Skipping...
Folder 'GCA_005328535.1_PDT000345463.1' already exists. Skipping...
Folder 'GCA_005328555.1_PDT000345467.1' already exists. Skipping...
Folder 'GCA_005328575.1_PDT000345491.1' already exists. Skipping...
Folder 'GCA_005328615.1_PDT000345494.1' already exists. Skipping...
Folder 'GCA_005328635.1_PDT000345497.1' already exists. Skipping...

Retreiveing data: 10785it [00:03, 6617.12it/s]

Folder 'GCA_006358855.1_PDT000522529.1' already exists. Skipping...
Folder 'GCA_006358915.1_PDT000521760.1' already exists. Skipping...
Folder 'GCA_006358935.1_PDT000521822.1' already exists. Skipping...
Folder 'GCA_006358995.1_PDT000521767.1' already exists. Skipping...
Folder 'GCA_006359035.1_PDT000521765.1' already exists. Skipping...
Folder 'GCA_006359075.1_PDT000521774.1' already exists. Skipping...
Folder 'GCA_006359115.1_PDT000521778.1' already exists. Skipping...
Folder 'GCA_006359155.1_PDT000521881.1' already exists. Skipping...
Folder 'GCA_006359195.1_PDT000521862.1' already exists. Skipping...
Folder 'GCA_006359275.1_PDT000521779.1' already exists. Skipping...
Folder 'GCA_006359295.1_PDT000521780.1' already exists. Skipping...
Folder 'GCA_006359315.1_PDT000521783.1' already exists. Skipping...
Folder 'GCA_006359335.1_PDT000521858.1' already exists. Skipping...
Folder 'GCA_006359515.1_PDT000521860.1' already exists. Skipping...
Folder 'GCA_006359565.1_PDT000521863.1' already exists. Skipping...
Folder 'GCA_006359595.1_PDT000521789.1' already exists. Skipping...
Folder 'GCA_006359615.1_PDT000522537.1' already exists. Skipping...
Folder 'GCA_006359655.1_PDT000521968.1' already exists. Skipping...
Folder 'GCA_006359675.1_PDT000521833.1' already exists. Skipping...
Folder 'GCA_006359695.1_PDT000521840.1' already exists. Skipping...
Folder 'GCA_006359755.1_PDT000521875.1' already exists. Skipping...
Folder 'GCA_006359775.1_PDT000521903.1' already exists. Skipping...
Folder 'GCA_006359835.1_PDT000521888.1' already exists. Skipping...
Folder 'GCA_006359875.1_PDT000521838.1' already exists. Skipping...
Folder 'GCA_006359955.1_PDT000521847.1' already exists. Skipping...
Folder 'GCA_006359975.1_PDT000521879.1' already exists. Skipping...
Folder 'GCA_006360035.1_PDT000521787.1' already exists. Skipping...
Folder 'GCA_006360155.1_PDT000521853.1' already exists. Skipping...
Folder 'GCA_006360235.1_PDT000521861.1' already exists. Skipping...
Folder 'GCA_006360295.1_PDT000521889.1' already exists. Skipping...
Folder 'GCA_006360315.1_PDT000521866.1' already exists. Skipping...
Folder 'GCA_006360335.1_PDT000521843.1' already exists. Skipping...
Folder 'GCA_006360375.1_PDT000521793.1' already exists. Skipping...
Folder 'GCA_006360475.1_PDT000521834.1' already exists. Skipping...
Folder 'GCA_006360495.1_PDT000521801.1' already exists. Skipping...
Folder 'GCA_006360535.1_PDT000521885.1' already exists. Skipping...
Folder 'GCA_006360625.1_PDT000521897.1' already exists. Skipping...
Folder 'GCA_006360695.1_PDT000521855.1' already exists. Skipping...
Folder 'GCA_006360715.1_PDT000521791.1' already exists. Skipping...
Folder 'GCA_006360915.1_PDT000521896.1' already exists. Skipping...
Folder 'GCA_006360935.1_PDT000521818.1' already exists. Skipping...
Folder 'GCA_006360955.1_PDT000521907.1' already exists. Skipping...
Folder 'GCA_006360975.1_PDT000521908.1' already exists. Skipping...
Folder 'GCA_006361015.1_PDT000521941.1' already exists. Skipping...
Folder 'GCA_006361055.1_PDT000521900.1' already exists. Skipping...
Folder 'GCA_006361095.1_PDT000521943.1' already exists. Skipping...
Folder 'GCA_006361115.1_PDT000521942.1' already exists. Skipping...
Folder 'GCA_006361135.1_PDT000521951.1' already exists. Skipping...
Folder 'GCA_006361155.1_PDT000521939.1' already exists. Skipping...
Folder 'GCA_006361175.1_PDT000521948.1' already exists. Skipping...
Folder 'GCA_006361195.1_PDT000521946.1' already exists. Skipping...
Folder 'GCA_006361225.1_PDT000521949.1' already exists. Skipping...
Folder 'GCA_006361255.1_PDT000521958.1' already exists. Skipping...
Folder 'GCA_006361295.1_PDT000521961.1' already exists. Skipping...
Folder 'GCA_006361315.1_PDT000521959.1' already exists. Skipping...
Folder 'GCA_006361335.1_PDT000521974.1' already exists. Skipping...
Folder 'GCA_006361355.1_PDT000521960.1' already exists. Skipping...
Folder 'GCA_006361375.1_PDT000521962.1' already exists. Skipping...
Folder 'GCA_006361455.1_PDT000521950.1' already exists. Skipping...
Folder 'GCA_006361495.1_PDT000521882.1' already exists. Skipping...
Folder 'GCA_006361515.1_PDT000521956.1' already exists. Skipping...
Folder 'GCA_006361595.1_PDT000521901.1' already exists. Skipping...
Folder 'GCA_006361655.1_PDT000521909.1' already exists. Skipping...
Folder 'GCA_006361675.1_PDT000521925.1' already exists. Skipping...
Folder 'GCA_006361715.1_PDT000521910.1' already exists. Skipping...
Folder 'GCA_006361755.1_PDT000521927.1' already exists. Skipping...
Folder 'GCA_006361835.1_PDT000521934.1' already exists. Skipping...
Folder 'GCA_006361855.1_PDT000521931.1' already exists. Skipping...
Folder 'GCA_006361895.1_PDT000521937.1' already exists. Skipping...
Folder 'GCA_006361915.1_PDT000521940.1' already exists. Skipping...
Folder 'GCA_006361955.1_PDT000521938.1' already exists. Skipping...
Folder 'GCA_006362015.1_PDT000521944.1' already exists. Skipping...
Folder 'GCA_006362035.1_PDT000521972.1' already exists. Skipping...
Folder 'GCA_006362055.1_PDT000521977.1' already exists. Skipping...
Folder 'GCA_006362075.1_PDT000521975.1' already exists. Skipping...
Folder 'GCA_006362115.1_PDT000521979.1' already exists. Skipping...
Folder 'GCA_006362155.1_PDT000521978.1' already exists. Skipping...
Folder 'GCA_006362195.1_PDT000521984.1' already exists. Skipping...
Folder 'GCA_006362215.1_PDT000521982.1' already exists. Skipping...
Folder 'GCA_006362235.1_PDT000521992.1' already exists. Skipping...
Folder 'GCA_006362275.1_PDT000521988.1' already exists. Skipping...
Folder 'GCA_006362395.1_PDT000522028.1' already exists. Skipping...
Folder 'GCA_006362415.1_PDT000521994.1' already exists. Skipping...
Folder 'GCA_006362435.1_PDT000522003.1' already exists. Skipping...
Folder 'GCA_006362475.1_PDT000521997.1' already exists. Skipping...
Folder 'GCA_006362515.1_PDT000521999.1' already exists. Skipping...
Folder 'GCA_006362555.1_PDT000521996.1' already exists. Skipping...
Folder 'GCA_006362635.1_PDT000522037.1' already exists. Skipping...
Folder 'GCA_006362655.1_PDT000521995.1' already exists. Skipping...
Folder 'GCA_006362775.1_PDT000522522.1' already exists. Skipping...
Folder 'GCA_006362815.1_PDT000522517.1' already exists. Skipping...
Folder 'GCA_006362895.1_PDT000522541.1' already exists. Skipping...
Folder 'GCA_006362935.1_PDT000522540.1' already exists. Skipping...
Folder 'GCA_006362975.1_PDT000522555.1' already exists. Skipping...
Folder 'GCA_006363035.1_PDT000522562.1' already exists. Skipping...
Folder 'GCA_006363055.1_PDT000522564.1' already exists. Skipping...
Folder 'GCA_006363075.1_PDT000522569.1' already exists. Skipping...
Folder 'GCA_006363095.1_PDT000522559.1' already exists. Skipping...
Folder 'GCA_006363135.1_PDT000522563.1' already exists. Skipping...
Folder 'GCA_006363155.1_PDT000522571.1' already exists. Skipping...
Folder 'GCA_006363175.1_PDT000522565.1' already exists. Skipping...
Folder 'GCA_006363235.1_PDT000522582.1' already exists. Skipping...
Folder 'GCA_006363275.1_PDT000522595.1' already exists. Skipping...
Folder 'GCA_006363315.1_PDT000522586.1' already exists. Skipping...
Folder 'GCA_006363375.1_PDT000522588.1' already exists. Skipping...
Folder 'GCA_006363415.1_PDT000522590.1' already exists. Skipping...
Folder 'GCA_006363495.1_PDT000522594.1' already exists. Skipping...
Folder 'GCA_006363505.1_PDT000522593.1' already exists. Skipping...
Folder 'GCA_006363535.1_PDT000522596.1' already exists. Skipping...
Folder 'GCA_006363715.1_PDT000521867.1' already exists. Skipping...
Folder 'GCA_006363735.1_PDT000521851.1' already exists. Skipping...
Folder 'GCA_006364835.1_PDT000521724.1' already exists. Skipping...
Folder 'GCA_006370305.1_ASM637030v1' already exists. Skipping...
Folder 'GCA_006495775.1_PDT000532215.1' already exists. Skipping...
Folder 'GCA_006495875.1_PDT000532216.1' already exists. Skipping...
Folder 'GCA_006495915.1_PDT000532217.1' already exists. Skipping...
Folder 'GCA_006495935.1_PDT000532220.1' already exists. Skipping...
Folder 'GCA_006495975.1_PDT000532221.1' already exists. Skipping...
Folder 'GCA_006496665.1_PDT000532951.1' already exists. Skipping...
Folder 'GCA_006543645.1_PDT000533094.1' already exists. Skipping...
Folder 'GCA_006543665.1_PDT000533092.1' already exists. Skipping...
Folder 'GCA_006543685.1_PDT000533096.1' already exists. Skipping...
Folder 'GCA_006543725.1_PDT000533093.1' already exists. Skipping...
Folder 'GCA_006543745.1_PDT000533099.1' already exists. Skipping...
Folder 'GCA_006543825.1_PDT000533103.1' already exists. Skipping...
Folder 'GCA_006543845.1_PDT000533112.1' already exists. Skipping...
Folder 'GCA_006543855.1_PDT000533192.1' already exists. Skipping...
Folder 'GCA_006543985.1_PDT000533191.1' already exists. Skipping...
Folder 'GCA_006544145.1_PDT000533120.1' already exists. Skipping...
Folder 'GCA_006544165.1_PDT000533119.1' already exists. Skipping...
Folder 'GCA_006544185.1_PDT000533117.1' already exists. Skipping...
Folder 'GCA_006544265.1_PDT000533213.1' already exists. Skipping...
Folder 'GCA_006544285.1_PDT000533121.1' already exists. Skipping...
Folder 'GCA_006544325.1_PDT000533124.1' already exists. Skipping...
Folder 'GCA_006544345.1_PDT000533122.1' already exists. Skipping...
Folder 'GCA_006544365.1_PDT000533125.1' already exists. Skipping...
Folder 'GCA_006544445.1_PDT000533982.1' already exists. Skipping...
Folder 'GCA_006544465.1_PDT000533129.1' already exists. Skipping...
Folder 'GCA_006544485.1_PDT000533130.1' already exists. Skipping...
Folder 'GCA_006544505.1_PDT000533128.1' already exists. Skipping...
Folder 'GCA_006544565.1_PDT000533133.1' already exists. Skipping...
Folder 'GCA_006544765.1_PDT000533115.1' already exists. Skipping...
Folder 'GCA_006544845.1_PDT000533146.1' already exists. Skipping...
Folder 'GCA_006544865.1_PDT000533134.1' already exists. Skipping...
Folder 'GCA_006544885.1_PDT000533136.1' already exists. Skipping...
Folder 'GCA_006545005.1_PDT000533147.1' already exists. Skipping...
Folder 'GCA_006545085.1_PDT000533157.1' already exists. Skipping...
Folder 'GCA_006545105.1_PDT000533152.1' already exists. Skipping...
Folder 'GCA_006545125.1_PDT000533143.1' already exists. Skipping...
Folder 'GCA_006545185.1_PDT000533153.1' already exists. Skipping...
Folder 'GCA_006545205.1_PDT000533156.1' already exists. Skipping...
Folder 'GCA_006545225.1_PDT000533158.1' already exists. Skipping...
Folder 'GCA_006545365.1_PDT000533277.1' already exists. Skipping...
Folder 'GCA_006545465.1_PDT000533296.1' already exists. Skipping...
Folder 'GCA_006545485.1_PDT000533319.1' already exists. Skipping...
Folder 'GCA_006545555.1_PDT000533315.1' already exists. Skipping...
Folder 'GCA_006545585.1_PDT000533317.1' already exists. Skipping...
Folder 'GCA_006545665.1_PDT000533322.1' already exists. Skipping...
Folder 'GCA_006545685.1_PDT000533324.1' already exists. Skipping...
Folder 'GCA_006545705.1_PDT000533342.1' already exists. Skipping...
Folder 'GCA_006545725.1_PDT000533323.1' already exists. Skipping...
Folder 'GCA_006546325.1_PDT000534846.1' already exists. Skipping...
Folder 'GCA_007447165.1_PDT000537153.1' already exists. Skipping...
Folder 'GCA_007447305.1_PDT000537184.1' already exists. Skipping...
Folder 'GCA_007448725.1_PDT000537149.1' already exists. Skipping...
Folder 'GCA_007449125.1_PDT000537026.1' already exists. Skipping...
Folder 'GCA_007449285.1_PDT000537255.1' already exists. Skipping...
Folder 'GCA_007449645.1_PDT000537297.1' already exists. Skipping...
Folder 'GCA_007449705.1_PDT000537300.1' already exists. Skipping...
Folder 'GCA_007449725.1_PDT000537276.1' already exists. Skipping...
Folder 'GCA_007449745.1_PDT000537277.1' already exists. Skipping...
Folder 'GCA_007449825.1_PDT000537283.1' already exists. Skipping...
Folder 'GCA_007449865.1_PDT000537316.1' already exists. Skipping...
Folder 'GCA_007449925.1_PDT000537320.1' already exists. Skipping...
Folder 'GCA_007449945.1_PDT000537287.1' already exists. Skipping...
Folder 'GCA_007450025.1_PDT000537293.1' already exists. Skipping...
Folder 'GCA_007450045.1_PDT000537318.1' already exists. Skipping...
Folder 'GCA_007450065.1_PDT000537269.1' already exists. Skipping...
Folder 'GCA_007450085.1_PDT000537289.1' already exists. Skipping...
Folder 'GCA_007450225.1_PDT000537298.1' already exists. Skipping...
Folder 'GCA_007450265.1_PDT000537313.1' already exists. Skipping...
Folder 'GCA_007450305.1_PDT000537301.1' already exists. Skipping...
Folder 'GCA_007450405.1_PDT000537330.1' already exists. Skipping...
Folder 'GCA_007450685.1_PDT000537332.1' already exists. Skipping...
Folder 'GCA_007450705.1_PDT000537312.1' already exists. Skipping...
Folder 'GCA_007450825.1_PDT000537331.1' already exists. Skipping...
Folder 'GCA_007450845.1_PDT000537314.1' already exists. Skipping...
Folder 'GCA_007450895.1_PDT000537346.1' already exists. Skipping...
Folder 'GCA_007451005.1_PDT000537347.1' already exists. Skipping...
Folder 'GCA_007451245.1_PDT000537345.1' already exists. Skipping...
Folder 'GCA_007451265.1_PDT000537295.1' already exists. Skipping...
Folder 'GCA_007451325.1_PDT000537329.1' already exists. Skipping...
Folder 'GCA_007451335.1_PDT000537393.1' already exists. Skipping...
Folder 'GCA_007451445.1_PDT000537324.1' already exists. Skipping...
Folder 'GCA_007451505.1_PDT000537323.1' already exists. Skipping...
Folder 'GCA_007452235.1_PDT000538692.1' already exists. Skipping...
Folder 'GCA_007452325.1_PDT000538699.1' already exists. Skipping...
Folder 'GCA_007452385.1_PDT000538698.1' already exists. Skipping...
Folder 'GCA_007452445.1_PDT000538712.1' already exists. Skipping...
Folder 'GCA_007452505.1_PDT000538710.1' already exists. Skipping...
Folder 'GCA_007452525.1_PDT000538703.1' already exists. Skipping...
Folder 'GCA_007452585.1_PDT000538706.1' already exists. Skipping...
Folder 'GCA_007452665.1_PDT000538664.1' already exists. Skipping...
Folder 'GCA_007452685.1_PDT000538727.1' already exists. Skipping...
Folder 'GCA_007452705.1_PDT000538667.1' already exists. Skipping...
Folder 'GCA_007453105.1_PDT000538723.1' already exists. Skipping...
Folder 'GCA_007453165.1_PDT000538873.1' already exists. Skipping...
Folder 'GCA_007453285.1_PDT000538805.1' already exists. Skipping...
Folder 'GCA_007453325.1_PDT000538806.1' already exists. Skipping...
Folder 'GCA_007453465.1_PDT000538693.1' already exists. Skipping...
Folder 'GCA_007453505.1_PDT000538697.1' already exists. Skipping...
Folder 'GCA_007453525.1_PDT000538715.1' already exists. Skipping...
Folder 'GCA_007453545.1_PDT000538702.1' already exists. Skipping...
Folder 'GCA_007453605.1_PDT000538717.1' already exists. Skipping...
Folder 'GCA_007453725.1_PDT000538720.1' already exists. Skipping...
Folder 'GCA_007453825.1_PDT000538735.1' already exists. Skipping...
Folder 'GCA_007453905.1_PDT000538751.1' already exists. Skipping...
Folder 'GCA_007454175.1_PDT000538853.1' already exists. Skipping...
Folder 'GCA_007454195.1_PDT000538776.1' already exists. Skipping...
Folder 'GCA_007454215.1_PDT000538795.1' already exists. Skipping...
Folder 'GCA_007454255.1_PDT000538782.1' already exists. Skipping...
Folder 'GCA_007454295.1_PDT000538783.1' already exists. Skipping...
Folder 'GCA_007454335.1_PDT000538861.1' already exists. Skipping...
Folder 'GCA_007454355.1_PDT000538730.1' already exists. Skipping...
Folder 'GCA_007454395.1_PDT000538792.1' already exists. Skipping...
Folder 'GCA_007454455.1_PDT000538800.1' already exists. Skipping...
Folder 'GCA_007454475.1_PDT000538797.1' already exists. Skipping...
Folder 'GCA_007454595.1_PDT000538871.1' already exists. Skipping...
Folder 'GCA_007454615.1_PDT000538856.1' already exists. Skipping...
Folder 'GCA_007454655.1_PDT000538791.1' already exists. Skipping...
Folder 'GCA_007454675.1_PDT000538866.1' already exists. Skipping...
Folder 'GCA_007454715.1_PDT000538864.1' already exists. Skipping...
Folder 'GCA_007454835.1_PDT000538868.1' already exists. Skipping...
Folder 'GCA_007454895.1_PDT000538872.1' already exists. Skipping...
Folder 'GCA_007454955.1_PDT000538877.1' already exists. Skipping...
Folder 'GCA_007455075.1_PDT000538879.1' already exists. Skipping...
Folder 'GCA_007455215.1_PDT000538788.1' already exists. Skipping...
Folder 'GCA_007455345.1_PDT000539236.1' already exists. Skipping...
Folder 'GCA_007455735.1_PDT000539828.1' already exists. Skipping...
Folder 'GCA_007455835.1_PDT000539341.1' already exists. Skipping...
Folder 'GCA_007455855.1_PDT000539304.1' already exists. Skipping...
Folder 'GCA_007455895.1_PDT000539240.1' already exists. Skipping...
Folder 'GCA_007455915.1_PDT000539933.1' already exists. Skipping...
Folder 'GCA_007456015.1_PDT000539234.1' already exists. Skipping...
Folder 'GCA_007456115.1_PDT000539244.1' already exists. Skipping...
Folder 'GCA_007456195.1_PDT000539255.1' already exists. Skipping...
Folder 'GCA_007456235.1_PDT000539340.1' already exists. Skipping...
Folder 'GCA_007456275.1_PDT000539824.1' already exists. Skipping...
Folder 'GCA_007456355.1_PDT000539825.1' already exists. Skipping...
Folder 'GCA_007456395.1_PDT000539328.1' already exists. Skipping...
Folder 'GCA_007456455.1_PDT000539247.1' already exists. Skipping...
Folder 'GCA_007456515.1_PDT000539334.1' already exists. Skipping...
Folder 'GCA_007456595.1_PDT000539253.1' already exists. Skipping...
Folder 'GCA_007456635.1_PDT000539241.1' already exists. Skipping...
Folder 'GCA_007456675.1_PDT000539264.1' already exists. Skipping...
Folder 'GCA_007456715.1_PDT000539235.1' already exists. Skipping...
Folder 'GCA_007456855.1_PDT000539238.1' already exists. Skipping...
Folder 'GCA_007456885.1_PDT000539327.1' already exists. Skipping...
Folder 'GCA_007456945.1_PDT000539237.1' already exists. Skipping...
Folder 'GCA_007456995.1_PDT000539261.1' already exists. Skipping...
Folder 'GCA_007457065.1_PDT000539242.1' already exists. Skipping...
Folder 'GCA_007457115.1_PDT000539260.1' already exists. Skipping...
Folder 'GCA_007457175.1_PDT000539286.1' already exists. Skipping...
Folder 'GCA_007457235.1_PDT000539239.1' already exists. Skipping...
Folder 'GCA_007457255.1_PDT000539269.1' already exists. Skipping...
Folder 'GCA_007457275.1_PDT000539254.1' already exists. Skipping...
Folder 'GCA_007457295.1_PDT000539322.1' already exists. Skipping...
Folder 'GCA_007457335.1_PDT000539252.1' already exists. Skipping...
Folder 'GCA_007457575.1_PDT000539817.1' already exists. Skipping...
Folder 'GCA_007457655.1_PDT000539818.1' already exists. Skipping...
Folder 'GCA_007457675.1_PDT000539831.1' already exists. Skipping...
Folder 'GCA_007457695.1_PDT000539931.1' already exists. Skipping...
Folder 'GCA_007457815.1_PDT000539806.1' already exists. Skipping...
Folder 'GCA_007457835.1_PDT000539949.1' already exists. Skipping...
Folder 'GCA_007457895.1_PDT000539950.1' already exists. Skipping...
Folder 'GCA_007457905.1_PDT000539875.1' already exists. Skipping...
Folder 'GCA_007458055.1_PDT000539968.1' already exists. Skipping...
Folder 'GCA_007458155.1_PDT000539794.1' already exists. Skipping...
Folder 'GCA_007458175.1_PDT000539797.1' already exists. Skipping...
Folder 'GCA_007458195.1_PDT000539866.1' already exists. Skipping...
Folder 'GCA_007458215.1_PDT000539798.1' already exists. Skipping...
Folder 'GCA_007458465.1_PDT000539954.1' already exists. Skipping...
Folder 'GCA_007458495.1_PDT000540145.1' already exists. Skipping...
Folder 'GCA_007458535.1_PDT000539937.1' already exists. Skipping...
Folder 'GCA_007458635.1_PDT000540126.1' already exists. Skipping...
Folder 'GCA_007458895.1_PDT000541684.1' already exists. Skipping...
Folder 'GCA_007458975.1_PDT000539842.1' already exists. Skipping...
Folder 'GCA_007459055.1_PDT000539944.1' already exists. Skipping...
Folder 'GCA_007459195.1_PDT000539960.1' already exists. Skipping...
Folder 'GCA_007459455.1_PDT000539946.1' already exists. Skipping...
Folder 'GCA_007459535.1_PDT000539953.1' already exists. Skipping...
Folder 'GCA_007459555.1_PDT000540132.1' already exists. Skipping...
Folder 'GCA_007459635.1_PDT000540133.1' already exists. Skipping...
Folder 'GCA_007459655.1_PDT000540136.1' already exists. Skipping...

Retreiveing data: 12134it [00:03, 6666.19it/s]

Folder 'GCA_008250685.1_PDT000573792.1' already exists. Skipping...
Folder 'GCA_008250705.1_PDT000573796.1' already exists. Skipping...
Folder 'GCA_008250845.1_PDT000573816.1' already exists. Skipping...
Folder 'GCA_008250865.1_PDT000573812.1' already exists. Skipping...
Folder 'GCA_008250965.1_PDT000573830.1' already exists. Skipping...
Folder 'GCA_008251125.1_PDT000573846.1' already exists. Skipping...
Folder 'GCA_008251165.1_PDT000573850.1' already exists. Skipping...
Folder 'GCA_008251385.1_PDT000573869.1' already exists. Skipping...
Folder 'GCA_008251465.1_PDT000573881.1' already exists. Skipping...
Folder 'GCA_008251725.1_PDT000573893.1' already exists. Skipping...
Folder 'GCA_008252905.1_PDT000573979.1' already exists. Skipping...
Folder 'GCA_008252965.1_PDT000575716.1' already exists. Skipping...
Folder 'GCA_008253245.1_PDT000573997.1' already exists. Skipping...
Folder 'GCA_008253505.1_PDT000574019.1' already exists. Skipping...
Folder 'GCA_008253645.1_PDT000574056.1' already exists. Skipping...
Folder 'GCA_008253765.1_PDT000574060.1' already exists. Skipping...
Folder 'GCA_008253845.1_PDT000574044.1' already exists. Skipping...
Folder 'GCA_008254025.1_PDT000574049.1' already exists. Skipping...
Folder 'GCA_008254165.1_PDT000574054.1' already exists. Skipping...
Folder 'GCA_008261485.1_PDT000576536.1' already exists. Skipping...
Folder 'GCA_008261545.1_PDT000576583.1' already exists. Skipping...
Folder 'GCA_008261705.1_PDT000576584.1' already exists. Skipping...
Folder 'GCA_008261725.1_PDT000576589.1' already exists. Skipping...
Folder 'GCA_008262265.1_PDT000576600.1' already exists. Skipping...
Folder 'GCA_008262325.1_PDT000576593.1' already exists. Skipping...
Folder 'GCA_008262445.1_PDT000576604.1' already exists. Skipping...
Folder 'GCA_008262465.1_PDT000576601.1' already exists. Skipping...
Folder 'GCA_008262545.1_PDT000576606.1' already exists. Skipping...
Folder 'GCA_008262565.1_PDT000576605.1' already exists. Skipping...
Folder 'GCA_008262625.1_PDT000576615.1' already exists. Skipping...
Folder 'GCA_008262685.1_PDT000576618.1' already exists. Skipping...
Folder 'GCA_008262745.1_PDT000576694.1' already exists. Skipping...
Folder 'GCA_008262805.1_PDT000576617.1' already exists. Skipping...
Folder 'GCA_008262885.1_PDT000576729.1' already exists. Skipping...
Folder 'GCA_008263165.1_PDT000576737.1' already exists. Skipping...
Folder 'GCA_008263175.1_PDT000576738.1' already exists. Skipping...
Folder 'GCA_008263845.1_PDT000576793.1' already exists. Skipping...
Folder 'GCA_008264185.1_PDT000576949.1' already exists. Skipping...
Folder 'GCA_008264325.1_PDT000576948.1' already exists. Skipping...
Folder 'GCA_008264445.1_PDT000576914.1' already exists. Skipping...
Folder 'GCA_008264825.1_PDT000576958.1' already exists. Skipping...
Folder 'GCA_008265205.1_PDT000576906.1' already exists. Skipping...
Folder 'GCA_008265265.1_PDT000576919.1' already exists. Skipping...
Folder 'GCA_008265275.1_PDT000576903.1' already exists. Skipping...
Folder 'GCA_008265405.1_PDT000576934.1' already exists. Skipping...
Folder 'GCA_008267205.1_PDT000576925.1' already exists. Skipping...
Folder 'GCA_008269045.1_PDT000577539.1' already exists. Skipping...
Folder 'GCA_008269065.1_PDT000577541.1' already exists. Skipping...
Folder 'GCA_008275175.1_PDT000574022.1' already exists. Skipping...
Folder 'GCA_008275245.1_PDT000573818.1' already exists. Skipping...
Folder 'GCA_008275285.1_PDT000573808.1' already exists. Skipping...
Folder 'GCA_008275445.1_PDT000573773.1' already exists. Skipping...
Folder 'GCA_008275885.1_PDT000573849.1' already exists. Skipping...
Folder 'GCA_008276185.1_PDT000573896.1' already exists. Skipping...
Folder 'GCA_008276205.1_PDT000573913.1' already exists. Skipping...
Folder 'GCA_008276325.1_PDT000574591.1' already exists. Skipping...
Folder 'GCA_008276345.1_PDT000573947.1' already exists. Skipping...
Folder 'GCA_008276425.1_PDT000573972.1' already exists. Skipping...
Folder 'GCA_008276685.1_PDT000574023.1' already exists. Skipping...
Folder 'GCA_008276755.1_PDT000574134.1' already exists. Skipping...
Folder 'GCA_008277045.1_PDT000574490.1' already exists. Skipping...
Folder 'GCA_008277165.1_PDT000574140.1' already exists. Skipping...
Folder 'GCA_008277325.1_PDT000574151.1' already exists. Skipping...
Folder 'GCA_008277665.1_PDT000574582.1' already exists. Skipping...
Folder 'GCA_008277915.1_PDT000574492.1' already exists. Skipping...
Folder 'GCA_008278005.1_PDT000574599.1' already exists. Skipping...
Folder 'GCA_008278015.1_PDT000574575.1' already exists. Skipping...
Folder 'GCA_008278425.1_PDT000574596.1' already exists. Skipping...
Folder 'GCA_008278505.1_PDT000574631.1' already exists. Skipping...
Folder 'GCA_008278605.1_PDT000574618.1' already exists. Skipping...
Folder 'GCA_008278705.1_PDT000574619.1' already exists. Skipping...
Folder 'GCA_008278965.1_PDT000574639.1' already exists. Skipping...
Folder 'GCA_008279105.1_PDT000574645.1' already exists. Skipping...
Folder 'GCA_008279205.1_PDT000574648.1' already exists. Skipping...
Folder 'GCA_008279215.1_PDT000574627.1' already exists. Skipping...
Folder 'GCA_008279245.1_PDT000574650.1' already exists. Skipping...
Folder 'GCA_008279445.1_PDT000574666.1' already exists. Skipping...
Folder 'GCA_008279485.1_PDT000574663.1' already exists. Skipping...
Folder 'GCA_008279525.1_PDT000574687.1' already exists. Skipping...
Folder 'GCA_008279705.1_PDT000574684.1' already exists. Skipping...
Folder 'GCA_008279885.1_PDT000574688.1' already exists. Skipping...
Folder 'GCA_008279895.1_PDT000574682.1' already exists. Skipping...
Folder 'GCA_008279915.1_PDT000574712.1' already exists. Skipping...
Folder 'GCA_008279945.1_PDT000574683.1' already exists. Skipping...
Folder 'GCA_008280065.1_PDT000574695.1' already exists. Skipping...
Folder 'GCA_008280365.1_PDT000574715.1' already exists. Skipping...
Folder 'GCA_008280405.1_PDT000574724.1' already exists. Skipping...
Folder 'GCA_008280425.1_PDT000574719.1' already exists. Skipping...
Folder 'GCA_008280525.1_PDT000574723.1' already exists. Skipping...
Folder 'GCA_008280565.1_PDT000574702.1' already exists. Skipping...
Folder 'GCA_008280685.1_PDT000574760.1' already exists. Skipping...
Folder 'GCA_008280805.1_PDT000574768.1' already exists. Skipping...
Folder 'GCA_008281195.1_PDT000574753.1' already exists. Skipping...
Folder 'GCA_008281255.1_PDT000573825.1' already exists. Skipping...
Folder 'GCA_008281495.1_PDT000575380.1' already exists. Skipping...
Folder 'GCA_008281935.1_PDT000575371.1' already exists. Skipping...
Folder 'GCA_008282335.1_PDT000574879.1' already exists. Skipping...
Folder 'GCA_008282415.1_PDT000575384.1' already exists. Skipping...
Folder 'GCA_008282475.1_PDT000574857.1' already exists. Skipping...
Folder 'GCA_008282515.1_PDT000574815.1' already exists. Skipping...
Folder 'GCA_008282555.1_PDT000575382.1' already exists. Skipping...
Folder 'GCA_008282575.1_PDT000575510.1' already exists. Skipping...
Folder 'GCA_008282715.1_PDT000574809.1' already exists. Skipping...
Folder 'GCA_008282795.1_PDT000574880.1' already exists. Skipping...
Folder 'GCA_008282875.1_PDT000574726.1' already exists. Skipping...
Folder 'GCA_008283035.1_PDT000575388.1' already exists. Skipping...
Folder 'GCA_008283135.1_PDT000575394.1' already exists. Skipping...
Folder 'GCA_008283215.1_PDT000575403.1' already exists. Skipping...
Folder 'GCA_008283455.1_PDT000575423.1' already exists. Skipping...
Folder 'GCA_008283495.1_PDT000575385.1' already exists. Skipping...
Folder 'GCA_008283615.1_PDT000575460.1' already exists. Skipping...
Folder 'GCA_008283875.1_PDT000575468.1' already exists. Skipping...
Folder 'GCA_008283895.1_PDT000575446.1' already exists. Skipping...
Folder 'GCA_008283935.1_PDT000575445.1' already exists. Skipping...
Folder 'GCA_008283995.1_PDT000575444.1' already exists. Skipping...
Folder 'GCA_008284045.1_PDT000575417.1' already exists. Skipping...
Folder 'GCA_008284115.1_PDT000575480.1' already exists. Skipping...
Folder 'GCA_008284195.1_PDT000575466.1' already exists. Skipping...
Folder 'GCA_008284295.1_PDT000575467.1' already exists. Skipping...
Folder 'GCA_008284515.1_PDT000575507.1' already exists. Skipping...
Folder 'GCA_008284635.1_PDT000575479.1' already exists. Skipping...
Folder 'GCA_008284995.1_PDT000575513.1' already exists. Skipping...
Folder 'GCA_008285035.1_PDT000575543.1' already exists. Skipping...
Folder 'GCA_008285195.1_PDT000576240.1' already exists. Skipping...
Folder 'GCA_008285275.1_PDT000575698.1' already exists. Skipping...
Folder 'GCA_008286095.1_PDT000575699.1' already exists. Skipping...
Folder 'GCA_008286315.1_PDT000575551.1' already exists. Skipping...
Folder 'GCA_008286375.1_PDT000575542.1' already exists. Skipping...
Folder 'GCA_008286495.1_PDT000576272.1' already exists. Skipping...
Folder 'GCA_008286555.1_PDT000576339.1' already exists. Skipping...
Folder 'GCA_008286735.1_PDT000576234.1' already exists. Skipping...
Folder 'GCA_008287035.1_PDT000576309.1' already exists. Skipping...
Folder 'GCA_008287315.1_PDT000576382.1' already exists. Skipping...
Folder 'GCA_008287355.1_PDT000576269.1' already exists. Skipping...
Folder 'GCA_008287435.1_PDT000576233.1' already exists. Skipping...
Folder 'GCA_008287535.1_PDT000575547.1' already exists. Skipping...
Folder 'GCA_008287575.1_PDT000575561.1' already exists. Skipping...
Folder 'GCA_008287815.1_PDT000575574.1' already exists. Skipping...
Folder 'GCA_008288195.1_PDT000576331.1' already exists. Skipping...
Folder 'GCA_008288275.1_PDT000576335.1' already exists. Skipping...
Folder 'GCA_008288335.1_PDT000576266.1' already exists. Skipping...
Folder 'GCA_008288375.1_PDT000576385.1' already exists. Skipping...
Folder 'GCA_008288435.1_PDT000576325.1' already exists. Skipping...
Folder 'GCA_008289295.1_PDT000574832.1' already exists. Skipping...
Folder 'GCA_008289375.1_PDT000574824.1' already exists. Skipping...
Folder 'GCA_008289535.1_PDT000574794.1' already exists. Skipping...
Folder 'GCA_008289615.1_PDT000574833.1' already exists. Skipping...
Folder 'GCA_008289635.1_PDT000574797.1' already exists. Skipping...
Folder 'GCA_008289915.1_PDT000575399.1' already exists. Skipping...
Folder 'GCA_008290115.1_PDT000574837.1' already exists. Skipping...
Folder 'GCA_008290195.1_PDT000574800.1' already exists. Skipping...
Folder 'GCA_008290255.1_PDT000575408.1' already exists. Skipping...
Folder 'GCA_008290355.1_PDT000574791.1' already exists. Skipping...
Folder 'GCA_008290475.1_PDT000574798.1' already exists. Skipping...
Folder 'GCA_008290875.1_PDT000574889.1' already exists. Skipping...
Folder 'GCA_008290995.1_PDT000575526.1' already exists. Skipping...
Folder 'GCA_008291035.1_PDT000575563.1' already exists. Skipping...
Folder 'GCA_008291075.1_PDT000575525.1' already exists. Skipping...
Folder 'GCA_008291315.1_PDT000575539.1' already exists. Skipping...
Folder 'GCA_008291335.1_PDT000575537.1' already exists. Skipping...
Folder 'GCA_008291595.1_PDT000576416.1' already exists. Skipping...
Folder 'GCA_008291795.1_PDT000576286.1' already exists. Skipping...
Folder 'GCA_008291815.1_PDT000576273.1' already exists. Skipping...
Folder 'GCA_008292035.1_PDT000576381.1' already exists. Skipping...
Folder 'GCA_008292115.1_PDT000576351.1' already exists. Skipping...
Folder 'GCA_008292215.1_PDT000576320.1' already exists. Skipping...
Folder 'GCA_008292275.1_PDT000576299.1' already exists. Skipping...
Folder 'GCA_008292515.1_PDT000576372.1' already exists. Skipping...
Folder 'GCA_008292735.1_PDT000576378.1' already exists. Skipping...
Folder 'GCA_008292755.1_PDT000576376.1' already exists. Skipping...
Folder 'GCA_008293615.1_PDT000576452.1' already exists. Skipping...
Folder 'GCA_008293655.1_PDT000576445.1' already exists. Skipping...
Folder 'GCA_008293775.1_PDT000576519.1' already exists. Skipping...
Folder 'GCA_008294035.1_PDT000576489.1' already exists. Skipping...
Folder 'GCA_008294455.1_PDT000576479.1' already exists. Skipping...
Folder 'GCA_008294775.1_PDT000576555.1' already exists. Skipping...
Folder 'GCA_008294815.1_PDT000576571.1' already exists. Skipping...
Folder 'GCA_008294935.1_PDT000576500.1' already exists. Skipping...
Folder 'GCA_008295035.1_PDT000576442.1' already exists. Skipping...
Folder 'GCA_008295175.1_PDT000577069.1' already exists. Skipping...
Folder 'GCA_008295315.1_PDT000576542.1' already exists. Skipping...
Folder 'GCA_008295415.1_PDT000576989.1' already exists. Skipping...
Folder 'GCA_008295575.1_PDT000577090.1' already exists. Skipping...
Folder 'GCA_008295975.1_PDT000576990.1' already exists. Skipping...
Folder 'GCA_008295995.1_PDT000577068.1' already exists. Skipping...
Folder 'GCA_008296115.1_PDT000577105.1' already exists. Skipping...
Folder 'GCA_008296135.1_PDT000577077.1' already exists. Skipping...
Folder 'GCA_008296155.1_PDT000577121.1' already exists. Skipping...
Folder 'GCA_008296215.1_PDT000577114.1' already exists. Skipping...
Folder 'GCA_008296395.1_PDT000577058.1' already exists. Skipping...
Folder 'GCA_008296615.1_PDT000577131.1' already exists. Skipping...
Folder 'GCA_008296655.1_PDT000577149.1' already exists. Skipping...
Folder 'GCA_008296815.1_PDT000577137.1' already exists. Skipping...
Folder 'GCA_008296895.1_PDT000577148.1' already exists. Skipping...
Folder 'GCA_008297155.1_PDT000577111.1' already exists. Skipping...
Folder 'GCA_008297175.1_PDT000577173.1' already exists. Skipping...
Folder 'GCA_008297275.1_PDT000577174.1' already exists. Skipping...
Folder 'GCA_008298085.1_PDT000579186.1' already exists. Skipping...
Folder 'GCA_008298765.1_PDT000579177.1' already exists. Skipping...
Folder 'GCA_008298825.1_PDT000579152.1' already exists. Skipping...
Folder 'GCA_008299185.1_PDT000579202.1' already exists. Skipping...
Folder 'GCA_008299385.1_PDT000579171.1' already exists. Skipping...
Folder 'GCA_008299625.1_PDT000579168.1' already exists. Skipping...
Folder 'GCA_008300025.1_PDT000579339.1' already exists. Skipping...
Folder 'GCA_008300145.1_PDT000579321.1' already exists. Skipping...
Folder 'GCA_008300225.1_PDT000579341.1' already exists. Skipping...
Folder 'GCA_008300285.1_PDT000579345.1' already exists. Skipping...
Folder 'GCA_008300325.1_PDT000579327.1' already exists. Skipping...
Folder 'GCA_008300725.1_PDT000579334.1' already exists. Skipping...
Folder 'GCA_008301485.1_PDT000579344.1' already exists. Skipping...
Folder 'GCA_008301645.1_PDT000579336.1' already exists. Skipping...
Folder 'GCA_008301785.1_PDT000579352.1' already exists. Skipping...
Folder 'GCA_008301805.1_PDT000579318.1' already exists. Skipping...
Folder 'GCA_008303785.1_PDT000579498.1' already exists. Skipping...
Folder 'GCA_008304735.1_PDT000577157.1' already exists. Skipping...
Folder 'GCA_008304755.1_PDT000577181.1' already exists. Skipping...
Folder 'GCA_008304955.1_PDT000577228.1' already exists. Skipping...
Folder 'GCA_008305035.1_PDT000577235.1' already exists. Skipping...
Folder 'GCA_008305375.1_PDT000577248.1' already exists. Skipping...
Folder 'GCA_008305475.1_PDT000577253.1' already exists. Skipping...
Folder 'GCA_008305595.1_PDT000577170.1' already exists. Skipping...
Folder 'GCA_008305615.1_PDT000577172.1' already exists. Skipping...
Folder 'GCA_008305625.1_PDT000577180.1' already exists. Skipping...
Folder 'GCA_008305675.1_PDT000577182.1' already exists. Skipping...
Folder 'GCA_008306265.1_PDT000577196.1' already exists. Skipping...
Folder 'GCA_008306735.1_PDT000577269.1' already exists. Skipping...
Folder 'GCA_008307295.1_PDT000577220.1' already exists. Skipping...
Folder 'GCA_008307435.1_PDT000577329.1' already exists. Skipping...
Folder 'GCA_008308005.1_PDT000577279.1' already exists. Skipping...
Folder 'GCA_008308035.1_PDT000577278.1' already exists. Skipping...
Folder 'GCA_008308055.1_PDT000577287.1' already exists. Skipping...
Folder 'GCA_008308255.1_PDT000578449.1' already exists. Skipping...
Folder 'GCA_008308275.1_PDT000577298.1' already exists. Skipping...
Folder 'GCA_008308305.1_PDT000577301.1' already exists. Skipping...
Folder 'GCA_008308375.1_PDT000577305.1' already exists. Skipping...
Folder 'GCA_008308695.1_PDT000577332.1' already exists. Skipping...
Folder 'GCA_008309735.1_PDT000577558.1' already exists. Skipping...
Folder 'GCA_008309795.1_PDT000577561.1' already exists. Skipping...
Folder 'GCA_008309815.1_PDT000577560.1' already exists. Skipping...
Folder 'GCA_008309835.1_PDT000577562.1' already exists. Skipping...
Folder 'GCA_008309915.1_PDT000577567.1' already exists. Skipping...
Folder 'GCA_008310255.1_PDT000578388.1' already exists. Skipping...
Folder 'GCA_008310335.1_PDT000578396.1' already exists. Skipping...
Folder 'GCA_008310415.1_PDT000578401.1' already exists. Skipping...
Folder 'GCA_008310555.1_PDT000578413.1' already exists. Skipping...
Folder 'GCA_008310575.1_PDT000578414.1' already exists. Skipping...
Folder 'GCA_008310715.1_PDT000578430.1' already exists. Skipping...
Folder 'GCA_008310995.1_PDT000577334.1' already exists. Skipping...
Folder 'GCA_008311195.1_PDT000578489.1' already exists. Skipping...
Folder 'GCA_008311215.1_PDT000578495.1' already exists. Skipping...
Folder 'GCA_008311505.1_PDT000578564.1' already exists. Skipping...
Folder 'GCA_008311615.1_PDT000578600.1' already exists. Skipping...
Folder 'GCA_008311675.1_PDT000577142.1' already exists. Skipping...
Folder 'GCA_008319725.1_PDT000580448.1' already exists. Skipping...
Folder 'GCA_008319905.1_PDT000580434.1' already exists. Skipping...
Folder 'GCA_008319945.1_PDT000580430.1' already exists. Skipping...
Folder 'GCA_008320145.1_PDT000580452.1' already exists. Skipping...
Folder 'GCA_008320155.1_PDT000580458.1' already exists. Skipping...
Folder 'GCA_008320165.1_PDT000580438.1' already exists. Skipping...
Folder 'GCA_008320175.1_PDT000580439.1' already exists. Skipping...
Folder 'GCA_008320245.1_PDT000580453.1' already exists. Skipping...
Folder 'GCA_008320565.1_PDT000580456.1' already exists. Skipping...
Folder 'GCA_008321205.1_PDT000580463.1' already exists. Skipping...
Folder 'GCA_008321325.1_PDT000580462.1' already exists. Skipping...
Folder 'GCA_008321405.1_PDT000580469.1' already exists. Skipping...
Folder 'GCA_008321425.1_PDT000580477.1' already exists. Skipping...
Folder 'GCA_008321445.1_PDT000580474.1' already exists. Skipping...
Folder 'GCA_008321495.1_PDT000580476.1' already exists. Skipping...
Folder 'GCA_008321545.1_PDT000580478.1' already exists. Skipping...
Folder 'GCA_008321705.1_PDT000580750.1' already exists. Skipping...
Folder 'GCA_008321785.1_PDT000580743.1' already exists. Skipping...
Folder 'GCA_008321805.1_PDT000580754.1' already exists. Skipping...
Folder 'GCA_008321825.1_PDT000580779.1' already exists. Skipping...
Folder 'GCA_008321905.1_PDT000580777.1' already exists. Skipping...
Folder 'GCA_008321945.1_PDT000580781.1' already exists. Skipping...
Folder 'GCA_008321965.1_PDT000580783.1' already exists. Skipping...
Folder 'GCA_008322005.1_PDT000580792.1' already exists. Skipping...
Folder 'GCA_008322025.1_PDT000580785.1' already exists. Skipping...
Folder 'GCA_008322045.1_PDT000580787.1' already exists. Skipping...
Folder 'GCA_008322085.1_PDT000580791.1' already exists. Skipping...
Folder 'GCA_008322205.1_PDT000580747.1' already exists. Skipping...
Folder 'GCA_008322245.1_PDT000580746.1' already exists. Skipping...
Folder 'GCA_008322265.1_PDT000580748.1' already exists. Skipping...
Folder 'GCA_008324025.1_PDT000579153.1' already exists. Skipping...
Folder 'GCA_008331045.1_PDT000578418.1' already exists. Skipping...
Folder 'GCA_008331065.1_PDT000578402.1' already exists. Skipping...
Folder 'GCA_008331185.1_PDT000578453.1' already exists. Skipping...
Folder 'GCA_008331225.1_PDT000578530.1' already exists. Skipping...
Folder 'GCA_008331545.1_PDT000578487.1' already exists. Skipping...
Folder 'GCA_008331585.1_PDT000578481.1' already exists. Skipping...
Folder 'GCA_008331645.1_PDT000578491.1' already exists. Skipping...
Folder 'GCA_008332005.1_PDT000578506.1' already exists. Skipping...
Folder 'GCA_008332365.1_PDT000578417.1' already exists. Skipping...
Folder 'GCA_008332425.1_PDT000578531.1' already exists. Skipping...

Retreiveing data: 13479it [00:03, 6695.63it/s]

Folder 'GCA_010202245.1_PDT000565208.1' already exists. Skipping...
Folder 'GCA_010202275.1_PDT000565209.1' already exists. Skipping...
Folder 'GCA_010202295.1_PDT000565201.1' already exists. Skipping...
Folder 'GCA_010202325.1_PDT000565238.1' already exists. Skipping...
Folder 'GCA_010202335.1_PDT000565222.1' already exists. Skipping...
Folder 'GCA_010202365.1_PDT000565340.1' already exists. Skipping...
Folder 'GCA_010202385.1_PDT000565296.1' already exists. Skipping...
Folder 'GCA_010202405.1_PDT000565280.1' already exists. Skipping...
Folder 'GCA_010202415.1_PDT000565254.1' already exists. Skipping...
Folder 'GCA_010202445.1_PDT000564603.1' already exists. Skipping...
Folder 'GCA_010202485.1_PDT000565328.1' already exists. Skipping...
Folder 'GCA_010202505.1_PDT000565346.1' already exists. Skipping...
Folder 'GCA_010202525.1_PDT000565286.1' already exists. Skipping...
Folder 'GCA_010202545.1_PDT000565419.1' already exists. Skipping...
Folder 'GCA_010202565.1_PDT000565306.1' already exists. Skipping...
Folder 'GCA_010202585.1_PDT000565311.1' already exists. Skipping...
Folder 'GCA_010202605.1_PDT000565337.1' already exists. Skipping...
Folder 'GCA_010202625.1_PDT000565403.1' already exists. Skipping...
Folder 'GCA_010202655.1_PDT000565376.1' already exists. Skipping...
Folder 'GCA_010202685.1_PDT000565325.1' already exists. Skipping...
Folder 'GCA_010202705.1_PDT000565379.1' already exists. Skipping...
Folder 'GCA_010202725.1_PDT000565389.1' already exists. Skipping...
Folder 'GCA_010202745.1_PDT000565415.1' already exists. Skipping...
Folder 'GCA_010202765.1_PDT000565404.1' already exists. Skipping...
Folder 'GCA_010202785.1_PDT000565501.1' already exists. Skipping...
Folder 'GCA_010202795.1_PDT000565428.1' already exists. Skipping...
Folder 'GCA_010202825.1_PDT000565491.1' already exists. Skipping...
Folder 'GCA_010202855.1_PDT000565513.1' already exists. Skipping...
Folder 'GCA_010202885.1_PDT000565226.1' already exists. Skipping...
Folder 'GCA_010202905.1_PDT000566812.1' already exists. Skipping...
Folder 'GCA_010202925.1_PDT000565193.1' already exists. Skipping...
Folder 'GCA_010202945.1_PDT000566845.1' already exists. Skipping...
Folder 'GCA_010202965.1_PDT000566847.1' already exists. Skipping...
Folder 'GCA_010202985.1_PDT000566824.1' already exists. Skipping...
Folder 'GCA_010203005.1_PDT000566848.1' already exists. Skipping...
Folder 'GCA_010203025.1_PDT000567054.1' already exists. Skipping...
Folder 'GCA_010203045.1_PDT000567034.1' already exists. Skipping...
Folder 'GCA_010203065.1_PDT000567183.1' already exists. Skipping...
Folder 'GCA_010203085.1_PDT000568272.1' already exists. Skipping...
Folder 'GCA_010203105.1_PDT000568251.1' already exists. Skipping...
Folder 'GCA_010203125.1_PDT000567124.1' already exists. Skipping...
Folder 'GCA_010203145.1_PDT000567098.1' already exists. Skipping...
Folder 'GCA_010203165.1_PDT000567081.1' already exists. Skipping...
Folder 'GCA_010203185.1_PDT000567173.1' already exists. Skipping...
Folder 'GCA_010203205.1_PDT000567200.1' already exists. Skipping...
Folder 'GCA_010203225.1_PDT000567186.1' already exists. Skipping...
Folder 'GCA_010203245.1_PDT000567250.1' already exists. Skipping...
Folder 'GCA_010203265.1_PDT000567227.1' already exists. Skipping...
Folder 'GCA_010203285.1_PDT000567258.1' already exists. Skipping...
Folder 'GCA_010203305.1_PDT000567076.1' already exists. Skipping...
Folder 'GCA_010203325.1_PDT000568299.1' already exists. Skipping...
Folder 'GCA_010203345.1_PDT000567232.1' already exists. Skipping...
Folder 'GCA_010203365.1_PDT000568311.1' already exists. Skipping...
Folder 'GCA_010203385.1_PDT000567405.1' already exists. Skipping...
Folder 'GCA_010203405.1_PDT000566946.1' already exists. Skipping...
Folder 'GCA_010203425.1_PDT000567391.1' already exists. Skipping...
Folder 'GCA_010203445.1_PDT000567438.1' already exists. Skipping...
Folder 'GCA_010203455.1_PDT000567222.1' already exists. Skipping...
Folder 'GCA_010203485.1_PDT000567468.1' already exists. Skipping...
Folder 'GCA_010203505.1_PDT000568342.1' already exists. Skipping...
Folder 'GCA_010203515.1_PDT000566810.1' already exists. Skipping...
Folder 'GCA_010203545.1_PDT000567413.1' already exists. Skipping...
Folder 'GCA_010203565.1_PDT000567517.1' already exists. Skipping...
Folder 'GCA_010203585.1_PDT000567499.1' already exists. Skipping...
Folder 'GCA_010203605.1_PDT000567510.1' already exists. Skipping...
Folder 'GCA_010203625.1_PDT000566953.1' already exists. Skipping...
Folder 'GCA_010203645.1_PDT000567571.1' already exists. Skipping...
Folder 'GCA_010203665.1_PDT000567570.1' already exists. Skipping...
Folder 'GCA_010203685.1_PDT000567625.1' already exists. Skipping...
Folder 'GCA_010203705.1_PDT000567677.1' already exists. Skipping...
Folder 'GCA_010203725.1_PDT000567665.1' already exists. Skipping...
Folder 'GCA_010203755.1_PDT000566809.1' already exists. Skipping...
Folder 'GCA_010203775.1_PDT000567568.1' already exists. Skipping...
Folder 'GCA_010203805.1_PDT000567586.1' already exists. Skipping...
Folder 'GCA_010203825.1_PDT000567508.1' already exists. Skipping...
Folder 'GCA_010203845.1_PDT000567590.1' already exists. Skipping...
Folder 'GCA_010203865.1_PDT000567639.1' already exists. Skipping...
Folder 'GCA_010203885.1_PDT000566820.1' already exists. Skipping...
Folder 'GCA_010203905.1_PDT000568196.1' already exists. Skipping...
Folder 'GCA_010203925.1_PDT000566832.1' already exists. Skipping...
Folder 'GCA_010203945.1_PDT000566827.1' already exists. Skipping...
Folder 'GCA_010203965.1_PDT000566836.1' already exists. Skipping...
Folder 'GCA_010203985.1_PDT000566844.1' already exists. Skipping...
Folder 'GCA_010204005.1_PDT000566818.1' already exists. Skipping...
Folder 'GCA_010204025.1_PDT000568273.1' already exists. Skipping...
Folder 'GCA_010204045.1_PDT000566816.1' already exists. Skipping...
Folder 'GCA_010204065.1_PDT000566831.1' already exists. Skipping...
Folder 'GCA_010204075.1_PDT000566944.1' already exists. Skipping...
Folder 'GCA_010204105.1_PDT000568300.1' already exists. Skipping...
Folder 'GCA_010204125.1_PDT000566942.1' already exists. Skipping...
Folder 'GCA_010204145.1_PDT000567024.1' already exists. Skipping...
Folder 'GCA_010204165.1_PDT000567033.1' already exists. Skipping...
Folder 'GCA_010204185.1_PDT000566840.1' already exists. Skipping...
Folder 'GCA_010204205.1_PDT000566819.1' already exists. Skipping...
Folder 'GCA_010204225.1_PDT000567016.1' already exists. Skipping...
Folder 'GCA_010204245.1_PDT000568189.1' already exists. Skipping...
Folder 'GCA_010204265.1_PDT000567659.1' already exists. Skipping...
Folder 'GCA_010204285.1_PDT000567613.1' already exists. Skipping...
Folder 'GCA_010204305.1_PDT000566825.1' already exists. Skipping...
Folder 'GCA_010204325.1_PDT000567678.1' already exists. Skipping...
Folder 'GCA_010204345.1_PDT000568219.1' already exists. Skipping...
Folder 'GCA_010204365.1_PDT000568412.1' already exists. Skipping...
Folder 'GCA_010204385.1_PDT000568221.1' already exists. Skipping...
Folder 'GCA_010204405.1_PDT000568349.1' already exists. Skipping...
Folder 'GCA_010204425.1_PDT000566834.1' already exists. Skipping...
Folder 'GCA_010204445.1_PDT000568240.1' already exists. Skipping...
Folder 'GCA_010204465.1_PDT000624248.1' already exists. Skipping...
Folder 'GCA_010204485.1_PDT000568422.1' already exists. Skipping...
Folder 'GCA_010204505.1_PDT000568312.1' already exists. Skipping...
Folder 'GCA_010204525.1_PDT000568318.1' already exists. Skipping...
Folder 'GCA_010204545.1_PDT000567007.1' already exists. Skipping...
Folder 'GCA_010204565.1_PDT000567194.1' already exists. Skipping...
Folder 'GCA_010204585.1_PDT000566937.1' already exists. Skipping...
Folder 'GCA_010204605.1_PDT000566830.1' already exists. Skipping...
Folder 'GCA_010204625.1_PDT000567068.1' already exists. Skipping...
Folder 'GCA_010204645.1_PDT000566835.1' already exists. Skipping...
Folder 'GCA_010204665.1_PDT000624628.1' already exists. Skipping...
Folder 'GCA_010204685.1_PDT000624567.1' already exists. Skipping...
Folder 'GCA_010204705.1_PDT000567246.1' already exists. Skipping...
Folder 'GCA_010204725.1_PDT000567114.1' already exists. Skipping...
Folder 'GCA_010204745.1_PDT000566983.1' already exists. Skipping...
Folder 'GCA_010204765.1_PDT000567386.1' already exists. Skipping...
Folder 'GCA_010204785.1_PDT000624636.1' already exists. Skipping...
Folder 'GCA_010204805.1_PDT000567182.1' already exists. Skipping...
Folder 'GCA_010204825.1_PDT000624608.1' already exists. Skipping...
Folder 'GCA_010204845.1_PDT000567390.1' already exists. Skipping...
Folder 'GCA_010204865.1_PDT000567479.1' already exists. Skipping...
Folder 'GCA_010204885.1_PDT000624639.1' already exists. Skipping...
Folder 'GCA_010204905.1_PDT000567515.1' already exists. Skipping...
Folder 'GCA_010204925.1_PDT000567443.1' already exists. Skipping...
Folder 'GCA_010204945.1_PDT000567484.1' already exists. Skipping...
Folder 'GCA_010204955.1_PDT000567671.1' already exists. Skipping...
Folder 'GCA_010204985.1_PDT000567627.1' already exists. Skipping...
Folder 'GCA_010205005.1_PDT000567597.1' already exists. Skipping...
Folder 'GCA_010205025.1_PDT000567581.1' already exists. Skipping...
Folder 'GCA_010205045.1_PDT000568224.1' already exists. Skipping...
Folder 'GCA_010205065.1_PDT000567623.1' already exists. Skipping...
Folder 'GCA_010205085.1_PDT000567029.1' already exists. Skipping...
Folder 'GCA_010205105.1_PDT000567679.1' already exists. Skipping...
Folder 'GCA_010205125.1_PDT000624593.1' already exists. Skipping...
Folder 'GCA_010205145.1_PDT000568359.1' already exists. Skipping...
Folder 'GCA_010205165.1_PDT000568216.1' already exists. Skipping...
Folder 'GCA_010205185.1_PDT000568263.1' already exists. Skipping...
Folder 'GCA_010205205.1_PDT000568332.1' already exists. Skipping...
Folder 'GCA_010205225.1_PDT000568287.1' already exists. Skipping...
Folder 'GCA_010205245.1_PDT000624566.1' already exists. Skipping...
Folder 'GCA_010205265.1_PDT000568456.1' already exists. Skipping...
Folder 'GCA_010205285.1_PDT000568432.1' already exists. Skipping...
Folder 'GCA_010205305.1_PDT000623864.1' already exists. Skipping...
Folder 'GCA_010205325.1_PDT000568429.1' already exists. Skipping...
Folder 'GCA_010205345.1_PDT000624538.1' already exists. Skipping...
Folder 'GCA_010205365.1_PDT000624547.1' already exists. Skipping...
Folder 'GCA_010205385.1_PDT000624555.1' already exists. Skipping...
Folder 'GCA_010205405.1_PDT000624592.1' already exists. Skipping...
Folder 'GCA_010205425.1_PDT000624535.1' already exists. Skipping...
Folder 'GCA_010205435.1_PDT000624571.1' already exists. Skipping...
Folder 'GCA_010205455.1_PDT000624529.1' already exists. Skipping...
Folder 'GCA_010205465.1_PDT000624901.1' already exists. Skipping...
Folder 'GCA_010205475.1_PDT000567231.1' already exists. Skipping...
Folder 'GCA_010205525.1_PDT000624615.1' already exists. Skipping...
Folder 'GCA_010205545.1_PDT000624610.1' already exists. Skipping...
Folder 'GCA_010205565.1_PDT000624575.1' already exists. Skipping...
Folder 'GCA_010205585.1_PDT000624569.1' already exists. Skipping...
Folder 'GCA_010205605.1_PDT000566822.1' already exists. Skipping...
Folder 'GCA_010205625.1_PDT000624558.1' already exists. Skipping...
Folder 'GCA_010205645.1_PDT000624779.1' already exists. Skipping...
Folder 'GCA_010205665.1_PDT000624585.1' already exists. Skipping...
Folder 'GCA_010205685.1_PDT000624561.1' already exists. Skipping...
Folder 'GCA_010205705.1_PDT000566850.1' already exists. Skipping...
Folder 'GCA_010205725.1_PDT000567423.1' already exists. Skipping...
Folder 'GCA_010205735.1_PDT000567239.1' already exists. Skipping...
Folder 'GCA_010205765.1_PDT000624900.1' already exists. Skipping...
Folder 'GCA_010205785.1_PDT000625737.1' already exists. Skipping...
Folder 'GCA_010205805.1_PDT000624616.1' already exists. Skipping...
Folder 'GCA_010205815.1_PDT000567538.1' already exists. Skipping...
Folder 'GCA_010205845.1_PDT000625338.1' already exists. Skipping...
Folder 'GCA_010205865.1_PDT000567580.1' already exists. Skipping...
Folder 'GCA_010205885.1_PDT000625738.1' already exists. Skipping...
Folder 'GCA_010205895.1_PDT000625364.1' already exists. Skipping...
Folder 'GCA_010205905.1_PDT000567603.1' already exists. Skipping...
Folder 'GCA_010205945.1_PDT000625337.1' already exists. Skipping...
Folder 'GCA_010205965.1_PDT000625335.1' already exists. Skipping...
Folder 'GCA_010205985.1_PDT000568213.1' already exists. Skipping...
Folder 'GCA_010205995.1_PDT000567688.1' already exists. Skipping...
Folder 'GCA_010206025.1_PDT000626544.1' already exists. Skipping...
Folder 'GCA_010206045.1_PDT000625340.1' already exists. Skipping...
Folder 'GCA_010206065.1_PDT000626541.1' already exists. Skipping...
Folder 'GCA_010206085.1_PDT000626571.1' already exists. Skipping...
Folder 'GCA_010206105.1_PDT000567149.1' already exists. Skipping...
Folder 'GCA_010206125.1_PDT000568257.1' already exists. Skipping...
Folder 'GCA_010206395.1_PDT000567208.1' already exists. Skipping...
Folder 'GCA_010206445.1_PDT000568184.1' already exists. Skipping...
Folder 'GCA_010206465.1_PDT000568232.1' already exists. Skipping...
Folder 'GCA_010206485.1_PDT000567628.1' already exists. Skipping...
Folder 'GCA_010206505.1_PDT000626603.1' already exists. Skipping...
Folder 'GCA_010206525.1_PDT000568321.1' already exists. Skipping...
Folder 'GCA_010206545.1_PDT000567150.1' already exists. Skipping...
Folder 'GCA_010206565.1_PDT000568338.1' already exists. Skipping...
Folder 'GCA_010206585.1_PDT000567399.1' already exists. Skipping...
Folder 'GCA_010206605.1_PDT000567561.1' already exists. Skipping...
Folder 'GCA_010206625.1_PDT000624525.1' already exists. Skipping...
Folder 'GCA_010206645.1_PDT000624581.1' already exists. Skipping...
Folder 'GCA_010206665.1_PDT000624633.1' already exists. Skipping...
Folder 'GCA_010206685.1_PDT000624629.1' already exists. Skipping...
Folder 'GCA_010206705.1_PDT000627217.1' already exists. Skipping...
Folder 'GCA_010206725.1_PDT000625359.1' already exists. Skipping...
Folder 'GCA_010206745.1_PDT000627014.1' already exists. Skipping...
Folder 'GCA_010206765.1_PDT000624588.1' already exists. Skipping...
Folder 'GCA_010206785.1_PDT000624614.1' already exists. Skipping...
Folder 'GCA_010206805.1_PDT000626535.1' already exists. Skipping...
Folder 'GCA_010206825.1_PDT000625344.1' already exists. Skipping...
Folder 'GCA_010206845.1_PDT000626552.1' already exists. Skipping...
Folder 'GCA_010206865.1_PDT000625334.1' already exists. Skipping...
Folder 'GCA_010206885.1_PDT000566842.1' already exists. Skipping...
Folder 'GCA_010206905.1_PDT000627510.1' already exists. Skipping...
Folder 'GCA_010206945.1_PDT000627495.1' already exists. Skipping...
Folder 'GCA_010206965.1_PDT000627512.1' already exists. Skipping...
Folder 'GCA_010206985.1_PDT000627516.1' already exists. Skipping...
Folder 'GCA_010207105.1_PDT000567035.1' already exists. Skipping...
Folder 'GCA_010207205.1_PDT000567605.1' already exists. Skipping...
Folder 'GCA_010207225.1_PDT000568298.1' already exists. Skipping...
Folder 'GCA_010207305.1_PDT000568446.1' already exists. Skipping...
Folder 'GCA_010207365.1_PDT000626555.1' already exists. Skipping...
Folder 'GCA_010207385.1_PDT000626604.1' already exists. Skipping...
Folder 'GCA_010207405.1_PDT000626574.1' already exists. Skipping...
Folder 'GCA_010207425.1_PDT000626617.1' already exists. Skipping...
Folder 'GCA_010207445.1_PDT000626612.1' already exists. Skipping...
Folder 'GCA_010207465.1_PDT000626561.1' already exists. Skipping...
Folder 'GCA_010207475.1_PDT000626572.1' already exists. Skipping...
Folder 'GCA_010207505.1_PDT000627477.1' already exists. Skipping...
Folder 'GCA_010207525.1_PDT000627490.1' already exists. Skipping...
Folder 'GCA_010207545.1_PDT000627484.1' already exists. Skipping...
Folder 'GCA_010207565.1_PDT000567023.1' already exists. Skipping...
Folder 'GCA_010207585.1_PDT000566813.1' already exists. Skipping...
Folder 'GCA_010207605.1_PDT000624526.1' already exists. Skipping...
Folder 'GCA_010207615.1_PDT000568400.1' already exists. Skipping...
Folder 'GCA_010207645.1_PDT000626595.1' already exists. Skipping...
Folder 'GCA_010207665.1_PDT000568319.1' already exists. Skipping...
Folder 'GCA_010207685.1_PDT000624595.1' already exists. Skipping...
Folder 'GCA_010207705.1_PDT000624552.1' already exists. Skipping...
Folder 'GCA_010207725.1_PDT000624545.1' already exists. Skipping...
Folder 'GCA_010207745.1_PDT000624565.1' already exists. Skipping...
Folder 'GCA_010207765.1_PDT000627472.1' already exists. Skipping...
Folder 'GCA_010207785.1_PDT000624542.1' already exists. Skipping...
Folder 'GCA_010207805.1_PDT000626679.1' already exists. Skipping...
Folder 'GCA_010207825.1_PDT000626591.1' already exists. Skipping...
Folder 'GCA_010207845.1_PDT000624642.1' already exists. Skipping...
Folder 'GCA_010207865.1_PDT000624530.1' already exists. Skipping...
Folder 'GCA_010207885.1_PDT000624570.1' already exists. Skipping...
Folder 'GCA_010207905.1_PDT000624563.1' already exists. Skipping...
Folder 'GCA_010207925.1_PDT000624605.1' already exists. Skipping...
Folder 'GCA_010207945.1_PDT000624572.1' already exists. Skipping...
Folder 'GCA_010207965.1_PDT000624573.1' already exists. Skipping...
Folder 'GCA_010207985.1_PDT000567491.1' already exists. Skipping...
Folder 'GCA_010208015.1_PDT000625239.1' already exists. Skipping...
Folder 'GCA_010208045.1_PDT000624902.1' already exists. Skipping...
Folder 'GCA_010208105.1_PDT000624562.1' already exists. Skipping...
Folder 'GCA_010208145.1_PDT000624602.1' already exists. Skipping...
Folder 'GCA_010208165.1_PDT000624576.1' already exists. Skipping...
Folder 'GCA_010208185.1_PDT000624528.1' already exists. Skipping...
Folder 'GCA_010208205.1_PDT000624578.1' already exists. Skipping...
Folder 'GCA_010208225.1_PDT000626534.1' already exists. Skipping...
Folder 'GCA_010208245.1_PDT000624543.1' already exists. Skipping...
Folder 'GCA_010208265.1_PDT000625333.1' already exists. Skipping...
Folder 'GCA_010208305.1_PDT000626594.1' already exists. Skipping...
Folder 'GCA_010208325.1_PDT000625343.1' already exists. Skipping...
Folder 'GCA_010208365.1_PDT000627500.1' already exists. Skipping...
Folder 'GCA_010208405.1_PDT000625352.1' already exists. Skipping...
Folder 'GCA_010208425.1_PDT000626550.1' already exists. Skipping...
Folder 'GCA_010208445.1_PDT000626568.1' already exists. Skipping...
Folder 'GCA_010208465.1_PDT000626573.1' already exists. Skipping...
Folder 'GCA_010208485.1_PDT000626611.1' already exists. Skipping...
Folder 'GCA_010208495.1_PDT000626565.1' already exists. Skipping...
Folder 'GCA_010208545.1_PDT000626557.1' already exists. Skipping...
Folder 'GCA_010208565.1_PDT000626682.1' already exists. Skipping...
Folder 'GCA_010208605.1_PDT000626593.1' already exists. Skipping...
Folder 'GCA_010208625.1_PDT000626614.1' already exists. Skipping...
Folder 'GCA_010208645.1_PDT000627463.1' already exists. Skipping...
Folder 'GCA_010208665.1_PDT000626619.1' already exists. Skipping...
Folder 'GCA_010208685.1_PDT000626740.1' already exists. Skipping...
Folder 'GCA_010208725.1_PDT000626600.1' already exists. Skipping...
Folder 'GCA_010208745.1_PDT000627483.1' already exists. Skipping...
Folder 'GCA_010208765.1_PDT000627478.1' already exists. Skipping...
Folder 'GCA_010208785.1_PDT000627517.1' already exists. Skipping...
Folder 'GCA_010208805.1_PDT000627444.1' already exists. Skipping...
Folder 'GCA_010208825.1_PDT000626615.1' already exists. Skipping...
Folder 'GCA_010208845.1_PDT000627492.1' already exists. Skipping...
Folder 'GCA_010208865.1_PDT000627513.1' already exists. Skipping...
Folder 'GCA_010208905.1_PDT000627473.1' already exists. Skipping...
Folder 'GCA_010209725.1_PDT000627511.1' already exists. Skipping...
Folder 'GCA_010211835.1_PDT000628488.1' already exists. Skipping...
Folder 'GCA_010211855.1_PDT000628496.1' already exists. Skipping...
Folder 'GCA_010211875.1_PDT000628484.1' already exists. Skipping...
Folder 'GCA_010211895.1_PDT000628508.1' already exists. Skipping...

Retreiveing data: 14828it [00:03, 6703.66it/s]

Folder 'GCA_011500205.1_PDT000706463.1' already exists. Skipping...
Folder 'GCA_011500225.1_PDT000706070.1' already exists. Skipping...
Folder 'GCA_011500245.1_PDT000703675.1' already exists. Skipping...
Folder 'GCA_011500265.1_PDT000706470.1' already exists. Skipping...
Folder 'GCA_011500285.1_PDT000703353.1' already exists. Skipping...
Folder 'GCA_011500305.1_PDT000706065.1' already exists. Skipping...
Folder 'GCA_011500345.1_PDT000706561.1' already exists. Skipping...
Folder 'GCA_011500365.1_PDT000706577.1' already exists. Skipping...
Folder 'GCA_011500385.1_PDT000706466.1' already exists. Skipping...
Folder 'GCA_011500405.1_PDT000706562.1' already exists. Skipping...
Folder 'GCA_011500425.1_PDT000706442.1' already exists. Skipping...
Folder 'GCA_011500445.1_PDT000703676.1' already exists. Skipping...
Folder 'GCA_011500465.1_PDT000706454.1' already exists. Skipping...
Folder 'GCA_011500485.1_PDT000706461.1' already exists. Skipping...
Folder 'GCA_011500525.1_PDT000706327.1' already exists. Skipping...
Folder 'GCA_011500585.1_PDT000706530.1' already exists. Skipping...
Folder 'GCA_011500845.1_PDT000706068.1' already exists. Skipping...
Folder 'GCA_011501065.1_PDT000706080.1' already exists. Skipping...
Folder 'GCA_011501145.1_PDT000706058.1' already exists. Skipping...
Folder 'GCA_011501285.1_PDT000706055.1' already exists. Skipping...
Folder 'GCA_011501665.1_PDT000706079.1' already exists. Skipping...
Folder 'GCA_011510725.1_PDT000708489.1' already exists. Skipping...
Folder 'GCA_011512685.1_PDT000708676.1' already exists. Skipping...
Folder 'GCA_011513465.1_PDT000708585.1' already exists. Skipping...
Folder 'GCA_011513545.1_PDT000708531.1' already exists. Skipping...
Folder 'GCA_011513625.1_PDT000708532.1' already exists. Skipping...
Folder 'GCA_011514205.1_PDT000708590.1' already exists. Skipping...
Folder 'GCA_011646215.1_PDT000687498.1' already exists. Skipping...
Folder 'GCA_011671105.1_PDT000706072.1' already exists. Skipping...
Folder 'GCA_011689915.1_PDT000690332.1' already exists. Skipping...
Folder 'GCA_011689935.1_PDT000690362.1' already exists. Skipping...
Folder 'GCA_011689955.1_PDT000690353.1' already exists. Skipping...
Folder 'GCA_011689975.1_PDT000690338.1' already exists. Skipping...
Folder 'GCA_011689995.1_PDT000690377.1' already exists. Skipping...
Folder 'GCA_011690015.1_PDT000686983.1' already exists. Skipping...
Folder 'GCA_011690035.1_PDT000690038.1' already exists. Skipping...
Folder 'GCA_011690055.1_PDT000690350.1' already exists. Skipping...
Folder 'GCA_011690075.1_PDT000690352.1' already exists. Skipping...
Folder 'GCA_011690115.1_PDT000690333.1' already exists. Skipping...
Folder 'GCA_011690135.1_PDT000690335.1' already exists. Skipping...
Folder 'GCA_011690155.1_PDT000690016.1' already exists. Skipping...
Folder 'GCA_011690195.1_PDT000690344.1' already exists. Skipping...
Folder 'GCA_011690215.1_PDT000690037.1' already exists. Skipping...
Folder 'GCA_011690235.1_PDT000690028.1' already exists. Skipping...
Folder 'GCA_011690255.1_PDT000691120.1' already exists. Skipping...
Folder 'GCA_011690275.1_PDT000691131.1' already exists. Skipping...
Folder 'GCA_011690315.1_PDT000687007.1' already exists. Skipping...
Folder 'GCA_011694855.1_PDT000691134.1' already exists. Skipping...
Folder 'GCA_011694955.1_PDT000688574.1' already exists. Skipping...
Folder 'GCA_011695235.1_PDT000690015.1' already exists. Skipping...
Folder 'GCA_011695455.1_PDT000689930.1' already exists. Skipping...
Folder 'GCA_011695545.1_PDT000686963.1' already exists. Skipping...
Folder 'GCA_011695575.1_PDT000690373.1' already exists. Skipping...
Folder 'GCA_011695595.1_PDT000690378.1' already exists. Skipping...
Folder 'GCA_011695615.1_PDT000686965.1' already exists. Skipping...
Folder 'GCA_011695635.1_PDT000690474.1' already exists. Skipping...
Folder 'GCA_011695645.1_PDT000687006.1' already exists. Skipping...
Folder 'GCA_011695675.1_PDT000690339.1' already exists. Skipping...
Folder 'GCA_011695695.1_PDT000690368.1' already exists. Skipping...
Folder 'GCA_011695715.1_PDT000690477.1' already exists. Skipping...
Folder 'GCA_011695735.1_PDT000690374.1' already exists. Skipping...
Folder 'GCA_011695755.1_PDT000686996.1' already exists. Skipping...
Folder 'GCA_011695775.1_PDT000690376.1' already exists. Skipping...
Folder 'GCA_011695935.1_PDT000686967.1' already exists. Skipping...
Folder 'GCA_011695975.1_PDT000686979.1' already exists. Skipping...
Folder 'GCA_011698795.1_PDT000690025.1' already exists. Skipping...
Folder 'GCA_011699015.1_PDT000690029.1' already exists. Skipping...
Folder 'GCA_011699155.1_PDT000690367.1' already exists. Skipping...
Folder 'GCA_011699175.1_PDT000690336.1' already exists. Skipping...
Folder 'GCA_011699195.1_PDT000690345.1' already exists. Skipping...
Folder 'GCA_011699235.1_PDT000690383.1' already exists. Skipping...
Folder 'GCA_011699255.1_PDT000690371.1' already exists. Skipping...
Folder 'GCA_011699275.1_PDT000690381.1' already exists. Skipping...
Folder 'GCA_011699295.1_PDT000690137.1' already exists. Skipping...
Folder 'GCA_011699315.1_PDT000690348.1' already exists. Skipping...
Folder 'GCA_011699335.1_PDT000690382.1' already exists. Skipping...
Folder 'GCA_011699355.1_PDT000691121.1' already exists. Skipping...
Folder 'GCA_011699375.1_PDT000686973.1' already exists. Skipping...
Folder 'GCA_011699395.1_PDT000690361.1' already exists. Skipping...
Folder 'GCA_011699415.1_PDT000690369.1' already exists. Skipping...
Folder 'GCA_011699435.1_PDT000690347.1' already exists. Skipping...
Folder 'GCA_011699455.1_PDT000690364.1' already exists. Skipping...
Folder 'GCA_011699515.1_PDT000690051.1' already exists. Skipping...
Folder 'GCA_011700635.1_PDT000690330.1' already exists. Skipping...
Folder 'GCA_011700675.1_PDT000690139.1' already exists. Skipping...
Folder 'GCA_011700715.1_PDT000690329.1' already exists. Skipping...
Folder 'GCA_011711715.1_PDT000709693.1' already exists. Skipping...
Folder 'GCA_011711855.1_PDT000709659.1' already exists. Skipping...
Folder 'GCA_011712035.1_PDT000709675.1' already exists. Skipping...
Folder 'GCA_011712075.1_PDT000709685.1' already exists. Skipping...
Folder 'GCA_011712255.1_PDT000709646.1' already exists. Skipping...
Folder 'GCA_011712355.1_PDT000709609.1' already exists. Skipping...
Folder 'GCA_011712395.1_PDT000709605.1' already exists. Skipping...
Folder 'GCA_011712535.1_PDT000709633.1' already exists. Skipping...
Folder 'GCA_011712555.1_PDT000709614.1' already exists. Skipping...
Folder 'GCA_011712615.1_PDT000709651.1' already exists. Skipping...
Folder 'GCA_011712635.1_PDT000709699.1' already exists. Skipping...
Folder 'GCA_011712655.1_PDT000709690.1' already exists. Skipping...
Folder 'GCA_011712695.1_PDT000709644.1' already exists. Skipping...
Folder 'GCA_011712715.1_PDT000709676.1' already exists. Skipping...
Folder 'GCA_011712735.1_PDT000709681.1' already exists. Skipping...
Folder 'GCA_011712755.1_PDT000709648.1' already exists. Skipping...
Folder 'GCA_011712815.1_PDT000709700.1' already exists. Skipping...
Folder 'GCA_011713095.1_PDT000709691.1' already exists. Skipping...
Folder 'GCA_011713215.1_PDT000709652.1' already exists. Skipping...
Folder 'GCA_011713275.1_PDT000709669.1' already exists. Skipping...
Folder 'GCA_011713495.1_PDT000709679.1' already exists. Skipping...
Folder 'GCA_011713515.1_PDT000709613.1' already exists. Skipping...
Folder 'GCA_011713535.1_PDT000709620.1' already exists. Skipping...
Folder 'GCA_011715895.1_PDT000710375.1' already exists. Skipping...
Folder 'GCA_011716035.1_PDT000710407.1' already exists. Skipping...
Folder 'GCA_011716355.1_PDT000710510.1' already exists. Skipping...
Folder 'GCA_011717055.1_PDT000710729.1' already exists. Skipping...
Folder 'GCA_011717875.1_PDT000710731.1' already exists. Skipping...
Folder 'GCA_011717955.1_PDT000710732.1' already exists. Skipping...
Folder 'GCA_011718045.1_PDT000710733.1' already exists. Skipping...
Folder 'GCA_011718595.1_PDT000710728.1' already exists. Skipping...
Folder 'GCA_011718975.1_PDT000710641.1' already exists. Skipping...
Folder 'GCA_011719015.1_PDT000710633.1' already exists. Skipping...
Folder 'GCA_011719055.1_PDT000710638.1' already exists. Skipping...
Folder 'GCA_011719115.1_PDT000710616.1' already exists. Skipping...
Folder 'GCA_011719395.1_PDT000710700.1' already exists. Skipping...
Folder 'GCA_011719455.1_PDT000710629.1' already exists. Skipping...
Folder 'GCA_011719755.1_PDT000710645.1' already exists. Skipping...
Folder 'GCA_011719835.1_PDT000710651.1' already exists. Skipping...
Folder 'GCA_011719855.1_PDT000710632.1' already exists. Skipping...
Folder 'GCA_011719935.1_PDT000710622.1' already exists. Skipping...
Folder 'GCA_011720135.1_PDT000710398.1' already exists. Skipping...
Folder 'GCA_011720195.1_PDT000710406.1' already exists. Skipping...
Folder 'GCA_011720315.1_PDT000710481.1' already exists. Skipping...
Folder 'GCA_011720335.1_PDT000710482.1' already exists. Skipping...
Folder 'GCA_011720355.1_PDT000710401.1' already exists. Skipping...
Folder 'GCA_011720375.1_PDT000710457.1' already exists. Skipping...
Folder 'GCA_011720395.1_PDT000710504.1' already exists. Skipping...
Folder 'GCA_011720475.1_PDT000710473.1' already exists. Skipping...
Folder 'GCA_011720535.1_PDT000710465.1' already exists. Skipping...
Folder 'GCA_011720555.1_PDT000711187.1' already exists. Skipping...
Folder 'GCA_011720595.1_PDT000711203.1' already exists. Skipping...
Folder 'GCA_011720615.1_PDT000710493.1' already exists. Skipping...
Folder 'GCA_011720655.1_PDT000710497.1' already exists. Skipping...
Folder 'GCA_011720675.1_PDT000710511.1' already exists. Skipping...
Folder 'GCA_011720695.1_PDT000710512.1' already exists. Skipping...
Folder 'GCA_011720715.1_PDT000710514.1' already exists. Skipping...
Folder 'GCA_011720755.1_PDT000710508.1' already exists. Skipping...
Folder 'GCA_011720775.1_PDT000711165.1' already exists. Skipping...
Folder 'GCA_011720795.1_PDT000710506.1' already exists. Skipping...
Folder 'GCA_011720815.1_PDT000711125.1' already exists. Skipping...
Folder 'GCA_011720835.1_PDT000711359.1' already exists. Skipping...
Folder 'GCA_011720855.1_PDT000711157.1' already exists. Skipping...
Folder 'GCA_011720875.1_PDT000711334.1' already exists. Skipping...
Folder 'GCA_011720895.1_PDT000711306.1' already exists. Skipping...
Folder 'GCA_011720955.1_PDT000710395.1' already exists. Skipping...
Folder 'GCA_011720975.1_PDT000710389.1' already exists. Skipping...
Folder 'GCA_011721075.1_PDT000711164.1' already exists. Skipping...
Folder 'GCA_011721095.1_PDT000711186.1' already exists. Skipping...
Folder 'GCA_011721105.1_PDT000711369.1' already exists. Skipping...
Folder 'GCA_011721135.1_PDT000711155.1' already exists. Skipping...
Folder 'GCA_011721145.1_PDT000711365.1' already exists. Skipping...
Folder 'GCA_011721175.1_PDT000711145.1' already exists. Skipping...
Folder 'GCA_011721195.1_PDT000711173.1' already exists. Skipping...
Folder 'GCA_011721235.1_PDT000711368.1' already exists. Skipping...
Folder 'GCA_011721295.1_PDT000710399.1' already exists. Skipping...
Folder 'GCA_011721315.1_PDT000711448.1' already exists. Skipping...
Folder 'GCA_011721355.1_PDT000711265.1' already exists. Skipping...
Folder 'GCA_011721415.1_PDT000711459.1' already exists. Skipping...
Folder 'GCA_011721575.1_PDT000711445.1' already exists. Skipping...
Folder 'GCA_011721595.1_PDT000711467.1' already exists. Skipping...
Folder 'GCA_011721995.1_PDT000711466.1' already exists. Skipping...
Folder 'GCA_011722015.1_PDT000711465.1' already exists. Skipping...
Folder 'GCA_011722055.1_PDT000711468.1' already exists. Skipping...
Folder 'GCA_011723435.1_PDT000711456.1' already exists. Skipping...
Folder 'GCA_011737605.1_PDT000712594.1' already exists. Skipping...
Folder 'GCA_011737635.1_PDT000712577.1' already exists. Skipping...
Folder 'GCA_011737935.1_PDT000712554.1' already exists. Skipping...
Folder 'GCA_011738195.1_PDT000712580.1' already exists. Skipping...
Folder 'GCA_011738235.1_PDT000712589.1' already exists. Skipping...
Folder 'GCA_011738275.1_PDT000712555.1' already exists. Skipping...
Folder 'GCA_011738335.1_PDT000712593.1' already exists. Skipping...
Folder 'GCA_011738375.1_PDT000712561.1' already exists. Skipping...
Folder 'GCA_011738395.1_PDT000712557.1' already exists. Skipping...
Folder 'GCA_011738415.1_PDT000712610.1' already exists. Skipping...
Folder 'GCA_011738435.1_PDT000712556.1' already exists. Skipping...
Folder 'GCA_011738515.1_PDT000712566.1' already exists. Skipping...
Folder 'GCA_011738635.1_PDT000712606.1' already exists. Skipping...
Folder 'GCA_011738735.1_PDT000712560.1' already exists. Skipping...
Folder 'GCA_011749575.1_PDT000710627.1' already exists. Skipping...
Folder 'GCA_011749645.1_PDT000710636.1' already exists. Skipping...
Folder 'GCA_011749765.1_PDT000710657.1' already exists. Skipping...
Folder 'GCA_011749985.1_PDT000710453.1' already exists. Skipping...
Folder 'GCA_011750425.1_PDT000709607.1' already exists. Skipping...
Folder 'GCA_011750465.1_PDT000709665.1' already exists. Skipping...
Folder 'GCA_011750525.1_PDT000709661.1' already exists. Skipping...
Folder 'GCA_011750545.1_PDT000709604.1' already exists. Skipping...
Folder 'GCA_011759245.1_PDT000714498.1' already exists. Skipping...
Folder 'GCA_011766125.1_PDT000716728.1' already exists. Skipping...
Folder 'GCA_011769555.1_PDT000716520.1' already exists. Skipping...
Folder 'GCA_011769625.1_PDT000716521.1' already exists. Skipping...
Folder 'GCA_011979775.1_PDT000718362.1' already exists. Skipping...
Folder 'GCA_011979885.1_PDT000718359.1' already exists. Skipping...
Folder 'GCA_011979905.1_PDT000718357.1' already exists. Skipping...
Folder 'GCA_011979925.1_PDT000718360.1' already exists. Skipping...
Folder 'GCA_011979965.1_PDT000718356.1' already exists. Skipping...
Folder 'GCA_011979985.1_PDT000718354.1' already exists. Skipping...
Folder 'GCA_011980005.1_PDT000718353.1' already exists. Skipping...
Folder 'GCA_011982245.1_PDT000718345.1' already exists. Skipping...
Folder 'GCA_011983145.1_PDT000718347.1' already exists. Skipping...
Folder 'GCA_011985705.1_PDT000718284.1' already exists. Skipping...
Folder 'GCA_011985725.1_PDT000718283.1' already exists. Skipping...
Folder 'GCA_011988165.1_PDT000718115.1' already exists. Skipping...
Folder 'GCA_011988185.1_PDT000718079.1' already exists. Skipping...
Folder 'GCA_011988205.1_PDT000718113.1' already exists. Skipping...
Folder 'GCA_011988225.1_PDT000718116.1' already exists. Skipping...
Folder 'GCA_011988245.1_PDT000718106.1' already exists. Skipping...
Folder 'GCA_011988265.1_PDT000718101.1' already exists. Skipping...
Folder 'GCA_011988305.1_PDT000718097.1' already exists. Skipping...
Folder 'GCA_011988325.1_PDT000718081.1' already exists. Skipping...
Folder 'GCA_011988405.1_PDT000718083.1' already exists. Skipping...
Folder 'GCA_011988425.1_PDT000718108.1' already exists. Skipping...
Folder 'GCA_011988545.1_PDT000718082.1' already exists. Skipping...
Folder 'GCA_011988565.1_PDT000718112.1' already exists. Skipping...
Folder 'GCA_011988665.1_PDT000718107.1' already exists. Skipping...
Folder 'GCA_011988745.1_PDT000718089.1' already exists. Skipping...
Folder 'GCA_011988765.1_PDT000718093.1' already exists. Skipping...
Folder 'GCA_011988785.1_PDT000718086.1' already exists. Skipping...
Folder 'GCA_011988805.1_PDT000718095.1' already exists. Skipping...
Folder 'GCA_011988825.1_PDT000718096.1' already exists. Skipping...
Folder 'GCA_011988865.1_PDT000718092.1' already exists. Skipping...
Folder 'GCA_011988885.1_PDT000718084.1' already exists. Skipping...
Folder 'GCA_011988905.1_PDT000718090.1' already exists. Skipping...
Folder 'GCA_011988965.1_PDT000718087.1' already exists. Skipping...
Folder 'GCA_011989005.1_PDT000718071.1' already exists. Skipping...
Folder 'GCA_011989035.1_PDT000718072.1' already exists. Skipping...
Folder 'GCA_011989105.1_PDT000718066.1' already exists. Skipping...
Folder 'GCA_011989135.1_PDT000718067.1' already exists. Skipping...
Folder 'GCA_011989185.1_PDT000718062.1' already exists. Skipping...
Folder 'GCA_011989245.1_PDT000718061.1' already exists. Skipping...
Folder 'GCA_011990045.1_PDT000718077.1' already exists. Skipping...
Folder 'GCA_011994885.1_PDT000690017.1' already exists. Skipping...
Folder 'GCA_011994905.1_PDT000691125.1' already exists. Skipping...
Folder 'GCA_011996965.1_PDT000717486.1' already exists. Skipping...
Folder 'GCA_011997185.1_PDT000717491.1' already exists. Skipping...
Folder 'GCA_011997265.1_PDT000717487.1' already exists. Skipping...
Folder 'GCA_011998725.1_PDT000717488.1' already exists. Skipping...
Folder 'GCA_011998785.1_PDT000717489.1' already exists. Skipping...
Folder 'GCA_011999265.1_PDT000717509.1' already exists. Skipping...
Folder 'GCA_011999325.1_PDT000717492.1' already exists. Skipping...
Folder 'GCA_011999605.1_PDT000717495.1' already exists. Skipping...
Folder 'GCA_011999645.1_PDT000717476.1' already exists. Skipping...
Folder 'GCA_011999825.1_PDT000717479.1' already exists. Skipping...
Folder 'GCA_011999925.1_PDT000717478.1' already exists. Skipping...
Folder 'GCA_011999945.1_PDT000717436.1' already exists. Skipping...
Folder 'GCA_012000005.1_PDT000717437.1' already exists. Skipping...
Folder 'GCA_012000085.1_PDT000717471.1' already exists. Skipping...
Folder 'GCA_012000105.1_PDT000717467.1' already exists. Skipping...
Folder 'GCA_012000145.1_PDT000717438.1' already exists. Skipping...
Folder 'GCA_012000185.1_PDT000717472.1' already exists. Skipping...
Folder 'GCA_012000205.1_PDT000717473.1' already exists. Skipping...
Folder 'GCA_012000225.1_PDT000717468.1' already exists. Skipping...
Folder 'GCA_012000245.1_PDT000717440.1' already exists. Skipping...
Folder 'GCA_012000265.1_PDT000717466.1' already exists. Skipping...
Folder 'GCA_012000485.1_PDT000717447.1' already exists. Skipping...
Folder 'GCA_012000495.1_PDT000717445.1' already exists. Skipping...
Folder 'GCA_012000605.1_PDT000717428.1' already exists. Skipping...
Folder 'GCA_012000645.1_PDT000717430.1' already exists. Skipping...
Folder 'GCA_012000665.1_PDT000717429.1' already exists. Skipping...
Folder 'GCA_012000745.1_PDT000717422.1' already exists. Skipping...
Folder 'GCA_012000765.1_PDT000717424.1' already exists. Skipping...
Folder 'GCA_012000855.1_PDT000717416.1' already exists. Skipping...
Folder 'GCA_012000885.1_PDT000717417.1' already exists. Skipping...
Folder 'GCA_012000905.1_PDT000717418.1' already exists. Skipping...
Folder 'GCA_012000925.1_PDT000717413.1' already exists. Skipping...
Folder 'GCA_012000965.1_PDT000717412.1' already exists. Skipping...
Folder 'GCA_012001125.1_PDT000717408.1' already exists. Skipping...
Folder 'GCA_012001145.1_PDT000717402.1' already exists. Skipping...
Folder 'GCA_012001245.1_PDT000717398.1' already exists. Skipping...
Folder 'GCA_012001265.1_PDT000717399.1' already exists. Skipping...
Folder 'GCA_012001305.1_PDT000717401.1' already exists. Skipping...
Folder 'GCA_012041175.1_PDT000718647.1' already exists. Skipping...
Folder 'GCA_012041355.1_PDT000718663.1' already exists. Skipping...
Folder 'GCA_012041855.1_PDT000718613.1' already exists. Skipping...
Folder 'GCA_012041895.1_PDT000718566.1' already exists. Skipping...
Folder 'GCA_012042345.1_PDT000718567.1' already exists. Skipping...
Folder 'GCA_012042515.1_PDT000718578.1' already exists. Skipping...
Folder 'GCA_012043095.1_PDT000718514.1' already exists. Skipping...
Folder 'GCA_012043135.1_PDT000718510.1' already exists. Skipping...
Folder 'GCA_012043175.1_PDT000718512.1' already exists. Skipping...
Folder 'GCA_012043195.1_PDT000718509.1' already exists. Skipping...
Folder 'GCA_012043235.1_PDT000718511.1' already exists. Skipping...
Folder 'GCA_012043495.1_PDT000718526.1' already exists. Skipping...
Folder 'GCA_012043595.1_PDT000718521.1' already exists. Skipping...
Folder 'GCA_012160005.1_PDT000720569.1' already exists. Skipping...
Folder 'GCA_012170095.1_PDT000720599.1' already exists. Skipping...
Folder 'GCA_012244065.1_PDT000720860.1' already exists. Skipping...
Folder 'GCA_012282385.1_PDT000721301.1' already exists. Skipping...

Retreiveing data: 16172it [00:03, 6708.54it/s]

Folder 'GCA_013773085.1_PDT000753946.1' already exists. Skipping...
Folder 'GCA_013787305.1_PDT000750893.1' already exists. Skipping...
Folder 'GCA_013787325.1_PDT000750889.1' already exists. Skipping...
Folder 'GCA_013787355.1_PDT000750887.1' already exists. Skipping...
Folder 'GCA_013787425.1_PDT000750884.1' already exists. Skipping...
Folder 'GCA_013787505.1_PDT000750879.1' already exists. Skipping...
Folder 'GCA_013787545.1_PDT000750885.1' already exists. Skipping...
Folder 'GCA_013787585.1_PDT000750882.1' already exists. Skipping...
Folder 'GCA_013787605.1_PDT000750877.1' already exists. Skipping...
Folder 'GCA_013787725.1_PDT000750891.1' already exists. Skipping...
Folder 'GCA_013787745.1_PDT000750888.1' already exists. Skipping...
Folder 'GCA_013787805.1_PDT000750878.1' already exists. Skipping...
Folder 'GCA_013787825.1_PDT000750875.1' already exists. Skipping...
Folder 'GCA_013787845.1_PDT000750876.1' already exists. Skipping...
Folder 'GCA_013787865.1_PDT000750874.1' already exists. Skipping...
Folder 'GCA_013787985.1_PDT000750871.1' already exists. Skipping...
Folder 'GCA_013790025.1_PDT000750365.1' already exists. Skipping...
Folder 'GCA_013790765.1_PDT000750318.1' already exists. Skipping...
Folder 'GCA_013791485.1_PDT000750161.1' already exists. Skipping...
Folder 'GCA_013791505.1_PDT000750163.1' already exists. Skipping...
Folder 'GCA_013792225.1_PDT000750156.1' already exists. Skipping...
Folder 'GCA_013792245.1_PDT000750153.1' already exists. Skipping...
Folder 'GCA_013792265.1_PDT000750157.1' already exists. Skipping...
Folder 'GCA_013792315.1_PDT000750154.1' already exists. Skipping...
Folder 'GCA_013800225.1_PDT000748874.1' already exists. Skipping...
Folder 'GCA_013800245.1_PDT000748872.1' already exists. Skipping...
Folder 'GCA_013800285.1_PDT000748871.1' already exists. Skipping...
Folder 'GCA_013800305.1_PDT000748867.1' already exists. Skipping...
Folder 'GCA_013800345.1_PDT000748868.1' already exists. Skipping...
Folder 'GCA_013800445.1_PDT000748858.1' already exists. Skipping...
Folder 'GCA_013800465.1_PDT000748861.1' already exists. Skipping...
Folder 'GCA_013800505.1_PDT000748856.1' already exists. Skipping...
Folder 'GCA_013800525.1_PDT000748854.1' already exists. Skipping...
Folder 'GCA_013800565.1_PDT000748855.1' already exists. Skipping...
Folder 'GCA_013800625.1_PDT000748850.1' already exists. Skipping...
Folder 'GCA_013800645.1_PDT000748849.1' already exists. Skipping...
Folder 'GCA_013801345.1_PDT000748851.1' already exists. Skipping...
Folder 'GCA_013801365.1_PDT000748853.1' already exists. Skipping...
Folder 'GCA_013801385.1_PDT000748848.1' already exists. Skipping...
Folder 'GCA_013801805.1_PDT000748101.1' already exists. Skipping...
Folder 'GCA_013802245.1_PDT000748124.1' already exists. Skipping...
Folder 'GCA_013802255.1_PDT000748126.1' already exists. Skipping...
Folder 'GCA_013802285.1_PDT000748120.1' already exists. Skipping...
Folder 'GCA_013802305.1_PDT000748125.1' already exists. Skipping...
Folder 'GCA_013802465.1_PDT000748114.1' already exists. Skipping...
Folder 'GCA_013802485.1_PDT000748119.1' already exists. Skipping...
Folder 'GCA_013802525.1_PDT000748109.1' already exists. Skipping...
Folder 'GCA_013802545.1_PDT000748112.1' already exists. Skipping...
Folder 'GCA_013802565.1_PDT000748111.1' already exists. Skipping...
Folder 'GCA_013802595.1_PDT000748106.1' already exists. Skipping...
Folder 'GCA_013802615.1_PDT000748110.1' already exists. Skipping...
Folder 'GCA_013802665.1_PDT000748103.1' already exists. Skipping...
Folder 'GCA_013802705.1_PDT000748104.1' already exists. Skipping...
Folder 'GCA_013802725.1_PDT000748105.1' already exists. Skipping...
Folder 'GCA_013802805.1_PDT000748100.1' already exists. Skipping...
Folder 'GCA_013802825.1_PDT000748102.1' already exists. Skipping...
Folder 'GCA_013802905.1_PDT000748099.1' already exists. Skipping...
Folder 'GCA_013803125.1_PDT000747999.1' already exists. Skipping...
Folder 'GCA_013803265.1_PDT000748000.1' already exists. Skipping...
Folder 'GCA_013803505.1_PDT000748001.1' already exists. Skipping...
Folder 'GCA_013803665.1_PDT000747997.1' already exists. Skipping...
Folder 'GCA_013805165.1_PDT000748004.1' already exists. Skipping...
Folder 'GCA_013809015.1_PDT000747666.1' already exists. Skipping...
Folder 'GCA_013809065.1_PDT000747670.1' already exists. Skipping...
Folder 'GCA_013809505.1_PDT000747681.1' already exists. Skipping...
Folder 'GCA_013809545.1_PDT000747683.1' already exists. Skipping...
Folder 'GCA_013809565.1_PDT000747684.1' already exists. Skipping...
Folder 'GCA_013809605.1_PDT000747682.1' already exists. Skipping...
Folder 'GCA_013809665.1_PDT000747677.1' already exists. Skipping...
Folder 'GCA_013809685.1_PDT000747672.1' already exists. Skipping...
Folder 'GCA_013809745.1_PDT000747676.1' already exists. Skipping...
Folder 'GCA_013809765.1_PDT000747675.1' already exists. Skipping...
Folder 'GCA_013810025.1_PDT000747663.1' already exists. Skipping...
Folder 'GCA_013810085.1_PDT000747658.1' already exists. Skipping...
Folder 'GCA_013810125.1_PDT000747665.1' already exists. Skipping...
Folder 'GCA_013810165.1_PDT000747669.1' already exists. Skipping...
Folder 'GCA_013810245.1_PDT000747668.1' already exists. Skipping...
Folder 'GCA_013810305.1_PDT000747661.1' already exists. Skipping...
Folder 'GCA_013810325.1_PDT000747659.1' already exists. Skipping...
Folder 'GCA_013829295.1_PDT000737534.1' already exists. Skipping...
Folder 'GCA_013871135.1_PDT000798332.1' already exists. Skipping...
Folder 'GCA_013965815.1_PDT000799668.1' already exists. Skipping...
Folder 'GCA_013968865.1_PDT000799682.1' already exists. Skipping...
Folder 'GCA_013968925.1_PDT000799678.1' already exists. Skipping...
Folder 'GCA_013968985.1_PDT000799670.1' already exists. Skipping...
Folder 'GCA_013969005.1_PDT000799681.1' already exists. Skipping...
Folder 'GCA_013969085.1_PDT000799663.1' already exists. Skipping...
Folder 'GCA_013969125.1_PDT000799662.1' already exists. Skipping...
Folder 'GCA_013969165.1_PDT000799666.1' already exists. Skipping...
Folder 'GCA_013969265.1_PDT000799673.1' already exists. Skipping...
Folder 'GCA_013970585.1_PDT000799677.1' already exists. Skipping...
Folder 'GCA_013972205.1_PDT000799680.1' already exists. Skipping...
Folder 'GCA_013972405.1_PDT000799679.1' already exists. Skipping...
Folder 'GCA_013975385.1_PDT000799675.1' already exists. Skipping...
Folder 'GCA_013975605.1_PDT000799674.1' already exists. Skipping...
Folder 'GCA_013979335.1_PDT000799660.1' already exists. Skipping...
Folder 'GCA_013983575.1_PDT000799809.1' already exists. Skipping...
Folder 'GCA_013984495.1_PDT000799676.1' already exists. Skipping...
Folder 'GCA_013984535.1_PDT000799665.1' already exists. Skipping...
Folder 'GCA_014044705.1_PDT000800160.1' already exists. Skipping...
Folder 'GCA_014052905.1_PDT000801338.1' already exists. Skipping...
Folder 'GCA_014054065.1_PDT000801337.1' already exists. Skipping...
Folder 'GCA_014054145.1_PDT000801323.1' already exists. Skipping...
Folder 'GCA_014054245.1_PDT000801322.1' already exists. Skipping...
Folder 'GCA_014064125.1_PDT000802209.1' already exists. Skipping...
Folder 'GCA_014064225.1_PDT000802222.1' already exists. Skipping...
Folder 'GCA_014064265.1_PDT000802214.1' already exists. Skipping...
Folder 'GCA_014064285.1_PDT000802217.1' already exists. Skipping...
Folder 'GCA_014064305.1_PDT000802216.1' already exists. Skipping...
Folder 'GCA_014064325.1_PDT000802215.1' already exists. Skipping...
Folder 'GCA_014064345.1_PDT000802213.1' already exists. Skipping...
Folder 'GCA_014064445.1_PDT000802205.1' already exists. Skipping...
Folder 'GCA_014064465.1_PDT000802206.1' already exists. Skipping...
Folder 'GCA_014064505.1_PDT000802204.1' already exists. Skipping...
Folder 'GCA_014064545.1_PDT000802203.1' already exists. Skipping...
Folder 'GCA_014064585.1_PDT000802200.1' already exists. Skipping...
Folder 'GCA_014064625.1_PDT000802196.1' already exists. Skipping...
Folder 'GCA_014064645.1_PDT000802194.1' already exists. Skipping...
Folder 'GCA_014064685.1_PDT000802197.1' already exists. Skipping...
Folder 'GCA_014064705.1_PDT000802195.1' already exists. Skipping...
Folder 'GCA_014067335.1_PDT000802008.1' already exists. Skipping...
Folder 'GCA_014067435.1_PDT000802003.1' already exists. Skipping...
Folder 'GCA_014067515.1_PDT000801996.1' already exists. Skipping...
Folder 'GCA_014067595.1_PDT000801994.1' already exists. Skipping...
Folder 'GCA_014067635.1_PDT000801991.1' already exists. Skipping...
Folder 'GCA_014067655.1_PDT000801988.1' already exists. Skipping...
Folder 'GCA_014067675.1_PDT000801990.1' already exists. Skipping...
Folder 'GCA_014067695.1_PDT000801989.1' already exists. Skipping...
Folder 'GCA_014067715.1_PDT000801981.1' already exists. Skipping...
Folder 'GCA_014067815.1_PDT000801959.1' already exists. Skipping...
Folder 'GCA_014068035.1_PDT000801987.1' already exists. Skipping...
Folder 'GCA_014068075.1_PDT000801979.1' already exists. Skipping...
Folder 'GCA_014068115.1_PDT000801976.1' already exists. Skipping...
Folder 'GCA_014068135.1_PDT000801977.1' already exists. Skipping...
Folder 'GCA_014068155.1_PDT000801974.1' already exists. Skipping...
Folder 'GCA_014071515.1_PDT000802842.1' already exists. Skipping...
Folder 'GCA_014107635.1_PDT000803120.1' already exists. Skipping...
Folder 'GCA_014120145.1_PDT000805939.1' already exists. Skipping...
Folder 'GCA_014120565.1_PDT000804634.2' already exists. Skipping...
Folder 'GCA_014120725.1_PDT000804661.2' already exists. Skipping...
Folder 'GCA_014120785.1_PDT000804650.2' already exists. Skipping...
Folder 'GCA_014120825.1_PDT000804651.2' already exists. Skipping...
Folder 'GCA_014120865.1_PDT000804652.2' already exists. Skipping...
Folder 'GCA_014120895.1_PDT000804648.2' already exists. Skipping...
Folder 'GCA_014120945.1_PDT000804647.2' already exists. Skipping...
Folder 'GCA_014121045.1_PDT000804644.2' already exists. Skipping...
Folder 'GCA_014121085.1_PDT000804639.2' already exists. Skipping...
Folder 'GCA_014121105.1_PDT000804638.2' already exists. Skipping...
Folder 'GCA_014122425.1_PDT000804618.2' already exists. Skipping...
Folder 'GCA_014122645.1_PDT000804615.2' already exists. Skipping...
Folder 'GCA_014122705.1_PDT000804613.2' already exists. Skipping...
Folder 'GCA_014122845.1_PDT000804605.2' already exists. Skipping...
Folder 'GCA_014122925.1_PDT000804596.2' already exists. Skipping...
Folder 'GCA_014139625.1_PDT000806418.1' already exists. Skipping...
Folder 'GCA_014147565.1_PDT000806811.1' already exists. Skipping...
Folder 'GCA_014147725.1_PDT000806812.1' already exists. Skipping...
Folder 'GCA_014147925.1_PDT000806826.1' already exists. Skipping...
Folder 'GCA_014148065.1_PDT000806830.1' already exists. Skipping...
Folder 'GCA_014148505.1_PDT000806816.1' already exists. Skipping...
Folder 'GCA_014148685.1_PDT000806802.1' already exists. Skipping...
Folder 'GCA_014148765.1_PDT000806793.1' already exists. Skipping...
Folder 'GCA_014148785.1_PDT000806794.1' already exists. Skipping...
Folder 'GCA_014148805.1_PDT000806790.1' already exists. Skipping...
Folder 'GCA_014148845.1_PDT000806792.1' already exists. Skipping...
Folder 'GCA_014148925.1_PDT000806807.1' already exists. Skipping...
Folder 'GCA_014149005.1_PDT000806784.1' already exists. Skipping...
Folder 'GCA_014149385.1_PDT000806764.1' already exists. Skipping...
Folder 'GCA_014149425.1_PDT000806765.1' already exists. Skipping...
Folder 'GCA_014149465.1_PDT000806763.1' already exists. Skipping...
Folder 'GCA_014149545.1_PDT000806757.1' already exists. Skipping...
Folder 'GCA_014149565.1_PDT000806756.1' already exists. Skipping...
Folder 'GCA_014149585.1_PDT000806754.1' already exists. Skipping...
Folder 'GCA_014149605.1_PDT000806755.1' already exists. Skipping...
Folder 'GCA_014149705.1_PDT000806752.1' already exists. Skipping...
Folder 'GCA_014149745.1_PDT000806740.1' already exists. Skipping...
Folder 'GCA_014149835.1_PDT000806742.1' already exists. Skipping...
Folder 'GCA_014155975.1_PDT000806820.1' already exists. Skipping...
Folder 'GCA_014167115.1_PDT000807525.1' already exists. Skipping...
Folder 'GCA_014174925.1_PDT000807648.2' already exists. Skipping...
Folder 'GCA_014174995.1_PDT000807647.2' already exists. Skipping...
Folder 'GCA_014231725.1_PDT000814364.1' already exists. Skipping...
Folder 'GCA_014231785.1_PDT000814362.1' already exists. Skipping...
Folder 'GCA_014231825.1_PDT000814361.1' already exists. Skipping...
Folder 'GCA_014245955.1_PDT000814914.1' already exists. Skipping...
Folder 'GCA_014246455.1_PDT000814912.1' already exists. Skipping...
Folder 'GCA_014246635.1_PDT000814906.1' already exists. Skipping...
Folder 'GCA_014246675.1_PDT000814904.1' already exists. Skipping...
Folder 'GCA_014246895.1_PDT000814902.1' already exists. Skipping...
Folder 'GCA_014247075.1_PDT000814907.1' already exists. Skipping...
Folder 'GCA_014247215.1_PDT000814900.1' already exists. Skipping...
Folder 'GCA_014247255.1_PDT000814898.1' already exists. Skipping...
Folder 'GCA_014247295.1_PDT000814903.1' already exists. Skipping...
Folder 'GCA_014247335.1_PDT000814894.1' already exists. Skipping...
Folder 'GCA_014247355.1_PDT000814890.1' already exists. Skipping...
Folder 'GCA_014247415.1_PDT000814913.1' already exists. Skipping...
Folder 'GCA_014247435.1_PDT000814910.1' already exists. Skipping...
Folder 'GCA_014247655.1_PDT000814891.1' already exists. Skipping...
Folder 'GCA_014248815.1_PDT000814799.1' already exists. Skipping...
Folder 'GCA_014256025.1_PDT000816278.1' already exists. Skipping...
Folder 'GCA_014257985.1_PDT000817273.1' already exists. Skipping...
Folder 'GCA_014258045.1_PDT000817275.1' already exists. Skipping...
Folder 'GCA_014258125.1_PDT000817269.1' already exists. Skipping...
Folder 'GCA_014258145.1_PDT000817271.1' already exists. Skipping...
Folder 'GCA_014258165.1_PDT000817268.1' already exists. Skipping...
Folder 'GCA_014258185.1_PDT000817266.1' already exists. Skipping...
Folder 'GCA_014258225.1_PDT000817265.1' already exists. Skipping...
Folder 'GCA_014258265.1_PDT000817263.1' already exists. Skipping...
Folder 'GCA_014258305.1_PDT000817261.1' already exists. Skipping...
Folder 'GCA_014258345.1_PDT000817259.1' already exists. Skipping...
Folder 'GCA_014258365.1_PDT000817254.1' already exists. Skipping...
Folder 'GCA_014258445.1_PDT000817255.1' already exists. Skipping...
Folder 'GCA_014258725.1_PDT000817230.1' already exists. Skipping...
Folder 'GCA_014258755.1_PDT000817228.1' already exists. Skipping...
Folder 'GCA_014258855.1_PDT000817225.1' already exists. Skipping...
Folder 'GCA_014275405.1_PDT000817639.1' already exists. Skipping...
Folder 'GCA_014275445.1_PDT000817634.1' already exists. Skipping...
Folder 'GCA_014275965.1_PDT000817628.1' already exists. Skipping...
Folder 'GCA_014276005.1_PDT000817625.1' already exists. Skipping...
Folder 'GCA_014276025.1_PDT000817631.1' already exists. Skipping...
Folder 'GCA_014276095.1_PDT000817629.1' already exists. Skipping...
Folder 'GCA_014276145.1_PDT000817621.1' already exists. Skipping...
Folder 'GCA_014276225.1_PDT000817623.1' already exists. Skipping...
Folder 'GCA_014277205.1_PDT000817571.1' already exists. Skipping...
Folder 'GCA_014299705.1_PDT000820794.1' already exists. Skipping...
Folder 'GCA_014299795.1_PDT000820788.1' already exists. Skipping...
Folder 'GCA_014299835.1_PDT000820792.1' already exists. Skipping...
Folder 'GCA_014299915.1_PDT000820784.1' already exists. Skipping...
Folder 'GCA_014299955.1_PDT000820780.1' already exists. Skipping...
Folder 'GCA_014300185.1_PDT000820753.1' already exists. Skipping...
Folder 'GCA_014300225.1_PDT000820750.1' already exists. Skipping...
Folder 'GCA_014300285.1_PDT000820777.1' already exists. Skipping...
Folder 'GCA_014300405.1_PDT000820774.1' already exists. Skipping...
Folder 'GCA_014300465.1_PDT000820772.1' already exists. Skipping...
Folder 'GCA_014300485.1_PDT000820770.1' already exists. Skipping...
Folder 'GCA_014300905.1_PDT000820702.1' already exists. Skipping...
Folder 'GCA_014300945.1_PDT000820703.1' already exists. Skipping...
Folder 'GCA_014300965.1_PDT000820700.1' already exists. Skipping...
Folder 'GCA_014300985.1_PDT000820699.1' already exists. Skipping...
Folder 'GCA_014301225.1_PDT000820713.1' already exists. Skipping...
Folder 'GCA_014301305.1_PDT000820711.1' already exists. Skipping...
Folder 'GCA_014301365.1_PDT000820706.1' already exists. Skipping...
Folder 'GCA_014301405.1_PDT000820695.1' already exists. Skipping...
Folder 'GCA_014301425.1_PDT000820709.1' already exists. Skipping...
Folder 'GCA_014301445.1_PDT000820694.1' already exists. Skipping...
Folder 'GCA_014301485.1_PDT000820698.1' already exists. Skipping...
Folder 'GCA_014301565.1_PDT000820690.1' already exists. Skipping...
Folder 'GCA_014301605.1_PDT000820687.1' already exists. Skipping...
Folder 'GCA_014301625.1_PDT000820686.1' already exists. Skipping...
Folder 'GCA_014307155.1_PDT000821890.1' already exists. Skipping...
Folder 'GCA_014307635.1_PDT000821892.1' already exists. Skipping...
Folder 'GCA_014307975.1_PDT000821869.1' already exists. Skipping...
Folder 'GCA_014307995.1_PDT000821868.1' already exists. Skipping...
Folder 'GCA_014308055.1_PDT000821867.1' already exists. Skipping...
Folder 'GCA_014308075.1_PDT000821891.1' already exists. Skipping...
Folder 'GCA_014308255.1_PDT000821877.1' already exists. Skipping...
Folder 'GCA_014308275.1_PDT000821873.1' already exists. Skipping...
Folder 'GCA_014311435.1_PDT000821887.1' already exists. Skipping...
Folder 'GCA_014318075.1_PDT000821874.1' already exists. Skipping...
Folder 'GCA_014339215.1_PDT000826865.1' already exists. Skipping...
Folder 'GCA_014339295.1_PDT000826831.1' already exists. Skipping...
Folder 'GCA_014339315.1_PDT000826833.1' already exists. Skipping...
Folder 'GCA_014339775.1_PDT000826857.1' already exists. Skipping...
Folder 'GCA_014339935.1_PDT000826860.1' already exists. Skipping...
Folder 'GCA_014339955.1_PDT000826844.1' already exists. Skipping...
Folder 'GCA_014340575.1_PDT000820714.1' already exists. Skipping...
Folder 'GCA_014340615.1_PDT000820707.1' already exists. Skipping...
Folder 'GCA_014340775.1_PDT000826870.1' already exists. Skipping...
Folder 'GCA_014341775.1_PDT000810165.1' already exists. Skipping...
Folder 'GCA_014343055.1_PDT000717415.1' already exists. Skipping...
Folder 'GCA_014343595.1_PDT000687014.1' already exists. Skipping...
Folder 'GCA_014343695.1_PDT000687005.1' already exists. Skipping...
Folder 'GCA_014343705.1_PDT000687016.1' already exists. Skipping...
Folder 'GCA_014343775.1_PDT000686966.1' already exists. Skipping...
Folder 'GCA_014343795.1_PDT000686961.1' already exists. Skipping...
Folder 'GCA_014344375.1_PDT000636412.1' already exists. Skipping...
Folder 'GCA_014344455.1_PDT000634677.1' already exists. Skipping...
Folder 'GCA_014344495.1_PDT000635521.1' already exists. Skipping...
Folder 'GCA_014344515.1_PDT000632242.1' already exists. Skipping...
Folder 'GCA_014344535.1_PDT000632240.1' already exists. Skipping...
Folder 'GCA_014344555.1_PDT000631976.1' already exists. Skipping...
Folder 'GCA_014344575.1_PDT000631983.1' already exists. Skipping...
Folder 'GCA_014344595.1_PDT000631981.1' already exists. Skipping...
Folder 'GCA_014344615.1_PDT000632042.1' already exists. Skipping...
Folder 'GCA_014344635.1_PDT000631974.1' already exists. Skipping...
Folder 'GCA_014344655.1_PDT000631654.1' already exists. Skipping...
Folder 'GCA_014344675.1_PDT000631972.1' already exists. Skipping...
Folder 'GCA_014344695.1_PDT000630740.1' already exists. Skipping...
Folder 'GCA_014344715.1_PDT000630657.1' already exists. Skipping...
Folder 'GCA_014344835.1_PDT000826859.1' already exists. Skipping...
Folder 'GCA_014344895.1_PDT000826871.1' already exists. Skipping...
Folder 'GCA_014345535.1_PDT000630632.1' already exists. Skipping...
Folder 'GCA_014345595.1_PDT000630614.1' already exists. Skipping...
Folder 'GCA_014350075.1_PDT000827002.1' already exists. Skipping...
Folder 'GCA_014358945.1_PDT000823028.1' already exists. Skipping...

Retreiveing data: 17518it [00:04, 6689.23it/s]

Folder 'GCA_015859105.1_PDT000901938.1' already exists. Skipping...
Folder 'GCA_015859305.1_PDT000901944.1' already exists. Skipping...
Folder 'GCA_015860105.1_PDT000901963.1' already exists. Skipping...
Folder 'GCA_015860225.1_PDT000901925.1' already exists. Skipping...
Folder 'GCA_015860265.1_PDT000901932.1' already exists. Skipping...
Folder 'GCA_015860285.1_PDT000901919.1' already exists. Skipping...
Folder 'GCA_015860325.1_PDT000901926.1' already exists. Skipping...
Folder 'GCA_015860345.1_PDT000901917.1' already exists. Skipping...
Folder 'GCA_015860385.1_PDT000901924.1' already exists. Skipping...
Folder 'GCA_015860405.1_PDT000901916.1' already exists. Skipping...
Folder 'GCA_015860585.1_PDT000901962.1' already exists. Skipping...
Folder 'GCA_015860665.1_PDT000901959.1' already exists. Skipping...
Folder 'GCA_015860705.1_PDT000901957.1' already exists. Skipping...
Folder 'GCA_015860765.1_PDT000901954.1' already exists. Skipping...
Folder 'GCA_015860805.1_PDT000901951.1' already exists. Skipping...
Folder 'GCA_015860845.1_PDT000901941.1' already exists. Skipping...
Folder 'GCA_015860865.1_PDT000901946.1' already exists. Skipping...
Folder 'GCA_015860885.1_PDT000901950.1' already exists. Skipping...
Folder 'GCA_015860925.1_PDT000901933.1' already exists. Skipping...
Folder 'GCA_015860985.1_PDT000901942.1' already exists. Skipping...
Folder 'GCA_015861025.1_PDT000901943.1' already exists. Skipping...
Folder 'GCA_015861085.1_PDT000901966.1' already exists. Skipping...
Folder 'GCA_015861125.1_PDT000901927.1' already exists. Skipping...
Folder 'GCA_015863295.1_PDT000906127.1' already exists. Skipping...
Folder 'GCA_015865625.1_PDT000906126.1' already exists. Skipping...
Folder 'GCA_015866245.1_PDT000906460.1' already exists. Skipping...
Folder 'GCA_015866285.1_PDT000906461.1' already exists. Skipping...
Folder 'GCA_015866345.1_PDT000906458.1' already exists. Skipping...
Folder 'GCA_015866385.1_PDT000906454.1' already exists. Skipping...
Folder 'GCA_015866405.1_PDT000906453.1' already exists. Skipping...
Folder 'GCA_015866445.1_PDT000906451.1' already exists. Skipping...
Folder 'GCA_015866465.1_PDT000906450.1' already exists. Skipping...
Folder 'GCA_015866505.1_PDT000906452.1' already exists. Skipping...
Folder 'GCA_015866525.1_PDT000906445.1' already exists. Skipping...
Folder 'GCA_015866565.1_PDT000906444.1' already exists. Skipping...
Folder 'GCA_015866625.1_PDT000906441.1' already exists. Skipping...
Folder 'GCA_015866645.1_PDT000906443.1' already exists. Skipping...
Folder 'GCA_015866665.1_PDT000906440.1' already exists. Skipping...
Folder 'GCA_015866725.1_PDT000906433.1' already exists. Skipping...
Folder 'GCA_015866785.1_PDT000906434.1' already exists. Skipping...
Folder 'GCA_015866805.1_PDT000906438.1' already exists. Skipping...
Folder 'GCA_015866885.1_PDT000906435.1' already exists. Skipping...
Folder 'GCA_015887425.1_PDT000901937.1' already exists. Skipping...
Folder 'GCA_015902805.1_PDT000908080.1' already exists. Skipping...
Folder 'GCA_015909285.1_PDT000908083.1' already exists. Skipping...
Folder 'GCA_015913995.1_PDT000898447.1' already exists. Skipping...
Folder 'GCA_015914055.1_PDT000898461.1' already exists. Skipping...
Folder 'GCA_015914835.1_PDT000898389.1' already exists. Skipping...
Folder 'GCA_015918645.1_PDT000898178.1' already exists. Skipping...
Folder 'GCA_015918705.1_PDT000898180.1' already exists. Skipping...
Folder 'GCA_015919025.1_PDT000898175.1' already exists. Skipping...
Folder 'GCA_015919245.1_PDT000898146.1' already exists. Skipping...
Folder 'GCA_015919305.1_PDT000898142.1' already exists. Skipping...
Folder 'GCA_015919325.1_PDT000898141.1' already exists. Skipping...
Folder 'GCA_015919445.1_PDT000898053.1' already exists. Skipping...
Folder 'GCA_015920645.1_PDT000897861.1' already exists. Skipping...
Folder 'GCA_015921225.1_PDT000897936.1' already exists. Skipping...
Folder 'GCA_015921505.1_PDT000897876.1' already exists. Skipping...
Folder 'GCA_015921565.1_PDT000897871.1' already exists. Skipping...
Folder 'GCA_015921645.1_PDT000897869.1' already exists. Skipping...
Folder 'GCA_015921685.1_PDT000897860.1' already exists. Skipping...
Folder 'GCA_015921705.1_PDT000897865.1' already exists. Skipping...
Folder 'GCA_015922125.1_PDT000897858.1' already exists. Skipping...
Folder 'GCA_015922345.1_PDT000897859.1' already exists. Skipping...
Folder 'GCA_015923625.1_PDT000897718.1' already exists. Skipping...
Folder 'GCA_015923665.1_PDT000897717.1' already exists. Skipping...
Folder 'GCA_015923825.1_PDT000897768.1' already exists. Skipping...
Folder 'GCA_015923865.1_PDT000897715.1' already exists. Skipping...
Folder 'GCA_015923905.1_PDT000897710.1' already exists. Skipping...
Folder 'GCA_015923945.1_PDT000897714.1' already exists. Skipping...
Folder 'GCA_015923965.1_PDT000897704.1' already exists. Skipping...
Folder 'GCA_015924025.1_PDT000897702.1' already exists. Skipping...
Folder 'GCA_015924285.1_PDT000897770.1' already exists. Skipping...
Folder 'GCA_015924725.1_PDT000897688.1' already exists. Skipping...
Folder 'GCA_015924745.1_PDT000897685.1' already exists. Skipping...
Folder 'GCA_015924805.1_PDT000897682.1' already exists. Skipping...
Folder 'GCA_015924845.1_PDT000897681.1' already exists. Skipping...
Folder 'GCA_015924875.1_PDT000897680.1' already exists. Skipping...
Folder 'GCA_015924905.1_PDT000897678.1' already exists. Skipping...
Folder 'GCA_015928145.1_PDT000897389.1' already exists. Skipping...
Folder 'GCA_015928745.1_PDT000897684.1' already exists. Skipping...
Folder 'GCA_015933165.1_PDT000897863.1' already exists. Skipping...
Folder 'GCA_015951285.1_PDT000908626.1' already exists. Skipping...
Folder 'GCA_015951305.1_PDT000908638.1' already exists. Skipping...
Folder 'GCA_015951365.1_PDT000908632.1' already exists. Skipping...
Folder 'GCA_015951405.1_PDT000908625.1' already exists. Skipping...
Folder 'GCA_015951425.1_PDT000908622.1' already exists. Skipping...
Folder 'GCA_015951585.1_PDT000908615.1' already exists. Skipping...
Folder 'GCA_015951645.1_PDT000908616.1' already exists. Skipping...
Folder 'GCA_015951665.1_PDT000908613.1' already exists. Skipping...
Folder 'GCA_015951725.1_PDT000908640.1' already exists. Skipping...
Folder 'GCA_015951765.1_PDT000908647.1' already exists. Skipping...
Folder 'GCA_015951785.1_PDT000908634.1' already exists. Skipping...
Folder 'GCA_015951825.1_PDT000908643.1' already exists. Skipping...
Folder 'GCA_015951845.1_PDT000908648.1' already exists. Skipping...
Folder 'GCA_015951865.1_PDT000908639.1' already exists. Skipping...
Folder 'GCA_015951925.1_PDT000908642.1' already exists. Skipping...
Folder 'GCA_015953965.1_PDT000894741.1' already exists. Skipping...
Folder 'GCA_015954045.1_PDT000894735.1' already exists. Skipping...
Folder 'GCA_015954055.1_PDT000894731.1' already exists. Skipping...
Folder 'GCA_015954105.1_PDT000894730.1' already exists. Skipping...
Folder 'GCA_015954955.1_PDT000894733.1' already exists. Skipping...
Folder 'GCA_015955015.1_PDT000894746.1' already exists. Skipping...
Folder 'GCA_015955125.1_PDT000894739.1' already exists. Skipping...
Folder 'GCA_015955505.1_PDT000908630.1' already exists. Skipping...
Folder 'GCA_015955645.1_PDT000894589.1' already exists. Skipping...
Folder 'GCA_015958305.1_PDT000893922.1' already exists. Skipping...
Folder 'GCA_015958315.1_PDT000893921.1' already exists. Skipping...
Folder 'GCA_015958375.1_PDT000893923.1' already exists. Skipping...
Folder 'GCA_015958405.1_PDT000893919.1' already exists. Skipping...
Folder 'GCA_015958435.1_PDT000893914.1' already exists. Skipping...
Folder 'GCA_015958465.1_PDT000893917.1' already exists. Skipping...
Folder 'GCA_015958475.1_PDT000893915.1' already exists. Skipping...
Folder 'GCA_015958505.1_PDT000893908.1' already exists. Skipping...
Folder 'GCA_015958545.1_PDT000893910.1' already exists. Skipping...
Folder 'GCA_015958605.1_PDT000893907.1' already exists. Skipping...
Folder 'GCA_015958645.1_PDT000893906.1' already exists. Skipping...
Folder 'GCA_016030475.1_PDT000913267.1' already exists. Skipping...
Folder 'GCA_016030495.1_PDT000913289.1' already exists. Skipping...
Folder 'GCA_016030515.1_PDT000913266.1' already exists. Skipping...
Folder 'GCA_016030525.1_PDT000913269.1' already exists. Skipping...
Folder 'GCA_016030615.1_PDT000913274.1' already exists. Skipping...
Folder 'GCA_016030625.1_PDT000913295.1' already exists. Skipping...
Folder 'GCA_016030655.1_PDT000913297.1' already exists. Skipping...
Folder 'GCA_016030695.1_PDT000913268.1' already exists. Skipping...
Folder 'GCA_016030755.1_PDT000913316.1' already exists. Skipping...
Folder 'GCA_016030915.1_PDT000913312.1' already exists. Skipping...
Folder 'GCA_016031095.1_PDT000913294.1' already exists. Skipping...
Folder 'GCA_016031315.1_PDT000913291.1' already exists. Skipping...
Folder 'GCA_016056435.1_PDT000908757.1' already exists. Skipping...
Folder 'GCA_016056445.1_PDT000908760.1' already exists. Skipping...
Folder 'GCA_016056475.1_PDT000908759.1' already exists. Skipping...
Folder 'GCA_016056515.1_PDT000908756.1' already exists. Skipping...
Folder 'GCA_016056525.1_PDT000908758.1' already exists. Skipping...
Folder 'GCA_016056895.1_PDT000908769.1' already exists. Skipping...
Folder 'GCA_016056955.1_PDT000908764.1' already exists. Skipping...
Folder 'GCA_016056975.1_PDT000908765.1' already exists. Skipping...
Folder 'GCA_016057075.1_PDT000908780.1' already exists. Skipping...
Folder 'GCA_016057155.1_PDT000908775.1' already exists. Skipping...
Folder 'GCA_016057175.1_PDT000908773.1' already exists. Skipping...
Folder 'GCA_016057215.1_PDT000908768.1' already exists. Skipping...
Folder 'GCA_016057395.1_PDT000908778.1' already exists. Skipping...
Folder 'GCA_016057815.1_PDT000913464.1' already exists. Skipping...
Folder 'GCA_016057875.1_PDT000913462.1' already exists. Skipping...
Folder 'GCA_016058095.1_PDT000913463.1' already exists. Skipping...
Folder 'GCA_016058475.1_PDT000913430.1' already exists. Skipping...
Folder 'GCA_016058495.1_PDT000913427.1' already exists. Skipping...
Folder 'GCA_016058815.1_PDT000913416.1' already exists. Skipping...
Folder 'GCA_016058835.1_PDT000913414.1' already exists. Skipping...
Folder 'GCA_016058895.1_PDT000913412.1' already exists. Skipping...
Folder 'GCA_016059145.1_PDT000913410.1' already exists. Skipping...
Folder 'GCA_016059195.1_PDT000913405.1' already exists. Skipping...
Folder 'GCA_016059215.1_PDT000913411.1' already exists. Skipping...
Folder 'GCA_016059235.1_PDT000913406.1' already exists. Skipping...
Folder 'GCA_016059275.1_PDT000913409.1' already exists. Skipping...
Folder 'GCA_016059295.1_PDT000913403.1' already exists. Skipping...
Folder 'GCA_016059315.1_PDT000913401.1' already exists. Skipping...
Folder 'GCA_016059355.1_PDT000913402.1' already exists. Skipping...
Folder 'GCA_016059375.1_PDT000913398.1' already exists. Skipping...
Folder 'GCA_016059395.1_PDT000913404.1' already exists. Skipping...
Folder 'GCA_016059475.1_PDT000913399.1' already exists. Skipping...
Folder 'GCA_016059495.1_PDT000913394.1' already exists. Skipping...
Folder 'GCA_016059515.1_PDT000913396.1' already exists. Skipping...
Folder 'GCA_016059555.1_PDT000913395.1' already exists. Skipping...
Folder 'GCA_016059575.1_PDT000913387.1' already exists. Skipping...
Folder 'GCA_016059675.1_PDT000913389.1' already exists. Skipping...
Folder 'GCA_016059695.1_PDT000913383.1' already exists. Skipping...
Folder 'GCA_016059755.1_PDT000913382.1' already exists. Skipping...
Folder 'GCA_016059795.1_PDT000913378.1' already exists. Skipping...
Folder 'GCA_016059815.1_PDT000913380.1' already exists. Skipping...
Folder 'GCA_016059955.1_PDT000913374.1' already exists. Skipping...
Folder 'GCA_016059975.1_PDT000913373.1' already exists. Skipping...
Folder 'GCA_016059995.1_PDT000913375.1' already exists. Skipping...
Folder 'GCA_016060235.1_PDT000913359.1' already exists. Skipping...
Folder 'GCA_016060295.1_PDT000913358.1' already exists. Skipping...
Folder 'GCA_016060345.1_PDT000913355.1' already exists. Skipping...
Folder 'GCA_016060415.1_PDT000913354.1' already exists. Skipping...
Folder 'GCA_016060435.1_PDT000913352.1' already exists. Skipping...
Folder 'GCA_016060455.1_PDT000913351.1' already exists. Skipping...
Folder 'GCA_016060475.1_PDT000913350.1' already exists. Skipping...
Folder 'GCA_016060485.1_PDT000913353.1' already exists. Skipping...
Folder 'GCA_016060515.1_PDT000913349.1' already exists. Skipping...
Folder 'GCA_016060535.1_PDT000913347.1' already exists. Skipping...
Folder 'GCA_016060575.1_PDT000913345.1' already exists. Skipping...
Folder 'GCA_016060655.1_PDT000913344.1' already exists. Skipping...
Folder 'GCA_016060675.1_PDT000913343.1' already exists. Skipping...
Folder 'GCA_016060715.1_PDT000913342.1' already exists. Skipping...
Folder 'GCA_016060745.1_PDT000913338.1' already exists. Skipping...
Folder 'GCA_016060775.1_PDT000913336.1' already exists. Skipping...
Folder 'GCA_016060935.1_PDT000913332.1' already exists. Skipping...
Folder 'GCA_016082155.1_PDT000913486.1' already exists. Skipping...
Folder 'GCA_016082195.1_PDT000913479.1' already exists. Skipping...
Folder 'GCA_016082215.1_PDT000913485.1' already exists. Skipping...
Folder 'GCA_016082335.1_PDT000913482.1' already exists. Skipping...
Folder 'GCA_016083295.1_PDT000913488.1' already exists. Skipping...
Folder 'GCA_016103925.1_PDT000914373.1' already exists. Skipping...
Folder 'GCA_016103935.1_PDT000914360.1' already exists. Skipping...
Folder 'GCA_016103965.1_PDT000914363.1' already exists. Skipping...
Folder 'GCA_016104035.1_PDT000914368.1' already exists. Skipping...
Folder 'GCA_016104045.1_PDT000914370.1' already exists. Skipping...
Folder 'GCA_016104085.1_PDT000914366.1' already exists. Skipping...
Folder 'GCA_016104305.1_PDT000914354.1' already exists. Skipping...
Folder 'GCA_016104385.1_PDT000914350.1' already exists. Skipping...
Folder 'GCA_016104445.1_PDT000914347.1' already exists. Skipping...
Folder 'GCA_016112245.1_PDT000914346.1' already exists. Skipping...
Folder 'GCA_016117895.1_PDT000917156.1' already exists. Skipping...
Folder 'GCA_016119715.1_PDT000917222.1' already exists. Skipping...
Folder 'GCA_016120215.1_PDT000917192.1' already exists. Skipping...
Folder 'GCA_016120975.1_PDT000917190.1' already exists. Skipping...
Folder 'GCA_016121555.1_PDT000917229.1' already exists. Skipping...
Folder 'GCA_016121645.1_PDT000917209.1' already exists. Skipping...
Folder 'GCA_016121975.1_PDT000917267.1' already exists. Skipping...
Folder 'GCA_016121985.1_PDT000917199.1' already exists. Skipping...
Folder 'GCA_016122015.1_PDT000917208.1' already exists. Skipping...
Folder 'GCA_016122235.1_PDT000917216.1' already exists. Skipping...
Folder 'GCA_016122255.1_PDT000917214.1' already exists. Skipping...
Folder 'GCA_016122315.1_PDT000917226.1' already exists. Skipping...
Folder 'GCA_016122335.1_PDT000917219.1' already exists. Skipping...
Folder 'GCA_016122355.1_PDT000917198.1' already exists. Skipping...
Folder 'GCA_016122435.1_PDT000917228.1' already exists. Skipping...
Folder 'GCA_016122455.1_PDT000917272.1' already exists. Skipping...
Folder 'GCA_016122475.1_PDT000917188.1' already exists. Skipping...
Folder 'GCA_016122515.1_PDT000917202.1' already exists. Skipping...
Folder 'GCA_016122535.1_PDT000917231.1' already exists. Skipping...
Folder 'GCA_016122555.1_PDT000917194.1' already exists. Skipping...
Folder 'GCA_016122565.1_PDT000917227.1' already exists. Skipping...
Folder 'GCA_016122665.1_PDT000917186.1' already exists. Skipping...
Folder 'GCA_016122715.1_PDT000917212.1' already exists. Skipping...
Folder 'GCA_016122755.1_PDT000917211.1' already exists. Skipping...
Folder 'GCA_016122795.1_PDT000917187.1' already exists. Skipping...
Folder 'GCA_016122975.1_PDT000917230.1' already exists. Skipping...
Folder 'GCA_016122995.1_PDT000917195.1' already exists. Skipping...
Folder 'GCA_016123145.1_PDT000917196.1' already exists. Skipping...
Folder 'GCA_016123175.1_PDT000917205.1' already exists. Skipping...
Folder 'GCA_016141935.1_PDT000919122.1' already exists. Skipping...
Folder 'GCA_016144335.1_PDT000917684.1' already exists. Skipping...
Folder 'GCA_016144375.1_PDT000917683.1' already exists. Skipping...
Folder 'GCA_016144415.1_PDT000917680.1' already exists. Skipping...
Folder 'GCA_016144675.1_PDT000917674.1' already exists. Skipping...
Folder 'GCA_016145355.1_PDT000917645.1' already exists. Skipping...
Folder 'GCA_016146935.1_PDT000917570.1' already exists. Skipping...
Folder 'GCA_016146975.1_PDT000917567.1' already exists. Skipping...
Folder 'GCA_016147495.1_PDT000917516.1' already exists. Skipping...
Folder 'GCA_016148035.1_PDT000917507.1' already exists. Skipping...
Folder 'GCA_016148635.1_PDT000917408.1' already exists. Skipping...
Folder 'GCA_016148655.1_PDT000917413.1' already exists. Skipping...
Folder 'GCA_016148755.1_PDT000917414.1' already exists. Skipping...
Folder 'GCA_016148855.1_PDT000917422.1' already exists. Skipping...
Folder 'GCA_016148875.1_PDT000917403.1' already exists. Skipping...
Folder 'GCA_016148895.1_PDT000917407.1' already exists. Skipping...
Folder 'GCA_016148915.1_PDT000917423.1' already exists. Skipping...
Folder 'GCA_016148955.1_PDT000917415.1' already exists. Skipping...
Folder 'GCA_016149215.1_PDT000917402.1' already exists. Skipping...
Folder 'GCA_016149335.1_PDT000917390.1' already exists. Skipping...
Folder 'GCA_016149395.1_PDT000917396.1' already exists. Skipping...
Folder 'GCA_016149695.1_PDT000917495.1' already exists. Skipping...
Folder 'GCA_016150275.1_PDT000917416.1' already exists. Skipping...
Folder 'GCA_016150835.1_PDT000917400.1' already exists. Skipping...
Folder 'GCA_016151275.1_PDT000917220.1' already exists. Skipping...
Folder 'GCA_016151335.1_PDT000917203.1' already exists. Skipping...
Folder 'GCA_016151375.1_PDT000917388.1' already exists. Skipping...
Folder 'GCA_016151475.1_PDT000917395.1' already exists. Skipping...
Folder 'GCA_016152455.1_PDT000917393.1' already exists. Skipping...
Folder 'GCA_016239435.1_PDT000920007.1' already exists. Skipping...
Folder 'GCA_016241975.1_PDT000920036.1' already exists. Skipping...
Folder 'GCA_016242075.1_PDT000920053.1' already exists. Skipping...
Folder 'GCA_016244635.1_PDT000920030.1' already exists. Skipping...
Folder 'GCA_016244855.1_PDT000920024.1' already exists. Skipping...
Folder 'GCA_016244975.1_PDT000920028.1' already exists. Skipping...
Folder 'GCA_016245215.1_PDT000920042.1' already exists. Skipping...
Folder 'GCA_016245295.1_PDT000920049.1' already exists. Skipping...
Folder 'GCA_016245315.1_PDT000920052.1' already exists. Skipping...
Folder 'GCA_016245615.1_PDT000920019.1' already exists. Skipping...
Folder 'GCA_016245635.1_PDT000920022.1' already exists. Skipping...
Folder 'GCA_016246055.1_PDT000920013.1' already exists. Skipping...
Folder 'GCA_016246095.1_PDT000920014.1' already exists. Skipping...
Folder 'GCA_016246115.1_PDT000920015.1' already exists. Skipping...
Folder 'GCA_016246175.1_PDT000920011.1' already exists. Skipping...
Folder 'GCA_016246235.1_PDT000920006.1' already exists. Skipping...
Folder 'GCA_016246295.1_PDT000920003.1' already exists. Skipping...
Folder 'GCA_016246315.1_PDT000920001.1' already exists. Skipping...
Folder 'GCA_016246355.1_PDT000919998.1' already exists. Skipping...
Folder 'GCA_016246375.1_PDT000920000.1' already exists. Skipping...
Folder 'GCA_016246495.1_PDT000919993.1' already exists. Skipping...
Folder 'GCA_016246515.1_PDT000919989.1' already exists. Skipping...
Folder 'GCA_016246565.1_PDT000919990.1' already exists. Skipping...
Folder 'GCA_016248535.1_PDT000919932.1' already exists. Skipping...
Folder 'GCA_016266985.1_PDT000917672.1' already exists. Skipping...
Folder 'GCA_016313445.1_PDT000921359.1' already exists. Skipping...
Folder 'GCA_016313625.1_PDT000921365.1' already exists. Skipping...
Folder 'GCA_016313685.1_PDT000921369.1' already exists. Skipping...
Folder 'GCA_016332465.1_PDT000922360.1' already exists. Skipping...
Folder 'GCA_016332485.1_PDT000922368.1' already exists. Skipping...
Folder 'GCA_016332525.1_PDT000922364.1' already exists. Skipping...

Retreiveing data: 18854it [00:04, 6624.33it/s]

Folder 'GCA_017899995.1_PDT001003756.1' already exists. Skipping...
Folder 'GCA_017900035.1_PDT001003753.1' already exists. Skipping...
Folder 'GCA_017900155.1_PDT001003747.1' already exists. Skipping...
Folder 'GCA_017900175.1_PDT001003746.1' already exists. Skipping...
Folder 'GCA_017900275.1_PDT001003741.1' already exists. Skipping...
Folder 'GCA_017900295.1_PDT001003739.1' already exists. Skipping...
Folder 'GCA_017905095.1_PDT001002908.1' already exists. Skipping...
Folder 'GCA_017905135.1_PDT001002906.1' already exists. Skipping...
Folder 'GCA_017905235.1_PDT001002901.1' already exists. Skipping...
Folder 'GCA_017905255.1_PDT001002898.1' already exists. Skipping...
Folder 'GCA_017905675.1_PDT001002882.1' already exists. Skipping...
Folder 'GCA_017931135.1_PDT001005016.1' already exists. Skipping...
Folder 'GCA_017931155.1_PDT001005017.1' already exists. Skipping...
Folder 'GCA_017931255.1_PDT001005000.1' already exists. Skipping...
Folder 'GCA_017931355.1_PDT001004978.1' already exists. Skipping...
Folder 'GCA_017931375.1_PDT001004970.1' already exists. Skipping...
Folder 'GCA_017931435.1_PDT001004964.1' already exists. Skipping...
Folder 'GCA_017931515.1_PDT001004957.1' already exists. Skipping...
Folder 'GCA_017931635.1_PDT001004947.1' already exists. Skipping...
Folder 'GCA_017931655.1_PDT001004943.1' already exists. Skipping...
Folder 'GCA_017931675.1_PDT001004942.1' already exists. Skipping...
Folder 'GCA_017931975.1_PDT001005021.1' already exists. Skipping...
Folder 'GCA_017932015.1_PDT001004994.1' already exists. Skipping...
Folder 'GCA_017932035.1_PDT001004998.1' already exists. Skipping...
Folder 'GCA_017932075.1_PDT001004993.1' already exists. Skipping...
Folder 'GCA_017932135.1_PDT001004988.1' already exists. Skipping...
Folder 'GCA_017932155.1_PDT001004979.1' already exists. Skipping...
Folder 'GCA_017932175.1_PDT001004977.1' already exists. Skipping...
Folder 'GCA_017932215.1_PDT001004967.1' already exists. Skipping...
Folder 'GCA_017932235.1_PDT001004951.1' already exists. Skipping...
Folder 'GCA_017932275.1_PDT001004944.1' already exists. Skipping...
Folder 'GCA_017932435.1_PDT001004975.1' already exists. Skipping...
Folder 'GCA_017932495.1_PDT001005007.1' already exists. Skipping...
Folder 'GCA_017932515.1_PDT001004989.1' already exists. Skipping...
Folder 'GCA_017932535.1_PDT001004973.1' already exists. Skipping...
Folder 'GCA_017932555.1_PDT001004968.1' already exists. Skipping...
Folder 'GCA_017932695.1_PDT001005020.1' already exists. Skipping...
Folder 'GCA_017932735.1_PDT001004992.1' already exists. Skipping...
Folder 'GCA_017932755.1_PDT001004999.1' already exists. Skipping...
Folder 'GCA_017932775.1_PDT001005003.1' already exists. Skipping...
Folder 'GCA_017932815.1_PDT001004961.1' already exists. Skipping...
Folder 'GCA_017932935.1_PDT001004945.1' already exists. Skipping...
Folder 'GCA_017933295.1_PDT001005001.1' already exists. Skipping...
Folder 'GCA_017933315.1_PDT001004971.1' already exists. Skipping...
Folder 'GCA_017933335.1_PDT001004997.1' already exists. Skipping...
Folder 'GCA_017933475.1_PDT001005005.1' already exists. Skipping...
Folder 'GCA_017933495.1_PDT001005015.1' already exists. Skipping...
Folder 'GCA_017933515.1_PDT001004996.1' already exists. Skipping...
Folder 'GCA_017933635.1_PDT001005036.1' already exists. Skipping...
Folder 'GCA_017933675.1_PDT001004983.1' already exists. Skipping...
Folder 'GCA_017968445.1_PDT001005773.1' already exists. Skipping...
Folder 'GCA_017968485.1_PDT001005769.1' already exists. Skipping...
Folder 'GCA_017968505.1_PDT001005770.1' already exists. Skipping...
Folder 'GCA_017968565.1_PDT001005767.1' already exists. Skipping...
Folder 'GCA_017968605.1_PDT001005765.1' already exists. Skipping...
Folder 'GCA_017968645.1_PDT001005763.1' already exists. Skipping...
Folder 'GCA_017969405.1_PDT001005731.1' already exists. Skipping...
Folder 'GCA_017969445.1_PDT001005729.1' already exists. Skipping...
Folder 'GCA_017969525.1_PDT001005725.1' already exists. Skipping...
Folder 'GCA_017969555.1_PDT001005723.1' already exists. Skipping...
Folder 'GCA_017969625.1_PDT001005720.1' already exists. Skipping...
Folder 'GCA_017969745.1_PDT001005712.1' already exists. Skipping...
Folder 'GCA_017969765.1_PDT001005714.1' already exists. Skipping...
Folder 'GCA_017969795.1_PDT001005710.1' already exists. Skipping...
Folder 'GCA_017969805.1_PDT001005713.1' already exists. Skipping...
Folder 'GCA_017969865.1_PDT001005706.1' already exists. Skipping...
Folder 'GCA_017969885.1_PDT001005708.1' already exists. Skipping...
Folder 'GCA_017969925.1_PDT001005705.1' already exists. Skipping...
Folder 'GCA_017969945.1_PDT001005704.1' already exists. Skipping...
Folder 'GCA_017969965.1_PDT001005703.1' already exists. Skipping...
Folder 'GCA_017969985.1_PDT001005702.1' already exists. Skipping...
Folder 'GCA_017970925.1_PDT001005655.1' already exists. Skipping...
Folder 'GCA_018008295.1_PDT001006624.1' already exists. Skipping...
Folder 'GCA_018037525.1_PDT001007218.1' already exists. Skipping...
Folder 'GCA_018043645.1_PDT000856789.1' already exists. Skipping...
Folder 'GCA_018045425.1_PDT001007267.1' already exists. Skipping...
Folder 'GCA_018077445.1_PDT001007595.1' already exists. Skipping...
Folder 'GCA_018077505.1_PDT001007593.1' already exists. Skipping...
Folder 'GCA_018077565.1_PDT001007590.1' already exists. Skipping...
Folder 'GCA_018077645.1_PDT001007586.1' already exists. Skipping...
Folder 'GCA_018077785.1_PDT001007581.1' already exists. Skipping...
Folder 'GCA_018077865.1_PDT001007579.1' already exists. Skipping...
Folder 'GCA_018077885.1_PDT001007577.1' already exists. Skipping...
Folder 'GCA_018077905.1_PDT001007576.1' already exists. Skipping...
Folder 'GCA_018077925.1_PDT001007578.1' already exists. Skipping...
Folder 'GCA_018077945.1_PDT001007575.1' already exists. Skipping...
Folder 'GCA_018078025.1_PDT001007573.1' already exists. Skipping...
Folder 'GCA_018078045.1_PDT001007570.1' already exists. Skipping...
Folder 'GCA_018080165.1_PDT001007454.1' already exists. Skipping...
Folder 'GCA_018080225.1_PDT001007451.1' already exists. Skipping...
Folder 'GCA_018080245.1_PDT001007448.1' already exists. Skipping...
Folder 'GCA_018080265.1_PDT001007449.1' already exists. Skipping...
Folder 'GCA_018080285.1_PDT001007445.1' already exists. Skipping...
Folder 'GCA_018080325.1_PDT001007443.1' already exists. Skipping...
Folder 'GCA_018096505.1_PDT001008701.1' already exists. Skipping...
Folder 'GCA_018096545.1_PDT001008703.1' already exists. Skipping...
Folder 'GCA_018096565.1_PDT001008698.1' already exists. Skipping...
Folder 'GCA_018097045.1_PDT001008700.1' already exists. Skipping...
Folder 'GCA_018099785.1_PDT001008704.1' already exists. Skipping...
Folder 'GCA_018107085.1_PDT001009541.1' already exists. Skipping...
Folder 'GCA_018107325.1_PDT001009560.1' already exists. Skipping...
Folder 'GCA_018107385.1_PDT001009556.1' already exists. Skipping...
Folder 'GCA_018107405.1_PDT001009547.1' already exists. Skipping...
Folder 'GCA_018107445.1_PDT001009540.1' already exists. Skipping...
Folder 'GCA_018107605.1_PDT001009490.1' already exists. Skipping...
Folder 'GCA_018107625.1_PDT001009485.1' already exists. Skipping...
Folder 'GCA_018107845.1_PDT001009563.1' already exists. Skipping...
Folder 'GCA_018107895.1_PDT001009513.1' already exists. Skipping...
Folder 'GCA_018107975.1_PDT001009566.1' already exists. Skipping...
Folder 'GCA_018109485.1_PDT001009545.1' already exists. Skipping...
Folder 'GCA_018109525.1_PDT001009509.1' already exists. Skipping...
Folder 'GCA_018109725.1_PDT001009521.1' already exists. Skipping...
Folder 'GCA_018110085.1_PDT001009564.1' already exists. Skipping...
Folder 'GCA_018110125.1_PDT001009558.1' already exists. Skipping...
Folder 'GCA_018110185.1_PDT001009551.1' already exists. Skipping...
Folder 'GCA_018110245.1_PDT001009529.1' already exists. Skipping...
Folder 'GCA_018110265.1_PDT001009531.1' already exists. Skipping...
Folder 'GCA_018110305.1_PDT001009533.1' already exists. Skipping...
Folder 'GCA_018110325.1_PDT001009528.1' already exists. Skipping...
Folder 'GCA_018111125.1_PDT001009567.1' already exists. Skipping...
Folder 'GCA_018111145.1_PDT001009565.1' already exists. Skipping...
Folder 'GCA_018111165.1_PDT001009552.1' already exists. Skipping...
Folder 'GCA_018111205.1_PDT001009550.1' already exists. Skipping...
Folder 'GCA_018111225.1_PDT001009562.1' already exists. Skipping...
Folder 'GCA_018111285.1_PDT001009527.1' already exists. Skipping...
Folder 'GCA_018113805.1_PDT001009795.1' already exists. Skipping...
Folder 'GCA_018113845.1_PDT001009794.1' already exists. Skipping...
Folder 'GCA_018119535.1_PDT001010728.1' already exists. Skipping...
Folder 'GCA_018121055.1_PDT001010783.1' already exists. Skipping...
Folder 'GCA_018121175.1_PDT001010775.1' already exists. Skipping...
Folder 'GCA_018125485.1_PDT001010781.1' already exists. Skipping...
Folder 'GCA_018128665.1_PDT001011049.1' already exists. Skipping...
Folder 'GCA_018129125.1_PDT001011040.1' already exists. Skipping...
Folder 'GCA_018129165.1_PDT001011042.1' already exists. Skipping...
Folder 'GCA_018136055.1_PDT001011758.1' already exists. Skipping...
Folder 'GCA_018136075.1_PDT001011760.1' already exists. Skipping...
Folder 'GCA_018169215.1_ASM1816921v1' already exists. Skipping...
Folder 'GCA_018171635.1_PDT001012028.1' already exists. Skipping...
Folder 'GCA_018171675.1_PDT001012026.1' already exists. Skipping...
Folder 'GCA_018173555.1_PDT001014370.1' already exists. Skipping...
Folder 'GCA_018173575.1_PDT001014369.1' already exists. Skipping...
Folder 'GCA_018174535.1_PDT001014378.1' already exists. Skipping...
Folder 'GCA_018174575.1_PDT001014377.1' already exists. Skipping...
Folder 'GCA_018174595.1_PDT001014374.1' already exists. Skipping...
Folder 'GCA_018174635.1_PDT001014366.1' already exists. Skipping...
Folder 'GCA_018174655.1_PDT001014363.1' already exists. Skipping...
Folder 'GCA_018174675.1_PDT001014322.1' already exists. Skipping...
Folder 'GCA_018175935.1_PDT000634283.2' already exists. Skipping...
Folder 'GCA_018176015.1_PDT001014414.1' already exists. Skipping...
Folder 'GCA_018176035.1_PDT001014412.1' already exists. Skipping...
Folder 'GCA_018176195.1_PDT001014410.1' already exists. Skipping...
Folder 'GCA_018176395.1_PDT000640604.2' already exists. Skipping...
Folder 'GCA_018176455.1_PDT000634278.2' already exists. Skipping...
Folder 'GCA_018176595.1_PDT001014413.1' already exists. Skipping...
Folder 'GCA_018176635.1_PDT001014411.1' already exists. Skipping...
Folder 'GCA_018176795.1_PDT000634279.2' already exists. Skipping...
Folder 'GCA_018177615.1_PDT001014376.1' already exists. Skipping...
Folder 'GCA_018177635.1_PDT001014375.1' already exists. Skipping...
Folder 'GCA_018177895.1_PDT001014379.1' already exists. Skipping...
Folder 'GCA_018177935.1_PDT001014364.1' already exists. Skipping...
Folder 'GCA_018178715.1_PDT001014513.1' already exists. Skipping...
Folder 'GCA_018178735.1_PDT001014496.1' already exists. Skipping...
Folder 'GCA_018178855.1_PDT001014505.1' already exists. Skipping...
Folder 'GCA_018178915.1_PDT001014511.1' already exists. Skipping...
Folder 'GCA_018178955.1_PDT001014510.1' already exists. Skipping...
Folder 'GCA_018179035.1_PDT001014502.1' already exists. Skipping...
Folder 'GCA_018179195.1_PDT001014486.1' already exists. Skipping...
Folder 'GCA_018179355.1_PDT001014487.1' already exists. Skipping...
Folder 'GCA_018179735.1_PDT001014512.1' already exists. Skipping...
Folder 'GCA_018179915.1_PDT001014507.1' already exists. Skipping...
Folder 'GCA_018182695.1_PDT001014537.1' already exists. Skipping...
Folder 'GCA_018196695.1_PDT001015912.1' already exists. Skipping...
Folder 'GCA_018196715.1_PDT001015911.1' already exists. Skipping...
Folder 'GCA_018196735.1_PDT001015909.1' already exists. Skipping...
Folder 'GCA_018196775.1_PDT001015908.1' already exists. Skipping...
Folder 'GCA_018196795.1_PDT001015910.1' already exists. Skipping...
Folder 'GCA_018196815.1_PDT001015906.1' already exists. Skipping...
Folder 'GCA_018196855.1_PDT001015903.1' already exists. Skipping...
Folder 'GCA_018196895.1_PDT001015901.1' already exists. Skipping...
Folder 'GCA_018197615.1_PDT001015896.1' already exists. Skipping...
Folder 'GCA_018207695.1_PDT001016101.1' already exists. Skipping...
Folder 'GCA_018207715.1_PDT001016112.1' already exists. Skipping...
Folder 'GCA_018207735.1_PDT001016107.1' already exists. Skipping...
Folder 'GCA_018207915.1_PDT001016110.1' already exists. Skipping...
Folder 'GCA_018215975.1_PDT001016436.1' already exists. Skipping...
Folder 'GCA_018216635.1_PDT001016439.1' already exists. Skipping...
Folder 'GCA_018216655.1_PDT001016437.1' already exists. Skipping...
Folder 'GCA_018216675.1_PDT001016435.1' already exists. Skipping...
Folder 'GCA_018216695.1_PDT001016434.1' already exists. Skipping...
Folder 'GCA_018216715.1_PDT001016433.1' already exists. Skipping...
Folder 'GCA_018218375.1_PDT001016313.1' already exists. Skipping...
Folder 'GCA_018220135.1_PDT001016541.1' already exists. Skipping...
Folder 'GCA_018220295.1_PDT001016536.1' already exists. Skipping...
Folder 'GCA_018220655.1_PDT001016560.1' already exists. Skipping...
Folder 'GCA_018220695.1_PDT001016553.1' already exists. Skipping...
Folder 'GCA_018220715.1_PDT001016544.1' already exists. Skipping...
Folder 'GCA_018221845.1_PDT001016556.1' already exists. Skipping...
Folder 'GCA_018221945.1_PDT001016549.1' already exists. Skipping...
Folder 'GCA_018221965.1_PDT001016550.1' already exists. Skipping...
Folder 'GCA_018222225.1_PDT001016542.1' already exists. Skipping...
Folder 'GCA_018225045.1_PDT001016555.1' already exists. Skipping...
Folder 'GCA_018225055.1_PDT001016548.1' already exists. Skipping...
Folder 'GCA_018225085.1_PDT001016551.1' already exists. Skipping...
Folder 'GCA_018239965.1_PDT001017827.1' already exists. Skipping...
Folder 'GCA_018244365.1_PDT001017990.1' already exists. Skipping...
Folder 'GCA_018254615.1_PDT001018101.1' already exists. Skipping...
Folder 'GCA_018258335.1_PDT001018266.1' already exists. Skipping...
Folder 'GCA_018258415.1_PDT001018254.1' already exists. Skipping...
Folder 'GCA_018282495.1_PDT001019041.1' already exists. Skipping...
Folder 'GCA_018282515.1_PDT001019040.1' already exists. Skipping...
Folder 'GCA_018282535.1_PDT001019046.1' already exists. Skipping...
Folder 'GCA_018282605.1_PDT001019037.1' already exists. Skipping...
Folder 'GCA_018282635.1_PDT001019036.1' already exists. Skipping...
Folder 'GCA_018282655.1_PDT001019031.1' already exists. Skipping...
Folder 'GCA_018282675.1_PDT001019034.1' already exists. Skipping...
Folder 'GCA_018282755.1_PDT001019023.1' already exists. Skipping...
Folder 'GCA_018283055.1_PDT001019024.1' already exists. Skipping...
Folder 'GCA_018290455.1_PDT001019169.1' already exists. Skipping...
Folder 'GCA_018291925.1_PDT001019095.1' already exists. Skipping...
Folder 'GCA_018293085.1_PDT001019042.1' already exists. Skipping...
Folder 'GCA_018293105.1_PDT001019035.1' already exists. Skipping...
Folder 'GCA_018296505.1_PDT001021451.1' already exists. Skipping...
Folder 'GCA_018300005.1_PDT001021647.1' already exists. Skipping...
Folder 'GCA_018300045.1_PDT001021645.1' already exists. Skipping...
Folder 'GCA_018300085.1_PDT001021642.1' already exists. Skipping...
Folder 'GCA_018300125.1_PDT001021641.1' already exists. Skipping...
Folder 'GCA_018300185.1_PDT001021638.1' already exists. Skipping...
Folder 'GCA_018300265.1_PDT001021635.1' already exists. Skipping...
Folder 'GCA_018300305.1_PDT001021631.1' already exists. Skipping...
Folder 'GCA_018300325.1_PDT001021632.1' already exists. Skipping...
Folder 'GCA_018300345.1_PDT001021629.1' already exists. Skipping...
Folder 'GCA_018300385.1_PDT001021630.1' already exists. Skipping...
Folder 'GCA_018300425.1_PDT001021626.1' already exists. Skipping...
Folder 'GCA_018300445.1_PDT001021625.1' already exists. Skipping...
Folder 'GCA_018300465.1_PDT001021621.1' already exists. Skipping...
Folder 'GCA_018300505.1_PDT001021620.1' already exists. Skipping...
Folder 'GCA_018300525.1_PDT001021623.1' already exists. Skipping...
Folder 'GCA_018300545.1_PDT001021618.1' already exists. Skipping...
Folder 'GCA_018301125.1_PDT001021589.1' already exists. Skipping...
Folder 'GCA_018301285.1_PDT001021582.1' already exists. Skipping...
Folder 'GCA_018301305.1_PDT001021581.1' already exists. Skipping...
Folder 'GCA_018301325.1_PDT001021580.1' already exists. Skipping...
Folder 'GCA_018308605.1_PDT001021954.1' already exists. Skipping...
Folder 'GCA_018309625.1_PDT001021448.1' already exists. Skipping...
Folder 'GCA_018339315.1_PDT001021622.1' already exists. Skipping...
Folder 'GCA_018354125.1_PDT001025876.1' already exists. Skipping...
Folder 'GCA_018354185.1_PDT001025874.1' already exists. Skipping...
Folder 'GCA_018354265.1_PDT001025870.1' already exists. Skipping...
Folder 'GCA_018354285.1_PDT001025869.1' already exists. Skipping...
Folder 'GCA_018354385.1_PDT001025865.1' already exists. Skipping...
Folder 'GCA_018355805.1_PDT001025712.1' already exists. Skipping...
Folder 'GCA_018355925.1_PDT001025713.1' already exists. Skipping...
Folder 'GCA_018356265.1_PDT001025694.1' already exists. Skipping...
Folder 'GCA_018356345.1_PDT001025690.1' already exists. Skipping...
Folder 'GCA_018356545.1_PDT001025684.1' already exists. Skipping...
Folder 'GCA_018361895.1_PDT001026012.1' already exists. Skipping...
Folder 'GCA_018362075.1_PDT001026020.1' already exists. Skipping...
Folder 'GCA_018362095.1_PDT001026019.1' already exists. Skipping...
Folder 'GCA_018362115.1_PDT001026018.1' already exists. Skipping...
Folder 'GCA_018362135.1_PDT001026016.1' already exists. Skipping...
Folder 'GCA_018362555.1_PDT001026017.1' already exists. Skipping...
Folder 'GCA_018389525.1_PDT001028955.1' already exists. Skipping...
Folder 'GCA_018392895.1_PDT001040567.1' already exists. Skipping...
Folder 'GCA_018406045.1_PDT001042047.1' already exists. Skipping...
Folder 'GCA_018415265.1_PDT001042898.1' already exists. Skipping...
Folder 'GCA_018451285.1_PDT001044940.1' already exists. Skipping...
Folder 'GCA_018451345.1_PDT001044936.1' already exists. Skipping...
Folder 'GCA_018451385.1_PDT001044935.1' already exists. Skipping...
Folder 'GCA_018451405.1_PDT001044933.1' already exists. Skipping...
Folder 'GCA_018451445.1_PDT001044931.1' already exists. Skipping...
Folder 'GCA_018451465.1_PDT001044930.1' already exists. Skipping...
Folder 'GCA_018451545.1_PDT001044925.1' already exists. Skipping...
Folder 'GCA_018451565.1_PDT001044926.1' already exists. Skipping...
Folder 'GCA_018451605.1_PDT001044924.1' already exists. Skipping...
Folder 'GCA_018451625.1_PDT001044922.1' already exists. Skipping...
Folder 'GCA_018451665.1_PDT001044917.1' already exists. Skipping...
Folder 'GCA_018451705.1_PDT001044910.1' already exists. Skipping...
Folder 'GCA_018451765.1_PDT001044906.1' already exists. Skipping...
Folder 'GCA_018451785.1_PDT001044916.1' already exists. Skipping...
Folder 'GCA_018451805.1_PDT001044918.1' already exists. Skipping...
Folder 'GCA_018451825.1_PDT001044911.1' already exists. Skipping...
Folder 'GCA_018451845.1_PDT001044913.1' already exists. Skipping...
Folder 'GCA_018451905.1_PDT001044905.1' already exists. Skipping...
Folder 'GCA_018451925.1_PDT001044901.1' already exists. Skipping...
Folder 'GCA_018451945.1_PDT001044902.1' already exists. Skipping...
Folder 'GCA_018451965.1_PDT001044903.1' already exists. Skipping...
Folder 'GCA_018451985.1_PDT001044900.1' already exists. Skipping...
Folder 'GCA_018451995.1_PDT001044899.1' already exists. Skipping...
Folder 'GCA_018452045.1_PDT001044896.1' already exists. Skipping...
Folder 'GCA_018452065.1_PDT001044898.1' already exists. Skipping...
Folder 'GCA_018452085.1_PDT001044893.1' already exists. Skipping...
Folder 'GCA_018452305.1_PDT001044920.1' already exists. Skipping...
Folder 'GCA_018453065.1_PDT001044846.1' already exists. Skipping...
Folder 'GCA_018453105.1_PDT001044844.1' already exists. Skipping...

Retreiveing data: 20191it [00:04, 6658.12it/s]

Folder 'GCA_019759895.1_PDT001116768.1' already exists. Skipping...
Folder 'GCA_019759915.1_PDT001116770.1' already exists. Skipping...
Folder 'GCA_019760015.1_PDT001116793.1' already exists. Skipping...
Folder 'GCA_019760025.1_PDT001116779.1' already exists. Skipping...
Folder 'GCA_019760095.1_PDT001116767.1' already exists. Skipping...
Folder 'GCA_019760155.1_PDT001116798.1' already exists. Skipping...
Folder 'GCA_019761055.1_PDT001116804.1' already exists. Skipping...
Folder 'GCA_019761155.1_PDT001116802.1' already exists. Skipping...
Folder 'GCA_019761175.1_PDT001116856.1' already exists. Skipping...
Folder 'GCA_019761195.1_PDT001116852.1' already exists. Skipping...
Folder 'GCA_019761255.1_PDT001116851.1' already exists. Skipping...
Folder 'GCA_019761295.1_PDT001116846.1' already exists. Skipping...
Folder 'GCA_019761335.1_PDT001116843.1' already exists. Skipping...
Folder 'GCA_019761395.1_PDT001116840.1' already exists. Skipping...
Folder 'GCA_019761615.1_PDT001116837.1' already exists. Skipping...
Folder 'GCA_019762155.1_PDT001116847.1' already exists. Skipping...
Folder 'GCA_019762265.1_PDT001116833.1' already exists. Skipping...
Folder 'GCA_019762295.1_PDT001116780.1' already exists. Skipping...
Folder 'GCA_019772215.1_PDT001116850.1' already exists. Skipping...
Folder 'GCA_019773695.1_PDT001116875.1' already exists. Skipping...
Folder 'GCA_019773755.1_PDT001116871.1' already exists. Skipping...
Folder 'GCA_019773795.1_PDT001116873.1' already exists. Skipping...
Folder 'GCA_019773815.1_PDT001116869.1' already exists. Skipping...
Folder 'GCA_019777665.1_PDT001117153.1' already exists. Skipping...
Folder 'GCA_019777685.1_PDT001117155.1' already exists. Skipping...
Folder 'GCA_019777725.1_PDT001117156.1' already exists. Skipping...
Folder 'GCA_019777785.1_PDT001117201.1' already exists. Skipping...
Folder 'GCA_019777865.1_PDT001117194.1' already exists. Skipping...
Folder 'GCA_019777905.1_PDT001117185.1' already exists. Skipping...
Folder 'GCA_019777945.1_PDT001117180.1' already exists. Skipping...
Folder 'GCA_019777965.1_PDT001117174.1' already exists. Skipping...
Folder 'GCA_019778345.1_PDT001117172.1' already exists. Skipping...
Folder 'GCA_019778395.1_PDT001117159.1' already exists. Skipping...
Folder 'GCA_019780785.1_PDT001117165.1' already exists. Skipping...
Folder 'GCA_019784285.1_PDT001117179.1' already exists. Skipping...
Folder 'GCA_019787505.1_PDT001117858.1' already exists. Skipping...
Folder 'GCA_019789595.1_PDT001118015.1' already exists. Skipping...
Folder 'GCA_019789635.1_PDT001118017.1' already exists. Skipping...
Folder 'GCA_019789675.1_PDT001118014.1' already exists. Skipping...
Folder 'GCA_019789735.1_PDT001118010.1' already exists. Skipping...
Folder 'GCA_019789775.1_PDT001118008.1' already exists. Skipping...
Folder 'GCA_019789815.1_PDT001118000.1' already exists. Skipping...
Folder 'GCA_019789835.1_PDT001117994.1' already exists. Skipping...
Folder 'GCA_019789875.1_PDT001117998.1' already exists. Skipping...
Folder 'GCA_019789915.1_PDT001117992.1' already exists. Skipping...
Folder 'GCA_019789935.1_PDT001117993.1' already exists. Skipping...
Folder 'GCA_019789975.1_PDT001117988.1' already exists. Skipping...
Folder 'GCA_019789995.1_PDT001117989.1' already exists. Skipping...
Folder 'GCA_019790035.1_PDT001117986.1' already exists. Skipping...
Folder 'GCA_019790055.1_PDT001117984.1' already exists. Skipping...
Folder 'GCA_019791335.1_PDT001118151.1' already exists. Skipping...
Folder 'GCA_019803095.1_PDT001118938.1' already exists. Skipping...
Folder 'GCA_019803135.1_PDT001118941.1' already exists. Skipping...
Folder 'GCA_019803155.1_PDT001118939.1' already exists. Skipping...
Folder 'GCA_019803335.1_PDT001118900.1' already exists. Skipping...
Folder 'GCA_019803415.1_PDT001118945.1' already exists. Skipping...
Folder 'GCA_019803475.1_PDT001118963.1' already exists. Skipping...
Folder 'GCA_019803565.1_PDT001118960.1' already exists. Skipping...
Folder 'GCA_019803645.1_PDT001118957.1' already exists. Skipping...
Folder 'GCA_019803685.1_PDT001118955.1' already exists. Skipping...
Folder 'GCA_019803745.1_PDT001118940.1' already exists. Skipping...
Folder 'GCA_019804365.1_PDT001118967.1' already exists. Skipping...
Folder 'GCA_019812995.1_PDT001119592.1' already exists. Skipping...
Folder 'GCA_019814465.1_PDT001119707.1' already exists. Skipping...
Folder 'GCA_019814505.1_PDT001119687.1' already exists. Skipping...
Folder 'GCA_019814525.1_PDT001119712.1' already exists. Skipping...
Folder 'GCA_019815485.1_PDT001119727.1' already exists. Skipping...
Folder 'GCA_019815545.1_PDT001119711.1' already exists. Skipping...
Folder 'GCA_019815585.1_PDT001119702.1' already exists. Skipping...
Folder 'GCA_019816665.1_PDT001119896.1' already exists. Skipping...
Folder 'GCA_019816685.1_PDT001119891.1' already exists. Skipping...
Folder 'GCA_019816725.1_PDT001119822.1' already exists. Skipping...
Folder 'GCA_019817085.1_PDT001119918.1' already exists. Skipping...
Folder 'GCA_019817105.1_PDT001119912.1' already exists. Skipping...
Folder 'GCA_019817165.1_PDT001119901.1' already exists. Skipping...
Folder 'GCA_019818325.1_PDT001119898.1' already exists. Skipping...
Folder 'GCA_019819305.1_PDT001119910.1' already exists. Skipping...
Folder 'GCA_019825415.1_PDT001119916.1' already exists. Skipping...
Folder 'GCA_019825465.1_PDT001119911.1' already exists. Skipping...
Folder 'GCA_019825485.1_PDT001119907.1' already exists. Skipping...
Folder 'GCA_019825585.1_PDT001119899.1' already exists. Skipping...
Folder 'GCA_019825645.1_PDT001119894.1' already exists. Skipping...
Folder 'GCA_019829045.1_PDT001119726.1' already exists. Skipping...
Folder 'GCA_019829125.1_PDT001119714.1' already exists. Skipping...
Folder 'GCA_019829385.1_PDT001119692.1' already exists. Skipping...
Folder 'GCA_019829485.1_PDT001119681.1' already exists. Skipping...
Folder 'GCA_019831225.1_PDT000967721.1' already exists. Skipping...
Folder 'GCA_019831785.1_PDT001120406.1' already exists. Skipping...
Folder 'GCA_019845375.1_PDT000967724.1' already exists. Skipping...
Folder 'GCA_019845515.1_PDT001120364.1' already exists. Skipping...
Folder 'GCA_019847735.1_PDT001121105.1' already exists. Skipping...
Folder 'GCA_019850665.1_PDT001115501.2' already exists. Skipping...
Folder 'GCA_019859015.1_PDT001122281.1' already exists. Skipping...
Folder 'GCA_019859085.1_PDT001122292.1' already exists. Skipping...
Folder 'GCA_019859125.1_PDT001122291.1' already exists. Skipping...
Folder 'GCA_019860405.1_PDT001122288.1' already exists. Skipping...
Folder 'GCA_019862445.1_PDT001122295.1' already exists. Skipping...
Folder 'GCA_019863305.1_PDT001122301.1' already exists. Skipping...
Folder 'GCA_019863625.1_PDT001122294.1' already exists. Skipping...
Folder 'GCA_019866625.1_PDT001122305.1' already exists. Skipping...
Folder 'GCA_019866645.1_PDT001122303.1' already exists. Skipping...
Folder 'GCA_019867505.1_PDT001122304.1' already exists. Skipping...
Folder 'GCA_019867565.1_PDT001122298.1' already exists. Skipping...
Folder 'GCA_019867625.1_PDT001122290.1' already exists. Skipping...
Folder 'GCA_019870905.1_PDT001122620.1' already exists. Skipping...
Folder 'GCA_019873845.1_PDT001122679.1' already exists. Skipping...
Folder 'GCA_019892315.1_PDT001087865.1' already exists. Skipping...
Folder 'GCA_019893805.1_PDT001044915.1' already exists. Skipping...
Folder 'GCA_019898395.1_PDT001125158.1' already exists. Skipping...
Folder 'GCA_019898485.1_PDT001125161.1' already exists. Skipping...
Folder 'GCA_019898865.1_PDT001125233.1' already exists. Skipping...
Folder 'GCA_019898945.1_PDT001125230.1' already exists. Skipping...
Folder 'GCA_019898985.1_PDT001125231.1' already exists. Skipping...
Folder 'GCA_019899025.1_PDT001125229.1' already exists. Skipping...
Folder 'GCA_019899045.1_PDT001125226.1' already exists. Skipping...
Folder 'GCA_019899265.1_PDT001125215.1' already exists. Skipping...
Folder 'GCA_019899405.1_PDT001125207.1' already exists. Skipping...
Folder 'GCA_019899705.1_PDT001125189.1' already exists. Skipping...
Folder 'GCA_019899785.1_PDT001125188.1' already exists. Skipping...
Folder 'GCA_019900105.1_PDT001125247.1' already exists. Skipping...
Folder 'GCA_019900145.1_PDT001125248.1' already exists. Skipping...
Folder 'GCA_019900165.1_PDT001125243.1' already exists. Skipping...
Folder 'GCA_019900425.1_PDT001125304.1' already exists. Skipping...
Folder 'GCA_019900545.1_PDT001125292.1' already exists. Skipping...
Folder 'GCA_019900565.1_PDT001125283.1' already exists. Skipping...
Folder 'GCA_019900665.1_PDT001125269.1' already exists. Skipping...
Folder 'GCA_019900685.1_PDT001125265.1' already exists. Skipping...
Folder 'GCA_019900925.1_PDT001125299.1' already exists. Skipping...
Folder 'GCA_019906995.1_PDT001125756.1' already exists. Skipping...
Folder 'GCA_019907015.1_PDT001125754.1' already exists. Skipping...
Folder 'GCA_019908735.1_PDT001125765.1' already exists. Skipping...
Folder 'GCA_019908795.1_PDT001125760.1' already exists. Skipping...
Folder 'GCA_019909125.1_PDT001125764.1' already exists. Skipping...
Folder 'GCA_019916105.1_PDT001125767.1' already exists. Skipping...
Folder 'GCA_019916135.1_PDT001125778.1' already exists. Skipping...
Folder 'GCA_019916165.1_PDT001125781.1' already exists. Skipping...
Folder 'GCA_019916185.1_PDT001125766.1' already exists. Skipping...
Folder 'GCA_019916245.1_PDT001125762.1' already exists. Skipping...
Folder 'GCA_019916285.1_PDT001125759.1' already exists. Skipping...
Folder 'GCA_019916305.1_PDT001125836.1' already exists. Skipping...
Folder 'GCA_019916325.1_PDT001125833.1' already exists. Skipping...
Folder 'GCA_019916365.1_PDT001125826.1' already exists. Skipping...
Folder 'GCA_019916405.1_PDT001125823.1' already exists. Skipping...
Folder 'GCA_019916425.1_PDT001125830.1' already exists. Skipping...
Folder 'GCA_019916465.1_PDT001125820.1' already exists. Skipping...
Folder 'GCA_019916505.1_PDT001125821.1' already exists. Skipping...
Folder 'GCA_019916565.1_PDT001125837.1' already exists. Skipping...
Folder 'GCA_019916665.1_PDT001125828.1' already exists. Skipping...
Folder 'GCA_019916705.1_PDT001125824.1' already exists. Skipping...
Folder 'GCA_019959855.1_PDT001126429.1' already exists. Skipping...
Folder 'GCA_019960275.1_PDT001126407.1' already exists. Skipping...
Folder 'GCA_019962835.1_PDT001129109.1' already exists. Skipping...
Folder 'GCA_019962895.1_PDT001129099.1' already exists. Skipping...
Folder 'GCA_019962905.1_PDT001129100.1' already exists. Skipping...
Folder 'GCA_019966475.1_PDT001129406.1' already exists. Skipping...
Folder 'GCA_019966615.1_PDT001129404.1' already exists. Skipping...
Folder 'GCA_019966655.1_PDT001129390.1' already exists. Skipping...
Folder 'GCA_019966715.1_PDT001129405.1' already exists. Skipping...
Folder 'GCA_019966735.1_PDT001129396.1' already exists. Skipping...
Folder 'GCA_019966795.1_PDT001129395.1' already exists. Skipping...
Folder 'GCA_019966815.1_PDT001129388.1' already exists. Skipping...
Folder 'GCA_019966835.1_PDT001129386.1' already exists. Skipping...
Folder 'GCA_019967155.1_PDT001129403.1' already exists. Skipping...
Folder 'GCA_019967195.1_PDT001129387.1' already exists. Skipping...
Folder 'GCA_019967235.1_PDT001129398.1' already exists. Skipping...
Folder 'GCA_019967295.1_PDT001129402.1' already exists. Skipping...
Folder 'GCA_019993285.1_PDT001130262.1' already exists. Skipping...
Folder 'GCA_019993345.1_PDT001130264.1' already exists. Skipping...
Folder 'GCA_019993385.1_PDT001130263.1' already exists. Skipping...
Folder 'GCA_019994305.1_PDT001130207.1' already exists. Skipping...
Folder 'GCA_019998845.1_PDT001130329.1' already exists. Skipping...
Folder 'GCA_019998945.1_PDT001130320.1' already exists. Skipping...
Folder 'GCA_019998995.1_PDT001130304.1' already exists. Skipping...
Folder 'GCA_019999205.1_PDT001130268.1' already exists. Skipping...
Folder 'GCA_019999225.1_PDT001130276.1' already exists. Skipping...
Folder 'GCA_019999305.1_PDT001130280.1' already exists. Skipping...
Folder 'GCA_019999325.1_PDT001130345.1' already exists. Skipping...
Folder 'GCA_019999405.1_PDT001130270.1' already exists. Skipping...
Folder 'GCA_019999425.1_PDT001130346.1' already exists. Skipping...
Folder 'GCA_019999465.1_PDT001130330.1' already exists. Skipping...
Folder 'GCA_019999485.1_PDT001130325.1' already exists. Skipping...
Folder 'GCA_019999505.1_PDT001130337.1' already exists. Skipping...
Folder 'GCA_019999565.1_PDT001130335.1' already exists. Skipping...
Folder 'GCA_019999585.1_PDT001130290.1' already exists. Skipping...
Folder 'GCA_020000105.1_PDT001130369.1' already exists. Skipping...
Folder 'GCA_020000165.1_PDT001130365.1' already exists. Skipping...
Folder 'GCA_020000225.1_PDT001130363.1' already exists. Skipping...
Folder 'GCA_020000245.1_PDT001130364.1' already exists. Skipping...
Folder 'GCA_020000265.1_PDT001130359.1' already exists. Skipping...
Folder 'GCA_020000285.1_PDT001130361.1' already exists. Skipping...
Folder 'GCA_020000325.1_PDT001130362.1' already exists. Skipping...
Folder 'GCA_020000365.1_PDT001130356.1' already exists. Skipping...
Folder 'GCA_020005805.1_PDT001130573.1' already exists. Skipping...
Folder 'GCA_020005815.1_PDT001130574.1' already exists. Skipping...
Folder 'GCA_020005845.1_PDT001130571.1' already exists. Skipping...
Folder 'GCA_020005865.1_PDT001130572.1' already exists. Skipping...
Folder 'GCA_020005885.1_PDT001130570.1' already exists. Skipping...
Folder 'GCA_020005905.1_PDT001130567.1' already exists. Skipping...
Folder 'GCA_020005925.1_PDT001130568.1' already exists. Skipping...
Folder 'GCA_020005945.1_PDT001130569.1' already exists. Skipping...
Folder 'GCA_020005965.1_PDT001130564.1' already exists. Skipping...
Folder 'GCA_020005985.1_PDT001130566.1' already exists. Skipping...
Folder 'GCA_020006005.1_PDT001130565.1' already exists. Skipping...
Folder 'GCA_020006185.1_PDT001130549.1' already exists. Skipping...
Folder 'GCA_020006205.1_PDT001130548.1' already exists. Skipping...
Folder 'GCA_020006225.1_PDT001130547.1' already exists. Skipping...
Folder 'GCA_020006245.1_PDT001130546.1' already exists. Skipping...
Folder 'GCA_020006265.1_PDT001130544.1' already exists. Skipping...
Folder 'GCA_020006305.1_PDT001130543.1' already exists. Skipping...
Folder 'GCA_020006405.1_PDT001130545.1' already exists. Skipping...
Folder 'GCA_020012195.1_PDT001130870.1' already exists. Skipping...
Folder 'GCA_020012215.1_PDT001131121.1' already exists. Skipping...
Folder 'GCA_020012555.1_PDT001131135.1' already exists. Skipping...
Folder 'GCA_020016015.1_PDT001131123.1' already exists. Skipping...
Folder 'GCA_020017515.1_PDT001131295.1' already exists. Skipping...
Folder 'GCA_020017575.1_PDT001131293.1' already exists. Skipping...
Folder 'GCA_020017595.1_PDT001131294.1' already exists. Skipping...
Folder 'GCA_020017635.1_PDT001131289.1' already exists. Skipping...
Folder 'GCA_020017735.1_PDT001131280.1' already exists. Skipping...
Folder 'GCA_020018235.1_PDT001131217.1' already exists. Skipping...
Folder 'GCA_020018255.1_PDT001131216.1' already exists. Skipping...
Folder 'GCA_020021235.1_PDT001131435.1' already exists. Skipping...
Folder 'GCA_020023955.1_PDT001131563.1' already exists. Skipping...
Folder 'GCA_020023975.1_PDT001131562.1' already exists. Skipping...
Folder 'GCA_020030135.1_PDT001131601.1' already exists. Skipping...
Folder 'GCA_020030195.1_PDT001131615.1' already exists. Skipping...
Folder 'GCA_020030215.1_PDT001131614.1' already exists. Skipping...
Folder 'GCA_020064765.1_PDT001133705.1' already exists. Skipping...
Folder 'GCA_020064845.1_PDT001133711.1' already exists. Skipping...
Folder 'GCA_020064965.1_PDT001133716.1' already exists. Skipping...
Folder 'GCA_020064985.1_PDT001133709.1' already exists. Skipping...
Folder 'GCA_020065025.1_PDT001133712.1' already exists. Skipping...
Folder 'GCA_020065525.1_PDT001133786.1' already exists. Skipping...
Folder 'GCA_020065545.1_PDT001133816.1' already exists. Skipping...
Folder 'GCA_020065565.1_PDT001133782.1' already exists. Skipping...
Folder 'GCA_020065575.1_PDT001133796.1' already exists. Skipping...
Folder 'GCA_020065605.1_PDT001133784.1' already exists. Skipping...
Folder 'GCA_020065685.1_PDT001133851.1' already exists. Skipping...
Folder 'GCA_020065695.1_PDT001133845.1' already exists. Skipping...
Folder 'GCA_020065725.1_PDT001133781.1' already exists. Skipping...
Folder 'GCA_020065745.1_PDT001133780.1' already exists. Skipping...
Folder 'GCA_020065785.1_PDT001133777.1' already exists. Skipping...
Folder 'GCA_020065805.1_PDT001133766.1' already exists. Skipping...
Folder 'GCA_020065845.1_PDT001133733.1' already exists. Skipping...
Folder 'GCA_020065905.1_PDT001133732.1' already exists. Skipping...
Folder 'GCA_020066005.1_PDT001133833.1' already exists. Skipping...
Folder 'GCA_020066065.1_PDT001133832.1' already exists. Skipping...
Folder 'GCA_020066185.1_PDT001133828.1' already exists. Skipping...
Folder 'GCA_020066225.1_PDT001133783.1' already exists. Skipping...
Folder 'GCA_020066265.1_PDT001133775.1' already exists. Skipping...
Folder 'GCA_020066305.1_PDT001133767.1' already exists. Skipping...
Folder 'GCA_020066485.1_PDT001133802.1' already exists. Skipping...
Folder 'GCA_020066495.1_PDT001133785.1' already exists. Skipping...
Folder 'GCA_020066515.1_PDT001133788.1' already exists. Skipping...
Folder 'GCA_020066625.1_PDT001133839.1' already exists. Skipping...
Folder 'GCA_020066665.1_PDT001133770.1' already exists. Skipping...
Folder 'GCA_020066675.1_PDT001133763.1' already exists. Skipping...
Folder 'GCA_020066725.1_PDT001133748.1' already exists. Skipping...
Folder 'GCA_020066765.1_PDT001133741.1' already exists. Skipping...
Folder 'GCA_020066785.1_PDT001133727.1' already exists. Skipping...
Folder 'GCA_020066805.1_PDT001133890.1' already exists. Skipping...
Folder 'GCA_020066905.1_PDT001133889.1' already exists. Skipping...
Folder 'GCA_020087605.1_PDT001134817.1' already exists. Skipping...
Folder 'GCA_020093445.1_PDT001135693.1' already exists. Skipping...
Folder 'GCA_020094255.1_PDT001136039.1' already exists. Skipping...
Folder 'GCA_020094355.1_PDT001136036.1' already exists. Skipping...
Folder 'GCA_020094395.1_PDT001136033.1' already exists. Skipping...
Folder 'GCA_020094415.1_PDT001136032.1' already exists. Skipping...
Folder 'GCA_020094515.1_PDT001136025.1' already exists. Skipping...
Folder 'GCA_020094535.1_PDT001136024.1' already exists. Skipping...
Folder 'GCA_020094575.1_PDT001136029.1' already exists. Skipping...
Folder 'GCA_020094655.1_PDT001136021.1' already exists. Skipping...
Folder 'GCA_020094795.1_PDT001136011.1' already exists. Skipping...
Folder 'GCA_020094815.1_PDT001136017.1' already exists. Skipping...
Folder 'GCA_020094855.1_PDT001136012.1' already exists. Skipping...
Folder 'GCA_020094955.1_PDT001136014.1' already exists. Skipping...
Folder 'GCA_020099655.1_PDT001135716.1' already exists. Skipping...
Folder 'GCA_020099695.1_PDT001135711.1' already exists. Skipping...
Folder 'GCA_020099715.1_PDT001135710.1' already exists. Skipping...
Folder 'GCA_020099735.1_PDT001135705.1' already exists. Skipping...
Folder 'GCA_020111995.1_PDT001135717.1' already exists. Skipping...
Folder 'GCA_020112015.1_PDT001135713.1' already exists. Skipping...
Folder 'GCA_020112715.1_PDT001135718.1' already exists. Skipping...
Folder 'GCA_020112735.1_PDT001135715.1' already exists. Skipping...
Folder 'GCA_020112755.1_PDT001135712.1' already exists. Skipping...
Folder 'GCA_020112775.1_PDT001135707.1' already exists. Skipping...
Folder 'GCA_020112995.1_PDT001135709.1' already exists. Skipping...
Folder 'GCA_020113015.1_PDT001135714.1' already exists. Skipping...
Folder 'GCA_020113035.1_PDT001135706.1' already exists. Skipping...
Folder 'GCA_020113075.1_PDT001135704.1' already exists. Skipping...
Folder 'GCA_020113095.1_PDT001135708.1' already exists. Skipping...
Folder 'GCA_020114055.1_PDT001136324.1' already exists. Skipping...
Folder 'GCA_020121815.1_PDT001136454.1' already exists. Skipping...
Folder 'GCA_020122055.1_PDT001136438.1' already exists. Skipping...

Retreiveing data: 21530it [00:04, 6661.17it/s]

Folder 'GCA_021391815.1_ASM2139181v1' already exists. Skipping...
Folder 'GCA_021391835.1_ASM2139183v1' already exists. Skipping...
Folder 'GCA_021391855.1_ASM2139185v1' already exists. Skipping...
Folder 'GCA_021391875.1_ASM2139187v1' already exists. Skipping...
Folder 'GCA_021391895.1_ASM2139189v1' already exists. Skipping...
Folder 'GCA_021391905.1_ASM2139190v1' already exists. Skipping...
Folder 'GCA_021391935.1_ASM2139193v1' already exists. Skipping...
Folder 'GCA_021391955.1_ASM2139195v1' already exists. Skipping...
Folder 'GCA_021391975.1_ASM2139197v1' already exists. Skipping...
Folder 'GCA_021391985.1_ASM2139198v1' already exists. Skipping...
Folder 'GCA_021391995.1_ASM2139199v1' already exists. Skipping...
Folder 'GCA_021392035.1_ASM2139203v1' already exists. Skipping...
Folder 'GCA_021392045.1_ASM2139204v1' already exists. Skipping...
Folder 'GCA_021392115.1_ASM2139211v1' already exists. Skipping...
Folder 'GCA_021392135.1_ASM2139213v1' already exists. Skipping...
Folder 'GCA_021392155.1_ASM2139215v1' already exists. Skipping...
Folder 'GCA_021392175.1_ASM2139217v1' already exists. Skipping...
Folder 'GCA_021392185.1_ASM2139218v1' already exists. Skipping...
Folder 'GCA_021392215.1_ASM2139221v1' already exists. Skipping...
Folder 'GCA_021392235.1_ASM2139223v1' already exists. Skipping...
Folder 'GCA_021392255.1_ASM2139225v1' already exists. Skipping...
Folder 'GCA_021392295.1_ASM2139229v1' already exists. Skipping...
Folder 'GCA_021392435.1_ASM2139243v1' already exists. Skipping...
Folder 'GCA_021392475.1_ASM2139247v1' already exists. Skipping...
Folder 'GCA_021392485.1_ASM2139248v1' already exists. Skipping...
Folder 'GCA_021392515.1_ASM2139251v1' already exists. Skipping...
Folder 'GCA_021392525.1_ASM2139252v1' already exists. Skipping...
Folder 'GCA_021392555.1_ASM2139255v1' already exists. Skipping...
Folder 'GCA_021392575.1_ASM2139257v1' already exists. Skipping...
Folder 'GCA_021392615.1_ASM2139261v1' already exists. Skipping...
Folder 'GCA_021392635.1_ASM2139263v1' already exists. Skipping...
Folder 'GCA_021392645.1_ASM2139264v1' already exists. Skipping...
Folder 'GCA_021392675.1_ASM2139267v1' already exists. Skipping...
Folder 'GCA_021392695.1_ASM2139269v1' already exists. Skipping...
Folder 'GCA_021392715.1_ASM2139271v1' already exists. Skipping...
Folder 'GCA_021392725.1_ASM2139272v1' already exists. Skipping...
Folder 'GCA_021392755.1_ASM2139275v1' already exists. Skipping...
Folder 'GCA_021392775.1_ASM2139277v1' already exists. Skipping...
Folder 'GCA_021392795.1_ASM2139279v1' already exists. Skipping...
Folder 'GCA_021392805.1_ASM2139280v1' already exists. Skipping...
Folder 'GCA_021392845.1_ASM2139284v1' already exists. Skipping...
Folder 'GCA_021392875.1_ASM2139287v1' already exists. Skipping...
Folder 'GCA_021392885.1_ASM2139288v1' already exists. Skipping...
Folder 'GCA_021392915.1_ASM2139291v1' already exists. Skipping...
Folder 'GCA_021392925.1_ASM2139292v1' already exists. Skipping...
Folder 'GCA_021392955.1_ASM2139295v1' already exists. Skipping...
Folder 'GCA_021392975.1_ASM2139297v1' already exists. Skipping...
Folder 'GCA_021392995.1_ASM2139299v1' already exists. Skipping...
Folder 'GCA_021393015.1_ASM2139301v1' already exists. Skipping...
Folder 'GCA_021393025.1_ASM2139302v1' already exists. Skipping...
Folder 'GCA_021393035.1_ASM2139303v1' already exists. Skipping...
Folder 'GCA_021393075.1_ASM2139307v1' already exists. Skipping...
Folder 'GCA_021393095.1_ASM2139309v1' already exists. Skipping...
Folder 'GCA_021393115.1_ASM2139311v1' already exists. Skipping...
Folder 'GCA_021393125.1_ASM2139312v1' already exists. Skipping...
Folder 'GCA_021393155.1_ASM2139315v1' already exists. Skipping...
Folder 'GCA_021393175.1_ASM2139317v1' already exists. Skipping...
Folder 'GCA_021393195.1_ASM2139319v1' already exists. Skipping...
Folder 'GCA_021393215.1_ASM2139321v1' already exists. Skipping...
Folder 'GCA_021393235.1_ASM2139323v1' already exists. Skipping...
Folder 'GCA_021393255.1_ASM2139325v1' already exists. Skipping...
Folder 'GCA_021393275.1_ASM2139327v1' already exists. Skipping...
Folder 'GCA_021393305.1_ASM2139330v1' already exists. Skipping...
Folder 'GCA_021393335.1_ASM2139333v1' already exists. Skipping...
Folder 'GCA_021393355.1_ASM2139335v1' already exists. Skipping...
Folder 'GCA_021393375.1_ASM2139337v1' already exists. Skipping...
Folder 'GCA_021393395.1_ASM2139339v1' already exists. Skipping...
Folder 'GCA_021393405.1_ASM2139340v1' already exists. Skipping...
Folder 'GCA_021393435.1_ASM2139343v1' already exists. Skipping...
Folder 'GCA_021393445.1_ASM2139344v1' already exists. Skipping...
Folder 'GCA_021393475.1_ASM2139347v1' already exists. Skipping...
Folder 'GCA_021393495.1_ASM2139349v1' already exists. Skipping...
Folder 'GCA_021393505.1_ASM2139350v1' already exists. Skipping...
Folder 'GCA_021393535.1_ASM2139353v1' already exists. Skipping...
Folder 'GCA_021393555.1_ASM2139355v1' already exists. Skipping...
Folder 'GCA_021393565.1_ASM2139356v1' already exists. Skipping...
Folder 'GCA_021393595.1_ASM2139359v1' already exists. Skipping...
Folder 'GCA_021393605.1_ASM2139360v1' already exists. Skipping...
Folder 'GCA_021393635.1_ASM2139363v1' already exists. Skipping...
Folder 'GCA_021393655.1_ASM2139365v1' already exists. Skipping...
Folder 'GCA_021393675.1_ASM2139367v1' already exists. Skipping...
Folder 'GCA_021393695.1_ASM2139369v1' already exists. Skipping...
Folder 'GCA_021393705.1_ASM2139370v1' already exists. Skipping...
Folder 'GCA_021393725.1_ASM2139372v1' already exists. Skipping...
Folder 'GCA_021393755.1_ASM2139375v1' already exists. Skipping...
Folder 'GCA_021393775.1_ASM2139377v1' already exists. Skipping...
Folder 'GCA_021393795.1_ASM2139379v1' already exists. Skipping...
Folder 'GCA_021393815.1_ASM2139381v1' already exists. Skipping...
Folder 'GCA_021393825.1_ASM2139382v1' already exists. Skipping...
Folder 'GCA_021393875.1_ASM2139387v1' already exists. Skipping...
Folder 'GCA_021393895.1_ASM2139389v1' already exists. Skipping...
Folder 'GCA_021393915.1_ASM2139391v1' already exists. Skipping...
Folder 'GCA_021393925.1_ASM2139392v1' already exists. Skipping...
Folder 'GCA_021393935.1_ASM2139393v1' already exists. Skipping...
Folder 'GCA_021393975.1_ASM2139397v1' already exists. Skipping...
Folder 'GCA_021393995.1_ASM2139399v1' already exists. Skipping...
Folder 'GCA_021394015.1_ASM2139401v1' already exists. Skipping...
Folder 'GCA_021394035.1_ASM2139403v1' already exists. Skipping...
Folder 'GCA_021394045.1_ASM2139404v1' already exists. Skipping...
Folder 'GCA_021394075.1_ASM2139407v1' already exists. Skipping...
Folder 'GCA_021394095.1_ASM2139409v1' already exists. Skipping...
Folder 'GCA_021394115.1_ASM2139411v1' already exists. Skipping...
Folder 'GCA_021394125.1_ASM2139412v1' already exists. Skipping...
Folder 'GCA_021394155.1_ASM2139415v1' already exists. Skipping...
Folder 'GCA_021394175.1_ASM2139417v1' already exists. Skipping...
Folder 'GCA_021394185.1_ASM2139418v1' already exists. Skipping...
Folder 'GCA_021394215.1_ASM2139421v1' already exists. Skipping...
Folder 'GCA_021394225.1_ASM2139422v1' already exists. Skipping...
Folder 'GCA_021394255.1_ASM2139425v1' already exists. Skipping...
Folder 'GCA_021394295.1_ASM2139429v1' already exists. Skipping...
Folder 'GCA_021395955.1_ASM2139595v1' already exists. Skipping...
Folder 'GCA_021395965.1_ASM2139596v1' already exists. Skipping...
Folder 'GCA_021395995.1_ASM2139599v1' already exists. Skipping...
Folder 'GCA_021396015.1_ASM2139601v1' already exists. Skipping...
Folder 'GCA_021396035.1_ASM2139603v1' already exists. Skipping...
Folder 'GCA_021396055.1_ASM2139605v1' already exists. Skipping...
Folder 'GCA_021396075.1_ASM2139607v1' already exists. Skipping...
Folder 'GCA_021396085.1_ASM2139608v1' already exists. Skipping...
Folder 'GCA_021396115.1_ASM2139611v1' already exists. Skipping...
Folder 'GCA_021396135.1_ASM2139613v1' already exists. Skipping...
Folder 'GCA_021396155.1_ASM2139615v1' already exists. Skipping...
Folder 'GCA_021396165.1_ASM2139616v1' already exists. Skipping...
Folder 'GCA_021420445.1_PDT001219230.1' already exists. Skipping...
Folder 'GCA_021420485.1_PDT001219228.1' already exists. Skipping...
Folder 'GCA_021420505.1_PDT001219229.1' already exists. Skipping...
Folder 'GCA_021420545.1_PDT001219226.1' already exists. Skipping...
Folder 'GCA_021420565.1_PDT001219225.1' already exists. Skipping...
Folder 'GCA_021421485.1_PDT001219245.1' already exists. Skipping...
Folder 'GCA_021421505.1_PDT001219243.1' already exists. Skipping...
Folder 'GCA_021421525.1_PDT001219244.1' already exists. Skipping...
Folder 'GCA_021421545.1_PDT001219246.1' already exists. Skipping...
Folder 'GCA_021421585.1_PDT001219224.1' already exists. Skipping...
Folder 'GCA_021421605.1_PDT001219236.1' already exists. Skipping...
Folder 'GCA_021423415.1_PDT001219409.1' already exists. Skipping...
Folder 'GCA_021427305.1_PDT001219231.1' already exists. Skipping...
Folder 'GCA_021428125.1_PDT001219407.1' already exists. Skipping...
Folder 'GCA_021428185.1_PDT001219354.1' already exists. Skipping...
Folder 'GCA_021428225.1_PDT001219405.1' already exists. Skipping...
Folder 'GCA_021428245.1_PDT001219397.1' already exists. Skipping...
Folder 'GCA_021428305.1_PDT001219385.1' already exists. Skipping...
Folder 'GCA_021428345.1_PDT001219382.1' already exists. Skipping...
Folder 'GCA_021450645.1_PDT001221258.1' already exists. Skipping...
Folder 'GCA_021453245.1_PDT001221887.1' already exists. Skipping...
Folder 'GCA_021453265.1_PDT001221882.1' already exists. Skipping...
Folder 'GCA_021464735.1_PDT001222683.1' already exists. Skipping...
Folder 'GCA_021464785.1_PDT001222686.1' already exists. Skipping...
Folder 'GCA_021465625.1_PDT001222547.1' already exists. Skipping...
Folder 'GCA_021465645.1_PDT001222543.1' already exists. Skipping...
Folder 'GCA_021465685.1_PDT001222542.1' already exists. Skipping...
Folder 'GCA_021465705.1_PDT001222544.1' already exists. Skipping...
Folder 'GCA_021465725.1_PDT001222545.1' already exists. Skipping...
Folder 'GCA_021465745.1_PDT001222541.1' already exists. Skipping...
Folder 'GCA_021466045.1_PDT001222524.1' already exists. Skipping...
Folder 'GCA_021466405.1_PDT001222557.1' already exists. Skipping...
Folder 'GCA_021470185.1_PDT001222678.1' already exists. Skipping...
Folder 'GCA_021470225.1_PDT001222677.1' already exists. Skipping...
Folder 'GCA_021470805.1_PDT001222564.1' already exists. Skipping...
Folder 'GCA_021470865.1_PDT001222554.1' already exists. Skipping...
Folder 'GCA_021470945.1_PDT001222551.1' already exists. Skipping...
Folder 'GCA_021470965.1_PDT001222550.1' already exists. Skipping...
Folder 'GCA_021471005.1_PDT001222552.1' already exists. Skipping...
Folder 'GCA_021471045.1_PDT001222548.1' already exists. Skipping...
Folder 'GCA_021473005.1_PDT001222558.1' already exists. Skipping...
Folder 'GCA_021486355.1_PDT001223366.1' already exists. Skipping...
Folder 'GCA_021486395.1_PDT001223367.1' already exists. Skipping...
Folder 'GCA_021486415.1_PDT001223364.1' already exists. Skipping...
Folder 'GCA_021486455.1_PDT001223362.1' already exists. Skipping...
Folder 'GCA_021486495.1_PDT001223360.1' already exists. Skipping...
Folder 'GCA_021486915.1_PDT001223431.1' already exists. Skipping...
Folder 'GCA_021486955.1_PDT001223434.1' already exists. Skipping...
Folder 'GCA_021486975.1_PDT001223433.1' already exists. Skipping...
Folder 'GCA_021486995.1_PDT001223428.1' already exists. Skipping...
Folder 'GCA_021487055.1_PDT001223419.1' already exists. Skipping...
Folder 'GCA_021487075.1_PDT001223424.1' already exists. Skipping...
Folder 'GCA_021487135.1_PDT001223416.1' already exists. Skipping...
Folder 'GCA_021487195.1_PDT001223398.1' already exists. Skipping...
Folder 'GCA_021487235.1_PDT001223385.1' already exists. Skipping...
Folder 'GCA_021487255.1_PDT001223383.1' already exists. Skipping...
Folder 'GCA_021487295.1_PDT001223376.1' already exists. Skipping...
Folder 'GCA_021487315.1_PDT001223371.1' already exists. Skipping...
Folder 'GCA_021487395.1_PDT001223374.1' already exists. Skipping...
Folder 'GCA_021487895.1_PDT001223514.1' already exists. Skipping...
Folder 'GCA_021487935.1_PDT001223513.1' already exists. Skipping...
Folder 'GCA_021487995.1_PDT001223502.1' already exists. Skipping...
Folder 'GCA_021488035.1_PDT001223494.1' already exists. Skipping...
Folder 'GCA_021488315.1_PDT001223503.1' already exists. Skipping...
Folder 'GCA_021488335.1_PDT001223500.1' already exists. Skipping...
Folder 'GCA_021488355.1_PDT001223499.1' already exists. Skipping...
Folder 'GCA_021488375.1_PDT001223497.1' already exists. Skipping...
Folder 'GCA_021488415.1_PDT001223493.1' already exists. Skipping...
Folder 'GCA_021489355.1_PDT001223441.1' already exists. Skipping...
Folder 'GCA_021489435.1_PDT001223381.1' already exists. Skipping...
Folder 'GCA_021489455.1_PDT001223378.1' already exists. Skipping...
Folder 'GCA_021489615.1_PDT001223459.1' already exists. Skipping...
Folder 'GCA_021489735.1_PDT001223452.1' already exists. Skipping...
Folder 'GCA_021489815.1_PDT001223370.1' already exists. Skipping...
Folder 'GCA_021489895.1_PDT001223457.1' already exists. Skipping...
Folder 'GCA_021489915.1_PDT001223454.1' already exists. Skipping...
Folder 'GCA_021489935.1_PDT001223435.1' already exists. Skipping...
Folder 'GCA_021489955.1_PDT001223377.1' already exists. Skipping...
Folder 'GCA_021491095.1_PDT001223515.1' already exists. Skipping...
Folder 'GCA_021492805.1_PDT001223492.1' already exists. Skipping...
Folder 'GCA_021495385.1_ASM2149538v1' already exists. Skipping...
Folder 'GCA_021505735.1_PDT001225127.1' already exists. Skipping...
Folder 'GCA_021505755.1_PDT001225124.1' already exists. Skipping...
Folder 'GCA_021505775.1_PDT001225116.1' already exists. Skipping...
Folder 'GCA_021505845.1_PDT001225137.1' already exists. Skipping...
Folder 'GCA_021505875.1_PDT001225125.1' already exists. Skipping...
Folder 'GCA_021505945.1_PDT001225136.1' already exists. Skipping...
Folder 'GCA_021505975.1_PDT001225131.1' already exists. Skipping...
Folder 'GCA_021506075.1_PDT001225118.1' already exists. Skipping...
Folder 'GCA_021506255.1_PDT001225115.1' already exists. Skipping...
Folder 'GCA_021513895.1_PDT001225895.1' already exists. Skipping...
Folder 'GCA_021514035.1_PDT001225972.1' already exists. Skipping...
Folder 'GCA_021514085.1_PDT001225885.1' already exists. Skipping...
Folder 'GCA_021514155.1_PDT001225905.1' already exists. Skipping...
Folder 'GCA_021514315.1_PDT001226477.1' already exists. Skipping...
Folder 'GCA_021514595.1_PDT001225971.1' already exists. Skipping...
Folder 'GCA_021514655.1_PDT001225969.1' already exists. Skipping...
Folder 'GCA_021514835.1_PDT001225967.1' already exists. Skipping...
Folder 'GCA_021514855.1_PDT001225966.1' already exists. Skipping...
Folder 'GCA_021514915.1_PDT001225964.1' already exists. Skipping...
Folder 'GCA_021514935.1_PDT001225962.1' already exists. Skipping...
Folder 'GCA_021514975.1_PDT001225960.1' already exists. Skipping...
Folder 'GCA_021514995.1_PDT001225958.1' already exists. Skipping...
Folder 'GCA_021515015.1_PDT001225959.1' already exists. Skipping...
Folder 'GCA_021515095.1_PDT001225954.1' already exists. Skipping...
Folder 'GCA_021515115.1_PDT001225951.1' already exists. Skipping...
Folder 'GCA_021516555.1_PDT001225906.1' already exists. Skipping...
Folder 'GCA_021516605.1_PDT001225904.1' already exists. Skipping...
Folder 'GCA_021516725.1_PDT001225902.1' already exists. Skipping...
Folder 'GCA_021516745.1_PDT001225901.1' already exists. Skipping...
Folder 'GCA_021516935.1_PDT001225896.1' already exists. Skipping...
Folder 'GCA_021517035.1_PDT001225898.1' already exists. Skipping...
Folder 'GCA_021517125.1_PDT001225892.1' already exists. Skipping...
Folder 'GCA_021517195.1_PDT001225889.1' already exists. Skipping...
Folder 'GCA_021517385.1_PDT001225884.1' already exists. Skipping...
Folder 'GCA_021517545.1_PDT001225881.1' already exists. Skipping...
Folder 'GCA_021517585.1_PDT001225879.1' already exists. Skipping...
Folder 'GCA_021517655.1_PDT001225878.1' already exists. Skipping...
Folder 'GCA_021518635.1_PDT001225852.1' already exists. Skipping...
Folder 'GCA_021529575.1_PDT001226815.1' already exists. Skipping...
Folder 'GCA_021530135.1_PDT001226863.1' already exists. Skipping...
Folder 'GCA_021545935.1_PDT001228352.1' already exists. Skipping...
Folder 'GCA_021545945.1_PDT001228359.1' already exists. Skipping...
Folder 'GCA_021545995.1_PDT001228354.1' already exists. Skipping...
Folder 'GCA_021546015.1_PDT001228353.1' already exists. Skipping...
Folder 'GCA_021546035.1_PDT001228346.1' already exists. Skipping...
Folder 'GCA_021546055.1_PDT001228350.1' already exists. Skipping...
Folder 'GCA_021546075.1_PDT001228348.1' already exists. Skipping...
Folder 'GCA_021546135.1_PDT001228344.1' already exists. Skipping...
Folder 'GCA_021546155.1_PDT001228345.1' already exists. Skipping...
Folder 'GCA_021548995.1_PDT001228562.1' already exists. Skipping...
Folder 'GCA_021549015.1_PDT001228584.1' already exists. Skipping...
Folder 'GCA_021549035.1_PDT001228589.1' already exists. Skipping...
Folder 'GCA_021549175.1_PDT001228553.1' already exists. Skipping...
Folder 'GCA_021549195.1_PDT001228550.1' already exists. Skipping...
Folder 'GCA_021549255.1_PDT001228546.1' already exists. Skipping...
Folder 'GCA_021549275.1_PDT001228541.1' already exists. Skipping...
Folder 'GCA_021549295.1_PDT001228538.1' already exists. Skipping...
Folder 'GCA_021549315.1_PDT001228536.1' already exists. Skipping...
Folder 'GCA_021549335.1_PDT001228540.1' already exists. Skipping...
Folder 'GCA_021549375.1_PDT001228532.1' already exists. Skipping...
Folder 'GCA_021549775.1_PDT001228642.1' already exists. Skipping...
Folder 'GCA_021549815.1_PDT001228640.1' already exists. Skipping...
Folder 'GCA_021549835.1_PDT001228638.1' already exists. Skipping...
Folder 'GCA_021549875.1_PDT001228637.1' already exists. Skipping...
Folder 'GCA_021549915.1_PDT001228636.1' already exists. Skipping...
Folder 'GCA_021549955.1_PDT001228634.1' already exists. Skipping...
Folder 'GCA_021549975.1_PDT001228633.1' already exists. Skipping...
Folder 'GCA_021549995.1_PDT001228623.1' already exists. Skipping...
Folder 'GCA_021550015.1_PDT001228612.1' already exists. Skipping...
Folder 'GCA_021550035.1_PDT001228608.1' already exists. Skipping...
Folder 'GCA_021550055.1_PDT001228604.1' already exists. Skipping...
Folder 'GCA_021550095.1_PDT001228602.1' already exists. Skipping...
Folder 'GCA_021550135.1_PDT001228599.1' already exists. Skipping...
Folder 'GCA_021550155.1_PDT001228598.1' already exists. Skipping...
Folder 'GCA_021550175.1_PDT001228597.1' already exists. Skipping...
Folder 'GCA_021550235.1_PDT001228585.1' already exists. Skipping...
Folder 'GCA_021550315.1_PDT001228534.1' already exists. Skipping...
Folder 'GCA_021550335.1_PDT001228535.1' already exists. Skipping...
Folder 'GCA_021550755.1_PDT001228580.1' already exists. Skipping...
Folder 'GCA_021550815.1_PDT001228561.1' already exists. Skipping...
Folder 'GCA_021550915.1_PDT001228542.1' already exists. Skipping...
Folder 'GCA_021551415.1_PDT001228590.1' already exists. Skipping...
Folder 'GCA_021552195.1_PDT001228737.1' already exists. Skipping...
Folder 'GCA_021552245.1_PDT001228735.1' already exists. Skipping...
Folder 'GCA_021552495.1_PDT001228733.1' already exists. Skipping...
Folder 'GCA_021552515.1_PDT001228731.1' already exists. Skipping...
Folder 'GCA_021552555.1_PDT001228732.1' already exists. Skipping...
Folder 'GCA_021552995.1_PDT001228739.1' already exists. Skipping...
Folder 'GCA_021560795.1_PDT001229337.1' already exists. Skipping...
Folder 'GCA_021560815.1_PDT001229335.1' already exists. Skipping...
Folder 'GCA_021560835.1_PDT001229333.1' already exists. Skipping...
Folder 'GCA_021560855.1_PDT001229331.1' already exists. Skipping...
Folder 'GCA_021560895.1_PDT001229332.1' already exists. Skipping...
Folder 'GCA_021560915.1_PDT001229327.1' already exists. Skipping...

Retreiveing data: 22871it [00:04, 6671.04it/s]

Folder 'GCA_023241215.1_PDT001299549.1' already exists. Skipping...
Folder 'GCA_023241235.1_PDT001299547.1' already exists. Skipping...
Folder 'GCA_023241255.1_PDT001299544.1' already exists. Skipping...
Folder 'GCA_023241275.1_PDT001299538.1' already exists. Skipping...
Folder 'GCA_023241495.1_PDT001299557.1' already exists. Skipping...
Folder 'GCA_023241595.1_PDT001299564.1' already exists. Skipping...
Folder 'GCA_023241935.1_PDT001299570.1' already exists. Skipping...
Folder 'GCA_023241995.1_PDT001299571.1' already exists. Skipping...
Folder 'GCA_023270965.1_PDT001270617.1' already exists. Skipping...
Folder 'GCA_023279225.1_PDT001302569.1' already exists. Skipping...
Folder 'GCA_023279245.1_PDT001302432.1' already exists. Skipping...
Folder 'GCA_023279265.1_PDT001302435.1' already exists. Skipping...
Folder 'GCA_023279285.1_PDT001302444.1' already exists. Skipping...
Folder 'GCA_023279305.1_PDT001302439.1' already exists. Skipping...
Folder 'GCA_023279385.1_PDT001302426.1' already exists. Skipping...
Folder 'GCA_023279445.1_PDT001302425.1' already exists. Skipping...
Folder 'GCA_023279465.1_PDT001302429.1' already exists. Skipping...
Folder 'GCA_023279885.1_PDT001302568.1' already exists. Skipping...
Folder 'GCA_023279905.1_PDT001302449.1' already exists. Skipping...
Folder 'GCA_023279925.1_PDT001302443.1' already exists. Skipping...
Folder 'GCA_023279985.1_PDT001302438.1' already exists. Skipping...
Folder 'GCA_023280025.1_PDT001302440.1' already exists. Skipping...
Folder 'GCA_023280045.1_PDT001302437.1' already exists. Skipping...
Folder 'GCA_023280065.1_PDT001302434.1' already exists. Skipping...
Folder 'GCA_023280085.1_PDT001302422.1' already exists. Skipping...
Folder 'GCA_023280095.1_PDT001302431.1' already exists. Skipping...
Folder 'GCA_023280125.1_PDT001302433.1' already exists. Skipping...
Folder 'GCA_023280145.1_PDT001302419.1' already exists. Skipping...
Folder 'GCA_023280185.1_PDT001302418.1' already exists. Skipping...
Folder 'GCA_023280205.1_PDT001302713.1' already exists. Skipping...
Folder 'GCA_023280225.1_PDT001302413.1' already exists. Skipping...
Folder 'GCA_023280245.1_PDT001302415.1' already exists. Skipping...
Folder 'GCA_023280265.1_PDT001302714.1' already exists. Skipping...
Folder 'GCA_023280305.1_PDT001302723.1' already exists. Skipping...
Folder 'GCA_023280325.1_PDT001302709.1' already exists. Skipping...
Folder 'GCA_023280845.1_PDT001302427.1' already exists. Skipping...
Folder 'GCA_023280945.1_PDT001302421.1' already exists. Skipping...
Folder 'GCA_023281285.1_PDT001302724.1' already exists. Skipping...
Folder 'GCA_023281325.1_PDT001302727.1' already exists. Skipping...
Folder 'GCA_023281385.1_PDT001302722.1' already exists. Skipping...
Folder 'GCA_023281405.1_PDT001302711.1' already exists. Skipping...
Folder 'GCA_023281425.1_PDT001302715.1' already exists. Skipping...
Folder 'GCA_023281445.1_PDT001302708.1' already exists. Skipping...
Folder 'GCA_023281485.1_PDT001302704.1' already exists. Skipping...
Folder 'GCA_023281505.1_PDT001302703.1' already exists. Skipping...
Folder 'GCA_023281625.1_PDT001302697.1' already exists. Skipping...
Folder 'GCA_023281645.1_PDT001302690.1' already exists. Skipping...
Folder 'GCA_023281685.1_PDT001302687.1' already exists. Skipping...
Folder 'GCA_023281925.1_PDT001302719.1' already exists. Skipping...
Folder 'GCA_023281945.1_PDT001302718.1' already exists. Skipping...
Folder 'GCA_023281965.1_PDT001302712.1' already exists. Skipping...
Folder 'GCA_023281985.1_PDT001302702.1' already exists. Skipping...
Folder 'GCA_023288245.1_PDT001303039.1' already exists. Skipping...
Folder 'GCA_023289305.1_PDT001303105.1' already exists. Skipping...
Folder 'GCA_023289885.1_PDT001303113.1' already exists. Skipping...
Folder 'GCA_023290545.1_PDT001303123.1' already exists. Skipping...
Folder 'GCA_023290565.1_PDT001303104.1' already exists. Skipping...
Folder 'GCA_023290585.1_PDT001303097.1' already exists. Skipping...
Folder 'GCA_023291285.1_PDT001300968.1' already exists. Skipping...
Folder 'GCA_023291605.1_PDT001300953.1' already exists. Skipping...
Folder 'GCA_023291645.1_PDT001300950.1' already exists. Skipping...
Folder 'GCA_023291725.1_PDT001300937.1' already exists. Skipping...
Folder 'GCA_023291765.1_PDT001300928.1' already exists. Skipping...
Folder 'GCA_023291785.1_PDT001300926.1' already exists. Skipping...
Folder 'GCA_023291825.1_PDT001300925.1' already exists. Skipping...
Folder 'GCA_023291845.1_PDT001303156.1' already exists. Skipping...
Folder 'GCA_023291885.1_PDT001300960.1' already exists. Skipping...
Folder 'GCA_023291925.1_PDT001300927.1' already exists. Skipping...
Folder 'GCA_023291965.1_PDT001300913.1' already exists. Skipping...
Folder 'GCA_023292045.1_PDT001300899.1' already exists. Skipping...
Folder 'GCA_023292075.1_PDT001303140.1' already exists. Skipping...
Folder 'GCA_023292125.1_PDT001303124.1' already exists. Skipping...
Folder 'GCA_023292145.1_PDT001303112.1' already exists. Skipping...
Folder 'GCA_023292165.1_PDT001303116.1' already exists. Skipping...
Folder 'GCA_023292185.1_PDT001303115.1' already exists. Skipping...
Folder 'GCA_023292225.1_PDT001303098.1' already exists. Skipping...
Folder 'GCA_023292285.1_PDT001303096.1' already exists. Skipping...
Folder 'GCA_023292345.1_PDT001300943.1' already exists. Skipping...
Folder 'GCA_023292385.1_PDT001300924.1' already exists. Skipping...
Folder 'GCA_023292465.1_PDT001300901.1' already exists. Skipping...
Folder 'GCA_023292485.1_PDT001300898.1' already exists. Skipping...
Folder 'GCA_023292765.1_PDT001300909.1' already exists. Skipping...
Folder 'GCA_023292805.1_PDT001300890.1' already exists. Skipping...
Folder 'GCA_023292825.1_PDT001300883.1' already exists. Skipping...
Folder 'GCA_023304065.1_PDT001300429.1' already exists. Skipping...
Folder 'GCA_023304125.1_PDT001300425.1' already exists. Skipping...
Folder 'GCA_023304225.1_PDT001300419.1' already exists. Skipping...
Folder 'GCA_023304305.1_PDT001300416.1' already exists. Skipping...
Folder 'GCA_023304325.1_PDT001300415.1' already exists. Skipping...
Folder 'GCA_023304405.1_PDT001300411.1' already exists. Skipping...
Folder 'GCA_023304545.1_PDT001300405.1' already exists. Skipping...
Folder 'GCA_023304605.1_PDT001300404.1' already exists. Skipping...
Folder 'GCA_023304745.1_PDT001300395.1' already exists. Skipping...
Folder 'GCA_023304765.1_PDT001300394.1' already exists. Skipping...
Folder 'GCA_023304785.1_PDT001300391.1' already exists. Skipping...
Folder 'GCA_023304865.1_PDT001300387.1' already exists. Skipping...
Folder 'GCA_023304925.1_PDT001300386.1' already exists. Skipping...
Folder 'GCA_023304965.1_PDT001300382.1' already exists. Skipping...
Folder 'GCA_023307585.1_PDT001300135.1' already exists. Skipping...
Folder 'GCA_023307645.1_PDT001300130.1' already exists. Skipping...
Folder 'GCA_023307845.1_PDT001300123.1' already exists. Skipping...
Folder 'GCA_023307885.1_PDT001300120.1' already exists. Skipping...
Folder 'GCA_023307935.1_PDT001300117.1' already exists. Skipping...
Folder 'GCA_023307965.1_PDT001300119.1' already exists. Skipping...
Folder 'GCA_023308245.1_PDT001300103.1' already exists. Skipping...
Folder 'GCA_023308265.1_PDT001300100.1' already exists. Skipping...
Folder 'GCA_023308285.1_PDT001300101.1' already exists. Skipping...
Folder 'GCA_023308305.1_PDT001300099.1' already exists. Skipping...
Folder 'GCA_023308345.1_PDT001300096.1' already exists. Skipping...
Folder 'GCA_023308405.1_PDT001300094.1' already exists. Skipping...
Folder 'GCA_023308445.1_PDT001300091.1' already exists. Skipping...
Folder 'GCA_023308465.1_PDT001300092.1' already exists. Skipping...
Folder 'GCA_023308485.1_PDT001300090.1' already exists. Skipping...
Folder 'GCA_023308505.1_PDT001300087.1' already exists. Skipping...
Folder 'GCA_023308585.1_PDT001300089.1' already exists. Skipping...
Folder 'GCA_023308605.1_PDT001300083.1' already exists. Skipping...
Folder 'GCA_023308645.1_PDT001300082.1' already exists. Skipping...
Folder 'GCA_023308665.1_PDT001300080.1' already exists. Skipping...
Folder 'GCA_023308705.1_PDT001300079.1' already exists. Skipping...
Folder 'GCA_023308725.1_PDT001300077.1' already exists. Skipping...
Folder 'GCA_023308745.1_PDT001300078.1' already exists. Skipping...
Folder 'GCA_023308765.1_PDT001300075.1' already exists. Skipping...
Folder 'GCA_023308805.1_PDT001300074.1' already exists. Skipping...
Folder 'GCA_023308825.1_PDT001300073.1' already exists. Skipping...
Folder 'GCA_023308845.1_PDT001300072.1' already exists. Skipping...
Folder 'GCA_023334625.1_PDT001305943.1' already exists. Skipping...
Folder 'GCA_023334685.1_PDT001305949.1' already exists. Skipping...
Folder 'GCA_023334735.1_PDT001305922.1' already exists. Skipping...
Folder 'GCA_023334905.1_PDT001305955.1' already exists. Skipping...
Folder 'GCA_023335025.1_PDT001306122.1' already exists. Skipping...
Folder 'GCA_023335415.1_PDT001306124.1' already exists. Skipping...
Folder 'GCA_023343215.1_PDT001306117.1' already exists. Skipping...
Folder 'GCA_023343815.1_PDT001306129.1' already exists. Skipping...
Folder 'GCA_023344215.1_PDT001306132.1' already exists. Skipping...
Folder 'GCA_023344295.1_PDT001306127.1' already exists. Skipping...
Folder 'GCA_023344315.1_PDT001306123.1' already exists. Skipping...
Folder 'GCA_023344375.1_PDT001306116.1' already exists. Skipping...
Folder 'GCA_023344815.1_PDT001306049.1' already exists. Skipping...
Folder 'GCA_023344835.1_PDT001306037.1' already exists. Skipping...
Folder 'GCA_023345325.1_PDT001305970.1' already exists. Skipping...
Folder 'GCA_023345385.1_PDT001305965.1' already exists. Skipping...
Folder 'GCA_023345405.1_PDT001305947.1' already exists. Skipping...
Folder 'GCA_023345445.1_PDT001305935.1' already exists. Skipping...
Folder 'GCA_023345525.1_PDT001305925.1' already exists. Skipping...
Folder 'GCA_023345615.1_PDT001305944.1' already exists. Skipping...
Folder 'GCA_023345705.1_PDT001306106.1' already exists. Skipping...
Folder 'GCA_023346135.1_PDT001305962.1' already exists. Skipping...
Folder 'GCA_023346205.1_PDT001305958.1' already exists. Skipping...
Folder 'GCA_023346275.1_PDT001305953.1' already exists. Skipping...
Folder 'GCA_023346325.1_PDT001305939.1' already exists. Skipping...
Folder 'GCA_023346405.1_PDT001305933.1' already exists. Skipping...
Folder 'GCA_023346445.1_PDT001305929.1' already exists. Skipping...
Folder 'GCA_023346505.1_PDT001305928.1' already exists. Skipping...
Folder 'GCA_023346585.1_PDT001305927.1' already exists. Skipping...
Folder 'GCA_023346805.1_PDT001305946.1' already exists. Skipping...
Folder 'GCA_023347165.1_PDT001305963.1' already exists. Skipping...
Folder 'GCA_023347415.1_PDT001305961.1' already exists. Skipping...
Folder 'GCA_023347455.1_PDT001305954.1' already exists. Skipping...
Folder 'GCA_023371485.1_PDT001308458.1' already exists. Skipping...
Folder 'GCA_023371505.1_PDT001308456.1' already exists. Skipping...
Folder 'GCA_023371525.1_PDT001308461.1' already exists. Skipping...
Folder 'GCA_023371645.1_PDT001308462.1' already exists. Skipping...
Folder 'GCA_023376215.1_PDT001295245.1' already exists. Skipping...
Folder 'GCA_023376375.1_PDT001291196.1' already exists. Skipping...
Folder 'GCA_023376395.1_PDT001290018.1' already exists. Skipping...
Folder 'GCA_023376415.1_PDT001289862.1' already exists. Skipping...
Folder 'GCA_023376435.1_PDT001289835.1' already exists. Skipping...
Folder 'GCA_023376455.1_PDT001280477.1' already exists. Skipping...
Folder 'GCA_023376565.1_PDT001264071.1' already exists. Skipping...
Folder 'GCA_023376595.1_PDT001264208.1' already exists. Skipping...
Folder 'GCA_023376615.1_PDT001258681.1' already exists. Skipping...
Folder 'GCA_023376655.1_PDT001258582.1' already exists. Skipping...
Folder 'GCA_023376665.1_PDT001258598.1' already exists. Skipping...
Folder 'GCA_023376755.1_PDT001252295.1' already exists. Skipping...
Folder 'GCA_023376815.1_PDT001252283.1' already exists. Skipping...
Folder 'GCA_023376835.1_PDT001241970.1' already exists. Skipping...
Folder 'GCA_023376875.1_PDT001222555.1' already exists. Skipping...
Folder 'GCA_023376885.1_PDT001228738.1' already exists. Skipping...
Folder 'GCA_023376955.1_PDT001205370.1' already exists. Skipping...
Folder 'GCA_023377005.1_PDT001206456.1' already exists. Skipping...
Folder 'GCA_023377045.1_PDT001205349.1' already exists. Skipping...
Folder 'GCA_023377165.1_PDT001168618.1' already exists. Skipping...
Folder 'GCA_023377175.1_PDT001163612.1' already exists. Skipping...
Folder 'GCA_023377265.1_PDT001157863.3' already exists. Skipping...
Folder 'GCA_023377325.1_PDT001150968.1' already exists. Skipping...
Folder 'GCA_023377385.1_PDT001150974.1' already exists. Skipping...
Folder 'GCA_023377505.1_PDT001308925.1' already exists. Skipping...
Folder 'GCA_023377625.1_PDT001269659.1' already exists. Skipping...
Folder 'GCA_023377755.1_PDT001270630.1' already exists. Skipping...
Folder 'GCA_023380085.1_PDT001309013.1' already exists. Skipping...
Folder 'GCA_023380105.1_PDT001308927.1' already exists. Skipping...
Folder 'GCA_023471085.1_PDT001310154.1' already exists. Skipping...
Folder 'GCA_023471145.1_PDT001310156.1' already exists. Skipping...
Folder 'GCA_023471165.1_PDT001310153.1' already exists. Skipping...
Folder 'GCA_023471185.1_PDT001310151.1' already exists. Skipping...
Folder 'GCA_023471205.1_PDT001310152.1' already exists. Skipping...
Folder 'GCA_023471245.1_PDT001310149.1' already exists. Skipping...
Folder 'GCA_023471265.1_PDT001310145.1' already exists. Skipping...
Folder 'GCA_023475815.1_PDT001310148.1' already exists. Skipping...
Folder 'GCA_023475845.1_PDT001310141.1' already exists. Skipping...
Folder 'GCA_023476665.1_PDT001310139.1' already exists. Skipping...
Folder 'GCA_023479425.1_PDT001310159.1' already exists. Skipping...
Folder 'GCA_023480045.1_PDT001310155.1' already exists. Skipping...
Folder 'GCA_023480115.1_PDT001310158.1' already exists. Skipping...
Folder 'GCA_023480285.1_PDT001310146.1' already exists. Skipping...
Folder 'GCA_023481125.1_PDT001310137.1' already exists. Skipping...
Folder 'GCA_023492985.1_PDT001310690.1' already exists. Skipping...
Folder 'GCA_023493165.1_PDT001310680.1' already exists. Skipping...
Folder 'GCA_023493205.1_PDT001310678.1' already exists. Skipping...
Folder 'GCA_023493505.1_PDT001310681.1' already exists. Skipping...
Folder 'GCA_023493525.1_PDT001310673.1' already exists. Skipping...
Folder 'GCA_023499395.1_PDT001310708.1' already exists. Skipping...
Folder 'GCA_023499455.1_PDT001310707.1' already exists. Skipping...
Folder 'GCA_023499515.1_PDT001310705.1' already exists. Skipping...
Folder 'GCA_023499715.1_PDT001311014.1' already exists. Skipping...
Folder 'GCA_023506505.1_PDT001295422.1' already exists. Skipping...
Folder 'GCA_023506625.1_PDT001295416.1' already exists. Skipping...
Folder 'GCA_023506655.1_PDT001295415.1' already exists. Skipping...
Folder 'GCA_023506695.1_PDT001295414.1' already exists. Skipping...
Folder 'GCA_023506805.1_PDT001295413.1' already exists. Skipping...
Folder 'GCA_023506825.1_PDT001295411.1' already exists. Skipping...
Folder 'GCA_023506925.1_PDT001295408.1' already exists. Skipping...
Folder 'GCA_023506985.1_PDT001295406.1' already exists. Skipping...
Folder 'GCA_023507115.1_PDT001295404.1' already exists. Skipping...
Folder 'GCA_023507175.1_PDT001295403.1' already exists. Skipping...
Folder 'GCA_023507225.1_PDT001295400.1' already exists. Skipping...
Folder 'GCA_023507275.1_PDT001295398.1' already exists. Skipping...
Folder 'GCA_023507345.1_PDT001295397.1' already exists. Skipping...
Folder 'GCA_023507425.1_PDT001295395.1' already exists. Skipping...
Folder 'GCA_023508405.1_PDT001295392.1' already exists. Skipping...
Folder 'GCA_023508485.1_PDT001295388.1' already exists. Skipping...
Folder 'GCA_023509095.1_PDT001309997.1' already exists. Skipping...
Folder 'GCA_023509115.1_PDT001309993.1' already exists. Skipping...
Folder 'GCA_023509135.1_PDT001309999.1' already exists. Skipping...
Folder 'GCA_023509155.1_PDT001309995.1' already exists. Skipping...
Folder 'GCA_023509175.1_PDT001309994.1' already exists. Skipping...
Folder 'GCA_023509195.1_PDT001309992.1' already exists. Skipping...
Folder 'GCA_023509215.1_PDT001309991.1' already exists. Skipping...
Folder 'GCA_023511135.1_PDT001311257.1' already exists. Skipping...
Folder 'GCA_023511155.1_PDT001311255.1' already exists. Skipping...
Folder 'GCA_023511195.1_PDT001311254.1' already exists. Skipping...
Folder 'GCA_023511215.1_PDT001311253.1' already exists. Skipping...
Folder 'GCA_023511235.1_PDT001311251.1' already exists. Skipping...
Folder 'GCA_023512965.1_PDT001311256.1' already exists. Skipping...
Folder 'GCA_023512985.1_PDT001311262.1' already exists. Skipping...
Folder 'GCA_023513265.1_PDT001311268.1' already exists. Skipping...
Folder 'GCA_023513305.1_PDT001311267.1' already exists. Skipping...
Folder 'GCA_023513325.1_PDT001311265.1' already exists. Skipping...
Folder 'GCA_023513345.1_PDT001311264.1' already exists. Skipping...
Folder 'GCA_023513625.1_PDT001311274.1' already exists. Skipping...
Folder 'GCA_023521285.1_PDT001312546.1' already exists. Skipping...
Folder 'GCA_023521355.1_PDT001312544.1' already exists. Skipping...
Folder 'GCA_023521795.1_PDT001312527.1' already exists. Skipping...
Folder 'GCA_023521815.1_PDT001312524.1' already exists. Skipping...
Folder 'GCA_023521835.1_PDT001312525.1' already exists. Skipping...
Folder 'GCA_023521935.1_PDT001312520.1' already exists. Skipping...
Folder 'GCA_023521975.1_PDT001312517.1' already exists. Skipping...
Folder 'GCA_023522015.1_PDT001312515.1' already exists. Skipping...
Folder 'GCA_023522055.1_PDT001312512.1' already exists. Skipping...
Folder 'GCA_023522075.1_PDT001312513.1' already exists. Skipping...
Folder 'GCA_023522115.1_PDT001312510.1' already exists. Skipping...
Folder 'GCA_023522215.1_PDT001312504.1' already exists. Skipping...
Folder 'GCA_023522255.1_PDT001312502.1' already exists. Skipping...
Folder 'GCA_023526065.1_PDT001311646.1' already exists. Skipping...
Folder 'GCA_023526125.1_PDT001311645.1' already exists. Skipping...
Folder 'GCA_023526205.1_PDT001311641.1' already exists. Skipping...
Folder 'GCA_023526225.1_PDT001311638.1' already exists. Skipping...
Folder 'GCA_023526255.1_PDT001311640.1' already exists. Skipping...
Folder 'GCA_023526385.1_PDT001311632.1' already exists. Skipping...
Folder 'GCA_023526425.1_PDT001311630.1' already exists. Skipping...
Folder 'GCA_023526445.1_PDT001311629.1' already exists. Skipping...
Folder 'GCA_023526525.1_PDT001311626.1' already exists. Skipping...
Folder 'GCA_023526545.1_PDT001311623.1' already exists. Skipping...
Folder 'GCA_023526605.1_PDT001311620.1' already exists. Skipping...
Folder 'GCA_023526625.1_PDT001311621.1' already exists. Skipping...
Folder 'GCA_023526685.1_PDT001311617.1' already exists. Skipping...
Folder 'GCA_023526835.1_PDT001313862.1' already exists. Skipping...
Folder 'GCA_023527225.1_PDT001314083.1' already exists. Skipping...
Folder 'GCA_023532595.1_PDT001314342.1' already exists. Skipping...
Folder 'GCA_023532635.1_PDT001314340.1' already exists. Skipping...
Folder 'GCA_023532655.1_PDT001314341.1' already exists. Skipping...
Folder 'GCA_023532695.1_PDT001314336.1' already exists. Skipping...
Folder 'GCA_023532755.1_PDT001314332.1' already exists. Skipping...
Folder 'GCA_023532775.1_PDT001314329.1' already exists. Skipping...
Folder 'GCA_023532795.1_PDT001314330.1' already exists. Skipping...
Folder 'GCA_023532815.1_PDT001314325.1' already exists. Skipping...
Folder 'GCA_023532855.1_PDT001314327.1' already exists. Skipping...
Folder 'GCA_023532895.1_PDT001314324.1' already exists. Skipping...
Folder 'GCA_023532935.1_PDT001314321.1' already exists. Skipping...
Folder 'GCA_023533035.1_PDT001314295.1' already exists. Skipping...
Folder 'GCA_023533255.1_PDT001314333.1' already exists. Skipping...
Folder 'GCA_023533275.1_PDT001314296.1' already exists. Skipping...
Folder 'GCA_023533415.1_PDT001314309.1' already exists. Skipping...
Folder 'GCA_023547645.1_PDT001314957.1' already exists. Skipping...

Retreiveing data: 24214it [00:05, 6692.34it/s]

Folder 'GCA_025241105.1_PDT001419667.1' already exists. Skipping...
Folder 'GCA_025241125.1_PDT001419657.1' already exists. Skipping...
Folder 'GCA_025303395.1_PDT001424669.1' already exists. Skipping...
Folder 'GCA_025303495.1_PDT001424628.1' already exists. Skipping...
Folder 'GCA_025314175.1_PDT001419692.1' already exists. Skipping...
Folder 'GCA_025314495.1_PDT001419672.1' already exists. Skipping...
Folder 'GCA_025314515.1_PDT001419662.1' already exists. Skipping...
Folder 'GCA_025314555.1_PDT001419660.1' already exists. Skipping...
Folder 'GCA_025322245.1_PDT001425154.1' already exists. Skipping...
Folder 'GCA_025334545.1_PDT001427204.1' already exists. Skipping...
Folder 'GCA_025334725.1_PDT001427200.1' already exists. Skipping...
Folder 'GCA_025339525.1_PDT001427403.1' already exists. Skipping...
Folder 'GCA_025343465.1_PDT001427208.1' already exists. Skipping...
Folder 'GCA_025359465.1_PDT001427816.1' already exists. Skipping...
Folder 'GCA_025363935.1_PDT001427901.1' already exists. Skipping...
Folder 'GCA_025364315.1_PDT001427916.1' already exists. Skipping...
Folder 'GCA_025364365.1_PDT001427918.1' already exists. Skipping...
Folder 'GCA_025382645.1_PDT001429287.1' already exists. Skipping...
Folder 'GCA_025386725.1_PDT001429674.1' already exists. Skipping...
Folder 'GCA_025387585.1_PDT001429690.1' already exists. Skipping...
Folder 'GCA_025401295.1_PDT001433844.1' already exists. Skipping...
Folder 'GCA_025401455.1_PDT001433838.1' already exists. Skipping...
Folder 'GCA_025401495.1_PDT001433834.1' already exists. Skipping...
Folder 'GCA_025401595.1_PDT001433830.1' already exists. Skipping...
Folder 'GCA_025401635.1_PDT001433827.1' already exists. Skipping...
Folder 'GCA_025401655.1_PDT001433826.1' already exists. Skipping...
Folder 'GCA_025401695.1_PDT001433825.1' already exists. Skipping...
Folder 'GCA_025410685.1_PDT001434232.1' already exists. Skipping...
Folder 'GCA_025416315.1_PDT001434425.1' already exists. Skipping...
Folder 'GCA_025417335.1_PDT001434498.1' already exists. Skipping...
Folder 'GCA_025417375.1_PDT001434495.1' already exists. Skipping...
Folder 'GCA_025417395.1_PDT001434492.1' already exists. Skipping...
Folder 'GCA_025417455.1_PDT001434463.1' already exists. Skipping...
Folder 'GCA_025417535.1_PDT001434457.1' already exists. Skipping...
Folder 'GCA_025418675.1_PDT001434511.1' already exists. Skipping...
Folder 'GCA_025418775.1_PDT001434477.1' already exists. Skipping...
Folder 'GCA_025419335.1_PDT001434521.1' already exists. Skipping...
Folder 'GCA_025419655.1_PDT001434461.1' already exists. Skipping...
Folder 'GCA_025423055.1_PDT001434483.1' already exists. Skipping...
Folder 'GCA_025425415.1_PDT001430209.1' already exists. Skipping...
Folder 'GCA_025443895.1_PDT001435211.1' already exists. Skipping...
Folder 'GCA_025443915.1_PDT001435206.1' already exists. Skipping...
Folder 'GCA_025443995.1_PDT001435194.1' already exists. Skipping...
Folder 'GCA_025444115.1_PDT001435204.1' already exists. Skipping...
Folder 'GCA_025444215.1_PDT001435226.1' already exists. Skipping...
Folder 'GCA_025444295.1_PDT001435220.1' already exists. Skipping...
Folder 'GCA_025444335.1_PDT001435213.1' already exists. Skipping...
Folder 'GCA_025444495.1_PDT001435222.1' already exists. Skipping...
Folder 'GCA_025444535.1_PDT001435221.1' already exists. Skipping...
Folder 'GCA_025445115.1_PDT001435217.1' already exists. Skipping...
Folder 'GCA_025445295.1_PDT001435219.1' already exists. Skipping...
Folder 'GCA_025452275.1_PDT001435223.1' already exists. Skipping...
Folder 'GCA_025476215.1_PDT001436554.1' already exists. Skipping...
Folder 'GCA_025476235.1_PDT001436553.1' already exists. Skipping...
Folder 'GCA_025476295.1_PDT001436548.1' already exists. Skipping...
Folder 'GCA_025476315.1_PDT001436547.1' already exists. Skipping...
Folder 'GCA_025476355.1_PDT001436543.1' already exists. Skipping...
Folder 'GCA_025476375.1_PDT001436540.1' already exists. Skipping...
Folder 'GCA_025476395.1_PDT001436538.1' already exists. Skipping...
Folder 'GCA_025476565.1_PDT001436535.1' already exists. Skipping...
Folder 'GCA_025484855.1_PDT001436567.1' already exists. Skipping...
Folder 'GCA_025485015.1_PDT001436541.1' already exists. Skipping...
Folder 'GCA_025498785.1_PDT001437344.1' already exists. Skipping...
Folder 'GCA_025498805.1_PDT001437345.1' already exists. Skipping...
Folder 'GCA_025498825.1_PDT001437340.1' already exists. Skipping...
Folder 'GCA_025498845.1_PDT001437342.1' already exists. Skipping...
Folder 'GCA_025498865.1_PDT001437337.1' already exists. Skipping...
Folder 'GCA_025498905.1_PDT001437338.1' already exists. Skipping...
Folder 'GCA_025498925.1_PDT001437336.1' already exists. Skipping...
Folder 'GCA_025499005.1_PDT001437329.1' already exists. Skipping...
Folder 'GCA_025499045.1_PDT001437328.1' already exists. Skipping...
Folder 'GCA_025499085.1_PDT001437322.1' already exists. Skipping...
Folder 'GCA_025499105.1_PDT001437323.1' already exists. Skipping...
Folder 'GCA_025499125.1_PDT001437327.1' already exists. Skipping...
Folder 'GCA_025499145.1_PDT001437319.1' already exists. Skipping...
Folder 'GCA_025499165.1_PDT001437316.1' already exists. Skipping...
Folder 'GCA_025499225.1_PDT001437324.1' already exists. Skipping...
Folder 'GCA_025499475.1_PDT001437325.1' already exists. Skipping...
Folder 'GCA_025499495.1_PDT001437320.1' already exists. Skipping...
Folder 'GCA_025499535.1_PDT001437321.1' already exists. Skipping...
Folder 'GCA_025500485.1_PDT001437391.1' already exists. Skipping...
Folder 'GCA_025506835.1_PDT001438388.1' already exists. Skipping...
Folder 'GCA_025506915.1_PDT001438397.1' already exists. Skipping...
Folder 'GCA_025506935.1_PDT001438389.1' already exists. Skipping...
Folder 'GCA_025506955.1_PDT001438391.1' already exists. Skipping...
Folder 'GCA_025506975.1_PDT001438413.1' already exists. Skipping...
Folder 'GCA_025506995.1_PDT001438406.1' already exists. Skipping...
Folder 'GCA_025507155.1_PDT001438395.1' already exists. Skipping...
Folder 'GCA_025508155.1_PDT001438640.1' already exists. Skipping...
Folder 'GCA_025508175.1_PDT001438637.1' already exists. Skipping...
Folder 'GCA_025508275.1_PDT001438634.1' already exists. Skipping...
Folder 'GCA_025508295.1_PDT001438623.1' already exists. Skipping...
Folder 'GCA_025508775.1_PDT001438620.1' already exists. Skipping...
Folder 'GCA_025508795.1_PDT001438630.1' already exists. Skipping...
Folder 'GCA_025508875.1_PDT001438392.1' already exists. Skipping...
Folder 'GCA_025509975.1_PDT001438621.1' already exists. Skipping...
Folder 'GCA_025510295.1_PDT001438625.1' already exists. Skipping...
Folder 'GCA_025512655.1_PDT001438963.1' already exists. Skipping...
Folder 'GCA_025520065.1_PDT001438985.1' already exists. Skipping...
Folder 'GCA_025520095.1_PDT001438981.1' already exists. Skipping...
Folder 'GCA_025520115.1_PDT001438983.1' already exists. Skipping...
Folder 'GCA_025520135.1_PDT001438979.1' already exists. Skipping...
Folder 'GCA_025520155.1_PDT001438975.1' already exists. Skipping...
Folder 'GCA_025520165.1_PDT001438978.1' already exists. Skipping...
Folder 'GCA_025520195.1_PDT001438974.1' already exists. Skipping...
Folder 'GCA_025520215.1_PDT001438976.1' already exists. Skipping...
Folder 'GCA_025520275.1_PDT001438965.1' already exists. Skipping...
Folder 'GCA_025520295.1_PDT001438966.1' already exists. Skipping...
Folder 'GCA_025520315.1_PDT001438964.1' already exists. Skipping...
Folder 'GCA_025520335.1_PDT001438961.1' already exists. Skipping...
Folder 'GCA_025520395.1_PDT001438958.1' already exists. Skipping...
Folder 'GCA_025520675.1_PDT001438407.1' already exists. Skipping...
Folder 'GCA_025520695.1_PDT001438393.1' already exists. Skipping...
Folder 'GCA_025520815.1_PDT001439464.1' already exists. Skipping...
Folder 'GCA_025530195.1_PDT001438973.1' already exists. Skipping...
Folder 'GCA_025530215.1_PDT001438972.1' already exists. Skipping...
Folder 'GCA_025530295.1_PDT001438959.1' already exists. Skipping...
Folder 'GCA_025534475.1_PDT001440448.1' already exists. Skipping...
Folder 'GCA_025535035.1_PDT001440454.1' already exists. Skipping...
Folder 'GCA_025535095.1_PDT001440449.1' already exists. Skipping...
Folder 'GCA_025535115.1_PDT001440446.1' already exists. Skipping...
Folder 'GCA_025535255.1_PDT001440451.1' already exists. Skipping...
Folder 'GCA_025535275.1_PDT001440461.1' already exists. Skipping...
Folder 'GCA_025535295.1_PDT001440445.1' already exists. Skipping...
Folder 'GCA_025535735.1_PDT001440438.1' already exists. Skipping...
Folder 'GCA_025540435.1_PDT001440460.1' already exists. Skipping...
Folder 'GCA_025544895.1_PDT001441102.1' already exists. Skipping...
Folder 'GCA_025574745.1_PDT001442597.1' already exists. Skipping...
Folder 'GCA_025575485.1_PDT001442559.1' already exists. Skipping...
Folder 'GCA_025575645.1_PDT001442553.1' already exists. Skipping...
Folder 'GCA_025576045.1_PDT001442532.1' already exists. Skipping...
Folder 'GCA_025576265.1_PDT001442520.1' already exists. Skipping...
Folder 'GCA_025576325.1_PDT001442517.1' already exists. Skipping...
Folder 'GCA_025576365.1_PDT001442516.1' already exists. Skipping...
Folder 'GCA_025576485.1_PDT001442510.1' already exists. Skipping...
Folder 'GCA_025576505.1_PDT001442509.1' already exists. Skipping...
Folder 'GCA_025576665.1_PDT001442498.1' already exists. Skipping...
Folder 'GCA_025576785.1_PDT001442497.1' already exists. Skipping...
Folder 'GCA_025576805.1_PDT001442496.1' already exists. Skipping...
Folder 'GCA_025576865.1_PDT001442489.1' already exists. Skipping...
Folder 'GCA_025576945.1_PDT001442485.1' already exists. Skipping...
Folder 'GCA_025577165.1_PDT001442476.1' already exists. Skipping...
Folder 'GCA_025577225.1_PDT001442474.1' already exists. Skipping...
Folder 'GCA_025607255.1_PDT001444550.1' already exists. Skipping...
Folder 'GCA_025610275.1_PDT001444801.1' already exists. Skipping...
Folder 'GCA_025610295.1_PDT001444800.1' already exists. Skipping...
Folder 'GCA_025610315.1_PDT001444786.1' already exists. Skipping...
Folder 'GCA_025617765.1_PDT001445404.1' already exists. Skipping...
Folder 'GCA_025620685.1_PDT001446357.1' already exists. Skipping...
Folder 'GCA_025620805.1_PDT001446376.1' already exists. Skipping...
Folder 'GCA_025620905.1_PDT001446542.1' already exists. Skipping...
Folder 'GCA_025621585.1_PDT001446538.1' already exists. Skipping...
Folder 'GCA_025621605.1_PDT001446564.1' already exists. Skipping...
Folder 'GCA_025621645.1_PDT001446539.1' already exists. Skipping...
Folder 'GCA_025621765.1_PDT001446525.1' already exists. Skipping...
Folder 'GCA_025621885.1_PDT001446526.1' already exists. Skipping...
Folder 'GCA_025621905.1_PDT001446517.1' already exists. Skipping...
Folder 'GCA_025621925.1_PDT001446519.1' already exists. Skipping...
Folder 'GCA_025621965.1_PDT001446513.1' already exists. Skipping...
Folder 'GCA_025622105.1_PDT001446500.1' already exists. Skipping...
Folder 'GCA_025622585.1_PDT001446518.1' already exists. Skipping...
Folder 'GCA_025622605.1_PDT001446521.1' already exists. Skipping...
Folder 'GCA_025622625.1_PDT001446504.1' already exists. Skipping...
Folder 'GCA_025622645.1_PDT001446501.1' already exists. Skipping...
Folder 'GCA_025623625.1_PDT001446496.1' already exists. Skipping...
Folder 'GCA_025623645.1_PDT001446499.1' already exists. Skipping...
Folder 'GCA_025624005.1_PDT001446358.1' already exists. Skipping...
Folder 'GCA_025631485.1_PDT001446503.1' already exists. Skipping...
Folder 'GCA_025644445.1_PDT001450310.1' already exists. Skipping...
Folder 'GCA_025644595.1_PDT001450315.1' already exists. Skipping...
Folder 'GCA_025646695.1_PDT001450294.1' already exists. Skipping...
Folder 'GCA_025647775.1_PDT001450454.1' already exists. Skipping...
Folder 'GCA_025647815.1_PDT001450452.1' already exists. Skipping...
Folder 'GCA_025647835.1_PDT001450448.1' already exists. Skipping...
Folder 'GCA_025647875.1_PDT001450443.1' already exists. Skipping...
Folder 'GCA_025647935.1_PDT001450432.1' already exists. Skipping...
Folder 'GCA_025647955.1_PDT001450436.1' already exists. Skipping...
Folder 'GCA_025647965.1_PDT001450435.1' already exists. Skipping...
Folder 'GCA_025648175.1_PDT001450313.1' already exists. Skipping...
Folder 'GCA_025649695.1_PDT001450319.1' already exists. Skipping...
Folder 'GCA_025649775.1_PDT001450308.1' already exists. Skipping...
Folder 'GCA_025649795.1_PDT001450309.1' already exists. Skipping...
Folder 'GCA_025649855.1_PDT001450289.1' already exists. Skipping...
Folder 'GCA_025649875.1_PDT001450293.1' already exists. Skipping...
Folder 'GCA_025650595.1_PDT001450460.1' already exists. Skipping...
Folder 'GCA_025650695.1_PDT001450318.1' already exists. Skipping...
Folder 'GCA_025652455.1_PDT001450304.1' already exists. Skipping...
Folder 'GCA_025652475.1_PDT001450301.1' already exists. Skipping...
Folder 'GCA_025669085.1_PDT001450952.1' already exists. Skipping...
Folder 'GCA_025670685.1_PDT001450949.1' already exists. Skipping...
Folder 'GCA_025678075.1_PDT001450490.1' already exists. Skipping...
Folder 'GCA_025678455.1_PDT001450440.1' already exists. Skipping...
Folder 'GCA_025678475.1_PDT001450427.1' already exists. Skipping...
Folder 'GCA_025678515.1_PDT001450444.1' already exists. Skipping...
Folder 'GCA_025678555.1_PDT001450433.1' already exists. Skipping...
Folder 'GCA_025678875.1_PDT001450324.1' already exists. Skipping...
Folder 'GCA_025678955.1_PDT001450317.1' already exists. Skipping...
Folder 'GCA_025678975.1_PDT001450314.1' already exists. Skipping...
Folder 'GCA_025679035.1_PDT001450299.1' already exists. Skipping...
Folder 'GCA_025679315.1_PDT001450297.1' already exists. Skipping...
Folder 'GCA_025686255.1_PDT001452211.1' already exists. Skipping...
Folder 'GCA_025686815.1_PDT001452229.1' already exists. Skipping...
Folder 'GCA_025686835.1_PDT001452230.1' already exists. Skipping...
Folder 'GCA_025686875.1_PDT001452220.1' already exists. Skipping...
Folder 'GCA_025686895.1_PDT001452225.1' already exists. Skipping...
Folder 'GCA_025686935.1_PDT001452222.1' already exists. Skipping...
Folder 'GCA_025686955.1_PDT001452217.1' already exists. Skipping...
Folder 'GCA_025686975.1_PDT001452205.1' already exists. Skipping...
Folder 'GCA_025687335.1_PDT001452213.1' already exists. Skipping...
Folder 'GCA_025687475.1_PDT001452227.1' already exists. Skipping...
Folder 'GCA_025687535.1_PDT001452228.1' already exists. Skipping...
Folder 'GCA_025692925.1_PDT001452979.1' already exists. Skipping...
Folder 'GCA_025693005.1_PDT001452976.1' already exists. Skipping...
Folder 'GCA_025693025.1_PDT001452974.1' already exists. Skipping...
Folder 'GCA_025693085.1_PDT001452971.1' already exists. Skipping...
Folder 'GCA_025693105.1_PDT001452972.1' already exists. Skipping...
Folder 'GCA_025693145.1_PDT001452969.1' already exists. Skipping...
Folder 'GCA_025693195.1_PDT001452967.1' already exists. Skipping...
Folder 'GCA_025693265.1_PDT001452961.1' already exists. Skipping...
Folder 'GCA_025693365.1_PDT001452957.1' already exists. Skipping...
Folder 'GCA_025693385.1_PDT001452954.1' already exists. Skipping...
Folder 'GCA_025693405.1_PDT001452956.1' already exists. Skipping...
Folder 'GCA_025693425.1_PDT001452955.1' already exists. Skipping...
Folder 'GCA_025693445.1_PDT001452958.1' already exists. Skipping...
Folder 'GCA_025693465.1_PDT001452953.1' already exists. Skipping...
Folder 'GCA_025693485.1_PDT001452951.1' already exists. Skipping...
Folder 'GCA_025704205.1_PDT001454007.1' already exists. Skipping...
Folder 'GCA_025704245.1_PDT001454003.1' already exists. Skipping...
Folder 'GCA_025704285.1_PDT001453970.1' already exists. Skipping...
Folder 'GCA_025704305.1_PDT001453987.1' already exists. Skipping...
Folder 'GCA_025704365.1_PDT001453967.1' already exists. Skipping...
Folder 'GCA_025707605.1_PDT001453992.1' already exists. Skipping...
Folder 'GCA_025707625.1_PDT001453990.1' already exists. Skipping...
Folder 'GCA_025709925.1_PDT001453999.1' already exists. Skipping...
Folder 'GCA_025710005.1_PDT001454010.1' already exists. Skipping...
Folder 'GCA_025712585.1_PDT001454002.1' already exists. Skipping...
Folder 'GCA_025712665.1_PDT001454006.1' already exists. Skipping...
Folder 'GCA_025724445.1_PDT001454482.1' already exists. Skipping...
Folder 'GCA_025724465.1_PDT001454488.1' already exists. Skipping...
Folder 'GCA_025724485.1_PDT001454486.1' already exists. Skipping...
Folder 'GCA_025724505.1_PDT001454483.1' already exists. Skipping...
Folder 'GCA_025724565.1_PDT001454476.1' already exists. Skipping...
Folder 'GCA_025724605.1_PDT001454475.1' already exists. Skipping...
Folder 'GCA_025724765.1_PDT001454463.1' already exists. Skipping...
Folder 'GCA_025724925.1_PDT001454461.1' already exists. Skipping...
Folder 'GCA_025724945.1_PDT001454458.1' already exists. Skipping...
Folder 'GCA_025724985.1_PDT001454456.1' already exists. Skipping...
Folder 'GCA_025725025.1_PDT001454453.1' already exists. Skipping...
Folder 'GCA_025725045.1_PDT001454452.1' already exists. Skipping...
Folder 'GCA_025725065.1_PDT001454450.1' already exists. Skipping...
Folder 'GCA_025726565.1_PDT001454490.1' already exists. Skipping...
Folder 'GCA_025728155.1_PDT001455517.1' already exists. Skipping...
Folder 'GCA_025805435.1_PDT001463291.1' already exists. Skipping...
Folder 'GCA_025805475.1_PDT001463295.1' already exists. Skipping...
Folder 'GCA_025805495.1_PDT001463294.1' already exists. Skipping...
Folder 'GCA_025805575.1_PDT001463288.1' already exists. Skipping...
Folder 'GCA_025805595.1_PDT001463286.1' already exists. Skipping...
Folder 'GCA_025805715.1_PDT001463285.1' already exists. Skipping...
Folder 'GCA_025805975.1_PDT001463270.1' already exists. Skipping...
Folder 'GCA_025806075.1_PDT001463268.1' already exists. Skipping...
Folder 'GCA_025806235.1_PDT001463257.1' already exists. Skipping...
Folder 'GCA_025807535.1_PDT001463191.1' already exists. Skipping...
Folder 'GCA_025807595.1_PDT001463188.1' already exists. Skipping...
Folder 'GCA_025807735.1_PDT001463179.1' already exists. Skipping...
Folder 'GCA_025808115.1_PDT001463158.1' already exists. Skipping...
Folder 'GCA_025808715.1_PDT001463142.1' already exists. Skipping...
Folder 'GCA_025808815.1_PDT001463136.1' already exists. Skipping...
Folder 'GCA_025808835.1_PDT001463140.1' already exists. Skipping...
Folder 'GCA_025809155.1_PDT001463121.1' already exists. Skipping...
Folder 'GCA_025809495.1_PDT001463116.1' already exists. Skipping...
Folder 'GCA_025809535.1_PDT001463109.1' already exists. Skipping...
Folder 'GCA_025809595.1_PDT001463111.1' already exists. Skipping...
Folder 'GCA_025809775.1_PDT001463097.1' already exists. Skipping...
Folder 'GCA_025809935.1_PDT001463089.1' already exists. Skipping...
Folder 'GCA_025809995.1_PDT001463086.1' already exists. Skipping...
Folder 'GCA_025810315.1_PDT001463068.1' already exists. Skipping...
Folder 'GCA_025810335.1_PDT001463070.1' already exists. Skipping...
Folder 'GCA_025810495.1_PDT001463055.1' already exists. Skipping...
Folder 'GCA_025810535.1_PDT001463056.1' already exists. Skipping...
Folder 'GCA_025810895.1_PDT001463030.1' already exists. Skipping...
Folder 'GCA_025810995.1_PDT001463025.1' already exists. Skipping...
Folder 'GCA_025811235.1_PDT001463012.1' already exists. Skipping...
Folder 'GCA_025811335.1_PDT001463006.1' already exists. Skipping...
Folder 'GCA_025811515.1_PDT001463002.1' already exists. Skipping...
Folder 'GCA_025811595.1_PDT001462994.1' already exists. Skipping...
Folder 'GCA_025811695.1_PDT001462988.1' already exists. Skipping...
Folder 'GCA_025811755.1_PDT001462984.1' already exists. Skipping...
Folder 'GCA_025811835.1_PDT001462980.1' already exists. Skipping...
Folder 'GCA_025812075.1_PDT001462965.1' already exists. Skipping...
Folder 'GCA_025812275.1_PDT001462956.1' already exists. Skipping...
Folder 'GCA_025812395.1_PDT001462949.1' already exists. Skipping...
Folder 'GCA_025812835.1_PDT001462926.1' already exists. Skipping...
Folder 'GCA_025813015.1_PDT001462917.1' already exists. Skipping...
Folder 'GCA_025813255.1_PDT001462906.1' already exists. Skipping...

Retreiveing data: 25561it [00:05, 6694.01it/s]

Folder 'GCA_028447965.1_PDT001601392.1' already exists. Skipping...
Folder 'GCA_028447985.1_PDT001601384.1' already exists. Skipping...
Folder 'GCA_028448005.1_PDT001601385.1' already exists. Skipping...
Folder 'GCA_028448045.1_PDT001601383.1' already exists. Skipping...
Folder 'GCA_028448645.1_PDT001601362.1' already exists. Skipping...
Folder 'GCA_028460145.1_PDT001602624.1' already exists. Skipping...
Folder 'GCA_028460525.1_PDT001602618.1' already exists. Skipping...
Folder 'GCA_028461225.1_PDT001602617.1' already exists. Skipping...
Folder 'GCA_028511455.1_PDT001607428.1' already exists. Skipping...
Folder 'GCA_028511515.1_PDT001607424.1' already exists. Skipping...
Folder 'GCA_028511595.1_PDT001607421.1' already exists. Skipping...
Folder 'GCA_028511615.1_PDT001607418.1' already exists. Skipping...
Folder 'GCA_028511655.1_PDT001607415.1' already exists. Skipping...
Folder 'GCA_028511735.1_PDT001607399.1' already exists. Skipping...
Folder 'GCA_028511755.1_PDT001607401.1' already exists. Skipping...
Folder 'GCA_028511775.1_PDT001607398.1' already exists. Skipping...
Folder 'GCA_028511855.1_PDT001607393.1' already exists. Skipping...
Folder 'GCA_028511875.1_PDT001607390.1' already exists. Skipping...
Folder 'GCA_028511895.1_PDT001607385.1' already exists. Skipping...
Folder 'GCA_028512435.1_PDT001607504.1' already exists. Skipping...
Folder 'GCA_028512455.1_PDT001607511.1' already exists. Skipping...
Folder 'GCA_028512555.1_PDT001607391.1' already exists. Skipping...
Folder 'GCA_028513415.1_PDT001607392.1' already exists. Skipping...
Folder 'GCA_028514255.1_PDT001607419.1' already exists. Skipping...
Folder 'GCA_028514415.1_PDT001607404.1' already exists. Skipping...
Folder 'GCA_028515365.1_PDT001607510.1' already exists. Skipping...
Folder 'GCA_028516365.1_PDT001607577.1' already exists. Skipping...
Folder 'GCA_028516425.1_PDT001607573.1' already exists. Skipping...
Folder 'GCA_028516445.1_PDT001607568.1' already exists. Skipping...
Folder 'GCA_028516525.1_PDT001607558.1' already exists. Skipping...
Folder 'GCA_028516565.1_PDT001607557.1' already exists. Skipping...
Folder 'GCA_028516585.1_PDT001607556.1' already exists. Skipping...
Folder 'GCA_028516645.1_PDT001607522.1' already exists. Skipping...
Folder 'GCA_028516685.1_PDT001607524.1' already exists. Skipping...
Folder 'GCA_028517645.1_PDT001607601.1' already exists. Skipping...
Folder 'GCA_028517685.1_PDT001607594.1' already exists. Skipping...
Folder 'GCA_028517705.1_PDT001607604.1' already exists. Skipping...
Folder 'GCA_028517725.1_PDT001607584.1' already exists. Skipping...
Folder 'GCA_028517745.1_PDT001607583.1' already exists. Skipping...
Folder 'GCA_028517765.1_PDT001607579.1' already exists. Skipping...
Folder 'GCA_028517825.1_PDT001607561.1' already exists. Skipping...
Folder 'GCA_028517865.1_PDT001607533.1' already exists. Skipping...
Folder 'GCA_028517945.1_PDT001607525.1' already exists. Skipping...
Folder 'GCA_028517985.1_PDT001607521.1' already exists. Skipping...
Folder 'GCA_028518445.1_PDT001607528.1' already exists. Skipping...
Folder 'GCA_028518485.1_PDT001607514.1' already exists. Skipping...
Folder 'GCA_028519265.1_PDT001607518.1' already exists. Skipping...
Folder 'GCA_028520025.1_PDT001607855.1' already exists. Skipping...
Folder 'GCA_028520045.1_PDT001607853.1' already exists. Skipping...
Folder 'GCA_028520065.1_PDT001607852.1' already exists. Skipping...
Folder 'GCA_028520105.1_PDT001607848.1' already exists. Skipping...
Folder 'GCA_028520145.1_PDT001607847.1' already exists. Skipping...
Folder 'GCA_028520185.1_PDT001607845.1' already exists. Skipping...
Folder 'GCA_028520225.1_PDT001607839.1' already exists. Skipping...
Folder 'GCA_028520265.1_PDT001607838.1' already exists. Skipping...
Folder 'GCA_028520285.1_PDT001607835.1' already exists. Skipping...
Folder 'GCA_028520305.1_PDT001607832.1' already exists. Skipping...
Folder 'GCA_028520785.1_PDT001607842.1' already exists. Skipping...
Folder 'GCA_028520865.1_PDT001607841.1' already exists. Skipping...
Folder 'GCA_028520885.1_PDT001607836.1' already exists. Skipping...
Folder 'GCA_028520905.1_PDT001607834.1' already exists. Skipping...
Folder 'GCA_028529285.1_PDT001607833.1' already exists. Skipping...
Folder 'GCA_028541755.1_PDT001609257.1' already exists. Skipping...
Folder 'GCA_028541775.1_PDT001609262.1' already exists. Skipping...
Folder 'GCA_028541795.1_PDT001609258.1' already exists. Skipping...
Folder 'GCA_028541835.1_PDT001609251.1' already exists. Skipping...
Folder 'GCA_028541855.1_PDT001609252.1' already exists. Skipping...
Folder 'GCA_028541875.1_PDT001609245.1' already exists. Skipping...
Folder 'GCA_028541915.1_PDT001609256.1' already exists. Skipping...
Folder 'GCA_028541935.1_PDT001609239.1' already exists. Skipping...
Folder 'GCA_028541955.1_PDT001609242.1' already exists. Skipping...
Folder 'GCA_028542035.1_PDT001609236.1' already exists. Skipping...
Folder 'GCA_028542225.1_PDT001609233.1' already exists. Skipping...
Folder 'GCA_028542315.1_PDT001609259.1' already exists. Skipping...
Folder 'GCA_028542335.1_PDT001609254.1' already exists. Skipping...
Folder 'GCA_028542375.1_PDT001609235.1' already exists. Skipping...
Folder 'GCA_028542435.1_PDT001609248.1' already exists. Skipping...
Folder 'GCA_028542675.1_PDT001609261.1' already exists. Skipping...
Folder 'GCA_028542695.1_PDT001609250.1' already exists. Skipping...
Folder 'GCA_028550505.1_ASM2855050v1' already exists. Skipping...
Folder 'GCA_028550535.1_ASM2855053v1' already exists. Skipping...
Folder 'GCA_028557615.1_PDT001610541.1' already exists. Skipping...
Folder 'GCA_028557695.1_PDT001610486.1' already exists. Skipping...
Folder 'GCA_028557735.1_PDT001610538.1' already exists. Skipping...
Folder 'GCA_028558175.1_PDT001610535.1' already exists. Skipping...
Folder 'GCA_028562595.1_PDT001611065.1' already exists. Skipping...
Folder 'GCA_028562675.1_PDT001611062.1' already exists. Skipping...
Folder 'GCA_028562775.1_PDT001611057.1' already exists. Skipping...
Folder 'GCA_028563415.1_PDT001611025.1' already exists. Skipping...
Folder 'GCA_028570005.1_ASM2857000v1' already exists. Skipping...
Folder 'GCA_028570015.1_ASM2857001v1' already exists. Skipping...
Folder 'GCA_028570045.1_ASM2857004v1' already exists. Skipping...
Folder 'GCA_028570065.1_ASM2857006v1' already exists. Skipping...
Folder 'GCA_028570085.1_ASM2857008v1' already exists. Skipping...
Folder 'GCA_028570105.1_ASM2857010v1' already exists. Skipping...
Folder 'GCA_028570125.1_ASM2857012v1' already exists. Skipping...
Folder 'GCA_028570185.1_ASM2857018v1' already exists. Skipping...
Folder 'GCA_028570245.1_ASM2857024v1' already exists. Skipping...
Folder 'GCA_028570265.1_ASM2857026v1' already exists. Skipping...
Folder 'GCA_028570475.1_ASM2857047v1' already exists. Skipping...
Folder 'GCA_028570505.1_ASM2857050v1' already exists. Skipping...
Folder 'GCA_028570525.1_ASM2857052v1' already exists. Skipping...
Folder 'GCA_028570625.1_ASM2857062v1' already exists. Skipping...
Folder 'GCA_028570635.1_ASM2857063v1' already exists. Skipping...
Folder 'GCA_028570645.1_ASM2857064v1' already exists. Skipping...
Folder 'GCA_028570685.1_ASM2857068v1' already exists. Skipping...
Folder 'GCA_028570705.1_ASM2857070v1' already exists. Skipping...
Folder 'GCA_028570745.1_ASM2857074v1' already exists. Skipping...
Folder 'GCA_028572645.1_PDT001611228.1' already exists. Skipping...
Folder 'GCA_028574055.1_PDT001611311.1' already exists. Skipping...
Folder 'GCA_028574135.1_PDT001611312.1' already exists. Skipping...
Folder 'GCA_028581805.1_PDT001611582.1' already exists. Skipping...
Folder 'GCA_028581895.1_PDT001611577.1' already exists. Skipping...
Folder 'GCA_028581915.1_PDT001611576.1' already exists. Skipping...
Folder 'GCA_028581955.1_PDT001611573.1' already exists. Skipping...
Folder 'GCA_028581975.1_PDT001611574.1' already exists. Skipping...
Folder 'GCA_028582075.1_PDT001611568.1' already exists. Skipping...
Folder 'GCA_028582095.1_PDT001611567.1' already exists. Skipping...
Folder 'GCA_028582115.1_PDT001611566.1' already exists. Skipping...
Folder 'GCA_028590505.1_PDT001612312.1' already exists. Skipping...
Folder 'GCA_028590625.1_PDT001612268.1' already exists. Skipping...
Folder 'GCA_028590785.1_PDT001612300.1' already exists. Skipping...
Folder 'GCA_028590905.1_PDT001612284.1' already exists. Skipping...
Folder 'GCA_028590945.1_PDT001612282.1' already exists. Skipping...
Folder 'GCA_028590965.1_PDT001612277.1' already exists. Skipping...
Folder 'GCA_028590985.1_PDT001612283.1' already exists. Skipping...
Folder 'GCA_028591025.1_PDT001612271.1' already exists. Skipping...
Folder 'GCA_028591105.1_PDT001612266.1' already exists. Skipping...
Folder 'GCA_028591145.1_PDT001612252.1' already exists. Skipping...
Folder 'GCA_028591165.1_PDT001612260.1' already exists. Skipping...
Folder 'GCA_028591225.1_PDT001612255.1' already exists. Skipping...
Folder 'GCA_028591305.1_PDT001612290.1' already exists. Skipping...
Folder 'GCA_028591365.1_PDT001612316.1' already exists. Skipping...
Folder 'GCA_028591425.1_PDT001612280.1' already exists. Skipping...
Folder 'GCA_028591525.1_PDT001612275.1' already exists. Skipping...
Folder 'GCA_028591545.1_PDT001612259.1' already exists. Skipping...
Folder 'GCA_028591565.1_PDT001612251.1' already exists. Skipping...
Folder 'GCA_028591595.1_PDT001612256.1' already exists. Skipping...
Folder 'GCA_028592345.1_PDT001612314.1' already exists. Skipping...
Folder 'GCA_028592465.1_PDT001612281.1' already exists. Skipping...
Folder 'GCA_028592505.1_PDT001612315.1' already exists. Skipping...
Folder 'GCA_028592825.1_PDT001612289.1' already exists. Skipping...
Folder 'GCA_028593205.1_PDT001612253.1' already exists. Skipping...
Folder 'GCA_028603645.1_PDT001612650.1' already exists. Skipping...
Folder 'GCA_028603685.1_PDT001612649.1' already exists. Skipping...
Folder 'GCA_028603705.1_PDT001612648.1' already exists. Skipping...
Folder 'GCA_028603725.1_PDT001612647.1' already exists. Skipping...
Folder 'GCA_028603865.1_PDT001612639.1' already exists. Skipping...
Folder 'GCA_028603965.1_PDT001612636.1' already exists. Skipping...
Folder 'GCA_028603985.1_PDT001612632.1' already exists. Skipping...
Folder 'GCA_028604005.1_PDT001612633.1' already exists. Skipping...
Folder 'GCA_028604025.1_PDT001612634.1' already exists. Skipping...
Folder 'GCA_028604065.1_PDT001612631.1' already exists. Skipping...
Folder 'GCA_028604125.1_PDT001612628.1' already exists. Skipping...
Folder 'GCA_028604145.1_PDT001612627.1' already exists. Skipping...
Folder 'GCA_028604205.1_PDT001612621.1' already exists. Skipping...
Folder 'GCA_028606745.1_PDT001612495.1' already exists. Skipping...
Folder 'GCA_028606785.1_PDT001612493.1' already exists. Skipping...
Folder 'GCA_028606835.1_PDT001612490.1' already exists. Skipping...
Folder 'GCA_028606885.1_PDT001612488.1' already exists. Skipping...
Folder 'GCA_028606925.1_PDT001612486.1' already exists. Skipping...
Folder 'GCA_028607465.1_PDT001612481.1' already exists. Skipping...
Folder 'GCA_028611635.1_PDT001613888.1' already exists. Skipping...
Folder 'GCA_028613255.1_PDT001614332.1' already exists. Skipping...
Folder 'GCA_028623345.1_PDT001614372.1' already exists. Skipping...
Folder 'GCA_028626945.1_PDT001615354.1' already exists. Skipping...
Folder 'GCA_028629285.1_PDT001615353.1' already exists. Skipping...
Folder 'GCA_028632005.1_PDT001615349.1' already exists. Skipping...
Folder 'GCA_028634725.1_PDT001615356.1' already exists. Skipping...
Folder 'GCA_028635145.1_PDT001615374.1' already exists. Skipping...
Folder 'GCA_028636615.1_PDT001615344.1' already exists. Skipping...
Folder 'GCA_028638635.1_PDT001615370.1' already exists. Skipping...
Folder 'GCA_028643855.1_PDT001616464.1' already exists. Skipping...
Folder 'GCA_028649375.1_ASM2864937v1' already exists. Skipping...
Folder 'GCA_028658685.1_PDT001617142.1' already exists. Skipping...
Folder 'GCA_028658705.1_PDT001617127.1' already exists. Skipping...
Folder 'GCA_028658725.1_PDT001617137.1' already exists. Skipping...
Folder 'GCA_028658745.1_PDT001617128.1' already exists. Skipping...
Folder 'GCA_028658775.1_PDT001617126.1' already exists. Skipping...
Folder 'GCA_028658815.1_PDT001617132.1' already exists. Skipping...
Folder 'GCA_028658855.1_PDT001617134.1' already exists. Skipping...
Folder 'GCA_028660815.1_PDT001617141.1' already exists. Skipping...
Folder 'GCA_028660855.1_PDT001617139.1' already exists. Skipping...
Folder 'GCA_028666635.1_PDT001617258.1' already exists. Skipping...
Folder 'GCA_028671435.1_PDT001617462.1' already exists. Skipping...
Folder 'GCA_028671495.1_PDT001617452.1' already exists. Skipping...
Folder 'GCA_028671515.1_PDT001617454.1' already exists. Skipping...
Folder 'GCA_028671535.1_PDT001617457.1' already exists. Skipping...
Folder 'GCA_028671575.1_PDT001617451.1' already exists. Skipping...
Folder 'GCA_028672265.1_PDT001617461.1' already exists. Skipping...
Folder 'GCA_028672315.1_PDT001617460.1' already exists. Skipping...
Folder 'GCA_028672395.1_PDT001617455.1' already exists. Skipping...
Folder 'GCA_028672745.1_PDT001617459.1' already exists. Skipping...
Folder 'GCA_028675065.1_PDT001618399.1' already exists. Skipping...
Folder 'GCA_028725085.1_ASM2872508v1' already exists. Skipping...
Folder 'GCA_028738655.1_PDT001618871.1' already exists. Skipping...
Folder 'GCA_028738735.1_PDT001632560.1' already exists. Skipping...
Folder 'GCA_028738775.1_PDT001632556.1' already exists. Skipping...
Folder 'GCA_028738835.1_PDT001632553.1' already exists. Skipping...
Folder 'GCA_028738855.1_PDT001632552.1' already exists. Skipping...
Folder 'GCA_028738895.1_PDT001632550.1' already exists. Skipping...
Folder 'GCA_028739015.1_PDT001632542.1' already exists. Skipping...
Folder 'GCA_028739035.1_PDT001632544.1' already exists. Skipping...
Folder 'GCA_028739055.1_PDT001632543.1' already exists. Skipping...
Folder 'GCA_028739075.1_PDT001632541.1' already exists. Skipping...
Folder 'GCA_028739135.1_PDT001632535.1' already exists. Skipping...
Folder 'GCA_028739155.1_PDT001632538.1' already exists. Skipping...
Folder 'GCA_028739215.1_PDT001632534.1' already exists. Skipping...
Folder 'GCA_028739235.1_PDT001632531.1' already exists. Skipping...
Folder 'GCA_028739255.1_PDT001632533.1' already exists. Skipping...
Folder 'GCA_028739285.1_PDT001632532.1' already exists. Skipping...
Folder 'GCA_028739635.1_PDT001627010.1' already exists. Skipping...
Folder 'GCA_028739695.1_PDT001627007.1' already exists. Skipping...
Folder 'GCA_028739735.1_PDT001627004.1' already exists. Skipping...
Folder 'GCA_028739755.1_PDT001627003.1' already exists. Skipping...
Folder 'GCA_028739775.1_PDT001627005.1' already exists. Skipping...
Folder 'GCA_028739855.1_PDT001626998.1' already exists. Skipping...
Folder 'GCA_028739875.1_PDT001626999.1' already exists. Skipping...
Folder 'GCA_028739895.1_PDT001626997.1' already exists. Skipping...
Folder 'GCA_028739915.1_PDT001626996.1' already exists. Skipping...
Folder 'GCA_028739955.1_PDT001626994.1' already exists. Skipping...
Folder 'GCA_028739995.1_PDT001626991.1' already exists. Skipping...
Folder 'GCA_028740015.1_PDT001626993.1' already exists. Skipping...
Folder 'GCA_028740035.1_PDT001626992.1' already exists. Skipping...
Folder 'GCA_028740055.1_PDT001626989.1' already exists. Skipping...
Folder 'GCA_028740075.1_PDT001626988.1' already exists. Skipping...
Folder 'GCA_028740175.1_PDT001626983.1' already exists. Skipping...
Folder 'GCA_028740215.1_PDT001626980.1' already exists. Skipping...
Folder 'GCA_028740255.1_PDT001626981.1' already exists. Skipping...
Folder 'GCA_028740675.1_PDT001618878.1' already exists. Skipping...
Folder 'GCA_028740695.1_PDT001618879.1' already exists. Skipping...
Folder 'GCA_028740715.1_PDT001618876.1' already exists. Skipping...
Folder 'GCA_028740725.1_PDT001618875.1' already exists. Skipping...
Folder 'GCA_028740795.1_PDT001618873.1' already exists. Skipping...
Folder 'GCA_028740815.1_PDT001618872.1' already exists. Skipping...
Folder 'GCA_028740835.1_PDT001618869.1' already exists. Skipping...
Folder 'GCA_028740975.1_PDT001618863.1' already exists. Skipping...
Folder 'GCA_028740995.1_PDT001618862.1' already exists. Skipping...
Folder 'GCA_028741015.1_PDT001618861.1' already exists. Skipping...
Folder 'GCA_028741055.1_PDT001618859.1' already exists. Skipping...
Folder 'GCA_028741075.1_PDT001618858.1' already exists. Skipping...
Folder 'GCA_028741095.1_PDT001618856.1' already exists. Skipping...
Folder 'GCA_028741135.1_PDT001618854.1' already exists. Skipping...
Folder 'GCA_028741155.1_PDT001618855.1' already exists. Skipping...
Folder 'GCA_028741175.1_PDT001618853.1' already exists. Skipping...
Folder 'GCA_028741595.1_PDT001618827.1' already exists. Skipping...
Folder 'GCA_028741695.1_PDT001618824.1' already exists. Skipping...
Folder 'GCA_028741755.1_PDT001618823.1' already exists. Skipping...
Folder 'GCA_028741795.1_PDT001618820.1' already exists. Skipping...
Folder 'GCA_028741815.1_PDT001618819.1' already exists. Skipping...
Folder 'GCA_028741835.1_PDT001618817.1' already exists. Skipping...
Folder 'GCA_028741855.1_PDT001618818.1' already exists. Skipping...
Folder 'GCA_028741935.1_PDT001618812.1' already exists. Skipping...
Folder 'GCA_028741955.1_PDT001618806.1' already exists. Skipping...
Folder 'GCA_028741975.1_PDT001618805.1' already exists. Skipping...
Folder 'GCA_028742015.1_PDT001618811.1' already exists. Skipping...
Folder 'GCA_028742035.1_PDT001618809.1' already exists. Skipping...
Folder 'GCA_028742055.1_PDT001618804.1' already exists. Skipping...
Folder 'GCA_028742075.1_PDT001618808.1' already exists. Skipping...
Folder 'GCA_028742095.1_PDT001618807.1' already exists. Skipping...
Folder 'GCA_028742115.1_PDT001618803.1' already exists. Skipping...
Folder 'GCA_028742595.1_PDT001618762.1' already exists. Skipping...
Folder 'GCA_028742715.1_PDT001618761.1' already exists. Skipping...
Folder 'GCA_028760765.1_PDT001637004.1' already exists. Skipping...
Folder 'GCA_028793765.2_PDT001639028.2' already exists. Skipping...
Folder 'GCA_028793785.2_PDT001639029.2' already exists. Skipping...
Folder 'GCA_028793815.2_PDT001639018.2' already exists. Skipping...
Folder 'GCA_028793845.2_PDT001639023.2' already exists. Skipping...
Folder 'GCA_028793865.2_PDT001639020.2' already exists. Skipping...
Folder 'GCA_028793885.2_PDT001639017.2' already exists. Skipping...
Folder 'GCA_028793925.2_PDT001639016.2' already exists. Skipping...
Folder 'GCA_028794765.2_PDT001639021.2' already exists. Skipping...
Folder 'GCA_028794785.2_PDT001639033.2' already exists. Skipping...
Folder 'GCA_028794805.2_PDT001639022.2' already exists. Skipping...
Folder 'GCA_028794825.2_PDT001639026.2' already exists. Skipping...
Folder 'GCA_028794845.2_PDT001639019.2' already exists. Skipping...
Folder 'GCA_028796745.2_PDT001639031.2' already exists. Skipping...
Folder 'GCA_028796785.2_PDT001639032.2' already exists. Skipping...
Folder 'GCA_028796805.2_PDT001639027.2' already exists. Skipping...
Folder 'GCA_028796825.2_PDT001639030.2' already exists. Skipping...
Folder 'GCA_028796845.2_PDT001639024.2' already exists. Skipping...
Folder 'GCA_028800265.1_PDT001639015.1' already exists. Skipping...
Folder 'GCA_028812935.1_PDT001639811.1' already exists. Skipping...
Folder 'GCA_028812975.1_PDT001639810.1' already exists. Skipping...
Folder 'GCA_028813055.1_PDT001639806.1' already exists. Skipping...
Folder 'GCA_028813075.1_PDT001639807.1' already exists. Skipping...
Folder 'GCA_028813095.1_PDT001639808.1' already exists. Skipping...
Folder 'GCA_028813115.1_PDT001639802.1' already exists. Skipping...
Folder 'GCA_028813155.1_PDT001639803.1' already exists. Skipping...
Folder 'GCA_028841265.1_PDT001640742.1' already exists. Skipping...
Folder 'GCA_028856585.1_PDT001618843.1' already exists. Skipping...
Folder 'GCA_028861955.1_PDT001642447.1' already exists. Skipping...
Folder 'GCA_028878615.1_PDT001646900.1' already exists. Skipping...
Folder 'GCA_028878635.1_PDT001646904.1' already exists. Skipping...

Retreiveing data: 26906it [00:05, 6700.43it/s]

Folder 'GCA_031402555.1_PDT001794692.1' already exists. Skipping...
Folder 'GCA_031402575.1_PDT001794693.1' already exists. Skipping...
Folder 'GCA_031402675.1_PDT001794691.1' already exists. Skipping...
Folder 'GCA_031402705.1_PDT001794690.1' already exists. Skipping...
Folder 'GCA_031402755.1_PDT001794697.1' already exists. Skipping...
Folder 'GCA_031402795.1_PDT001794698.1' already exists. Skipping...
Folder 'GCA_031402895.1_PDT001794685.1' already exists. Skipping...
Folder 'GCA_031402915.1_PDT001794686.1' already exists. Skipping...
Folder 'GCA_031403335.1_PDT001794675.1' already exists. Skipping...
Folder 'GCA_031403575.1_PDT001794668.1' already exists. Skipping...
Folder 'GCA_031404995.1_PDT001794664.1' already exists. Skipping...
Folder 'GCA_031405415.1_PDT001794650.1' already exists. Skipping...
Folder 'GCA_031406695.1_PDT001794638.1' already exists. Skipping...
Folder 'GCA_031406745.1_PDT001794649.1' already exists. Skipping...
Folder 'GCA_031407535.1_PDT001794614.1' already exists. Skipping...
Folder 'GCA_031407555.1_PDT001794613.1' already exists. Skipping...
Folder 'GCA_031407685.1_PDT001794609.1' already exists. Skipping...
Folder 'GCA_031408495.1_PDT001794608.1' already exists. Skipping...
Folder 'GCA_031408655.1_PDT001794602.1' already exists. Skipping...
Folder 'GCA_031408675.1_PDT001794600.1' already exists. Skipping...
Folder 'GCA_031409075.1_PDT001794569.1' already exists. Skipping...
Folder 'GCA_031409095.1_PDT001794571.1' already exists. Skipping...
Folder 'GCA_031409135.1_PDT001794563.1' already exists. Skipping...
Folder 'GCA_031409155.1_PDT001794561.1' already exists. Skipping...
Folder 'GCA_031409175.1_PDT001794562.1' already exists. Skipping...
Folder 'GCA_031409195.1_PDT001794557.1' already exists. Skipping...
Folder 'GCA_031409215.1_PDT001794553.1' already exists. Skipping...
Folder 'GCA_031434105.1_PDT001882496.1' already exists. Skipping...
Folder 'GCA_031434125.1_PDT001882495.1' already exists. Skipping...
Folder 'GCA_031434385.1_PDT001882482.1' already exists. Skipping...
Folder 'GCA_031434425.1_PDT001882481.1' already exists. Skipping...
Folder 'GCA_031434445.1_PDT001882480.1' already exists. Skipping...
Folder 'GCA_031434565.1_PDT001882472.1' already exists. Skipping...
Folder 'GCA_031434575.1_PDT001882473.1' already exists. Skipping...
Folder 'GCA_031434625.1_PDT001882469.1' already exists. Skipping...
Folder 'GCA_031434645.1_PDT001882470.1' already exists. Skipping...
Folder 'GCA_031437945.1_PDT001882261.1' already exists. Skipping...
Folder 'GCA_031438485.1_PDT001794550.1' already exists. Skipping...
Folder 'GCA_031438525.1_PDT001794547.1' already exists. Skipping...
Folder 'GCA_031438585.1_PDT001794543.1' already exists. Skipping...
Folder 'GCA_031438595.1_PDT001794544.1' already exists. Skipping...
Folder 'GCA_031438645.1_PDT001794541.1' already exists. Skipping...
Folder 'GCA_031438685.1_PDT001794540.1' already exists. Skipping...
Folder 'GCA_031438705.1_PDT001794539.1' already exists. Skipping...
Folder 'GCA_031438765.1_PDT001794536.1' already exists. Skipping...
Folder 'GCA_031438805.1_PDT001794534.1' already exists. Skipping...
Folder 'GCA_031438885.1_PDT001794531.1' already exists. Skipping...
Folder 'GCA_031438965.1_PDT001794528.1' already exists. Skipping...
Folder 'GCA_031442805.1_PDT001794288.1' already exists. Skipping...
Folder 'GCA_031443545.1_PDT001794078.1' already exists. Skipping...
Folder 'GCA_031443565.1_PDT001794077.1' already exists. Skipping...
Folder 'GCA_031443605.1_PDT001794076.1' already exists. Skipping...
Folder 'GCA_031443645.1_PDT001794074.1' already exists. Skipping...
Folder 'GCA_031443665.1_PDT001794073.1' already exists. Skipping...
Folder 'GCA_031443845.1_PDT001794065.1' already exists. Skipping...
Folder 'GCA_031444065.1_PDT001794053.1' already exists. Skipping...
Folder 'GCA_031444085.1_PDT001794052.1' already exists. Skipping...
Folder 'GCA_031444125.1_PDT001794050.1' already exists. Skipping...
Folder 'GCA_031444185.1_PDT001794048.1' already exists. Skipping...
Folder 'GCA_031444205.1_PDT001794044.1' already exists. Skipping...
Folder 'GCA_031444265.1_PDT001794042.1' already exists. Skipping...
Folder 'GCA_031444365.1_PDT001794036.1' already exists. Skipping...
Folder 'GCA_031444405.1_PDT001794034.1' already exists. Skipping...
Folder 'GCA_031445125.1_PDT001793996.1' already exists. Skipping...
Folder 'GCA_031445345.1_PDT001793967.1' already exists. Skipping...
Folder 'GCA_031445365.1_PDT001793959.1' already exists. Skipping...
Folder 'GCA_031445405.1_PDT001793973.1' already exists. Skipping...
Folder 'GCA_031445515.1_PDT001793969.1' already exists. Skipping...
Folder 'GCA_031445545.1_PDT001793968.1' already exists. Skipping...
Folder 'GCA_031445565.1_PDT001793960.1' already exists. Skipping...
Folder 'GCA_031445865.1_PDT001793938.1' already exists. Skipping...
Folder 'GCA_031445885.1_PDT001793937.1' already exists. Skipping...
Folder 'GCA_031446005.1_PDT001793932.1' already exists. Skipping...
Folder 'GCA_031446025.1_PDT001793931.1' already exists. Skipping...
Folder 'GCA_031446045.1_PDT001793928.1' already exists. Skipping...
Folder 'GCA_031446305.1_PDT001793915.1' already exists. Skipping...
Folder 'GCA_031446325.1_PDT001793914.1' already exists. Skipping...
Folder 'GCA_031446365.1_PDT001793913.1' already exists. Skipping...
Folder 'GCA_031446405.1_PDT001793911.1' already exists. Skipping...
Folder 'GCA_031449665.1_PDT001793664.1' already exists. Skipping...
Folder 'GCA_031450275.1_PDT001793622.1' already exists. Skipping...
Folder 'GCA_031450315.1_PDT001793621.1' already exists. Skipping...
Folder 'GCA_031450375.1_PDT001793618.1' already exists. Skipping...
Folder 'GCA_031450535.1_PDT001793608.1' already exists. Skipping...
Folder 'GCA_031450615.1_PDT001793601.1' already exists. Skipping...
Folder 'GCA_031450695.1_PDT001793598.1' already exists. Skipping...
Folder 'GCA_031450755.1_PDT001793590.1' already exists. Skipping...
Folder 'GCA_031451055.1_PDT001793584.1' already exists. Skipping...
Folder 'GCA_031451085.1_PDT001793581.1' already exists. Skipping...
Folder 'GCA_031451355.1_PDT001793566.1' already exists. Skipping...
Folder 'GCA_031451395.1_PDT001793561.1' already exists. Skipping...
Folder 'GCA_031468735.1_PDT001883696.1' already exists. Skipping...
Folder 'GCA_031473695.1_PDT001709453.1' already exists. Skipping...
Folder 'GCA_031473735.1_PDT001709450.1' already exists. Skipping...
Folder 'GCA_031473755.1_PDT001709449.1' already exists. Skipping...
Folder 'GCA_031474015.1_PDT001709397.1' already exists. Skipping...
Folder 'GCA_031474035.1_PDT001709398.1' already exists. Skipping...
Folder 'GCA_031474055.1_PDT001709379.1' already exists. Skipping...
Folder 'GCA_031474115.1_PDT001709378.1' already exists. Skipping...
Folder 'GCA_031474135.1_PDT001709377.1' already exists. Skipping...
Folder 'GCA_031474195.1_PDT001709376.1' already exists. Skipping...
Folder 'GCA_031474215.1_PDT001709373.1' already exists. Skipping...
Folder 'GCA_031474235.1_PDT001709372.1' already exists. Skipping...
Folder 'GCA_031474255.1_PDT001709371.1' already exists. Skipping...
Folder 'GCA_031474265.1_PDT001709370.1' already exists. Skipping...
Folder 'GCA_031474335.1_PDT001709366.1' already exists. Skipping...
Folder 'GCA_031474855.1_PDT001709328.1' already exists. Skipping...
Folder 'GCA_031474875.1_PDT001709326.1' already exists. Skipping...
Folder 'GCA_031475035.1_PDT001709315.1' already exists. Skipping...
Folder 'GCA_031475055.1_PDT001709314.1' already exists. Skipping...
Folder 'GCA_031475075.1_PDT001709313.1' already exists. Skipping...
Folder 'GCA_031475115.1_PDT001709311.1' already exists. Skipping...
Folder 'GCA_031475195.1_PDT001709307.1' already exists. Skipping...
Folder 'GCA_031475255.1_PDT001709303.1' already exists. Skipping...
Folder 'GCA_031475275.1_PDT001709304.1' already exists. Skipping...
Folder 'GCA_031475315.1_PDT001709302.1' already exists. Skipping...
Folder 'GCA_031475375.1_PDT001709299.1' already exists. Skipping...
Folder 'GCA_031475415.1_PDT001709296.1' already exists. Skipping...
Folder 'GCA_031475535.1_PDT001709290.1' already exists. Skipping...
Folder 'GCA_031475575.1_PDT001709288.1' already exists. Skipping...
Folder 'GCA_031475795.1_PDT001709267.1' already exists. Skipping...
Folder 'GCA_031476095.1_PDT001709275.1' already exists. Skipping...
Folder 'GCA_031479015.1_PDT001767676.1' already exists. Skipping...
Folder 'GCA_031479055.1_PDT001767675.1' already exists. Skipping...
Folder 'GCA_031482355.1_PDT001767335.1' already exists. Skipping...
Folder 'GCA_031483355.1_PDT001767105.1' already exists. Skipping...
Folder 'GCA_031484535.1_PDT001767021.1' already exists. Skipping...
Folder 'GCA_031484595.1_PDT001767020.1' already exists. Skipping...
Folder 'GCA_031484655.1_PDT001767016.1' already exists. Skipping...
Folder 'GCA_031484675.1_PDT001767017.1' already exists. Skipping...
Folder 'GCA_031484775.1_PDT001767011.1' already exists. Skipping...
Folder 'GCA_031484835.1_PDT001767009.1' already exists. Skipping...
Folder 'GCA_031484915.1_PDT001767005.1' already exists. Skipping...
Folder 'GCA_031484935.1_PDT001767003.1' already exists. Skipping...
Folder 'GCA_031484955.1_PDT001767002.1' already exists. Skipping...
Folder 'GCA_031484975.1_PDT001767001.1' already exists. Skipping...
Folder 'GCA_031485075.1_PDT001766997.1' already exists. Skipping...
Folder 'GCA_031486115.1_PDT001766945.1' already exists. Skipping...
Folder 'GCA_031488755.1_PDT001766792.1' already exists. Skipping...
Folder 'GCA_031495245.1_PDT001709258.1' already exists. Skipping...
Folder 'GCA_031495285.1_PDT001709256.1' already exists. Skipping...
Folder 'GCA_031495305.1_PDT001709255.1' already exists. Skipping...
Folder 'GCA_031495325.1_PDT001709253.1' already exists. Skipping...
Folder 'GCA_031495345.1_PDT001709254.1' already exists. Skipping...
Folder 'GCA_031495365.1_PDT001709251.1' already exists. Skipping...
Folder 'GCA_031495425.1_PDT001709247.1' already exists. Skipping...
Folder 'GCA_031495465.1_PDT001709250.1' already exists. Skipping...
Folder 'GCA_031495505.1_PDT001709244.1' already exists. Skipping...
Folder 'GCA_031495565.1_PDT001709239.1' already exists. Skipping...
Folder 'GCA_031495585.1_PDT001709240.1' already exists. Skipping...
Folder 'GCA_031495605.1_PDT001709238.1' already exists. Skipping...
Folder 'GCA_031495625.1_PDT001709236.1' already exists. Skipping...
Folder 'GCA_031495665.1_PDT001709234.1' already exists. Skipping...
Folder 'GCA_031495685.1_PDT001709231.1' already exists. Skipping...
Folder 'GCA_031495885.1_PDT001709243.1' already exists. Skipping...
Folder 'GCA_031501765.1_PDT001708689.1' already exists. Skipping...
Folder 'GCA_031501965.1_PDT001708682.1' already exists. Skipping...
Folder 'GCA_031502025.1_PDT001708686.1' already exists. Skipping...
Folder 'GCA_031529365.1_PDT001862665.1' already exists. Skipping...
Folder 'GCA_031529385.1_PDT001862663.1' already exists. Skipping...
Folder 'GCA_031530465.1_PDT001862598.1' already exists. Skipping...
Folder 'GCA_031530725.1_PDT001862585.1' already exists. Skipping...
Folder 'GCA_031531345.1_PDT001862548.1' already exists. Skipping...
Folder 'GCA_031531385.1_PDT001862546.1' already exists. Skipping...
Folder 'GCA_031531465.1_PDT001862542.1' already exists. Skipping...
Folder 'GCA_031531565.1_PDT001862539.1' already exists. Skipping...
Folder 'GCA_031532045.1_PDT001862506.1' already exists. Skipping...
Folder 'GCA_031532085.1_PDT001862505.1' already exists. Skipping...
Folder 'GCA_031532145.1_PDT001862500.1' already exists. Skipping...
Folder 'GCA_031532245.1_PDT001862497.1' already exists. Skipping...
Folder 'GCA_031532305.1_PDT001862493.1' already exists. Skipping...
Folder 'GCA_031532365.1_PDT001862490.1' already exists. Skipping...
Folder 'GCA_031532385.1_PDT001862488.1' already exists. Skipping...
Folder 'GCA_031532665.1_PDT001862468.1' already exists. Skipping...
Folder 'GCA_031532885.1_PDT001862457.1' already exists. Skipping...
Folder 'GCA_031536765.1_PDT001860430.1' already exists. Skipping...
Folder 'GCA_031536785.1_PDT001860432.1' already exists. Skipping...
Folder 'GCA_031544365.1_PDT001859775.1' already exists. Skipping...
Folder 'GCA_031544425.1_PDT001859772.1' already exists. Skipping...
Folder 'GCA_031545075.1_PDT001859762.1' already exists. Skipping...
Folder 'GCA_031553325.1_PDT001887788.1' already exists. Skipping...
Folder 'GCA_031553355.1_PDT001887787.1' already exists. Skipping...
Folder 'GCA_031554395.1_PDT001887779.1' already exists. Skipping...
Folder 'GCA_031554575.1_PDT001887778.1' already exists. Skipping...
Folder 'GCA_031554595.1_PDT001887777.1' already exists. Skipping...
Folder 'GCA_031554705.1_PDT001887774.1' already exists. Skipping...
Folder 'GCA_031554815.1_PDT001887772.1' already exists. Skipping...
Folder 'GCA_031554835.1_PDT001887771.1' already exists. Skipping...
Folder 'GCA_031554885.1_PDT001887766.1' already exists. Skipping...
Folder 'GCA_031554925.1_PDT001887765.1' already exists. Skipping...
Folder 'GCA_031554985.1_PDT001887764.1' already exists. Skipping...
Folder 'GCA_031555015.1_PDT001887763.1' already exists. Skipping...
Folder 'GCA_031555085.1_PDT001887758.1' already exists. Skipping...
Folder 'GCA_031555095.1_PDT001887762.1' already exists. Skipping...
Folder 'GCA_031555355.1_PDT001887708.1' already exists. Skipping...
Folder 'GCA_031555595.1_PDT001887707.1' already exists. Skipping...
Folder 'GCA_031555635.1_PDT001887693.1' already exists. Skipping...
Folder 'GCA_031555805.1_PDT001887687.1' already exists. Skipping...
Folder 'GCA_031555855.1_PDT001887688.1' already exists. Skipping...
Folder 'GCA_031556595.1_PDT001887681.1' already exists. Skipping...
Folder 'GCA_031556615.1_PDT001887682.1' already exists. Skipping...
Folder 'GCA_031556635.1_PDT001887684.1' already exists. Skipping...
Folder 'GCA_031556655.1_PDT001887680.1' already exists. Skipping...
Folder 'GCA_031556795.1_PDT001887781.1' already exists. Skipping...
Folder 'GCA_031557215.1_PDT001887675.1' already exists. Skipping...
Folder 'GCA_031557295.1_PDT001887671.1' already exists. Skipping...
Folder 'GCA_031557315.1_PDT001887669.1' already exists. Skipping...
Folder 'GCA_031557395.1_PDT001887670.1' already exists. Skipping...
Folder 'GCA_031557435.1_PDT001887664.1' already exists. Skipping...
Folder 'GCA_031557775.1_PDT001887645.1' already exists. Skipping...
Folder 'GCA_031557795.1_PDT001887643.1' already exists. Skipping...
Folder 'GCA_031557835.1_PDT001887642.1' already exists. Skipping...
Folder 'GCA_031557855.1_PDT001887641.1' already exists. Skipping...
Folder 'GCA_031557935.1_PDT001887640.1' already exists. Skipping...
Folder 'GCA_031557975.1_PDT001887638.1' already exists. Skipping...
Folder 'GCA_031557995.1_PDT001887637.1' already exists. Skipping...
Folder 'GCA_031558055.1_PDT001887632.1' already exists. Skipping...
Folder 'GCA_031558095.1_PDT001887631.1' already exists. Skipping...
Folder 'GCA_031558115.1_PDT001887630.1' already exists. Skipping...
Folder 'GCA_031558135.1_PDT001887628.1' already exists. Skipping...
Folder 'GCA_031558205.1_PDT001887626.1' already exists. Skipping...
Folder 'GCA_031558315.1_PDT001887621.1' already exists. Skipping...
Folder 'GCA_031558335.1_PDT001887620.1' already exists. Skipping...
Folder 'GCA_031558375.1_PDT001887617.1' already exists. Skipping...
Folder 'GCA_031558415.1_PDT001887615.1' already exists. Skipping...
Folder 'GCA_031558435.1_PDT001887616.1' already exists. Skipping...
Folder 'GCA_031558515.1_PDT001887611.1' already exists. Skipping...
Folder 'GCA_031558535.1_PDT001887610.1' already exists. Skipping...
Folder 'GCA_031558595.1_PDT001887608.1' already exists. Skipping...
Folder 'GCA_031559475.1_PDT001859223.1' already exists. Skipping...
Folder 'GCA_031559515.1_PDT001859222.1' already exists. Skipping...
Folder 'GCA_031559535.1_PDT001859221.1' already exists. Skipping...
Folder 'GCA_031559655.1_PDT001859213.1' already exists. Skipping...
Folder 'GCA_031559675.1_PDT001859212.1' already exists. Skipping...
Folder 'GCA_031559795.1_PDT001859206.1' already exists. Skipping...
Folder 'GCA_031559955.1_PDT001859203.1' already exists. Skipping...
Folder 'GCA_031559975.1_PDT001859202.1' already exists. Skipping...
Folder 'GCA_031559995.1_PDT001859200.1' already exists. Skipping...
Folder 'GCA_031560155.1_PDT001859193.1' already exists. Skipping...
Folder 'GCA_031560275.1_PDT001859189.1' already exists. Skipping...
Folder 'GCA_031560335.1_PDT001859184.1' already exists. Skipping...
Folder 'GCA_031560415.1_PDT001859179.1' already exists. Skipping...
Folder 'GCA_031560455.1_PDT001859178.1' already exists. Skipping...
Folder 'GCA_031560595.1_PDT001859171.1' already exists. Skipping...
Folder 'GCA_031565875.1_PDT001887971.1' already exists. Skipping...
Folder 'GCA_031566755.1_PDT001858668.1' already exists. Skipping...
Folder 'GCA_031567095.1_PDT001858655.1' already exists. Skipping...
Folder 'GCA_031567115.1_PDT001858654.1' already exists. Skipping...
Folder 'GCA_031567175.1_PDT001858652.1' already exists. Skipping...
Folder 'GCA_031567195.1_PDT001858650.1' already exists. Skipping...
Folder 'GCA_031567275.1_PDT001858647.1' already exists. Skipping...
Folder 'GCA_031567315.1_PDT001858644.1' already exists. Skipping...
Folder 'GCA_031567335.1_PDT001858643.1' already exists. Skipping...
Folder 'GCA_031567355.1_PDT001858645.1' already exists. Skipping...
Folder 'GCA_031567365.1_PDT001858642.1' already exists. Skipping...
Folder 'GCA_031567395.1_PDT001858641.1' already exists. Skipping...
Folder 'GCA_031567415.1_PDT001858640.1' already exists. Skipping...
Folder 'GCA_031567455.1_PDT001858638.1' already exists. Skipping...
Folder 'GCA_031567475.1_PDT001858637.1' already exists. Skipping...
Folder 'GCA_031567575.1_PDT001858631.1' already exists. Skipping...
Folder 'GCA_031567595.1_PDT001858621.1' already exists. Skipping...
Folder 'GCA_031567615.1_PDT001858620.1' already exists. Skipping...
Folder 'GCA_031567635.1_PDT001858622.1' already exists. Skipping...
Folder 'GCA_031567695.1_PDT001858616.1' already exists. Skipping...
Folder 'GCA_031567775.1_PDT001858613.1' already exists. Skipping...
Folder 'GCA_031567795.1_PDT001858611.1' already exists. Skipping...
Folder 'GCA_031567815.1_PDT001858612.1' already exists. Skipping...
Folder 'GCA_031567835.1_PDT001858610.1' already exists. Skipping...
Folder 'GCA_031567955.1_PDT001858608.1' already exists. Skipping...
Folder 'GCA_031567995.1_PDT001858607.1' already exists. Skipping...
Folder 'GCA_031568035.1_PDT001858605.1' already exists. Skipping...
Folder 'GCA_031568115.1_PDT001858601.1' already exists. Skipping...
Folder 'GCA_031568155.1_PDT001858599.1' already exists. Skipping...
Folder 'GCA_031568185.1_PDT001858594.1' already exists. Skipping...
Folder 'GCA_031576535.1_PDT001857941.1' already exists. Skipping...
Folder 'GCA_031576615.1_PDT001857916.1' already exists. Skipping...
Folder 'GCA_031585315.1_PDT001888410.1' already exists. Skipping...
Folder 'GCA_031585385.1_PDT001888407.1' already exists. Skipping...
Folder 'GCA_031585415.1_PDT001888405.1' already exists. Skipping...
Folder 'GCA_031585455.1_PDT001888403.1' already exists. Skipping...
Folder 'GCA_031585475.1_PDT001888404.1' already exists. Skipping...
Folder 'GCA_031585495.1_PDT001888401.1' already exists. Skipping...
Folder 'GCA_031585515.1_PDT001888400.1' already exists. Skipping...
Folder 'GCA_031585555.1_PDT001888398.1' already exists. Skipping...
Folder 'GCA_031585575.1_PDT001888396.1' already exists. Skipping...
Folder 'GCA_031585595.1_PDT001888395.1' already exists. Skipping...
Folder 'GCA_031585615.1_PDT001888394.1' already exists. Skipping...
Folder 'GCA_031585695.1_PDT001888392.1' already exists. Skipping...
Folder 'GCA_031585715.1_PDT001888389.1' already exists. Skipping...
Folder 'GCA_031585755.1_PDT001888388.1' already exists. Skipping...
Folder 'GCA_031585775.1_PDT001888386.1' already exists. Skipping...
Folder 'GCA_031585785.1_PDT001888387.1' already exists. Skipping...
Folder 'GCA_031585835.1_PDT001888385.1' already exists. Skipping...
Folder 'GCA_031585855.1_PDT001888382.1' already exists. Skipping...

Retreiveing data: 28254it [00:05, 6691.97it/s]

Folder 'GCA_032708005.1_PDT001790536.1' already exists. Skipping...
Folder 'GCA_032708025.1_PDT001790533.1' already exists. Skipping...
Folder 'GCA_032708045.1_PDT001790531.1' already exists. Skipping...
Folder 'GCA_032708065.1_PDT001790532.1' already exists. Skipping...
Folder 'GCA_032708085.1_PDT001790530.1' already exists. Skipping...
Folder 'GCA_032708105.1_PDT001790529.1' already exists. Skipping...
Folder 'GCA_032708125.1_PDT001790528.1' already exists. Skipping...
Folder 'GCA_032708145.1_PDT001790526.1' already exists. Skipping...
Folder 'GCA_032708165.1_PDT001790525.1' already exists. Skipping...
Folder 'GCA_032708185.1_PDT001790527.1' already exists. Skipping...
Folder 'GCA_032708205.1_PDT001790524.1' already exists. Skipping...
Folder 'GCA_032708225.1_PDT001790523.1' already exists. Skipping...
Folder 'GCA_032708245.1_PDT001790522.1' already exists. Skipping...
Folder 'GCA_032708265.1_PDT001790521.1' already exists. Skipping...
Folder 'GCA_032708285.1_PDT001790520.1' already exists. Skipping...
Folder 'GCA_032708305.1_PDT001790518.1' already exists. Skipping...
Folder 'GCA_032708325.1_PDT001790519.1' already exists. Skipping...
Folder 'GCA_032708345.1_PDT001790517.1' already exists. Skipping...
Folder 'GCA_032708365.1_PDT001790515.1' already exists. Skipping...
Folder 'GCA_032708385.1_PDT001790516.1' already exists. Skipping...
Folder 'GCA_032708405.1_PDT001790514.1' already exists. Skipping...
Folder 'GCA_032708425.1_PDT001790513.1' already exists. Skipping...
Folder 'GCA_032708505.1_PDT001790498.1' already exists. Skipping...
Folder 'GCA_032708525.1_PDT001790497.1' already exists. Skipping...
Folder 'GCA_032708545.1_PDT001790496.1' already exists. Skipping...
Folder 'GCA_032708565.1_PDT001790495.1' already exists. Skipping...
Folder 'GCA_032708585.1_PDT001790493.1' already exists. Skipping...
Folder 'GCA_032708595.1_PDT001790494.1' already exists. Skipping...
Folder 'GCA_032708625.1_PDT001790490.1' already exists. Skipping...
Folder 'GCA_032708645.1_PDT001790492.1' already exists. Skipping...
Folder 'GCA_032708665.1_PDT001790491.1' already exists. Skipping...
Folder 'GCA_032708685.1_PDT001790489.1' already exists. Skipping...
Folder 'GCA_032708705.1_PDT001790488.1' already exists. Skipping...
Folder 'GCA_032708725.1_PDT001790487.1' already exists. Skipping...
Folder 'GCA_032708745.1_PDT001790486.1' already exists. Skipping...
Folder 'GCA_032708765.1_PDT001790485.1' already exists. Skipping...
Folder 'GCA_032708785.1_PDT001790484.1' already exists. Skipping...
Folder 'GCA_032708805.1_PDT001790483.1' already exists. Skipping...
Folder 'GCA_032708825.1_PDT001790482.1' already exists. Skipping...
Folder 'GCA_032708845.1_PDT001790481.1' already exists. Skipping...
Folder 'GCA_032708885.1_PDT001790479.1' already exists. Skipping...
Folder 'GCA_032708925.1_PDT001790480.1' already exists. Skipping...
Folder 'GCA_032709765.1_PDT001790396.1' already exists. Skipping...
Folder 'GCA_032709845.1_PDT001790393.1' already exists. Skipping...
Folder 'GCA_032709855.1_PDT001790394.1' already exists. Skipping...
Folder 'GCA_032710025.1_PDT001790379.1' already exists. Skipping...
Folder 'GCA_032710065.1_PDT001790378.1' already exists. Skipping...
Folder 'GCA_032710125.1_PDT001790374.1' already exists. Skipping...
Folder 'GCA_032710145.1_PDT001790375.1' already exists. Skipping...
Folder 'GCA_032710225.1_PDT001790369.1' already exists. Skipping...
Folder 'GCA_032710245.1_PDT001790368.1' already exists. Skipping...
Folder 'GCA_032712775.1_PDT001790365.1' already exists. Skipping...
Folder 'GCA_032712815.1_PDT001790364.1' already exists. Skipping...
Folder 'GCA_032712835.1_PDT001790363.1' already exists. Skipping...
Folder 'GCA_032712855.1_PDT001790362.1' already exists. Skipping...
Folder 'GCA_032712995.1_PDT001790355.1' already exists. Skipping...
Folder 'GCA_032713035.1_PDT001790350.1' already exists. Skipping...
Folder 'GCA_032713085.1_PDT001790348.1' already exists. Skipping...
Folder 'GCA_032713105.1_PDT001790347.1' already exists. Skipping...
Folder 'GCA_032713145.1_PDT001790346.1' already exists. Skipping...
Folder 'GCA_032716545.1_PDT001927267.1' already exists. Skipping...
Folder 'GCA_032716565.1_PDT001927269.1' already exists. Skipping...
Folder 'GCA_032716715.1_PDT001927260.1' already exists. Skipping...
Folder 'GCA_032717085.1_PDT001927241.1' already exists. Skipping...
Folder 'GCA_032717145.1_PDT001927240.1' already exists. Skipping...
Folder 'GCA_032717205.1_PDT001927232.1' already exists. Skipping...
Folder 'GCA_032717225.1_PDT001927231.1' already exists. Skipping...
Folder 'GCA_032717305.1_PDT001927225.1' already exists. Skipping...
Folder 'GCA_032717365.1_PDT001927224.1' already exists. Skipping...
Folder 'GCA_032717425.1_PDT001927219.1' already exists. Skipping...
Folder 'GCA_032717445.1_PDT001927218.1' already exists. Skipping...
Folder 'GCA_032717495.1_PDT001927216.1' already exists. Skipping...
Folder 'GCA_032717535.1_PDT001927215.1' already exists. Skipping...
Folder 'GCA_032717985.1_PDT001927195.1' already exists. Skipping...
Folder 'GCA_032718065.1_PDT001927187.1' already exists. Skipping...
Folder 'GCA_032718085.1_PDT001927186.1' already exists. Skipping...
Folder 'GCA_032718795.1_PDT001927150.1' already exists. Skipping...
Folder 'GCA_032718845.1_PDT001927149.1' already exists. Skipping...
Folder 'GCA_032719325.1_PDT001927128.1' already exists. Skipping...
Folder 'GCA_032719545.1_PDT001927117.1' already exists. Skipping...
Folder 'GCA_032724335.1_PDT001790280.1' already exists. Skipping...
Folder 'GCA_032724355.1_PDT001790278.1' already exists. Skipping...
Folder 'GCA_032724375.1_PDT001790279.1' already exists. Skipping...
Folder 'GCA_032724395.1_PDT001790277.1' already exists. Skipping...
Folder 'GCA_032724415.1_PDT001790276.1' already exists. Skipping...
Folder 'GCA_032724435.1_PDT001790275.1' already exists. Skipping...
Folder 'GCA_032724455.1_PDT001790274.1' already exists. Skipping...
Folder 'GCA_032724475.1_PDT001790273.1' already exists. Skipping...
Folder 'GCA_032724515.1_PDT001790271.1' already exists. Skipping...
Folder 'GCA_032724535.1_PDT001790270.1' already exists. Skipping...
Folder 'GCA_032724555.1_PDT001790268.1' already exists. Skipping...
Folder 'GCA_032724575.1_PDT001790269.1' already exists. Skipping...
Folder 'GCA_032724595.1_PDT001790267.1' already exists. Skipping...
Folder 'GCA_032724615.1_PDT001790266.1' already exists. Skipping...
Folder 'GCA_032724635.1_PDT001790265.1' already exists. Skipping...
Folder 'GCA_032724655.1_PDT001790264.1' already exists. Skipping...
Folder 'GCA_032724675.1_PDT001790263.1' already exists. Skipping...
Folder 'GCA_032724715.1_PDT001790262.1' already exists. Skipping...
Folder 'GCA_032724735.1_PDT001790260.1' already exists. Skipping...
Folder 'GCA_032724755.1_PDT001790256.1' already exists. Skipping...
Folder 'GCA_032724775.1_PDT001790259.1' already exists. Skipping...
Folder 'GCA_032724795.1_PDT001790257.1' already exists. Skipping...
Folder 'GCA_032724815.1_PDT001790258.1' already exists. Skipping...
Folder 'GCA_032724835.1_PDT001790253.1' already exists. Skipping...
Folder 'GCA_032724855.1_PDT001790254.1' already exists. Skipping...
Folder 'GCA_032724875.1_PDT001790255.1' already exists. Skipping...
Folder 'GCA_032724895.1_PDT001790252.1' already exists. Skipping...
Folder 'GCA_032724915.1_PDT001790251.1' already exists. Skipping...
Folder 'GCA_032724935.1_PDT001790250.1' already exists. Skipping...
Folder 'GCA_032724955.1_PDT001790249.1' already exists. Skipping...
Folder 'GCA_032724975.1_PDT001790248.1' already exists. Skipping...
Folder 'GCA_032724995.1_PDT001790247.1' already exists. Skipping...
Folder 'GCA_032725015.1_PDT001790246.1' already exists. Skipping...
Folder 'GCA_032725535.1_PDT001790242.1' already exists. Skipping...
Folder 'GCA_032725575.1_PDT001790243.1' already exists. Skipping...
Folder 'GCA_032725595.1_PDT001790244.1' already exists. Skipping...
Folder 'GCA_032725615.1_PDT001790245.1' already exists. Skipping...
Folder 'GCA_032725635.1_PDT001790240.1' already exists. Skipping...
Folder 'GCA_032725655.1_PDT001790239.1' already exists. Skipping...
Folder 'GCA_032725755.1_PDT001790233.1' already exists. Skipping...
Folder 'GCA_032725815.1_PDT001790231.1' already exists. Skipping...
Folder 'GCA_032725835.1_PDT001790230.1' already exists. Skipping...
Folder 'GCA_032725855.1_PDT001790228.1' already exists. Skipping...
Folder 'GCA_032725875.1_PDT001790227.1' already exists. Skipping...
Folder 'GCA_032725895.1_PDT001790229.1' already exists. Skipping...
Folder 'GCA_032725915.1_PDT001790226.1' already exists. Skipping...
Folder 'GCA_032725935.1_PDT001790225.1' already exists. Skipping...
Folder 'GCA_032725955.1_PDT001790224.1' already exists. Skipping...
Folder 'GCA_032725975.1_PDT001790223.1' already exists. Skipping...
Folder 'GCA_032725995.1_PDT001790221.1' already exists. Skipping...
Folder 'GCA_032726015.1_PDT001790222.1' already exists. Skipping...
Folder 'GCA_032726495.1_PDT001790219.1' already exists. Skipping...
Folder 'GCA_032726515.1_PDT001790220.1' already exists. Skipping...
Folder 'GCA_032726635.1_PDT001790213.1' already exists. Skipping...
Folder 'GCA_032726695.1_PDT001790210.1' already exists. Skipping...
Folder 'GCA_032728005.1_PDT001940823.1' already exists. Skipping...
Folder 'GCA_032728025.1_PDT001940814.1' already exists. Skipping...
Folder 'GCA_032729605.1_PDT001788115.1' already exists. Skipping...
Folder 'GCA_032731265.1_PDT001940820.1' already exists. Skipping...
Folder 'GCA_032731285.1_PDT001940806.1' already exists. Skipping...
Folder 'GCA_032733185.1_PDT001940805.1' already exists. Skipping...
Folder 'GCA_032733605.1_PDT001788033.1' already exists. Skipping...
Folder 'GCA_032733705.1_PDT001788027.1' already exists. Skipping...
Folder 'GCA_032733745.1_PDT001788025.1' already exists. Skipping...
Folder 'GCA_032733805.1_PDT001788023.1' already exists. Skipping...
Folder 'GCA_032733825.1_PDT001788022.1' already exists. Skipping...
Folder 'GCA_032733905.1_PDT001788018.1' already exists. Skipping...
Folder 'GCA_032733925.1_PDT001788015.1' already exists. Skipping...
Folder 'GCA_032733965.1_PDT001788016.1' already exists. Skipping...
Folder 'GCA_032733985.1_PDT001788014.1' already exists. Skipping...
Folder 'GCA_032734005.1_PDT001788012.1' already exists. Skipping...
Folder 'GCA_032734045.1_PDT001788013.1' already exists. Skipping...
Folder 'GCA_032734165.1_PDT001788010.1' already exists. Skipping...
Folder 'GCA_032734205.1_PDT001788003.1' already exists. Skipping...
Folder 'GCA_032735325.1_PDT001787889.1' already exists. Skipping...
Folder 'GCA_032735375.1_PDT001787888.1' already exists. Skipping...
Folder 'GCA_032735425.1_PDT001787887.1' already exists. Skipping...
Folder 'GCA_032735445.1_PDT001787886.1' already exists. Skipping...
Folder 'GCA_032735465.1_PDT001787884.1' already exists. Skipping...
Folder 'GCA_032735485.1_PDT001787885.1' already exists. Skipping...
Folder 'GCA_032735505.1_PDT001787883.1' already exists. Skipping...
Folder 'GCA_032735525.1_PDT001787882.1' already exists. Skipping...
Folder 'GCA_032735545.1_PDT001787880.1' already exists. Skipping...
Folder 'GCA_032735565.1_PDT001787878.1' already exists. Skipping...
Folder 'GCA_032735585.1_PDT001787877.1' already exists. Skipping...
Folder 'GCA_032735595.1_PDT001787879.1' already exists. Skipping...
Folder 'GCA_032735625.1_PDT001787881.1' already exists. Skipping...
Folder 'GCA_032735645.1_PDT001787876.1' already exists. Skipping...
Folder 'GCA_032735665.1_PDT001787873.1' already exists. Skipping...
Folder 'GCA_032735685.1_PDT001787874.1' already exists. Skipping...
Folder 'GCA_032735705.1_PDT001787872.1' already exists. Skipping...
Folder 'GCA_032735725.1_PDT001787875.1' already exists. Skipping...
Folder 'GCA_032735745.1_PDT001787871.1' already exists. Skipping...
Folder 'GCA_032735765.1_PDT001787870.1' already exists. Skipping...
Folder 'GCA_032735785.1_PDT001787869.1' already exists. Skipping...
Folder 'GCA_032735825.1_PDT001787868.1' already exists. Skipping...
Folder 'GCA_032736905.1_PDT001940812.1' already exists. Skipping...
Folder 'GCA_032740495.1_PDT001941053.1' already exists. Skipping...
Folder 'GCA_032748615.1_PDT001927237.1' already exists. Skipping...
Folder 'GCA_032748635.1_PDT001927234.1' already exists. Skipping...
Folder 'GCA_032754435.1_PDT001787439.1' already exists. Skipping...
Folder 'GCA_032754455.1_PDT001787437.1' already exists. Skipping...
Folder 'GCA_032754475.1_PDT001787438.1' already exists. Skipping...
Folder 'GCA_032754495.1_PDT001787436.1' already exists. Skipping...
Folder 'GCA_032754515.1_PDT001787434.1' already exists. Skipping...
Folder 'GCA_032754535.1_PDT001787435.1' already exists. Skipping...
Folder 'GCA_032754555.1_PDT001787433.1' already exists. Skipping...
Folder 'GCA_032754575.1_PDT001787428.1' already exists. Skipping...
Folder 'GCA_032754615.1_PDT001787431.1' already exists. Skipping...
Folder 'GCA_032754635.1_PDT001787427.1' already exists. Skipping...
Folder 'GCA_032754655.1_PDT001787430.1' already exists. Skipping...
Folder 'GCA_032754675.1_PDT001787426.1' already exists. Skipping...
Folder 'GCA_032754705.1_PDT001787425.1' already exists. Skipping...
Folder 'GCA_032754735.1_PDT001787420.1' already exists. Skipping...
Folder 'GCA_032754755.1_PDT001787423.1' already exists. Skipping...
Folder 'GCA_032754795.1_PDT001787419.1' already exists. Skipping...
Folder 'GCA_032754815.1_PDT001787418.1' already exists. Skipping...
Folder 'GCA_032754975.1_PDT001787405.1' already exists. Skipping...
Folder 'GCA_032755075.1_PDT001787399.1' already exists. Skipping...
Folder 'GCA_032755295.1_PDT001787386.1' already exists. Skipping...
Folder 'GCA_032755375.1_PDT001787381.1' already exists. Skipping...
Folder 'GCA_032755395.1_PDT001787379.1' already exists. Skipping...
Folder 'GCA_032755415.1_PDT001787380.1' already exists. Skipping...
Folder 'GCA_032755455.1_PDT001787373.1' already exists. Skipping...
Folder 'GCA_032755475.1_PDT001787375.1' already exists. Skipping...
Folder 'GCA_032756015.1_PDT001774488.1' already exists. Skipping...
Folder 'GCA_032756285.1_PDT001757819.1' already exists. Skipping...
Folder 'GCA_032756475.1_PDT001757811.1' already exists. Skipping...
Folder 'GCA_032756535.1_PDT001757806.1' already exists. Skipping...
Folder 'GCA_032756555.1_PDT001757804.1' already exists. Skipping...
Folder 'GCA_032756575.1_PDT001757805.1' already exists. Skipping...
Folder 'GCA_032756615.1_PDT001757802.1' already exists. Skipping...
Folder 'GCA_032756635.1_PDT001757801.1' already exists. Skipping...
Folder 'GCA_032756715.1_PDT001757800.1' already exists. Skipping...
Folder 'GCA_032756735.1_PDT001757799.1' already exists. Skipping...
Folder 'GCA_032759535.1_PDT001941408.1' already exists. Skipping...
Folder 'GCA_032759555.1_PDT001941409.1' already exists. Skipping...
Folder 'GCA_032759595.1_PDT001941396.1' already exists. Skipping...
Folder 'GCA_032759655.1_PDT001941391.1' already exists. Skipping...
Folder 'GCA_032759675.1_PDT001941394.1' already exists. Skipping...
Folder 'GCA_032759695.1_PDT001941406.1' already exists. Skipping...
Folder 'GCA_032759735.1_PDT001941405.1' already exists. Skipping...
Folder 'GCA_032759755.1_PDT001941404.1' already exists. Skipping...
Folder 'GCA_032759765.1_PDT001941402.1' already exists. Skipping...
Folder 'GCA_032759815.1_PDT001941400.1' already exists. Skipping...
Folder 'GCA_032759845.1_PDT001941398.1' already exists. Skipping...
Folder 'GCA_032759895.1_PDT001941392.1' already exists. Skipping...
Folder 'GCA_032759975.1_PDT001941387.1' already exists. Skipping...
Folder 'GCA_032760095.1_PDT001941381.1' already exists. Skipping...
Folder 'GCA_032760115.1_PDT001941380.1' already exists. Skipping...
Folder 'GCA_032760615.1_PDT001941354.1' already exists. Skipping...
Folder 'GCA_032760695.1_PDT001941352.1' already exists. Skipping...
Folder 'GCA_032765315.1_PDT001787429.1' already exists. Skipping...
Folder 'GCA_032765355.1_PDT001787422.1' already exists. Skipping...
Folder 'GCA_032765495.1_PDT001787388.1' already exists. Skipping...
Folder 'GCA_032765535.1_PDT001787382.1' already exists. Skipping...
Folder 'GCA_032765555.1_PDT001787374.1' already exists. Skipping...
Folder 'GCA_032769855.1_PDT001786728.1' already exists. Skipping...
Folder 'GCA_032769915.1_PDT001786723.1' already exists. Skipping...
Folder 'GCA_032769955.1_PDT001786724.1' already exists. Skipping...
Folder 'GCA_032769975.1_PDT001786722.1' already exists. Skipping...
Folder 'GCA_032769995.1_PDT001786721.1' already exists. Skipping...
Folder 'GCA_032770015.1_PDT001786718.1' already exists. Skipping...
Folder 'GCA_032770045.1_PDT001786720.1' already exists. Skipping...
Folder 'GCA_032770535.1_PDT001786656.1' already exists. Skipping...
Folder 'GCA_032770575.1_PDT001786655.1' already exists. Skipping...
Folder 'GCA_032770595.1_PDT001786654.1' already exists. Skipping...
Folder 'GCA_032770615.1_PDT001786653.1' already exists. Skipping...
Folder 'GCA_032770635.1_PDT001786652.1' already exists. Skipping...
Folder 'GCA_032770655.1_PDT001786651.1' already exists. Skipping...
Folder 'GCA_032770675.1_PDT001786649.1' already exists. Skipping...
Folder 'GCA_032770695.1_PDT001786650.1' already exists. Skipping...
Folder 'GCA_032772635.1_PDT001786508.1' already exists. Skipping...
Folder 'GCA_032775545.1_PDT001941503.1' already exists. Skipping...
Folder 'GCA_032775585.1_PDT001941504.1' already exists. Skipping...
Folder 'GCA_032775625.1_PDT001941509.1' already exists. Skipping...
Folder 'GCA_032779125.1_PDT001786013.1' already exists. Skipping...
Folder 'GCA_032781385.1_PDT001785958.1' already exists. Skipping...
Folder 'GCA_032781405.1_PDT001785949.1' already exists. Skipping...
Folder 'GCA_032782445.1_PDT001941889.1' already exists. Skipping...
Folder 'GCA_032782485.1_PDT001941887.1' already exists. Skipping...
Folder 'GCA_032782505.1_PDT001941884.1' already exists. Skipping...
Folder 'GCA_032782525.1_PDT001941882.1' already exists. Skipping...
Folder 'GCA_032782565.1_PDT001941880.1' already exists. Skipping...
Folder 'GCA_032782605.1_PDT001941875.1' already exists. Skipping...
Folder 'GCA_032783745.1_PDT001941883.1' already exists. Skipping...
Folder 'GCA_032783765.1_PDT001941881.1' already exists. Skipping...
Folder 'GCA_032785645.1_PDT001941885.1' already exists. Skipping...
Folder 'GCA_032785925.1_PDT001941786.1' already exists. Skipping...
Folder 'GCA_032788225.1_PDT001785705.1' already exists. Skipping...
Folder 'GCA_032788545.1_PDT001941918.1' already exists. Skipping...
Folder 'GCA_032790765.1_PDT001941933.1' already exists. Skipping...
Folder 'GCA_032790805.1_PDT001941906.1' already exists. Skipping...
Folder 'GCA_032790815.1_PDT001941928.1' already exists. Skipping...
Folder 'GCA_032790905.1_PDT001941895.1' already exists. Skipping...
Folder 'GCA_032790925.1_PDT001941894.1' already exists. Skipping...
Folder 'GCA_032790945.1_PDT001941892.1' already exists. Skipping...
Folder 'GCA_032793565.1_PDT001785539.1' already exists. Skipping...
Folder 'GCA_032793575.1_PDT001785538.1' already exists. Skipping...
Folder 'GCA_032794585.1_PDT001785492.1' already exists. Skipping...
Folder 'GCA_032794605.1_PDT001785490.1' already exists. Skipping...
Folder 'GCA_032794645.1_PDT001785487.1' already exists. Skipping...
Folder 'GCA_032794685.1_PDT001785486.1' already exists. Skipping...
Folder 'GCA_032794705.1_PDT001785485.1' already exists. Skipping...
Folder 'GCA_032794885.1_PDT001785482.1' already exists. Skipping...
Folder 'GCA_032794925.1_PDT001785483.1' already exists. Skipping...
Folder 'GCA_032794945.1_PDT001785480.1' already exists. Skipping...
Folder 'GCA_032794985.1_PDT001785478.1' already exists. Skipping...
Folder 'GCA_032795025.1_PDT001785481.1' already exists. Skipping...
Folder 'GCA_032795045.1_PDT001785475.1' already exists. Skipping...
Folder 'GCA_032795585.1_PDT001785448.1' already exists. Skipping...
Folder 'GCA_032795605.1_PDT001785446.1' already exists. Skipping...
Folder 'GCA_032795645.1_PDT001785443.1' already exists. Skipping...
Folder 'GCA_032795665.1_PDT001785445.1' already exists. Skipping...

Retreiveing data: 29603it [00:05, 6714.69it/s]

Folder 'GCA_033204875.1_PDT001757856.1' already exists. Skipping...
Folder 'GCA_033204965.1_PDT001757797.1' already exists. Skipping...
Folder 'GCA_033205175.1_PDT001757786.1' already exists. Skipping...
Folder 'GCA_033205215.1_PDT001757785.1' already exists. Skipping...
Folder 'GCA_033205455.1_PDT001757772.1' already exists. Skipping...
Folder 'GCA_033205595.1_PDT001757766.1' already exists. Skipping...
Folder 'GCA_033205755.1_PDT001757760.1' already exists. Skipping...
Folder 'GCA_033205795.1_PDT001757754.1' already exists. Skipping...
Folder 'GCA_033205815.1_PDT001757755.1' already exists. Skipping...
Folder 'GCA_033205925.1_PDT001757749.1' already exists. Skipping...
Folder 'GCA_033206035.1_PDT001757744.1' already exists. Skipping...
Folder 'GCA_033206475.1_PDT001757721.1' already exists. Skipping...
Folder 'GCA_033206495.1_PDT001757720.1' already exists. Skipping...
Folder 'GCA_033206515.1_PDT001757719.1' already exists. Skipping...
Folder 'GCA_033206535.1_PDT001757717.1' already exists. Skipping...
Folder 'GCA_033206555.1_PDT001757718.1' already exists. Skipping...
Folder 'GCA_033206615.1_PDT001757715.1' already exists. Skipping...
Folder 'GCA_033207015.1_PDT001757693.1' already exists. Skipping...
Folder 'GCA_033207275.1_PDT001757681.1' already exists. Skipping...
Folder 'GCA_033207375.1_PDT001757675.1' already exists. Skipping...
Folder 'GCA_033207475.1_PDT001757671.1' already exists. Skipping...
Folder 'GCA_033207595.1_PDT001757669.1' already exists. Skipping...
Folder 'GCA_033207615.1_PDT001757664.1' already exists. Skipping...
Folder 'GCA_033207635.1_PDT001757661.1' already exists. Skipping...
Folder 'GCA_033207715.1_PDT001757658.1' already exists. Skipping...
Folder 'GCA_033207915.1_PDT001757646.1' already exists. Skipping...
Folder 'GCA_033207935.1_PDT001757648.1' already exists. Skipping...
Folder 'GCA_033208255.1_PDT001757629.1' already exists. Skipping...
Folder 'GCA_033208475.1_PDT001757622.1' already exists. Skipping...
Folder 'GCA_033208595.1_PDT001757612.1' already exists. Skipping...
Folder 'GCA_033209015.1_PDT001757590.1' already exists. Skipping...
Folder 'GCA_033209115.1_PDT001757585.1' already exists. Skipping...
Folder 'GCA_033209255.1_PDT001757577.1' already exists. Skipping...
Folder 'GCA_033209395.1_PDT001757569.1' already exists. Skipping...
Folder 'GCA_033209915.1_PDT001757543.1' already exists. Skipping...
Folder 'GCA_033209975.1_PDT001757541.1' already exists. Skipping...
Folder 'GCA_033209995.1_PDT001757540.1' already exists. Skipping...
Folder 'GCA_033210155.1_PDT001757532.1' already exists. Skipping...
Folder 'GCA_033210375.1_PDT001757520.1' already exists. Skipping...
Folder 'GCA_033210495.1_PDT001757516.1' already exists. Skipping...
Folder 'GCA_033210515.1_PDT001757515.1' already exists. Skipping...
Folder 'GCA_033210555.1_PDT001757512.1' already exists. Skipping...
Folder 'GCA_033210575.1_PDT001757511.1' already exists. Skipping...
Folder 'GCA_033210595.1_PDT001757508.1' already exists. Skipping...
Folder 'GCA_033210615.1_PDT001757507.1' already exists. Skipping...
Folder 'GCA_033210635.1_PDT001757505.1' already exists. Skipping...
Folder 'GCA_033210645.1_PDT001757506.1' already exists. Skipping...
Folder 'GCA_033210675.1_PDT001757504.1' already exists. Skipping...
Folder 'GCA_033210695.1_PDT001757503.1' already exists. Skipping...
Folder 'GCA_033210715.1_PDT001757502.1' already exists. Skipping...
Folder 'GCA_033210735.1_PDT001757500.1' already exists. Skipping...
Folder 'GCA_033211195.1_PDT001757425.1' already exists. Skipping...
Folder 'GCA_033211215.1_PDT001757424.1' already exists. Skipping...
Folder 'GCA_033211255.1_PDT001757423.1' already exists. Skipping...
Folder 'GCA_033211535.1_PDT001757407.1' already exists. Skipping...
Folder 'GCA_033211595.1_PDT001757405.1' already exists. Skipping...
Folder 'GCA_033211635.1_PDT001757401.1' already exists. Skipping...
Folder 'GCA_033212235.1_PDT001757366.1' already exists. Skipping...
Folder 'GCA_033212475.1_PDT001757340.1' already exists. Skipping...
Folder 'GCA_033212535.1_PDT001757337.1' already exists. Skipping...
Folder 'GCA_033212575.1_PDT001757334.1' already exists. Skipping...
Folder 'GCA_033213175.1_PDT001757294.1' already exists. Skipping...
Folder 'GCA_033213195.1_PDT001757292.1' already exists. Skipping...
Folder 'GCA_033213355.1_PDT001757286.1' already exists. Skipping...
Folder 'GCA_033214175.1_PDT001757245.1' already exists. Skipping...
Folder 'GCA_033214195.1_PDT001757242.1' already exists. Skipping...
Folder 'GCA_033215155.1_PDT001965021.1' already exists. Skipping...
Folder 'GCA_033215195.1_PDT001965018.1' already exists. Skipping...
Folder 'GCA_033215235.1_PDT001965017.1' already exists. Skipping...
Folder 'GCA_033215375.1_PDT001965009.1' already exists. Skipping...
Folder 'GCA_033215395.1_PDT001965007.1' already exists. Skipping...
Folder 'GCA_033215615.1_PDT001757218.1' already exists. Skipping...
Folder 'GCA_033216355.1_PDT001964924.1' already exists. Skipping...
Folder 'GCA_033217715.1_PDT001757098.1' already exists. Skipping...
Folder 'GCA_033217755.1_PDT001757096.1' already exists. Skipping...
Folder 'GCA_033218135.1_PDT001757082.1' already exists. Skipping...
Folder 'GCA_033218475.1_PDT001757061.1' already exists. Skipping...
Folder 'GCA_033219415.1_PDT001757028.1' already exists. Skipping...
Folder 'GCA_033219435.1_PDT001757029.1' already exists. Skipping...
Folder 'GCA_033219675.1_PDT001757016.1' already exists. Skipping...
Folder 'GCA_033219735.1_PDT001757013.1' already exists. Skipping...
Folder 'GCA_033220055.1_PDT001780389.1' already exists. Skipping...
Folder 'GCA_033220295.1_PDT001965016.1' already exists. Skipping...
Folder 'GCA_033220565.1_PDT001756992.1' already exists. Skipping...
Folder 'GCA_033220775.1_PDT001756983.1' already exists. Skipping...
Folder 'GCA_033221055.1_PDT001756962.1' already exists. Skipping...
Folder 'GCA_033221815.1_PDT001756925.1' already exists. Skipping...
Folder 'GCA_033222385.1_PDT001756898.1' already exists. Skipping...
Folder 'GCA_033223065.1_PDT001756975.1' already exists. Skipping...
Folder 'GCA_033223105.1_PDT001757047.1' already exists. Skipping...
Folder 'GCA_033223125.1_PDT001756966.1' already exists. Skipping...
Folder 'GCA_033223445.1_PDT001756855.1' already exists. Skipping...
Folder 'GCA_033223465.1_PDT001756854.1' already exists. Skipping...
Folder 'GCA_033224145.1_PDT001756829.1' already exists. Skipping...
Folder 'GCA_033224225.1_PDT001756821.1' already exists. Skipping...
Folder 'GCA_033224245.1_PDT001756813.1' already exists. Skipping...
Folder 'GCA_033224685.1_PDT001756792.1' already exists. Skipping...
Folder 'GCA_033225125.1_PDT001756771.1' already exists. Skipping...
Folder 'GCA_033225645.1_PDT001756746.1' already exists. Skipping...
Folder 'GCA_033226105.1_PDT001756724.1' already exists. Skipping...
Folder 'GCA_033226145.1_PDT001756722.1' already exists. Skipping...
Folder 'GCA_033226775.1_PDT001756688.1' already exists. Skipping...
Folder 'GCA_033226885.1_PDT001756687.1' already exists. Skipping...
Folder 'GCA_033226945.1_PDT001756683.1' already exists. Skipping...
Folder 'GCA_033227085.1_PDT001756675.1' already exists. Skipping...
Folder 'GCA_033227385.1_PDT001756658.1' already exists. Skipping...
Folder 'GCA_033227685.1_PDT001756642.1' already exists. Skipping...
Folder 'GCA_033228025.1_PDT001756628.1' already exists. Skipping...
Folder 'GCA_033228885.1_PDT001756584.1' already exists. Skipping...
Folder 'GCA_033229325.1_PDT001756561.1' already exists. Skipping...
Folder 'GCA_033229545.1_PDT001756972.1' already exists. Skipping...
Folder 'GCA_033229725.1_PDT001756548.1' already exists. Skipping...
Folder 'GCA_033229945.1_PDT001756535.1' already exists. Skipping...
Folder 'GCA_033230105.1_PDT001756528.1' already exists. Skipping...
Folder 'GCA_033230465.1_PDT001756512.1' already exists. Skipping...
Folder 'GCA_033230845.1_PDT001756492.1' already exists. Skipping...
Folder 'GCA_033230905.1_PDT001756491.1' already exists. Skipping...
Folder 'GCA_033231025.1_PDT001756484.1' already exists. Skipping...
Folder 'GCA_033231105.1_PDT001756478.1' already exists. Skipping...
Folder 'GCA_033231625.1_PDT001756452.1' already exists. Skipping...
Folder 'GCA_033231745.1_PDT001756444.1' already exists. Skipping...
Folder 'GCA_033232005.1_PDT001756431.1' already exists. Skipping...
Folder 'GCA_033232105.1_PDT001756458.1' already exists. Skipping...
Folder 'GCA_033232265.1_PDT001756423.1' already exists. Skipping...
Folder 'GCA_033232545.1_PDT001756407.1' already exists. Skipping...
Folder 'GCA_033233365.1_PDT001756385.1' already exists. Skipping...
Folder 'GCA_033233635.1_PDT001756378.1' already exists. Skipping...
Folder 'GCA_033233855.1_PDT001756372.1' already exists. Skipping...
Folder 'GCA_033235385.1_PDT001756342.1' already exists. Skipping...
Folder 'GCA_033235485.1_PDT001756341.1' already exists. Skipping...
Folder 'GCA_033236105.1_PDT001756322.1' already exists. Skipping...
Folder 'GCA_033236285.1_PDT001756317.1' already exists. Skipping...
Folder 'GCA_033236565.1_PDT001756310.1' already exists. Skipping...
Folder 'GCA_033236605.1_PDT001756307.1' already exists. Skipping...
Folder 'GCA_033236625.1_PDT001756308.1' already exists. Skipping...
Folder 'GCA_033236805.1_PDT001756306.1' already exists. Skipping...
Folder 'GCA_033236965.1_PDT001756300.1' already exists. Skipping...
Folder 'GCA_033237525.1_PDT001756297.1' already exists. Skipping...
Folder 'GCA_033237545.1_PDT001756296.1' already exists. Skipping...
Folder 'GCA_033237725.1_PDT001756290.1' already exists. Skipping...
Folder 'GCA_033237765.1_PDT001756291.1' already exists. Skipping...
Folder 'GCA_033237785.1_PDT001756289.1' already exists. Skipping...
Folder 'GCA_033240365.1_ASM3324036v1' already exists. Skipping...
Folder 'GCA_033240445.1_ASM3324044v1' already exists. Skipping...
Folder 'GCA_033240915.1_ASM3324091v1' already exists. Skipping...
Folder 'GCA_033241395.1_ASM3324139v1' already exists. Skipping...
Folder 'GCA_033241575.1_PDT001756145.1' already exists. Skipping...
Folder 'GCA_033241615.1_PDT001756144.1' already exists. Skipping...
Folder 'GCA_033241635.1_PDT001756146.1' already exists. Skipping...
Folder 'GCA_033241695.1_PDT001756143.1' already exists. Skipping...
Folder 'GCA_033241715.1_PDT001756140.1' already exists. Skipping...
Folder 'GCA_033241775.1_PDT001756141.1' already exists. Skipping...
Folder 'GCA_033241985.1_ASM3324198v1' already exists. Skipping...
Folder 'GCA_033242045.1_ASM3324204v1' already exists. Skipping...
Folder 'GCA_033242075.1_ASM3324207v1' already exists. Skipping...
Folder 'GCA_033242105.1_ASM3324210v1' already exists. Skipping...
Folder 'GCA_033242165.1_ASM3324216v1' already exists. Skipping...
Folder 'GCA_033242185.1_ASM3324218v1' already exists. Skipping...
Folder 'GCA_033242505.1_PDT001756603.1' already exists. Skipping...
Folder 'GCA_033242685.1_PDT001754318.1' already exists. Skipping...
Folder 'GCA_033242705.1_PDT001754317.1' already exists. Skipping...
Folder 'GCA_033242725.1_PDT001754314.1' already exists. Skipping...
Folder 'GCA_033242745.1_PDT001754310.1' already exists. Skipping...
Folder 'GCA_033242765.1_PDT001754312.1' already exists. Skipping...
Folder 'GCA_033242785.1_PDT001754311.1' already exists. Skipping...
Folder 'GCA_033242805.1_PDT001754309.1' already exists. Skipping...
Folder 'GCA_033242825.1_PDT001754308.1' already exists. Skipping...
Folder 'GCA_033242865.1_PDT001754307.1' already exists. Skipping...
Folder 'GCA_033242905.1_PDT001754182.1' already exists. Skipping...
Folder 'GCA_033242925.1_PDT001754181.1' already exists. Skipping...
Folder 'GCA_033242985.1_PDT001754172.1' already exists. Skipping...
Folder 'GCA_033243005.1_PDT001754169.1' already exists. Skipping...
Folder 'GCA_033243025.1_PDT001754170.1' already exists. Skipping...
Folder 'GCA_033243045.1_PDT001754168.1' already exists. Skipping...
Folder 'GCA_033243065.1_PDT001754165.1' already exists. Skipping...
Folder 'GCA_033244185.1_PDT001754079.1' already exists. Skipping...
Folder 'GCA_033244205.1_PDT001754078.1' already exists. Skipping...
Folder 'GCA_033244225.1_PDT001754077.1' already exists. Skipping...
Folder 'GCA_033244245.1_PDT001754074.1' already exists. Skipping...
Folder 'GCA_033244285.1_PDT001754073.1' already exists. Skipping...
Folder 'GCA_033244305.1_PDT001754072.1' already exists. Skipping...
Folder 'GCA_033244475.1_PDT001754057.1' already exists. Skipping...
Folder 'GCA_033244795.1_PDT001754041.1' already exists. Skipping...
Folder 'GCA_033245505.1_PDT001744924.1' already exists. Skipping...
Folder 'GCA_033245825.1_PDT001744908.1' already exists. Skipping...
Folder 'GCA_033245865.1_PDT001744906.1' already exists. Skipping...
Folder 'GCA_033246225.1_PDT001748450.1' already exists. Skipping...
Folder 'GCA_033246305.1_PDT001748440.1' already exists. Skipping...
Folder 'GCA_033246505.1_PDT001748395.1' already exists. Skipping...
Folder 'GCA_033246545.1_PDT001748391.1' already exists. Skipping...
Folder 'GCA_033246585.1_PDT001748388.1' already exists. Skipping...
Folder 'GCA_033246605.1_PDT001748385.1' already exists. Skipping...
Folder 'GCA_033246685.1_PDT001748378.1' already exists. Skipping...
Folder 'GCA_033246765.1_PDT001748371.1' already exists. Skipping...
Folder 'GCA_033246825.1_PDT001744889.1' already exists. Skipping...
Folder 'GCA_033246845.1_PDT001748363.1' already exists. Skipping...
Folder 'GCA_033247345.1_PDT001744862.1' already exists. Skipping...
Folder 'GCA_033247365.1_PDT001744861.1' already exists. Skipping...
Folder 'GCA_033247385.1_PDT001744860.1' already exists. Skipping...
Folder 'GCA_033247885.1_PDT001744840.1' already exists. Skipping...
Folder 'GCA_033248025.1_PDT001744834.1' already exists. Skipping...
Folder 'GCA_033248325.1_PDT001748361.1' already exists. Skipping...
Folder 'GCA_033248365.1_PDT001748353.1' already exists. Skipping...
Folder 'GCA_033248405.1_PDT001748338.1' already exists. Skipping...
Folder 'GCA_033248465.1_PDT001748328.1' already exists. Skipping...
Folder 'GCA_033248705.1_PDT001748271.1' already exists. Skipping...
Folder 'GCA_033248805.1_PDT001748253.1' already exists. Skipping...
Folder 'GCA_033249225.1_PDT001748191.1' already exists. Skipping...
Folder 'GCA_033249385.1_PDT001748161.1' already exists. Skipping...
Folder 'GCA_033249505.1_PDT001748141.1' already exists. Skipping...
Folder 'GCA_033249525.1_PDT001748136.1' already exists. Skipping...
Folder 'GCA_033249545.1_PDT001748132.1' already exists. Skipping...
Folder 'GCA_033249565.1_PDT001748131.1' already exists. Skipping...
Folder 'GCA_033249585.1_PDT001748126.1' already exists. Skipping...
Folder 'GCA_033249605.1_PDT001748129.1' already exists. Skipping...
Folder 'GCA_033249635.1_PDT001748121.1' already exists. Skipping...
Folder 'GCA_033249825.1_PDT001748087.1' already exists. Skipping...
Folder 'GCA_033251065.1_PDT001747895.1' already exists. Skipping...
Folder 'GCA_033251245.1_PDT001747860.1' already exists. Skipping...
Folder 'GCA_033251365.1_PDT001747848.1' already exists. Skipping...
Folder 'GCA_033251405.1_PDT001747840.1' already exists. Skipping...
Folder 'GCA_033251445.1_PDT001747835.1' already exists. Skipping...
Folder 'GCA_033251545.1_PDT001747820.1' already exists. Skipping...
Folder 'GCA_033251765.1_PDT001747778.1' already exists. Skipping...
Folder 'GCA_033251785.1_PDT001747775.1' already exists. Skipping...
Folder 'GCA_033252165.1_PDT001747708.1' already exists. Skipping...
Folder 'GCA_033252175.1_PDT001747718.1' already exists. Skipping...
Folder 'GCA_033252205.1_PDT001747713.1' already exists. Skipping...
Folder 'GCA_033252225.1_PDT001747721.1' already exists. Skipping...
Folder 'GCA_033252245.1_PDT001747723.1' already exists. Skipping...
Folder 'GCA_033253385.1_PDT001747536.1' already exists. Skipping...
Folder 'GCA_033253625.1_PDT001747494.1' already exists. Skipping...
Folder 'GCA_033253825.1_PDT001747479.1' already exists. Skipping...
Folder 'GCA_033253965.1_PDT001747457.1' already exists. Skipping...
Folder 'GCA_033253985.1_PDT001747454.1' already exists. Skipping...
Folder 'GCA_033254745.1_PDT001747377.1' already exists. Skipping...
Folder 'GCA_033254945.1_PDT001747347.1' already exists. Skipping...
Folder 'GCA_033255185.1_PDT001747318.1' already exists. Skipping...
Folder 'GCA_033255385.1_PDT001747315.1' already exists. Skipping...
Folder 'GCA_033255485.1_PDT001747305.1' already exists. Skipping...
Folder 'GCA_033255525.1_PDT001747303.1' already exists. Skipping...
Folder 'GCA_033255865.1_PDT001747275.1' already exists. Skipping...
Folder 'GCA_033256285.1_PDT001747228.1' already exists. Skipping...
Folder 'GCA_033256405.1_PDT001747210.1' already exists. Skipping...
Folder 'GCA_033256645.1_PDT001747190.1' already exists. Skipping...
Folder 'GCA_033256685.1_PDT001747185.1' already exists. Skipping...
Folder 'GCA_033256705.1_PDT001747183.1' already exists. Skipping...
Folder 'GCA_033256745.1_PDT001747181.1' already exists. Skipping...
Folder 'GCA_033256785.1_PDT001747176.1' already exists. Skipping...
Folder 'GCA_033256825.1_PDT001747173.1' already exists. Skipping...
Folder 'GCA_033257105.1_PDT001747150.1' already exists. Skipping...
Folder 'GCA_033257665.1_PDT001747078.1' already exists. Skipping...
Folder 'GCA_033257695.1_PDT001747073.1' already exists. Skipping...
Folder 'GCA_033257985.1_PDT001747044.1' already exists. Skipping...
Folder 'GCA_033258065.1_PDT001747041.1' already exists. Skipping...
Folder 'GCA_033259565.1_PDT001747024.1' already exists. Skipping...
Folder 'GCA_033259605.1_PDT001747016.1' already exists. Skipping...
Folder 'GCA_033259745.1_PDT001746999.1' already exists. Skipping...
Folder 'GCA_033259785.1_PDT001746994.1' already exists. Skipping...
Folder 'GCA_033259825.1_PDT001746989.1' already exists. Skipping...
Folder 'GCA_033260365.1_PDT001746954.1' already exists. Skipping...
Folder 'GCA_033260605.1_PDT001746931.1' already exists. Skipping...
Folder 'GCA_033260765.1_PDT001746917.1' already exists. Skipping...
Folder 'GCA_033260845.1_PDT001746909.1' already exists. Skipping...
Folder 'GCA_033260925.1_PDT001746904.1' already exists. Skipping...
Folder 'GCA_033260945.1_PDT001746899.1' already exists. Skipping...
Folder 'GCA_033260965.1_PDT001746894.1' already exists. Skipping...
Folder 'GCA_033261325.1_PDT001746859.1' already exists. Skipping...
Folder 'GCA_033261425.1_PDT001746842.1' already exists. Skipping...
Folder 'GCA_033261625.1_PDT001746825.1' already exists. Skipping...
Folder 'GCA_033261685.1_PDT001746820.1' already exists. Skipping...
Folder 'GCA_033261705.1_PDT001746819.1' already exists. Skipping...
Folder 'GCA_033261725.1_PDT001746817.1' already exists. Skipping...
Folder 'GCA_033262065.1_PDT001746784.1' already exists. Skipping...
Folder 'GCA_033262405.1_PDT001746752.1' already exists. Skipping...
Folder 'GCA_033262705.1_PDT001746717.1' already exists. Skipping...
Folder 'GCA_033263305.1_PDT001746678.1' already exists. Skipping...
Folder 'GCA_033263525.1_PDT001746660.1' already exists. Skipping...
Folder 'GCA_033263605.1_PDT001746658.1' already exists. Skipping...
Folder 'GCA_033263645.1_PDT001746645.1' already exists. Skipping...
Folder 'GCA_033263745.1_PDT001746635.1' already exists. Skipping...
Folder 'GCA_033263845.1_PDT001746620.1' already exists. Skipping...
Folder 'GCA_033263865.1_PDT001746615.1' already exists. Skipping...
Folder 'GCA_033263905.1_PDT001746618.1' already exists. Skipping...
Folder 'GCA_033263945.1_PDT001746610.1' already exists. Skipping...
Folder 'GCA_033263965.1_PDT001746605.1' already exists. Skipping...
Folder 'GCA_033264005.1_PDT001746600.1' already exists. Skipping...
Folder 'GCA_033264105.1_PDT001746595.1' already exists. Skipping...
Folder 'GCA_033265205.1_PDT001746498.1' already exists. Skipping...
Folder 'GCA_033265325.1_PDT001746481.1' already exists. Skipping...
Folder 'GCA_033265365.1_PDT001746474.1' already exists. Skipping...
Folder 'GCA_033265865.1_PDT001746301.1' already exists. Skipping...
Folder 'GCA_033265925.1_PDT001746224.1' already exists. Skipping...
Folder 'GCA_033265965.1_PDT001746214.1' already exists. Skipping...

Retreiveing data: 30948it [00:06, 6709.54it/s]

Folder 'GCA_033484455.1_PDT001746679.1' already exists. Skipping...
Folder 'GCA_033484615.1_PDT001746661.1' already exists. Skipping...
Folder 'GCA_033484635.1_PDT001746657.1' already exists. Skipping...
Folder 'GCA_033484735.1_PDT001746649.1' already exists. Skipping...
Folder 'GCA_033484815.1_PDT001746641.1' already exists. Skipping...
Folder 'GCA_033484835.1_PDT001746642.1' already exists. Skipping...
Folder 'GCA_033484855.1_PDT001746639.1' already exists. Skipping...
Folder 'GCA_033488975.1_PDT001975688.1' already exists. Skipping...
Folder 'GCA_033489155.1_PDT001975682.1' already exists. Skipping...
Folder 'GCA_033489295.1_PDT001975674.1' already exists. Skipping...
Folder 'GCA_033489425.1_PDT001975659.1' already exists. Skipping...
Folder 'GCA_033489475.1_PDT001975657.1' already exists. Skipping...
Folder 'GCA_033489575.1_PDT001975652.1' already exists. Skipping...
Folder 'GCA_033489675.1_PDT001975645.1' already exists. Skipping...
Folder 'GCA_033489715.1_PDT001975644.1' already exists. Skipping...
Folder 'GCA_033489775.1_PDT001975642.1' already exists. Skipping...
Folder 'GCA_033489795.1_PDT001975641.1' already exists. Skipping...
Folder 'GCA_033492035.1_PDT001975505.1' already exists. Skipping...
Folder 'GCA_033499935.1_PDT001746634.1' already exists. Skipping...
Folder 'GCA_033499975.1_PDT001746631.1' already exists. Skipping...
Folder 'GCA_033500175.1_PDT001746612.1' already exists. Skipping...
Folder 'GCA_033500215.1_PDT001746619.1' already exists. Skipping...
Folder 'GCA_033500275.1_PDT001746607.1' already exists. Skipping...
Folder 'GCA_033500295.1_PDT001746606.1' already exists. Skipping...
Folder 'GCA_033500315.1_PDT001746604.1' already exists. Skipping...
Folder 'GCA_033500375.1_PDT001746599.1' already exists. Skipping...
Folder 'GCA_033500435.1_PDT001746589.1' already exists. Skipping...
Folder 'GCA_033500935.1_PDT001746529.1' already exists. Skipping...
Folder 'GCA_033501075.1_PDT001746522.1' already exists. Skipping...
Folder 'GCA_033501175.1_PDT001746514.1' already exists. Skipping...
Folder 'GCA_033501375.1_PDT001746497.1' already exists. Skipping...
Folder 'GCA_033501895.1_PDT001742374.1' already exists. Skipping...
Folder 'GCA_033501955.1_PDT001742371.1' already exists. Skipping...
Folder 'GCA_033502335.1_PDT001742291.1' already exists. Skipping...
Folder 'GCA_033502355.1_PDT001742290.1' already exists. Skipping...
Folder 'GCA_033502395.1_PDT001742288.1' already exists. Skipping...
Folder 'GCA_033502415.1_PDT001742287.1' already exists. Skipping...
Folder 'GCA_033502475.1_PDT001742286.1' already exists. Skipping...
Folder 'GCA_033502535.1_PDT001742264.1' already exists. Skipping...
Folder 'GCA_033502555.1_PDT001742274.1' already exists. Skipping...
Folder 'GCA_033502655.1_PDT001742261.1' already exists. Skipping...
Folder 'GCA_033502675.1_PDT001742253.1' already exists. Skipping...
Folder 'GCA_033502715.1_PDT001742249.1' already exists. Skipping...
Folder 'GCA_033502775.1_PDT001742244.1' already exists. Skipping...
Folder 'GCA_033502815.1_PDT001742241.1' already exists. Skipping...
Folder 'GCA_033505135.1_PDT001741846.1' already exists. Skipping...
Folder 'GCA_033505155.1_PDT001741839.1' already exists. Skipping...
Folder 'GCA_033505355.1_PDT001741819.1' already exists. Skipping...
Folder 'GCA_033505515.1_PDT001741783.1' already exists. Skipping...
Folder 'GCA_033505735.1_PDT001741735.1' already exists. Skipping...
Folder 'GCA_033505855.1_PDT001741711.1' already exists. Skipping...
Folder 'GCA_033505895.1_PDT001741714.1' already exists. Skipping...
Folder 'GCA_033505975.1_PDT001741704.1' already exists. Skipping...
Folder 'GCA_033505995.1_PDT001741705.1' already exists. Skipping...
Folder 'GCA_033506035.1_PDT001741690.1' already exists. Skipping...
Folder 'GCA_033506075.1_PDT001741688.1' already exists. Skipping...
Folder 'GCA_033506115.1_PDT001741683.1' already exists. Skipping...
Folder 'GCA_033506135.1_PDT001741679.1' already exists. Skipping...
Folder 'GCA_033506155.1_PDT001741677.1' already exists. Skipping...
Folder 'GCA_033506175.1_PDT001741675.1' already exists. Skipping...
Folder 'GCA_033506195.1_PDT001741674.1' already exists. Skipping...
Folder 'GCA_033506255.1_PDT001741670.1' already exists. Skipping...
Folder 'GCA_033506295.1_PDT001741673.1' already exists. Skipping...
Folder 'GCA_033506315.1_PDT001741669.1' already exists. Skipping...
Folder 'GCA_033506335.1_PDT001741671.1' already exists. Skipping...
Folder 'GCA_033506395.1_PDT001741639.1' already exists. Skipping...
Folder 'GCA_033506415.1_PDT001741636.1' already exists. Skipping...
Folder 'GCA_033506435.1_PDT001741638.1' already exists. Skipping...
Folder 'GCA_033506455.1_PDT001741634.1' already exists. Skipping...
Folder 'GCA_033506555.1_PDT001741621.1' already exists. Skipping...
Folder 'GCA_033506615.1_PDT001741610.1' already exists. Skipping...
Folder 'GCA_033506635.1_PDT001741612.1' already exists. Skipping...
Folder 'GCA_033506675.1_PDT001741607.1' already exists. Skipping...
Folder 'GCA_033506715.1_PDT001741606.1' already exists. Skipping...
Folder 'GCA_033506775.1_PDT001741604.1' already exists. Skipping...
Folder 'GCA_033506875.1_PDT001741589.1' already exists. Skipping...
Folder 'GCA_033506915.1_PDT001741586.1' already exists. Skipping...
Folder 'GCA_033506935.1_PDT001741584.1' already exists. Skipping...
Folder 'GCA_033506975.1_PDT001741583.1' already exists. Skipping...
Folder 'GCA_033507035.1_PDT001741558.1' already exists. Skipping...
Folder 'GCA_033507055.1_PDT001741545.1' already exists. Skipping...
Folder 'GCA_033507075.1_PDT001741565.1' already exists. Skipping...
Folder 'GCA_033507135.1_PDT001741537.1' already exists. Skipping...
Folder 'GCA_033507155.1_PDT001741539.1' already exists. Skipping...
Folder 'GCA_033507175.1_PDT001741538.1' already exists. Skipping...
Folder 'GCA_033507235.1_PDT001741532.1' already exists. Skipping...
Folder 'GCA_033507275.1_PDT001741530.1' already exists. Skipping...
Folder 'GCA_033507335.1_PDT001741525.1' already exists. Skipping...
Folder 'GCA_033507435.1_PDT001741514.1' already exists. Skipping...
Folder 'GCA_033507455.1_PDT001741509.1' already exists. Skipping...
Folder 'GCA_033507555.1_PDT001741496.1' already exists. Skipping...
Folder 'GCA_033507575.1_PDT001741494.1' already exists. Skipping...
Folder 'GCA_033507615.1_PDT001741493.1' already exists. Skipping...
Folder 'GCA_033507655.1_PDT001741490.1' already exists. Skipping...
Folder 'GCA_033507675.1_PDT001741489.1' already exists. Skipping...
Folder 'GCA_033507995.1_PDT001741002.1' already exists. Skipping...
Folder 'GCA_033508075.1_PDT001740998.1' already exists. Skipping...
Folder 'GCA_033508115.1_PDT001740996.1' already exists. Skipping...
Folder 'GCA_033508155.1_PDT001740995.1' already exists. Skipping...
Folder 'GCA_033508195.1_PDT001740993.1' already exists. Skipping...
Folder 'GCA_033508275.1_PDT001740988.1' already exists. Skipping...
Folder 'GCA_033508395.1_PDT001740983.1' already exists. Skipping...
Folder 'GCA_033508575.1_PDT001740971.1' already exists. Skipping...
Folder 'GCA_033510375.1_PDT001740863.1' already exists. Skipping...
Folder 'GCA_033510895.1_PDT001740834.1' already exists. Skipping...
Folder 'GCA_033510955.1_PDT001740831.1' already exists. Skipping...
Folder 'GCA_033511055.1_PDT001740824.1' already exists. Skipping...
Folder 'GCA_033511115.1_PDT001740822.1' already exists. Skipping...
Folder 'GCA_033511235.1_PDT001740814.1' already exists. Skipping...
Folder 'GCA_033511385.1_PDT001740809.1' already exists. Skipping...
Folder 'GCA_033511455.1_PDT001740804.1' already exists. Skipping...
Folder 'GCA_033512275.1_PDT001740759.1' already exists. Skipping...
Folder 'GCA_033512315.1_PDT001740756.1' already exists. Skipping...
Folder 'GCA_033512395.1_PDT001740753.1' already exists. Skipping...
Folder 'GCA_033512495.1_PDT001740747.1' already exists. Skipping...
Folder 'GCA_033512515.1_PDT001740744.1' already exists. Skipping...
Folder 'GCA_033512575.1_PDT001740740.1' already exists. Skipping...
Folder 'GCA_033512715.1_PDT001740734.1' already exists. Skipping...
Folder 'GCA_033512775.1_PDT001740731.1' already exists. Skipping...
Folder 'GCA_033512795.1_PDT001740729.1' already exists. Skipping...
Folder 'GCA_033512975.1_PDT001740655.1' already exists. Skipping...
Folder 'GCA_033513155.1_PDT001740647.1' already exists. Skipping...
Folder 'GCA_033513215.1_PDT001740642.1' already exists. Skipping...
Folder 'GCA_033513235.1_PDT001740643.1' already exists. Skipping...
Folder 'GCA_033513255.1_PDT001740641.1' already exists. Skipping...
Folder 'GCA_033514275.1_PDT001740104.1' already exists. Skipping...
Folder 'GCA_033515095.1_PDT001740058.1' already exists. Skipping...
Folder 'GCA_033538155.1_PDT001739788.1' already exists. Skipping...
Folder 'GCA_033572935.1_PDT001741582.1' already exists. Skipping...
Folder 'GCA_033584655.1_PDT001738765.1' already exists. Skipping...
Folder 'GCA_033585995.1_PDT001738616.1' already exists. Skipping...
Folder 'GCA_033586175.1_PDT001738609.1' already exists. Skipping...
Folder 'GCA_033586195.1_PDT001738606.1' already exists. Skipping...
Folder 'GCA_033586355.1_PDT001738598.1' already exists. Skipping...
Folder 'GCA_033586375.1_PDT001738599.1' already exists. Skipping...
Folder 'GCA_033586395.1_PDT001738597.1' already exists. Skipping...
Folder 'GCA_033586515.1_PDT001738592.1' already exists. Skipping...
Folder 'GCA_033586555.1_PDT001738589.1' already exists. Skipping...
Folder 'GCA_033586575.1_PDT001738587.1' already exists. Skipping...
Folder 'GCA_033586615.1_PDT001738585.1' already exists. Skipping...
Folder 'GCA_033586775.1_PDT001738584.1' already exists. Skipping...
Folder 'GCA_033586855.1_PDT001738579.1' already exists. Skipping...
Folder 'GCA_033586865.1_PDT001738576.1' already exists. Skipping...
Folder 'GCA_033586915.1_PDT001738577.1' already exists. Skipping...
Folder 'GCA_033586935.1_PDT001738573.1' already exists. Skipping...
Folder 'GCA_033586955.1_PDT001738574.1' already exists. Skipping...
Folder 'GCA_033586995.1_PDT001738570.1' already exists. Skipping...
Folder 'GCA_033587035.1_PDT001738569.1' already exists. Skipping...
Folder 'GCA_033587055.1_PDT001738567.1' already exists. Skipping...
Folder 'GCA_033587115.1_PDT001738565.1' already exists. Skipping...
Folder 'GCA_033587215.1_PDT001738559.1' already exists. Skipping...
Folder 'GCA_033587275.1_PDT001738556.1' already exists. Skipping...
Folder 'GCA_033587375.1_PDT001738551.1' already exists. Skipping...
Folder 'GCA_033587415.1_PDT001738549.1' already exists. Skipping...
Folder 'GCA_033587455.1_PDT001738547.1' already exists. Skipping...
Folder 'GCA_033587495.1_PDT001738546.1' already exists. Skipping...
Folder 'GCA_033587535.1_PDT001738543.1' already exists. Skipping...
Folder 'GCA_033587545.1_PDT001738542.1' already exists. Skipping...
Folder 'GCA_033587575.1_PDT001738541.1' already exists. Skipping...
Folder 'GCA_033587635.1_PDT001738540.1' already exists. Skipping...
Folder 'GCA_033587675.1_PDT001738539.1' already exists. Skipping...
Folder 'GCA_033587715.1_PDT001738536.1' already exists. Skipping...
Folder 'GCA_033587735.1_PDT001738538.1' already exists. Skipping...
Folder 'GCA_033587755.1_PDT001738537.1' already exists. Skipping...
Folder 'GCA_033587815.1_PDT001738533.1' already exists. Skipping...
Folder 'GCA_033587835.1_PDT001738531.1' already exists. Skipping...
Folder 'GCA_033587855.1_PDT001738532.1' already exists. Skipping...
Folder 'GCA_033587885.1_PDT001738530.1' already exists. Skipping...
Folder 'GCA_033587915.1_PDT001738528.1' already exists. Skipping...
Folder 'GCA_033587955.1_PDT001738525.1' already exists. Skipping...
Folder 'GCA_033587975.1_PDT001738527.1' already exists. Skipping...
Folder 'GCA_033587995.1_PDT001738524.1' already exists. Skipping...
Folder 'GCA_033588015.1_PDT001738522.1' already exists. Skipping...
Folder 'GCA_033588055.1_PDT001738521.1' already exists. Skipping...
Folder 'GCA_033588095.1_PDT001738519.1' already exists. Skipping...
Folder 'GCA_033588135.1_PDT001738517.1' already exists. Skipping...
Folder 'GCA_033588155.1_PDT001738516.1' already exists. Skipping...
Folder 'GCA_033588255.1_PDT001738511.1' already exists. Skipping...
Folder 'GCA_033588275.1_PDT001738509.1' already exists. Skipping...
Folder 'GCA_033588335.1_PDT001738506.1' already exists. Skipping...
Folder 'GCA_033588395.1_PDT001738504.1' already exists. Skipping...
Folder 'GCA_033588415.1_PDT001738503.1' already exists. Skipping...
Folder 'GCA_033588435.1_PDT001738502.1' already exists. Skipping...
Folder 'GCA_033588455.1_PDT001738500.1' already exists. Skipping...
Folder 'GCA_033588475.1_PDT001738501.1' already exists. Skipping...
Folder 'GCA_033588515.1_PDT001738499.1' already exists. Skipping...
Folder 'GCA_033588535.1_PDT001738497.1' already exists. Skipping...
Folder 'GCA_033588555.1_PDT001738496.1' already exists. Skipping...
Folder 'GCA_033588575.1_PDT001738495.1' already exists. Skipping...
Folder 'GCA_033588595.1_PDT001738494.1' already exists. Skipping...
Folder 'GCA_033588615.1_PDT001738493.1' already exists. Skipping...
Folder 'GCA_033588635.1_PDT001738492.1' already exists. Skipping...
Folder 'GCA_033588675.1_PDT001738491.1' already exists. Skipping...
Folder 'GCA_033588715.1_PDT001738488.1' already exists. Skipping...
Folder 'GCA_033588735.1_PDT001738487.1' already exists. Skipping...
Folder 'GCA_033588795.1_PDT001738484.1' already exists. Skipping...
Folder 'GCA_033588835.1_PDT001738482.1' already exists. Skipping...
Folder 'GCA_033588875.1_PDT001738480.1' already exists. Skipping...
Folder 'GCA_033588895.1_PDT001738479.1' already exists. Skipping...
Folder 'GCA_033588915.1_PDT001738478.1' already exists. Skipping...
Folder 'GCA_033588935.1_PDT001738477.1' already exists. Skipping...
Folder 'GCA_033588975.1_PDT001738475.1' already exists. Skipping...
Folder 'GCA_033588995.1_PDT001738474.1' already exists. Skipping...
Folder 'GCA_033589015.1_PDT001738473.1' already exists. Skipping...
Folder 'GCA_033589075.1_PDT001738470.1' already exists. Skipping...
Folder 'GCA_033589095.1_PDT001738471.1' already exists. Skipping...
Folder 'GCA_033589135.1_PDT001738466.1' already exists. Skipping...
Folder 'GCA_033589155.1_PDT001738468.1' already exists. Skipping...
Folder 'GCA_033589175.1_PDT001738465.1' already exists. Skipping...
Folder 'GCA_033589195.1_PDT001738463.1' already exists. Skipping...
Folder 'GCA_033589215.1_PDT001738464.1' already exists. Skipping...
Folder 'GCA_033589235.1_PDT001738462.1' already exists. Skipping...
Folder 'GCA_033589275.1_PDT001738461.1' already exists. Skipping...
Folder 'GCA_033589315.1_PDT001738456.1' already exists. Skipping...
Folder 'GCA_033589395.1_PDT001738457.1' already exists. Skipping...
Folder 'GCA_033589415.1_PDT001738453.1' already exists. Skipping...
Folder 'GCA_033589435.1_PDT001738452.1' already exists. Skipping...
Folder 'GCA_033589455.1_PDT001738451.1' already exists. Skipping...
Folder 'GCA_033589495.1_PDT001738448.1' already exists. Skipping...
Folder 'GCA_033589515.1_PDT001738449.1' already exists. Skipping...
Folder 'GCA_033589535.1_PDT001738447.1' already exists. Skipping...
Folder 'GCA_033589575.1_PDT001738445.1' already exists. Skipping...
Folder 'GCA_033589615.1_PDT001738444.1' already exists. Skipping...
Folder 'GCA_033590415.1_PDT001738443.1' already exists. Skipping...
Folder 'GCA_033590435.1_PDT001738442.1' already exists. Skipping...
Folder 'GCA_033590455.1_PDT001738440.1' already exists. Skipping...
Folder 'GCA_033590495.1_PDT001738438.1' already exists. Skipping...
Folder 'GCA_033590515.1_PDT001738437.1' already exists. Skipping...
Folder 'GCA_033590535.1_PDT001738435.1' already exists. Skipping...
Folder 'GCA_033590575.1_PDT001738434.1' already exists. Skipping...
Folder 'GCA_033590615.1_PDT001738432.1' already exists. Skipping...
Folder 'GCA_033590655.1_PDT001738430.1' already exists. Skipping...
Folder 'GCA_033590735.1_PDT001738426.1' already exists. Skipping...
Folder 'GCA_033590795.1_PDT001738422.1' already exists. Skipping...
Folder 'GCA_033590855.1_PDT001738420.1' already exists. Skipping...
Folder 'GCA_033590895.1_PDT001738418.1' already exists. Skipping...
Folder 'GCA_033590915.1_PDT001738417.1' already exists. Skipping...
Folder 'GCA_033590935.1_PDT001738416.1' already exists. Skipping...
Folder 'GCA_033590975.1_PDT001738414.1' already exists. Skipping...
Folder 'GCA_033591035.1_PDT001738410.1' already exists. Skipping...
Folder 'GCA_033591075.1_PDT001738409.1' already exists. Skipping...
Folder 'GCA_033591115.1_PDT001738408.1' already exists. Skipping...
Folder 'GCA_033591135.1_PDT001738406.1' already exists. Skipping...
Folder 'GCA_033591155.1_PDT001738405.1' already exists. Skipping...
Folder 'GCA_033591255.1_PDT001738399.1' already exists. Skipping...
Folder 'GCA_033591275.1_PDT001738400.1' already exists. Skipping...
Folder 'GCA_033591295.1_PDT001738398.1' already exists. Skipping...
Folder 'GCA_033591335.1_PDT001738397.1' already exists. Skipping...
Folder 'GCA_033591375.1_PDT001738395.1' already exists. Skipping...
Folder 'GCA_033591395.1_PDT001738392.1' already exists. Skipping...
Folder 'GCA_033591415.1_PDT001738393.1' already exists. Skipping...
Folder 'GCA_033591435.1_PDT001738391.1' already exists. Skipping...
Folder 'GCA_033591495.1_PDT001738388.1' already exists. Skipping...
Folder 'GCA_033592035.1_PDT001738387.1' already exists. Skipping...
Folder 'GCA_033592075.1_PDT001738385.1' already exists. Skipping...
Folder 'GCA_033592095.1_PDT001738383.1' already exists. Skipping...
Folder 'GCA_033592175.1_PDT001738381.1' already exists. Skipping...
Folder 'GCA_033592195.1_PDT001738377.1' already exists. Skipping...
Folder 'GCA_033592255.1_PDT001738378.1' already exists. Skipping...
Folder 'GCA_033592275.1_PDT001738374.1' already exists. Skipping...
Folder 'GCA_033592315.1_PDT001738373.1' already exists. Skipping...
Folder 'GCA_033592335.1_PDT001738371.1' already exists. Skipping...
Folder 'GCA_033592355.1_PDT001738372.1' already exists. Skipping...
Folder 'GCA_033592375.1_PDT001738370.1' already exists. Skipping...
Folder 'GCA_033594975.1_PDT001982773.1' already exists. Skipping...
Folder 'GCA_033595515.1_PDT001738366.1' already exists. Skipping...
Folder 'GCA_033595575.1_PDT001738365.1' already exists. Skipping...
Folder 'GCA_033595695.1_PDT001738360.1' already exists. Skipping...
Folder 'GCA_033595735.1_PDT001738358.1' already exists. Skipping...
Folder 'GCA_033595755.1_PDT001738356.1' already exists. Skipping...
Folder 'GCA_033595795.1_PDT001738355.1' already exists. Skipping...
Folder 'GCA_033595815.1_PDT001738354.1' already exists. Skipping...
Folder 'GCA_033595855.1_PDT001738352.1' already exists. Skipping...
Folder 'GCA_033595875.1_PDT001738351.1' already exists. Skipping...
Folder 'GCA_033595915.1_PDT001738349.1' already exists. Skipping...
Folder 'GCA_033595935.1_PDT001738348.1' already exists. Skipping...
Folder 'GCA_033596075.1_PDT001738337.1' already exists. Skipping...
Folder 'GCA_033596095.1_PDT001738338.1' already exists. Skipping...
Folder 'GCA_033596115.1_PDT001738336.1' already exists. Skipping...
Folder 'GCA_033596135.1_PDT001738334.1' already exists. Skipping...
Folder 'GCA_033596225.1_PDT001738327.1' already exists. Skipping...
Folder 'GCA_033596275.1_PDT001738326.1' already exists. Skipping...
Folder 'GCA_033596335.1_PDT001738325.1' already exists. Skipping...
Folder 'GCA_033596375.1_PDT001738322.1' already exists. Skipping...
Folder 'GCA_033596475.1_PDT001738315.1' already exists. Skipping...
Folder 'GCA_033596515.1_PDT001738317.1' already exists. Skipping...
Folder 'GCA_033596575.1_PDT001738310.1' already exists. Skipping...
Folder 'GCA_033596615.1_PDT001738311.1' already exists. Skipping...
Folder 'GCA_033596655.1_PDT001738309.1' already exists. Skipping...
Folder 'GCA_033596695.1_PDT001738307.1' already exists. Skipping...
Folder 'GCA_033596715.1_PDT001738306.1' already exists. Skipping...
Folder 'GCA_033596755.1_PDT001738303.1' already exists. Skipping...
Folder 'GCA_033596775.1_PDT001738301.1' already exists. Skipping...
Folder 'GCA_033596795.1_PDT001738302.1' already exists. Skipping...

Retreiveing data: 32290it [00:06, 6681.61it/s]

Folder 'GCA_036358395.1_PDT002069740.1' already exists. Skipping...
Folder 'GCA_036358435.1_PDT002069737.1' already exists. Skipping...
Folder 'GCA_036400815.1_PDT002069745.1' already exists. Skipping...
Folder 'GCA_036406855.1_PDT002072138.1' already exists. Skipping...
Folder 'GCA_036406895.1_PDT002072120.1' already exists. Skipping...
Folder 'GCA_036406915.1_PDT002072127.1' already exists. Skipping...
Folder 'GCA_036407375.1_PDT002072160.1' already exists. Skipping...
Folder 'GCA_036407435.1_PDT002072139.1' already exists. Skipping...
Folder 'GCA_036407475.1_PDT002072136.1' already exists. Skipping...
Folder 'GCA_036407495.1_PDT002072135.1' already exists. Skipping...
Folder 'GCA_036407535.1_PDT002072130.1' already exists. Skipping...
Folder 'GCA_036407555.1_PDT002072128.1' already exists. Skipping...
Folder 'GCA_036407835.1_PDT002072145.1' already exists. Skipping...
Folder 'GCA_036408375.1_PDT002072161.1' already exists. Skipping...
Folder 'GCA_036408435.1_PDT002072155.1' already exists. Skipping...
Folder 'GCA_036408455.1_PDT002072154.1' already exists. Skipping...
Folder 'GCA_036408595.1_PDT002072143.1' already exists. Skipping...
Folder 'GCA_036408615.1_PDT002072132.1' already exists. Skipping...
Folder 'GCA_036408635.1_PDT002072126.1' already exists. Skipping...
Folder 'GCA_036408655.1_PDT002072131.1' already exists. Skipping...
Folder 'GCA_036408675.1_PDT002072125.1' already exists. Skipping...
Folder 'GCA_036408695.1_PDT002072123.1' already exists. Skipping...
Folder 'GCA_036408715.1_PDT002072122.1' already exists. Skipping...
Folder 'GCA_036410925.1_PDT002072144.1' already exists. Skipping...
Folder 'GCA_036410955.1_PDT002072134.1' already exists. Skipping...
Folder 'GCA_036425455.1_PDT002073403.1' already exists. Skipping...
Folder 'GCA_036425475.1_PDT002073385.1' already exists. Skipping...
Folder 'GCA_036425525.1_PDT002073382.1' already exists. Skipping...
Folder 'GCA_036425755.1_PDT002073282.1' already exists. Skipping...
Folder 'GCA_036426245.1_ASM3642624v1' already exists. Skipping...
Folder 'GCA_036426265.1_ASM3642626v1' already exists. Skipping...
Folder 'GCA_036426285.1_ASM3642628v1' already exists. Skipping...
Folder 'GCA_036426305.1_ASM3642630v1' already exists. Skipping...
Folder 'GCA_036426325.1_ASM3642632v1' already exists. Skipping...
Folder 'GCA_036426365.1_PDT002073409.1' already exists. Skipping...
Folder 'GCA_036426385.1_PDT002073408.1' already exists. Skipping...
Folder 'GCA_036426425.1_PDT002073406.1' already exists. Skipping...
Folder 'GCA_036426465.1_ASM3642646v1' already exists. Skipping...
Folder 'GCA_036426505.1_ASM3642650v1' already exists. Skipping...
Folder 'GCA_036426525.1_PDT002073405.1' already exists. Skipping...
Folder 'GCA_036426545.1_ASM3642654v1' already exists. Skipping...
Folder 'GCA_036426605.1_PDT002073401.1' already exists. Skipping...
Folder 'GCA_036426645.1_ASM3642664v1' already exists. Skipping...
Folder 'GCA_036426665.1_ASM3642666v1' already exists. Skipping...
Folder 'GCA_036426685.1_ASM3642668v1' already exists. Skipping...
Folder 'GCA_036426705.1_ASM3642670v1' already exists. Skipping...
Folder 'GCA_036426725.1_PDT002073395.1' already exists. Skipping...
Folder 'GCA_036426745.1_ASM3642674v1' already exists. Skipping...
Folder 'GCA_036426785.1_PDT002073397.1' already exists. Skipping...
Folder 'GCA_036426825.1_ASM3642682v1' already exists. Skipping...
Folder 'GCA_036426845.1_PDT002073393.1' already exists. Skipping...
Folder 'GCA_036426865.1_ASM3642686v1' already exists. Skipping...
Folder 'GCA_036426885.1_ASM3642688v1' already exists. Skipping...
Folder 'GCA_036426905.1_ASM3642690v1' already exists. Skipping...
Folder 'GCA_036426935.1_PDT002073389.1' already exists. Skipping...
Folder 'GCA_036426965.1_PDT002073390.1' already exists. Skipping...
Folder 'GCA_036426985.1_PDT002073387.1' already exists. Skipping...
Folder 'GCA_036427005.1_ASM3642700v1' already exists. Skipping...
Folder 'GCA_036427025.1_PDT002073388.1' already exists. Skipping...
Folder 'GCA_036427045.1_ASM3642704v1' already exists. Skipping...
Folder 'GCA_036427065.1_ASM3642706v1' already exists. Skipping...
Folder 'GCA_036427085.1_ASM3642708v1' already exists. Skipping...
Folder 'GCA_036427105.1_ASM3642710v1' already exists. Skipping...
Folder 'GCA_036427145.1_ASM3642714v1' already exists. Skipping...
Folder 'GCA_036427185.1_ASM3642718v1' already exists. Skipping...
Folder 'GCA_036427205.1_PDT002073383.1' already exists. Skipping...
Folder 'GCA_036427225.1_ASM3642722v1' already exists. Skipping...
Folder 'GCA_036427265.1_PDT002073380.1' already exists. Skipping...
Folder 'GCA_036427285.1_ASM3642728v1' already exists. Skipping...
Folder 'GCA_036427305.1_ASM3642730v1' already exists. Skipping...
Folder 'GCA_036427345.1_ASM3642734v1' already exists. Skipping...
Folder 'GCA_036427385.1_ASM3642738v1' already exists. Skipping...
Folder 'GCA_036427405.1_ASM3642740v1' already exists. Skipping...
Folder 'GCA_036427465.1_ASM3642746v1' already exists. Skipping...
Folder 'GCA_036427495.1_ASM3642749v1' already exists. Skipping...
Folder 'GCA_036427545.1_ASM3642754v1' already exists. Skipping...
Folder 'GCA_036427585.1_ASM3642758v1' already exists. Skipping...
Folder 'GCA_036427625.1_PDT002073285.1' already exists. Skipping...
Folder 'GCA_036427645.1_ASM3642764v1' already exists. Skipping...
Folder 'GCA_036427685.1_ASM3642768v1' already exists. Skipping...
Folder 'GCA_036427705.1_ASM3642770v1' already exists. Skipping...
Folder 'GCA_036427725.1_ASM3642772v1' already exists. Skipping...
Folder 'GCA_036427825.1_ASM3642782v1' already exists. Skipping...
Folder 'GCA_036427845.1_ASM3642784v1' already exists. Skipping...
Folder 'GCA_036427865.1_ASM3642786v1' already exists. Skipping...
Folder 'GCA_036427885.1_ASM3642788v1' already exists. Skipping...
Folder 'GCA_036427905.1_ASM3642790v1' already exists. Skipping...
Folder 'GCA_036427925.1_ASM3642792v1' already exists. Skipping...
Folder 'GCA_036427945.1_ASM3642794v1' already exists. Skipping...
Folder 'GCA_036427965.1_ASM3642796v1' already exists. Skipping...
Folder 'GCA_036427985.1_ASM3642798v1' already exists. Skipping...
Folder 'GCA_036428005.1_ASM3642800v1' already exists. Skipping...
Folder 'GCA_036428025.1_ASM3642802v1' already exists. Skipping...
Folder 'GCA_036428065.1_ASM3642806v1' already exists. Skipping...
Folder 'GCA_036428085.1_ASM3642808v1' already exists. Skipping...
Folder 'GCA_036428105.1_ASM3642810v1' already exists. Skipping...
Folder 'GCA_036428125.1_ASM3642812v1' already exists. Skipping...
Folder 'GCA_036428545.1_PDT002073399.1' already exists. Skipping...
Folder 'GCA_036428565.1_PDT002073402.1' already exists. Skipping...
Folder 'GCA_036429555.1_PDT002073391.1' already exists. Skipping...
Folder 'GCA_036439815.1_PDT002071254.1' already exists. Skipping...
Folder 'GCA_036440235.1_PDT002071228.1' already exists. Skipping...
Folder 'GCA_036455825.1_PDT002071225.1' already exists. Skipping...
Folder 'GCA_036455925.1_PDT002071223.1' already exists. Skipping...
Folder 'GCA_036455945.1_PDT002071222.1' already exists. Skipping...
Folder 'GCA_036455985.1_PDT002071219.1' already exists. Skipping...
Folder 'GCA_036456005.1_PDT002071218.1' already exists. Skipping...
Folder 'GCA_036456025.1_PDT002071215.1' already exists. Skipping...
Folder 'GCA_036456105.1_PDT002071212.1' already exists. Skipping...
Folder 'GCA_036456125.1_PDT002071213.1' already exists. Skipping...
Folder 'GCA_036456145.1_PDT002071211.1' already exists. Skipping...
Folder 'GCA_036456185.1_PDT002071209.1' already exists. Skipping...
Folder 'GCA_036456205.1_PDT002071206.1' already exists. Skipping...
Folder 'GCA_036456225.1_PDT002071208.1' already exists. Skipping...
Folder 'GCA_036456245.1_PDT002071207.1' already exists. Skipping...
Folder 'GCA_036456285.1_PDT002071202.1' already exists. Skipping...
Folder 'GCA_036456325.1_PDT002071204.1' already exists. Skipping...
Folder 'GCA_036456365.1_PDT002071200.1' already exists. Skipping...
Folder 'GCA_036456425.1_PDT002071196.1' already exists. Skipping...
Folder 'GCA_036457685.1_PDT002070691.1' already exists. Skipping...
Folder 'GCA_036459525.1_PDT002070577.1' already exists. Skipping...
Folder 'GCA_036459585.1_PDT002070575.1' already exists. Skipping...
Folder 'GCA_036478555.1_PDT002067321.1' already exists. Skipping...
Folder 'GCA_036483315.1_PDT002067158.1' already exists. Skipping...
Folder 'GCA_036483395.1_PDT002067153.1' already exists. Skipping...
Folder 'GCA_036483545.1_PDT002067142.1' already exists. Skipping...
Folder 'GCA_036483735.1_PDT002067131.1' already exists. Skipping...
Folder 'GCA_036483775.1_PDT002067128.1' already exists. Skipping...
Folder 'GCA_036483795.1_PDT002067127.1' already exists. Skipping...
Folder 'GCA_036483815.1_PDT002067130.1' already exists. Skipping...
Folder 'GCA_036483935.1_PDT002067120.1' already exists. Skipping...
Folder 'GCA_036483955.1_PDT002067118.1' already exists. Skipping...
Folder 'GCA_036484015.1_PDT002067116.1' already exists. Skipping...
Folder 'GCA_036512195.1_PDT002074434.1' already exists. Skipping...
Folder 'GCA_036512225.1_PDT002074435.1' already exists. Skipping...
Folder 'GCA_036512265.1_PDT002074436.1' already exists. Skipping...
Folder 'GCA_036523215.1_PDT002074484.1' already exists. Skipping...
Folder 'GCA_036567035.1_PDT002076363.1' already exists. Skipping...
Folder 'GCA_036571025.1_PDT002076453.1' already exists. Skipping...
Folder 'GCA_036571125.1_PDT002076437.1' already exists. Skipping...
Folder 'GCA_036571225.1_PDT002076425.1' already exists. Skipping...
Folder 'GCA_036571405.1_PDT002076465.1' already exists. Skipping...
Folder 'GCA_036571425.1_PDT002076435.1' already exists. Skipping...
Folder 'GCA_036571485.1_PDT002076423.1' already exists. Skipping...
Folder 'GCA_036571505.1_PDT002076418.1' already exists. Skipping...
Folder 'GCA_036571525.1_PDT002076419.1' already exists. Skipping...
Folder 'GCA_036571545.1_PDT002076415.1' already exists. Skipping...
Folder 'GCA_036571565.1_PDT002076414.1' already exists. Skipping...
Folder 'GCA_036571625.1_PDT002076469.1' already exists. Skipping...
Folder 'GCA_036571665.1_PDT002076468.1' already exists. Skipping...
Folder 'GCA_036571685.1_PDT002076416.1' already exists. Skipping...
Folder 'GCA_036571835.1_PDT002076420.1' already exists. Skipping...
Folder 'GCA_036572195.1_PDT002076422.1' already exists. Skipping...
Folder 'GCA_036575395.1_PDT002077042.1' already exists. Skipping...
Folder 'GCA_036575525.1_PDT002076986.1' already exists. Skipping...
Folder 'GCA_036575745.1_PDT002076949.1' already exists. Skipping...
Folder 'GCA_036624285.1_PDT002078359.1' already exists. Skipping...
Folder 'GCA_036624815.1_PDT002078383.1' already exists. Skipping...
Folder 'GCA_036624835.1_PDT002078416.1' already exists. Skipping...
Folder 'GCA_036624915.1_PDT002078378.1' already exists. Skipping...
Folder 'GCA_036630825.1_PDT002080286.1' already exists. Skipping...
Folder 'GCA_036630855.1_PDT002080283.1' already exists. Skipping...
Folder 'GCA_036630875.1_PDT002080280.1' already exists. Skipping...
Folder 'GCA_036630895.1_PDT002080279.1' already exists. Skipping...
Folder 'GCA_036630995.1_PDT002080273.1' already exists. Skipping...
Folder 'GCA_036631355.1_PDT002080282.1' already exists. Skipping...
Folder 'GCA_036633095.1_PDT002080285.1' already exists. Skipping...
Folder 'GCA_036668775.1_PDT002080316.1' already exists. Skipping...
Folder 'GCA_036668795.1_PDT002080317.1' already exists. Skipping...
Folder 'GCA_036668855.1_PDT002080315.1' already exists. Skipping...
Folder 'GCA_036674225.1_PDT002079963.1' already exists. Skipping...
Folder 'GCA_036679925.1_PDT002080401.1' already exists. Skipping...
Folder 'GCA_036684925.1_PDT002080897.1' already exists. Skipping...
Folder 'GCA_036684945.1_PDT002080894.1' already exists. Skipping...
Folder 'GCA_036684965.1_PDT002080898.1' already exists. Skipping...
Folder 'GCA_036684985.1_PDT002080896.1' already exists. Skipping...
Folder 'GCA_036685005.1_PDT002080893.1' already exists. Skipping...
Folder 'GCA_036685065.1_PDT002080866.1' already exists. Skipping...
Folder 'GCA_036685165.1_PDT002080858.1' already exists. Skipping...
Folder 'GCA_036685185.1_PDT002080859.1' already exists. Skipping...
Folder 'GCA_036685205.1_PDT002080860.1' already exists. Skipping...
Folder 'GCA_036685265.1_PDT002080845.1' already exists. Skipping...
Folder 'GCA_036685305.1_PDT002080844.1' already exists. Skipping...
Folder 'GCA_036685345.1_PDT002080841.1' already exists. Skipping...
Folder 'GCA_036685365.1_PDT002080839.1' already exists. Skipping...
Folder 'GCA_036685385.1_PDT002080840.1' already exists. Skipping...
Folder 'GCA_036685405.1_PDT002080834.1' already exists. Skipping...
Folder 'GCA_036685425.1_PDT002080831.1' already exists. Skipping...
Folder 'GCA_036685445.1_PDT002080830.1' already exists. Skipping...
Folder 'GCA_036685505.1_PDT002080827.1' already exists. Skipping...
Folder 'GCA_036685525.1_PDT002080825.1' already exists. Skipping...
Folder 'GCA_036685585.1_PDT002080793.1' already exists. Skipping...
Folder 'GCA_036685645.1_PDT002080783.1' already exists. Skipping...
Folder 'GCA_036685705.1_PDT002080820.1' already exists. Skipping...
Folder 'GCA_036685725.1_PDT002080836.1' already exists. Skipping...
Folder 'GCA_036685765.1_PDT002080851.1' already exists. Skipping...
Folder 'GCA_036686045.1_PDT002080853.1' already exists. Skipping...
Folder 'GCA_036686085.1_PDT002080848.1' already exists. Skipping...
Folder 'GCA_036690765.1_PDT002082099.1' already exists. Skipping...
Folder 'GCA_036712115.1_PDT002082582.1' already exists. Skipping...
Folder 'GCA_036715515.1_PDT002082822.1' already exists. Skipping...
Folder 'GCA_036716395.1_PDT002082410.1' already exists. Skipping...
Folder 'GCA_036717375.1_PDT002082358.1' already exists. Skipping...
Folder 'GCA_036762615.1_PDT002083975.1' already exists. Skipping...
Folder 'GCA_036762655.1_PDT002083977.1' already exists. Skipping...
Folder 'GCA_036762695.1_PDT002083976.1' already exists. Skipping...
Folder 'GCA_036786225.1_PDT002084501.1' already exists. Skipping...
Folder 'GCA_036795755.1_PDT002084506.1' already exists. Skipping...
Folder 'GCA_036797465.1_PDT002084497.1' already exists. Skipping...
Folder 'GCA_036810935.1_PDT002084553.1' already exists. Skipping...
Folder 'GCA_036812765.1_PDT002084626.1' already exists. Skipping...
Folder 'GCA_036854835.1_PDT002085104.1' already exists. Skipping...
Folder 'GCA_036856435.1_PDT002085332.1' already exists. Skipping...
Folder 'GCA_036856455.1_PDT002085333.1' already exists. Skipping...
Folder 'GCA_036868265.1_PDT002085844.1' already exists. Skipping...
Folder 'GCA_036868325.1_PDT002085841.1' already exists. Skipping...
Folder 'GCA_036868345.1_PDT002085840.1' already exists. Skipping...
Folder 'GCA_036868365.1_PDT002085839.1' already exists. Skipping...
Folder 'GCA_036868385.1_PDT002085838.1' already exists. Skipping...
Folder 'GCA_036868445.1_PDT002085835.1' already exists. Skipping...
Folder 'GCA_036868505.1_PDT002085832.1' already exists. Skipping...
Folder 'GCA_036868525.1_PDT002085831.1' already exists. Skipping...
Folder 'GCA_036868545.1_PDT002085830.1' already exists. Skipping...
Folder 'GCA_036868565.1_PDT002085829.1' already exists. Skipping...
Folder 'GCA_036868625.1_PDT002085827.1' already exists. Skipping...
Folder 'GCA_036868645.1_PDT002085825.1' already exists. Skipping...
Folder 'GCA_036868685.1_PDT002085823.1' already exists. Skipping...
Folder 'GCA_036874105.1_PDT002086587.1' already exists. Skipping...
Folder 'GCA_036886285.1_PDT002089198.1' already exists. Skipping...
Folder 'GCA_036887625.1_PDT002089207.1' already exists. Skipping...
Folder 'GCA_036888865.1_ASM3688886v1' already exists. Skipping...
Folder 'GCA_036888925.1_PDT002089320.1' already exists. Skipping...
Folder 'GCA_036889055.1_ASM3688905v1' already exists. Skipping...
Folder 'GCA_036889345.1_ASM3688934v1' already exists. Skipping...
Folder 'GCA_036889535.1_ASM3688953v1' already exists. Skipping...
Folder 'GCA_036890805.1_PDT002089325.1' already exists. Skipping...
Folder 'GCA_036925035.1_PDT002091837.1' already exists. Skipping...
Folder 'GCA_036925175.1_PDT002091845.1' already exists. Skipping...
Folder 'GCA_036925895.1_PDT002091943.1' already exists. Skipping...
Folder 'GCA_036926355.1_PDT002091949.1' already exists. Skipping...
Folder 'GCA_036926445.1_PDT002091944.1' already exists. Skipping...
Folder 'GCA_036926465.1_PDT002091942.1' already exists. Skipping...
Folder 'GCA_036940365.1_ASM3694036v1' already exists. Skipping...
Folder 'GCA_036940375.1_ASM3694037v1' already exists. Skipping...
Folder 'GCA_036940765.1_PDT002094160.1' already exists. Skipping...
Folder 'GCA_036944805.1_PDT002094870.1' already exists. Skipping...
Folder 'GCA_036944845.1_PDT002094869.1' already exists. Skipping...
Folder 'GCA_036944885.1_PDT002094842.1' already exists. Skipping...
Folder 'GCA_036944905.1_PDT002094836.1' already exists. Skipping...
Folder 'GCA_036944945.1_PDT002094834.1' already exists. Skipping...
Folder 'GCA_036944965.1_PDT002094827.1' already exists. Skipping...
Folder 'GCA_036945005.1_PDT002094823.1' already exists. Skipping...
Folder 'GCA_036945045.1_PDT002094824.1' already exists. Skipping...
Folder 'GCA_036967495.1_PDT002094871.1' already exists. Skipping...
Folder 'GCA_036967515.1_PDT002094868.1' already exists. Skipping...
Folder 'GCA_036967555.1_PDT002094867.1' already exists. Skipping...
Folder 'GCA_036967775.1_PDT002094852.1' already exists. Skipping...
Folder 'GCA_036967795.1_PDT002094851.1' already exists. Skipping...
Folder 'GCA_036967895.1_PDT002094846.1' already exists. Skipping...
Folder 'GCA_036967975.1_PDT002094838.1' already exists. Skipping...
Folder 'GCA_036967995.1_PDT002094837.1' already exists. Skipping...
Folder 'GCA_036968055.1_PDT002094832.1' already exists. Skipping...
Folder 'GCA_036968075.1_PDT002094829.1' already exists. Skipping...
Folder 'GCA_036968115.1_PDT002094828.1' already exists. Skipping...
Folder 'GCA_036968415.1_PDT002096899.1' already exists. Skipping...
Folder 'GCA_036968455.1_PDT002096896.1' already exists. Skipping...
Folder 'GCA_036968655.1_PDT002096885.1' already exists. Skipping...
Folder 'GCA_036968675.1_PDT002096883.1' already exists. Skipping...
Folder 'GCA_036968695.1_PDT002096882.1' already exists. Skipping...
Folder 'GCA_036969405.1_PDT002096901.1' already exists. Skipping...
Folder 'GCA_037009525.1_PDT002097962.1' already exists. Skipping...
Folder 'GCA_037009645.1_PDT002097958.1' already exists. Skipping...
Folder 'GCA_037009785.1_PDT002097952.1' already exists. Skipping...
Folder 'GCA_037039455.1_PDT002099658.1' already exists. Skipping...
Folder 'GCA_037055945.1_PDT002100503.1' already exists. Skipping...
Folder 'GCA_037062055.1_PDT002100933.1' already exists. Skipping...
Folder 'GCA_037072245.1_PDT002101120.1' already exists. Skipping...
Folder 'GCA_037076995.1_PDT002102829.1' already exists. Skipping...
Folder 'GCA_037077015.1_PDT002102828.1' already exists. Skipping...
Folder 'GCA_037078375.1_PDT002102830.1' already exists. Skipping...
Folder 'GCA_037102425.1_PDT002107456.1' already exists. Skipping...
Folder 'GCA_037109935.1_PDT002109159.1' already exists. Skipping...
Folder 'GCA_037109955.1_PDT002109158.1' already exists. Skipping...
Folder 'GCA_037109975.1_PDT002109157.1' already exists. Skipping...
Folder 'GCA_037110005.1_PDT002109161.1' already exists. Skipping...
Folder 'GCA_037110035.1_PDT002109156.1' already exists. Skipping...
Folder 'GCA_037110115.1_PDT002109152.1' already exists. Skipping...
Folder 'GCA_037110235.1_PDT002109146.1' already exists. Skipping...
Folder 'GCA_037110535.1_PDT002109145.1' already exists. Skipping...
Folder 'GCA_037110735.1_PDT002109135.1' already exists. Skipping...
Folder 'GCA_037110795.1_PDT002109133.1' already exists. Skipping...
Folder 'GCA_037110855.1_PDT002109130.1' already exists. Skipping...
Folder 'GCA_037111015.1_PDT002109119.1' already exists. Skipping...
Folder 'GCA_037111215.1_PDT002109093.1' already exists. Skipping...
Folder 'GCA_037122565.1_PDT002111012.1' already exists. Skipping...

Retreiveing data: 33631it [00:06, 6688.28it/s]

Folder 'GCA_041212415.1_PDT002310530.1' already exists. Skipping...
Folder 'GCA_041212435.1_PDT002310529.1' already exists. Skipping...
Folder 'GCA_041212595.1_PDT002310520.1' already exists. Skipping...
Folder 'GCA_041212615.1_PDT002310521.1' already exists. Skipping...
Folder 'GCA_041212635.1_PDT002310519.1' already exists. Skipping...
Folder 'GCA_041212675.1_PDT002310518.1' already exists. Skipping...
Folder 'GCA_041212735.1_PDT002310515.1' already exists. Skipping...
Folder 'GCA_041218035.1_PDT002306291.1' already exists. Skipping...
Folder 'GCA_041219455.1_PDT002305925.1' already exists. Skipping...
Folder 'GCA_041219795.1_PDT002304884.1' already exists. Skipping...
Folder 'GCA_041219815.1_PDT002304886.1' already exists. Skipping...
Folder 'GCA_041269765.1_PDT002316475.1' already exists. Skipping...
Folder 'GCA_041276045.1_PDT002316325.1' already exists. Skipping...
Folder 'GCA_041279405.1_PDT002319097.1' already exists. Skipping...
Folder 'GCA_041301575.1_PDT002324338.1' already exists. Skipping...
Folder 'GCA_041301655.1_PDT002324339.1' already exists. Skipping...
Folder 'GCA_041312005.1_PDT002324690.1' already exists. Skipping...
Folder 'GCA_041316265.1_PDT002325239.1' already exists. Skipping...
Folder 'GCA_041316295.1_PDT002325277.1' already exists. Skipping...
Folder 'GCA_041316415.1_PDT002325267.1' already exists. Skipping...
Folder 'GCA_041316485.1_PDT002325252.1' already exists. Skipping...
Folder 'GCA_041316495.1_PDT002325248.1' already exists. Skipping...
Folder 'GCA_041316525.1_PDT002325245.1' already exists. Skipping...
Folder 'GCA_041316545.1_PDT002325244.1' already exists. Skipping...
Folder 'GCA_041316575.1_PDT002325235.1' already exists. Skipping...
Folder 'GCA_041316715.1_PDT002325238.1' already exists. Skipping...
Folder 'GCA_041318105.1_PDT002325265.1' already exists. Skipping...
Folder 'GCA_041318145.1_PDT002325250.1' already exists. Skipping...
Folder 'GCA_041320335.1_PDT002325606.1' already exists. Skipping...
Folder 'GCA_041339315.1_PDT002326049.1' already exists. Skipping...
Folder 'GCA_041339355.1_PDT002326047.1' already exists. Skipping...
Folder 'GCA_041339515.1_PDT002326038.1' already exists. Skipping...
Folder 'GCA_041339535.1_PDT002326039.1' already exists. Skipping...
Folder 'GCA_041339575.1_PDT002326037.1' already exists. Skipping...
Folder 'GCA_041339755.1_PDT002326026.1' already exists. Skipping...
Folder 'GCA_041339875.1_PDT002326019.1' already exists. Skipping...
Folder 'GCA_041339885.1_PDT002326021.1' already exists. Skipping...
Folder 'GCA_041339975.1_PDT002326015.1' already exists. Skipping...
Folder 'GCA_041340035.1_PDT002326013.1' already exists. Skipping...
Folder 'GCA_041340095.1_PDT002326007.1' already exists. Skipping...
Folder 'GCA_041340115.1_PDT002326010.1' already exists. Skipping...
Folder 'GCA_041340175.1_PDT002326003.1' already exists. Skipping...
Folder 'GCA_041340235.1_PDT002326002.1' already exists. Skipping...
Folder 'GCA_041341535.1_PDT002325736.1' already exists. Skipping...
Folder 'GCA_041383785.1_PDT002331013.1' already exists. Skipping...
Folder 'GCA_041412695.1_PDT002333375.1' already exists. Skipping...
Folder 'GCA_041434055.1_PDT002334149.1' already exists. Skipping...
Folder 'GCA_041434075.1_PDT002334144.1' already exists. Skipping...
Folder 'GCA_041434095.1_PDT002334159.1' already exists. Skipping...
Folder 'GCA_041434175.1_PDT002334148.1' already exists. Skipping...
Folder 'GCA_041434195.1_PDT002334158.1' already exists. Skipping...
Folder 'GCA_041434215.1_PDT002334139.1' already exists. Skipping...
Folder 'GCA_041434235.1_PDT002334161.1' already exists. Skipping...
Folder 'GCA_041434255.1_PDT002334160.1' already exists. Skipping...
Folder 'GCA_041434275.1_PDT002334155.1' already exists. Skipping...
Folder 'GCA_041434295.1_PDT002334157.1' already exists. Skipping...
Folder 'GCA_041434315.1_PDT002334154.1' already exists. Skipping...
Folder 'GCA_041434335.1_PDT002334156.1' already exists. Skipping...
Folder 'GCA_041434355.1_PDT002334153.1' already exists. Skipping...
Folder 'GCA_041434375.1_PDT002334152.1' already exists. Skipping...
Folder 'GCA_041434395.1_PDT002334151.1' already exists. Skipping...
Folder 'GCA_041434415.1_PDT002334145.1' already exists. Skipping...
Folder 'GCA_041434435.1_PDT002334143.1' already exists. Skipping...
Folder 'GCA_041434455.1_PDT002334142.1' already exists. Skipping...
Folder 'GCA_041434475.1_PDT002334146.1' already exists. Skipping...
Folder 'GCA_041434495.1_PDT002334135.1' already exists. Skipping...
Folder 'GCA_041434515.1_PDT002334141.1' already exists. Skipping...
Folder 'GCA_041434535.1_PDT002334138.1' already exists. Skipping...
Folder 'GCA_041434555.1_PDT002334147.1' already exists. Skipping...
Folder 'GCA_041434575.1_PDT002334136.1' already exists. Skipping...
Folder 'GCA_041434595.1_PDT002334133.1' already exists. Skipping...
Folder 'GCA_041434615.1_PDT002334137.1' already exists. Skipping...
Folder 'GCA_041434635.1_PDT002334140.1' already exists. Skipping...
Folder 'GCA_041434655.1_PDT002334134.1' already exists. Skipping...
Folder 'GCA_041434675.1_PDT002334162.1' already exists. Skipping...
Folder 'GCA_041437375.1_PDT002335427.1' already exists. Skipping...
Folder 'GCA_041502145.1_PDT002341065.1' already exists. Skipping...
Folder 'GCA_041519435.1_PDT002342385.1' already exists. Skipping...
Folder 'GCA_041519655.1_PDT002342399.1' already exists. Skipping...
Folder 'GCA_041519695.1_PDT002342452.1' already exists. Skipping...
Folder 'GCA_041519735.1_PDT002342413.1' already exists. Skipping...
Folder 'GCA_041521485.1_PDT002342426.1' already exists. Skipping...
Folder 'GCA_041521845.1_PDT002342402.1' already exists. Skipping...
Folder 'GCA_041531805.1_PDT002342987.1' already exists. Skipping...
Folder 'GCA_041539655.1_PDT002343206.1' already exists. Skipping...
Folder 'GCA_041539675.1_PDT002343209.1' already exists. Skipping...
Folder 'GCA_041539695.1_PDT002343207.1' already exists. Skipping...
Folder 'GCA_041540735.1_PDT002343180.1' already exists. Skipping...
Folder 'GCA_041540915.1_PDT002343171.1' already exists. Skipping...
Folder 'GCA_041541155.1_PDT002343163.1' already exists. Skipping...
Folder 'GCA_041606775.1_PDT002344953.1' already exists. Skipping...
Folder 'GCA_041606815.1_PDT002344950.1' already exists. Skipping...
Folder 'GCA_041609495.1_PDT002344976.1' already exists. Skipping...
Folder 'GCA_041612275.1_PDT002344949.1' already exists. Skipping...
Folder 'GCA_041627955.1_PDT002344974.1' already exists. Skipping...
Folder 'GCA_041697055.1_PDT002345769.1' already exists. Skipping...
Folder 'GCA_041717265.1_PDT002346646.1' already exists. Skipping...
Folder 'GCA_041717285.1_PDT002346643.1' already exists. Skipping...
Folder 'GCA_041717385.1_PDT002346640.1' already exists. Skipping...
Folder 'GCA_041717405.1_PDT002346638.1' already exists. Skipping...
Folder 'GCA_041717545.1_PDT002346632.1' already exists. Skipping...
Folder 'GCA_041723925.1_PDT002352010.1' already exists. Skipping...
Folder 'GCA_041723965.1_PDT002352009.1' already exists. Skipping...
Folder 'GCA_041724145.1_PDT002351999.1' already exists. Skipping...
Folder 'GCA_041728645.1_PDT002352025.1' already exists. Skipping...
Folder 'GCA_041729005.1_PDT002352031.1' already exists. Skipping...
Folder 'GCA_041729225.1_PDT002352021.1' already exists. Skipping...
Folder 'GCA_041729775.1_PDT002352215.1' already exists. Skipping...
Folder 'GCA_041731655.1_PDT002361643.1' already exists. Skipping...
Folder 'GCA_041731675.1_PDT002361631.1' already exists. Skipping...
Folder 'GCA_041731695.1_PDT002361860.1' already exists. Skipping...
Folder 'GCA_041731715.1_PDT002361773.1' already exists. Skipping...
Folder 'GCA_041731735.1_PDT002361718.1' already exists. Skipping...
Folder 'GCA_041731815.1_PDT002361636.1' already exists. Skipping...
Folder 'GCA_041732395.1_PDT002361843.1' already exists. Skipping...
Folder 'GCA_041732555.1_PDT002361749.1' already exists. Skipping...
Folder 'GCA_041734275.1_PDT002361947.1' already exists. Skipping...
Folder 'GCA_041734695.1_PDT002361704.1' already exists. Skipping...
Folder 'GCA_041768645.1_PDT002361863.1' already exists. Skipping...
Folder 'GCA_041768805.1_PDT002361856.1' already exists. Skipping...
Folder 'GCA_041769165.1_PDT002361746.1' already exists. Skipping...
Folder 'GCA_041769225.1_PDT002361771.1' already exists. Skipping...
Folder 'GCA_041769815.1_PDT002361632.1' already exists. Skipping...
Folder 'GCA_041771485.1_PDT002364759.1' already exists. Skipping...
Folder 'GCA_041771565.1_PDT002364731.1' already exists. Skipping...
Folder 'GCA_041771625.1_PDT002364727.1' already exists. Skipping...
Folder 'GCA_041771685.1_PDT002364724.1' already exists. Skipping...
Folder 'GCA_041771815.1_PDT002364723.1' already exists. Skipping...
Folder 'GCA_041773615.1_PDT002364773.1' already exists. Skipping...
Folder 'GCA_041774925.1_PDT002364738.1' already exists. Skipping...
Folder 'GCA_041775145.1_PDT002364732.1' already exists. Skipping...
Folder 'GCA_041784705.1_PDT002365100.1' already exists. Skipping...
Folder 'GCA_041790365.1_PDT002361857.1' already exists. Skipping...
Folder 'GCA_041790525.1_PDT002361854.1' already exists. Skipping...
Folder 'GCA_041790645.1_PDT002361844.1' already exists. Skipping...
Folder 'GCA_041790765.1_PDT002361838.1' already exists. Skipping...
Folder 'GCA_041791425.1_PDT002361799.1' already exists. Skipping...
Folder 'GCA_041791975.1_PDT002361750.1' already exists. Skipping...
Folder 'GCA_041792135.1_PDT002361740.1' already exists. Skipping...
Folder 'GCA_041792155.1_PDT002361737.1' already exists. Skipping...
Folder 'GCA_041792395.1_PDT002361703.1' already exists. Skipping...
Folder 'GCA_041793085.1_PDT002361652.1' already exists. Skipping...
Folder 'GCA_041793295.1_PDT002361650.1' already exists. Skipping...
Folder 'GCA_041793415.1_PDT002361640.1' already exists. Skipping...
Folder 'GCA_041793515.1_PDT002361638.1' already exists. Skipping...
Folder 'GCA_041800215.1_PDT002359088.1' already exists. Skipping...
Folder 'GCA_041869345.1_PDT002371102.1' already exists. Skipping...
Folder 'GCA_041869385.1_PDT002371098.1' already exists. Skipping...
Folder 'GCA_041869405.1_PDT002371096.1' already exists. Skipping...
Folder 'GCA_041869425.1_PDT002371097.1' already exists. Skipping...
Folder 'GCA_041869465.1_PDT002371095.1' already exists. Skipping...
Folder 'GCA_041869505.1_PDT002371100.1' already exists. Skipping...
Folder 'GCA_041884725.1_PDT002373550.1' already exists. Skipping...
Folder 'GCA_041884745.1_PDT002373552.1' already exists. Skipping...
Folder 'GCA_041884765.1_PDT002373549.1' already exists. Skipping...
Folder 'GCA_041884825.1_PDT002373544.1' already exists. Skipping...
Folder 'GCA_041884925.1_PDT002373536.1' already exists. Skipping...
Folder 'GCA_041885375.1_PDT002373506.1' already exists. Skipping...
Folder 'GCA_041886375.1_PDT002373395.1' already exists. Skipping...
Folder 'GCA_041889515.1_PDT002344951.1' already exists. Skipping...
Folder 'GCA_041889545.1_PDT002344965.1' already exists. Skipping...
Folder 'GCA_042140535.1_PDT002389386.1' already exists. Skipping...
Folder 'GCA_042140655.1_PDT002389388.1' already exists. Skipping...
Folder 'GCA_042140755.1_PDT002388893.1' already exists. Skipping...
Folder 'GCA_042140775.1_PDT002388892.1' already exists. Skipping...
Folder 'GCA_042140835.1_PDT002388889.1' already exists. Skipping...
Folder 'GCA_042140875.1_PDT002388886.1' already exists. Skipping...
Folder 'GCA_042140895.1_PDT002388887.1' already exists. Skipping...
Folder 'GCA_042140915.1_PDT002388883.1' already exists. Skipping...
Folder 'GCA_042140935.1_PDT002388885.1' already exists. Skipping...
Folder 'GCA_042140955.1_PDT002388881.1' already exists. Skipping...
Folder 'GCA_042140995.1_PDT002388882.1' already exists. Skipping...
Folder 'GCA_042141015.1_PDT002388879.1' already exists. Skipping...
Folder 'GCA_042141025.1_PDT002388878.1' already exists. Skipping...
Folder 'GCA_042141055.1_PDT002388872.1' already exists. Skipping...
Folder 'GCA_042141095.1_PDT002388831.1' already exists. Skipping...
Folder 'GCA_042141245.1_PDT002388884.1' already exists. Skipping...
Folder 'GCA_042142405.1_PDT002388840.1' already exists. Skipping...
Folder 'GCA_042146295.1_PDT002388876.1' already exists. Skipping...
Folder 'GCA_042146355.1_PDT002388873.1' already exists. Skipping...
Folder 'GCA_042146375.1_PDT002388870.1' already exists. Skipping...
Folder 'GCA_042146395.1_PDT002388871.1' already exists. Skipping...
Folder 'GCA_042146495.1_PDT002388861.1' already exists. Skipping...
Folder 'GCA_042146665.1_PDT002388854.1' already exists. Skipping...
Folder 'GCA_042146685.1_PDT002388853.1' already exists. Skipping...
Folder 'GCA_042147125.1_PDT002388847.1' already exists. Skipping...
Folder 'GCA_042147145.1_PDT002388848.1' already exists. Skipping...
Folder 'GCA_042147165.1_PDT002388849.1' already exists. Skipping...
Folder 'GCA_042147185.1_PDT002388843.1' already exists. Skipping...
Folder 'GCA_042147225.1_PDT002388845.1' already exists. Skipping...
Folder 'GCA_042147255.1_PDT002388838.1' already exists. Skipping...
Folder 'GCA_042147575.1_PDT002388819.1' already exists. Skipping...
Folder 'GCA_042147675.1_PDT002388818.1' already exists. Skipping...
Folder 'GCA_042147695.1_PDT002388816.1' already exists. Skipping...
Folder 'GCA_042147715.1_PDT002388817.1' already exists. Skipping...
Folder 'GCA_042150825.1_PDT002390275.1' already exists. Skipping...
Folder 'GCA_042152875.1_PDT002390321.1' already exists. Skipping...
Folder 'GCA_042152915.1_PDT002390319.1' already exists. Skipping...
Folder 'GCA_042152935.1_PDT002390317.1' already exists. Skipping...
Folder 'GCA_042152985.1_PDT002390313.1' already exists. Skipping...
Folder 'GCA_042153005.1_PDT002390314.1' already exists. Skipping...
Folder 'GCA_042153025.1_PDT002390299.1' already exists. Skipping...
Folder 'GCA_042153045.1_PDT002390301.1' already exists. Skipping...
Folder 'GCA_042160615.1_PDT002388228.1' already exists. Skipping...
Folder 'GCA_042160745.1_PDT002388224.1' already exists. Skipping...
Folder 'GCA_042160765.1_PDT002388219.1' already exists. Skipping...
Folder 'GCA_042160805.1_PDT002388222.1' already exists. Skipping...
Folder 'GCA_042160825.1_PDT002388214.1' already exists. Skipping...
Folder 'GCA_042160865.1_PDT002388213.1' already exists. Skipping...
Folder 'GCA_042160885.1_PDT002388216.1' already exists. Skipping...
Folder 'GCA_042160945.1_PDT002388210.1' already exists. Skipping...
Folder 'GCA_042160965.1_PDT002388212.1' already exists. Skipping...
Folder 'GCA_042160985.1_PDT002388209.1' already exists. Skipping...
Folder 'GCA_042161005.1_PDT002388204.1' already exists. Skipping...
Folder 'GCA_042161025.1_PDT002388207.1' already exists. Skipping...
Folder 'GCA_042161065.1_PDT002388206.1' already exists. Skipping...
Folder 'GCA_042161085.1_PDT002388203.1' already exists. Skipping...
Folder 'GCA_042161205.1_PDT002388199.1' already exists. Skipping...
Folder 'GCA_042161245.1_PDT002388197.1' already exists. Skipping...
Folder 'GCA_042161285.1_PDT002388196.1' already exists. Skipping...
Folder 'GCA_042161365.1_PDT002388192.1' already exists. Skipping...
Folder 'GCA_042161385.1_PDT002388187.1' already exists. Skipping...
Folder 'GCA_042161435.1_PDT002388172.1' already exists. Skipping...
Folder 'GCA_042161455.1_PDT002388182.1' already exists. Skipping...
Folder 'GCA_042161535.1_PDT002388176.1' already exists. Skipping...
Folder 'GCA_042161555.1_PDT002388171.1' already exists. Skipping...
Folder 'GCA_042161595.1_PDT002388169.1' already exists. Skipping...
Folder 'GCA_042161655.1_PDT002388162.1' already exists. Skipping...
Folder 'GCA_042161675.1_PDT002388165.1' already exists. Skipping...
Folder 'GCA_042161695.1_PDT002388161.1' already exists. Skipping...
Folder 'GCA_042161735.1_PDT002388160.1' already exists. Skipping...
Folder 'GCA_042161755.1_PDT002388157.1' already exists. Skipping...
Folder 'GCA_042161785.1_PDT002388155.1' already exists. Skipping...
Folder 'GCA_042161835.1_PDT002388156.1' already exists. Skipping...
Folder 'GCA_042161855.1_PDT002388153.1' already exists. Skipping...
Folder 'GCA_042161875.1_PDT002388151.1' already exists. Skipping...
Folder 'GCA_042161955.1_PDT002388147.1' already exists. Skipping...
Folder 'GCA_042163015.1_PDT002388102.1' already exists. Skipping...
Folder 'GCA_042163035.1_PDT002388103.1' already exists. Skipping...
Folder 'GCA_042163055.1_PDT002388101.1' already exists. Skipping...
Folder 'GCA_042164475.1_PDT002387787.1' already exists. Skipping...
Folder 'GCA_042166595.1_PDT002387543.1' already exists. Skipping...
Folder 'GCA_042166955.1_PDT002387472.1' already exists. Skipping...
Folder 'GCA_042168125.1_PDT002387418.1' already exists. Skipping...
Folder 'GCA_042168145.1_PDT002387417.1' already exists. Skipping...
Folder 'GCA_042168165.1_PDT002387416.1' already exists. Skipping...
Folder 'GCA_042168185.1_PDT002387415.1' already exists. Skipping...
Folder 'GCA_042168225.1_PDT002387414.1' already exists. Skipping...
Folder 'GCA_042168305.1_PDT002387410.1' already exists. Skipping...
Folder 'GCA_042168345.1_PDT002390602.1' already exists. Skipping...
Folder 'GCA_042168385.1_PDT002387409.1' already exists. Skipping...
Folder 'GCA_042168445.1_PDT002387406.1' already exists. Skipping...
Folder 'GCA_042168485.1_PDT002387403.1' already exists. Skipping...
Folder 'GCA_042168525.1_PDT002387402.1' already exists. Skipping...
Folder 'GCA_042168585.1_PDT002387399.1' already exists. Skipping...
Folder 'GCA_042168605.1_PDT002387398.1' already exists. Skipping...
Folder 'GCA_042168645.1_PDT002387395.1' already exists. Skipping...
Folder 'GCA_042168665.1_PDT002387394.1' already exists. Skipping...
Folder 'GCA_042168685.1_PDT002387397.1' already exists. Skipping...
Folder 'GCA_042168745.1_PDT002387391.1' already exists. Skipping...
Folder 'GCA_042168805.1_PDT002387390.1' already exists. Skipping...
Folder 'GCA_042168865.1_PDT002387386.1' already exists. Skipping...
Folder 'GCA_042168885.1_PDT002387384.1' already exists. Skipping...
Folder 'GCA_042168905.1_PDT002387381.1' already exists. Skipping...
Folder 'GCA_042168955.1_PDT002387380.1' already exists. Skipping...
Folder 'GCA_042169005.1_PDT002387378.1' already exists. Skipping...
Folder 'GCA_042169025.1_PDT002387376.1' already exists. Skipping...
Folder 'GCA_042169045.1_PDT002387377.1' already exists. Skipping...
Folder 'GCA_042169085.1_PDT002387373.1' already exists. Skipping...
Folder 'GCA_042169105.1_PDT002387371.1' already exists. Skipping...
Folder 'GCA_042169145.1_PDT002387372.1' already exists. Skipping...
Folder 'GCA_042169165.1_PDT002387369.1' already exists. Skipping...
Folder 'GCA_042169185.1_PDT002387370.1' already exists. Skipping...
Folder 'GCA_042169205.1_PDT002387368.1' already exists. Skipping...
Folder 'GCA_042169325.1_PDT002390653.1' already exists. Skipping...
Folder 'GCA_042169385.1_PDT002390643.1' already exists. Skipping...
Folder 'GCA_042169405.1_PDT002390644.1' already exists. Skipping...
Folder 'GCA_042169425.1_PDT002390642.1' already exists. Skipping...
Folder 'GCA_042169465.1_PDT002390636.1' already exists. Skipping...
Folder 'GCA_042169485.1_PDT002390629.1' already exists. Skipping...
Folder 'GCA_042169565.1_PDT002390626.1' already exists. Skipping...
Folder 'GCA_042169585.1_PDT002390625.1' already exists. Skipping...
Folder 'GCA_042169605.1_PDT002390623.1' already exists. Skipping...
Folder 'GCA_042169735.1_PDT002390604.1' already exists. Skipping...
Folder 'GCA_042169765.1_PDT002390601.1' already exists. Skipping...
Folder 'GCA_042169785.1_PDT002390596.1' already exists. Skipping...
Folder 'GCA_042169805.1_PDT002390595.1' already exists. Skipping...
Folder 'GCA_042169825.1_PDT002390594.1' already exists. Skipping...
Folder 'GCA_042169845.1_PDT002390593.1' already exists. Skipping...
Folder 'GCA_042169865.1_PDT002390538.1' already exists. Skipping...
Folder 'GCA_042169925.1_PDT002390590.1' already exists. Skipping...
Folder 'GCA_042169965.1_PDT002390536.1' already exists. Skipping...
Folder 'GCA_042169985.1_PDT002390534.1' already exists. Skipping...
Folder 'GCA_042170005.1_PDT002390535.1' already exists. Skipping...

Retreiveing data: 34967it [00:06, 6663.87it/s]

Folder 'GCA_045301795.1_PDT002485590.1' already exists. Skipping...
Folder 'GCA_045301815.1_PDT002485586.1' already exists. Skipping...
Folder 'GCA_045301835.1_PDT002485584.1' already exists. Skipping...
Folder 'GCA_045314475.1_PDT002493449.1' already exists. Skipping...
Folder 'GCA_045320535.1_PDT002493525.1' already exists. Skipping...
Folder 'GCA_045328475.1_PDT002493634.1' already exists. Skipping...
Folder 'GCA_045335555.1_PDT002493869.1' already exists. Skipping...
Folder 'GCA_045349175.1_PDT002494460.1' already exists. Skipping...
Folder 'GCA_045413895.1_PDT002497481.1' already exists. Skipping...
Folder 'GCA_045443495.1_PDT002497480.1' already exists. Skipping...
Folder 'GCA_045463775.1_PDT002499020.1' already exists. Skipping...
Folder 'GCA_045500795.1_PDT002477701.1' already exists. Skipping...
Folder 'GCA_045505485.1_PDT002503529.1' already exists. Skipping...
Folder 'GCA_045505545.1_PDT002503526.1' already exists. Skipping...
Folder 'GCA_045505605.1_PDT002503523.1' already exists. Skipping...
Folder 'GCA_045505645.1_PDT002503519.1' already exists. Skipping...
Folder 'GCA_045505665.1_PDT002503521.1' already exists. Skipping...
Folder 'GCA_045505685.1_PDT002503520.1' already exists. Skipping...
Folder 'GCA_045505725.1_PDT002503517.1' already exists. Skipping...
Folder 'GCA_045505765.1_PDT002503514.1' already exists. Skipping...
Folder 'GCA_045505845.1_PDT002503511.1' already exists. Skipping...
Folder 'GCA_045505865.1_PDT002503509.1' already exists. Skipping...
Folder 'GCA_045505905.1_PDT002503508.1' already exists. Skipping...
Folder 'GCA_045506085.1_PDT002503497.1' already exists. Skipping...
Folder 'GCA_045506105.1_PDT002503495.1' already exists. Skipping...
Folder 'GCA_045506145.1_PDT002503498.1' already exists. Skipping...
Folder 'GCA_045506165.1_PDT002503494.1' already exists. Skipping...
Folder 'GCA_045506245.1_PDT002503170.1' already exists. Skipping...
Folder 'GCA_045506905.1_PDT002502874.1' already exists. Skipping...
Folder 'GCA_045506945.1_PDT002502872.1' already exists. Skipping...
Folder 'GCA_045506955.1_PDT002502873.1' already exists. Skipping...
Folder 'GCA_045507005.1_PDT002502868.1' already exists. Skipping...
Folder 'GCA_045507025.1_PDT002502869.1' already exists. Skipping...
Folder 'GCA_045507085.1_PDT002502823.1' already exists. Skipping...
Folder 'GCA_045507125.1_PDT002502864.1' already exists. Skipping...
Folder 'GCA_045507165.1_PDT002502861.1' already exists. Skipping...
Folder 'GCA_045507185.1_PDT002502862.1' already exists. Skipping...
Folder 'GCA_045507205.1_PDT002502863.1' already exists. Skipping...
Folder 'GCA_045507325.1_PDT002502824.1' already exists. Skipping...
Folder 'GCA_045507345.1_PDT002502822.1' already exists. Skipping...
Folder 'GCA_045507365.1_PDT002502821.1' already exists. Skipping...
Folder 'GCA_045507385.1_PDT002502818.1' already exists. Skipping...
Folder 'GCA_045507405.1_PDT002502819.1' already exists. Skipping...
Folder 'GCA_045507445.1_PDT002502815.1' already exists. Skipping...
Folder 'GCA_045507465.1_PDT002502816.1' already exists. Skipping...
Folder 'GCA_045507505.1_PDT002502811.1' already exists. Skipping...
Folder 'GCA_045507525.1_PDT002502809.1' already exists. Skipping...
Folder 'GCA_045507545.1_PDT002502810.1' already exists. Skipping...
Folder 'GCA_045507565.1_PDT002502808.1' already exists. Skipping...
Folder 'GCA_045507605.1_PDT002502807.1' already exists. Skipping...
Folder 'GCA_045507625.1_PDT002502805.1' already exists. Skipping...
Folder 'GCA_045507645.1_PDT002502803.1' already exists. Skipping...
Folder 'GCA_045507665.1_PDT002502804.1' already exists. Skipping...
Folder 'GCA_045507705.1_PDT002502802.1' already exists. Skipping...
Folder 'GCA_045507725.1_PDT002502800.1' already exists. Skipping...
Folder 'GCA_045507745.1_PDT002502799.1' already exists. Skipping...
Folder 'GCA_045507785.1_PDT002502798.1' already exists. Skipping...
Folder 'GCA_045507805.1_PDT002502796.1' already exists. Skipping...
Folder 'GCA_045507825.1_PDT002502794.1' already exists. Skipping...
Folder 'GCA_045507845.1_PDT002502780.1' already exists. Skipping...
Folder 'GCA_045507885.1_PDT002502779.1' already exists. Skipping...
Folder 'GCA_045507905.1_PDT002502792.1' already exists. Skipping...
Folder 'GCA_045507925.1_PDT002502788.1' already exists. Skipping...
Folder 'GCA_045507945.1_PDT002502789.1' already exists. Skipping...
Folder 'GCA_045507965.1_PDT002502793.1' already exists. Skipping...
Folder 'GCA_045507985.1_PDT002502790.1' already exists. Skipping...
Folder 'GCA_045508025.1_PDT002502783.1' already exists. Skipping...
Folder 'GCA_045508045.1_PDT002502787.1' already exists. Skipping...
Folder 'GCA_045508085.1_PDT002502781.1' already exists. Skipping...
Folder 'GCA_045508125.1_PDT002502778.1' already exists. Skipping...
Folder 'GCA_045508145.1_PDT002502776.1' already exists. Skipping...
Folder 'GCA_045508185.1_PDT002502774.1' already exists. Skipping...
Folder 'GCA_045508265.1_PDT002502768.1' already exists. Skipping...
Folder 'GCA_045508285.1_PDT002502767.1' already exists. Skipping...
Folder 'GCA_045508345.1_PDT002502759.1' already exists. Skipping...
Folder 'GCA_045508365.1_PDT002502757.1' already exists. Skipping...
Folder 'GCA_045508445.1_PDT002494910.1' already exists. Skipping...
Folder 'GCA_045513035.1_PDT002485614.1' already exists. Skipping...
Folder 'GCA_045513125.1_PDT002485612.1' already exists. Skipping...
Folder 'GCA_045513165.1_PDT002485609.1' already exists. Skipping...
Folder 'GCA_045513185.1_PDT002485599.1' already exists. Skipping...
Folder 'GCA_045513195.1_PDT002485600.1' already exists. Skipping...
Folder 'GCA_045523885.1_PDT002484458.1' already exists. Skipping...
Folder 'GCA_045523925.1_PDT002484456.1' already exists. Skipping...
Folder 'GCA_045524105.1_PDT002484449.1' already exists. Skipping...
Folder 'GCA_045525255.1_PDT002484366.1' already exists. Skipping...
Folder 'GCA_045525295.1_PDT002484363.1' already exists. Skipping...
Folder 'GCA_045525415.1_PDT002484354.1' already exists. Skipping...
Folder 'GCA_045525525.1_PDT002484350.1' already exists. Skipping...
Folder 'GCA_045527365.1_PDT001793976.1' already exists. Skipping...
Folder 'GCA_045527425.1_PDT001790354.1' already exists. Skipping...
Folder 'GCA_045528945.1_PDT001700575.1' already exists. Skipping...
Folder 'GCA_045530555.1_PDT002504034.1' already exists. Skipping...
Folder 'GCA_045540455.1_PDT002504035.1' already exists. Skipping...
Folder 'GCA_045543115.1_PDT002504268.1' already exists. Skipping...
Folder 'GCA_045543275.1_PDT002504100.1' already exists. Skipping...
Folder 'GCA_045543295.1_PDT002504093.1' already exists. Skipping...
Folder 'GCA_045547095.1_PDT002504237.1' already exists. Skipping...
Folder 'GCA_045558175.1_PDT002505329.1' already exists. Skipping...
Folder 'GCA_045579685.1_PDT002485258.1' already exists. Skipping...
Folder 'GCA_045666905.1_PDT002507389.1' already exists. Skipping...
Folder 'GCA_045667005.1_PDT002507385.1' already exists. Skipping...
Folder 'GCA_045667025.1_PDT002507383.1' already exists. Skipping...
Folder 'GCA_045667065.1_PDT002507382.1' already exists. Skipping...
Folder 'GCA_045667105.1_PDT002507377.1' already exists. Skipping...
Folder 'GCA_045667125.1_PDT002507380.1' already exists. Skipping...
Folder 'GCA_045688705.1_PDT002507939.1' already exists. Skipping...
Folder 'GCA_045700735.1_PDT002512047.1' already exists. Skipping...
Folder 'GCA_900446285.1_57269_F01' already exists. Skipping...
Folder 'GCA_900446295.1_34576_C01' already exists. Skipping...
Folder 'GCA_900446305.1_59014_E02' already exists. Skipping...
Folder 'GCA_900446315.1_58225_F01' already exists. Skipping...
Folder 'GCA_900446325.1_56527_D01' already exists. Skipping...
Folder 'GCA_900446345.2_35556_G01' already exists. Skipping...
Folder 'GCA_900446355.1_42650_D02' already exists. Skipping...
Folder 'GCA_900460755.1_34576_B01' already exists. Skipping...
Folder 'GCA_900460815.1_52278_E01' already exists. Skipping...
Folder 'GCA_918429225.1_18-MIK194727' already exists. Skipping...
Folder 'GCA_000773615.1_ASM77361v1' already exists. Skipping...
Folder 'GCA_003626705.1_ASM362670v1' already exists. Skipping...
Folder 'GCA_003994875.1_ASM399487v1' already exists. Skipping...
Folder 'GCA_003994885.1_ASM399488v1' already exists. Skipping...
Folder 'GCA_004853005.1_PDT000453599.1' already exists. Skipping...
Folder 'GCA_004926415.1_PDT000063193.2' already exists. Skipping...
Folder 'GCA_004926455.1_PDT000063199.2' already exists. Skipping...
Folder 'GCA_004928685.1_PDT000062996.2' already exists. Skipping...
Folder 'GCA_004930295.1_PDT000113286.2' already exists. Skipping...
Folder 'GCA_004930635.1_PDT000113287.4' already exists. Skipping...
Folder 'GCA_004930995.1_PDT000113295.2' already exists. Skipping...
Folder 'GCA_004943125.1_PDT000175677.2' already exists. Skipping...
Folder 'GCA_004945645.1_PDT000197524.2' already exists. Skipping...
Folder 'GCA_004949185.1_PDT000200546.2' already exists. Skipping...
Folder 'GCA_004970245.1_PDT000237658.2' already exists. Skipping...
Folder 'GCA_004988645.1_PDT000272461.2' already exists. Skipping...
Folder 'GCA_005005295.1_PDT000175674.2' already exists. Skipping...
Folder 'GCA_005005395.1_PDT000063194.2' already exists. Skipping...
Folder 'GCA_005005455.1_PDT000063000.2' already exists. Skipping...
Folder 'GCA_005005515.1_PDT000063015.2' already exists. Skipping...
Folder 'GCA_005005535.1_PDT000063010.2' already exists. Skipping...
Folder 'GCA_005014395.1_PDT000113297.2' already exists. Skipping...
Folder 'GCA_005014455.1_PDT000113292.2' already exists. Skipping...
Folder 'GCA_005014515.1_PDT000179407.2' already exists. Skipping...
Folder 'GCA_005014615.1_PDT000113290.2' already exists. Skipping...
Folder 'GCA_005014855.1_PDT000063001.2' already exists. Skipping...
Folder 'GCA_005015375.1_PDT000063198.2' already exists. Skipping...
Folder 'GCA_005079465.1_PDT000113291.2' already exists. Skipping...
Folder 'GCA_005079665.1_PDT000175679.2' already exists. Skipping...
Folder 'GCA_005079785.1_PDT000272460.2' already exists. Skipping...
Folder 'GCA_005084885.1_PDT000317545.2' already exists. Skipping...
Folder 'GCA_005085005.1_PDT000306813.2' already exists. Skipping...
Folder 'GCA_005123465.1_PDT000489609.1' already exists. Skipping...
Folder 'GCA_005133605.1_PDT000062999.2' already exists. Skipping...
Folder 'GCA_005133625.1_PDT000062998.2' already exists. Skipping...
Folder 'GCA_005133685.1_PDT000063003.2' already exists. Skipping...
Folder 'GCA_005133745.1_PDT000063006.2' already exists. Skipping...
Folder 'GCA_005135125.1_PDT000063008.2' already exists. Skipping...
Folder 'GCA_005135525.1_PDT000063190.2' already exists. Skipping...
Folder 'GCA_005135565.1_PDT000063192.2' already exists. Skipping...
Folder 'GCA_005135605.1_PDT000063195.2' already exists. Skipping...
Folder 'GCA_005135645.1_PDT000063197.2' already exists. Skipping...
Folder 'GCA_005138625.1_PDT000113294.2' already exists. Skipping...
Folder 'GCA_005138945.1_PDT000113293.2' already exists. Skipping...
Folder 'GCA_005139145.1_PDT000113218.2' already exists. Skipping...
Folder 'GCA_005139445.1_PDT000113296.2' already exists. Skipping...
Folder 'GCA_005139735.1_PDT000113299.2' already exists. Skipping...
Folder 'GCA_005139985.1_PDT000113298.2' already exists. Skipping...
Folder 'GCA_005193855.1_PDT000175672.2' already exists. Skipping...
Folder 'GCA_005200355.1_PDT000275580.2' already exists. Skipping...
Folder 'GCA_005200755.1_PDT000150549.3' already exists. Skipping...
Folder 'GCA_005200975.1_PDT000237893.2' already exists. Skipping...
Folder 'GCA_005221085.1_PDT000495501.1' already exists. Skipping...
Folder 'GCA_005250765.1_PDT000063004.2' already exists. Skipping...
Folder 'GCA_005250775.1_PDT000063002.2' already exists. Skipping...
Folder 'GCA_005250805.1_PDT000062997.2' already exists. Skipping...
Folder 'GCA_005250845.1_PDT000063014.2' already exists. Skipping...
Folder 'GCA_005250875.1_PDT000063009.2' already exists. Skipping...
Folder 'GCA_005250925.1_PDT000063017.2' already exists. Skipping...
Folder 'GCA_005251145.1_PDT000063191.2' already exists. Skipping...
Folder 'GCA_005251185.1_PDT000063196.2' already exists. Skipping...
Folder 'GCA_005251245.1_PDT000081836.2' already exists. Skipping...
Folder 'GCA_005298745.1_PDT000113289.3' already exists. Skipping...
Folder 'GCA_005298765.1_PDT000113288.3' already exists. Skipping...
Folder 'GCA_005300305.1_PDT000134210.3' already exists. Skipping...
Folder 'GCA_005300345.1_PDT000134208.2' already exists. Skipping...
Folder 'GCA_005300425.1_PDT000134209.3' already exists. Skipping...
Folder 'GCA_005305185.1_PDT000328450.1' already exists. Skipping...
Folder 'GCA_005374085.1_PDT000371720.1' already exists. Skipping...
Folder 'GCA_005895565.1_PDT000063005.2' already exists. Skipping...
Folder 'GCA_006224625.1_PDT000517644.1' already exists. Skipping...
Folder 'GCA_006224945.1_PDT000517653.1' already exists. Skipping...
Folder 'GCA_007467195.1_PDT000544553.1' already exists. Skipping...
Folder 'GCA_008159725.1_PDT000568906.1' already exists. Skipping...
Folder 'GCA_008350865.1_PDT000580601.1' already exists. Skipping...
Folder 'GCA_010275415.1_PDT000643045.1' already exists. Skipping...
Folder 'GCA_010275645.1_PDT000656298.1' already exists. Skipping...
Folder 'GCA_010276535.1_PDT000640815.1' already exists. Skipping...
Folder 'GCA_011501845.1_PDT000703130.1' already exists. Skipping...
Folder 'GCA_011660495.1_PDT000690133.1' already exists. Skipping...
Folder 'GCA_011707135.1_PDT000708886.1' already exists. Skipping...
Folder 'GCA_013752395.1_PDT000760600.1' already exists. Skipping...
Folder 'GCA_014088745.1_PDT000803193.1' already exists. Skipping...
Folder 'GCA_014361755.1_PDT000823103.1' already exists. Skipping...
Folder 'GCA_014764615.1_ASM1476461v1' already exists. Skipping...
Folder 'GCA_014973985.1_PDT000862212.1' already exists. Skipping...
Folder 'GCA_014974235.1_PDT000862145.1' already exists. Skipping...
Folder 'GCA_014974265.1_PDT000862174.1' already exists. Skipping...
Folder 'GCA_014974285.1_PDT000862178.1' already exists. Skipping...
Folder 'GCA_014974405.1_PDT000862143.1' already exists. Skipping...
Folder 'GCA_014974705.1_PDT000862159.1' already exists. Skipping...
Folder 'GCA_014974725.1_PDT000862158.1' already exists. Skipping...
Folder 'GCA_014974745.1_PDT000862160.1' already exists. Skipping...
Folder 'GCA_014974825.1_PDT000862157.1' already exists. Skipping...
Folder 'GCA_014974865.1_PDT000862152.1' already exists. Skipping...
Folder 'GCA_014977125.1_PDT000862146.1' already exists. Skipping...
Folder 'GCA_014977265.1_PDT000862173.1' already exists. Skipping...
Folder 'GCA_014977285.1_PDT000862168.1' already exists. Skipping...
Folder 'GCA_014977315.1_PDT000862172.1' already exists. Skipping...
Folder 'GCA_015004495.1_PDT000868397.1' already exists. Skipping...
Folder 'GCA_022961255.1_PDT001285105.1' already exists. Skipping...
Folder 'GCA_023047835.1_PDT001290183.1' already exists. Skipping...
Folder 'GCA_023047895.1_PDT001290190.1' already exists. Skipping...
Folder 'GCA_025224375.1_PDT001417242.1' already exists. Skipping...
Folder 'GCA_025902965.1_PDT001470085.1' already exists. Skipping...
Folder 'GCA_027917135.1_PDT001557713.1' already exists. Skipping...
Folder 'GCA_027917155.1_PDT001557710.1' already exists. Skipping...
Folder 'GCA_027918875.1_PDT001557451.1' already exists. Skipping...
Folder 'GCA_028433265.1_PDT001600936.1' already exists. Skipping...
Folder 'GCA_028997925.1_PDT001651512.1' already exists. Skipping...
Folder 'GCA_029328255.1_PDT001664925.1' already exists. Skipping...
Folder 'GCA_029574485.1_PDT001677979.1' already exists. Skipping...
Folder 'GCA_029574505.1_PDT001677977.1' already exists. Skipping...
Folder 'GCA_029574525.1_PDT001677978.1' already exists. Skipping...
Folder 'GCA_029574545.1_PDT001677975.1' already exists. Skipping...
Folder 'GCA_029574585.1_PDT001677976.1' already exists. Skipping...
Folder 'GCA_029574605.1_PDT001677972.1' already exists. Skipping...
Folder 'GCA_029574625.1_PDT001677971.1' already exists. Skipping...
Folder 'GCA_029574645.1_PDT001677973.1' already exists. Skipping...
Folder 'GCA_029574665.1_PDT001677974.1' already exists. Skipping...
Folder 'GCA_029574685.1_PDT001677970.1' already exists. Skipping...
Folder 'GCA_029574705.1_PDT001677969.1' already exists. Skipping...
Folder 'GCA_029574725.1_PDT001677968.1' already exists. Skipping...
Folder 'GCA_029574735.1_PDT001677966.1' already exists. Skipping...
Folder 'GCA_029574765.1_PDT001677967.1' already exists. Skipping...
Folder 'GCA_029574785.1_PDT001677965.1' already exists. Skipping...
Folder 'GCA_029574805.1_PDT001677964.1' already exists. Skipping...
Folder 'GCA_029574815.1_PDT001677963.1' already exists. Skipping...
Folder 'GCA_029574845.1_PDT001677961.1' already exists. Skipping...
Folder 'GCA_029574865.1_PDT001677962.1' already exists. Skipping...
Folder 'GCA_029574885.1_PDT001677959.1' already exists. Skipping...
Folder 'GCA_029574905.1_PDT001677957.1' already exists. Skipping...
Folder 'GCA_029574925.1_PDT001677956.1' already exists. Skipping...
Folder 'GCA_029574945.1_PDT001677955.1' already exists. Skipping...
Folder 'GCA_029574965.1_PDT001677954.1' already exists. Skipping...
Folder 'GCA_029574985.1_PDT001677960.1' already exists. Skipping...
Folder 'GCA_029575005.1_PDT001677958.1' already exists. Skipping...
Folder 'GCA_029575025.1_PDT001677953.1' already exists. Skipping...
Folder 'GCA_029575045.1_PDT001677952.1' already exists. Skipping...
Folder 'GCA_029575065.1_PDT001677950.1' already exists. Skipping...
Folder 'GCA_029575085.1_PDT001677951.1' already exists. Skipping...
Folder 'GCA_029575105.1_PDT001677949.1' already exists. Skipping...
Folder 'GCA_029575125.1_PDT001677948.1' already exists. Skipping...
Folder 'GCA_029575145.1_PDT001677945.1' already exists. Skipping...
Folder 'GCA_029575165.1_PDT001677946.1' already exists. Skipping...
Folder 'GCA_029575185.1_PDT001677940.1' already exists. Skipping...
Folder 'GCA_029575205.1_PDT001677941.1' already exists. Skipping...
Folder 'GCA_029575225.1_PDT001677939.1' already exists. Skipping...
Folder 'GCA_029575245.1_PDT001677938.1' already exists. Skipping...
Folder 'GCA_029575265.1_PDT001677944.1' already exists. Skipping...
Folder 'GCA_029575285.1_PDT001677936.1' already exists. Skipping...
Folder 'GCA_029575325.1_PDT001677931.1' already exists. Skipping...
Folder 'GCA_029575345.1_PDT001677934.1' already exists. Skipping...
Folder 'GCA_029575485.1_PDT001677942.1' already exists. Skipping...
Folder 'GCA_029575565.1_PDT001677937.1' already exists. Skipping...
Folder 'GCA_029575585.1_PDT001677935.1' already exists. Skipping...
Folder 'GCA_029575595.1_PDT001677932.1' already exists. Skipping...
Folder 'GCA_029576555.1_PDT001677947.1' already exists. Skipping...
Folder 'GCA_029579275.1_PDT001677933.1' already exists. Skipping...
Folder 'GCA_029579295.1_PDT001677943.1' already exists. Skipping...
Folder 'GCA_031879515.1_PDT001893575.1' already exists. Skipping...
Folder 'GCA_031879575.1_PDT001893580.1' already exists. Skipping...
Folder 'GCA_031901685.1_PDT001893576.1' already exists. Skipping...
Folder 'GCA_031901705.1_PDT001893574.1' already exists. Skipping...
Folder 'GCA_031901725.1_PDT001893573.1' already exists. Skipping...
Folder 'GCA_031901745.1_PDT001893572.1' already exists. Skipping...
Folder 'GCA_031905345.1_PDT001844083.1' already exists. Skipping...
Folder 'GCA_031943065.1_PDT001838812.1' already exists. Skipping...
Folder 'GCA_032157905.1_PDT001857804.1' already exists. Skipping...
Folder 'GCA_032218245.1_PDT001740694.1' already exists. Skipping...
Folder 'GCA_032218665.1_PDT001740673.1' already exists. Skipping...
Folder 'GCA_032428455.1_PDT001822812.1' already exists. Skipping...
Folder 'GCA_032614795.1_PDT001924810.1' already exists. Skipping...
Folder 'GCA_032951095.1_PDT001774292.1' already exists. Skipping...
Folder 'GCA_033034275.1_PDT001759832.1' already exists. Skipping...
Folder 'GCA_033081745.1_PDT001745246.1' already exists. Skipping...
Folder 'GCA_033246785.1_PDT001748368.1' already exists. Skipping...

Retreiveing data: 36310it [00:06, 6642.31it/s]

Folder 'GCA_004810465.1_PDT000384911.1' already exists. Skipping...
Folder 'GCA_004810495.1_PDT000385014.1' already exists. Skipping...
Folder 'GCA_004810515.1_PDT000384910.1' already exists. Skipping...
Folder 'GCA_004810595.1_PDT000385013.1' already exists. Skipping...
Folder 'GCA_004810615.1_PDT000384899.1' already exists. Skipping...
Folder 'GCA_004810635.1_PDT000385012.1' already exists. Skipping...
Folder 'GCA_004810675.1_PDT000386981.1' already exists. Skipping...
Folder 'GCA_004810695.1_PDT000386220.1' already exists. Skipping...
Folder 'GCA_004810775.1_PDT000386223.1' already exists. Skipping...
Folder 'GCA_004810795.1_PDT000385023.1' already exists. Skipping...
Folder 'GCA_004810815.1_PDT000386201.1' already exists. Skipping...
Folder 'GCA_004810855.1_PDT000386218.1' already exists. Skipping...
Folder 'GCA_004810895.1_PDT000385020.1' already exists. Skipping...
Folder 'GCA_004810915.1_PDT000385021.1' already exists. Skipping...
Folder 'GCA_004810975.1_PDT000386115.1' already exists. Skipping...
Folder 'GCA_004810995.1_PDT000384912.1' already exists. Skipping...
Folder 'GCA_004811015.1_PDT000386204.1' already exists. Skipping...
Folder 'GCA_004811035.1_PDT000386202.1' already exists. Skipping...
Folder 'GCA_004811095.1_PDT000386203.1' already exists. Skipping...
Folder 'GCA_004811115.1_PDT000386205.1' already exists. Skipping...
Folder 'GCA_004811155.1_PDT000386207.1' already exists. Skipping...
Folder 'GCA_004811195.1_PDT000386209.1' already exists. Skipping...
Folder 'GCA_004811215.1_PDT000386703.1' already exists. Skipping...
Folder 'GCA_004811255.1_PDT000386211.1' already exists. Skipping...
Folder 'GCA_004811315.1_PDT000386213.1' already exists. Skipping...
Folder 'GCA_004811375.1_PDT000386228.1' already exists. Skipping...
Folder 'GCA_004811415.1_PDT000386975.1' already exists. Skipping...
Folder 'GCA_004811435.1_PDT000386976.1' already exists. Skipping...
Folder 'GCA_004811475.1_PDT000386973.1' already exists. Skipping...
Folder 'GCA_004811495.1_PDT000386977.1' already exists. Skipping...
Folder 'GCA_004811535.1_PDT000386702.1' already exists. Skipping...
Folder 'GCA_004811555.1_PDT000387158.1' already exists. Skipping...
Folder 'GCA_004811575.1_PDT000387136.1' already exists. Skipping...
Folder 'GCA_004811655.1_PDT000386984.1' already exists. Skipping...
Folder 'GCA_004811675.1_PDT000386982.1' already exists. Skipping...
Folder 'GCA_004811715.1_PDT000387418.1' already exists. Skipping...
Folder 'GCA_004811755.1_PDT000387421.1' already exists. Skipping...
Folder 'GCA_004811795.1_PDT000387138.1' already exists. Skipping...
Folder 'GCA_004811835.1_PDT000386978.1' already exists. Skipping...
Folder 'GCA_004811855.1_PDT000387154.1' already exists. Skipping...
Folder 'GCA_004811875.1_PDT000387155.1' already exists. Skipping...
Folder 'GCA_004811915.1_PDT000386988.1' already exists. Skipping...
Folder 'GCA_004811935.1_PDT000386986.1' already exists. Skipping...
Folder 'GCA_004811955.1_PDT000386979.1' already exists. Skipping...
Folder 'GCA_004811975.1_PDT000386985.1' already exists. Skipping...
Folder 'GCA_004811995.1_PDT000387157.1' already exists. Skipping...
Folder 'GCA_004812005.1_PDT000387104.1' already exists. Skipping...
Folder 'GCA_004812075.1_PDT000387461.1' already exists. Skipping...
Folder 'GCA_004812115.1_PDT000387103.1' already exists. Skipping...
Folder 'GCA_004812125.1_PDT000387740.1' already exists. Skipping...
Folder 'GCA_004812155.1_PDT000387133.1' already exists. Skipping...
Folder 'GCA_004812195.1_PDT000387134.1' already exists. Skipping...
Folder 'GCA_004812225.1_PDT000387135.1' already exists. Skipping...
Folder 'GCA_004812255.1_PDT000387478.1' already exists. Skipping...
Folder 'GCA_004812275.1_PDT000387144.1' already exists. Skipping...
Folder 'GCA_004812295.1_PDT000387140.1' already exists. Skipping...
Folder 'GCA_004812335.1_PDT000387648.1' already exists. Skipping...
Folder 'GCA_004812375.1_PDT000387645.1' already exists. Skipping...
Folder 'GCA_004812395.1_PDT000387147.1' already exists. Skipping...
Folder 'GCA_004812415.1_PDT000387153.1' already exists. Skipping...
Folder 'GCA_004812445.1_PDT000387443.1' already exists. Skipping...
Folder 'GCA_004812495.1_PDT000387664.1' already exists. Skipping...
Folder 'GCA_004812615.1_PDT000387166.1' already exists. Skipping...
Folder 'GCA_004812635.1_PDT000387404.1' already exists. Skipping...
Folder 'GCA_004812655.1_PDT000388793.1' already exists. Skipping...
Folder 'GCA_004812675.1_PDT000387480.1' already exists. Skipping...
Folder 'GCA_004812695.1_PDT000387410.1' already exists. Skipping...
Folder 'GCA_004812715.1_PDT000387415.1' already exists. Skipping...
Folder 'GCA_004812735.1_PDT000387413.1' already exists. Skipping...
Folder 'GCA_004812755.1_PDT000387409.1' already exists. Skipping...
Folder 'GCA_004812775.1_PDT000387422.1' already exists. Skipping...
Folder 'GCA_004812795.1_PDT000387427.1' already exists. Skipping...
Folder 'GCA_004812815.1_PDT000387649.1' already exists. Skipping...
Folder 'GCA_004812835.1_PDT000387644.1' already exists. Skipping...
Folder 'GCA_004812855.1_PDT000387423.1' already exists. Skipping...
Folder 'GCA_004812895.1_PDT000387420.1' already exists. Skipping...
Folder 'GCA_004812915.1_PDT000387434.1' already exists. Skipping...
Folder 'GCA_004812935.1_PDT000387431.1' already exists. Skipping...
Folder 'GCA_004812975.1_PDT000387438.1' already exists. Skipping...
Folder 'GCA_004812995.1_PDT000387435.1' already exists. Skipping...
Folder 'GCA_004813015.1_PDT000387439.1' already exists. Skipping...
Folder 'GCA_004813035.1_PDT000387741.1' already exists. Skipping...
Folder 'GCA_004813075.1_PDT000387624.1' already exists. Skipping...
Folder 'GCA_004813115.1_PDT000387634.1' already exists. Skipping...
Folder 'GCA_004813155.1_PDT000387631.1' already exists. Skipping...
Folder 'GCA_004813175.1_PDT000387636.1' already exists. Skipping...
Folder 'GCA_004813195.1_PDT000387638.1' already exists. Skipping...
Folder 'GCA_004813255.1_PDT000387637.1' already exists. Skipping...
Folder 'GCA_004813275.1_PDT000388796.1' already exists. Skipping...
Folder 'GCA_004813295.1_PDT000387641.1' already exists. Skipping...
Folder 'GCA_004813315.1_PDT000387650.1' already exists. Skipping...
Folder 'GCA_004813335.1_PDT000387653.1' already exists. Skipping...
Folder 'GCA_004813355.1_PDT000387642.1' already exists. Skipping...
Folder 'GCA_004813395.1_PDT000387655.1' already exists. Skipping...
Folder 'GCA_004813415.1_PDT000387652.1' already exists. Skipping...
Folder 'GCA_004813435.1_PDT000387657.1' already exists. Skipping...
Folder 'GCA_004813455.1_PDT000388794.1' already exists. Skipping...
Folder 'GCA_004813475.1_PDT000387659.1' already exists. Skipping...
Folder 'GCA_004813495.1_PDT000387662.1' already exists. Skipping...
Folder 'GCA_004813515.1_PDT000387663.1' already exists. Skipping...
Folder 'GCA_004813545.1_PDT000387743.1' already exists. Skipping...
Folder 'GCA_004813575.1_PDT000387658.1' already exists. Skipping...
Folder 'GCA_004813835.1_PDT000388785.1' already exists. Skipping...
Folder 'GCA_004813875.1_PDT000388792.1' already exists. Skipping...
Folder 'GCA_004813915.1_PDT000388786.1' already exists. Skipping...
Folder 'GCA_004813955.1_PDT000388799.1' already exists. Skipping...
Folder 'GCA_004813975.1_PDT000388797.1' already exists. Skipping...
Folder 'GCA_004814015.1_PDT000388803.1' already exists. Skipping...
Folder 'GCA_004814055.1_PDT000388804.1' already exists. Skipping...
Folder 'GCA_004814075.1_PDT000388805.1' already exists. Skipping...
Folder 'GCA_004814095.1_PDT000389452.1' already exists. Skipping...
Folder 'GCA_004814115.1_PDT000389826.1' already exists. Skipping...
Folder 'GCA_004814155.1_PDT000389458.1' already exists. Skipping...
Folder 'GCA_004814175.1_PDT000388841.1' already exists. Skipping...
Folder 'GCA_004814195.1_PDT000388846.1' already exists. Skipping...
Folder 'GCA_004814215.1_PDT000388810.1' already exists. Skipping...
Folder 'GCA_004814235.1_PDT000389404.1' already exists. Skipping...
Folder 'GCA_004814255.1_PDT000388840.1' already exists. Skipping...
Folder 'GCA_004814275.1_PDT000389421.1' already exists. Skipping...
Folder 'GCA_004814295.1_PDT000389422.1' already exists. Skipping...
Folder 'GCA_004814315.1_PDT000388843.1' already exists. Skipping...
Folder 'GCA_004814335.1_PDT000389437.1' already exists. Skipping...
Folder 'GCA_004814355.1_PDT000389424.1' already exists. Skipping...
Folder 'GCA_004814375.1_PDT000389438.1' already exists. Skipping...
Folder 'GCA_004814395.1_PDT000389459.1' already exists. Skipping...
Folder 'GCA_004814415.1_PDT000388844.1' already exists. Skipping...
Folder 'GCA_004814435.1_PDT000389454.1' already exists. Skipping...
Folder 'GCA_004814495.1_PDT000389408.1' already exists. Skipping...
Folder 'GCA_004814515.1_PDT000389825.1' already exists. Skipping...
Folder 'GCA_004814535.1_PDT000388855.1' already exists. Skipping...
Folder 'GCA_004814555.1_PDT000389406.1' already exists. Skipping...
Folder 'GCA_004814575.1_PDT000389405.1' already exists. Skipping...
Folder 'GCA_004814595.1_PDT000389425.1' already exists. Skipping...
Folder 'GCA_004814615.1_PDT000389423.1' already exists. Skipping...
Folder 'GCA_004814635.1_PDT000389841.1' already exists. Skipping...
Folder 'GCA_004814675.1_PDT000389442.1' already exists. Skipping...
Folder 'GCA_004814695.1_PDT000389439.1' already exists. Skipping...
Folder 'GCA_004814715.1_PDT000389445.1' already exists. Skipping...
Folder 'GCA_004814735.1_PDT000389441.1' already exists. Skipping...
Folder 'GCA_004814755.1_PDT000389460.1' already exists. Skipping...
Folder 'GCA_004814775.1_PDT000389827.1' already exists. Skipping...
Folder 'GCA_004814785.1_PDT000389461.1' already exists. Skipping...
Folder 'GCA_004814815.1_PDT000388807.1' already exists. Skipping...
Folder 'GCA_004814855.1_PDT000388808.1' already exists. Skipping...
Folder 'GCA_004814875.1_PDT000388847.1' already exists. Skipping...
Folder 'GCA_004814895.1_PDT000388850.1' already exists. Skipping...
Folder 'GCA_004814915.1_PDT000388849.1' already exists. Skipping...
Folder 'GCA_004814935.1_PDT000388851.1' already exists. Skipping...
Folder 'GCA_004814955.1_PDT000390340.1' already exists. Skipping...
Folder 'GCA_004814975.1_PDT000390339.1' already exists. Skipping...
Folder 'GCA_004814995.1_PDT000389860.1' already exists. Skipping...
Folder 'GCA_004815015.1_PDT000390729.1' already exists. Skipping...
Folder 'GCA_004815035.1_PDT000388852.1' already exists. Skipping...
Folder 'GCA_004815055.1_PDT000388853.1' already exists. Skipping...
Folder 'GCA_004815075.1_PDT000388854.1' already exists. Skipping...
Folder 'GCA_004815095.1_PDT000389409.1' already exists. Skipping...
Folder 'GCA_004815115.1_PDT000390730.1' already exists. Skipping...
Folder 'GCA_004815135.1_PDT000389413.1' already exists. Skipping...
Folder 'GCA_004815155.1_PDT000389416.1' already exists. Skipping...
Folder 'GCA_004815175.1_PDT000389411.1' already exists. Skipping...
Folder 'GCA_004815195.1_PDT000389412.1' already exists. Skipping...
Folder 'GCA_004815215.1_PDT000389410.1' already exists. Skipping...
Folder 'GCA_004815235.1_PDT000389407.1' already exists. Skipping...
Folder 'GCA_004815255.1_PDT000389417.1' already exists. Skipping...
Folder 'GCA_004815275.1_PDT000389430.1' already exists. Skipping...
Folder 'GCA_004815295.1_PDT000389427.1' already exists. Skipping...
Folder 'GCA_004815315.1_PDT000389415.1' already exists. Skipping...
Folder 'GCA_004815335.1_PDT000389419.1' already exists. Skipping...
Folder 'GCA_004815355.1_PDT000389429.1' already exists. Skipping...
Folder 'GCA_004815375.1_PDT000389433.1' already exists. Skipping...
Folder 'GCA_004815395.1_PDT000389432.1' already exists. Skipping...
Folder 'GCA_004815415.1_PDT000389434.1' already exists. Skipping...
Folder 'GCA_004815435.1_PDT000389444.1' already exists. Skipping...
Folder 'GCA_004815445.1_PDT000389435.1' already exists. Skipping...
Folder 'GCA_004815475.1_PDT000389436.1' already exists. Skipping...
Folder 'GCA_004815515.1_PDT000389443.1' already exists. Skipping...
Folder 'GCA_004815535.1_PDT000389463.1' already exists. Skipping...
Folder 'GCA_004815555.1_PDT000389462.1' already exists. Skipping...
Folder 'GCA_004815575.1_PDT000389451.1' already exists. Skipping...
Folder 'GCA_004815595.1_PDT000389448.1' already exists. Skipping...
Folder 'GCA_004815615.1_PDT000389446.1' already exists. Skipping...
Folder 'GCA_004815635.1_PDT000389450.1' already exists. Skipping...
Folder 'GCA_004815735.1_PDT000389464.1' already exists. Skipping...
Folder 'GCA_004815755.1_PDT000389824.1' already exists. Skipping...
Folder 'GCA_004815795.1_PDT000389829.1' already exists. Skipping...
Folder 'GCA_004815805.1_PDT000389832.1' already exists. Skipping...
Folder 'GCA_004815835.1_PDT000389833.1' already exists. Skipping...
Folder 'GCA_004815855.1_PDT000389835.1' already exists. Skipping...
Folder 'GCA_004815875.1_PDT000389828.1' already exists. Skipping...
Folder 'GCA_004815895.1_PDT000389831.1' already exists. Skipping...
Folder 'GCA_004815915.1_PDT000389836.1' already exists. Skipping...
Folder 'GCA_004815935.1_PDT000389837.1' already exists. Skipping...
Folder 'GCA_004815955.1_PDT000390345.1' already exists. Skipping...
Folder 'GCA_004815975.1_PDT000389838.1' already exists. Skipping...
Folder 'GCA_004815995.1_PDT000390721.1' already exists. Skipping...
Folder 'GCA_004816015.1_PDT000390341.1' already exists. Skipping...
Folder 'GCA_004816035.1_PDT000390347.1' already exists. Skipping...
Folder 'GCA_004816055.1_PDT000390723.1' already exists. Skipping...
Folder 'GCA_004816075.1_PDT000390722.1' already exists. Skipping...
Folder 'GCA_004816095.1_PDT000390346.1' already exists. Skipping...
Folder 'GCA_004816115.1_PDT000390726.1' already exists. Skipping...
Folder 'GCA_004816135.1_PDT000390354.1' already exists. Skipping...
Folder 'GCA_004816155.1_PDT000390724.1' already exists. Skipping...
Folder 'GCA_004816175.1_PDT000390728.1' already exists. Skipping...
Folder 'GCA_004816195.1_PDT000390731.1' already exists. Skipping...
Folder 'GCA_004816275.1_PDT000390735.1' already exists. Skipping...
Folder 'GCA_004816335.1_PDT000390740.1' already exists. Skipping...
Folder 'GCA_004816355.1_PDT000390738.1' already exists. Skipping...
Folder 'GCA_004816395.1_PDT000390742.1' already exists. Skipping...
Folder 'GCA_004816415.1_PDT000391467.1' already exists. Skipping...
Folder 'GCA_004816455.1_PDT000390773.1' already exists. Skipping...
Folder 'GCA_004816475.1_PDT000390754.1' already exists. Skipping...
Folder 'GCA_004816495.1_PDT000390766.1' already exists. Skipping...
Folder 'GCA_004816535.1_PDT000390744.1' already exists. Skipping...
Folder 'GCA_004816555.1_PDT000390772.1' already exists. Skipping...
Folder 'GCA_004816575.1_PDT000390965.1' already exists. Skipping...
Folder 'GCA_004816595.1_PDT000391762.1' already exists. Skipping...
Folder 'GCA_004816615.1_PDT000390743.1' already exists. Skipping...
Folder 'GCA_004816635.1_PDT000391698.1' already exists. Skipping...
Folder 'GCA_004816655.1_PDT000390771.1' already exists. Skipping...
Folder 'GCA_004816675.1_PDT000390763.1' already exists. Skipping...
Folder 'GCA_004816715.1_PDT000390967.1' already exists. Skipping...
Folder 'GCA_004816755.1_PDT000391700.1' already exists. Skipping...
Folder 'GCA_004816795.1_PDT000390760.1' already exists. Skipping...
Folder 'GCA_004816815.1_PDT000390745.1' already exists. Skipping...
Folder 'GCA_004816835.1_PDT000390758.1' already exists. Skipping...
Folder 'GCA_004816875.1_PDT000391736.1' already exists. Skipping...
Folder 'GCA_004816915.1_PDT000391693.1' already exists. Skipping...
Folder 'GCA_004816935.1_PDT000390774.1' already exists. Skipping...
Folder 'GCA_004816955.1_PDT000391778.1' already exists. Skipping...
Folder 'GCA_004816975.1_PDT000391710.1' already exists. Skipping...
Folder 'GCA_004816995.1_PDT000390761.1' already exists. Skipping...
Folder 'GCA_004817015.1_PDT000390757.1' already exists. Skipping...
Folder 'GCA_004817035.1_PDT000390964.1' already exists. Skipping...
Folder 'GCA_004817055.1_PDT000391706.1' already exists. Skipping...
Folder 'GCA_004817095.1_PDT000390972.1' already exists. Skipping...
Folder 'GCA_004817115.1_PDT000390756.1' already exists. Skipping...
Folder 'GCA_004817155.1_PDT000391694.1' already exists. Skipping...
Folder 'GCA_004817195.1_PDT000391766.1' already exists. Skipping...
Folder 'GCA_004817235.1_PDT000390963.1' already exists. Skipping...
Folder 'GCA_004817275.1_PDT000390968.1' already exists. Skipping...
Folder 'GCA_004817295.1_PDT000391696.1' already exists. Skipping...
Folder 'GCA_004817315.1_PDT000390767.1' already exists. Skipping...
Folder 'GCA_004817355.1_PDT000391765.1' already exists. Skipping...
Folder 'GCA_004817375.1_PDT000391767.1' already exists. Skipping...
Folder 'GCA_004817435.1_PDT000391708.1' already exists. Skipping...
Folder 'GCA_004817475.1_PDT000391606.1' already exists. Skipping...
Folder 'GCA_004817535.1_PDT000391782.1' already exists. Skipping...
Folder 'GCA_004817555.1_PDT000391757.1' already exists. Skipping...
Folder 'GCA_004817575.1_PDT000390753.1' already exists. Skipping...
Folder 'GCA_004817595.1_PDT000391783.1' already exists. Skipping...
Folder 'GCA_004817615.1_PDT000391702.1' already exists. Skipping...
Folder 'GCA_004817635.1_PDT000391799.1' already exists. Skipping...
Folder 'GCA_004817655.1_PDT000391695.1' already exists. Skipping...
Folder 'GCA_004817715.1_PDT000391756.1' already exists. Skipping...
Folder 'GCA_004817735.1_PDT000391798.1' already exists. Skipping...
Folder 'GCA_004817755.1_PDT000391794.1' already exists. Skipping...
Folder 'GCA_004817775.1_PDT000391802.1' already exists. Skipping...
Folder 'GCA_004817795.1_PDT000391758.1' already exists. Skipping...
Folder 'GCA_004817855.1_PDT000391763.1' already exists. Skipping...
Folder 'GCA_004817875.1_PDT000391759.1' already exists. Skipping...
Folder 'GCA_004817895.1_PDT000392109.1' already exists. Skipping...
Folder 'GCA_004817955.1_PDT000392112.1' already exists. Skipping...
Folder 'GCA_004817995.1_PDT000391772.1' already exists. Skipping...
Folder 'GCA_004818015.1_PDT000391774.1' already exists. Skipping...
Folder 'GCA_004818055.1_PDT000392108.1' already exists. Skipping...
Folder 'GCA_004818075.1_PDT000391788.1' already exists. Skipping...
Folder 'GCA_004818115.1_PDT000391785.1' already exists. Skipping...
Folder 'GCA_004818135.1_PDT000391787.1' already exists. Skipping...
Folder 'GCA_004818275.1_PDT000391793.1' already exists. Skipping...
Folder 'GCA_004818315.1_PDT000391805.1' already exists. Skipping...
Folder 'GCA_004818335.1_PDT000391811.1' already exists. Skipping...
Folder 'GCA_004818355.1_PDT000391810.1' already exists. Skipping...
Folder 'GCA_004818375.1_PDT000391842.1' already exists. Skipping...
Folder 'GCA_004818395.1_PDT000392106.1' already exists. Skipping...
Folder 'GCA_004818415.1_PDT000391849.1' already exists. Skipping...
Folder 'GCA_004818435.1_PDT000392115.1' already exists. Skipping...
Folder 'GCA_004818455.1_PDT000392113.1' already exists. Skipping...
Folder 'GCA_004818475.1_PDT000392520.1' already exists. Skipping...
Folder 'GCA_004818515.1_PDT000392564.1' already exists. Skipping...
Folder 'GCA_004818555.1_PDT000394790.1' already exists. Skipping...
Folder 'GCA_004818575.1_PDT000392529.1' already exists. Skipping...
Folder 'GCA_004818615.1_PDT000392550.1' already exists. Skipping...
Folder 'GCA_004818665.1_PDT000392596.1' already exists. Skipping...
Folder 'GCA_004818695.1_PDT000392528.1' already exists. Skipping...
Folder 'GCA_004818715.1_PDT000392563.1' already exists. Skipping...
Folder 'GCA_004818735.1_PDT000392593.1' already exists. Skipping...
Folder 'GCA_004818775.1_PDT000392527.1' already exists. Skipping...
Folder 'GCA_004818815.1_PDT000392530.1' already exists. Skipping...
Folder 'GCA_004818835.1_PDT000393023.1' already exists. Skipping...
Folder 'GCA_004818855.1_PDT000392531.1' already exists. Skipping...
Folder 'GCA_004818895.1_PDT000393251.1' already exists. Skipping...
Folder 'GCA_004818935.1_PDT000393805.1' already exists. Skipping...
Folder 'GCA_004819055.1_PDT000392117.1' already exists. Skipping...

Retreiveing data: 37650it [00:07, 6668.79it/s]

Folder 'GCA_004855645.1_PDT000457746.1' already exists. Skipping...
Folder 'GCA_004855665.1_PDT000457744.1' already exists. Skipping...
Folder 'GCA_004855685.1_PDT000457754.1' already exists. Skipping...
Folder 'GCA_004855705.1_PDT000457758.1' already exists. Skipping...
Folder 'GCA_004855725.1_PDT000458509.1' already exists. Skipping...
Folder 'GCA_004855745.1_PDT000457751.1' already exists. Skipping...
Folder 'GCA_004855765.1_PDT000457749.1' already exists. Skipping...
Folder 'GCA_004855785.1_PDT000457757.1' already exists. Skipping...
Folder 'GCA_004855805.1_PDT000457747.1' already exists. Skipping...
Folder 'GCA_004855815.1_PDT000458807.1' already exists. Skipping...
Folder 'GCA_004855895.1_PDT000458508.1' already exists. Skipping...
Folder 'GCA_004855925.1_PDT000457761.1' already exists. Skipping...
Folder 'GCA_004855945.1_PDT000457760.1' already exists. Skipping...
Folder 'GCA_004855985.1_PDT000457752.1' already exists. Skipping...
Folder 'GCA_004856005.1_PDT000458522.1' already exists. Skipping...
Folder 'GCA_004856015.1_PDT000457745.1' already exists. Skipping...
Folder 'GCA_004856045.1_PDT000457753.1' already exists. Skipping...
Folder 'GCA_004856065.1_PDT000457750.1' already exists. Skipping...
Folder 'GCA_004856085.1_PDT000457787.1' already exists. Skipping...
Folder 'GCA_004856125.1_PDT000458525.1' already exists. Skipping...
Folder 'GCA_004856155.1_PDT000459229.1' already exists. Skipping...
Folder 'GCA_004856185.1_PDT000458791.1' already exists. Skipping...
Folder 'GCA_004856225.1_PDT000457867.1' already exists. Skipping...
Folder 'GCA_004856245.1_PDT000459230.1' already exists. Skipping...
Folder 'GCA_004856265.1_PDT000457798.1' already exists. Skipping...
Folder 'GCA_004856285.1_PDT000458747.1' already exists. Skipping...
Folder 'GCA_004856325.1_PDT000457871.1' already exists. Skipping...
Folder 'GCA_004856365.1_PDT000458762.1' already exists. Skipping...
Folder 'GCA_004856425.1_PDT000457876.1' already exists. Skipping...
Folder 'GCA_004856465.1_PDT000458764.1' already exists. Skipping...
Folder 'GCA_004856505.1_PDT000458515.1' already exists. Skipping...
Folder 'GCA_004856545.1_PDT000458502.1' already exists. Skipping...
Folder 'GCA_004856565.1_PDT000458808.1' already exists. Skipping...
Folder 'GCA_004856585.1_PDT000458504.1' already exists. Skipping...
Folder 'GCA_004856625.1_PDT000458512.1' already exists. Skipping...
Folder 'GCA_004856635.1_PDT000458505.1' already exists. Skipping...
Folder 'GCA_004856665.1_PDT000458511.1' already exists. Skipping...
Folder 'GCA_004856725.1_PDT000458513.1' already exists. Skipping...
Folder 'GCA_004856745.1_PDT000458514.1' already exists. Skipping...
Folder 'GCA_004856765.1_PDT000459643.1' already exists. Skipping...
Folder 'GCA_004856785.1_PDT000459658.1' already exists. Skipping...
Folder 'GCA_004856805.1_PDT000458517.1' already exists. Skipping...
Folder 'GCA_004856825.1_PDT000459233.1' already exists. Skipping...
Folder 'GCA_004856865.1_PDT000458814.1' already exists. Skipping...
Folder 'GCA_004856905.1_PDT000459232.1' already exists. Skipping...
Folder 'GCA_004856945.1_PDT000459231.1' already exists. Skipping...
Folder 'GCA_004856965.1_PDT000458518.1' already exists. Skipping...
Folder 'GCA_004856985.1_PDT000458527.1' already exists. Skipping...
Folder 'GCA_004857025.1_PDT000458519.1' already exists. Skipping...
Folder 'GCA_004857045.1_PDT000459262.1' already exists. Skipping...
Folder 'GCA_004857065.1_PDT000458740.1' already exists. Skipping...
Folder 'GCA_004857075.1_PDT000458528.1' already exists. Skipping...
Folder 'GCA_004857125.1_PDT000458738.1' already exists. Skipping...
Folder 'GCA_004857145.1_PDT000458521.1' already exists. Skipping...
Folder 'GCA_004857165.1_PDT000459256.1' already exists. Skipping...
Folder 'GCA_004857205.1_PDT000459254.1' already exists. Skipping...
Folder 'GCA_004857285.1_PDT000458741.1' already exists. Skipping...
Folder 'GCA_004857305.1_PDT000458751.1' already exists. Skipping...
Folder 'GCA_004857325.1_PDT000459236.1' already exists. Skipping...
Folder 'GCA_004857365.1_PDT000458749.1' already exists. Skipping...
Folder 'GCA_004857385.1_PDT000459263.1' already exists. Skipping...
Folder 'GCA_004857405.1_PDT000458750.1' already exists. Skipping...
Folder 'GCA_004857445.1_PDT000458752.1' already exists. Skipping...
Folder 'GCA_004857465.1_PDT000459639.1' already exists. Skipping...
Folder 'GCA_004857485.1_PDT000458754.1' already exists. Skipping...
Folder 'GCA_004857505.1_PDT000459260.1' already exists. Skipping...
Folder 'GCA_004857535.1_PDT000459641.1' already exists. Skipping...
Folder 'GCA_004857585.1_PDT000458757.1' already exists. Skipping...
Folder 'GCA_004857625.1_PDT000458755.1' already exists. Skipping...
Folder 'GCA_004857645.1_PDT000459659.1' already exists. Skipping...
Folder 'GCA_004857665.1_PDT000459258.1' already exists. Skipping...
Folder 'GCA_004857685.1_PDT000458760.1' already exists. Skipping...
Folder 'GCA_004857725.1_PDT000458806.1' already exists. Skipping...
Folder 'GCA_004857745.1_PDT000458802.1' already exists. Skipping...
Folder 'GCA_004857785.1_PDT000459672.1' already exists. Skipping...
Folder 'GCA_004857845.1_PDT000458804.1' already exists. Skipping...
Folder 'GCA_004857865.1_PDT000458793.1' already exists. Skipping...
Folder 'GCA_004857885.1_PDT000459657.1' already exists. Skipping...
Folder 'GCA_004857925.1_PDT000458759.1' already exists. Skipping...
Folder 'GCA_004857965.1_PDT000458797.1' already exists. Skipping...
Folder 'GCA_004857985.1_PDT000459642.1' already exists. Skipping...
Folder 'GCA_004858065.1_PDT000457780.1' already exists. Skipping...
Folder 'GCA_004858085.1_PDT000457784.1' already exists. Skipping...
Folder 'GCA_004858105.1_PDT000458743.1' already exists. Skipping...
Folder 'GCA_004858125.1_PDT000458524.1' already exists. Skipping...
Folder 'GCA_004858145.1_PDT000458510.1' already exists. Skipping...
Folder 'GCA_004858185.1_PDT000458820.1' already exists. Skipping...
Folder 'GCA_004858225.1_PDT000459791.1' already exists. Skipping...
Folder 'GCA_004858265.1_PDT000459223.1' already exists. Skipping...
Folder 'GCA_004858285.1_PDT000459674.1' already exists. Skipping...
Folder 'GCA_004858295.1_PDT000459673.1' already exists. Skipping...
Folder 'GCA_004858325.1_PDT000459228.1' already exists. Skipping...
Folder 'GCA_004858345.1_PDT000459224.1' already exists. Skipping...
Folder 'GCA_004858405.1_PDT000459239.1' already exists. Skipping...
Folder 'GCA_004858445.1_PDT000459240.1' already exists. Skipping...
Folder 'GCA_004858465.1_PDT000459225.1' already exists. Skipping...
Folder 'GCA_004858485.1_PDT000459807.1' already exists. Skipping...
Folder 'GCA_004858505.1_PDT000459237.1' already exists. Skipping...
Folder 'GCA_004858525.1_PDT000459238.1' already exists. Skipping...
Folder 'GCA_004858545.1_PDT000459625.1' already exists. Skipping...
Folder 'GCA_004858565.1_PDT000459246.1' already exists. Skipping...
Folder 'GCA_004858585.1_PDT000459244.1' already exists. Skipping...
Folder 'GCA_004858595.1_PDT000459242.1' already exists. Skipping...
Folder 'GCA_004858625.1_PDT000459248.1' already exists. Skipping...
Folder 'GCA_004858685.1_PDT000459824.1' already exists. Skipping...
Folder 'GCA_004858715.1_PDT000459636.1' already exists. Skipping...
Folder 'GCA_004858765.1_PDT000459251.1' already exists. Skipping...
Folder 'GCA_004858825.1_PDT000459252.1' already exists. Skipping...
Folder 'GCA_004858845.1_PDT000459632.1' already exists. Skipping...
Folder 'GCA_004858865.1_PDT000459638.1' already exists. Skipping...
Folder 'GCA_004858905.1_PDT000459647.1' already exists. Skipping...
Folder 'GCA_004858945.1_PDT000459646.1' already exists. Skipping...
Folder 'GCA_004858965.1_PDT000459648.1' already exists. Skipping...
Folder 'GCA_004858985.1_PDT000459650.1' already exists. Skipping...
Folder 'GCA_004859025.1_PDT000459652.1' already exists. Skipping...
Folder 'GCA_004859045.1_PDT000459654.1' already exists. Skipping...
Folder 'GCA_004859065.1_PDT000459653.1' already exists. Skipping...
Folder 'GCA_004859085.1_PDT000459662.1' already exists. Skipping...
Folder 'GCA_004859105.1_PDT000459660.1' already exists. Skipping...
Folder 'GCA_004859125.1_PDT000459655.1' already exists. Skipping...
Folder 'GCA_004859145.1_PDT000459664.1' already exists. Skipping...
Folder 'GCA_004859165.1_PDT000459663.1' already exists. Skipping...
Folder 'GCA_004859185.1_PDT000459661.1' already exists. Skipping...
Folder 'GCA_004859205.1_PDT000459665.1' already exists. Skipping...
Folder 'GCA_004859225.1_PDT000459667.1' already exists. Skipping...
Folder 'GCA_004859285.1_PDT000459669.1' already exists. Skipping...
Folder 'GCA_004859325.1_PDT000459670.1' already exists. Skipping...
Folder 'GCA_004859345.1_PDT000459671.1' already exists. Skipping...
Folder 'GCA_004859365.1_PDT000459796.1' already exists. Skipping...
Folder 'GCA_004859425.1_PDT000459792.1' already exists. Skipping...
Folder 'GCA_004859445.1_PDT000459797.1' already exists. Skipping...
Folder 'GCA_004859485.1_PDT000459801.1' already exists. Skipping...
Folder 'GCA_004859545.1_PDT000459809.1' already exists. Skipping...
Folder 'GCA_004859565.1_PDT000459802.1' already exists. Skipping...
Folder 'GCA_004859585.1_PDT000459808.1' already exists. Skipping...
Folder 'GCA_004859625.1_PDT000459812.1' already exists. Skipping...
Folder 'GCA_004859665.1_PDT000459815.1' already exists. Skipping...
Folder 'GCA_004859685.1_PDT000459813.1' already exists. Skipping...
Folder 'GCA_004859725.1_PDT000459825.1' already exists. Skipping...
Folder 'GCA_004859785.1_PDT000459818.1' already exists. Skipping...
Folder 'GCA_004859805.1_PDT000459828.1' already exists. Skipping...
Folder 'GCA_004859825.1_PDT000459853.1' already exists. Skipping...
Folder 'GCA_004859865.1_PDT000459838.1' already exists. Skipping...
Folder 'GCA_004859905.1_PDT000459840.1' already exists. Skipping...
Folder 'GCA_004859945.1_PDT000459851.1' already exists. Skipping...
Folder 'GCA_004859985.1_PDT000459867.1' already exists. Skipping...
Folder 'GCA_004860065.1_PDT000459854.1' already exists. Skipping...
Folder 'GCA_004860085.1_PDT000459869.1' already exists. Skipping...
Folder 'GCA_004860105.1_PDT000459855.1' already exists. Skipping...
Folder 'GCA_004860125.1_PDT000459871.1' already exists. Skipping...
Folder 'GCA_004860165.1_PDT000459870.1' already exists. Skipping...
Folder 'GCA_004860185.1_PDT000459806.1' already exists. Skipping...
Folder 'GCA_004860205.1_PDT000459826.1' already exists. Skipping...
Folder 'GCA_004860225.1_PDT000459830.1' already exists. Skipping...
Folder 'GCA_004860245.1_PDT000459833.1' already exists. Skipping...
Folder 'GCA_004860285.1_PDT000459832.1' already exists. Skipping...
Folder 'GCA_004860305.1_PDT000459835.1' already exists. Skipping...
Folder 'GCA_004860325.1_PDT000459831.1' already exists. Skipping...
Folder 'GCA_004860345.1_PDT000459834.1' already exists. Skipping...
Folder 'GCA_004860425.1_PDT000459842.1' already exists. Skipping...
Folder 'GCA_004860485.1_PDT000459846.1' already exists. Skipping...
Folder 'GCA_004860565.1_PDT000459847.1' already exists. Skipping...
Folder 'GCA_004860665.1_PDT000464024.1' already exists. Skipping...
Folder 'GCA_004860725.1_PDT000464022.1' already exists. Skipping...
Folder 'GCA_004860765.1_PDT000464023.1' already exists. Skipping...
Folder 'GCA_004860785.1_PDT000459865.1' already exists. Skipping...
Folder 'GCA_004860805.1_PDT000459864.1' already exists. Skipping...
Folder 'GCA_004860825.1_PDT000464025.1' already exists. Skipping...
Folder 'GCA_004860845.1_PDT000464028.1' already exists. Skipping...
Folder 'GCA_004860865.1_PDT000464026.1' already exists. Skipping...
Folder 'GCA_004860885.1_PDT000464027.1' already exists. Skipping...
Folder 'GCA_004860905.1_PDT000464459.1' already exists. Skipping...
Folder 'GCA_004860925.1_PDT000464453.1' already exists. Skipping...
Folder 'GCA_004860945.1_PDT000464484.1' already exists. Skipping...
Folder 'GCA_004860965.1_PDT000464474.1' already exists. Skipping...
Folder 'GCA_004860985.1_PDT000464485.1' already exists. Skipping...
Folder 'GCA_004861005.1_PDT000464487.1' already exists. Skipping...
Folder 'GCA_004861025.1_PDT000465015.1' already exists. Skipping...
Folder 'GCA_004861045.1_PDT000464460.1' already exists. Skipping...
Folder 'GCA_004861065.1_PDT000464456.1' already exists. Skipping...
Folder 'GCA_004861085.1_PDT000464481.1' already exists. Skipping...
Folder 'GCA_004861105.1_PDT000464478.1' already exists. Skipping...
Folder 'GCA_004861125.1_PDT000465054.1' already exists. Skipping...
Folder 'GCA_004861145.1_PDT000465016.1' already exists. Skipping...
Folder 'GCA_004861205.1_PDT000464479.1' already exists. Skipping...
Folder 'GCA_004861245.1_PDT000464465.1' already exists. Skipping...
Folder 'GCA_004861265.1_PDT000464462.1' already exists. Skipping...
Folder 'GCA_004861285.1_PDT000464457.1' already exists. Skipping...
Folder 'GCA_004861305.1_PDT000465014.1' already exists. Skipping...
Folder 'GCA_004861325.1_PDT000465000.1' already exists. Skipping...
Folder 'GCA_004861345.1_PDT000464469.1' already exists. Skipping...
Folder 'GCA_004861365.1_PDT000464466.1' already exists. Skipping...
Folder 'GCA_004861385.1_PDT000465037.1' already exists. Skipping...
Folder 'GCA_004861405.1_PDT000465024.1' already exists. Skipping...
Folder 'GCA_004861425.1_PDT000464993.1' already exists. Skipping...
Folder 'GCA_004861445.1_PDT000465039.1' already exists. Skipping...
Folder 'GCA_004861465.1_PDT000465052.1' already exists. Skipping...
Folder 'GCA_004861485.1_PDT000464480.1' already exists. Skipping...
Folder 'GCA_004861505.1_PDT000464029.1' already exists. Skipping...
Folder 'GCA_004861525.1_PDT000465009.1' already exists. Skipping...
Folder 'GCA_004861545.1_PDT000465053.1' already exists. Skipping...
Folder 'GCA_004861565.1_PDT000465005.1' already exists. Skipping...
Folder 'GCA_004861585.1_PDT000464463.1' already exists. Skipping...
Folder 'GCA_004861625.1_PDT000464461.1' already exists. Skipping...
Folder 'GCA_004861645.1_PDT000465003.1' already exists. Skipping...
Folder 'GCA_004861665.1_PDT000465098.1' already exists. Skipping...
Folder 'GCA_004861685.1_PDT000464488.1' already exists. Skipping...
Folder 'GCA_004861705.1_PDT000465012.1' already exists. Skipping...
Folder 'GCA_004861725.1_PDT000465030.1' already exists. Skipping...
Folder 'GCA_004861765.1_PDT000465040.1' already exists. Skipping...
Folder 'GCA_004861785.1_PDT000465028.1' already exists. Skipping...
Folder 'GCA_004861825.1_PDT000465020.1' already exists. Skipping...
Folder 'GCA_004861845.1_PDT000465034.1' already exists. Skipping...
Folder 'GCA_004861865.1_PDT000464455.1' already exists. Skipping...
Folder 'GCA_004861885.1_PDT000464998.1' already exists. Skipping...
Folder 'GCA_004861905.1_PDT000465050.1' already exists. Skipping...
Folder 'GCA_004861925.1_PDT000465033.1' already exists. Skipping...
Folder 'GCA_004861945.1_PDT000464038.1' already exists. Skipping...
Folder 'GCA_004861965.1_PDT000464032.1' already exists. Skipping...
Folder 'GCA_004861985.1_PDT000465013.1' already exists. Skipping...
Folder 'GCA_004862005.1_PDT000464458.1' already exists. Skipping...
Folder 'GCA_004862025.1_PDT000465027.1' already exists. Skipping...
Folder 'GCA_004862045.1_PDT000465001.1' already exists. Skipping...
Folder 'GCA_004862065.1_PDT000465029.1' already exists. Skipping...
Folder 'GCA_004862105.1_PDT000464031.1' already exists. Skipping...
Folder 'GCA_004862125.1_PDT000465036.1' already exists. Skipping...
Folder 'GCA_004862145.1_PDT000465008.1' already exists. Skipping...
Folder 'GCA_004862165.1_PDT000465055.1' already exists. Skipping...
Folder 'GCA_004862185.1_PDT000465043.1' already exists. Skipping...
Folder 'GCA_004862225.1_PDT000464454.1' already exists. Skipping...
Folder 'GCA_004862245.1_PDT000465091.1' already exists. Skipping...
Folder 'GCA_004862265.1_PDT000465006.1' already exists. Skipping...
Folder 'GCA_004862285.1_PDT000465104.1' already exists. Skipping...
Folder 'GCA_004862305.1_PDT000465017.1' already exists. Skipping...
Folder 'GCA_004862325.1_PDT000464473.1' already exists. Skipping...
Folder 'GCA_004862345.1_PDT000465011.1' already exists. Skipping...
Folder 'GCA_004862365.1_PDT000465031.1' already exists. Skipping...
Folder 'GCA_004862385.1_PDT000465035.1' already exists. Skipping...
Folder 'GCA_004862405.1_PDT000465002.1' already exists. Skipping...
Folder 'GCA_004862425.1_PDT000465042.1' already exists. Skipping...
Folder 'GCA_004862445.1_PDT000465038.1' already exists. Skipping...
Folder 'GCA_004862485.1_PDT000465044.1' already exists. Skipping...
Folder 'GCA_004862505.1_PDT000465046.1' already exists. Skipping...
Folder 'GCA_004862525.1_PDT000465047.1' already exists. Skipping...
Folder 'GCA_004862545.1_PDT000465058.1' already exists. Skipping...
Folder 'GCA_004862565.1_PDT000465056.1' already exists. Skipping...
Folder 'GCA_004862585.1_PDT000464471.1' already exists. Skipping...
Folder 'GCA_004862605.1_PDT000465048.1' already exists. Skipping...
Folder 'GCA_004862685.1_PDT000465057.1' already exists. Skipping...
Folder 'GCA_004862705.1_PDT000465060.1' already exists. Skipping...
Folder 'GCA_004862725.1_PDT000465059.1' already exists. Skipping...
Folder 'GCA_004862745.1_PDT000465086.1' already exists. Skipping...
Folder 'GCA_004862825.1_PDT000465090.1' already exists. Skipping...
Folder 'GCA_004862845.1_PDT000465112.1' already exists. Skipping...
Folder 'GCA_004862855.1_PDT000464486.1' already exists. Skipping...
Folder 'GCA_004862885.1_PDT000465106.1' already exists. Skipping...
Folder 'GCA_004862905.1_PDT000465278.1' already exists. Skipping...
Folder 'GCA_004862955.1_PDT000465127.1' already exists. Skipping...
Folder 'GCA_004863005.1_PDT000465296.1' already exists. Skipping...
Folder 'GCA_004863065.1_PDT000466874.1' already exists. Skipping...
Folder 'GCA_004863085.1_PDT000465299.1' already exists. Skipping...
Folder 'GCA_004863125.1_PDT000465294.1' already exists. Skipping...
Folder 'GCA_004863145.1_PDT000465293.1' already exists. Skipping...
Folder 'GCA_004863165.1_PDT000466873.1' already exists. Skipping...
Folder 'GCA_004863185.1_PDT000465295.1' already exists. Skipping...
Folder 'GCA_004863205.1_PDT000465280.1' already exists. Skipping...
Folder 'GCA_004863245.1_PDT000465723.1' already exists. Skipping...
Folder 'GCA_004863265.1_PDT000466102.1' already exists. Skipping...
Folder 'GCA_004863285.1_PDT000465298.1' already exists. Skipping...
Folder 'GCA_004863305.1_PDT000465718.1' already exists. Skipping...
Folder 'GCA_004863325.1_PDT000465734.1' already exists. Skipping...
Folder 'GCA_004863345.1_PDT000465719.1' already exists. Skipping...
Folder 'GCA_004863365.1_PDT000465720.1' already exists. Skipping...
Folder 'GCA_004863385.1_PDT000465736.1' already exists. Skipping...
Folder 'GCA_004863405.1_PDT000465739.1' already exists. Skipping...
Folder 'GCA_004863425.1_PDT000465737.1' already exists. Skipping...
Folder 'GCA_004863445.1_PDT000466230.1' already exists. Skipping...
Folder 'GCA_004863465.1_PDT000465735.1' already exists. Skipping...
Folder 'GCA_004863485.1_PDT000465113.1' already exists. Skipping...
Folder 'GCA_004863575.1_PDT000465119.1' already exists. Skipping...
Folder 'GCA_004863605.1_PDT000466890.1' already exists. Skipping...
Folder 'GCA_004863625.1_PDT000466112.1' already exists. Skipping...
Folder 'GCA_004863645.1_PDT000465120.1' already exists. Skipping...
Folder 'GCA_004863665.1_PDT000466891.1' already exists. Skipping...
Folder 'GCA_004863705.1_PDT000465121.1' already exists. Skipping...
Folder 'GCA_004863725.1_PDT000465140.1' already exists. Skipping...
Folder 'GCA_004863735.1_PDT000465136.1' already exists. Skipping...
Folder 'GCA_004863785.1_PDT000465133.1' already exists. Skipping...
Folder 'GCA_004863805.1_PDT000466893.1' already exists. Skipping...
Folder 'GCA_004863825.1_PDT000466931.1' already exists. Skipping...
Folder 'GCA_004863835.1_PDT000465148.1' already exists. Skipping...
Folder 'GCA_004863865.1_PDT000465147.1' already exists. Skipping...
Folder 'GCA_004863885.1_PDT000465149.1' already exists. Skipping...
Folder 'GCA_004863905.1_PDT000466895.1' already exists. Skipping...

Retreiveing data: 38983it [00:07, 6645.52it/s]

Folder 'GCA_004896555.1_PDT000477151.1' already exists. Skipping...
Folder 'GCA_004896575.1_PDT000477152.1' already exists. Skipping...
Folder 'GCA_004896635.1_PDT000477154.1' already exists. Skipping...
Folder 'GCA_004896675.1_PDT000477171.1' already exists. Skipping...
Folder 'GCA_004896715.1_PDT000477166.1' already exists. Skipping...
Folder 'GCA_004896735.1_PDT000477172.1' already exists. Skipping...
Folder 'GCA_004896755.1_PDT000477159.1' already exists. Skipping...
Folder 'GCA_004896775.1_PDT000477175.1' already exists. Skipping...
Folder 'GCA_004896815.1_PDT000477174.1' already exists. Skipping...
Folder 'GCA_004896875.1_PDT000476859.1' already exists. Skipping...
Folder 'GCA_004896895.1_PDT000477177.1' already exists. Skipping...
Folder 'GCA_004896915.1_PDT000477178.1' already exists. Skipping...
Folder 'GCA_004896975.1_PDT000414496.1' already exists. Skipping...
Folder 'GCA_004896995.1_PDT000414476.1' already exists. Skipping...
Folder 'GCA_004897015.1_PDT000414488.1' already exists. Skipping...
Folder 'GCA_004897055.1_PDT000414972.1' already exists. Skipping...
Folder 'GCA_004897075.1_PDT000414499.1' already exists. Skipping...
Folder 'GCA_004897095.1_PDT000414479.1' already exists. Skipping...
Folder 'GCA_004897115.1_PDT000475529.1' already exists. Skipping...
Folder 'GCA_004897155.1_PDT000414510.1' already exists. Skipping...
Folder 'GCA_004897175.1_PDT000476855.1' already exists. Skipping...
Folder 'GCA_004897195.1_PDT000414531.1' already exists. Skipping...
Folder 'GCA_004897235.1_PDT000416969.1' already exists. Skipping...
Folder 'GCA_004897275.1_PDT000415902.1' already exists. Skipping...
Folder 'GCA_004897295.1_PDT000414505.1' already exists. Skipping...
Folder 'GCA_004897315.1_PDT000416916.1' already exists. Skipping...
Folder 'GCA_004897335.1_PDT000414503.1' already exists. Skipping...
Folder 'GCA_004897375.1_PDT000476862.1' already exists. Skipping...
Folder 'GCA_004897455.1_PDT000475539.1' already exists. Skipping...
Folder 'GCA_004897475.1_PDT000414525.1' already exists. Skipping...
Folder 'GCA_004897495.1_PDT000416959.1' already exists. Skipping...
Folder 'GCA_004897535.1_PDT000416930.1' already exists. Skipping...
Folder 'GCA_004897555.1_PDT000415890.1' already exists. Skipping...
Folder 'GCA_004897575.1_PDT000414537.1' already exists. Skipping...
Folder 'GCA_004897595.1_PDT000414543.1' already exists. Skipping...
Folder 'GCA_004897615.1_PDT000414539.1' already exists. Skipping...
Folder 'GCA_004897675.1_PDT000415917.1' already exists. Skipping...
Folder 'GCA_004897695.1_PDT000416908.1' already exists. Skipping...
Folder 'GCA_004897715.1_PDT000415622.1' already exists. Skipping...
Folder 'GCA_004897735.1_PDT000415919.1' already exists. Skipping...
Folder 'GCA_004897755.1_PDT000416932.1' already exists. Skipping...
Folder 'GCA_004897795.1_PDT000415921.1' already exists. Skipping...
Folder 'GCA_004897855.1_PDT000417789.1' already exists. Skipping...
Folder 'GCA_004897875.1_PDT000416384.1' already exists. Skipping...
Folder 'GCA_004897895.1_PDT000416997.1' already exists. Skipping...
Folder 'GCA_004897915.1_PDT000416948.1' already exists. Skipping...
Folder 'GCA_004897925.1_PDT000416984.1' already exists. Skipping...
Folder 'GCA_004897955.1_PDT000416945.1' already exists. Skipping...
Folder 'GCA_004897975.1_PDT000476861.1' already exists. Skipping...
Folder 'GCA_004897995.1_PDT000416957.1' already exists. Skipping...
Folder 'GCA_004898055.1_PDT000417342.1' already exists. Skipping...
Folder 'GCA_004898095.1_PDT000416922.1' already exists. Skipping...
Folder 'GCA_004898115.1_PDT000416920.1' already exists. Skipping...
Folder 'GCA_004898135.1_PDT000414487.1' already exists. Skipping...
Folder 'GCA_004898155.1_PDT000416912.1' already exists. Skipping...
Folder 'GCA_004898215.1_PDT000416983.1' already exists. Skipping...
Folder 'GCA_004898235.1_PDT000476863.1' already exists. Skipping...
Folder 'GCA_004898265.1_PDT000416926.1' already exists. Skipping...
Folder 'GCA_004898295.1_PDT000416974.1' already exists. Skipping...
Folder 'GCA_004898335.1_PDT000416935.1' already exists. Skipping...
Folder 'GCA_004898355.1_PDT000416936.1' already exists. Skipping...
Folder 'GCA_004898375.1_PDT000417525.1' already exists. Skipping...
Folder 'GCA_004898395.1_PDT000416949.1' already exists. Skipping...
Folder 'GCA_004898405.1_PDT000416950.1' already exists. Skipping...
Folder 'GCA_004898455.1_PDT000416942.1' already exists. Skipping...
Folder 'GCA_004898475.1_PDT000416951.1' already exists. Skipping...
Folder 'GCA_004898515.1_PDT000416952.1' already exists. Skipping...
Folder 'GCA_004898535.1_PDT000416956.1' already exists. Skipping...
Folder 'GCA_004898555.1_PDT000416964.1' already exists. Skipping...
Folder 'GCA_004898595.1_PDT000416966.1' already exists. Skipping...
Folder 'GCA_004898615.1_PDT000417426.1' already exists. Skipping...
Folder 'GCA_004898635.1_PDT000416975.1' already exists. Skipping...
Folder 'GCA_004898655.1_PDT000416971.1' already exists. Skipping...
Folder 'GCA_004898675.1_PDT000416976.1' already exists. Skipping...
Folder 'GCA_004898695.1_PDT000417422.1' already exists. Skipping...
Folder 'GCA_004898715.1_PDT000416977.1' already exists. Skipping...
Folder 'GCA_004898735.1_PDT000416980.1' already exists. Skipping...
Folder 'GCA_004898755.1_PDT000417522.1' already exists. Skipping...
Folder 'GCA_004898765.1_PDT000416978.1' already exists. Skipping...
Folder 'GCA_004898795.1_PDT000416982.1' already exists. Skipping...
Folder 'GCA_004898815.1_PDT000416981.1' already exists. Skipping...
Folder 'GCA_004898855.1_PDT000416994.1' already exists. Skipping...
Folder 'GCA_004898885.1_PDT000416993.1' already exists. Skipping...
Folder 'GCA_004898915.1_PDT000476876.1' already exists. Skipping...
Folder 'GCA_004898935.1_PDT000416996.1' already exists. Skipping...
Folder 'GCA_004899015.1_PDT000418676.1' already exists. Skipping...
Folder 'GCA_004899035.1_PDT000417351.1' already exists. Skipping...
Folder 'GCA_004899055.1_PDT000418681.1' already exists. Skipping...
Folder 'GCA_004899075.1_PDT000417423.1' already exists. Skipping...
Folder 'GCA_004899085.1_PDT000417428.1' already exists. Skipping...
Folder 'GCA_004899155.1_PDT000417430.1' already exists. Skipping...
Folder 'GCA_004899175.1_PDT000418837.1' already exists. Skipping...
Folder 'GCA_004899195.1_PDT000476874.1' already exists. Skipping...
Folder 'GCA_004899215.1_PDT000417534.1' already exists. Skipping...
Folder 'GCA_004899295.1_PDT000418660.1' already exists. Skipping...
Folder 'GCA_004899315.1_PDT000418092.1' already exists. Skipping...
Folder 'GCA_004899335.1_PDT000418095.1' already exists. Skipping...
Folder 'GCA_004899355.1_PDT000418094.1' already exists. Skipping...
Folder 'GCA_004899375.1_PDT000476880.1' already exists. Skipping...
Folder 'GCA_004899415.1_PDT000476872.1' already exists. Skipping...
Folder 'GCA_004899475.1_PDT000476873.1' already exists. Skipping...
Folder 'GCA_004899495.1_PDT000418850.1' already exists. Skipping...
Folder 'GCA_004899535.1_PDT000477047.1' already exists. Skipping...
Folder 'GCA_004899555.1_PDT000418849.1' already exists. Skipping...
Folder 'GCA_004899575.1_PDT000418852.1' already exists. Skipping...
Folder 'GCA_004899595.1_PDT000420921.1' already exists. Skipping...
Folder 'GCA_004899655.1_PDT000418857.1' already exists. Skipping...
Folder 'GCA_004899675.1_PDT000418854.1' already exists. Skipping...
Folder 'GCA_004899685.1_PDT000476879.1' already exists. Skipping...
Folder 'GCA_004899715.1_PDT000420937.1' already exists. Skipping...
Folder 'GCA_004899755.1_PDT000420913.1' already exists. Skipping...
Folder 'GCA_004899775.1_PDT000420926.1' already exists. Skipping...
Folder 'GCA_004899795.1_PDT000420918.1' already exists. Skipping...
Folder 'GCA_004899875.1_PDT000477051.1' already exists. Skipping...
Folder 'GCA_004899935.1_PDT000476875.1' already exists. Skipping...
Folder 'GCA_004899955.1_PDT000421697.1' already exists. Skipping...
Folder 'GCA_004899995.1_PDT000421698.1' already exists. Skipping...
Folder 'GCA_004900015.1_PDT000476878.1' already exists. Skipping...
Folder 'GCA_004900035.1_PDT000477052.1' already exists. Skipping...
Folder 'GCA_004900075.1_PDT000478372.1' already exists. Skipping...
Folder 'GCA_004900095.1_PDT000478388.1' already exists. Skipping...
Folder 'GCA_004900115.1_PDT000478387.1' already exists. Skipping...
Folder 'GCA_004900135.1_PDT000477216.1' already exists. Skipping...
Folder 'GCA_004900155.1_PDT000477202.1' already exists. Skipping...
Folder 'GCA_004900195.1_PDT000477240.1' already exists. Skipping...
Folder 'GCA_004900235.1_PDT000477241.1' already exists. Skipping...
Folder 'GCA_004900255.1_PDT000477243.1' already exists. Skipping...
Folder 'GCA_004900275.1_PDT000477256.1' already exists. Skipping...
Folder 'GCA_004900295.1_PDT000478404.1' already exists. Skipping...
Folder 'GCA_004900315.1_PDT000478402.1' already exists. Skipping...
Folder 'GCA_004900335.1_PDT000477255.1' already exists. Skipping...
Folder 'GCA_004900355.1_PDT000478375.1' already exists. Skipping...
Folder 'GCA_004900375.1_PDT000478389.1' already exists. Skipping...
Folder 'GCA_004900395.1_PDT000478407.1' already exists. Skipping...
Folder 'GCA_004900435.1_PDT000478403.1' already exists. Skipping...
Folder 'GCA_004900515.1_PDT000477185.1' already exists. Skipping...
Folder 'GCA_004900555.1_PDT000477188.1' already exists. Skipping...
Folder 'GCA_004900635.1_PDT000477191.1' already exists. Skipping...
Folder 'GCA_004900675.1_PDT000477194.1' already exists. Skipping...
Folder 'GCA_004900695.1_PDT000477206.1' already exists. Skipping...
Folder 'GCA_004900715.1_PDT000477210.1' already exists. Skipping...
Folder 'GCA_004900735.1_PDT000477203.1' already exists. Skipping...
Folder 'GCA_004900775.1_PDT000477193.1' already exists. Skipping...
Folder 'GCA_004900795.1_PDT000477211.1' already exists. Skipping...
Folder 'GCA_004900815.1_PDT000477207.1' already exists. Skipping...
Folder 'GCA_004900855.1_PDT000477195.1' already exists. Skipping...
Folder 'GCA_004900875.1_PDT000477213.1' already exists. Skipping...
Folder 'GCA_004900885.1_PDT000477218.1' already exists. Skipping...
Folder 'GCA_004900935.1_PDT000477214.1' already exists. Skipping...
Folder 'GCA_004900955.1_PDT000477217.1' already exists. Skipping...
Folder 'GCA_004900975.1_PDT000477226.1' already exists. Skipping...
Folder 'GCA_004901015.1_PDT000477219.1' already exists. Skipping...
Folder 'GCA_004901055.1_PDT000477223.1' already exists. Skipping...
Folder 'GCA_004901095.1_PDT000477224.1' already exists. Skipping...
Folder 'GCA_004901135.1_PDT000477227.1' already exists. Skipping...
Folder 'GCA_004901155.1_PDT000477235.1' already exists. Skipping...
Folder 'GCA_004901175.1_PDT000477236.1' already exists. Skipping...
Folder 'GCA_004901225.1_PDT000477244.1' already exists. Skipping...
Folder 'GCA_004901255.1_PDT000477246.1' already exists. Skipping...
Folder 'GCA_004901275.1_PDT000477248.1' already exists. Skipping...
Folder 'GCA_004901295.1_PDT000477247.1' already exists. Skipping...
Folder 'GCA_004901335.1_PDT000477259.1' already exists. Skipping...
Folder 'GCA_004901355.1_PDT000477249.1' already exists. Skipping...
Folder 'GCA_004901395.1_PDT000477260.1' already exists. Skipping...
Folder 'GCA_004901455.1_PDT000477275.1' already exists. Skipping...
Folder 'GCA_004901515.1_PDT000477261.1' already exists. Skipping...
Folder 'GCA_004901535.1_PDT000477276.1' already exists. Skipping...
Folder 'GCA_004901595.1_PDT000477281.1' already exists. Skipping...
Folder 'GCA_004901635.1_PDT000478354.1' already exists. Skipping...
Folder 'GCA_004901675.1_PDT000478358.1' already exists. Skipping...
Folder 'GCA_004901695.1_PDT000478361.1' already exists. Skipping...
Folder 'GCA_004901715.1_PDT000478357.1' already exists. Skipping...
Folder 'GCA_004901735.1_PDT000478365.1' already exists. Skipping...
Folder 'GCA_004901775.1_PDT000478366.1' already exists. Skipping...
Folder 'GCA_004901815.1_PDT000478368.1' already exists. Skipping...
Folder 'GCA_004901835.1_PDT000478367.1' already exists. Skipping...
Folder 'GCA_004901855.1_PDT000478380.1' already exists. Skipping...
Folder 'GCA_004901875.1_PDT000478376.1' already exists. Skipping...
Folder 'GCA_004901885.1_PDT000478383.1' already exists. Skipping...
Folder 'GCA_004901915.1_PDT000478377.1' already exists. Skipping...
Folder 'GCA_004901935.1_PDT000478379.1' already exists. Skipping...
Folder 'GCA_004901955.1_PDT000478385.1' already exists. Skipping...
Folder 'GCA_004901975.1_PDT000478386.1' already exists. Skipping...
Folder 'GCA_004902015.1_PDT000478391.1' already exists. Skipping...
Folder 'GCA_004902035.1_PDT000478394.1' already exists. Skipping...
Folder 'GCA_004902055.1_PDT000478395.1' already exists. Skipping...
Folder 'GCA_004902095.1_PDT000478393.1' already exists. Skipping...
Folder 'GCA_004902115.1_PDT000478400.1' already exists. Skipping...
Folder 'GCA_004902135.1_PDT000478398.1' already exists. Skipping...
Folder 'GCA_004902155.1_PDT000478410.1' already exists. Skipping...
Folder 'GCA_004902165.1_PDT000478401.1' already exists. Skipping...
Folder 'GCA_004902195.1_PDT000478411.1' already exists. Skipping...
Folder 'GCA_004902215.1_PDT000478408.1' already exists. Skipping...
Folder 'GCA_004902235.1_PDT000478370.1' already exists. Skipping...
Folder 'GCA_004902275.1_PDT000477279.1' already exists. Skipping...
Folder 'GCA_004902295.1_PDT000478374.1' already exists. Skipping...
Folder 'GCA_004902315.1_PDT000477239.1' already exists. Skipping...
Folder 'GCA_004902335.1_PDT000477197.1' already exists. Skipping...
Folder 'GCA_004902355.1_PDT000477238.1' already exists. Skipping...
Folder 'GCA_004902365.1_PDT000477215.1' already exists. Skipping...
Folder 'GCA_004902395.1_PDT000422098.1' already exists. Skipping...
Folder 'GCA_004902415.1_PDT000477196.1' already exists. Skipping...
Folder 'GCA_004902455.1_PDT000422163.1' already exists. Skipping...
Folder 'GCA_004902515.1_PDT000422172.1' already exists. Skipping...
Folder 'GCA_004902535.1_PDT000424663.1' already exists. Skipping...
Folder 'GCA_004902555.1_PDT000424662.1' already exists. Skipping...
Folder 'GCA_004902595.1_PDT000422082.1' already exists. Skipping...
Folder 'GCA_004902635.1_PDT000422084.1' already exists. Skipping...
Folder 'GCA_004902655.1_PDT000422122.1' already exists. Skipping...
Folder 'GCA_004902695.1_PDT000422116.1' already exists. Skipping...
Folder 'GCA_004902715.1_PDT000422165.1' already exists. Skipping...
Folder 'GCA_004902735.1_PDT000422173.1' already exists. Skipping...
Folder 'GCA_004902755.1_PDT000422190.1' already exists. Skipping...
Folder 'GCA_004902835.1_PDT000422196.1' already exists. Skipping...
Folder 'GCA_004902935.1_PDT000428410.1' already exists. Skipping...
Folder 'GCA_004902955.1_PDT000428958.1' already exists. Skipping...
Folder 'GCA_004903115.1_PDT000428388.1' already exists. Skipping...
Folder 'GCA_004903135.1_PDT000428397.1' already exists. Skipping...
Folder 'GCA_004903165.1_PDT000428494.1' already exists. Skipping...
Folder 'GCA_004903195.1_PDT000428957.1' already exists. Skipping...
Folder 'GCA_004903235.1_PDT000428971.1' already exists. Skipping...
Folder 'GCA_004903255.1_PDT000428923.1' already exists. Skipping...
Folder 'GCA_004903315.1_PDT000428944.1' already exists. Skipping...
Folder 'GCA_004903335.1_PDT000428973.1' already exists. Skipping...
Folder 'GCA_004903355.1_PDT000428959.1' already exists. Skipping...
Folder 'GCA_004903375.1_PDT000428928.1' already exists. Skipping...
Folder 'GCA_004903395.1_PDT000428972.1' already exists. Skipping...
Folder 'GCA_004903415.1_PDT000428938.1' already exists. Skipping...
Folder 'GCA_004903435.1_PDT000428941.1' already exists. Skipping...
Folder 'GCA_004903455.1_PDT000428942.1' already exists. Skipping...
Folder 'GCA_004903465.1_PDT000428949.1' already exists. Skipping...
Folder 'GCA_004903495.1_PDT000428950.1' already exists. Skipping...
Folder 'GCA_004903515.1_PDT000428985.1' already exists. Skipping...
Folder 'GCA_004903535.1_PDT000428953.1' already exists. Skipping...
Folder 'GCA_004903555.1_PDT000428963.1' already exists. Skipping...
Folder 'GCA_004903575.1_PDT000428954.1' already exists. Skipping...
Folder 'GCA_004903595.1_PDT000428976.1' already exists. Skipping...
Folder 'GCA_004903615.1_PDT000428964.1' already exists. Skipping...
Folder 'GCA_004903635.1_PDT000428969.1' already exists. Skipping...
Folder 'GCA_004903655.1_PDT000428978.1' already exists. Skipping...
Folder 'GCA_004903675.1_PDT000428988.1' already exists. Skipping...
Folder 'GCA_004903695.1_PDT000428979.1' already exists. Skipping...
Folder 'GCA_004903715.1_PDT000428990.1' already exists. Skipping...
Folder 'GCA_004903735.1_PDT000478426.1' already exists. Skipping...
Folder 'GCA_004903745.1_PDT000478424.1' already exists. Skipping...
Folder 'GCA_004903775.1_PDT000478428.1' already exists. Skipping...
Folder 'GCA_004903785.1_PDT000478427.1' already exists. Skipping...
Folder 'GCA_004903815.1_PDT000478412.1' already exists. Skipping...
Folder 'GCA_004903835.1_PDT000478419.1' already exists. Skipping...
Folder 'GCA_004903855.1_PDT000478418.1' already exists. Skipping...
Folder 'GCA_004903875.1_PDT000478415.1' already exists. Skipping...
Folder 'GCA_004903895.1_PDT000478413.1' already exists. Skipping...
Folder 'GCA_004903915.1_PDT000478417.1' already exists. Skipping...
Folder 'GCA_004903935.1_PDT000478421.1' already exists. Skipping...
Folder 'GCA_004903955.1_PDT000478416.1' already exists. Skipping...
Folder 'GCA_004903975.1_PDT000421700.1' already exists. Skipping...
Folder 'GCA_004903995.1_PDT000478425.1' already exists. Skipping...
Folder 'GCA_004904005.1_PDT000478423.1' already exists. Skipping...
Folder 'GCA_004904035.1_PDT000421704.1' already exists. Skipping...
Folder 'GCA_004904055.1_PDT000421705.1' already exists. Skipping...
Folder 'GCA_004904075.1_PDT000422007.1' already exists. Skipping...
Folder 'GCA_004904095.1_PDT000421707.1' already exists. Skipping...
Folder 'GCA_004904115.1_PDT000421710.1' already exists. Skipping...
Folder 'GCA_004904135.1_PDT000421711.1' already exists. Skipping...
Folder 'GCA_004904155.1_PDT000421706.1' already exists. Skipping...
Folder 'GCA_004904175.1_PDT000421718.1' already exists. Skipping...
Folder 'GCA_004904195.1_PDT000421713.1' already exists. Skipping...
Folder 'GCA_004904215.1_PDT000421712.1' already exists. Skipping...
Folder 'GCA_004904235.1_PDT000421721.1' already exists. Skipping...
Folder 'GCA_004904255.1_PDT000430074.1' already exists. Skipping...
Folder 'GCA_004904275.1_PDT000421720.1' already exists. Skipping...
Folder 'GCA_004904295.1_PDT000421820.1' already exists. Skipping...
Folder 'GCA_004904315.1_PDT000421731.1' already exists. Skipping...
Folder 'GCA_004904335.1_PDT000421724.1' already exists. Skipping...
Folder 'GCA_004904355.1_PDT000421729.1' already exists. Skipping...
Folder 'GCA_004904375.1_PDT000421732.1' already exists. Skipping...
Folder 'GCA_004904395.1_PDT000421734.1' already exists. Skipping...
Folder 'GCA_004904415.1_PDT000421738.1' already exists. Skipping...
Folder 'GCA_004904435.1_PDT000422000.1' already exists. Skipping...
Folder 'GCA_004904455.1_PDT000421990.1' already exists. Skipping...
Folder 'GCA_004904485.1_PDT000421996.1' already exists. Skipping...
Folder 'GCA_004904535.1_PDT000422003.1' already exists. Skipping...
Folder 'GCA_004904555.1_PDT000429028.1' already exists. Skipping...
Folder 'GCA_004904575.1_PDT000431632.1' already exists. Skipping...
Folder 'GCA_004904595.1_PDT000430087.1' already exists. Skipping...
Folder 'GCA_004904605.1_PDT000429039.1' already exists. Skipping...
Folder 'GCA_004904635.1_PDT000428997.1' already exists. Skipping...
Folder 'GCA_004904655.1_PDT000429026.1' already exists. Skipping...
Folder 'GCA_004904675.1_PDT000430103.1' already exists. Skipping...
Folder 'GCA_004904685.1_PDT000429012.1' already exists. Skipping...
Folder 'GCA_004904715.1_PDT000429001.1' already exists. Skipping...
Folder 'GCA_004904735.1_PDT000428994.1' already exists. Skipping...
Folder 'GCA_004904755.1_PDT000428992.1' already exists. Skipping...
Folder 'GCA_004904775.1_PDT000429038.1' already exists. Skipping...

Retreiveing data: 40317it [00:07, 6647.91it/s]

Folder 'GCA_004940205.1_PDT000153011.2' already exists. Skipping...
Folder 'GCA_004940225.1_PDT000153003.2' already exists. Skipping...
Folder 'GCA_004940245.1_PDT000153015.2' already exists. Skipping...
Folder 'GCA_004940265.1_PDT000153087.2' already exists. Skipping...
Folder 'GCA_004940305.1_PDT000153103.2' already exists. Skipping...
Folder 'GCA_004940345.1_PDT000153101.2' already exists. Skipping...
Folder 'GCA_004940365.1_PDT000153107.2' already exists. Skipping...
Folder 'GCA_004940405.1_PDT000153208.2' already exists. Skipping...
Folder 'GCA_004940425.1_PDT000154117.2' already exists. Skipping...
Folder 'GCA_004940445.1_PDT000153110.2' already exists. Skipping...
Folder 'GCA_004940465.1_PDT000153111.2' already exists. Skipping...
Folder 'GCA_004940505.1_PDT000153210.2' already exists. Skipping...
Folder 'GCA_004940525.1_PDT000153207.2' already exists. Skipping...
Folder 'GCA_004940545.1_PDT000153113.2' already exists. Skipping...
Folder 'GCA_004940585.1_PDT000154118.2' already exists. Skipping...
Folder 'GCA_004940605.1_PDT000154123.2' already exists. Skipping...
Folder 'GCA_004940645.1_PDT000154463.2' already exists. Skipping...
Folder 'GCA_004940665.1_PDT000154200.2' already exists. Skipping...
Folder 'GCA_004940685.1_PDT000158496.2' already exists. Skipping...
Folder 'GCA_004940705.1_PDT000154931.2' already exists. Skipping...
Folder 'GCA_004940765.1_PDT000154199.2' already exists. Skipping...
Folder 'GCA_004940805.1_PDT000158544.2' already exists. Skipping...
Folder 'GCA_004940825.1_PDT000162129.2' already exists. Skipping...
Folder 'GCA_004940845.1_PDT000158491.2' already exists. Skipping...
Folder 'GCA_004940865.1_PDT000158548.2' already exists. Skipping...
Folder 'GCA_004940885.1_PDT000154932.2' already exists. Skipping...
Folder 'GCA_004940905.1_PDT000158513.2' already exists. Skipping...
Folder 'GCA_004940985.1_PDT000162351.2' already exists. Skipping...
Folder 'GCA_004941005.1_PDT000162353.2' already exists. Skipping...
Folder 'GCA_004941025.1_PDT000162355.2' already exists. Skipping...
Folder 'GCA_004941045.1_PDT000162357.2' already exists. Skipping...
Folder 'GCA_004941065.1_PDT000162354.2' already exists. Skipping...
Folder 'GCA_004941105.1_PDT000162364.2' already exists. Skipping...
Folder 'GCA_004941125.1_PDT000162367.2' already exists. Skipping...
Folder 'GCA_004941145.1_PDT000162365.2' already exists. Skipping...
Folder 'GCA_004941165.1_PDT000162360.2' already exists. Skipping...
Folder 'GCA_004941185.1_PDT000162395.2' already exists. Skipping...
Folder 'GCA_004941225.1_PDT000162394.2' already exists. Skipping...
Folder 'GCA_004941245.1_PDT000162397.2' already exists. Skipping...
Folder 'GCA_004941255.1_PDT000162398.2' already exists. Skipping...
Folder 'GCA_004941285.1_PDT000143635.2' already exists. Skipping...
Folder 'GCA_004941305.1_PDT000137448.2' already exists. Skipping...
Folder 'GCA_004941315.1_PDT000143638.2' already exists. Skipping...
Folder 'GCA_004941345.1_PDT000137444.2' already exists. Skipping...
Folder 'GCA_004941365.1_PDT000137454.2' already exists. Skipping...
Folder 'GCA_004941385.1_PDT000145225.2' already exists. Skipping...
Folder 'GCA_004941445.1_PDT000171392.2' already exists. Skipping...
Folder 'GCA_004941465.1_PDT000162718.2' already exists. Skipping...
Folder 'GCA_004941485.1_PDT000143640.2' already exists. Skipping...
Folder 'GCA_004941505.1_PDT000143636.2' already exists. Skipping...
Folder 'GCA_004941545.1_PDT000162724.2' already exists. Skipping...
Folder 'GCA_004941565.1_PDT000145960.2' already exists. Skipping...
Folder 'GCA_004941575.1_PDT000162723.2' already exists. Skipping...
Folder 'GCA_004941605.1_PDT000173384.2' already exists. Skipping...
Folder 'GCA_004941625.1_PDT000146082.2' already exists. Skipping...
Folder 'GCA_004941645.1_PDT000145210.2' already exists. Skipping...
Folder 'GCA_004941665.1_PDT000163404.2' already exists. Skipping...
Folder 'GCA_004941685.1_PDT000179218.2' already exists. Skipping...
Folder 'GCA_004941705.1_PDT000187933.2' already exists. Skipping...
Folder 'GCA_004941725.1_PDT000162542.2' already exists. Skipping...
Folder 'GCA_004941745.1_PDT000168593.2' already exists. Skipping...
Folder 'GCA_004941765.1_PDT000178451.2' already exists. Skipping...
Folder 'GCA_004941785.1_PDT000173260.2' already exists. Skipping...
Folder 'GCA_004941805.1_PDT000181046.2' already exists. Skipping...
Folder 'GCA_004941825.1_PDT000178459.2' already exists. Skipping...
Folder 'GCA_004941845.1_PDT000175428.2' already exists. Skipping...
Folder 'GCA_004941865.1_PDT000185745.2' already exists. Skipping...
Folder 'GCA_004941885.1_PDT000177212.2' already exists. Skipping...
Folder 'GCA_004941905.1_PDT000167779.2' already exists. Skipping...
Folder 'GCA_004941925.1_PDT000171387.2' already exists. Skipping...
Folder 'GCA_004941965.1_PDT000176277.2' already exists. Skipping...
Folder 'GCA_004941985.1_PDT000174033.2' already exists. Skipping...
Folder 'GCA_004942005.1_PDT000171874.2' already exists. Skipping...
Folder 'GCA_004942025.1_PDT000152314.2' already exists. Skipping...
Folder 'GCA_004942045.1_PDT000152318.2' already exists. Skipping...
Folder 'GCA_004942065.1_PDT000152323.2' already exists. Skipping...
Folder 'GCA_004942085.1_PDT000152308.2' already exists. Skipping...
Folder 'GCA_004942105.1_PDT000171782.2' already exists. Skipping...
Folder 'GCA_004942125.1_PDT000152319.2' already exists. Skipping...
Folder 'GCA_004942135.1_PDT000162738.2' already exists. Skipping...
Folder 'GCA_004942165.1_PDT000179229.2' already exists. Skipping...
Folder 'GCA_004942205.1_PDT000162322.2' already exists. Skipping...
Folder 'GCA_004942225.1_PDT000162314.2' already exists. Skipping...
Folder 'GCA_004942265.1_PDT000162317.2' already exists. Skipping...
Folder 'GCA_004942285.1_PDT000178447.2' already exists. Skipping...
Folder 'GCA_004942305.1_PDT000173383.2' already exists. Skipping...
Folder 'GCA_004942325.1_PDT000162324.2' already exists. Skipping...
Folder 'GCA_004942345.1_PDT000162316.2' already exists. Skipping...
Folder 'GCA_004942365.1_PDT000174029.2' already exists. Skipping...
Folder 'GCA_004942385.1_PDT000175562.2' already exists. Skipping...
Folder 'GCA_004942405.1_PDT000162323.2' already exists. Skipping...
Folder 'GCA_004942425.1_PDT000173271.2' already exists. Skipping...
Folder 'GCA_004942445.1_PDT000175415.2' already exists. Skipping...
Folder 'GCA_004942465.1_PDT000176445.2' already exists. Skipping...
Folder 'GCA_004942485.1_PDT000162373.2' already exists. Skipping...
Folder 'GCA_004942505.1_PDT000175569.2' already exists. Skipping...
Folder 'GCA_004942525.1_PDT000187323.2' already exists. Skipping...
Folder 'GCA_004942545.1_PDT000176298.2' already exists. Skipping...
Folder 'GCA_004942605.1_PDT000171402.2' already exists. Skipping...
Folder 'GCA_004942625.1_PDT000177201.2' already exists. Skipping...
Folder 'GCA_004942645.1_PDT000171386.2' already exists. Skipping...
Folder 'GCA_004942685.1_PDT000188413.2' already exists. Skipping...
Folder 'GCA_004942705.1_PDT000171397.2' already exists. Skipping...
Folder 'GCA_004942725.1_PDT000175420.2' already exists. Skipping...
Folder 'GCA_004942745.1_PDT000176442.2' already exists. Skipping...
Folder 'GCA_004942785.1_PDT000179234.2' already exists. Skipping...
Folder 'GCA_004942795.1_PDT000179196.2' already exists. Skipping...
Folder 'GCA_004942825.1_PDT000175558.2' already exists. Skipping...
Folder 'GCA_004942845.1_PDT000183211.2' already exists. Skipping...
Folder 'GCA_004942865.1_PDT000171391.2' already exists. Skipping...
Folder 'GCA_004942885.1_PDT000173281.2' already exists. Skipping...
Folder 'GCA_004942895.1_PDT000175547.2' already exists. Skipping...
Folder 'GCA_004942925.1_PDT000163400.2' already exists. Skipping...
Folder 'GCA_004942965.1_PDT000181058.2' already exists. Skipping...
Folder 'GCA_004943025.1_PDT000175578.2' already exists. Skipping...
Folder 'GCA_004943045.1_PDT000167794.2' already exists. Skipping...
Folder 'GCA_004943065.1_PDT000173385.2' already exists. Skipping...
Folder 'GCA_004943085.1_PDT000185454.2' already exists. Skipping...
Folder 'GCA_004943105.1_PDT000181624.2' already exists. Skipping...
Folder 'GCA_004943145.1_PDT000171407.2' already exists. Skipping...
Folder 'GCA_004943165.1_PDT000178465.2' already exists. Skipping...
Folder 'GCA_004943185.1_PDT000183210.2' already exists. Skipping...
Folder 'GCA_004943205.1_PDT000171396.2' already exists. Skipping...
Folder 'GCA_004943225.1_PDT000167771.2' already exists. Skipping...
Folder 'GCA_004943245.1_PDT000173276.2' already exists. Skipping...
Folder 'GCA_004943265.1_PDT000179200.2' already exists. Skipping...
Folder 'GCA_004943305.1_PDT000174445.2' already exists. Skipping...
Folder 'GCA_004943345.1_PDT000162529.2' already exists. Skipping...
Folder 'GCA_004943365.1_PDT000181621.2' already exists. Skipping...
Folder 'GCA_004943405.1_PDT000163394.2' already exists. Skipping...
Folder 'GCA_004943425.1_PDT000183204.2' already exists. Skipping...
Folder 'GCA_004943445.1_PDT000176440.2' already exists. Skipping...
Folder 'GCA_004943455.1_PDT000184401.2' already exists. Skipping...
Folder 'GCA_004943505.1_PDT000181606.2' already exists. Skipping...
Folder 'GCA_004943525.1_PDT000168588.2' already exists. Skipping...
Folder 'GCA_004943555.1_PDT000184400.2' already exists. Skipping...
Folder 'GCA_004943585.1_PDT000179230.2' already exists. Skipping...
Folder 'GCA_004943645.1_PDT000178464.2' already exists. Skipping...
Folder 'GCA_004943665.1_PDT000167798.2' already exists. Skipping...
Folder 'GCA_004943675.1_PDT000174028.2' already exists. Skipping...
Folder 'GCA_004943725.1_PDT000175423.2' already exists. Skipping...
Folder 'GCA_004943745.1_PDT000181152.2' already exists. Skipping...
Folder 'GCA_004943765.1_PDT000181617.2' already exists. Skipping...
Folder 'GCA_004943785.1_PDT000184395.2' already exists. Skipping...
Folder 'GCA_004943805.1_PDT000188932.2' already exists. Skipping...
Folder 'GCA_004943845.1_PDT000188444.2' already exists. Skipping...
Folder 'GCA_004943865.1_PDT000188425.2' already exists. Skipping...
Folder 'GCA_004943885.1_PDT000188456.2' already exists. Skipping...
Folder 'GCA_004943905.1_PDT000181063.2' already exists. Skipping...
Folder 'GCA_004943925.1_PDT000188928.2' already exists. Skipping...
Folder 'GCA_004943945.1_PDT000185452.2' already exists. Skipping...
Folder 'GCA_004944025.1_PDT000181604.2' already exists. Skipping...
Folder 'GCA_004944035.1_PDT000174446.2' already exists. Skipping...
Folder 'GCA_004944065.1_PDT000187936.2' already exists. Skipping...
Folder 'GCA_004944085.1_PDT000178457.2' already exists. Skipping...
Folder 'GCA_004944165.1_PDT000179245.2' already exists. Skipping...
Folder 'GCA_004944225.1_PDT000188401.2' already exists. Skipping...
Folder 'GCA_004944245.1_PDT000178460.2' already exists. Skipping...
Folder 'GCA_004944285.1_PDT000185453.2' already exists. Skipping...
Folder 'GCA_004944325.1_PDT000181056.2' already exists. Skipping...
Folder 'GCA_004944385.1_PDT000173272.2' already exists. Skipping...
Folder 'GCA_004944405.1_PDT000162536.2' already exists. Skipping...
Folder 'GCA_004944425.1_PDT000181052.2' already exists. Skipping...
Folder 'GCA_004944465.1_PDT000179253.2' already exists. Skipping...
Folder 'GCA_004944505.1_PDT000181150.2' already exists. Skipping...
Folder 'GCA_004944525.1_PDT000179240.2' already exists. Skipping...
Folder 'GCA_004944565.1_PDT000171382.2' already exists. Skipping...
Folder 'GCA_004944585.1_PDT000185449.2' already exists. Skipping...
Folder 'GCA_004944605.1_PDT000184408.2' already exists. Skipping...
Folder 'GCA_004944625.1_PDT000188433.2' already exists. Skipping...
Folder 'GCA_004944665.1_PDT000184403.2' already exists. Skipping...
Folder 'GCA_004944685.1_PDT000188426.2' already exists. Skipping...
Folder 'GCA_004944705.1_PDT000187333.2' already exists. Skipping...
Folder 'GCA_004944725.1_PDT000179255.2' already exists. Skipping...
Folder 'GCA_004944745.1_PDT000188408.2' already exists. Skipping...
Folder 'GCA_004944765.1_PDT000179252.2' already exists. Skipping...
Folder 'GCA_004944785.1_PDT000187343.2' already exists. Skipping...
Folder 'GCA_004944805.1_PDT000178771.2' already exists. Skipping...
Folder 'GCA_004944825.1_PDT000190628.2' already exists. Skipping...
Folder 'GCA_004944865.1_PDT000171406.2' already exists. Skipping...
Folder 'GCA_004944925.1_PDT000198224.2' already exists. Skipping...
Folder 'GCA_004944945.1_PDT000199946.2' already exists. Skipping...
Folder 'GCA_004944965.1_PDT000199586.2' already exists. Skipping...
Folder 'GCA_004944995.1_PDT000199614.2' already exists. Skipping...
Folder 'GCA_004945025.1_PDT000199947.2' already exists. Skipping...
Folder 'GCA_004945045.1_PDT000198217.2' already exists. Skipping...
Folder 'GCA_004945065.1_PDT000199945.2' already exists. Skipping...
Folder 'GCA_004945085.1_PDT000199967.2' already exists. Skipping...
Folder 'GCA_004945105.1_PDT000199957.2' already exists. Skipping...
Folder 'GCA_004945125.1_PDT000199618.2' already exists. Skipping...
Folder 'GCA_004945145.1_PDT000199599.2' already exists. Skipping...
Folder 'GCA_004945165.1_PDT000198216.2' already exists. Skipping...
Folder 'GCA_004945225.1_PDT000198033.2' already exists. Skipping...
Folder 'GCA_004945245.1_PDT000199961.2' already exists. Skipping...
Folder 'GCA_004945265.1_PDT000190075.2' already exists. Skipping...
Folder 'GCA_004945275.1_PDT000198030.2' already exists. Skipping...
Folder 'GCA_004945325.1_PDT000190631.2' already exists. Skipping...
Folder 'GCA_004945345.1_PDT000190077.2' already exists. Skipping...
Folder 'GCA_004945355.1_PDT000190748.2' already exists. Skipping...
Folder 'GCA_004945385.1_PDT000190765.2' already exists. Skipping...
Folder 'GCA_004945405.1_PDT000190768.2' already exists. Skipping...
Folder 'GCA_004945425.1_PDT000193609.2' already exists. Skipping...
Folder 'GCA_004945465.1_PDT000192366.2' already exists. Skipping...
Folder 'GCA_004945545.1_PDT000196408.2' already exists. Skipping...
Folder 'GCA_004945565.1_PDT000193644.2' already exists. Skipping...
Folder 'GCA_004945585.1_PDT000192390.2' already exists. Skipping...
Folder 'GCA_004945605.1_PDT000193511.2' already exists. Skipping...
Folder 'GCA_004945655.1_PDT000198236.2' already exists. Skipping...
Folder 'GCA_004945685.1_PDT000198229.2' already exists. Skipping...
Folder 'GCA_004945705.1_PDT000198994.2' already exists. Skipping...
Folder 'GCA_004945725.1_PDT000197891.2' already exists. Skipping...
Folder 'GCA_004945785.1_PDT000197893.2' already exists. Skipping...
Folder 'GCA_004945805.1_PDT000199464.2' already exists. Skipping...
Folder 'GCA_004945825.1_PDT000199489.2' already exists. Skipping...
Folder 'GCA_004945845.1_PDT000198997.2' already exists. Skipping...
Folder 'GCA_004945865.1_PDT000199466.2' already exists. Skipping...
Folder 'GCA_004945885.1_PDT000199158.2' already exists. Skipping...
Folder 'GCA_004945965.1_PDT000199217.2' already exists. Skipping...
Folder 'GCA_004945985.1_PDT000199482.2' already exists. Skipping...
Folder 'GCA_004946015.1_PDT000199479.2' already exists. Skipping...
Folder 'GCA_004946045.1_PDT000199000.2' already exists. Skipping...
Folder 'GCA_004946065.1_PDT000199462.2' already exists. Skipping...
Folder 'GCA_004946105.1_PDT000199494.2' already exists. Skipping...
Folder 'GCA_004946125.1_PDT000199496.2' already exists. Skipping...
Folder 'GCA_004946145.1_PDT000199477.2' already exists. Skipping...
Folder 'GCA_004946165.1_PDT000199497.2' already exists. Skipping...
Folder 'GCA_004946185.1_PDT000199534.2' already exists. Skipping...
Folder 'GCA_004946265.1_PDT000199513.2' already exists. Skipping...
Folder 'GCA_004946285.1_PDT000199524.2' already exists. Skipping...
Folder 'GCA_004946345.1_PDT000199527.2' already exists. Skipping...
Folder 'GCA_004946365.1_PDT000199544.2' already exists. Skipping...
Folder 'GCA_004946385.1_PDT000199556.2' already exists. Skipping...
Folder 'GCA_004946425.1_PDT000199559.2' already exists. Skipping...
Folder 'GCA_004946465.1_PDT000199561.2' already exists. Skipping...
Folder 'GCA_004946525.1_PDT000199615.2' already exists. Skipping...
Folder 'GCA_004946545.1_PDT000199581.2' already exists. Skipping...
Folder 'GCA_004946565.1_PDT000199584.2' already exists. Skipping...
Folder 'GCA_004946575.1_PDT000199562.2' already exists. Skipping...
Folder 'GCA_004946605.1_PDT000199624.2' already exists. Skipping...
Folder 'GCA_004946625.1_PDT000199616.2' already exists. Skipping...
Folder 'GCA_004946725.1_PDT000199889.2' already exists. Skipping...
Folder 'GCA_004946805.1_PDT000199621.2' already exists. Skipping...
Folder 'GCA_004946845.1_PDT000199887.2' already exists. Skipping...
Folder 'GCA_004946865.1_PDT000199893.2' already exists. Skipping...
Folder 'GCA_004946885.1_PDT000199894.2' already exists. Skipping...
Folder 'GCA_004946925.1_PDT000199895.2' already exists. Skipping...
Folder 'GCA_004947025.1_PDT000199900.2' already exists. Skipping...
Folder 'GCA_004947045.1_PDT000199912.2' already exists. Skipping...
Folder 'GCA_004947085.1_PDT000199909.2' already exists. Skipping...
Folder 'GCA_004947105.1_PDT000199922.2' already exists. Skipping...
Folder 'GCA_004947125.1_PDT000199913.2' already exists. Skipping...
Folder 'GCA_004947145.1_PDT000199914.2' already exists. Skipping...
Folder 'GCA_004947185.1_PDT000199930.2' already exists. Skipping...
Folder 'GCA_004947245.1_PDT000199931.2' already exists. Skipping...
Folder 'GCA_004947265.1_PDT000199929.2' already exists. Skipping...
Folder 'GCA_004947285.1_PDT000199920.2' already exists. Skipping...
Folder 'GCA_004947345.1_PDT000199934.2' already exists. Skipping...
Folder 'GCA_004947385.1_PDT000199940.2' already exists. Skipping...
Folder 'GCA_004947405.1_PDT000199969.2' already exists. Skipping...
Folder 'GCA_004947425.1_PDT000199944.2' already exists. Skipping...
Folder 'GCA_004947445.1_PDT000199968.2' already exists. Skipping...
Folder 'GCA_004947505.1_PDT000199962.2' already exists. Skipping...
Folder 'GCA_004947525.1_PDT000199981.2' already exists. Skipping...
Folder 'GCA_004947565.1_PDT000199983.2' already exists. Skipping...
Folder 'GCA_004947585.1_PDT000199985.2' already exists. Skipping...
Folder 'GCA_004947625.1_PDT000200016.2' already exists. Skipping...
Folder 'GCA_004947645.1_PDT000200002.2' already exists. Skipping...
Folder 'GCA_004947655.1_PDT000200004.2' already exists. Skipping...
Folder 'GCA_004947685.1_PDT000200009.2' already exists. Skipping...
Folder 'GCA_004947725.1_PDT000199998.2' already exists. Skipping...
Folder 'GCA_004947745.1_PDT000200008.2' already exists. Skipping...
Folder 'GCA_004947805.1_PDT000200424.2' already exists. Skipping...
Folder 'GCA_004947825.1_PDT000200423.2' already exists. Skipping...
Folder 'GCA_004947865.1_PDT000200420.2' already exists. Skipping...
Folder 'GCA_004947885.1_PDT000200439.2' already exists. Skipping...
Folder 'GCA_004947905.1_PDT000200427.2' already exists. Skipping...
Folder 'GCA_004947965.1_PDT000200039.2' already exists. Skipping...
Folder 'GCA_004948005.1_PDT000200402.2' already exists. Skipping...
Folder 'GCA_004948025.1_PDT000200412.2' already exists. Skipping...
Folder 'GCA_004948045.1_PDT000200379.2' already exists. Skipping...
Folder 'GCA_004948105.1_PDT000200403.2' already exists. Skipping...
Folder 'GCA_004948125.1_PDT000200044.2' already exists. Skipping...
Folder 'GCA_004948145.1_PDT000200414.2' already exists. Skipping...
Folder 'GCA_004948165.1_PDT000200444.2' already exists. Skipping...
Folder 'GCA_004948205.1_PDT000200449.2' already exists. Skipping...
Folder 'GCA_004948225.1_PDT000200399.2' already exists. Skipping...
Folder 'GCA_004948235.1_PDT000200019.2' already exists. Skipping...
Folder 'GCA_004948285.1_PDT000200384.2' already exists. Skipping...
Folder 'GCA_004948325.1_PDT000200022.2' already exists. Skipping...
Folder 'GCA_004948335.1_PDT000200425.2' already exists. Skipping...
Folder 'GCA_004948385.1_PDT000200021.2' already exists. Skipping...
Folder 'GCA_004948405.1_PDT000200378.2' already exists. Skipping...
Folder 'GCA_004948425.1_PDT000200036.2' already exists. Skipping...
Folder 'GCA_004948465.1_PDT000200404.2' already exists. Skipping...

Retreiveing data: 41648it [00:07, 6646.04it/s]

Folder 'GCA_004988305.1_PDT000271470.2' already exists. Skipping...
Folder 'GCA_004988325.1_PDT000271510.2' already exists. Skipping...
Folder 'GCA_004988405.1_PDT000271531.2' already exists. Skipping...
Folder 'GCA_004988505.1_PDT000271699.2' already exists. Skipping...
Folder 'GCA_004988705.1_PDT000272463.2' already exists. Skipping...
Folder 'GCA_004988765.1_PDT000272469.2' already exists. Skipping...
Folder 'GCA_004988785.1_PDT000272484.2' already exists. Skipping...
Folder 'GCA_004988805.1_PDT000272476.2' already exists. Skipping...
Folder 'GCA_004988825.1_PDT000272468.2' already exists. Skipping...
Folder 'GCA_004988845.1_PDT000272481.2' already exists. Skipping...
Folder 'GCA_004988865.1_PDT000272483.2' already exists. Skipping...
Folder 'GCA_004988885.1_PDT000272482.2' already exists. Skipping...
Folder 'GCA_004988905.1_PDT000272486.2' already exists. Skipping...
Folder 'GCA_004988925.1_PDT000272485.2' already exists. Skipping...
Folder 'GCA_004988985.1_PDT000272496.2' already exists. Skipping...
Folder 'GCA_004989085.1_PDT000273333.2' already exists. Skipping...
Folder 'GCA_004989125.1_PDT000273482.2' already exists. Skipping...
Folder 'GCA_004989145.1_PDT000273474.2' already exists. Skipping...
Folder 'GCA_004989165.1_PDT000273475.2' already exists. Skipping...
Folder 'GCA_004989185.1_PDT000273471.2' already exists. Skipping...
Folder 'GCA_004989225.1_PDT000273334.2' already exists. Skipping...
Folder 'GCA_004989785.1_PDT000274827.2' already exists. Skipping...
Folder 'GCA_004989805.1_PDT000274565.2' already exists. Skipping...
Folder 'GCA_004989845.1_PDT000274895.2' already exists. Skipping...
Folder 'GCA_004989865.1_PDT000274564.2' already exists. Skipping...
Folder 'GCA_004989885.1_PDT000278361.2' already exists. Skipping...
Folder 'GCA_004989945.1_PDT000273754.2' already exists. Skipping...
Folder 'GCA_004989965.1_PDT000274539.2' already exists. Skipping...
Folder 'GCA_004990005.1_PDT000278360.2' already exists. Skipping...
Folder 'GCA_004990025.1_PDT000273717.2' already exists. Skipping...
Folder 'GCA_004990045.1_PDT000274569.2' already exists. Skipping...
Folder 'GCA_004990065.1_PDT000273708.2' already exists. Skipping...
Folder 'GCA_004990185.1_PDT000273724.2' already exists. Skipping...
Folder 'GCA_004990205.1_PDT000274316.2' already exists. Skipping...
Folder 'GCA_004990245.1_PDT000273731.2' already exists. Skipping...
Folder 'GCA_004990255.1_PDT000274567.2' already exists. Skipping...
Folder 'GCA_004990325.1_PDT000274826.2' already exists. Skipping...
Folder 'GCA_004990345.1_PDT000281113.2' already exists. Skipping...
Folder 'GCA_004990365.1_PDT000274898.2' already exists. Skipping...
Folder 'GCA_004990385.1_PDT000273732.2' already exists. Skipping...
Folder 'GCA_004990405.1_PDT000274314.2' already exists. Skipping...
Folder 'GCA_004990485.1_PDT000274721.2' already exists. Skipping...
Folder 'GCA_004990525.1_PDT000273714.2' already exists. Skipping...
Folder 'GCA_004990565.1_PDT000273689.2' already exists. Skipping...
Folder 'GCA_004990605.1_PDT000273721.2' already exists. Skipping...
Folder 'GCA_004990665.1_PDT000276543.2' already exists. Skipping...
Folder 'GCA_004990685.1_PDT000274545.2' already exists. Skipping...
Folder 'GCA_004990705.1_PDT000276866.2' already exists. Skipping...
Folder 'GCA_004990765.1_PDT000274308.2' already exists. Skipping...
Folder 'GCA_004990785.1_PDT000273762.2' already exists. Skipping...
Folder 'GCA_004990805.1_PDT000273702.2' already exists. Skipping...
Folder 'GCA_004990825.1_PDT000274820.2' already exists. Skipping...
Folder 'GCA_004990865.1_PDT000273761.2' already exists. Skipping...
Folder 'GCA_004990885.1_PDT000273748.2' already exists. Skipping...
Folder 'GCA_004990905.1_PDT000274824.2' already exists. Skipping...
Folder 'GCA_004990925.1_PDT000276570.2' already exists. Skipping...
Folder 'GCA_004990945.1_PDT000275577.2' already exists. Skipping...
Folder 'GCA_004991025.1_PDT000274904.2' already exists. Skipping...
Folder 'GCA_004991085.1_PDT000274971.2' already exists. Skipping...
Folder 'GCA_004991125.1_PDT000276865.2' already exists. Skipping...
Folder 'GCA_004991145.1_PDT000273756.2' already exists. Skipping...
Folder 'GCA_004991205.1_PDT000274568.2' already exists. Skipping...
Folder 'GCA_004991245.1_PDT000278366.2' already exists. Skipping...
Folder 'GCA_004991265.1_PDT000275583.2' already exists. Skipping...
Folder 'GCA_004991285.1_PDT000275578.2' already exists. Skipping...
Folder 'GCA_004991315.1_PDT000275573.2' already exists. Skipping...
Folder 'GCA_004991365.1_PDT000273734.2' already exists. Skipping...
Folder 'GCA_004991395.1_PDT000274897.2' already exists. Skipping...
Folder 'GCA_004991465.1_PDT000274549.2' already exists. Skipping...
Folder 'GCA_004991565.1_PDT000274566.2' already exists. Skipping...
Folder 'GCA_004991645.1_PDT000274823.2' already exists. Skipping...
Folder 'GCA_004991685.1_PDT000274312.2' already exists. Skipping...
Folder 'GCA_004991705.1_PDT000275575.2' already exists. Skipping...
Folder 'GCA_004991745.1_PDT000273760.2' already exists. Skipping...
Folder 'GCA_004991765.1_PDT000274964.2' already exists. Skipping...
Folder 'GCA_004991785.1_PDT000274903.2' already exists. Skipping...
Folder 'GCA_004991825.1_PDT000275994.2' already exists. Skipping...
Folder 'GCA_004991845.1_PDT000275581.2' already exists. Skipping...
Folder 'GCA_004991865.1_PDT000275990.2' already exists. Skipping...
Folder 'GCA_004991885.1_PDT000275996.2' already exists. Skipping...
Folder 'GCA_004991905.1_PDT000275582.2' already exists. Skipping...
Folder 'GCA_004991925.1_PDT000275995.2' already exists. Skipping...
Folder 'GCA_004991945.1_PDT000276002.2' already exists. Skipping...
Folder 'GCA_004991965.1_PDT000275998.2' already exists. Skipping...
Folder 'GCA_004992345.1_PDT000276873.2' already exists. Skipping...
Folder 'GCA_004992365.1_PDT000276871.2' already exists. Skipping...
Folder 'GCA_004992385.1_PDT000276559.2' already exists. Skipping...
Folder 'GCA_004992405.1_PDT000276885.2' already exists. Skipping...
Folder 'GCA_004992445.1_PDT000276868.2' already exists. Skipping...
Folder 'GCA_004992465.1_PDT000276891.2' already exists. Skipping...
Folder 'GCA_004992505.1_PDT000276955.2' already exists. Skipping...
Folder 'GCA_004992545.1_PDT000276894.2' already exists. Skipping...
Folder 'GCA_004992605.1_PDT000276940.2' already exists. Skipping...
Folder 'GCA_004992625.1_PDT000276968.2' already exists. Skipping...
Folder 'GCA_004992665.1_PDT000276942.2' already exists. Skipping...
Folder 'GCA_004992705.1_PDT000276999.2' already exists. Skipping...
Folder 'GCA_004992775.1_PDT000276965.2' already exists. Skipping...
Folder 'GCA_004992845.1_PDT000277010.2' already exists. Skipping...
Folder 'GCA_004992855.1_PDT000277689.2' already exists. Skipping...
Folder 'GCA_004992885.1_PDT000277009.2' already exists. Skipping...
Folder 'GCA_004992925.1_PDT000277698.2' already exists. Skipping...
Folder 'GCA_004992945.1_PDT000277764.2' already exists. Skipping...
Folder 'GCA_004992965.1_PDT000277766.2' already exists. Skipping...
Folder 'GCA_004992985.1_PDT000277761.2' already exists. Skipping...
Folder 'GCA_004993005.1_PDT000277767.2' already exists. Skipping...
Folder 'GCA_004993025.1_PDT000277769.2' already exists. Skipping...
Folder 'GCA_004993045.1_PDT000277774.2' already exists. Skipping...
Folder 'GCA_004993065.1_PDT000277776.2' already exists. Skipping...
Folder 'GCA_004993085.1_PDT000277770.2' already exists. Skipping...
Folder 'GCA_004993105.1_PDT000278353.2' already exists. Skipping...
Folder 'GCA_004993125.1_PDT000278365.2' already exists. Skipping...
Folder 'GCA_004993145.1_PDT000278664.2' already exists. Skipping...
Folder 'GCA_004993185.1_PDT000277778.2' already exists. Skipping...
Folder 'GCA_004993225.1_PDT000278697.2' already exists. Skipping...
Folder 'GCA_004993255.1_PDT000278701.2' already exists. Skipping...
Folder 'GCA_004993305.1_PDT000278698.2' already exists. Skipping...
Folder 'GCA_004993345.1_PDT000279723.2' already exists. Skipping...
Folder 'GCA_004993365.1_PDT000278364.2' already exists. Skipping...
Folder 'GCA_004993385.1_PDT000280484.2' already exists. Skipping...
Folder 'GCA_004993405.1_PDT000278703.2' already exists. Skipping...
Folder 'GCA_004993445.1_PDT000278663.2' already exists. Skipping...
Folder 'GCA_004993465.1_PDT000280490.2' already exists. Skipping...
Folder 'GCA_004993485.1_PDT000278374.2' already exists. Skipping...
Folder 'GCA_004993505.1_PDT000280492.2' already exists. Skipping...
Folder 'GCA_004993525.1_PDT000280485.2' already exists. Skipping...
Folder 'GCA_004993565.1_PDT000281015.2' already exists. Skipping...
Folder 'GCA_004993585.1_PDT000281017.2' already exists. Skipping...
Folder 'GCA_004993605.1_PDT000281013.2' already exists. Skipping...
Folder 'GCA_004993645.1_PDT000281035.2' already exists. Skipping...
Folder 'GCA_004993675.1_PDT000281024.2' already exists. Skipping...
Folder 'GCA_004993725.1_PDT000281038.2' already exists. Skipping...
Folder 'GCA_004993745.1_PDT000281022.2' already exists. Skipping...
Folder 'GCA_004993805.1_PDT000281051.2' already exists. Skipping...
Folder 'GCA_004993825.1_PDT000281062.2' already exists. Skipping...
Folder 'GCA_004993845.1_PDT000281046.2' already exists. Skipping...
Folder 'GCA_004993925.1_PDT000281064.2' already exists. Skipping...
Folder 'GCA_004993945.1_PDT000281096.2' already exists. Skipping...
Folder 'GCA_004994005.1_PDT000281076.2' already exists. Skipping...
Folder 'GCA_004994065.1_PDT000276876.2' already exists. Skipping...
Folder 'GCA_004994085.1_PDT000276882.2' already exists. Skipping...
Folder 'GCA_004994105.1_PDT000276878.2' already exists. Skipping...
Folder 'GCA_004994115.1_PDT000276881.2' already exists. Skipping...
Folder 'GCA_004994165.1_PDT000281442.2' already exists. Skipping...
Folder 'GCA_004994185.1_PDT000281434.2' already exists. Skipping...
Folder 'GCA_004994205.1_PDT000274563.2' already exists. Skipping...
Folder 'GCA_004994265.1_PDT000281428.2' already exists. Skipping...
Folder 'GCA_004994405.1_PDT000281254.2' already exists. Skipping...
Folder 'GCA_004994435.1_PDT000281260.2' already exists. Skipping...
Folder 'GCA_004994485.1_PDT000281286.2' already exists. Skipping...
Folder 'GCA_004994505.1_PDT000281273.2' already exists. Skipping...
Folder 'GCA_004994525.1_PDT000281276.2' already exists. Skipping...
Folder 'GCA_004994565.1_PDT000281284.2' already exists. Skipping...
Folder 'GCA_004994585.1_PDT000281281.2' already exists. Skipping...
Folder 'GCA_004994685.1_PDT000281300.2' already exists. Skipping...
Folder 'GCA_004994705.1_PDT000281310.2' already exists. Skipping...
Folder 'GCA_004994725.1_PDT000281293.2' already exists. Skipping...
Folder 'GCA_004994765.1_PDT000281305.2' already exists. Skipping...
Folder 'GCA_004994825.1_PDT000281311.2' already exists. Skipping...
Folder 'GCA_004994845.1_PDT000281317.2' already exists. Skipping...
Folder 'GCA_004994905.1_PDT000281325.2' already exists. Skipping...
Folder 'GCA_004994925.1_PDT000281318.2' already exists. Skipping...
Folder 'GCA_004994945.1_PDT000281315.2' already exists. Skipping...
Folder 'GCA_004995005.1_PDT000281331.2' already exists. Skipping...
Folder 'GCA_004995045.1_PDT000281345.2' already exists. Skipping...
Folder 'GCA_004995065.1_PDT000281346.2' already exists. Skipping...
Folder 'GCA_004995185.1_PDT000281361.2' already exists. Skipping...
Folder 'GCA_004995225.1_PDT000281446.2' already exists. Skipping...
Folder 'GCA_004995245.1_PDT000281449.2' already exists. Skipping...
Folder 'GCA_004995265.1_PDT000281367.2' already exists. Skipping...
Folder 'GCA_004995325.1_PDT000281445.2' already exists. Skipping...
Folder 'GCA_004995345.1_PDT000281535.2' already exists. Skipping...
Folder 'GCA_004995405.1_PDT000281532.2' already exists. Skipping...
Folder 'GCA_004995425.1_PDT000281538.2' already exists. Skipping...
Folder 'GCA_004995445.1_PDT000281780.2' already exists. Skipping...
Folder 'GCA_004995525.1_PDT000281533.2' already exists. Skipping...
Folder 'GCA_004995545.1_PDT000281447.2' already exists. Skipping...
Folder 'GCA_004995565.1_PDT000281719.2' already exists. Skipping...
Folder 'GCA_004995585.1_PDT000281537.2' already exists. Skipping...
Folder 'GCA_004995605.1_PDT000281544.2' already exists. Skipping...
Folder 'GCA_004995645.1_PDT000281536.2' already exists. Skipping...
Folder 'GCA_004995685.1_PDT000283474.2' already exists. Skipping...
Folder 'GCA_004995705.1_PDT000283054.2' already exists. Skipping...
Folder 'GCA_004995725.1_PDT000282880.2' already exists. Skipping...
Folder 'GCA_004995805.1_PDT000283041.2' already exists. Skipping...
Folder 'GCA_004995825.1_PDT000283052.2' already exists. Skipping...
Folder 'GCA_004995845.1_PDT000283415.2' already exists. Skipping...
Folder 'GCA_004995865.1_PDT000283398.2' already exists. Skipping...
Folder 'GCA_004995885.1_PDT000283102.2' already exists. Skipping...
Folder 'GCA_004995905.1_PDT000283047.2' already exists. Skipping...
Folder 'GCA_004995925.1_PDT000283121.2' already exists. Skipping...
Folder 'GCA_004995985.1_PDT000283039.2' already exists. Skipping...
Folder 'GCA_004996085.1_PDT000282414.2' already exists. Skipping...
Folder 'GCA_004996125.1_PDT000283112.2' already exists. Skipping...
Folder 'GCA_004996145.1_PDT000282875.2' already exists. Skipping...
Folder 'GCA_004996205.1_PDT000283445.2' already exists. Skipping...
Folder 'GCA_004996225.1_PDT000283408.2' already exists. Skipping...
Folder 'GCA_004996245.1_PDT000283438.2' already exists. Skipping...
Folder 'GCA_004996285.1_PDT000283422.2' already exists. Skipping...
Folder 'GCA_004996305.1_PDT000283439.2' already exists. Skipping...
Folder 'GCA_004996325.1_PDT000283152.2' already exists. Skipping...
Folder 'GCA_004996345.1_PDT000282874.2' already exists. Skipping...
Folder 'GCA_004996365.1_PDT000283397.2' already exists. Skipping...
Folder 'GCA_004996405.1_PDT000283412.2' already exists. Skipping...
Folder 'GCA_004996425.1_PDT000283458.2' already exists. Skipping...
Folder 'GCA_004996445.1_PDT000283037.2' already exists. Skipping...
Folder 'GCA_004996465.1_PDT000283394.2' already exists. Skipping...
Folder 'GCA_004996485.1_PDT000283410.2' already exists. Skipping...
Folder 'GCA_004996545.1_PDT000283431.2' already exists. Skipping...
Folder 'GCA_004996565.1_PDT000283333.2' already exists. Skipping...
Folder 'GCA_004996605.1_PDT000282877.2' already exists. Skipping...
Folder 'GCA_004996625.1_PDT000283453.2' already exists. Skipping...
Folder 'GCA_004996685.1_PDT000283126.2' already exists. Skipping...
Folder 'GCA_004996725.1_PDT000283467.2' already exists. Skipping...
Folder 'GCA_004996785.1_PDT000283150.2' already exists. Skipping...
Folder 'GCA_004996805.1_PDT000283158.2' already exists. Skipping...
Folder 'GCA_004996865.1_PDT000284052.2' already exists. Skipping...
Folder 'GCA_004996885.1_PDT000283171.2' already exists. Skipping...
Folder 'GCA_004996905.1_PDT000283387.2' already exists. Skipping...
Folder 'GCA_004996925.1_PDT000283462.2' already exists. Skipping...
Folder 'GCA_004996945.1_PDT000283330.2' already exists. Skipping...
Folder 'GCA_004996965.1_PDT000284050.2' already exists. Skipping...
Folder 'GCA_004996985.1_PDT000283429.2' already exists. Skipping...
Folder 'GCA_004997005.1_PDT000283132.2' already exists. Skipping...
Folder 'GCA_004997045.1_PDT000287106.2' already exists. Skipping...
Folder 'GCA_004997065.1_PDT000284056.2' already exists. Skipping...
Folder 'GCA_004997125.1_PDT000283454.2' already exists. Skipping...
Folder 'GCA_004997165.1_PDT000283335.2' already exists. Skipping...
Folder 'GCA_004997185.1_PDT000283166.2' already exists. Skipping...
Folder 'GCA_004997245.1_PDT000283470.2' already exists. Skipping...
Folder 'GCA_004997265.1_PDT000283159.2' already exists. Skipping...
Folder 'GCA_004997285.1_PDT000283421.2' already exists. Skipping...
Folder 'GCA_004997305.1_PDT000283413.2' already exists. Skipping...
Folder 'GCA_004997365.1_PDT000283418.2' already exists. Skipping...
Folder 'GCA_004997405.1_PDT000284081.2' already exists. Skipping...
Folder 'GCA_004997425.1_PDT000283419.2' already exists. Skipping...
Folder 'GCA_004997445.1_PDT000283488.2' already exists. Skipping...
Folder 'GCA_004997505.1_PDT000283468.2' already exists. Skipping...
Folder 'GCA_004997525.1_PDT000283489.2' already exists. Skipping...
Folder 'GCA_004997545.1_PDT000283494.2' already exists. Skipping...
Folder 'GCA_004997565.1_PDT000283479.2' already exists. Skipping...
Folder 'GCA_004997585.1_PDT000283490.2' already exists. Skipping...
Folder 'GCA_004997605.1_PDT000283499.2' already exists. Skipping...
Folder 'GCA_004997625.1_PDT000283497.2' already exists. Skipping...
Folder 'GCA_004997645.1_PDT000283493.2' already exists. Skipping...
Folder 'GCA_004997665.1_PDT000283498.2' already exists. Skipping...
Folder 'GCA_004997685.1_PDT000283501.2' already exists. Skipping...
Folder 'GCA_004997725.1_PDT000283509.2' already exists. Skipping...
Folder 'GCA_004997765.1_PDT000283504.2' already exists. Skipping...
Folder 'GCA_004997845.1_PDT000283522.2' already exists. Skipping...
Folder 'GCA_004997925.1_PDT000283525.2' already exists. Skipping...
Folder 'GCA_004997945.1_PDT000283536.2' already exists. Skipping...
Folder 'GCA_004998005.1_PDT000283546.2' already exists. Skipping...
Folder 'GCA_004998025.1_PDT000283543.2' already exists. Skipping...
Folder 'GCA_004998305.1_PDT000284130.2' already exists. Skipping...
Folder 'GCA_004998345.1_PDT000285255.2' already exists. Skipping...
Folder 'GCA_004998365.1_PDT000285262.2' already exists. Skipping...
Folder 'GCA_004998385.1_PDT000285264.2' already exists. Skipping...
Folder 'GCA_004998405.1_PDT000285263.2' already exists. Skipping...
Folder 'GCA_004998425.1_PDT000285260.2' already exists. Skipping...
Folder 'GCA_004998445.1_PDT000285269.2' already exists. Skipping...
Folder 'GCA_004998465.1_PDT000285267.2' already exists. Skipping...
Folder 'GCA_004998485.1_PDT000285254.2' already exists. Skipping...
Folder 'GCA_004998505.1_PDT000285266.2' already exists. Skipping...
Folder 'GCA_004998525.1_PDT000285273.2' already exists. Skipping...
Folder 'GCA_004998545.1_PDT000285265.2' already exists. Skipping...
Folder 'GCA_004998565.1_PDT000285278.2' already exists. Skipping...
Folder 'GCA_004998595.1_PDT000285270.2' already exists. Skipping...
Folder 'GCA_004998625.1_PDT000285284.2' already exists. Skipping...
Folder 'GCA_004998645.1_PDT000285367.2' already exists. Skipping...
Folder 'GCA_004998665.1_PDT000285957.2' already exists. Skipping...
Folder 'GCA_004998685.1_PDT000285961.2' already exists. Skipping...
Folder 'GCA_004998715.1_PDT000285369.2' already exists. Skipping...
Folder 'GCA_004998765.1_PDT000285951.2' already exists. Skipping...
Folder 'GCA_004998785.1_PDT000285370.2' already exists. Skipping...
Folder 'GCA_004998805.1_PDT000285971.2' already exists. Skipping...
Folder 'GCA_004998825.1_PDT000286255.2' already exists. Skipping...
Folder 'GCA_004998845.1_PDT000286258.2' already exists. Skipping...
Folder 'GCA_004998865.1_PDT000286257.2' already exists. Skipping...
Folder 'GCA_004998885.1_PDT000286264.2' already exists. Skipping...
Folder 'GCA_004998905.1_PDT000286846.2' already exists. Skipping...
Folder 'GCA_004998945.1_PDT000284083.2' already exists. Skipping...
Folder 'GCA_004998965.1_PDT000286849.2' already exists. Skipping...
Folder 'GCA_004999065.1_PDT000284090.2' already exists. Skipping...
Folder 'GCA_004999085.1_PDT000284111.2' already exists. Skipping...
Folder 'GCA_004999145.1_PDT000287399.2' already exists. Skipping...
Folder 'GCA_004999185.1_PDT000286850.2' already exists. Skipping...
Folder 'GCA_004999305.1_PDT000290418.2' already exists. Skipping...
Folder 'GCA_004999365.1_PDT000285972.2' already exists. Skipping...
Folder 'GCA_004999385.1_PDT000286267.2' already exists. Skipping...
Folder 'GCA_004999405.1_PDT000286847.2' already exists. Skipping...
Folder 'GCA_004999445.1_PDT000287541.2' already exists. Skipping...
Folder 'GCA_004999545.1_PDT000287559.2' already exists. Skipping...
Folder 'GCA_004999585.1_PDT000287674.2' already exists. Skipping...
Folder 'GCA_004999605.1_PDT000287717.2' already exists. Skipping...

Retreiveing data: 42979it [00:07, 6624.64it/s]

Folder 'GCA_005031595.1_PDT000289182.2' already exists. Skipping...
Folder 'GCA_005031635.1_PDT000289162.2' already exists. Skipping...
Folder 'GCA_005031655.1_PDT000283155.2' already exists. Skipping...
Folder 'GCA_005031675.1_PDT000284055.2' already exists. Skipping...
Folder 'GCA_005031695.1_PDT000285963.2' already exists. Skipping...
Folder 'GCA_005031735.1_PDT000295572.2' already exists. Skipping...
Folder 'GCA_005031815.1_PDT000294734.2' already exists. Skipping...
Folder 'GCA_005031835.1_PDT000291357.2' already exists. Skipping...
Folder 'GCA_005031875.1_PDT000289189.2' already exists. Skipping...
Folder 'GCA_005031915.1_PDT000266593.2' already exists. Skipping...
Folder 'GCA_005031935.1_PDT000291355.2' already exists. Skipping...
Folder 'GCA_005032005.1_PDT000291360.2' already exists. Skipping...
Folder 'GCA_005032035.1_PDT000300305.2' already exists. Skipping...
Folder 'GCA_005032055.1_PDT000294694.2' already exists. Skipping...
Folder 'GCA_005032155.1_PDT000295604.2' already exists. Skipping...
Folder 'GCA_005032175.1_PDT000294689.2' already exists. Skipping...
Folder 'GCA_005032255.1_PDT000294709.2' already exists. Skipping...
Folder 'GCA_005032275.1_PDT000295597.2' already exists. Skipping...
Folder 'GCA_005032315.1_PDT000266578.2' already exists. Skipping...
Folder 'GCA_005032335.1_PDT000146422.3' already exists. Skipping...
Folder 'GCA_005032415.1_PDT000291370.2' already exists. Skipping...
Folder 'GCA_005032535.1_PDT000295718.2' already exists. Skipping...
Folder 'GCA_005032555.1_PDT000266710.2' already exists. Skipping...
Folder 'GCA_005032575.1_PDT000144272.3' already exists. Skipping...
Folder 'GCA_005032595.1_PDT000283457.2' already exists. Skipping...
Folder 'GCA_005032605.1_PDT000269769.2' already exists. Skipping...
Folder 'GCA_005032635.1_PDT000269749.2' already exists. Skipping...
Folder 'GCA_005032735.1_PDT000272466.2' already exists. Skipping...
Folder 'GCA_005032755.1_PDT000269747.2' already exists. Skipping...
Folder 'GCA_005032775.1_PDT000126011.3' already exists. Skipping...
Folder 'GCA_005032835.1_PDT000283452.2' already exists. Skipping...
Folder 'GCA_005032855.1_PDT000283425.2' already exists. Skipping...
Folder 'GCA_005032875.1_PDT000283482.2' already exists. Skipping...
Folder 'GCA_005032915.1_PDT000266598.2' already exists. Skipping...
Folder 'GCA_005032975.1_PDT000296328.2' already exists. Skipping...
Folder 'GCA_005032995.1_PDT000283502.2' already exists. Skipping...
Folder 'GCA_005033035.1_PDT000295570.2' already exists. Skipping...
Folder 'GCA_005033055.1_PDT000295643.2' already exists. Skipping...
Folder 'GCA_005033075.1_PDT000138006.3' already exists. Skipping...
Folder 'GCA_005033115.1_PDT000295648.2' already exists. Skipping...
Folder 'GCA_005033155.1_PDT000266603.2' already exists. Skipping...
Folder 'GCA_005033235.1_PDT000294645.2' already exists. Skipping...
Folder 'GCA_005033255.1_PDT000283475.2' already exists. Skipping...
Folder 'GCA_005033275.1_PDT000291595.2' already exists. Skipping...
Folder 'GCA_005033295.1_PDT000269834.2' already exists. Skipping...
Folder 'GCA_005033315.1_PDT000285956.2' already exists. Skipping...
Folder 'GCA_005033335.1_PDT000284127.2' already exists. Skipping...
Folder 'GCA_005033375.1_PDT000283477.2' already exists. Skipping...
Folder 'GCA_005033395.1_PDT000283405.2' already exists. Skipping...
Folder 'GCA_005033435.1_PDT000289165.2' already exists. Skipping...
Folder 'GCA_005033455.1_PDT000294707.2' already exists. Skipping...
Folder 'GCA_005033495.1_PDT000291378.2' already exists. Skipping...
Folder 'GCA_005033515.1_PDT000289190.2' already exists. Skipping...
Folder 'GCA_005033575.1_PDT000294722.2' already exists. Skipping...
Folder 'GCA_005033595.1_PDT000272464.2' already exists. Skipping...
Folder 'GCA_005033635.1_PDT000294727.2' already exists. Skipping...
Folder 'GCA_005033655.1_PDT000146427.3' already exists. Skipping...
Folder 'GCA_005033675.1_PDT000283517.2' already exists. Skipping...
Folder 'GCA_005033685.1_PDT000289180.2' already exists. Skipping...
Folder 'GCA_005033715.1_PDT000137116.3' already exists. Skipping...
Folder 'GCA_005033735.1_PDT000294732.2' already exists. Skipping...
Folder 'GCA_005033755.1_PDT000291353.2' already exists. Skipping...
Folder 'GCA_005033775.1_PDT000285946.2' already exists. Skipping...
Folder 'GCA_005033795.1_PDT000290504.2' already exists. Skipping...
Folder 'GCA_005033815.1_PDT000284057.2' already exists. Skipping...
Folder 'GCA_005033875.1_PDT000290402.2' already exists. Skipping...
Folder 'GCA_005033895.1_PDT000287105.2' already exists. Skipping...
Folder 'GCA_005033915.1_PDT000290417.2' already exists. Skipping...
Folder 'GCA_005033935.1_PDT000287785.2' already exists. Skipping...
Folder 'GCA_005033955.1_PDT000287762.2' already exists. Skipping...
Folder 'GCA_005033975.1_PDT000295623.2' already exists. Skipping...
Folder 'GCA_005033995.1_PDT000295618.2' already exists. Skipping...
Folder 'GCA_005034015.1_PDT000293224.2' already exists. Skipping...
Folder 'GCA_005034035.1_PDT000295613.2' already exists. Skipping...
Folder 'GCA_005034055.1_PDT000295638.2' already exists. Skipping...
Folder 'GCA_005034075.1_PDT000291316.2' already exists. Skipping...
Folder 'GCA_005034095.1_PDT000303186.2' already exists. Skipping...
Folder 'GCA_005034115.1_PDT000303189.2' already exists. Skipping...
Folder 'GCA_005034135.1_PDT000304936.2' already exists. Skipping...
Folder 'GCA_005034165.1_PDT000304825.2' already exists. Skipping...
Folder 'GCA_005034235.1_PDT000304924.2' already exists. Skipping...
Folder 'GCA_005035355.1_PDT000304941.2' already exists. Skipping...
Folder 'GCA_005035375.1_PDT000304946.2' already exists. Skipping...
Folder 'GCA_005035395.1_PDT000305918.2' already exists. Skipping...
Folder 'GCA_005035415.1_PDT000305925.2' already exists. Skipping...
Folder 'GCA_005035455.1_PDT000306412.2' already exists. Skipping...
Folder 'GCA_005035475.1_PDT000306397.2' already exists. Skipping...
Folder 'GCA_005035495.1_PDT000306392.2' already exists. Skipping...
Folder 'GCA_005035515.1_PDT000304951.2' already exists. Skipping...
Folder 'GCA_005035535.1_PDT000306452.2' already exists. Skipping...
Folder 'GCA_005035555.1_PDT000310424.2' already exists. Skipping...
Folder 'GCA_005035565.1_PDT000306402.2' already exists. Skipping...
Folder 'GCA_005035595.1_PDT000306439.2' already exists. Skipping...
Folder 'GCA_005035615.1_PDT000310414.2' already exists. Skipping...
Folder 'GCA_005035675.1_PDT000287735.2' already exists. Skipping...
Folder 'GCA_005035735.1_PDT000291375.2' already exists. Skipping...
Folder 'GCA_005035775.1_PDT000274912.2' already exists. Skipping...
Folder 'GCA_005035795.1_PDT000256941.2' already exists. Skipping...
Folder 'GCA_005035815.1_PDT000256951.2' already exists. Skipping...
Folder 'GCA_005035835.1_PDT000273755.2' already exists. Skipping...
Folder 'GCA_005035875.1_PDT000274892.2' already exists. Skipping...
Folder 'GCA_005035895.1_PDT000273735.2' already exists. Skipping...
Folder 'GCA_005035915.1_PDT000272498.2' already exists. Skipping...
Folder 'GCA_005035955.1_PDT000253406.2' already exists. Skipping...
Folder 'GCA_005035975.1_PDT000253411.2' already exists. Skipping...
Folder 'GCA_005035995.1_PDT000311298.2' already exists. Skipping...
Folder 'GCA_005036015.1_PDT000306454.2' already exists. Skipping...
Folder 'GCA_005036035.1_PDT000256931.2' already exists. Skipping...
Folder 'GCA_005036055.1_PDT000281355.2' already exists. Skipping...
Folder 'GCA_005036075.1_PDT000256936.2' already exists. Skipping...
Folder 'GCA_005036095.1_PDT000256921.2' already exists. Skipping...
Folder 'GCA_005036115.1_PDT000300306.2' already exists. Skipping...
Folder 'GCA_005036135.1_PDT000304942.2' already exists. Skipping...
Folder 'GCA_005036155.1_PDT000283396.2' already exists. Skipping...
Folder 'GCA_005036175.1_PDT000274825.2' already exists. Skipping...
Folder 'GCA_005036195.1_PDT000282518.2' already exists. Skipping...
Folder 'GCA_005036215.1_PDT000275989.2' already exists. Skipping...
Folder 'GCA_005036235.1_PDT000295575.2' already exists. Skipping...
Folder 'GCA_005036275.1_PDT000281363.2' already exists. Skipping...
Folder 'GCA_005036295.1_PDT000295600.2' already exists. Skipping...
Folder 'GCA_005036315.1_PDT000304937.2' already exists. Skipping...
Folder 'GCA_005036335.1_PDT000305926.2' already exists. Skipping...
Folder 'GCA_005036355.1_PDT000304947.2' already exists. Skipping...
Folder 'GCA_005036375.1_PDT000306400.2' already exists. Skipping...
Folder 'GCA_005036395.1_PDT000305933.2' already exists. Skipping...
Folder 'GCA_005036415.1_PDT000305936.2' already exists. Skipping...
Folder 'GCA_005036435.1_PDT000306440.2' already exists. Skipping...
Folder 'GCA_005036455.1_PDT000306410.2' already exists. Skipping...
Folder 'GCA_005036475.1_PDT000306465.2' already exists. Skipping...
Folder 'GCA_005036495.1_PDT000244891.3' already exists. Skipping...
Folder 'GCA_005036515.1_PDT000306405.2' already exists. Skipping...
Folder 'GCA_005036555.1_PDT000306467.2' already exists. Skipping...
Folder 'GCA_005036575.1_PDT000311301.2' already exists. Skipping...
Folder 'GCA_005036595.1_PDT000312313.2' already exists. Skipping...
Folder 'GCA_005036615.1_PDT000313068.2' already exists. Skipping...
Folder 'GCA_005036635.1_PDT000314355.2' already exists. Skipping...
Folder 'GCA_005036655.1_PDT000314347.2' already exists. Skipping...
Folder 'GCA_005036675.1_PDT000314345.2' already exists. Skipping...
Folder 'GCA_005036695.1_PDT000314360.2' already exists. Skipping...
Folder 'GCA_005036715.1_PDT000314350.2' already exists. Skipping...
Folder 'GCA_005036725.1_PDT000313309.2' already exists. Skipping...
Folder 'GCA_005036735.1_PDT000313302.2' already exists. Skipping...
Folder 'GCA_005036775.1_PDT000314357.2' already exists. Skipping...
Folder 'GCA_005036835.1_PDT000314362.2' already exists. Skipping...
Folder 'GCA_005037175.1_PDT000314367.2' already exists. Skipping...
Folder 'GCA_005037195.1_PDT000314365.2' already exists. Skipping...
Folder 'GCA_005037215.1_PDT000300645.2' already exists. Skipping...
Folder 'GCA_005037235.1_PDT000314370.2' already exists. Skipping...
Folder 'GCA_005037255.1_PDT000300799.2' already exists. Skipping...
Folder 'GCA_005037275.1_PDT000300782.2' already exists. Skipping...
Folder 'GCA_005037295.1_PDT000296338.2' already exists. Skipping...
Folder 'GCA_005037315.1_PDT000300787.2' already exists. Skipping...
Folder 'GCA_005037325.1_PDT000300807.2' already exists. Skipping...
Folder 'GCA_005037355.1_PDT000302952.2' already exists. Skipping...
Folder 'GCA_005037375.1_PDT000302977.2' already exists. Skipping...
Folder 'GCA_005037385.1_PDT000300792.2' already exists. Skipping...
Folder 'GCA_005037415.1_PDT000302967.2' already exists. Skipping...
Folder 'GCA_005037435.1_PDT000300804.2' already exists. Skipping...
Folder 'GCA_005037455.1_PDT000302982.2' already exists. Skipping...
Folder 'GCA_005037475.1_PDT000305562.2' already exists. Skipping...
Folder 'GCA_005037495.1_PDT000307949.2' already exists. Skipping...
Folder 'GCA_005037515.1_PDT000305557.2' already exists. Skipping...
Folder 'GCA_005037535.1_PDT000303756.2' already exists. Skipping...
Folder 'GCA_005037555.1_PDT000303786.2' already exists. Skipping...
Folder 'GCA_005037575.1_PDT000306806.2' already exists. Skipping...
Folder 'GCA_005037595.1_PDT000307979.2' already exists. Skipping...
Folder 'GCA_005037615.1_PDT000309849.2' already exists. Skipping...
Folder 'GCA_005037635.1_PDT000307959.2' already exists. Skipping...
Folder 'GCA_005037655.1_PDT000307969.2' already exists. Skipping...
Folder 'GCA_005037675.1_PDT000312991.2' already exists. Skipping...
Folder 'GCA_005037695.1_PDT000312989.2' already exists. Skipping...
Folder 'GCA_005049385.1_PDT000313504.2' already exists. Skipping...
Folder 'GCA_005049425.1_PDT000317532.2' already exists. Skipping...
Folder 'GCA_005049945.1_PDT000317552.2' already exists. Skipping...
Folder 'GCA_005049965.1_PDT000317554.2' already exists. Skipping...
Folder 'GCA_005049985.1_PDT000258825.2' already exists. Skipping...
Folder 'GCA_005050005.1_PDT000317559.2' already exists. Skipping...
Folder 'GCA_005050015.1_PDT000317557.2' already exists. Skipping...
Folder 'GCA_005050045.1_PDT000266345.2' already exists. Skipping...
Folder 'GCA_005050055.1_PDT000317648.2' already exists. Skipping...
Folder 'GCA_005050085.1_PDT000266377.2' already exists. Skipping...
Folder 'GCA_005050105.1_PDT000273481.2' already exists. Skipping...
Folder 'GCA_005050125.1_PDT000273476.2' already exists. Skipping...
Folder 'GCA_005050145.1_PDT000271539.2' already exists. Skipping...
Folder 'GCA_005050165.1_PDT000278367.2' already exists. Skipping...
Folder 'GCA_005050185.1_PDT000278362.2' already exists. Skipping...
Folder 'GCA_005050205.1_PDT000281256.2' already exists. Skipping...
Folder 'GCA_005050225.1_PDT000278372.2' already exists. Skipping...
Folder 'GCA_005050245.1_PDT000281266.2' already exists. Skipping...
Folder 'GCA_005050265.1_PDT000281097.2' already exists. Skipping...
Folder 'GCA_005050285.1_PDT000283441.2' already exists. Skipping...
Folder 'GCA_005050545.1_PDT000266975.2' already exists. Skipping...
Folder 'GCA_005050585.1_PDT000263071.2' already exists. Skipping...
Folder 'GCA_005050625.1_PDT000266965.2' already exists. Skipping...
Folder 'GCA_005050665.1_PDT000265263.2' already exists. Skipping...
Folder 'GCA_005050685.1_PDT000283446.2' already exists. Skipping...
Folder 'GCA_005050705.1_PDT000283401.2' already exists. Skipping...
Folder 'GCA_005050725.1_PDT000285955.2' already exists. Skipping...
Folder 'GCA_005050765.1_PDT000283526.2' already exists. Skipping...
Folder 'GCA_005050785.1_PDT000285945.2' already exists. Skipping...
Folder 'GCA_005050805.1_PDT000263964.2' already exists. Skipping...
Folder 'GCA_005050815.1_PDT000289179.2' already exists. Skipping...
Folder 'GCA_005050845.1_PDT000285970.2' already exists. Skipping...
Folder 'GCA_005050865.1_PDT000285965.2' already exists. Skipping...
Folder 'GCA_005050885.1_PDT000289171.2' already exists. Skipping...
Folder 'GCA_005050925.1_PDT000285950.2' already exists. Skipping...
Folder 'GCA_005051105.1_PDT000294696.2' already exists. Skipping...
Folder 'GCA_005051125.1_PDT000291354.2' already exists. Skipping...
Folder 'GCA_005051165.1_PDT000294721.2' already exists. Skipping...
Folder 'GCA_005051185.1_PDT000291374.2' already exists. Skipping...
Folder 'GCA_005051225.1_PDT000294731.2' already exists. Skipping...
Folder 'GCA_005051245.1_PDT000294736.2' already exists. Skipping...
Folder 'GCA_005051265.1_PDT000294738.2' already exists. Skipping...
Folder 'GCA_005051285.1_PDT000295599.2' already exists. Skipping...
Folder 'GCA_005051325.1_PDT000295601.2' already exists. Skipping...
Folder 'GCA_005051345.1_PDT000295574.2' already exists. Skipping...
Folder 'GCA_005051385.1_PDT000300302.2' already exists. Skipping...
Folder 'GCA_005051405.1_PDT000303178.2' already exists. Skipping...
Folder 'GCA_005051425.1_PDT000303193.2' already exists. Skipping...
Folder 'GCA_005051445.1_PDT000319106.2' already exists. Skipping...
Folder 'GCA_005051465.1_PDT000319091.2' already exists. Skipping...
Folder 'GCA_005051485.1_PDT000319096.2' already exists. Skipping...
Folder 'GCA_005051505.1_PDT000319166.2' already exists. Skipping...
Folder 'GCA_005051525.1_PDT000319116.2' already exists. Skipping...
Folder 'GCA_005051545.1_PDT000319111.2' already exists. Skipping...
Folder 'GCA_005051585.1_PDT000262587.2' already exists. Skipping...
Folder 'GCA_005051615.1_PDT000319141.2' already exists. Skipping...
Folder 'GCA_005051665.1_PDT000319161.2' already exists. Skipping...
Folder 'GCA_005051685.1_PDT000319126.2' already exists. Skipping...
Folder 'GCA_005051725.1_PDT000319121.2' already exists. Skipping...
Folder 'GCA_005051735.1_PDT000319151.2' already exists. Skipping...
Folder 'GCA_005051765.1_PDT000262597.2' already exists. Skipping...
Folder 'GCA_005051785.1_PDT000262617.2' already exists. Skipping...
Folder 'GCA_005051805.1_PDT000267909.2' already exists. Skipping...
Folder 'GCA_005051825.1_PDT000283104.2' already exists. Skipping...
Folder 'GCA_005051845.1_PDT000283109.2' already exists. Skipping...
Folder 'GCA_005051865.1_PDT000283044.2' already exists. Skipping...
Folder 'GCA_005051885.1_PDT000283139.2' already exists. Skipping...
Folder 'GCA_005051905.1_PDT000283114.2' already exists. Skipping...
Folder 'GCA_005051925.1_PDT000283146.2' already exists. Skipping...
Folder 'GCA_005051955.1_PDT000283156.2' already exists. Skipping...
Folder 'GCA_005052005.1_PDT000283161.2' already exists. Skipping...
Folder 'GCA_005052805.1_PDT000283169.2' already exists. Skipping...
Folder 'GCA_005052865.1_PDT000284051.2' already exists. Skipping...
Folder 'GCA_005052885.1_PDT000287766.2' already exists. Skipping...
Folder 'GCA_005052905.1_PDT000287736.2' already exists. Skipping...
Folder 'GCA_005052925.1_PDT000287761.2' already exists. Skipping...
Folder 'GCA_005052945.1_PDT000284123.2' already exists. Skipping...
Folder 'GCA_005052965.1_PDT000287771.2' already exists. Skipping...
Folder 'GCA_005052985.1_PDT000270131.2' already exists. Skipping...
Folder 'GCA_005053005.1_PDT000290324.2' already exists. Skipping...
Folder 'GCA_005053025.1_PDT000288005.2' already exists. Skipping...
Folder 'GCA_005053035.1_PDT000273479.2' already exists. Skipping...
Folder 'GCA_005053065.1_PDT000258848.2' already exists. Skipping...
Folder 'GCA_005053085.1_PDT000281299.2' already exists. Skipping...
Folder 'GCA_005053105.1_PDT000281272.2' already exists. Skipping...
Folder 'GCA_005053125.1_PDT000281289.2' already exists. Skipping...
Folder 'GCA_005053145.1_PDT000278370.2' already exists. Skipping...
Folder 'GCA_005053165.1_PDT000283045.2' already exists. Skipping...
Folder 'GCA_005053185.1_PDT000281324.2' already exists. Skipping...
Folder 'GCA_005053205.1_PDT000281329.2' already exists. Skipping...
Folder 'GCA_005053225.1_PDT000304827.2' already exists. Skipping...
Folder 'GCA_005053245.1_PDT000304938.2' already exists. Skipping...
Folder 'GCA_005053265.1_PDT000283040.2' already exists. Skipping...
Folder 'GCA_005053285.1_PDT000305922.2' already exists. Skipping...
Folder 'GCA_005053305.1_PDT000306384.2' already exists. Skipping...
Folder 'GCA_005053325.1_PDT000306404.2' already exists. Skipping...
Folder 'GCA_005053345.1_PDT000306394.2' already exists. Skipping...
Folder 'GCA_005053365.1_PDT000306406.2' already exists. Skipping...
Folder 'GCA_005053405.1_PDT000306441.2' already exists. Skipping...
Folder 'GCA_005053445.1_PDT000306411.2' already exists. Skipping...
Folder 'GCA_005053465.1_PDT000306409.2' already exists. Skipping...
Folder 'GCA_005053505.1_PDT000306451.2' already exists. Skipping...
Folder 'GCA_005053865.1_PDT000306456.2' already exists. Skipping...
Folder 'GCA_005053905.1_PDT000310416.2' already exists. Skipping...
Folder 'GCA_005053925.1_PDT000311300.2' already exists. Skipping...
Folder 'GCA_005053945.1_PDT000249143.2' already exists. Skipping...
Folder 'GCA_005053965.1_PDT000249141.2' already exists. Skipping...
Folder 'GCA_005053985.1_PDT000249148.2' already exists. Skipping...
Folder 'GCA_005053995.1_PDT000254246.2' already exists. Skipping...
Folder 'GCA_005054025.1_PDT000254386.2' already exists. Skipping...
Folder 'GCA_005054045.1_PDT000283034.2' already exists. Skipping...
Folder 'GCA_005054065.1_PDT000281296.2' already exists. Skipping...
Folder 'GCA_005054085.1_PDT000256925.2' already exists. Skipping...
Folder 'GCA_005054105.1_PDT000283059.2' already exists. Skipping...
Folder 'GCA_005054125.1_PDT000290493.2' already exists. Skipping...
Folder 'GCA_005054145.1_PDT000291350.2' already exists. Skipping...
Folder 'GCA_005054165.1_PDT000256933.2' already exists. Skipping...
Folder 'GCA_005054185.1_PDT000256955.2' already exists. Skipping...
Folder 'GCA_005054195.1_PDT000256935.2' already exists. Skipping...
Folder 'GCA_005054225.1_PDT000293230.2' already exists. Skipping...
Folder 'GCA_005054245.1_PDT000295614.2' already exists. Skipping...
Folder 'GCA_005054285.1_PDT000295609.2' already exists. Skipping...
Folder 'GCA_005054305.1_PDT000295612.2' already exists. Skipping...

Retreiveing data: 44302it [00:08, 6587.81it/s]

Folder 'GCA_005089925.1_PDT000486295.1' already exists. Skipping...
Folder 'GCA_005089945.1_PDT000486291.1' already exists. Skipping...
Folder 'GCA_005089965.1_PDT000486292.1' already exists. Skipping...
Folder 'GCA_005089985.1_PDT000486293.1' already exists. Skipping...
Folder 'GCA_005090005.1_PDT000486264.1' already exists. Skipping...
Folder 'GCA_005090025.1_PDT000486299.1' already exists. Skipping...
Folder 'GCA_005090045.1_PDT000486302.1' already exists. Skipping...
Folder 'GCA_005090065.1_PDT000486306.1' already exists. Skipping...
Folder 'GCA_005090085.1_PDT000486354.1' already exists. Skipping...
Folder 'GCA_005090145.1_PDT000486314.1' already exists. Skipping...
Folder 'GCA_005090155.1_PDT000486300.1' already exists. Skipping...
Folder 'GCA_005090225.1_PDT000486353.1' already exists. Skipping...
Folder 'GCA_005090235.1_PDT000486391.1' already exists. Skipping...
Folder 'GCA_005090285.1_PDT000486370.1' already exists. Skipping...
Folder 'GCA_005090385.1_PDT000486387.1' already exists. Skipping...
Folder 'GCA_005090415.1_PDT000486400.1' already exists. Skipping...
Folder 'GCA_005090465.1_PDT000486408.1' already exists. Skipping...
Folder 'GCA_005090505.1_PDT000486414.1' already exists. Skipping...
Folder 'GCA_005090525.1_PDT000486417.1' already exists. Skipping...
Folder 'GCA_005090605.1_PDT000486429.1' already exists. Skipping...
Folder 'GCA_005090625.1_PDT000486434.1' already exists. Skipping...
Folder 'GCA_005090715.1_PDT000487481.1' already exists. Skipping...
Folder 'GCA_005090805.1_PDT000487540.1' already exists. Skipping...
Folder 'GCA_005090845.1_PDT000473046.2' already exists. Skipping...
Folder 'GCA_005090885.1_PDT000487542.1' already exists. Skipping...
Folder 'GCA_005090905.1_PDT000487541.1' already exists. Skipping...
Folder 'GCA_005090925.1_PDT000487665.1' already exists. Skipping...
Folder 'GCA_005090945.1_PDT000487661.1' already exists. Skipping...
Folder 'GCA_005090965.1_PDT000487666.1' already exists. Skipping...
Folder 'GCA_005091025.1_PDT000488068.1' already exists. Skipping...
Folder 'GCA_005091035.1_PDT000487861.1' already exists. Skipping...
Folder 'GCA_005091125.1_PDT000490564.1' already exists. Skipping...
Folder 'GCA_005091145.1_PDT000490940.1' already exists. Skipping...
Folder 'GCA_005091165.1_PDT000490935.1' already exists. Skipping...
Folder 'GCA_005091185.1_PDT000490565.1' already exists. Skipping...
Folder 'GCA_005091205.1_PDT000490998.1' already exists. Skipping...
Folder 'GCA_005091225.1_PDT000490562.1' already exists. Skipping...
Folder 'GCA_005091305.1_PDT000490556.1' already exists. Skipping...
Folder 'GCA_005091325.1_PDT000489255.1' already exists. Skipping...
Folder 'GCA_005091405.1_PDT000489274.1' already exists. Skipping...
Folder 'GCA_005091485.1_PDT000489311.1' already exists. Skipping...
Folder 'GCA_005091505.1_PDT000489284.1' already exists. Skipping...
Folder 'GCA_005091545.1_PDT000489600.1' already exists. Skipping...
Folder 'GCA_005091565.1_PDT000489602.1' already exists. Skipping...
Folder 'GCA_005091585.1_PDT000489613.1' already exists. Skipping...
Folder 'GCA_005091605.1_PDT000489606.1' already exists. Skipping...
Folder 'GCA_005091625.1_PDT000489608.1' already exists. Skipping...
Folder 'GCA_005091645.1_PDT000489605.1' already exists. Skipping...
Folder 'GCA_005091665.1_PDT000489610.1' already exists. Skipping...
Folder 'GCA_005091685.1_PDT000490286.1' already exists. Skipping...
Folder 'GCA_005091705.1_PDT000489607.1' already exists. Skipping...
Folder 'GCA_005091725.1_PDT000490943.1' already exists. Skipping...
Folder 'GCA_005091825.1_PDT000490942.1' already exists. Skipping...
Folder 'GCA_005091845.1_PDT000490947.1' already exists. Skipping...
Folder 'GCA_005091865.1_PDT000490555.1' already exists. Skipping...
Folder 'GCA_005091885.1_PDT000490957.1' already exists. Skipping...
Folder 'GCA_005091965.1_PDT000490289.1' already exists. Skipping...
Folder 'GCA_005091985.1_PDT000490950.1' already exists. Skipping...
Folder 'GCA_005092005.1_PDT000490963.1' already exists. Skipping...
Folder 'GCA_005092065.1_PDT000490978.1' already exists. Skipping...
Folder 'GCA_005092085.1_PDT000490969.1' already exists. Skipping...
Folder 'GCA_005092105.1_PDT000490986.1' already exists. Skipping...
Folder 'GCA_005092165.1_PDT000490987.1' already exists. Skipping...
Folder 'GCA_005092205.1_PDT000491002.1' already exists. Skipping...
Folder 'GCA_005092225.1_PDT000491001.1' already exists. Skipping...
Folder 'GCA_005092245.1_PDT000491008.1' already exists. Skipping...
Folder 'GCA_005092265.1_PDT000491012.1' already exists. Skipping...
Folder 'GCA_005092285.1_PDT000491650.1' already exists. Skipping...
Folder 'GCA_005092325.1_PDT000491068.1' already exists. Skipping...
Folder 'GCA_005092345.1_PDT000491654.1' already exists. Skipping...
Folder 'GCA_005092365.1_PDT000491358.1' already exists. Skipping...
Folder 'GCA_005092385.1_PDT000491066.1' already exists. Skipping...
Folder 'GCA_005092445.1_PDT000491041.1' already exists. Skipping...
Folder 'GCA_005092465.1_PDT000492536.1' already exists. Skipping...
Folder 'GCA_005092505.1_PDT000491049.1' already exists. Skipping...
Folder 'GCA_005092525.1_PDT000491048.1' already exists. Skipping...
Folder 'GCA_005092565.1_PDT000491045.1' already exists. Skipping...
Folder 'GCA_005092585.1_PDT000491031.1' already exists. Skipping...
Folder 'GCA_005092625.1_PDT000491020.1' already exists. Skipping...
Folder 'GCA_005092645.1_PDT000491071.1' already exists. Skipping...
Folder 'GCA_005092665.1_PDT000491035.1' already exists. Skipping...
Folder 'GCA_005092685.1_PDT000491055.1' already exists. Skipping...
Folder 'GCA_005092705.1_PDT000491027.1' already exists. Skipping...
Folder 'GCA_005092725.1_PDT000491036.1' already exists. Skipping...
Folder 'GCA_005092765.1_PDT000491061.1' already exists. Skipping...
Folder 'GCA_005092805.1_PDT000491363.1' already exists. Skipping...
Folder 'GCA_005092885.1_PDT000491043.1' already exists. Skipping...
Folder 'GCA_005092905.1_PDT000491663.1' already exists. Skipping...
Folder 'GCA_005092925.1_PDT000491059.1' already exists. Skipping...
Folder 'GCA_005092945.1_PDT000491343.1' already exists. Skipping...
Folder 'GCA_005092965.1_PDT000491028.1' already exists. Skipping...
Folder 'GCA_005093025.1_PDT000491019.1' already exists. Skipping...
Folder 'GCA_005093045.1_PDT000491653.1' already exists. Skipping...
Folder 'GCA_005093065.1_PDT000491065.1' already exists. Skipping...
Folder 'GCA_005093105.1_PDT000491047.1' already exists. Skipping...
Folder 'GCA_005093125.1_PDT000491675.1' already exists. Skipping...
Folder 'GCA_005093165.1_PDT000491054.1' already exists. Skipping...
Folder 'GCA_005093225.1_PDT000062781.2' already exists. Skipping...
Folder 'GCA_005093245.1_PDT000062907.2' already exists. Skipping...
Folder 'GCA_005093265.1_PDT000046021.2' already exists. Skipping...
Folder 'GCA_005093285.1_PDT000046025.2' already exists. Skipping...
Folder 'GCA_005093325.1_PDT000046011.2' already exists. Skipping...
Folder 'GCA_005093365.1_PDT000048615.2' already exists. Skipping...
Folder 'GCA_005093405.1_PDT000053688.2' already exists. Skipping...
Folder 'GCA_005093425.1_PDT000053686.2' already exists. Skipping...
Folder 'GCA_005093445.1_PDT000046026.2' already exists. Skipping...
Folder 'GCA_005093465.1_PDT000045999.2' already exists. Skipping...
Folder 'GCA_005093485.1_PDT000053692.2' already exists. Skipping...
Folder 'GCA_005093505.1_PDT000053687.2' already exists. Skipping...
Folder 'GCA_005093525.1_PDT000046004.2' already exists. Skipping...
Folder 'GCA_005093545.2_ASM509354v2' already exists. Skipping...
Folder 'GCA_005093565.1_PDT000062774.2' already exists. Skipping...
Folder 'GCA_005093585.1_PDT000048241.2' already exists. Skipping...
Folder 'GCA_005093645.1_PDT000062906.2' already exists. Skipping...
Folder 'GCA_005093665.1_PDT000049706.2' already exists. Skipping...
Folder 'GCA_005093705.2_ASM509370v2' already exists. Skipping...
Folder 'GCA_005093725.1_PDT000053691.2' already exists. Skipping...
Folder 'GCA_005093745.1_PDT000062904.2' already exists. Skipping...
Folder 'GCA_005093755.2_ASM509375v2' already exists. Skipping...
Folder 'GCA_005093785.1_PDT000046003.2' already exists. Skipping...
Folder 'GCA_005093805.1_PDT000049354.2' already exists. Skipping...
Folder 'GCA_005093845.1_PDT000061260.2' already exists. Skipping...
Folder 'GCA_005093865.1_PDT000046013.2' already exists. Skipping...
Folder 'GCA_005093895.1_PDT000049875.2' already exists. Skipping...
Folder 'GCA_005093925.1_PDT000061282.2' already exists. Skipping...
Folder 'GCA_005093945.1_PDT000046012.2' already exists. Skipping...
Folder 'GCA_005094025.1_PDT000049357.2' already exists. Skipping...
Folder 'GCA_005094045.2_ASM509404v2' already exists. Skipping...
Folder 'GCA_005094065.1_PDT000048246.2' already exists. Skipping...
Folder 'GCA_005094085.2_ASM509408v2' already exists. Skipping...
Folder 'GCA_005094105.1_PDT000048228.2' already exists. Skipping...
Folder 'GCA_005094125.1_PDT000062780.2' already exists. Skipping...
Folder 'GCA_005094145.1_PDT000061281.2' already exists. Skipping...
Folder 'GCA_005094165.1_PDT000046027.2' already exists. Skipping...
Folder 'GCA_005094185.1_PDT000062913.2' already exists. Skipping...
Folder 'GCA_005094205.1_PDT000049359.2' already exists. Skipping...
Folder 'GCA_005094225.2_ASM509422v2' already exists. Skipping...
Folder 'GCA_005094245.1_PDT000062784.2' already exists. Skipping...
Folder 'GCA_005094285.1_PDT000061272.2' already exists. Skipping...
Folder 'GCA_005094305.1_PDT000061271.2' already exists. Skipping...
Folder 'GCA_005094325.2_ASM509432v2' already exists. Skipping...
Folder 'GCA_005094345.1_PDT000049352.3' already exists. Skipping...
Folder 'GCA_005094365.1_PDT000049351.2' already exists. Skipping...
Folder 'GCA_005094385.1_PDT000061274.2' already exists. Skipping...
Folder 'GCA_005094405.1_PDT000046008.2' already exists. Skipping...
Folder 'GCA_005094425.1_PDT000062773.2' already exists. Skipping...
Folder 'GCA_005094445.1_PDT000062783.2' already exists. Skipping...
Folder 'GCA_005094625.1_PDT000062738.2' already exists. Skipping...
Folder 'GCA_005094685.1_PDT000062755.2' already exists. Skipping...
Folder 'GCA_005094705.1_PDT000062751.2' already exists. Skipping...
Folder 'GCA_005094725.1_PDT000062748.3' already exists. Skipping...
Folder 'GCA_005094745.1_PDT000062752.2' already exists. Skipping...
Folder 'GCA_005094765.1_PDT000062750.2' already exists. Skipping...
Folder 'GCA_005094785.1_PDT000062765.2' already exists. Skipping...
Folder 'GCA_005094795.1_PDT000062756.2' already exists. Skipping...
Folder 'GCA_005094805.1_PDT000062769.2' already exists. Skipping...
Folder 'GCA_005094855.1_PDT000062761.2' already exists. Skipping...
Folder 'GCA_005094885.1_PDT000062816.2' already exists. Skipping...
Folder 'GCA_005094905.1_PDT000062766.2' already exists. Skipping...
Folder 'GCA_005094925.1_PDT000062804.2' already exists. Skipping...
Folder 'GCA_005094945.1_PDT000062768.2' already exists. Skipping...
Folder 'GCA_005094965.1_PDT000062793.2' already exists. Skipping...
Folder 'GCA_005095005.1_PDT000062772.2' already exists. Skipping...
Folder 'GCA_005095025.1_PDT000062803.2' already exists. Skipping...
Folder 'GCA_005095045.1_PDT000062806.2' already exists. Skipping...
Folder 'GCA_005095065.1_PDT000062823.2' already exists. Skipping...
Folder 'GCA_005095085.1_PDT000062819.2' already exists. Skipping...
Folder 'GCA_005095105.1_PDT000062826.2' already exists. Skipping...
Folder 'GCA_005095125.1_PDT000062833.2' already exists. Skipping...
Folder 'GCA_005095145.1_PDT000062821.2' already exists. Skipping...
Folder 'GCA_005095165.1_PDT000062837.2' already exists. Skipping...
Folder 'GCA_005095185.1_PDT000062835.2' already exists. Skipping...
Folder 'GCA_005095205.1_PDT000062841.2' already exists. Skipping...
Folder 'GCA_005095225.1_PDT000062830.2' already exists. Skipping...
Folder 'GCA_005095245.1_PDT000062832.2' already exists. Skipping...
Folder 'GCA_005095265.1_PDT000062843.3' already exists. Skipping...
Folder 'GCA_005095285.1_PDT000062855.2' already exists. Skipping...
Folder 'GCA_005095305.1_PDT000062846.2' already exists. Skipping...
Folder 'GCA_005095325.1_PDT000062851.2' already exists. Skipping...
Folder 'GCA_005095345.1_PDT000062847.2' already exists. Skipping...
Folder 'GCA_005095365.1_PDT000062852.3' already exists. Skipping...
Folder 'GCA_005095385.1_PDT000062857.2' already exists. Skipping...
Folder 'GCA_005095405.1_PDT000062853.2' already exists. Skipping...
Folder 'GCA_005095425.1_PDT000062865.2' already exists. Skipping...
Folder 'GCA_005095465.1_PDT000062859.2' already exists. Skipping...
Folder 'GCA_005095485.1_PDT000062867.2' already exists. Skipping...
Folder 'GCA_005095505.1_PDT000062877.2' already exists. Skipping...
Folder 'GCA_005095525.1_PDT000062874.2' already exists. Skipping...
Folder 'GCA_005095545.1_PDT000062871.2' already exists. Skipping...
Folder 'GCA_005095565.1_PDT000062880.2' already exists. Skipping...
Folder 'GCA_005095585.1_PDT000062889.2' already exists. Skipping...
Folder 'GCA_005095605.1_PDT000062893.2' already exists. Skipping...
Folder 'GCA_005095625.1_PDT000062890.2' already exists. Skipping...
Folder 'GCA_005095645.1_PDT000062882.2' already exists. Skipping...
Folder 'GCA_005095665.1_PDT000062921.2' already exists. Skipping...
Folder 'GCA_005095675.1_PDT000062896.2' already exists. Skipping...
Folder 'GCA_005095745.1_PDT000062914.2' already exists. Skipping...
Folder 'GCA_005095765.1_PDT000062922.2' already exists. Skipping...
Folder 'GCA_005095825.1_PDT000063203.2' already exists. Skipping...
Folder 'GCA_005095905.1_PDT000062919.2' already exists. Skipping...
Folder 'GCA_005095945.1_PDT000062923.2' already exists. Skipping...
Folder 'GCA_005095985.1_PDT000063207.2' already exists. Skipping...
Folder 'GCA_005096005.1_PDT000063201.2' already exists. Skipping...
Folder 'GCA_005096025.1_PDT000063211.2' already exists. Skipping...
Folder 'GCA_005096045.1_PDT000063208.2' already exists. Skipping...
Folder 'GCA_005096105.1_PDT000063218.2' already exists. Skipping...
Folder 'GCA_005096125.1_PDT000063215.2' already exists. Skipping...
Folder 'GCA_005096165.1_PDT000065275.2' already exists. Skipping...
Folder 'GCA_005096185.1_PDT000064973.2' already exists. Skipping...
Folder 'GCA_005096225.1_PDT000066936.3' already exists. Skipping...
Folder 'GCA_005096245.1_PDT000062802.2' already exists. Skipping...
Folder 'GCA_005096265.1_PDT000062778.2' already exists. Skipping...
Folder 'GCA_005096285.1_PDT000062805.2' already exists. Skipping...
Folder 'GCA_005096305.1_PDT000062786.2' already exists. Skipping...
Folder 'GCA_005096395.1_PDT000096676.2' already exists. Skipping...
Folder 'GCA_005096435.1_PDT000086195.2' already exists. Skipping...
Folder 'GCA_005096455.1_PDT000087337.2' already exists. Skipping...
Folder 'GCA_005096475.1_PDT000086125.2' already exists. Skipping...
Folder 'GCA_005096495.1_PDT000096659.2' already exists. Skipping...
Folder 'GCA_005096515.1_PDT000086199.2' already exists. Skipping...
Folder 'GCA_005096535.1_PDT000086194.2' already exists. Skipping...
Folder 'GCA_005096575.1_PDT000095658.2' already exists. Skipping...
Folder 'GCA_005096595.1_PDT000096679.2' already exists. Skipping...
Folder 'GCA_005096635.1_PDT000081257.2' already exists. Skipping...
Folder 'GCA_005096655.1_PDT000081838.2' already exists. Skipping...
Folder 'GCA_005096675.1_PDT000081841.2' already exists. Skipping...
Folder 'GCA_005096695.1_PDT000070066.2' already exists. Skipping...
Folder 'GCA_005096715.1_PDT000081839.2' already exists. Skipping...
Folder 'GCA_005096735.1_PDT000082548.2' already exists. Skipping...
Folder 'GCA_005096795.1_PDT000081842.2' already exists. Skipping...
Folder 'GCA_005096835.1_PDT000085750.2' already exists. Skipping...
Folder 'GCA_005096855.1_PDT000087449.2' already exists. Skipping...
Folder 'GCA_005096875.1_PDT000086105.2' already exists. Skipping...
Folder 'GCA_005096895.1_PDT000087339.2' already exists. Skipping...
Folder 'GCA_005096915.1_PDT000087452.2' already exists. Skipping...
Folder 'GCA_005096935.1_PDT000086112.2' already exists. Skipping...
Folder 'GCA_005096975.1_PDT000087448.2' already exists. Skipping...
Folder 'GCA_005097015.1_PDT000087457.2' already exists. Skipping...
Folder 'GCA_005097035.1_PDT000087454.2' already exists. Skipping...
Folder 'GCA_005097075.1_PDT000087466.2' already exists. Skipping...
Folder 'GCA_005097115.1_PDT000087472.2' already exists. Skipping...
Folder 'GCA_005097135.1_PDT000095320.2' already exists. Skipping...
Folder 'GCA_005097155.1_PDT000087468.2' already exists. Skipping...
Folder 'GCA_005097195.1_PDT000092891.2' already exists. Skipping...
Folder 'GCA_005097215.1_PDT000094734.2' already exists. Skipping...
Folder 'GCA_005097235.1_PDT000094297.2' already exists. Skipping...
Folder 'GCA_005097255.1_PDT000095380.2' already exists. Skipping...
Folder 'GCA_005097285.1_PDT000093289.2' already exists. Skipping...
Folder 'GCA_005097325.1_PDT000094885.2' already exists. Skipping...
Folder 'GCA_005097345.1_PDT000094886.2' already exists. Skipping...
Folder 'GCA_005097365.1_PDT000095327.2' already exists. Skipping...
Folder 'GCA_005097385.1_PDT000095332.2' already exists. Skipping...
Folder 'GCA_005097405.1_PDT000095322.2' already exists. Skipping...
Folder 'GCA_005097425.1_PDT000095379.2' already exists. Skipping...
Folder 'GCA_005097445.1_PDT000095321.2' already exists. Skipping...
Folder 'GCA_005097465.1_PDT000095329.2' already exists. Skipping...
Folder 'GCA_005097545.1_PDT000095383.2' already exists. Skipping...
Folder 'GCA_005097565.1_PDT000095386.2' already exists. Skipping...
Folder 'GCA_005097585.1_PDT000095554.2' already exists. Skipping...
Folder 'GCA_005097605.1_PDT000095391.2' already exists. Skipping...
Folder 'GCA_005097625.1_PDT000082666.3' already exists. Skipping...
Folder 'GCA_005097645.1_PDT000095654.2' already exists. Skipping...
Folder 'GCA_005097665.1_PDT000095647.2' already exists. Skipping...
Folder 'GCA_005097685.1_PDT000095649.2' already exists. Skipping...
Folder 'GCA_005097725.1_PDT000095655.2' already exists. Skipping...
Folder 'GCA_005097765.1_PDT000096691.2' already exists. Skipping...
Folder 'GCA_005097805.1_PDT000096683.2' already exists. Skipping...
Folder 'GCA_005097845.1_PDT000096688.2' already exists. Skipping...
Folder 'GCA_005097855.1_PDT000096693.2' already exists. Skipping...
Folder 'GCA_005097885.1_PDT000096700.2' already exists. Skipping...
Folder 'GCA_005097905.1_PDT000095651.2' already exists. Skipping...
Folder 'GCA_005097965.1_PDT000096718.3' already exists. Skipping...
Folder 'GCA_005097985.1_PDT000096717.2' already exists. Skipping...
Folder 'GCA_005098025.1_PDT000097443.2' already exists. Skipping...
Folder 'GCA_005098045.1_PDT000097445.2' already exists. Skipping...
Folder 'GCA_005098065.1_PDT000098278.2' already exists. Skipping...
Folder 'GCA_005098105.1_PDT000097013.2' already exists. Skipping...
Folder 'GCA_005098125.1_PDT000100958.2' already exists. Skipping...
Folder 'GCA_005098165.1_PDT000100955.2' already exists. Skipping...
Folder 'GCA_005098285.1_PDT000101219.2' already exists. Skipping...
Folder 'GCA_005098325.1_PDT000101450.2' already exists. Skipping...
Folder 'GCA_005098345.1_PDT000101460.2' already exists. Skipping...
Folder 'GCA_005098425.1_PDT000102833.2' already exists. Skipping...
Folder 'GCA_005098465.1_PDT000104871.2' already exists. Skipping...
Folder 'GCA_005098505.1_PDT000102844.2' already exists. Skipping...
Folder 'GCA_005098545.1_PDT000103514.2' already exists. Skipping...
Folder 'GCA_005098605.1_PDT000104876.2' already exists. Skipping...
Folder 'GCA_005098625.1_PDT000103105.2' already exists. Skipping...
Folder 'GCA_005098645.1_PDT000101484.2' already exists. Skipping...
Folder 'GCA_005098665.1_PDT000103521.2' already exists. Skipping...
Folder 'GCA_005098685.1_PDT000103520.2' already exists. Skipping...
Folder 'GCA_005098705.1_PDT000101477.2' already exists. Skipping...
Folder 'GCA_005098725.1_PDT000103511.2' already exists. Skipping...
Folder 'GCA_005098745.1_PDT000103522.2' already exists. Skipping...

Retreiveing data: 45640it [00:08, 6642.56it/s]

Folder 'GCA_005127825.1_PDT000180997.2' already exists. Skipping...
Folder 'GCA_005127845.1_PDT000180995.2' already exists. Skipping...
Folder 'GCA_005127865.1_PDT000181605.2' already exists. Skipping...
Folder 'GCA_005127885.1_PDT000181611.2' already exists. Skipping...
Folder 'GCA_005127905.1_PDT000181633.2' already exists. Skipping...
Folder 'GCA_005127925.1_PDT000181610.2' already exists. Skipping...
Folder 'GCA_005127945.1_PDT000181000.2' already exists. Skipping...
Folder 'GCA_005127965.1_PDT000181613.2' already exists. Skipping...
Folder 'GCA_005128025.1_PDT000181636.2' already exists. Skipping...
Folder 'GCA_005128045.1_PDT000181640.2' already exists. Skipping...
Folder 'GCA_005128105.1_PDT000181853.2' already exists. Skipping...
Folder 'GCA_005128145.1_PDT000181618.2' already exists. Skipping...
Folder 'GCA_005128165.1_PDT000181865.2' already exists. Skipping...
Folder 'GCA_005128185.1_PDT000181859.2' already exists. Skipping...
Folder 'GCA_005128205.1_PDT000181857.2' already exists. Skipping...
Folder 'GCA_005128225.1_PDT000181866.2' already exists. Skipping...
Folder 'GCA_005128245.1_PDT000181861.2' already exists. Skipping...
Folder 'GCA_005128265.1_PDT000181860.2' already exists. Skipping...
Folder 'GCA_005128285.1_PDT000181876.2' already exists. Skipping...
Folder 'GCA_005128305.1_PDT000181864.2' already exists. Skipping...
Folder 'GCA_005128325.1_PDT000181863.2' already exists. Skipping...
Folder 'GCA_005128345.1_PDT000181872.2' already exists. Skipping...
Folder 'GCA_005128385.1_PDT000184341.2' already exists. Skipping...
Folder 'GCA_005128405.1_PDT000184347.2' already exists. Skipping...
Folder 'GCA_005128425.1_PDT000184567.2' already exists. Skipping...
Folder 'GCA_005128445.1_PDT000484825.1' already exists. Skipping...
Folder 'GCA_005128465.1_PDT000485604.1' already exists. Skipping...
Folder 'GCA_005128485.1_PDT000485524.1' already exists. Skipping...
Folder 'GCA_005128525.1_PDT000485526.1' already exists. Skipping...
Folder 'GCA_005128585.1_PDT000485480.1' already exists. Skipping...
Folder 'GCA_005128625.1_PDT000180975.2' already exists. Skipping...
Folder 'GCA_005128665.1_PDT000178772.2' already exists. Skipping...
Folder 'GCA_005128685.1_PDT000178437.2' already exists. Skipping...
Folder 'GCA_005128705.1_PDT000178436.2' already exists. Skipping...
Folder 'GCA_005128725.1_PDT000178443.2' already exists. Skipping...
Folder 'GCA_005128745.1_PDT000178439.2' already exists. Skipping...
Folder 'GCA_005128765.1_PDT000180974.2' already exists. Skipping...
Folder 'GCA_005128805.1_PDT000178438.2' already exists. Skipping...
Folder 'GCA_005128825.1_PDT000177214.2' already exists. Skipping...
Folder 'GCA_005128865.1_PDT000485527.1' already exists. Skipping...
Folder 'GCA_005128925.1_PDT000491051.1' already exists. Skipping...
Folder 'GCA_005128945.1_PDT000485489.1' already exists. Skipping...
Folder 'GCA_005129005.1_PDT000484793.1' already exists. Skipping...
Folder 'GCA_005129025.1_PDT000485607.1' already exists. Skipping...
Folder 'GCA_005129045.1_PDT000484804.1' already exists. Skipping...
Folder 'GCA_005129125.1_PDT000484809.1' already exists. Skipping...
Folder 'GCA_005129185.1_PDT000485483.1' already exists. Skipping...
Folder 'GCA_005129205.1_PDT000485521.1' already exists. Skipping...
Folder 'GCA_005129245.1_PDT000485505.1' already exists. Skipping...
Folder 'GCA_005129265.1_PDT000485639.1' already exists. Skipping...
Folder 'GCA_005129275.1_PDT000485495.1' already exists. Skipping...
Folder 'GCA_005129325.1_PDT000484813.1' already exists. Skipping...
Folder 'GCA_005129345.1_PDT000485618.1' already exists. Skipping...
Folder 'GCA_005129355.1_PDT000485517.1' already exists. Skipping...
Folder 'GCA_005129385.1_PDT000485516.1' already exists. Skipping...
Folder 'GCA_005129405.1_PDT000485633.1' already exists. Skipping...
Folder 'GCA_005129425.1_PDT000485631.1' already exists. Skipping...
Folder 'GCA_005129485.1_PDT000485643.1' already exists. Skipping...
Folder 'GCA_005129525.1_PDT000485641.1' already exists. Skipping...
Folder 'GCA_005129605.1_PDT000485661.1' already exists. Skipping...
Folder 'GCA_005129625.1_PDT000485509.1' already exists. Skipping...
Folder 'GCA_005129665.1_PDT000485664.1' already exists. Skipping...
Folder 'GCA_005129685.1_PDT000485667.1' already exists. Skipping...
Folder 'GCA_005129745.1_PDT000485668.1' already exists. Skipping...
Folder 'GCA_005129785.1_PDT000485710.1' already exists. Skipping...
Folder 'GCA_005129825.1_PDT000491058.1' already exists. Skipping...
Folder 'GCA_005129865.1_PDT000486410.1' already exists. Skipping...
Folder 'GCA_005129905.1_PDT000494996.1' already exists. Skipping...
Folder 'GCA_005129985.1_PDT000486427.1' already exists. Skipping...
Folder 'GCA_005130005.1_PDT000486897.1' already exists. Skipping...
Folder 'GCA_005130025.1_PDT000491030.1' already exists. Skipping...
Folder 'GCA_005130085.1_PDT000490993.1' already exists. Skipping...
Folder 'GCA_005130125.1_PDT000494342.1' already exists. Skipping...
Folder 'GCA_005130165.1_PDT000491040.1' already exists. Skipping...
Folder 'GCA_005130265.1_PDT000490982.1' already exists. Skipping...
Folder 'GCA_005130285.1_PDT000491038.1' already exists. Skipping...
Folder 'GCA_005130305.1_PDT000491063.1' already exists. Skipping...
Folder 'GCA_005130325.1_PDT000491046.1' already exists. Skipping...
Folder 'GCA_005130345.1_PDT000491034.1' already exists. Skipping...
Folder 'GCA_005130365.1_PDT000491044.1' already exists. Skipping...
Folder 'GCA_005130385.1_PDT000491026.1' already exists. Skipping...
Folder 'GCA_005130395.1_PDT000491029.1' already exists. Skipping...
Folder 'GCA_005130425.1_PDT000491007.1' already exists. Skipping...
Folder 'GCA_005130445.1_PDT000490981.1' already exists. Skipping...
Folder 'GCA_005130465.1_PDT000491042.1' already exists. Skipping...
Folder 'GCA_005130485.1_PDT000491361.1' already exists. Skipping...
Folder 'GCA_005130525.1_PDT000491052.1' already exists. Skipping...
Folder 'GCA_005130545.1_PDT000491357.1' already exists. Skipping...
Folder 'GCA_005130605.1_PDT000490995.1' already exists. Skipping...
Folder 'GCA_005130625.1_PDT000491062.1' already exists. Skipping...
Folder 'GCA_005130645.1_PDT000491069.1' already exists. Skipping...
Folder 'GCA_005130665.1_PDT000491067.1' already exists. Skipping...
Folder 'GCA_005130685.1_PDT000491348.1' already exists. Skipping...
Folder 'GCA_005130725.1_PDT000491024.1' already exists. Skipping...
Folder 'GCA_005130745.1_PDT000491060.1' already exists. Skipping...
Folder 'GCA_005130785.1_PDT000491070.1' already exists. Skipping...
Folder 'GCA_005130805.1_PDT000491362.1' already exists. Skipping...
Folder 'GCA_005130825.1_PDT000491011.1' already exists. Skipping...
Folder 'GCA_005130845.1_PDT000494339.1' already exists. Skipping...
Folder 'GCA_005130865.1_PDT000491339.1' already exists. Skipping...
Folder 'GCA_005130885.1_PDT000491652.1' already exists. Skipping...
Folder 'GCA_005130925.1_PDT000491655.1' already exists. Skipping...
Folder 'GCA_005130945.1_PDT000491669.1' already exists. Skipping...
Folder 'GCA_005130965.1_PDT000491665.1' already exists. Skipping...
Folder 'GCA_005131005.1_PDT000492532.1' already exists. Skipping...
Folder 'GCA_005131025.1_PDT000491878.1' already exists. Skipping...
Folder 'GCA_005131065.1_PDT000494282.1' already exists. Skipping...
Folder 'GCA_005131075.1_PDT000492542.1' already exists. Skipping...
Folder 'GCA_005131205.1_PDT000494285.1' already exists. Skipping...
Folder 'GCA_005131245.1_PDT000494297.1' already exists. Skipping...
Folder 'GCA_005131305.1_PDT000494296.1' already exists. Skipping...
Folder 'GCA_005131325.1_PDT000494307.1' already exists. Skipping...
Folder 'GCA_005131345.1_PDT000494298.1' already exists. Skipping...
Folder 'GCA_005131385.1_PDT000494310.1' already exists. Skipping...
Folder 'GCA_005131405.1_PDT000494311.1' already exists. Skipping...
Folder 'GCA_005131445.1_PDT000494313.1' already exists. Skipping...
Folder 'GCA_005131485.1_PDT000494322.1' already exists. Skipping...
Folder 'GCA_005131545.1_PDT000494323.1' already exists. Skipping...
Folder 'GCA_005131585.1_PDT000494345.1' already exists. Skipping...
Folder 'GCA_005131605.1_PDT000494336.1' already exists. Skipping...
Folder 'GCA_005131665.1_PDT000494333.1' already exists. Skipping...
Folder 'GCA_005131725.1_PDT000495344.1' already exists. Skipping...
Folder 'GCA_005131745.1_PDT000495004.1' already exists. Skipping...
Folder 'GCA_005131785.1_PDT000494903.1' already exists. Skipping...
Folder 'GCA_005131845.1_PDT000495000.1' already exists. Skipping...
Folder 'GCA_005131885.1_PDT000495148.1' already exists. Skipping...
Folder 'GCA_005131905.1_PDT000495149.1' already exists. Skipping...
Folder 'GCA_005131925.1_PDT000495074.1' already exists. Skipping...
Folder 'GCA_005131985.1_PDT000495156.1' already exists. Skipping...
Folder 'GCA_005132005.1_PDT000495165.1' already exists. Skipping...
Folder 'GCA_005132045.1_PDT000495158.1' already exists. Skipping...
Folder 'GCA_005132085.1_PDT000495168.1' already exists. Skipping...
Folder 'GCA_005132105.1_PDT000495154.1' already exists. Skipping...
Folder 'GCA_005132125.1_PDT000495169.1' already exists. Skipping...
Folder 'GCA_005132145.1_PDT000495172.1' already exists. Skipping...
Folder 'GCA_005132165.1_PDT000495167.1' already exists. Skipping...
Folder 'GCA_005132185.1_PDT000495215.1' already exists. Skipping...
Folder 'GCA_005132205.1_PDT000495173.1' already exists. Skipping...
Folder 'GCA_005132225.1_PDT000495175.1' already exists. Skipping...
Folder 'GCA_005132245.1_PDT000495204.1' already exists. Skipping...
Folder 'GCA_005132285.1_PDT000495251.1' already exists. Skipping...
Folder 'GCA_005132345.1_PDT000495342.1' already exists. Skipping...
Folder 'GCA_005132365.1_PDT000495350.1' already exists. Skipping...
Folder 'GCA_005132385.1_PDT000495277.1' already exists. Skipping...
Folder 'GCA_005132425.1_PDT000046005.2' already exists. Skipping...
Folder 'GCA_005132445.1_PDT000046023.2' already exists. Skipping...
Folder 'GCA_005132485.1_PDT000046017.2' already exists. Skipping...
Folder 'GCA_005132525.1_PDT000053690.2' already exists. Skipping...
Folder 'GCA_005132545.1_PDT000046018.2' already exists. Skipping...
Folder 'GCA_005132565.1_PDT000046014.2' already exists. Skipping...
Folder 'GCA_005132585.1_PDT000046022.2' already exists. Skipping...
Folder 'GCA_005132605.1_PDT000046019.2' already exists. Skipping...
Folder 'GCA_005132625.1_PDT000046007.2' already exists. Skipping...
Folder 'GCA_005132645.1_PDT000048218.2' already exists. Skipping...
Folder 'GCA_005132705.2_ASM513270v2' already exists. Skipping...
Folder 'GCA_005132725.1_PDT000046028.2' already exists. Skipping...
Folder 'GCA_005132745.1_PDT000053685.2' already exists. Skipping...
Folder 'GCA_005132765.2_ASM513276v2' already exists. Skipping...
Folder 'GCA_005132785.2_ASM513278v2' already exists. Skipping...
Folder 'GCA_005132825.1_PDT000049355.2' already exists. Skipping...
Folder 'GCA_005132885.1_PDT000049353.2' already exists. Skipping...
Folder 'GCA_005132925.1_PDT000049358.2' already exists. Skipping...
Folder 'GCA_005132945.1_PDT000049877.2' already exists. Skipping...
Folder 'GCA_005133045.1_PDT000061226.2' already exists. Skipping...
Folder 'GCA_005133065.2_ASM513306v2' already exists. Skipping...
Folder 'GCA_005133105.1_PDT000061227.2' already exists. Skipping...
Folder 'GCA_005133125.1_PDT000061231.2' already exists. Skipping...
Folder 'GCA_005133145.1_PDT000061234.2' already exists. Skipping...
Folder 'GCA_005133165.1_PDT000061228.2' already exists. Skipping...
Folder 'GCA_005133205.1_PDT000061233.2' already exists. Skipping...
Folder 'GCA_005133245.1_PDT000061251.2' already exists. Skipping...
Folder 'GCA_005133265.1_PDT000061262.2' already exists. Skipping...
Folder 'GCA_005133305.1_PDT000061259.2' already exists. Skipping...
Folder 'GCA_005133325.1_PDT000061261.2' already exists. Skipping...
Folder 'GCA_005133345.1_PDT000061258.2' already exists. Skipping...
Folder 'GCA_005133365.1_PDT000061263.2' already exists. Skipping...
Folder 'GCA_005133405.1_PDT000061265.2' already exists. Skipping...
Folder 'GCA_005133445.1_PDT000062796.2' already exists. Skipping...
Folder 'GCA_005133465.1_PDT000062776.2' already exists. Skipping...
Folder 'GCA_005133485.1_PDT000094287.2' already exists. Skipping...
Folder 'GCA_005133525.1_PDT000062795.2' already exists. Skipping...
Folder 'GCA_005133545.1_PDT000062801.2' already exists. Skipping...
Folder 'GCA_005133555.1_PDT000062797.2' already exists. Skipping...
Folder 'GCA_005133585.1_PDT000062788.2' already exists. Skipping...
Folder 'GCA_005133645.1_PDT000062925.2' already exists. Skipping...
Folder 'GCA_005133665.1_PDT000070065.2' already exists. Skipping...
Folder 'GCA_005133725.1_PDT000094302.2' already exists. Skipping...
Folder 'GCA_005133765.1_PDT000061276.2' already exists. Skipping...
Folder 'GCA_005133785.1_PDT000082546.2' already exists. Skipping...
Folder 'GCA_005133805.1_PDT000061283.2' already exists. Skipping...
Folder 'GCA_005133825.1_PDT000069928.2' already exists. Skipping...
Folder 'GCA_005133865.1_PDT000062653.2' already exists. Skipping...
Folder 'GCA_005133885.1_PDT000081843.2' already exists. Skipping...
Folder 'GCA_005134005.1_PDT000062775.2' already exists. Skipping...
Folder 'GCA_005134065.1_PDT000098274.2' already exists. Skipping...
Folder 'GCA_005134075.1_PDT000062758.3' already exists. Skipping...
Folder 'GCA_005134125.1_PDT000100957.2' already exists. Skipping...
Folder 'GCA_005134145.1_PDT000062762.2' already exists. Skipping...
Folder 'GCA_005134165.1_PDT000062810.2' already exists. Skipping...
Folder 'GCA_005134185.1_PDT000062807.3' already exists. Skipping...
Folder 'GCA_005134205.1_PDT000062743.2' already exists. Skipping...
Folder 'GCA_005134245.1_PDT000062745.2' already exists. Skipping...
Folder 'GCA_005134265.1_PDT000062740.2' already exists. Skipping...
Folder 'GCA_005134305.1_PDT000062763.2' already exists. Skipping...
Folder 'GCA_005134325.1_PDT000062767.2' already exists. Skipping...
Folder 'GCA_005134345.1_PDT000081840.2' already exists. Skipping...
Folder 'GCA_005134365.2_ASM513436v2' already exists. Skipping...
Folder 'GCA_005134385.1_PDT000094296.2' already exists. Skipping...
Folder 'GCA_005134405.1_PDT000094293.2' already exists. Skipping...
Folder 'GCA_005134425.1_PDT000094883.2' already exists. Skipping...
Folder 'GCA_005134445.1_PDT000062817.2' already exists. Skipping...
Folder 'GCA_005134455.1_PDT000062827.2' already exists. Skipping...
Folder 'GCA_005134485.1_PDT000062811.2' already exists. Skipping...
Folder 'GCA_005134505.1_PDT000062822.2' already exists. Skipping...
Folder 'GCA_005134525.1_PDT000094283.2' already exists. Skipping...
Folder 'GCA_005134535.1_PDT000062838.2' already exists. Skipping...
Folder 'GCA_005134565.1_PDT000062831.2' already exists. Skipping...
Folder 'GCA_005134575.1_PDT000062845.2' already exists. Skipping...
Folder 'GCA_005134605.1_PDT000062839.2' already exists. Skipping...
Folder 'GCA_005134625.1_PDT000062844.2' already exists. Skipping...
Folder 'GCA_005134645.1_PDT000062842.2' already exists. Skipping...
Folder 'GCA_005134665.1_PDT000062849.2' already exists. Skipping...
Folder 'GCA_005134685.1_PDT000100954.2' already exists. Skipping...
Folder 'GCA_005134705.1_PDT000062850.2' already exists. Skipping...
Folder 'GCA_005134725.1_PDT000062856.2' already exists. Skipping...
Folder 'GCA_005134745.1_PDT000062863.2' already exists. Skipping...
Folder 'GCA_005134785.1_PDT000062878.2' already exists. Skipping...
Folder 'GCA_005134805.1_PDT000062861.2' already exists. Skipping...
Folder 'GCA_005134825.1_PDT000098279.2' already exists. Skipping...
Folder 'GCA_005134845.1_PDT000062868.2' already exists. Skipping...
Folder 'GCA_005134865.1_PDT000062883.2' already exists. Skipping...
Folder 'GCA_005134885.1_PDT000100962.2' already exists. Skipping...
Folder 'GCA_005134905.1_PDT000062897.2' already exists. Skipping...
Folder 'GCA_005134925.1_PDT000062901.2' already exists. Skipping...
Folder 'GCA_005134945.1_PDT000062884.2' already exists. Skipping...
Folder 'GCA_005134965.1_PDT000062900.2' already exists. Skipping...
Folder 'GCA_005134985.1_PDT000062892.2' already exists. Skipping...
Folder 'GCA_005135005.1_PDT000100959.2' already exists. Skipping...
Folder 'GCA_005135025.1_PDT000062903.2' already exists. Skipping...
Folder 'GCA_005135045.2_ASM513504v2' already exists. Skipping...
Folder 'GCA_005135085.1_PDT000062915.2' already exists. Skipping...
Folder 'GCA_005135105.1_PDT000062909.2' already exists. Skipping...
Folder 'GCA_005135135.1_PDT000062912.2' already exists. Skipping...
Folder 'GCA_005135185.1_PDT000062905.3' already exists. Skipping...
Folder 'GCA_005135225.1_PDT000095653.2' already exists. Skipping...
Folder 'GCA_005135615.1_PDT000063209.2' already exists. Skipping...
Folder 'GCA_005135665.1_PDT000063213.2' already exists. Skipping...
Folder 'GCA_005135705.1_PDT000063217.2' already exists. Skipping...
Folder 'GCA_005135725.1_PDT000063219.2' already exists. Skipping...
Folder 'GCA_005135745.1_PDT000063205.2' already exists. Skipping...
Folder 'GCA_005135775.1_PDT000063214.2' already exists. Skipping...
Folder 'GCA_005135805.1_PDT000064974.2' already exists. Skipping...
Folder 'GCA_005135905.1_PDT000067192.2' already exists. Skipping...
Folder 'GCA_005135925.1_PDT000082550.2' already exists. Skipping...
Folder 'GCA_005135945.1_PDT000082547.2' already exists. Skipping...
Folder 'GCA_005135985.1_PDT000085741.2' already exists. Skipping...
Folder 'GCA_005135995.1_PDT000085570.2' already exists. Skipping...
Folder 'GCA_005136045.1_PDT000085753.2' already exists. Skipping...
Folder 'GCA_005136065.1_PDT000085739.2' already exists. Skipping...
Folder 'GCA_005136085.1_PDT000086106.2' already exists. Skipping...
Folder 'GCA_005136105.1_PDT000085745.2' already exists. Skipping...
Folder 'GCA_005136125.1_PDT000085571.2' already exists. Skipping...
Folder 'GCA_005136145.1_PDT000086111.3' already exists. Skipping...
Folder 'GCA_005136165.1_PDT000086107.2' already exists. Skipping...
Folder 'GCA_005136215.1_PDT000085757.2' already exists. Skipping...
Folder 'GCA_005136275.1_PDT000086116.2' already exists. Skipping...
Folder 'GCA_005136325.1_PDT000086114.2' already exists. Skipping...
Folder 'GCA_005136365.2_ASM513636v2' already exists. Skipping...
Folder 'GCA_005136385.1_PDT000086198.2' already exists. Skipping...
Folder 'GCA_005136405.1_PDT000086121.2' already exists. Skipping...
Folder 'GCA_005136415.1_PDT000086123.2' already exists. Skipping...
Folder 'GCA_005136465.2_ASM513646v2' already exists. Skipping...
Folder 'GCA_005136485.1_PDT000087446.2' already exists. Skipping...
Folder 'GCA_005136505.1_PDT000087447.2' already exists. Skipping...
Folder 'GCA_005136525.1_PDT000087450.2' already exists. Skipping...
Folder 'GCA_005136545.1_PDT000087469.2' already exists. Skipping...
Folder 'GCA_005136565.1_PDT000087470.2' already exists. Skipping...
Folder 'GCA_005136585.1_PDT000087496.2' already exists. Skipping...
Folder 'GCA_005136605.1_PDT000092889.2' already exists. Skipping...
Folder 'GCA_005136625.1_PDT000087499.2' already exists. Skipping...
Folder 'GCA_005136635.1_PDT000092894.2' already exists. Skipping...
Folder 'GCA_005136665.1_PDT000092903.2' already exists. Skipping...
Folder 'GCA_005136685.1_PDT000087500.2' already exists. Skipping...
Folder 'GCA_005136765.1_PDT000094243.2' already exists. Skipping...
Folder 'GCA_005136785.1_PDT000095378.2' already exists. Skipping...
Folder 'GCA_005136805.1_PDT000095170.2' already exists. Skipping...
Folder 'GCA_005136825.1_PDT000094887.2' already exists. Skipping...
Folder 'GCA_005136845.1_PDT000095384.2' already exists. Skipping...
Folder 'GCA_005136865.1_PDT000095324.2' already exists. Skipping...
Folder 'GCA_005136905.1_PDT000082545.3' already exists. Skipping...
Folder 'GCA_005136965.1_PDT000095648.2' already exists. Skipping...
Folder 'GCA_005136975.1_PDT000095650.2' already exists. Skipping...
Folder 'GCA_005137005.1_PDT000095652.2' already exists. Skipping...
Folder 'GCA_005137025.1_PDT000095656.2' already exists. Skipping...

Retreiveing data: 46982it [00:08, 6676.35it/s]

Folder 'GCA_005170585.1_PDT000272963.2' already exists. Skipping...
Folder 'GCA_005170605.1_PDT000320114.2' already exists. Skipping...
Folder 'GCA_005170645.1_PDT000245698.2' already exists. Skipping...
Folder 'GCA_005170685.1_PDT000320062.2' already exists. Skipping...
Folder 'GCA_005170785.1_PDT000298342.2' already exists. Skipping...
Folder 'GCA_005170845.1_PDT000320094.2' already exists. Skipping...
Folder 'GCA_005170885.1_PDT000319117.2' already exists. Skipping...
Folder 'GCA_005170905.1_PDT000308474.2' already exists. Skipping...
Folder 'GCA_005170925.1_PDT000319167.2' already exists. Skipping...
Folder 'GCA_005170945.1_PDT000319182.2' already exists. Skipping...
Folder 'GCA_005170965.1_PDT000317538.2' already exists. Skipping...
Folder 'GCA_005170975.1_PDT000315062.2' already exists. Skipping...
Folder 'GCA_005171005.1_PDT000314349.2' already exists. Skipping...
Folder 'GCA_005171045.1_PDT000274309.2' already exists. Skipping...
Folder 'GCA_005171115.1_PDT000320087.2' already exists. Skipping...
Folder 'GCA_005171135.1_PDT000137119.3' already exists. Skipping...
Folder 'GCA_005171155.1_PDT000272473.2' already exists. Skipping...
Folder 'GCA_005171175.1_PDT000269751.2' already exists. Skipping...
Folder 'GCA_005171195.1_PDT000310751.2' already exists. Skipping...
Folder 'GCA_005171225.1_PDT000173285.3' already exists. Skipping...
Folder 'GCA_005171245.1_PDT000269848.2' already exists. Skipping...
Folder 'GCA_005171265.1_PDT000285257.2' already exists. Skipping...
Folder 'GCA_005171285.1_PDT000281725.2' already exists. Skipping...
Folder 'GCA_005171305.1_PDT000287682.2' already exists. Skipping...
Folder 'GCA_005171325.1_PDT000287662.2' already exists. Skipping...
Folder 'GCA_005171345.1_PDT000271332.2' already exists. Skipping...
Folder 'GCA_005171365.1_PDT000319177.2' already exists. Skipping...
Folder 'GCA_005171405.1_PDT000307265.2' already exists. Skipping...
Folder 'GCA_005171425.1_PDT000303425.2' already exists. Skipping...
Folder 'GCA_005171445.1_PDT000313306.2' already exists. Skipping...
Folder 'GCA_005171465.1_PDT000310550.2' already exists. Skipping...
Folder 'GCA_005171485.1_PDT000263069.2' already exists. Skipping...
Folder 'GCA_005171505.1_PDT000313311.2' already exists. Skipping...
Folder 'GCA_005171525.1_PDT000252053.2' already exists. Skipping...
Folder 'GCA_005171545.1_PDT000319188.2' already exists. Skipping...
Folder 'GCA_005171565.1_PDT000317533.2' already exists. Skipping...
Folder 'GCA_005171585.1_PDT000288683.2' already exists. Skipping...
Folder 'GCA_005171605.1_PDT000310498.2' already exists. Skipping...
Folder 'GCA_005171645.1_PDT000319651.2' already exists. Skipping...
Folder 'GCA_005171725.1_PDT000316077.2' already exists. Skipping...
Folder 'GCA_005171765.1_PDT000303595.2' already exists. Skipping...
Folder 'GCA_005171785.1_PDT000135838.3' already exists. Skipping...
Folder 'GCA_005171825.1_PDT000293370.2' already exists. Skipping...
Folder 'GCA_005171845.1_PDT000294558.2' already exists. Skipping...
Folder 'GCA_005171885.1_PDT000276993.2' already exists. Skipping...
Folder 'GCA_005171905.1_PDT000294635.2' already exists. Skipping...
Folder 'GCA_005171945.1_PDT000277777.2' already exists. Skipping...
Folder 'GCA_005171965.1_PDT000320109.2' already exists. Skipping...
Folder 'GCA_005171985.1_PDT000266590.2' already exists. Skipping...
Folder 'GCA_005172025.1_PDT000285272.2' already exists. Skipping...
Folder 'GCA_005172085.1_PDT000303600.2' already exists. Skipping...
Folder 'GCA_005172105.1_PDT000277008.2' already exists. Skipping...
Folder 'GCA_005172125.1_PDT000281048.2' already exists. Skipping...
Folder 'GCA_005172145.1_PDT000308901.2' already exists. Skipping...
Folder 'GCA_005172165.1_PDT000286848.2' already exists. Skipping...
Folder 'GCA_005172185.1_PDT000294585.2' already exists. Skipping...
Folder 'GCA_005172205.1_PDT000287546.2' already exists. Skipping...
Folder 'GCA_005172225.1_PDT000273712.2' already exists. Skipping...
Folder 'GCA_005172265.1_PDT000273727.2' already exists. Skipping...
Folder 'GCA_005172415.1_PDT000145973.2' already exists. Skipping...
Folder 'GCA_005172505.1_PDT000149261.2' already exists. Skipping...
Folder 'GCA_005172545.1_PDT000218621.2' already exists. Skipping...
Folder 'GCA_005172565.1_PDT000187326.2' already exists. Skipping...
Folder 'GCA_005172605.1_PDT000162118.2' already exists. Skipping...
Folder 'GCA_005172625.1_PDT000181637.2' already exists. Skipping...
Folder 'GCA_005172645.1_PDT000145961.2' already exists. Skipping...
Folder 'GCA_005172665.1_PDT000215066.2' already exists. Skipping...
Folder 'GCA_005172705.1_PDT000218812.2' already exists. Skipping...
Folder 'GCA_005172785.1_PDT000198494.2' already exists. Skipping...
Folder 'GCA_005172865.1_PDT000190608.2' already exists. Skipping...
Folder 'GCA_005172885.1_PDT000190619.2' already exists. Skipping...
Folder 'GCA_005172905.1_PDT000215145.2' already exists. Skipping...
Folder 'GCA_005172925.1_PDT000146083.2' already exists. Skipping...
Folder 'GCA_005172945.1_PDT000175421.2' already exists. Skipping...
Folder 'GCA_005173045.1_PDT000184575.2' already exists. Skipping...
Folder 'GCA_005173125.1_PDT000218742.2' already exists. Skipping...
Folder 'GCA_005173205.1_PDT000184568.2' already exists. Skipping...
Folder 'GCA_005173225.1_PDT000183033.2' already exists. Skipping...
Folder 'GCA_005173265.1_PDT000150767.2' already exists. Skipping...
Folder 'GCA_005173305.1_PDT000162820.2' already exists. Skipping...
Folder 'GCA_005173315.1_PDT000150794.2' already exists. Skipping...
Folder 'GCA_005173365.1_PDT000196404.2' already exists. Skipping...
Folder 'GCA_005173385.1_PDT000179193.2' already exists. Skipping...
Folder 'GCA_005173405.1_PDT000174444.2' already exists. Skipping...
Folder 'GCA_005173425.1_PDT000180996.2' already exists. Skipping...
Folder 'GCA_005173455.1_PDT000171774.2' already exists. Skipping...
Folder 'GCA_005173475.1_PDT000221395.2' already exists. Skipping...
Folder 'GCA_005173525.1_PDT000182986.2' already exists. Skipping...
Folder 'GCA_005173545.1_PDT000182952.2' already exists. Skipping...
Folder 'GCA_005173585.1_PDT000168405.2' already exists. Skipping...
Folder 'GCA_005173605.1_PDT000159062.2' already exists. Skipping...
Folder 'GCA_005173625.1_PDT000180976.2' already exists. Skipping...
Folder 'GCA_005173645.1_PDT000173582.2' already exists. Skipping...
Folder 'GCA_005173665.1_PDT000150773.2' already exists. Skipping...
Folder 'GCA_005173685.1_PDT000152798.2' already exists. Skipping...
Folder 'GCA_005173705.1_PDT000215071.2' already exists. Skipping...
Folder 'GCA_005173745.1_PDT000193510.2' already exists. Skipping...
Folder 'GCA_005173765.1_PDT000168418.2' already exists. Skipping...
Folder 'GCA_005173825.1_PDT000180978.2' already exists. Skipping...
Folder 'GCA_005173845.1_PDT000176580.2' already exists. Skipping...
Folder 'GCA_005173925.1_PDT000190627.2' already exists. Skipping...
Folder 'GCA_005173945.1_PDT000173599.2' already exists. Skipping...
Folder 'GCA_005173965.1_PDT000168422.2' already exists. Skipping...
Folder 'GCA_005173985.1_PDT000154681.2' already exists. Skipping...
Folder 'GCA_005174005.1_PDT000162116.2' already exists. Skipping...
Folder 'GCA_005174025.1_PDT000185463.2' already exists. Skipping...
Folder 'GCA_005174045.1_PDT000176567.2' already exists. Skipping...
Folder 'GCA_005174065.1_PDT000168411.2' already exists. Skipping...
Folder 'GCA_005174085.1_PDT000192022.2' already exists. Skipping...
Folder 'GCA_005174105.1_PDT000190960.2' already exists. Skipping...
Folder 'GCA_005174125.1_PDT000195289.2' already exists. Skipping...
Folder 'GCA_005174145.1_PDT000172076.2' already exists. Skipping...
Folder 'GCA_005174165.1_PDT000168381.2' already exists. Skipping...
Folder 'GCA_005174185.1_PDT000189098.2' already exists. Skipping...
Folder 'GCA_005174325.1_PDT000189351.2' already exists. Skipping...
Folder 'GCA_005174345.1_PDT000181638.2' already exists. Skipping...
Folder 'GCA_005174365.1_PDT000215068.2' already exists. Skipping...
Folder 'GCA_005174385.1_PDT000171388.2' already exists. Skipping...
Folder 'GCA_005174415.1_PDT000187317.2' already exists. Skipping...
Folder 'GCA_005174445.1_PDT000192389.2' already exists. Skipping...
Folder 'GCA_005174465.1_PDT000218737.2' already exists. Skipping...
Folder 'GCA_005174485.1_PDT000171873.2' already exists. Skipping...
Folder 'GCA_005174505.1_PDT000218648.2' already exists. Skipping...
Folder 'GCA_005174525.1_PDT000218749.2' already exists. Skipping...
Folder 'GCA_005174545.1_PDT000193480.2' already exists. Skipping...
Folder 'GCA_005174565.1_PDT000215083.2' already exists. Skipping...
Folder 'GCA_005174585.1_PDT000189095.2' already exists. Skipping...
Folder 'GCA_005174605.1_PDT000215065.2' already exists. Skipping...
Folder 'GCA_005174625.1_PDT000192034.2' already exists. Skipping...
Folder 'GCA_005174645.1_PDT000197514.2' already exists. Skipping...
Folder 'GCA_005174665.1_PDT000218650.2' already exists. Skipping...
Folder 'GCA_005174685.1_PDT000198500.2' already exists. Skipping...
Folder 'GCA_005174705.1_PDT000171773.2' already exists. Skipping...
Folder 'GCA_005174715.1_PDT000190974.2' already exists. Skipping...
Folder 'GCA_005174745.1_PDT000190573.2' already exists. Skipping...
Folder 'GCA_005174845.1_PDT000218735.2' already exists. Skipping...
Folder 'GCA_005174865.1_PDT000218619.2' already exists. Skipping...
Folder 'GCA_005174885.1_PDT000187314.2' already exists. Skipping...
Folder 'GCA_005174905.1_PDT000181635.2' already exists. Skipping...
Folder 'GCA_005174925.1_PDT000184572.2' already exists. Skipping...
Folder 'GCA_005175005.1_PDT000190609.2' already exists. Skipping...
Folder 'GCA_005175025.1_PDT000201329.2' already exists. Skipping...
Folder 'GCA_005175105.1_PDT000198031.2' already exists. Skipping...
Folder 'GCA_005175145.1_PDT000221420.2' already exists. Skipping...
Folder 'GCA_005175165.1_PDT000233459.2' already exists. Skipping...
Folder 'GCA_005175185.1_PDT000197527.2' already exists. Skipping...
Folder 'GCA_005175205.1_PDT000221410.2' already exists. Skipping...
Folder 'GCA_005175225.1_PDT000217315.2' already exists. Skipping...
Folder 'GCA_005175235.1_PDT000177650.2' already exists. Skipping...
Folder 'GCA_005175265.1_PDT000195381.2' already exists. Skipping...
Folder 'GCA_005175285.1_PDT000185497.2' already exists. Skipping...
Folder 'GCA_005175295.1_PDT000187626.2' already exists. Skipping...
Folder 'GCA_005175325.1_PDT000185470.2' already exists. Skipping...
Folder 'GCA_005175345.1_PDT000185485.2' already exists. Skipping...
Folder 'GCA_005175365.1_PDT000184339.2' already exists. Skipping...
Folder 'GCA_005175385.1_PDT000181869.2' already exists. Skipping...
Folder 'GCA_005175445.1_PDT000185471.2' already exists. Skipping...
Folder 'GCA_005175465.1_PDT000189096.2' already exists. Skipping...
Folder 'GCA_005175485.1_PDT000199681.2' already exists. Skipping...
Folder 'GCA_005175505.1_PDT000187700.2' already exists. Skipping...
Folder 'GCA_005175525.1_PDT000192018.2' already exists. Skipping...
Folder 'GCA_005175535.1_PDT000189074.2' already exists. Skipping...
Folder 'GCA_005175565.1_PDT000187605.2' already exists. Skipping...
Folder 'GCA_005175585.1_PDT000148759.2' already exists. Skipping...
Folder 'GCA_005175595.1_PDT000185481.2' already exists. Skipping...
Folder 'GCA_005175625.1_PDT000149623.2' already exists. Skipping...
Folder 'GCA_005175645.1_PDT000149598.2' already exists. Skipping...
Folder 'GCA_005175665.1_PDT000152306.2' already exists. Skipping...
Folder 'GCA_005175725.1_PDT000167773.2' already exists. Skipping...
Folder 'GCA_005175805.1_PDT000189097.2' already exists. Skipping...
Folder 'GCA_005175825.1_PDT000191006.2' already exists. Skipping...
Folder 'GCA_005175865.1_PDT000197528.2' already exists. Skipping...
Folder 'GCA_005175905.1_PDT000198497.2' already exists. Skipping...
Folder 'GCA_005176065.1_PDT000215079.2' already exists. Skipping...
Folder 'GCA_005176105.1_PDT000218750.2' already exists. Skipping...
Folder 'GCA_005176125.1_PDT000218629.2' already exists. Skipping...
Folder 'GCA_005176165.1_PDT000184580.2' already exists. Skipping...
Folder 'GCA_005176205.1_PDT000183208.2' already exists. Skipping...
Folder 'GCA_005176445.1_PDT000182959.2' already exists. Skipping...
Folder 'GCA_005176465.1_PDT000192368.2' already exists. Skipping...
Folder 'GCA_005176475.1_PDT000221392.2' already exists. Skipping...
Folder 'GCA_005176525.1_PDT000162237.3' already exists. Skipping...
Folder 'GCA_005176545.1_PDT000221412.2' already exists. Skipping...
Folder 'GCA_005176605.1_PDT000201206.2' already exists. Skipping...
Folder 'GCA_005176615.1_PDT000208215.2' already exists. Skipping...
Folder 'GCA_005176645.1_PDT000193625.2' already exists. Skipping...
Folder 'GCA_005176665.1_PDT000193525.2' already exists. Skipping...
Folder 'GCA_005176685.1_PDT000196411.2' already exists. Skipping...
Folder 'GCA_005176725.1_PDT000198036.2' already exists. Skipping...
Folder 'GCA_005176865.1_PDT000201331.2' already exists. Skipping...
Folder 'GCA_005176885.1_PDT000196406.2' already exists. Skipping...
Folder 'GCA_005176905.1_PDT000217335.2' already exists. Skipping...
Folder 'GCA_005176925.1_PDT000225208.2' already exists. Skipping...
Folder 'GCA_005176945.1_PDT000217419.2' already exists. Skipping...
Folder 'GCA_005176965.1_PDT000190650.2' already exists. Skipping...
Folder 'GCA_005176985.1_PDT000221415.2' already exists. Skipping...
Folder 'GCA_005177005.1_PDT000233461.2' already exists. Skipping...
Folder 'GCA_005177045.1_PDT000217307.2' already exists. Skipping...
Folder 'GCA_005177065.1_PDT000192815.2' already exists. Skipping...
Folder 'GCA_005177085.1_PDT000221424.2' already exists. Skipping...
Folder 'GCA_005177105.1_PDT000192802.2' already exists. Skipping...
Folder 'GCA_005177125.1_PDT000192387.2' already exists. Skipping...
Folder 'GCA_005177145.1_PDT000182946.2' already exists. Skipping...
Folder 'GCA_005177165.1_PDT000485877.1' already exists. Skipping...
Folder 'GCA_005177205.1_PDT000193613.2' already exists. Skipping...
Folder 'GCA_005177225.1_PDT000193623.2' already exists. Skipping...
Folder 'GCA_005177305.1_PDT000190575.2' already exists. Skipping...
Folder 'GCA_005177365.1_PDT000175577.2' already exists. Skipping...
Folder 'GCA_005177405.1_PDT000187332.2' already exists. Skipping...
Folder 'GCA_005177445.1_PDT000182957.2' already exists. Skipping...
Folder 'GCA_005177465.1_PDT000221390.2' already exists. Skipping...
Folder 'GCA_005177485.1_PDT000218734.2' already exists. Skipping...
Folder 'GCA_005177505.1_PDT000171870.2' already exists. Skipping...
Folder 'GCA_005177525.1_PDT000215073.2' already exists. Skipping...
Folder 'GCA_005177545.1_PDT000195276.2' already exists. Skipping...
Folder 'GCA_005177565.1_PDT000215075.2' already exists. Skipping...
Folder 'GCA_005177585.1_PDT000189090.2' already exists. Skipping...
Folder 'GCA_005177605.1_PDT000189115.2' already exists. Skipping...
Folder 'GCA_005177625.1_PDT000218736.2' already exists. Skipping...
Folder 'GCA_005177645.1_PDT000192024.2' already exists. Skipping...
Folder 'GCA_005177665.1_PDT000190613.2' already exists. Skipping...
Folder 'GCA_005177685.1_PDT000171872.2' already exists. Skipping...
Folder 'GCA_005177705.1_PDT000171776.2' already exists. Skipping...
Folder 'GCA_005177725.1_PDT000171758.2' already exists. Skipping...
Folder 'GCA_005177745.1_PDT000192813.2' already exists. Skipping...
Folder 'GCA_005177765.1_PDT000187335.2' already exists. Skipping...
Folder 'GCA_005177785.1_PDT000218630.2' already exists. Skipping...
Folder 'GCA_005177805.1_PDT000198495.2' already exists. Skipping...
Folder 'GCA_005177825.1_PDT000195367.2' already exists. Skipping...
Folder 'GCA_005177845.1_PDT000171876.2' already exists. Skipping...
Folder 'GCA_005177865.1_PDT000178458.2' already exists. Skipping...
Folder 'GCA_005177875.1_PDT000190578.2' already exists. Skipping...
Folder 'GCA_005177905.1_PDT000174449.2' already exists. Skipping...
Folder 'GCA_005177965.1_PDT000224581.2' already exists. Skipping...
Folder 'GCA_005177985.1_PDT000221400.2' already exists. Skipping...
Folder 'GCA_005178005.1_PDT000225218.2' already exists. Skipping...
Folder 'GCA_005178025.1_PDT000192379.2' already exists. Skipping...
Folder 'GCA_005178065.1_PDT000215061.2' already exists. Skipping...
Folder 'GCA_005178085.1_PDT000193517.2' already exists. Skipping...
Folder 'GCA_005178105.1_PDT000217413.2' already exists. Skipping...
Folder 'GCA_005178125.1_PDT000182944.2' already exists. Skipping...
Folder 'GCA_005178145.1_PDT000182951.2' already exists. Skipping...
Folder 'GCA_005178165.1_PDT000182956.2' already exists. Skipping...
Folder 'GCA_005178185.1_PDT000221387.2' already exists. Skipping...
Folder 'GCA_005178195.1_PDT000183020.2' already exists. Skipping...
Folder 'GCA_005178225.1_PDT000221409.2' already exists. Skipping...
Folder 'GCA_005178245.1_PDT000221402.2' already exists. Skipping...
Folder 'GCA_005178265.1_PDT000221422.2' already exists. Skipping...
Folder 'GCA_005178285.1_PDT000221417.2' already exists. Skipping...
Folder 'GCA_005178305.1_PDT000250288.2' already exists. Skipping...
Folder 'GCA_005178345.1_PDT000272472.2' already exists. Skipping...
Folder 'GCA_005178365.1_PDT000146411.3' already exists. Skipping...
Folder 'GCA_005178385.1_PDT000245054.2' already exists. Skipping...
Folder 'GCA_005178445.1_PDT000266279.2' already exists. Skipping...
Folder 'GCA_005178455.1_PDT000266582.2' already exists. Skipping...
Folder 'GCA_005178485.1_PDT000252055.2' already exists. Skipping...
Folder 'GCA_005178505.1_PDT000273331.2' already exists. Skipping...
Folder 'GCA_005178565.1_PDT000269612.2' already exists. Skipping...
Folder 'GCA_005178575.1_PDT000269572.2' already exists. Skipping...
Folder 'GCA_005178605.1_PDT000266581.2' already exists. Skipping...
Folder 'GCA_005178685.1_PDT000245174.2' already exists. Skipping...
Folder 'GCA_005178725.1_PDT000266597.2' already exists. Skipping...
Folder 'GCA_005178805.1_PDT000239738.2' already exists. Skipping...
Folder 'GCA_005178825.1_PDT000245074.2' already exists. Skipping...
Folder 'GCA_005178845.1_PDT000245246.2' already exists. Skipping...
Folder 'GCA_005178905.1_PDT000287767.2' already exists. Skipping...
Folder 'GCA_005178965.1_PDT000285943.2' already exists. Skipping...
Folder 'GCA_005178985.1_PDT000268342.2' already exists. Skipping...
Folder 'GCA_005179005.1_PDT000144288.3' already exists. Skipping...
Folder 'GCA_005179025.1_PDT000241149.2' already exists. Skipping...
Folder 'GCA_005179065.1_PDT000146410.3' already exists. Skipping...
Folder 'GCA_005179085.1_PDT000150539.3' already exists. Skipping...
Folder 'GCA_005179105.1_PDT000269759.2' already exists. Skipping...
Folder 'GCA_005179115.1_PDT000277773.2' already exists. Skipping...
Folder 'GCA_005179145.1_PDT000247622.2' already exists. Skipping...
Folder 'GCA_005179255.1_PDT000283469.2' already exists. Skipping...
Folder 'GCA_005179345.1_PDT000278704.2' already exists. Skipping...
Folder 'GCA_005179365.1_PDT000283450.2' already exists. Skipping...
Folder 'GCA_005179385.1_PDT000294657.2' already exists. Skipping...
Folder 'GCA_005179465.1_PDT000245706.2' already exists. Skipping...
Folder 'GCA_005179485.1_PDT000283058.2' already exists. Skipping...
Folder 'GCA_005179545.1_PDT000273744.2' already exists. Skipping...
Folder 'GCA_005179565.1_PDT000283100.2' already exists. Skipping...
Folder 'GCA_005179585.1_PDT000278358.2' already exists. Skipping...
Folder 'GCA_005179635.1_PDT000273833.2' already exists. Skipping...
Folder 'GCA_005179705.1_PDT000272467.2' already exists. Skipping...
Folder 'GCA_005179735.1_PDT000269622.2' already exists. Skipping...
Folder 'GCA_005179765.1_PDT000273746.2' already exists. Skipping...
Folder 'GCA_005179785.1_PDT000285948.2' already exists. Skipping...
Folder 'GCA_005179805.1_PDT000283420.2' already exists. Skipping...
Folder 'GCA_005179885.1_PDT000281531.2' already exists. Skipping...
Folder 'GCA_005179905.1_PDT000283170.2' already exists. Skipping...
Folder 'GCA_005179945.1_PDT000278368.2' already exists. Skipping...
Folder 'GCA_005179985.1_PDT000294669.2' already exists. Skipping...

Retreiveing data: 48324it [00:08, 6689.05it/s]

Folder 'GCA_005213745.1_PDT000495166.1' already exists. Skipping...
Folder 'GCA_005213765.1_PDT000495280.1' already exists. Skipping...
Folder 'GCA_005213825.1_PDT000495355.1' already exists. Skipping...
Folder 'GCA_005213865.1_PDT000495359.1' already exists. Skipping...
Folder 'GCA_005213885.1_PDT000495366.1' already exists. Skipping...
Folder 'GCA_005213905.1_PDT000495341.1' already exists. Skipping...
Folder 'GCA_005213915.1_PDT000494330.1' already exists. Skipping...
Folder 'GCA_005213945.1_PDT000495353.1' already exists. Skipping...
Folder 'GCA_005214025.1_PDT000494353.1' already exists. Skipping...
Folder 'GCA_005214105.1_PDT000494286.1' already exists. Skipping...
Folder 'GCA_005214125.1_PDT000494340.1' already exists. Skipping...
Folder 'GCA_005214185.1_PDT000494450.1' already exists. Skipping...
Folder 'GCA_005214265.1_PDT000494454.1' already exists. Skipping...
Folder 'GCA_005214305.1_PDT000231689.2' already exists. Skipping...
Folder 'GCA_005214345.1_PDT000226061.2' already exists. Skipping...
Folder 'GCA_005214385.1_PDT000244911.2' already exists. Skipping...
Folder 'GCA_005214405.1_PDT000490975.1' already exists. Skipping...
Folder 'GCA_005214425.1_PDT000489604.1' already exists. Skipping...
Folder 'GCA_005214445.1_PDT000232711.2' already exists. Skipping...
Folder 'GCA_005214465.1_PDT000490959.1' already exists. Skipping...
Folder 'GCA_005214485.1_PDT000490988.1' already exists. Skipping...
Folder 'GCA_005214505.1_PDT000235443.2' already exists. Skipping...
Folder 'GCA_005214525.1_PDT000224976.2' already exists. Skipping...
Folder 'GCA_005214545.1_PDT000233678.2' already exists. Skipping...
Folder 'GCA_005214585.1_PDT000244818.2' already exists. Skipping...
Folder 'GCA_005214605.1_PDT000237007.2' already exists. Skipping...
Folder 'GCA_005214625.1_PDT000226090.2' already exists. Skipping...
Folder 'GCA_005214645.1_PDT000239505.2' already exists. Skipping...
Folder 'GCA_005214665.1_PDT000489250.1' already exists. Skipping...
Folder 'GCA_005214685.1_PDT000227109.2' already exists. Skipping...
Folder 'GCA_005214705.1_PDT000234037.2' already exists. Skipping...
Folder 'GCA_005214765.1_PDT000219257.2' already exists. Skipping...
Folder 'GCA_005214785.1_PDT000237035.2' already exists. Skipping...
Folder 'GCA_005214805.1_PDT000239530.2' already exists. Skipping...
Folder 'GCA_005214825.1_PDT000205629.2' already exists. Skipping...
Folder 'GCA_005214865.1_PDT000231644.2' already exists. Skipping...
Folder 'GCA_005214885.1_PDT000256932.2' already exists. Skipping...
Folder 'GCA_005214915.1_PDT000244085.2' already exists. Skipping...
Folder 'GCA_005214965.1_PDT000491009.1' already exists. Skipping...
Folder 'GCA_005215025.1_PDT000225832.2' already exists. Skipping...
Folder 'GCA_005215055.1_PDT000239555.2' already exists. Skipping...
Folder 'GCA_005215085.1_PDT000253410.2' already exists. Skipping...
Folder 'GCA_005215105.1_PDT000245370.2' already exists. Skipping...
Folder 'GCA_005215125.1_PDT000244832.2' already exists. Skipping...
Folder 'GCA_005215145.1_PDT000220652.2' already exists. Skipping...
Folder 'GCA_005215165.1_PDT000244924.2' already exists. Skipping...
Folder 'GCA_005215185.1_PDT000250547.2' already exists. Skipping...
Folder 'GCA_005215205.1_PDT000244956.2' already exists. Skipping...
Folder 'GCA_005215225.1_PDT000245896.2' already exists. Skipping...
Folder 'GCA_005215245.1_PDT000181158.2' already exists. Skipping...
Folder 'GCA_005215265.1_PDT000179231.2' already exists. Skipping...
Folder 'GCA_005215365.1_PDT000219213.2' already exists. Skipping...
Folder 'GCA_005215385.1_PDT000219241.2' already exists. Skipping...
Folder 'GCA_005215445.1_PDT000226060.2' already exists. Skipping...
Folder 'GCA_005215485.1_PDT000222888.2' already exists. Skipping...
Folder 'GCA_005215505.1_PDT000216092.2' already exists. Skipping...
Folder 'GCA_005215545.1_PDT000237020.2' already exists. Skipping...
Folder 'GCA_005215565.1_PDT000237047.2' already exists. Skipping...
Folder 'GCA_005215585.1_PDT000231684.2' already exists. Skipping...
Folder 'GCA_005215605.1_PDT000239577.2' already exists. Skipping...
Folder 'GCA_005215625.1_PDT000239562.2' already exists. Skipping...
Folder 'GCA_005215645.1_PDT000239515.2' already exists. Skipping...
Folder 'GCA_005215705.1_PDT000245278.2' already exists. Skipping...
Folder 'GCA_005215825.1_PDT000491053.1' already exists. Skipping...
Folder 'GCA_005215845.1_PDT000491877.1' already exists. Skipping...
Folder 'GCA_005215865.1_PDT000491340.1' already exists. Skipping...
Folder 'GCA_005215895.1_PDT000491064.1' already exists. Skipping...
Folder 'GCA_005215945.1_PDT000491999.1' already exists. Skipping...
Folder 'GCA_005216005.1_PDT000494628.1' already exists. Skipping...
Folder 'GCA_005216015.1_PDT000494897.1' already exists. Skipping...
Folder 'GCA_005216045.1_PDT000494893.1' already exists. Skipping...
Folder 'GCA_005216065.1_PDT000494824.1' already exists. Skipping...
Folder 'GCA_005216085.1_PDT000247136.2' already exists. Skipping...
Folder 'GCA_005216105.1_PDT000237260.2' already exists. Skipping...
Folder 'GCA_005216125.1_PDT000250553.2' already exists. Skipping...
Folder 'GCA_005216145.1_PDT000244796.2' already exists. Skipping...
Folder 'GCA_005216185.1_PDT000245884.2' already exists. Skipping...
Folder 'GCA_005216205.1_PDT000244842.2' already exists. Skipping...
Folder 'GCA_005216225.1_PDT000495367.1' already exists. Skipping...
Folder 'GCA_005216235.1_PDT000245380.2' already exists. Skipping...
Folder 'GCA_005216265.1_PDT000258811.2' already exists. Skipping...
Folder 'GCA_005216285.1_PDT000494626.1' already exists. Skipping...
Folder 'GCA_005216325.1_PDT000495078.1' already exists. Skipping...
Folder 'GCA_005216365.1_PDT000244979.2' already exists. Skipping...
Folder 'GCA_005216385.1_PDT000489282.1' already exists. Skipping...
Folder 'GCA_005216405.1_PDT000490973.1' already exists. Skipping...
Folder 'GCA_005216425.1_PDT000491033.1' already exists. Skipping...
Folder 'GCA_005216465.1_PDT000491037.1' already exists. Skipping...
Folder 'GCA_005216485.1_PDT000491050.1' already exists. Skipping...
Folder 'GCA_005216505.1_PDT000491039.1' already exists. Skipping...
Folder 'GCA_005216525.1_PDT000491032.1' already exists. Skipping...
Folder 'GCA_005216545.1_PDT000491347.1' already exists. Skipping...
Folder 'GCA_005216565.1_PDT000491338.1' already exists. Skipping...
Folder 'GCA_005216585.1_PDT000495403.1' already exists. Skipping...
Folder 'GCA_005216605.1_PDT000473115.2' already exists. Skipping...
Folder 'GCA_005216645.1_PDT000495400.1' already exists. Skipping...
Folder 'GCA_005216685.1_PDT000495519.1' already exists. Skipping...
Folder 'GCA_005216705.1_PDT000495532.1' already exists. Skipping...
Folder 'GCA_005216725.1_PDT000495838.1' already exists. Skipping...
Folder 'GCA_005216745.1_PDT000473000.2' already exists. Skipping...
Folder 'GCA_005216765.1_PDT000495844.1' already exists. Skipping...
Folder 'GCA_005216825.1_PDT000250563.2' already exists. Skipping...
Folder 'GCA_005216845.1_PDT000495842.1' already exists. Skipping...
Folder 'GCA_005216865.1_PDT000495115.1' already exists. Skipping...
Folder 'GCA_005216905.1_PDT000495122.1' already exists. Skipping...
Folder 'GCA_005216965.1_PDT000495222.1' already exists. Skipping...
Folder 'GCA_005216985.1_PDT000495174.1' already exists. Skipping...
Folder 'GCA_005217025.1_PDT000495254.1' already exists. Skipping...
Folder 'GCA_005217105.1_PDT000495348.1' already exists. Skipping...
Folder 'GCA_005217945.1_PDT000472960.2' already exists. Skipping...
Folder 'GCA_005218005.1_PDT000441561.2' already exists. Skipping...
Folder 'GCA_005218065.1_PDT000441563.2' already exists. Skipping...
Folder 'GCA_005218075.1_PDT000441566.2' already exists. Skipping...
Folder 'GCA_005218085.1_PDT000468651.2' already exists. Skipping...
Folder 'GCA_005218225.1_PDT000495160.1' already exists. Skipping...
Folder 'GCA_005218245.1_PDT000495171.1' already exists. Skipping...
Folder 'GCA_005218265.1_PDT000495170.1' already exists. Skipping...
Folder 'GCA_005218285.1_PDT000495176.1' already exists. Skipping...
Folder 'GCA_005218305.1_PDT000495299.1' already exists. Skipping...
Folder 'GCA_005218345.1_PDT000495837.1' already exists. Skipping...
Folder 'GCA_005218365.1_PDT000495206.1' already exists. Skipping...
Folder 'GCA_005218405.1_PDT000495841.1' already exists. Skipping...
Folder 'GCA_005218425.1_PDT000495843.1' already exists. Skipping...
Folder 'GCA_005218445.1_PDT000496124.1' already exists. Skipping...
Folder 'GCA_005218505.1_PDT000496136.1' already exists. Skipping...
Folder 'GCA_005218525.1_PDT000496120.1' already exists. Skipping...
Folder 'GCA_005218645.1_PDT000494914.1' already exists. Skipping...
Folder 'GCA_005218685.1_PDT000489278.1' already exists. Skipping...
Folder 'GCA_005218705.1_PDT000495271.1' already exists. Skipping...
Folder 'GCA_005218725.1_PDT000489297.1' already exists. Skipping...
Folder 'GCA_005218735.1_PDT000489601.1' already exists. Skipping...
Folder 'GCA_005218805.1_PDT000494316.1' already exists. Skipping...
Folder 'GCA_005218845.1_PDT000489260.1' already exists. Skipping...
Folder 'GCA_005218925.1_PDT000495261.1' already exists. Skipping...
Folder 'GCA_005218965.1_PDT000494315.1' already exists. Skipping...
Folder 'GCA_005218985.1_PDT000494319.1' already exists. Skipping...
Folder 'GCA_005219045.1_PDT000489614.1' already exists. Skipping...
Folder 'GCA_005219085.1_PDT000489254.1' already exists. Skipping...
Folder 'GCA_005219115.1_PDT000489612.1' already exists. Skipping...
Folder 'GCA_005219195.1_PDT000490934.1' already exists. Skipping...
Folder 'GCA_005219205.1_PDT000490275.1' already exists. Skipping...
Folder 'GCA_005219285.1_PDT000490968.1' already exists. Skipping...
Folder 'GCA_005219325.1_PDT000490966.1' already exists. Skipping...
Folder 'GCA_005219365.1_PDT000496114.1' already exists. Skipping...
Folder 'GCA_005219385.1_PDT000490996.1' already exists. Skipping...
Folder 'GCA_005219405.1_PDT000490999.1' already exists. Skipping...
Folder 'GCA_005219445.1_PDT000491000.1' already exists. Skipping...
Folder 'GCA_005219465.1_PDT000490992.1' already exists. Skipping...
Folder 'GCA_005219485.1_PDT000491056.1' already exists. Skipping...
Folder 'GCA_005219525.1_PDT000491359.1' already exists. Skipping...
Folder 'GCA_005219545.1_PDT000496117.1' already exists. Skipping...
Folder 'GCA_005219585.1_PDT000490970.1' already exists. Skipping...
Folder 'GCA_005219605.1_PDT000491010.1' already exists. Skipping...
Folder 'GCA_005219625.1_PDT000491025.1' already exists. Skipping...
Folder 'GCA_005219665.1_PDT000491072.1' already exists. Skipping...
Folder 'GCA_005219685.1_PDT000491349.1' already exists. Skipping...
Folder 'GCA_005219695.1_PDT000491004.1' already exists. Skipping...
Folder 'GCA_005219725.1_PDT000491668.1' already exists. Skipping...
Folder 'GCA_005219785.1_PDT000491995.1' already exists. Skipping...
Folder 'GCA_005219845.1_PDT000494300.1' already exists. Skipping...
Folder 'GCA_005219865.1_PDT000494304.1' already exists. Skipping...
Folder 'GCA_005219885.1_PDT000492531.1' already exists. Skipping...
Folder 'GCA_005219925.1_PDT000494288.1' already exists. Skipping...
Folder 'GCA_005219945.1_PDT000494292.1' already exists. Skipping...
Folder 'GCA_005219985.1_PDT000494344.1' already exists. Skipping...
Folder 'GCA_005220025.1_PDT000494337.1' already exists. Skipping...
Folder 'GCA_005220045.1_PDT000494370.1' already exists. Skipping...
Folder 'GCA_005220065.1_PDT000494354.1' already exists. Skipping...
Folder 'GCA_005220105.1_PDT000494358.1' already exists. Skipping...
Folder 'GCA_005220145.1_PDT000494913.1' already exists. Skipping...
Folder 'GCA_005220165.1_PDT000494456.1' already exists. Skipping...
Folder 'GCA_005220205.1_PDT000494623.1' already exists. Skipping...
Folder 'GCA_005220225.1_PDT000494912.1' already exists. Skipping...
Folder 'GCA_005220265.1_PDT000494916.1' already exists. Skipping...
Folder 'GCA_005220325.1_PDT000495111.1' already exists. Skipping...
Folder 'GCA_005220345.1_PDT000495071.1' already exists. Skipping...
Folder 'GCA_005220465.1_PDT000495141.1' already exists. Skipping...
Folder 'GCA_005220505.1_PDT000495283.1' already exists. Skipping...
Folder 'GCA_005220605.1_PDT000495297.1' already exists. Skipping...
Folder 'GCA_005220705.1_PDT000495340.1' already exists. Skipping...
Folder 'GCA_005220725.1_PDT000495339.1' already exists. Skipping...
Folder 'GCA_005220825.1_PDT000495378.1' already exists. Skipping...
Folder 'GCA_005220845.1_PDT000495376.1' already exists. Skipping...
Folder 'GCA_005220885.1_PDT000495362.1' already exists. Skipping...
Folder 'GCA_005220905.1_PDT000495381.1' already exists. Skipping...
Folder 'GCA_005220925.1_PDT000495491.1' already exists. Skipping...
Folder 'GCA_005220935.1_PDT000495492.1' already exists. Skipping...
Folder 'GCA_005220965.1_PDT000495489.1' already exists. Skipping...
Folder 'GCA_005220985.1_PDT000495497.1' already exists. Skipping...
Folder 'GCA_005221005.1_PDT000495352.1' already exists. Skipping...
Folder 'GCA_005221025.1_PDT000495493.1' already exists. Skipping...
Folder 'GCA_005221045.1_PDT000495495.1' already exists. Skipping...
Folder 'GCA_005221065.1_PDT000495498.1' already exists. Skipping...
Folder 'GCA_005221105.1_PDT000495512.1' already exists. Skipping...
Folder 'GCA_005221125.1_PDT000495520.1' already exists. Skipping...
Folder 'GCA_005221145.1_PDT000495514.1' already exists. Skipping...
Folder 'GCA_005221225.1_PDT000495535.1' already exists. Skipping...
Folder 'GCA_005221245.1_PDT000495537.1' already exists. Skipping...
Folder 'GCA_005222105.1_PDT000243595.2' already exists. Skipping...
Folder 'GCA_005223435.1_PDT000486930.1' already exists. Skipping...
Folder 'GCA_005223455.1_PDT000486934.1' already exists. Skipping...
Folder 'GCA_005223475.1_PDT000486933.1' already exists. Skipping...
Folder 'GCA_005223495.1_PDT000486936.1' already exists. Skipping...
Folder 'GCA_005223515.1_PDT000486939.1' already exists. Skipping...
Folder 'GCA_005223535.1_PDT000486945.1' already exists. Skipping...
Folder 'GCA_005223545.1_PDT000486932.1' already exists. Skipping...
Folder 'GCA_005223575.1_PDT000486944.1' already exists. Skipping...
Folder 'GCA_005223595.1_PDT000486940.1' already exists. Skipping...
Folder 'GCA_005223615.1_PDT000488382.1' already exists. Skipping...
Folder 'GCA_005223635.1_PDT000488383.1' already exists. Skipping...
Folder 'GCA_005223665.1_PDT000488386.1' already exists. Skipping...
Folder 'GCA_005223695.1_PDT000488388.1' already exists. Skipping...
Folder 'GCA_005223735.1_PDT000488392.1' already exists. Skipping...
Folder 'GCA_005223755.1_PDT000488396.1' already exists. Skipping...
Folder 'GCA_005223815.1_PDT000488454.1' already exists. Skipping...
Folder 'GCA_005223855.1_PDT000488465.1' already exists. Skipping...
Folder 'GCA_005223875.1_PDT000488468.1' already exists. Skipping...
Folder 'GCA_005223895.1_PDT000488466.1' already exists. Skipping...
Folder 'GCA_005223915.1_PDT000488402.1' already exists. Skipping...
Folder 'GCA_005223935.1_PDT000488403.1' already exists. Skipping...
Folder 'GCA_005223955.1_PDT000488400.1' already exists. Skipping...
Folder 'GCA_005223975.1_PDT000488398.1' already exists. Skipping...
Folder 'GCA_005223995.1_PDT000488404.1' already exists. Skipping...
Folder 'GCA_005224015.1_PDT000488410.1' already exists. Skipping...
Folder 'GCA_005224035.1_PDT000488412.1' already exists. Skipping...
Folder 'GCA_005224055.1_PDT000488411.1' already exists. Skipping...
Folder 'GCA_005224075.1_PDT000488415.1' already exists. Skipping...
Folder 'GCA_005224095.1_PDT000488425.1' already exists. Skipping...
Folder 'GCA_005224105.1_PDT000488417.1' already exists. Skipping...
Folder 'GCA_005224135.1_PDT000488432.1' already exists. Skipping...
Folder 'GCA_005224155.1_PDT000488428.1' already exists. Skipping...
Folder 'GCA_005224165.1_PDT000488426.1' already exists. Skipping...
Folder 'GCA_005224195.1_PDT000488427.1' already exists. Skipping...
Folder 'GCA_005224235.1_PDT000488445.1' already exists. Skipping...
Folder 'GCA_005224255.1_PDT000488442.1' already exists. Skipping...
Folder 'GCA_005224275.1_PDT000488441.1' already exists. Skipping...
Folder 'GCA_005224295.1_PDT000488450.1' already exists. Skipping...
Folder 'GCA_005224315.1_PDT000488444.1' already exists. Skipping...
Folder 'GCA_005224335.1_PDT000488448.1' already exists. Skipping...
Folder 'GCA_005224355.1_PDT000488452.1' already exists. Skipping...
Folder 'GCA_005224375.1_PDT000488467.1' already exists. Skipping...
Folder 'GCA_005224385.1_PDT000488451.1' already exists. Skipping...
Folder 'GCA_005224415.1_PDT000488472.1' already exists. Skipping...
Folder 'GCA_005224435.1_PDT000488477.1' already exists. Skipping...
Folder 'GCA_005224445.1_PDT000488475.1' already exists. Skipping...
Folder 'GCA_005224495.1_PDT000488478.1' already exists. Skipping...
Folder 'GCA_005224535.1_PDT000488455.1' already exists. Skipping...
Folder 'GCA_005224555.1_PDT000488484.1' already exists. Skipping...
Folder 'GCA_005224575.1_PDT000488479.1' already exists. Skipping...
Folder 'GCA_005224595.1_PDT000488499.1' already exists. Skipping...
Folder 'GCA_005224615.1_PDT000488492.1' already exists. Skipping...
Folder 'GCA_005224655.1_PDT000488491.1' already exists. Skipping...
Folder 'GCA_005224675.1_PDT000488506.1' already exists. Skipping...
Folder 'GCA_005224695.1_PDT000488502.1' already exists. Skipping...
Folder 'GCA_005224715.1_PDT000488500.1' already exists. Skipping...
Folder 'GCA_005224725.1_PDT000488496.1' already exists. Skipping...
Folder 'GCA_005224755.1_PDT000488511.1' already exists. Skipping...
Folder 'GCA_005224775.1_PDT000488503.1' already exists. Skipping...
Folder 'GCA_005224795.1_PDT000488509.1' already exists. Skipping...
Folder 'GCA_005224815.1_PDT000488510.1' already exists. Skipping...
Folder 'GCA_005224835.1_PDT000488508.1' already exists. Skipping...
Folder 'GCA_005224855.1_PDT000488518.1' already exists. Skipping...
Folder 'GCA_005224875.1_PDT000488520.1' already exists. Skipping...
Folder 'GCA_005224895.1_PDT000488512.1' already exists. Skipping...
Folder 'GCA_005224935.1_PDT000488513.1' already exists. Skipping...
Folder 'GCA_005224955.1_PDT000488528.1' already exists. Skipping...
Folder 'GCA_005224995.1_PDT000488600.1' already exists. Skipping...
Folder 'GCA_005225015.1_PDT000488561.1' already exists. Skipping...
Folder 'GCA_005225035.1_PDT000488552.1' already exists. Skipping...
Folder 'GCA_005225055.1_PDT000488623.1' already exists. Skipping...
Folder 'GCA_005225075.1_PDT000488582.1' already exists. Skipping...
Folder 'GCA_005225095.1_PDT000488683.1' already exists. Skipping...
Folder 'GCA_005225115.1_PDT000488721.1' already exists. Skipping...
Folder 'GCA_005225135.1_PDT000488738.1' already exists. Skipping...
Folder 'GCA_005225155.1_PDT000488590.1' already exists. Skipping...
Folder 'GCA_005225175.1_PDT000488904.1' already exists. Skipping...
Folder 'GCA_005225195.1_PDT000488723.1' already exists. Skipping...
Folder 'GCA_005225215.1_PDT000488717.1' already exists. Skipping...
Folder 'GCA_005225235.1_PDT000488550.1' already exists. Skipping...
Folder 'GCA_005225275.1_PDT000488592.1' already exists. Skipping...
Folder 'GCA_005225315.1_PDT000488635.1' already exists. Skipping...
Folder 'GCA_005225335.1_PDT000488560.1' already exists. Skipping...
Folder 'GCA_005225355.1_PDT000488636.1' already exists. Skipping...
Folder 'GCA_005225375.1_PDT000488631.1' already exists. Skipping...
Folder 'GCA_005225395.1_PDT000488543.1' already exists. Skipping...
Folder 'GCA_005225415.1_PDT000488624.1' already exists. Skipping...
Folder 'GCA_005225435.1_PDT000488654.1' already exists. Skipping...
Folder 'GCA_005225455.1_PDT000488634.1' already exists. Skipping...
Folder 'GCA_005225475.1_PDT000488643.1' already exists. Skipping...
Folder 'GCA_005225495.1_PDT000488905.1' already exists. Skipping...
Folder 'GCA_005225515.1_PDT000488915.1' already exists. Skipping...
Folder 'GCA_005225535.1_PDT000488936.1' already exists. Skipping...
Folder 'GCA_005225555.1_PDT000488572.1' already exists. Skipping...
Folder 'GCA_005225565.1_PDT000488663.1' already exists. Skipping...

Retreiveing data: 49668it [00:08, 6676.03it/s]

Folder 'GCA_005268415.1_PDT000219886.2' already exists. Skipping...
Folder 'GCA_005268435.1_PDT000496801.1' already exists. Skipping...
Folder 'GCA_005268495.1_PDT000496494.1' already exists. Skipping...
Folder 'GCA_005268555.1_PDT000219893.2' already exists. Skipping...
Folder 'GCA_005268575.1_PDT000219892.2' already exists. Skipping...
Folder 'GCA_005268595.1_PDT000219895.2' already exists. Skipping...
Folder 'GCA_005268655.1_PDT000496696.1' already exists. Skipping...
Folder 'GCA_005268675.1_PDT000219897.2' already exists. Skipping...
Folder 'GCA_005268705.1_PDT000219898.2' already exists. Skipping...
Folder 'GCA_005268735.1_PDT000219900.2' already exists. Skipping...
Folder 'GCA_005268815.1_PDT000496174.1' already exists. Skipping...
Folder 'GCA_005268835.1_PDT000219910.2' already exists. Skipping...
Folder 'GCA_005268875.1_PDT000496845.1' already exists. Skipping...
Folder 'GCA_005268885.1_PDT000219907.2' already exists. Skipping...
Folder 'GCA_005268915.1_PDT000219918.2' already exists. Skipping...
Folder 'GCA_005268935.1_PDT000219915.2' already exists. Skipping...
Folder 'GCA_005268955.1_PDT000219913.2' already exists. Skipping...
Folder 'GCA_005268975.1_PDT000219917.2' already exists. Skipping...
Folder 'GCA_005268995.1_PDT000219923.2' already exists. Skipping...
Folder 'GCA_005269005.1_PDT000219920.2' already exists. Skipping...
Folder 'GCA_005269035.1_PDT000497681.1' already exists. Skipping...
Folder 'GCA_005269055.1_PDT000219922.2' already exists. Skipping...
Folder 'GCA_005269075.1_PDT000219924.2' already exists. Skipping...
Folder 'GCA_005269085.1_PDT000219925.2' already exists. Skipping...
Folder 'GCA_005269115.1_PDT000496919.1' already exists. Skipping...
Folder 'GCA_005269135.1_PDT000221388.2' already exists. Skipping...
Folder 'GCA_005269155.1_PDT000236296.2' already exists. Skipping...
Folder 'GCA_005269175.1_PDT000221393.2' already exists. Skipping...
Folder 'GCA_005269235.1_PDT000221398.2' already exists. Skipping...
Folder 'GCA_005269255.1_PDT000221403.2' already exists. Skipping...
Folder 'GCA_005269315.1_PDT000496504.1' already exists. Skipping...
Folder 'GCA_005269335.1_PDT000496933.1' already exists. Skipping...
Folder 'GCA_005269355.1_PDT000497620.1' already exists. Skipping...
Folder 'GCA_005269375.1_PDT000496837.1' already exists. Skipping...
Folder 'GCA_005269395.1_PDT000236281.2' already exists. Skipping...
Folder 'GCA_005269415.1_PDT000496932.1' already exists. Skipping...
Folder 'GCA_005269435.1_PDT000497631.1' already exists. Skipping...
Folder 'GCA_005269535.1_PDT000496181.1' already exists. Skipping...
Folder 'GCA_005269555.1_PDT000496492.1' already exists. Skipping...
Folder 'GCA_005269695.1_PDT000496931.1' already exists. Skipping...
Folder 'GCA_005269715.1_PDT000496920.1' already exists. Skipping...
Folder 'GCA_005269735.1_PDT000226551.2' already exists. Skipping...
Folder 'GCA_005269755.1_PDT000496172.1' already exists. Skipping...
Folder 'GCA_005269775.1_PDT000496842.1' already exists. Skipping...
Folder 'GCA_005269795.1_PDT000496929.1' already exists. Skipping...
Folder 'GCA_005269815.1_PDT000496925.1' already exists. Skipping...
Folder 'GCA_005269855.1_PDT000496522.1' already exists. Skipping...
Folder 'GCA_005269875.1_PDT000496943.1' already exists. Skipping...
Folder 'GCA_005269915.1_PDT000496833.1' already exists. Skipping...
Folder 'GCA_005269995.1_PDT000496799.1' already exists. Skipping...
Folder 'GCA_005270015.1_PDT000497508.1' already exists. Skipping...
Folder 'GCA_005270055.1_PDT000496942.1' already exists. Skipping...
Folder 'GCA_005270075.1_PDT000233462.2' already exists. Skipping...
Folder 'GCA_005270095.1_PDT000496927.1' already exists. Skipping...
Folder 'GCA_005270135.1_PDT000497625.1' already exists. Skipping...
Folder 'GCA_005270155.1_PDT000497622.1' already exists. Skipping...
Folder 'GCA_005270175.1_PDT000497114.1' already exists. Skipping...
Folder 'GCA_005270195.1_PDT000497621.1' already exists. Skipping...
Folder 'GCA_005270215.1_PDT000497627.1' already exists. Skipping...
Folder 'GCA_005270255.1_PDT000497633.1' already exists. Skipping...
Folder 'GCA_005270315.1_PDT000497634.1' already exists. Skipping...
Folder 'GCA_005270355.1_PDT000497637.1' already exists. Skipping...
Folder 'GCA_005270375.1_PDT000497638.1' already exists. Skipping...
Folder 'GCA_005270395.1_PDT000497636.1' already exists. Skipping...
Folder 'GCA_005270415.1_PDT000497641.1' already exists. Skipping...
Folder 'GCA_005270425.1_PDT000497640.1' already exists. Skipping...
Folder 'GCA_005270455.1_PDT000497642.1' already exists. Skipping...
Folder 'GCA_005270475.1_PDT000497644.1' already exists. Skipping...
Folder 'GCA_005270495.1_PDT000497643.1' already exists. Skipping...
Folder 'GCA_005270525.1_PDT000497648.1' already exists. Skipping...
Folder 'GCA_005270535.1_PDT000497645.1' already exists. Skipping...
Folder 'GCA_005270575.1_PDT000497650.1' already exists. Skipping...
Folder 'GCA_005270595.1_PDT000497649.1' already exists. Skipping...
Folder 'GCA_005270615.1_PDT000497647.1' already exists. Skipping...
Folder 'GCA_005270655.1_PDT000497651.1' already exists. Skipping...
Folder 'GCA_005270695.1_PDT000497654.1' already exists. Skipping...
Folder 'GCA_005270715.1_PDT000497656.1' already exists. Skipping...
Folder 'GCA_005270755.1_PDT000497657.1' already exists. Skipping...
Folder 'GCA_005270775.1_PDT000497662.1' already exists. Skipping...
Folder 'GCA_005270875.1_PDT000497666.1' already exists. Skipping...
Folder 'GCA_005270955.1_PDT000497670.1' already exists. Skipping...
Folder 'GCA_005271015.1_PDT000497685.1' already exists. Skipping...
Folder 'GCA_005271055.1_PDT000497686.1' already exists. Skipping...
Folder 'GCA_005271095.1_PDT000497687.1' already exists. Skipping...
Folder 'GCA_005271155.1_PDT000497659.1' already exists. Skipping...
Folder 'GCA_005271195.1_PDT000497660.1' already exists. Skipping...
Folder 'GCA_005271215.1_PDT000497661.1' already exists. Skipping...
Folder 'GCA_005271235.1_PDT000497727.1' already exists. Skipping...
Folder 'GCA_005271275.1_PDT000497698.1' already exists. Skipping...
Folder 'GCA_005271295.1_PDT000497733.1' already exists. Skipping...
Folder 'GCA_005271315.1_PDT000497734.1' already exists. Skipping...
Folder 'GCA_005271335.1_PDT000497736.1' already exists. Skipping...
Folder 'GCA_005271355.1_PDT000497738.1' already exists. Skipping...
Folder 'GCA_005271375.1_PDT000497728.1' already exists. Skipping...
Folder 'GCA_005271395.1_PDT000497735.1' already exists. Skipping...
Folder 'GCA_005271415.1_PDT000498210.1' already exists. Skipping...
Folder 'GCA_005271435.1_PDT000497737.1' already exists. Skipping...
Folder 'GCA_005271455.1_PDT000497740.1' already exists. Skipping...
Folder 'GCA_005271495.1_PDT000497739.1' already exists. Skipping...
Folder 'GCA_005271515.1_PDT000497741.1' already exists. Skipping...
Folder 'GCA_005271555.1_PDT000498216.1' already exists. Skipping...
Folder 'GCA_005271615.1_PDT000497696.1' already exists. Skipping...
Folder 'GCA_005271635.1_PDT000497694.1' already exists. Skipping...
Folder 'GCA_005271695.1_PDT000497695.1' already exists. Skipping...
Folder 'GCA_005271735.1_PDT000497697.1' already exists. Skipping...
Folder 'GCA_005271755.1_PDT000498223.1' already exists. Skipping...
Folder 'GCA_005271775.1_PDT000497699.1' already exists. Skipping...
Folder 'GCA_005271795.1_PDT000498222.1' already exists. Skipping...
Folder 'GCA_005271815.1_PDT000498221.1' already exists. Skipping...
Folder 'GCA_005271835.1_PDT000498228.1' already exists. Skipping...
Folder 'GCA_005271935.1_PDT000498234.1' already exists. Skipping...
Folder 'GCA_005271955.1_PDT000498231.1' already exists. Skipping...
Folder 'GCA_005271975.1_PDT000498233.1' already exists. Skipping...
Folder 'GCA_005272075.1_PDT000206856.2' already exists. Skipping...
Folder 'GCA_005272095.1_PDT000496490.1' already exists. Skipping...
Folder 'GCA_005272115.1_PDT000496855.1' already exists. Skipping...
Folder 'GCA_005272135.1_PDT000496501.1' already exists. Skipping...
Folder 'GCA_005272145.1_PDT000496857.1' already exists. Skipping...
Folder 'GCA_005272175.1_PDT000496176.1' already exists. Skipping...
Folder 'GCA_005272195.1_PDT000205469.2' already exists. Skipping...
Folder 'GCA_005272215.1_PDT000496489.1' already exists. Skipping...
Folder 'GCA_005272235.1_PDT000206849.2' already exists. Skipping...
Folder 'GCA_005272255.1_PDT000221408.2' already exists. Skipping...
Folder 'GCA_005272265.1_PDT000212974.2' already exists. Skipping...
Folder 'GCA_005272295.1_PDT000497626.1' already exists. Skipping...
Folder 'GCA_005272315.1_PDT000212973.2' already exists. Skipping...
Folder 'GCA_005272335.1_PDT000496185.1' already exists. Skipping...
Folder 'GCA_005272355.1_PDT000496832.1' already exists. Skipping...
Folder 'GCA_005272435.1_PDT000496802.1' already exists. Skipping...
Folder 'GCA_005272475.1_PDT000496497.1' already exists. Skipping...
Folder 'GCA_005272495.1_PDT000233132.2' already exists. Skipping...
Folder 'GCA_005272515.1_PDT000206854.2' already exists. Skipping...
Folder 'GCA_005272595.1_PDT000496859.1' already exists. Skipping...
Folder 'GCA_005272635.1_PDT000496539.1' already exists. Skipping...
Folder 'GCA_005272695.1_PDT000496800.1' already exists. Skipping...
Folder 'GCA_005272775.1_PDT000205044.2' already exists. Skipping...
Folder 'GCA_005272815.1_PDT000205459.2' already exists. Skipping...
Folder 'GCA_005272855.1_PDT000205462.2' already exists. Skipping...
Folder 'GCA_005272915.1_PDT000205460.2' already exists. Skipping...
Folder 'GCA_005272935.1_PDT000205465.2' already exists. Skipping...
Folder 'GCA_005272955.1_PDT000205464.2' already exists. Skipping...
Folder 'GCA_005272975.1_PDT000205466.2' already exists. Skipping...
Folder 'GCA_005272995.1_PDT000497629.1' already exists. Skipping...
Folder 'GCA_005273015.1_PDT000496858.1' already exists. Skipping...
Folder 'GCA_005273035.1_PDT000205468.2' already exists. Skipping...
Folder 'GCA_005273055.1_PDT000207018.2' already exists. Skipping...
Folder 'GCA_005273075.1_PDT000496516.1' already exists. Skipping...
Folder 'GCA_005273095.1_PDT000207019.2' already exists. Skipping...
Folder 'GCA_005273115.1_PDT000496491.1' already exists. Skipping...
Folder 'GCA_005273135.1_PDT000207021.2' already exists. Skipping...
Folder 'GCA_005273155.1_PDT000207022.2' already exists. Skipping...
Folder 'GCA_005273175.1_PDT000207020.2' already exists. Skipping...
Folder 'GCA_005273195.1_PDT000497672.1' already exists. Skipping...
Folder 'GCA_005273205.1_PDT000207024.2' already exists. Skipping...
Folder 'GCA_005273255.1_PDT000496922.1' already exists. Skipping...
Folder 'GCA_005273275.1_PDT000207023.2' already exists. Skipping...
Folder 'GCA_005273295.1_PDT000210975.2' already exists. Skipping...
Folder 'GCA_005273315.1_PDT000496944.1' already exists. Skipping...
Folder 'GCA_005273335.1_PDT000207027.2' already exists. Skipping...
Folder 'GCA_005273355.1_PDT000207028.2' already exists. Skipping...
Folder 'GCA_005273395.1_PDT000207029.2' already exists. Skipping...
Folder 'GCA_005273415.1_PDT000207026.2' already exists. Skipping...
Folder 'GCA_005273445.1_PDT000210973.2' already exists. Skipping...
Folder 'GCA_005273495.1_PDT000210978.2' already exists. Skipping...
Folder 'GCA_005273515.1_PDT000210974.2' already exists. Skipping...
Folder 'GCA_005273555.1_PDT000210980.2' already exists. Skipping...
Folder 'GCA_005273655.1_PDT000230088.2' already exists. Skipping...
Folder 'GCA_005273675.1_PDT000496498.1' already exists. Skipping...
Folder 'GCA_005273715.1_PDT000496834.1' already exists. Skipping...
Folder 'GCA_005273755.1_PDT000210983.2' already exists. Skipping...
Folder 'GCA_005273815.1_PDT000496502.1' already exists. Skipping...
Folder 'GCA_005273835.1_PDT000496549.1' already exists. Skipping...
Folder 'GCA_005273855.1_PDT000236291.2' already exists. Skipping...
Folder 'GCA_005273915.1_PDT000210984.2' already exists. Skipping...
Folder 'GCA_005273935.1_PDT000210987.2' already exists. Skipping...
Folder 'GCA_005273955.1_PDT000233117.2' already exists. Skipping...
Folder 'GCA_005273975.1_PDT000210986.2' already exists. Skipping...
Folder 'GCA_005273985.1_PDT000496175.1' already exists. Skipping...
Folder 'GCA_005274015.1_PDT000210990.2' already exists. Skipping...
Folder 'GCA_005274035.1_PDT000210985.2' already exists. Skipping...
Folder 'GCA_005274055.1_PDT000496941.1' already exists. Skipping...
Folder 'GCA_005274075.1_PDT000210989.2' already exists. Skipping...
Folder 'GCA_005274095.1_PDT000210988.2' already exists. Skipping...
Folder 'GCA_005274115.1_PDT000496835.1' already exists. Skipping...
Folder 'GCA_005274135.1_PDT000210991.2' already exists. Skipping...
Folder 'GCA_005274155.1_PDT000211017.2' already exists. Skipping...
Folder 'GCA_005274195.1_PDT000211024.2' already exists. Skipping...
Folder 'GCA_005274215.1_PDT000211046.2' already exists. Skipping...
Folder 'GCA_005274225.1_PDT000211018.2' already exists. Skipping...
Folder 'GCA_005274255.1_PDT000210992.2' already exists. Skipping...
Folder 'GCA_005274295.1_PDT000496190.1' already exists. Skipping...
Folder 'GCA_005274315.1_PDT000211025.2' already exists. Skipping...
Folder 'GCA_005274355.1_PDT000212970.2' already exists. Skipping...
Folder 'GCA_005274375.1_PDT000211052.2' already exists. Skipping...
Folder 'GCA_005274415.1_PDT000212972.2' already exists. Skipping...
Folder 'GCA_005274435.1_PDT000211114.2' already exists. Skipping...
Folder 'GCA_005274455.1_PDT000212969.2' already exists. Skipping...
Folder 'GCA_005274475.1_PDT000212975.2' already exists. Skipping...
Folder 'GCA_005274495.1_PDT000496860.1' already exists. Skipping...
Folder 'GCA_005274515.1_PDT000211095.2' already exists. Skipping...
Folder 'GCA_005274535.1_PDT000212976.2' already exists. Skipping...
Folder 'GCA_005274555.1_PDT000212971.2' already exists. Skipping...
Folder 'GCA_005274575.1_PDT000212981.2' already exists. Skipping...
Folder 'GCA_005274585.1_PDT000212980.2' already exists. Skipping...
Folder 'GCA_005274635.1_PDT000212977.2' already exists. Skipping...
Folder 'GCA_005274655.1_PDT000212982.2' already exists. Skipping...
Folder 'GCA_005274675.1_PDT000212996.2' already exists. Skipping...
Folder 'GCA_005274695.1_PDT000212988.2' already exists. Skipping...
Folder 'GCA_005274715.1_PDT000212990.2' already exists. Skipping...
Folder 'GCA_005274735.1_PDT000212989.2' already exists. Skipping...
Folder 'GCA_005274775.1_PDT000212984.2' already exists. Skipping...
Folder 'GCA_005274805.1_PDT000233137.2' already exists. Skipping...
Folder 'GCA_005274835.1_PDT000212986.2' already exists. Skipping...
Folder 'GCA_005274855.1_PDT000212983.2' already exists. Skipping...
Folder 'GCA_005274895.1_PDT000212991.2' already exists. Skipping...
Folder 'GCA_005274915.1_PDT000496838.1' already exists. Skipping...
Folder 'GCA_005274935.1_PDT000496836.1' already exists. Skipping...
Folder 'GCA_005274955.1_PDT000212992.2' already exists. Skipping...
Folder 'GCA_005274975.1_PDT000212993.2' already exists. Skipping...
Folder 'GCA_005275015.1_PDT000212998.2' already exists. Skipping...
Folder 'GCA_005275055.1_PDT000496580.1' already exists. Skipping...
Folder 'GCA_005275075.1_PDT000213000.2' already exists. Skipping...
Folder 'GCA_005275095.1_PDT000212999.2' already exists. Skipping...
Folder 'GCA_005275215.1_PDT000213003.2' already exists. Skipping...
Folder 'GCA_005275235.1_PDT000213008.2' already exists. Skipping...
Folder 'GCA_005275315.1_PDT000217306.2' already exists. Skipping...
Folder 'GCA_005275335.1_PDT000496934.1' already exists. Skipping...
Folder 'GCA_005275395.1_PDT000217316.2' already exists. Skipping...
Folder 'GCA_005275415.1_PDT000217318.2' already exists. Skipping...
Folder 'GCA_005275435.1_PDT000213009.2' already exists. Skipping...
Folder 'GCA_005275475.1_PDT000217341.2' already exists. Skipping...
Folder 'GCA_005275535.1_PDT000217336.2' already exists. Skipping...
Folder 'GCA_005275555.1_PDT000217347.2' already exists. Skipping...
Folder 'GCA_005275575.1_PDT000496939.1' already exists. Skipping...
Folder 'GCA_005275595.1_PDT000217338.2' already exists. Skipping...
Folder 'GCA_005275635.1_PDT000496500.1' already exists. Skipping...
Folder 'GCA_005275675.1_PDT000217382.2' already exists. Skipping...
Folder 'GCA_005275695.1_PDT000217362.2' already exists. Skipping...
Folder 'GCA_005275775.1_PDT000496921.1' already exists. Skipping...
Folder 'GCA_005275855.1_PDT000219882.2' already exists. Skipping...
Folder 'GCA_005275875.1_PDT000219880.2' already exists. Skipping...
Folder 'GCA_005275935.1_PDT000219883.2' already exists. Skipping...
Folder 'GCA_005275955.1_PDT000219881.2' already exists. Skipping...
Folder 'GCA_005275975.1_PDT000219887.2' already exists. Skipping...
Folder 'GCA_005276015.1_PDT000219885.2' already exists. Skipping...
Folder 'GCA_005276035.1_PDT000496579.1' already exists. Skipping...
Folder 'GCA_005276045.1_PDT000496493.1' already exists. Skipping...
Folder 'GCA_005276075.1_PDT000496503.1' already exists. Skipping...
Folder 'GCA_005276085.1_PDT000496698.1' already exists. Skipping...
Folder 'GCA_005276115.1_PDT000496841.1' already exists. Skipping...
Folder 'GCA_005276215.1_PDT000496396.1' already exists. Skipping...
Folder 'GCA_005276235.1_PDT000496193.1' already exists. Skipping...
Folder 'GCA_005276255.1_PDT000496538.1' already exists. Skipping...
Folder 'GCA_005276275.1_PDT000496505.1' already exists. Skipping...
Folder 'GCA_005276335.1_PDT000496499.1' already exists. Skipping...
Folder 'GCA_005276415.1_PDT000496846.1' already exists. Skipping...
Folder 'GCA_005276475.1_PDT000235425.2' already exists. Skipping...
Folder 'GCA_005276495.1_PDT000498300.1' already exists. Skipping...
Folder 'GCA_005276615.1_PDT000498249.1' already exists. Skipping...
Folder 'GCA_005276655.1_PDT000498306.1' already exists. Skipping...
Folder 'GCA_005276675.1_PDT000498251.1' already exists. Skipping...
Folder 'GCA_005276705.1_PDT000498247.1' already exists. Skipping...
Folder 'GCA_005276755.1_PDT000498243.1' already exists. Skipping...
Folder 'GCA_005276775.1_PDT000498307.1' already exists. Skipping...
Folder 'GCA_005276795.1_PDT000498252.1' already exists. Skipping...
Folder 'GCA_005276815.1_PDT000498250.1' already exists. Skipping...
Folder 'GCA_005276875.1_PDT000498240.1' already exists. Skipping...
Folder 'GCA_005276955.1_PDT000498255.1' already exists. Skipping...
Folder 'GCA_005276975.1_PDT000498259.1' already exists. Skipping...
Folder 'GCA_005276995.1_PDT000498261.1' already exists. Skipping...
Folder 'GCA_005277055.1_PDT000498260.1' already exists. Skipping...
Folder 'GCA_005277075.1_PDT000498253.1' already exists. Skipping...
Folder 'GCA_005277115.1_PDT000498264.1' already exists. Skipping...
Folder 'GCA_005277155.1_PDT000498263.1' already exists. Skipping...
Folder 'GCA_005277175.1_PDT000498267.1' already exists. Skipping...
Folder 'GCA_005277215.1_PDT000498270.1' already exists. Skipping...
Folder 'GCA_005277295.1_PDT000498273.1' already exists. Skipping...
Folder 'GCA_005277315.1_PDT000498275.1' already exists. Skipping...
Folder 'GCA_005277335.1_PDT000498281.1' already exists. Skipping...
Folder 'GCA_005277355.1_PDT000498279.1' already exists. Skipping...
Folder 'GCA_005277375.1_PDT000498282.1' already exists. Skipping...
Folder 'GCA_005277415.1_PDT000498284.1' already exists. Skipping...
Folder 'GCA_005277435.1_PDT000498283.1' already exists. Skipping...
Folder 'GCA_005277455.1_PDT000498287.1' already exists. Skipping...
Folder 'GCA_005277475.1_PDT000498286.1' already exists. Skipping...
Folder 'GCA_005277535.1_PDT000498290.1' already exists. Skipping...
Folder 'GCA_005277595.1_PDT000498294.1' already exists. Skipping...
Folder 'GCA_005277615.1_PDT000498292.1' already exists. Skipping...
Folder 'GCA_005277635.1_PDT000498295.1' already exists. Skipping...
Folder 'GCA_005277675.1_PDT000498296.1' already exists. Skipping...
Folder 'GCA_005277695.1_PDT000498309.1' already exists. Skipping...
Folder 'GCA_005277715.1_PDT000498298.1' already exists. Skipping...
Folder 'GCA_005277735.1_PDT000498310.1' already exists. Skipping...
Folder 'GCA_005277755.1_PDT000498314.1' already exists. Skipping...

Retreiveing data: 51011it [00:09, 6655.08it/s]

Folder 'GCA_005313485.1_PDT000333835.1' already exists. Skipping...
Folder 'GCA_005313545.1_PDT000333836.1' already exists. Skipping...
Folder 'GCA_005313565.1_PDT000333839.1' already exists. Skipping...
Folder 'GCA_005313605.1_PDT000333840.1' already exists. Skipping...
Folder 'GCA_005313685.1_PDT000333859.1' already exists. Skipping...
Folder 'GCA_005313705.1_PDT000333861.1' already exists. Skipping...
Folder 'GCA_005313725.1_PDT000333862.1' already exists. Skipping...
Folder 'GCA_005313785.1_PDT000333863.1' already exists. Skipping...
Folder 'GCA_005313805.1_PDT000333869.1' already exists. Skipping...
Folder 'GCA_005313825.1_PDT000333875.1' already exists. Skipping...
Folder 'GCA_005313845.1_PDT000333871.1' already exists. Skipping...
Folder 'GCA_005313865.1_PDT000333872.1' already exists. Skipping...
Folder 'GCA_005313885.1_PDT000333870.1' already exists. Skipping...
Folder 'GCA_005313905.1_PDT000333885.1' already exists. Skipping...
Folder 'GCA_005313925.1_PDT000333874.1' already exists. Skipping...
Folder 'GCA_005313945.1_PDT000333873.1' already exists. Skipping...
Folder 'GCA_005313965.1_PDT000333887.1' already exists. Skipping...
Folder 'GCA_005313985.1_PDT000333884.1' already exists. Skipping...
Folder 'GCA_005314005.1_PDT000333896.1' already exists. Skipping...
Folder 'GCA_005314025.1_PDT000333888.1' already exists. Skipping...
Folder 'GCA_005314085.1_PDT000333883.1' already exists. Skipping...
Folder 'GCA_005314105.1_PDT000333890.1' already exists. Skipping...
Folder 'GCA_005314145.1_PDT000333897.1' already exists. Skipping...
Folder 'GCA_005314165.1_PDT000333891.1' already exists. Skipping...
Folder 'GCA_005314225.1_PDT000333900.1' already exists. Skipping...
Folder 'GCA_005314245.1_PDT000333895.1' already exists. Skipping...
Folder 'GCA_005314285.1_PDT000334155.1' already exists. Skipping...
Folder 'GCA_005314305.1_PDT000333899.1' already exists. Skipping...
Folder 'GCA_005314325.1_PDT000060610.4' already exists. Skipping...
Folder 'GCA_005314365.1_PDT000333846.1' already exists. Skipping...
Folder 'GCA_005314425.1_PDT000333845.1' already exists. Skipping...
Folder 'GCA_005314445.1_PDT000333853.1' already exists. Skipping...
Folder 'GCA_005314465.1_PDT000333850.1' already exists. Skipping...
Folder 'GCA_005314485.1_PDT000333848.1' already exists. Skipping...
Folder 'GCA_005314505.1_PDT000333847.1' already exists. Skipping...
Folder 'GCA_005314525.1_PDT000333849.1' already exists. Skipping...
Folder 'GCA_005314565.1_PDT000332633.1' already exists. Skipping...
Folder 'GCA_005314585.1_PDT000333827.1' already exists. Skipping...
Folder 'GCA_005314665.1_PDT000333831.1' already exists. Skipping...
Folder 'GCA_005314685.1_PDT000336825.1' already exists. Skipping...
Folder 'GCA_005314725.1_PDT000333811.1' already exists. Skipping...
Folder 'GCA_005314745.1_PDT000066079.4' already exists. Skipping...
Folder 'GCA_005314765.1_PDT000066080.4' already exists. Skipping...
Folder 'GCA_005314785.1_PDT000336826.1' already exists. Skipping...
Folder 'GCA_005314805.1_PDT000066081.4' already exists. Skipping...
Folder 'GCA_005314815.1_PDT000336823.1' already exists. Skipping...
Folder 'GCA_005314845.1_PDT000066078.4' already exists. Skipping...
Folder 'GCA_005314865.1_PDT000336828.1' already exists. Skipping...
Folder 'GCA_005314885.1_PDT000336824.1' already exists. Skipping...
Folder 'GCA_005314905.1_PDT000049874.4' already exists. Skipping...
Folder 'GCA_005314925.1_PDT000066082.4' already exists. Skipping...
Folder 'GCA_005314945.1_PDT000334154.1' already exists. Skipping...
Folder 'GCA_005314965.1_PDT000060611.4' already exists. Skipping...
Folder 'GCA_005314985.1_PDT000066291.4' already exists. Skipping...
Folder 'GCA_005315005.1_PDT000066289.4' already exists. Skipping...
Folder 'GCA_005315045.1_PDT000066934.4' already exists. Skipping...
Folder 'GCA_005315065.1_PDT000066290.4' already exists. Skipping...
Folder 'GCA_005315075.1_PDT000066083.4' already exists. Skipping...
Folder 'GCA_005315105.1_PDT000066933.4' already exists. Skipping...
Folder 'GCA_005315125.1_PDT000066292.4' already exists. Skipping...
Folder 'GCA_005315145.1_PDT000067191.4' already exists. Skipping...
Folder 'GCA_005315165.1_PDT000066939.4' already exists. Skipping...
Folder 'GCA_005315185.1_PDT000066935.4' already exists. Skipping...
Folder 'GCA_005315205.1_PDT000066839.5' already exists. Skipping...
Folder 'GCA_005315225.1_PDT000066938.4' already exists. Skipping...
Folder 'GCA_005315245.1_PDT000067196.4' already exists. Skipping...
Folder 'GCA_005315285.1_PDT000066937.4' already exists. Skipping...
Folder 'GCA_005315305.1_PDT000067197.4' already exists. Skipping...
Folder 'GCA_005315325.1_PDT000067769.4' already exists. Skipping...
Folder 'GCA_005315355.1_PDT000067195.4' already exists. Skipping...
Folder 'GCA_005315385.1_PDT000067767.4' already exists. Skipping...
Folder 'GCA_005315405.1_PDT000067766.4' already exists. Skipping...
Folder 'GCA_005315425.1_PDT000067768.4' already exists. Skipping...
Folder 'GCA_005315445.1_PDT000067770.4' already exists. Skipping...
Folder 'GCA_005315485.1_PDT000336068.1' already exists. Skipping...
Folder 'GCA_005315505.1_PDT000336064.1' already exists. Skipping...
Folder 'GCA_005315545.1_PDT000336069.1' already exists. Skipping...
Folder 'GCA_005315565.1_PDT000336066.1' already exists. Skipping...
Folder 'GCA_005315585.1_PDT000336065.1' already exists. Skipping...
Folder 'GCA_005315605.1_PDT000336072.1' already exists. Skipping...
Folder 'GCA_005315625.1_PDT000336067.1' already exists. Skipping...
Folder 'GCA_005315645.1_PDT000336070.1' already exists. Skipping...
Folder 'GCA_005315665.1_PDT000336078.1' already exists. Skipping...
Folder 'GCA_005315685.1_PDT000336073.1' already exists. Skipping...
Folder 'GCA_005315695.1_PDT000336833.1' already exists. Skipping...
Folder 'GCA_005315725.1_PDT000336071.1' already exists. Skipping...
Folder 'GCA_005315745.1_PDT000336834.1' already exists. Skipping...
Folder 'GCA_005315765.1_PDT000336832.1' already exists. Skipping...
Folder 'GCA_005315785.1_PDT000336831.1' already exists. Skipping...
Folder 'GCA_005315805.1_PDT000336074.1' already exists. Skipping...
Folder 'GCA_005315825.1_PDT000336829.1' already exists. Skipping...
Folder 'GCA_005315845.1_PDT000336835.1' already exists. Skipping...
Folder 'GCA_005315865.1_PDT000336077.1' already exists. Skipping...
Folder 'GCA_005315885.1_PDT000336830.1' already exists. Skipping...
Folder 'GCA_005315905.1_PDT000336075.1' already exists. Skipping...
Folder 'GCA_005315915.1_PDT000336827.1' already exists. Skipping...
Folder 'GCA_005315945.1_PDT000336076.1' already exists. Skipping...
Folder 'GCA_005315965.1_PDT000336837.1' already exists. Skipping...
Folder 'GCA_005315985.1_PDT000336838.1' already exists. Skipping...
Folder 'GCA_005316005.1_PDT000336844.1' already exists. Skipping...
Folder 'GCA_005316025.1_PDT000336839.1' already exists. Skipping...
Folder 'GCA_005316045.1_PDT000336843.1' already exists. Skipping...
Folder 'GCA_005316065.1_PDT000336836.1' already exists. Skipping...
Folder 'GCA_005316085.1_PDT000336840.1' already exists. Skipping...
Folder 'GCA_005316105.1_PDT000336846.1' already exists. Skipping...
Folder 'GCA_005316125.1_PDT000336845.1' already exists. Skipping...
Folder 'GCA_005316145.1_PDT000336841.1' already exists. Skipping...
Folder 'GCA_005316165.1_PDT000336842.1' already exists. Skipping...
Folder 'GCA_005316225.1_PDT000336849.1' already exists. Skipping...
Folder 'GCA_005316245.1_PDT000336851.1' already exists. Skipping...
Folder 'GCA_005316265.1_PDT000336850.1' already exists. Skipping...
Folder 'GCA_005316285.1_PDT000336853.1' already exists. Skipping...
Folder 'GCA_005316305.1_PDT000336856.1' already exists. Skipping...
Folder 'GCA_005316325.1_PDT000336852.1' already exists. Skipping...
Folder 'GCA_005316345.1_PDT000336855.1' already exists. Skipping...
Folder 'GCA_005316365.1_PDT000336857.1' already exists. Skipping...
Folder 'GCA_005316525.1_PDT000266954.5' already exists. Skipping...
Folder 'GCA_005316545.1_PDT000233672.5' already exists. Skipping...
Folder 'GCA_005316565.1_PDT000266952.5' already exists. Skipping...
Folder 'GCA_005316585.1_PDT000152991.6' already exists. Skipping...
Folder 'GCA_005316605.1_PDT000266951.5' already exists. Skipping...
Folder 'GCA_005316625.1_PDT000266956.5' already exists. Skipping...
Folder 'GCA_005316705.1_PDT000266953.5' already exists. Skipping...
Folder 'GCA_005316725.1_PDT000266959.5' already exists. Skipping...
Folder 'GCA_005316785.1_PDT000266958.5' already exists. Skipping...
Folder 'GCA_005316845.1_PDT000266955.5' already exists. Skipping...
Folder 'GCA_005316885.1_PDT000145072.8' already exists. Skipping...
Folder 'GCA_005316905.1_PDT000266957.5' already exists. Skipping...
Folder 'GCA_005316965.1_PDT000242665.5' already exists. Skipping...
Folder 'GCA_005316985.1_PDT000266960.5' already exists. Skipping...
Folder 'GCA_005317045.1_PDT000337889.1' already exists. Skipping...
Folder 'GCA_005317165.1_PDT000339295.1' already exists. Skipping...
Folder 'GCA_005317185.1_PDT000337892.1' already exists. Skipping...
Folder 'GCA_005317205.1_PDT000337901.1' already exists. Skipping...
Folder 'GCA_005317225.1_PDT000340426.1' already exists. Skipping...
Folder 'GCA_005317245.1_PDT000337904.1' already exists. Skipping...
Folder 'GCA_005317265.1_PDT000337903.1' already exists. Skipping...
Folder 'GCA_005317305.1_PDT000338856.1' already exists. Skipping...
Folder 'GCA_005317325.1_PDT000338365.1' already exists. Skipping...
Folder 'GCA_005317365.1_PDT000337894.1' already exists. Skipping...
Folder 'GCA_005317385.1_PDT000340559.1' already exists. Skipping...
Folder 'GCA_005317405.1_PDT000338361.1' already exists. Skipping...
Folder 'GCA_005317425.1_PDT000338369.1' already exists. Skipping...
Folder 'GCA_005317445.1_PDT000337905.1' already exists. Skipping...
Folder 'GCA_005317475.1_PDT000337906.1' already exists. Skipping...
Folder 'GCA_005317505.1_PDT000340561.1' already exists. Skipping...
Folder 'GCA_005317525.1_PDT000340429.1' already exists. Skipping...
Folder 'GCA_005317545.1_PDT000337902.1' already exists. Skipping...
Folder 'GCA_005317625.1_PDT000340431.1' already exists. Skipping...
Folder 'GCA_005317645.1_PDT000337898.1' already exists. Skipping...
Folder 'GCA_005317705.1_PDT000340430.1' already exists. Skipping...
Folder 'GCA_005317715.1_PDT000337896.1' already exists. Skipping...
Folder 'GCA_005317745.1_PDT000338865.1' already exists. Skipping...
Folder 'GCA_005317765.1_PDT000337895.1' already exists. Skipping...
Folder 'GCA_005317785.1_PDT000337911.1' already exists. Skipping...
Folder 'GCA_005317805.1_PDT000337910.1' already exists. Skipping...
Folder 'GCA_005317865.1_PDT000340428.1' already exists. Skipping...
Folder 'GCA_005317905.1_PDT000339293.1' already exists. Skipping...
Folder 'GCA_005317925.1_PDT000338371.1' already exists. Skipping...
Folder 'GCA_005317945.1_PDT000338367.1' already exists. Skipping...
Folder 'GCA_005318005.1_PDT000337912.1' already exists. Skipping...
Folder 'GCA_005318025.1_PDT000337890.1' already exists. Skipping...
Folder 'GCA_005318045.1_PDT000340427.1' already exists. Skipping...
Folder 'GCA_005318085.1_PDT000337900.1' already exists. Skipping...
Folder 'GCA_005318145.1_PDT000340947.1' already exists. Skipping...
Folder 'GCA_005318165.1_PDT000340425.1' already exists. Skipping...
Folder 'GCA_005318225.1_PDT000337908.1' already exists. Skipping...
Folder 'GCA_005318275.1_PDT000338215.1' already exists. Skipping...
Folder 'GCA_005318305.1_PDT000337891.1' already exists. Skipping...
Folder 'GCA_005318325.1_PDT000337899.1' already exists. Skipping...
Folder 'GCA_005318345.1_PDT000338363.1' already exists. Skipping...
Folder 'GCA_005318375.1_PDT000337897.1' already exists. Skipping...
Folder 'GCA_005318445.1_PDT000338370.1' already exists. Skipping...
Folder 'GCA_005318465.1_PDT000339298.1' already exists. Skipping...
Folder 'GCA_005318485.1_PDT000340950.1' already exists. Skipping...
Folder 'GCA_005318525.1_PDT000338368.1' already exists. Skipping...
Folder 'GCA_005318545.1_PDT000337907.1' already exists. Skipping...
Folder 'GCA_005318625.1_PDT000338699.1' already exists. Skipping...
Folder 'GCA_005318665.1_PDT000338372.1' already exists. Skipping...
Folder 'GCA_005318685.1_PDT000340946.1' already exists. Skipping...
Folder 'GCA_005318785.1_PDT000338816.1' already exists. Skipping...
Folder 'GCA_005318825.1_PDT000339292.1' already exists. Skipping...
Folder 'GCA_005318845.1_PDT000338362.1' already exists. Skipping...
Folder 'GCA_005318865.1_PDT000339271.1' already exists. Skipping...
Folder 'GCA_005318885.1_PDT000339272.1' already exists. Skipping...
Folder 'GCA_005318905.1_PDT000339266.1' already exists. Skipping...
Folder 'GCA_005318945.1_PDT000339268.1' already exists. Skipping...
Folder 'GCA_005318965.1_PDT000340952.1' already exists. Skipping...
Folder 'GCA_005318985.1_PDT000339270.1' already exists. Skipping...
Folder 'GCA_005319025.1_PDT000339274.1' already exists. Skipping...
Folder 'GCA_005319065.1_PDT000340948.1' already exists. Skipping...
Folder 'GCA_005319085.1_PDT000339276.1' already exists. Skipping...
Folder 'GCA_005319125.1_PDT000340949.1' already exists. Skipping...
Folder 'GCA_005319145.1_PDT000339283.1' already exists. Skipping...
Folder 'GCA_005319185.1_PDT000339275.1' already exists. Skipping...
Folder 'GCA_005319225.1_PDT000339284.1' already exists. Skipping...
Folder 'GCA_005319245.1_PDT000339285.1' already exists. Skipping...
Folder 'GCA_005319265.1_PDT000339289.1' already exists. Skipping...
Folder 'GCA_005319285.1_PDT000339290.1' already exists. Skipping...
Folder 'GCA_005319325.1_PDT000339314.1' already exists. Skipping...
Folder 'GCA_005319365.1_PDT000339309.1' already exists. Skipping...
Folder 'GCA_005319445.1_PDT000339320.1' already exists. Skipping...
Folder 'GCA_005319465.1_PDT000339317.1' already exists. Skipping...
Folder 'GCA_005319485.1_PDT000339318.1' already exists. Skipping...
Folder 'GCA_005319545.1_PDT000339311.1' already exists. Skipping...
Folder 'GCA_005319565.1_PDT000339313.1' already exists. Skipping...
Folder 'GCA_005319625.1_PDT000339307.1' already exists. Skipping...
Folder 'GCA_005319645.1_PDT000339322.1' already exists. Skipping...
Folder 'GCA_005319705.1_PDT000339321.1' already exists. Skipping...
Folder 'GCA_005319785.1_PDT000340410.1' already exists. Skipping...
Folder 'GCA_005319865.1_PDT000340416.1' already exists. Skipping...
Folder 'GCA_005319885.1_PDT000340411.1' already exists. Skipping...
Folder 'GCA_005319905.1_PDT000340414.1' already exists. Skipping...
Folder 'GCA_005319925.1_PDT000340418.1' already exists. Skipping...
Folder 'GCA_005319945.1_PDT000340412.1' already exists. Skipping...
Folder 'GCA_005319965.1_PDT000340424.1' already exists. Skipping...
Folder 'GCA_005319985.1_PDT000340413.1' already exists. Skipping...
Folder 'GCA_005320005.1_PDT000340415.1' already exists. Skipping...
Folder 'GCA_005320045.1_PDT000340417.1' already exists. Skipping...
Folder 'GCA_005320055.1_PDT000340420.1' already exists. Skipping...
Folder 'GCA_005320065.1_PDT000340419.1' already exists. Skipping...
Folder 'GCA_005320075.1_PDT000340433.1' already exists. Skipping...
Folder 'GCA_005320125.1_PDT000340438.1' already exists. Skipping...
Folder 'GCA_005320145.1_PDT000340436.1' already exists. Skipping...
Folder 'GCA_005320165.1_PDT000340437.1' already exists. Skipping...
Folder 'GCA_005320185.1_PDT000340422.1' already exists. Skipping...
Folder 'GCA_005320205.1_PDT000340423.1' already exists. Skipping...
Folder 'GCA_005320225.1_PDT000340440.1' already exists. Skipping...
Folder 'GCA_005320245.1_PDT000340432.1' already exists. Skipping...
Folder 'GCA_005320265.1_PDT000340441.1' already exists. Skipping...
Folder 'GCA_005320285.1_PDT000340434.1' already exists. Skipping...
Folder 'GCA_005320305.1_PDT000340439.1' already exists. Skipping...
Folder 'GCA_005320345.1_PDT000340445.1' already exists. Skipping...
Folder 'GCA_005320355.1_PDT000340443.1' already exists. Skipping...
Folder 'GCA_005320375.1_PDT000340442.1' already exists. Skipping...
Folder 'GCA_005320425.1_PDT000340536.1' already exists. Skipping...
Folder 'GCA_005320445.1_PDT000340535.1' already exists. Skipping...
Folder 'GCA_005320485.1_PDT000340537.1' already exists. Skipping...
Folder 'GCA_005320505.1_PDT000340540.1' already exists. Skipping...
Folder 'GCA_005320525.1_PDT000340545.1' already exists. Skipping...
Folder 'GCA_005320545.1_PDT000340542.1' already exists. Skipping...
Folder 'GCA_005320625.1_PDT000340547.1' already exists. Skipping...
Folder 'GCA_005320705.1_PDT000340554.1' already exists. Skipping...
Folder 'GCA_005320725.1_PDT000340549.1' already exists. Skipping...
Folder 'GCA_005320765.1_PDT000340565.1' already exists. Skipping...
Folder 'GCA_005320785.1_PDT000340583.1' already exists. Skipping...
Folder 'GCA_005320815.1_PDT000340572.1' already exists. Skipping...
Folder 'GCA_005320845.1_PDT000340571.1' already exists. Skipping...
Folder 'GCA_005320865.1_PDT000340573.1' already exists. Skipping...
Folder 'GCA_005320905.1_PDT000340569.1' already exists. Skipping...
Folder 'GCA_005320925.1_PDT000340551.1' already exists. Skipping...
Folder 'GCA_005320945.1_PDT000340568.1' already exists. Skipping...
Folder 'GCA_005321045.1_PDT000340587.1' already exists. Skipping...
Folder 'GCA_005321055.1_PDT000340575.1' already exists. Skipping...
Folder 'GCA_005321085.1_PDT000340448.1' already exists. Skipping...
Folder 'GCA_005321145.1_PDT000340576.1' already exists. Skipping...
Folder 'GCA_005321165.1_PDT000340588.1' already exists. Skipping...
Folder 'GCA_005321185.1_PDT000340582.1' already exists. Skipping...
Folder 'GCA_005321205.1_PDT000340589.1' already exists. Skipping...
Folder 'GCA_005321225.1_PDT000340586.1' already exists. Skipping...
Folder 'GCA_005321265.1_PDT000340592.1' already exists. Skipping...
Folder 'GCA_005321275.1_PDT000340595.1' already exists. Skipping...
Folder 'GCA_005321365.1_PDT000340599.1' already exists. Skipping...
Folder 'GCA_005321405.1_PDT000340600.1' already exists. Skipping...
Folder 'GCA_005321415.1_PDT000340598.1' already exists. Skipping...
Folder 'GCA_005321445.1_PDT000340957.1' already exists. Skipping...
Folder 'GCA_005321545.1_PDT000339286.1' already exists. Skipping...
Folder 'GCA_005321565.1_PDT000339303.1' already exists. Skipping...
Folder 'GCA_005321605.1_PDT000339288.1' already exists. Skipping...
Folder 'GCA_005321625.1_PDT000339287.1' already exists. Skipping...
Folder 'GCA_005321645.1_PDT000340940.1' already exists. Skipping...
Folder 'GCA_005321665.1_PDT000339291.1' already exists. Skipping...
Folder 'GCA_005321685.1_PDT000340941.1' already exists. Skipping...
Folder 'GCA_005321725.1_PDT000340942.1' already exists. Skipping...
Folder 'GCA_005321745.1_PDT000340943.1' already exists. Skipping...
Folder 'GCA_005321755.1_PDT000340944.1' already exists. Skipping...
Folder 'GCA_005321785.1_PDT000340953.1' already exists. Skipping...
Folder 'GCA_005321805.1_PDT000340956.1' already exists. Skipping...
Folder 'GCA_005321825.1_PDT000340945.1' already exists. Skipping...
Folder 'GCA_005321845.1_PDT000340951.1' already exists. Skipping...
Folder 'GCA_005321865.1_PDT000340965.1' already exists. Skipping...
Folder 'GCA_005321875.1_PDT000340955.1' already exists. Skipping...
Folder 'GCA_005321905.1_PDT000340954.1' already exists. Skipping...
Folder 'GCA_005321925.1_PDT000340967.1' already exists. Skipping...
Folder 'GCA_005321965.1_PDT000340962.1' already exists. Skipping...
Folder 'GCA_005321985.1_PDT000340964.1' already exists. Skipping...
Folder 'GCA_005322005.1_PDT000340958.1' already exists. Skipping...
Folder 'GCA_005322025.1_PDT000340960.1' already exists. Skipping...
Folder 'GCA_005322065.1_PDT000340968.1' already exists. Skipping...
Folder 'GCA_005322085.1_PDT000340969.1' already exists. Skipping...
Folder 'GCA_005322105.1_PDT000340959.1' already exists. Skipping...
Folder 'GCA_005322125.1_PDT000340975.1' already exists. Skipping...
Folder 'GCA_005322145.1_PDT000340977.1' already exists. Skipping...
Folder 'GCA_005322165.1_PDT000340971.1' already exists. Skipping...

Retreiveing data: 52341it [00:09, 6627.16it/s]

Folder 'GCA_005353405.1_PDT000360060.1' already exists. Skipping...
Folder 'GCA_005353425.1_PDT000360028.1' already exists. Skipping...
Folder 'GCA_005353445.1_PDT000360059.1' already exists. Skipping...
Folder 'GCA_005353465.1_PDT000360040.1' already exists. Skipping...
Folder 'GCA_005353485.1_PDT000360029.1' already exists. Skipping...
Folder 'GCA_005353525.1_PDT000360052.1' already exists. Skipping...
Folder 'GCA_005353565.1_PDT000360047.1' already exists. Skipping...
Folder 'GCA_005353605.1_PDT000360048.1' already exists. Skipping...
Folder 'GCA_005353625.1_PDT000360043.1' already exists. Skipping...
Folder 'GCA_005353645.1_PDT000360036.1' already exists. Skipping...
Folder 'GCA_005353655.1_PDT000360049.1' already exists. Skipping...
Folder 'GCA_005353685.1_PDT000360039.1' already exists. Skipping...
Folder 'GCA_005353725.1_PDT000360057.1' already exists. Skipping...
Folder 'GCA_005353765.1_PDT000360880.1' already exists. Skipping...
Folder 'GCA_005353805.1_PDT000360298.1' already exists. Skipping...
Folder 'GCA_005353845.1_PDT000360286.1' already exists. Skipping...
Folder 'GCA_005353945.1_PDT000360884.1' already exists. Skipping...
Folder 'GCA_005353955.1_PDT000360335.1' already exists. Skipping...
Folder 'GCA_005353985.1_PDT000360339.1' already exists. Skipping...
Folder 'GCA_005354025.1_PDT000360883.1' already exists. Skipping...
Folder 'GCA_005354065.1_PDT000360885.1' already exists. Skipping...
Folder 'GCA_005354125.1_PDT000360330.1' already exists. Skipping...
Folder 'GCA_005354185.1_PDT000360267.1' already exists. Skipping...
Folder 'GCA_005354195.1_PDT000362780.1' already exists. Skipping...
Folder 'GCA_005354235.1_PDT000360133.1' already exists. Skipping...
Folder 'GCA_005354265.1_PDT000360290.1' already exists. Skipping...
Folder 'GCA_005354285.1_PDT000360283.1' already exists. Skipping...
Folder 'GCA_005354305.1_PDT000362766.1' already exists. Skipping...
Folder 'GCA_005354325.1_PDT000360332.1' already exists. Skipping...
Folder 'GCA_005354345.1_PDT000360336.1' already exists. Skipping...
Folder 'GCA_005354365.1_PDT000360874.1' already exists. Skipping...
Folder 'GCA_005354395.1_PDT000362764.1' already exists. Skipping...
Folder 'GCA_005354425.1_PDT000360877.1' already exists. Skipping...
Folder 'GCA_005354465.1_PDT000362723.1' already exists. Skipping...
Folder 'GCA_005354485.1_PDT000360291.1' already exists. Skipping...
Folder 'GCA_005354525.1_PDT000360892.1' already exists. Skipping...
Folder 'GCA_005354565.1_PDT000360894.1' already exists. Skipping...
Folder 'GCA_005354605.1_PDT000362726.1' already exists. Skipping...
Folder 'GCA_005354625.1_PDT000362732.1' already exists. Skipping...
Folder 'GCA_005354665.1_PDT000360891.1' already exists. Skipping...
Folder 'GCA_005354705.1_PDT000360337.1' already exists. Skipping...
Folder 'GCA_005354745.1_PDT000283008.3' already exists. Skipping...
Folder 'GCA_005354765.1_PDT000360889.1' already exists. Skipping...
Folder 'GCA_005354785.1_PDT000360873.1' already exists. Skipping...
Folder 'GCA_005354805.1_PDT000360110.1' already exists. Skipping...
Folder 'GCA_005354845.1_PDT000360876.1' already exists. Skipping...
Folder 'GCA_005354885.1_PDT000361218.1' already exists. Skipping...
Folder 'GCA_005354945.1_PDT000361215.1' already exists. Skipping...
Folder 'GCA_005354965.1_PDT000360896.1' already exists. Skipping...
Folder 'GCA_005354985.1_PDT000360901.1' already exists. Skipping...
Folder 'GCA_005355005.1_PDT000360911.1' already exists. Skipping...
Folder 'GCA_005355025.1_PDT000361214.1' already exists. Skipping...
Folder 'GCA_005355065.1_PDT000360895.1' already exists. Skipping...
Folder 'GCA_005355085.1_PDT000361219.1' already exists. Skipping...
Folder 'GCA_005355125.1_PDT000361216.1' already exists. Skipping...
Folder 'GCA_005355145.1_PDT000360899.1' already exists. Skipping...
Folder 'GCA_005355165.1_PDT000360902.1' already exists. Skipping...
Folder 'GCA_005355185.1_PDT000361217.1' already exists. Skipping...
Folder 'GCA_005355245.1_PDT000305552.3' already exists. Skipping...
Folder 'GCA_005355285.1_PDT000362714.1' already exists. Skipping...
Folder 'GCA_005355305.1_PDT000362715.1' already exists. Skipping...
Folder 'GCA_005355325.1_PDT000362716.1' already exists. Skipping...
Folder 'GCA_005355405.1_PDT000362736.1' already exists. Skipping...
Folder 'GCA_005355445.1_PDT000361221.1' already exists. Skipping...
Folder 'GCA_005355465.1_PDT000362721.1' already exists. Skipping...
Folder 'GCA_005355485.1_PDT000362718.1' already exists. Skipping...
Folder 'GCA_005355505.1_PDT000362743.1' already exists. Skipping...
Folder 'GCA_005355545.1_PDT000361220.1' already exists. Skipping...
Folder 'GCA_005355565.1_PDT000362734.1' already exists. Skipping...
Folder 'GCA_005355585.1_PDT000362742.1' already exists. Skipping...
Folder 'GCA_005355625.1_PDT000362744.1' already exists. Skipping...
Folder 'GCA_005355705.1_PDT000362750.1' already exists. Skipping...
Folder 'GCA_005355725.1_PDT000362752.1' already exists. Skipping...
Folder 'GCA_005355785.1_PDT000362754.1' already exists. Skipping...
Folder 'GCA_005355845.1_PDT000362912.1' already exists. Skipping...
Folder 'GCA_005355855.1_PDT000362753.1' already exists. Skipping...
Folder 'GCA_005355885.1_PDT000362801.1' already exists. Skipping...
Folder 'GCA_005355905.1_PDT000362763.1' already exists. Skipping...
Folder 'GCA_005355925.1_PDT000362741.1' already exists. Skipping...
Folder 'GCA_005355945.1_PDT000362955.1' already exists. Skipping...
Folder 'GCA_005355965.1_PDT000362740.1' already exists. Skipping...
Folder 'GCA_005356005.1_PDT000362957.1' already exists. Skipping...
Folder 'GCA_005356025.1_PDT000362958.1' already exists. Skipping...
Folder 'GCA_005356045.1_PDT000362956.1' already exists. Skipping...
Folder 'GCA_005356185.1_PDT000362769.1' already exists. Skipping...
Folder 'GCA_005356205.1_PDT000362949.1' already exists. Skipping...
Folder 'GCA_005356245.1_PDT000362946.1' already exists. Skipping...
Folder 'GCA_005356265.1_PDT000362776.1' already exists. Skipping...
Folder 'GCA_005356285.1_PDT000362777.1' already exists. Skipping...
Folder 'GCA_005356325.1_PDT000362779.1' already exists. Skipping...
Folder 'GCA_005356385.1_PDT000362945.1' already exists. Skipping...
Folder 'GCA_005356405.1_PDT000362799.1' already exists. Skipping...
Folder 'GCA_005356425.1_PDT000362944.1' already exists. Skipping...
Folder 'GCA_005356445.1_PDT000362739.1' already exists. Skipping...
Folder 'GCA_005356485.1_PDT000362947.1' already exists. Skipping...
Folder 'GCA_005356505.1_PDT000362953.1' already exists. Skipping...
Folder 'GCA_005356525.1_PDT000362952.1' already exists. Skipping...
Folder 'GCA_005356545.1_PDT000362965.1' already exists. Skipping...
Folder 'GCA_005356565.1_PDT000362948.1' already exists. Skipping...
Folder 'GCA_005356585.1_PDT000362950.1' already exists. Skipping...
Folder 'GCA_005356605.1_PDT000362951.1' already exists. Skipping...
Folder 'GCA_005356625.1_PDT000362954.1' already exists. Skipping...
Folder 'GCA_005356645.1_PDT000360266.1' already exists. Skipping...
Folder 'GCA_005356705.1_PDT000360879.1' already exists. Skipping...
Folder 'GCA_005356745.1_PDT000363222.1' already exists. Skipping...
Folder 'GCA_005356785.1_PDT000362722.1' already exists. Skipping...
Folder 'GCA_005356815.1_PDT000362980.1' already exists. Skipping...
Folder 'GCA_005356835.1_PDT000360333.1' already exists. Skipping...
Folder 'GCA_005356865.1_PDT000363005.1' already exists. Skipping...
Folder 'GCA_005356895.1_PDT000362979.1' already exists. Skipping...
Folder 'GCA_005356915.1_PDT000363224.1' already exists. Skipping...
Folder 'GCA_005356945.1_PDT000362982.1' already exists. Skipping...
Folder 'GCA_005356965.1_PDT000362981.1' already exists. Skipping...
Folder 'GCA_005356985.1_PDT000363007.1' already exists. Skipping...
Folder 'GCA_005357005.1_PDT000362978.1' already exists. Skipping...
Folder 'GCA_005357025.1_PDT000362959.1' already exists. Skipping...
Folder 'GCA_005357045.1_PDT000363180.1' already exists. Skipping...
Folder 'GCA_005357095.1_PDT000363210.1' already exists. Skipping...
Folder 'GCA_005357125.1_PDT000363207.1' already exists. Skipping...
Folder 'GCA_005357165.1_PDT000363008.1' already exists. Skipping...
Folder 'GCA_005357185.1_PDT000363208.1' already exists. Skipping...
Folder 'GCA_005357205.1_PDT000362910.1' already exists. Skipping...
Folder 'GCA_005357255.1_PDT000362942.1' already exists. Skipping...
Folder 'GCA_005357325.1_PDT000362966.1' already exists. Skipping...
Folder 'GCA_005357345.1_PDT000362964.1' already exists. Skipping...
Folder 'GCA_005357365.1_PDT000362943.1' already exists. Skipping...
Folder 'GCA_005357385.1_PDT000362976.1' already exists. Skipping...
Folder 'GCA_005357395.1_PDT000362971.1' already exists. Skipping...
Folder 'GCA_005357425.1_PDT000362967.1' already exists. Skipping...
Folder 'GCA_005357445.1_PDT000362963.1' already exists. Skipping...
Folder 'GCA_005357465.1_PDT000362968.1' already exists. Skipping...
Folder 'GCA_005357485.1_PDT000362972.1' already exists. Skipping...
Folder 'GCA_005357505.1_PDT000362961.1' already exists. Skipping...
Folder 'GCA_005357525.1_PDT000362969.1' already exists. Skipping...
Folder 'GCA_005357545.1_PDT000362974.1' already exists. Skipping...
Folder 'GCA_005357565.1_PDT000362991.1' already exists. Skipping...
Folder 'GCA_005357605.1_PDT000362988.1' already exists. Skipping...
Folder 'GCA_005357615.1_PDT000362970.1' already exists. Skipping...
Folder 'GCA_005357645.1_PDT000362989.1' already exists. Skipping...
Folder 'GCA_005357665.1_PDT000362960.1' already exists. Skipping...
Folder 'GCA_005357685.1_PDT000362977.1' already exists. Skipping...
Folder 'GCA_005357705.1_PDT000362987.1' already exists. Skipping...
Folder 'GCA_005357725.1_PDT000362973.1' already exists. Skipping...
Folder 'GCA_005357735.1_PDT000362962.1' already exists. Skipping...
Folder 'GCA_005357765.1_PDT000363185.1' already exists. Skipping...
Folder 'GCA_005357785.1_PDT000362993.1' already exists. Skipping...
Folder 'GCA_005357805.1_PDT000362994.1' already exists. Skipping...
Folder 'GCA_005357825.1_PDT000362992.1' already exists. Skipping...
Folder 'GCA_005357845.1_PDT000362999.1' already exists. Skipping...
Folder 'GCA_005357865.1_PDT000362997.1' already exists. Skipping...
Folder 'GCA_005357885.1_PDT000362995.1' already exists. Skipping...
Folder 'GCA_005357905.1_PDT000362998.1' already exists. Skipping...
Folder 'GCA_005357925.1_PDT000363190.1' already exists. Skipping...
Folder 'GCA_005357945.1_PDT000362996.1' already exists. Skipping...
Folder 'GCA_005357965.1_PDT000363000.1' already exists. Skipping...
Folder 'GCA_005357985.1_PDT000363003.1' already exists. Skipping...
Folder 'GCA_005358005.1_PDT000363001.1' already exists. Skipping...
Folder 'GCA_005358015.1_PDT000363002.1' already exists. Skipping...
Folder 'GCA_005358045.1_PDT000363004.1' already exists. Skipping...
Folder 'GCA_005358065.1_PDT000362985.1' already exists. Skipping...
Folder 'GCA_005358085.1_PDT000362986.1' already exists. Skipping...
Folder 'GCA_005358105.1_PDT000363183.1' already exists. Skipping...
Folder 'GCA_005358125.1_PDT000363182.1' already exists. Skipping...
Folder 'GCA_005358185.1_PDT000362983.1' already exists. Skipping...
Folder 'GCA_005358245.1_PDT000363188.1' already exists. Skipping...
Folder 'GCA_005358265.1_PDT000363196.1' already exists. Skipping...
Folder 'GCA_005358285.1_PDT000363192.1' already exists. Skipping...
Folder 'GCA_005358305.1_PDT000363189.1' already exists. Skipping...
Folder 'GCA_005358325.1_PDT000363194.1' already exists. Skipping...
Folder 'GCA_005358365.1_PDT000363006.1' already exists. Skipping...
Folder 'GCA_005358385.1_PDT000363201.1' already exists. Skipping...
Folder 'GCA_005358405.1_PDT000363191.1' already exists. Skipping...
Folder 'GCA_005358445.1_PDT000363215.1' already exists. Skipping...
Folder 'GCA_005358485.1_PDT000363214.1' already exists. Skipping...
Folder 'GCA_005358495.1_PDT000363216.1' already exists. Skipping...
Folder 'GCA_005358585.1_PDT000363212.1' already exists. Skipping...
Folder 'GCA_005358625.1_PDT000363219.1' already exists. Skipping...
Folder 'GCA_005358635.1_PDT000363223.1' already exists. Skipping...
Folder 'GCA_005358665.1_PDT000363221.1' already exists. Skipping...
Folder 'GCA_005358705.1_PDT000363203.1' already exists. Skipping...
Folder 'GCA_005358745.1_PDT000363204.1' already exists. Skipping...
Folder 'GCA_005358765.1_PDT000363232.1' already exists. Skipping...
Folder 'GCA_005358825.1_PDT000363205.1' already exists. Skipping...
Folder 'GCA_005358865.1_PDT000363256.1' already exists. Skipping...
Folder 'GCA_005358905.1_PDT000363243.1' already exists. Skipping...
Folder 'GCA_005358925.1_PDT000363264.1' already exists. Skipping...
Folder 'GCA_005358965.1_PDT000363279.1' already exists. Skipping...
Folder 'GCA_005359005.1_PDT000363253.1' already exists. Skipping...
Folder 'GCA_005359015.1_PDT000363254.1' already exists. Skipping...
Folder 'GCA_005359045.1_PDT000363241.1' already exists. Skipping...
Folder 'GCA_005359065.1_PDT000363295.1' already exists. Skipping...
Folder 'GCA_005359085.1_PDT000363278.1' already exists. Skipping...
Folder 'GCA_005359105.1_PDT000363257.1' already exists. Skipping...
Folder 'GCA_005359125.1_PDT000363297.1' already exists. Skipping...
Folder 'GCA_005359145.1_PDT000363283.1' already exists. Skipping...
Folder 'GCA_005359185.1_PDT000363255.1' already exists. Skipping...
Folder 'GCA_005359205.1_PDT000363298.1' already exists. Skipping...
Folder 'GCA_005359225.1_PDT000363266.1' already exists. Skipping...
Folder 'GCA_005359245.1_PDT000363258.1' already exists. Skipping...
Folder 'GCA_005359265.1_PDT000363235.1' already exists. Skipping...
Folder 'GCA_005359285.1_PDT000363245.1' already exists. Skipping...
Folder 'GCA_005359305.1_PDT000363236.1' already exists. Skipping...
Folder 'GCA_005359325.1_PDT000363285.1' already exists. Skipping...
Folder 'GCA_005359345.1_PDT000363237.1' already exists. Skipping...
Folder 'GCA_005359365.1_PDT000363272.1' already exists. Skipping...
Folder 'GCA_005359375.1_PDT000363240.1' already exists. Skipping...
Folder 'GCA_005359405.1_PDT000363225.1' already exists. Skipping...
Folder 'GCA_005359425.1_PDT000363271.1' already exists. Skipping...
Folder 'GCA_005359445.1_PDT000363238.1' already exists. Skipping...
Folder 'GCA_005359465.1_PDT000363230.1' already exists. Skipping...
Folder 'GCA_005359485.1_PDT000363284.1' already exists. Skipping...
Folder 'GCA_005359505.1_PDT000363227.1' already exists. Skipping...
Folder 'GCA_005359525.1_PDT000363270.1' already exists. Skipping...
Folder 'GCA_005359545.1_PDT000363265.1' already exists. Skipping...
Folder 'GCA_005359565.1_PDT000363229.1' already exists. Skipping...
Folder 'GCA_005359585.1_PDT000363277.1' already exists. Skipping...
Folder 'GCA_005359605.1_PDT000363267.1' already exists. Skipping...
Folder 'GCA_005359645.1_PDT000363242.1' already exists. Skipping...
Folder 'GCA_005359665.1_PDT000363269.1' already exists. Skipping...
Folder 'GCA_005359695.1_PDT000363250.1' already exists. Skipping...
Folder 'GCA_005359725.1_PDT000363244.1' already exists. Skipping...
Folder 'GCA_005359735.1_PDT000363276.1' already exists. Skipping...
Folder 'GCA_005359805.1_PDT000363251.1' already exists. Skipping...
Folder 'GCA_005359825.1_PDT000363248.1' already exists. Skipping...
Folder 'GCA_005359845.1_PDT000363280.1' already exists. Skipping...
Folder 'GCA_005359855.1_PDT000363263.1' already exists. Skipping...
Folder 'GCA_005359885.1_PDT000363234.1' already exists. Skipping...
Folder 'GCA_005359905.1_PDT000363252.1' already exists. Skipping...
Folder 'GCA_005359925.1_PDT000363275.1' already exists. Skipping...
Folder 'GCA_005359945.1_PDT000363273.1' already exists. Skipping...
Folder 'GCA_005359965.1_PDT000363288.1' already exists. Skipping...
Folder 'GCA_005359985.1_PDT000363292.1' already exists. Skipping...
Folder 'GCA_005360005.1_PDT000363287.1' already exists. Skipping...
Folder 'GCA_005360045.1_PDT000363366.1' already exists. Skipping...
Folder 'GCA_005360125.1_PDT000363370.1' already exists. Skipping...
Folder 'GCA_005360145.1_PDT000363306.1' already exists. Skipping...
Folder 'GCA_005360245.1_PDT000363260.1' already exists. Skipping...
Folder 'GCA_005360265.1_PDT000363299.1' already exists. Skipping...
Folder 'GCA_005360285.1_PDT000363296.1' already exists. Skipping...
Folder 'GCA_005360305.1_PDT000363259.1' already exists. Skipping...
Folder 'GCA_005360325.1_PDT000363261.1' already exists. Skipping...
Folder 'GCA_005360345.1_PDT000363291.1' already exists. Skipping...
Folder 'GCA_005360365.1_PDT000363313.1' already exists. Skipping...
Folder 'GCA_005360445.1_PDT000363321.1' already exists. Skipping...
Folder 'GCA_005360465.1_PDT000363332.1' already exists. Skipping...
Folder 'GCA_005360505.1_PDT000363331.1' already exists. Skipping...
Folder 'GCA_005360525.1_PDT000363330.1' already exists. Skipping...
Folder 'GCA_005360545.1_PDT000363326.1' already exists. Skipping...
Folder 'GCA_005360605.1_PDT000363338.1' already exists. Skipping...
Folder 'GCA_005360625.1_PDT000363310.1' already exists. Skipping...
Folder 'GCA_005360645.1_PDT000363328.1' already exists. Skipping...
Folder 'GCA_005360665.1_PDT000363302.1' already exists. Skipping...
Folder 'GCA_005360695.1_PDT000363324.1' already exists. Skipping...
Folder 'GCA_005360745.1_PDT000363329.1' already exists. Skipping...
Folder 'GCA_005360785.1_PDT000363325.1' already exists. Skipping...
Folder 'GCA_005360825.1_PDT000363317.1' already exists. Skipping...
Folder 'GCA_005360845.1_PDT000363339.1' already exists. Skipping...
Folder 'GCA_005360925.1_PDT000363345.1' already exists. Skipping...
Folder 'GCA_005360945.1_PDT000363341.1' already exists. Skipping...
Folder 'GCA_005361085.1_PDT000363334.1' already exists. Skipping...
Folder 'GCA_005361105.1_PDT000363353.1' already exists. Skipping...
Folder 'GCA_005361165.1_PDT000363336.1' already exists. Skipping...
Folder 'GCA_005361205.1_PDT000363347.1' already exists. Skipping...
Folder 'GCA_005361265.1_PDT000363307.1' already exists. Skipping...
Folder 'GCA_005361305.1_PDT000363356.1' already exists. Skipping...
Folder 'GCA_005361325.1_PDT000363362.1' already exists. Skipping...
Folder 'GCA_005361345.1_PDT000363409.1' already exists. Skipping...
Folder 'GCA_005361405.1_PDT000363383.1' already exists. Skipping...
Folder 'GCA_005361465.1_PDT000363385.1' already exists. Skipping...
Folder 'GCA_005361485.1_PDT000363449.1' already exists. Skipping...
Folder 'GCA_005361505.1_PDT000363371.1' already exists. Skipping...
Folder 'GCA_005361525.1_PDT000363399.1' already exists. Skipping...
Folder 'GCA_005361565.1_PDT000363373.1' already exists. Skipping...
Folder 'GCA_005361645.1_PDT000363354.1' already exists. Skipping...
Folder 'GCA_005361665.1_PDT000363406.1' already exists. Skipping...
Folder 'GCA_005361705.1_PDT000363365.1' already exists. Skipping...
Folder 'GCA_005361725.1_PDT000363364.1' already exists. Skipping...
Folder 'GCA_005361745.1_PDT000363358.1' already exists. Skipping...
Folder 'GCA_005361765.1_PDT000363378.1' already exists. Skipping...
Folder 'GCA_005361825.1_PDT000363382.1' already exists. Skipping...
Folder 'GCA_005361845.1_PDT000363367.1' already exists. Skipping...
Folder 'GCA_005361865.1_PDT000363293.1' already exists. Skipping...
Folder 'GCA_005361885.1_PDT000363393.1' already exists. Skipping...
Folder 'GCA_005361905.1_PDT000363315.1' already exists. Skipping...
Folder 'GCA_005361965.1_PDT000363335.1' already exists. Skipping...
Folder 'GCA_005361985.1_PDT000363397.1' already exists. Skipping...
Folder 'GCA_005362045.1_PDT000363497.1' already exists. Skipping...
Folder 'GCA_005362065.1_PDT000363460.1' already exists. Skipping...
Folder 'GCA_005362085.1_PDT000363420.1' already exists. Skipping...
Folder 'GCA_005362105.1_PDT000363516.1' already exists. Skipping...
Folder 'GCA_005362145.1_PDT000364169.1' already exists. Skipping...
Folder 'GCA_005362165.1_PDT000363458.1' already exists. Skipping...
Folder 'GCA_005362185.1_PDT000363463.1' already exists. Skipping...
Folder 'GCA_005362225.1_PDT000363517.1' already exists. Skipping...

Retreiveing data: 53676it [00:09, 6643.05it/s]

Folder 'GCA_005930115.1_PDT000509986.1' already exists. Skipping...
Folder 'GCA_005930135.1_PDT000510018.1' already exists. Skipping...
Folder 'GCA_005930155.1_PDT000509988.1' already exists. Skipping...
Folder 'GCA_005930175.1_PDT000509992.1' already exists. Skipping...
Folder 'GCA_005930195.1_PDT000509989.1' already exists. Skipping...
Folder 'GCA_005930215.1_PDT000509994.1' already exists. Skipping...
Folder 'GCA_005930235.1_PDT000509995.1' already exists. Skipping...
Folder 'GCA_005930275.1_PDT000509993.1' already exists. Skipping...
Folder 'GCA_005930295.1_PDT000510020.1' already exists. Skipping...
Folder 'GCA_005930315.1_PDT000510019.1' already exists. Skipping...
Folder 'GCA_005930335.1_PDT000510022.1' already exists. Skipping...
Folder 'GCA_005930375.1_PDT000510021.1' already exists. Skipping...
Folder 'GCA_005930755.1_PDT000510023.1' already exists. Skipping...
Folder 'GCA_006149945.1_PDT000198028.2' already exists. Skipping...
Folder 'GCA_006149965.1_PDT000208338.2' already exists. Skipping...
Folder 'GCA_006176565.1_PDT000137312.2' already exists. Skipping...
Folder 'GCA_006176585.1_PDT000137319.2' already exists. Skipping...
Folder 'GCA_006176645.1_PDT000137322.2' already exists. Skipping...
Folder 'GCA_006219545.1_PDT000510612.1' already exists. Skipping...
Folder 'GCA_006222275.1_PDT000517909.1' already exists. Skipping...
Folder 'GCA_006222315.1_PDT000517911.1' already exists. Skipping...
Folder 'GCA_006222335.1_PDT000517910.1' already exists. Skipping...
Folder 'GCA_006222395.1_PDT000517914.1' already exists. Skipping...
Folder 'GCA_006222415.1_PDT000510853.1' already exists. Skipping...
Folder 'GCA_006222435.1_PDT000518096.1' already exists. Skipping...
Folder 'GCA_006222455.1_PDT000517555.1' already exists. Skipping...
Folder 'GCA_006222495.1_PDT000518103.1' already exists. Skipping...
Folder 'GCA_006222515.1_PDT000518106.1' already exists. Skipping...
Folder 'GCA_006222535.1_PDT000518105.1' already exists. Skipping...
Folder 'GCA_006222555.1_PDT000518108.1' already exists. Skipping...
Folder 'GCA_006222575.1_PDT000518110.1' already exists. Skipping...
Folder 'GCA_006222605.1_PDT000518111.1' already exists. Skipping...
Folder 'GCA_006222625.1_PDT000518092.1' already exists. Skipping...
Folder 'GCA_006222665.1_PDT000518080.1' already exists. Skipping...
Folder 'GCA_006222685.1_PDT000518087.1' already exists. Skipping...
Folder 'GCA_006222705.1_PDT000518090.1' already exists. Skipping...
Folder 'GCA_006222725.1_PDT000518084.1' already exists. Skipping...
Folder 'GCA_006222735.1_PDT000518083.1' already exists. Skipping...
Folder 'GCA_006222765.1_PDT000518075.1' already exists. Skipping...
Folder 'GCA_006222805.1_PDT000518086.1' already exists. Skipping...
Folder 'GCA_006222845.1_PDT000518077.1' already exists. Skipping...
Folder 'GCA_006222905.1_PDT000517990.1' already exists. Skipping...
Folder 'GCA_006222925.1_PDT000517994.1' already exists. Skipping...
Folder 'GCA_006222945.1_PDT000517992.1' already exists. Skipping...
Folder 'GCA_006222985.1_PDT000518059.1' already exists. Skipping...
Folder 'GCA_006223005.1_PDT000518051.1' already exists. Skipping...
Folder 'GCA_006223045.1_PDT000517409.1' already exists. Skipping...
Folder 'GCA_006223065.1_PDT000517564.1' already exists. Skipping...
Folder 'GCA_006223085.1_PDT000518063.1' already exists. Skipping...
Folder 'GCA_006223105.1_PDT000517987.1' already exists. Skipping...
Folder 'GCA_006223145.1_PDT000517985.1' already exists. Skipping...
Folder 'GCA_006223185.1_PDT000517432.1' already exists. Skipping...
Folder 'GCA_006223245.1_PDT000510624.1' already exists. Skipping...
Folder 'GCA_006223265.1_PDT000517433.1' already exists. Skipping...
Folder 'GCA_006223285.1_PDT000517981.1' already exists. Skipping...
Folder 'GCA_006223305.1_PDT000517979.1' already exists. Skipping...
Folder 'GCA_006223325.1_PDT000517980.1' already exists. Skipping...
Folder 'GCA_006223345.1_PDT000510851.1' already exists. Skipping...
Folder 'GCA_006223365.1_PDT000510891.1' already exists. Skipping...
Folder 'GCA_006223385.1_PDT000510859.1' already exists. Skipping...
Folder 'GCA_006223405.1_PDT000517553.1' already exists. Skipping...
Folder 'GCA_006223425.1_PDT000517551.1' already exists. Skipping...
Folder 'GCA_006223445.1_PDT000517501.1' already exists. Skipping...
Folder 'GCA_006223465.1_PDT000517398.1' already exists. Skipping...
Folder 'GCA_006223485.1_PDT000517431.1' already exists. Skipping...
Folder 'GCA_006223505.1_PDT000517250.1' already exists. Skipping...
Folder 'GCA_006223565.1_PDT000517400.1' already exists. Skipping...
Folder 'GCA_006223625.1_PDT000510622.1' already exists. Skipping...
Folder 'GCA_006223665.1_PDT000517563.1' already exists. Skipping...
Folder 'GCA_006223685.1_PDT000510861.1' already exists. Skipping...
Folder 'GCA_006223705.1_PDT000510871.1' already exists. Skipping...
Folder 'GCA_006223765.1_PDT000510860.1' already exists. Skipping...
Folder 'GCA_006223805.1_PDT000517405.1' already exists. Skipping...
Folder 'GCA_006223865.1_PDT000517430.1' already exists. Skipping...
Folder 'GCA_006223885.1_PDT000517549.1' already exists. Skipping...
Folder 'GCA_006223905.1_PDT000517550.1' already exists. Skipping...
Folder 'GCA_006223925.1_PDT000517514.1' already exists. Skipping...
Folder 'GCA_006223945.1_PDT000510857.1' already exists. Skipping...
Folder 'GCA_006223965.1_PDT000517917.1' already exists. Skipping...
Folder 'GCA_006224005.1_PDT000510888.1' already exists. Skipping...
Folder 'GCA_006224045.1_PDT000510889.1' already exists. Skipping...
Folder 'GCA_006224065.1_PDT000510890.1' already exists. Skipping...
Folder 'GCA_006224125.1_PDT000510894.1' already exists. Skipping...
Folder 'GCA_006224145.1_PDT000517526.1' already exists. Skipping...
Folder 'GCA_006224165.1_PDT000517505.1' already exists. Skipping...
Folder 'GCA_006224205.1_PDT000517506.1' already exists. Skipping...
Folder 'GCA_006224245.1_PDT000510638.1' already exists. Skipping...
Folder 'GCA_006224285.1_PDT000510623.1' already exists. Skipping...
Folder 'GCA_006224305.1_PDT000510849.1' already exists. Skipping...
Folder 'GCA_006224325.2_PDT000510858.2' already exists. Skipping...
Folder 'GCA_006224365.1_PDT000517402.1' already exists. Skipping...
Folder 'GCA_006224395.1_PDT000510856.1' already exists. Skipping...
Folder 'GCA_006224445.1_PDT000518071.1' already exists. Skipping...
Folder 'GCA_006224465.1_PDT000517902.1' already exists. Skipping...
Folder 'GCA_006224485.1_PDT000517552.1' already exists. Skipping...
Folder 'GCA_006224505.1_PDT000510850.1' already exists. Skipping...
Folder 'GCA_006224525.1_PDT000517567.1' already exists. Skipping...
Folder 'GCA_006224645.1_PDT000517918.1' already exists. Skipping...
Folder 'GCA_006224725.1_PDT000517972.1' already exists. Skipping...
Folder 'GCA_006224745.1_PDT000517970.1' already exists. Skipping...
Folder 'GCA_006224785.1_PDT000517973.1' already exists. Skipping...
Folder 'GCA_006224825.1_PDT000517975.1' already exists. Skipping...
Folder 'GCA_006224905.1_PDT000517820.1' already exists. Skipping...
Folder 'GCA_006224925.1_PDT000517800.1' already exists. Skipping...
Folder 'GCA_006225025.1_PDT000517570.1' already exists. Skipping...
Folder 'GCA_006225045.1_PDT000517901.1' already exists. Skipping...
Folder 'GCA_006225085.1_PDT000517499.1' already exists. Skipping...
Folder 'GCA_006225105.1_PDT000517565.1' already exists. Skipping...
Folder 'GCA_006225125.1_PDT000518098.1' already exists. Skipping...
Folder 'GCA_006225145.1_PDT000517561.1' already exists. Skipping...
Folder 'GCA_006225165.1_PDT000510776.1' already exists. Skipping...
Folder 'GCA_006225185.1_PDT000518069.1' already exists. Skipping...
Folder 'GCA_006225205.1_PDT000510847.1' already exists. Skipping...
Folder 'GCA_006225225.1_PDT000510848.1' already exists. Skipping...
Folder 'GCA_006352995.1_PDT000521874.1' already exists. Skipping...
Folder 'GCA_006353355.1_PDT000519257.1' already exists. Skipping...
Folder 'GCA_006353485.1_PDT000519251.1' already exists. Skipping...
Folder 'GCA_006353575.1_PDT000521712.1' already exists. Skipping...
Folder 'GCA_006353695.1_PDT000520658.1' already exists. Skipping...
Folder 'GCA_006353925.1_PDT000521769.1' already exists. Skipping...
Folder 'GCA_006354015.1_PDT000521718.1' already exists. Skipping...
Folder 'GCA_006354035.1_PDT000521857.1' already exists. Skipping...
Folder 'GCA_006354115.1_PDT000521715.1' already exists. Skipping...
Folder 'GCA_006354165.1_PDT000521892.1' already exists. Skipping...
Folder 'GCA_006354195.1_PDT000522536.1' already exists. Skipping...
Folder 'GCA_006354235.1_PDT000521713.1' already exists. Skipping...
Folder 'GCA_006354555.1_PDT000521859.1' already exists. Skipping...
Folder 'GCA_006354675.1_PDT000521773.1' already exists. Skipping...
Folder 'GCA_006354995.1_PDT000521832.1' already exists. Skipping...
Folder 'GCA_006355175.1_PDT000521964.1' already exists. Skipping...
Folder 'GCA_006355555.1_PDT000521785.1' already exists. Skipping...
Folder 'GCA_006355615.1_PDT000521836.1' already exists. Skipping...
Folder 'GCA_006355655.1_PDT000518237.1' already exists. Skipping...
Folder 'GCA_006355675.1_PDT000518236.1' already exists. Skipping...
Folder 'GCA_006355715.1_PDT000518245.1' already exists. Skipping...
Folder 'GCA_006355755.1_PDT000518240.1' already exists. Skipping...
Folder 'GCA_006355775.1_PDT000518640.1' already exists. Skipping...
Folder 'GCA_006355795.1_PDT000518639.1' already exists. Skipping...
Folder 'GCA_006355815.1_PDT000518642.1' already exists. Skipping...
Folder 'GCA_006355855.1_PDT000518243.1' already exists. Skipping...
Folder 'GCA_006355875.1_PDT000518641.1' already exists. Skipping...
Folder 'GCA_006355895.1_PDT000519144.1' already exists. Skipping...
Folder 'GCA_006355935.1_PDT000519214.1' already exists. Skipping...
Folder 'GCA_006356035.1_PDT000519224.1' already exists. Skipping...
Folder 'GCA_006356055.1_PDT000519219.1' already exists. Skipping...
Folder 'GCA_006356115.1_PDT000519227.1' already exists. Skipping...
Folder 'GCA_006356135.1_PDT000519228.1' already exists. Skipping...
Folder 'GCA_006356175.1_PDT000519230.1' already exists. Skipping...
Folder 'GCA_006356255.1_PDT000521794.1' already exists. Skipping...
Folder 'GCA_006356275.1_PDT000519235.1' already exists. Skipping...
Folder 'GCA_006356295.1_PDT000521802.1' already exists. Skipping...
Folder 'GCA_006356315.1_PDT000519234.1' already exists. Skipping...
Folder 'GCA_006356375.1_PDT000521792.1' already exists. Skipping...
Folder 'GCA_006356395.1_PDT000519237.1' already exists. Skipping...
Folder 'GCA_006356425.1_PDT000519238.1' already exists. Skipping...
Folder 'GCA_006356475.1_PDT000519240.1' already exists. Skipping...
Folder 'GCA_006356495.1_PDT000519241.1' already exists. Skipping...
Folder 'GCA_006356515.1_PDT000519245.1' already exists. Skipping...
Folder 'GCA_006356535.1_PDT000519249.1' already exists. Skipping...
Folder 'GCA_006356575.1_PDT000519244.1' already exists. Skipping...
Folder 'GCA_006356655.1_PDT000521800.1' already exists. Skipping...
Folder 'GCA_006356715.1_PDT000519262.1' already exists. Skipping...
Folder 'GCA_006356755.1_PDT000519743.1' already exists. Skipping...
Folder 'GCA_006356815.1_PDT000521849.1' already exists. Skipping...
Folder 'GCA_006356855.1_PDT000519760.1' already exists. Skipping...
Folder 'GCA_006356915.1_PDT000519756.1' already exists. Skipping...
Folder 'GCA_006356945.1_PDT000519762.1' already exists. Skipping...
Folder 'GCA_006356975.1_PDT000519763.1' already exists. Skipping...
Folder 'GCA_006356995.1_PDT000519769.1' already exists. Skipping...
Folder 'GCA_006357015.1_PDT000519764.1' already exists. Skipping...
Folder 'GCA_006357035.1_PDT000519766.1' already exists. Skipping...
Folder 'GCA_006357055.1_PDT000519768.1' already exists. Skipping...
Folder 'GCA_006357075.1_PDT000519765.1' already exists. Skipping...
Folder 'GCA_006357095.1_PDT000519767.1' already exists. Skipping...
Folder 'GCA_006357135.1_PDT000519775.1' already exists. Skipping...
Folder 'GCA_006357215.1_PDT000519774.1' already exists. Skipping...
Folder 'GCA_006357235.1_PDT000519773.1' already exists. Skipping...
Folder 'GCA_006357255.1_PDT000519777.1' already exists. Skipping...
Folder 'GCA_006357275.1_PDT000519971.1' already exists. Skipping...
Folder 'GCA_006357315.1_PDT000519776.1' already exists. Skipping...
Folder 'GCA_006357375.1_PDT000519970.1' already exists. Skipping...
Folder 'GCA_006357435.1_PDT000519779.1' already exists. Skipping...
Folder 'GCA_006357455.1_PDT000519967.1' already exists. Skipping...
Folder 'GCA_006357495.1_PDT000519976.1' already exists. Skipping...
Folder 'GCA_006357555.1_PDT000519973.1' already exists. Skipping...
Folder 'GCA_006357575.1_PDT000519978.1' already exists. Skipping...
Folder 'GCA_006357595.1_PDT000519977.1' already exists. Skipping...
Folder 'GCA_006357615.1_PDT000520116.1' already exists. Skipping...
Folder 'GCA_006357635.1_PDT000520257.1' already exists. Skipping...
Folder 'GCA_006357655.1_PDT000520184.1' already exists. Skipping...
Folder 'GCA_006357675.1_PDT000520657.1' already exists. Skipping...
Folder 'GCA_006357695.1_PDT000520656.1' already exists. Skipping...
Folder 'GCA_006357705.1_PDT000520655.1' already exists. Skipping...
Folder 'GCA_006357735.1_PDT000520654.1' already exists. Skipping...
Folder 'GCA_006357755.1_PDT000520653.1' already exists. Skipping...
Folder 'GCA_006357795.1_PDT000521722.1' already exists. Skipping...
Folder 'GCA_006357815.1_PDT000521719.1' already exists. Skipping...
Folder 'GCA_006357835.1_PDT000521720.1' already exists. Skipping...
Folder 'GCA_006357875.1_PDT000521726.1' already exists. Skipping...
Folder 'GCA_006357895.1_PDT000521725.1' already exists. Skipping...
Folder 'GCA_006357915.1_PDT000521723.1' already exists. Skipping...
Folder 'GCA_006357935.1_PDT000521727.1' already exists. Skipping...
Folder 'GCA_006357995.1_PDT000522686.1' already exists. Skipping...
Folder 'GCA_006358015.1_PDT000521730.1' already exists. Skipping...
Folder 'GCA_006358055.1_PDT000521821.1' already exists. Skipping...
Folder 'GCA_006358075.1_PDT000521728.1' already exists. Skipping...
Folder 'GCA_006358095.1_PDT000521731.1' already exists. Skipping...
Folder 'GCA_006358115.1_PDT000521733.1' already exists. Skipping...
Folder 'GCA_006358135.1_PDT000521808.1' already exists. Skipping...
Folder 'GCA_006358155.1_PDT000521735.1' already exists. Skipping...
Folder 'GCA_006358215.1_PDT000521740.1' already exists. Skipping...
Folder 'GCA_006358275.1_PDT000521737.1' already exists. Skipping...
Folder 'GCA_006358295.1_PDT000521739.1' already exists. Skipping...
Folder 'GCA_006358315.1_PDT000521906.1' already exists. Skipping...
Folder 'GCA_006358355.1_PDT000521743.1' already exists. Skipping...
Folder 'GCA_006358375.1_PDT000521738.1' already exists. Skipping...
Folder 'GCA_006358395.1_PDT000521877.1' already exists. Skipping...
Folder 'GCA_006358415.1_PDT000521750.1' already exists. Skipping...
Folder 'GCA_006358435.1_PDT000522528.1' already exists. Skipping...
Folder 'GCA_006358455.1_PDT000521844.1' already exists. Skipping...
Folder 'GCA_006358475.1_PDT000521742.1' already exists. Skipping...
Folder 'GCA_006358515.1_PDT000521746.1' already exists. Skipping...
Folder 'GCA_006358535.1_PDT000521809.1' already exists. Skipping...
Folder 'GCA_006358555.1_PDT000521748.1' already exists. Skipping...
Folder 'GCA_006358595.1_PDT000521741.1' already exists. Skipping...
Folder 'GCA_006358635.1_PDT000521749.1' already exists. Skipping...
Folder 'GCA_006358715.1_PDT000521846.1' already exists. Skipping...
Folder 'GCA_006358795.1_PDT000521759.1' already exists. Skipping...
Folder 'GCA_006358835.1_PDT000521751.1' already exists. Skipping...
Folder 'GCA_006358875.1_PDT000521969.1' already exists. Skipping...
Folder 'GCA_006358895.1_PDT000521762.1' already exists. Skipping...
Folder 'GCA_006358955.1_PDT000521850.1' already exists. Skipping...
Folder 'GCA_006358975.1_PDT000521764.1' already exists. Skipping...
Folder 'GCA_006359015.1_PDT000521805.1' already exists. Skipping...
Folder 'GCA_006359045.1_PDT000521766.1' already exists. Skipping...
Folder 'GCA_006359095.1_PDT000521776.1' already exists. Skipping...
Folder 'GCA_006359135.1_PDT000521790.1' already exists. Skipping...
Folder 'GCA_006359175.1_PDT000521781.1' already exists. Skipping...
Folder 'GCA_006359215.1_PDT000521807.1' already exists. Skipping...
Folder 'GCA_006359235.1_PDT000521782.1' already exists. Skipping...
Folder 'GCA_006359255.1_PDT000521777.1' already exists. Skipping...
Folder 'GCA_006359355.1_PDT000521880.1' already exists. Skipping...
Folder 'GCA_006359375.1_PDT000521784.1' already exists. Skipping...
Folder 'GCA_006359395.1_PDT000522703.1' already exists. Skipping...
Folder 'GCA_006359415.1_PDT000521868.1' already exists. Skipping...
Folder 'GCA_006359435.1_PDT000521827.1' already exists. Skipping...
Folder 'GCA_006359455.1_PDT000521841.1' already exists. Skipping...
Folder 'GCA_006359475.1_PDT000521803.1' already exists. Skipping...
Folder 'GCA_006359495.1_PDT000521856.1' already exists. Skipping...
Folder 'GCA_006359535.1_PDT000521839.1' already exists. Skipping...
Folder 'GCA_006359555.1_PDT000521854.1' already exists. Skipping...
Folder 'GCA_006359635.1_PDT000521828.1' already exists. Skipping...
Folder 'GCA_006359715.1_PDT000521824.1' already exists. Skipping...
Folder 'GCA_006359735.1_PDT000521970.1' already exists. Skipping...
Folder 'GCA_006359795.1_PDT000521884.1' already exists. Skipping...
Folder 'GCA_006359815.1_PDT000521799.1' already exists. Skipping...
Folder 'GCA_006359855.1_PDT000521820.1' already exists. Skipping...
Folder 'GCA_006359895.1_PDT000521883.1' already exists. Skipping...
Folder 'GCA_006359915.1_PDT000521830.1' already exists. Skipping...
Folder 'GCA_006359935.1_PDT000521825.1' already exists. Skipping...
Folder 'GCA_006359995.1_PDT000521845.1' already exists. Skipping...
Folder 'GCA_006360015.1_PDT000521887.1' already exists. Skipping...
Folder 'GCA_006360055.1_PDT000521795.1' already exists. Skipping...
Folder 'GCA_006360075.1_PDT000522532.1' already exists. Skipping...
Folder 'GCA_006360095.1_PDT000521898.1' already exists. Skipping...
Folder 'GCA_006360115.1_PDT000521788.1' already exists. Skipping...
Folder 'GCA_006360135.1_PDT000521842.1' already exists. Skipping...
Folder 'GCA_006360175.1_PDT000521786.1' already exists. Skipping...
Folder 'GCA_006360195.1_PDT000521899.1' already exists. Skipping...
Folder 'GCA_006360215.1_PDT000521873.1' already exists. Skipping...
Folder 'GCA_006360255.1_PDT000521865.1' already exists. Skipping...
Folder 'GCA_006360275.1_PDT000521872.1' already exists. Skipping...
Folder 'GCA_006360355.1_PDT000522712.1' already exists. Skipping...
Folder 'GCA_006360395.1_PDT000521826.1' already exists. Skipping...
Folder 'GCA_006360415.1_PDT000521886.1' already exists. Skipping...
Folder 'GCA_006360425.1_PDT000521796.1' already exists. Skipping...
Folder 'GCA_006360455.1_PDT000521904.1' already exists. Skipping...
Folder 'GCA_006360515.1_PDT000521890.1' already exists. Skipping...
Folder 'GCA_006360555.1_PDT000521797.1' already exists. Skipping...
Folder 'GCA_006360575.1_PDT000522707.1' already exists. Skipping...
Folder 'GCA_006360595.1_PDT000521831.1' already exists. Skipping...
Folder 'GCA_006360615.1_PDT000521837.1' already exists. Skipping...
Folder 'GCA_006360655.1_PDT000522690.1' already exists. Skipping...
Folder 'GCA_006360675.1_PDT000521966.1' already exists. Skipping...
Folder 'GCA_006360735.1_PDT000521893.1' already exists. Skipping...
Folder 'GCA_006360775.1_PDT000521819.1' already exists. Skipping...
Folder 'GCA_006360785.1_PDT000521871.1' already exists. Skipping...
Folder 'GCA_006360815.1_PDT000521891.1' already exists. Skipping...
Folder 'GCA_006360835.1_PDT000521878.1' already exists. Skipping...
Folder 'GCA_006360855.1_PDT000522704.1' already exists. Skipping...
Folder 'GCA_006360875.1_PDT000521829.1' already exists. Skipping...
Folder 'GCA_006360895.1_PDT000521895.1' already exists. Skipping...
Folder 'GCA_006360995.1_PDT000521924.1' already exists. Skipping...
Folder 'GCA_006361035.1_PDT000521905.1' already exists. Skipping...

Retreiveing data: 55003it [00:09, 6607.95it/s]

Folder 'GCA_007892645.1_PDT000554226.1' already exists. Skipping...
Folder 'GCA_007892665.1_PDT000554235.1' already exists. Skipping...
Folder 'GCA_007892675.1_PDT000554233.1' already exists. Skipping...
Folder 'GCA_007892775.1_PDT000554237.1' already exists. Skipping...
Folder 'GCA_007892825.1_PDT000554236.1' already exists. Skipping...
Folder 'GCA_007892845.1_PDT000554239.1' already exists. Skipping...
Folder 'GCA_007892865.1_PDT000554243.1' already exists. Skipping...
Folder 'GCA_007892925.1_PDT000554241.1' already exists. Skipping...
Folder 'GCA_007893125.1_PDT000552783.1' already exists. Skipping...
Folder 'GCA_007893205.1_PDT000552782.1' already exists. Skipping...
Folder 'GCA_007893305.1_PDT000552779.1' already exists. Skipping...
Folder 'GCA_007893405.1_PDT000552836.1' already exists. Skipping...
Folder 'GCA_007893425.1_PDT000552784.1' already exists. Skipping...
Folder 'GCA_007893485.1_PDT000552837.1' already exists. Skipping...
Folder 'GCA_007893565.1_PDT000552781.1' already exists. Skipping...
Folder 'GCA_007893585.1_PDT000552778.1' already exists. Skipping...
Folder 'GCA_007893645.1_PDT000554247.1' already exists. Skipping...
Folder 'GCA_007893705.1_PDT000552841.1' already exists. Skipping...
Folder 'GCA_007893725.1_PDT000552839.1' already exists. Skipping...
Folder 'GCA_007893845.1_PDT000552843.1' already exists. Skipping...
Folder 'GCA_007893865.1_PDT000554259.1' already exists. Skipping...
Folder 'GCA_007893925.1_PDT000554261.1' already exists. Skipping...
Folder 'GCA_007893965.1_PDT000554258.1' already exists. Skipping...
Folder 'GCA_007895025.1_PDT000552771.1' already exists. Skipping...
Folder 'GCA_007895045.1_PDT000552767.1' already exists. Skipping...
Folder 'GCA_007895145.1_PDT000552766.1' already exists. Skipping...
Folder 'GCA_007895165.1_PDT000552770.1' already exists. Skipping...
Folder 'GCA_007895205.1_PDT000552774.1' already exists. Skipping...
Folder 'GCA_007895225.1_PDT000552772.1' already exists. Skipping...
Folder 'GCA_007895245.1_PDT000552768.1' already exists. Skipping...
Folder 'GCA_007895265.1_PDT000552776.1' already exists. Skipping...
Folder 'GCA_007895285.1_PDT000552773.1' already exists. Skipping...
Folder 'GCA_007895305.1_PDT000552785.1' already exists. Skipping...
Folder 'GCA_007895325.1_PDT000552777.1' already exists. Skipping...
Folder 'GCA_007895365.1_PDT000552787.1' already exists. Skipping...
Folder 'GCA_007895385.1_PDT000552791.1' already exists. Skipping...
Folder 'GCA_007895425.1_PDT000552797.1' already exists. Skipping...
Folder 'GCA_007895435.1_PDT000552790.1' already exists. Skipping...
Folder 'GCA_007895465.1_PDT000552796.1' already exists. Skipping...
Folder 'GCA_007895485.1_PDT000552792.1' already exists. Skipping...
Folder 'GCA_007895525.1_PDT000552798.1' already exists. Skipping...
Folder 'GCA_007895545.1_PDT000552800.1' already exists. Skipping...
Folder 'GCA_007895565.1_PDT000552794.1' already exists. Skipping...
Folder 'GCA_007895585.1_PDT000552788.1' already exists. Skipping...
Folder 'GCA_007895605.1_PDT000552801.1' already exists. Skipping...
Folder 'GCA_007895625.1_PDT000552807.1' already exists. Skipping...
Folder 'GCA_007895645.1_PDT000552806.1' already exists. Skipping...
Folder 'GCA_007895685.1_PDT000552803.1' already exists. Skipping...
Folder 'GCA_007895725.1_PDT000552799.1' already exists. Skipping...
Folder 'GCA_007895735.1_PDT000552808.1' already exists. Skipping...
Folder 'GCA_007895765.1_PDT000552805.1' already exists. Skipping...
Folder 'GCA_007895825.1_PDT000552813.1' already exists. Skipping...
Folder 'GCA_007895845.1_PDT000552810.1' already exists. Skipping...
Folder 'GCA_007895865.1_PDT000552815.1' already exists. Skipping...
Folder 'GCA_007895875.1_PDT000552812.1' already exists. Skipping...
Folder 'GCA_007895905.1_PDT000552814.1' already exists. Skipping...
Folder 'GCA_007895925.1_PDT000552816.1' already exists. Skipping...
Folder 'GCA_007895945.1_PDT000552819.1' already exists. Skipping...
Folder 'GCA_007895985.1_PDT000552821.1' already exists. Skipping...
Folder 'GCA_007896025.1_PDT000552824.1' already exists. Skipping...
Folder 'GCA_007896045.1_PDT000552825.1' already exists. Skipping...
Folder 'GCA_007896065.1_PDT000552823.1' already exists. Skipping...
Folder 'GCA_007896075.1_PDT000552820.1' already exists. Skipping...
Folder 'GCA_007896105.1_PDT000552827.1' already exists. Skipping...
Folder 'GCA_007896115.1_PDT000552822.1' already exists. Skipping...
Folder 'GCA_007896145.1_PDT000552828.1' already exists. Skipping...
Folder 'GCA_007896185.1_PDT000552829.1' already exists. Skipping...
Folder 'GCA_007896205.1_PDT000552832.1' already exists. Skipping...
Folder 'GCA_007896225.1_PDT000552830.1' already exists. Skipping...
Folder 'GCA_007896245.1_PDT000552840.1' already exists. Skipping...
Folder 'GCA_007896265.1_PDT000552833.1' already exists. Skipping...
Folder 'GCA_007896285.1_PDT000552834.1' already exists. Skipping...
Folder 'GCA_007896295.1_PDT000552835.1' already exists. Skipping...
Folder 'GCA_007896325.1_PDT000552844.1' already exists. Skipping...
Folder 'GCA_007896345.1_PDT000552847.1' already exists. Skipping...
Folder 'GCA_007896365.1_PDT000552846.1' already exists. Skipping...
Folder 'GCA_007896385.1_PDT000552848.1' already exists. Skipping...
Folder 'GCA_007896405.1_PDT000552845.1' already exists. Skipping...
Folder 'GCA_007897205.1_PDT000552982.1' already exists. Skipping...
Folder 'GCA_007897225.1_PDT000553077.1' already exists. Skipping...
Folder 'GCA_007897245.1_PDT000552849.1' already exists. Skipping...
Folder 'GCA_007897265.1_PDT000552851.1' already exists. Skipping...
Folder 'GCA_007897285.1_PDT000552852.1' already exists. Skipping...
Folder 'GCA_007897305.1_PDT000552856.1' already exists. Skipping...
Folder 'GCA_007897325.1_PDT000552929.1' already exists. Skipping...
Folder 'GCA_007897365.1_PDT000552850.1' already exists. Skipping...
Folder 'GCA_007897405.1_PDT000552854.1' already exists. Skipping...
Folder 'GCA_007897445.1_PDT000552884.1' already exists. Skipping...
Folder 'GCA_007897465.1_PDT000552861.1' already exists. Skipping...
Folder 'GCA_007897485.1_PDT000552882.1' already exists. Skipping...
Folder 'GCA_007897525.1_PDT000552859.1' already exists. Skipping...
Folder 'GCA_007897565.1_PDT000552885.1' already exists. Skipping...
Folder 'GCA_007897635.1_PDT000552864.1' already exists. Skipping...
Folder 'GCA_007897665.1_PDT000552866.1' already exists. Skipping...
Folder 'GCA_007897685.1_PDT000552865.1' already exists. Skipping...
Folder 'GCA_007897705.1_PDT000552867.1' already exists. Skipping...
Folder 'GCA_007897725.1_PDT000552874.1' already exists. Skipping...
Folder 'GCA_007897785.1_PDT000552871.1' already exists. Skipping...
Folder 'GCA_007897805.1_PDT000552872.1' already exists. Skipping...
Folder 'GCA_007897845.1_PDT000552936.1' already exists. Skipping...
Folder 'GCA_007897865.1_PDT000552873.1' already exists. Skipping...
Folder 'GCA_007897885.1_PDT000552878.1' already exists. Skipping...
Folder 'GCA_007897905.1_PDT000552877.1' already exists. Skipping...
Folder 'GCA_007897925.1_PDT000552935.1' already exists. Skipping...
Folder 'GCA_007897945.1_PDT000552876.1' already exists. Skipping...
Folder 'GCA_007897965.1_PDT000552879.1' already exists. Skipping...
Folder 'GCA_007897985.1_PDT000552880.1' already exists. Skipping...
Folder 'GCA_007898005.1_PDT000552886.1' already exists. Skipping...
Folder 'GCA_007898045.1_PDT000552893.1' already exists. Skipping...
Folder 'GCA_007898085.1_PDT000552934.1' already exists. Skipping...
Folder 'GCA_007898145.1_PDT000552898.1' already exists. Skipping...
Folder 'GCA_007898165.1_PDT000552903.1' already exists. Skipping...
Folder 'GCA_007898185.1_PDT000552902.1' already exists. Skipping...
Folder 'GCA_007898205.1_PDT000552906.1' already exists. Skipping...
Folder 'GCA_007898245.1_PDT000552905.1' already exists. Skipping...
Folder 'GCA_007898285.1_PDT000552900.1' already exists. Skipping...
Folder 'GCA_007898305.1_PDT000552907.1' already exists. Skipping...
Folder 'GCA_007898325.1_PDT000552901.1' already exists. Skipping...
Folder 'GCA_007898345.1_PDT000552910.1' already exists. Skipping...
Folder 'GCA_007898385.1_PDT000552987.1' already exists. Skipping...
Folder 'GCA_007898405.1_PDT000552904.1' already exists. Skipping...
Folder 'GCA_007898465.1_PDT000552913.1' already exists. Skipping...
Folder 'GCA_007898485.1_PDT000552914.1' already exists. Skipping...
Folder 'GCA_007898505.1_PDT000553074.1' already exists. Skipping...
Folder 'GCA_007898525.1_PDT000552917.1' already exists. Skipping...
Folder 'GCA_007898545.1_PDT000552918.1' already exists. Skipping...
Folder 'GCA_007898625.1_PDT000552920.1' already exists. Skipping...
Folder 'GCA_007898645.1_PDT000552924.1' already exists. Skipping...
Folder 'GCA_007898665.1_PDT000552921.1' already exists. Skipping...
Folder 'GCA_007898675.1_PDT000552919.1' already exists. Skipping...
Folder 'GCA_007898705.1_PDT000552927.1' already exists. Skipping...
Folder 'GCA_007898725.1_PDT000553076.1' already exists. Skipping...
Folder 'GCA_007898805.1_PDT000552938.1' already exists. Skipping...
Folder 'GCA_007898825.1_PDT000552933.1' already exists. Skipping...
Folder 'GCA_007898865.1_PDT000552942.1' already exists. Skipping...
Folder 'GCA_007898885.1_PDT000552941.1' already exists. Skipping...
Folder 'GCA_007898905.1_PDT000552944.1' already exists. Skipping...
Folder 'GCA_007898925.1_PDT000552937.1' already exists. Skipping...
Folder 'GCA_007898945.1_PDT000552946.1' already exists. Skipping...
Folder 'GCA_007898985.1_PDT000552943.1' already exists. Skipping...
Folder 'GCA_007899005.1_PDT000552945.1' already exists. Skipping...
Folder 'GCA_007899025.1_PDT000552953.1' already exists. Skipping...
Folder 'GCA_007899055.1_PDT000552950.1' already exists. Skipping...
Folder 'GCA_007899085.1_PDT000552949.1' already exists. Skipping...
Folder 'GCA_007899105.1_PDT000552952.1' already exists. Skipping...
Folder 'GCA_007899115.1_PDT000552951.1' already exists. Skipping...
Folder 'GCA_007899135.1_PDT000552957.1' already exists. Skipping...
Folder 'GCA_007899205.1_PDT000552962.1' already exists. Skipping...
Folder 'GCA_007899225.1_PDT000552955.1' already exists. Skipping...
Folder 'GCA_007899245.1_PDT000552959.1' already exists. Skipping...
Folder 'GCA_007899265.1_PDT000552961.1' already exists. Skipping...
Folder 'GCA_007899305.1_PDT000552960.1' already exists. Skipping...
Folder 'GCA_007899325.1_PDT000552964.1' already exists. Skipping...
Folder 'GCA_007899365.1_PDT000552970.1' already exists. Skipping...
Folder 'GCA_007899385.1_PDT000552968.1' already exists. Skipping...
Folder 'GCA_007899405.1_PDT000552965.1' already exists. Skipping...
Folder 'GCA_007899425.1_PDT000552966.1' already exists. Skipping...
Folder 'GCA_007899445.1_PDT000552967.1' already exists. Skipping...
Folder 'GCA_007899465.1_PDT000552972.1' already exists. Skipping...
Folder 'GCA_007899485.1_PDT000552974.1' already exists. Skipping...
Folder 'GCA_007899525.1_PDT000552980.1' already exists. Skipping...
Folder 'GCA_007899545.1_PDT000552977.1' already exists. Skipping...
Folder 'GCA_007899565.1_PDT000552976.1' already exists. Skipping...
Folder 'GCA_007899585.1_PDT000552978.1' already exists. Skipping...
Folder 'GCA_007899605.1_PDT000552981.1' already exists. Skipping...
Folder 'GCA_007899625.1_PDT000552998.1' already exists. Skipping...
Folder 'GCA_007899635.1_PDT000552993.1' already exists. Skipping...
Folder 'GCA_007899665.1_PDT000552979.1' already exists. Skipping...
Folder 'GCA_007899685.1_PDT000552992.1' already exists. Skipping...
Folder 'GCA_007899705.1_PDT000552995.1' already exists. Skipping...
Folder 'GCA_007899725.1_PDT000552989.1' already exists. Skipping...
Folder 'GCA_007899765.1_PDT000552990.1' already exists. Skipping...
Folder 'GCA_007899785.1_PDT000552991.1' already exists. Skipping...
Folder 'GCA_007899805.1_PDT000553046.1' already exists. Skipping...
Folder 'GCA_007899825.1_PDT000552895.1' already exists. Skipping...
Folder 'GCA_007899845.1_PDT000552983.1' already exists. Skipping...
Folder 'GCA_007899865.1_PDT000552988.1' already exists. Skipping...
Folder 'GCA_007899885.1_PDT000553075.1' already exists. Skipping...
Folder 'GCA_007899925.1_PDT000552891.1' already exists. Skipping...
Folder 'GCA_007899945.1_PDT000552896.1' already exists. Skipping...
Folder 'GCA_007899965.1_PDT000552892.1' already exists. Skipping...
Folder 'GCA_007899985.1_PDT000552986.1' already exists. Skipping...
Folder 'GCA_007900005.1_PDT000552887.1' already exists. Skipping...
Folder 'GCA_007900025.1_PDT000552984.1' already exists. Skipping...
Folder 'GCA_007900045.1_PDT000553071.1' already exists. Skipping...
Folder 'GCA_007900065.1_PDT000552899.1' already exists. Skipping...
Folder 'GCA_007900105.1_PDT000552897.1' already exists. Skipping...
Folder 'GCA_007900145.1_PDT000553081.1' already exists. Skipping...
Folder 'GCA_007900165.1_PDT000553072.1' already exists. Skipping...
Folder 'GCA_007900185.1_PDT000553069.1' already exists. Skipping...
Folder 'GCA_007900225.1_PDT000553082.1' already exists. Skipping...
Folder 'GCA_007900245.1_PDT000553068.1' already exists. Skipping...
Folder 'GCA_007900265.1_PDT000553083.1' already exists. Skipping...
Folder 'GCA_007900285.1_PDT000553034.1' already exists. Skipping...
Folder 'GCA_007900295.1_PDT000553619.1' already exists. Skipping...
Folder 'GCA_007900345.1_PDT000553622.1' already exists. Skipping...
Folder 'GCA_007900365.1_PDT000553033.1' already exists. Skipping...
Folder 'GCA_007900385.1_PDT000553040.1' already exists. Skipping...
Folder 'GCA_007900405.1_PDT000553618.1' already exists. Skipping...
Folder 'GCA_007900425.1_PDT000553623.1' already exists. Skipping...
Folder 'GCA_007900465.1_PDT000553621.1' already exists. Skipping...
Folder 'GCA_007900505.1_PDT000553620.1' already exists. Skipping...
Folder 'GCA_007900525.1_PDT000553003.1' already exists. Skipping...
Folder 'GCA_007900545.1_PDT000553002.1' already exists. Skipping...
Folder 'GCA_007900565.1_PDT000553000.1' already exists. Skipping...
Folder 'GCA_007900605.1_PDT000552994.1' already exists. Skipping...
Folder 'GCA_007900665.1_PDT000553008.1' already exists. Skipping...
Folder 'GCA_007900685.1_PDT000553004.1' already exists. Skipping...
Folder 'GCA_007900705.1_PDT000553007.1' already exists. Skipping...
Folder 'GCA_007900725.1_PDT000553005.1' already exists. Skipping...
Folder 'GCA_007900745.1_PDT000553006.1' already exists. Skipping...
Folder 'GCA_007900765.1_PDT000553010.1' already exists. Skipping...
Folder 'GCA_007900775.1_PDT000553009.1' already exists. Skipping...
Folder 'GCA_007900805.1_PDT000553012.1' already exists. Skipping...
Folder 'GCA_007900825.1_PDT000553011.1' already exists. Skipping...
Folder 'GCA_007900845.1_PDT000553014.1' already exists. Skipping...
Folder 'GCA_007900865.1_PDT000553013.1' already exists. Skipping...
Folder 'GCA_007900875.1_PDT000553017.1' already exists. Skipping...
Folder 'GCA_007900885.1_PDT000553015.1' already exists. Skipping...
Folder 'GCA_007900945.1_PDT000553018.1' already exists. Skipping...
Folder 'GCA_007900965.1_PDT000553020.1' already exists. Skipping...
Folder 'GCA_007900975.1_PDT000553019.1' already exists. Skipping...
Folder 'GCA_007901025.1_PDT000553022.1' already exists. Skipping...
Folder 'GCA_007901045.1_PDT000553025.1' already exists. Skipping...
Folder 'GCA_007901065.1_PDT000553026.1' already exists. Skipping...
Folder 'GCA_007901105.1_PDT000553024.1' already exists. Skipping...
Folder 'GCA_007901125.1_PDT000553028.1' already exists. Skipping...
Folder 'GCA_007901165.1_PDT000553027.1' already exists. Skipping...
Folder 'GCA_007901185.1_PDT000553029.1' already exists. Skipping...
Folder 'GCA_007901205.1_PDT000553032.1' already exists. Skipping...
Folder 'GCA_007901225.1_PDT000553030.1' already exists. Skipping...
Folder 'GCA_007901265.1_PDT000553043.1' already exists. Skipping...
Folder 'GCA_007901285.1_PDT000553041.1' already exists. Skipping...
Folder 'GCA_007901305.1_PDT000553042.1' already exists. Skipping...
Folder 'GCA_007901325.1_PDT000553051.1' already exists. Skipping...
Folder 'GCA_007901345.1_PDT000553045.1' already exists. Skipping...
Folder 'GCA_007901365.1_PDT000553049.1' already exists. Skipping...
Folder 'GCA_007901385.1_PDT000553047.1' already exists. Skipping...
Folder 'GCA_007901405.1_PDT000553044.1' already exists. Skipping...
Folder 'GCA_007901425.1_PDT000553053.1' already exists. Skipping...
Folder 'GCA_007901435.1_PDT000553050.1' already exists. Skipping...
Folder 'GCA_007901465.1_PDT000553059.1' already exists. Skipping...
Folder 'GCA_007901485.1_PDT000553037.1' already exists. Skipping...
Folder 'GCA_007901505.1_PDT000553054.1' already exists. Skipping...
Folder 'GCA_007901525.1_PDT000553060.1' already exists. Skipping...
Folder 'GCA_007901545.1_PDT000553627.1' already exists. Skipping...
Folder 'GCA_007901565.1_PDT000553036.1' already exists. Skipping...
Folder 'GCA_007901585.1_PDT000553055.1' already exists. Skipping...
Folder 'GCA_007901605.1_PDT000553056.1' already exists. Skipping...
Folder 'GCA_007901625.1_PDT000553052.1' already exists. Skipping...
Folder 'GCA_007901645.1_PDT000553058.1' already exists. Skipping...
Folder 'GCA_007901665.1_PDT000553048.1' already exists. Skipping...
Folder 'GCA_007901685.1_PDT000553057.1' already exists. Skipping...
Folder 'GCA_007901705.1_PDT000553061.1' already exists. Skipping...
Folder 'GCA_007901725.1_PDT000553062.1' already exists. Skipping...
Folder 'GCA_007901745.1_PDT000553065.1' already exists. Skipping...
Folder 'GCA_007901765.1_PDT000553064.1' already exists. Skipping...
Folder 'GCA_007901785.1_PDT000553067.1' already exists. Skipping...
Folder 'GCA_007901805.1_PDT000553063.1' already exists. Skipping...
Folder 'GCA_007901845.1_PDT000553088.1' already exists. Skipping...
Folder 'GCA_007901865.1_PDT000553078.1' already exists. Skipping...
Folder 'GCA_007901905.1_PDT000553089.1' already exists. Skipping...
Folder 'GCA_007901925.1_PDT000553092.1' already exists. Skipping...
Folder 'GCA_007901965.1_PDT000553085.1' already exists. Skipping...
Folder 'GCA_007901985.1_PDT000553091.1' already exists. Skipping...
Folder 'GCA_007902025.1_PDT000553087.1' already exists. Skipping...
Folder 'GCA_007902045.1_PDT000553084.1' already exists. Skipping...
Folder 'GCA_007902065.1_PDT000553094.1' already exists. Skipping...
Folder 'GCA_007902085.1_PDT000553095.1' already exists. Skipping...
Folder 'GCA_007902125.1_PDT000553097.1' already exists. Skipping...
Folder 'GCA_007902145.1_PDT000553100.1' already exists. Skipping...
Folder 'GCA_007902165.1_PDT000553099.1' already exists. Skipping...
Folder 'GCA_007902185.1_PDT000553101.1' already exists. Skipping...
Folder 'GCA_007902205.1_PDT000553098.1' already exists. Skipping...
Folder 'GCA_007902225.1_PDT000553104.1' already exists. Skipping...
Folder 'GCA_007902245.1_PDT000553102.1' already exists. Skipping...
Folder 'GCA_007902265.1_PDT000553106.1' already exists. Skipping...
Folder 'GCA_007902285.1_PDT000553103.1' already exists. Skipping...
Folder 'GCA_007902305.1_PDT000553105.1' already exists. Skipping...
Folder 'GCA_007902365.1_PDT000553602.1' already exists. Skipping...
Folder 'GCA_007902385.1_PDT000553603.1' already exists. Skipping...
Folder 'GCA_007902425.1_PDT000553609.1' already exists. Skipping...
Folder 'GCA_007902465.1_PDT000553611.1' already exists. Skipping...
Folder 'GCA_007902485.1_PDT000553610.1' already exists. Skipping...
Folder 'GCA_007902505.1_PDT000553626.1' already exists. Skipping...
Folder 'GCA_007902535.1_PDT000553614.1' already exists. Skipping...
Folder 'GCA_007902585.1_PDT000553632.1' already exists. Skipping...
Folder 'GCA_007902605.1_PDT000553639.1' already exists. Skipping...
Folder 'GCA_007902625.1_PDT000553636.1' already exists. Skipping...
Folder 'GCA_007902645.1_PDT000553637.1' already exists. Skipping...
Folder 'GCA_007902665.1_PDT000553638.1' already exists. Skipping...
Folder 'GCA_007902675.1_PDT000553633.1' already exists. Skipping...
Folder 'GCA_007902705.1_PDT000553629.1' already exists. Skipping...
Folder 'GCA_007902725.1_PDT000553635.1' already exists. Skipping...

Retreiveing data: 56337it [00:09, 6642.53it/s]

Folder 'GCA_007943325.1_PDT000555178.1' already exists. Skipping...
Folder 'GCA_007943345.1_PDT000555169.1' already exists. Skipping...
Folder 'GCA_007943365.1_PDT000555123.1' already exists. Skipping...
Folder 'GCA_007943385.1_PDT000555179.1' already exists. Skipping...
Folder 'GCA_007943425.1_PDT000555182.1' already exists. Skipping...
Folder 'GCA_007943435.1_PDT000555180.1' already exists. Skipping...
Folder 'GCA_007943465.1_PDT000555185.1' already exists. Skipping...
Folder 'GCA_007943485.1_PDT000555183.1' already exists. Skipping...
Folder 'GCA_007943505.1_PDT000555187.1' already exists. Skipping...
Folder 'GCA_007943545.1_PDT000555184.1' already exists. Skipping...
Folder 'GCA_007943565.1_PDT000555186.1' already exists. Skipping...
Folder 'GCA_007943575.1_PDT000555188.1' already exists. Skipping...
Folder 'GCA_007943605.1_PDT000555199.1' already exists. Skipping...
Folder 'GCA_007943625.1_PDT000555189.1' already exists. Skipping...
Folder 'GCA_007943645.1_PDT000555201.1' already exists. Skipping...
Folder 'GCA_007943665.1_PDT000555207.1' already exists. Skipping...
Folder 'GCA_007943685.1_PDT000555198.1' already exists. Skipping...
Folder 'GCA_007943705.1_PDT000555190.1' already exists. Skipping...
Folder 'GCA_007943725.1_PDT000555211.1' already exists. Skipping...
Folder 'GCA_007943745.1_PDT000555200.1' already exists. Skipping...
Folder 'GCA_007943765.1_PDT000555208.1' already exists. Skipping...
Folder 'GCA_007943785.1_PDT000555203.1' already exists. Skipping...
Folder 'GCA_007943805.1_PDT000555202.1' already exists. Skipping...
Folder 'GCA_007943845.1_PDT000555216.1' already exists. Skipping...
Folder 'GCA_007943875.1_PDT000555217.1' already exists. Skipping...
Folder 'GCA_007943905.1_PDT000555218.1' already exists. Skipping...
Folder 'GCA_007943925.1_PDT000555205.1' already exists. Skipping...
Folder 'GCA_007943945.1_PDT000555220.1' already exists. Skipping...
Folder 'GCA_007943965.1_PDT000555214.1' already exists. Skipping...
Folder 'GCA_007943985.1_PDT000555204.1' already exists. Skipping...
Folder 'GCA_007944005.1_PDT000555209.1' already exists. Skipping...
Folder 'GCA_007944045.1_PDT000555221.1' already exists. Skipping...
Folder 'GCA_007944065.1_PDT000555212.1' already exists. Skipping...
Folder 'GCA_007944085.1_PDT000555222.1' already exists. Skipping...
Folder 'GCA_007944105.1_PDT000555219.1' already exists. Skipping...
Folder 'GCA_007944125.1_PDT000555226.1' already exists. Skipping...
Folder 'GCA_007944145.1_PDT000555224.1' already exists. Skipping...
Folder 'GCA_007944165.1_PDT000555225.1' already exists. Skipping...
Folder 'GCA_007944185.1_PDT000555227.1' already exists. Skipping...
Folder 'GCA_007944205.1_PDT000555229.1' already exists. Skipping...
Folder 'GCA_007944225.1_PDT000555232.1' already exists. Skipping...
Folder 'GCA_007944245.1_PDT000555228.1' already exists. Skipping...
Folder 'GCA_007944285.1_PDT000555230.1' already exists. Skipping...
Folder 'GCA_007944305.1_PDT000555234.1' already exists. Skipping...
Folder 'GCA_007944345.1_PDT000555324.1' already exists. Skipping...
Folder 'GCA_007944365.1_PDT000555327.1' already exists. Skipping...
Folder 'GCA_007944375.1_PDT000555330.1' already exists. Skipping...
Folder 'GCA_007944405.1_PDT000555336.1' already exists. Skipping...
Folder 'GCA_007944425.1_PDT000555328.1' already exists. Skipping...
Folder 'GCA_007944465.1_PDT000555339.1' already exists. Skipping...
Folder 'GCA_007944485.1_PDT000555342.1' already exists. Skipping...
Folder 'GCA_007944525.1_PDT000555352.1' already exists. Skipping...
Folder 'GCA_007944545.1_PDT000555345.1' already exists. Skipping...
Folder 'GCA_007944565.1_PDT000555346.1' already exists. Skipping...
Folder 'GCA_007944585.1_PDT000554969.1' already exists. Skipping...
Folder 'GCA_007944605.1_PDT000554964.1' already exists. Skipping...
Folder 'GCA_007944625.1_PDT000554934.1' already exists. Skipping...
Folder 'GCA_007944645.1_PDT000555196.1' already exists. Skipping...
Folder 'GCA_007944665.1_PDT000554966.1' already exists. Skipping...
Folder 'GCA_007944705.1_PDT000554942.1' already exists. Skipping...
Folder 'GCA_007944725.1_PDT000555192.1' already exists. Skipping...
Folder 'GCA_007944745.1_PDT000555143.1' already exists. Skipping...
Folder 'GCA_007944765.1_PDT000554963.1' already exists. Skipping...
Folder 'GCA_007944785.1_PDT000555145.1' already exists. Skipping...
Folder 'GCA_007944805.1_PDT000554954.1' already exists. Skipping...
Folder 'GCA_007944845.1_PDT000554937.1' already exists. Skipping...
Folder 'GCA_007944865.1_PDT000555170.1' already exists. Skipping...
Folder 'GCA_007944885.1_PDT000554939.1' already exists. Skipping...
Folder 'GCA_007944925.1_PDT000555150.1' already exists. Skipping...
Folder 'GCA_007944945.1_PDT000555130.1' already exists. Skipping...
Folder 'GCA_007944965.1_PDT000555144.1' already exists. Skipping...
Folder 'GCA_007945005.1_PDT000554947.1' already exists. Skipping...
Folder 'GCA_007945025.1_PDT000555153.1' already exists. Skipping...
Folder 'GCA_007945045.1_PDT000554957.1' already exists. Skipping...
Folder 'GCA_007945065.1_PDT000555157.1' already exists. Skipping...
Folder 'GCA_007945085.1_PDT000554949.1' already exists. Skipping...
Folder 'GCA_007945125.1_PDT000554950.1' already exists. Skipping...
Folder 'GCA_007945145.1_PDT000554931.1' already exists. Skipping...
Folder 'GCA_007945165.1_PDT000554930.1' already exists. Skipping...
Folder 'GCA_007945175.1_PDT000555122.1' already exists. Skipping...
Folder 'GCA_007945205.1_PDT000554965.1' already exists. Skipping...
Folder 'GCA_007945245.1_PDT000555125.1' already exists. Skipping...
Folder 'GCA_007945255.1_PDT000554951.1' already exists. Skipping...
Folder 'GCA_007945305.1_PDT000555348.1' already exists. Skipping...
Folder 'GCA_007945325.1_PDT000555148.1' already exists. Skipping...
Folder 'GCA_007945345.1_PDT000555151.1' already exists. Skipping...
Folder 'GCA_007945365.1_PDT000555197.1' already exists. Skipping...
Folder 'GCA_007945385.1_PDT000554968.1' already exists. Skipping...
Folder 'GCA_007945405.1_PDT000555160.1' already exists. Skipping...
Folder 'GCA_007945425.1_PDT000555349.1' already exists. Skipping...
Folder 'GCA_007945445.1_PDT000555311.1' already exists. Skipping...
Folder 'GCA_007945465.1_PDT000555309.1' already exists. Skipping...
Folder 'GCA_007945485.1_PDT000555278.1' already exists. Skipping...
Folder 'GCA_007945505.1_PDT000555250.1' already exists. Skipping...
Folder 'GCA_007945565.1_PDT000555243.1' already exists. Skipping...
Folder 'GCA_007945605.1_PDT000555237.1' already exists. Skipping...
Folder 'GCA_007945625.1_PDT000555235.1' already exists. Skipping...
Folder 'GCA_007945645.1_PDT000555238.1' already exists. Skipping...
Folder 'GCA_007945665.1_PDT000555244.1' already exists. Skipping...
Folder 'GCA_007945685.1_PDT000555240.1' already exists. Skipping...
Folder 'GCA_007945705.1_PDT000555242.1' already exists. Skipping...
Folder 'GCA_007945725.1_PDT000555254.1' already exists. Skipping...
Folder 'GCA_007945745.1_PDT000555241.1' already exists. Skipping...
Folder 'GCA_007945765.1_PDT000555256.1' already exists. Skipping...
Folder 'GCA_007945785.1_PDT000555253.1' already exists. Skipping...
Folder 'GCA_007945825.1_PDT000555258.1' already exists. Skipping...
Folder 'GCA_007945845.1_PDT000555257.1' already exists. Skipping...
Folder 'GCA_007945865.1_PDT000555259.1' already exists. Skipping...
Folder 'GCA_007945885.1_PDT000555245.1' already exists. Skipping...
Folder 'GCA_007945905.1_PDT000555255.1' already exists. Skipping...
Folder 'GCA_007945925.1_PDT000555263.1' already exists. Skipping...
Folder 'GCA_007945945.1_PDT000555267.1' already exists. Skipping...
Folder 'GCA_007946005.1_PDT000555246.1' already exists. Skipping...
Folder 'GCA_007946025.1_PDT000555264.1' already exists. Skipping...
Folder 'GCA_007946045.1_PDT000555266.1' already exists. Skipping...
Folder 'GCA_007946065.1_PDT000555265.1' already exists. Skipping...
Folder 'GCA_007946085.1_PDT000555268.1' already exists. Skipping...
Folder 'GCA_007946095.1_PDT000555270.1' already exists. Skipping...
Folder 'GCA_007946145.1_PDT000555271.1' already exists. Skipping...
Folder 'GCA_007946165.1_PDT000555272.1' already exists. Skipping...
Folder 'GCA_007946185.1_PDT000555274.1' already exists. Skipping...
Folder 'GCA_007946205.1_PDT000555276.1' already exists. Skipping...
Folder 'GCA_007946225.1_PDT000555275.1' already exists. Skipping...
Folder 'GCA_007946265.1_PDT000555282.1' already exists. Skipping...
Folder 'GCA_007946285.1_PDT000555285.1' already exists. Skipping...
Folder 'GCA_007946305.1_PDT000555288.1' already exists. Skipping...
Folder 'GCA_007946325.1_PDT000555286.1' already exists. Skipping...
Folder 'GCA_007946345.1_PDT000555280.1' already exists. Skipping...
Folder 'GCA_007946365.1_PDT000555277.1' already exists. Skipping...
Folder 'GCA_007946385.1_PDT000555281.1' already exists. Skipping...
Folder 'GCA_007946405.1_PDT000555291.1' already exists. Skipping...
Folder 'GCA_007946435.1_PDT000555279.1' already exists. Skipping...
Folder 'GCA_007946465.1_PDT000555283.1' already exists. Skipping...
Folder 'GCA_007946525.1_PDT000555295.1' already exists. Skipping...
Folder 'GCA_007946545.1_PDT000555292.1' already exists. Skipping...
Folder 'GCA_007946585.1_PDT000555294.1' already exists. Skipping...
Folder 'GCA_007946605.1_PDT000555299.1' already exists. Skipping...
Folder 'GCA_007946625.1_PDT000555300.1' already exists. Skipping...
Folder 'GCA_007946635.1_PDT000555304.1' already exists. Skipping...
Folder 'GCA_007946665.1_PDT000555298.1' already exists. Skipping...
Folder 'GCA_007946685.1_PDT000555297.1' already exists. Skipping...
Folder 'GCA_007946705.1_PDT000555312.1' already exists. Skipping...
Folder 'GCA_007946725.1_PDT000555302.1' already exists. Skipping...
Folder 'GCA_007946735.1_PDT000555301.1' already exists. Skipping...
Folder 'GCA_007946765.1_PDT000555306.1' already exists. Skipping...
Folder 'GCA_007946785.1_PDT000555314.1' already exists. Skipping...
Folder 'GCA_007946805.1_PDT000555303.1' already exists. Skipping...
Folder 'GCA_007946825.1_PDT000555316.1' already exists. Skipping...
Folder 'GCA_007946845.1_PDT000555313.1' already exists. Skipping...
Folder 'GCA_007946865.1_PDT000555305.1' already exists. Skipping...
Folder 'GCA_007946885.1_PDT000555321.1' already exists. Skipping...
Folder 'GCA_007946905.1_PDT000555315.1' already exists. Skipping...
Folder 'GCA_007946925.1_PDT000555319.1' already exists. Skipping...
Folder 'GCA_007946945.1_PDT000555318.1' already exists. Skipping...
Folder 'GCA_007946965.1_PDT000555317.1' already exists. Skipping...
Folder 'GCA_007946985.1_PDT000555323.1' already exists. Skipping...
Folder 'GCA_007947005.1_PDT000555320.1' already exists. Skipping...
Folder 'GCA_007947025.1_PDT000555325.1' already exists. Skipping...
Folder 'GCA_007947045.1_PDT000555322.1' already exists. Skipping...
Folder 'GCA_007947105.1_PDT000555333.1' already exists. Skipping...
Folder 'GCA_007947125.1_PDT000555334.1' already exists. Skipping...
Folder 'GCA_007947165.1_PDT000555326.1' already exists. Skipping...
Folder 'GCA_007947185.1_PDT000555332.1' already exists. Skipping...
Folder 'GCA_007947205.1_PDT000555338.1' already exists. Skipping...
Folder 'GCA_007947225.1_PDT000555343.1' already exists. Skipping...
Folder 'GCA_007947245.1_PDT000555340.1' already exists. Skipping...
Folder 'GCA_007947265.1_PDT000555344.1' already exists. Skipping...
Folder 'GCA_007947285.1_PDT000555359.1' already exists. Skipping...
Folder 'GCA_007947305.1_PDT000555354.1' already exists. Skipping...
Folder 'GCA_007947325.1_PDT000555353.1' already exists. Skipping...
Folder 'GCA_007947345.1_PDT000555357.1' already exists. Skipping...
Folder 'GCA_007947365.1_PDT000555356.1' already exists. Skipping...
Folder 'GCA_007947385.1_PDT000555360.1' already exists. Skipping...
Folder 'GCA_007947405.1_PDT000555365.1' already exists. Skipping...
Folder 'GCA_007947445.1_PDT000555363.1' already exists. Skipping...
Folder 'GCA_007947485.1_PDT000555358.1' already exists. Skipping...
Folder 'GCA_007947505.1_PDT000555355.1' already exists. Skipping...
Folder 'GCA_007947525.1_PDT000555364.1' already exists. Skipping...
Folder 'GCA_007947545.1_PDT000555362.1' already exists. Skipping...
Folder 'GCA_007947585.1_PDT000555367.1' already exists. Skipping...
Folder 'GCA_007947605.1_PDT000555369.1' already exists. Skipping...
Folder 'GCA_007947625.1_PDT000555366.1' already exists. Skipping...
Folder 'GCA_007947645.1_PDT000555368.1' already exists. Skipping...
Folder 'GCA_007947685.1_PDT000555371.1' already exists. Skipping...
Folder 'GCA_007947725.1_PDT000555372.1' already exists. Skipping...
Folder 'GCA_007947745.1_PDT000555378.1' already exists. Skipping...
Folder 'GCA_007947765.1_PDT000555374.1' already exists. Skipping...
Folder 'GCA_007947785.1_PDT000555377.1' already exists. Skipping...
Folder 'GCA_007947805.1_PDT000555381.1' already exists. Skipping...
Folder 'GCA_007947825.1_PDT000555376.1' already exists. Skipping...
Folder 'GCA_007947845.1_PDT000555380.1' already exists. Skipping...
Folder 'GCA_007947855.1_PDT000555383.1' already exists. Skipping...
Folder 'GCA_007947885.1_PDT000555382.1' already exists. Skipping...
Folder 'GCA_007947905.1_PDT000555273.1' already exists. Skipping...
Folder 'GCA_007947925.1_PDT000555307.1' already exists. Skipping...
Folder 'GCA_007947945.1_PDT000555310.1' already exists. Skipping...
Folder 'GCA_007947965.1_PDT000555248.1' already exists. Skipping...
Folder 'GCA_007947985.1_PDT000555252.1' already exists. Skipping...
Folder 'GCA_007948005.1_PDT000555247.1' already exists. Skipping...
Folder 'GCA_007948025.1_PDT000555249.1' already exists. Skipping...
Folder 'GCA_007948045.1_PDT000555420.1' already exists. Skipping...
Folder 'GCA_007948065.1_PDT000555419.1' already exists. Skipping...
Folder 'GCA_007948105.1_PDT000555427.1' already exists. Skipping...
Folder 'GCA_007948125.1_PDT000555400.1' already exists. Skipping...
Folder 'GCA_007948145.1_PDT000555397.1' already exists. Skipping...
Folder 'GCA_007948165.1_PDT000555421.1' already exists. Skipping...
Folder 'GCA_007948185.1_PDT000555424.1' already exists. Skipping...
Folder 'GCA_007948225.1_PDT000555635.1' already exists. Skipping...
Folder 'GCA_007948245.1_PDT000555396.1' already exists. Skipping...
Folder 'GCA_007948265.1_PDT000555632.1' already exists. Skipping...
Folder 'GCA_007948305.1_PDT000555426.1' already exists. Skipping...
Folder 'GCA_007948345.1_PDT000555423.1' already exists. Skipping...
Folder 'GCA_007948405.1_PDT000555429.1' already exists. Skipping...
Folder 'GCA_007948465.1_PDT000555425.1' already exists. Skipping...
Folder 'GCA_007948505.1_PDT000555407.1' already exists. Skipping...
Folder 'GCA_007948525.1_PDT000555452.1' already exists. Skipping...
Folder 'GCA_007948545.1_PDT000555445.1' already exists. Skipping...
Folder 'GCA_007948585.1_PDT000555414.1' already exists. Skipping...
Folder 'GCA_007948605.1_PDT000555385.1' already exists. Skipping...
Folder 'GCA_007948645.1_PDT000555623.1' already exists. Skipping...
Folder 'GCA_007948665.1_PDT000555406.1' already exists. Skipping...
Folder 'GCA_007948685.1_PDT000555387.1' already exists. Skipping...
Folder 'GCA_007948705.1_PDT000555412.1' already exists. Skipping...
Folder 'GCA_007948725.1_PDT000555392.1' already exists. Skipping...
Folder 'GCA_007948745.1_PDT000555435.1' already exists. Skipping...
Folder 'GCA_007948805.1_PDT000555463.1' already exists. Skipping...
Folder 'GCA_007948815.1_PDT000555413.1' already exists. Skipping...
Folder 'GCA_007948845.1_PDT000555442.1' already exists. Skipping...
Folder 'GCA_007948865.1_PDT000555437.1' already exists. Skipping...
Folder 'GCA_007948885.1_PDT000555430.1' already exists. Skipping...
Folder 'GCA_007948905.1_PDT000555466.1' already exists. Skipping...
Folder 'GCA_007948925.1_PDT000555458.1' already exists. Skipping...
Folder 'GCA_007948965.1_PDT000555462.1' already exists. Skipping...
Folder 'GCA_007948985.1_PDT000555625.1' already exists. Skipping...
Folder 'GCA_007949025.1_PDT000555455.1' already exists. Skipping...
Folder 'GCA_007949045.1_PDT000555432.1' already exists. Skipping...
Folder 'GCA_007949065.1_PDT000555631.1' already exists. Skipping...
Folder 'GCA_007949085.1_PDT000555409.1' already exists. Skipping...
Folder 'GCA_007949105.1_PDT000555459.1' already exists. Skipping...
Folder 'GCA_007949125.1_PDT000555629.1' already exists. Skipping...
Folder 'GCA_007949145.1_PDT000555453.1' already exists. Skipping...
Folder 'GCA_007949165.1_PDT000555451.1' already exists. Skipping...
Folder 'GCA_007949185.1_PDT000555399.1' already exists. Skipping...
Folder 'GCA_007949205.1_PDT000555622.1' already exists. Skipping...
Folder 'GCA_007949245.1_PDT000555630.1' already exists. Skipping...
Folder 'GCA_007949285.1_PDT000555416.1' already exists. Skipping...
Folder 'GCA_007949305.1_PDT000555439.1' already exists. Skipping...
Folder 'GCA_007949325.1_PDT000555403.1' already exists. Skipping...
Folder 'GCA_007949365.1_PDT000555398.1' already exists. Skipping...
Folder 'GCA_007949385.1_PDT000555465.1' already exists. Skipping...
Folder 'GCA_007949405.1_PDT000555433.1' already exists. Skipping...
Folder 'GCA_007949425.1_PDT000555436.1' already exists. Skipping...
Folder 'GCA_007949465.1_PDT000555624.1' already exists. Skipping...
Folder 'GCA_007949485.1_PDT000555449.1' already exists. Skipping...
Folder 'GCA_007949525.1_PDT000555405.1' already exists. Skipping...
Folder 'GCA_007949545.1_PDT000555450.1' already exists. Skipping...
Folder 'GCA_007949565.1_PDT000555434.1' already exists. Skipping...
Folder 'GCA_007949605.1_PDT000555444.1' already exists. Skipping...
Folder 'GCA_007949625.1_PDT000555634.1' already exists. Skipping...
Folder 'GCA_007949645.1_PDT000555393.1' already exists. Skipping...
Folder 'GCA_007949665.1_PDT000555438.1' already exists. Skipping...
Folder 'GCA_007949685.1_PDT000555415.1' already exists. Skipping...
Folder 'GCA_007949705.1_PDT000555464.1' already exists. Skipping...
Folder 'GCA_007949725.1_PDT000555454.1' already exists. Skipping...
Folder 'GCA_007949735.1_PDT000555633.1' already exists. Skipping...
Folder 'GCA_007949765.1_PDT000555447.1' already exists. Skipping...
Folder 'GCA_007949785.1_PDT000555401.1' already exists. Skipping...
Folder 'GCA_007949805.1_PDT000555628.1' already exists. Skipping...
Folder 'GCA_007949825.1_PDT000555640.1' already exists. Skipping...
Folder 'GCA_007949845.1_PDT000555457.1' already exists. Skipping...
Folder 'GCA_007949865.1_PDT000555404.1' already exists. Skipping...
Folder 'GCA_007949885.1_PDT000555411.1' already exists. Skipping...
Folder 'GCA_007950105.1_PDT000555448.1' already exists. Skipping...
Folder 'GCA_007950145.1_PDT000555402.1' already exists. Skipping...
Folder 'GCA_007950165.1_PDT000555417.1' already exists. Skipping...
Folder 'GCA_007950185.1_PDT000555446.1' already exists. Skipping...
Folder 'GCA_007950205.1_PDT000555440.1' already exists. Skipping...
Folder 'GCA_007950225.1_PDT000555636.1' already exists. Skipping...
Folder 'GCA_007950245.1_PDT000555627.1' already exists. Skipping...
Folder 'GCA_007950265.1_PDT000555384.1' already exists. Skipping...
Folder 'GCA_007950285.1_PDT000555394.1' already exists. Skipping...
Folder 'GCA_007950305.1_PDT000555752.1' already exists. Skipping...
Folder 'GCA_007950405.1_PDT000555765.1' already exists. Skipping...
Folder 'GCA_007950425.1_PDT000555760.1' already exists. Skipping...
Folder 'GCA_007951035.1_PDT000555727.1' already exists. Skipping...
Folder 'GCA_007951125.1_PDT000555734.1' already exists. Skipping...
Folder 'GCA_007951285.1_PDT000555775.1' already exists. Skipping...
Folder 'GCA_007951305.1_PDT000555750.1' already exists. Skipping...
Folder 'GCA_007951325.1_PDT000555777.1' already exists. Skipping...
Folder 'GCA_007951385.1_PDT000555755.1' already exists. Skipping...
Folder 'GCA_007951405.1_PDT000555770.1' already exists. Skipping...
Folder 'GCA_007951485.1_PDT000555774.1' already exists. Skipping...
Folder 'GCA_007951545.1_PDT000555788.1' already exists. Skipping...
Folder 'GCA_007951565.1_PDT000555792.1' already exists. Skipping...

Retreiveing data: 57664it [00:10, 6611.65it/s]

Folder 'GCA_008134965.1_PDT000569211.1' already exists. Skipping...
Folder 'GCA_008134985.1_PDT000569212.1' already exists. Skipping...
Folder 'GCA_008135005.1_PDT000569225.1' already exists. Skipping...
Folder 'GCA_008135045.1_PDT000569233.1' already exists. Skipping...
Folder 'GCA_008135055.1_PDT000569236.1' already exists. Skipping...
Folder 'GCA_008135085.1_PDT000569230.1' already exists. Skipping...
Folder 'GCA_008135105.1_PDT000569258.1' already exists. Skipping...
Folder 'GCA_008135125.1_PDT000569220.1' already exists. Skipping...
Folder 'GCA_008135145.1_PDT000569275.1' already exists. Skipping...
Folder 'GCA_008135165.1_PDT000569252.1' already exists. Skipping...
Folder 'GCA_008135185.1_PDT000569273.1' already exists. Skipping...
Folder 'GCA_008135205.1_PDT000569282.1' already exists. Skipping...
Folder 'GCA_008135225.1_PDT000569278.1' already exists. Skipping...
Folder 'GCA_008135245.1_PDT000569305.1' already exists. Skipping...
Folder 'GCA_008135265.1_PDT000569285.1' already exists. Skipping...
Folder 'GCA_008135285.1_PDT000569283.1' already exists. Skipping...
Folder 'GCA_008135345.1_PDT000569292.1' already exists. Skipping...
Folder 'GCA_008135365.1_PDT000569313.1' already exists. Skipping...
Folder 'GCA_008135385.1_PDT000569288.1' already exists. Skipping...
Folder 'GCA_008135405.1_PDT000569318.1' already exists. Skipping...
Folder 'GCA_008135425.1_PDT000569312.1' already exists. Skipping...
Folder 'GCA_008135445.1_PDT000569310.1' already exists. Skipping...
Folder 'GCA_008135465.1_PDT000569315.1' already exists. Skipping...
Folder 'GCA_008135485.1_PDT000569317.1' already exists. Skipping...
Folder 'GCA_008135505.1_PDT000569314.1' already exists. Skipping...
Folder 'GCA_008135525.1_PDT000569320.1' already exists. Skipping...
Folder 'GCA_008135565.1_PDT000569802.1' already exists. Skipping...
Folder 'GCA_008135585.1_PDT000569319.1' already exists. Skipping...
Folder 'GCA_008135605.1_PDT000569804.1' already exists. Skipping...
Folder 'GCA_008135645.1_PDT000569807.1' already exists. Skipping...
Folder 'GCA_008135685.1_PDT000569297.1' already exists. Skipping...
Folder 'GCA_008135705.1_PDT000569293.1' already exists. Skipping...
Folder 'GCA_008135725.1_PDT000569294.1' already exists. Skipping...
Folder 'GCA_008135745.1_PDT000569304.1' already exists. Skipping...
Folder 'GCA_008135765.1_PDT000569302.1' already exists. Skipping...
Folder 'GCA_008135785.1_PDT000569307.1' already exists. Skipping...
Folder 'GCA_008135805.1_PDT000569303.1' already exists. Skipping...
Folder 'GCA_008135825.1_PDT000569309.1' already exists. Skipping...
Folder 'GCA_008135845.1_PDT000569308.1' already exists. Skipping...
Folder 'GCA_008135865.1_PDT000569295.1' already exists. Skipping...
Folder 'GCA_008135885.1_PDT000569808.1' already exists. Skipping...
Folder 'GCA_008135905.1_PDT000569817.1' already exists. Skipping...
Folder 'GCA_008135925.1_PDT000569814.1' already exists. Skipping...
Folder 'GCA_008135945.1_PDT000569810.1' already exists. Skipping...
Folder 'GCA_008135965.1_PDT000569813.1' already exists. Skipping...
Folder 'GCA_008136045.1_PDT000569815.1' already exists. Skipping...
Folder 'GCA_008136065.1_PDT000569820.1' already exists. Skipping...
Folder 'GCA_008136085.1_PDT000569821.1' already exists. Skipping...
Folder 'GCA_008136125.1_PDT000569824.1' already exists. Skipping...
Folder 'GCA_008136145.1_PDT000569827.1' already exists. Skipping...
Folder 'GCA_008136165.1_PDT000569822.1' already exists. Skipping...
Folder 'GCA_008136185.1_PDT000569826.1' already exists. Skipping...
Folder 'GCA_008136205.1_PDT000569825.1' already exists. Skipping...
Folder 'GCA_008136265.1_PDT000569823.1' already exists. Skipping...
Folder 'GCA_008136285.1_PDT000569832.1' already exists. Skipping...
Folder 'GCA_008136325.1_PDT000569838.1' already exists. Skipping...
Folder 'GCA_008136365.1_PDT000569837.1' already exists. Skipping...
Folder 'GCA_008136385.1_PDT000569839.1' already exists. Skipping...
Folder 'GCA_008136425.1_PDT000569842.1' already exists. Skipping...
Folder 'GCA_008136455.1_PDT000569844.1' already exists. Skipping...
Folder 'GCA_008136485.1_PDT000569843.1' already exists. Skipping...
Folder 'GCA_008136505.1_PDT000569836.1' already exists. Skipping...
Folder 'GCA_008136565.1_PDT000569846.1' already exists. Skipping...
Folder 'GCA_008136605.1_PDT000569859.1' already exists. Skipping...
Folder 'GCA_008136625.1_PDT000569857.1' already exists. Skipping...
Folder 'GCA_008136705.1_PDT000569858.1' already exists. Skipping...
Folder 'GCA_008136745.1_PDT000569865.1' already exists. Skipping...
Folder 'GCA_008136765.1_PDT000569863.1' already exists. Skipping...
Folder 'GCA_008136865.1_PDT000569869.1' already exists. Skipping...
Folder 'GCA_008136905.1_PDT000569875.1' already exists. Skipping...
Folder 'GCA_008136965.1_PDT000569871.1' already exists. Skipping...
Folder 'GCA_008137025.1_PDT000569874.1' already exists. Skipping...
Folder 'GCA_008137045.1_PDT000569879.1' already exists. Skipping...
Folder 'GCA_008137085.1_PDT000569872.1' already exists. Skipping...
Folder 'GCA_008137125.1_PDT000569899.1' already exists. Skipping...
Folder 'GCA_008137185.1_PDT000569884.1' already exists. Skipping...
Folder 'GCA_008137205.1_PDT000569882.1' already exists. Skipping...
Folder 'GCA_008137305.1_PDT000569900.1' already exists. Skipping...
Folder 'GCA_008137405.1_PDT000569218.1' already exists. Skipping...
Folder 'GCA_008137445.1_PDT000569221.1' already exists. Skipping...
Folder 'GCA_008137465.1_PDT000569217.1' already exists. Skipping...
Folder 'GCA_008137485.1_PDT000569263.1' already exists. Skipping...
Folder 'GCA_008137505.1_PDT000569235.1' already exists. Skipping...
Folder 'GCA_008137525.1_PDT000569228.1' already exists. Skipping...
Folder 'GCA_008137545.1_PDT000569222.1' already exists. Skipping...
Folder 'GCA_008137565.1_PDT000569257.1' already exists. Skipping...
Folder 'GCA_008137585.1_PDT000569262.1' already exists. Skipping...
Folder 'GCA_008137625.1_PDT000569226.1' already exists. Skipping...
Folder 'GCA_008137645.1_PDT000569231.1' already exists. Skipping...
Folder 'GCA_008137665.1_PDT000569260.1' already exists. Skipping...
Folder 'GCA_008137685.1_PDT000569227.1' already exists. Skipping...
Folder 'GCA_008137705.1_PDT000569232.1' already exists. Skipping...
Folder 'GCA_008137725.1_PDT000569268.1' already exists. Skipping...
Folder 'GCA_008137765.1_PDT000569272.1' already exists. Skipping...
Folder 'GCA_008137785.1_PDT000569265.1' already exists. Skipping...
Folder 'GCA_008137805.1_PDT000570517.1' already exists. Skipping...
Folder 'GCA_008137825.1_PDT000569910.1' already exists. Skipping...
Folder 'GCA_008137845.1_PDT000569906.1' already exists. Skipping...
Folder 'GCA_008137865.1_PDT000570465.1' already exists. Skipping...
Folder 'GCA_008137885.1_PDT000570451.1' already exists. Skipping...
Folder 'GCA_008137905.1_PDT000569908.1' already exists. Skipping...
Folder 'GCA_008137965.1_PDT000570458.1' already exists. Skipping...
Folder 'GCA_008137985.1_PDT000570470.1' already exists. Skipping...
Folder 'GCA_008138005.1_PDT000570478.1' already exists. Skipping...
Folder 'GCA_008138025.1_PDT000570523.1' already exists. Skipping...
Folder 'GCA_008138045.1_PDT000570467.1' already exists. Skipping...
Folder 'GCA_008138065.1_PDT000570473.1' already exists. Skipping...
Folder 'GCA_008138185.1_PDT000570522.1' already exists. Skipping...
Folder 'GCA_008138245.1_PDT000570446.1' already exists. Skipping...
Folder 'GCA_008138265.1_PDT000570482.1' already exists. Skipping...
Folder 'GCA_008138305.1_PDT000570488.1' already exists. Skipping...
Folder 'GCA_008138325.1_PDT000570464.1' already exists. Skipping...
Folder 'GCA_008138345.1_PDT000569922.1' already exists. Skipping...
Folder 'GCA_008138365.1_PDT000570444.1' already exists. Skipping...
Folder 'GCA_008138385.1_PDT000570518.1' already exists. Skipping...
Folder 'GCA_008138405.1_PDT000570452.1' already exists. Skipping...
Folder 'GCA_008138415.1_PDT000569921.1' already exists. Skipping...
Folder 'GCA_008138445.1_PDT000570456.1' already exists. Skipping...
Folder 'GCA_008138465.1_PDT000570493.1' already exists. Skipping...
Folder 'GCA_008138485.1_PDT000570461.1' already exists. Skipping...
Folder 'GCA_008138505.1_PDT000570443.1' already exists. Skipping...
Folder 'GCA_008138525.1_PDT000570447.1' already exists. Skipping...
Folder 'GCA_008138555.1_PDT000569907.1' already exists. Skipping...
Folder 'GCA_008138585.1_PDT000570486.1' already exists. Skipping...
Folder 'GCA_008138605.1_PDT000570515.1' already exists. Skipping...
Folder 'GCA_008138645.1_PDT000570448.1' already exists. Skipping...
Folder 'GCA_008138665.1_PDT000570463.1' already exists. Skipping...
Folder 'GCA_008138685.1_PDT000570454.1' already exists. Skipping...
Folder 'GCA_008138705.1_PDT000570494.1' already exists. Skipping...
Folder 'GCA_008138725.1_PDT000570531.1' already exists. Skipping...
Folder 'GCA_008138745.1_PDT000570509.1' already exists. Skipping...
Folder 'GCA_008138785.1_PDT000570510.1' already exists. Skipping...
Folder 'GCA_008138805.1_PDT000570442.1' already exists. Skipping...
Folder 'GCA_008138825.1_PDT000570472.1' already exists. Skipping...
Folder 'GCA_008138845.1_PDT000570449.1' already exists. Skipping...
Folder 'GCA_008138865.1_PDT000570485.1' already exists. Skipping...
Folder 'GCA_008138885.1_PDT000570450.1' already exists. Skipping...
Folder 'GCA_008138905.1_PDT000570484.1' already exists. Skipping...
Folder 'GCA_008138925.1_PDT000570512.1' already exists. Skipping...
Folder 'GCA_008138945.1_PDT000570487.1' already exists. Skipping...
Folder 'GCA_008138965.1_PDT000570504.1' already exists. Skipping...
Folder 'GCA_008138985.1_PDT000570477.1' already exists. Skipping...
Folder 'GCA_008139005.1_PDT000570525.1' already exists. Skipping...
Folder 'GCA_008139025.1_PDT000570460.1' already exists. Skipping...
Folder 'GCA_008139065.1_PDT000570480.1' already exists. Skipping...
Folder 'GCA_008139105.1_PDT000570505.1' already exists. Skipping...
Folder 'GCA_008139125.1_PDT000570455.1' already exists. Skipping...
Folder 'GCA_008139145.1_PDT000570528.1' already exists. Skipping...
Folder 'GCA_008139165.1_PDT000570459.1' already exists. Skipping...
Folder 'GCA_008139185.1_PDT000570489.1' already exists. Skipping...
Folder 'GCA_008139195.1_PDT000570483.1' already exists. Skipping...
Folder 'GCA_008139225.1_PDT000570514.1' already exists. Skipping...
Folder 'GCA_008139245.1_PDT000570496.1' already exists. Skipping...
Folder 'GCA_008139265.1_PDT000570475.1' already exists. Skipping...
Folder 'GCA_008139285.1_PDT000570471.1' already exists. Skipping...
Folder 'GCA_008139305.1_PDT000570520.1' already exists. Skipping...
Folder 'GCA_008139325.1_PDT000570516.1' already exists. Skipping...
Folder 'GCA_008139345.1_PDT000569926.1' already exists. Skipping...
Folder 'GCA_008139365.1_PDT000570527.1' already exists. Skipping...
Folder 'GCA_008139405.1_PDT000570468.1' already exists. Skipping...
Folder 'GCA_008139415.1_PDT000570491.1' already exists. Skipping...
Folder 'GCA_008139465.1_PDT000570511.1' already exists. Skipping...
Folder 'GCA_008139485.1_PDT000570519.1' already exists. Skipping...
Folder 'GCA_008139505.1_PDT000570474.1' already exists. Skipping...
Folder 'GCA_008139525.1_PDT000570490.1' already exists. Skipping...
Folder 'GCA_008139545.1_PDT000570466.1' already exists. Skipping...
Folder 'GCA_008139645.1_PDT000570498.1' already exists. Skipping...
Folder 'GCA_008139665.1_PDT000570479.1' already exists. Skipping...
Folder 'GCA_008139685.1_PDT000570521.1' already exists. Skipping...
Folder 'GCA_008139705.1_PDT000570453.1' already exists. Skipping...
Folder 'GCA_008139745.1_PDT000570462.1' already exists. Skipping...
Folder 'GCA_008139765.1_PDT000570457.1' already exists. Skipping...
Folder 'GCA_008139785.1_PDT000570476.1' already exists. Skipping...
Folder 'GCA_008139805.1_PDT000570533.1' already exists. Skipping...
Folder 'GCA_008139825.1_PDT000570501.1' already exists. Skipping...
Folder 'GCA_008139845.1_PDT000570500.1' already exists. Skipping...
Folder 'GCA_008139865.1_PDT000570502.1' already exists. Skipping...
Folder 'GCA_008139885.1_PDT000570492.1' already exists. Skipping...
Folder 'GCA_008139905.1_PDT000570534.1' already exists. Skipping...
Folder 'GCA_008139925.1_PDT000570507.1' already exists. Skipping...
Folder 'GCA_008139945.1_PDT000570506.1' already exists. Skipping...
Folder 'GCA_008139965.1_PDT000570532.1' already exists. Skipping...
Folder 'GCA_008139985.1_PDT000570678.1' already exists. Skipping...
Folder 'GCA_008140005.1_PDT000570673.1' already exists. Skipping...
Folder 'GCA_008140045.1_PDT000570577.1' already exists. Skipping...
Folder 'GCA_008140065.1_PDT000570675.1' already exists. Skipping...
Folder 'GCA_008140085.1_PDT000570570.1' already exists. Skipping...
Folder 'GCA_008140125.1_PDT000570624.1' already exists. Skipping...
Folder 'GCA_008140145.1_PDT000570679.1' already exists. Skipping...
Folder 'GCA_008140165.1_PDT000570623.1' already exists. Skipping...
Folder 'GCA_008140185.1_PDT000570530.1' already exists. Skipping...
Folder 'GCA_008140205.1_PDT000570677.1' already exists. Skipping...
Folder 'GCA_008140225.1_PDT000570629.1' already exists. Skipping...
Folder 'GCA_008140265.1_PDT000570572.1' already exists. Skipping...
Folder 'GCA_008140285.1_PDT000570576.1' already exists. Skipping...
Folder 'GCA_008140305.1_PDT000570676.1' already exists. Skipping...
Folder 'GCA_008140325.1_PDT000570628.1' already exists. Skipping...
Folder 'GCA_008140345.1_PDT000570625.1' already exists. Skipping...
Folder 'GCA_008140365.1_PDT000570680.1' already exists. Skipping...
Folder 'GCA_008140405.1_PDT000570728.1' already exists. Skipping...
Folder 'GCA_008140425.1_PDT000570729.1' already exists. Skipping...
Folder 'GCA_008140445.1_PDT000570536.1' already exists. Skipping...
Folder 'GCA_008140465.1_PDT000570626.1' already exists. Skipping...
Folder 'GCA_008140485.1_PDT000570537.1' already exists. Skipping...
Folder 'GCA_008140505.1_PDT000570674.1' already exists. Skipping...
Folder 'GCA_008140525.1_PDT000570538.1' already exists. Skipping...
Folder 'GCA_008140545.1_PDT000570540.1' already exists. Skipping...
Folder 'GCA_008140565.1_PDT000570539.1' already exists. Skipping...
Folder 'GCA_008140585.1_PDT000570541.1' already exists. Skipping...
Folder 'GCA_008140605.1_PDT000570542.1' already exists. Skipping...
Folder 'GCA_008140625.1_PDT000570546.1' already exists. Skipping...
Folder 'GCA_008140645.1_PDT000570543.1' already exists. Skipping...
Folder 'GCA_008140665.1_PDT000570545.1' already exists. Skipping...
Folder 'GCA_008140685.1_PDT000570557.1' already exists. Skipping...
Folder 'GCA_008140705.1_PDT000570549.1' already exists. Skipping...
Folder 'GCA_008140725.1_PDT000570544.1' already exists. Skipping...
Folder 'GCA_008140745.1_PDT000570547.1' already exists. Skipping...
Folder 'GCA_008140765.1_PDT000570730.1' already exists. Skipping...
Folder 'GCA_008140785.1_PDT000570548.1' already exists. Skipping...
Folder 'GCA_008140805.1_PDT000570731.1' already exists. Skipping...
Folder 'GCA_008140825.1_PDT000570550.1' already exists. Skipping...
Folder 'GCA_008140845.1_PDT000570554.1' already exists. Skipping...
Folder 'GCA_008140865.1_PDT000570551.1' already exists. Skipping...
Folder 'GCA_008140885.1_PDT000570564.1' already exists. Skipping...
Folder 'GCA_008140905.1_PDT000570565.1' already exists. Skipping...
Folder 'GCA_008140925.1_PDT000570562.1' already exists. Skipping...
Folder 'GCA_008140945.1_PDT000570566.1' already exists. Skipping...
Folder 'GCA_008140965.1_PDT000570552.1' already exists. Skipping...
Folder 'GCA_008140985.1_PDT000570578.1' already exists. Skipping...
Folder 'GCA_008141005.1_PDT000570567.1' already exists. Skipping...
Folder 'GCA_008141025.1_PDT000570569.1' already exists. Skipping...
Folder 'GCA_008141065.1_PDT000570568.1' already exists. Skipping...
Folder 'GCA_008141105.1_PDT000570582.1' already exists. Skipping...
Folder 'GCA_008141115.1_PDT000570581.1' already exists. Skipping...
Folder 'GCA_008141145.1_PDT000570580.1' already exists. Skipping...
Folder 'GCA_008141165.1_PDT000570583.1' already exists. Skipping...
Folder 'GCA_008141185.1_PDT000570584.1' already exists. Skipping...
Folder 'GCA_008141205.1_PDT000570587.1' already exists. Skipping...
Folder 'GCA_008141215.1_PDT000570586.1' already exists. Skipping...
Folder 'GCA_008141265.1_PDT000570589.1' already exists. Skipping...
Folder 'GCA_008141285.1_PDT000570588.1' already exists. Skipping...
Folder 'GCA_008141325.1_PDT000570594.1' already exists. Skipping...
Folder 'GCA_008141345.1_PDT000570591.1' already exists. Skipping...
Folder 'GCA_008141365.1_PDT000570595.1' already exists. Skipping...
Folder 'GCA_008141385.1_PDT000570593.1' already exists. Skipping...
Folder 'GCA_008141405.1_PDT000570619.1' already exists. Skipping...
Folder 'GCA_008141445.1_PDT000570627.1' already exists. Skipping...
Folder 'GCA_008141465.1_PDT000570634.1' already exists. Skipping...
Folder 'GCA_008141485.1_PDT000570621.1' already exists. Skipping...
Folder 'GCA_008141505.1_PDT000570622.1' already exists. Skipping...
Folder 'GCA_008141515.1_PDT000570620.1' already exists. Skipping...
Folder 'GCA_008141545.1_PDT000570630.1' already exists. Skipping...
Folder 'GCA_008141565.1_PDT000570631.1' already exists. Skipping...
Folder 'GCA_008141585.1_PDT000570632.1' already exists. Skipping...
Folder 'GCA_008141605.1_PDT000570633.1' already exists. Skipping...
Folder 'GCA_008141625.1_PDT000570635.1' already exists. Skipping...
Folder 'GCA_008141635.1_PDT000570638.1' already exists. Skipping...
Folder 'GCA_008141665.1_PDT000570639.1' already exists. Skipping...
Folder 'GCA_008141685.1_PDT000570644.1' already exists. Skipping...
Folder 'GCA_008141725.1_PDT000570637.1' already exists. Skipping...
Folder 'GCA_008141745.1_PDT000570640.1' already exists. Skipping...
Folder 'GCA_008141765.1_PDT000570642.1' already exists. Skipping...
Folder 'GCA_008141785.1_PDT000570648.1' already exists. Skipping...
Folder 'GCA_008141805.1_PDT000570641.1' already exists. Skipping...
Folder 'GCA_008141825.1_PDT000570645.1' already exists. Skipping...
Folder 'GCA_008141845.1_PDT000570649.1' already exists. Skipping...
Folder 'GCA_008141865.1_PDT000570647.1' already exists. Skipping...
Folder 'GCA_008141885.1_PDT000570652.1' already exists. Skipping...
Folder 'GCA_008141945.1_PDT000570651.1' already exists. Skipping...
Folder 'GCA_008141965.1_PDT000570653.1' already exists. Skipping...
Folder 'GCA_008141985.1_PDT000570656.1' already exists. Skipping...
Folder 'GCA_008142005.1_PDT000570660.1' already exists. Skipping...
Folder 'GCA_008142025.1_PDT000570658.1' already exists. Skipping...
Folder 'GCA_008142045.1_PDT000570654.1' already exists. Skipping...
Folder 'GCA_008142085.1_PDT000570666.1' already exists. Skipping...
Folder 'GCA_008142105.1_PDT000570665.1' already exists. Skipping...
Folder 'GCA_008142115.1_PDT000570657.1' already exists. Skipping...
Folder 'GCA_008142155.1_PDT000570663.1' already exists. Skipping...
Folder 'GCA_008142185.1_PDT000570655.1' already exists. Skipping...
Folder 'GCA_008142205.1_PDT000570664.1' already exists. Skipping...
Folder 'GCA_008142225.1_PDT000570661.1' already exists. Skipping...
Folder 'GCA_008142245.1_PDT000570670.1' already exists. Skipping...
Folder 'GCA_008142265.1_PDT000570667.1' already exists. Skipping...
Folder 'GCA_008142285.1_PDT000570669.1' already exists. Skipping...
Folder 'GCA_008142305.1_PDT000570671.1' already exists. Skipping...
Folder 'GCA_008142325.1_PDT000570682.1' already exists. Skipping...
Folder 'GCA_008142345.1_PDT000570672.1' already exists. Skipping...
Folder 'GCA_008142365.1_PDT000570681.1' already exists. Skipping...
Folder 'GCA_008142385.1_PDT000570683.1' already exists. Skipping...
Folder 'GCA_008142425.1_PDT000570684.1' already exists. Skipping...
Folder 'GCA_008142465.1_PDT000570693.1' already exists. Skipping...
Folder 'GCA_008142485.1_PDT000570685.1' already exists. Skipping...
Folder 'GCA_008142505.1_PDT000570690.1' already exists. Skipping...
Folder 'GCA_008142545.1_PDT000570689.1' already exists. Skipping...

Retreiveing data: 59005it [00:10, 6662.91it/s]

Folder 'GCA_008225585.1_PDT000559839.1' already exists. Skipping...
Folder 'GCA_008225605.1_PDT000559856.1' already exists. Skipping...
Folder 'GCA_008225665.1_PDT000559858.1' already exists. Skipping...
Folder 'GCA_008225675.1_PDT000559919.1' already exists. Skipping...
Folder 'GCA_008225765.1_PDT000559848.1' already exists. Skipping...
Folder 'GCA_008225785.1_PDT000559972.1' already exists. Skipping...
Folder 'GCA_008225825.1_PDT000559928.1' already exists. Skipping...
Folder 'GCA_008225865.1_PDT000559916.1' already exists. Skipping...
Folder 'GCA_008225885.1_PDT000559971.1' already exists. Skipping...
Folder 'GCA_008225925.1_PDT000559911.1' already exists. Skipping...
Folder 'GCA_008225965.1_PDT000559910.1' already exists. Skipping...
Folder 'GCA_008225985.1_PDT000559978.1' already exists. Skipping...
Folder 'GCA_008226005.1_PDT000559923.1' already exists. Skipping...
Folder 'GCA_008226025.1_PDT000559908.1' already exists. Skipping...
Folder 'GCA_008226065.1_PDT000559906.1' already exists. Skipping...
Folder 'GCA_008226085.1_PDT000559917.1' already exists. Skipping...
Folder 'GCA_008226105.1_PDT000559913.1' already exists. Skipping...
Folder 'GCA_008226155.1_PDT000559918.1' already exists. Skipping...
Folder 'GCA_008226255.1_PDT000559974.1' already exists. Skipping...
Folder 'GCA_008226345.1_PDT000559907.1' already exists. Skipping...
Folder 'GCA_008226395.1_PDT000559925.1' already exists. Skipping...
Folder 'GCA_008226445.1_PDT000559930.1' already exists. Skipping...
Folder 'GCA_008226505.1_PDT000559920.1' already exists. Skipping...
Folder 'GCA_008226605.1_PDT000559973.1' already exists. Skipping...
Folder 'GCA_008226625.1_PDT000559850.1' already exists. Skipping...
Folder 'GCA_008226665.1_PDT000559912.1' already exists. Skipping...
Folder 'GCA_008226725.1_PDT000559854.1' already exists. Skipping...
Folder 'GCA_008226765.1_PDT000559969.1' already exists. Skipping...
Folder 'GCA_008226785.1_PDT000559970.1' already exists. Skipping...
Folder 'GCA_008226825.1_PDT000559975.1' already exists. Skipping...
Folder 'GCA_008226905.1_PDT000559935.1' already exists. Skipping...
Folder 'GCA_008226945.1_PDT000559931.1' already exists. Skipping...
Folder 'GCA_008226965.1_PDT000559941.1' already exists. Skipping...
Folder 'GCA_008227005.1_PDT000559927.1' already exists. Skipping...
Folder 'GCA_008227225.1_PDT000559959.1' already exists. Skipping...
Folder 'GCA_008227245.1_PDT000559965.1' already exists. Skipping...
Folder 'GCA_008227265.1_PDT000559960.1' already exists. Skipping...
Folder 'GCA_008227285.1_PDT000559963.1' already exists. Skipping...
Folder 'GCA_008227305.1_PDT000559964.1' already exists. Skipping...
Folder 'GCA_008227365.1_PDT000559979.1' already exists. Skipping...
Folder 'GCA_008227385.1_PDT000559966.1' already exists. Skipping...
Folder 'GCA_008227485.1_PDT000559983.1' already exists. Skipping...
Folder 'GCA_008227545.1_PDT000559985.1' already exists. Skipping...
Folder 'GCA_008227585.1_PDT000559981.1' already exists. Skipping...
Folder 'GCA_008227605.1_PDT000559984.1' already exists. Skipping...
Folder 'GCA_008227685.1_PDT000559987.1' already exists. Skipping...
Folder 'GCA_008227725.1_PDT000560052.1' already exists. Skipping...
Folder 'GCA_008227865.1_PDT000560097.1' already exists. Skipping...
Folder 'GCA_008227885.1_PDT000560051.1' already exists. Skipping...
Folder 'GCA_008227925.1_PDT000560014.1' already exists. Skipping...
Folder 'GCA_008227965.1_PDT000560012.1' already exists. Skipping...
Folder 'GCA_008227985.1_PDT000560011.1' already exists. Skipping...
Folder 'GCA_008227995.1_PDT000560015.1' already exists. Skipping...
Folder 'GCA_008228025.1_PDT000560053.1' already exists. Skipping...
Folder 'GCA_008228065.1_PDT000560058.1' already exists. Skipping...
Folder 'GCA_008228085.1_PDT000560056.1' already exists. Skipping...
Folder 'GCA_008228125.1_PDT000560050.1' already exists. Skipping...
Folder 'GCA_008228145.1_PDT000560054.1' already exists. Skipping...
Folder 'GCA_008228165.1_PDT000560057.1' already exists. Skipping...
Folder 'GCA_008228205.1_PDT000560060.1' already exists. Skipping...
Folder 'GCA_008228225.1_PDT000560094.1' already exists. Skipping...
Folder 'GCA_008228245.1_PDT000560098.1' already exists. Skipping...
Folder 'GCA_008228265.1_PDT000560099.1' already exists. Skipping...
Folder 'GCA_008228285.1_PDT000560139.1' already exists. Skipping...
Folder 'GCA_008228325.1_PDT000560093.1' already exists. Skipping...
Folder 'GCA_008228345.1_PDT000560141.1' already exists. Skipping...
Folder 'GCA_008228405.1_PDT000559988.1' already exists. Skipping...
Folder 'GCA_008228425.1_PDT000560134.1' already exists. Skipping...
Folder 'GCA_008228445.1_PDT000560143.1' already exists. Skipping...
Folder 'GCA_008228455.1_PDT000559990.1' already exists. Skipping...
Folder 'GCA_008228505.1_PDT000559989.1' already exists. Skipping...
Folder 'GCA_008228525.1_PDT000559991.1' already exists. Skipping...
Folder 'GCA_008228545.1_PDT000560140.1' already exists. Skipping...
Folder 'GCA_008228565.1_PDT000560137.1' already exists. Skipping...
Folder 'GCA_008228585.1_PDT000559992.1' already exists. Skipping...
Folder 'GCA_008228625.1_PDT000560136.1' already exists. Skipping...
Folder 'GCA_008228645.1_PDT000559994.1' already exists. Skipping...
Folder 'GCA_008228665.1_PDT000559993.1' already exists. Skipping...
Folder 'GCA_008228685.1_PDT000560142.1' already exists. Skipping...
Folder 'GCA_008228705.1_PDT000559997.1' already exists. Skipping...
Folder 'GCA_008228725.1_PDT000559996.1' already exists. Skipping...
Folder 'GCA_008228745.1_PDT000559998.1' already exists. Skipping...
Folder 'GCA_008228785.1_PDT000560001.1' already exists. Skipping...
Folder 'GCA_008228805.1_PDT000560000.1' already exists. Skipping...
Folder 'GCA_008228845.1_PDT000560004.1' already exists. Skipping...
Folder 'GCA_008228865.1_PDT000560002.1' already exists. Skipping...
Folder 'GCA_008228885.1_PDT000560006.1' already exists. Skipping...
Folder 'GCA_008228905.1_PDT000560005.1' already exists. Skipping...
Folder 'GCA_008228925.1_PDT000560016.1' already exists. Skipping...
Folder 'GCA_008228945.1_PDT000560010.1' already exists. Skipping...
Folder 'GCA_008228965.1_PDT000560017.1' already exists. Skipping...
Folder 'GCA_008228985.1_PDT000560007.1' already exists. Skipping...
Folder 'GCA_008229005.1_PDT000560018.1' already exists. Skipping...
Folder 'GCA_008229045.1_PDT000560021.1' already exists. Skipping...
Folder 'GCA_008229125.1_PDT000560022.1' already exists. Skipping...
Folder 'GCA_008229145.1_PDT000560027.1' already exists. Skipping...
Folder 'GCA_008229185.1_PDT000560020.1' already exists. Skipping...
Folder 'GCA_008229205.1_PDT000560019.1' already exists. Skipping...
Folder 'GCA_008229225.1_PDT000560030.1' already exists. Skipping...
Folder 'GCA_008229245.1_PDT000560026.1' already exists. Skipping...
Folder 'GCA_008229265.1_PDT000560036.1' already exists. Skipping...
Folder 'GCA_008229285.1_PDT000560034.1' already exists. Skipping...
Folder 'GCA_008229305.1_PDT000560033.1' already exists. Skipping...
Folder 'GCA_008229325.1_PDT000560032.1' already exists. Skipping...
Folder 'GCA_008229345.1_PDT000560037.1' already exists. Skipping...
Folder 'GCA_008229365.1_PDT000560035.1' already exists. Skipping...
Folder 'GCA_008229385.1_PDT000560041.1' already exists. Skipping...
Folder 'GCA_008229405.1_PDT000560038.1' already exists. Skipping...
Folder 'GCA_008229425.1_PDT000560040.1' already exists. Skipping...
Folder 'GCA_008229445.1_PDT000560043.1' already exists. Skipping...
Folder 'GCA_008229465.1_PDT000560042.1' already exists. Skipping...
Folder 'GCA_008229485.1_PDT000560044.1' already exists. Skipping...
Folder 'GCA_008229525.1_PDT000560047.1' already exists. Skipping...
Folder 'GCA_008229545.1_PDT000560059.1' already exists. Skipping...
Folder 'GCA_008229565.1_PDT000560048.1' already exists. Skipping...
Folder 'GCA_008229625.1_PDT000560045.1' already exists. Skipping...
Folder 'GCA_008229665.1_PDT000560064.1' already exists. Skipping...
Folder 'GCA_008229705.1_PDT000560069.1' already exists. Skipping...
Folder 'GCA_008229725.1_PDT000560068.1' already exists. Skipping...
Folder 'GCA_008229745.1_PDT000560067.1' already exists. Skipping...
Folder 'GCA_008229765.1_PDT000560071.1' already exists. Skipping...
Folder 'GCA_008229785.1_PDT000560073.1' already exists. Skipping...
Folder 'GCA_008229805.1_PDT000560065.1' already exists. Skipping...
Folder 'GCA_008229825.1_PDT000560070.1' already exists. Skipping...
Folder 'GCA_008229845.1_PDT000560075.1' already exists. Skipping...
Folder 'GCA_008229865.1_PDT000560077.1' already exists. Skipping...
Folder 'GCA_008229885.1_PDT000560074.1' already exists. Skipping...
Folder 'GCA_008229925.1_PDT000560076.1' already exists. Skipping...
Folder 'GCA_008229945.1_PDT000560078.1' already exists. Skipping...
Folder 'GCA_008229965.1_PDT000560080.1' already exists. Skipping...
Folder 'GCA_008229985.1_PDT000560079.1' already exists. Skipping...
Folder 'GCA_008230005.1_PDT000560081.1' already exists. Skipping...
Folder 'GCA_008230025.1_PDT000560082.1' already exists. Skipping...
Folder 'GCA_008230045.1_PDT000560084.1' already exists. Skipping...
Folder 'GCA_008230065.1_PDT000560083.1' already exists. Skipping...
Folder 'GCA_008230085.1_PDT000560086.1' already exists. Skipping...
Folder 'GCA_008230095.1_PDT000560085.1' already exists. Skipping...
Folder 'GCA_008230125.1_PDT000560087.1' already exists. Skipping...
Folder 'GCA_008230145.1_PDT000560089.1' already exists. Skipping...
Folder 'GCA_008230185.1_PDT000560090.1' already exists. Skipping...
Folder 'GCA_008230205.1_PDT000560091.1' already exists. Skipping...
Folder 'GCA_008230245.1_PDT000560105.1' already exists. Skipping...
Folder 'GCA_008230265.1_PDT000560100.1' already exists. Skipping...
Folder 'GCA_008230285.1_PDT000560107.1' already exists. Skipping...
Folder 'GCA_008230305.1_PDT000560103.1' already exists. Skipping...
Folder 'GCA_008230325.1_PDT000560111.1' already exists. Skipping...
Folder 'GCA_008230365.1_PDT000560106.1' already exists. Skipping...
Folder 'GCA_008230385.1_PDT000560109.1' already exists. Skipping...
Folder 'GCA_008230405.1_PDT000560108.1' already exists. Skipping...
Folder 'GCA_008230425.1_PDT000560104.1' already exists. Skipping...
Folder 'GCA_008230445.1_PDT000560112.1' already exists. Skipping...
Folder 'GCA_008230465.1_PDT000560115.1' already exists. Skipping...
Folder 'GCA_008230485.1_PDT000560116.1' already exists. Skipping...
Folder 'GCA_008230505.1_PDT000560117.1' already exists. Skipping...
Folder 'GCA_008230525.1_PDT000560118.1' already exists. Skipping...
Folder 'GCA_008230535.1_PDT000560114.1' already exists. Skipping...
Folder 'GCA_008230565.1_PDT000560119.1' already exists. Skipping...
Folder 'GCA_008230585.1_PDT000560120.1' already exists. Skipping...
Folder 'GCA_008230605.1_PDT000560121.1' already exists. Skipping...
Folder 'GCA_008230625.1_PDT000560122.1' already exists. Skipping...
Folder 'GCA_008230645.1_PDT000560124.1' already exists. Skipping...
Folder 'GCA_008230685.1_PDT000560125.1' already exists. Skipping...
Folder 'GCA_008230705.1_PDT000560126.1' already exists. Skipping...
Folder 'GCA_008230725.1_PDT000560127.1' already exists. Skipping...
Folder 'GCA_008230735.1_PDT000560128.1' already exists. Skipping...
Folder 'GCA_008230765.1_PDT000560129.1' already exists. Skipping...
Folder 'GCA_008230805.1_PDT000560133.1' already exists. Skipping...
Folder 'GCA_008230825.1_PDT000560131.1' already exists. Skipping...
Folder 'GCA_008230845.1_PDT000560130.1' already exists. Skipping...
Folder 'GCA_008230865.1_PDT000560144.1' already exists. Skipping...
Folder 'GCA_008230885.1_PDT000560154.1' already exists. Skipping...
Folder 'GCA_008230905.1_PDT000560146.1' already exists. Skipping...
Folder 'GCA_008230925.1_PDT000560148.1' already exists. Skipping...
Folder 'GCA_008230945.1_PDT000560155.1' already exists. Skipping...
Folder 'GCA_008230965.1_PDT000560149.1' already exists. Skipping...
Folder 'GCA_008230985.1_PDT000560150.1' already exists. Skipping...
Folder 'GCA_008231005.1_PDT000560151.1' already exists. Skipping...
Folder 'GCA_008231025.1_PDT000560145.1' already exists. Skipping...
Folder 'GCA_008231035.1_PDT000560152.1' already exists. Skipping...
Folder 'GCA_008231085.1_PDT000560156.1' already exists. Skipping...
Folder 'GCA_008231105.1_PDT000560158.1' already exists. Skipping...
Folder 'GCA_008231125.1_PDT000560157.1' already exists. Skipping...
Folder 'GCA_008231145.1_PDT000560161.1' already exists. Skipping...
Folder 'GCA_008231185.1_PDT000560228.1' already exists. Skipping...
Folder 'GCA_008231205.1_PDT000560194.1' already exists. Skipping...
Folder 'GCA_008231225.1_PDT000560208.1' already exists. Skipping...
Folder 'GCA_008231245.1_PDT000560227.1' already exists. Skipping...
Folder 'GCA_008231265.1_PDT000560216.1' already exists. Skipping...
Folder 'GCA_008231285.1_PDT000560262.1' already exists. Skipping...
Folder 'GCA_008231305.1_PDT000560222.1' already exists. Skipping...
Folder 'GCA_008231325.1_PDT000560193.1' already exists. Skipping...
Folder 'GCA_008231345.1_PDT000560162.1' already exists. Skipping...
Folder 'GCA_008231365.1_PDT000560212.1' already exists. Skipping...
Folder 'GCA_008231385.1_PDT000560189.1' already exists. Skipping...
Folder 'GCA_008231405.1_PDT000560183.1' already exists. Skipping...
Folder 'GCA_008231425.1_PDT000560159.1' already exists. Skipping...
Folder 'GCA_008231445.1_PDT000560165.1' already exists. Skipping...
Folder 'GCA_008231465.1_PDT000560203.1' already exists. Skipping...
Folder 'GCA_008231485.1_PDT000560174.1' already exists. Skipping...
Folder 'GCA_008231505.1_PDT000560175.1' already exists. Skipping...
Folder 'GCA_008231525.1_PDT000560185.1' already exists. Skipping...
Folder 'GCA_008231545.1_PDT000560190.1' already exists. Skipping...
Folder 'GCA_008231565.1_PDT000560235.1' already exists. Skipping...
Folder 'GCA_008231585.1_PDT000560182.1' already exists. Skipping...
Folder 'GCA_008231605.1_PDT000560201.1' already exists. Skipping...
Folder 'GCA_008231625.1_PDT000560198.1' already exists. Skipping...
Folder 'GCA_008231645.1_PDT000560166.1' already exists. Skipping...
Folder 'GCA_008231665.1_PDT000560261.1' already exists. Skipping...
Folder 'GCA_008231685.1_PDT000560173.1' already exists. Skipping...
Folder 'GCA_008231705.1_PDT000560160.1' already exists. Skipping...
Folder 'GCA_008231725.1_PDT000560226.1' already exists. Skipping...
Folder 'GCA_008231745.1_PDT000560218.1' already exists. Skipping...
Folder 'GCA_008231785.1_PDT000560168.1' already exists. Skipping...
Folder 'GCA_008231805.1_PDT000560225.1' already exists. Skipping...
Folder 'GCA_008231815.1_PDT000560163.1' already exists. Skipping...
Folder 'GCA_008231845.1_PDT000560213.1' already exists. Skipping...
Folder 'GCA_008231865.1_PDT000560188.1' already exists. Skipping...
Folder 'GCA_008231905.1_PDT000560264.1' already exists. Skipping...
Folder 'GCA_008231925.1_PDT000560265.1' already exists. Skipping...
Folder 'GCA_008231945.1_PDT000560239.1' already exists. Skipping...
Folder 'GCA_008231965.1_PDT000560259.1' already exists. Skipping...
Folder 'GCA_008231985.1_PDT000560243.1' already exists. Skipping...
Folder 'GCA_008232005.1_PDT000560167.1' already exists. Skipping...
Folder 'GCA_008232025.1_PDT000560230.1' already exists. Skipping...
Folder 'GCA_008232065.1_PDT000560229.1' already exists. Skipping...
Folder 'GCA_008232085.1_PDT000560238.1' already exists. Skipping...
Folder 'GCA_008232105.1_PDT000560170.1' already exists. Skipping...
Folder 'GCA_008232145.1_PDT000560210.1' already exists. Skipping...
Folder 'GCA_008232165.1_PDT000560209.1' already exists. Skipping...
Folder 'GCA_008232185.1_PDT000560232.1' already exists. Skipping...
Folder 'GCA_008232205.1_PDT000560233.1' already exists. Skipping...
Folder 'GCA_008232215.1_PDT000560180.1' already exists. Skipping...
Folder 'GCA_008232245.1_PDT000560224.1' already exists. Skipping...
Folder 'GCA_008232265.1_PDT000560263.1' already exists. Skipping...
Folder 'GCA_008232285.1_PDT000560200.1' already exists. Skipping...
Folder 'GCA_008232305.1_PDT000560242.1' already exists. Skipping...
Folder 'GCA_008232325.1_PDT000560176.1' already exists. Skipping...
Folder 'GCA_008232345.1_PDT000560197.1' already exists. Skipping...
Folder 'GCA_008232365.1_PDT000560219.1' already exists. Skipping...
Folder 'GCA_008232385.1_PDT000560207.1' already exists. Skipping...
Folder 'GCA_008232405.1_PDT000560214.1' already exists. Skipping...
Folder 'GCA_008232425.1_PDT000560237.1' already exists. Skipping...
Folder 'GCA_008232445.1_PDT000560199.1' already exists. Skipping...
Folder 'GCA_008232485.1_PDT000560245.1' already exists. Skipping...
Folder 'GCA_008232505.1_PDT000560192.1' already exists. Skipping...
Folder 'GCA_008232525.1_PDT000560221.1' already exists. Skipping...
Folder 'GCA_008232545.1_PDT000560215.1' already exists. Skipping...
Folder 'GCA_008232565.1_PDT000560181.1' already exists. Skipping...
Folder 'GCA_008232585.1_PDT000560202.1' already exists. Skipping...
Folder 'GCA_008232605.1_PDT000560246.1' already exists. Skipping...
Folder 'GCA_008232625.1_PDT000560236.1' already exists. Skipping...
Folder 'GCA_008232645.1_PDT000560240.1' already exists. Skipping...
Folder 'GCA_008232685.1_PDT000560178.1' already exists. Skipping...
Folder 'GCA_008232705.1_PDT000560206.1' already exists. Skipping...
Folder 'GCA_008232725.1_PDT000560223.1' already exists. Skipping...
Folder 'GCA_008232745.1_PDT000560191.1' already exists. Skipping...
Folder 'GCA_008232755.1_PDT000560266.1' already exists. Skipping...
Folder 'GCA_008232785.1_PDT000560205.1' already exists. Skipping...
Folder 'GCA_008232825.1_PDT000560247.1' already exists. Skipping...
Folder 'GCA_008232845.1_PDT000560177.1' already exists. Skipping...
Folder 'GCA_008232885.1_PDT000560217.1' already exists. Skipping...
Folder 'GCA_008232905.1_PDT000560248.1' already exists. Skipping...
Folder 'GCA_008232925.1_PDT000560241.1' already exists. Skipping...
Folder 'GCA_008232945.1_PDT000560249.1' already exists. Skipping...
Folder 'GCA_008232965.1_PDT000560211.1' already exists. Skipping...
Folder 'GCA_008232985.1_PDT000560252.1' already exists. Skipping...
Folder 'GCA_008233005.1_PDT000560250.1' already exists. Skipping...
Folder 'GCA_008233025.1_PDT000560251.1' already exists. Skipping...
Folder 'GCA_008233045.1_PDT000560254.1' already exists. Skipping...
Folder 'GCA_008233085.1_PDT000560255.1' already exists. Skipping...
Folder 'GCA_008233105.1_PDT000560257.1' already exists. Skipping...
Folder 'GCA_008233125.1_PDT000560258.1' already exists. Skipping...
Folder 'GCA_008233145.1_PDT000560268.1' already exists. Skipping...
Folder 'GCA_008233165.1_PDT000562146.1' already exists. Skipping...
Folder 'GCA_008233185.1_PDT000560267.1' already exists. Skipping...
Folder 'GCA_008233195.1_PDT000562150.1' already exists. Skipping...
Folder 'GCA_008233225.1_PDT000562152.1' already exists. Skipping...
Folder 'GCA_008233245.1_PDT000562151.1' already exists. Skipping...
Folder 'GCA_008233265.1_PDT000562148.1' already exists. Skipping...
Folder 'GCA_008233285.1_PDT000562157.1' already exists. Skipping...
Folder 'GCA_008233305.1_PDT000562149.1' already exists. Skipping...
Folder 'GCA_008233345.1_PDT000562154.1' already exists. Skipping...
Folder 'GCA_008233365.1_PDT000562155.1' already exists. Skipping...
Folder 'GCA_008233385.1_PDT000562147.1' already exists. Skipping...
Folder 'GCA_008233405.1_PDT000562158.1' already exists. Skipping...
Folder 'GCA_008233415.1_PDT000562153.1' already exists. Skipping...
Folder 'GCA_008233445.1_PDT000562159.1' already exists. Skipping...
Folder 'GCA_008233465.1_PDT000562163.1' already exists. Skipping...
Folder 'GCA_008233485.1_PDT000562164.1' already exists. Skipping...
Folder 'GCA_008233495.1_PDT000562343.1' already exists. Skipping...
Folder 'GCA_008233525.1_PDT000562162.1' already exists. Skipping...
Folder 'GCA_008233545.1_PDT000562221.1' already exists. Skipping...
Folder 'GCA_008233565.1_PDT000562177.1' already exists. Skipping...
Folder 'GCA_008233585.1_PDT000562298.1' already exists. Skipping...

Retreiveing data: 60343it [00:10, 6654.10it/s]

Folder 'GCA_008290455.1_PDT000574852.1' already exists. Skipping...
Folder 'GCA_008290495.1_PDT000574843.1' already exists. Skipping...
Folder 'GCA_008290515.1_PDT000574853.1' already exists. Skipping...
Folder 'GCA_008290535.1_PDT000574835.1' already exists. Skipping...
Folder 'GCA_008290555.1_PDT000574870.1' already exists. Skipping...
Folder 'GCA_008290575.1_PDT000576267.1' already exists. Skipping...
Folder 'GCA_008290595.1_PDT000574799.1' already exists. Skipping...
Folder 'GCA_008290615.1_PDT000576379.1' already exists. Skipping...
Folder 'GCA_008290635.1_PDT000575376.1' already exists. Skipping...
Folder 'GCA_008290655.1_PDT000575377.1' already exists. Skipping...
Folder 'GCA_008290715.1_PDT000576278.1' already exists. Skipping...
Folder 'GCA_008290755.1_PDT000574888.1' already exists. Skipping...
Folder 'GCA_008290775.1_PDT000574891.1' already exists. Skipping...
Folder 'GCA_008290795.1_PDT000574886.1' already exists. Skipping...
Folder 'GCA_008290815.1_PDT000575406.1' already exists. Skipping...
Folder 'GCA_008290835.1_PDT000574890.1' already exists. Skipping...
Folder 'GCA_008290855.1_PDT000575522.1' already exists. Skipping...
Folder 'GCA_008290895.1_PDT000575550.1' already exists. Skipping...
Folder 'GCA_008290915.1_PDT000575521.1' already exists. Skipping...
Folder 'GCA_008290935.1_PDT000576417.1' already exists. Skipping...
Folder 'GCA_008290975.1_PDT000575552.1' already exists. Skipping...
Folder 'GCA_008291015.1_PDT000575523.1' already exists. Skipping...
Folder 'GCA_008291055.1_PDT000575527.1' already exists. Skipping...
Folder 'GCA_008291095.1_PDT000575528.1' already exists. Skipping...
Folder 'GCA_008291115.1_PDT000575524.1' already exists. Skipping...
Folder 'GCA_008291135.1_PDT000575529.1' already exists. Skipping...
Folder 'GCA_008291155.1_PDT000575531.1' already exists. Skipping...
Folder 'GCA_008291195.1_PDT000575532.1' already exists. Skipping...
Folder 'GCA_008291215.1_PDT000575534.1' already exists. Skipping...
Folder 'GCA_008291235.1_PDT000575559.1' already exists. Skipping...
Folder 'GCA_008291255.1_PDT000575535.1' already exists. Skipping...
Folder 'GCA_008291275.1_PDT000575564.1' already exists. Skipping...
Folder 'GCA_008291355.1_PDT000575515.1' already exists. Skipping...
Folder 'GCA_008291365.1_PDT000575538.1' already exists. Skipping...
Folder 'GCA_008291435.1_PDT000576265.1' already exists. Skipping...
Folder 'GCA_008291515.1_PDT000576280.1' already exists. Skipping...
Folder 'GCA_008291555.1_PDT000575695.1' already exists. Skipping...
Folder 'GCA_008291575.1_PDT000575693.1' already exists. Skipping...
Folder 'GCA_008291615.1_PDT000576277.1' already exists. Skipping...
Folder 'GCA_008291635.1_PDT000576310.1' already exists. Skipping...
Folder 'GCA_008291655.1_PDT000576282.1' already exists. Skipping...
Folder 'GCA_008291675.1_PDT000576268.1' already exists. Skipping...
Folder 'GCA_008291695.1_PDT000576283.1' already exists. Skipping...
Folder 'GCA_008291735.1_PDT000576312.1' already exists. Skipping...
Folder 'GCA_008291755.1_PDT000576274.1' already exists. Skipping...
Folder 'GCA_008291765.1_PDT000576306.1' already exists. Skipping...
Folder 'GCA_008291835.1_PDT000576307.1' already exists. Skipping...
Folder 'GCA_008291855.1_PDT000576308.1' already exists. Skipping...
Folder 'GCA_008291875.1_PDT000576332.1' already exists. Skipping...
Folder 'GCA_008291885.1_PDT000576317.1' already exists. Skipping...
Folder 'GCA_008291895.1_PDT000576342.1' already exists. Skipping...
Folder 'GCA_008291935.1_PDT000576319.1' already exists. Skipping...
Folder 'GCA_008291955.1_PDT000576343.1' already exists. Skipping...
Folder 'GCA_008291975.1_PDT000576318.1' already exists. Skipping...
Folder 'GCA_008291985.1_PDT000576347.1' already exists. Skipping...
Folder 'GCA_008292015.1_PDT000576346.1' already exists. Skipping...
Folder 'GCA_008292055.1_PDT000576321.1' already exists. Skipping...
Folder 'GCA_008292075.1_PDT000576348.1' already exists. Skipping...
Folder 'GCA_008292135.1_PDT000576380.1' already exists. Skipping...
Folder 'GCA_008292155.1_PDT000576290.1' already exists. Skipping...
Folder 'GCA_008292175.1_PDT000576291.1' already exists. Skipping...
Folder 'GCA_008292195.1_PDT000576292.1' already exists. Skipping...
Folder 'GCA_008292235.1_PDT000576294.1' already exists. Skipping...
Folder 'GCA_008292255.1_PDT000576295.1' already exists. Skipping...
Folder 'GCA_008292295.1_PDT000576298.1' already exists. Skipping...
Folder 'GCA_008292315.1_PDT000576300.1' already exists. Skipping...
Folder 'GCA_008292355.1_PDT000576305.1' already exists. Skipping...
Folder 'GCA_008292365.1_PDT000576316.1' already exists. Skipping...
Folder 'GCA_008292415.1_PDT000576352.1' already exists. Skipping...
Folder 'GCA_008292435.1_PDT000576384.1' already exists. Skipping...
Folder 'GCA_008292455.1_PDT000576371.1' already exists. Skipping...
Folder 'GCA_008292495.1_PDT000576403.1' already exists. Skipping...
Folder 'GCA_008292555.1_PDT000576370.1' already exists. Skipping...
Folder 'GCA_008292575.1_PDT000576375.1' already exists. Skipping...
Folder 'GCA_008292595.1_PDT000576408.1' already exists. Skipping...
Folder 'GCA_008292615.1_PDT000576413.1' already exists. Skipping...
Folder 'GCA_008292635.1_PDT000576373.1' already exists. Skipping...
Folder 'GCA_008292655.1_PDT000576409.1' already exists. Skipping...
Folder 'GCA_008292675.1_PDT000576412.1' already exists. Skipping...
Folder 'GCA_008292695.1_PDT000576411.1' already exists. Skipping...
Folder 'GCA_008292775.1_PDT000576389.1' already exists. Skipping...
Folder 'GCA_008292795.1_PDT000576522.1' already exists. Skipping...
Folder 'GCA_008292835.1_PDT000576388.1' already exists. Skipping...
Folder 'GCA_008292855.1_PDT000576390.1' already exists. Skipping...
Folder 'GCA_008292875.1_PDT000576434.1' already exists. Skipping...
Folder 'GCA_008292895.1_PDT000576361.1' already exists. Skipping...
Folder 'GCA_008292915.1_PDT000576392.1' already exists. Skipping...
Folder 'GCA_008292975.1_PDT000576405.1' already exists. Skipping...
Folder 'GCA_008292995.1_PDT000576362.1' already exists. Skipping...
Folder 'GCA_008293015.1_PDT000576401.1' already exists. Skipping...
Folder 'GCA_008293035.1_PDT000576439.1' already exists. Skipping...
Folder 'GCA_008293095.1_PDT000576415.1' already exists. Skipping...
Folder 'GCA_008293115.1_PDT000576407.1' already exists. Skipping...
Folder 'GCA_008293135.1_PDT000576406.1' already exists. Skipping...
Folder 'GCA_008293155.1_PDT000576447.1' already exists. Skipping...
Folder 'GCA_008293175.1_PDT000576492.1' already exists. Skipping...
Folder 'GCA_008293195.1_PDT000576410.1' already exists. Skipping...
Folder 'GCA_008293235.1_PDT000576418.1' already exists. Skipping...
Folder 'GCA_008293265.1_PDT000576482.1' already exists. Skipping...
Folder 'GCA_008293315.1_PDT000576486.1' already exists. Skipping...
Folder 'GCA_008293335.1_PDT000576547.1' already exists. Skipping...
Folder 'GCA_008293375.1_PDT000576396.1' already exists. Skipping...
Folder 'GCA_008293395.1_PDT000576395.1' already exists. Skipping...
Folder 'GCA_008293415.1_PDT000576488.1' already exists. Skipping...
Folder 'GCA_008293435.1_PDT000576493.1' already exists. Skipping...
Folder 'GCA_008293455.1_PDT000576497.1' already exists. Skipping...
Folder 'GCA_008293515.1_PDT000576441.1' already exists. Skipping...
Folder 'GCA_008293555.1_PDT000576435.1' already exists. Skipping...
Folder 'GCA_008293575.1_PDT000576449.1' already exists. Skipping...
Folder 'GCA_008293595.1_PDT000576433.1' already exists. Skipping...
Folder 'GCA_008293635.1_PDT000576438.1' already exists. Skipping...
Folder 'GCA_008293695.1_PDT000576444.1' already exists. Skipping...
Folder 'GCA_008293755.1_PDT000576475.1' already exists. Skipping...
Folder 'GCA_008293815.1_PDT000576477.1' already exists. Skipping...
Folder 'GCA_008293835.1_PDT000576521.1' already exists. Skipping...
Folder 'GCA_008293855.1_PDT000576496.1' already exists. Skipping...
Folder 'GCA_008293875.1_PDT000576528.1' already exists. Skipping...
Folder 'GCA_008293895.1_PDT000576501.1' already exists. Skipping...
Folder 'GCA_008293935.1_PDT000576502.1' already exists. Skipping...
Folder 'GCA_008293955.1_PDT000576527.1' already exists. Skipping...
Folder 'GCA_008293975.1_PDT000576540.1' already exists. Skipping...
Folder 'GCA_008293995.1_PDT000576532.1' already exists. Skipping...
Folder 'GCA_008294015.1_PDT000576499.1' already exists. Skipping...
Folder 'GCA_008294095.1_PDT000576480.1' already exists. Skipping...
Folder 'GCA_008294195.1_PDT000576564.1' already exists. Skipping...
Folder 'GCA_008294215.1_PDT000576456.1' already exists. Skipping...
Folder 'GCA_008294275.1_PDT000576430.1' already exists. Skipping...
Folder 'GCA_008294315.1_PDT000576462.1' already exists. Skipping...
Folder 'GCA_008294355.1_PDT000576473.1' already exists. Skipping...
Folder 'GCA_008294375.1_PDT000576487.1' already exists. Skipping...
Folder 'GCA_008294475.1_PDT000576485.1' already exists. Skipping...
Folder 'GCA_008294575.1_PDT000576474.1' already exists. Skipping...
Folder 'GCA_008294655.1_PDT000576529.1' already exists. Skipping...
Folder 'GCA_008294715.1_PDT000576552.1' already exists. Skipping...
Folder 'GCA_008294755.1_PDT000576518.1' already exists. Skipping...
Folder 'GCA_008294855.1_PDT000576526.1' already exists. Skipping...
Folder 'GCA_008294875.1_PDT000576508.1' already exists. Skipping...
Folder 'GCA_008294895.1_PDT000576478.1' already exists. Skipping...
Folder 'GCA_008294915.1_PDT000576554.1' already exists. Skipping...
Folder 'GCA_008294975.1_PDT000576463.1' already exists. Skipping...
Folder 'GCA_008295075.1_PDT000576288.1' already exists. Skipping...
Folder 'GCA_008295095.1_PDT000576289.1' already exists. Skipping...
Folder 'GCA_008295115.1_PDT000577147.1' already exists. Skipping...
Folder 'GCA_008295135.1_PDT000577112.1' already exists. Skipping...
Folder 'GCA_008295155.1_PDT000577128.1' already exists. Skipping...
Folder 'GCA_008295195.1_PDT000577082.1' already exists. Skipping...
Folder 'GCA_008295215.1_PDT000577070.1' already exists. Skipping...
Folder 'GCA_008295235.1_PDT000577118.1' already exists. Skipping...
Folder 'GCA_008295255.1_PDT000576548.1' already exists. Skipping...
Folder 'GCA_008295275.1_PDT000576553.1' already exists. Skipping...
Folder 'GCA_008295295.1_PDT000576551.1' already exists. Skipping...
Folder 'GCA_008295335.1_PDT000576541.1' already exists. Skipping...
Folder 'GCA_008295355.1_PDT000576544.1' already exists. Skipping...
Folder 'GCA_008295375.1_PDT000576988.1' already exists. Skipping...
Folder 'GCA_008295395.1_PDT000576556.1' already exists. Skipping...
Folder 'GCA_008295435.1_PDT000576557.1' already exists. Skipping...
Folder 'GCA_008295455.1_PDT000576993.1' already exists. Skipping...
Folder 'GCA_008295475.1_PDT000577085.1' already exists. Skipping...
Folder 'GCA_008295495.1_PDT000576558.1' already exists. Skipping...
Folder 'GCA_008295515.1_PDT000576570.1' already exists. Skipping...
Folder 'GCA_008295555.1_PDT000576562.1' already exists. Skipping...
Folder 'GCA_008295615.1_PDT000576561.1' already exists. Skipping...
Folder 'GCA_008295635.1_PDT000576560.1' already exists. Skipping...
Folder 'GCA_008295675.1_PDT000576563.1' already exists. Skipping...
Folder 'GCA_008295695.1_PDT000576559.1' already exists. Skipping...
Folder 'GCA_008295735.1_PDT000576566.1' already exists. Skipping...
Folder 'GCA_008295755.1_PDT000577055.1' already exists. Skipping...
Folder 'GCA_008295775.1_PDT000576568.1' already exists. Skipping...
Folder 'GCA_008295795.1_PDT000576991.1' already exists. Skipping...
Folder 'GCA_008295815.1_PDT000576574.1' already exists. Skipping...
Folder 'GCA_008295835.1_PDT000576573.1' already exists. Skipping...
Folder 'GCA_008295855.1_PDT000576539.1' already exists. Skipping...
Folder 'GCA_008295895.1_PDT000577054.1' already exists. Skipping...
Folder 'GCA_008295935.1_PDT000577116.1' already exists. Skipping...
Folder 'GCA_008295955.1_PDT000577056.1' already exists. Skipping...
Folder 'GCA_008296015.1_PDT000577115.1' already exists. Skipping...
Folder 'GCA_008296035.1_PDT000577135.1' already exists. Skipping...
Folder 'GCA_008296055.1_PDT000577088.1' already exists. Skipping...
Folder 'GCA_008296075.1_PDT000577108.1' already exists. Skipping...
Folder 'GCA_008296095.1_PDT000577089.1' already exists. Skipping...
Folder 'GCA_008296175.1_PDT000577084.1' already exists. Skipping...
Folder 'GCA_008296195.1_PDT000577125.1' already exists. Skipping...
Folder 'GCA_008296235.1_PDT000577140.1' already exists. Skipping...
Folder 'GCA_008296255.1_PDT000577143.1' already exists. Skipping...
Folder 'GCA_008296275.1_PDT000577106.1' already exists. Skipping...
Folder 'GCA_008296295.1_PDT000577145.1' already exists. Skipping...
Folder 'GCA_008296315.1_PDT000577144.1' already exists. Skipping...
Folder 'GCA_008296335.1_PDT000577129.1' already exists. Skipping...
Folder 'GCA_008296355.1_PDT000577110.1' already exists. Skipping...
Folder 'GCA_008296375.1_PDT000577139.1' already exists. Skipping...
Folder 'GCA_008296415.1_PDT000577062.1' already exists. Skipping...
Folder 'GCA_008296435.1_PDT000577141.1' already exists. Skipping...
Folder 'GCA_008296455.1_PDT000577065.1' already exists. Skipping...
Folder 'GCA_008296475.1_PDT000577075.1' already exists. Skipping...
Folder 'GCA_008296495.1_PDT000577126.1' already exists. Skipping...
Folder 'GCA_008296515.1_PDT000577161.1' already exists. Skipping...
Folder 'GCA_008296535.1_PDT000577132.1' already exists. Skipping...
Folder 'GCA_008296555.1_PDT000577127.1' already exists. Skipping...
Folder 'GCA_008296575.1_PDT000577160.1' already exists. Skipping...
Folder 'GCA_008296595.1_PDT000577066.1' already exists. Skipping...
Folder 'GCA_008296635.1_PDT000577164.1' already exists. Skipping...
Folder 'GCA_008296675.1_PDT000577086.1' already exists. Skipping...
Folder 'GCA_008296695.1_PDT000577130.1' already exists. Skipping...
Folder 'GCA_008296715.1_PDT000577146.1' already exists. Skipping...
Folder 'GCA_008296735.1_PDT000577133.1' already exists. Skipping...
Folder 'GCA_008296755.1_PDT000577254.1' already exists. Skipping...
Folder 'GCA_008296775.1_PDT000577120.1' already exists. Skipping...
Folder 'GCA_008296795.1_PDT000577138.1' already exists. Skipping...
Folder 'GCA_008296835.1_PDT000577136.1' already exists. Skipping...
Folder 'GCA_008296855.1_PDT000577113.1' already exists. Skipping...
Folder 'GCA_008296875.1_PDT000577150.1' already exists. Skipping...
Folder 'GCA_008296915.1_PDT000577156.1' already exists. Skipping...
Folder 'GCA_008296935.1_PDT000577152.1' already exists. Skipping...
Folder 'GCA_008296955.1_PDT000577154.1' already exists. Skipping...
Folder 'GCA_008296975.1_PDT000577159.1' already exists. Skipping...
Folder 'GCA_008296995.1_PDT000577162.1' already exists. Skipping...
Folder 'GCA_008297015.1_PDT000577165.1' already exists. Skipping...
Folder 'GCA_008297035.1_PDT000577158.1' already exists. Skipping...
Folder 'GCA_008297055.1_PDT000577167.1' already exists. Skipping...
Folder 'GCA_008297075.1_PDT000577168.1' already exists. Skipping...
Folder 'GCA_008297095.1_PDT000577169.1' already exists. Skipping...
Folder 'GCA_008297115.1_PDT000577072.1' already exists. Skipping...
Folder 'GCA_008297195.1_PDT000577134.1' already exists. Skipping...
Folder 'GCA_008297215.1_PDT000577230.1' already exists. Skipping...
Folder 'GCA_008297235.1_PDT000577214.1' already exists. Skipping...
Folder 'GCA_008297255.1_PDT000577176.1' already exists. Skipping...
Folder 'GCA_008297315.1_PDT000577215.1' already exists. Skipping...
Folder 'GCA_008298165.1_PDT000579184.1' already exists. Skipping...
Folder 'GCA_008298265.1_PDT000579165.1' already exists. Skipping...
Folder 'GCA_008298365.1_PDT000579182.1' already exists. Skipping...
Folder 'GCA_008298505.1_PDT000579212.1' already exists. Skipping...
Folder 'GCA_008298665.1_PDT000579200.1' already exists. Skipping...
Folder 'GCA_008299065.1_PDT000579214.1' already exists. Skipping...
Folder 'GCA_008299245.1_PDT000579189.1' already exists. Skipping...
Folder 'GCA_008299365.1_PDT000579201.1' already exists. Skipping...
Folder 'GCA_008299405.1_PDT000579155.1' already exists. Skipping...
Folder 'GCA_008299545.1_PDT000579147.1' already exists. Skipping...
Folder 'GCA_008299645.1_PDT000579219.1' already exists. Skipping...
Folder 'GCA_008299725.1_PDT000579148.1' already exists. Skipping...
Folder 'GCA_008299865.1_PDT000579164.1' already exists. Skipping...
Folder 'GCA_008299945.1_PDT000579179.1' already exists. Skipping...
Folder 'GCA_008299985.1_PDT000579160.1' already exists. Skipping...
Folder 'GCA_008300305.1_PDT000579380.1' already exists. Skipping...
Folder 'GCA_008300745.1_PDT000579332.1' already exists. Skipping...
Folder 'GCA_008300925.1_PDT000579378.1' already exists. Skipping...
Folder 'GCA_008301165.1_PDT000579369.1' already exists. Skipping...
Folder 'GCA_008301225.1_PDT000579364.1' already exists. Skipping...
Folder 'GCA_008301325.1_PDT000579383.1' already exists. Skipping...
Folder 'GCA_008301525.1_PDT000579379.1' already exists. Skipping...
Folder 'GCA_008301705.1_PDT000579377.1' already exists. Skipping...
Folder 'GCA_008301845.1_PDT000579324.1' already exists. Skipping...
Folder 'GCA_008301885.1_PDT000579346.1' already exists. Skipping...
Folder 'GCA_008301925.1_PDT000579323.1' already exists. Skipping...
Folder 'GCA_008302005.1_PDT000579371.1' already exists. Skipping...
Folder 'GCA_008302265.1_PDT000579382.1' already exists. Skipping...
Folder 'GCA_008302305.1_PDT000579381.1' already exists. Skipping...
Folder 'GCA_008302465.1_PDT000579595.1' already exists. Skipping...
Folder 'GCA_008302525.1_PDT000579599.1' already exists. Skipping...
Folder 'GCA_008302565.1_PDT000579597.1' already exists. Skipping...
Folder 'GCA_008302605.1_PDT000579601.1' already exists. Skipping...
Folder 'GCA_008302645.1_PDT000579603.1' already exists. Skipping...
Folder 'GCA_008302725.1_PDT000579612.1' already exists. Skipping...
Folder 'GCA_008302765.1_PDT000579592.1' already exists. Skipping...
Folder 'GCA_008302805.1_PDT000579593.1' already exists. Skipping...
Folder 'GCA_008302885.1_PDT000579596.1' already exists. Skipping...
Folder 'GCA_008302905.1_PDT000579598.1' already exists. Skipping...
Folder 'GCA_008302925.1_PDT000579594.1' already exists. Skipping...
Folder 'GCA_008303045.1_PDT000579609.1' already exists. Skipping...
Folder 'GCA_008303205.1_PDT000579600.1' already exists. Skipping...
Folder 'GCA_008303285.1_PDT000579602.1' already exists. Skipping...
Folder 'GCA_008303485.1_PDT000579607.1' already exists. Skipping...
Folder 'GCA_008303505.1_PDT000579450.1' already exists. Skipping...
Folder 'GCA_008303545.1_PDT000579368.1' already exists. Skipping...
Folder 'GCA_008303805.1_PDT000579499.1' already exists. Skipping...
Folder 'GCA_008304655.1_PDT000577153.1' already exists. Skipping...
Folder 'GCA_008304675.1_PDT000577199.1' already exists. Skipping...
Folder 'GCA_008304685.1_PDT000577226.1' already exists. Skipping...
Folder 'GCA_008304715.1_PDT000577151.1' already exists. Skipping...
Folder 'GCA_008304775.1_PDT000577227.1' already exists. Skipping...
Folder 'GCA_008304785.1_PDT000577186.1' already exists. Skipping...
Folder 'GCA_008304815.1_PDT000577190.1' already exists. Skipping...
Folder 'GCA_008304835.1_PDT000577194.1' already exists. Skipping...
Folder 'GCA_008304855.1_PDT000577205.1' already exists. Skipping...
Folder 'GCA_008304875.1_PDT000577207.1' already exists. Skipping...
Folder 'GCA_008304885.1_PDT000577209.1' already exists. Skipping...
Folder 'GCA_008304915.1_PDT000577221.1' already exists. Skipping...
Folder 'GCA_008304935.1_PDT000577264.1' already exists. Skipping...
Folder 'GCA_008304975.1_PDT000577232.1' already exists. Skipping...
Folder 'GCA_008304995.1_PDT000577231.1' already exists. Skipping...
Folder 'GCA_008305075.1_PDT000577236.1' already exists. Skipping...
Folder 'GCA_008305115.1_PDT000577237.1' already exists. Skipping...
Folder 'GCA_008305135.1_PDT000577238.1' already exists. Skipping...
Folder 'GCA_008305155.1_PDT000577239.1' already exists. Skipping...
Folder 'GCA_008305215.1_PDT000577242.1' already exists. Skipping...

Retreiveing data: 61698it [00:10, 6714.85it/s]

Folder 'GCA_008392815.1_PDT000584402.1' already exists. Skipping...
Folder 'GCA_008392875.1_PDT000584406.1' already exists. Skipping...
Folder 'GCA_008392915.1_PDT000584410.1' already exists. Skipping...
Folder 'GCA_008392955.1_PDT000584407.1' already exists. Skipping...
Folder 'GCA_008392975.1_PDT000584414.1' already exists. Skipping...
Folder 'GCA_008393015.1_PDT000584411.1' already exists. Skipping...
Folder 'GCA_008393055.1_PDT000584413.1' already exists. Skipping...
Folder 'GCA_008393075.1_PDT000584419.1' already exists. Skipping...
Folder 'GCA_008393135.1_PDT000584418.1' already exists. Skipping...
Folder 'GCA_008393175.1_PDT000584421.1' already exists. Skipping...
Folder 'GCA_008393195.1_PDT000584425.1' already exists. Skipping...
Folder 'GCA_008393215.1_PDT000584424.1' already exists. Skipping...
Folder 'GCA_008393275.1_PDT000584426.1' already exists. Skipping...
Folder 'GCA_008393295.1_PDT000584430.1' already exists. Skipping...
Folder 'GCA_008394235.1_PDT000584556.1' already exists. Skipping...
Folder 'GCA_008394255.1_PDT000584557.1' already exists. Skipping...
Folder 'GCA_008394315.1_PDT000584558.1' already exists. Skipping...
Folder 'GCA_008394325.1_PDT000584561.1' already exists. Skipping...
Folder 'GCA_008394355.1_PDT000584564.1' already exists. Skipping...
Folder 'GCA_008394375.1_PDT000584567.1' already exists. Skipping...
Folder 'GCA_008394395.1_PDT000584568.1' already exists. Skipping...
Folder 'GCA_008394415.1_PDT000584565.1' already exists. Skipping...
Folder 'GCA_008394645.1_PDT000584594.1' already exists. Skipping...
Folder 'GCA_008395295.1_PDT000584659.1' already exists. Skipping...
Folder 'GCA_008395595.1_PDT000586164.1' already exists. Skipping...
Folder 'GCA_008395635.1_PDT000584812.1' already exists. Skipping...
Folder 'GCA_008395675.1_PDT000584813.1' already exists. Skipping...
Folder 'GCA_008395735.1_PDT000584815.1' already exists. Skipping...
Folder 'GCA_008395795.1_PDT000586212.1' already exists. Skipping...
Folder 'GCA_008395825.1_PDT000584816.1' already exists. Skipping...
Folder 'GCA_008395935.1_PDT000584817.1' already exists. Skipping...
Folder 'GCA_008396115.1_PDT000586154.1' already exists. Skipping...
Folder 'GCA_008396135.1_PDT000586155.1' already exists. Skipping...
Folder 'GCA_008396175.1_PDT000586158.1' already exists. Skipping...
Folder 'GCA_008396195.1_PDT000586157.1' already exists. Skipping...
Folder 'GCA_008397335.1_PDT000585060.1' already exists. Skipping...
Folder 'GCA_008397455.1_PDT000585062.1' already exists. Skipping...
Folder 'GCA_008397515.1_PDT000585064.1' already exists. Skipping...
Folder 'GCA_008397755.1_PDT000586488.1' already exists. Skipping...
Folder 'GCA_008400555.1_PDT000585497.1' already exists. Skipping...
Folder 'GCA_008400635.1_PDT000585509.1' already exists. Skipping...
Folder 'GCA_008400675.1_PDT000585512.1' already exists. Skipping...
Folder 'GCA_008400715.1_PDT000585513.1' already exists. Skipping...
Folder 'GCA_008400855.1_PDT000585526.1' already exists. Skipping...
Folder 'GCA_008400975.1_PDT000585530.1' already exists. Skipping...
Folder 'GCA_008401145.1_PDT000585541.1' already exists. Skipping...
Folder 'GCA_008402305.1_PDT000586024.1' already exists. Skipping...
Folder 'GCA_008402395.1_PDT000586031.1' already exists. Skipping...
Folder 'GCA_008402415.1_PDT000586029.1' already exists. Skipping...
Folder 'GCA_008403365.1_PDT000586127.1' already exists. Skipping...
Folder 'GCA_008403435.1_PDT000586133.1' already exists. Skipping...
Folder 'GCA_008403495.1_PDT000586147.1' already exists. Skipping...
Folder 'GCA_008403545.1_PDT000586143.1' already exists. Skipping...
Folder 'GCA_008403565.1_PDT000586145.1' already exists. Skipping...
Folder 'GCA_008464325.1_PDT000583831.1' already exists. Skipping...
Folder 'GCA_008464505.1_PDT000558185.1' already exists. Skipping...
Folder 'GCA_008465285.1_PDT000586129.1' already exists. Skipping...
Folder 'GCA_008465505.1_PDT000584370.1' already exists. Skipping...
Folder 'GCA_008465545.1_PDT000584415.1' already exists. Skipping...
Folder 'GCA_008465565.1_PDT000584433.1' already exists. Skipping...
Folder 'GCA_008465925.1_PDT000584385.1' already exists. Skipping...
Folder 'GCA_008466105.1_PDT000584566.1' already exists. Skipping...
Folder 'GCA_008466125.1_PDT000585065.1' already exists. Skipping...
Folder 'GCA_008466165.1_PDT000585061.1' already exists. Skipping...
Folder 'GCA_008466385.1_PDT000585507.1' already exists. Skipping...
Folder 'GCA_008466585.1_PDT000585063.1' already exists. Skipping...
Folder 'GCA_008467145.1_PDT000586142.1' already exists. Skipping...
Folder 'GCA_008467325.1_PDT000586128.1' already exists. Skipping...
Folder 'GCA_008485345.1_PDT000199690.2' already exists. Skipping...
Folder 'GCA_008509955.1_PDT000584371.1' already exists. Skipping...
Folder 'GCA_008510555.1_PDT000583838.1' already exists. Skipping...
Folder 'GCA_008511935.1_PDT000584563.1' already exists. Skipping...
Folder 'GCA_008511955.1_PDT000584399.1' already exists. Skipping...
Folder 'GCA_008511995.1_PDT000584389.1' already exists. Skipping...
Folder 'GCA_008512005.1_PDT000584378.1' already exists. Skipping...
Folder 'GCA_008512055.1_PDT000586150.1' already exists. Skipping...
Folder 'GCA_008512255.1_PDT000586030.1' already exists. Skipping...
Folder 'GCA_008512695.1_PDT000585066.1' already exists. Skipping...
Folder 'GCA_008512975.1_PDT000584814.1' already exists. Skipping...
Folder 'GCA_008526675.1_PDT000183012.2' already exists. Skipping...
Folder 'GCA_008541755.1_PDT000584403.1' already exists. Skipping...
Folder 'GCA_008545895.1_PDT000585059.1' already exists. Skipping...
Folder 'GCA_008546115.1_PDT000584388.1' already exists. Skipping...
Folder 'GCA_008546315.1_PDT000584559.1' already exists. Skipping...
Folder 'GCA_008558275.1_PDT000585500.1' already exists. Skipping...
Folder 'GCA_008561795.1_PDT000586990.1' already exists. Skipping...
Folder 'GCA_008561995.1_PDT000586998.1' already exists. Skipping...
Folder 'GCA_008562035.1_PDT000587000.1' already exists. Skipping...
Folder 'GCA_008562095.1_PDT000586978.1' already exists. Skipping...
Folder 'GCA_008562155.1_PDT000586988.1' already exists. Skipping...
Folder 'GCA_008562195.1_PDT000586992.1' already exists. Skipping...
Folder 'GCA_008562435.1_PDT000587007.1' already exists. Skipping...
Folder 'GCA_008562495.1_PDT000586999.1' already exists. Skipping...
Folder 'GCA_008562515.1_PDT000587002.1' already exists. Skipping...
Folder 'GCA_008562525.1_PDT000587001.1' already exists. Skipping...
Folder 'GCA_008562575.1_PDT000587005.1' already exists. Skipping...
Folder 'GCA_008562595.1_PDT000587011.1' already exists. Skipping...
Folder 'GCA_008562675.1_PDT000587018.1' already exists. Skipping...
Folder 'GCA_008562695.1_PDT000587017.1' already exists. Skipping...
Folder 'GCA_008562735.1_PDT000587032.1' already exists. Skipping...
Folder 'GCA_008562795.1_PDT000587038.1' already exists. Skipping...
Folder 'GCA_008562975.1_PDT000587110.1' already exists. Skipping...
Folder 'GCA_008562995.1_PDT000587173.1' already exists. Skipping...
Folder 'GCA_008563075.1_PDT000587107.1' already exists. Skipping...
Folder 'GCA_008563115.1_PDT000587039.1' already exists. Skipping...
Folder 'GCA_008563155.1_PDT000587040.1' already exists. Skipping...
Folder 'GCA_008563175.1_PDT000587033.1' already exists. Skipping...
Folder 'GCA_008563455.1_PDT000586986.1' already exists. Skipping...
Folder 'GCA_008563475.1_PDT000587131.1' already exists. Skipping...
Folder 'GCA_008563495.1_PDT000586983.1' already exists. Skipping...
Folder 'GCA_008563535.1_PDT000586981.1' already exists. Skipping...
Folder 'GCA_008563595.1_PDT000587211.1' already exists. Skipping...
Folder 'GCA_008563915.1_PDT000587175.1' already exists. Skipping...
Folder 'GCA_008564175.1_PDT000587183.1' already exists. Skipping...
Folder 'GCA_008564195.1_PDT000587180.1' already exists. Skipping...
Folder 'GCA_008564435.1_PDT000587204.1' already exists. Skipping...
Folder 'GCA_008564555.1_PDT000587209.1' already exists. Skipping...
Folder 'GCA_008564595.1_PDT000587232.1' already exists. Skipping...
Folder 'GCA_008564835.1_PDT000587244.1' already exists. Skipping...
Folder 'GCA_008564915.2_PDT000587245.3' already exists. Skipping...
Folder 'GCA_008565135.1_PDT000587212.1' already exists. Skipping...
Folder 'GCA_008584805.1_PDT000574138.1' already exists. Skipping...
Folder 'GCA_008584855.1_PDT000577163.1' already exists. Skipping...
Folder 'GCA_008585325.1_PDT000582717.1' already exists. Skipping...
Folder 'GCA_008585385.1_PDT000582720.1' already exists. Skipping...
Folder 'GCA_008585425.1_PDT000582716.1' already exists. Skipping...
Folder 'GCA_008585465.1_PDT000582715.1' already exists. Skipping...
Folder 'GCA_008585655.1_PDT000582723.1' already exists. Skipping...
Folder 'GCA_008585705.1_PDT000582727.1' already exists. Skipping...
Folder 'GCA_008585765.1_PDT000582712.1' already exists. Skipping...
Folder 'GCA_008585805.1_PDT000582711.1' already exists. Skipping...
Folder 'GCA_008586405.1_PDT000586487.1' already exists. Skipping...
Folder 'GCA_008588085.1_PDT000586939.1' already exists. Skipping...
Folder 'GCA_008597205.1_PDT000587771.1' already exists. Skipping...
Folder 'GCA_008597365.1_PDT000587774.1' already exists. Skipping...
Folder 'GCA_008597385.1_PDT000587773.1' already exists. Skipping...
Folder 'GCA_008597425.1_PDT000587775.1' already exists. Skipping...
Folder 'GCA_008597585.1_PDT000587804.1' already exists. Skipping...
Folder 'GCA_008597685.1_PDT000587810.1' already exists. Skipping...
Folder 'GCA_008597725.1_PDT000587812.1' already exists. Skipping...
Folder 'GCA_008597745.1_PDT000587811.1' already exists. Skipping...
Folder 'GCA_008602725.1_PDT000588226.1' already exists. Skipping...
Folder 'GCA_008602745.1_PDT000588224.1' already exists. Skipping...
Folder 'GCA_008602765.1_PDT000588225.1' already exists. Skipping...
Folder 'GCA_008602785.1_PDT000588230.1' already exists. Skipping...
Folder 'GCA_008603065.1_PDT000588234.1' already exists. Skipping...
Folder 'GCA_008603125.1_PDT000588232.1' already exists. Skipping...
Folder 'GCA_008603205.1_PDT000588231.1' already exists. Skipping...
Folder 'GCA_008603225.1_PDT000588235.1' already exists. Skipping...
Folder 'GCA_008603245.1_PDT000588233.1' already exists. Skipping...
Folder 'GCA_008621485.1_PDT000588570.1' already exists. Skipping...
Folder 'GCA_008621535.1_PDT000588572.1' already exists. Skipping...
Folder 'GCA_008621635.1_PDT000588576.1' already exists. Skipping...
Folder 'GCA_008621755.1_PDT000588582.1' already exists. Skipping...
Folder 'GCA_008621775.1_PDT000588581.1' already exists. Skipping...
Folder 'GCA_008621795.1_PDT000588584.1' already exists. Skipping...
Folder 'GCA_008621835.1_PDT000588586.1' already exists. Skipping...
Folder 'GCA_008621885.1_PDT000588588.1' already exists. Skipping...
Folder 'GCA_008622315.1_PDT000588650.1' already exists. Skipping...
Folder 'GCA_008623295.1_PDT000588678.1' already exists. Skipping...
Folder 'GCA_008623315.1_PDT000588677.1' already exists. Skipping...
Folder 'GCA_008623335.1_PDT000588698.1' already exists. Skipping...
Folder 'GCA_008623355.1_PDT000588696.1' already exists. Skipping...
Folder 'GCA_008623375.1_PDT000588697.1' already exists. Skipping...
Folder 'GCA_008623435.1_PDT000588703.1' already exists. Skipping...
Folder 'GCA_008623455.1_PDT000588701.1' already exists. Skipping...
Folder 'GCA_008623475.1_PDT000588699.1' already exists. Skipping...
Folder 'GCA_008623495.1_PDT000588700.1' already exists. Skipping...
Folder 'GCA_008623575.1_PDT000588704.1' already exists. Skipping...
Folder 'GCA_008624795.1_PDT000588853.1' already exists. Skipping...
Folder 'GCA_008625495.1_PDT000588858.1' already exists. Skipping...
Folder 'GCA_008625535.1_PDT000588860.1' already exists. Skipping...
Folder 'GCA_008625555.1_PDT000588863.1' already exists. Skipping...
Folder 'GCA_008625595.1_PDT000588864.1' already exists. Skipping...
Folder 'GCA_008629155.1_PDT000589133.1' already exists. Skipping...
Folder 'GCA_008629195.1_PDT000589135.1' already exists. Skipping...
Folder 'GCA_008629215.1_PDT000589139.1' already exists. Skipping...
Folder 'GCA_008629235.1_PDT000589136.1' already exists. Skipping...
Folder 'GCA_008629255.1_PDT000589134.1' already exists. Skipping...
Folder 'GCA_008629275.1_PDT000589137.1' already exists. Skipping...
Folder 'GCA_008629295.1_PDT000589140.1' already exists. Skipping...
Folder 'GCA_008629315.1_PDT000589138.1' already exists. Skipping...
Folder 'GCA_008629335.1_PDT000589148.1' already exists. Skipping...
Folder 'GCA_008629435.1_PDT000589153.1' already exists. Skipping...
Folder 'GCA_008629475.1_PDT000589150.1' already exists. Skipping...
Folder 'GCA_008629515.1_PDT000589152.1' already exists. Skipping...
Folder 'GCA_008629535.1_PDT000589149.1' already exists. Skipping...
Folder 'GCA_008629555.1_PDT000589154.1' already exists. Skipping...
Folder 'GCA_008629575.1_PDT000589155.1' already exists. Skipping...
Folder 'GCA_008658575.1_PDT000589596.1' already exists. Skipping...
Folder 'GCA_008658595.1_PDT000589329.1' already exists. Skipping...
Folder 'GCA_008658695.1_PDT000589328.1' already exists. Skipping...
Folder 'GCA_008659015.1_PDT000589589.1' already exists. Skipping...
Folder 'GCA_008659035.1_PDT000589593.1' already exists. Skipping...
Folder 'GCA_008659335.1_PDT000589725.1' already exists. Skipping...
Folder 'GCA_008660035.1_PDT000589476.1' already exists. Skipping...
Folder 'GCA_008660275.1_PDT000589485.1' already exists. Skipping...
Folder 'GCA_008660315.1_PDT000589486.1' already exists. Skipping...
Folder 'GCA_008660555.1_PDT000589575.1' already exists. Skipping...
Folder 'GCA_008660575.1_PDT000589576.1' already exists. Skipping...
Folder 'GCA_008660595.1_PDT000589572.1' already exists. Skipping...
Folder 'GCA_008660755.1_PDT000589584.1' already exists. Skipping...
Folder 'GCA_008663955.1_PDT000590108.1' already exists. Skipping...
Folder 'GCA_008666695.1_PDT000590245.1' already exists. Skipping...
Folder 'GCA_008667115.1_PDT000590247.1' already exists. Skipping...
Folder 'GCA_008667195.1_PDT000590248.1' already exists. Skipping...
Folder 'GCA_008670595.1_PDT000590287.1' already exists. Skipping...
Folder 'GCA_008670675.1_PDT000590288.1' already exists. Skipping...
Folder 'GCA_008677825.1_PDT000590360.1' already exists. Skipping...
Folder 'GCA_008677955.1_PDT000590357.1' already exists. Skipping...
Folder 'GCA_008695305.1_PDT000217352.2' already exists. Skipping...
Folder 'GCA_008705655.1_PDT000591343.1' already exists. Skipping...
Folder 'GCA_008706075.1_PDT000591321.1' already exists. Skipping...
Folder 'GCA_008707615.1_PDT000591779.1' already exists. Skipping...
Folder 'GCA_008707635.1_PDT000591781.1' already exists. Skipping...
Folder 'GCA_008707795.1_PDT000591754.1' already exists. Skipping...
Folder 'GCA_008707815.1_PDT000591782.1' already exists. Skipping...
Folder 'GCA_008707835.1_PDT000591783.1' already exists. Skipping...
Folder 'GCA_008707855.1_PDT000591780.1' already exists. Skipping...
Folder 'GCA_008707995.1_PDT000591842.1' already exists. Skipping...
Folder 'GCA_008708135.1_PDT000591843.1' already exists. Skipping...
Folder 'GCA_008708315.1_PDT000591761.1' already exists. Skipping...
Folder 'GCA_008708375.1_PDT000591757.1' already exists. Skipping...
Folder 'GCA_008708615.1_PDT000591784.1' already exists. Skipping...
Folder 'GCA_008708635.1_PDT000591775.1' already exists. Skipping...
Folder 'GCA_008708655.1_PDT000591773.1' already exists. Skipping...
Folder 'GCA_008708695.1_PDT000591786.1' already exists. Skipping...
Folder 'GCA_008708955.1_PDT000591825.1' already exists. Skipping...
Folder 'GCA_008709035.1_PDT000591824.1' already exists. Skipping...
Folder 'GCA_008709155.1_PDT000591863.1' already exists. Skipping...
Folder 'GCA_008709175.1_PDT000591851.1' already exists. Skipping...
Folder 'GCA_008709255.1_PDT000591859.1' already exists. Skipping...
Folder 'GCA_008709275.1_PDT000591858.1' already exists. Skipping...
Folder 'GCA_008709295.1_PDT000591860.1' already exists. Skipping...
Folder 'GCA_008709315.1_PDT000591862.1' already exists. Skipping...
Folder 'GCA_008709375.1_PDT000591883.1' already exists. Skipping...
Folder 'GCA_008709385.1_PDT000591869.1' already exists. Skipping...
Folder 'GCA_008715355.1_PDT000592098.1' already exists. Skipping...
Folder 'GCA_008715435.1_PDT000592105.1' already exists. Skipping...
Folder 'GCA_008715475.1_PDT000592102.1' already exists. Skipping...
Folder 'GCA_008715495.1_PDT000592146.1' already exists. Skipping...
Folder 'GCA_008715515.1_PDT000592109.1' already exists. Skipping...
Folder 'GCA_008715875.1_PDT000592188.1' already exists. Skipping...
Folder 'GCA_008715935.1_PDT000592186.1' already exists. Skipping...
Folder 'GCA_008716135.1_PDT000592108.1' already exists. Skipping...
Folder 'GCA_008716145.1_PDT000592110.1' already exists. Skipping...
Folder 'GCA_008716355.1_PDT000592144.1' already exists. Skipping...
Folder 'GCA_008716675.1_PDT000592178.1' already exists. Skipping...
Folder 'GCA_008716775.1_PDT000592177.1' already exists. Skipping...
Folder 'GCA_008716875.1_PDT000592195.1' already exists. Skipping...
Folder 'GCA_008716895.1_PDT000592180.1' already exists. Skipping...
Folder 'GCA_008716935.1_PDT000592191.1' already exists. Skipping...
Folder 'GCA_008716955.1_PDT000592194.1' already exists. Skipping...
Folder 'GCA_008716995.1_PDT000592196.1' already exists. Skipping...
Folder 'GCA_008717035.1_PDT000592198.1' already exists. Skipping...
Folder 'GCA_008717055.1_PDT000592201.1' already exists. Skipping...
Folder 'GCA_008717075.1_PDT000592199.1' already exists. Skipping...
Folder 'GCA_008717095.1_PDT000592200.1' already exists. Skipping...
Folder 'GCA_008717115.1_PDT000592197.1' already exists. Skipping...
Folder 'GCA_008717135.1_PDT000592202.1' already exists. Skipping...
Folder 'GCA_008717195.1_PDT000592207.1' already exists. Skipping...
Folder 'GCA_008719955.1_PDT000592446.1' already exists. Skipping...
Folder 'GCA_008720315.1_PDT000592467.1' already exists. Skipping...
Folder 'GCA_008721375.1_PDT000592651.1' already exists. Skipping...
Folder 'GCA_008721395.1_PDT000592647.1' already exists. Skipping...
Folder 'GCA_008721405.1_PDT000592652.1' already exists. Skipping...
Folder 'GCA_008721495.1_PDT000592661.1' already exists. Skipping...
Folder 'GCA_008721555.1_PDT000592663.1' already exists. Skipping...
Folder 'GCA_008721595.1_PDT000592664.1' already exists. Skipping...
Folder 'GCA_008721615.1_PDT000592667.1' already exists. Skipping...
Folder 'GCA_008721675.1_PDT000592668.1' already exists. Skipping...
Folder 'GCA_008721715.1_PDT000592670.1' already exists. Skipping...
Folder 'GCA_008721755.1_PDT000592673.1' already exists. Skipping...
Folder 'GCA_008721775.1_PDT000592671.1' already exists. Skipping...
Folder 'GCA_008722155.1_PDT000592677.1' already exists. Skipping...
Folder 'GCA_008722715.1_PDT000592643.1' already exists. Skipping...
Folder 'GCA_008722775.1_PDT000592644.1' already exists. Skipping...
Folder 'GCA_008746015.1_PDT000593717.1' already exists. Skipping...
Folder 'GCA_008746185.1_PDT000593716.1' already exists. Skipping...
Folder 'GCA_008746635.1_PDT000593714.1' already exists. Skipping...
Folder 'GCA_008746675.1_PDT000593713.1' already exists. Skipping...
Folder 'GCA_008746695.1_PDT000593715.1' already exists. Skipping...
Folder 'GCA_008746755.1_PDT000593827.1' already exists. Skipping...
Folder 'GCA_008747415.1_PDT000593761.1' already exists. Skipping...
Folder 'GCA_008748095.1_PDT000593718.1' already exists. Skipping...
Folder 'GCA_008748115.1_PDT000593712.1' already exists. Skipping...
Folder 'GCA_008748395.1_PDT000593757.1' already exists. Skipping...
Folder 'GCA_008748755.1_PDT000593760.1' already exists. Skipping...
Folder 'GCA_008748915.1_PDT000593747.1' already exists. Skipping...
Folder 'GCA_008748975.1_PDT000593759.1' already exists. Skipping...
Folder 'GCA_008764975.1_PDT000596664.1' already exists. Skipping...
Folder 'GCA_008765035.1_PDT000596665.1' already exists. Skipping...
Folder 'GCA_008765055.1_PDT000596667.1' already exists. Skipping...
Folder 'GCA_008765095.1_PDT000596663.1' already exists. Skipping...

Retreiveing data: 63045it [00:10, 6713.08it/s]

Folder 'GCA_009265325.1_PDT000146747.3' already exists. Skipping...
Folder 'GCA_009265345.1_PDT000146773.3' already exists. Skipping...
Folder 'GCA_009265355.1_PDT000146743.3' already exists. Skipping...
Folder 'GCA_009265405.1_PDT000146745.3' already exists. Skipping...
Folder 'GCA_009265425.1_PDT000146769.3' already exists. Skipping...
Folder 'GCA_009265445.1_PDT000146730.3' already exists. Skipping...
Folder 'GCA_009265465.1_PDT000146731.3' already exists. Skipping...
Folder 'GCA_009265525.1_PDT000146774.3' already exists. Skipping...
Folder 'GCA_009265545.1_PDT000146729.3' already exists. Skipping...
Folder 'GCA_009265565.1_PDT000146733.3' already exists. Skipping...
Folder 'GCA_009265585.1_PDT000146723.3' already exists. Skipping...
Folder 'GCA_009265625.1_PDT000146720.3' already exists. Skipping...
Folder 'GCA_009265645.1_PDT000146727.3' already exists. Skipping...
Folder 'GCA_009265665.1_PDT000146724.3' already exists. Skipping...
Folder 'GCA_009265685.1_PDT000146732.3' already exists. Skipping...
Folder 'GCA_009265705.1_PDT000146725.3' already exists. Skipping...
Folder 'GCA_009265725.1_PDT000146722.3' already exists. Skipping...
Folder 'GCA_009265745.1_PDT000146771.3' already exists. Skipping...
Folder 'GCA_009265765.1_PDT000146721.3' already exists. Skipping...
Folder 'GCA_009265785.1_PDT000146718.3' already exists. Skipping...
Folder 'GCA_009265825.1_PDT000146719.3' already exists. Skipping...
Folder 'GCA_009265845.1_PDT000146738.3' already exists. Skipping...
Folder 'GCA_009265885.1_PDT000146734.3' already exists. Skipping...
Folder 'GCA_009265925.1_PDT000146735.3' already exists. Skipping...
Folder 'GCA_009265945.1_PDT000146736.3' already exists. Skipping...
Folder 'GCA_009265985.1_PDT000146741.3' already exists. Skipping...
Folder 'GCA_009266005.1_PDT000146740.3' already exists. Skipping...
Folder 'GCA_009266025.1_PDT000146742.3' already exists. Skipping...
Folder 'GCA_009266045.1_PDT000146746.3' already exists. Skipping...
Folder 'GCA_009266065.1_PDT000146737.3' already exists. Skipping...
Folder 'GCA_009266085.1_PDT000146770.3' already exists. Skipping...
Folder 'GCA_009266105.1_PDT000146726.3' already exists. Skipping...
Folder 'GCA_009266125.1_PDT000146876.3' already exists. Skipping...
Folder 'GCA_009266155.1_PDT000146744.3' already exists. Skipping...
Folder 'GCA_009266185.1_PDT000146877.3' already exists. Skipping...
Folder 'GCA_009266205.1_PDT000146879.3' already exists. Skipping...
Folder 'GCA_009266225.1_PDT000146874.3' already exists. Skipping...
Folder 'GCA_009266245.1_PDT000146878.3' already exists. Skipping...
Folder 'GCA_009266385.1_PDT000146875.3' already exists. Skipping...
Folder 'GCA_009266445.1_PDT000146873.3' already exists. Skipping...
Folder 'GCA_009266465.1_PDT000146950.3' already exists. Skipping...
Folder 'GCA_009266485.1_PDT000146880.3' already exists. Skipping...
Folder 'GCA_009266505.1_PDT000146881.3' already exists. Skipping...
Folder 'GCA_009266525.1_PDT000146947.3' already exists. Skipping...
Folder 'GCA_009266545.1_PDT000146883.3' already exists. Skipping...
Folder 'GCA_009266565.1_PDT000146882.3' already exists. Skipping...
Folder 'GCA_009266585.1_PDT000146885.3' already exists. Skipping...
Folder 'GCA_009266605.1_PDT000146907.3' already exists. Skipping...
Folder 'GCA_009266625.1_PDT000146884.3' already exists. Skipping...
Folder 'GCA_009266645.1_PDT000146913.3' already exists. Skipping...
Folder 'GCA_009266665.1_PDT000146914.3' already exists. Skipping...
Folder 'GCA_009266685.1_PDT000146908.3' already exists. Skipping...
Folder 'GCA_009266705.1_PDT000146915.3' already exists. Skipping...
Folder 'GCA_009266725.1_PDT000146911.3' already exists. Skipping...
Folder 'GCA_009266765.1_PDT000146919.3' already exists. Skipping...
Folder 'GCA_009266785.1_PDT000146916.3' already exists. Skipping...
Folder 'GCA_009266805.1_PDT000146917.3' already exists. Skipping...
Folder 'GCA_009266825.1_PDT000146910.3' already exists. Skipping...
Folder 'GCA_009266845.1_PDT000146918.3' already exists. Skipping...
Folder 'GCA_009266865.1_PDT000146922.3' already exists. Skipping...
Folder 'GCA_009266885.1_PDT000146923.3' already exists. Skipping...
Folder 'GCA_009266905.1_PDT000146924.3' already exists. Skipping...
Folder 'GCA_009266925.1_PDT000146921.3' already exists. Skipping...
Folder 'GCA_009266945.1_PDT000146927.3' already exists. Skipping...
Folder 'GCA_009266965.1_PDT000146926.3' already exists. Skipping...
Folder 'GCA_009266975.1_PDT000146925.3' already exists. Skipping...
Folder 'GCA_009267005.1_PDT000146928.3' already exists. Skipping...
Folder 'GCA_009267015.1_PDT000146929.3' already exists. Skipping...
Folder 'GCA_009267085.1_PDT000146951.3' already exists. Skipping...
Folder 'GCA_009267145.1_PDT000146954.3' already exists. Skipping...
Folder 'GCA_009267165.1_PDT000146952.3' already exists. Skipping...
Folder 'GCA_009267205.1_PDT000146872.3' already exists. Skipping...
Folder 'GCA_009267265.1_PDT000146870.3' already exists. Skipping...
Folder 'GCA_009267285.1_PDT000146871.3' already exists. Skipping...
Folder 'GCA_009267295.1_PDT000146934.3' already exists. Skipping...
Folder 'GCA_009267325.1_PDT000146930.3' already exists. Skipping...
Folder 'GCA_009267355.1_PDT000146955.3' already exists. Skipping...
Folder 'GCA_009267385.1_PDT000146933.3' already exists. Skipping...
Folder 'GCA_009267405.1_PDT000146935.3' already exists. Skipping...
Folder 'GCA_009267425.1_PDT000146938.3' already exists. Skipping...
Folder 'GCA_009267445.1_PDT000146936.3' already exists. Skipping...
Folder 'GCA_009267485.1_PDT000146958.3' already exists. Skipping...
Folder 'GCA_009267505.1_PDT000146959.3' already exists. Skipping...
Folder 'GCA_009267525.1_PDT000146939.3' already exists. Skipping...
Folder 'GCA_009267545.1_PDT000146956.3' already exists. Skipping...
Folder 'GCA_009267565.1_PDT000146957.3' already exists. Skipping...
Folder 'GCA_009267585.1_PDT000146940.3' already exists. Skipping...
Folder 'GCA_009267605.1_PDT000146966.3' already exists. Skipping...
Folder 'GCA_009267625.1_PDT000146965.3' already exists. Skipping...
Folder 'GCA_009267645.1_PDT000146962.3' already exists. Skipping...
Folder 'GCA_009267665.1_PDT000146941.3' already exists. Skipping...
Folder 'GCA_009267685.1_PDT000146961.3' already exists. Skipping...
Folder 'GCA_009267705.1_PDT000146963.3' already exists. Skipping...
Folder 'GCA_009267725.1_PDT000146960.3' already exists. Skipping...
Folder 'GCA_009267765.1_PDT000146968.3' already exists. Skipping...
Folder 'GCA_009267775.1_PDT000146967.3' already exists. Skipping...
Folder 'GCA_009267805.1_PDT000423067.2' already exists. Skipping...
Folder 'GCA_009267825.1_PDT000146972.3' already exists. Skipping...
Folder 'GCA_009267845.1_PDT000146969.3' already exists. Skipping...
Folder 'GCA_009267865.1_PDT000146970.3' already exists. Skipping...
Folder 'GCA_009267885.1_PDT000146977.3' already exists. Skipping...
Folder 'GCA_009267905.1_PDT000146971.3' already exists. Skipping...
Folder 'GCA_009267925.1_PDT000146974.3' already exists. Skipping...
Folder 'GCA_009267945.1_PDT000146978.3' already exists. Skipping...
Folder 'GCA_009267965.1_PDT000146976.3' already exists. Skipping...
Folder 'GCA_009268165.1_ASM926816v1' already exists. Skipping...
Folder 'GCA_009268175.1_ASM926817v1' already exists. Skipping...
Folder 'GCA_009268185.1_ASM926818v1' already exists. Skipping...
Folder 'GCA_009268195.1_ASM926819v1' already exists. Skipping...
Folder 'GCA_009268205.1_ASM926820v1' already exists. Skipping...
Folder 'GCA_009268265.1_ASM926826v1' already exists. Skipping...
Folder 'GCA_009268275.1_ASM926827v1' already exists. Skipping...
Folder 'GCA_009268285.1_ASM926828v1' already exists. Skipping...
Folder 'GCA_009268305.1_ASM926830v1' already exists. Skipping...
Folder 'GCA_009268325.1_ASM926832v1' already exists. Skipping...
Folder 'GCA_009268365.1_ASM926836v1' already exists. Skipping...
Folder 'GCA_009268385.1_ASM926838v1' already exists. Skipping...
Folder 'GCA_009268395.1_ASM926839v1' already exists. Skipping...
Folder 'GCA_009268415.1_ASM926841v1' already exists. Skipping...
Folder 'GCA_009268425.1_ASM926842v1' already exists. Skipping...
Folder 'GCA_009268465.1_ASM926846v1' already exists. Skipping...
Folder 'GCA_009268475.1_ASM926847v1' already exists. Skipping...
Folder 'GCA_009268495.1_ASM926849v1' already exists. Skipping...
Folder 'GCA_009268515.1_ASM926851v1' already exists. Skipping...
Folder 'GCA_009268525.1_ASM926852v1' already exists. Skipping...
Folder 'GCA_009268565.1_ASM926856v1' already exists. Skipping...
Folder 'GCA_009268585.1_ASM926858v1' already exists. Skipping...
Folder 'GCA_009268595.1_ASM926859v1' already exists. Skipping...
Folder 'GCA_009268605.1_ASM926860v1' already exists. Skipping...
Folder 'GCA_009268635.1_ASM926863v1' already exists. Skipping...
Folder 'GCA_009268665.1_ASM926866v1' already exists. Skipping...
Folder 'GCA_009268675.1_ASM926867v1' already exists. Skipping...
Folder 'GCA_009268705.1_ASM926870v1' already exists. Skipping...
Folder 'GCA_009268715.1_ASM926871v1' already exists. Skipping...
Folder 'GCA_009268725.1_ASM926872v1' already exists. Skipping...
Folder 'GCA_009268765.1_ASM926876v1' already exists. Skipping...
Folder 'GCA_009268785.1_ASM926878v1' already exists. Skipping...
Folder 'GCA_009268805.1_ASM926880v1' already exists. Skipping...
Folder 'GCA_009268815.1_ASM926881v1' already exists. Skipping...
Folder 'GCA_009268845.1_ASM926884v1' already exists. Skipping...
Folder 'GCA_009268855.1_ASM926885v1' already exists. Skipping...
Folder 'GCA_009268885.1_ASM926888v1' already exists. Skipping...
Folder 'GCA_009268905.1_ASM926890v1' already exists. Skipping...
Folder 'GCA_009268915.1_ASM926891v1' already exists. Skipping...
Folder 'GCA_009268935.1_ASM926893v1' already exists. Skipping...
Folder 'GCA_009268945.1_ASM926894v1' already exists. Skipping...
Folder 'GCA_009268985.1_ASM926898v1' already exists. Skipping...
Folder 'GCA_009269005.1_ASM926900v1' already exists. Skipping...
Folder 'GCA_009269015.1_ASM926901v1' already exists. Skipping...
Folder 'GCA_009269025.1_ASM926902v1' already exists. Skipping...
Folder 'GCA_009269065.1_ASM926906v1' already exists. Skipping...
Folder 'GCA_009269085.1_ASM926908v1' already exists. Skipping...
Folder 'GCA_009269105.1_ASM926910v1' already exists. Skipping...
Folder 'GCA_009269115.1_ASM926911v1' already exists. Skipping...
Folder 'GCA_009269135.1_ASM926913v1' already exists. Skipping...
Folder 'GCA_009269145.1_ASM926914v1' already exists. Skipping...
Folder 'GCA_009269185.1_ASM926918v1' already exists. Skipping...
Folder 'GCA_009269205.1_ASM926920v1' already exists. Skipping...
Folder 'GCA_009269215.1_ASM926921v1' already exists. Skipping...
Folder 'GCA_009269235.1_ASM926923v1' already exists. Skipping...
Folder 'GCA_009269245.1_ASM926924v1' already exists. Skipping...
Folder 'GCA_009269275.1_ASM926927v1' already exists. Skipping...
Folder 'GCA_009269305.1_ASM926930v1' already exists. Skipping...
Folder 'GCA_009269315.1_ASM926931v1' already exists. Skipping...
Folder 'GCA_009269325.1_ASM926932v1' already exists. Skipping...
Folder 'GCA_009269345.1_ASM926934v1' already exists. Skipping...
Folder 'GCA_009269375.1_ASM926937v1' already exists. Skipping...
Folder 'GCA_009269405.1_ASM926940v1' already exists. Skipping...
Folder 'GCA_009269415.1_ASM926941v1' already exists. Skipping...
Folder 'GCA_009269425.1_ASM926942v1' already exists. Skipping...
Folder 'GCA_009269435.1_ASM926943v1' already exists. Skipping...
Folder 'GCA_009269475.1_ASM926947v1' already exists. Skipping...
Folder 'GCA_009269505.1_ASM926950v1' already exists. Skipping...
Folder 'GCA_009269525.1_ASM926952v1' already exists. Skipping...
Folder 'GCA_009269535.1_ASM926953v1' already exists. Skipping...
Folder 'GCA_009269545.1_ASM926954v1' already exists. Skipping...
Folder 'GCA_009269575.1_ASM926957v1' already exists. Skipping...
Folder 'GCA_009269605.1_ASM926960v1' already exists. Skipping...
Folder 'GCA_009269625.1_ASM926962v1' already exists. Skipping...
Folder 'GCA_009269635.1_ASM926963v1' already exists. Skipping...
Folder 'GCA_009269655.1_ASM926965v1' already exists. Skipping...
Folder 'GCA_009269665.1_ASM926966v1' already exists. Skipping...
Folder 'GCA_009269705.1_ASM926970v1' already exists. Skipping...
Folder 'GCA_009269725.1_ASM926972v1' already exists. Skipping...
Folder 'GCA_009269745.1_ASM926974v1' already exists. Skipping...
Folder 'GCA_009269765.1_ASM926976v1' already exists. Skipping...
Folder 'GCA_009269775.1_ASM926977v1' already exists. Skipping...
Folder 'GCA_009269805.1_ASM926980v1' already exists. Skipping...
Folder 'GCA_009269825.1_ASM926982v1' already exists. Skipping...
Folder 'GCA_009269835.1_ASM926983v1' already exists. Skipping...
Folder 'GCA_009269865.1_ASM926986v1' already exists. Skipping...
Folder 'GCA_009269885.1_ASM926988v1' already exists. Skipping...
Folder 'GCA_009269895.1_ASM926989v1' already exists. Skipping...
Folder 'GCA_009269925.1_ASM926992v1' already exists. Skipping...
Folder 'GCA_009269935.1_ASM926993v1' already exists. Skipping...
Folder 'GCA_009269965.1_ASM926996v1' already exists. Skipping...
Folder 'GCA_009269975.1_ASM926997v1' already exists. Skipping...
Folder 'GCA_009270005.1_ASM927000v1' already exists. Skipping...
Folder 'GCA_009270025.1_ASM927002v1' already exists. Skipping...
Folder 'GCA_009270045.1_ASM927004v1' already exists. Skipping...
Folder 'GCA_009270055.1_ASM927005v1' already exists. Skipping...
Folder 'GCA_009270075.1_ASM927007v1' already exists. Skipping...
Folder 'GCA_009270095.1_ASM927009v1' already exists. Skipping...
Folder 'GCA_009270105.1_ASM927010v1' already exists. Skipping...
Folder 'GCA_009270145.1_ASM927014v1' already exists. Skipping...
Folder 'GCA_009270155.1_ASM927015v1' already exists. Skipping...
Folder 'GCA_009270185.1_ASM927018v1' already exists. Skipping...
Folder 'GCA_009270195.1_ASM927019v1' already exists. Skipping...
Folder 'GCA_009270205.1_ASM927020v1' already exists. Skipping...
Folder 'GCA_009270245.1_ASM927024v1' already exists. Skipping...
Folder 'GCA_009270255.1_ASM927025v1' already exists. Skipping...
Folder 'GCA_009270285.1_ASM927028v1' already exists. Skipping...
Folder 'GCA_009270295.1_ASM927029v1' already exists. Skipping...
Folder 'GCA_009270325.1_ASM927032v1' already exists. Skipping...
Folder 'GCA_009270345.1_ASM927034v1' already exists. Skipping...
Folder 'GCA_009270355.1_ASM927035v1' already exists. Skipping...
Folder 'GCA_009270385.1_ASM927038v1' already exists. Skipping...
Folder 'GCA_009270395.1_ASM927039v1' already exists. Skipping...
Folder 'GCA_009270415.1_ASM927041v1' already exists. Skipping...
Folder 'GCA_009270445.1_ASM927044v1' already exists. Skipping...
Folder 'GCA_009270455.1_ASM927045v1' already exists. Skipping...
Folder 'GCA_009272085.1_ASM927208v1' already exists. Skipping...
Folder 'GCA_009272095.1_ASM927209v1' already exists. Skipping...
Folder 'GCA_009302495.1_PDT000609586.1' already exists. Skipping...
Folder 'GCA_009343355.1_PDT000616294.1' already exists. Skipping...
Folder 'GCA_009343555.1_PDT000616303.1' already exists. Skipping...
Folder 'GCA_009343575.1_PDT000616295.1' already exists. Skipping...
Folder 'GCA_009343755.1_PDT000616415.1' already exists. Skipping...
Folder 'GCA_009343775.1_PDT000616412.1' already exists. Skipping...
Folder 'GCA_009343815.1_PDT000616418.1' already exists. Skipping...
Folder 'GCA_009343895.1_PDT000616420.1' already exists. Skipping...
Folder 'GCA_009343915.1_PDT000616419.1' already exists. Skipping...
Folder 'GCA_009343935.1_PDT000616421.1' already exists. Skipping...
Folder 'GCA_009343955.1_PDT000616422.1' already exists. Skipping...
Folder 'GCA_009344055.1_PDT000616464.1' already exists. Skipping...
Folder 'GCA_009345175.1_PDT000616210.1' already exists. Skipping...
Folder 'GCA_009345235.1_PDT000616208.1' already exists. Skipping...
Folder 'GCA_009345345.1_PDT000616213.1' already exists. Skipping...
Folder 'GCA_009346355.1_PDT000616572.1' already exists. Skipping...
Folder 'GCA_009346375.1_PDT000616569.1' already exists. Skipping...
Folder 'GCA_009346425.1_PDT000616570.1' already exists. Skipping...
Folder 'GCA_009346455.1_PDT000616571.1' already exists. Skipping...
Folder 'GCA_009346475.1_PDT000616574.1' already exists. Skipping...
Folder 'GCA_009349835.1_PDT000617096.1' already exists. Skipping...
Folder 'GCA_009349875.1_PDT000616286.1' already exists. Skipping...
Folder 'GCA_009350655.1_PDT000616284.1' already exists. Skipping...
Folder 'GCA_009350695.1_PDT000616289.1' already exists. Skipping...
Folder 'GCA_009350735.1_PDT000617095.1' already exists. Skipping...
Folder 'GCA_009350755.1_PDT000617099.1' already exists. Skipping...
Folder 'GCA_009350775.1_PDT000617097.1' already exists. Skipping...
Folder 'GCA_009350815.1_PDT000617092.1' already exists. Skipping...
Folder 'GCA_009351115.1_PDT000617012.1' already exists. Skipping...
Folder 'GCA_009351195.1_PDT000617091.1' already exists. Skipping...
Folder 'GCA_009351235.1_PDT000617098.1' already exists. Skipping...
Folder 'GCA_009351255.1_PDT000617011.1' already exists. Skipping...
Folder 'GCA_009354815.1_PDT000617088.1' already exists. Skipping...
Folder 'GCA_009354835.1_PDT000617087.1' already exists. Skipping...
Folder 'GCA_009355685.1_PDT000617155.1' already exists. Skipping...
Folder 'GCA_009356595.1_PDT000617141.1' already exists. Skipping...
Folder 'GCA_009356655.1_PDT000617152.1' already exists. Skipping...
Folder 'GCA_009356675.1_PDT000617148.1' already exists. Skipping...
Folder 'GCA_009356695.1_PDT000617151.1' already exists. Skipping...
Folder 'GCA_009356715.1_PDT000617150.1' already exists. Skipping...
Folder 'GCA_009356735.1_PDT000617153.1' already exists. Skipping...
Folder 'GCA_009356775.1_PDT000617149.1' already exists. Skipping...
Folder 'GCA_009358075.1_PDT000617664.1' already exists. Skipping...
Folder 'GCA_009358205.1_PDT000617663.1' already exists. Skipping...
Folder 'GCA_009358395.1_PDT000617714.1' already exists. Skipping...
Folder 'GCA_009358415.1_PDT000617710.1' already exists. Skipping...
Folder 'GCA_009358435.1_PDT000617711.1' already exists. Skipping...
Folder 'GCA_009358455.1_PDT000617712.1' already exists. Skipping...
Folder 'GCA_009358475.1_PDT000617716.1' already exists. Skipping...
Folder 'GCA_009358495.1_PDT000617713.1' already exists. Skipping...
Folder 'GCA_009358505.1_PDT000617715.1' already exists. Skipping...
Folder 'GCA_009358535.1_PDT000617717.1' already exists. Skipping...
Folder 'GCA_009358555.1_PDT000617718.1' already exists. Skipping...
Folder 'GCA_009358575.1_PDT000617719.1' already exists. Skipping...
Folder 'GCA_009358595.1_PDT000617722.1' already exists. Skipping...
Folder 'GCA_009358635.1_PDT000617720.1' already exists. Skipping...
Folder 'GCA_009358655.1_PDT000617721.1' already exists. Skipping...
Folder 'GCA_009359615.1_PDT000617705.1' already exists. Skipping...
Folder 'GCA_009359635.1_PDT000617707.1' already exists. Skipping...
Folder 'GCA_009359655.1_PDT000617706.1' already exists. Skipping...
Folder 'GCA_009359675.1_PDT000617708.1' already exists. Skipping...
Folder 'GCA_009359695.1_PDT000617709.1' already exists. Skipping...
Folder 'GCA_009371015.1_PDT000617758.1' already exists. Skipping...
Folder 'GCA_009375315.1_PDT000617229.1' already exists. Skipping...
Folder 'GCA_009382055.1_PDT000617917.1' already exists. Skipping...
Folder 'GCA_009382575.1_PDT000617919.1' already exists. Skipping...
Folder 'GCA_009385075.1_PDT000618148.1' already exists. Skipping...
Folder 'GCA_009385095.1_PDT000618133.1' already exists. Skipping...
Folder 'GCA_009385135.1_PDT000618147.1' already exists. Skipping...
Folder 'GCA_009385155.1_PDT000618132.1' already exists. Skipping...
Folder 'GCA_009385175.1_PDT000618146.1' already exists. Skipping...
Folder 'GCA_009385195.1_PDT000618136.1' already exists. Skipping...
Folder 'GCA_009385215.1_PDT000618171.1' already exists. Skipping...
Folder 'GCA_009385235.1_PDT000618139.1' already exists. Skipping...
Folder 'GCA_009385295.1_PDT000618143.1' already exists. Skipping...
Folder 'GCA_009385315.1_PDT000618135.1' already exists. Skipping...

Retreiveing data: 64394it [00:11, 6727.52it/s]

Folder 'GCA_010281885.1_PDT000636546.1' already exists. Skipping...
Folder 'GCA_010281905.1_PDT000646224.1' already exists. Skipping...
Folder 'GCA_010281915.1_PDT000639067.1' already exists. Skipping...
Folder 'GCA_010281945.1_PDT000636604.1' already exists. Skipping...
Folder 'GCA_010281955.1_PDT000639403.1' already exists. Skipping...
Folder 'GCA_010281965.1_PDT000567251.1' already exists. Skipping...
Folder 'GCA_010281975.1_PDT000563186.1' already exists. Skipping...
Folder 'GCA_010281985.1_PDT000563125.1' already exists. Skipping...
Folder 'GCA_010282045.1_PDT000563159.1' already exists. Skipping...
Folder 'GCA_010282065.1_PDT000563259.1' already exists. Skipping...
Folder 'GCA_010282075.1_PDT000563164.1' already exists. Skipping...
Folder 'GCA_010282085.1_PDT000563139.1' already exists. Skipping...
Folder 'GCA_010282095.1_PDT000567249.1' already exists. Skipping...
Folder 'GCA_010282145.1_PDT000563136.1' already exists. Skipping...
Folder 'GCA_010282165.1_PDT000563270.1' already exists. Skipping...
Folder 'GCA_010282175.1_PDT000563220.1' already exists. Skipping...
Folder 'GCA_010282185.1_PDT000558297.1' already exists. Skipping...
Folder 'GCA_010282225.1_PDT000563160.1' already exists. Skipping...
Folder 'GCA_010282245.1_PDT000563147.1' already exists. Skipping...
Folder 'GCA_010282265.1_PDT000563275.1' already exists. Skipping...
Folder 'GCA_010282275.1_PDT000567255.1' already exists. Skipping...
Folder 'GCA_010282285.1_PDT000563155.1' already exists. Skipping...
Folder 'GCA_010282325.1_PDT000563169.1' already exists. Skipping...
Folder 'GCA_010282345.1_PDT000563287.1' already exists. Skipping...
Folder 'GCA_010282355.1_PDT000563152.1' already exists. Skipping...
Folder 'GCA_010282385.1_PDT000563283.1' already exists. Skipping...
Folder 'GCA_010282405.1_PDT000563106.1' already exists. Skipping...
Folder 'GCA_010282425.1_PDT000563299.1' already exists. Skipping...
Folder 'GCA_010282435.1_PDT000562542.1' already exists. Skipping...
Folder 'GCA_010282465.1_PDT000563222.1' already exists. Skipping...
Folder 'GCA_010282485.1_PDT000563184.1' already exists. Skipping...
Folder 'GCA_010282505.1_PDT000563191.1' already exists. Skipping...
Folder 'GCA_010282525.1_PDT000563304.1' already exists. Skipping...
Folder 'GCA_010282545.1_PDT000563248.1' already exists. Skipping...
Folder 'GCA_010282565.1_PDT000563253.1' already exists. Skipping...
Folder 'GCA_010282585.1_PDT000562818.1' already exists. Skipping...
Folder 'GCA_010282605.1_PDT000562903.1' already exists. Skipping...
Folder 'GCA_010282625.1_PDT000563313.1' already exists. Skipping...
Folder 'GCA_010282645.1_PDT000563308.1' already exists. Skipping...
Folder 'GCA_010282665.1_PDT000562907.1' already exists. Skipping...
Folder 'GCA_010282685.1_PDT000563260.1' already exists. Skipping...
Folder 'GCA_010282705.1_PDT000563276.1' already exists. Skipping...
Folder 'GCA_010282715.1_PDT000563317.1' already exists. Skipping...
Folder 'GCA_010282745.1_PDT000563266.1' already exists. Skipping...
Folder 'GCA_010282755.1_PDT000563274.1' already exists. Skipping...
Folder 'GCA_010282785.1_PDT000563278.1' already exists. Skipping...
Folder 'GCA_010282805.1_PDT000563108.1' already exists. Skipping...
Folder 'GCA_010282825.1_PDT000563272.1' already exists. Skipping...
Folder 'GCA_010282845.1_PDT000563282.1' already exists. Skipping...
Folder 'GCA_010282865.1_PDT000563196.1' already exists. Skipping...
Folder 'GCA_010282885.1_PDT000563280.1' already exists. Skipping...
Folder 'GCA_010282905.1_PDT000563286.1' already exists. Skipping...
Folder 'GCA_010282915.1_PDT000563292.1' already exists. Skipping...
Folder 'GCA_010282945.1_PDT000563325.1' already exists. Skipping...
Folder 'GCA_010282965.1_PDT000563284.1' already exists. Skipping...
Folder 'GCA_010282985.1_PDT000563121.1' already exists. Skipping...
Folder 'GCA_010283005.1_PDT000563126.1' already exists. Skipping...
Folder 'GCA_010283025.1_PDT000563329.1' already exists. Skipping...
Folder 'GCA_010283045.1_PDT000563288.1' already exists. Skipping...
Folder 'GCA_010283065.1_PDT000563298.1' already exists. Skipping...
Folder 'GCA_010291125.1_PDT000563135.1' already exists. Skipping...
Folder 'GCA_010291165.1_PDT000563242.1' already exists. Skipping...
Folder 'GCA_010291185.1_PDT000563142.1' already exists. Skipping...
Folder 'GCA_010291205.1_PDT000563123.1' already exists. Skipping...
Folder 'GCA_010291225.1_PDT000562815.1' already exists. Skipping...
Folder 'GCA_010291245.1_PDT000562902.1' already exists. Skipping...
Folder 'GCA_010291265.1_PDT000563281.1' already exists. Skipping...
Folder 'GCA_010291285.1_PDT000563120.1' already exists. Skipping...
Folder 'GCA_010291305.1_PDT000562540.1' already exists. Skipping...
Folder 'GCA_010291325.1_PDT000562541.1' already exists. Skipping...
Folder 'GCA_010291345.1_PDT000563285.1' already exists. Skipping...
Folder 'GCA_010291365.1_PDT000562909.1' already exists. Skipping...
Folder 'GCA_010291385.1_PDT000562908.1' already exists. Skipping...
Folder 'GCA_010291405.1_PDT000563149.1' already exists. Skipping...
Folder 'GCA_010291425.1_PDT000563134.1' already exists. Skipping...
Folder 'GCA_010291445.1_PDT000563300.1' already exists. Skipping...
Folder 'GCA_010291465.1_PDT000562904.1' already exists. Skipping...
Folder 'GCA_010291485.1_PDT000562906.1' already exists. Skipping...
Folder 'GCA_010291505.1_PDT000562911.1' already exists. Skipping...
Folder 'GCA_010291525.1_PDT000563156.1' already exists. Skipping...
Folder 'GCA_010291545.1_PDT000563165.1' already exists. Skipping...
Folder 'GCA_010291565.1_PDT000563119.1' already exists. Skipping...
Folder 'GCA_010291585.1_PDT000563141.1' already exists. Skipping...
Folder 'GCA_010291605.1_PDT000563124.1' already exists. Skipping...
Folder 'GCA_010291625.1_PDT000563138.1' already exists. Skipping...
Folder 'GCA_010291645.1_PDT000563133.1' already exists. Skipping...
Folder 'GCA_010291665.1_PDT000563144.1' already exists. Skipping...
Folder 'GCA_010291685.1_PDT000563148.1' already exists. Skipping...
Folder 'GCA_010291705.1_PDT000563254.1' already exists. Skipping...
Folder 'GCA_010291725.1_PDT000563153.1' already exists. Skipping...
Folder 'GCA_010291745.1_PDT000563140.1' already exists. Skipping...
Folder 'GCA_010291765.1_PDT000563173.1' already exists. Skipping...
Folder 'GCA_010291785.1_PDT000563269.1' already exists. Skipping...
Folder 'GCA_010291805.1_PDT000563146.1' already exists. Skipping...
Folder 'GCA_010291825.1_PDT000563150.1' already exists. Skipping...
Folder 'GCA_010291845.1_PDT000563166.1' already exists. Skipping...
Folder 'GCA_010291865.1_PDT000563209.1' already exists. Skipping...
Folder 'GCA_010291885.1_PDT000563162.1' already exists. Skipping...
Folder 'GCA_010291905.1_PDT000563170.1' already exists. Skipping...
Folder 'GCA_010291925.1_PDT000563179.1' already exists. Skipping...
Folder 'GCA_010291945.1_PDT000563185.1' already exists. Skipping...
Folder 'GCA_010291965.1_PDT000563190.1' already exists. Skipping...
Folder 'GCA_010291985.1_PDT000563247.1' already exists. Skipping...
Folder 'GCA_010292005.1_PDT000563171.1' already exists. Skipping...
Folder 'GCA_010292015.1_PDT000563181.1' already exists. Skipping...
Folder 'GCA_010292045.1_PDT000563188.1' already exists. Skipping...
Folder 'GCA_010292065.1_PDT000563202.1' already exists. Skipping...
Folder 'GCA_010292085.1_PDT000563177.1' already exists. Skipping...
Folder 'GCA_010292105.1_PDT000563199.1' already exists. Skipping...
Folder 'GCA_010292125.1_PDT000563206.1' already exists. Skipping...
Folder 'GCA_010292145.1_PDT000563182.1' already exists. Skipping...
Folder 'GCA_010292165.1_PDT000563197.1' already exists. Skipping...
Folder 'GCA_010292185.1_PDT000563193.1' already exists. Skipping...
Folder 'GCA_010292205.1_PDT000563194.1' already exists. Skipping...
Folder 'GCA_010292225.1_PDT000563189.1' already exists. Skipping...
Folder 'GCA_010292245.1_PDT000563218.1' already exists. Skipping...
Folder 'GCA_010292265.1_PDT000563211.1' already exists. Skipping...
Folder 'GCA_010292285.1_PDT000563204.1' already exists. Skipping...
Folder 'GCA_010292305.1_PDT000563229.1' already exists. Skipping...
Folder 'GCA_010292325.1_PDT000563234.1' already exists. Skipping...
Folder 'GCA_010292345.1_PDT000563244.1' already exists. Skipping...
Folder 'GCA_010292365.1_PDT000563200.1' already exists. Skipping...
Folder 'GCA_010292385.1_PDT000563205.1' already exists. Skipping...
Folder 'GCA_010292405.1_PDT000563210.1' already exists. Skipping...
Folder 'GCA_010292425.1_PDT000563249.1' already exists. Skipping...
Folder 'GCA_010292445.1_PDT000563238.1' already exists. Skipping...
Folder 'GCA_010292465.1_PDT000563233.1' already exists. Skipping...
Folder 'GCA_010292485.1_PDT000563215.1' already exists. Skipping...
Folder 'GCA_010292505.1_PDT000563214.1' already exists. Skipping...
Folder 'GCA_010292525.1_PDT000563257.1' already exists. Skipping...
Folder 'GCA_010292545.1_PDT000563228.1' already exists. Skipping...
Folder 'GCA_010292565.1_PDT000563273.1' already exists. Skipping...
Folder 'GCA_010292585.1_PDT000563322.1' already exists. Skipping...
Folder 'GCA_010292605.1_PDT000563237.1' already exists. Skipping...
Folder 'GCA_010292615.1_PDT000563318.1' already exists. Skipping...
Folder 'GCA_010292645.1_PDT000563305.1' already exists. Skipping...
Folder 'GCA_010292665.1_PDT000563225.1' already exists. Skipping...
Folder 'GCA_010292685.1_PDT000563295.1' already exists. Skipping...
Folder 'GCA_010292725.1_PDT000563232.1' already exists. Skipping...
Folder 'GCA_010296125.1_PDT000563151.1' already exists. Skipping...
Folder 'GCA_010296165.1_PDT000563279.1' already exists. Skipping...
Folder 'GCA_010296225.1_PDT000563174.1' already exists. Skipping...
Folder 'GCA_010296245.1_PDT000563268.1' already exists. Skipping...
Folder 'GCA_010296265.1_PDT000563212.1' already exists. Skipping...
Folder 'GCA_010296285.1_PDT000563307.1' already exists. Skipping...
Folder 'GCA_010296305.1_PDT000563192.1' already exists. Skipping...
Folder 'GCA_010296325.1_PDT000563294.1' already exists. Skipping...
Folder 'GCA_010296345.1_PDT000563301.1' already exists. Skipping...
Folder 'GCA_010296365.1_PDT000563246.1' already exists. Skipping...
Folder 'GCA_010296385.1_PDT000563236.1' already exists. Skipping...
Folder 'GCA_010296405.1_PDT000563302.1' already exists. Skipping...
Folder 'GCA_010296425.1_PDT000563309.1' already exists. Skipping...
Folder 'GCA_010296445.1_PDT000628208.1' already exists. Skipping...
Folder 'GCA_010296465.1_PDT000628204.1' already exists. Skipping...
Folder 'GCA_010296485.1_PDT000628200.1' already exists. Skipping...
Folder 'GCA_010296505.1_PDT000627525.1' already exists. Skipping...
Folder 'GCA_010296525.1_PDT000628212.1' already exists. Skipping...
Folder 'GCA_010296545.1_PDT000628459.1' already exists. Skipping...
Folder 'GCA_010296565.1_PDT000628315.1' already exists. Skipping...
Folder 'GCA_010296585.1_PDT000628325.1' already exists. Skipping...
Folder 'GCA_010296605.1_PDT000627496.1' already exists. Skipping...
Folder 'GCA_010296625.1_PDT000628478.1' already exists. Skipping...
Folder 'GCA_010296645.1_PDT000628454.1' already exists. Skipping...
Folder 'GCA_010296665.1_PDT000628507.1' already exists. Skipping...
Folder 'GCA_010296685.1_PDT000628495.1' already exists. Skipping...
Folder 'GCA_010296705.1_PDT000628517.1' already exists. Skipping...
Folder 'GCA_010296725.1_PDT000626607.1' already exists. Skipping...
Folder 'GCA_010296745.1_PDT000628521.1' already exists. Skipping...
Folder 'GCA_010296765.1_PDT000629660.1' already exists. Skipping...
Folder 'GCA_010296785.1_PDT000629635.1' already exists. Skipping...
Folder 'GCA_010296825.1_PDT000629761.1' already exists. Skipping...
Folder 'GCA_010296845.1_PDT000629739.1' already exists. Skipping...
Folder 'GCA_010296865.1_PDT000629789.1' already exists. Skipping...
Folder 'GCA_010296905.1_PDT000563240.1' already exists. Skipping...
Folder 'GCA_010296925.1_PDT000563252.1' already exists. Skipping...
Folder 'GCA_010297005.1_PDT000563203.1' already exists. Skipping...
Folder 'GCA_010297025.1_PDT000563158.1' already exists. Skipping...
Folder 'GCA_010297045.1_PDT000563231.1' already exists. Skipping...
Folder 'GCA_010297085.1_PDT000563180.1' already exists. Skipping...
Folder 'GCA_010297105.1_PDT000567253.1' already exists. Skipping...
Folder 'GCA_010297205.1_PDT000567262.1' already exists. Skipping...
Folder 'GCA_010297225.1_PDT000563176.1' already exists. Skipping...
Folder 'GCA_010297265.1_PDT000563198.1' already exists. Skipping...
Folder 'GCA_010297285.1_PDT000563219.1' already exists. Skipping...
Folder 'GCA_010297305.1_PDT000563239.1' already exists. Skipping...
Folder 'GCA_010297345.1_PDT000563277.1' already exists. Skipping...
Folder 'GCA_010297365.1_PDT000563251.1' already exists. Skipping...
Folder 'GCA_010297385.1_PDT000563161.1' already exists. Skipping...
Folder 'GCA_010297405.1_PDT000629827.1' already exists. Skipping...
Folder 'GCA_010297425.1_PDT000629831.1' already exists. Skipping...
Folder 'GCA_010297885.1_PDT000625247.1' already exists. Skipping...
Folder 'GCA_010298145.1_PDT000625166.1' already exists. Skipping...
Folder 'GCA_010298245.1_PDT000626596.1' already exists. Skipping...
Folder 'GCA_010298265.1_PDT000625234.1' already exists. Skipping...
Folder 'GCA_010298645.1_PDT000625238.1' already exists. Skipping...
Folder 'GCA_010298685.1_PDT000625243.1' already exists. Skipping...
Folder 'GCA_010298765.1_PDT000626613.1' already exists. Skipping...
Folder 'GCA_010298825.1_PDT000627010.1' already exists. Skipping...
Folder 'GCA_010298865.1_PDT000625167.1' already exists. Skipping...
Folder 'GCA_010298905.1_PDT000625235.1' already exists. Skipping...
Folder 'GCA_010298945.1_PDT000625244.1' already exists. Skipping...
Folder 'GCA_010298965.1_PDT000626605.1' already exists. Skipping...
Folder 'GCA_010298985.1_PDT000626621.1' already exists. Skipping...
Folder 'GCA_010299005.1_PDT000627197.1' already exists. Skipping...
Folder 'GCA_010299015.1_PDT000625240.1' already exists. Skipping...
Folder 'GCA_010299045.1_PDT000625248.1' already exists. Skipping...
Folder 'GCA_010299055.1_PDT000627204.1' already exists. Skipping...
Folder 'GCA_010299085.1_PDT000567155.1' already exists. Skipping...
Folder 'GCA_010299105.1_PDT000567163.1' already exists. Skipping...
Folder 'GCA_010299115.1_PDT000567151.1' already exists. Skipping...
Folder 'GCA_010299145.1_PDT000563375.1' already exists. Skipping...
Folder 'GCA_010299165.1_PDT000567138.1' already exists. Skipping...
Folder 'GCA_010299185.1_PDT000563365.1' already exists. Skipping...
Folder 'GCA_010299205.1_PDT000563389.1' already exists. Skipping...
Folder 'GCA_010299225.1_PDT000563380.1' already exists. Skipping...
Folder 'GCA_010299245.1_PDT000567184.1' already exists. Skipping...
Folder 'GCA_010299255.1_PDT000567178.1' already exists. Skipping...
Folder 'GCA_010299285.1_PDT000563466.1' already exists. Skipping...
Folder 'GCA_010299305.1_PDT000563515.1' already exists. Skipping...
Folder 'GCA_010299325.1_PDT000563371.1' already exists. Skipping...
Folder 'GCA_010299345.1_PDT000567174.1' already exists. Skipping...
Folder 'GCA_010299365.1_PDT000567196.1' already exists. Skipping...
Folder 'GCA_010299385.1_PDT000567118.1' already exists. Skipping...
Folder 'GCA_010299405.1_PDT000567123.1' already exists. Skipping...
Folder 'GCA_010299425.1_PDT000563672.1' already exists. Skipping...
Folder 'GCA_010299445.1_PDT000567205.1' already exists. Skipping...
Folder 'GCA_010299465.1_PDT000567210.1' already exists. Skipping...
Folder 'GCA_010299485.1_PDT000563509.1' already exists. Skipping...
Folder 'GCA_010299505.1_PDT000563168.1' already exists. Skipping...
Folder 'GCA_010299525.1_PDT000567147.1' already exists. Skipping...
Folder 'GCA_010299545.1_PDT000563361.1' already exists. Skipping...
Folder 'GCA_010299565.1_PDT000567158.1' already exists. Skipping...
Folder 'GCA_010299585.1_PDT000563245.1' already exists. Skipping...
Folder 'GCA_010299605.1_PDT000567162.1' already exists. Skipping...
Folder 'GCA_010299625.1_PDT000567154.1' already exists. Skipping...
Folder 'GCA_010299645.1_PDT000563328.1' already exists. Skipping...
Folder 'GCA_010299655.1_PDT000563310.1' already exists. Skipping...
Folder 'GCA_010299685.1_PDT000567166.1' already exists. Skipping...
Folder 'GCA_010299705.1_PDT000567181.1' already exists. Skipping...
Folder 'GCA_010299725.1_PDT000563323.1' already exists. Skipping...
Folder 'GCA_010299745.1_PDT000563316.1' already exists. Skipping...
Folder 'GCA_010299765.1_PDT000567177.1' already exists. Skipping...
Folder 'GCA_010299785.1_PDT000563333.1' already exists. Skipping...
Folder 'GCA_010299805.1_PDT000563449.1' already exists. Skipping...
Folder 'GCA_010299825.1_PDT000563343.1' already exists. Skipping...
Folder 'GCA_010299845.1_PDT000567189.1' already exists. Skipping...
Folder 'GCA_010299865.1_PDT000567195.1' already exists. Skipping...
Folder 'GCA_010299885.1_PDT000563338.1' already exists. Skipping...
Folder 'GCA_010299905.1_PDT000567204.1' already exists. Skipping...
Folder 'GCA_010299925.1_PDT000563366.1' already exists. Skipping...
Folder 'GCA_010299945.1_PDT000567199.1' already exists. Skipping...
Folder 'GCA_010299965.1_PDT000563357.1' already exists. Skipping...
Folder 'GCA_010299975.1_PDT000567120.1' already exists. Skipping...
Folder 'GCA_010300005.1_PDT000563399.1' already exists. Skipping...
Folder 'GCA_010300025.1_PDT000563348.1' already exists. Skipping...
Folder 'GCA_010300045.1_PDT000567209.1' already exists. Skipping...
Folder 'GCA_010300065.1_PDT000563362.1' already exists. Skipping...
Folder 'GCA_010300085.1_PDT000567219.1' already exists. Skipping...
Folder 'GCA_010300095.1_PDT000563381.1' already exists. Skipping...
Folder 'GCA_010300125.1_PDT000567225.1' already exists. Skipping...
Folder 'GCA_010300145.1_PDT000563372.1' already exists. Skipping...
Folder 'GCA_010300165.1_PDT000567230.1' already exists. Skipping...
Folder 'GCA_010300185.1_PDT000563376.1' already exists. Skipping...
Folder 'GCA_010300205.1_PDT000563385.1' already exists. Skipping...
Folder 'GCA_010300225.1_PDT000567238.1' already exists. Skipping...
Folder 'GCA_010300235.1_PDT000567243.1' already exists. Skipping...
Folder 'GCA_010300245.1_PDT000563332.1' already exists. Skipping...
Folder 'GCA_010300255.1_PDT000563235.1' already exists. Skipping...
Folder 'GCA_010300265.1_PDT000567385.1' already exists. Skipping...
Folder 'GCA_010300325.1_PDT000563306.1' already exists. Skipping...
Folder 'GCA_010300345.1_PDT000563405.1' already exists. Skipping...
Folder 'GCA_010300365.1_PDT000563315.1' already exists. Skipping...
Folder 'GCA_010300375.1_PDT000563400.1' already exists. Skipping...
Folder 'GCA_010300405.1_PDT000563321.1' already exists. Skipping...
Folder 'GCA_010300425.1_PDT000563417.1' already exists. Skipping...
Folder 'GCA_010300435.1_PDT000563337.1' already exists. Skipping...
Folder 'GCA_010300465.1_PDT000563327.1' already exists. Skipping...
Folder 'GCA_010300485.1_PDT000563430.1' already exists. Skipping...
Folder 'GCA_010300505.1_PDT000563395.1' already exists. Skipping...
Folder 'GCA_010300525.1_PDT000563422.1' already exists. Skipping...
Folder 'GCA_010300545.1_PDT000563342.1' already exists. Skipping...
Folder 'GCA_010300565.1_PDT000563351.1' already exists. Skipping...
Folder 'GCA_010300585.1_PDT000563346.1' already exists. Skipping...
Folder 'GCA_010300605.1_PDT000563426.1' already exists. Skipping...
Folder 'GCA_010300625.1_PDT000563356.1' already exists. Skipping...
Folder 'GCA_010300645.1_PDT000563384.1' already exists. Skipping...
Folder 'GCA_010300685.1_PDT000563678.1' already exists. Skipping...
Folder 'GCA_010300705.1_PDT000628201.1' already exists. Skipping...
Folder 'GCA_010300725.1_PDT000627939.1' already exists. Skipping...
Folder 'GCA_010300765.1_PDT000627609.1' already exists. Skipping...
Folder 'GCA_010300825.1_PDT000627445.1' already exists. Skipping...
Folder 'GCA_010300845.1_PDT000625232.1' already exists. Skipping...
Folder 'GCA_010300885.1_PDT000627464.1' already exists. Skipping...
Folder 'GCA_010300905.1_PDT000627326.1' already exists. Skipping...

Retreiveing data: 65737it [00:11, 6680.81it/s]

Folder 'GCA_010322985.1_PDT000567616.1' already exists. Skipping...
Folder 'GCA_010323005.1_PDT000567619.1' already exists. Skipping...
Folder 'GCA_010323025.1_PDT000567624.1' already exists. Skipping...
Folder 'GCA_010323045.1_PDT000567676.1' already exists. Skipping...
Folder 'GCA_010323065.1_PDT000567652.1' already exists. Skipping...
Folder 'GCA_010323085.1_PDT000567635.1' already exists. Skipping...
Folder 'GCA_010323105.1_PDT000567609.1' already exists. Skipping...
Folder 'GCA_010323125.1_PDT000567697.1' already exists. Skipping...
Folder 'GCA_010323135.1_PDT000567687.1' already exists. Skipping...
Folder 'GCA_010323145.1_PDT000567539.1' already exists. Skipping...
Folder 'GCA_010323185.1_PDT000567471.1' already exists. Skipping...
Folder 'GCA_010323205.1_PDT000567435.1' already exists. Skipping...
Folder 'GCA_010323225.1_PDT000567461.1' already exists. Skipping...
Folder 'GCA_010323245.1_PDT000567520.1' already exists. Skipping...
Folder 'GCA_010323265.1_PDT000567530.1' already exists. Skipping...
Folder 'GCA_010323285.1_PDT000568200.1' already exists. Skipping...
Folder 'GCA_010323305.1_PDT000567579.1' already exists. Skipping...
Folder 'GCA_010323325.1_PDT000568210.1' already exists. Skipping...
Folder 'GCA_010323345.1_PDT000567585.1' already exists. Skipping...
Folder 'GCA_010323365.1_PDT000568198.1' already exists. Skipping...
Folder 'GCA_010323385.1_PDT000567569.1' already exists. Skipping...
Folder 'GCA_010323405.1_PDT000568201.1' already exists. Skipping...
Folder 'GCA_010323425.1_PDT000568214.1' already exists. Skipping...
Folder 'GCA_010323445.1_PDT000567602.1' already exists. Skipping...
Folder 'GCA_010323465.1_PDT000567593.1' already exists. Skipping...
Folder 'GCA_010323485.1_PDT000567608.1' already exists. Skipping...
Folder 'GCA_010323505.1_PDT000567632.1' already exists. Skipping...
Folder 'GCA_010323525.1_PDT000567621.1' already exists. Skipping...
Folder 'GCA_010323545.1_PDT000568206.1' already exists. Skipping...
Folder 'GCA_010323565.1_PDT000568205.1' already exists. Skipping...
Folder 'GCA_010323585.1_PDT000567629.1' already exists. Skipping...
Folder 'GCA_010323605.1_PDT000567634.1' already exists. Skipping...
Folder 'GCA_010323625.1_PDT000567612.1' already exists. Skipping...
Folder 'GCA_010323645.1_PDT000567636.1' already exists. Skipping...
Folder 'GCA_010323665.1_PDT000568209.1' already exists. Skipping...
Folder 'GCA_010323685.1_PDT000567642.1' already exists. Skipping...
Folder 'GCA_010323705.1_PDT000567646.1' already exists. Skipping...
Folder 'GCA_010323725.1_PDT000567637.1' already exists. Skipping...
Folder 'GCA_010323745.1_PDT000567641.1' already exists. Skipping...
Folder 'GCA_010323765.1_PDT000567653.1' already exists. Skipping...
Folder 'GCA_010323785.1_PDT000567649.1' already exists. Skipping...
Folder 'GCA_010323805.1_PDT000567662.1' already exists. Skipping...
Folder 'GCA_010323825.1_PDT000567651.1' already exists. Skipping...
Folder 'GCA_010323845.1_PDT000567658.1' already exists. Skipping...
Folder 'GCA_010323865.1_PDT000567647.1' already exists. Skipping...
Folder 'GCA_010323885.1_PDT000568202.1' already exists. Skipping...
Folder 'GCA_010323905.1_PDT000567643.1' already exists. Skipping...
Folder 'GCA_010323925.1_PDT000567669.1' already exists. Skipping...
Folder 'GCA_010323945.1_PDT000567670.1' already exists. Skipping...
Folder 'GCA_010323965.1_PDT000568204.1' already exists. Skipping...
Folder 'GCA_010323985.1_PDT000567657.1' already exists. Skipping...
Folder 'GCA_010324005.1_PDT000567663.1' already exists. Skipping...
Folder 'GCA_010324025.1_PDT000567660.1' already exists. Skipping...
Folder 'GCA_010324045.1_PDT000567664.1' already exists. Skipping...
Folder 'GCA_010324065.1_PDT000567654.1' already exists. Skipping...
Folder 'GCA_010324085.1_PDT000568208.1' already exists. Skipping...
Folder 'GCA_010324105.1_PDT000567675.1' already exists. Skipping...
Folder 'GCA_010324125.1_PDT000567681.1' already exists. Skipping...
Folder 'GCA_010324135.1_PDT000567680.1' already exists. Skipping...
Folder 'GCA_010324165.1_PDT000567673.1' already exists. Skipping...
Folder 'GCA_010324185.1_PDT000567690.1' already exists. Skipping...
Folder 'GCA_010324205.1_PDT000567689.1' already exists. Skipping...
Folder 'GCA_010324225.1_PDT000568171.1' already exists. Skipping...
Folder 'GCA_010324245.1_PDT000568173.1' already exists. Skipping...
Folder 'GCA_010324265.1_PDT000567692.1' already exists. Skipping...
Folder 'GCA_010324285.1_PDT000568174.1' already exists. Skipping...
Folder 'GCA_010324305.1_PDT000568177.1' already exists. Skipping...
Folder 'GCA_010324325.1_PDT000568176.1' already exists. Skipping...
Folder 'GCA_010324345.1_PDT000568178.1' already exists. Skipping...
Folder 'GCA_010324365.1_PDT000568181.1' already exists. Skipping...
Folder 'GCA_010324385.1_PDT000568185.1' already exists. Skipping...
Folder 'GCA_010324405.1_PDT000568180.1' already exists. Skipping...
Folder 'GCA_010324425.1_PDT000568182.1' already exists. Skipping...
Folder 'GCA_010324445.1_PDT000568191.1' already exists. Skipping...
Folder 'GCA_010324465.1_PDT000568187.1' already exists. Skipping...
Folder 'GCA_010324485.1_PDT000568190.1' already exists. Skipping...
Folder 'GCA_010324505.1_PDT000568186.1' already exists. Skipping...
Folder 'GCA_010324525.1_PDT000568197.1' already exists. Skipping...
Folder 'GCA_010324545.1_PDT000568220.1' already exists. Skipping...
Folder 'GCA_010324565.1_PDT000568195.1' already exists. Skipping...
Folder 'GCA_010324575.1_PDT000568192.1' already exists. Skipping...
Folder 'GCA_010324605.1_PDT000568226.1' already exists. Skipping...
Folder 'GCA_010324625.1_PDT000568215.1' already exists. Skipping...
Folder 'GCA_010324645.1_PDT000568212.1' already exists. Skipping...
Folder 'GCA_010324665.1_PDT000568230.1' already exists. Skipping...
Folder 'GCA_010324685.1_PDT000568218.1' already exists. Skipping...
Folder 'GCA_010324695.1_PDT000568222.1' already exists. Skipping...
Folder 'GCA_010324725.1_PDT000568227.1' already exists. Skipping...
Folder 'GCA_010324745.1_PDT000568229.1' already exists. Skipping...
Folder 'GCA_010324765.1_PDT000568231.1' already exists. Skipping...
Folder 'GCA_010324785.1_PDT000568234.1' already exists. Skipping...
Folder 'GCA_010324805.1_PDT000568241.1' already exists. Skipping...
Folder 'GCA_010324825.1_PDT000568253.1' already exists. Skipping...
Folder 'GCA_010324845.1_PDT000568236.1' already exists. Skipping...
Folder 'GCA_010324865.1_PDT000568258.1' already exists. Skipping...
Folder 'GCA_010324885.1_PDT000568438.1' already exists. Skipping...
Folder 'GCA_010324905.1_PDT000568442.1' already exists. Skipping...
Folder 'GCA_010324925.1_PDT000568445.1' already exists. Skipping...
Folder 'GCA_010324945.1_PDT000568443.1' already exists. Skipping...
Folder 'GCA_010324965.1_PDT000568434.1' already exists. Skipping...
Folder 'GCA_010324985.1_PDT000568435.1' already exists. Skipping...
Folder 'GCA_010325005.1_PDT000568352.1' already exists. Skipping...
Folder 'GCA_010325025.1_PDT000568357.1' already exists. Skipping...
Folder 'GCA_010325045.1_PDT000568370.1' already exists. Skipping...
Folder 'GCA_010325055.1_PDT000568451.1' already exists. Skipping...
Folder 'GCA_010325085.1_PDT000568366.1' already exists. Skipping...
Folder 'GCA_010325105.1_PDT000568362.1' already exists. Skipping...
Folder 'GCA_010325125.1_PDT000568378.1' already exists. Skipping...
Folder 'GCA_010325145.1_PDT000568382.1' already exists. Skipping...
Folder 'GCA_010325165.1_PDT000568354.1' already exists. Skipping...
Folder 'GCA_010325185.1_PDT000568448.1' already exists. Skipping...
Folder 'GCA_010325205.1_PDT000568374.1' already exists. Skipping...
Folder 'GCA_010325225.1_PDT000568459.1' already exists. Skipping...
Folder 'GCA_010325245.1_PDT000568390.1' already exists. Skipping...
Folder 'GCA_010325265.1_PDT000568453.1' already exists. Skipping...
Folder 'GCA_010325285.1_PDT000568455.1' already exists. Skipping...
Folder 'GCA_010325305.1_PDT000568395.1' already exists. Skipping...
Folder 'GCA_010325325.1_PDT000568386.1' already exists. Skipping...
Folder 'GCA_010325345.1_PDT000568367.1' already exists. Skipping...
Folder 'GCA_010325365.1_PDT000568363.1' already exists. Skipping...
Folder 'GCA_010325385.1_PDT000568399.1' already exists. Skipping...
Folder 'GCA_010325405.1_PDT000568361.1' already exists. Skipping...
Folder 'GCA_010325425.1_PDT000568372.1' already exists. Skipping...
Folder 'GCA_010325445.1_PDT000568355.1' already exists. Skipping...
Folder 'GCA_010325465.1_PDT000568383.1' already exists. Skipping...
Folder 'GCA_010325475.1_PDT000568371.1' already exists. Skipping...
Folder 'GCA_010325505.1_PDT000568365.1' already exists. Skipping...
Folder 'GCA_010325525.1_PDT000568375.1' already exists. Skipping...
Folder 'GCA_010325545.1_PDT000568369.1' already exists. Skipping...
Folder 'GCA_010325565.1_PDT000568379.1' already exists. Skipping...
Folder 'GCA_010325585.1_PDT000568387.1' already exists. Skipping...
Folder 'GCA_010325605.1_PDT000568368.1' already exists. Skipping...
Folder 'GCA_010325625.1_PDT000568430.1' already exists. Skipping...
Folder 'GCA_010325645.1_PDT000568373.1' already exists. Skipping...
Folder 'GCA_010325665.1_PDT000568376.1' already exists. Skipping...
Folder 'GCA_010325685.1_PDT000568441.1' already exists. Skipping...
Folder 'GCA_010325705.1_PDT000568384.1' already exists. Skipping...
Folder 'GCA_010325725.1_PDT000568381.1' already exists. Skipping...
Folder 'GCA_010325745.1_PDT000568391.1' already exists. Skipping...
Folder 'GCA_010325765.1_PDT000568377.1' already exists. Skipping...
Folder 'GCA_010325785.1_PDT000568380.1' already exists. Skipping...
Folder 'GCA_010325805.1_PDT000568396.1' already exists. Skipping...
Folder 'GCA_010325825.1_PDT000568389.1' already exists. Skipping...
Folder 'GCA_010325845.1_PDT000568388.1' already exists. Skipping...
Folder 'GCA_010325865.1_PDT000568385.1' already exists. Skipping...
Folder 'GCA_010325885.1_PDT000568401.1' already exists. Skipping...
Folder 'GCA_010325905.1_PDT000568411.1' already exists. Skipping...
Folder 'GCA_010325925.1_PDT000568392.1' already exists. Skipping...
Folder 'GCA_010325945.1_PDT000568397.1' already exists. Skipping...
Folder 'GCA_010325965.1_PDT000568420.1' already exists. Skipping...
Folder 'GCA_010325985.1_PDT000568403.1' already exists. Skipping...
Folder 'GCA_010326005.1_PDT000568406.1' already exists. Skipping...
Folder 'GCA_010326025.1_PDT000568393.1' already exists. Skipping...
Folder 'GCA_010326045.1_PDT000568433.1' already exists. Skipping...
Folder 'GCA_010326055.1_PDT000568427.1' already exists. Skipping...
Folder 'GCA_010326065.1_PDT000568413.1' already exists. Skipping...
Folder 'GCA_010326105.1_PDT000568398.1' already exists. Skipping...
Folder 'GCA_010326125.1_PDT000568421.1' already exists. Skipping...
Folder 'GCA_010326145.1_PDT000568407.1' already exists. Skipping...
Folder 'GCA_010326165.1_PDT000568416.1' already exists. Skipping...
Folder 'GCA_010326185.1_PDT000568425.1' already exists. Skipping...
Folder 'GCA_010326205.1_PDT000568463.1' already exists. Skipping...
Folder 'GCA_010326225.1_PDT000568428.1' already exists. Skipping...
Folder 'GCA_010326245.1_PDT000568452.1' already exists. Skipping...
Folder 'GCA_010326265.1_PDT000568437.1' already exists. Skipping...
Folder 'GCA_010326285.1_PDT000568461.1' already exists. Skipping...
Folder 'GCA_010326305.1_PDT000568447.1' already exists. Skipping...
Folder 'GCA_010326325.1_PDT000568465.1' already exists. Skipping...
Folder 'GCA_010326345.1_PDT000568467.1' already exists. Skipping...
Folder 'GCA_010326365.1_PDT000568458.1' already exists. Skipping...
Folder 'GCA_010326385.1_PDT000568469.1' already exists. Skipping...
Folder 'GCA_010326405.1_PDT000568476.1' already exists. Skipping...
Folder 'GCA_010326425.1_PDT000568471.1' already exists. Skipping...
Folder 'GCA_010326445.1_PDT000568480.1' already exists. Skipping...
Folder 'GCA_010326465.1_PDT000568474.1' already exists. Skipping...
Folder 'GCA_010326485.1_PDT000567598.1' already exists. Skipping...
Folder 'GCA_010326505.1_PDT000567617.1' already exists. Skipping...
Folder 'GCA_010326525.1_PDT000568307.1' already exists. Skipping...
Folder 'GCA_010326545.1_PDT000567712.1' already exists. Skipping...
Folder 'GCA_010326565.1_PDT000567633.1' already exists. Skipping...
Folder 'GCA_010326585.1_PDT000568269.1' already exists. Skipping...
Folder 'GCA_010326605.1_PDT000567645.1' already exists. Skipping...
Folder 'GCA_010326625.1_PDT000568179.1' already exists. Skipping...
Folder 'GCA_010326645.1_PDT000568233.1' already exists. Skipping...
Folder 'GCA_010326665.1_PDT000567650.1' already exists. Skipping...
Folder 'GCA_010326685.1_PDT000567674.1' already exists. Skipping...
Folder 'GCA_010326705.1_PDT000568217.1' already exists. Skipping...
Folder 'GCA_010326725.1_PDT000568175.1' already exists. Skipping...
Folder 'GCA_010326735.1_PDT000568292.1' already exists. Skipping...
Folder 'GCA_010326765.1_PDT000568301.1' already exists. Skipping...
Folder 'GCA_010326785.1_PDT000568239.1' already exists. Skipping...
Folder 'GCA_010326805.1_PDT000568242.1' already exists. Skipping...
Folder 'GCA_010326825.1_PDT000568193.1' already exists. Skipping...
Folder 'GCA_010326845.1_PDT000568211.1' already exists. Skipping...
Folder 'GCA_010326865.1_PDT000568228.1' already exists. Skipping...
Folder 'GCA_010326885.1_PDT000568247.1' already exists. Skipping...
Folder 'GCA_010326905.1_PDT000568265.1' already exists. Skipping...
Folder 'GCA_010326925.1_PDT000568256.1' already exists. Skipping...
Folder 'GCA_010326945.1_PDT000568245.1' already exists. Skipping...
Folder 'GCA_010326965.1_PDT000568246.1' already exists. Skipping...
Folder 'GCA_010326985.1_PDT000568252.1' already exists. Skipping...
Folder 'GCA_010327005.1_PDT000568275.1' already exists. Skipping...
Folder 'GCA_010327025.1_PDT000568262.1' already exists. Skipping...
Folder 'GCA_010327045.1_PDT000568274.1' already exists. Skipping...
Folder 'GCA_010327065.1_PDT000568290.1' already exists. Skipping...
Folder 'GCA_010327085.1_PDT000568261.1' already exists. Skipping...
Folder 'GCA_010327105.1_PDT000568249.1' already exists. Skipping...
Folder 'GCA_010327125.1_PDT000568238.1' already exists. Skipping...
Folder 'GCA_010327145.1_PDT000568250.1' already exists. Skipping...
Folder 'GCA_010327165.1_PDT000568259.1' already exists. Skipping...
Folder 'GCA_010327185.1_PDT000568255.1' already exists. Skipping...
Folder 'GCA_010327205.1_PDT000568283.1' already exists. Skipping...
Folder 'GCA_010327225.1_PDT000568267.1' already exists. Skipping...
Folder 'GCA_010327245.1_PDT000568279.1' already exists. Skipping...
Folder 'GCA_010327265.1_PDT000568268.1' already exists. Skipping...
Folder 'GCA_010327285.1_PDT000568278.1' already exists. Skipping...
Folder 'GCA_010327305.1_PDT000568271.1' already exists. Skipping...
Folder 'GCA_010327325.1_PDT000568289.1' already exists. Skipping...
Folder 'GCA_010327345.1_PDT000568295.1' already exists. Skipping...
Folder 'GCA_010327365.1_PDT000568282.1' already exists. Skipping...
Folder 'GCA_010327385.1_PDT000568277.1' already exists. Skipping...
Folder 'GCA_010327405.1_PDT000568281.1' already exists. Skipping...
Folder 'GCA_010327425.1_PDT000568313.1' already exists. Skipping...
Folder 'GCA_010327445.1_PDT000568294.1' already exists. Skipping...
Folder 'GCA_010327465.1_PDT000567575.1' already exists. Skipping...
Folder 'GCA_010327485.1_PDT000568302.1' already exists. Skipping...
Folder 'GCA_010327505.1_PDT000568304.1' already exists. Skipping...
Folder 'GCA_010327525.1_PDT000568297.1' already exists. Skipping...
Folder 'GCA_010327545.1_PDT000568288.1' already exists. Skipping...
Folder 'GCA_010327565.1_PDT000568309.1' already exists. Skipping...
Folder 'GCA_010327585.1_PDT000568188.1' already exists. Skipping...
Folder 'GCA_010327605.1_PDT000568310.1' already exists. Skipping...
Folder 'GCA_010327625.1_PDT000568203.1' already exists. Skipping...
Folder 'GCA_010327645.1_PDT000567668.1' already exists. Skipping...
Folder 'GCA_010327665.1_PDT000568183.1' already exists. Skipping...
Folder 'GCA_010327685.1_PDT000568199.1' already exists. Skipping...
Folder 'GCA_010327705.1_PDT000567655.1' already exists. Skipping...
Folder 'GCA_010327725.1_PDT000568223.1' already exists. Skipping...
Folder 'GCA_010327745.1_PDT000568235.1' already exists. Skipping...
Folder 'GCA_010327765.1_PDT000567638.1' already exists. Skipping...
Folder 'GCA_010327785.1_PDT000567683.1' already exists. Skipping...
Folder 'GCA_010327805.1_PDT000568207.1' already exists. Skipping...
Folder 'GCA_010327825.1_PDT000568317.1' already exists. Skipping...
Folder 'GCA_010327845.1_PDT000568315.1' already exists. Skipping...
Folder 'GCA_010327865.1_PDT000568316.1' already exists. Skipping...
Folder 'GCA_010327885.1_PDT000568323.1' already exists. Skipping...
Folder 'GCA_010327905.1_PDT000568322.1' already exists. Skipping...
Folder 'GCA_010327925.1_PDT000568326.1' already exists. Skipping...
Folder 'GCA_010327945.1_PDT000568225.1' already exists. Skipping...
Folder 'GCA_010327965.1_PDT000568237.1' already exists. Skipping...
Folder 'GCA_010327985.1_PDT000568330.1' already exists. Skipping...
Folder 'GCA_010328005.1_PDT000568324.1' already exists. Skipping...
Folder 'GCA_010328025.1_PDT000568306.1' already exists. Skipping...
Folder 'GCA_010328045.1_PDT000568327.1' already exists. Skipping...
Folder 'GCA_010328085.1_PDT000568248.1' already exists. Skipping...
Folder 'GCA_010328105.1_PDT000568497.1' already exists. Skipping...
Folder 'GCA_010328125.1_PDT000568492.1' already exists. Skipping...
Folder 'GCA_010328145.1_PDT000568254.1' already exists. Skipping...
Folder 'GCA_010328165.1_PDT000568493.1' already exists. Skipping...
Folder 'GCA_010328185.1_PDT000568280.1' already exists. Skipping...
Folder 'GCA_010328205.1_PDT000568303.1' already exists. Skipping...
Folder 'GCA_010328225.1_PDT000568495.1' already exists. Skipping...
Folder 'GCA_010328235.1_PDT000568270.1' already exists. Skipping...
Folder 'GCA_010328265.1_PDT000568296.1' already exists. Skipping...
Folder 'GCA_010328285.1_PDT000568501.1' already exists. Skipping...
Folder 'GCA_010328305.1_PDT000568325.1' already exists. Skipping...
Folder 'GCA_010328325.1_PDT000568276.1' already exists. Skipping...
Folder 'GCA_010328345.1_PDT000568491.1' already exists. Skipping...
Folder 'GCA_010328365.1_PDT000568488.1' already exists. Skipping...
Folder 'GCA_010328385.1_PDT000568291.1' already exists. Skipping...
Folder 'GCA_010328405.1_PDT000568320.1' already exists. Skipping...
Folder 'GCA_010328415.1_PDT000568329.1' already exists. Skipping...
Folder 'GCA_010328445.1_PDT000568484.1' already exists. Skipping...
Folder 'GCA_010328465.1_PDT000568314.1' already exists. Skipping...
Folder 'GCA_010328485.1_PDT000568331.1' already exists. Skipping...
Folder 'GCA_010328505.1_PDT000568489.1' already exists. Skipping...
Folder 'GCA_010328525.1_PDT000568502.1' already exists. Skipping...
Folder 'GCA_010328545.1_PDT000568333.1' already exists. Skipping...
Folder 'GCA_010328565.1_PDT000568337.1' already exists. Skipping...
Folder 'GCA_010328585.1_PDT000568496.1' already exists. Skipping...
Folder 'GCA_010328605.1_PDT000568336.1' already exists. Skipping...
Folder 'GCA_010328625.1_PDT000568335.1' already exists. Skipping...
Folder 'GCA_010328645.1_PDT000568340.1' already exists. Skipping...
Folder 'GCA_010328665.1_PDT000568343.1' already exists. Skipping...
Folder 'GCA_010328685.1_PDT000568341.1' already exists. Skipping...
Folder 'GCA_010328705.1_PDT000568345.1' already exists. Skipping...
Folder 'GCA_010328725.1_PDT000568346.1' already exists. Skipping...
Folder 'GCA_010328745.1_PDT000568243.1' already exists. Skipping...
Folder 'GCA_010328765.1_PDT000568285.1' already exists. Skipping...
Folder 'GCA_010328785.1_PDT000568347.1' already exists. Skipping...
Folder 'GCA_010328805.1_PDT000568348.1' already exists. Skipping...
Folder 'GCA_010328825.1_PDT000568266.1' already exists. Skipping...
Folder 'GCA_010328845.1_PDT000568334.1' already exists. Skipping...
Folder 'GCA_010328865.1_PDT000568328.1' already exists. Skipping...

Retreiveing data: 67085it [00:11, 6712.88it/s]

Folder 'GCA_010350695.1_PDT000632250.1' already exists. Skipping...
Folder 'GCA_010350725.1_PDT000632114.1' already exists. Skipping...
Folder 'GCA_010350745.1_PDT000646210.1' already exists. Skipping...
Folder 'GCA_010350765.1_PDT000638737.1' already exists. Skipping...
Folder 'GCA_010350785.1_PDT000637653.1' already exists. Skipping...
Folder 'GCA_010350805.1_PDT000639711.1' already exists. Skipping...
Folder 'GCA_010350825.1_PDT000632039.1' already exists. Skipping...
Folder 'GCA_010350845.1_PDT000634667.1' already exists. Skipping...
Folder 'GCA_010350865.1_PDT000637107.1' already exists. Skipping...
Folder 'GCA_010350885.1_PDT000638985.1' already exists. Skipping...
Folder 'GCA_010350905.1_PDT000639043.1' already exists. Skipping...
Folder 'GCA_010350925.1_PDT000637530.1' already exists. Skipping...
Folder 'GCA_010350965.1_PDT000631987.1' already exists. Skipping...
Folder 'GCA_010350985.1_PDT000637695.1' already exists. Skipping...
Folder 'GCA_010351005.1_PDT000637103.1' already exists. Skipping...
Folder 'GCA_010351025.1_PDT000636420.1' already exists. Skipping...
Folder 'GCA_010351045.1_PDT000637178.1' already exists. Skipping...
Folder 'GCA_010351065.1_PDT000636438.1' already exists. Skipping...
Folder 'GCA_010351085.1_PDT000634669.1' already exists. Skipping...
Folder 'GCA_010351105.1_PDT000632258.1' already exists. Skipping...
Folder 'GCA_010351125.1_PDT000637151.1' already exists. Skipping...
Folder 'GCA_010351145.1_PDT000636608.1' already exists. Skipping...
Folder 'GCA_010351155.1_PDT000634771.1' already exists. Skipping...
Folder 'GCA_010351185.1_PDT000637147.1' already exists. Skipping...
Folder 'GCA_010351205.1_PDT000636602.1' already exists. Skipping...
Folder 'GCA_010351225.1_PDT000636404.1' already exists. Skipping...
Folder 'GCA_010351245.1_PDT000636821.1' already exists. Skipping...
Folder 'GCA_010351265.1_PDT000634686.1' already exists. Skipping...
Folder 'GCA_010351285.1_PDT000635731.1' already exists. Skipping...
Folder 'GCA_010351295.1_PDT000636411.1' already exists. Skipping...
Folder 'GCA_010351305.1_PDT000634586.1' already exists. Skipping...
Folder 'GCA_010351345.1_PDT000634568.1' already exists. Skipping...
Folder 'GCA_010351365.1_PDT000634688.1' already exists. Skipping...
Folder 'GCA_010351385.1_PDT000632116.1' already exists. Skipping...
Folder 'GCA_010351405.1_PDT000632147.1' already exists. Skipping...
Folder 'GCA_010351425.1_PDT000634582.1' already exists. Skipping...
Folder 'GCA_010351445.1_PDT000632136.1' already exists. Skipping...
Folder 'GCA_010351465.1_PDT000632152.1' already exists. Skipping...
Folder 'GCA_010351485.1_PDT000632149.1' already exists. Skipping...
Folder 'GCA_010351505.1_PDT000632118.1' already exists. Skipping...
Folder 'GCA_010351525.1_PDT000632120.1' already exists. Skipping...
Folder 'GCA_010351545.1_PDT000632234.1' already exists. Skipping...
Folder 'GCA_010351565.1_PDT000632041.1' already exists. Skipping...
Folder 'GCA_010351585.1_PDT000632148.1' already exists. Skipping...
Folder 'GCA_010351605.1_PDT000630579.1' already exists. Skipping...
Folder 'GCA_010351625.1_PDT000631978.1' already exists. Skipping...
Folder 'GCA_010351645.1_PDT000631722.1' already exists. Skipping...
Folder 'GCA_010351665.1_PDT000632150.1' already exists. Skipping...
Folder 'GCA_010351685.1_PDT000631721.1' already exists. Skipping...
Folder 'GCA_010351705.1_PDT000632047.1' already exists. Skipping...
Folder 'GCA_010351725.1_PDT000630578.1' already exists. Skipping...
Folder 'GCA_010351735.1_PDT000631725.1' already exists. Skipping...
Folder 'GCA_010351765.1_PDT000631723.1' already exists. Skipping...
Folder 'GCA_010351785.1_PDT000631724.1' already exists. Skipping...
Folder 'GCA_010351805.1_PDT000631546.1' already exists. Skipping...
Folder 'GCA_010351825.1_PDT000631585.1' already exists. Skipping...
Folder 'GCA_010351845.1_PDT000631443.1' already exists. Skipping...
Folder 'GCA_010351865.1_PDT000630716.1' already exists. Skipping...
Folder 'GCA_010351885.1_PDT000631651.1' already exists. Skipping...
Folder 'GCA_010351905.1_PDT000631587.1' already exists. Skipping...
Folder 'GCA_010351925.1_PDT000630721.1' already exists. Skipping...
Folder 'GCA_010351945.1_PDT000630712.1' already exists. Skipping...
Folder 'GCA_010351965.1_PDT000630717.1' already exists. Skipping...
Folder 'GCA_010351985.1_PDT000630726.1' already exists. Skipping...
Folder 'GCA_010352005.1_PDT000630727.1' already exists. Skipping...
Folder 'GCA_010352025.1_PDT000631268.1' already exists. Skipping...
Folder 'GCA_010352045.1_PDT000630799.1' already exists. Skipping...
Folder 'GCA_010352065.1_PDT000630797.1' already exists. Skipping...
Folder 'GCA_010352085.1_PDT000630619.1' already exists. Skipping...
Folder 'GCA_010352105.1_PDT000631267.1' already exists. Skipping...
Folder 'GCA_010352125.1_PDT000630631.1' already exists. Skipping...
Folder 'GCA_010352135.1_PDT000630605.1' already exists. Skipping...
Folder 'GCA_010352165.1_PDT000630609.1' already exists. Skipping...
Folder 'GCA_010352185.1_PDT000659657.1' already exists. Skipping...
Folder 'GCA_010352205.1_PDT000631273.1' already exists. Skipping...
Folder 'GCA_010352225.1_PDT000630595.1' already exists. Skipping...
Folder 'GCA_010352245.1_PDT000630629.1' already exists. Skipping...
Folder 'GCA_010352255.1_PDT000630655.1' already exists. Skipping...
Folder 'GCA_010352285.1_PDT000630615.1' already exists. Skipping...
Folder 'GCA_010352305.1_PDT000630621.1' already exists. Skipping...
Folder 'GCA_010352325.1_PDT000631274.1' already exists. Skipping...
Folder 'GCA_010352345.1_PDT000656344.1' already exists. Skipping...
Folder 'GCA_010352385.1_PDT000631352.1' already exists. Skipping...
Folder 'GCA_010352405.1_PDT000631394.1' already exists. Skipping...
Folder 'GCA_010352425.1_PDT000630611.1' already exists. Skipping...
Folder 'GCA_010352445.1_PDT000656360.1' already exists. Skipping...
Folder 'GCA_010352465.1_PDT000631351.1' already exists. Skipping...
Folder 'GCA_010352485.1_PDT000631353.1' already exists. Skipping...
Folder 'GCA_010352505.1_PDT000659114.1' already exists. Skipping...
Folder 'GCA_010352525.1_PDT000631350.1' already exists. Skipping...
Folder 'GCA_010352535.1_PDT000631354.1' already exists. Skipping...
Folder 'GCA_010352565.1_PDT000656334.1' already exists. Skipping...
Folder 'GCA_010352585.1_PDT000659121.1' already exists. Skipping...
Folder 'GCA_010352605.1_PDT000631356.1' already exists. Skipping...
Folder 'GCA_010352625.1_PDT000631406.1' already exists. Skipping...
Folder 'GCA_010352645.1_PDT000659119.1' already exists. Skipping...
Folder 'GCA_010352665.1_PDT000631396.1' already exists. Skipping...
Folder 'GCA_010352675.1_PDT000631398.1' already exists. Skipping...
Folder 'GCA_010352705.1_PDT000631408.1' already exists. Skipping...
Folder 'GCA_010352715.1_PDT000631400.1' already exists. Skipping...
Folder 'GCA_010352745.1_PDT000631404.1' already exists. Skipping...
Folder 'GCA_010352765.1_PDT000629852.1' already exists. Skipping...
Folder 'GCA_010352785.1_PDT000629842.1' already exists. Skipping...
Folder 'GCA_010352805.1_PDT000631402.1' already exists. Skipping...
Folder 'GCA_010352825.1_PDT000631410.1' already exists. Skipping...
Folder 'GCA_010352835.1_PDT000658806.1' already exists. Skipping...
Folder 'GCA_010352865.1_PDT000659117.1' already exists. Skipping...
Folder 'GCA_010352885.1_PDT000630593.1' already exists. Skipping...
Folder 'GCA_010352905.1_PDT000630120.1' already exists. Skipping...
Folder 'GCA_010352925.1_PDT000629774.1' already exists. Skipping...
Folder 'GCA_010352945.1_PDT000656366.1' already exists. Skipping...
Folder 'GCA_010352965.1_PDT000629769.1' already exists. Skipping...
Folder 'GCA_010352985.1_PDT000656358.1' already exists. Skipping...
Folder 'GCA_010353005.2_ASM1035300v2' already exists. Skipping...
Folder 'GCA_010353025.2_ASM1035302v2' already exists. Skipping...
Folder 'GCA_010353045.1_PDT000656048.1' already exists. Skipping...
Folder 'GCA_010353065.2_ASM1035306v2' already exists. Skipping...
Folder 'GCA_010353085.1_PDT000659656.1' already exists. Skipping...
Folder 'GCA_010353105.1_PDT000656739.1' already exists. Skipping...
Folder 'GCA_010353125.1_PDT000659127.1' already exists. Skipping...
Folder 'GCA_010353145.1_PDT000659126.1' already exists. Skipping...
Folder 'GCA_010353155.1_PDT000659674.1' already exists. Skipping...
Folder 'GCA_010353185.1_PDT000659672.1' already exists. Skipping...
Folder 'GCA_010353205.1_PDT000659122.1' already exists. Skipping...
Folder 'GCA_010353225.1_PDT000656342.1' already exists. Skipping...
Folder 'GCA_010353245.1_PDT000631412.1' already exists. Skipping...
Folder 'GCA_010353265.1_PDT000658833.1' already exists. Skipping...
Folder 'GCA_010353305.1_PDT000631416.1' already exists. Skipping...
Folder 'GCA_010353325.1_PDT000659025.1' already exists. Skipping...
Folder 'GCA_010353345.1_PDT000659309.1' already exists. Skipping...
Folder 'GCA_010353365.1_PDT000658817.1' already exists. Skipping...
Folder 'GCA_010353385.1_PDT000629857.1' already exists. Skipping...
Folder 'GCA_010353405.1_PDT000631439.1' already exists. Skipping...
Folder 'GCA_010353425.1_PDT000629856.1' already exists. Skipping...
Folder 'GCA_010353445.1_PDT000659031.1' already exists. Skipping...
Folder 'GCA_010353465.2_ASM1035346v2' already exists. Skipping...
Folder 'GCA_010353485.1_PDT000629867.1' already exists. Skipping...
Folder 'GCA_010353505.1_PDT000659668.1' already exists. Skipping...
Folder 'GCA_010353525.1_PDT000629862.1' already exists. Skipping...
Folder 'GCA_010353545.1_PDT000630723.1' already exists. Skipping...
Folder 'GCA_010353565.1_PDT000629847.1' already exists. Skipping...
Folder 'GCA_010353585.1_PDT000630587.1' already exists. Skipping...
Folder 'GCA_010353605.1_PDT000630110.1' already exists. Skipping...
Folder 'GCA_010353625.1_PDT000630603.1' already exists. Skipping...
Folder 'GCA_010353645.1_PDT000630708.1' already exists. Skipping...
Folder 'GCA_010353665.1_PDT000630607.1' already exists. Skipping...
Folder 'GCA_010353685.1_PDT000630577.1' already exists. Skipping...
Folder 'GCA_010353705.1_PDT000630601.1' already exists. Skipping...
Folder 'GCA_010353725.1_PDT000679299.1' already exists. Skipping...
Folder 'GCA_010353805.1_PDT000677671.1' already exists. Skipping...
Folder 'GCA_010353845.1_PDT000677640.1' already exists. Skipping...
Folder 'GCA_010353885.1_PDT000677679.1' already exists. Skipping...
Folder 'GCA_010353945.1_PDT000677639.1' already exists. Skipping...
Folder 'GCA_010354105.1_PDT000677637.1' already exists. Skipping...
Folder 'GCA_010354265.1_PDT000677644.1' already exists. Skipping...
Folder 'GCA_010354275.1_PDT000562817.1' already exists. Skipping...
Folder 'GCA_010354305.1_PDT000678289.1' already exists. Skipping...
Folder 'GCA_010354325.1_PDT000603811.1' already exists. Skipping...
Folder 'GCA_010354345.1_PDT000603799.1' already exists. Skipping...
Folder 'GCA_010354405.1_PDT000603804.1' already exists. Skipping...
Folder 'GCA_010354445.1_PDT000677636.1' already exists. Skipping...
Folder 'GCA_010354465.1_PDT000677634.1' already exists. Skipping...
Folder 'GCA_010354485.1_PDT000603802.1' already exists. Skipping...
Folder 'GCA_010354705.1_PDT000678243.1' already exists. Skipping...
Folder 'GCA_010354805.1_PDT000677675.1' already exists. Skipping...
Folder 'GCA_010355025.1_PDT000679145.1' already exists. Skipping...
Folder 'GCA_010355065.1_PDT000677673.1' already exists. Skipping...
Folder 'GCA_010355105.1_PDT000677635.1' already exists. Skipping...
Folder 'GCA_010355185.1_PDT000631428.1' already exists. Skipping...
Folder 'GCA_010355225.1_PDT000630728.1' already exists. Skipping...
Folder 'GCA_010355245.1_PDT000630719.1' already exists. Skipping...
Folder 'GCA_010355265.1_PDT000629849.1' already exists. Skipping...
Folder 'GCA_010355315.1_PDT000650525.1' already exists. Skipping...
Folder 'GCA_010355345.1_PDT000630613.1' already exists. Skipping...
Folder 'GCA_010355365.1_PDT000651518.1' already exists. Skipping...
Folder 'GCA_010355385.1_PDT000651514.1' already exists. Skipping...
Folder 'GCA_010355405.1_PDT000651510.1' already exists. Skipping...
Folder 'GCA_010355425.1_PDT000651522.1' already exists. Skipping...
Folder 'GCA_010355435.1_PDT000651600.1' already exists. Skipping...
Folder 'GCA_010355465.1_PDT000676979.1' already exists. Skipping...
Folder 'GCA_010355485.1_PDT000649879.1' already exists. Skipping...
Folder 'GCA_010355545.1_PDT000650512.1' already exists. Skipping...
Folder 'GCA_010355565.1_PDT000676966.1' already exists. Skipping...
Folder 'GCA_010355575.1_PDT000651524.1' already exists. Skipping...
Folder 'GCA_010355695.1_PDT000630157.1' already exists. Skipping...
Folder 'GCA_010355745.1_PDT000677647.1' already exists. Skipping...
Folder 'GCA_010355765.1_PDT000630718.1' already exists. Skipping...
Folder 'GCA_010355865.1_PDT000677641.1' already exists. Skipping...
Folder 'GCA_010355885.1_PDT000651515.1' already exists. Skipping...
Folder 'GCA_010355905.1_PDT000677654.1' already exists. Skipping...
Folder 'GCA_010355925.1_PDT000651511.1' already exists. Skipping...
Folder 'GCA_010355945.1_PDT000649742.1' already exists. Skipping...
Folder 'GCA_010355985.1_PDT000630658.1' already exists. Skipping...
Folder 'GCA_010356105.1_PDT000651519.1' already exists. Skipping...
Folder 'GCA_010356145.1_PDT000651726.1' already exists. Skipping...
Folder 'GCA_010356165.1_PDT000651523.1' already exists. Skipping...
Folder 'GCA_010356185.1_PDT000678650.1' already exists. Skipping...
Folder 'GCA_010356205.1_PDT000630080.1' already exists. Skipping...
Folder 'GCA_010356225.1_PDT000651509.1' already exists. Skipping...
Folder 'GCA_010356245.1_PDT000603800.1' already exists. Skipping...
Folder 'GCA_010356265.1_PDT000603808.1' already exists. Skipping...
Folder 'GCA_010356285.1_PDT000651513.1' already exists. Skipping...
Folder 'GCA_010356305.1_PDT000603807.1' already exists. Skipping...
Folder 'GCA_010356345.1_PDT000603810.1' already exists. Skipping...
Folder 'GCA_010356365.1_PDT000650355.1' already exists. Skipping...
Folder 'GCA_010356385.1_PDT000651481.1' already exists. Skipping...
Folder 'GCA_010356405.1_PDT000651517.1' already exists. Skipping...
Folder 'GCA_010356425.1_PDT000649731.1' already exists. Skipping...
Folder 'GCA_010356465.1_PDT000651521.1' already exists. Skipping...
Folder 'GCA_010356485.1_PDT000651526.1' already exists. Skipping...
Folder 'GCA_010356505.1_PDT000651512.1' already exists. Skipping...
Folder 'GCA_010356545.1_PDT000679147.1' already exists. Skipping...
Folder 'GCA_010356565.1_PDT000649733.1' already exists. Skipping...
Folder 'GCA_010356625.1_PDT000651516.1' already exists. Skipping...
Folder 'GCA_010356665.1_PDT000631414.1' already exists. Skipping...
Folder 'GCA_010356685.1_PDT000649737.1' already exists. Skipping...
Folder 'GCA_010356705.1_PDT000651520.1' already exists. Skipping...
Folder 'GCA_010356725.1_PDT000651933.1' already exists. Skipping...
Folder 'GCA_010356745.1_PDT000629747.1' already exists. Skipping...
Folder 'GCA_010356765.1_PDT000650356.1' already exists. Skipping...
Folder 'GCA_010356775.1_PDT000677842.1' already exists. Skipping...
Folder 'GCA_010356805.1_PDT000656336.1' already exists. Skipping...
Folder 'GCA_010356825.1_PDT000656364.1' already exists. Skipping...
Folder 'GCA_010356835.1_PDT000677638.1' already exists. Skipping...
Folder 'GCA_010356885.1_PDT000650298.1' already exists. Skipping...
Folder 'GCA_010356905.1_PDT000656091.1' already exists. Skipping...
Folder 'GCA_010356955.1_PDT000677661.1' already exists. Skipping...
Folder 'GCA_010356975.1_PDT000677653.1' already exists. Skipping...
Folder 'GCA_010357045.1_PDT000649735.1' already exists. Skipping...
Folder 'GCA_010357055.1_PDT000677646.1' already exists. Skipping...
Folder 'GCA_010357085.1_PDT000676983.1' already exists. Skipping...
Folder 'GCA_010357105.1_PDT000677648.1' already exists. Skipping...
Folder 'GCA_010357125.1_PDT000677768.1' already exists. Skipping...
Folder 'GCA_010357145.1_PDT000676987.1' already exists. Skipping...
Folder 'GCA_010357165.1_PDT000677643.1' already exists. Skipping...
Folder 'GCA_010357185.1_PDT000677645.1' already exists. Skipping...
Folder 'GCA_010357285.1_PDT000562819.1' already exists. Skipping...
Folder 'GCA_010357325.1_PDT000678290.1' already exists. Skipping...
Folder 'GCA_010357365.1_PDT000677663.1' already exists. Skipping...
Folder 'GCA_010357385.1_PDT000677682.1' already exists. Skipping...
Folder 'GCA_010357395.1_PDT000677649.1' already exists. Skipping...
Folder 'GCA_010357435.1_PDT000677650.1' already exists. Skipping...
Folder 'GCA_010357645.1_PDT000603805.1' already exists. Skipping...
Folder 'GCA_010357705.1_PDT000603812.1' already exists. Skipping...
Folder 'GCA_010357765.1_PDT000562813.1' already exists. Skipping...
Folder 'GCA_010357815.1_PDT000603803.1' already exists. Skipping...
Folder 'GCA_010357865.1_PDT000676977.1' already exists. Skipping...
Folder 'GCA_010357905.1_PDT000603809.1' already exists. Skipping...
Folder 'GCA_010357965.1_PDT000679148.1' already exists. Skipping...
Folder 'GCA_010358025.1_PDT000631415.1' already exists. Skipping...
Folder 'GCA_010358185.1_PDT000629777.1' already exists. Skipping...
Folder 'GCA_010358205.1_PDT000630617.1' already exists. Skipping...
Folder 'GCA_010358265.1_PDT000591334.1' already exists. Skipping...
Folder 'GCA_010358295.1_PDT000603806.1' already exists. Skipping...
Folder 'GCA_010358345.1_PDT000630724.1' already exists. Skipping...
Folder 'GCA_010358425.1_PDT000630081.1' already exists. Skipping...
Folder 'GCA_010358455.1_PDT000629765.1' already exists. Skipping...
Folder 'GCA_010358485.1_PDT000656729.1' already exists. Skipping...
Folder 'GCA_010358505.1_PDT000603815.1' already exists. Skipping...
Folder 'GCA_010358525.1_PDT000656046.1' already exists. Skipping...
Folder 'GCA_010358565.1_PDT000603798.1' already exists. Skipping...
Folder 'GCA_010358585.1_PDT000679146.1' already exists. Skipping...
Folder 'GCA_010358605.2_ASM1035860v2' already exists. Skipping...
Folder 'GCA_010358625.2_ASM1035862v2' already exists. Skipping...
Folder 'GCA_010358685.1_PDT000679144.1' already exists. Skipping...
Folder 'GCA_010358705.1_PDT000679301.1' already exists. Skipping...
Folder 'GCA_010358725.2_ASM1035872v2' already exists. Skipping...
Folder 'GCA_010358745.2_ASM1035874v2' already exists. Skipping...
Folder 'GCA_010358805.1_PDT000631431.1' already exists. Skipping...
Folder 'GCA_010358825.2_ASM1035882v2' already exists. Skipping...
Folder 'GCA_010358865.1_PDT000630725.1' already exists. Skipping...
Folder 'GCA_010358885.1_PDT000630720.1' already exists. Skipping...
Folder 'GCA_010358895.1_PDT000631430.1' already exists. Skipping...
Folder 'GCA_010358925.1_PDT000631413.1' already exists. Skipping...
Folder 'GCA_010358945.1_PDT000630633.1' already exists. Skipping...
Folder 'GCA_010358965.1_PDT000629778.1' already exists. Skipping...
Folder 'GCA_010358985.1_PDT000630156.1' already exists. Skipping...
Folder 'GCA_010359005.1_PDT000629859.1' already exists. Skipping...
Folder 'GCA_010359025.1_PDT000630597.1' already exists. Skipping...
Folder 'GCA_010359045.1_PDT000629861.1' already exists. Skipping...
Folder 'GCA_010359065.1_PDT000656354.1' already exists. Skipping...
Folder 'GCA_010359085.1_PDT000629851.1' already exists. Skipping...
Folder 'GCA_010359105.1_PDT000629763.1' already exists. Skipping...
Folder 'GCA_010359125.1_PDT000656089.1' already exists. Skipping...
Folder 'GCA_010359145.1_PDT000656350.1' already exists. Skipping...
Folder 'GCA_010359185.1_PDT000656044.1' already exists. Skipping...
Folder 'GCA_010359205.1_PDT000656040.1' already exists. Skipping...
Folder 'GCA_010359225.1_PDT000656052.1' already exists. Skipping...
Folder 'GCA_010359245.1_PDT000656085.1' already exists. Skipping...
Folder 'GCA_010359265.2_ASM1035926v2' already exists. Skipping...
Folder 'GCA_010359285.2_ASM1035928v2' already exists. Skipping...
Folder 'GCA_010359305.1_PDT000603813.1' already exists. Skipping...
Folder 'GCA_010359345.1_PDT000630627.1' already exists. Skipping...
Folder 'GCA_010359385.2_ASM1035938v2' already exists. Skipping...

Retreiveing data: 68440it [00:11, 6745.87it/s]

Folder 'GCA_011990445.1_PDT000717979.1' already exists. Skipping...
Folder 'GCA_011990465.1_PDT000717981.1' already exists. Skipping...
Folder 'GCA_011990475.1_PDT000717984.1' already exists. Skipping...
Folder 'GCA_011990505.1_PDT000718016.1' already exists. Skipping...
Folder 'GCA_011990525.1_PDT000717983.1' already exists. Skipping...
Folder 'GCA_011990545.1_PDT000718017.1' already exists. Skipping...
Folder 'GCA_011990565.1_PDT000718009.1' already exists. Skipping...
Folder 'GCA_011990585.1_PDT000717982.1' already exists. Skipping...
Folder 'GCA_011990595.1_PDT000718014.1' already exists. Skipping...
Folder 'GCA_011990625.1_PDT000717980.1' already exists. Skipping...
Folder 'GCA_011990645.1_PDT000718005.1' already exists. Skipping...
Folder 'GCA_011990665.1_PDT000718000.1' already exists. Skipping...
Folder 'GCA_011990685.1_PDT000718003.1' already exists. Skipping...
Folder 'GCA_011990705.1_PDT000718001.1' already exists. Skipping...
Folder 'GCA_011990725.1_PDT000717999.1' already exists. Skipping...
Folder 'GCA_011990745.1_PDT000717998.1' already exists. Skipping...
Folder 'GCA_011990755.1_PDT000718002.1' already exists. Skipping...
Folder 'GCA_011990785.1_PDT000717997.1' already exists. Skipping...
Folder 'GCA_011990805.1_PDT000717995.1' already exists. Skipping...
Folder 'GCA_011990825.1_PDT000717996.1' already exists. Skipping...
Folder 'GCA_011990845.1_PDT000717992.1' already exists. Skipping...
Folder 'GCA_011990865.1_PDT000717990.1' already exists. Skipping...
Folder 'GCA_011990885.1_PDT000717993.1' already exists. Skipping...
Folder 'GCA_011990905.1_PDT000717994.1' already exists. Skipping...
Folder 'GCA_011990925.1_PDT000717991.1' already exists. Skipping...
Folder 'GCA_011990945.1_PDT000717989.1' already exists. Skipping...
Folder 'GCA_011990965.1_PDT000717985.1' already exists. Skipping...
Folder 'GCA_011990985.1_PDT000717988.1' already exists. Skipping...
Folder 'GCA_011991005.1_PDT000717986.1' already exists. Skipping...
Folder 'GCA_011991025.1_PDT000717977.1' already exists. Skipping...
Folder 'GCA_011991045.1_PDT000717978.1' already exists. Skipping...
Folder 'GCA_011991065.1_PDT000717975.1' already exists. Skipping...
Folder 'GCA_011991085.1_PDT000717976.1' already exists. Skipping...
Folder 'GCA_011991105.1_PDT000717974.1' already exists. Skipping...
Folder 'GCA_011991125.1_PDT000717972.1' already exists. Skipping...
Folder 'GCA_011991145.1_PDT000717973.1' already exists. Skipping...
Folder 'GCA_011991185.1_PDT000717971.1' already exists. Skipping...
Folder 'GCA_011991225.1_PDT000717970.1' already exists. Skipping...
Folder 'GCA_011991265.1_PDT000717969.1' already exists. Skipping...
Folder 'GCA_011991425.1_PDT000717945.1' already exists. Skipping...
Folder 'GCA_011991685.1_PDT000717953.1' already exists. Skipping...
Folder 'GCA_011991705.1_PDT000717949.1' already exists. Skipping...
Folder 'GCA_011991725.1_PDT000717965.1' already exists. Skipping...
Folder 'GCA_011991745.1_PDT000717952.1' already exists. Skipping...
Folder 'GCA_011991765.1_PDT000717957.1' already exists. Skipping...
Folder 'GCA_011991785.1_PDT000717948.1' already exists. Skipping...
Folder 'GCA_011991805.1_PDT000717958.1' already exists. Skipping...
Folder 'GCA_011991825.1_PDT000717961.1' already exists. Skipping...
Folder 'GCA_011991835.1_PDT000717963.1' already exists. Skipping...
Folder 'GCA_011991845.1_PDT000717968.1' already exists. Skipping...
Folder 'GCA_011991875.1_PDT000717951.1' already exists. Skipping...
Folder 'GCA_011991905.1_PDT000717891.1' already exists. Skipping...
Folder 'GCA_011991925.1_PDT000717950.1' already exists. Skipping...
Folder 'GCA_011991945.1_PDT000717956.1' already exists. Skipping...
Folder 'GCA_011991965.1_PDT000717955.1' already exists. Skipping...
Folder 'GCA_011992005.1_PDT000717890.1' already exists. Skipping...
Folder 'GCA_011992025.1_PDT000717964.1' already exists. Skipping...
Folder 'GCA_011992045.1_PDT000717885.1' already exists. Skipping...
Folder 'GCA_011992065.1_PDT000717967.1' already exists. Skipping...
Folder 'GCA_011992085.1_PDT000717939.1' already exists. Skipping...
Folder 'GCA_011992105.1_PDT000717887.1' already exists. Skipping...
Folder 'GCA_011992115.1_PDT000717944.1' already exists. Skipping...
Folder 'GCA_011992145.1_PDT000717942.1' already exists. Skipping...
Folder 'GCA_011992165.1_PDT000717943.1' already exists. Skipping...
Folder 'GCA_011992185.1_PDT000717954.1' already exists. Skipping...
Folder 'GCA_011992205.1_PDT000717933.1' already exists. Skipping...
Folder 'GCA_011992225.1_PDT000717936.1' already exists. Skipping...
Folder 'GCA_011992245.1_PDT000717930.1' already exists. Skipping...
Folder 'GCA_011992265.1_PDT000717931.1' already exists. Skipping...
Folder 'GCA_011992275.1_PDT000717926.1' already exists. Skipping...
Folder 'GCA_011992305.1_PDT000717937.1' already exists. Skipping...
Folder 'GCA_011992325.1_PDT000717932.1' already exists. Skipping...
Folder 'GCA_011992345.1_PDT000717940.1' already exists. Skipping...
Folder 'GCA_011992365.1_PDT000717889.1' already exists. Skipping...
Folder 'GCA_011992385.1_PDT000717934.1' already exists. Skipping...
Folder 'GCA_011992405.1_PDT000717941.1' already exists. Skipping...
Folder 'GCA_011992415.1_PDT000717946.1' already exists. Skipping...
Folder 'GCA_011992445.1_PDT000717929.1' already exists. Skipping...
Folder 'GCA_011992465.1_PDT000717884.1' already exists. Skipping...
Folder 'GCA_011992485.1_PDT000717927.1' already exists. Skipping...
Folder 'GCA_011992505.1_PDT000717938.1' already exists. Skipping...
Folder 'GCA_011992525.1_PDT000717925.1' already exists. Skipping...
Folder 'GCA_011992545.1_PDT000717924.1' already exists. Skipping...
Folder 'GCA_011992565.1_PDT000717947.1' already exists. Skipping...
Folder 'GCA_011992585.1_PDT000717935.1' already exists. Skipping...
Folder 'GCA_011992605.1_PDT000717886.1' already exists. Skipping...
Folder 'GCA_011992625.1_PDT000717919.1' already exists. Skipping...
Folder 'GCA_011992645.1_PDT000717922.1' already exists. Skipping...
Folder 'GCA_011992665.1_PDT000717916.1' already exists. Skipping...
Folder 'GCA_011992685.1_PDT000717921.1' already exists. Skipping...
Folder 'GCA_011992725.1_PDT000717920.1' already exists. Skipping...
Folder 'GCA_011992745.1_PDT000717918.1' already exists. Skipping...
Folder 'GCA_011992765.1_PDT000717911.1' already exists. Skipping...
Folder 'GCA_011992785.1_PDT000717917.1' already exists. Skipping...
Folder 'GCA_011992805.1_PDT000717914.1' already exists. Skipping...
Folder 'GCA_011992825.1_PDT000717915.1' already exists. Skipping...
Folder 'GCA_011992845.1_PDT000717902.1' already exists. Skipping...
Folder 'GCA_011992865.1_PDT000717910.1' already exists. Skipping...
Folder 'GCA_011992885.1_PDT000717908.1' already exists. Skipping...
Folder 'GCA_011992895.1_PDT000717913.1' already exists. Skipping...
Folder 'GCA_011992915.1_PDT000717912.1' already exists. Skipping...
Folder 'GCA_011992945.1_PDT000717907.1' already exists. Skipping...
Folder 'GCA_011992965.1_PDT000717905.1' already exists. Skipping...
Folder 'GCA_011992985.1_PDT000717906.1' already exists. Skipping...
Folder 'GCA_011993005.1_PDT000717900.1' already exists. Skipping...
Folder 'GCA_011993025.1_PDT000717903.1' already exists. Skipping...
Folder 'GCA_011993045.1_PDT000717904.1' already exists. Skipping...
Folder 'GCA_011993065.1_PDT000717898.1' already exists. Skipping...
Folder 'GCA_011993085.1_PDT000717901.1' already exists. Skipping...
Folder 'GCA_011993105.1_PDT000717896.1' already exists. Skipping...
Folder 'GCA_011993125.1_PDT000717899.1' already exists. Skipping...
Folder 'GCA_011993145.1_PDT000717893.1' already exists. Skipping...
Folder 'GCA_011993165.1_PDT000717894.1' already exists. Skipping...
Folder 'GCA_011993185.1_PDT000717895.1' already exists. Skipping...
Folder 'GCA_011993205.1_PDT000717897.1' already exists. Skipping...
Folder 'GCA_011993225.1_PDT000718307.1' already exists. Skipping...
Folder 'GCA_011993245.1_PDT000717834.1' already exists. Skipping...
Folder 'GCA_011993265.1_PDT000717883.1' already exists. Skipping...
Folder 'GCA_011993285.1_PDT000717838.1' already exists. Skipping...
Folder 'GCA_011993305.1_PDT000717836.1' already exists. Skipping...
Folder 'GCA_011993325.1_PDT000717831.1' already exists. Skipping...
Folder 'GCA_011993345.1_PDT000717830.1' already exists. Skipping...
Folder 'GCA_011993365.1_PDT000717835.1' already exists. Skipping...
Folder 'GCA_011993385.1_PDT000717837.1' already exists. Skipping...
Folder 'GCA_011993405.1_PDT000717877.1' already exists. Skipping...
Folder 'GCA_011993415.1_PDT000717880.1' already exists. Skipping...
Folder 'GCA_011993445.1_PDT000717833.1' already exists. Skipping...
Folder 'GCA_011993465.1_PDT000717878.1' already exists. Skipping...
Folder 'GCA_011993485.1_PDT000717841.1' already exists. Skipping...
Folder 'GCA_011993505.1_PDT000717881.1' already exists. Skipping...
Folder 'GCA_011993525.1_PDT000717828.1' already exists. Skipping...
Folder 'GCA_011993535.1_PDT000717826.1' already exists. Skipping...
Folder 'GCA_011993565.1_PDT000717829.1' already exists. Skipping...
Folder 'GCA_011993585.1_PDT000717879.1' already exists. Skipping...
Folder 'GCA_011993605.1_PDT000717832.1' already exists. Skipping...
Folder 'GCA_011993625.1_PDT000717827.1' already exists. Skipping...
Folder 'GCA_011993645.1_PDT000717865.1' already exists. Skipping...
Folder 'GCA_011993665.1_PDT000717882.1' already exists. Skipping...
Folder 'GCA_011993675.1_PDT000717866.1' already exists. Skipping...
Folder 'GCA_011993705.1_PDT000717876.1' already exists. Skipping...
Folder 'GCA_011993725.1_PDT000717872.1' already exists. Skipping...
Folder 'GCA_011993745.1_PDT000717871.1' already exists. Skipping...
Folder 'GCA_011993765.1_PDT000717861.1' already exists. Skipping...
Folder 'GCA_011993785.1_PDT000717863.1' already exists. Skipping...
Folder 'GCA_011993805.1_PDT000717854.1' already exists. Skipping...
Folder 'GCA_011993825.1_PDT000717859.1' already exists. Skipping...
Folder 'GCA_011993845.1_PDT000717855.1' already exists. Skipping...
Folder 'GCA_011993865.1_PDT000717860.1' already exists. Skipping...
Folder 'GCA_011993885.1_PDT000717853.1' already exists. Skipping...
Folder 'GCA_011993905.1_PDT000717858.1' already exists. Skipping...
Folder 'GCA_011993925.1_PDT000717856.1' already exists. Skipping...
Folder 'GCA_011993945.1_PDT000717849.1' already exists. Skipping...
Folder 'GCA_011993965.1_PDT000717851.1' already exists. Skipping...
Folder 'GCA_011993985.1_PDT000717850.1' already exists. Skipping...
Folder 'GCA_011994005.1_PDT000717852.1' already exists. Skipping...
Folder 'GCA_011994025.1_PDT000717848.1' already exists. Skipping...
Folder 'GCA_011994045.1_PDT000717847.1' already exists. Skipping...
Folder 'GCA_011994065.1_PDT000717846.1' already exists. Skipping...
Folder 'GCA_011994085.1_PDT000717842.1' already exists. Skipping...
Folder 'GCA_011994095.1_PDT000717844.1' already exists. Skipping...
Folder 'GCA_011994125.1_PDT000717845.1' already exists. Skipping...
Folder 'GCA_011994145.1_PDT000717825.1' already exists. Skipping...
Folder 'GCA_011994165.1_PDT000717820.1' already exists. Skipping...
Folder 'GCA_011994185.1_PDT000717823.1' already exists. Skipping...
Folder 'GCA_011994205.1_PDT000717822.1' already exists. Skipping...
Folder 'GCA_011994225.1_PDT000717821.1' already exists. Skipping...
Folder 'GCA_011994245.1_PDT000717824.1' already exists. Skipping...
Folder 'GCA_011994265.1_PDT000717819.1' already exists. Skipping...
Folder 'GCA_011994285.1_PDT000717816.1' already exists. Skipping...
Folder 'GCA_011994305.1_PDT000717818.1' already exists. Skipping...
Folder 'GCA_011994325.1_PDT000717817.1' already exists. Skipping...
Folder 'GCA_011994345.1_PDT000717813.1' already exists. Skipping...
Folder 'GCA_011994365.1_PDT000717815.1' already exists. Skipping...
Folder 'GCA_011994385.1_PDT000717812.1' already exists. Skipping...
Folder 'GCA_011994405.1_PDT000717808.1' already exists. Skipping...
Folder 'GCA_011994415.1_PDT000717809.1' already exists. Skipping...
Folder 'GCA_011994445.1_PDT000717811.1' already exists. Skipping...
Folder 'GCA_011994465.1_PDT000717805.1' already exists. Skipping...
Folder 'GCA_011994485.1_PDT000717807.1' already exists. Skipping...
Folder 'GCA_011994505.1_PDT000717806.1' already exists. Skipping...
Folder 'GCA_011994515.1_PDT000717804.1' already exists. Skipping...
Folder 'GCA_011994545.1_PDT000717802.1' already exists. Skipping...
Folder 'GCA_011994565.1_PDT000717803.1' already exists. Skipping...
Folder 'GCA_011994585.1_PDT000717801.1' already exists. Skipping...
Folder 'GCA_011994605.1_PDT000717799.1' already exists. Skipping...
Folder 'GCA_011994625.1_PDT000717800.1' already exists. Skipping...
Folder 'GCA_011994635.1_PDT000717870.1' already exists. Skipping...
Folder 'GCA_011994665.1_PDT000717874.1' already exists. Skipping...
Folder 'GCA_011994685.1_PDT000717873.1' already exists. Skipping...
Folder 'GCA_011994705.1_PDT000717867.1' already exists. Skipping...
Folder 'GCA_011994725.1_PDT000717869.1' already exists. Skipping...
Folder 'GCA_011994745.1_PDT000717875.1' already exists. Skipping...
Folder 'GCA_011994765.1_PDT000717864.1' already exists. Skipping...
Folder 'GCA_011994825.1_PDT000691050.1' already exists. Skipping...
Folder 'GCA_011994845.1_PDT000690156.1' already exists. Skipping...
Folder 'GCA_011994865.1_PDT000689992.1' already exists. Skipping...
Folder 'GCA_011994945.1_PDT000717810.1' already exists. Skipping...
Folder 'GCA_011994955.1_PDT000717814.1' already exists. Skipping...
Folder 'GCA_011994985.1_PDT000717798.1' already exists. Skipping...
Folder 'GCA_011995005.1_PDT000717737.1' already exists. Skipping...
Folder 'GCA_011995025.1_PDT000717736.1' already exists. Skipping...
Folder 'GCA_011995045.1_PDT000717795.1' already exists. Skipping...
Folder 'GCA_011995065.1_PDT000717797.1' already exists. Skipping...
Folder 'GCA_011995085.1_PDT000717767.1' already exists. Skipping...
Folder 'GCA_011995105.1_PDT000717778.1' already exists. Skipping...
Folder 'GCA_011995125.1_PDT000717796.1' already exists. Skipping...
Folder 'GCA_011995145.1_PDT000717788.1' already exists. Skipping...
Folder 'GCA_011995165.1_PDT000717739.1' already exists. Skipping...
Folder 'GCA_011995185.1_PDT000717774.1' already exists. Skipping...
Folder 'GCA_011995205.1_PDT000717769.1' already exists. Skipping...
Folder 'GCA_011995225.1_PDT000717772.1' already exists. Skipping...
Folder 'GCA_011995245.1_PDT000717792.1' already exists. Skipping...
Folder 'GCA_011995265.1_PDT000717765.1' already exists. Skipping...
Folder 'GCA_011995285.1_PDT000717738.1' already exists. Skipping...
Folder 'GCA_011995305.1_PDT000717787.1' already exists. Skipping...
Folder 'GCA_011995325.1_PDT000717790.1' already exists. Skipping...
Folder 'GCA_011995345.1_PDT000717777.1' already exists. Skipping...
Folder 'GCA_011995365.1_PDT000717763.1' already exists. Skipping...
Folder 'GCA_011995385.1_PDT000717758.1' already exists. Skipping...
Folder 'GCA_011995405.1_PDT000717734.1' already exists. Skipping...
Folder 'GCA_011995415.1_PDT000717781.1' already exists. Skipping...
Folder 'GCA_011995445.1_PDT000717793.1' already exists. Skipping...
Folder 'GCA_011995465.1_PDT000717780.1' already exists. Skipping...
Folder 'GCA_011995485.1_PDT000717782.1' already exists. Skipping...
Folder 'GCA_011995505.1_PDT000717786.1' already exists. Skipping...
Folder 'GCA_011995525.1_PDT000717776.1' already exists. Skipping...
Folder 'GCA_011995545.1_PDT000717784.1' already exists. Skipping...
Folder 'GCA_011995565.1_PDT000717731.1' already exists. Skipping...
Folder 'GCA_011995585.1_PDT000717757.1' already exists. Skipping...
Folder 'GCA_011995605.1_PDT000717762.1' already exists. Skipping...
Folder 'GCA_011995625.1_PDT000717727.1' already exists. Skipping...
Folder 'GCA_011995645.1_PDT000717766.1' already exists. Skipping...
Folder 'GCA_011995685.1_PDT000717759.1' already exists. Skipping...
Folder 'GCA_011995695.1_PDT000717760.1' already exists. Skipping...
Folder 'GCA_011995725.1_PDT000717761.1' already exists. Skipping...
Folder 'GCA_011995745.1_PDT000717779.1' already exists. Skipping...
Folder 'GCA_011995765.1_PDT000717722.1' already exists. Skipping...
Folder 'GCA_011995785.1_PDT000717771.1' already exists. Skipping...
Folder 'GCA_011995805.1_PDT000717775.1' already exists. Skipping...
Folder 'GCA_011995825.1_PDT000717732.1' already exists. Skipping...
Folder 'GCA_011995845.1_PDT000717729.1' already exists. Skipping...
Folder 'GCA_011995865.1_PDT000717725.1' already exists. Skipping...
Folder 'GCA_011995895.1_PDT000717730.1' already exists. Skipping...
Folder 'GCA_011995945.1_PDT000717740.1' already exists. Skipping...
Folder 'GCA_011995955.1_PDT000717733.1' already exists. Skipping...
Folder 'GCA_011995985.1_PDT000717721.1' already exists. Skipping...
Folder 'GCA_011996005.1_PDT000717754.1' already exists. Skipping...
Folder 'GCA_011996025.1_PDT000717755.1' already exists. Skipping...
Folder 'GCA_011996045.1_PDT000717756.1' already exists. Skipping...
Folder 'GCA_011996065.1_PDT000717753.1' already exists. Skipping...
Folder 'GCA_011996095.1_PDT000717728.1' already exists. Skipping...
Folder 'GCA_011996105.1_PDT000717752.1' already exists. Skipping...
Folder 'GCA_011996145.1_PDT000717748.1' already exists. Skipping...
Folder 'GCA_011996165.1_PDT000717751.1' already exists. Skipping...
Folder 'GCA_011996175.1_PDT000717749.1' already exists. Skipping...
Folder 'GCA_011996205.1_PDT000717750.1' already exists. Skipping...
Folder 'GCA_011996215.1_PDT000717747.1' already exists. Skipping...
Folder 'GCA_011996245.1_PDT000717745.1' already exists. Skipping...
Folder 'GCA_011996265.1_PDT000717744.1' already exists. Skipping...
Folder 'GCA_011996295.1_PDT000717746.1' already exists. Skipping...
Folder 'GCA_011996315.1_PDT000717741.1' already exists. Skipping...
Folder 'GCA_011996345.1_PDT000717717.1' already exists. Skipping...
Folder 'GCA_011996355.1_PDT000717743.1' already exists. Skipping...
Folder 'GCA_011996385.1_PDT000717742.1' already exists. Skipping...
Folder 'GCA_011996405.1_PDT000717720.1' already exists. Skipping...
Folder 'GCA_011996425.1_PDT000717715.1' already exists. Skipping...
Folder 'GCA_011996445.1_PDT000717716.1' already exists. Skipping...
Folder 'GCA_011996465.1_PDT000717712.1' already exists. Skipping...
Folder 'GCA_011996485.1_PDT000717718.1' already exists. Skipping...
Folder 'GCA_011996505.1_PDT000717714.1' already exists. Skipping...
Folder 'GCA_011996545.1_PDT000717711.1' already exists. Skipping...
Folder 'GCA_011996565.1_PDT000717735.1' already exists. Skipping...
Folder 'GCA_011996575.1_PDT000717719.1' already exists. Skipping...
Folder 'GCA_011996605.1_PDT000717789.1' already exists. Skipping...
Folder 'GCA_011996615.1_PDT000717724.1' already exists. Skipping...
Folder 'GCA_011996645.1_PDT000717773.1' already exists. Skipping...
Folder 'GCA_011996745.1_PDT000717701.1' already exists. Skipping...
Folder 'GCA_011996785.1_PDT000717689.1' already exists. Skipping...
Folder 'GCA_011996805.1_PDT000717688.1' already exists. Skipping...
Folder 'GCA_011996825.1_PDT000717710.1' already exists. Skipping...
Folder 'GCA_011996845.1_PDT000717685.1' already exists. Skipping...
Folder 'GCA_011996865.1_PDT000717708.1' already exists. Skipping...
Folder 'GCA_011996925.1_PDT000717709.1' already exists. Skipping...
Folder 'GCA_011996945.1_PDT000717706.1' already exists. Skipping...
Folder 'GCA_011997205.1_PDT000717686.1' already exists. Skipping...
Folder 'GCA_011997225.1_PDT000717490.1' already exists. Skipping...
Folder 'GCA_011997245.1_PDT000717682.1' already exists. Skipping...
Folder 'GCA_011997275.1_PDT000717703.1' already exists. Skipping...
Folder 'GCA_011997305.1_PDT000717683.1' already exists. Skipping...
Folder 'GCA_011997325.1_PDT000717684.1' already exists. Skipping...
Folder 'GCA_011997345.1_PDT000717697.1' already exists. Skipping...
Folder 'GCA_011997385.1_PDT000717704.1' already exists. Skipping...
Folder 'GCA_011997395.1_PDT000717702.1' already exists. Skipping...
Folder 'GCA_011997445.1_PDT000717707.1' already exists. Skipping...

Retreiveing data: 69789it [00:11, 6719.26it/s]

Folder 'GCA_013161485.1_PDT000744336.1' already exists. Skipping...
Folder 'GCA_013161505.1_PDT000744335.1' already exists. Skipping...
Folder 'GCA_013161525.1_PDT000744332.1' already exists. Skipping...
Folder 'GCA_013162985.1_PDT000743677.1' already exists. Skipping...
Folder 'GCA_013163005.1_PDT000743680.1' already exists. Skipping...
Folder 'GCA_013163225.1_PDT000743699.1' already exists. Skipping...
Folder 'GCA_013163265.1_PDT000743700.1' already exists. Skipping...
Folder 'GCA_013163305.1_PDT000743693.1' already exists. Skipping...
Folder 'GCA_013163325.1_PDT000743684.1' already exists. Skipping...
Folder 'GCA_013163345.1_PDT000743686.1' already exists. Skipping...
Folder 'GCA_013163365.1_PDT000743683.1' already exists. Skipping...
Folder 'GCA_013163385.1_PDT000743682.1' already exists. Skipping...
Folder 'GCA_013163405.1_PDT000743681.1' already exists. Skipping...
Folder 'GCA_013163425.1_PDT000743679.1' already exists. Skipping...
Folder 'GCA_013163445.1_PDT000743676.1' already exists. Skipping...
Folder 'GCA_013163465.1_PDT000743675.1' already exists. Skipping...
Folder 'GCA_013163505.1_PDT000743665.1' already exists. Skipping...
Folder 'GCA_013163525.1_PDT000743664.1' already exists. Skipping...
Folder 'GCA_013163605.1_PDT000743670.1' already exists. Skipping...
Folder 'GCA_013163705.1_PDT000743671.1' already exists. Skipping...
Folder 'GCA_013163865.1_PDT000743672.1' already exists. Skipping...
Folder 'GCA_013163885.1_PDT000743673.1' already exists. Skipping...
Folder 'GCA_013163965.1_PDT000743669.1' already exists. Skipping...
Folder 'GCA_013164705.1_PDT000743499.1' already exists. Skipping...
Folder 'GCA_013164765.1_PDT000743496.1' already exists. Skipping...
Folder 'GCA_013164885.1_PDT000743491.1' already exists. Skipping...
Folder 'GCA_013164925.1_PDT000743480.1' already exists. Skipping...
Folder 'GCA_013164935.1_PDT000743486.1' already exists. Skipping...
Folder 'GCA_013164965.1_PDT000743484.1' already exists. Skipping...
Folder 'GCA_013164985.1_PDT000743474.1' already exists. Skipping...
Folder 'GCA_013165005.1_PDT000743479.1' already exists. Skipping...
Folder 'GCA_013165065.1_PDT000743473.1' already exists. Skipping...
Folder 'GCA_013165085.1_PDT000743455.1' already exists. Skipping...
Folder 'GCA_013165105.1_PDT000743471.1' already exists. Skipping...
Folder 'GCA_013165125.1_PDT000743469.1' already exists. Skipping...
Folder 'GCA_013165145.1_PDT000743466.1' already exists. Skipping...
Folder 'GCA_013170975.1_PDT000745240.1' already exists. Skipping...
Folder 'GCA_013171025.1_PDT000745241.1' already exists. Skipping...
Folder 'GCA_013390525.1_ASM1339052v1' already exists. Skipping...
Folder 'GCA_013390965.1_ASM1339096v1' already exists. Skipping...
Folder 'GCA_013441075.1_PDT000793199.1' already exists. Skipping...
Folder 'GCA_013441175.1_PDT000793191.1' already exists. Skipping...
Folder 'GCA_013441195.1_PDT000793193.1' already exists. Skipping...
Folder 'GCA_013441735.1_PDT000793564.1' already exists. Skipping...
Folder 'GCA_013443255.1_PDT000793096.1' already exists. Skipping...
Folder 'GCA_013443335.1_PDT000793090.1' already exists. Skipping...
Folder 'GCA_013443375.1_PDT000793093.1' already exists. Skipping...
Folder 'GCA_013443395.1_PDT000793091.1' already exists. Skipping...
Folder 'GCA_013443415.1_PDT000793083.1' already exists. Skipping...
Folder 'GCA_013443455.1_PDT000793088.1' already exists. Skipping...
Folder 'GCA_013443475.1_PDT000793084.1' already exists. Skipping...
Folder 'GCA_013443495.1_PDT000793089.1' already exists. Skipping...
Folder 'GCA_013443515.1_PDT000793080.1' already exists. Skipping...
Folder 'GCA_013443535.1_PDT000793085.1' already exists. Skipping...
Folder 'GCA_013443555.1_PDT000793087.1' already exists. Skipping...
Folder 'GCA_013443565.1_PDT000793081.1' already exists. Skipping...
Folder 'GCA_013443595.1_PDT000793079.1' already exists. Skipping...
Folder 'GCA_013443615.1_PDT000793082.1' already exists. Skipping...
Folder 'GCA_013443655.1_PDT000793075.1' already exists. Skipping...
Folder 'GCA_013443675.1_PDT000793078.1' already exists. Skipping...
Folder 'GCA_013443695.1_PDT000793074.1' already exists. Skipping...
Folder 'GCA_013443735.1_PDT000793076.1' already exists. Skipping...
Folder 'GCA_013443775.1_PDT000793071.1' already exists. Skipping...
Folder 'GCA_013443795.1_PDT000793068.1' already exists. Skipping...
Folder 'GCA_013443815.1_PDT000793069.1' already exists. Skipping...
Folder 'GCA_013443855.1_PDT000793065.1' already exists. Skipping...
Folder 'GCA_013443895.1_PDT000793066.1' already exists. Skipping...
Folder 'GCA_013443915.1_PDT000793059.1' already exists. Skipping...
Folder 'GCA_013443955.1_PDT000793060.1' already exists. Skipping...
Folder 'GCA_013445795.1_PDT000792718.1' already exists. Skipping...
Folder 'GCA_013445835.1_PDT000792731.1' already exists. Skipping...
Folder 'GCA_013445935.1_PDT000792714.1' already exists. Skipping...
Folder 'GCA_013445965.1_PDT000792713.1' already exists. Skipping...
Folder 'GCA_013446135.1_PDT000792704.1' already exists. Skipping...
Folder 'GCA_013446155.1_PDT000792705.1' already exists. Skipping...
Folder 'GCA_013447095.1_PDT000793053.1' already exists. Skipping...
Folder 'GCA_013447255.1_PDT000793051.1' already exists. Skipping...
Folder 'GCA_013447295.1_PDT000793049.1' already exists. Skipping...
Folder 'GCA_013447315.1_PDT000793048.1' already exists. Skipping...
Folder 'GCA_013447355.1_PDT000793045.1' already exists. Skipping...
Folder 'GCA_013447415.1_PDT000793042.1' already exists. Skipping...
Folder 'GCA_013447455.1_PDT000793038.1' already exists. Skipping...
Folder 'GCA_013447495.1_PDT000793041.1' already exists. Skipping...
Folder 'GCA_013447835.1_PDT000792760.1' already exists. Skipping...
Folder 'GCA_013448195.1_PDT000792761.1' already exists. Skipping...
Folder 'GCA_013448235.1_PDT000792784.1' already exists. Skipping...
Folder 'GCA_013448375.1_PDT000792781.1' already exists. Skipping...
Folder 'GCA_013448415.1_PDT000792719.1' already exists. Skipping...
Folder 'GCA_013448615.1_PDT000792748.1' already exists. Skipping...
Folder 'GCA_013448695.1_PDT000792749.1' already exists. Skipping...
Folder 'GCA_013448835.1_PDT000792738.1' already exists. Skipping...
Folder 'GCA_013448875.1_PDT000792739.1' already exists. Skipping...
Folder 'GCA_013448935.1_PDT000792735.1' already exists. Skipping...
Folder 'GCA_013448975.1_PDT000792736.1' already exists. Skipping...
Folder 'GCA_013448995.1_PDT000792733.1' already exists. Skipping...
Folder 'GCA_013449015.1_PDT000792737.1' already exists. Skipping...
Folder 'GCA_013449095.1_PDT000792727.1' already exists. Skipping...
Folder 'GCA_013449115.1_PDT000792725.1' already exists. Skipping...
Folder 'GCA_013449175.1_PDT000792724.1' already exists. Skipping...
Folder 'GCA_013449215.1_PDT000792728.1' already exists. Skipping...
Folder 'GCA_013449235.1_PDT000792721.1' already exists. Skipping...
Folder 'GCA_013449295.1_PDT000792720.1' already exists. Skipping...
Folder 'GCA_013450635.1_PDT000792617.1' already exists. Skipping...
Folder 'GCA_013450695.1_PDT000792615.1' already exists. Skipping...
Folder 'GCA_013450715.1_PDT000792616.1' already exists. Skipping...
Folder 'GCA_013450755.1_PDT000792614.1' already exists. Skipping...
Folder 'GCA_013450765.1_PDT000792613.1' already exists. Skipping...
Folder 'GCA_013450795.1_PDT000792612.1' already exists. Skipping...
Folder 'GCA_013450815.1_PDT000792611.1' already exists. Skipping...
Folder 'GCA_013450835.1_PDT000792619.1' already exists. Skipping...
Folder 'GCA_013450875.1_PDT000792610.1' already exists. Skipping...
Folder 'GCA_013451075.1_PDT000792618.1' already exists. Skipping...
Folder 'GCA_013451135.1_PDT000792620.1' already exists. Skipping...
Folder 'GCA_013451255.1_PDT000792609.1' already exists. Skipping...
Folder 'GCA_013451275.1_PDT000792608.1' already exists. Skipping...
Folder 'GCA_013451295.1_PDT000792606.1' already exists. Skipping...
Folder 'GCA_013451305.1_PDT000792603.1' already exists. Skipping...
Folder 'GCA_013451335.1_PDT000792607.1' already exists. Skipping...
Folder 'GCA_013451355.1_PDT000792599.1' already exists. Skipping...
Folder 'GCA_013451375.1_PDT000792605.1' already exists. Skipping...
Folder 'GCA_013451455.1_PDT000792593.1' already exists. Skipping...
Folder 'GCA_013451875.1_PDT000792590.1' already exists. Skipping...
Folder 'GCA_013451915.1_PDT000792586.1' already exists. Skipping...
Folder 'GCA_013451935.1_PDT000792579.1' already exists. Skipping...
Folder 'GCA_013451955.1_PDT000792588.1' already exists. Skipping...
Folder 'GCA_013451975.1_PDT000792601.1' already exists. Skipping...
Folder 'GCA_013451995.1_PDT000792600.1' already exists. Skipping...
Folder 'GCA_013452015.1_PDT000792602.1' already exists. Skipping...
Folder 'GCA_013452035.1_PDT000792592.1' already exists. Skipping...
Folder 'GCA_013452055.1_PDT000792597.1' already exists. Skipping...
Folder 'GCA_013452065.1_PDT000792598.1' already exists. Skipping...
Folder 'GCA_013452095.1_PDT000792594.1' already exists. Skipping...
Folder 'GCA_013452115.1_PDT000792595.1' already exists. Skipping...
Folder 'GCA_013452135.1_PDT000792585.1' already exists. Skipping...
Folder 'GCA_013452155.1_PDT000792577.1' already exists. Skipping...
Folder 'GCA_013452175.1_PDT000792596.1' already exists. Skipping...
Folder 'GCA_013452185.1_PDT000792591.1' already exists. Skipping...
Folder 'GCA_013452215.1_PDT000792584.1' already exists. Skipping...
Folder 'GCA_013452235.1_PDT000792587.1' already exists. Skipping...
Folder 'GCA_013452255.1_PDT000792583.1' already exists. Skipping...
Folder 'GCA_013452275.1_PDT000792582.1' already exists. Skipping...
Folder 'GCA_013452315.1_PDT000792581.1' already exists. Skipping...
Folder 'GCA_013452335.1_PDT000792576.1' already exists. Skipping...
Folder 'GCA_013452355.1_PDT000792589.1' already exists. Skipping...
Folder 'GCA_013452375.1_PDT000792580.1' already exists. Skipping...
Folder 'GCA_013452395.1_PDT000792572.1' already exists. Skipping...
Folder 'GCA_013452415.1_PDT000792574.1' already exists. Skipping...
Folder 'GCA_013452435.1_PDT000792575.1' already exists. Skipping...
Folder 'GCA_013452455.1_PDT000792578.1' already exists. Skipping...
Folder 'GCA_013452475.1_PDT000792573.1' already exists. Skipping...
Folder 'GCA_013452495.1_PDT000792570.1' already exists. Skipping...
Folder 'GCA_013452505.1_PDT000792571.1' already exists. Skipping...
Folder 'GCA_013452515.1_PDT000792566.1' already exists. Skipping...
Folder 'GCA_013452555.1_PDT000792568.1' already exists. Skipping...
Folder 'GCA_013452575.1_PDT000792567.1' already exists. Skipping...
Folder 'GCA_013452595.1_PDT000792565.1' already exists. Skipping...
Folder 'GCA_013452605.1_PDT000792569.1' already exists. Skipping...
Folder 'GCA_013452635.1_PDT000792564.1' already exists. Skipping...
Folder 'GCA_013452655.1_PDT000792563.1' already exists. Skipping...
Folder 'GCA_013452675.1_PDT000792561.1' already exists. Skipping...
Folder 'GCA_013452695.1_PDT000792560.1' already exists. Skipping...
Folder 'GCA_013452715.1_PDT000792562.1' already exists. Skipping...
Folder 'GCA_013452735.1_PDT000792558.1' already exists. Skipping...
Folder 'GCA_013452755.1_PDT000792557.1' already exists. Skipping...
Folder 'GCA_013452775.1_PDT000792559.1' already exists. Skipping...
Folder 'GCA_013452915.1_PDT000792111.1' already exists. Skipping...
Folder 'GCA_013452995.1_PDT000792105.1' already exists. Skipping...
Folder 'GCA_013453005.1_PDT000792108.1' already exists. Skipping...
Folder 'GCA_013453035.1_PDT000792109.1' already exists. Skipping...
Folder 'GCA_013453055.1_PDT000792106.1' already exists. Skipping...
Folder 'GCA_013453075.1_PDT000792104.1' already exists. Skipping...
Folder 'GCA_013453095.1_PDT000792107.1' already exists. Skipping...
Folder 'GCA_013453115.1_PDT000792101.1' already exists. Skipping...
Folder 'GCA_013453215.1_PDT000792079.1' already exists. Skipping...
Folder 'GCA_013453255.1_PDT000792075.1' already exists. Skipping...
Folder 'GCA_013453275.1_PDT000792078.1' already exists. Skipping...
Folder 'GCA_013453295.1_PDT000792077.1' already exists. Skipping...
Folder 'GCA_013453315.1_PDT000792076.1' already exists. Skipping...
Folder 'GCA_013477565.1_PDT000793913.1' already exists. Skipping...
Folder 'GCA_013478125.1_PDT000794158.1' already exists. Skipping...
Folder 'GCA_013478585.1_PDT000793934.1' already exists. Skipping...
Folder 'GCA_013478925.1_PDT000794152.1' already exists. Skipping...
Folder 'GCA_013479045.1_PDT000794159.1' already exists. Skipping...
Folder 'GCA_013479285.1_PDT000794157.1' already exists. Skipping...
Folder 'GCA_013479325.1_PDT000794151.1' already exists. Skipping...
Folder 'GCA_013479425.1_PDT000794155.1' already exists. Skipping...
Folder 'GCA_013481065.1_PDT000793974.1' already exists. Skipping...
Folder 'GCA_013481165.1_PDT000793976.1' already exists. Skipping...
Folder 'GCA_013482125.1_PDT000793916.1' already exists. Skipping...
Folder 'GCA_013482285.1_PDT000793883.1' already exists. Skipping...
Folder 'GCA_013482545.1_PDT000793879.1' already exists. Skipping...
Folder 'GCA_013482765.1_PDT000793870.1' already exists. Skipping...
Folder 'GCA_013482785.1_PDT000793871.1' already exists. Skipping...
Folder 'GCA_013483005.1_PDT000793914.1' already exists. Skipping...
Folder 'GCA_013483025.1_PDT000793909.1' already exists. Skipping...
Folder 'GCA_013483225.1_PDT000793911.1' already exists. Skipping...
Folder 'GCA_013483265.1_PDT000793907.1' already exists. Skipping...
Folder 'GCA_013483465.1_PDT000792070.1' already exists. Skipping...
Folder 'GCA_013483545.1_PDT000792072.1' already exists. Skipping...
Folder 'GCA_013483765.1_PDT000793900.1' already exists. Skipping...
Folder 'GCA_013483845.1_PDT000793896.1' already exists. Skipping...
Folder 'GCA_013483855.1_PDT000793899.1' already exists. Skipping...
Folder 'GCA_013484165.1_PDT000792071.1' already exists. Skipping...
Folder 'GCA_013484285.1_PDT000792069.1' already exists. Skipping...
Folder 'GCA_013484665.1_PDT000794149.1' already exists. Skipping...
Folder 'GCA_013494475.1_PDT000784658.1' already exists. Skipping...
Folder 'GCA_013497455.1_PDT000784516.1' already exists. Skipping...
Folder 'GCA_013497495.1_PDT000784517.1' already exists. Skipping...
Folder 'GCA_013497905.1_PDT000785427.1' already exists. Skipping...
Folder 'GCA_013498015.1_PDT000785436.1' already exists. Skipping...
Folder 'GCA_013498035.1_PDT000785434.1' already exists. Skipping...
Folder 'GCA_013498055.1_PDT000785432.1' already exists. Skipping...
Folder 'GCA_013498095.1_PDT000785428.1' already exists. Skipping...
Folder 'GCA_013498155.1_PDT000785429.1' already exists. Skipping...
Folder 'GCA_013500015.1_PDT000785247.1' already exists. Skipping...
Folder 'GCA_013500105.1_PDT000785249.1' already exists. Skipping...
Folder 'GCA_013504935.1_PDT000784486.1' already exists. Skipping...
Folder 'GCA_013505015.1_PDT000784481.1' already exists. Skipping...
Folder 'GCA_013505055.1_PDT000784487.1' already exists. Skipping...
Folder 'GCA_013505115.1_PDT000784490.1' already exists. Skipping...
Folder 'GCA_013505235.1_PDT000784474.1' already exists. Skipping...
Folder 'GCA_013505255.1_PDT000784472.1' already exists. Skipping...
Folder 'GCA_013505315.1_PDT000784471.1' already exists. Skipping...
Folder 'GCA_013505355.1_PDT000784469.1' already exists. Skipping...
Folder 'GCA_013505375.1_PDT000784463.1' already exists. Skipping...
Folder 'GCA_013505395.1_PDT000784465.1' already exists. Skipping...
Folder 'GCA_013505435.1_PDT000784457.1' already exists. Skipping...
Folder 'GCA_013505515.1_PDT000784454.1' already exists. Skipping...
Folder 'GCA_013505555.1_PDT000784450.1' already exists. Skipping...
Folder 'GCA_013505575.1_PDT000784451.1' already exists. Skipping...
Folder 'GCA_013505595.1_PDT000784445.1' already exists. Skipping...
Folder 'GCA_013506215.1_PDT000784464.1' already exists. Skipping...
Folder 'GCA_013506495.1_PDT000795179.1' already exists. Skipping...
Folder 'GCA_013506515.1_PDT000784324.1' already exists. Skipping...
Folder 'GCA_013506555.1_PDT000784327.1' already exists. Skipping...
Folder 'GCA_013506615.1_PDT000784326.1' already exists. Skipping...
Folder 'GCA_013506695.1_PDT000784321.1' already exists. Skipping...
Folder 'GCA_013506715.1_PDT000784323.1' already exists. Skipping...
Folder 'GCA_013506755.1_PDT000784325.1' already exists. Skipping...
Folder 'GCA_013506775.1_PDT000784320.1' already exists. Skipping...
Folder 'GCA_013506895.1_PDT000784322.1' already exists. Skipping...
Folder 'GCA_013507695.1_PDT000784261.1' already exists. Skipping...
Folder 'GCA_013507715.1_PDT000784259.1' already exists. Skipping...
Folder 'GCA_013507735.1_PDT000784256.1' already exists. Skipping...
Folder 'GCA_013507755.1_PDT000784258.1' already exists. Skipping...
Folder 'GCA_013507795.1_PDT000784263.1' already exists. Skipping...
Folder 'GCA_013507815.1_PDT000784260.1' already exists. Skipping...
Folder 'GCA_013507835.1_PDT000784264.1' already exists. Skipping...
Folder 'GCA_013507875.1_PDT000784257.1' already exists. Skipping...
Folder 'GCA_013509415.1_PDT000784135.1' already exists. Skipping...
Folder 'GCA_013511095.1_PDT000784513.1' already exists. Skipping...
Folder 'GCA_013511255.1_PDT000784508.1' already exists. Skipping...
Folder 'GCA_013511295.1_PDT000784505.1' already exists. Skipping...
Folder 'GCA_013511345.1_PDT000784504.1' already exists. Skipping...
Folder 'GCA_013511465.1_PDT000784495.1' already exists. Skipping...
Folder 'GCA_013513735.1_PDT000785996.1' already exists. Skipping...
Folder 'GCA_013513755.1_PDT000785998.1' already exists. Skipping...
Folder 'GCA_013513835.1_PDT000785989.1' already exists. Skipping...
Folder 'GCA_013513855.1_PDT000785997.1' already exists. Skipping...
Folder 'GCA_013513915.1_PDT000785995.1' already exists. Skipping...
Folder 'GCA_013513985.1_PDT000785985.1' already exists. Skipping...
Folder 'GCA_013514055.1_PDT000785986.1' already exists. Skipping...
Folder 'GCA_013514075.1_PDT000785990.1' already exists. Skipping...
Folder 'GCA_013514105.1_PDT000785984.1' already exists. Skipping...
Folder 'GCA_013514185.1_PDT000785983.1' already exists. Skipping...
Folder 'GCA_013514295.1_PDT000785973.1' already exists. Skipping...
Folder 'GCA_013514315.1_PDT000785976.1' already exists. Skipping...
Folder 'GCA_013514325.1_PDT000785974.1' already exists. Skipping...
Folder 'GCA_013514335.1_PDT000785975.1' already exists. Skipping...
Folder 'GCA_013514415.1_PDT000785972.1' already exists. Skipping...
Folder 'GCA_013514435.1_PDT000785971.1' already exists. Skipping...
Folder 'GCA_013514445.1_PDT000785970.1' already exists. Skipping...
Folder 'GCA_013515585.1_PDT000785830.1' already exists. Skipping...
Folder 'GCA_013515695.1_PDT000785831.1' already exists. Skipping...
Folder 'GCA_013515755.1_PDT000785835.1' already exists. Skipping...
Folder 'GCA_013515955.1_PDT000785828.1' already exists. Skipping...
Folder 'GCA_013515975.1_PDT000785834.1' already exists. Skipping...
Folder 'GCA_013516035.1_PDT000785829.1' already exists. Skipping...
Folder 'GCA_013516095.1_PDT000785833.1' already exists. Skipping...
Folder 'GCA_013516275.1_PDT000785845.1' already exists. Skipping...
Folder 'GCA_013516375.1_PDT000785827.1' already exists. Skipping...
Folder 'GCA_013516395.1_PDT000785838.1' already exists. Skipping...
Folder 'GCA_013524475.1_PDT000787263.1' already exists. Skipping...
Folder 'GCA_013524495.1_PDT000787261.1' already exists. Skipping...
Folder 'GCA_013524515.1_PDT000787260.1' already exists. Skipping...
Folder 'GCA_013524555.1_PDT000787259.1' already exists. Skipping...
Folder 'GCA_013524575.1_PDT000787257.1' already exists. Skipping...
Folder 'GCA_013524615.1_PDT000787254.1' already exists. Skipping...
Folder 'GCA_013524695.1_PDT000787252.1' already exists. Skipping...
Folder 'GCA_013524715.1_PDT000787251.1' already exists. Skipping...
Folder 'GCA_013527595.1_PDT000783792.1' already exists. Skipping...
Folder 'GCA_013527795.1_PDT000783803.1' already exists. Skipping...
Folder 'GCA_013527835.1_PDT000783799.1' already exists. Skipping...
Folder 'GCA_013527875.1_PDT000783801.1' already exists. Skipping...

Retreiveing data: 71132it [00:12, 6692.13it/s]

Folder 'GCA_014148705.1_PDT000806800.1' already exists. Skipping...
Folder 'GCA_014148725.1_PDT000806799.1' already exists. Skipping...
Folder 'GCA_014148825.1_PDT000806791.1' already exists. Skipping...
Folder 'GCA_014149025.1_PDT000806789.1' already exists. Skipping...
Folder 'GCA_014149085.1_PDT000806785.1' already exists. Skipping...
Folder 'GCA_014149305.1_PDT000806766.1' already exists. Skipping...
Folder 'GCA_014149345.1_PDT000806762.1' already exists. Skipping...
Folder 'GCA_014149355.1_PDT000806767.1' already exists. Skipping...
Folder 'GCA_014149445.1_PDT000806760.1' already exists. Skipping...
Folder 'GCA_014149485.1_PDT000806761.1' already exists. Skipping...
Folder 'GCA_014149505.1_PDT000806759.1' already exists. Skipping...
Folder 'GCA_014149525.1_PDT000806758.1' already exists. Skipping...
Folder 'GCA_014149625.1_PDT000806751.1' already exists. Skipping...
Folder 'GCA_014149665.1_PDT000806753.1' already exists. Skipping...
Folder 'GCA_014149685.1_PDT000806750.1' already exists. Skipping...
Folder 'GCA_014149725.1_PDT000806748.1' already exists. Skipping...
Folder 'GCA_014149865.1_PDT000806743.1' already exists. Skipping...
Folder 'GCA_014149905.1_PDT000806739.1' already exists. Skipping...
Folder 'GCA_014149945.1_PDT000806737.1' already exists. Skipping...
Folder 'GCA_014149995.1_PDT000806736.1' already exists. Skipping...
Folder 'GCA_014152285.1_PDT000806591.1' already exists. Skipping...
Folder 'GCA_014152515.1_PDT000806602.1' already exists. Skipping...
Folder 'GCA_014153015.1_PDT000806564.1' already exists. Skipping...
Folder 'GCA_014153125.1_PDT000806567.1' already exists. Skipping...
Folder 'GCA_014153145.1_PDT000806563.1' already exists. Skipping...
Folder 'GCA_014153165.1_PDT000806568.1' already exists. Skipping...
Folder 'GCA_014153205.1_PDT000806558.1' already exists. Skipping...
Folder 'GCA_014153225.1_PDT000806559.1' already exists. Skipping...
Folder 'GCA_014153245.1_PDT000806556.1' already exists. Skipping...
Folder 'GCA_014153265.1_PDT000806565.1' already exists. Skipping...
Folder 'GCA_014153285.1_PDT000806560.1' already exists. Skipping...
Folder 'GCA_014153365.1_PDT000806554.1' already exists. Skipping...
Folder 'GCA_014153425.1_PDT000806553.1' already exists. Skipping...
Folder 'GCA_014153445.1_PDT000806550.1' already exists. Skipping...
Folder 'GCA_014153465.1_PDT000806547.1' already exists. Skipping...
Folder 'GCA_014153485.1_PDT000806551.1' already exists. Skipping...
Folder 'GCA_014153505.1_PDT000806546.1' already exists. Skipping...
Folder 'GCA_014153545.1_PDT000806544.1' already exists. Skipping...
Folder 'GCA_014153565.1_PDT000806549.1' already exists. Skipping...
Folder 'GCA_014153605.1_PDT000806542.1' already exists. Skipping...
Folder 'GCA_014153645.1_PDT000806540.1' already exists. Skipping...
Folder 'GCA_014153685.1_PDT000806539.1' already exists. Skipping...
Folder 'GCA_014153725.1_PDT000806536.1' already exists. Skipping...
Folder 'GCA_014153765.1_PDT000806535.1' already exists. Skipping...
Folder 'GCA_014153825.1_PDT000806531.1' already exists. Skipping...
Folder 'GCA_014154015.1_PDT000806526.1' already exists. Skipping...
Folder 'GCA_014154065.1_PDT000806528.1' already exists. Skipping...
Folder 'GCA_014154525.1_PDT000806416.1' already exists. Skipping...
Folder 'GCA_014154845.1_PDT000806519.1' already exists. Skipping...
Folder 'GCA_014155275.1_PDT000806590.1' already exists. Skipping...
Folder 'GCA_014161535.1_PDT000807405.1' already exists. Skipping...
Folder 'GCA_014161875.1_PDT000807398.1' already exists. Skipping...
Folder 'GCA_014162075.1_PDT000807401.1' already exists. Skipping...
Folder 'GCA_014162095.1_PDT000807406.1' already exists. Skipping...
Folder 'GCA_014162185.1_PDT000807403.1' already exists. Skipping...
Folder 'GCA_014162255.1_PDT000807390.1' already exists. Skipping...
Folder 'GCA_014162915.1_PDT000807411.1' already exists. Skipping...
Folder 'GCA_014162955.1_PDT000807402.1' already exists. Skipping...
Folder 'GCA_014163145.1_PDT000807389.1' already exists. Skipping...
Folder 'GCA_014167155.1_PDT000807521.1' already exists. Skipping...
Folder 'GCA_014167195.1_PDT000807522.1' already exists. Skipping...
Folder 'GCA_014170155.1_PDT000807704.1' already exists. Skipping...
Folder 'GCA_014170175.1_PDT000807707.1' already exists. Skipping...
Folder 'GCA_014170815.1_PDT000807708.1' already exists. Skipping...
Folder 'GCA_014174895.1_PDT000807650.2' already exists. Skipping...
Folder 'GCA_014174915.1_PDT000807649.2' already exists. Skipping...
Folder 'GCA_014174955.1_PDT000807645.2' already exists. Skipping...
Folder 'GCA_014174975.1_PDT000807646.2' already exists. Skipping...
Folder 'GCA_014175015.1_PDT000807642.2' already exists. Skipping...
Folder 'GCA_014175035.1_PDT000807643.2' already exists. Skipping...
Folder 'GCA_014175055.1_PDT000807641.2' already exists. Skipping...
Folder 'GCA_014175095.1_PDT000807644.2' already exists. Skipping...
Folder 'GCA_014184415.1_PDT000809333.1' already exists. Skipping...
Folder 'GCA_014205475.1_PDT000810005.1' already exists. Skipping...
Folder 'GCA_014213855.1_PDT000810170.1' already exists. Skipping...
Folder 'GCA_014214355.1_PDT000810169.1' already exists. Skipping...
Folder 'GCA_014214475.1_PDT000810167.1' already exists. Skipping...
Folder 'GCA_014214495.1_PDT000810168.1' already exists. Skipping...
Folder 'GCA_014214615.1_PDT000810163.1' already exists. Skipping...
Folder 'GCA_014214625.1_PDT000810164.1' already exists. Skipping...
Folder 'GCA_014214645.1_PDT000810166.1' already exists. Skipping...
Folder 'GCA_014214675.1_PDT000810162.1' already exists. Skipping...
Folder 'GCA_014214695.1_PDT000810160.1' already exists. Skipping...
Folder 'GCA_014214755.1_PDT000810161.1' already exists. Skipping...
Folder 'GCA_014221285.1_PDT000814208.1' already exists. Skipping...
Folder 'GCA_014221445.1_PDT000814164.1' already exists. Skipping...
Folder 'GCA_014221605.1_PDT000814154.1' already exists. Skipping...
Folder 'GCA_014231765.1_PDT000814363.1' already exists. Skipping...
Folder 'GCA_014231805.1_PDT000814360.1' already exists. Skipping...
Folder 'GCA_014232005.1_PDT000814323.1' already exists. Skipping...
Folder 'GCA_014232225.1_PDT000814342.1' already exists. Skipping...
Folder 'GCA_014232345.1_PDT000814322.1' already exists. Skipping...
Folder 'GCA_014232425.1_PDT000814321.1' already exists. Skipping...
Folder 'GCA_014232445.1_PDT000814320.1' already exists. Skipping...
Folder 'GCA_014232535.1_PDT000814343.1' already exists. Skipping...
Folder 'GCA_014234165.1_PDT000814157.1' already exists. Skipping...
Folder 'GCA_014235005.1_PDT000814155.1' already exists. Skipping...
Folder 'GCA_014243315.1_ASM1424331v1' already exists. Skipping...
Folder 'GCA_014243325.1_ASM1424332v1' already exists. Skipping...
Folder 'GCA_014243335.1_ASM1424333v1' already exists. Skipping...
Folder 'GCA_014245295.1_PDT000815879.1' already exists. Skipping...
Folder 'GCA_014245325.1_PDT000815880.1' already exists. Skipping...
Folder 'GCA_014246475.1_PDT000814908.1' already exists. Skipping...
Folder 'GCA_014246495.1_PDT000814909.1' already exists. Skipping...
Folder 'GCA_014246875.1_PDT000814905.1' already exists. Skipping...
Folder 'GCA_014247235.1_PDT000814915.1' already exists. Skipping...
Folder 'GCA_014247275.1_PDT000814899.1' already exists. Skipping...
Folder 'GCA_014247375.1_PDT000814897.1' already exists. Skipping...
Folder 'GCA_014247395.1_PDT000814889.1' already exists. Skipping...
Folder 'GCA_014247455.1_PDT000814911.1' already exists. Skipping...
Folder 'GCA_014247475.1_PDT000814864.1' already exists. Skipping...
Folder 'GCA_014247495.1_PDT000814861.1' already exists. Skipping...
Folder 'GCA_014247515.1_PDT000814860.1' already exists. Skipping...
Folder 'GCA_014247535.1_PDT000814863.1' already exists. Skipping...
Folder 'GCA_014247855.1_PDT000814880.1' already exists. Skipping...
Folder 'GCA_014248415.1_PDT000814901.1' already exists. Skipping...
Folder 'GCA_014249055.1_PDT000814789.1' already exists. Skipping...
Folder 'GCA_014253265.1_PDT000816479.1' already exists. Skipping...
Folder 'GCA_014253365.1_PDT000816478.1' already exists. Skipping...
Folder 'GCA_014254735.1_PDT000816270.1' already exists. Skipping...
Folder 'GCA_014257945.1_PDT000817278.1' already exists. Skipping...
Folder 'GCA_014257965.1_PDT000817280.1' already exists. Skipping...
Folder 'GCA_014258005.1_PDT000817276.1' already exists. Skipping...
Folder 'GCA_014258025.1_PDT000817274.1' already exists. Skipping...
Folder 'GCA_014258065.1_PDT000817272.1' already exists. Skipping...
Folder 'GCA_014258085.1_PDT000817270.1' already exists. Skipping...
Folder 'GCA_014258105.1_PDT000817277.1' already exists. Skipping...
Folder 'GCA_014258205.1_PDT000817267.1' already exists. Skipping...
Folder 'GCA_014258245.1_PDT000817264.1' already exists. Skipping...
Folder 'GCA_014258285.1_PDT000817262.1' already exists. Skipping...
Folder 'GCA_014258325.1_PDT000817260.1' already exists. Skipping...
Folder 'GCA_014258375.1_PDT000817258.1' already exists. Skipping...
Folder 'GCA_014258385.1_PDT000817256.1' already exists. Skipping...
Folder 'GCA_014258425.1_PDT000817257.1' already exists. Skipping...
Folder 'GCA_014258505.1_PDT000817252.1' already exists. Skipping...
Folder 'GCA_014258515.1_PDT000817253.1' already exists. Skipping...
Folder 'GCA_014258625.1_PDT000817240.1' already exists. Skipping...
Folder 'GCA_014258665.1_PDT000817234.1' already exists. Skipping...
Folder 'GCA_014258685.1_PDT000817235.1' already exists. Skipping...
Folder 'GCA_014258785.1_PDT000817231.1' already exists. Skipping...
Folder 'GCA_014258825.1_PDT000817226.1' already exists. Skipping...
Folder 'GCA_014258905.1_PDT000817224.1' already exists. Skipping...
Folder 'GCA_014259985.1_PDT000817232.1' already exists. Skipping...
Folder 'GCA_014260305.1_PDT000817233.1' already exists. Skipping...
Folder 'GCA_014263435.1_PDT000817320.1' already exists. Skipping...
Folder 'GCA_014263675.1_PDT000817321.1' already exists. Skipping...
Folder 'GCA_014264485.1_PDT000817408.1' already exists. Skipping...
Folder 'GCA_014265945.1_ASM1426594v1' already exists. Skipping...
Folder 'GCA_014271985.1_PDT000819557.1' already exists. Skipping...
Folder 'GCA_014272365.1_PDT000817791.1' already exists. Skipping...
Folder 'GCA_014273005.1_PDT000817788.1' already exists. Skipping...
Folder 'GCA_014273025.1_PDT000817790.1' already exists. Skipping...
Folder 'GCA_014273045.1_PDT000817789.1' already exists. Skipping...
Folder 'GCA_014273065.1_PDT000817786.1' already exists. Skipping...
Folder 'GCA_014273085.1_PDT000817787.1' already exists. Skipping...
Folder 'GCA_014273145.1_PDT000817784.1' already exists. Skipping...
Folder 'GCA_014273165.1_PDT000817785.1' already exists. Skipping...
Folder 'GCA_014273185.1_PDT000817783.1' already exists. Skipping...
Folder 'GCA_014274005.1_PDT000817727.1' already exists. Skipping...
Folder 'GCA_014275425.1_PDT000817638.1' already exists. Skipping...
Folder 'GCA_014275905.1_PDT000817632.1' already exists. Skipping...
Folder 'GCA_014275915.1_PDT000817633.1' already exists. Skipping...
Folder 'GCA_014275985.1_PDT000817627.1' already exists. Skipping...
Folder 'GCA_014276045.1_PDT000817624.1' already exists. Skipping...
Folder 'GCA_014276065.1_PDT000817626.1' already exists. Skipping...
Folder 'GCA_014276125.1_PDT000817620.1' already exists. Skipping...
Folder 'GCA_014276565.1_PDT000817564.1' already exists. Skipping...
Folder 'GCA_014277365.1_PDT000817567.1' already exists. Skipping...
Folder 'GCA_014277385.1_PDT000817566.1' already exists. Skipping...
Folder 'GCA_014277405.1_PDT000817568.1' already exists. Skipping...
Folder 'GCA_014277425.1_PDT000817569.1' already exists. Skipping...
Folder 'GCA_014277465.1_PDT000817570.1' already exists. Skipping...
Folder 'GCA_014277505.1_PDT000817565.1' already exists. Skipping...
Folder 'GCA_014280555.1_PDT000819824.1' already exists. Skipping...
Folder 'GCA_014280595.1_PDT000819813.1' already exists. Skipping...
Folder 'GCA_014281175.1_PDT000819842.1' already exists. Skipping...
Folder 'GCA_014281455.1_PDT000819843.1' already exists. Skipping...
Folder 'GCA_014291255.1_PDT000820034.1' already exists. Skipping...
Folder 'GCA_014291415.1_PDT000819982.1' already exists. Skipping...
Folder 'GCA_014291435.1_PDT000820002.1' already exists. Skipping...
Folder 'GCA_014291595.1_PDT000820035.1' already exists. Skipping...
Folder 'GCA_014291955.1_PDT000820009.1' already exists. Skipping...
Folder 'GCA_014292015.1_PDT000820007.1' already exists. Skipping...
Folder 'GCA_014292035.1_PDT000820008.1' already exists. Skipping...
Folder 'GCA_014292055.1_PDT000819983.1' already exists. Skipping...
Folder 'GCA_014292135.1_PDT000820003.1' already exists. Skipping...
Folder 'GCA_014292195.1_PDT000820000.1' already exists. Skipping...
Folder 'GCA_014292235.1_PDT000819998.1' already exists. Skipping...
Folder 'GCA_014292295.1_PDT000819995.1' already exists. Skipping...
Folder 'GCA_014298915.1_PDT000820826.1' already exists. Skipping...
Folder 'GCA_014299155.1_PDT000820796.1' already exists. Skipping...
Folder 'GCA_014299355.1_PDT000820798.1' already exists. Skipping...
Folder 'GCA_014299655.1_PDT000820793.1' already exists. Skipping...
Folder 'GCA_014299715.1_PDT000820787.1' already exists. Skipping...
Folder 'GCA_014299875.1_PDT000820786.1' already exists. Skipping...
Folder 'GCA_014299895.1_PDT000820785.1' already exists. Skipping...
Folder 'GCA_014299935.1_PDT000820782.1' already exists. Skipping...
Folder 'GCA_014299975.1_PDT000820779.1' already exists. Skipping...
Folder 'GCA_014300035.1_PDT000820749.1' already exists. Skipping...
Folder 'GCA_014300105.1_PDT000820755.1' already exists. Skipping...
Folder 'GCA_014300145.1_PDT000820748.1' already exists. Skipping...
Folder 'GCA_014300165.1_PDT000820752.1' already exists. Skipping...
Folder 'GCA_014300305.1_PDT000820751.1' already exists. Skipping...
Folder 'GCA_014300345.1_PDT000820776.1' already exists. Skipping...
Folder 'GCA_014300365.1_PDT000820754.1' already exists. Skipping...
Folder 'GCA_014300385.1_PDT000820775.1' already exists. Skipping...
Folder 'GCA_014300745.1_PDT000820697.1' already exists. Skipping...
Folder 'GCA_014300765.1_PDT000820701.1' already exists. Skipping...
Folder 'GCA_014301315.1_PDT000820712.1' already exists. Skipping...
Folder 'GCA_014301345.1_PDT000820705.1' already exists. Skipping...
Folder 'GCA_014301385.1_PDT000820708.1' already exists. Skipping...
Folder 'GCA_014301465.1_PDT000820696.1' already exists. Skipping...
Folder 'GCA_014301505.1_PDT000820691.1' already exists. Skipping...
Folder 'GCA_014301525.1_PDT000820693.1' already exists. Skipping...
Folder 'GCA_014301545.1_PDT000820692.1' already exists. Skipping...
Folder 'GCA_014301585.1_PDT000820689.1' already exists. Skipping...
Folder 'GCA_014301885.1_PDT000820671.1' already exists. Skipping...
Folder 'GCA_014302555.1_PDT000820640.1' already exists. Skipping...
Folder 'GCA_014302615.1_PDT000820639.1' already exists. Skipping...
Folder 'GCA_014305235.1_ASM1430523v1' already exists. Skipping...
Folder 'GCA_014305275.1_ASM1430527v1' already exists. Skipping...
Folder 'GCA_014305285.1_ASM1430528v1' already exists. Skipping...
Folder 'GCA_014307655.1_PDT000821888.1' already exists. Skipping...
Folder 'GCA_014307795.1_PDT000821864.1' already exists. Skipping...
Folder 'GCA_014307815.1_PDT000821865.1' already exists. Skipping...
Folder 'GCA_014307855.1_PDT000821863.1' already exists. Skipping...
Folder 'GCA_014307875.1_PDT000821862.1' already exists. Skipping...
Folder 'GCA_014308015.1_PDT000821871.1' already exists. Skipping...
Folder 'GCA_014308035.1_PDT000821866.1' already exists. Skipping...
Folder 'GCA_014308095.1_PDT000821855.1' already exists. Skipping...
Folder 'GCA_014309755.1_PDT000821854.1' already exists. Skipping...
Folder 'GCA_014311315.1_PDT000821630.1' already exists. Skipping...
Folder 'GCA_014314085.1_PDT000821856.1' already exists. Skipping...
Folder 'GCA_014318095.1_PDT000821870.1' already exists. Skipping...
Folder 'GCA_014339075.1_PDT000826874.1' already exists. Skipping...
Folder 'GCA_014339095.1_PDT000826876.1' already exists. Skipping...
Folder 'GCA_014339135.1_PDT000826873.1' already exists. Skipping...
Folder 'GCA_014339155.1_PDT000826867.1' already exists. Skipping...
Folder 'GCA_014339175.1_PDT000826832.1' already exists. Skipping...
Folder 'GCA_014339335.1_PDT000826830.1' already exists. Skipping...
Folder 'GCA_014339875.1_PDT000826863.1' already exists. Skipping...
Folder 'GCA_014339915.1_PDT000826861.1' already exists. Skipping...
Folder 'GCA_014340315.1_PDT000826644.1' already exists. Skipping...
Folder 'GCA_014340595.1_PDT000820688.1' already exists. Skipping...
Folder 'GCA_014341805.1_PDT000810159.1' already exists. Skipping...
Folder 'GCA_014341955.1_PDT000826862.1' already exists. Skipping...
Folder 'GCA_014342335.1_PDT000826866.1' already exists. Skipping...
Folder 'GCA_014342575.1_PDT000717271.1' already exists. Skipping...
Folder 'GCA_014342775.1_PDT000717273.1' already exists. Skipping...
Folder 'GCA_014342975.1_PDT000721112.1' already exists. Skipping...
Folder 'GCA_014342995.1_PDT000721121.1' already exists. Skipping...
Folder 'GCA_014343135.1_PDT000717268.1' already exists. Skipping...
Folder 'GCA_014343735.1_PDT000686978.1' already exists. Skipping...
Folder 'GCA_014343755.1_PDT000686999.1' already exists. Skipping...
Folder 'GCA_014344795.1_PDT000826858.1' already exists. Skipping...
Folder 'GCA_014344815.1_PDT000826868.1' already exists. Skipping...
Folder 'GCA_014344875.1_PDT000826837.1' already exists. Skipping...
Folder 'GCA_014345605.1_PDT000627528.1' already exists. Skipping...
Folder 'GCA_014345855.1_PDT000567188.1' already exists. Skipping...
Folder 'GCA_014345975.1_PDT000567143.1' already exists. Skipping...
Folder 'GCA_014345995.1_PDT000567121.1' already exists. Skipping...
Folder 'GCA_014346595.1_PDT000826864.1' already exists. Skipping...
Folder 'GCA_014347695.1_PDT000826875.1' already exists. Skipping...
Folder 'GCA_014347755.1_PDT000826869.1' already exists. Skipping...
Folder 'GCA_014349515.1_PDT000826925.1' already exists. Skipping...
Folder 'GCA_014349635.1_PDT000826928.1' already exists. Skipping...
Folder 'GCA_014349935.1_PDT000827005.1' already exists. Skipping...
Folder 'GCA_014351285.1_PDT000826954.1' already exists. Skipping...
Folder 'GCA_014351375.1_PDT000826952.1' already exists. Skipping...
Folder 'GCA_014356395.1_PDT000823273.1' already exists. Skipping...
Folder 'GCA_014356875.1_PDT000822993.1' already exists. Skipping...
Folder 'GCA_014356975.1_PDT000823077.1' already exists. Skipping...
Folder 'GCA_014363435.1_PDT000814134.1' already exists. Skipping...
Folder 'GCA_014363475.1_PDT000814133.1' already exists. Skipping...
Folder 'GCA_014363535.1_PDT000814132.1' already exists. Skipping...
Folder 'GCA_014363755.1_PDT000814123.1' already exists. Skipping...
Folder 'GCA_014363775.1_PDT000814121.1' already exists. Skipping...
Folder 'GCA_014364385.1_PDT000816976.1' already exists. Skipping...
Folder 'GCA_014364405.1_PDT000816977.1' already exists. Skipping...
Folder 'GCA_014364465.1_PDT000816975.1' already exists. Skipping...
Folder 'GCA_014364485.1_PDT000816971.1' already exists. Skipping...
Folder 'GCA_014364525.1_PDT000816968.1' already exists. Skipping...
Folder 'GCA_014364595.1_PDT000814109.1' already exists. Skipping...
Folder 'GCA_014364655.1_PDT000816964.1' already exists. Skipping...
Folder 'GCA_014364685.1_PDT000816962.1' already exists. Skipping...
Folder 'GCA_014364695.1_PDT000816963.1' already exists. Skipping...
Folder 'GCA_014364725.1_PDT000816960.1' already exists. Skipping...
Folder 'GCA_014364785.1_PDT000814120.1' already exists. Skipping...
Folder 'GCA_014364865.1_PDT000814117.1' already exists. Skipping...
Folder 'GCA_014364925.1_PDT000814111.1' already exists. Skipping...
Folder 'GCA_014364985.1_PDT000814113.1' already exists. Skipping...
Folder 'GCA_014365125.1_PDT000827463.1' already exists. Skipping...
Folder 'GCA_014366305.1_PDT000809355.1' already exists. Skipping...
Folder 'GCA_014366725.1_PDT000806888.1' already exists. Skipping...

Retreiveing data: 72472it [00:12, 6660.05it/s]

Folder 'GCA_015079695.1_PDT000856951.1' already exists. Skipping...
Folder 'GCA_015079715.1_PDT000856948.1' already exists. Skipping...
Folder 'GCA_015079735.1_PDT000856945.1' already exists. Skipping...
Folder 'GCA_015079755.1_PDT000856949.1' already exists. Skipping...
Folder 'GCA_015079775.1_PDT000856943.1' already exists. Skipping...
Folder 'GCA_015079795.1_PDT000856942.1' already exists. Skipping...
Folder 'GCA_015079815.1_PDT000856944.1' already exists. Skipping...
Folder 'GCA_015079835.1_PDT000856941.1' already exists. Skipping...
Folder 'GCA_015080255.1_PDT000856854.1' already exists. Skipping...
Folder 'GCA_015080315.1_PDT000856852.1' already exists. Skipping...
Folder 'GCA_015080335.1_PDT000856853.1' already exists. Skipping...
Folder 'GCA_015080375.1_PDT000856851.1' already exists. Skipping...
Folder 'GCA_015080455.1_PDT000856843.1' already exists. Skipping...
Folder 'GCA_015080565.1_PDT000856842.1' already exists. Skipping...
Folder 'GCA_015080935.1_PDT000856804.1' already exists. Skipping...
Folder 'GCA_015080955.1_PDT000856799.1' already exists. Skipping...
Folder 'GCA_015080975.1_PDT000856801.1' already exists. Skipping...
Folder 'GCA_015081035.1_PDT000856796.1' already exists. Skipping...
Folder 'GCA_015081095.1_PDT000856795.1' already exists. Skipping...
Folder 'GCA_015081115.1_PDT000856792.1' already exists. Skipping...
Folder 'GCA_015081125.1_PDT000856790.1' already exists. Skipping...
Folder 'GCA_015081155.1_PDT000856955.1' already exists. Skipping...
Folder 'GCA_015081255.1_PDT000856783.1' already exists. Skipping...
Folder 'GCA_015081275.1_PDT000856784.1' already exists. Skipping...
Folder 'GCA_015081315.1_PDT000856781.1' already exists. Skipping...
Folder 'GCA_015081395.1_PDT000856791.1' already exists. Skipping...
Folder 'GCA_015081435.1_PDT000856779.1' already exists. Skipping...
Folder 'GCA_015081455.1_PDT000856787.1' already exists. Skipping...
Folder 'GCA_015085415.1_PDT000856404.1' already exists. Skipping...
Folder 'GCA_015085475.1_PDT000856403.1' already exists. Skipping...
Folder 'GCA_015085495.1_PDT000856402.1' already exists. Skipping...
Folder 'GCA_015085535.1_PDT000856399.1' already exists. Skipping...
Folder 'GCA_015085555.1_PDT000856401.1' already exists. Skipping...
Folder 'GCA_015085595.1_PDT000856393.1' already exists. Skipping...
Folder 'GCA_015085655.1_PDT000856390.1' already exists. Skipping...
Folder 'GCA_015085675.1_PDT000856394.1' already exists. Skipping...
Folder 'GCA_015085735.1_PDT000856392.1' already exists. Skipping...
Folder 'GCA_015085775.1_PDT000856389.1' already exists. Skipping...
Folder 'GCA_015085795.1_PDT000856386.1' already exists. Skipping...
Folder 'GCA_015086455.1_PDT000856338.1' already exists. Skipping...
Folder 'GCA_015086535.1_PDT000856333.1' already exists. Skipping...
Folder 'GCA_015086555.1_PDT000856330.1' already exists. Skipping...
Folder 'GCA_015086655.1_PDT000856782.1' already exists. Skipping...
Folder 'GCA_015086675.1_PDT000856788.1' already exists. Skipping...
Folder 'GCA_015087655.1_PDT000856321.1' already exists. Skipping...
Folder 'GCA_015087775.1_PDT000856275.1' already exists. Skipping...
Folder 'GCA_015087875.1_PDT000856319.1' already exists. Skipping...
Folder 'GCA_015087895.1_PDT000856312.1' already exists. Skipping...
Folder 'GCA_015087905.1_PDT000856316.1' already exists. Skipping...
Folder 'GCA_015087995.1_PDT000856301.1' already exists. Skipping...
Folder 'GCA_015088015.1_PDT000856299.1' already exists. Skipping...
Folder 'GCA_015088055.1_PDT000856297.1' already exists. Skipping...
Folder 'GCA_015088075.1_PDT000856298.1' already exists. Skipping...
Folder 'GCA_015088095.1_PDT000856296.1' already exists. Skipping...
Folder 'GCA_015088155.1_PDT000856295.1' already exists. Skipping...
Folder 'GCA_015088195.1_PDT000856291.1' already exists. Skipping...
Folder 'GCA_015088235.1_PDT000856289.1' already exists. Skipping...
Folder 'GCA_015088255.1_PDT000856286.1' already exists. Skipping...
Folder 'GCA_015088295.1_PDT000856288.1' already exists. Skipping...
Folder 'GCA_015088315.1_PDT000856283.1' already exists. Skipping...
Folder 'GCA_015088475.1_PDT000856311.1' already exists. Skipping...
Folder 'GCA_015088535.1_PDT000856278.1' already exists. Skipping...
Folder 'GCA_015088555.1_PDT000856307.1' already exists. Skipping...
Folder 'GCA_015088575.1_PDT000856277.1' already exists. Skipping...
Folder 'GCA_015088595.1_PDT000856306.1' already exists. Skipping...
Folder 'GCA_015088635.1_PDT000856308.1' already exists. Skipping...
Folder 'GCA_015088695.1_PDT000856247.1' already exists. Skipping...
Folder 'GCA_015088715.1_PDT000856305.1' already exists. Skipping...
Folder 'GCA_015088755.1_PDT000856300.1' already exists. Skipping...
Folder 'GCA_015088775.1_PDT000856264.1' already exists. Skipping...
Folder 'GCA_015088795.1_PDT000856259.1' already exists. Skipping...
Folder 'GCA_015088835.1_PDT000856263.1' already exists. Skipping...
Folder 'GCA_015088875.1_PDT000856260.1' already exists. Skipping...
Folder 'GCA_015088915.1_PDT000856211.1' already exists. Skipping...
Folder 'GCA_015088975.1_PDT000856213.1' already exists. Skipping...
Folder 'GCA_015088995.1_PDT000856251.1' already exists. Skipping...
Folder 'GCA_015089075.1_PDT000856210.1' already exists. Skipping...
Folder 'GCA_015089095.1_PDT000856206.1' already exists. Skipping...
Folder 'GCA_015089115.1_PDT000856220.1' already exists. Skipping...
Folder 'GCA_015089135.1_PDT000856204.1' already exists. Skipping...
Folder 'GCA_015089195.1_PDT000856327.1' already exists. Skipping...
Folder 'GCA_015089215.1_PDT000856326.1' already exists. Skipping...
Folder 'GCA_015089295.1_PDT000856184.1' already exists. Skipping...
Folder 'GCA_015089315.1_PDT000856188.1' already exists. Skipping...
Folder 'GCA_015089775.1_PDT000856166.1' already exists. Skipping...
Folder 'GCA_015089835.1_PDT000856270.1' already exists. Skipping...
Folder 'GCA_015089855.1_PDT000856248.1' already exists. Skipping...
Folder 'GCA_015090055.1_PDT000856229.1' already exists. Skipping...
Folder 'GCA_015090135.1_PDT000856234.1' already exists. Skipping...
Folder 'GCA_015090155.1_PDT000856232.1' already exists. Skipping...
Folder 'GCA_015090205.1_PDT000856228.1' already exists. Skipping...
Folder 'GCA_015090295.1_PDT000856221.1' already exists. Skipping...
Folder 'GCA_015090395.1_PDT000856200.1' already exists. Skipping...
Folder 'GCA_015090415.1_PDT000856201.1' already exists. Skipping...
Folder 'GCA_015090455.1_PDT000856167.1' already exists. Skipping...
Folder 'GCA_015090495.1_PDT000856253.1' already exists. Skipping...
Folder 'GCA_015090555.1_PDT000856196.1' already exists. Skipping...
Folder 'GCA_015090595.1_PDT000856194.1' already exists. Skipping...
Folder 'GCA_015090655.1_PDT000856192.1' already exists. Skipping...
Folder 'GCA_015090695.1_PDT000856187.1' already exists. Skipping...
Folder 'GCA_015090705.1_PDT000856186.1' already exists. Skipping...
Folder 'GCA_015090775.1_PDT000856185.1' already exists. Skipping...
Folder 'GCA_015090795.1_PDT000856183.1' already exists. Skipping...
Folder 'GCA_015090835.1_PDT000856179.1' already exists. Skipping...
Folder 'GCA_015090995.1_PDT000856171.1' already exists. Skipping...
Folder 'GCA_015113575.1_PDT000855504.1' already exists. Skipping...
Folder 'GCA_015113615.1_PDT000855546.1' already exists. Skipping...
Folder 'GCA_015114035.1_PDT000855496.1' already exists. Skipping...
Folder 'GCA_015114175.1_PDT000855460.1' already exists. Skipping...
Folder 'GCA_015114195.1_PDT000855514.1' already exists. Skipping...
Folder 'GCA_015114435.1_PDT000855461.1' already exists. Skipping...
Folder 'GCA_015114575.1_PDT000855463.1' already exists. Skipping...
Folder 'GCA_015114715.1_PDT000855513.1' already exists. Skipping...
Folder 'GCA_015114735.1_PDT000855512.1' already exists. Skipping...
Folder 'GCA_015116015.1_PDT000855435.1' already exists. Skipping...
Folder 'GCA_015116215.1_PDT000855515.1' already exists. Skipping...
Folder 'GCA_015116625.1_PDT000855462.1' already exists. Skipping...
Folder 'GCA_015117355.1_PDT000855506.1' already exists. Skipping...
Folder 'GCA_015117955.1_PDT000855528.1' already exists. Skipping...
Folder 'GCA_015120315.1_PDT000871617.1' already exists. Skipping...
Folder 'GCA_015121025.1_PDT000871616.1' already exists. Skipping...
Folder 'GCA_015138895.1_PDT000854583.1' already exists. Skipping...
Folder 'GCA_015139635.1_PDT000854559.1' already exists. Skipping...
Folder 'GCA_015139655.1_PDT000854575.1' already exists. Skipping...
Folder 'GCA_015139675.1_PDT000854581.1' already exists. Skipping...
Folder 'GCA_015139695.1_PDT000854577.1' already exists. Skipping...
Folder 'GCA_015139995.1_PDT000854539.1' already exists. Skipping...
Folder 'GCA_015140035.1_PDT000854542.1' already exists. Skipping...
Folder 'GCA_015140075.1_PDT000854537.1' already exists. Skipping...
Folder 'GCA_015140165.1_PDT000854561.1' already exists. Skipping...
Folder 'GCA_015140215.1_PDT000854569.1' already exists. Skipping...
Folder 'GCA_015140265.1_PDT000854564.1' already exists. Skipping...
Folder 'GCA_015140315.1_PDT000854566.1' already exists. Skipping...
Folder 'GCA_015140375.1_PDT000854571.1' already exists. Skipping...
Folder 'GCA_015140435.1_PDT000854560.1' already exists. Skipping...
Folder 'GCA_015140495.1_PDT000854585.1' already exists. Skipping...
Folder 'GCA_015140515.1_PDT000854587.1' already exists. Skipping...
Folder 'GCA_015140535.1_PDT000854580.1' already exists. Skipping...
Folder 'GCA_015140555.1_PDT000854534.1' already exists. Skipping...
Folder 'GCA_015140675.1_PDT000854555.1' already exists. Skipping...
Folder 'GCA_015140695.1_PDT000854554.1' already exists. Skipping...
Folder 'GCA_015140715.1_PDT000854556.1' already exists. Skipping...
Folder 'GCA_015140735.1_PDT000854549.1' already exists. Skipping...
Folder 'GCA_015140775.1_PDT000854551.1' already exists. Skipping...
Folder 'GCA_015140815.1_PDT000854522.1' already exists. Skipping...
Folder 'GCA_015140855.1_PDT000854519.1' already exists. Skipping...
Folder 'GCA_015140875.1_PDT000854521.1' already exists. Skipping...
Folder 'GCA_015140895.1_PDT000854523.1' already exists. Skipping...
Folder 'GCA_015140915.1_PDT000854518.1' already exists. Skipping...
Folder 'GCA_015140935.1_PDT000854509.1' already exists. Skipping...
Folder 'GCA_015141075.1_PDT000854540.1' already exists. Skipping...
Folder 'GCA_015141095.1_PDT000854552.1' already exists. Skipping...
Folder 'GCA_015141115.1_PDT000854550.1' already exists. Skipping...
Folder 'GCA_015141135.1_PDT000854531.1' already exists. Skipping...
Folder 'GCA_015141175.1_PDT000854557.1' already exists. Skipping...
Folder 'GCA_015141195.1_PDT000854558.1' already exists. Skipping...
Folder 'GCA_015141205.1_PDT000854546.1' already exists. Skipping...
Folder 'GCA_015141235.1_PDT000854525.1' already exists. Skipping...
Folder 'GCA_015141255.1_PDT000854514.1' already exists. Skipping...
Folder 'GCA_015141275.1_PDT000854506.1' already exists. Skipping...
Folder 'GCA_015141315.1_PDT000854573.1' already exists. Skipping...
Folder 'GCA_015141375.1_PDT000854574.1' already exists. Skipping...
Folder 'GCA_015141395.1_PDT000854582.1' already exists. Skipping...
Folder 'GCA_015141455.1_PDT000854536.1' already exists. Skipping...
Folder 'GCA_015141475.1_PDT000854545.1' already exists. Skipping...
Folder 'GCA_015141595.1_PDT000854527.1' already exists. Skipping...
Folder 'GCA_015141675.1_PDT000854533.1' already exists. Skipping...
Folder 'GCA_015141695.1_PDT000854535.1' already exists. Skipping...
Folder 'GCA_015141735.1_PDT000854485.1' already exists. Skipping...
Folder 'GCA_015141775.1_PDT000854489.1' already exists. Skipping...
Folder 'GCA_015141835.1_PDT000854572.1' already exists. Skipping...
Folder 'GCA_015141855.1_PDT000854543.1' already exists. Skipping...
Folder 'GCA_015141895.1_PDT000854570.1' already exists. Skipping...
Folder 'GCA_015141915.1_PDT000854520.1' already exists. Skipping...
Folder 'GCA_015141935.1_PDT000854507.1' already exists. Skipping...
Folder 'GCA_015141975.1_PDT000854508.1' already exists. Skipping...
Folder 'GCA_015142015.1_PDT000854576.1' already exists. Skipping...
Folder 'GCA_015142055.1_PDT000854567.1' already exists. Skipping...
Folder 'GCA_015142095.1_PDT000854584.1' already exists. Skipping...
Folder 'GCA_015142135.1_PDT000854547.1' already exists. Skipping...
Folder 'GCA_015142175.1_PDT000854565.1' already exists. Skipping...
Folder 'GCA_015142315.1_PDT000854515.1' already exists. Skipping...
Folder 'GCA_015142375.1_PDT000854510.1' already exists. Skipping...
Folder 'GCA_015142475.1_PDT000854528.1' already exists. Skipping...
Folder 'GCA_015142495.1_PDT000854511.1' already exists. Skipping...
Folder 'GCA_015142695.1_PDT000854513.1' already exists. Skipping...
Folder 'GCA_015142775.1_PDT000854487.1' already exists. Skipping...
Folder 'GCA_015142815.1_PDT000854486.1' already exists. Skipping...
Folder 'GCA_015142855.1_PDT000854488.1' already exists. Skipping...
Folder 'GCA_015142955.1_PDT000854491.1' already exists. Skipping...
Folder 'GCA_015143055.1_PDT000854490.1' already exists. Skipping...
Folder 'GCA_015151535.1_PDT000854483.1' already exists. Skipping...
Folder 'GCA_015151585.1_PDT000854482.1' already exists. Skipping...
Folder 'GCA_015152935.1_PDT000853736.1' already exists. Skipping...
Folder 'GCA_015155055.1_PDT000853591.1' already exists. Skipping...
Folder 'GCA_015155075.1_PDT000853593.1' already exists. Skipping...
Folder 'GCA_015155115.1_PDT000853594.1' already exists. Skipping...
Folder 'GCA_015155675.1_PDT000853592.1' already exists. Skipping...
Folder 'GCA_015157435.1_PDT000853576.1' already exists. Skipping...
Folder 'GCA_015157475.1_PDT000853578.1' already exists. Skipping...
Folder 'GCA_015157555.1_PDT000853580.1' already exists. Skipping...
Folder 'GCA_015157575.1_PDT000853577.1' already exists. Skipping...
Folder 'GCA_015157635.1_PDT000853546.1' already exists. Skipping...
Folder 'GCA_015157875.1_PDT000853590.1' already exists. Skipping...
Folder 'GCA_015157975.1_PDT000853575.1' already exists. Skipping...
Folder 'GCA_015158015.1_PDT000853549.1' already exists. Skipping...
Folder 'GCA_015158075.1_PDT000853548.1' already exists. Skipping...
Folder 'GCA_015158235.1_PDT000853547.1' already exists. Skipping...
Folder 'GCA_015159475.1_PDT000873456.1' already exists. Skipping...
Folder 'GCA_015164495.1_PDT000873896.1' already exists. Skipping...
Folder 'GCA_015164535.1_PDT000873897.1' already exists. Skipping...
Folder 'GCA_015164575.1_PDT000873898.1' already exists. Skipping...
Folder 'GCA_015164935.1_PDT000872790.1' already exists. Skipping...
Folder 'GCA_015165485.1_PDT000872786.1' already exists. Skipping...
Folder 'GCA_015166695.1_PDT000872596.1' already exists. Skipping...
Folder 'GCA_015166735.1_PDT000872595.1' already exists. Skipping...
Folder 'GCA_015166835.1_PDT000872593.1' already exists. Skipping...
Folder 'GCA_015167015.1_PDT000872582.1' already exists. Skipping...
Folder 'GCA_015167025.1_PDT000872579.1' already exists. Skipping...
Folder 'GCA_015167035.1_PDT000872581.1' already exists. Skipping...
Folder 'GCA_015167075.1_PDT000872578.1' already exists. Skipping...
Folder 'GCA_015167095.1_PDT000872580.1' already exists. Skipping...
Folder 'GCA_015167135.1_PDT000872583.1' already exists. Skipping...
Folder 'GCA_015169495.1_PDT000872868.1' already exists. Skipping...
Folder 'GCA_015169955.1_PDT000872789.1' already exists. Skipping...
Folder 'GCA_015170535.1_PDT000872788.1' already exists. Skipping...
Folder 'GCA_015170575.1_PDT000872784.1' already exists. Skipping...
Folder 'GCA_015172935.1_PDT000872616.1' already exists. Skipping...
Folder 'GCA_015172985.1_PDT000872615.1' already exists. Skipping...
Folder 'GCA_015173005.1_PDT000872627.1' already exists. Skipping...
Folder 'GCA_015173045.1_PDT000872628.1' already exists. Skipping...
Folder 'GCA_015173125.1_PDT000872625.1' already exists. Skipping...
Folder 'GCA_015173185.1_PDT000872619.1' already exists. Skipping...
Folder 'GCA_015173665.1_PDT000872623.1' already exists. Skipping...
Folder 'GCA_015173945.1_PDT000873895.1' already exists. Skipping...
Folder 'GCA_015174065.1_PDT000873894.1' already exists. Skipping...
Folder 'GCA_015176545.1_PDT000873698.1' already exists. Skipping...
Folder 'GCA_015176585.1_PDT000873694.1' already exists. Skipping...
Folder 'GCA_015176645.1_PDT000873695.1' already exists. Skipping...
Folder 'GCA_015176745.1_PDT000873692.1' already exists. Skipping...
Folder 'GCA_015176785.1_PDT000873690.1' already exists. Skipping...
Folder 'GCA_015176805.1_PDT000873685.1' already exists. Skipping...
Folder 'GCA_015176815.1_PDT000873693.1' already exists. Skipping...
Folder 'GCA_015176845.1_PDT000873689.1' already exists. Skipping...
Folder 'GCA_015177025.1_PDT000873679.1' already exists. Skipping...
Folder 'GCA_015177045.1_PDT000873676.1' already exists. Skipping...
Folder 'GCA_015177145.1_PDT000873675.1' already exists. Skipping...
Folder 'GCA_015177245.1_PDT000873647.1' already exists. Skipping...
Folder 'GCA_015177285.1_PDT000873646.1' already exists. Skipping...
Folder 'GCA_015177305.1_PDT000873648.1' already exists. Skipping...
Folder 'GCA_015177345.1_PDT000873633.1' already exists. Skipping...
Folder 'GCA_015177405.1_PDT000873630.1' already exists. Skipping...
Folder 'GCA_015177545.1_PDT000873657.1' already exists. Skipping...
Folder 'GCA_015177585.1_PDT000873649.1' already exists. Skipping...
Folder 'GCA_015177625.1_PDT000873652.1' already exists. Skipping...
Folder 'GCA_015177645.1_PDT000873653.1' already exists. Skipping...
Folder 'GCA_015177705.1_PDT000873643.1' already exists. Skipping...
Folder 'GCA_015177725.1_PDT000873651.1' already exists. Skipping...
Folder 'GCA_015177785.1_PDT000873641.1' already exists. Skipping...
Folder 'GCA_015177805.1_PDT000873639.1' already exists. Skipping...
Folder 'GCA_015177825.1_PDT000873638.1' already exists. Skipping...
Folder 'GCA_015177845.1_PDT000873636.1' already exists. Skipping...
Folder 'GCA_015177885.1_PDT000873631.1' already exists. Skipping...
Folder 'GCA_015177905.1_PDT000873635.1' already exists. Skipping...
Folder 'GCA_015182025.1_PDT000873457.1' already exists. Skipping...
Folder 'GCA_015182085.1_PDT000873458.1' already exists. Skipping...
Folder 'GCA_015182105.1_PDT000873455.1' already exists. Skipping...
Folder 'GCA_015182125.1_PDT000873454.1' already exists. Skipping...
Folder 'GCA_015186885.1_PDT000853331.1' already exists. Skipping...
Folder 'GCA_015186945.1_PDT000853320.1' already exists. Skipping...
Folder 'GCA_015187025.1_PDT000853318.1' already exists. Skipping...
Folder 'GCA_015187085.1_PDT000853319.1' already exists. Skipping...
Folder 'GCA_015187265.1_PDT000853291.1' already exists. Skipping...
Folder 'GCA_015187405.1_PDT000853283.1' already exists. Skipping...
Folder 'GCA_015187425.1_PDT000853287.1' already exists. Skipping...
Folder 'GCA_015187445.1_PDT000853284.1' already exists. Skipping...
Folder 'GCA_015187485.1_PDT000853282.1' already exists. Skipping...
Folder 'GCA_015187745.1_PDT000853285.1' already exists. Skipping...
Folder 'GCA_015187785.1_PDT000853279.1' already exists. Skipping...
Folder 'GCA_015187825.1_PDT000853277.1' already exists. Skipping...
Folder 'GCA_015187865.1_PDT000853280.1' already exists. Skipping...
Folder 'GCA_015187945.1_PDT000853270.1' already exists. Skipping...
Folder 'GCA_015187965.1_PDT000853269.1' already exists. Skipping...
Folder 'GCA_015191325.1_PDT000852239.1' already exists. Skipping...
Folder 'GCA_015192025.1_PDT000852217.1' already exists. Skipping...
Folder 'GCA_015192825.1_PDT000852043.1' already exists. Skipping...
Folder 'GCA_015192925.1_PDT000852034.1' already exists. Skipping...
Folder 'GCA_015194045.1_PDT000851976.1' already exists. Skipping...
Folder 'GCA_015194285.1_PDT000851974.1' already exists. Skipping...
Folder 'GCA_015195185.1_PDT000784458.3' already exists. Skipping...
Folder 'GCA_015195685.1_PDT000610226.3' already exists. Skipping...
Folder 'GCA_015195725.1_PDT000608861.3' already exists. Skipping...
Folder 'GCA_015195785.1_PDT000851941.1' already exists. Skipping...
Folder 'GCA_015195925.1_PDT000610202.3' already exists. Skipping...

Retreiveing data: 73808it [00:12, 6650.75it/s]

Folder 'GCA_016414065.1_PDT000918948.1' already exists. Skipping...
Folder 'GCA_016414245.1_PDT000918926.1' already exists. Skipping...
Folder 'GCA_016414285.1_PDT000918921.1' already exists. Skipping...
Folder 'GCA_016414305.1_PDT000918936.1' already exists. Skipping...
Folder 'GCA_016414465.1_PDT000918947.1' already exists. Skipping...
Folder 'GCA_016414545.1_PDT000918941.1' already exists. Skipping...
Folder 'GCA_016414605.1_PDT000918935.1' already exists. Skipping...
Folder 'GCA_016414725.1_PDT000918932.1' already exists. Skipping...
Folder 'GCA_016434025.1_PDT000925744.1' already exists. Skipping...
Folder 'GCA_016434045.1_PDT000925742.1' already exists. Skipping...
Folder 'GCA_016434065.1_PDT000925743.1' already exists. Skipping...
Folder 'GCA_016434085.1_PDT000925740.1' already exists. Skipping...
Folder 'GCA_016434105.1_PDT000925738.1' already exists. Skipping...
Folder 'GCA_016434245.1_PDT000925732.1' already exists. Skipping...
Folder 'GCA_016434645.1_PDT000925721.1' already exists. Skipping...
Folder 'GCA_016435025.1_PDT000925716.1' already exists. Skipping...
Folder 'GCA_016435665.1_PDT000925666.1' already exists. Skipping...
Folder 'GCA_016435685.1_PDT000925670.1' already exists. Skipping...
Folder 'GCA_016435715.1_PDT000925669.1' already exists. Skipping...
Folder 'GCA_016435825.1_PDT000925662.1' already exists. Skipping...
Folder 'GCA_016435845.1_PDT000925663.1' already exists. Skipping...
Folder 'GCA_016435865.1_PDT000925661.1' already exists. Skipping...
Folder 'GCA_016435925.1_PDT000925660.1' already exists. Skipping...
Folder 'GCA_016435945.1_PDT000925659.1' already exists. Skipping...
Folder 'GCA_016435965.1_PDT000925657.1' already exists. Skipping...
Folder 'GCA_016435985.1_PDT000925658.1' already exists. Skipping...
Folder 'GCA_016436005.1_PDT000925656.1' already exists. Skipping...
Folder 'GCA_016436025.1_PDT000925655.1' already exists. Skipping...
Folder 'GCA_016436205.1_PDT000925647.1' already exists. Skipping...
Folder 'GCA_016436225.1_PDT000925646.1' already exists. Skipping...
Folder 'GCA_016436605.1_PDT000925631.1' already exists. Skipping...
Folder 'GCA_016438345.1_PDT000925502.1' already exists. Skipping...
Folder 'GCA_016439685.1_PDT000925432.1' already exists. Skipping...
Folder 'GCA_016439885.1_PDT000925433.1' already exists. Skipping...
Folder 'GCA_016441205.1_PDT000925372.1' already exists. Skipping...
Folder 'GCA_016441245.1_PDT000925369.1' already exists. Skipping...
Folder 'GCA_016441425.1_PDT000925355.1' already exists. Skipping...
Folder 'GCA_016441485.1_PDT000925353.1' already exists. Skipping...
Folder 'GCA_016441535.1_PDT000925352.1' already exists. Skipping...
Folder 'GCA_016441565.1_PDT000925351.1' already exists. Skipping...
Folder 'GCA_016441585.1_PDT000925349.1' already exists. Skipping...
Folder 'GCA_016441605.1_PDT000925348.1' already exists. Skipping...
Folder 'GCA_016441625.1_PDT000925347.1' already exists. Skipping...
Folder 'GCA_016441645.1_PDT000925344.1' already exists. Skipping...
Folder 'GCA_016441665.1_PDT000925346.1' already exists. Skipping...
Folder 'GCA_016441705.1_PDT000925342.1' already exists. Skipping...
Folder 'GCA_016441725.1_PDT000925339.1' already exists. Skipping...
Folder 'GCA_016441745.1_PDT000925340.1' already exists. Skipping...
Folder 'GCA_016441765.1_PDT000925341.1' already exists. Skipping...
Folder 'GCA_016442065.1_PDT000925343.1' already exists. Skipping...
Folder 'GCA_016442825.1_PDT000925298.1' already exists. Skipping...
Folder 'GCA_016443525.1_PDT000925224.1' already exists. Skipping...
Folder 'GCA_016450825.1_PDT000926065.1' already exists. Skipping...
Folder 'GCA_016450885.1_PDT000926067.1' already exists. Skipping...
Folder 'GCA_016458455.1_ASM1645845v1' already exists. Skipping...
Folder 'GCA_016458695.1_ASM1645869v1' already exists. Skipping...
Folder 'GCA_016459425.1_PDT000926327.1' already exists. Skipping...
Folder 'GCA_016459445.1_PDT000926337.1' already exists. Skipping...
Folder 'GCA_016460505.1_PDT000926341.1' already exists. Skipping...
Folder 'GCA_016460525.1_PDT000926340.1' already exists. Skipping...
Folder 'GCA_016460765.1_PDT000926324.1' already exists. Skipping...
Folder 'GCA_016460785.1_PDT000926325.1' already exists. Skipping...
Folder 'GCA_016460805.1_PDT000926326.1' already exists. Skipping...
Folder 'GCA_016460825.1_PDT000926323.1' already exists. Skipping...
Folder 'GCA_016465415.1_PDT000927392.1' already exists. Skipping...
Folder 'GCA_016465455.1_PDT000927397.1' already exists. Skipping...
Folder 'GCA_016465465.1_PDT000927393.1' already exists. Skipping...
Folder 'GCA_016465515.1_PDT000927396.1' already exists. Skipping...
Folder 'GCA_016465535.1_PDT000927395.1' already exists. Skipping...
Folder 'GCA_016465555.1_PDT000927394.1' already exists. Skipping...
Folder 'GCA_016492805.1_PDT000928130.1' already exists. Skipping...
Folder 'GCA_016492815.1_PDT000928129.1' already exists. Skipping...
Folder 'GCA_016492885.1_PDT000928127.1' already exists. Skipping...
Folder 'GCA_016492945.1_PDT000928126.1' already exists. Skipping...
Folder 'GCA_016493245.1_PDT000928099.1' already exists. Skipping...
Folder 'GCA_016493265.1_PDT000928100.1' already exists. Skipping...
Folder 'GCA_016493285.1_PDT000928101.1' already exists. Skipping...
Folder 'GCA_016493325.1_PDT000928109.1' already exists. Skipping...
Folder 'GCA_016493425.1_PDT000928098.1' already exists. Skipping...
Folder 'GCA_016493445.1_PDT000928091.1' already exists. Skipping...
Folder 'GCA_016493485.1_PDT000928090.1' already exists. Skipping...
Folder 'GCA_016493505.1_PDT000928089.1' already exists. Skipping...
Folder 'GCA_016493525.1_PDT000928096.1' already exists. Skipping...
Folder 'GCA_016493565.1_PDT000928093.1' already exists. Skipping...
Folder 'GCA_016493585.1_PDT000928087.1' already exists. Skipping...
Folder 'GCA_016493665.1_PDT000928072.1' already exists. Skipping...
Folder 'GCA_016493685.1_PDT000928073.1' already exists. Skipping...
Folder 'GCA_016493705.1_PDT000928070.1' already exists. Skipping...
Folder 'GCA_016493725.1_PDT000928074.1' already exists. Skipping...
Folder 'GCA_016493885.1_PDT000928071.1' already exists. Skipping...
Folder 'GCA_016493905.1_PDT000928069.1' already exists. Skipping...
Folder 'GCA_016493925.1_PDT000928068.1' already exists. Skipping...
Folder 'GCA_016493965.1_PDT000928066.1' already exists. Skipping...
Folder 'GCA_016494065.1_PDT000928057.1' already exists. Skipping...
Folder 'GCA_016494085.1_PDT000928058.1' already exists. Skipping...
Folder 'GCA_016494105.1_PDT000928059.1' already exists. Skipping...
Folder 'GCA_016494125.1_PDT000928056.1' already exists. Skipping...
Folder 'GCA_016494185.1_PDT000928052.1' already exists. Skipping...
Folder 'GCA_016494225.1_PDT000928050.1' already exists. Skipping...
Folder 'GCA_016494745.1_PDT000928018.1' already exists. Skipping...
Folder 'GCA_016494765.1_PDT000928017.1' already exists. Skipping...
Folder 'GCA_016494825.1_PDT000928016.1' already exists. Skipping...
Folder 'GCA_016494845.1_PDT000928015.1' already exists. Skipping...
Folder 'GCA_016494905.1_PDT000928006.1' already exists. Skipping...
Folder 'GCA_016494925.1_PDT000928005.1' already exists. Skipping...
Folder 'GCA_016494945.1_PDT000928007.1' already exists. Skipping...
Folder 'GCA_016541785.1_PDT000928325.1' already exists. Skipping...
Folder 'GCA_016568875.1_PDT000727365.2' already exists. Skipping...
Folder 'GCA_016571815.1_PDT000928983.1' already exists. Skipping...
Folder 'GCA_016571935.1_PDT000928971.1' already exists. Skipping...
Folder 'GCA_016572015.1_PDT000928967.1' already exists. Skipping...
Folder 'GCA_016572035.1_PDT000928966.1' already exists. Skipping...
Folder 'GCA_016572155.1_PDT000928960.1' already exists. Skipping...
Folder 'GCA_016572195.1_PDT000928952.1' already exists. Skipping...
Folder 'GCA_016572295.1_PDT000928958.1' already exists. Skipping...
Folder 'GCA_016572355.1_PDT000928957.1' already exists. Skipping...
Folder 'GCA_016572375.1_PDT000928954.1' already exists. Skipping...
Folder 'GCA_016582085.1_PDT000929755.1' already exists. Skipping...
Folder 'GCA_016582305.1_PDT000929762.1' already exists. Skipping...
Folder 'GCA_016582525.1_PDT000929761.1' already exists. Skipping...
Folder 'GCA_016582625.1_PDT000929759.1' already exists. Skipping...
Folder 'GCA_016582765.1_PDT000929763.1' already exists. Skipping...
Folder 'GCA_016582845.1_PDT000929827.1' already exists. Skipping...
Folder 'GCA_016582885.1_PDT000929833.1' already exists. Skipping...
Folder 'GCA_016582905.1_PDT000929819.1' already exists. Skipping...
Folder 'GCA_016582945.1_PDT000929829.1' already exists. Skipping...
Folder 'GCA_016583005.1_PDT000929815.1' already exists. Skipping...
Folder 'GCA_016583215.1_PDT000929823.1' already exists. Skipping...
Folder 'GCA_016583305.1_PDT000929825.1' already exists. Skipping...
Folder 'GCA_016587835.1_PDT000929834.1' already exists. Skipping...
Folder 'GCA_016587855.1_PDT000929824.1' already exists. Skipping...
Folder 'GCA_016588475.1_PDT000929903.1' already exists. Skipping...
Folder 'GCA_016588535.1_PDT000929902.1' already exists. Skipping...
Folder 'GCA_016589635.1_PDT000929817.1' already exists. Skipping...
Folder 'GCA_016589675.1_PDT000929835.1' already exists. Skipping...
Folder 'GCA_016594645.1_PDT000930036.1' already exists. Skipping...
Folder 'GCA_016599895.1_PDT000930092.1' already exists. Skipping...
Folder 'GCA_016601515.1_PDT000930283.1' already exists. Skipping...
Folder 'GCA_016601555.1_PDT000930282.1' already exists. Skipping...
Folder 'GCA_016602845.1_PDT000930281.1' already exists. Skipping...
Folder 'GCA_016607585.1_PDT000930111.1' already exists. Skipping...
Folder 'GCA_016607825.1_PDT000930097.1' already exists. Skipping...
Folder 'GCA_016607845.1_PDT000930100.1' already exists. Skipping...
Folder 'GCA_016607885.1_PDT000930098.1' already exists. Skipping...
Folder 'GCA_016608445.1_PDT000927398.1' already exists. Skipping...
Folder 'GCA_016610705.1_PDT000930998.1' already exists. Skipping...
Folder 'GCA_016610725.1_PDT000930997.1' already exists. Skipping...
Folder 'GCA_016611065.1_PDT000931005.1' already exists. Skipping...
Folder 'GCA_016611085.1_PDT000931000.1' already exists. Skipping...
Folder 'GCA_016611565.1_PDT000931057.1' already exists. Skipping...
Folder 'GCA_016611605.1_PDT000931051.1' already exists. Skipping...
Folder 'GCA_016611625.1_PDT000931053.1' already exists. Skipping...
Folder 'GCA_016611645.1_PDT000931036.1' already exists. Skipping...
Folder 'GCA_016611685.1_PDT000931032.1' already exists. Skipping...
Folder 'GCA_016611725.1_PDT000931038.1' already exists. Skipping...
Folder 'GCA_016611765.1_PDT000931031.1' already exists. Skipping...
Folder 'GCA_016611785.1_PDT000931035.1' already exists. Skipping...
Folder 'GCA_016611885.1_PDT000931063.1' already exists. Skipping...
Folder 'GCA_016611895.1_PDT000931034.1' already exists. Skipping...
Folder 'GCA_016624605.1_PDT000931702.1' already exists. Skipping...
Folder 'GCA_016624815.1_PDT000931692.1' already exists. Skipping...
Folder 'GCA_016624885.1_PDT000931690.1' already exists. Skipping...
Folder 'GCA_016625045.1_PDT000931686.1' already exists. Skipping...
Folder 'GCA_016625085.1_PDT000931689.1' already exists. Skipping...
Folder 'GCA_016625225.1_PDT000931682.1' already exists. Skipping...
Folder 'GCA_016625285.1_PDT000931681.1' already exists. Skipping...
Folder 'GCA_016625575.1_PDT000931670.1' already exists. Skipping...
Folder 'GCA_016626245.1_PDT000931650.1' already exists. Skipping...
Folder 'GCA_016626325.1_PDT000931651.1' already exists. Skipping...
Folder 'GCA_016626345.1_PDT000931648.1' already exists. Skipping...
Folder 'GCA_016626365.1_PDT000931646.1' already exists. Skipping...
Folder 'GCA_016626385.1_PDT000931643.1' already exists. Skipping...
Folder 'GCA_016626405.1_PDT000931640.1' already exists. Skipping...
Folder 'GCA_016626885.1_PDT000931616.1' already exists. Skipping...
Folder 'GCA_016626915.1_PDT000931608.1' already exists. Skipping...
Folder 'GCA_016627045.1_PDT000931612.1' already exists. Skipping...
Folder 'GCA_016627125.1_PDT000931603.1' already exists. Skipping...
Folder 'GCA_016627145.1_PDT000931602.1' already exists. Skipping...
Folder 'GCA_016627165.1_PDT000931605.1' already exists. Skipping...
Folder 'GCA_016627225.1_PDT000931601.1' already exists. Skipping...
Folder 'GCA_016627245.1_PDT000931600.1' already exists. Skipping...
Folder 'GCA_016627285.1_PDT000931597.1' already exists. Skipping...
Folder 'GCA_016627305.1_PDT000931596.1' already exists. Skipping...
Folder 'GCA_016627405.1_PDT000931592.1' already exists. Skipping...
Folder 'GCA_016627425.1_PDT000931591.1' already exists. Skipping...
Folder 'GCA_016631585.1_PDT000932071.1' already exists. Skipping...
Folder 'GCA_016631745.1_PDT000932057.1' already exists. Skipping...
Folder 'GCA_016631765.1_PDT000932058.1' already exists. Skipping...
Folder 'GCA_016631785.1_PDT000932054.1' already exists. Skipping...
Folder 'GCA_016631805.1_PDT000932046.1' already exists. Skipping...
Folder 'GCA_016632185.1_PDT000932073.1' already exists. Skipping...
Folder 'GCA_016632205.1_PDT000932049.1' already exists. Skipping...
Folder 'GCA_016632225.1_PDT000932066.1' already exists. Skipping...
Folder 'GCA_016637505.1_PDT000932279.1' already exists. Skipping...
Folder 'GCA_016637525.1_PDT000932278.1' already exists. Skipping...
Folder 'GCA_016637725.1_PDT000932265.1' already exists. Skipping...
Folder 'GCA_016637805.1_PDT000932267.1' already exists. Skipping...
Folder 'GCA_016639075.1_PDT000932183.1' already exists. Skipping...
Folder 'GCA_016639115.1_PDT000932181.1' already exists. Skipping...
Folder 'GCA_016639365.1_PDT000932168.1' already exists. Skipping...
Folder 'GCA_016640555.1_PDT000932080.1' already exists. Skipping...
Folder 'GCA_016640595.1_PDT000932074.1' already exists. Skipping...
Folder 'GCA_016640635.1_PDT000932060.1' already exists. Skipping...
Folder 'GCA_016640755.1_PDT000932050.1' already exists. Skipping...
Folder 'GCA_016640795.1_PDT000932051.1' already exists. Skipping...
Folder 'GCA_016644205.1_PDT000932410.1' already exists. Skipping...
Folder 'GCA_016644225.1_PDT000932408.1' already exists. Skipping...
Folder 'GCA_016644245.1_PDT000932403.1' already exists. Skipping...
Folder 'GCA_016644265.1_PDT000932419.1' already exists. Skipping...
Folder 'GCA_016644275.1_PDT000932422.1' already exists. Skipping...
Folder 'GCA_016644305.1_PDT000932423.1' already exists. Skipping...
Folder 'GCA_016644335.1_PDT000932427.1' already exists. Skipping...
Folder 'GCA_016644355.1_PDT000932416.1' already exists. Skipping...
Folder 'GCA_016644405.1_PDT000932412.1' already exists. Skipping...
Folder 'GCA_016644425.1_PDT000932405.1' already exists. Skipping...
Folder 'GCA_016644465.1_PDT000932399.1' already exists. Skipping...
Folder 'GCA_016644505.1_PDT000932426.1' already exists. Skipping...
Folder 'GCA_016644525.1_PDT000932418.1' already exists. Skipping...
Folder 'GCA_016644705.1_PDT000932482.1' already exists. Skipping...
Folder 'GCA_016644745.1_PDT000932476.1' already exists. Skipping...
Folder 'GCA_016644755.1_PDT000932486.1' already exists. Skipping...
Folder 'GCA_016644805.1_PDT000932470.1' already exists. Skipping...
Folder 'GCA_016646725.1_PDT000932502.1' already exists. Skipping...
Folder 'GCA_016646785.1_PDT000932498.1' already exists. Skipping...
Folder 'GCA_016646845.1_PDT000932494.1' already exists. Skipping...
Folder 'GCA_016646925.1_PDT000932492.1' already exists. Skipping...
Folder 'GCA_016646945.1_PDT000932490.1' already exists. Skipping...
Folder 'GCA_016646965.1_PDT000932489.1' already exists. Skipping...
Folder 'GCA_016646985.1_PDT000932488.1' already exists. Skipping...
Folder 'GCA_016647045.1_PDT000932487.1' already exists. Skipping...
Folder 'GCA_016647085.1_PDT000932484.1' already exists. Skipping...
Folder 'GCA_016647125.1_PDT000932478.1' already exists. Skipping...
Folder 'GCA_016647145.1_PDT000932475.1' already exists. Skipping...
Folder 'GCA_016647165.1_PDT000932477.1' already exists. Skipping...
Folder 'GCA_016647305.1_PDT000932466.1' already exists. Skipping...
Folder 'GCA_016648475.1_PDT000933235.1' already exists. Skipping...
Folder 'GCA_016654725.1_PDT000933236.1' already exists. Skipping...
Folder 'GCA_016658125.1_PDT000935903.1' already exists. Skipping...
Folder 'GCA_016658145.1_PDT000935902.1' already exists. Skipping...
Folder 'GCA_016658425.1_PDT000935901.1' already exists. Skipping...
Folder 'GCA_016658525.1_PDT000935882.1' already exists. Skipping...
Folder 'GCA_016658605.1_PDT000935881.1' already exists. Skipping...
Folder 'GCA_016658685.1_PDT000935873.1' already exists. Skipping...
Folder 'GCA_016658765.1_PDT000935877.1' already exists. Skipping...
Folder 'GCA_016659065.1_PDT000935861.1' already exists. Skipping...
Folder 'GCA_016659205.1_PDT000935852.1' already exists. Skipping...
Folder 'GCA_016659265.1_PDT000935851.1' already exists. Skipping...
Folder 'GCA_016688235.1_PDT000933520.1' already exists. Skipping...
Folder 'GCA_016688255.1_PDT000933522.1' already exists. Skipping...
Folder 'GCA_016688395.1_PDT000933506.1' already exists. Skipping...
Folder 'GCA_016688415.1_PDT000933507.1' already exists. Skipping...
Folder 'GCA_016688455.1_PDT000933505.1' already exists. Skipping...
Folder 'GCA_016688495.1_PDT000933504.1' already exists. Skipping...
Folder 'GCA_016688635.1_PDT000933501.1' already exists. Skipping...
Folder 'GCA_016689415.1_PDT000933440.1' already exists. Skipping...
Folder 'GCA_016694535.1_PDT000937373.1' already exists. Skipping...
Folder 'GCA_016694575.1_PDT000937375.1' already exists. Skipping...
Folder 'GCA_016694675.1_PDT000937377.1' already exists. Skipping...
Folder 'GCA_016694735.1_PDT000937374.1' already exists. Skipping...
Folder 'GCA_016698565.1_PDT000937381.1' already exists. Skipping...
Folder 'GCA_016700605.1_PDT000937885.1' already exists. Skipping...
Folder 'GCA_016700655.1_PDT000937879.1' already exists. Skipping...
Folder 'GCA_016701535.1_PDT000938250.1' already exists. Skipping...
Folder 'GCA_016701875.1_PDT000938249.1' already exists. Skipping...
Folder 'GCA_016701895.1_PDT000938248.1' already exists. Skipping...
Folder 'GCA_016723305.1_PDT000938469.1' already exists. Skipping...
Folder 'GCA_016723385.1_PDT000938453.1' already exists. Skipping...
Folder 'GCA_016723485.1_PDT000938450.1' already exists. Skipping...
Folder 'GCA_016723505.1_PDT000938448.1' already exists. Skipping...
Folder 'GCA_016723545.1_PDT000938451.1' already exists. Skipping...
Folder 'GCA_016723605.1_PDT000938447.1' already exists. Skipping...
Folder 'GCA_016723645.1_PDT000938446.1' already exists. Skipping...
Folder 'GCA_016730125.1_PDT000938536.1' already exists. Skipping...
Folder 'GCA_016730145.1_PDT000938539.1' already exists. Skipping...
Folder 'GCA_016730165.1_PDT000938540.1' already exists. Skipping...
Folder 'GCA_016730185.1_PDT000938538.1' already exists. Skipping...
Folder 'GCA_016735975.1_PDT000931040.1' already exists. Skipping...
Folder 'GCA_016736055.1_PDT000931037.1' already exists. Skipping...
Folder 'GCA_016740335.1_PDT000931120.1' already exists. Skipping...
Folder 'GCA_016741115.1_PDT000931079.1' already exists. Skipping...
Folder 'GCA_016741575.1_PDT000931039.1' already exists. Skipping...
Folder 'GCA_016741715.1_PDT000931007.1' already exists. Skipping...
Folder 'GCA_016807145.1_ASM1680714v1' already exists. Skipping...
Folder 'GCA_016807155.1_ASM1680715v1' already exists. Skipping...
Folder 'GCA_016807195.1_ASM1680719v1' already exists. Skipping...
Folder 'GCA_016807245.1_ASM1680724v1' already exists. Skipping...
Folder 'GCA_016807265.1_ASM1680726v1' already exists. Skipping...
Folder 'GCA_016807285.1_ASM1680728v1' already exists. Skipping...
Folder 'GCA_016807305.1_ASM1680730v1' already exists. Skipping...
Folder 'GCA_016807315.1_ASM1680731v1' already exists. Skipping...
Folder 'GCA_016807345.1_ASM1680734v1' already exists. Skipping...
Folder 'GCA_016807355.1_ASM1680735v1' already exists. Skipping...
Folder 'GCA_016807385.1_ASM1680738v1' already exists. Skipping...
Folder 'GCA_016807405.1_ASM1680740v1' already exists. Skipping...

Retreiveing data: 75144it [00:12, 6651.65it/s]

Folder 'GCA_017588255.1_PDT000991133.1' already exists. Skipping...
Folder 'GCA_017589875.1_PDT000991006.1' already exists. Skipping...
Folder 'GCA_017589895.1_PDT000991007.1' already exists. Skipping...
Folder 'GCA_017589915.1_PDT000991003.1' already exists. Skipping...
Folder 'GCA_017591215.1_PDT000991291.1' already exists. Skipping...
Folder 'GCA_017605585.1_PDT000991427.1' already exists. Skipping...
Folder 'GCA_017605665.1_PDT000991422.1' already exists. Skipping...
Folder 'GCA_017605725.1_PDT000991399.1' already exists. Skipping...
Folder 'GCA_017605735.1_PDT000991400.1' already exists. Skipping...
Folder 'GCA_017605805.1_PDT000991408.1' already exists. Skipping...
Folder 'GCA_017605825.1_PDT000991406.1' already exists. Skipping...
Folder 'GCA_017605845.1_PDT000991403.1' already exists. Skipping...
Folder 'GCA_017605865.1_PDT000991397.1' already exists. Skipping...
Folder 'GCA_017605965.1_PDT000991388.1' already exists. Skipping...
Folder 'GCA_017606005.1_PDT000991384.1' already exists. Skipping...
Folder 'GCA_017606025.1_PDT000991383.1' already exists. Skipping...
Folder 'GCA_017606045.1_PDT000991381.1' already exists. Skipping...
Folder 'GCA_017606065.1_PDT000991379.1' already exists. Skipping...
Folder 'GCA_017606105.1_PDT000991376.1' already exists. Skipping...
Folder 'GCA_017606125.1_PDT000991377.1' already exists. Skipping...
Folder 'GCA_017606165.1_PDT000991374.1' already exists. Skipping...
Folder 'GCA_017606285.1_PDT000991372.1' already exists. Skipping...
Folder 'GCA_017607245.1_PDT000991214.1' already exists. Skipping...
Folder 'GCA_017607645.1_PDT000991375.1' already exists. Skipping...
Folder 'GCA_017610765.1_PDT000991407.1' already exists. Skipping...
Folder 'GCA_017636005.1_PDT000993106.1' already exists. Skipping...
Folder 'GCA_017636505.1_PDT000993459.1' already exists. Skipping...
Folder 'GCA_017636625.1_PDT000993450.1' already exists. Skipping...
Folder 'GCA_017636645.1_PDT000993454.1' already exists. Skipping...
Folder 'GCA_017636665.1_PDT000993452.1' already exists. Skipping...
Folder 'GCA_017636685.1_PDT000993448.1' already exists. Skipping...
Folder 'GCA_017636705.1_PDT000993446.1' already exists. Skipping...
Folder 'GCA_017636765.1_PDT000993443.1' already exists. Skipping...
Folder 'GCA_017636845.1_PDT000993439.1' already exists. Skipping...
Folder 'GCA_017636865.1_PDT000993438.1' already exists. Skipping...
Folder 'GCA_017636965.1_PDT000993432.1' already exists. Skipping...
Folder 'GCA_017637005.1_PDT000993429.1' already exists. Skipping...
Folder 'GCA_017637025.1_PDT000993425.1' already exists. Skipping...
Folder 'GCA_017637065.1_PDT000993424.1' already exists. Skipping...
Folder 'GCA_017637105.1_PDT000993421.1' already exists. Skipping...
Folder 'GCA_017637145.1_PDT000993420.1' already exists. Skipping...
Folder 'GCA_017637165.1_PDT000993422.1' already exists. Skipping...
Folder 'GCA_017637245.1_PDT000993416.1' already exists. Skipping...
Folder 'GCA_017637325.1_PDT000993410.1' already exists. Skipping...
Folder 'GCA_017637385.1_PDT000993405.1' already exists. Skipping...
Folder 'GCA_017637425.1_PDT000993407.1' already exists. Skipping...
Folder 'GCA_017638115.1_PDT000993328.1' already exists. Skipping...
Folder 'GCA_017644695.1_ASM1764469v1' already exists. Skipping...
Folder 'GCA_017644725.1_ASM1764472v1' already exists. Skipping...
Folder 'GCA_017644735.1_ASM1764473v1' already exists. Skipping...
Folder 'GCA_017644765.1_ASM1764476v1' already exists. Skipping...
Folder 'GCA_017644775.1_ASM1764477v1' already exists. Skipping...
Folder 'GCA_017644795.1_ASM1764479v1' already exists. Skipping...
Folder 'GCA_017644805.1_ASM1764480v1' already exists. Skipping...
Folder 'GCA_017644845.1_ASM1764484v1' already exists. Skipping...
Folder 'GCA_017644865.1_ASM1764486v1' already exists. Skipping...
Folder 'GCA_017644875.1_ASM1764487v1' already exists. Skipping...
Folder 'GCA_017644895.1_ASM1764489v1' already exists. Skipping...
Folder 'GCA_017644905.1_ASM1764490v1' already exists. Skipping...
Folder 'GCA_017644945.1_ASM1764494v1' already exists. Skipping...
Folder 'GCA_017644965.1_ASM1764496v1' already exists. Skipping...
Folder 'GCA_017644985.1_ASM1764498v1' already exists. Skipping...
Folder 'GCA_017644995.1_ASM1764499v1' already exists. Skipping...
Folder 'GCA_017645025.1_ASM1764502v1' already exists. Skipping...
Folder 'GCA_017645045.1_ASM1764504v1' already exists. Skipping...
Folder 'GCA_017645065.1_ASM1764506v1' already exists. Skipping...
Folder 'GCA_017645085.1_ASM1764508v1' already exists. Skipping...
Folder 'GCA_017645105.1_ASM1764510v1' already exists. Skipping...
Folder 'GCA_017645125.1_ASM1764512v1' already exists. Skipping...
Folder 'GCA_017645145.1_ASM1764514v1' already exists. Skipping...
Folder 'GCA_017645155.1_ASM1764515v1' already exists. Skipping...
Folder 'GCA_017645185.1_ASM1764518v1' already exists. Skipping...
Folder 'GCA_017645205.1_ASM1764520v1' already exists. Skipping...
Folder 'GCA_017645215.1_ASM1764521v1' already exists. Skipping...
Folder 'GCA_017648265.1_ASM1764826v1' already exists. Skipping...
Folder 'GCA_017648275.1_ASM1764827v1' already exists. Skipping...
Folder 'GCA_017648375.1_ASM1764837v1' already exists. Skipping...
Folder 'GCA_017655005.1_PDT000993330.1' already exists. Skipping...
Folder 'GCA_017655025.1_PDT000993285.1' already exists. Skipping...
Folder 'GCA_017655035.1_PDT000993284.1' already exists. Skipping...
Folder 'GCA_017655065.1_PDT000993282.1' already exists. Skipping...
Folder 'GCA_017657615.1_PDT000993105.1' already exists. Skipping...
Folder 'GCA_017657635.1_PDT000993104.1' already exists. Skipping...
Folder 'GCA_017657795.1_PDT000993085.1' already exists. Skipping...
Folder 'GCA_017657875.1_PDT000993082.1' already exists. Skipping...
Folder 'GCA_017657935.1_PDT000993076.1' already exists. Skipping...
Folder 'GCA_017658035.1_PDT000993068.1' already exists. Skipping...
Folder 'GCA_017658055.1_PDT000993066.1' already exists. Skipping...
Folder 'GCA_017658095.1_PDT000993065.1' already exists. Skipping...
Folder 'GCA_017659335.1_PDT000991382.1' already exists. Skipping...
Folder 'GCA_017659355.1_PDT000991386.1' already exists. Skipping...
Folder 'GCA_017659455.1_PDT000991221.1' already exists. Skipping...
Folder 'GCA_017659495.1_PDT000991136.1' already exists. Skipping...
Folder 'GCA_017659595.1_PDT000993444.1' already exists. Skipping...
Folder 'GCA_017659655.1_PDT000993414.1' already exists. Skipping...
Folder 'GCA_017659795.1_PDT000993434.1' already exists. Skipping...
Folder 'GCA_017659875.1_PDT000993403.1' already exists. Skipping...
Folder 'GCA_017659915.1_PDT000993332.1' already exists. Skipping...
Folder 'GCA_017660035.1_PDT000993815.1' already exists. Skipping...
Folder 'GCA_017660055.1_PDT000993814.1' already exists. Skipping...
Folder 'GCA_017661275.1_PDT000993816.1' already exists. Skipping...
Folder 'GCA_017661615.1_PDT000993819.1' already exists. Skipping...
Folder 'GCA_017662735.1_PDT000993283.1' already exists. Skipping...
Folder 'GCA_017670045.1_PDT000995695.1' already exists. Skipping...
Folder 'GCA_017670085.1_PDT000995694.1' already exists. Skipping...
Folder 'GCA_017670705.1_PDT000995693.1' already exists. Skipping...
Folder 'GCA_017675325.1_PDT000996135.1' already exists. Skipping...
Folder 'GCA_017675405.1_PDT000996145.1' already exists. Skipping...
Folder 'GCA_017675445.1_PDT000996124.1' already exists. Skipping...
Folder 'GCA_017676325.1_PDT000996149.1' already exists. Skipping...
Folder 'GCA_017676425.1_PDT000996146.1' already exists. Skipping...
Folder 'GCA_017676465.1_PDT000996127.1' already exists. Skipping...
Folder 'GCA_017678445.1_PDT000996148.1' already exists. Skipping...
Folder 'GCA_017680445.1_PDT000996136.1' already exists. Skipping...
Folder 'GCA_017680465.1_PDT000996130.1' already exists. Skipping...
Folder 'GCA_017683445.1_PDT000996104.1' already exists. Skipping...
Folder 'GCA_017685435.1_PDT000996209.1' already exists. Skipping...
Folder 'GCA_017686555.1_PDT000996125.1' already exists. Skipping...
Folder 'GCA_017710655.1_PDT000996147.1' already exists. Skipping...
Folder 'GCA_017710795.1_PDT000996121.1' already exists. Skipping...
Folder 'GCA_017712775.1_PDT000996215.1' already exists. Skipping...
Folder 'GCA_017729495.1_PDT000997467.1' already exists. Skipping...
Folder 'GCA_017730495.1_PDT000997468.1' already exists. Skipping...
Folder 'GCA_017732435.1_PDT000997466.1' already exists. Skipping...
Folder 'GCA_017733435.1_PDT000997469.1' already exists. Skipping...
Folder 'GCA_017733475.1_PDT000997465.1' already exists. Skipping...
Folder 'GCA_017750325.1_PDT000997852.1' already exists. Skipping...
Folder 'GCA_017750405.1_PDT000997850.1' already exists. Skipping...
Folder 'GCA_017750425.1_PDT000997849.1' already exists. Skipping...
Folder 'GCA_017751585.1_PDT000997585.1' already exists. Skipping...
Folder 'GCA_017751605.1_PDT000997584.1' already exists. Skipping...
Folder 'GCA_017751645.1_PDT000997583.1' already exists. Skipping...
Folder 'GCA_017752225.1_PDT000997545.1' already exists. Skipping...
Folder 'GCA_017752805.1_PDT000997512.1' already exists. Skipping...
Folder 'GCA_017752865.1_PDT000997511.1' already exists. Skipping...
Folder 'GCA_017770005.1_PDT000986095.1' already exists. Skipping...
Folder 'GCA_017787625.1_PDT000997547.1' already exists. Skipping...
Folder 'GCA_017787645.1_PDT000997546.1' already exists. Skipping...
Folder 'GCA_017815175.1_PDT001000971.1' already exists. Skipping...
Folder 'GCA_017816195.1_PDT001001165.1' already exists. Skipping...
Folder 'GCA_017816215.1_PDT001001166.1' already exists. Skipping...
Folder 'GCA_017816235.1_PDT001001162.1' already exists. Skipping...
Folder 'GCA_017816255.1_PDT001001163.1' already exists. Skipping...
Folder 'GCA_017816275.1_PDT001001164.1' already exists. Skipping...
Folder 'GCA_017816295.1_PDT001001161.1' already exists. Skipping...
Folder 'GCA_017816315.1_PDT001001160.1' already exists. Skipping...
Folder 'GCA_017816335.1_PDT001001159.1' already exists. Skipping...
Folder 'GCA_017819095.1_PDT001000970.1' already exists. Skipping...
Folder 'GCA_017819155.1_PDT001000969.1' already exists. Skipping...
Folder 'GCA_017819175.1_PDT001000968.1' already exists. Skipping...
Folder 'GCA_017819195.1_PDT001000966.1' already exists. Skipping...
Folder 'GCA_017819735.1_PDT001001001.1' already exists. Skipping...
Folder 'GCA_017820155.1_PDT001000967.1' already exists. Skipping...
Folder 'GCA_017820195.1_PDT001000965.1' already exists. Skipping...
Folder 'GCA_017820215.1_PDT001000964.1' already exists. Skipping...
Folder 'GCA_017890345.1_PDT001002258.1' already exists. Skipping...
Folder 'GCA_017894005.1_PDT001002535.1' already exists. Skipping...
Folder 'GCA_017894405.1_PDT001002536.1' already exists. Skipping...
Folder 'GCA_017894445.1_PDT001002618.1' already exists. Skipping...
Folder 'GCA_017894465.1_PDT001002599.1' already exists. Skipping...
Folder 'GCA_017894505.1_PDT001002534.1' already exists. Skipping...
Folder 'GCA_017894965.1_PDT001002613.1' already exists. Skipping...
Folder 'GCA_017894985.1_PDT001002610.1' already exists. Skipping...
Folder 'GCA_017895125.1_PDT001002614.1' already exists. Skipping...
Folder 'GCA_017895485.1_PDT001002619.1' already exists. Skipping...
Folder 'GCA_017895525.1_PDT001002611.1' already exists. Skipping...
Folder 'GCA_017895685.1_PDT001002616.1' already exists. Skipping...
Folder 'GCA_017898775.1_PDT001002609.1' already exists. Skipping...
Folder 'GCA_017899975.1_PDT001003755.1' already exists. Skipping...
Folder 'GCA_017900015.1_PDT001003754.1' already exists. Skipping...
Folder 'GCA_017900055.1_PDT001003752.1' already exists. Skipping...
Folder 'GCA_017900135.1_PDT001003750.1' already exists. Skipping...
Folder 'GCA_017900195.1_PDT001003745.1' already exists. Skipping...
Folder 'GCA_017900235.1_PDT001003743.1' already exists. Skipping...
Folder 'GCA_017900255.1_PDT001003742.1' already exists. Skipping...
Folder 'GCA_017900315.1_PDT001003740.1' already exists. Skipping...
Folder 'GCA_017900335.1_PDT001003738.1' already exists. Skipping...
Folder 'GCA_017905035.1_PDT001002911.1' already exists. Skipping...
Folder 'GCA_017905115.1_PDT001002907.1' already exists. Skipping...
Folder 'GCA_017905155.1_PDT001002905.1' already exists. Skipping...
Folder 'GCA_017905215.1_PDT001002903.1' already exists. Skipping...
Folder 'GCA_017905495.1_PDT001002890.1' already exists. Skipping...
Folder 'GCA_017905635.1_PDT001002884.1' already exists. Skipping...
Folder 'GCA_017906355.1_PDT001002834.1' already exists. Skipping...
Folder 'GCA_017906795.1_PDT001002981.1' already exists. Skipping...
Folder 'GCA_017927015.1_PDT001004523.1' already exists. Skipping...
Folder 'GCA_017931175.1_PDT001005008.1' already exists. Skipping...
Folder 'GCA_017931195.1_PDT001005010.1' already exists. Skipping...
Folder 'GCA_017931235.1_PDT001005004.1' already exists. Skipping...
Folder 'GCA_017931275.1_PDT001004995.1' already exists. Skipping...
Folder 'GCA_017931295.1_PDT001004986.1' already exists. Skipping...
Folder 'GCA_017931315.1_PDT001004991.1' already exists. Skipping...
Folder 'GCA_017931335.1_PDT001004982.1' already exists. Skipping...
Folder 'GCA_017931395.1_PDT001004972.1' already exists. Skipping...
Folder 'GCA_017931415.1_PDT001004981.1' already exists. Skipping...
Folder 'GCA_017931455.1_PDT001004963.1' already exists. Skipping...
Folder 'GCA_017931465.1_PDT001004962.1' already exists. Skipping...
Folder 'GCA_017931475.1_PDT001004969.1' already exists. Skipping...
Folder 'GCA_017931535.1_PDT001004953.1' already exists. Skipping...
Folder 'GCA_017931555.1_PDT001004952.1' already exists. Skipping...
Folder 'GCA_017931575.1_PDT001004950.1' already exists. Skipping...
Folder 'GCA_017931595.1_PDT001004949.1' already exists. Skipping...
Folder 'GCA_017931615.1_PDT001004948.1' already exists. Skipping...
Folder 'GCA_017931695.1_PDT001004935.1' already exists. Skipping...
Folder 'GCA_017931995.1_PDT001005013.1' already exists. Skipping...
Folder 'GCA_017932055.1_PDT001005002.1' already exists. Skipping...
Folder 'GCA_017932095.1_PDT001004987.1' already exists. Skipping...
Folder 'GCA_017932105.1_PDT001004985.1' already exists. Skipping...
Folder 'GCA_017932195.1_PDT001004946.1' already exists. Skipping...
Folder 'GCA_017932255.1_PDT001004941.1' already exists. Skipping...
Folder 'GCA_017932455.1_PDT001004990.1' already exists. Skipping...
Folder 'GCA_017932475.1_PDT001004974.1' already exists. Skipping...
Folder 'GCA_017932575.1_PDT001004959.1' already exists. Skipping...
Folder 'GCA_017932585.1_PDT001004966.1' already exists. Skipping...
Folder 'GCA_017932615.1_PDT001004965.1' already exists. Skipping...
Folder 'GCA_017932635.1_PDT001004958.1' already exists. Skipping...
Folder 'GCA_017932715.1_PDT001005018.1' already exists. Skipping...
Folder 'GCA_017932795.1_PDT001004980.1' already exists. Skipping...
Folder 'GCA_017932835.1_PDT001004976.1' already exists. Skipping...
Folder 'GCA_017932855.1_PDT001004960.1' already exists. Skipping...
Folder 'GCA_017932875.1_PDT001004956.1' already exists. Skipping...
Folder 'GCA_017932895.1_PDT001004955.1' already exists. Skipping...
Folder 'GCA_017933275.1_PDT001005019.1' already exists. Skipping...
Folder 'GCA_017933355.1_PDT001005012.1' already exists. Skipping...
Folder 'GCA_017933455.1_PDT001005011.1' already exists. Skipping...
Folder 'GCA_017933535.1_PDT001005006.1' already exists. Skipping...
Folder 'GCA_017933655.1_PDT001004954.1' already exists. Skipping...
Folder 'GCA_017933715.1_PDT001004984.1' already exists. Skipping...
Folder 'GCA_017944365.1_PDT001005283.1' already exists. Skipping...
Folder 'GCA_017944385.1_PDT001005282.1' already exists. Skipping...
Folder 'GCA_017944405.1_PDT001005284.1' already exists. Skipping...
Folder 'GCA_017953775.1_PDT001005465.1' already exists. Skipping...
Folder 'GCA_017954095.1_PDT000690354.1' already exists. Skipping...
Folder 'GCA_017954315.1_PDT000687011.1' already exists. Skipping...
Folder 'GCA_017966805.1_PDT001005854.1' already exists. Skipping...
Folder 'GCA_017967185.1_PDT001005836.1' already exists. Skipping...
Folder 'GCA_017967285.1_PDT001005830.1' already exists. Skipping...
Folder 'GCA_017967305.1_PDT001005829.1' already exists. Skipping...
Folder 'GCA_017967345.1_PDT001005828.1' already exists. Skipping...
Folder 'GCA_017967365.1_PDT001005826.1' already exists. Skipping...
Folder 'GCA_017967405.1_PDT001005827.1' already exists. Skipping...
Folder 'GCA_017968525.1_PDT001005771.1' already exists. Skipping...
Folder 'GCA_017968545.1_PDT001005768.1' already exists. Skipping...
Folder 'GCA_017968585.1_PDT001005766.1' already exists. Skipping...
Folder 'GCA_017968625.1_PDT001005764.1' already exists. Skipping...
Folder 'GCA_017969425.1_PDT001005730.1' already exists. Skipping...
Folder 'GCA_017969465.1_PDT001005726.1' already exists. Skipping...
Folder 'GCA_017969485.1_PDT001005727.1' already exists. Skipping...
Folder 'GCA_017969495.1_PDT001005728.1' already exists. Skipping...
Folder 'GCA_017969545.1_PDT001005722.1' already exists. Skipping...
Folder 'GCA_017969585.1_PDT001005721.1' already exists. Skipping...
Folder 'GCA_017969605.1_PDT001005724.1' already exists. Skipping...
Folder 'GCA_017969645.1_PDT001005719.1' already exists. Skipping...
Folder 'GCA_017969665.1_PDT001005717.1' already exists. Skipping...
Folder 'GCA_017969685.1_PDT001005718.1' already exists. Skipping...
Folder 'GCA_017969705.1_PDT001005716.1' already exists. Skipping...
Folder 'GCA_017969725.1_PDT001005715.1' already exists. Skipping...
Folder 'GCA_017969785.1_PDT001005711.1' already exists. Skipping...
Folder 'GCA_017969845.1_PDT001005709.1' already exists. Skipping...
Folder 'GCA_017969905.1_PDT001005707.1' already exists. Skipping...
Folder 'GCA_017970885.1_PDT001005656.1' already exists. Skipping...
Folder 'GCA_017970905.1_PDT001005654.1' already exists. Skipping...
Folder 'GCA_017970945.1_PDT001005653.1' already exists. Skipping...
Folder 'GCA_017971525.1_PDT001005624.1' already exists. Skipping...
Folder 'GCA_017971545.1_PDT001005623.1' already exists. Skipping...
Folder 'GCA_017976485.1_PDT000997851.1' already exists. Skipping...
Folder 'GCA_017979765.1_PDT001006135.1' already exists. Skipping...
Folder 'GCA_017979775.1_PDT001006136.1' already exists. Skipping...
Folder 'GCA_018008275.1_PDT001006626.1' already exists. Skipping...
Folder 'GCA_018008315.1_PDT001006625.1' already exists. Skipping...
Folder 'GCA_018008335.1_PDT001006623.1' already exists. Skipping...
Folder 'GCA_018008375.1_PDT001006622.1' already exists. Skipping...
Folder 'GCA_018008995.1_PDT001006582.1' already exists. Skipping...
Folder 'GCA_018009235.1_PDT001006570.1' already exists. Skipping...
Folder 'GCA_018009375.1_PDT001006564.1' already exists. Skipping...
Folder 'GCA_018009435.1_PDT001006560.1' already exists. Skipping...
Folder 'GCA_018009475.1_PDT001006557.1' already exists. Skipping...
Folder 'GCA_018009495.1_PDT001006556.1' already exists. Skipping...
Folder 'GCA_018021915.1_PDT000961539.1' already exists. Skipping...
Folder 'GCA_018038525.1_PDT001007220.1' already exists. Skipping...
Folder 'GCA_018038545.1_PDT001007219.1' already exists. Skipping...
Folder 'GCA_018040465.1_PDT001007221.1' already exists. Skipping...
Folder 'GCA_018042365.1_PDT001007248.1' already exists. Skipping...
Folder 'GCA_018042385.1_PDT001007241.1' already exists. Skipping...
Folder 'GCA_018043665.1_PDT000856257.1' already exists. Skipping...
Folder 'GCA_018077425.1_PDT001007596.1' already exists. Skipping...
Folder 'GCA_018077465.1_PDT001007597.1' already exists. Skipping...
Folder 'GCA_018077485.1_PDT001007594.1' already exists. Skipping...
Folder 'GCA_018077525.1_PDT001007591.1' already exists. Skipping...
Folder 'GCA_018077545.1_PDT001007592.1' already exists. Skipping...
Folder 'GCA_018077585.1_PDT001007589.1' already exists. Skipping...
Folder 'GCA_018077605.1_PDT001007588.1' already exists. Skipping...
Folder 'GCA_018077625.1_PDT001007587.1' already exists. Skipping...
Folder 'GCA_018077665.1_PDT001007585.1' already exists. Skipping...
Folder 'GCA_018077685.1_PDT001007584.1' already exists. Skipping...

Retreiveing data: 76479it [00:12, 6643.33it/s]

Folder 'GCA_018775345.1_PDT001062951.1' already exists. Skipping...
Folder 'GCA_018799685.1_PDT001064155.1' already exists. Skipping...
Folder 'GCA_018801265.1_PDT001064063.1' already exists. Skipping...
Folder 'GCA_018801285.1_PDT001064064.1' already exists. Skipping...
Folder 'GCA_018801365.1_PDT001064069.1' already exists. Skipping...
Folder 'GCA_018801405.1_PDT001064070.1' already exists. Skipping...
Folder 'GCA_018801425.1_PDT001064067.1' already exists. Skipping...
Folder 'GCA_018801445.1_PDT001064068.1' already exists. Skipping...
Folder 'GCA_018801465.1_PDT001064065.1' already exists. Skipping...
Folder 'GCA_018801485.1_PDT001064066.1' already exists. Skipping...
Folder 'GCA_018801505.1_PDT001064059.1' already exists. Skipping...
Folder 'GCA_018801525.1_PDT001064061.1' already exists. Skipping...
Folder 'GCA_018801545.1_PDT001064060.1' already exists. Skipping...
Folder 'GCA_018801585.1_PDT001064055.1' already exists. Skipping...
Folder 'GCA_018801605.1_PDT001064057.1' already exists. Skipping...
Folder 'GCA_018801625.1_PDT001064058.1' already exists. Skipping...
Folder 'GCA_018801645.1_PDT001064054.1' already exists. Skipping...
Folder 'GCA_018801665.1_PDT001064056.1' already exists. Skipping...
Folder 'GCA_018801685.1_PDT001064053.1' already exists. Skipping...
Folder 'GCA_018801705.1_PDT001064051.1' already exists. Skipping...
Folder 'GCA_018801725.1_PDT001064049.1' already exists. Skipping...
Folder 'GCA_018801745.1_PDT001064050.1' already exists. Skipping...
Folder 'GCA_018801765.1_PDT001064048.1' already exists. Skipping...
Folder 'GCA_018801785.1_PDT001064046.1' already exists. Skipping...
Folder 'GCA_018801805.1_PDT001064047.1' already exists. Skipping...
Folder 'GCA_018801825.1_PDT001064045.1' already exists. Skipping...
Folder 'GCA_018801845.1_PDT001064044.1' already exists. Skipping...
Folder 'GCA_018801865.1_PDT001064041.1' already exists. Skipping...
Folder 'GCA_018801885.1_PDT001064040.1' already exists. Skipping...
Folder 'GCA_018801905.1_PDT001064043.1' already exists. Skipping...
Folder 'GCA_018801925.1_PDT001064037.1' already exists. Skipping...
Folder 'GCA_018801945.1_PDT001064038.1' already exists. Skipping...
Folder 'GCA_018801965.1_PDT001064036.1' already exists. Skipping...
Folder 'GCA_018801985.1_PDT001064035.1' already exists. Skipping...
Folder 'GCA_018802005.1_PDT001064034.1' already exists. Skipping...
Folder 'GCA_018802025.1_PDT001064032.1' already exists. Skipping...
Folder 'GCA_018802045.1_PDT001064031.1' already exists. Skipping...
Folder 'GCA_018802065.1_PDT001064028.1' already exists. Skipping...
Folder 'GCA_018802085.1_PDT001064062.1' already exists. Skipping...
Folder 'GCA_018802105.1_PDT001064052.1' already exists. Skipping...
Folder 'GCA_018802125.1_PDT001064029.1' already exists. Skipping...
Folder 'GCA_018802145.1_PDT001064030.1' already exists. Skipping...
Folder 'GCA_018802165.1_PDT001064039.1' already exists. Skipping...
Folder 'GCA_018802185.1_PDT001064042.1' already exists. Skipping...
Folder 'GCA_018802205.1_PDT001064033.1' already exists. Skipping...
Folder 'GCA_018804235.1_PDT001049870.1' already exists. Skipping...
Folder 'GCA_018804425.1_PDT001049861.1' already exists. Skipping...
Folder 'GCA_018804655.1_PDT001049842.1' already exists. Skipping...
Folder 'GCA_018804705.1_PDT001049836.1' already exists. Skipping...
Folder 'GCA_018804755.1_PDT001049834.1' already exists. Skipping...
Folder 'GCA_018804855.1_PDT001049828.1' already exists. Skipping...
Folder 'GCA_018804875.1_PDT001049823.1' already exists. Skipping...
Folder 'GCA_018805035.1_PDT001049815.1' already exists. Skipping...
Folder 'GCA_018805375.1_PDT001049802.1' already exists. Skipping...
Folder 'GCA_018805455.1_PDT001049792.1' already exists. Skipping...
Folder 'GCA_018805475.1_PDT001049791.1' already exists. Skipping...
Folder 'GCA_018805495.1_PDT001049793.1' already exists. Skipping...
Folder 'GCA_018805615.1_PDT001049785.1' already exists. Skipping...
Folder 'GCA_018805815.1_PDT001049776.1' already exists. Skipping...
Folder 'GCA_018805865.1_PDT001049771.1' already exists. Skipping...
Folder 'GCA_018805955.1_PDT001049763.1' already exists. Skipping...
Folder 'GCA_018806255.1_PDT001049750.1' already exists. Skipping...
Folder 'GCA_018808545.1_PDT001049626.1' already exists. Skipping...
Folder 'GCA_018809085.1_PDT001049613.1' already exists. Skipping...
Folder 'GCA_018809225.1_PDT001049602.1' already exists. Skipping...
Folder 'GCA_018809245.1_PDT001049600.1' already exists. Skipping...
Folder 'GCA_018809265.1_PDT001049595.1' already exists. Skipping...
Folder 'GCA_018810005.1_PDT001049555.1' already exists. Skipping...
Folder 'GCA_018832005.1_PDT001065516.1' already exists. Skipping...
Folder 'GCA_018832065.1_PDT001065509.1' already exists. Skipping...
Folder 'GCA_018832145.1_PDT001065504.1' already exists. Skipping...
Folder 'GCA_018832185.1_PDT001065502.1' already exists. Skipping...
Folder 'GCA_018832365.1_PDT001065494.1' already exists. Skipping...
Folder 'GCA_018832545.1_PDT001065481.1' already exists. Skipping...
Folder 'GCA_018833185.1_PDT001065449.1' already exists. Skipping...
Folder 'GCA_018833345.1_PDT001065441.1' already exists. Skipping...
Folder 'GCA_018833425.1_PDT001065439.1' already exists. Skipping...
Folder 'GCA_018833985.1_PDT001065408.1' already exists. Skipping...
Folder 'GCA_018834325.1_PDT001065371.1' already exists. Skipping...
Folder 'GCA_018834375.1_PDT001065369.1' already exists. Skipping...
Folder 'GCA_018834485.1_PDT001065362.1' already exists. Skipping...
Folder 'GCA_018834545.1_PDT001065354.1' already exists. Skipping...
Folder 'GCA_018834565.1_PDT001065351.1' already exists. Skipping...
Folder 'GCA_018834655.1_PDT001065361.1' already exists. Skipping...
Folder 'GCA_018834685.1_PDT001065357.1' already exists. Skipping...
Folder 'GCA_018834705.1_PDT001065358.1' already exists. Skipping...
Folder 'GCA_018834745.1_PDT001065350.1' already exists. Skipping...
Folder 'GCA_018834805.1_PDT001065345.1' already exists. Skipping...
Folder 'GCA_018834875.1_PDT001065344.1' already exists. Skipping...
Folder 'GCA_018834995.1_PDT001065339.1' already exists. Skipping...
Folder 'GCA_018835115.1_PDT001065330.1' already exists. Skipping...
Folder 'GCA_018835235.1_PDT001065324.1' already exists. Skipping...
Folder 'GCA_018835295.1_PDT001065325.1' already exists. Skipping...
Folder 'GCA_018835865.1_PDT001065289.1' already exists. Skipping...
Folder 'GCA_018835935.1_PDT001065282.1' already exists. Skipping...
Folder 'GCA_018836235.1_PDT001065272.1' already exists. Skipping...
Folder 'GCA_018836315.1_PDT001065266.1' already exists. Skipping...
Folder 'GCA_018836335.1_PDT001065265.1' already exists. Skipping...
Folder 'GCA_018836375.1_PDT001065263.1' already exists. Skipping...
Folder 'GCA_018836385.1_PDT001065264.1' already exists. Skipping...
Folder 'GCA_018836635.1_PDT001065227.1' already exists. Skipping...
Folder 'GCA_018837515.1_PDT001065695.1' already exists. Skipping...
Folder 'GCA_018837555.1_PDT001065691.1' already exists. Skipping...
Folder 'GCA_018838395.1_PDT001066693.1' already exists. Skipping...
Folder 'GCA_018838555.1_PDT001066689.1' already exists. Skipping...
Folder 'GCA_018838715.1_PDT001066682.1' already exists. Skipping...
Folder 'GCA_018840455.1_PDT001066561.1' already exists. Skipping...
Folder 'GCA_018840515.1_PDT001066555.1' already exists. Skipping...
Folder 'GCA_018840615.1_PDT001066550.1' already exists. Skipping...
Folder 'GCA_018840635.1_PDT001066546.1' already exists. Skipping...
Folder 'GCA_018840775.1_PDT001066539.1' already exists. Skipping...
Folder 'GCA_018840795.1_PDT001066538.1' already exists. Skipping...
Folder 'GCA_018840875.1_PDT001066534.1' already exists. Skipping...
Folder 'GCA_018840895.1_PDT001066532.1' already exists. Skipping...
Folder 'GCA_018840915.1_PDT001066529.1' already exists. Skipping...
Folder 'GCA_018840935.1_PDT001066531.1' already exists. Skipping...
Folder 'GCA_018840955.1_PDT001066527.1' already exists. Skipping...
Folder 'GCA_018840975.1_PDT001066525.1' already exists. Skipping...
Folder 'GCA_018840995.1_PDT001066522.1' already exists. Skipping...
Folder 'GCA_018841015.1_PDT001066519.1' already exists. Skipping...
Folder 'GCA_018841035.1_PDT001066518.1' already exists. Skipping...
Folder 'GCA_018841075.1_PDT001066524.1' already exists. Skipping...
Folder 'GCA_018841095.1_PDT001066516.1' already exists. Skipping...
Folder 'GCA_018869225.1_PDT001067652.1' already exists. Skipping...
Folder 'GCA_018869725.1_PDT001067622.1' already exists. Skipping...
Folder 'GCA_018869785.1_PDT001067616.1' already exists. Skipping...
Folder 'GCA_018869825.1_PDT001067617.1' already exists. Skipping...
Folder 'GCA_018869925.1_PDT001067614.1' already exists. Skipping...
Folder 'GCA_018869945.1_PDT001067610.1' already exists. Skipping...
Folder 'GCA_018869965.1_PDT001067612.1' already exists. Skipping...
Folder 'GCA_018870005.1_PDT001067606.1' already exists. Skipping...
Folder 'GCA_018870085.1_PDT001067605.1' already exists. Skipping...
Folder 'GCA_018870165.1_PDT001067602.1' already exists. Skipping...
Folder 'GCA_018870245.1_PDT001067590.1' already exists. Skipping...
Folder 'GCA_018870365.1_PDT001067594.1' already exists. Skipping...
Folder 'GCA_018870465.1_PDT001067584.1' already exists. Skipping...
Folder 'GCA_018870505.1_PDT001067587.1' already exists. Skipping...
Folder 'GCA_018870545.1_PDT001067582.1' already exists. Skipping...
Folder 'GCA_018870565.1_PDT001067581.1' already exists. Skipping...
Folder 'GCA_018870705.1_PDT001067569.1' already exists. Skipping...
Folder 'GCA_018870765.1_PDT001067572.1' already exists. Skipping...
Folder 'GCA_018870845.1_PDT001067567.1' already exists. Skipping...
Folder 'GCA_018870885.1_PDT001067560.1' already exists. Skipping...
Folder 'GCA_018871025.1_PDT001067556.1' already exists. Skipping...
Folder 'GCA_018871085.1_PDT001067550.1' already exists. Skipping...
Folder 'GCA_018871095.1_PDT001067549.1' already exists. Skipping...
Folder 'GCA_018871165.1_PDT001067554.1' already exists. Skipping...
Folder 'GCA_018871265.1_PDT001067545.1' already exists. Skipping...
Folder 'GCA_018871365.1_PDT001067543.1' already exists. Skipping...
Folder 'GCA_018871405.1_PDT001067538.1' already exists. Skipping...
Folder 'GCA_018871465.1_PDT001067536.1' already exists. Skipping...
Folder 'GCA_018871545.1_PDT001067523.1' already exists. Skipping...
Folder 'GCA_018871565.1_PDT001067524.1' already exists. Skipping...
Folder 'GCA_018871785.1_PDT001067519.1' already exists. Skipping...
Folder 'GCA_018871985.1_PDT001067509.1' already exists. Skipping...
Folder 'GCA_018872045.1_PDT001067498.1' already exists. Skipping...
Folder 'GCA_018872105.1_PDT001067505.1' already exists. Skipping...
Folder 'GCA_018872145.1_PDT001067504.1' already exists. Skipping...
Folder 'GCA_018872165.1_PDT001067503.1' already exists. Skipping...
Folder 'GCA_018872225.1_PDT001067499.1' already exists. Skipping...
Folder 'GCA_018872245.1_PDT001067496.1' already exists. Skipping...
Folder 'GCA_018872265.1_PDT001067492.1' already exists. Skipping...
Folder 'GCA_018873005.1_PDT001067458.1' already exists. Skipping...
Folder 'GCA_018873085.1_PDT001067455.1' already exists. Skipping...
Folder 'GCA_018873105.1_PDT001067454.1' already exists. Skipping...
Folder 'GCA_018873375.1_PDT001067434.1' already exists. Skipping...
Folder 'GCA_018873465.1_PDT001067191.1' already exists. Skipping...
Folder 'GCA_018873665.1_PDT001067175.1' already exists. Skipping...
Folder 'GCA_018873805.1_PDT001067167.1' already exists. Skipping...
Folder 'GCA_018873885.1_PDT001067169.1' already exists. Skipping...
Folder 'GCA_018873935.1_PDT001067158.1' already exists. Skipping...
Folder 'GCA_018873955.1_PDT001067160.1' already exists. Skipping...
Folder 'GCA_018874055.1_PDT001067154.1' already exists. Skipping...
Folder 'GCA_018874175.1_PDT001067145.1' already exists. Skipping...
Folder 'GCA_018874495.1_PDT001067142.1' already exists. Skipping...
Folder 'GCA_018874575.1_PDT001067133.1' already exists. Skipping...
Folder 'GCA_018874995.1_PDT001067121.1' already exists. Skipping...
Folder 'GCA_018875095.1_PDT001067185.1' already exists. Skipping...
Folder 'GCA_018875275.1_PDT001067116.1' already exists. Skipping...
Folder 'GCA_018886145.1_PDT001070322.1' already exists. Skipping...
Folder 'GCA_018908625.1_PDT001070350.1' already exists. Skipping...
Folder 'GCA_018920825.1_PDT001071523.1' already exists. Skipping...
Folder 'GCA_018920885.1_PDT001071521.1' already exists. Skipping...
Folder 'GCA_018920905.1_PDT001071518.1' already exists. Skipping...
Folder 'GCA_018921165.1_PDT001071513.1' already exists. Skipping...
Folder 'GCA_018921285.1_PDT001071499.1' already exists. Skipping...
Folder 'GCA_018921445.1_PDT001071494.1' already exists. Skipping...
Folder 'GCA_018937255.1_PDT001069897.1' already exists. Skipping...
Folder 'GCA_018937545.1_PDT001069877.1' already exists. Skipping...
Folder 'GCA_018939915.1_PDT001069741.1' already exists. Skipping...
Folder 'GCA_018940315.1_PDT001069721.1' already exists. Skipping...
Folder 'GCA_018944275.1_PDT001069475.1' already exists. Skipping...
Folder 'GCA_018944335.1_PDT001069461.1' already exists. Skipping...
Folder 'GCA_018944375.1_PDT001069458.1' already exists. Skipping...
Folder 'GCA_018944595.1_PDT001069448.1' already exists. Skipping...
Folder 'GCA_018944615.1_PDT001069453.1' already exists. Skipping...
Folder 'GCA_018944635.1_PDT001069441.1' already exists. Skipping...
Folder 'GCA_018949775.1_PDT001068901.1' already exists. Skipping...
Folder 'GCA_018949975.1_PDT001068931.1' already exists. Skipping...
Folder 'GCA_018949995.1_PDT001068928.1' already exists. Skipping...
Folder 'GCA_018950015.1_PDT001068930.1' already exists. Skipping...
Folder 'GCA_018950035.1_PDT001068925.1' already exists. Skipping...
Folder 'GCA_018950115.1_PDT001068912.1' already exists. Skipping...
Folder 'GCA_018950135.1_PDT001068905.1' already exists. Skipping...
Folder 'GCA_018950195.1_PDT001068917.1' already exists. Skipping...
Folder 'GCA_018950235.1_PDT001068921.1' already exists. Skipping...
Folder 'GCA_018950295.1_PDT001068898.1' already exists. Skipping...
Folder 'GCA_018950415.1_PDT001068891.1' already exists. Skipping...
Folder 'GCA_018950515.1_PDT001068926.1' already exists. Skipping...
Folder 'GCA_018950535.1_PDT001068920.1' already exists. Skipping...
Folder 'GCA_018950575.1_PDT001068918.1' already exists. Skipping...
Folder 'GCA_018950615.1_PDT001068915.1' already exists. Skipping...
Folder 'GCA_018952895.1_PDT001071712.1' already exists. Skipping...
Folder 'GCA_018953135.1_PDT001071699.1' already exists. Skipping...
Folder 'GCA_018953175.1_PDT001071697.1' already exists. Skipping...
Folder 'GCA_018953215.1_PDT001071698.1' already exists. Skipping...
Folder 'GCA_018953275.1_PDT001071693.1' already exists. Skipping...
Folder 'GCA_018955225.1_PDT001071563.1' already exists. Skipping...
Folder 'GCA_018955275.1_PDT001071565.1' already exists. Skipping...
Folder 'GCA_018955335.1_PDT001071560.1' already exists. Skipping...
Folder 'GCA_018955355.1_PDT001071566.1' already exists. Skipping...
Folder 'GCA_018955395.1_PDT001071559.1' already exists. Skipping...
Folder 'GCA_018955455.1_PDT001071555.1' already exists. Skipping...
Folder 'GCA_018955495.1_PDT001071553.1' already exists. Skipping...
Folder 'GCA_018955655.1_PDT001071543.1' already exists. Skipping...
Folder 'GCA_018955675.1_PDT001071550.1' already exists. Skipping...
Folder 'GCA_018955775.1_PDT001071539.1' already exists. Skipping...
Folder 'GCA_018955795.1_PDT001071536.1' already exists. Skipping...
Folder 'GCA_018959195.1_PDT001072176.1' already exists. Skipping...
Folder 'GCA_018962575.1_PDT001037683.1' already exists. Skipping...
Folder 'GCA_018962675.1_PDT001037657.1' already exists. Skipping...
Folder 'GCA_018962745.1_PDT001037656.1' already exists. Skipping...
Folder 'GCA_018962955.1_PDT001033353.1' already exists. Skipping...
Folder 'GCA_018963035.1_PDT001033348.1' already exists. Skipping...
Folder 'GCA_018963055.1_PDT001033343.1' already exists. Skipping...
Folder 'GCA_018963495.1_PDT001033351.1' already exists. Skipping...
Folder 'GCA_018963595.1_PDT001033344.1' already exists. Skipping...
Folder 'GCA_018963615.1_PDT001033346.1' already exists. Skipping...
Folder 'GCA_018963635.1_PDT001033349.1' already exists. Skipping...
Folder 'GCA_018963655.1_PDT001033352.1' already exists. Skipping...
Folder 'GCA_018963815.1_PDT001033342.1' already exists. Skipping...
Folder 'GCA_018966065.1_PDT001033347.1' already exists. Skipping...
Folder 'GCA_018966085.1_PDT001033345.1' already exists. Skipping...
Folder 'GCA_018968305.1_PDT001074007.1' already exists. Skipping...
Folder 'GCA_018968345.1_PDT001074010.1' already exists. Skipping...
Folder 'GCA_018968385.1_PDT001074005.1' already exists. Skipping...
Folder 'GCA_018968445.1_PDT001073999.1' already exists. Skipping...
Folder 'GCA_018968485.1_PDT001074003.1' already exists. Skipping...
Folder 'GCA_018968605.1_PDT001073985.1' already exists. Skipping...
Folder 'GCA_018976345.1_PDT001072687.1' already exists. Skipping...
Folder 'GCA_018976985.1_PDT001072637.1' already exists. Skipping...
Folder 'GCA_018977045.1_PDT001072632.1' already exists. Skipping...
Folder 'GCA_018977065.1_PDT001072630.1' already exists. Skipping...
Folder 'GCA_018977165.1_PDT001072622.1' already exists. Skipping...
Folder 'GCA_018977505.1_PDT001072607.1' already exists. Skipping...
Folder 'GCA_018977525.1_PDT001072608.1' already exists. Skipping...
Folder 'GCA_018977585.1_PDT001072605.1' already exists. Skipping...
Folder 'GCA_018978205.1_PDT001072567.1' already exists. Skipping...
Folder 'GCA_018978265.1_PDT001072564.1' already exists. Skipping...
Folder 'GCA_018978285.1_PDT001072565.1' already exists. Skipping...
Folder 'GCA_018978325.1_PDT001072562.1' already exists. Skipping...
Folder 'GCA_018979625.1_PDT001029108.1' already exists. Skipping...
Folder 'GCA_018981745.1_PDT001028945.1' already exists. Skipping...
Folder 'GCA_018981785.1_PDT001028949.1' already exists. Skipping...
Folder 'GCA_018981805.1_PDT001028941.1' already exists. Skipping...
Folder 'GCA_018981845.1_PDT001028940.1' already exists. Skipping...
Folder 'GCA_018987445.1_PDT001074532.1' already exists. Skipping...
Folder 'GCA_018987485.1_PDT001074627.1' already exists. Skipping...
Folder 'GCA_018994215.1_PDT001074590.1' already exists. Skipping...
Folder 'GCA_018994505.1_PDT001074575.1' already exists. Skipping...
Folder 'GCA_018994985.1_PDT001074550.1' already exists. Skipping...
Folder 'GCA_018997385.1_PDT001074500.1' already exists. Skipping...
Folder 'GCA_018997975.1_PDT001074474.1' already exists. Skipping...
Folder 'GCA_018999375.1_PDT001074448.1' already exists. Skipping...
Folder 'GCA_019003645.1_PDT001075721.1' already exists. Skipping...
Folder 'GCA_019003665.1_PDT001075720.1' already exists. Skipping...
Folder 'GCA_019003685.1_PDT001075719.1' already exists. Skipping...
Folder 'GCA_019003705.1_PDT001075718.1' already exists. Skipping...
Folder 'GCA_019003725.1_PDT001075717.1' already exists. Skipping...
Folder 'GCA_019003765.1_PDT001075686.1' already exists. Skipping...
Folder 'GCA_019003785.1_PDT001075683.1' already exists. Skipping...
Folder 'GCA_019005425.1_PDT001075941.1' already exists. Skipping...
Folder 'GCA_019005435.1_PDT001075939.1' already exists. Skipping...
Folder 'GCA_019005465.1_PDT001075937.1' already exists. Skipping...
Folder 'GCA_019005485.1_PDT001075923.1' already exists. Skipping...
Folder 'GCA_019005625.1_PDT001075882.1' already exists. Skipping...
Folder 'GCA_019005645.1_PDT001075876.1' already exists. Skipping...
Folder 'GCA_019006285.1_PDT001075997.1' already exists. Skipping...
Folder 'GCA_019006305.1_PDT001075996.1' already exists. Skipping...
Folder 'GCA_019006385.1_PDT001075992.1' already exists. Skipping...
Folder 'GCA_019006485.1_PDT001075986.1' already exists. Skipping...
Folder 'GCA_019006525.1_PDT001075984.1' already exists. Skipping...
Folder 'GCA_019006545.1_PDT001075985.1' already exists. Skipping...
Folder 'GCA_019006625.1_PDT001075978.1' already exists. Skipping...

Retreiveing data: 77812it [00:13, 6638.01it/s]

Folder 'GCA_019563595.1_PDT001101618.1' already exists. Skipping...
Folder 'GCA_019563695.1_PDT001101615.1' already exists. Skipping...
Folder 'GCA_019563735.1_PDT001101614.1' already exists. Skipping...
Folder 'GCA_019563815.1_PDT001101613.1' already exists. Skipping...
Folder 'GCA_019563895.1_PDT001101609.1' already exists. Skipping...
Folder 'GCA_019563915.1_PDT001101611.1' already exists. Skipping...
Folder 'GCA_019563935.1_PDT001101608.1' already exists. Skipping...
Folder 'GCA_019563955.1_PDT001101606.1' already exists. Skipping...
Folder 'GCA_019563975.1_PDT001101603.1' already exists. Skipping...
Folder 'GCA_019564055.1_PDT001101601.1' already exists. Skipping...
Folder 'GCA_019564095.1_PDT001101597.1' already exists. Skipping...
Folder 'GCA_019564115.1_PDT001101596.1' already exists. Skipping...
Folder 'GCA_019564175.1_PDT001101594.1' already exists. Skipping...
Folder 'GCA_019564235.1_PDT001101589.1' already exists. Skipping...
Folder 'GCA_019564255.1_PDT001101587.1' already exists. Skipping...
Folder 'GCA_019564265.1_PDT001101588.1' already exists. Skipping...
Folder 'GCA_019564475.1_PDT001101579.1' already exists. Skipping...
Folder 'GCA_019564495.1_PDT001101580.1' already exists. Skipping...
Folder 'GCA_019564675.1_PDT001101566.1' already exists. Skipping...
Folder 'GCA_019564735.1_PDT001101564.1' already exists. Skipping...
Folder 'GCA_019564755.1_PDT001101563.1' already exists. Skipping...
Folder 'GCA_019564795.1_PDT001101561.1' already exists. Skipping...
Folder 'GCA_019564915.1_PDT001101560.1' already exists. Skipping...
Folder 'GCA_019565075.1_PDT001101550.1' already exists. Skipping...
Folder 'GCA_019565155.1_PDT001101538.1' already exists. Skipping...
Folder 'GCA_019565175.1_PDT001101539.1' already exists. Skipping...
Folder 'GCA_019565235.1_PDT001101541.1' already exists. Skipping...
Folder 'GCA_019565355.1_PDT001101543.1' already exists. Skipping...
Folder 'GCA_019565395.1_PDT001101533.1' already exists. Skipping...
Folder 'GCA_019565415.1_PDT001101532.1' already exists. Skipping...
Folder 'GCA_019565435.1_PDT001101537.1' already exists. Skipping...
Folder 'GCA_019565475.1_PDT001101536.1' already exists. Skipping...
Folder 'GCA_019565595.1_PDT001101534.1' already exists. Skipping...
Folder 'GCA_019565655.1_PDT001101528.1' already exists. Skipping...
Folder 'GCA_019565675.1_PDT001101526.1' already exists. Skipping...
Folder 'GCA_019565695.1_PDT001101527.1' already exists. Skipping...
Folder 'GCA_019565715.1_PDT001101523.1' already exists. Skipping...
Folder 'GCA_019565755.1_PDT001101525.1' already exists. Skipping...
Folder 'GCA_019566015.1_PDT001101513.1' already exists. Skipping...
Folder 'GCA_019566055.1_PDT001101509.1' already exists. Skipping...
Folder 'GCA_019566095.1_PDT001101506.1' already exists. Skipping...
Folder 'GCA_019566155.1_PDT001101508.1' already exists. Skipping...
Folder 'GCA_019566205.1_PDT001101502.1' already exists. Skipping...
Folder 'GCA_019581195.1_PDT001108337.1' already exists. Skipping...
Folder 'GCA_019581235.1_PDT001108341.1' already exists. Skipping...
Folder 'GCA_019583195.1_PDT001108510.1' already exists. Skipping...
Folder 'GCA_019588265.1_PDT001108529.1' already exists. Skipping...
Folder 'GCA_019588305.1_PDT001108522.1' already exists. Skipping...
Folder 'GCA_019590265.1_PDT001108643.1' already exists. Skipping...
Folder 'GCA_019590285.1_PDT001108644.1' already exists. Skipping...
Folder 'GCA_019590545.1_PDT001108629.1' already exists. Skipping...
Folder 'GCA_019590665.1_PDT001108623.1' already exists. Skipping...
Folder 'GCA_019594685.1_PDT001108780.1' already exists. Skipping...
Folder 'GCA_019594705.1_PDT001108779.1' already exists. Skipping...
Folder 'GCA_019594825.1_PDT001108785.1' already exists. Skipping...
Folder 'GCA_019595755.1_PDT001108854.1' already exists. Skipping...
Folder 'GCA_019595825.1_PDT001108871.1' already exists. Skipping...
Folder 'GCA_019597945.1_PDT001108986.1' already exists. Skipping...
Folder 'GCA_019597965.1_PDT001108999.1' already exists. Skipping...
Folder 'GCA_019597975.1_PDT001108983.1' already exists. Skipping...
Folder 'GCA_019598005.1_PDT001108984.1' already exists. Skipping...
Folder 'GCA_019598025.1_PDT001108985.1' already exists. Skipping...
Folder 'GCA_019598045.1_PDT001108968.1' already exists. Skipping...
Folder 'GCA_019598065.1_PDT001108972.1' already exists. Skipping...
Folder 'GCA_019598105.1_PDT001109000.1' already exists. Skipping...
Folder 'GCA_019599875.1_PDT001109326.1' already exists. Skipping...
Folder 'GCA_019600335.1_PDT001109298.1' already exists. Skipping...
Folder 'GCA_019600435.1_PDT001109282.1' already exists. Skipping...
Folder 'GCA_019600835.1_PDT001109271.1' already exists. Skipping...
Folder 'GCA_019601095.1_PDT001109095.1' already exists. Skipping...
Folder 'GCA_019601835.1_PDT001109054.1' already exists. Skipping...
Folder 'GCA_019601875.1_PDT001109042.1' already exists. Skipping...
Folder 'GCA_019601915.1_PDT001109051.1' already exists. Skipping...
Folder 'GCA_019602095.1_PDT001109041.1' already exists. Skipping...
Folder 'GCA_019602275.1_PDT001109031.1' already exists. Skipping...
Folder 'GCA_019602315.1_PDT001109029.1' already exists. Skipping...
Folder 'GCA_019602335.1_PDT001109024.1' already exists. Skipping...
Folder 'GCA_019602395.1_PDT001109023.1' already exists. Skipping...
Folder 'GCA_019602415.1_PDT001109026.1' already exists. Skipping...
Folder 'GCA_019602435.1_PDT001109018.1' already exists. Skipping...
Folder 'GCA_019602455.1_PDT001109020.1' already exists. Skipping...
Folder 'GCA_019602475.1_PDT001109019.1' already exists. Skipping...
Folder 'GCA_019602535.1_PDT001109016.1' already exists. Skipping...
Folder 'GCA_019602555.1_PDT001109015.1' already exists. Skipping...
Folder 'GCA_019602575.1_PDT001109013.1' already exists. Skipping...
Folder 'GCA_019602635.1_PDT001109014.1' already exists. Skipping...
Folder 'GCA_019602655.1_PDT001109010.1' already exists. Skipping...
Folder 'GCA_019602675.1_PDT001109006.1' already exists. Skipping...
Folder 'GCA_019602695.1_PDT001109005.1' already exists. Skipping...
Folder 'GCA_019602755.1_PDT001109003.1' already exists. Skipping...
Folder 'GCA_019602775.1_PDT001109004.1' already exists. Skipping...
Folder 'GCA_019603415.1_ASM1960341v1' already exists. Skipping...
Folder 'GCA_019603425.1_ASM1960342v1' already exists. Skipping...
Folder 'GCA_019603455.1_ASM1960345v1' already exists. Skipping...
Folder 'GCA_019603465.1_ASM1960346v1' already exists. Skipping...
Folder 'GCA_019603475.1_ASM1960347v1' already exists. Skipping...
Folder 'GCA_019603515.1_ASM1960351v1' already exists. Skipping...
Folder 'GCA_019603535.1_ASM1960353v1' already exists. Skipping...
Folder 'GCA_019603555.1_ASM1960355v1' already exists. Skipping...
Folder 'GCA_019603575.1_ASM1960357v1' already exists. Skipping...
Folder 'GCA_019603595.1_ASM1960359v1' already exists. Skipping...
Folder 'GCA_019603615.1_ASM1960361v1' already exists. Skipping...
Folder 'GCA_019603635.1_ASM1960363v1' already exists. Skipping...
Folder 'GCA_019603655.1_ASM1960365v1' already exists. Skipping...
Folder 'GCA_019603675.1_ASM1960367v1' already exists. Skipping...
Folder 'GCA_019603695.1_ASM1960369v1' already exists. Skipping...
Folder 'GCA_019603715.1_ASM1960371v1' already exists. Skipping...
Folder 'GCA_019603735.1_ASM1960373v1' already exists. Skipping...
Folder 'GCA_019603745.1_ASM1960374v1' already exists. Skipping...
Folder 'GCA_019603775.1_ASM1960377v1' already exists. Skipping...
Folder 'GCA_019603795.1_ASM1960379v1' already exists. Skipping...
Folder 'GCA_019603815.1_ASM1960381v1' already exists. Skipping...
Folder 'GCA_019603825.1_ASM1960382v1' already exists. Skipping...
Folder 'GCA_019603855.1_ASM1960385v1' already exists. Skipping...
Folder 'GCA_019603875.1_ASM1960387v1' already exists. Skipping...
Folder 'GCA_019603895.1_ASM1960389v1' already exists. Skipping...
Folder 'GCA_019603935.1_ASM1960393v1' already exists. Skipping...
Folder 'GCA_019603955.1_ASM1960395v1' already exists. Skipping...
Folder 'GCA_019603975.1_ASM1960397v1' already exists. Skipping...
Folder 'GCA_019603995.1_ASM1960399v1' already exists. Skipping...
Folder 'GCA_019604005.1_ASM1960400v1' already exists. Skipping...
Folder 'GCA_019604035.1_ASM1960403v1' already exists. Skipping...
Folder 'GCA_019604045.1_ASM1960404v1' already exists. Skipping...
Folder 'GCA_019604075.1_ASM1960407v1' already exists. Skipping...
Folder 'GCA_019604095.1_ASM1960409v1' already exists. Skipping...
Folder 'GCA_019604115.1_ASM1960411v1' already exists. Skipping...
Folder 'GCA_019604155.1_ASM1960415v1' already exists. Skipping...
Folder 'GCA_019604195.1_ASM1960419v1' already exists. Skipping...
Folder 'GCA_019604275.1_ASM1960427v1' already exists. Skipping...
Folder 'GCA_019604295.1_ASM1960429v1' already exists. Skipping...
Folder 'GCA_019604445.1_ASM1960444v1' already exists. Skipping...
Folder 'GCA_019604485.1_ASM1960448v1' already exists. Skipping...
Folder 'GCA_019604505.1_ASM1960450v1' already exists. Skipping...
Folder 'GCA_019604545.1_ASM1960454v1' already exists. Skipping...
Folder 'GCA_019604565.1_ASM1960456v1' already exists. Skipping...
Folder 'GCA_019604605.1_ASM1960460v1' already exists. Skipping...
Folder 'GCA_019604615.1_ASM1960461v1' already exists. Skipping...
Folder 'GCA_019604645.1_ASM1960464v1' already exists. Skipping...
Folder 'GCA_019604705.1_ASM1960470v1' already exists. Skipping...
Folder 'GCA_019604715.1_ASM1960471v1' already exists. Skipping...
Folder 'GCA_019604745.1_ASM1960474v1' already exists. Skipping...
Folder 'GCA_019604785.1_ASM1960478v1' already exists. Skipping...
Folder 'GCA_019604805.1_ASM1960480v1' already exists. Skipping...
Folder 'GCA_019604815.1_ASM1960481v1' already exists. Skipping...
Folder 'GCA_019604845.1_ASM1960484v1' already exists. Skipping...
Folder 'GCA_019604855.1_ASM1960485v1' already exists. Skipping...
Folder 'GCA_019604885.1_ASM1960488v1' already exists. Skipping...
Folder 'GCA_019604905.1_ASM1960490v1' already exists. Skipping...
Folder 'GCA_019604915.1_ASM1960491v1' already exists. Skipping...
Folder 'GCA_019604945.1_ASM1960494v1' already exists. Skipping...
Folder 'GCA_019604955.1_ASM1960495v1' already exists. Skipping...
Folder 'GCA_019604985.1_ASM1960498v1' already exists. Skipping...
Folder 'GCA_019605005.1_ASM1960500v1' already exists. Skipping...
Folder 'GCA_019605015.1_ASM1960501v1' already exists. Skipping...
Folder 'GCA_019605045.1_ASM1960504v1' already exists. Skipping...
Folder 'GCA_019605065.1_ASM1960506v1' already exists. Skipping...
Folder 'GCA_019605085.1_ASM1960508v1' already exists. Skipping...
Folder 'GCA_019605105.1_ASM1960510v1' already exists. Skipping...
Folder 'GCA_019605115.1_ASM1960511v1' already exists. Skipping...
Folder 'GCA_019605145.1_ASM1960514v1' already exists. Skipping...
Folder 'GCA_019605155.1_ASM1960515v1' already exists. Skipping...
Folder 'GCA_019605185.1_ASM1960518v1' already exists. Skipping...
Folder 'GCA_019605195.1_ASM1960519v1' already exists. Skipping...
Folder 'GCA_019605215.1_ASM1960521v1' already exists. Skipping...
Folder 'GCA_019605245.1_ASM1960524v1' already exists. Skipping...
Folder 'GCA_019605265.1_ASM1960526v1' already exists. Skipping...
Folder 'GCA_019605285.1_ASM1960528v1' already exists. Skipping...
Folder 'GCA_019605305.1_ASM1960530v1' already exists. Skipping...
Folder 'GCA_019605325.1_ASM1960532v1' already exists. Skipping...
Folder 'GCA_019605345.1_ASM1960534v1' already exists. Skipping...
Folder 'GCA_019605385.1_ASM1960538v1' already exists. Skipping...
Folder 'GCA_019605405.1_ASM1960540v1' already exists. Skipping...
Folder 'GCA_019605425.1_ASM1960542v1' already exists. Skipping...
Folder 'GCA_019605435.1_ASM1960543v1' already exists. Skipping...
Folder 'GCA_019605465.1_ASM1960546v1' already exists. Skipping...
Folder 'GCA_019605485.1_ASM1960548v1' already exists. Skipping...
Folder 'GCA_019605495.1_ASM1960549v1' already exists. Skipping...
Folder 'GCA_019605525.1_ASM1960552v1' already exists. Skipping...
Folder 'GCA_019605555.1_ASM1960555v1' already exists. Skipping...
Folder 'GCA_019605585.1_ASM1960558v1' already exists. Skipping...
Folder 'GCA_019605605.1_ASM1960560v1' already exists. Skipping...
Folder 'GCA_019605625.1_ASM1960562v1' already exists. Skipping...
Folder 'GCA_019605655.1_ASM1960565v1' already exists. Skipping...
Folder 'GCA_019605685.1_ASM1960568v1' already exists. Skipping...
Folder 'GCA_019605745.1_ASM1960574v1' already exists. Skipping...
Folder 'GCA_019605755.1_ASM1960575v1' already exists. Skipping...
Folder 'GCA_019605785.1_ASM1960578v1' already exists. Skipping...
Folder 'GCA_019605805.1_ASM1960580v1' already exists. Skipping...
Folder 'GCA_019605825.1_ASM1960582v1' already exists. Skipping...
Folder 'GCA_019605835.1_ASM1960583v1' already exists. Skipping...
Folder 'GCA_019605865.1_ASM1960586v1' already exists. Skipping...
Folder 'GCA_019605885.1_ASM1960588v1' already exists. Skipping...
Folder 'GCA_019605895.1_ASM1960589v1' already exists. Skipping...
Folder 'GCA_019605925.1_ASM1960592v1' already exists. Skipping...
Folder 'GCA_019605935.1_ASM1960593v1' already exists. Skipping...
Folder 'GCA_019605955.1_ASM1960595v1' already exists. Skipping...
Folder 'GCA_019605985.1_ASM1960598v1' already exists. Skipping...
Folder 'GCA_019605995.1_ASM1960599v1' already exists. Skipping...
Folder 'GCA_019606025.1_ASM1960602v1' already exists. Skipping...
Folder 'GCA_019606045.1_ASM1960604v1' already exists. Skipping...
Folder 'GCA_019606065.1_ASM1960606v1' already exists. Skipping...
Folder 'GCA_019606085.1_ASM1960608v1' already exists. Skipping...
Folder 'GCA_019606105.1_ASM1960610v1' already exists. Skipping...
Folder 'GCA_019606125.1_ASM1960612v1' already exists. Skipping...
Folder 'GCA_019606145.1_ASM1960614v1' already exists. Skipping...
Folder 'GCA_019606155.1_ASM1960615v1' already exists. Skipping...
Folder 'GCA_019606185.1_ASM1960618v1' already exists. Skipping...
Folder 'GCA_019606205.1_ASM1960620v1' already exists. Skipping...
Folder 'GCA_019606225.1_ASM1960622v1' already exists. Skipping...
Folder 'GCA_019606245.1_ASM1960624v1' already exists. Skipping...
Folder 'GCA_019606255.1_ASM1960625v1' already exists. Skipping...
Folder 'GCA_019606285.1_ASM1960628v1' already exists. Skipping...
Folder 'GCA_019606305.1_ASM1960630v1' already exists. Skipping...
Folder 'GCA_019606315.1_ASM1960631v1' already exists. Skipping...
Folder 'GCA_019606345.1_ASM1960634v1' already exists. Skipping...
Folder 'GCA_019606365.1_ASM1960636v1' already exists. Skipping...
Folder 'GCA_019606445.1_ASM1960644v1' already exists. Skipping...
Folder 'GCA_019606485.1_ASM1960648v1' already exists. Skipping...
Folder 'GCA_019606495.1_ASM1960649v1' already exists. Skipping...
Folder 'GCA_019606525.1_ASM1960652v1' already exists. Skipping...
Folder 'GCA_019606555.1_ASM1960655v1' already exists. Skipping...
Folder 'GCA_019606585.1_ASM1960658v1' already exists. Skipping...
Folder 'GCA_019606605.1_ASM1960660v1' already exists. Skipping...
Folder 'GCA_019606615.1_ASM1960661v1' already exists. Skipping...
Folder 'GCA_019606675.1_ASM1960667v1' already exists. Skipping...
Folder 'GCA_019606705.1_ASM1960670v1' already exists. Skipping...
Folder 'GCA_019606715.1_ASM1960671v1' already exists. Skipping...
Folder 'GCA_019606745.1_ASM1960674v1' already exists. Skipping...
Folder 'GCA_019606765.1_ASM1960676v1' already exists. Skipping...
Folder 'GCA_019606805.1_ASM1960680v1' already exists. Skipping...
Folder 'GCA_019606825.1_ASM1960682v1' already exists. Skipping...
Folder 'GCA_019606845.1_ASM1960684v1' already exists. Skipping...
Folder 'GCA_019606865.1_ASM1960686v1' already exists. Skipping...
Folder 'GCA_019606875.1_ASM1960687v1' already exists. Skipping...
Folder 'GCA_019606905.1_ASM1960690v1' already exists. Skipping...
Folder 'GCA_019606945.1_ASM1960694v1' already exists. Skipping...
Folder 'GCA_019606965.1_ASM1960696v1' already exists. Skipping...
Folder 'GCA_019606985.1_ASM1960698v1' already exists. Skipping...
Folder 'GCA_019607005.1_ASM1960700v1' already exists. Skipping...
Folder 'GCA_019607085.1_ASM1960708v1' already exists. Skipping...
Folder 'GCA_019607115.1_ASM1960711v1' already exists. Skipping...
Folder 'GCA_019607125.1_ASM1960712v1' already exists. Skipping...
Folder 'GCA_019607165.1_ASM1960716v1' already exists. Skipping...
Folder 'GCA_019607185.1_ASM1960718v1' already exists. Skipping...
Folder 'GCA_019607205.1_ASM1960720v1' already exists. Skipping...
Folder 'GCA_019607225.1_ASM1960722v1' already exists. Skipping...
Folder 'GCA_019607235.1_ASM1960723v1' already exists. Skipping...
Folder 'GCA_019607265.1_ASM1960726v1' already exists. Skipping...
Folder 'GCA_019607285.1_ASM1960728v1' already exists. Skipping...
Folder 'GCA_019607305.1_ASM1960730v1' already exists. Skipping...
Folder 'GCA_019607315.1_ASM1960731v1' already exists. Skipping...
Folder 'GCA_019607335.1_ASM1960733v1' already exists. Skipping...
Folder 'GCA_019607365.1_ASM1960736v1' already exists. Skipping...
Folder 'GCA_019607375.1_ASM1960737v1' already exists. Skipping...
Folder 'GCA_019607405.1_ASM1960740v1' already exists. Skipping...
Folder 'GCA_019607425.1_ASM1960742v1' already exists. Skipping...
Folder 'GCA_019607445.1_ASM1960744v1' already exists. Skipping...
Folder 'GCA_019607455.1_ASM1960745v1' already exists. Skipping...
Folder 'GCA_019607485.1_ASM1960748v1' already exists. Skipping...
Folder 'GCA_019607495.1_ASM1960749v1' already exists. Skipping...
Folder 'GCA_019607525.1_ASM1960752v1' already exists. Skipping...
Folder 'GCA_019607565.1_ASM1960756v1' already exists. Skipping...
Folder 'GCA_019607585.1_ASM1960758v1' already exists. Skipping...
Folder 'GCA_019607595.1_ASM1960759v1' already exists. Skipping...
Folder 'GCA_019607625.1_ASM1960762v1' already exists. Skipping...
Folder 'GCA_019607635.1_ASM1960763v1' already exists. Skipping...
Folder 'GCA_019607645.1_ASM1960764v1' already exists. Skipping...
Folder 'GCA_019607685.1_ASM1960768v1' already exists. Skipping...
Folder 'GCA_019607705.1_ASM1960770v1' already exists. Skipping...
Folder 'GCA_019607725.1_ASM1960772v1' already exists. Skipping...
Folder 'GCA_019607745.1_ASM1960774v1' already exists. Skipping...
Folder 'GCA_019607755.1_ASM1960775v1' already exists. Skipping...
Folder 'GCA_019607785.1_ASM1960778v1' already exists. Skipping...
Folder 'GCA_019607805.1_ASM1960780v1' already exists. Skipping...
Folder 'GCA_019607825.1_ASM1960782v1' already exists. Skipping...
Folder 'GCA_019607845.1_ASM1960784v1' already exists. Skipping...
Folder 'GCA_019607855.1_ASM1960785v1' already exists. Skipping...
Folder 'GCA_019607885.1_ASM1960788v1' already exists. Skipping...
Folder 'GCA_019607895.1_ASM1960789v1' already exists. Skipping...
Folder 'GCA_019607925.1_ASM1960792v1' already exists. Skipping...
Folder 'GCA_019607945.1_ASM1960794v1' already exists. Skipping...
Folder 'GCA_019607965.1_ASM1960796v1' already exists. Skipping...
Folder 'GCA_019607985.1_ASM1960798v1' already exists. Skipping...
Folder 'GCA_019608005.1_ASM1960800v1' already exists. Skipping...
Folder 'GCA_019608025.1_ASM1960802v1' already exists. Skipping...
Folder 'GCA_019608035.1_ASM1960803v1' already exists. Skipping...
Folder 'GCA_019608065.1_ASM1960806v1' already exists. Skipping...
Folder 'GCA_019608075.1_ASM1960807v1' already exists. Skipping...
Folder 'GCA_019608115.1_ASM1960811v1' already exists. Skipping...
Folder 'GCA_019608125.1_ASM1960812v1' already exists. Skipping...
Folder 'GCA_019608165.1_ASM1960816v1' already exists. Skipping...
Folder 'GCA_019608175.1_ASM1960817v1' already exists. Skipping...
Folder 'GCA_019608205.1_ASM1960820v1' already exists. Skipping...
Folder 'GCA_019608225.1_ASM1960822v1' already exists. Skipping...
Folder 'GCA_019608245.1_ASM1960824v1' already exists. Skipping...
Folder 'GCA_019608285.1_ASM1960828v1' already exists. Skipping...
Folder 'GCA_019608305.1_ASM1960830v1' already exists. Skipping...
Folder 'GCA_019608315.1_ASM1960831v1' already exists. Skipping...
Folder 'GCA_019608345.1_ASM1960834v1' already exists. Skipping...
Folder 'GCA_019608365.1_ASM1960836v1' already exists. Skipping...

Retreiveing data: 79146it [00:13, 6640.09it/s]

Folder 'GCA_019633045.1_ASM1963304v1' already exists. Skipping...
Folder 'GCA_019633055.1_ASM1963305v1' already exists. Skipping...
Folder 'GCA_019633085.1_ASM1963308v1' already exists. Skipping...
Folder 'GCA_019633105.1_ASM1963310v1' already exists. Skipping...
Folder 'GCA_019633125.1_ASM1963312v1' already exists. Skipping...
Folder 'GCA_019633135.1_ASM1963313v1' already exists. Skipping...
Folder 'GCA_019633165.1_ASM1963316v1' already exists. Skipping...
Folder 'GCA_019633225.1_ASM1963322v1' already exists. Skipping...
Folder 'GCA_019633245.1_ASM1963324v1' already exists. Skipping...
Folder 'GCA_019633265.1_ASM1963326v1' already exists. Skipping...
Folder 'GCA_019633285.1_ASM1963328v1' already exists. Skipping...
Folder 'GCA_019633305.1_ASM1963330v1' already exists. Skipping...
Folder 'GCA_019633325.1_ASM1963332v1' already exists. Skipping...
Folder 'GCA_019633345.1_ASM1963334v1' already exists. Skipping...
Folder 'GCA_019633355.1_ASM1963335v1' already exists. Skipping...
Folder 'GCA_019633385.1_ASM1963338v1' already exists. Skipping...
Folder 'GCA_019640135.1_PDT001109747.1' already exists. Skipping...
Folder 'GCA_019640155.1_PDT001109742.1' already exists. Skipping...
Folder 'GCA_019641525.1_ASM1964152v1' already exists. Skipping...
Folder 'GCA_019641565.1_ASM1964156v1' already exists. Skipping...
Folder 'GCA_019641595.1_ASM1964159v1' already exists. Skipping...
Folder 'GCA_019643795.1_PDT001109820.1' already exists. Skipping...
Folder 'GCA_019643835.1_PDT001109822.1' already exists. Skipping...
Folder 'GCA_019646175.1_PDT001109972.1' already exists. Skipping...
Folder 'GCA_019647335.1_PDT001110012.1' already exists. Skipping...
Folder 'GCA_019647395.1_PDT001110024.1' already exists. Skipping...
Folder 'GCA_019647775.1_PDT001110037.1' already exists. Skipping...
Folder 'GCA_019647855.1_PDT001110034.1' already exists. Skipping...
Folder 'GCA_019647915.1_PDT001110026.1' already exists. Skipping...
Folder 'GCA_019647955.1_PDT001110015.1' already exists. Skipping...
Folder 'GCA_019647995.1_PDT001110014.1' already exists. Skipping...
Folder 'GCA_019648035.1_PDT001110008.1' already exists. Skipping...
Folder 'GCA_019648135.1_PDT001109996.1' already exists. Skipping...
Folder 'GCA_019648155.1_PDT001109995.1' already exists. Skipping...
Folder 'GCA_019648175.1_PDT001109994.1' already exists. Skipping...
Folder 'GCA_019648235.1_PDT001110021.1' already exists. Skipping...
Folder 'GCA_019648275.1_PDT001110044.1' already exists. Skipping...
Folder 'GCA_019648715.1_PDT001110036.1' already exists. Skipping...
Folder 'GCA_019658745.1_PDT001110300.1' already exists. Skipping...
Folder 'GCA_019658785.1_PDT001110297.1' already exists. Skipping...
Folder 'GCA_019658825.1_PDT001110306.1' already exists. Skipping...
Folder 'GCA_019658845.1_PDT001110303.1' already exists. Skipping...
Folder 'GCA_019658885.1_PDT001110305.1' already exists. Skipping...
Folder 'GCA_019658905.1_PDT001110304.1' already exists. Skipping...
Folder 'GCA_019662555.1_PDT001110762.1' already exists. Skipping...
Folder 'GCA_019662605.1_PDT001110765.1' already exists. Skipping...
Folder 'GCA_019662645.1_PDT001110771.1' already exists. Skipping...
Folder 'GCA_019662655.1_PDT001110770.1' already exists. Skipping...
Folder 'GCA_019662705.1_PDT001110759.1' already exists. Skipping...
Folder 'GCA_019662825.1_PDT001110720.1' already exists. Skipping...
Folder 'GCA_019662885.1_PDT001110758.1' already exists. Skipping...
Folder 'GCA_019663185.1_PDT001110722.1' already exists. Skipping...
Folder 'GCA_019663195.1_PDT001110723.1' already exists. Skipping...
Folder 'GCA_019663245.1_PDT001110724.1' already exists. Skipping...
Folder 'GCA_019663425.1_PDT001110711.1' already exists. Skipping...
Folder 'GCA_019664285.1_PDT001110646.1' already exists. Skipping...
Folder 'GCA_019664685.1_PDT001110644.1' already exists. Skipping...
Folder 'GCA_019666785.1_PDT001110504.1' already exists. Skipping...
Folder 'GCA_019666825.1_PDT001110506.1' already exists. Skipping...
Folder 'GCA_019666905.1_PDT001110502.1' already exists. Skipping...
Folder 'GCA_019667045.1_PDT001110489.1' already exists. Skipping...
Folder 'GCA_019667065.1_PDT001110488.1' already exists. Skipping...
Folder 'GCA_019667165.1_PDT001110494.1' already exists. Skipping...
Folder 'GCA_019667225.1_PDT001110484.1' already exists. Skipping...
Folder 'GCA_019667285.1_PDT001110481.1' already exists. Skipping...
Folder 'GCA_019667425.1_PDT001110476.1' already exists. Skipping...
Folder 'GCA_019667465.1_PDT001110470.1' already exists. Skipping...
Folder 'GCA_019667765.1_PDT001110458.1' already exists. Skipping...
Folder 'GCA_019668725.1_PDT001110421.1' already exists. Skipping...
Folder 'GCA_019668785.1_PDT001110419.1' already exists. Skipping...
Folder 'GCA_019669425.1_PDT001110402.1' already exists. Skipping...
Folder 'GCA_019669605.1_PDT001110394.1' already exists. Skipping...
Folder 'GCA_019669625.1_PDT001110393.1' already exists. Skipping...
Folder 'GCA_019669705.1_PDT001110383.1' already exists. Skipping...
Folder 'GCA_019669725.1_PDT001110387.1' already exists. Skipping...
Folder 'GCA_019669745.1_PDT001110384.1' already exists. Skipping...
Folder 'GCA_019669805.1_PDT001110388.1' already exists. Skipping...
Folder 'GCA_019674105.1_PDT001110381.1' already exists. Skipping...
Folder 'GCA_019676835.1_PDT001110348.1' already exists. Skipping...
Folder 'GCA_019677065.1_PDT001110345.1' already exists. Skipping...
Folder 'GCA_019677105.1_PDT001110344.1' already exists. Skipping...
Folder 'GCA_019677135.1_PDT001110343.1' already exists. Skipping...
Folder 'GCA_019677185.1_PDT001110341.1' already exists. Skipping...
Folder 'GCA_019677425.1_PDT001110336.1' already exists. Skipping...
Folder 'GCA_019677445.1_PDT001110338.1' already exists. Skipping...
Folder 'GCA_019677535.1_PDT001110334.1' already exists. Skipping...
Folder 'GCA_019677625.1_PDT001110331.1' already exists. Skipping...
Folder 'GCA_019677785.1_PDT001110327.1' already exists. Skipping...
Folder 'GCA_019677815.1_PDT001110326.1' already exists. Skipping...
Folder 'GCA_019678275.1_PDT001110325.1' already exists. Skipping...
Folder 'GCA_019678315.1_PDT001110324.1' already exists. Skipping...
Folder 'GCA_019678855.1_PDT001110316.1' already exists. Skipping...
Folder 'GCA_019680375.1_PDT001110906.1' already exists. Skipping...
Folder 'GCA_019680415.1_PDT001110904.1' already exists. Skipping...
Folder 'GCA_019680435.1_PDT001110902.1' already exists. Skipping...
Folder 'GCA_019680455.1_PDT001110903.1' already exists. Skipping...
Folder 'GCA_019680475.1_PDT001110900.1' already exists. Skipping...
Folder 'GCA_019680495.1_PDT001110901.1' already exists. Skipping...
Folder 'GCA_019680515.1_PDT001110899.1' already exists. Skipping...
Folder 'GCA_019680535.1_PDT001110898.1' already exists. Skipping...
Folder 'GCA_019696325.1_PDT001110973.1' already exists. Skipping...
Folder 'GCA_019696405.1_PDT001110962.1' already exists. Skipping...
Folder 'GCA_019696465.1_PDT001110961.1' already exists. Skipping...
Folder 'GCA_019696485.1_PDT001110963.1' already exists. Skipping...
Folder 'GCA_019696525.1_PDT001110960.1' already exists. Skipping...
Folder 'GCA_019696985.1_PDT001113043.1' already exists. Skipping...
Folder 'GCA_019697065.1_PDT001113042.1' already exists. Skipping...
Folder 'GCA_019697085.1_PDT001113040.1' already exists. Skipping...
Folder 'GCA_019697105.1_PDT001113041.1' already exists. Skipping...
Folder 'GCA_019697855.1_PDT001113044.1' already exists. Skipping...
Folder 'GCA_019699945.1_PDT001113161.1' already exists. Skipping...
Folder 'GCA_019699955.1_PDT001113158.1' already exists. Skipping...
Folder 'GCA_019699985.1_PDT001113162.1' already exists. Skipping...
Folder 'GCA_019700005.1_PDT001113157.1' already exists. Skipping...
Folder 'GCA_019700025.1_PDT001113169.1' already exists. Skipping...
Folder 'GCA_019701345.1_PDT001113243.1' already exists. Skipping...
Folder 'GCA_019701605.1_PDT001113242.1' already exists. Skipping...
Folder 'GCA_019701645.1_PDT001113238.1' already exists. Skipping...
Folder 'GCA_019701655.1_PDT001113240.1' already exists. Skipping...
Folder 'GCA_019701705.1_PDT001113239.1' already exists. Skipping...
Folder 'GCA_019701725.1_PDT001113241.1' already exists. Skipping...
Folder 'GCA_019702575.1_PDT001113492.1' already exists. Skipping...
Folder 'GCA_019702595.1_PDT001113493.1' already exists. Skipping...
Folder 'GCA_019705975.1_PDT001113610.1' already exists. Skipping...
Folder 'GCA_019706135.1_PDT001113617.1' already exists. Skipping...
Folder 'GCA_019706175.1_PDT001113624.1' already exists. Skipping...
Folder 'GCA_019706215.1_PDT001113631.1' already exists. Skipping...
Folder 'GCA_019706255.1_PDT001113642.1' already exists. Skipping...
Folder 'GCA_019706295.1_PDT001113625.1' already exists. Skipping...
Folder 'GCA_019706515.1_PDT001113628.1' already exists. Skipping...
Folder 'GCA_019706595.1_PDT001113646.1' already exists. Skipping...
Folder 'GCA_019706635.1_PDT001113620.1' already exists. Skipping...
Folder 'GCA_019706795.1_PDT001113727.1' already exists. Skipping...
Folder 'GCA_019706915.1_PDT001113705.1' already exists. Skipping...
Folder 'GCA_019706955.1_PDT001113690.1' already exists. Skipping...
Folder 'GCA_019708455.1_PDT001113830.1' already exists. Skipping...
Folder 'GCA_019708515.1_PDT001113828.1' already exists. Skipping...
Folder 'GCA_019708815.1_PDT001113832.1' already exists. Skipping...
Folder 'GCA_019708855.1_PDT001113829.1' already exists. Skipping...
Folder 'GCA_019719655.1_PDT001113927.1' already exists. Skipping...
Folder 'GCA_019719675.1_PDT001113928.1' already exists. Skipping...
Folder 'GCA_019719695.1_PDT001113926.1' already exists. Skipping...
Folder 'GCA_019719755.1_PDT001113925.1' already exists. Skipping...
Folder 'GCA_019719775.1_PDT001113924.1' already exists. Skipping...
Folder 'GCA_019719795.1_PDT001113923.1' already exists. Skipping...
Folder 'GCA_019721235.1_PDT001114755.1' already exists. Skipping...
Folder 'GCA_019721255.1_PDT001114754.1' already exists. Skipping...
Folder 'GCA_019721295.1_PDT001114756.1' already exists. Skipping...
Folder 'GCA_019721375.1_PDT001109065.1' already exists. Skipping...
Folder 'GCA_019724315.1_PDT001115126.1' already exists. Skipping...
Folder 'GCA_019724455.1_PDT001115160.1' already exists. Skipping...
Folder 'GCA_019724475.1_PDT001115151.1' already exists. Skipping...
Folder 'GCA_019724495.1_PDT001115184.1' already exists. Skipping...
Folder 'GCA_019724515.1_PDT001115177.1' already exists. Skipping...
Folder 'GCA_019724575.1_PDT001115132.1' already exists. Skipping...
Folder 'GCA_019726995.1_PDT001115183.1' already exists. Skipping...
Folder 'GCA_019727475.1_PDT001115142.1' already exists. Skipping...
Folder 'GCA_019727695.1_PDT001115239.1' already exists. Skipping...
Folder 'GCA_019727815.1_PDT001115178.1' already exists. Skipping...
Folder 'GCA_019727835.1_PDT001115176.1' already exists. Skipping...
Folder 'GCA_019728295.1_PDT001115291.1' already exists. Skipping...
Folder 'GCA_019728475.1_PDT001115334.1' already exists. Skipping...
Folder 'GCA_019728575.1_PDT001115333.1' already exists. Skipping...
Folder 'GCA_019728595.1_PDT001115331.1' already exists. Skipping...
Folder 'GCA_019728615.1_PDT001115332.1' already exists. Skipping...
Folder 'GCA_019728955.1_PDT001115359.1' already exists. Skipping...
Folder 'GCA_019729755.1_PDT001115357.1' already exists. Skipping...
Folder 'GCA_019730955.1_PDT001115123.1' already exists. Skipping...
Folder 'GCA_019731215.1_PDT001115118.1' already exists. Skipping...
Folder 'GCA_019731235.1_PDT001115119.1' already exists. Skipping...
Folder 'GCA_019732755.1_PDT001115117.1' already exists. Skipping...
Folder 'GCA_019734655.1_ASM1973465v1' already exists. Skipping...
Folder 'GCA_019735055.1_PDT001115127.1' already exists. Skipping...
Folder 'GCA_019735075.1_PDT001115125.1' already exists. Skipping...
Folder 'GCA_019737235.1_PDT001115436.1' already exists. Skipping...
Folder 'GCA_019737275.1_PDT001115435.1' already exists. Skipping...
Folder 'GCA_019737295.1_PDT001115434.1' already exists. Skipping...
Folder 'GCA_019737315.1_PDT001115433.1' already exists. Skipping...
Folder 'GCA_019737335.1_PDT001115431.1' already exists. Skipping...
Folder 'GCA_019737375.1_PDT001115429.1' already exists. Skipping...
Folder 'GCA_019737415.1_PDT001115428.1' already exists. Skipping...
Folder 'GCA_019738795.1_PDT001115120.1' already exists. Skipping...
Folder 'GCA_019739155.1_PDT001113608.1' already exists. Skipping...
Folder 'GCA_019740235.1_PDT001115992.1' already exists. Skipping...
Folder 'GCA_019745085.1_PDT001116220.1' already exists. Skipping...
Folder 'GCA_019745115.1_PDT001116218.1' already exists. Skipping...
Folder 'GCA_019745135.1_PDT001116217.1' already exists. Skipping...
Folder 'GCA_019745215.1_PDT001116214.1' already exists. Skipping...
Folder 'GCA_019745235.1_PDT001116212.1' already exists. Skipping...
Folder 'GCA_019745255.1_PDT001116213.1' already exists. Skipping...
Folder 'GCA_019745285.1_PDT001116211.1' already exists. Skipping...
Folder 'GCA_019745335.1_PDT001116215.1' already exists. Skipping...
Folder 'GCA_019745435.1_PDT001116210.1' already exists. Skipping...
Folder 'GCA_019745465.1_PDT001116208.1' already exists. Skipping...
Folder 'GCA_019745655.1_PDT001116193.1' already exists. Skipping...
Folder 'GCA_019745665.1_PDT001116205.1' already exists. Skipping...
Folder 'GCA_019745695.1_PDT001116207.1' already exists. Skipping...
Folder 'GCA_019745715.1_PDT001116206.1' already exists. Skipping...
Folder 'GCA_019745945.1_PDT001116219.1' already exists. Skipping...
Folder 'GCA_019750965.1_PDT001116216.1' already exists. Skipping...
Folder 'GCA_019751065.1_PDT001116209.1' already exists. Skipping...
Folder 'GCA_019754535.1_PDT001116511.1' already exists. Skipping...
Folder 'GCA_019754555.1_PDT001116510.1' already exists. Skipping...
Folder 'GCA_019754575.1_PDT001116509.1' already exists. Skipping...
Folder 'GCA_019754595.1_PDT001116507.1' already exists. Skipping...
Folder 'GCA_019754615.1_PDT001116508.1' already exists. Skipping...
Folder 'GCA_019754635.1_PDT001116506.1' already exists. Skipping...
Folder 'GCA_019754655.1_PDT001116505.1' already exists. Skipping...
Folder 'GCA_019754675.1_PDT001116504.1' already exists. Skipping...
Folder 'GCA_019759355.1_PDT001116791.1' already exists. Skipping...
Folder 'GCA_019759435.1_PDT001116795.1' already exists. Skipping...
Folder 'GCA_019759455.1_PDT001116801.1' already exists. Skipping...
Folder 'GCA_019759515.1_PDT001116790.1' already exists. Skipping...
Folder 'GCA_019759555.1_PDT001116787.1' already exists. Skipping...
Folder 'GCA_019759575.1_PDT001116786.1' already exists. Skipping...
Folder 'GCA_019759595.1_PDT001116785.1' already exists. Skipping...
Folder 'GCA_019759835.1_PDT001116788.1' already exists. Skipping...
Folder 'GCA_019759875.1_PDT001116784.1' already exists. Skipping...
Folder 'GCA_019759935.1_PDT001116765.1' already exists. Skipping...
Folder 'GCA_019761015.1_PDT001116805.1' already exists. Skipping...
Folder 'GCA_019761035.1_PDT001116803.1' already exists. Skipping...
Folder 'GCA_019761215.1_PDT001116855.1' already exists. Skipping...
Folder 'GCA_019761235.1_PDT001116857.1' already exists. Skipping...
Folder 'GCA_019761275.1_PDT001116844.1' already exists. Skipping...
Folder 'GCA_019761305.1_PDT001116849.1' already exists. Skipping...
Folder 'GCA_019761355.1_PDT001116841.1' already exists. Skipping...
Folder 'GCA_019761375.1_PDT001116838.1' already exists. Skipping...
Folder 'GCA_019761675.1_PDT001116826.1' already exists. Skipping...
Folder 'GCA_019761715.1_PDT001116836.1' already exists. Skipping...
Folder 'GCA_019761745.1_PDT001116832.1' already exists. Skipping...
Folder 'GCA_019761775.1_PDT001116825.1' already exists. Skipping...
Folder 'GCA_019772245.1_PDT001116830.1' already exists. Skipping...
Folder 'GCA_019773835.1_PDT001116868.1' already exists. Skipping...
Folder 'GCA_019773855.1_PDT001116867.1' already exists. Skipping...
Folder 'GCA_019776305.1_PDT001117113.1' already exists. Skipping...
Folder 'GCA_019776325.1_PDT001117112.1' already exists. Skipping...
Folder 'GCA_019777705.1_PDT001117150.1' already exists. Skipping...
Folder 'GCA_019777745.1_PDT001117158.1' already exists. Skipping...
Folder 'GCA_019777765.1_PDT001117202.1' already exists. Skipping...
Folder 'GCA_019777805.1_PDT001117198.1' already exists. Skipping...
Folder 'GCA_019777825.1_PDT001117200.1' already exists. Skipping...
Folder 'GCA_019777845.1_PDT001117196.1' already exists. Skipping...
Folder 'GCA_019777875.1_PDT001117187.1' already exists. Skipping...
Folder 'GCA_019777925.1_PDT001117183.1' already exists. Skipping...
Folder 'GCA_019777985.1_PDT001117173.1' already exists. Skipping...
Folder 'GCA_019778325.1_PDT001117160.1' already exists. Skipping...
Folder 'GCA_019778385.1_PDT001117161.1' already exists. Skipping...
Folder 'GCA_019784265.1_PDT001117199.1' already exists. Skipping...
Folder 'GCA_019787465.1_PDT001117857.1' already exists. Skipping...
Folder 'GCA_019787485.1_PDT001117859.1' already exists. Skipping...
Folder 'GCA_019787705.1_PDT001117917.1' already exists. Skipping...
Folder 'GCA_019787725.1_PDT001117918.1' already exists. Skipping...
Folder 'GCA_019787745.1_PDT001117915.1' already exists. Skipping...
Folder 'GCA_019787765.1_PDT001117916.1' already exists. Skipping...
Folder 'GCA_019789575.1_PDT001118027.1' already exists. Skipping...
Folder 'GCA_019789615.1_PDT001118026.1' already exists. Skipping...
Folder 'GCA_019789655.1_PDT001118016.1' already exists. Skipping...
Folder 'GCA_019789695.1_PDT001118012.1' already exists. Skipping...
Folder 'GCA_019789715.1_PDT001118009.1' already exists. Skipping...
Folder 'GCA_019789755.1_PDT001118013.1' already exists. Skipping...
Folder 'GCA_019789795.1_PDT001118006.1' already exists. Skipping...
Folder 'GCA_019789855.1_PDT001118003.1' already exists. Skipping...
Folder 'GCA_019789895.1_PDT001117996.1' already exists. Skipping...
Folder 'GCA_019789955.1_PDT001117987.1' already exists. Skipping...
Folder 'GCA_019790015.1_PDT001117985.1' already exists. Skipping...
Folder 'GCA_019790075.1_PDT001117978.1' already exists. Skipping...
Folder 'GCA_019790115.1_PDT001117983.1' already exists. Skipping...
Folder 'GCA_019790715.1_PDT001118129.1' already exists. Skipping...
Folder 'GCA_019790775.1_PDT001118121.1' already exists. Skipping...
Folder 'GCA_019790795.1_PDT001118112.1' already exists. Skipping...
Folder 'GCA_019790815.1_PDT001118119.1' already exists. Skipping...
Folder 'GCA_019790855.1_PDT001118108.1' already exists. Skipping...
Folder 'GCA_019790875.1_PDT001118168.1' already exists. Skipping...
Folder 'GCA_019790895.1_PDT001118154.1' already exists. Skipping...
Folder 'GCA_019790915.1_PDT001118130.1' already exists. Skipping...
Folder 'GCA_019790935.1_PDT001118164.1' already exists. Skipping...
Folder 'GCA_019790955.1_PDT001118127.1' already exists. Skipping...
Folder 'GCA_019791135.1_PDT001118167.1' already exists. Skipping...
Folder 'GCA_019791215.1_PDT001118162.1' already exists. Skipping...
Folder 'GCA_019791235.1_PDT001118153.1' already exists. Skipping...
Folder 'GCA_019791255.1_PDT001118159.1' already exists. Skipping...
Folder 'GCA_019791275.1_PDT001118161.1' already exists. Skipping...
Folder 'GCA_019791295.1_PDT001118157.1' already exists. Skipping...
Folder 'GCA_019791305.1_PDT001118158.1' already exists. Skipping...
Folder 'GCA_019791355.1_PDT001118149.1' already exists. Skipping...
Folder 'GCA_019791375.1_PDT001118147.1' already exists. Skipping...
Folder 'GCA_019791395.1_PDT001118148.1' already exists. Skipping...
Folder 'GCA_019791415.1_PDT001118141.1' already exists. Skipping...
Folder 'GCA_019791435.1_PDT001118137.1' already exists. Skipping...
Folder 'GCA_019791455.1_PDT001118136.1' already exists. Skipping...
Folder 'GCA_019791475.1_PDT001118115.1' already exists. Skipping...
Folder 'GCA_019791495.1_PDT001118120.1' already exists. Skipping...
Folder 'GCA_019791515.1_PDT001118117.1' already exists. Skipping...
Folder 'GCA_019791535.1_PDT001118125.1' already exists. Skipping...

Retreiveing data: 80481it [00:13, 6641.39it/s]

Folder 'GCA_020396465.1_PDT001146896.1' already exists. Skipping...
Folder 'GCA_020396485.1_PDT001146926.1' already exists. Skipping...
Folder 'GCA_020396505.1_PDT001146927.1' already exists. Skipping...
Folder 'GCA_020396525.1_PDT001146899.1' already exists. Skipping...
Folder 'GCA_020396565.1_PDT001147323.1' already exists. Skipping...
Folder 'GCA_020399265.1_PDT001147574.1' already exists. Skipping...
Folder 'GCA_020399275.1_PDT001147569.1' already exists. Skipping...
Folder 'GCA_020399305.1_PDT001147571.1' already exists. Skipping...
Folder 'GCA_020399325.1_PDT001147572.1' already exists. Skipping...
Folder 'GCA_020399365.1_PDT001147567.1' already exists. Skipping...
Folder 'GCA_020399375.1_PDT001147330.1' already exists. Skipping...
Folder 'GCA_020399405.1_PDT001147561.1' already exists. Skipping...
Folder 'GCA_020399425.1_PDT001147573.1' already exists. Skipping...
Folder 'GCA_020399465.1_PDT001147473.1' already exists. Skipping...
Folder 'GCA_020399485.1_PDT001147466.1' already exists. Skipping...
Folder 'GCA_020399505.1_PDT001147546.1' already exists. Skipping...
Folder 'GCA_020399525.1_PDT001147543.1' already exists. Skipping...
Folder 'GCA_020399545.1_PDT001147341.1' already exists. Skipping...
Folder 'GCA_020399565.1_PDT001147547.1' already exists. Skipping...
Folder 'GCA_020399585.1_PDT001147335.1' already exists. Skipping...
Folder 'GCA_020399605.1_PDT001147527.1' already exists. Skipping...
Folder 'GCA_020399625.1_PDT001147478.1' already exists. Skipping...
Folder 'GCA_020399645.1_PDT001147482.1' already exists. Skipping...
Folder 'GCA_020399665.1_PDT001147489.1' already exists. Skipping...
Folder 'GCA_020399705.1_PDT001147471.1' already exists. Skipping...
Folder 'GCA_020410465.1_PDT001147903.1' already exists. Skipping...
Folder 'GCA_020410485.1_PDT001147901.1' already exists. Skipping...
Folder 'GCA_020410505.1_PDT001147902.1' already exists. Skipping...
Folder 'GCA_020410545.1_PDT001147904.1' already exists. Skipping...
Folder 'GCA_020411145.1_PDT000641965.2' already exists. Skipping...
Folder 'GCA_020411205.1_PDT000708237.2' already exists. Skipping...
Folder 'GCA_020411225.1_PDT000651943.2' already exists. Skipping...
Folder 'GCA_020411265.1_PDT000643454.2' already exists. Skipping...
Folder 'GCA_020412125.1_PDT001147806.1' already exists. Skipping...
Folder 'GCA_020412165.1_PDT001147807.1' already exists. Skipping...
Folder 'GCA_020413785.1_PDT001147719.1' already exists. Skipping...
Folder 'GCA_020413845.1_PDT001147706.1' already exists. Skipping...
Folder 'GCA_020413865.1_PDT001147713.1' already exists. Skipping...
Folder 'GCA_020413885.1_PDT001147705.1' already exists. Skipping...
Folder 'GCA_020413965.1_PDT001147698.1' already exists. Skipping...
Folder 'GCA_020414025.1_PDT001147701.1' already exists. Skipping...
Folder 'GCA_020414045.1_PDT001147693.1' already exists. Skipping...
Folder 'GCA_020414125.1_PDT001147682.1' already exists. Skipping...
Folder 'GCA_020414145.1_PDT001147681.1' already exists. Skipping...
Folder 'GCA_020414205.1_PDT001147677.1' already exists. Skipping...
Folder 'GCA_020414285.1_PDT001147674.1' already exists. Skipping...
Folder 'GCA_020414345.1_PDT001147668.1' already exists. Skipping...
Folder 'GCA_020414405.1_PDT001147662.1' already exists. Skipping...
Folder 'GCA_020414505.1_PDT001147667.1' already exists. Skipping...
Folder 'GCA_020414525.1_PDT001147666.1' already exists. Skipping...
Folder 'GCA_020414785.1_PDT001147646.1' already exists. Skipping...
Folder 'GCA_020414805.1_PDT001147647.1' already exists. Skipping...
Folder 'GCA_020424405.1_PDT001148583.1' already exists. Skipping...
Folder 'GCA_020427025.1_PDT001148671.1' already exists. Skipping...
Folder 'GCA_020427045.1_PDT001148670.1' already exists. Skipping...
Folder 'GCA_020431005.1_PDT001148611.1' already exists. Skipping...
Folder 'GCA_020437405.1_PDT001148582.1' already exists. Skipping...
Folder 'GCA_020437525.1_PDT001148581.1' already exists. Skipping...
Folder 'GCA_020452285.1_PDT001149499.1' already exists. Skipping...
Folder 'GCA_020452305.1_PDT001149500.1' already exists. Skipping...
Folder 'GCA_020458205.1_PDT001149308.1' already exists. Skipping...
Folder 'GCA_020468605.1_PDT001148672.1' already exists. Skipping...
Folder 'GCA_020469465.1_PDT000655790.2' already exists. Skipping...
Folder 'GCA_020470225.1_PDT001126262.1' already exists. Skipping...
Folder 'GCA_020470325.1_PDT001129397.1' already exists. Skipping...
Folder 'GCA_020470845.1_PDT001110298.1' already exists. Skipping...
Folder 'GCA_020471685.1_PDT001077914.1' already exists. Skipping...
Folder 'GCA_020471885.1_PDT001068910.1' already exists. Skipping...
Folder 'GCA_020471905.1_PDT001068919.1' already exists. Skipping...
Folder 'GCA_020472325.1_PDT001058777.1' already exists. Skipping...
Folder 'GCA_020472705.1_PDT001046695.1' already exists. Skipping...
Folder 'GCA_020472885.1_PDT001044921.1' already exists. Skipping...
Folder 'GCA_020482055.1_PDT001150368.1' already exists. Skipping...
Folder 'GCA_020486885.1_PDT001150392.1' already exists. Skipping...
Folder 'GCA_020486985.1_PDT001150391.1' already exists. Skipping...
Folder 'GCA_020487045.1_PDT001150389.1' already exists. Skipping...
Folder 'GCA_020487285.1_PDT001150418.1' already exists. Skipping...
Folder 'GCA_020488545.1_PDT001150444.1' already exists. Skipping...
Folder 'GCA_020488605.1_PDT001150445.1' already exists. Skipping...
Folder 'GCA_020488925.1_PDT001150390.1' already exists. Skipping...
Folder 'GCA_020489485.1_PDT001150607.1' already exists. Skipping...
Folder 'GCA_020494035.1_PDT001150485.1' already exists. Skipping...
Folder 'GCA_020497245.1_PDT001150722.1' already exists. Skipping...
Folder 'GCA_020497265.1_PDT001150718.1' already exists. Skipping...
Folder 'GCA_020497325.1_PDT001150714.1' already exists. Skipping...
Folder 'GCA_020497365.1_PDT001150717.1' already exists. Skipping...
Folder 'GCA_020497385.1_PDT001150715.1' already exists. Skipping...
Folder 'GCA_020497405.1_PDT001150716.1' already exists. Skipping...
Folder 'GCA_020497445.1_PDT001150711.1' already exists. Skipping...
Folder 'GCA_020497505.1_PDT001150709.1' already exists. Skipping...
Folder 'GCA_020498125.1_PDT001150721.1' already exists. Skipping...
Folder 'GCA_020504045.1_PDT001151209.1' already exists. Skipping...
Folder 'GCA_020504345.1_PDT001151196.1' already exists. Skipping...
Folder 'GCA_020505245.1_PDT001151122.1' already exists. Skipping...
Folder 'GCA_020506385.1_PDT001151059.1' already exists. Skipping...
Folder 'GCA_020506585.1_PDT001151058.1' already exists. Skipping...
Folder 'GCA_020506625.1_PDT001151057.1' already exists. Skipping...
Folder 'GCA_020506645.1_PDT001151056.1' already exists. Skipping...
Folder 'GCA_020507825.1_PDT001150985.1' already exists. Skipping...
Folder 'GCA_020507865.1_PDT001150967.1' already exists. Skipping...
Folder 'GCA_020507875.1_PDT001150971.1' already exists. Skipping...
Folder 'GCA_020507965.1_PDT001150979.1' already exists. Skipping...
Folder 'GCA_020507985.1_PDT001150982.1' already exists. Skipping...
Folder 'GCA_020508025.1_PDT001150973.1' already exists. Skipping...
Folder 'GCA_020508065.1_PDT001150970.1' already exists. Skipping...
Folder 'GCA_020508085.1_PDT001150965.1' already exists. Skipping...
Folder 'GCA_020508125.1_PDT001150963.1' already exists. Skipping...
Folder 'GCA_020508865.1_PDT001150932.1' already exists. Skipping...
Folder 'GCA_020508885.1_PDT001150933.1' already exists. Skipping...
Folder 'GCA_020510305.1_PDT001151500.1' already exists. Skipping...
Folder 'GCA_020510325.1_PDT001151496.1' already exists. Skipping...
Folder 'GCA_020510345.1_PDT001151497.1' already exists. Skipping...
Folder 'GCA_020510365.1_PDT001151495.1' already exists. Skipping...
Folder 'GCA_020510385.1_PDT001151494.1' already exists. Skipping...
Folder 'GCA_020511515.1_PDT001151537.1' already exists. Skipping...
Folder 'GCA_020511655.1_PDT001151534.1' already exists. Skipping...
Folder 'GCA_020511795.1_PDT001151573.1' already exists. Skipping...
Folder 'GCA_020512275.1_PDT001151593.1' already exists. Skipping...
Folder 'GCA_020516585.1_PDT001154165.1' already exists. Skipping...
Folder 'GCA_020516605.1_PDT001154166.1' already exists. Skipping...
Folder 'GCA_020516725.1_PDT001154163.1' already exists. Skipping...
Folder 'GCA_020516745.1_PDT001154162.1' already exists. Skipping...
Folder 'GCA_020516765.1_PDT001154161.1' already exists. Skipping...
Folder 'GCA_020516825.1_PDT001154156.1' already exists. Skipping...
Folder 'GCA_020516835.1_PDT001154157.1' already exists. Skipping...
Folder 'GCA_020516865.1_PDT001154158.1' already exists. Skipping...
Folder 'GCA_020516885.1_PDT001154154.1' already exists. Skipping...
Folder 'GCA_020516925.1_PDT001154152.1' already exists. Skipping...
Folder 'GCA_020516945.1_PDT001154151.1' already exists. Skipping...
Folder 'GCA_020516985.1_PDT001154150.1' already exists. Skipping...
Folder 'GCA_020517065.1_PDT001154146.1' already exists. Skipping...
Folder 'GCA_020517085.1_PDT001154147.1' already exists. Skipping...
Folder 'GCA_020517105.1_PDT001154143.1' already exists. Skipping...
Folder 'GCA_020517125.1_PDT001154142.1' already exists. Skipping...
Folder 'GCA_020517145.1_PDT001154140.1' already exists. Skipping...
Folder 'GCA_020517165.1_PDT001154148.1' already exists. Skipping...
Folder 'GCA_020517205.1_PDT001154141.1' already exists. Skipping...
Folder 'GCA_020517325.1_PDT001154130.1' already exists. Skipping...
Folder 'GCA_020517345.1_PDT001154131.1' already exists. Skipping...
Folder 'GCA_020517365.1_PDT001154134.1' already exists. Skipping...
Folder 'GCA_020517385.1_PDT001154136.1' already exists. Skipping...
Folder 'GCA_020517405.1_PDT001154133.1' already exists. Skipping...
Folder 'GCA_020517445.1_PDT001154127.1' already exists. Skipping...
Folder 'GCA_020517465.1_PDT001154125.1' already exists. Skipping...
Folder 'GCA_020517485.1_PDT001154126.1' already exists. Skipping...
Folder 'GCA_020522405.1_PDT001126260.1' already exists. Skipping...
Folder 'GCA_020532905.2_PDT001156791.4' already exists. Skipping...
Folder 'GCA_020532925.2_PDT001156790.3' already exists. Skipping...
Folder 'GCA_020533025.2_PDT001156785.3' already exists. Skipping...
Folder 'GCA_020533125.2_PDT001156723.3' already exists. Skipping...
Folder 'GCA_020533225.2_PDT001156713.3' already exists. Skipping...
Folder 'GCA_020533285.2_PDT001156712.3' already exists. Skipping...
Folder 'GCA_020533305.2_PDT001156711.3' already exists. Skipping...
Folder 'GCA_020533325.2_PDT001156709.3' already exists. Skipping...
Folder 'GCA_020533345.1_PDT001156698.1' already exists. Skipping...
Folder 'GCA_020533545.1_PDT001156688.1' already exists. Skipping...
Folder 'GCA_020533585.1_PDT001156687.1' already exists. Skipping...
Folder 'GCA_020533665.2_PDT001156792.4' already exists. Skipping...
Folder 'GCA_020533745.1_PDT001156690.1' already exists. Skipping...
Folder 'GCA_020533765.1_PDT001156686.1' already exists. Skipping...
Folder 'GCA_020533785.1_PDT001156682.1' already exists. Skipping...
Folder 'GCA_020533805.1_PDT001156681.1' already exists. Skipping...
Folder 'GCA_020534005.1_PDT001156673.1' already exists. Skipping...
Folder 'GCA_020534085.1_PDT001156668.1' already exists. Skipping...
Folder 'GCA_020534645.2_PDT001156732.5' already exists. Skipping...
Folder 'GCA_020534805.2_PDT001156815.4' already exists. Skipping...
Folder 'GCA_020534825.2_PDT001156856.4' already exists. Skipping...
Folder 'GCA_020534905.2_PDT001156814.4' already exists. Skipping...
Folder 'GCA_020534985.2_PDT001156809.4' already exists. Skipping...
Folder 'GCA_020535005.2_PDT001156808.4' already exists. Skipping...
Folder 'GCA_020535265.2_PDT001156842.6' already exists. Skipping...
Folder 'GCA_020535285.2_PDT001156799.5' already exists. Skipping...
Folder 'GCA_020535365.2_PDT001156738.7' already exists. Skipping...
Folder 'GCA_020536255.2_PDT001156722.4' already exists. Skipping...
Folder 'GCA_020536695.2_PDT001156762.8' already exists. Skipping...
Folder 'GCA_020536715.2_PDT001156758.8' already exists. Skipping...
Folder 'GCA_020536735.2_PDT001156755.9' already exists. Skipping...
Folder 'GCA_020536755.2_PDT001156757.8' already exists. Skipping...
Folder 'GCA_020536775.2_PDT001156752.9' already exists. Skipping...
Folder 'GCA_020536805.2_PDT001156753.9' already exists. Skipping...
Folder 'GCA_020536835.2_PDT001156751.9' already exists. Skipping...
Folder 'GCA_020536875.2_PDT001156800.6' already exists. Skipping...
Folder 'GCA_020540885.2_PDT001156775.10' already exists. Skipping...
Folder 'GCA_020543065.1_PDT001157399.6' already exists. Skipping...
Folder 'GCA_020545825.1_PDT001157870.4' already exists. Skipping...
Folder 'GCA_020549865.1_PDT001156978.8' already exists. Skipping...
Folder 'GCA_020550825.1_PDT001158245.1' already exists. Skipping...
Folder 'GCA_020550885.1_PDT001158228.2' already exists. Skipping...
Folder 'GCA_020550905.1_PDT001158227.2' already exists. Skipping...
Folder 'GCA_020551125.1_PDT001157865.3' already exists. Skipping...
Folder 'GCA_020551185.1_PDT001157860.2' already exists. Skipping...
Folder 'GCA_020551345.1_PDT001157423.3' already exists. Skipping...
Folder 'GCA_020551505.1_PDT001157875.4' already exists. Skipping...
Folder 'GCA_020552925.1_PDT001156975.7' already exists. Skipping...
Folder 'GCA_020552945.1_PDT001156985.7' already exists. Skipping...
Folder 'GCA_020552985.1_PDT001156982.7' already exists. Skipping...
Folder 'GCA_020553005.1_PDT001156986.6' already exists. Skipping...
Folder 'GCA_020553105.1_PDT001156773.9' already exists. Skipping...
Folder 'GCA_020553195.1_PDT001156830.5' already exists. Skipping...
Folder 'GCA_020553375.1_PDT001156819.5' already exists. Skipping...
Folder 'GCA_020553425.1_PDT001156825.5' already exists. Skipping...
Folder 'GCA_020553565.1_PDT001156882.4' already exists. Skipping...
Folder 'GCA_020553875.1_PDT001157866.3' already exists. Skipping...
Folder 'GCA_020553945.1_PDT001157868.3' already exists. Skipping...
Folder 'GCA_020554425.1_PDT001157398.6' already exists. Skipping...
Folder 'GCA_020555145.1_PDT001156835.6' already exists. Skipping...
Folder 'GCA_020555165.1_PDT001156771.8' already exists. Skipping...
Folder 'GCA_020555245.1_PDT001156980.8' already exists. Skipping...
Folder 'GCA_020555285.1_PDT001156781.10' already exists. Skipping...
Folder 'GCA_020555375.1_PDT001156826.5' already exists. Skipping...
Folder 'GCA_020555395.1_PDT001156765.8' already exists. Skipping...
Folder 'GCA_020555455.1_PDT001156756.8' already exists. Skipping...
Folder 'GCA_020555465.1_PDT001156746.6' already exists. Skipping...
Folder 'GCA_020555765.1_PDT001156959.5' already exists. Skipping...
Folder 'GCA_020555845.1_PDT001156735.7' already exists. Skipping...
Folder 'GCA_020555875.1_PDT001156964.5' already exists. Skipping...
Folder 'GCA_020556085.1_PDT001158225.2' already exists. Skipping...
Folder 'GCA_020556235.1_PDT001157867.3' already exists. Skipping...
Folder 'GCA_020556285.1_PDT001157873.4' already exists. Skipping...
Folder 'GCA_020556515.1_PDT001157877.4' already exists. Skipping...
Folder 'GCA_020556685.1_PDT001157857.3' already exists. Skipping...
Folder 'GCA_020556785.1_PDT001157858.3' already exists. Skipping...
Folder 'GCA_020558695.1_PDT001157424.4' already exists. Skipping...
Folder 'GCA_020558735.1_PDT001157427.4' already exists. Skipping...
Folder 'GCA_020560125.1_PDT001157401.6' already exists. Skipping...
Folder 'GCA_020560365.1_PDT001156778.10' already exists. Skipping...
Folder 'GCA_020560395.1_PDT001156971.5' already exists. Skipping...
Folder 'GCA_020560455.1_PDT001156983.7' already exists. Skipping...
Folder 'GCA_020560525.1_PDT001156981.7' already exists. Skipping...
Folder 'GCA_020560585.1_PDT001156845.6' already exists. Skipping...
Folder 'GCA_020560905.1_PDT001156759.7' already exists. Skipping...
Folder 'GCA_020561285.1_PDT001157400.6' already exists. Skipping...
Folder 'GCA_020561505.1_PDT001156984.7' already exists. Skipping...
Folder 'GCA_020561635.1_PDT001156973.5' already exists. Skipping...
Folder 'GCA_020561655.1_PDT001156776.10' already exists. Skipping...
Folder 'GCA_020561715.1_PDT001156750.8' already exists. Skipping...
Folder 'GCA_020561805.1_PDT001156972.5' already exists. Skipping...
Folder 'GCA_020561825.1_PDT001156848.6' already exists. Skipping...
Folder 'GCA_020561945.1_PDT001156960.5' already exists. Skipping...
Folder 'GCA_020561995.1_PDT001156747.7' already exists. Skipping...
Folder 'GCA_020562005.1_PDT001156744.5' already exists. Skipping...
Folder 'GCA_020562045.1_PDT001156742.6' already exists. Skipping...
Folder 'GCA_020562625.1_PDT001156763.8' already exists. Skipping...
Folder 'GCA_020562795.1_PDT001157425.4' already exists. Skipping...
Folder 'GCA_020562835.1_PDT001156868.6' already exists. Skipping...
Folder 'GCA_020564065.1_PDT001156968.4' already exists. Skipping...
Folder 'GCA_020564135.1_PDT001156818.5' already exists. Skipping...
Folder 'GCA_020564275.1_PDT001156737.7' already exists. Skipping...
Folder 'GCA_020565005.1_PDT001156974.5' already exists. Skipping...
Folder 'GCA_020565435.1_PDT001156913.6' already exists. Skipping...
Folder 'GCA_020565515.1_PDT001156846.6' already exists. Skipping...
Folder 'GCA_020566815.1_PDT001156736.7' already exists. Skipping...
Folder 'GCA_020566875.1_PDT001156769.8' already exists. Skipping...
Folder 'GCA_020569035.1_PDT001157013.4' already exists. Skipping...
Folder 'GCA_020570225.1_PDT001159443.1' already exists. Skipping...
Folder 'GCA_020581415.1_PDT001158092.4' already exists. Skipping...
Folder 'GCA_020581855.1_PDT001157978.3' already exists. Skipping...
Folder 'GCA_020581875.1_PDT001157977.4' already exists. Skipping...
Folder 'GCA_020581895.1_PDT001157976.4' already exists. Skipping...
Folder 'GCA_020581915.1_PDT001157975.4' already exists. Skipping...
Folder 'GCA_020581935.1_PDT001157974.4' already exists. Skipping...
Folder 'GCA_020581945.1_PDT001157972.4' already exists. Skipping...
Folder 'GCA_020581995.1_PDT001157973.4' already exists. Skipping...
Folder 'GCA_020582115.1_PDT001157970.4' already exists. Skipping...
Folder 'GCA_020582135.1_PDT001157971.4' already exists. Skipping...
Folder 'GCA_020584155.1_PDT001158168.2' already exists. Skipping...
Folder 'GCA_020586895.1_PDT001159528.1' already exists. Skipping...
Folder 'GCA_020595075.1_PDT001159809.1' already exists. Skipping...
Folder 'GCA_020595145.1_PDT001159806.1' already exists. Skipping...
Folder 'GCA_020595215.1_PDT001159808.1' already exists. Skipping...
Folder 'GCA_020595495.1_PDT001159810.1' already exists. Skipping...
Folder 'GCA_020595515.1_PDT001159811.1' already exists. Skipping...
Folder 'GCA_020596295.1_PDT001159812.1' already exists. Skipping...
Folder 'GCA_020596435.1_PDT001159807.1' already exists. Skipping...
Folder 'GCA_020596455.1_PDT001159817.1' already exists. Skipping...
Folder 'GCA_020596475.1_PDT001159816.1' already exists. Skipping...
Folder 'GCA_020596895.1_PDT001159825.1' already exists. Skipping...
Folder 'GCA_020596915.1_PDT001159823.1' already exists. Skipping...
Folder 'GCA_020596935.1_PDT001159824.1' already exists. Skipping...
Folder 'GCA_020596955.1_PDT001159815.1' already exists. Skipping...
Folder 'GCA_020596975.1_PDT001159818.1' already exists. Skipping...
Folder 'GCA_020598135.1_PDT001160581.1' already exists. Skipping...
Folder 'GCA_020598155.1_PDT001160579.1' already exists. Skipping...
Folder 'GCA_020598175.1_PDT001160549.1' already exists. Skipping...
Folder 'GCA_020598195.1_PDT001160500.1' already exists. Skipping...
Folder 'GCA_020598255.1_PDT001160569.1' already exists. Skipping...
Folder 'GCA_020598275.1_PDT001160714.1' already exists. Skipping...
Folder 'GCA_020598295.1_PDT001160552.1' already exists. Skipping...
Folder 'GCA_020598315.1_PDT001160651.1' already exists. Skipping...
Folder 'GCA_020598415.1_PDT001160641.1' already exists. Skipping...
Folder 'GCA_020598435.1_PDT001160634.1' already exists. Skipping...
Folder 'GCA_020598515.1_PDT001160647.1' already exists. Skipping...
Folder 'GCA_020598575.1_PDT001160630.1' already exists. Skipping...
Folder 'GCA_020598615.1_PDT001160628.1' already exists. Skipping...

Retreiveing data: 81802it [00:13, 6468.29it/s]

Folder 'GCA_021225295.1_PDT001205429.1' already exists. Skipping...
Folder 'GCA_021225395.1_PDT001205421.1' already exists. Skipping...
Folder 'GCA_021225415.1_PDT001205420.1' already exists. Skipping...
Folder 'GCA_021225455.1_PDT001205419.1' already exists. Skipping...
Folder 'GCA_021225475.1_PDT001205425.1' already exists. Skipping...
Folder 'GCA_021225515.1_PDT001205426.1' already exists. Skipping...
Folder 'GCA_021225575.1_PDT001205415.1' already exists. Skipping...
Folder 'GCA_021225595.1_PDT001205417.1' already exists. Skipping...
Folder 'GCA_021225655.1_PDT001205412.1' already exists. Skipping...
Folder 'GCA_021225675.1_PDT001205411.1' already exists. Skipping...
Folder 'GCA_021225855.1_PDT001205410.1' already exists. Skipping...
Folder 'GCA_021226395.1_PDT001205462.1' already exists. Skipping...
Folder 'GCA_021227515.1_PDT001205350.1' already exists. Skipping...
Folder 'GCA_021227535.1_PDT001205330.1' already exists. Skipping...
Folder 'GCA_021227555.1_PDT001205331.1' already exists. Skipping...
Folder 'GCA_021227575.1_PDT001205334.1' already exists. Skipping...
Folder 'GCA_021227595.1_PDT001205328.1' already exists. Skipping...
Folder 'GCA_021227615.1_PDT001205364.1' already exists. Skipping...
Folder 'GCA_021227955.1_PDT001205430.1' already exists. Skipping...
Folder 'GCA_021230175.1_PDT001206473.1' already exists. Skipping...
Folder 'GCA_021230265.1_PDT001206450.1' already exists. Skipping...
Folder 'GCA_021230315.1_PDT001206452.1' already exists. Skipping...
Folder 'GCA_021230335.1_PDT001206460.1' already exists. Skipping...
Folder 'GCA_021230375.1_PDT001206459.1' already exists. Skipping...
Folder 'GCA_021230435.1_PDT001205918.1' already exists. Skipping...
Folder 'GCA_021230455.1_PDT001205919.1' already exists. Skipping...
Folder 'GCA_021230475.1_PDT001205917.1' already exists. Skipping...
Folder 'GCA_021230535.1_PDT001206467.1' already exists. Skipping...
Folder 'GCA_021230555.1_PDT001206462.1' already exists. Skipping...
Folder 'GCA_021230575.1_PDT001206468.1' already exists. Skipping...
Folder 'GCA_021230615.1_PDT001206465.1' already exists. Skipping...
Folder 'GCA_021230685.1_PDT001206470.1' already exists. Skipping...
Folder 'GCA_021230715.1_PDT001206466.1' already exists. Skipping...
Folder 'GCA_021230915.1_PDT001206443.1' already exists. Skipping...
Folder 'GCA_021232485.1_PDT001205540.1' already exists. Skipping...
Folder 'GCA_021232675.1_PDT001205781.1' already exists. Skipping...
Folder 'GCA_021237845.1_PDT001207299.1' already exists. Skipping...
Folder 'GCA_021238105.1_PDT001207316.1' already exists. Skipping...
Folder 'GCA_021238185.1_PDT001207309.1' already exists. Skipping...
Folder 'GCA_021238205.1_PDT001207333.1' already exists. Skipping...
Folder 'GCA_021238245.1_PDT001207324.1' already exists. Skipping...
Folder 'GCA_021238485.2_PDT001207211.2' already exists. Skipping...
Folder 'GCA_021238765.1_PDT001207322.1' already exists. Skipping...
Folder 'GCA_021238805.1_PDT001207325.1' already exists. Skipping...
Folder 'GCA_021239705.1_PDT001207317.1' already exists. Skipping...
Folder 'GCA_021239745.1_PDT001207302.1' already exists. Skipping...
Folder 'GCA_021241965.1_PDT001207311.1' already exists. Skipping...
Folder 'GCA_021244285.1_PDT001207773.1' already exists. Skipping...
Folder 'GCA_021244305.1_PDT001207774.1' already exists. Skipping...
Folder 'GCA_021244365.1_PDT001207818.1' already exists. Skipping...
Folder 'GCA_021244425.1_PDT001207769.1' already exists. Skipping...
Folder 'GCA_021245165.1_PDT001207924.1' already exists. Skipping...
Folder 'GCA_021245465.1_PDT001207939.1' already exists. Skipping...
Folder 'GCA_021246765.1_PDT001207935.1' already exists. Skipping...
Folder 'GCA_021247765.1_PDT001207334.1' already exists. Skipping...
Folder 'GCA_021260205.1_PDT001208986.1' already exists. Skipping...
Folder 'GCA_021260225.1_PDT001208985.1' already exists. Skipping...
Folder 'GCA_021267465.1_PDT001208983.1' already exists. Skipping...
Folder 'GCA_021267605.1_PDT001208984.1' already exists. Skipping...
Folder 'GCA_021268085.1_PDT001209036.1' already exists. Skipping...
Folder 'GCA_021270845.1_PDT001210361.1' already exists. Skipping...
Folder 'GCA_021270865.1_PDT001210369.1' already exists. Skipping...
Folder 'GCA_021270885.1_PDT001210301.1' already exists. Skipping...
Folder 'GCA_021279085.1_PDT001210979.1' already exists. Skipping...
Folder 'GCA_021279125.1_PDT001210983.1' already exists. Skipping...
Folder 'GCA_021279145.1_PDT001210982.1' already exists. Skipping...
Folder 'GCA_021279165.1_PDT001210981.1' already exists. Skipping...
Folder 'GCA_021279185.1_PDT001210978.1' already exists. Skipping...
Folder 'GCA_021279285.1_PDT001211021.1' already exists. Skipping...
Folder 'GCA_021291065.1_PDT001212249.1' already exists. Skipping...
Folder 'GCA_021291105.1_PDT001212247.1' already exists. Skipping...
Folder 'GCA_021291125.1_PDT001212246.1' already exists. Skipping...
Folder 'GCA_021291145.1_PDT001212248.1' already exists. Skipping...
Folder 'GCA_021291845.1_PDT001212294.1' already exists. Skipping...
Folder 'GCA_021291865.1_PDT001212295.1' already exists. Skipping...
Folder 'GCA_021291885.1_PDT001212263.1' already exists. Skipping...
Folder 'GCA_021291925.1_PDT001212261.1' already exists. Skipping...
Folder 'GCA_021291945.1_PDT001212260.1' already exists. Skipping...
Folder 'GCA_021301495.1_PDT001212350.1' already exists. Skipping...
Folder 'GCA_021303495.1_PDT001212498.1' already exists. Skipping...
Folder 'GCA_021304395.1_PDT001212580.1' already exists. Skipping...
Folder 'GCA_021304415.1_PDT001212581.1' already exists. Skipping...
Folder 'GCA_021304455.1_PDT001212592.1' already exists. Skipping...
Folder 'GCA_021304495.1_PDT001212578.1' already exists. Skipping...
Folder 'GCA_021304575.1_PDT001212575.1' already exists. Skipping...
Folder 'GCA_021304795.1_PDT001212569.1' already exists. Skipping...
Folder 'GCA_021304815.1_PDT001212572.1' already exists. Skipping...
Folder 'GCA_021306495.1_PDT001212590.1' already exists. Skipping...
Folder 'GCA_021306535.1_PDT001212589.1' already exists. Skipping...
Folder 'GCA_021306595.1_PDT001212588.1' already exists. Skipping...
Folder 'GCA_021306655.1_PDT001212584.1' already exists. Skipping...
Folder 'GCA_021307415.1_PDT001212598.1' already exists. Skipping...
Folder 'GCA_021307945.1_PDT001212843.1' already exists. Skipping...
Folder 'GCA_021307965.1_PDT001212839.1' already exists. Skipping...
Folder 'GCA_021307985.1_PDT001212841.1' already exists. Skipping...
Folder 'GCA_021308025.1_PDT001212837.1' already exists. Skipping...
Folder 'GCA_021308045.1_PDT001212834.1' already exists. Skipping...
Folder 'GCA_021308085.1_PDT001212836.1' already exists. Skipping...
Folder 'GCA_021308105.1_PDT001212831.1' already exists. Skipping...
Folder 'GCA_021308125.1_PDT001212832.1' already exists. Skipping...
Folder 'GCA_021308215.1_PDT001212838.1' already exists. Skipping...
Folder 'GCA_021308235.1_PDT001212830.1' already exists. Skipping...
Folder 'GCA_021308315.1_PDT001212835.1' already exists. Skipping...
Folder 'GCA_021308355.1_PDT001212845.1' already exists. Skipping...
Folder 'GCA_021308815.1_PDT001212849.1' already exists. Skipping...
Folder 'GCA_021309395.1_PDT001212871.1' already exists. Skipping...
Folder 'GCA_021309435.1_PDT001212870.1' already exists. Skipping...
Folder 'GCA_021320175.1_PDT001213932.1' already exists. Skipping...
Folder 'GCA_021320295.1_PDT001213929.1' already exists. Skipping...
Folder 'GCA_021320615.1_PDT001213957.1' already exists. Skipping...
Folder 'GCA_021321155.1_PDT001213950.1' already exists. Skipping...
Folder 'GCA_021326935.1_PDT001213938.1' already exists. Skipping...
Folder 'GCA_021326955.1_PDT001213945.1' already exists. Skipping...
Folder 'GCA_021326985.1_PDT001213944.1' already exists. Skipping...
Folder 'GCA_021327025.1_PDT001213927.1' already exists. Skipping...
Folder 'GCA_021330555.1_PDT001213943.1' already exists. Skipping...
Folder 'GCA_021330675.1_PDT001213933.1' already exists. Skipping...
Folder 'GCA_021330695.1_PDT001213935.1' already exists. Skipping...
Folder 'GCA_021330755.1_PDT001213947.1' already exists. Skipping...
Folder 'GCA_021336335.1_PDT001214047.1' already exists. Skipping...
Folder 'GCA_021336615.1_PDT001214321.1' already exists. Skipping...
Folder 'GCA_021339375.1_PDT001214252.1' already exists. Skipping...
Folder 'GCA_021342055.1_ASM2134205v1' already exists. Skipping...
Folder 'GCA_021346945.1_PDT001215186.1' already exists. Skipping...
Folder 'GCA_021347005.1_PDT001215184.1' already exists. Skipping...
Folder 'GCA_021347025.1_PDT001215182.1' already exists. Skipping...
Folder 'GCA_021347065.1_PDT001215183.1' already exists. Skipping...
Folder 'GCA_021347085.1_PDT001215185.1' already exists. Skipping...
Folder 'GCA_021347105.1_PDT001215162.1' already exists. Skipping...
Folder 'GCA_021347125.1_PDT001215173.1' already exists. Skipping...
Folder 'GCA_021347165.1_PDT001215180.1' already exists. Skipping...
Folder 'GCA_021347245.1_PDT001215169.1' already exists. Skipping...
Folder 'GCA_021347305.1_PDT001215175.1' already exists. Skipping...
Folder 'GCA_021347365.1_PDT001215167.1' already exists. Skipping...
Folder 'GCA_021347375.1_PDT001215166.1' already exists. Skipping...
Folder 'GCA_021347405.1_PDT001215160.1' already exists. Skipping...
Folder 'GCA_021347445.1_PDT001215165.1' already exists. Skipping...
Folder 'GCA_021347505.1_PDT001215179.1' already exists. Skipping...
Folder 'GCA_021347875.1_PDT001215315.1' already exists. Skipping...
Folder 'GCA_021348725.1_PDT001215357.1' already exists. Skipping...
Folder 'GCA_021349135.1_PDT001215417.1' already exists. Skipping...
Folder 'GCA_021349175.1_PDT001215378.1' already exists. Skipping...
Folder 'GCA_021349195.1_PDT001215375.1' already exists. Skipping...
Folder 'GCA_021349215.1_PDT001215371.1' already exists. Skipping...
Folder 'GCA_021349235.1_PDT001215358.1' already exists. Skipping...
Folder 'GCA_021349275.1_PDT001215381.1' already exists. Skipping...
Folder 'GCA_021349335.1_PDT001215379.1' already exists. Skipping...
Folder 'GCA_021349355.1_PDT001215374.1' already exists. Skipping...
Folder 'GCA_021349375.1_PDT001215376.1' already exists. Skipping...
Folder 'GCA_021349415.1_PDT001215365.1' already exists. Skipping...
Folder 'GCA_021349455.1_PDT001215369.1' already exists. Skipping...
Folder 'GCA_021349475.1_PDT001215366.1' already exists. Skipping...
Folder 'GCA_021349495.1_PDT001215368.1' already exists. Skipping...
Folder 'GCA_021349515.1_PDT001215367.1' already exists. Skipping...
Folder 'GCA_021349535.1_PDT001215361.1' already exists. Skipping...
Folder 'GCA_021349575.1_PDT001215360.1' already exists. Skipping...
Folder 'GCA_021349615.1_PDT001215363.1' already exists. Skipping...
Folder 'GCA_021349735.1_PDT001215447.1' already exists. Skipping...
Folder 'GCA_021351395.1_PDT001215485.1' already exists. Skipping...
Folder 'GCA_021351415.1_PDT001215487.1' already exists. Skipping...
Folder 'GCA_021356685.1_PDT001215694.1' already exists. Skipping...
Folder 'GCA_021356705.1_PDT001215701.1' already exists. Skipping...
Folder 'GCA_021356765.1_PDT001215692.1' already exists. Skipping...
Folder 'GCA_021357985.1_PDT001215546.1' already exists. Skipping...
Folder 'GCA_021358225.1_PDT001215530.1' already exists. Skipping...
Folder 'GCA_021358425.1_PDT001215551.1' already exists. Skipping...
Folder 'GCA_021358545.1_PDT001215538.1' already exists. Skipping...
Folder 'GCA_021358565.1_PDT001215543.1' already exists. Skipping...
Folder 'GCA_021360345.1_PDT001215845.1' already exists. Skipping...
Folder 'GCA_021360385.1_PDT001215840.1' already exists. Skipping...
Folder 'GCA_021361945.1_PDT001215920.1' already exists. Skipping...
Folder 'GCA_021361985.1_PDT001215918.1' already exists. Skipping...
Folder 'GCA_021362025.1_PDT001215919.1' already exists. Skipping...
Folder 'GCA_021363515.1_ASM2136351v1' already exists. Skipping...
Folder 'GCA_021363715.1_ASM2136371v1' already exists. Skipping...
Folder 'GCA_021365215.1_PDT001216236.1' already exists. Skipping...
Folder 'GCA_021366135.1_PDT001216325.1' already exists. Skipping...
Folder 'GCA_021366255.1_PDT001216324.1' already exists. Skipping...
Folder 'GCA_021378885.1_PDT001216913.1' already exists. Skipping...
Folder 'GCA_021381185.1_PDT001217603.1' already exists. Skipping...
Folder 'GCA_021381205.1_PDT001217602.1' already exists. Skipping...
Folder 'GCA_021381285.1_PDT001217599.1' already exists. Skipping...
Folder 'GCA_021383965.1_PDT001217976.1' already exists. Skipping...
Folder 'GCA_021384065.1_PDT001217971.1' already exists. Skipping...
Folder 'GCA_021420525.1_PDT001219227.1' already exists. Skipping...
Folder 'GCA_021420585.1_PDT001219222.1' already exists. Skipping...
Folder 'GCA_021420605.1_PDT001219223.1' already exists. Skipping...
Folder 'GCA_021421565.1_PDT001219238.1' already exists. Skipping...
Folder 'GCA_021422865.1_PDT001219353.1' already exists. Skipping...
Folder 'GCA_021422885.1_PDT001219351.1' already exists. Skipping...
Folder 'GCA_021422925.1_PDT001219352.1' already exists. Skipping...
Folder 'GCA_021423365.1_PDT001219411.1' already exists. Skipping...
Folder 'GCA_021423405.1_PDT001219412.1' already exists. Skipping...
Folder 'GCA_021423425.1_PDT001219408.1' already exists. Skipping...
Folder 'GCA_021423435.1_PDT001219410.1' already exists. Skipping...
Folder 'GCA_021423705.1_PDT001219406.1' already exists. Skipping...
Folder 'GCA_021423825.1_PDT001219387.1' already exists. Skipping...
Folder 'GCA_021424565.1_PDT001219641.1' already exists. Skipping...
Folder 'GCA_021424575.1_PDT001219639.1' already exists. Skipping...
Folder 'GCA_021424605.1_PDT001219640.1' already exists. Skipping...
Folder 'GCA_021424625.1_PDT001219638.1' already exists. Skipping...
Folder 'GCA_021427025.1_PDT001219262.1' already exists. Skipping...
Folder 'GCA_021427045.1_PDT001219261.1' already exists. Skipping...
Folder 'GCA_021427065.1_PDT001219260.1' already exists. Skipping...
Folder 'GCA_021427085.1_PDT001219259.1' already exists. Skipping...
Folder 'GCA_021427105.1_PDT001219258.1' already exists. Skipping...
Folder 'GCA_021427125.1_PDT001219252.1' already exists. Skipping...
Folder 'GCA_021427145.1_PDT001219256.1' already exists. Skipping...
Folder 'GCA_021427165.1_PDT001219242.1' already exists. Skipping...
Folder 'GCA_021427185.1_PDT001219240.1' already exists. Skipping...
Folder 'GCA_021427205.1_PDT001219241.1' already exists. Skipping...
Folder 'GCA_021427225.1_PDT001219237.1' already exists. Skipping...
Folder 'GCA_021427235.1_PDT001219234.1' already exists. Skipping...
Folder 'GCA_021427265.1_PDT001219235.1' already exists. Skipping...
Folder 'GCA_021427285.1_PDT001219233.1' already exists. Skipping...
Folder 'GCA_021427645.1_PDT001219239.1' already exists. Skipping...
Folder 'GCA_021428145.1_PDT001219355.1' already exists. Skipping...
Folder 'GCA_021428265.1_PDT001219386.1' already exists. Skipping...
Folder 'GCA_021428285.1_PDT001219396.1' already exists. Skipping...
Folder 'GCA_021428325.1_PDT001219384.1' already exists. Skipping...
Folder 'GCA_021428365.1_PDT001219383.1' already exists. Skipping...
Folder 'GCA_021437825.1_PDT001220794.1' already exists. Skipping...
Folder 'GCA_021437845.1_PDT001220795.1' already exists. Skipping...
Folder 'GCA_021445185.1_PDT001221162.1' already exists. Skipping...
Folder 'GCA_021445225.1_PDT001221161.1' already exists. Skipping...
Folder 'GCA_021445245.1_PDT001221160.1' already exists. Skipping...
Folder 'GCA_021445265.1_PDT001221159.1' already exists. Skipping...
Folder 'GCA_021445285.1_PDT001221158.1' already exists. Skipping...
Folder 'GCA_021445305.1_PDT001221155.1' already exists. Skipping...
Folder 'GCA_021445325.1_PDT001221153.1' already exists. Skipping...
Folder 'GCA_021445345.1_PDT001221154.1' already exists. Skipping...
Folder 'GCA_021445485.1_PDT001221185.1' already exists. Skipping...
Folder 'GCA_021445665.1_PDT001221157.1' already exists. Skipping...
Folder 'GCA_021445685.1_PDT001221163.1' already exists. Skipping...
Folder 'GCA_021445705.1_PDT001221156.1' already exists. Skipping...
Folder 'GCA_021446065.1_PDT001221005.1' already exists. Skipping...
Folder 'GCA_021450945.1_PDT001221184.1' already exists. Skipping...
Folder 'GCA_021451405.1_PDT001221004.1' already exists. Skipping...
Folder 'GCA_021451865.1_PDT001220869.1' already exists. Skipping...
Folder 'GCA_021464725.1_PDT001222684.1' already exists. Skipping...
Folder 'GCA_021464745.1_PDT001222685.1' already exists. Skipping...
Folder 'GCA_021464925.1_PDT001222626.1' already exists. Skipping...
Folder 'GCA_021464935.1_PDT001222624.1' already exists. Skipping...
Folder 'GCA_021465485.1_PDT001222582.1' already exists. Skipping...
Folder 'GCA_021465505.1_PDT001222581.1' already exists. Skipping...
Folder 'GCA_021465565.1_PDT001222579.1' already exists. Skipping...
Folder 'GCA_021465665.1_PDT001222546.1' already exists. Skipping...
Folder 'GCA_021465765.1_PDT001222540.1' already exists. Skipping...
Folder 'GCA_021466025.1_PDT001222529.1' already exists. Skipping...
Folder 'GCA_021466065.1_PDT001222525.1' already exists. Skipping...
Folder 'GCA_021466705.1_PDT001222461.1' already exists. Skipping...
Folder 'GCA_021467165.1_PDT001222403.1' already exists. Skipping...
Folder 'GCA_021470265.1_PDT001222675.1' already exists. Skipping...
Folder 'GCA_021470285.1_PDT001222676.1' already exists. Skipping...
Folder 'GCA_021470825.1_PDT001222565.1' already exists. Skipping...
Folder 'GCA_021470845.1_PDT001222556.1' already exists. Skipping...
Folder 'GCA_021470885.1_PDT001222578.1' already exists. Skipping...
Folder 'GCA_021470985.1_PDT001222553.1' already exists. Skipping...
Folder 'GCA_021471025.1_PDT001222549.1' already exists. Skipping...
Folder 'GCA_021473045.1_PDT001222559.1' already exists. Skipping...
Folder 'GCA_021473065.1_PDT001222563.1' already exists. Skipping...
Folder 'GCA_021473105.1_PDT001222429.1' already exists. Skipping...
Folder 'GCA_021473165.1_PDT001222430.1' already exists. Skipping...
Folder 'GCA_021473285.1_PDT001222422.1' already exists. Skipping...
Folder 'GCA_021473405.1_PDT001222409.1' already exists. Skipping...
Folder 'GCA_021486315.1_PDT001223368.1' already exists. Skipping...
Folder 'GCA_021486375.1_PDT001223365.1' already exists. Skipping...
Folder 'GCA_021486435.1_PDT001223363.1' already exists. Skipping...
Folder 'GCA_021486475.1_PDT001223361.1' already exists. Skipping...
Folder 'GCA_021486895.1_PDT001223437.1' already exists. Skipping...
Folder 'GCA_021486935.1_PDT001223432.1' already exists. Skipping...
Folder 'GCA_021487015.1_PDT001223429.1' already exists. Skipping...
Folder 'GCA_021487035.1_PDT001223422.1' already exists. Skipping...
Folder 'GCA_021487095.1_PDT001223430.1' already exists. Skipping...
Folder 'GCA_021487115.1_PDT001223420.1' already exists. Skipping...
Folder 'GCA_021487155.1_PDT001223411.1' already exists. Skipping...
Folder 'GCA_021487175.1_PDT001223412.1' already exists. Skipping...
Folder 'GCA_021487215.1_PDT001223397.1' already exists. Skipping...
Folder 'GCA_021487275.1_PDT001223384.1' already exists. Skipping...
Folder 'GCA_021487335.1_PDT001223375.1' already exists. Skipping...
Folder 'GCA_021487375.1_PDT001223380.1' already exists. Skipping...
Folder 'GCA_021487875.1_PDT001223512.1' already exists. Skipping...
Folder 'GCA_021487955.1_PDT001223511.1' already exists. Skipping...
Folder 'GCA_021487975.1_PDT001223507.1' already exists. Skipping...
Folder 'GCA_021488015.1_PDT001223495.1' already exists. Skipping...
Folder 'GCA_021488055.1_PDT001223498.1' already exists. Skipping...
Folder 'GCA_021488195.1_PDT001223510.1' already exists. Skipping...
Folder 'GCA_021488215.1_PDT001223506.1' already exists. Skipping...
Folder 'GCA_021488235.1_PDT001223508.1' already exists. Skipping...
Folder 'GCA_021488255.1_PDT001223504.1' already exists. Skipping...
Folder 'GCA_021488275.1_PDT001223505.1' already exists. Skipping...
Folder 'GCA_021488295.1_PDT001223501.1' already exists. Skipping...
Folder 'GCA_021488395.1_PDT001223496.1' already exists. Skipping...
Folder 'GCA_021488955.1_PDT001223217.1' already exists. Skipping...

Retreiveing data: 83127it [00:13, 6543.39it/s]

Folder 'GCA_022610385.1_PDT001254701.1' already exists. Skipping...
Folder 'GCA_022610395.1_PDT001267940.1' already exists. Skipping...
Folder 'GCA_022610505.1_PDT001254699.1' already exists. Skipping...
Folder 'GCA_022610525.1_PDT001254697.1' already exists. Skipping...
Folder 'GCA_022610665.1_PDT001254687.1' already exists. Skipping...
Folder 'GCA_022612455.1_PDT001269490.1' already exists. Skipping...
Folder 'GCA_022612975.1_PDT001269660.1' already exists. Skipping...
Folder 'GCA_022612995.1_PDT001269662.1' already exists. Skipping...
Folder 'GCA_022613115.1_PDT001269672.1' already exists. Skipping...
Folder 'GCA_022613235.1_PDT001269665.1' already exists. Skipping...
Folder 'GCA_022613255.1_PDT001269677.1' already exists. Skipping...
Folder 'GCA_022613295.1_PDT001269676.1' already exists. Skipping...
Folder 'GCA_022613335.1_PDT001269673.1' already exists. Skipping...
Folder 'GCA_022613355.1_PDT001269671.1' already exists. Skipping...
Folder 'GCA_022613395.1_PDT001269663.1' already exists. Skipping...
Folder 'GCA_022613435.1_PDT001269661.1' already exists. Skipping...
Folder 'GCA_022613455.1_PDT001269652.1' already exists. Skipping...
Folder 'GCA_022613475.1_PDT001269651.1' already exists. Skipping...
Folder 'GCA_022613495.1_PDT001269657.1' already exists. Skipping...
Folder 'GCA_022613915.1_PDT001269718.1' already exists. Skipping...
Folder 'GCA_022613935.1_PDT001269717.1' already exists. Skipping...
Folder 'GCA_022613955.1_PDT001269720.1' already exists. Skipping...
Folder 'GCA_022613975.1_PDT001269716.1' already exists. Skipping...
Folder 'GCA_022613995.1_PDT001269715.1' already exists. Skipping...
Folder 'GCA_022614075.1_PDT001269714.1' already exists. Skipping...
Folder 'GCA_022614095.1_PDT001269704.1' already exists. Skipping...
Folder 'GCA_022614115.1_PDT001269701.1' already exists. Skipping...
Folder 'GCA_022614155.1_PDT001269702.1' already exists. Skipping...
Folder 'GCA_022614175.1_PDT001269700.1' already exists. Skipping...
Folder 'GCA_022614365.1_PDT001269667.1' already exists. Skipping...
Folder 'GCA_022614485.1_PDT001269707.1' already exists. Skipping...
Folder 'GCA_022618575.1_PDT001269730.1' already exists. Skipping...
Folder 'GCA_022618715.1_PDT001269719.1' already exists. Skipping...
Folder 'GCA_022628675.1_PDT001270561.1' already exists. Skipping...
Folder 'GCA_022631875.1_PDT001271738.1' already exists. Skipping...
Folder 'GCA_022631955.1_PDT001271764.1' already exists. Skipping...
Folder 'GCA_022632135.1_PDT001271744.1' already exists. Skipping...
Folder 'GCA_022632175.1_PDT001271743.1' already exists. Skipping...
Folder 'GCA_022632195.1_PDT001271745.1' already exists. Skipping...
Folder 'GCA_022632235.1_PDT001271733.1' already exists. Skipping...
Folder 'GCA_022632255.1_PDT001271740.1' already exists. Skipping...
Folder 'GCA_022632315.1_PDT001271734.1' already exists. Skipping...
Folder 'GCA_022632355.1_PDT001271729.1' already exists. Skipping...
Folder 'GCA_022632375.1_PDT001271727.1' already exists. Skipping...
Folder 'GCA_022632395.1_PDT001271728.1' already exists. Skipping...
Folder 'GCA_022632415.1_PDT001271724.1' already exists. Skipping...
Folder 'GCA_022632915.1_PDT001271735.1' already exists. Skipping...
Folder 'GCA_022633015.1_PDT001271725.1' already exists. Skipping...
Folder 'GCA_022634735.1_PDT001271305.1' already exists. Skipping...
Folder 'GCA_022634775.1_PDT001271304.1' already exists. Skipping...
Folder 'GCA_022635275.1_PDT001271270.1' already exists. Skipping...
Folder 'GCA_022636775.1_PDT001271271.1' already exists. Skipping...
Folder 'GCA_022637195.1_PDT001271174.1' already exists. Skipping...
Folder 'GCA_022637235.1_PDT001271173.1' already exists. Skipping...
Folder 'GCA_022638555.1_PDT001271036.1' already exists. Skipping...
Folder 'GCA_022638695.1_PDT001271025.1' already exists. Skipping...
Folder 'GCA_022638715.1_PDT001271022.1' already exists. Skipping...
Folder 'GCA_022639055.1_PDT001271020.1' already exists. Skipping...
Folder 'GCA_022639935.1_PDT001270936.1' already exists. Skipping...
Folder 'GCA_022640175.1_PDT001270952.1' already exists. Skipping...
Folder 'GCA_022640235.1_PDT001270938.1' already exists. Skipping...
Folder 'GCA_022650745.1_PDT001270795.1' already exists. Skipping...
Folder 'GCA_022650825.1_PDT001270794.1' already exists. Skipping...
Folder 'GCA_022650845.1_PDT001270793.1' already exists. Skipping...
Folder 'GCA_022650965.1_PDT001270789.1' already exists. Skipping...
Folder 'GCA_022651395.1_PDT001270775.1' already exists. Skipping...
Folder 'GCA_022651485.1_PDT001270772.1' already exists. Skipping...
Folder 'GCA_022651505.1_PDT001270774.1' already exists. Skipping...
Folder 'GCA_022651885.1_PDT001270777.1' already exists. Skipping...
Folder 'GCA_022651905.1_PDT001270773.1' already exists. Skipping...
Folder 'GCA_022651975.1_PDT001270770.1' already exists. Skipping...
Folder 'GCA_022652455.1_PDT001270734.1' already exists. Skipping...
Folder 'GCA_022652755.1_PDT001270725.1' already exists. Skipping...
Folder 'GCA_022652915.1_PDT001270722.1' already exists. Skipping...
Folder 'GCA_022654395.1_PDT001270694.1' already exists. Skipping...
Folder 'GCA_022655065.1_PDT001270678.1' already exists. Skipping...
Folder 'GCA_022655275.1_PDT001270670.1' already exists. Skipping...
Folder 'GCA_022655745.1_PDT001270664.1' already exists. Skipping...
Folder 'GCA_022655785.1_PDT001270663.1' already exists. Skipping...
Folder 'GCA_022655845.1_PDT001270660.1' already exists. Skipping...
Folder 'GCA_022655965.1_PDT001270674.1' already exists. Skipping...
Folder 'GCA_022656045.1_PDT001270662.1' already exists. Skipping...
Folder 'GCA_022656445.1_PDT001270641.1' already exists. Skipping...
Folder 'GCA_022656485.1_PDT001270633.1' already exists. Skipping...
Folder 'GCA_022656505.1_PDT001270639.1' already exists. Skipping...
Folder 'GCA_022656525.1_PDT001270634.1' already exists. Skipping...
Folder 'GCA_022656545.1_PDT001270637.1' already exists. Skipping...
Folder 'GCA_022656725.1_PDT001270627.1' already exists. Skipping...
Folder 'GCA_022656765.1_PDT001270622.1' already exists. Skipping...
Folder 'GCA_022656805.1_PDT001270624.1' already exists. Skipping...
Folder 'GCA_022656845.1_PDT001270623.1' already exists. Skipping...
Folder 'GCA_022656885.1_PDT001270618.1' already exists. Skipping...
Folder 'GCA_022656915.1_PDT001270614.1' already exists. Skipping...
Folder 'GCA_022656975.1_PDT001270609.1' already exists. Skipping...
Folder 'GCA_022656995.1_PDT001270613.1' already exists. Skipping...
Folder 'GCA_022657015.1_PDT001270610.1' already exists. Skipping...
Folder 'GCA_022657055.1_PDT001270612.1' already exists. Skipping...
Folder 'GCA_022657075.1_PDT001270606.1' already exists. Skipping...
Folder 'GCA_022657095.1_PDT001270605.1' already exists. Skipping...
Folder 'GCA_022657155.1_PDT001270604.1' already exists. Skipping...
Folder 'GCA_022657175.1_PDT001270602.1' already exists. Skipping...
Folder 'GCA_022657195.1_PDT001270600.1' already exists. Skipping...
Folder 'GCA_022657215.1_PDT001270601.1' already exists. Skipping...
Folder 'GCA_022657235.1_PDT001270598.1' already exists. Skipping...
Folder 'GCA_022657295.1_PDT001270595.1' already exists. Skipping...
Folder 'GCA_022657315.1_PDT001270597.1' already exists. Skipping...
Folder 'GCA_022657335.1_PDT001270594.1' already exists. Skipping...
Folder 'GCA_022657615.1_PDT001270580.1' already exists. Skipping...
Folder 'GCA_022657675.1_PDT001270577.1' already exists. Skipping...
Folder 'GCA_022657715.1_PDT001270578.1' already exists. Skipping...
Folder 'GCA_022659975.1_PDT001268328.1' already exists. Skipping...
Folder 'GCA_022660275.1_PDT001268304.1' already exists. Skipping...
Folder 'GCA_022660335.1_PDT001268302.1' already exists. Skipping...
Folder 'GCA_022660355.1_PDT001268301.1' already exists. Skipping...
Folder 'GCA_022660415.1_PDT001270629.1' already exists. Skipping...
Folder 'GCA_022660595.1_PDT001268299.1' already exists. Skipping...
Folder 'GCA_022660615.1_PDT001268300.1' already exists. Skipping...
Folder 'GCA_022660655.1_PDT001268297.1' already exists. Skipping...
Folder 'GCA_022660755.1_PDT001267943.1' already exists. Skipping...
Folder 'GCA_022660795.1_PDT001267941.1' already exists. Skipping...
Folder 'GCA_022664625.1_PDT001271884.1' already exists. Skipping...
Folder 'GCA_022664645.1_PDT001271886.1' already exists. Skipping...
Folder 'GCA_022664685.1_PDT001271885.1' already exists. Skipping...
Folder 'GCA_022665085.1_PDT001271889.1' already exists. Skipping...
Folder 'GCA_022665105.1_PDT001271921.1' already exists. Skipping...
Folder 'GCA_022665125.1_PDT001271916.1' already exists. Skipping...
Folder 'GCA_022665695.1_PDT001264699.1' already exists. Skipping...
Folder 'GCA_022666095.1_PDT001271920.1' already exists. Skipping...
Folder 'GCA_022666175.1_PDT001271913.1' already exists. Skipping...
Folder 'GCA_022666215.1_PDT001271917.1' already exists. Skipping...
Folder 'GCA_022666255.1_PDT001271919.1' already exists. Skipping...
Folder 'GCA_022666775.1_PDT001264532.1' already exists. Skipping...
Folder 'GCA_022666795.1_PDT001264531.1' already exists. Skipping...
Folder 'GCA_022667475.1_PDT001271918.1' already exists. Skipping...
Folder 'GCA_022667715.1_PDT001271988.1' already exists. Skipping...
Folder 'GCA_022667755.1_PDT001271993.1' already exists. Skipping...
Folder 'GCA_022668155.1_PDT001272001.1' already exists. Skipping...
Folder 'GCA_022668175.1_PDT001271991.1' already exists. Skipping...
Folder 'GCA_022668215.1_PDT001271990.1' already exists. Skipping...
Folder 'GCA_022668295.1_PDT001271978.1' already exists. Skipping...
Folder 'GCA_022668315.1_PDT001271989.1' already exists. Skipping...
Folder 'GCA_022670855.1_PDT001272335.1' already exists. Skipping...
Folder 'GCA_022670915.1_PDT001272332.1' already exists. Skipping...
Folder 'GCA_022670935.1_PDT001272322.1' already exists. Skipping...
Folder 'GCA_022670975.1_PDT001272314.1' already exists. Skipping...
Folder 'GCA_022670995.1_PDT001272328.1' already exists. Skipping...
Folder 'GCA_022671055.1_PDT001272331.1' already exists. Skipping...
Folder 'GCA_022671075.1_PDT001272329.1' already exists. Skipping...
Folder 'GCA_022671155.1_PDT001272337.1' already exists. Skipping...
Folder 'GCA_022671175.1_PDT001272333.1' already exists. Skipping...
Folder 'GCA_022671195.1_PDT001272334.1' already exists. Skipping...
Folder 'GCA_022671215.1_PDT001272327.1' already exists. Skipping...
Folder 'GCA_022671235.1_PDT001272325.1' already exists. Skipping...
Folder 'GCA_022671275.1_PDT001272324.1' already exists. Skipping...
Folder 'GCA_022671315.1_PDT001272336.1' already exists. Skipping...
Folder 'GCA_022671895.1_PDT001272321.1' already exists. Skipping...
Folder 'GCA_022675495.1_PDT001273827.1' already exists. Skipping...
Folder 'GCA_022676655.1_PDT001273743.1' already exists. Skipping...
Folder 'GCA_022677925.1_PDT001273980.1' already exists. Skipping...
Folder 'GCA_022677945.1_PDT001273978.1' already exists. Skipping...
Folder 'GCA_022678045.1_PDT001273967.1' already exists. Skipping...
Folder 'GCA_022678145.1_PDT001273982.1' already exists. Skipping...
Folder 'GCA_022681325.1_PDT001274146.1' already exists. Skipping...
Folder 'GCA_022681505.1_PDT001274144.1' already exists. Skipping...
Folder 'GCA_022688625.1_PDT001274745.1' already exists. Skipping...
Folder 'GCA_022688645.1_PDT001274748.1' already exists. Skipping...
Folder 'GCA_022688665.1_PDT001274747.1' already exists. Skipping...
Folder 'GCA_022688685.1_PDT001274743.1' already exists. Skipping...
Folder 'GCA_022688705.1_PDT001274746.1' already exists. Skipping...
Folder 'GCA_022688725.1_PDT001274749.1' already exists. Skipping...
Folder 'GCA_022688745.1_PDT001274744.1' already exists. Skipping...
Folder 'GCA_022688845.1_PDT001274750.1' already exists. Skipping...
Folder 'GCA_022688865.1_PDT001274742.1' already exists. Skipping...
Folder 'GCA_022694725.1_PDT001275351.1' already exists. Skipping...
Folder 'GCA_022694895.1_PDT001275353.1' already exists. Skipping...
Folder 'GCA_022836515.1_ASM2283651v1' already exists. Skipping...
Folder 'GCA_022875525.1_PDT001280883.1' already exists. Skipping...
Folder 'GCA_022879225.1_PDT001280735.1' already exists. Skipping...
Folder 'GCA_022879275.1_PDT001280732.1' already exists. Skipping...
Folder 'GCA_022879305.1_PDT001280733.1' already exists. Skipping...
Folder 'GCA_022879375.1_PDT001280731.1' already exists. Skipping...
Folder 'GCA_022879655.1_PDT001280728.1' already exists. Skipping...
Folder 'GCA_022879715.1_PDT001280729.1' already exists. Skipping...
Folder 'GCA_022879735.1_PDT001280725.1' already exists. Skipping...
Folder 'GCA_022879775.1_PDT001280722.1' already exists. Skipping...
Folder 'GCA_022879835.1_PDT001280721.1' already exists. Skipping...
Folder 'GCA_022879875.1_PDT001280718.1' already exists. Skipping...
Folder 'GCA_022879935.1_PDT001280716.1' already exists. Skipping...
Folder 'GCA_022879955.1_PDT001280714.1' already exists. Skipping...
Folder 'GCA_022880015.1_PDT001280713.1' already exists. Skipping...
Folder 'GCA_022880035.1_PDT001280711.1' already exists. Skipping...
Folder 'GCA_022880055.1_PDT001280710.1' already exists. Skipping...
Folder 'GCA_022880095.1_PDT001280707.1' already exists. Skipping...
Folder 'GCA_022880135.1_PDT001280708.1' already exists. Skipping...
Folder 'GCA_022880275.1_PDT001280697.1' already exists. Skipping...
Folder 'GCA_022880295.1_PDT001280699.1' already exists. Skipping...
Folder 'GCA_022882045.1_PDT001280583.1' already exists. Skipping...
Folder 'GCA_022882115.1_PDT001280576.1' already exists. Skipping...
Folder 'GCA_022882135.1_PDT001280578.1' already exists. Skipping...
Folder 'GCA_022882145.1_PDT001280579.1' already exists. Skipping...
Folder 'GCA_022882175.1_PDT001280577.1' already exists. Skipping...
Folder 'GCA_022882235.1_PDT001280571.1' already exists. Skipping...
Folder 'GCA_022882255.1_PDT001280572.1' already exists. Skipping...
Folder 'GCA_022882275.1_PDT001280570.1' already exists. Skipping...
Folder 'GCA_022882335.1_PDT001280565.1' already exists. Skipping...
Folder 'GCA_022882395.1_PDT001280561.1' already exists. Skipping...
Folder 'GCA_022882455.1_PDT001280555.1' already exists. Skipping...
Folder 'GCA_022882475.1_PDT001280554.1' already exists. Skipping...
Folder 'GCA_022882515.1_PDT001280545.1' already exists. Skipping...
Folder 'GCA_022882575.1_PDT001280549.1' already exists. Skipping...
Folder 'GCA_022882615.1_PDT001280543.1' already exists. Skipping...
Folder 'GCA_022882655.1_PDT001280541.1' already exists. Skipping...
Folder 'GCA_022882735.1_PDT001280536.1' already exists. Skipping...
Folder 'GCA_022882755.1_PDT001280537.1' already exists. Skipping...
Folder 'GCA_022882775.1_PDT001280534.1' already exists. Skipping...
Folder 'GCA_022882915.1_PDT001280581.1' already exists. Skipping...
Folder 'GCA_022882935.1_PDT001280568.1' already exists. Skipping...
Folder 'GCA_022882955.1_PDT001280580.1' already exists. Skipping...
Folder 'GCA_022882975.1_PDT001280564.1' already exists. Skipping...
Folder 'GCA_022883015.1_PDT001280574.1' already exists. Skipping...
Folder 'GCA_022883055.1_PDT001280559.1' already exists. Skipping...
Folder 'GCA_022883075.1_PDT001280558.1' already exists. Skipping...
Folder 'GCA_022883095.1_PDT001280552.1' already exists. Skipping...
Folder 'GCA_022883115.1_PDT001280556.1' already exists. Skipping...
Folder 'GCA_022883135.1_PDT001280548.1' already exists. Skipping...
Folder 'GCA_022883155.1_PDT001280533.1' already exists. Skipping...
Folder 'GCA_022883195.1_PDT001280539.1' already exists. Skipping...
Folder 'GCA_022883255.1_PDT001280530.1' already exists. Skipping...
Folder 'GCA_022883635.1_PDT001280508.1' already exists. Skipping...
Folder 'GCA_022883655.1_PDT001280505.1' already exists. Skipping...
Folder 'GCA_022883675.1_PDT001280506.1' already exists. Skipping...
Folder 'GCA_022883695.1_PDT001280507.1' already exists. Skipping...
Folder 'GCA_022883715.1_PDT001280504.1' already exists. Skipping...
Folder 'GCA_022883755.1_PDT001280501.1' already exists. Skipping...
Folder 'GCA_022883855.1_PDT001280497.1' already exists. Skipping...
Folder 'GCA_022883875.1_PDT001280495.1' already exists. Skipping...
Folder 'GCA_022883935.1_PDT001280493.1' already exists. Skipping...
Folder 'GCA_022883975.1_PDT001280491.1' already exists. Skipping...
Folder 'GCA_022883995.1_PDT001280490.1' already exists. Skipping...
Folder 'GCA_022884015.1_PDT001280489.1' already exists. Skipping...
Folder 'GCA_022884105.1_PDT001280484.1' already exists. Skipping...
Folder 'GCA_022884155.1_PDT001280487.1' already exists. Skipping...
Folder 'GCA_022884175.1_PDT001280485.1' already exists. Skipping...
Folder 'GCA_022884195.1_PDT001280483.1' already exists. Skipping...
Folder 'GCA_022884225.1_PDT001280480.1' already exists. Skipping...
Folder 'GCA_022884265.1_PDT001280482.1' already exists. Skipping...
Folder 'GCA_022884295.1_PDT001280478.1' already exists. Skipping...
Folder 'GCA_022884425.1_PDT001280471.1' already exists. Skipping...
Folder 'GCA_022884445.1_PDT001280469.1' already exists. Skipping...
Folder 'GCA_022884465.1_PDT001280468.1' already exists. Skipping...
Folder 'GCA_022884505.1_PDT001280467.1' already exists. Skipping...
Folder 'GCA_022884525.1_PDT001280465.1' already exists. Skipping...
Folder 'GCA_022886975.1_PDT001280343.1' already exists. Skipping...
Folder 'GCA_022887015.1_PDT001280342.1' already exists. Skipping...
Folder 'GCA_022887055.1_PDT001280340.1' already exists. Skipping...
Folder 'GCA_022887075.1_PDT001280339.1' already exists. Skipping...
Folder 'GCA_022887095.1_PDT001280336.1' already exists. Skipping...
Folder 'GCA_022887115.1_PDT001280338.1' already exists. Skipping...
Folder 'GCA_022887155.1_PDT001280335.1' already exists. Skipping...
Folder 'GCA_022887235.1_PDT001280331.1' already exists. Skipping...
Folder 'GCA_022888035.1_PDT001280156.1' already exists. Skipping...
Folder 'GCA_022888055.1_PDT001280155.1' already exists. Skipping...
Folder 'GCA_022888075.1_PDT001280154.1' already exists. Skipping...
Folder 'GCA_022888095.1_PDT001280152.1' already exists. Skipping...
Folder 'GCA_022888115.1_PDT001280153.1' already exists. Skipping...
Folder 'GCA_022888135.1_PDT001280151.1' already exists. Skipping...
Folder 'GCA_022888595.1_PDT001280127.1' already exists. Skipping...
Folder 'GCA_022888855.1_PDT001280115.1' already exists. Skipping...
Folder 'GCA_022889055.1_PDT001280098.1' already exists. Skipping...
Folder 'GCA_022890315.1_PDT001280032.1' already exists. Skipping...
Folder 'GCA_022890335.1_PDT001280029.1' already exists. Skipping...
Folder 'GCA_022890355.1_PDT001280031.1' already exists. Skipping...
Folder 'GCA_022890395.1_PDT001280026.1' already exists. Skipping...
Folder 'GCA_022890415.1_PDT001280028.1' already exists. Skipping...
Folder 'GCA_022890455.1_PDT001280025.1' already exists. Skipping...
Folder 'GCA_022890495.1_PDT001280023.1' already exists. Skipping...
Folder 'GCA_022890555.1_PDT001280019.1' already exists. Skipping...
Folder 'GCA_022892915.1_PDT001283289.1' already exists. Skipping...
Folder 'GCA_022893895.1_PDT001283292.1' already exists. Skipping...
Folder 'GCA_022894895.1_PDT001283294.1' already exists. Skipping...
Folder 'GCA_022901755.1_PDT001279628.1' already exists. Skipping...
Folder 'GCA_022907335.1_PDT001279314.1' already exists. Skipping...
Folder 'GCA_022907755.1_PDT001279289.1' already exists. Skipping...
Folder 'GCA_022907875.1_PDT001279275.1' already exists. Skipping...
Folder 'GCA_022907895.1_PDT001279277.1' already exists. Skipping...
Folder 'GCA_022908315.1_PDT001279255.1' already exists. Skipping...
Folder 'GCA_022908335.1_PDT001279254.1' already exists. Skipping...
Folder 'GCA_022908395.1_PDT001279253.1' already exists. Skipping...
Folder 'GCA_022908735.1_PDT001279227.1' already exists. Skipping...
Folder 'GCA_022908795.1_PDT001279226.1' already exists. Skipping...
Folder 'GCA_022908815.1_PDT001279223.1' already exists. Skipping...
Folder 'GCA_022908835.1_PDT001279222.1' already exists. Skipping...
Folder 'GCA_022908915.1_PDT001279218.1' already exists. Skipping...
Folder 'GCA_022908995.1_PDT001279214.1' already exists. Skipping...

Retreiveing data: 84453it [00:14, 6587.07it/s]

Folder 'GCA_023783985.1_PDT001326556.1' already exists. Skipping...
Folder 'GCA_023784135.1_PDT001326412.1' already exists. Skipping...
Folder 'GCA_023784155.1_PDT001326413.1' already exists. Skipping...
Folder 'GCA_023784495.1_PDT001326606.1' already exists. Skipping...
Folder 'GCA_023784515.1_PDT001326613.1' already exists. Skipping...
Folder 'GCA_023784675.1_PDT001326552.1' already exists. Skipping...
Folder 'GCA_023784735.1_PDT001326541.1' already exists. Skipping...
Folder 'GCA_023784775.1_PDT001326549.1' already exists. Skipping...
Folder 'GCA_023785315.1_PDT001326612.1' already exists. Skipping...
Folder 'GCA_023785335.1_PDT001326611.1' already exists. Skipping...
Folder 'GCA_023785395.1_PDT001326557.1' already exists. Skipping...
Folder 'GCA_023787275.1_PDT001326618.1' already exists. Skipping...
Folder 'GCA_023788075.1_PDT001322926.1' already exists. Skipping...
Folder 'GCA_023788755.1_PDT001322773.1' already exists. Skipping...
Folder 'GCA_023788815.1_PDT001322770.1' already exists. Skipping...
Folder 'GCA_023788835.1_PDT001322769.1' already exists. Skipping...
Folder 'GCA_023788895.1_PDT001322757.1' already exists. Skipping...
Folder 'GCA_023788905.1_PDT001322759.1' already exists. Skipping...
Folder 'GCA_023788955.1_PDT001322708.1' already exists. Skipping...
Folder 'GCA_023789035.1_PDT001322717.1' already exists. Skipping...
Folder 'GCA_023789075.1_PDT001322702.1' already exists. Skipping...
Folder 'GCA_023789095.1_PDT001322696.1' already exists. Skipping...
Folder 'GCA_023789355.1_PDT001322743.1' already exists. Skipping...
Folder 'GCA_023789515.1_PDT001322620.1' already exists. Skipping...
Folder 'GCA_023789575.1_PDT001322573.1' already exists. Skipping...
Folder 'GCA_023790455.1_PDT001322344.1' already exists. Skipping...
Folder 'GCA_023790495.1_PDT001322331.1' already exists. Skipping...
Folder 'GCA_023791495.1_PDT001322328.1' already exists. Skipping...
Folder 'GCA_023792075.1_PDT001327315.1' already exists. Skipping...
Folder 'GCA_023793355.1_PDT001326760.1' already exists. Skipping...
Folder 'GCA_023793595.1_PDT001326731.1' already exists. Skipping...
Folder 'GCA_023793715.1_PDT001327369.1' already exists. Skipping...
Folder 'GCA_023793795.1_PDT001327359.1' already exists. Skipping...
Folder 'GCA_023794275.1_PDT001326707.1' already exists. Skipping...
Folder 'GCA_023794315.1_PDT001326706.1' already exists. Skipping...
Folder 'GCA_023794395.1_PDT001326700.1' already exists. Skipping...
Folder 'GCA_023794455.1_PDT001326698.1' already exists. Skipping...
Folder 'GCA_023794975.1_PDT001326674.1' already exists. Skipping...
Folder 'GCA_023795275.1_PDT001326654.1' already exists. Skipping...
Folder 'GCA_023795635.1_PDT001327355.1' already exists. Skipping...
Folder 'GCA_023795835.1_PDT001327462.1' already exists. Skipping...
Folder 'GCA_023795895.1_PDT001327461.1' already exists. Skipping...
Folder 'GCA_023795915.1_PDT001327451.1' already exists. Skipping...
Folder 'GCA_023795935.1_PDT001327448.1' already exists. Skipping...
Folder 'GCA_023795975.1_PDT001327430.1' already exists. Skipping...
Folder 'GCA_023796055.1_PDT001327442.1' already exists. Skipping...
Folder 'GCA_023796075.1_PDT001327456.1' already exists. Skipping...
Folder 'GCA_023796125.1_PDT001327444.1' already exists. Skipping...
Folder 'GCA_023796135.1_PDT001327471.1' already exists. Skipping...
Folder 'GCA_023796195.1_PDT001327460.1' already exists. Skipping...
Folder 'GCA_023796655.1_PDT001327436.1' already exists. Skipping...
Folder 'GCA_023799075.1_PDT001327860.1' already exists. Skipping...
Folder 'GCA_023799115.1_PDT001327859.1' already exists. Skipping...
Folder 'GCA_023799135.1_PDT001327873.1' already exists. Skipping...
Folder 'GCA_023799155.1_PDT001327830.1' already exists. Skipping...
Folder 'GCA_023799175.1_PDT001327827.1' already exists. Skipping...
Folder 'GCA_023799185.1_PDT001327842.1' already exists. Skipping...
Folder 'GCA_023799215.1_PDT001327825.1' already exists. Skipping...
Folder 'GCA_023799495.1_PDT001328023.1' already exists. Skipping...
Folder 'GCA_023799535.1_PDT001328021.1' already exists. Skipping...
Folder 'GCA_023803155.1_PDT001326672.2' already exists. Skipping...
Folder 'GCA_023803495.1_PDT001323131.2' already exists. Skipping...
Folder 'GCA_023803615.1_PDT001328078.1' already exists. Skipping...
Folder 'GCA_023815385.1_PDT001331260.1' already exists. Skipping...
Folder 'GCA_023815865.1_PDT001331239.1' already exists. Skipping...
Folder 'GCA_023815945.1_PDT001331235.1' already exists. Skipping...
Folder 'GCA_023816075.1_PDT001331254.1' already exists. Skipping...
Folder 'GCA_023816465.1_PDT001330402.1' already exists. Skipping...
Folder 'GCA_023817625.1_PDT001335689.1' already exists. Skipping...
Folder 'GCA_023817785.1_PDT001335691.1' already exists. Skipping...
Folder 'GCA_023826895.1_PDT001326614.1' already exists. Skipping...
Folder 'GCA_023826935.1_PDT001326610.1' already exists. Skipping...
Folder 'GCA_023826955.1_PDT001326605.1' already exists. Skipping...
Folder 'GCA_023826975.1_PDT001326608.1' already exists. Skipping...
Folder 'GCA_023826995.1_PDT001326602.1' already exists. Skipping...
Folder 'GCA_023827055.1_PDT001326594.1' already exists. Skipping...
Folder 'GCA_023827075.1_PDT001326598.1' already exists. Skipping...
Folder 'GCA_023827135.1_PDT001326560.1' already exists. Skipping...
Folder 'GCA_023827175.1_PDT001326547.1' already exists. Skipping...
Folder 'GCA_023827195.1_PDT001326550.1' already exists. Skipping...
Folder 'GCA_023827215.1_PDT001326439.1' already exists. Skipping...
Folder 'GCA_023827335.1_PDT001326419.1' already exists. Skipping...
Folder 'GCA_023827355.1_PDT001326616.1' already exists. Skipping...
Folder 'GCA_023827415.1_PDT001326609.1' already exists. Skipping...
Folder 'GCA_023827435.1_PDT001326607.1' already exists. Skipping...
Folder 'GCA_023827515.1_PDT001326567.1' already exists. Skipping...
Folder 'GCA_023827635.1_PDT001326409.1' already exists. Skipping...
Folder 'GCA_023828655.1_PDT001326545.1' already exists. Skipping...
Folder 'GCA_023830935.1_PDT001326772.1' already exists. Skipping...
Folder 'GCA_023830995.1_PDT001327358.1' already exists. Skipping...
Folder 'GCA_023831035.1_PDT001327356.1' already exists. Skipping...
Folder 'GCA_023833775.1_PDT001331252.1' already exists. Skipping...
Folder 'GCA_023833815.1_PDT001331241.1' already exists. Skipping...
Folder 'GCA_023833855.1_PDT001331240.1' already exists. Skipping...
Folder 'GCA_023834795.1_PDT001335652.1' already exists. Skipping...
Folder 'GCA_023835435.1_PDT001335690.1' already exists. Skipping...
Folder 'GCA_023837225.1_PDT001322330.2' already exists. Skipping...
Folder 'GCA_023873445.1_PDT001329092.1' already exists. Skipping...
Folder 'GCA_023874065.1_PDT001322366.1' already exists. Skipping...
Folder 'GCA_023900895.1_PDT001341725.1' already exists. Skipping...
Folder 'GCA_023900915.1_PDT001341727.1' already exists. Skipping...
Folder 'GCA_023900935.1_PDT001341729.1' already exists. Skipping...
Folder 'GCA_023900955.1_PDT001341728.1' already exists. Skipping...
Folder 'GCA_023901035.1_PDT001341719.1' already exists. Skipping...
Folder 'GCA_023901075.1_PDT001341721.1' already exists. Skipping...
Folder 'GCA_023902295.1_PDT001342270.1' already exists. Skipping...
Folder 'GCA_023902315.1_PDT001342272.1' already exists. Skipping...
Folder 'GCA_023902995.1_PDT001342275.1' already exists. Skipping...
Folder 'GCA_023903015.1_PDT001342273.1' already exists. Skipping...
Folder 'GCA_023903035.1_PDT001342269.1' already exists. Skipping...
Folder 'GCA_023903475.1_PDT001342286.1' already exists. Skipping...
Folder 'GCA_023903635.1_PDT001342283.1' already exists. Skipping...
Folder 'GCA_023936525.1_PDT001347226.1' already exists. Skipping...
Folder 'GCA_023967995.1_PDT001348143.1' already exists. Skipping...
Folder 'GCA_023969025.1_PDT001348138.1' already exists. Skipping...
Folder 'GCA_023969745.1_PDT001348075.1' already exists. Skipping...
Folder 'GCA_023970025.1_PDT001348067.1' already exists. Skipping...
Folder 'GCA_023970165.1_PDT001348056.1' already exists. Skipping...
Folder 'GCA_023970225.1_PDT001348055.1' already exists. Skipping...
Folder 'GCA_023970295.1_PDT001348049.1' already exists. Skipping...
Folder 'GCA_023970315.1_PDT001348048.1' already exists. Skipping...
Folder 'GCA_023970355.1_PDT001348046.1' already exists. Skipping...
Folder 'GCA_023970415.1_PDT001348045.1' already exists. Skipping...
Folder 'GCA_023970895.1_PDT001348020.1' already exists. Skipping...
Folder 'GCA_023970915.1_PDT001348018.1' already exists. Skipping...
Folder 'GCA_023971215.1_PDT001348005.1' already exists. Skipping...
Folder 'GCA_023972295.1_PDT001347927.1' already exists. Skipping...
Folder 'GCA_023972315.1_PDT001347926.1' already exists. Skipping...
Folder 'GCA_023973025.1_PDT001347889.1' already exists. Skipping...
Folder 'GCA_023974405.1_PDT001347820.1' already exists. Skipping...
Folder 'GCA_023975235.1_PDT001347774.1' already exists. Skipping...
Folder 'GCA_023975375.1_PDT001347767.1' already exists. Skipping...
Folder 'GCA_023975475.1_PDT001347763.1' already exists. Skipping...
Folder 'GCA_023975555.1_PDT001347759.1' already exists. Skipping...
Folder 'GCA_023975595.1_PDT001347757.1' already exists. Skipping...
Folder 'GCA_023975615.1_PDT001347755.1' already exists. Skipping...
Folder 'GCA_023976365.1_PDT001347717.1' already exists. Skipping...
Folder 'GCA_023976895.1_PDT001347691.1' already exists. Skipping...
Folder 'GCA_023976955.1_PDT001347690.1' already exists. Skipping...
Folder 'GCA_023977015.1_PDT001347685.1' already exists. Skipping...
Folder 'GCA_023977035.1_PDT001347684.1' already exists. Skipping...
Folder 'GCA_023982855.1_PDT001343189.1' already exists. Skipping...
Folder 'GCA_023982875.1_PDT001343192.1' already exists. Skipping...
Folder 'GCA_023983055.1_PDT001343188.1' already exists. Skipping...
Folder 'GCA_023983215.1_PDT001343177.1' already exists. Skipping...
Folder 'GCA_023983275.1_PDT001343174.1' already exists. Skipping...
Folder 'GCA_023983335.1_PDT001343173.1' already exists. Skipping...
Folder 'GCA_023983555.1_PDT001343190.1' already exists. Skipping...
Folder 'GCA_023983675.1_PDT001343186.1' already exists. Skipping...
Folder 'GCA_023983955.1_PDT001343150.1' already exists. Skipping...
Folder 'GCA_023984055.1_PDT001343141.1' already exists. Skipping...
Folder 'GCA_023984075.1_PDT001343134.1' already exists. Skipping...
Folder 'GCA_023984135.1_PDT001343127.1' already exists. Skipping...
Folder 'GCA_023984175.1_PDT001343128.1' already exists. Skipping...
Folder 'GCA_023984535.1_PDT001343146.1' already exists. Skipping...
Folder 'GCA_023984595.1_PDT001343143.1' already exists. Skipping...
Folder 'GCA_023984675.1_PDT001343138.1' already exists. Skipping...
Folder 'GCA_023984775.1_PDT001343116.1' already exists. Skipping...
Folder 'GCA_023984795.1_PDT001343117.1' already exists. Skipping...
Folder 'GCA_023984855.1_PDT001343112.1' already exists. Skipping...
Folder 'GCA_023984955.1_PDT001343106.1' already exists. Skipping...
Folder 'GCA_023984975.1_PDT001343107.1' already exists. Skipping...
Folder 'GCA_023985055.1_PDT001343101.1' already exists. Skipping...
Folder 'GCA_023986895.1_PDT001343015.1' already exists. Skipping...
Folder 'GCA_023987095.1_PDT001342997.1' already exists. Skipping...
Folder 'GCA_023987115.1_PDT001342996.1' already exists. Skipping...
Folder 'GCA_023989495.1_PDT001342856.1' already exists. Skipping...
Folder 'GCA_023989795.1_PDT001342838.1' already exists. Skipping...
Folder 'GCA_023990295.1_PDT001342837.1' already exists. Skipping...
Folder 'GCA_023995355.1_PDT001339866.1' already exists. Skipping...
Folder 'GCA_023995455.1_PDT001339859.1' already exists. Skipping...
Folder 'GCA_023995495.1_PDT001339857.1' already exists. Skipping...
Folder 'GCA_023995535.1_PDT001339858.1' already exists. Skipping...
Folder 'GCA_023995555.1_PDT001339855.1' already exists. Skipping...
Folder 'GCA_023995615.1_PDT001339862.1' already exists. Skipping...
Folder 'GCA_023995655.1_PDT001339853.1' already exists. Skipping...
Folder 'GCA_023995675.1_PDT001339850.1' already exists. Skipping...
Folder 'GCA_023995695.1_PDT001339852.1' already exists. Skipping...
Folder 'GCA_023995715.1_PDT001339851.1' already exists. Skipping...
Folder 'GCA_023995735.1_PDT001339849.1' already exists. Skipping...
Folder 'GCA_023995755.1_PDT001339846.1' already exists. Skipping...
Folder 'GCA_023995795.1_PDT001339832.1' already exists. Skipping...
Folder 'GCA_023995815.1_PDT001339841.1' already exists. Skipping...
Folder 'GCA_023995835.1_PDT001339812.1' already exists. Skipping...
Folder 'GCA_023995875.1_PDT001339830.1' already exists. Skipping...
Folder 'GCA_023995935.1_PDT001339844.1' already exists. Skipping...
Folder 'GCA_023995975.1_PDT001339825.1' already exists. Skipping...
Folder 'GCA_023995995.1_PDT001339821.1' already exists. Skipping...
Folder 'GCA_023996095.1_PDT001339817.1' already exists. Skipping...
Folder 'GCA_023996135.1_PDT001339840.1' already exists. Skipping...
Folder 'GCA_023996315.1_PDT001339829.1' already exists. Skipping...
Folder 'GCA_023996335.1_PDT001339809.1' already exists. Skipping...
Folder 'GCA_023996355.1_PDT001339828.1' already exists. Skipping...
Folder 'GCA_023996375.1_PDT001339824.1' already exists. Skipping...
Folder 'GCA_023996435.1_PDT001339823.1' already exists. Skipping...
Folder 'GCA_023996515.1_PDT001339810.1' already exists. Skipping...
Folder 'GCA_023996555.1_PDT001339806.1' already exists. Skipping...
Folder 'GCA_023996575.1_PDT001339807.1' already exists. Skipping...
Folder 'GCA_023996635.1_PDT001339802.1' already exists. Skipping...
Folder 'GCA_023999575.1_PDT001339606.1' already exists. Skipping...
Folder 'GCA_023999615.1_PDT001339605.1' already exists. Skipping...
Folder 'GCA_023999635.1_PDT001339603.1' already exists. Skipping...
Folder 'GCA_023999655.1_PDT001339604.1' already exists. Skipping...
Folder 'GCA_023999685.1_PDT001339602.1' already exists. Skipping...
Folder 'GCA_023999715.1_PDT001339607.1' already exists. Skipping...
Folder 'GCA_023999735.1_PDT001339600.1' already exists. Skipping...
Folder 'GCA_023999755.1_PDT001339599.1' already exists. Skipping...
Folder 'GCA_023999775.1_PDT001339598.1' already exists. Skipping...
Folder 'GCA_023999795.1_PDT001339597.1' already exists. Skipping...
Folder 'GCA_024000115.1_PDT001339560.1' already exists. Skipping...
Folder 'GCA_024000195.1_PDT001339562.1' already exists. Skipping...
Folder 'GCA_024000215.1_PDT001339557.1' already exists. Skipping...
Folder 'GCA_024000275.1_PDT001339556.1' already exists. Skipping...
Folder 'GCA_024000395.1_PDT001339551.1' already exists. Skipping...
Folder 'GCA_024000515.1_PDT001339543.1' already exists. Skipping...
Folder 'GCA_024000635.1_PDT001339531.1' already exists. Skipping...
Folder 'GCA_024000675.1_PDT001339528.1' already exists. Skipping...
Folder 'GCA_024000735.1_PDT001339527.1' already exists. Skipping...
Folder 'GCA_024000775.1_PDT001339525.1' already exists. Skipping...
Folder 'GCA_024000795.1_PDT001339524.1' already exists. Skipping...
Folder 'GCA_024000815.1_PDT001339523.1' already exists. Skipping...
Folder 'GCA_024000865.1_PDT001339513.1' already exists. Skipping...
Folder 'GCA_024000945.1_PDT001339518.1' already exists. Skipping...
Folder 'GCA_024000965.1_PDT001339519.1' already exists. Skipping...
Folder 'GCA_024001025.1_PDT001339512.1' already exists. Skipping...
Folder 'GCA_024001065.1_PDT001339514.1' already exists. Skipping...
Folder 'GCA_024001915.1_PDT001339457.1' already exists. Skipping...
Folder 'GCA_024003495.1_PDT001339133.1' already exists. Skipping...
Folder 'GCA_024003915.1_PDT001339076.1' already exists. Skipping...
Folder 'GCA_024011635.1_PDT001337998.3' already exists. Skipping...
Folder 'GCA_024011675.1_PDT001338000.2' already exists. Skipping...
Folder 'GCA_024011795.1_PDT001337996.3' already exists. Skipping...
Folder 'GCA_024011835.1_PDT001337994.3' already exists. Skipping...
Folder 'GCA_024011975.1_PDT001337986.3' already exists. Skipping...
Folder 'GCA_024011995.1_PDT001337985.3' already exists. Skipping...
Folder 'GCA_024012025.1_PDT001337983.3' already exists. Skipping...
Folder 'GCA_024012055.1_PDT001337982.3' already exists. Skipping...
Folder 'GCA_024012195.1_PDT001338300.2' already exists. Skipping...
Folder 'GCA_024012295.1_PDT001338297.2' already exists. Skipping...
Folder 'GCA_024012415.1_PDT001338284.2' already exists. Skipping...
Folder 'GCA_024012675.1_PDT001338735.1' already exists. Skipping...
Folder 'GCA_024012695.1_PDT001338736.1' already exists. Skipping...
Folder 'GCA_024012735.1_PDT001338733.1' already exists. Skipping...
Folder 'GCA_024012755.1_PDT001338732.1' already exists. Skipping...
Folder 'GCA_024012795.1_PDT001338731.1' already exists. Skipping...
Folder 'GCA_024012815.1_PDT001338730.1' already exists. Skipping...
Folder 'GCA_024012835.1_PDT001338726.1' already exists. Skipping...
Folder 'GCA_024012895.1_PDT001338723.1' already exists. Skipping...
Folder 'GCA_024012915.1_PDT001338728.1' already exists. Skipping...
Folder 'GCA_024013035.1_PDT001338379.1' already exists. Skipping...
Folder 'GCA_024013095.1_PDT001338375.1' already exists. Skipping...
Folder 'GCA_024013155.1_PDT001338373.1' already exists. Skipping...
Folder 'GCA_024013175.1_PDT001338380.1' already exists. Skipping...
Folder 'GCA_024013415.1_PDT001338351.1' already exists. Skipping...
Folder 'GCA_024013435.1_PDT001338350.1' already exists. Skipping...
Folder 'GCA_024013535.1_PDT001338342.1' already exists. Skipping...
Folder 'GCA_024013555.1_PDT001338343.1' already exists. Skipping...
Folder 'GCA_024014015.1_PDT001338231.1' already exists. Skipping...
Folder 'GCA_024014055.1_PDT001338208.1' already exists. Skipping...
Folder 'GCA_024014075.1_PDT001338209.1' already exists. Skipping...
Folder 'GCA_024014115.1_PDT001338207.1' already exists. Skipping...
Folder 'GCA_024014155.1_PDT001338194.1' already exists. Skipping...
Folder 'GCA_024052935.1_PDT001349381.1' already exists. Skipping...
Folder 'GCA_024052995.1_PDT001349361.1' already exists. Skipping...
Folder 'GCA_024053235.1_PDT001348711.1' already exists. Skipping...
Folder 'GCA_024057975.1_PDT001349390.1' already exists. Skipping...
Folder 'GCA_024060235.1_PDT001330676.1' already exists. Skipping...
Folder 'GCA_024060255.1_PDT001330675.1' already exists. Skipping...
Folder 'GCA_024060275.1_PDT001330674.1' already exists. Skipping...
Folder 'GCA_024060335.1_PDT001330671.1' already exists. Skipping...
Folder 'GCA_024060355.1_PDT001330668.1' already exists. Skipping...
Folder 'GCA_024060395.1_PDT001330669.1' already exists. Skipping...
Folder 'GCA_024060435.1_PDT001330666.1' already exists. Skipping...
Folder 'GCA_024060455.1_PDT001330665.1' already exists. Skipping...
Folder 'GCA_024060715.1_PDT001330662.1' already exists. Skipping...
Folder 'GCA_024060735.1_PDT001330659.1' already exists. Skipping...
Folder 'GCA_024060885.1_PDT001329090.1' already exists. Skipping...
Folder 'GCA_024060915.1_PDT001329089.1' already exists. Skipping...
Folder 'GCA_024060935.1_PDT001329088.1' already exists. Skipping...
Folder 'GCA_024060975.1_PDT001329087.1' already exists. Skipping...
Folder 'GCA_024061145.1_PDT001349164.1' already exists. Skipping...
Folder 'GCA_024062015.1_PDT001349961.1' already exists. Skipping...
Folder 'GCA_024063575.1_PDT001349967.1' already exists. Skipping...
Folder 'GCA_024064715.1_PDT001349966.1' already exists. Skipping...
Folder 'GCA_024064915.1_PDT001348990.3' already exists. Skipping...
Folder 'GCA_024065455.1_PDT001349146.3' already exists. Skipping...
Folder 'GCA_024065475.1_PDT001349137.3' already exists. Skipping...
Folder 'GCA_024066155.1_PDT001349134.2' already exists. Skipping...
Folder 'GCA_024066195.1_PDT001349132.2' already exists. Skipping...
Folder 'GCA_024066835.1_PDT001348712.1' already exists. Skipping...
Folder 'GCA_024067535.1_PDT001350112.1' already exists. Skipping...
Folder 'GCA_024069395.1_PDT001349145.3' already exists. Skipping...
Folder 'GCA_024069415.1_PDT001349138.3' already exists. Skipping...
Folder 'GCA_024069455.1_PDT001349141.3' already exists. Skipping...

Retreiveing data: 85772it [00:14, 6584.43it/s]

Folder 'GCA_024843345.1_PDT001399444.1' already exists. Skipping...
Folder 'GCA_024843485.1_PDT001399299.1' already exists. Skipping...
Folder 'GCA_024843545.1_PDT001399196.1' already exists. Skipping...
Folder 'GCA_024844405.1_PDT001399036.1' already exists. Skipping...
Folder 'GCA_024844905.1_PDT001398989.1' already exists. Skipping...
Folder 'GCA_024845005.1_PDT001398979.1' already exists. Skipping...
Folder 'GCA_024845485.1_PDT001399102.1' already exists. Skipping...
Folder 'GCA_024845785.1_PDT001399338.1' already exists. Skipping...
Folder 'GCA_024845845.1_PDT001399247.1' already exists. Skipping...
Folder 'GCA_024846175.1_PDT001398987.1' already exists. Skipping...
Folder 'GCA_024854305.1_PDT001407931.1' already exists. Skipping...
Folder 'GCA_024854805.1_PDT001407898.1' already exists. Skipping...
Folder 'GCA_024858845.1_PDT001398431.1' already exists. Skipping...
Folder 'GCA_024858965.1_PDT001398427.1' already exists. Skipping...
Folder 'GCA_024859165.1_PDT001398417.1' already exists. Skipping...
Folder 'GCA_024859305.1_PDT001398406.1' already exists. Skipping...
Folder 'GCA_024859545.1_PDT001398396.1' already exists. Skipping...
Folder 'GCA_024859665.1_PDT001398391.1' already exists. Skipping...
Folder 'GCA_024859765.1_PDT001398386.1' already exists. Skipping...
Folder 'GCA_024860005.1_PDT001398371.1' already exists. Skipping...
Folder 'GCA_024860085.1_PDT001398364.1' already exists. Skipping...
Folder 'GCA_024860125.1_PDT001398366.1' already exists. Skipping...
Folder 'GCA_024860205.1_PDT001398359.1' already exists. Skipping...
Folder 'GCA_024860285.1_PDT001398352.1' already exists. Skipping...
Folder 'GCA_024860345.1_PDT001398354.1' already exists. Skipping...
Folder 'GCA_024860385.1_PDT001398350.1' already exists. Skipping...
Folder 'GCA_024860625.1_PDT001398339.1' already exists. Skipping...
Folder 'GCA_024860635.1_PDT001398340.1' already exists. Skipping...
Folder 'GCA_024860765.1_PDT001398330.1' already exists. Skipping...
Folder 'GCA_024861025.1_PDT001398321.1' already exists. Skipping...
Folder 'GCA_024861485.1_PDT001398297.1' already exists. Skipping...
Folder 'GCA_024861545.1_PDT001398292.1' already exists. Skipping...
Folder 'GCA_024862105.1_PDT001398262.1' already exists. Skipping...
Folder 'GCA_024862125.1_PDT001398260.1' already exists. Skipping...
Folder 'GCA_024862815.1_PDT001398224.1' already exists. Skipping...
Folder 'GCA_024862855.1_PDT001398225.1' already exists. Skipping...
Folder 'GCA_024862915.1_PDT001398221.1' already exists. Skipping...
Folder 'GCA_024862935.1_PDT001398223.1' already exists. Skipping...
Folder 'GCA_024862955.1_PDT001398219.1' already exists. Skipping...
Folder 'GCA_024863025.1_PDT001398217.1' already exists. Skipping...
Folder 'GCA_024863125.1_PDT001398212.1' already exists. Skipping...
Folder 'GCA_024863165.1_PDT001398210.1' already exists. Skipping...
Folder 'GCA_024863205.1_PDT001398207.1' already exists. Skipping...
Folder 'GCA_024863345.1_PDT001398200.1' already exists. Skipping...
Folder 'GCA_024863525.1_PDT001398193.1' already exists. Skipping...
Folder 'GCA_024863705.1_PDT001398180.1' already exists. Skipping...
Folder 'GCA_024863825.1_PDT001398175.1' already exists. Skipping...
Folder 'GCA_024863845.1_PDT001398188.1' already exists. Skipping...
Folder 'GCA_024863905.1_PDT001398172.1' already exists. Skipping...
Folder 'GCA_024864145.1_PDT001398160.1' already exists. Skipping...
Folder 'GCA_024864185.1_PDT001398158.1' already exists. Skipping...
Folder 'GCA_024864305.1_PDT001398151.1' already exists. Skipping...
Folder 'GCA_024864505.1_PDT001398141.1' already exists. Skipping...
Folder 'GCA_024864525.1_PDT001398157.1' already exists. Skipping...
Folder 'GCA_024864785.1_PDT001398126.1' already exists. Skipping...
Folder 'GCA_024865105.1_PDT001398108.1' already exists. Skipping...
Folder 'GCA_024865145.1_PDT001398103.1' already exists. Skipping...
Folder 'GCA_024865245.1_PDT001398100.1' already exists. Skipping...
Folder 'GCA_024865965.1_PDT001398065.1' already exists. Skipping...
Folder 'GCA_024866085.1_PDT001398059.1' already exists. Skipping...
Folder 'GCA_024868425.1_PDT001397962.1' already exists. Skipping...
Folder 'GCA_024868485.1_PDT001397960.1' already exists. Skipping...
Folder 'GCA_024868645.1_PDT001397951.1' already exists. Skipping...
Folder 'GCA_024869615.1_PDT001397871.1' already exists. Skipping...
Folder 'GCA_024869775.1_PDT001397863.1' already exists. Skipping...
Folder 'GCA_024869795.1_PDT001397858.1' already exists. Skipping...
Folder 'GCA_024869845.1_PDT001397854.1' already exists. Skipping...
Folder 'GCA_024869875.1_PDT001397855.1' already exists. Skipping...
Folder 'GCA_024869895.1_PDT001397853.1' already exists. Skipping...
Folder 'GCA_024870045.1_PDT001397850.1' already exists. Skipping...
Folder 'GCA_024870125.1_PDT001397846.1' already exists. Skipping...
Folder 'GCA_024870165.1_PDT001397843.1' already exists. Skipping...
Folder 'GCA_024870405.1_PDT001397834.1' already exists. Skipping...
Folder 'GCA_024870625.1_PDT001407776.1' already exists. Skipping...
Folder 'GCA_024870645.1_PDT001407775.1' already exists. Skipping...
Folder 'GCA_024870965.1_PDT001404392.1' already exists. Skipping...
Folder 'GCA_024872005.1_PDT001397614.1' already exists. Skipping...
Folder 'GCA_024872845.1_PDT001397568.1' already exists. Skipping...
Folder 'GCA_024873385.1_PDT001397536.1' already exists. Skipping...
Folder 'GCA_024873445.1_PDT001397532.1' already exists. Skipping...
Folder 'GCA_024873525.1_PDT001397525.1' already exists. Skipping...
Folder 'GCA_024873625.1_PDT001397523.1' already exists. Skipping...
Folder 'GCA_024873745.1_PDT001397507.1' already exists. Skipping...
Folder 'GCA_024873905.1_PDT001397502.1' already exists. Skipping...
Folder 'GCA_024874065.1_PDT001397494.1' already exists. Skipping...
Folder 'GCA_024874165.1_PDT001397486.1' already exists. Skipping...
Folder 'GCA_024874205.1_PDT001397488.1' already exists. Skipping...
Folder 'GCA_024874385.1_PDT001397476.1' already exists. Skipping...
Folder 'GCA_024874465.1_PDT001397473.1' already exists. Skipping...
Folder 'GCA_024874525.1_PDT001397469.1' already exists. Skipping...
Folder 'GCA_024874545.1_PDT001397470.1' already exists. Skipping...
Folder 'GCA_024874785.1_PDT001397458.1' already exists. Skipping...
Folder 'GCA_024874825.1_PDT001397457.1' already exists. Skipping...
Folder 'GCA_024874945.1_PDT001397454.1' already exists. Skipping...
Folder 'GCA_024874985.1_PDT001397446.1' already exists. Skipping...
Folder 'GCA_024875045.1_PDT001397445.1' already exists. Skipping...
Folder 'GCA_024876205.1_PDT001397384.1' already exists. Skipping...
Folder 'GCA_024876225.1_PDT001397385.1' already exists. Skipping...
Folder 'GCA_024876385.1_PDT001397373.1' already exists. Skipping...
Folder 'GCA_024876585.1_PDT001397364.1' already exists. Skipping...
Folder 'GCA_024890875.1_PDT001396181.1' already exists. Skipping...
Folder 'GCA_024890995.1_PDT001396177.1' already exists. Skipping...
Folder 'GCA_024891075.1_PDT001396170.1' already exists. Skipping...
Folder 'GCA_024891195.1_PDT001396166.1' already exists. Skipping...
Folder 'GCA_024891495.1_PDT001396148.1' already exists. Skipping...
Folder 'GCA_024892735.1_PDT001395988.1' already exists. Skipping...
Folder 'GCA_024892875.1_PDT001395982.1' already exists. Skipping...
Folder 'GCA_024892895.1_PDT001395981.1' already exists. Skipping...
Folder 'GCA_024893255.1_PDT001395958.1' already exists. Skipping...
Folder 'GCA_024905355.1_PDT001395503.1' already exists. Skipping...
Folder 'GCA_024906055.1_PDT001394838.1' already exists. Skipping...
Folder 'GCA_024906115.1_PDT001394836.1' already exists. Skipping...
Folder 'GCA_024906135.1_PDT001394833.1' already exists. Skipping...
Folder 'GCA_024906155.1_PDT001394834.1' already exists. Skipping...
Folder 'GCA_024906165.1_PDT001394832.1' already exists. Skipping...
Folder 'GCA_024906195.1_PDT001394831.1' already exists. Skipping...
Folder 'GCA_024906215.1_PDT001394830.1' already exists. Skipping...
Folder 'GCA_024906255.1_PDT001394827.1' already exists. Skipping...
Folder 'GCA_024906295.1_PDT001394825.1' already exists. Skipping...
Folder 'GCA_024906315.1_PDT001394826.1' already exists. Skipping...
Folder 'GCA_024906335.1_PDT001394823.1' already exists. Skipping...
Folder 'GCA_024906355.1_PDT001394824.1' already exists. Skipping...
Folder 'GCA_024906375.1_PDT001394821.1' already exists. Skipping...
Folder 'GCA_024906395.1_PDT001394822.1' already exists. Skipping...
Folder 'GCA_024906435.1_PDT001394819.1' already exists. Skipping...
Folder 'GCA_024906455.1_PDT001394818.1' already exists. Skipping...
Folder 'GCA_024906515.1_PDT001394817.1' already exists. Skipping...
Folder 'GCA_024906555.1_PDT001394813.1' already exists. Skipping...
Folder 'GCA_024908475.1_PDT001394705.1' already exists. Skipping...
Folder 'GCA_024908645.1_PDT001394698.1' already exists. Skipping...
Folder 'GCA_024908935.1_PDT001394616.1' already exists. Skipping...
Folder 'GCA_024909575.1_PDT001394581.1' already exists. Skipping...
Folder 'GCA_024909655.1_PDT001394578.1' already exists. Skipping...
Folder 'GCA_024909675.1_PDT001394575.1' already exists. Skipping...
Folder 'GCA_024909715.1_PDT001394580.1' already exists. Skipping...
Folder 'GCA_024909735.1_PDT001394573.1' already exists. Skipping...
Folder 'GCA_024909775.1_PDT001394572.1' already exists. Skipping...
Folder 'GCA_024909835.1_PDT001408072.1' already exists. Skipping...
Folder 'GCA_024910655.1_PDT001394568.1' already exists. Skipping...
Folder 'GCA_024910775.1_PDT001394562.1' already exists. Skipping...
Folder 'GCA_024910795.1_PDT001394563.1' already exists. Skipping...
Folder 'GCA_024910815.1_PDT001394564.1' already exists. Skipping...
Folder 'GCA_024910875.1_PDT001394559.1' already exists. Skipping...
Folder 'GCA_024910895.1_PDT001394557.1' already exists. Skipping...
Folder 'GCA_024910935.1_PDT001394556.1' already exists. Skipping...
Folder 'GCA_024910955.1_PDT001394555.1' already exists. Skipping...
Folder 'GCA_024910975.1_PDT001394554.1' already exists. Skipping...
Folder 'GCA_024911275.1_PDT001394538.1' already exists. Skipping...
Folder 'GCA_024911355.1_PDT001394536.1' already exists. Skipping...
Folder 'GCA_024911435.1_PDT001394531.1' already exists. Skipping...
Folder 'GCA_024911445.1_PDT001394530.1' already exists. Skipping...
Folder 'GCA_024911575.1_PDT001394524.1' already exists. Skipping...
Folder 'GCA_024911655.1_PDT001394519.1' already exists. Skipping...
Folder 'GCA_024912795.1_PDT001408071.1' already exists. Skipping...
Folder 'GCA_024920945.1_PDT001394065.1' already exists. Skipping...
Folder 'GCA_024921205.1_PDT001394051.1' already exists. Skipping...
Folder 'GCA_024921245.1_PDT001394050.1' already exists. Skipping...
Folder 'GCA_024921405.1_PDT001394041.1' already exists. Skipping...
Folder 'GCA_024922305.1_PDT001394034.1' already exists. Skipping...
Folder 'GCA_024922365.1_PDT001409146.1' already exists. Skipping...
Folder 'GCA_024922465.1_PDT001409139.1' already exists. Skipping...
Folder 'GCA_024922485.1_PDT001409138.1' already exists. Skipping...
Folder 'GCA_024922685.1_PDT001393995.1' already exists. Skipping...
Folder 'GCA_024922745.1_PDT001393994.1' already exists. Skipping...
Folder 'GCA_024923245.1_PDT001409067.1' already exists. Skipping...
Folder 'GCA_024923265.1_PDT001409068.1' already exists. Skipping...
Folder 'GCA_024923285.1_PDT001409065.1' already exists. Skipping...
Folder 'GCA_024923305.1_PDT001409061.1' already exists. Skipping...
Folder 'GCA_024923485.1_PDT001393993.1' already exists. Skipping...
Folder 'GCA_024927045.1_PDT001408503.1' already exists. Skipping...
Folder 'GCA_024927245.1_PDT001408481.1' already exists. Skipping...
Folder 'GCA_024927265.1_PDT001408467.1' already exists. Skipping...
Folder 'GCA_024927325.1_PDT001408461.1' already exists. Skipping...
Folder 'GCA_024927385.1_PDT001408463.1' already exists. Skipping...
Folder 'GCA_024927405.1_PDT001408465.1' already exists. Skipping...
Folder 'GCA_024927845.1_PDT001408468.1' already exists. Skipping...
Folder 'GCA_024927885.1_PDT001408460.1' already exists. Skipping...
Folder 'GCA_024927985.1_PDT001408459.1' already exists. Skipping...
Folder 'GCA_024928245.1_PDT001408444.1' already exists. Skipping...
Folder 'GCA_024928265.1_PDT001408445.1' already exists. Skipping...
Folder 'GCA_024928305.1_PDT001408441.1' already exists. Skipping...
Folder 'GCA_024928365.1_PDT001408438.1' already exists. Skipping...
Folder 'GCA_024928385.1_PDT001408434.1' already exists. Skipping...
Folder 'GCA_024928425.1_PDT001408435.1' already exists. Skipping...
Folder 'GCA_024928785.1_PDT001408415.1' already exists. Skipping...
Folder 'GCA_024928845.1_PDT001408410.1' already exists. Skipping...
Folder 'GCA_024928885.1_PDT001408412.1' already exists. Skipping...
Folder 'GCA_024928945.1_PDT001408407.1' already exists. Skipping...
Folder 'GCA_024928965.1_PDT001408408.1' already exists. Skipping...
Folder 'GCA_024928975.1_PDT001408406.1' already exists. Skipping...
Folder 'GCA_024929025.1_PDT001408404.1' already exists. Skipping...
Folder 'GCA_024929045.1_PDT001408403.1' already exists. Skipping...
Folder 'GCA_024929185.1_PDT001408397.1' already exists. Skipping...
Folder 'GCA_024929205.1_PDT001408395.1' already exists. Skipping...
Folder 'GCA_024929485.1_PDT001408382.1' already exists. Skipping...
Folder 'GCA_024929505.1_PDT001408381.1' already exists. Skipping...
Folder 'GCA_024929645.1_PDT001408366.1' already exists. Skipping...
Folder 'GCA_024929665.1_PDT001408365.1' already exists. Skipping...
Folder 'GCA_024929685.1_PDT001408364.1' already exists. Skipping...
Folder 'GCA_024929765.1_PDT001408360.1' already exists. Skipping...
Folder 'GCA_024929965.1_PDT001408346.1' already exists. Skipping...
Folder 'GCA_024930665.1_PDT001408310.1' already exists. Skipping...
Folder 'GCA_024930725.1_PDT001408311.1' already exists. Skipping...
Folder 'GCA_024930745.1_PDT001408309.1' already exists. Skipping...
Folder 'GCA_024930785.1_PDT001408308.1' already exists. Skipping...
Folder 'GCA_024931605.1_PDT001408263.1' already exists. Skipping...
Folder 'GCA_024931785.1_PDT001408231.1' already exists. Skipping...
Folder 'GCA_024932225.1_PDT001408200.1' already exists. Skipping...
Folder 'GCA_024932245.1_PDT001408199.1' already exists. Skipping...
Folder 'GCA_024933085.1_PDT001408111.1' already exists. Skipping...
Folder 'GCA_024933245.1_PDT001408096.1' already exists. Skipping...
Folder 'GCA_024934625.1_PDT001393989.1' already exists. Skipping...
Folder 'GCA_024934845.1_PDT001404140.1' already exists. Skipping...
Folder 'GCA_024935325.1_PDT001393977.1' already exists. Skipping...
Folder 'GCA_024935365.1_PDT001393978.1' already exists. Skipping...
Folder 'GCA_024935385.1_PDT001393980.1' already exists. Skipping...
Folder 'GCA_024938345.1_PDT001393738.1' already exists. Skipping...
Folder 'GCA_024938405.1_PDT001393733.1' already exists. Skipping...
Folder 'GCA_024938465.1_PDT001393732.1' already exists. Skipping...
Folder 'GCA_024938685.1_PDT001393722.1' already exists. Skipping...
Folder 'GCA_024944525.1_PDT001392913.1' already exists. Skipping...
Folder 'GCA_024953025.1_PDT001392432.1' already exists. Skipping...
Folder 'GCA_024953745.1_PDT001392384.1' already exists. Skipping...
Folder 'GCA_024953765.1_PDT001392383.1' already exists. Skipping...
Folder 'GCA_024953945.1_PDT001392373.1' already exists. Skipping...
Folder 'GCA_024953985.1_PDT001392372.1' already exists. Skipping...
Folder 'GCA_024954045.1_PDT001392366.1' already exists. Skipping...
Folder 'GCA_024954085.1_PDT001392368.1' already exists. Skipping...
Folder 'GCA_024954185.1_PDT001392360.1' already exists. Skipping...
Folder 'GCA_024954205.1_PDT001392362.1' already exists. Skipping...
Folder 'GCA_024954265.1_PDT001392354.1' already exists. Skipping...
Folder 'GCA_024954325.1_PDT001392355.1' already exists. Skipping...
Folder 'GCA_024954345.1_PDT001392352.1' already exists. Skipping...
Folder 'GCA_024954385.1_PDT001391897.1' already exists. Skipping...
Folder 'GCA_024954485.1_PDT001391896.1' already exists. Skipping...
Folder 'GCA_024954505.1_PDT001391895.1' already exists. Skipping...
Folder 'GCA_024960825.1_PDT001391378.1' already exists. Skipping...
Folder 'GCA_024960865.1_PDT001391377.1' already exists. Skipping...
Folder 'GCA_024960885.1_PDT001391376.1' already exists. Skipping...
Folder 'GCA_024960905.1_PDT001391319.1' already exists. Skipping...
Folder 'GCA_024960965.1_PDT001391318.1' already exists. Skipping...
Folder 'GCA_024960985.1_PDT001391316.1' already exists. Skipping...
Folder 'GCA_024960995.1_PDT001391317.1' already exists. Skipping...
Folder 'GCA_024961025.1_PDT001391315.1' already exists. Skipping...
Folder 'GCA_024961065.1_PDT001391311.1' already exists. Skipping...
Folder 'GCA_024961085.1_PDT001391313.1' already exists. Skipping...
Folder 'GCA_024961105.1_PDT001391312.1' already exists. Skipping...
Folder 'GCA_024961125.1_PDT001391310.1' already exists. Skipping...
Folder 'GCA_024964765.1_PDT001391111.1' already exists. Skipping...
Folder 'GCA_024964785.1_PDT001391108.1' already exists. Skipping...
Folder 'GCA_024964825.1_PDT001391106.1' already exists. Skipping...
Folder 'GCA_024964845.1_PDT001391107.1' already exists. Skipping...
Folder 'GCA_024964865.1_PDT001391098.1' already exists. Skipping...
Folder 'GCA_024964885.1_PDT001391101.1' already exists. Skipping...
Folder 'GCA_024964905.1_PDT001391099.1' already exists. Skipping...
Folder 'GCA_024964925.1_PDT001391103.1' already exists. Skipping...
Folder 'GCA_024964945.1_PDT001391097.1' already exists. Skipping...
Folder 'GCA_024964965.1_PDT001391096.1' already exists. Skipping...
Folder 'GCA_024964985.1_PDT001391095.1' already exists. Skipping...
Folder 'GCA_024965005.1_PDT001391094.1' already exists. Skipping...
Folder 'GCA_024965025.1_PDT001391091.1' already exists. Skipping...
Folder 'GCA_024965045.1_PDT001391090.1' already exists. Skipping...
Folder 'GCA_024965065.1_PDT001391085.1' already exists. Skipping...
Folder 'GCA_024965085.1_PDT001391086.1' already exists. Skipping...
Folder 'GCA_024965105.1_PDT001391088.1' already exists. Skipping...
Folder 'GCA_024965125.1_PDT001391093.1' already exists. Skipping...
Folder 'GCA_024965145.1_PDT001391084.1' already exists. Skipping...
Folder 'GCA_024965165.1_PDT001391080.1' already exists. Skipping...
Folder 'GCA_024965185.1_PDT001391082.1' already exists. Skipping...
Folder 'GCA_024965285.1_PDT001391081.1' already exists. Skipping...
Folder 'GCA_024974515.1_PDT001390486.1' already exists. Skipping...
Folder 'GCA_024976155.1_PDT001390403.1' already exists. Skipping...
Folder 'GCA_024976235.1_PDT001390398.1' already exists. Skipping...
Folder 'GCA_024976355.1_PDT001390393.1' already exists. Skipping...
Folder 'GCA_024976395.1_PDT001390391.1' already exists. Skipping...
Folder 'GCA_024976855.1_PDT001390344.1' already exists. Skipping...
Folder 'GCA_024976875.1_PDT001390343.1' already exists. Skipping...
Folder 'GCA_024976895.1_PDT001390342.1' already exists. Skipping...
Folder 'GCA_024976915.1_PDT001390341.1' already exists. Skipping...
Folder 'GCA_024976935.1_PDT001390340.1' already exists. Skipping...
Folder 'GCA_024977995.1_PDT001390240.1' already exists. Skipping...
Folder 'GCA_024978015.1_PDT001390239.1' already exists. Skipping...
Folder 'GCA_024985415.1_PDT001389826.1' already exists. Skipping...
Folder 'GCA_024985555.1_PDT001389817.1' already exists. Skipping...
Folder 'GCA_024985595.1_PDT001389815.1' already exists. Skipping...
Folder 'GCA_024985695.1_PDT001389810.1' already exists. Skipping...
Folder 'GCA_024985815.1_PDT001389800.1' already exists. Skipping...
Folder 'GCA_024985995.1_PDT001389795.1' already exists. Skipping...
Folder 'GCA_024986035.1_PDT001389791.1' already exists. Skipping...
Folder 'GCA_024986395.1_PDT001389776.1' already exists. Skipping...
Folder 'GCA_024986635.1_PDT001389760.1' already exists. Skipping...
Folder 'GCA_024986655.1_PDT001389762.1' already exists. Skipping...
Folder 'GCA_024986675.1_PDT001389759.1' already exists. Skipping...
Folder 'GCA_024986695.1_PDT001389763.1' already exists. Skipping...

Retreiveing data: 87102it [00:14, 6612.42it/s]

Folder 'GCA_025903205.1_PDT001470215.1' already exists. Skipping...
Folder 'GCA_025904765.1_PDT001470086.1' already exists. Skipping...
Folder 'GCA_025911555.1_PDT001471119.1' already exists. Skipping...
Folder 'GCA_025911655.1_PDT001471116.1' already exists. Skipping...
Folder 'GCA_025911675.1_PDT001471114.1' already exists. Skipping...
Folder 'GCA_025911695.1_PDT001471113.1' already exists. Skipping...
Folder 'GCA_025911715.1_PDT001471112.1' already exists. Skipping...
Folder 'GCA_025911735.1_PDT001471111.1' already exists. Skipping...
Folder 'GCA_025911755.1_PDT001471109.1' already exists. Skipping...
Folder 'GCA_025911795.1_PDT001471108.1' already exists. Skipping...
Folder 'GCA_025911855.1_PDT001471106.1' already exists. Skipping...
Folder 'GCA_025911915.1_PDT001471102.1' already exists. Skipping...
Folder 'GCA_025911995.1_PDT001471098.1' already exists. Skipping...
Folder 'GCA_025912035.1_PDT001471096.1' already exists. Skipping...
Folder 'GCA_025912055.1_PDT001471095.1' already exists. Skipping...
Folder 'GCA_025912155.1_PDT001471090.1' already exists. Skipping...
Folder 'GCA_025916525.1_PDT001470479.1' already exists. Skipping...
Folder 'GCA_025916645.1_PDT001470480.1' already exists. Skipping...
Folder 'GCA_025916775.1_PDT001470477.1' already exists. Skipping...
Folder 'GCA_025916875.1_PDT001470475.1' already exists. Skipping...
Folder 'GCA_025917335.1_PDT001470459.1' already exists. Skipping...
Folder 'GCA_025917395.1_PDT001470456.1' already exists. Skipping...
Folder 'GCA_025917415.1_PDT001470458.1' already exists. Skipping...
Folder 'GCA_025917455.1_PDT001470455.1' already exists. Skipping...
Folder 'GCA_025917495.1_PDT001470452.1' already exists. Skipping...
Folder 'GCA_025917555.1_PDT001470450.1' already exists. Skipping...
Folder 'GCA_025917575.1_PDT001470451.1' already exists. Skipping...
Folder 'GCA_025917595.1_PDT001470448.1' already exists. Skipping...
Folder 'GCA_025917805.1_PDT001470443.1' already exists. Skipping...
Folder 'GCA_025917825.1_PDT001470444.1' already exists. Skipping...
Folder 'GCA_025917865.1_PDT001470445.1' already exists. Skipping...
Folder 'GCA_025917885.1_PDT001470446.1' already exists. Skipping...
Folder 'GCA_025925395.1_PDT001471671.1' already exists. Skipping...
Folder 'GCA_025925545.1_PDT001471911.1' already exists. Skipping...
Folder 'GCA_025925575.1_PDT001471910.1' already exists. Skipping...
Folder 'GCA_025925595.1_PDT001471901.1' already exists. Skipping...
Folder 'GCA_025925635.1_PDT001471899.1' already exists. Skipping...
Folder 'GCA_025925655.1_PDT001471885.1' already exists. Skipping...
Folder 'GCA_025925675.1_PDT001471888.1' already exists. Skipping...
Folder 'GCA_025925695.1_PDT001471853.1' already exists. Skipping...
Folder 'GCA_025925715.1_PDT001471855.1' already exists. Skipping...
Folder 'GCA_025925735.1_PDT001471840.1' already exists. Skipping...
Folder 'GCA_025925755.1_PDT001471841.1' already exists. Skipping...
Folder 'GCA_025925775.1_PDT001471842.1' already exists. Skipping...
Folder 'GCA_025925795.1_PDT001471814.1' already exists. Skipping...
Folder 'GCA_025925815.1_PDT001471839.1' already exists. Skipping...
Folder 'GCA_025931975.1_PDT001471916.1' already exists. Skipping...
Folder 'GCA_025932015.1_PDT001471909.1' already exists. Skipping...
Folder 'GCA_025932215.1_PDT001471872.1' already exists. Skipping...
Folder 'GCA_025932315.1_PDT001471856.1' already exists. Skipping...
Folder 'GCA_025932675.1_PDT001471900.1' already exists. Skipping...
Folder 'GCA_025933385.1_ASM2593338v1' already exists. Skipping...
Folder 'GCA_025933415.1_ASM2593341v1' already exists. Skipping...
Folder 'GCA_025938945.1_ASM2593894v1' already exists. Skipping...
Folder 'GCA_025938995.1_ASM2593899v1' already exists. Skipping...
Folder 'GCA_025939015.1_ASM2593901v1' already exists. Skipping...
Folder 'GCA_025939055.1_ASM2593905v1' already exists. Skipping...
Folder 'GCA_025939095.1_ASM2593909v1' already exists. Skipping...
Folder 'GCA_025939115.1_ASM2593911v1' already exists. Skipping...
Folder 'GCA_025939135.1_ASM2593913v1' already exists. Skipping...
Folder 'GCA_025939145.1_ASM2593914v1' already exists. Skipping...
Folder 'GCA_025939175.1_ASM2593917v1' already exists. Skipping...
Folder 'GCA_025939195.1_ASM2593919v1' already exists. Skipping...
Folder 'GCA_025939215.1_ASM2593921v1' already exists. Skipping...
Folder 'GCA_025939235.1_ASM2593923v1' already exists. Skipping...
Folder 'GCA_025939255.1_ASM2593925v1' already exists. Skipping...
Folder 'GCA_025939275.1_ASM2593927v1' already exists. Skipping...
Folder 'GCA_025939295.1_ASM2593929v1' already exists. Skipping...
Folder 'GCA_025939335.1_ASM2593933v1' already exists. Skipping...
Folder 'GCA_025939365.1_ASM2593936v1' already exists. Skipping...
Folder 'GCA_025939385.1_ASM2593938v1' already exists. Skipping...
Folder 'GCA_025939395.1_ASM2593939v1' already exists. Skipping...
Folder 'GCA_025939425.1_ASM2593942v1' already exists. Skipping...
Folder 'GCA_025939445.1_ASM2593944v1' already exists. Skipping...
Folder 'GCA_025939455.1_ASM2593945v1' already exists. Skipping...
Folder 'GCA_025939485.1_ASM2593948v1' already exists. Skipping...
Folder 'GCA_025939525.1_ASM2593952v1' already exists. Skipping...
Folder 'GCA_025939565.1_ASM2593956v1' already exists. Skipping...
Folder 'GCA_025939585.1_ASM2593958v1' already exists. Skipping...
Folder 'GCA_025939605.1_ASM2593960v1' already exists. Skipping...
Folder 'GCA_025939625.1_ASM2593962v1' already exists. Skipping...
Folder 'GCA_025939645.1_ASM2593964v1' already exists. Skipping...
Folder 'GCA_025939665.1_ASM2593966v1' already exists. Skipping...
Folder 'GCA_025939685.1_ASM2593968v1' already exists. Skipping...
Folder 'GCA_025939705.1_ASM2593970v1' already exists. Skipping...
Folder 'GCA_025939725.1_ASM2593972v1' already exists. Skipping...
Folder 'GCA_025939745.1_ASM2593974v1' already exists. Skipping...
Folder 'GCA_025939765.1_ASM2593976v1' already exists. Skipping...
Folder 'GCA_025939785.1_ASM2593978v1' already exists. Skipping...
Folder 'GCA_025939805.1_ASM2593980v1' already exists. Skipping...
Folder 'GCA_025939815.1_ASM2593981v1' already exists. Skipping...
Folder 'GCA_025939845.1_ASM2593984v1' already exists. Skipping...
Folder 'GCA_025939865.1_ASM2593986v1' already exists. Skipping...
Folder 'GCA_025939885.1_ASM2593988v1' already exists. Skipping...
Folder 'GCA_025939905.1_ASM2593990v1' already exists. Skipping...
Folder 'GCA_025939925.1_ASM2593992v1' already exists. Skipping...
Folder 'GCA_025939945.1_ASM2593994v1' already exists. Skipping...
Folder 'GCA_025939965.1_ASM2593996v1' already exists. Skipping...
Folder 'GCA_025939985.1_ASM2593998v1' already exists. Skipping...
Folder 'GCA_025940005.1_ASM2594000v1' already exists. Skipping...
Folder 'GCA_025940015.1_ASM2594001v1' already exists. Skipping...
Folder 'GCA_025940045.1_ASM2594004v1' already exists. Skipping...
Folder 'GCA_025940085.1_ASM2594008v1' already exists. Skipping...
Folder 'GCA_025940095.1_ASM2594009v1' already exists. Skipping...
Folder 'GCA_025940125.1_ASM2594012v1' already exists. Skipping...
Folder 'GCA_025940135.1_ASM2594013v1' already exists. Skipping...
Folder 'GCA_025940145.1_ASM2594014v1' already exists. Skipping...
Folder 'GCA_025940185.1_ASM2594018v1' already exists. Skipping...
Folder 'GCA_025940205.1_ASM2594020v1' already exists. Skipping...
Folder 'GCA_025940215.1_ASM2594021v1' already exists. Skipping...
Folder 'GCA_025940225.1_ASM2594022v1' already exists. Skipping...
Folder 'GCA_025940265.1_ASM2594026v1' already exists. Skipping...
Folder 'GCA_025940285.1_ASM2594028v1' already exists. Skipping...
Folder 'GCA_025940295.1_ASM2594029v1' already exists. Skipping...
Folder 'GCA_025940335.1_ASM2594033v1' already exists. Skipping...
Folder 'GCA_025940365.1_ASM2594036v1' already exists. Skipping...
Folder 'GCA_025940385.1_ASM2594038v1' already exists. Skipping...
Folder 'GCA_025940395.1_ASM2594039v1' already exists. Skipping...
Folder 'GCA_025940425.1_ASM2594042v1' already exists. Skipping...
Folder 'GCA_025940435.1_ASM2594043v1' already exists. Skipping...
Folder 'GCA_025940475.1_ASM2594047v1' already exists. Skipping...
Folder 'GCA_025940505.1_ASM2594050v1' already exists. Skipping...
Folder 'GCA_025940525.1_ASM2594052v1' already exists. Skipping...
Folder 'GCA_025940545.1_ASM2594054v1' already exists. Skipping...
Folder 'GCA_025940565.1_ASM2594056v1' already exists. Skipping...
Folder 'GCA_025940605.1_ASM2594060v1' already exists. Skipping...
Folder 'GCA_025940625.1_ASM2594062v1' already exists. Skipping...
Folder 'GCA_025940645.1_ASM2594064v1' already exists. Skipping...
Folder 'GCA_025940665.1_ASM2594066v1' already exists. Skipping...
Folder 'GCA_025940685.1_ASM2594068v1' already exists. Skipping...
Folder 'GCA_025940705.1_ASM2594070v1' already exists. Skipping...
Folder 'GCA_025940745.1_ASM2594074v1' already exists. Skipping...
Folder 'GCA_025940755.1_ASM2594075v1' already exists. Skipping...
Folder 'GCA_025940785.1_ASM2594078v1' already exists. Skipping...
Folder 'GCA_025940805.1_ASM2594080v1' already exists. Skipping...
Folder 'GCA_025940815.1_ASM2594081v1' already exists. Skipping...
Folder 'GCA_025940825.1_ASM2594082v1' already exists. Skipping...
Folder 'GCA_025940865.1_ASM2594086v1' already exists. Skipping...
Folder 'GCA_025940875.1_ASM2594087v1' already exists. Skipping...
Folder 'GCA_025940905.1_ASM2594090v1' already exists. Skipping...
Folder 'GCA_025940925.1_ASM2594092v1' already exists. Skipping...
Folder 'GCA_025940935.1_ASM2594093v1' already exists. Skipping...
Folder 'GCA_025940965.1_ASM2594096v1' already exists. Skipping...
Folder 'GCA_025940985.1_ASM2594098v1' already exists. Skipping...
Folder 'GCA_025941005.1_ASM2594100v1' already exists. Skipping...
Folder 'GCA_025941015.1_ASM2594101v1' already exists. Skipping...
Folder 'GCA_025941045.1_ASM2594104v1' already exists. Skipping...
Folder 'GCA_025941065.1_ASM2594106v1' already exists. Skipping...
Folder 'GCA_025941085.1_ASM2594108v1' already exists. Skipping...
Folder 'GCA_025941105.1_ASM2594110v1' already exists. Skipping...
Folder 'GCA_025941125.1_ASM2594112v1' already exists. Skipping...
Folder 'GCA_025941145.1_ASM2594114v1' already exists. Skipping...
Folder 'GCA_025941165.1_ASM2594116v1' already exists. Skipping...
Folder 'GCA_025941175.1_ASM2594117v1' already exists. Skipping...
Folder 'GCA_025941185.1_ASM2594118v1' already exists. Skipping...
Folder 'GCA_025941205.1_ASM2594120v1' already exists. Skipping...
Folder 'GCA_025941245.1_ASM2594124v1' already exists. Skipping...
Folder 'GCA_025941265.1_ASM2594126v1' already exists. Skipping...
Folder 'GCA_025941275.1_ASM2594127v1' already exists. Skipping...
Folder 'GCA_025941285.1_ASM2594128v1' already exists. Skipping...
Folder 'GCA_025941325.1_ASM2594132v1' already exists. Skipping...
Folder 'GCA_025941345.1_ASM2594134v1' already exists. Skipping...
Folder 'GCA_025941365.1_ASM2594136v1' already exists. Skipping...
Folder 'GCA_025941375.1_ASM2594137v1' already exists. Skipping...
Folder 'GCA_025941405.1_ASM2594140v1' already exists. Skipping...
Folder 'GCA_025941425.1_ASM2594142v1' already exists. Skipping...
Folder 'GCA_025941445.1_ASM2594144v1' already exists. Skipping...
Folder 'GCA_025941465.1_ASM2594146v1' already exists. Skipping...
Folder 'GCA_025941525.1_ASM2594152v1' already exists. Skipping...
Folder 'GCA_025941545.1_ASM2594154v1' already exists. Skipping...
Folder 'GCA_025942415.1_ASM2594241v1' already exists. Skipping...
Folder 'GCA_025942455.1_ASM2594245v1' already exists. Skipping...
Folder 'GCA_025942465.1_ASM2594246v1' already exists. Skipping...
Folder 'GCA_025942505.1_ASM2594250v1' already exists. Skipping...
Folder 'GCA_025942515.1_ASM2594251v1' already exists. Skipping...
Folder 'GCA_025942545.1_ASM2594254v1' already exists. Skipping...
Folder 'GCA_025942555.1_ASM2594255v1' already exists. Skipping...
Folder 'GCA_025942585.1_ASM2594258v1' already exists. Skipping...
Folder 'GCA_025942605.1_ASM2594260v1' already exists. Skipping...
Folder 'GCA_025942615.1_ASM2594261v1' already exists. Skipping...
Folder 'GCA_025942645.1_ASM2594264v1' already exists. Skipping...
Folder 'GCA_025942665.1_ASM2594266v1' already exists. Skipping...
Folder 'GCA_025942675.1_ASM2594267v1' already exists. Skipping...
Folder 'GCA_025942705.1_ASM2594270v1' already exists. Skipping...
Folder 'GCA_025942715.1_ASM2594271v1' already exists. Skipping...
Folder 'GCA_025942745.1_ASM2594274v1' already exists. Skipping...
Folder 'GCA_025942765.1_ASM2594276v1' already exists. Skipping...
Folder 'GCA_025942785.1_ASM2594278v1' already exists. Skipping...
Folder 'GCA_025942805.1_ASM2594280v1' already exists. Skipping...
Folder 'GCA_025942825.1_ASM2594282v1' already exists. Skipping...
Folder 'GCA_025942845.1_ASM2594284v1' already exists. Skipping...
Folder 'GCA_025942905.1_ASM2594290v1' already exists. Skipping...
Folder 'GCA_025942925.1_ASM2594292v1' already exists. Skipping...
Folder 'GCA_025942945.1_ASM2594294v1' already exists. Skipping...
Folder 'GCA_025942965.1_ASM2594296v1' already exists. Skipping...
Folder 'GCA_025942975.1_ASM2594297v1' already exists. Skipping...
Folder 'GCA_025943005.1_ASM2594300v1' already exists. Skipping...
Folder 'GCA_025943025.1_ASM2594302v1' already exists. Skipping...
Folder 'GCA_025943045.1_ASM2594304v1' already exists. Skipping...
Folder 'GCA_025943065.1_ASM2594306v1' already exists. Skipping...
Folder 'GCA_025943085.1_ASM2594308v1' already exists. Skipping...
Folder 'GCA_025943095.1_ASM2594309v1' already exists. Skipping...
Folder 'GCA_025943125.1_ASM2594312v1' already exists. Skipping...
Folder 'GCA_025943135.1_ASM2594313v1' already exists. Skipping...
Folder 'GCA_025943165.1_ASM2594316v1' already exists. Skipping...
Folder 'GCA_025943205.1_ASM2594320v1' already exists. Skipping...
Folder 'GCA_025943245.1_ASM2594324v1' already exists. Skipping...
Folder 'GCA_025943265.1_ASM2594326v1' already exists. Skipping...
Folder 'GCA_025943285.1_ASM2594328v1' already exists. Skipping...
Folder 'GCA_025943305.1_ASM2594330v1' already exists. Skipping...
Folder 'GCA_025943325.1_ASM2594332v1' already exists. Skipping...
Folder 'GCA_025943335.1_ASM2594333v1' already exists. Skipping...
Folder 'GCA_025943365.1_ASM2594336v1' already exists. Skipping...
Folder 'GCA_025943385.1_ASM2594338v1' already exists. Skipping...
Folder 'GCA_025943395.1_ASM2594339v1' already exists. Skipping...
Folder 'GCA_025943425.1_ASM2594342v1' already exists. Skipping...
Folder 'GCA_025943445.1_ASM2594344v1' already exists. Skipping...
Folder 'GCA_025943465.1_ASM2594346v1' already exists. Skipping...
Folder 'GCA_025943485.1_ASM2594348v1' already exists. Skipping...
Folder 'GCA_025943505.1_ASM2594350v1' already exists. Skipping...
Folder 'GCA_025943525.1_ASM2594352v1' already exists. Skipping...
Folder 'GCA_025943545.1_ASM2594354v1' already exists. Skipping...
Folder 'GCA_025943565.1_ASM2594356v1' already exists. Skipping...
Folder 'GCA_025943575.1_ASM2594357v1' already exists. Skipping...
Folder 'GCA_025943625.1_ASM2594362v1' already exists. Skipping...
Folder 'GCA_025943665.1_ASM2594366v1' already exists. Skipping...
Folder 'GCA_025943685.1_ASM2594368v1' already exists. Skipping...
Folder 'GCA_025943695.1_ASM2594369v1' already exists. Skipping...
Folder 'GCA_025943725.1_ASM2594372v1' already exists. Skipping...
Folder 'GCA_025943745.1_ASM2594374v1' already exists. Skipping...
Folder 'GCA_025943765.1_ASM2594376v1' already exists. Skipping...
Folder 'GCA_025943775.1_ASM2594377v1' already exists. Skipping...
Folder 'GCA_025943805.1_ASM2594380v1' already exists. Skipping...
Folder 'GCA_025943825.1_ASM2594382v1' already exists. Skipping...
Folder 'GCA_025943845.1_ASM2594384v1' already exists. Skipping...
Folder 'GCA_025943865.1_ASM2594386v1' already exists. Skipping...
Folder 'GCA_025943885.1_ASM2594388v1' already exists. Skipping...
Folder 'GCA_025943905.1_ASM2594390v1' already exists. Skipping...
Folder 'GCA_025943925.1_ASM2594392v1' already exists. Skipping...
Folder 'GCA_025944065.1_PDT001471986.1' already exists. Skipping...
Folder 'GCA_025944105.1_PDT001471987.1' already exists. Skipping...
Folder 'GCA_025945425.1_PDT001471993.1' already exists. Skipping...
Folder 'GCA_025945465.1_PDT001471991.1' already exists. Skipping...
Folder 'GCA_025945475.1_PDT001471989.1' already exists. Skipping...
Folder 'GCA_025945505.1_PDT001471990.1' already exists. Skipping...
Folder 'GCA_025945525.1_PDT001471988.1' already exists. Skipping...
Folder 'GCA_025952565.1_PDT001473029.1' already exists. Skipping...
Folder 'GCA_025952605.1_PDT001473025.1' already exists. Skipping...
Folder 'GCA_025953365.1_PDT001472978.1' already exists. Skipping...
Folder 'GCA_025953445.1_PDT001472977.1' already exists. Skipping...
Folder 'GCA_025953465.1_PDT001472974.1' already exists. Skipping...
Folder 'GCA_025953485.1_PDT001472976.1' already exists. Skipping...
Folder 'GCA_025953525.1_PDT001472975.1' already exists. Skipping...
Folder 'GCA_025954205.1_PDT001473028.1' already exists. Skipping...
Folder 'GCA_025966635.1_PDT001473497.1' already exists. Skipping...
Folder 'GCA_025966655.1_PDT001473544.1' already exists. Skipping...
Folder 'GCA_025966675.1_PDT001473495.1' already exists. Skipping...
Folder 'GCA_025966735.1_PDT001473496.1' already exists. Skipping...
Folder 'GCA_025967275.1_PDT001473774.1' already exists. Skipping...
Folder 'GCA_025967325.1_PDT001473776.1' already exists. Skipping...
Folder 'GCA_025967385.1_PDT001473775.1' already exists. Skipping...
Folder 'GCA_026034455.1_PDT001480032.1' already exists. Skipping...
Folder 'GCA_026034475.1_PDT001480029.1' already exists. Skipping...
Folder 'GCA_026034495.1_PDT001480030.1' already exists. Skipping...
Folder 'GCA_026034515.1_PDT001480028.1' already exists. Skipping...
Folder 'GCA_026034535.1_PDT001480026.1' already exists. Skipping...
Folder 'GCA_026034555.1_PDT001480023.1' already exists. Skipping...
Folder 'GCA_026034575.1_PDT001480022.1' already exists. Skipping...
Folder 'GCA_026034595.1_PDT001480020.1' already exists. Skipping...
Folder 'GCA_026034605.1_PDT001480021.1' already exists. Skipping...
Folder 'GCA_026034635.1_PDT001480018.1' already exists. Skipping...
Folder 'GCA_026034655.1_PDT001480019.1' already exists. Skipping...
Folder 'GCA_026034675.1_PDT001480017.1' already exists. Skipping...
Folder 'GCA_026034695.1_PDT001480016.1' already exists. Skipping...
Folder 'GCA_026034715.1_PDT001480015.1' already exists. Skipping...
Folder 'GCA_026034735.1_PDT001480013.1' already exists. Skipping...
Folder 'GCA_026034755.1_PDT001480008.1' already exists. Skipping...
Folder 'GCA_026034775.1_PDT001480006.1' already exists. Skipping...
Folder 'GCA_026034795.1_PDT001480002.1' already exists. Skipping...
Folder 'GCA_026034805.1_PDT001480004.1' already exists. Skipping...
Folder 'GCA_026036455.1_PDT001480027.1' already exists. Skipping...
Folder 'GCA_026036475.1_PDT001480024.1' already exists. Skipping...
Folder 'GCA_026036495.1_PDT001480014.1' already exists. Skipping...
Folder 'GCA_026036515.1_PDT001480012.1' already exists. Skipping...
Folder 'GCA_026039055.1_PDT001480025.1' already exists. Skipping...
Folder 'GCA_026039095.1_PDT001480011.1' already exists. Skipping...
Folder 'GCA_026039895.1_PDT001480031.1' already exists. Skipping...
Folder 'GCA_026040795.1_PDT001476870.1' already exists. Skipping...
Folder 'GCA_026040815.1_PDT001476869.1' already exists. Skipping...
Folder 'GCA_026041565.1_PDT001476848.1' already exists. Skipping...
Folder 'GCA_026041695.1_PDT001476845.1' already exists. Skipping...
Folder 'GCA_026041715.1_PDT001476843.1' already exists. Skipping...
Folder 'GCA_026048455.1_PDT001480327.1' already exists. Skipping...
Folder 'GCA_026048475.1_PDT001480328.1' already exists. Skipping...
Folder 'GCA_026050735.1_PDT001476329.1' already exists. Skipping...
Folder 'GCA_026050775.1_PDT001476328.1' already exists. Skipping...
Folder 'GCA_026050835.1_PDT001476325.1' already exists. Skipping...
Folder 'GCA_026050855.1_PDT001476324.1' already exists. Skipping...
Folder 'GCA_026053235.1_PDT001480737.1' already exists. Skipping...

Retreiveing data: 88432it [00:14, 6627.48it/s]

Folder 'GCA_027975245.1_PDT001581495.1' already exists. Skipping...
Folder 'GCA_027975405.1_PDT001581481.1' already exists. Skipping...
Folder 'GCA_027976525.1_PDT001581489.1' already exists. Skipping...
Folder 'GCA_027993245.1_PDT001577065.1' already exists. Skipping...
Folder 'GCA_027993265.1_PDT001577063.1' already exists. Skipping...
Folder 'GCA_027993345.1_PDT001577059.1' already exists. Skipping...
Folder 'GCA_027993365.1_PDT001577058.1' already exists. Skipping...
Folder 'GCA_027993805.1_PDT001577037.1' already exists. Skipping...
Folder 'GCA_027993825.1_PDT001577035.1' already exists. Skipping...
Folder 'GCA_027994085.1_PDT001577010.1' already exists. Skipping...
Folder 'GCA_027994205.1_PDT001577009.1' already exists. Skipping...
Folder 'GCA_027994565.1_PDT001576985.1' already exists. Skipping...
Folder 'GCA_027994785.1_PDT001576976.1' already exists. Skipping...
Folder 'GCA_027994795.1_PDT001576975.1' already exists. Skipping...
Folder 'GCA_027994845.1_PDT001576972.1' already exists. Skipping...
Folder 'GCA_027994905.1_PDT001576970.1' already exists. Skipping...
Folder 'GCA_027994945.1_PDT001576966.1' already exists. Skipping...
Folder 'GCA_027995005.1_PDT001576964.1' already exists. Skipping...
Folder 'GCA_027995045.1_PDT001576962.1' already exists. Skipping...
Folder 'GCA_027995105.1_PDT001576953.1' already exists. Skipping...
Folder 'GCA_027995125.1_PDT001576952.1' already exists. Skipping...
Folder 'GCA_027995165.1_PDT001576956.1' already exists. Skipping...
Folder 'GCA_027995185.1_PDT001576955.1' already exists. Skipping...
Folder 'GCA_027995445.1_PDT001576920.1' already exists. Skipping...
Folder 'GCA_027996665.1_PDT001576827.1' already exists. Skipping...
Folder 'GCA_027996685.1_PDT001576828.1' already exists. Skipping...
Folder 'GCA_027996725.1_PDT001576826.1' already exists. Skipping...
Folder 'GCA_027996845.1_PDT001576819.1' already exists. Skipping...
Folder 'GCA_027996925.1_PDT001576814.1' already exists. Skipping...
Folder 'GCA_027996945.1_PDT001576812.1' already exists. Skipping...
Folder 'GCA_027996965.1_PDT001576813.1' already exists. Skipping...
Folder 'GCA_028001665.1_PDT001579591.1' already exists. Skipping...
Folder 'GCA_028001705.1_PDT001579590.1' already exists. Skipping...
Folder 'GCA_028001725.1_PDT001579589.1' already exists. Skipping...
Folder 'GCA_028012555.1_PDT001575320.1' already exists. Skipping...
Folder 'GCA_028012885.1_PDT001575305.1' already exists. Skipping...
Folder 'GCA_028012945.1_PDT001575303.1' already exists. Skipping...
Folder 'GCA_028013005.1_PDT001575298.1' already exists. Skipping...
Folder 'GCA_028013025.1_PDT001575299.1' already exists. Skipping...
Folder 'GCA_028013745.1_PDT001575236.1' already exists. Skipping...
Folder 'GCA_028018125.1_PDT001573433.1' already exists. Skipping...
Folder 'GCA_028018145.1_PDT001573432.1' already exists. Skipping...
Folder 'GCA_028018225.1_PDT001573428.1' already exists. Skipping...
Folder 'GCA_028018415.1_PDT001573418.1' already exists. Skipping...
Folder 'GCA_028018435.1_PDT001573417.1' already exists. Skipping...
Folder 'GCA_028018515.1_PDT001573414.1' already exists. Skipping...
Folder 'GCA_028018545.1_PDT001573412.1' already exists. Skipping...
Folder 'GCA_028018595.1_PDT001573411.1' already exists. Skipping...
Folder 'GCA_028018615.1_PDT001573406.1' already exists. Skipping...
Folder 'GCA_028018695.1_PDT001573407.1' already exists. Skipping...
Folder 'GCA_028018715.1_PDT001573405.1' already exists. Skipping...
Folder 'GCA_028018825.1_PDT001573401.1' already exists. Skipping...
Folder 'GCA_028018875.1_PDT001573400.1' already exists. Skipping...
Folder 'GCA_028018895.1_PDT001573397.1' already exists. Skipping...
Folder 'GCA_028019275.1_PDT001573142.1' already exists. Skipping...
Folder 'GCA_028019305.1_PDT001573140.1' already exists. Skipping...
Folder 'GCA_028019345.1_PDT001573139.1' already exists. Skipping...
Folder 'GCA_028019365.1_PDT001573141.1' already exists. Skipping...
Folder 'GCA_028022315.1_PDT001581835.1' already exists. Skipping...
Folder 'GCA_028023395.1_PDT001581834.1' already exists. Skipping...
Folder 'GCA_028027945.1_PDT001582145.1' already exists. Skipping...
Folder 'GCA_028027985.1_PDT001582138.1' already exists. Skipping...
Folder 'GCA_028035105.1_PDT001582195.1' already exists. Skipping...
Folder 'GCA_028036075.1_PDT001581509.1' already exists. Skipping...
Folder 'GCA_028036275.1_PDT001581508.1' already exists. Skipping...
Folder 'GCA_028036355.1_PDT001582189.1' already exists. Skipping...
Folder 'GCA_028037575.1_PDT001576960.1' already exists. Skipping...
Folder 'GCA_028038685.1_PDT001582199.1' already exists. Skipping...
Folder 'GCA_028038845.1_PDT001582187.1' already exists. Skipping...
Folder 'GCA_028038915.1_PDT001582178.1' already exists. Skipping...
Folder 'GCA_028038955.1_PDT001582174.1' already exists. Skipping...
Folder 'GCA_028039005.1_PDT001582173.1' already exists. Skipping...
Folder 'GCA_028039035.1_PDT001582153.1' already exists. Skipping...
Folder 'GCA_028039055.1_PDT001582151.1' already exists. Skipping...
Folder 'GCA_028039085.1_PDT001582148.1' already exists. Skipping...
Folder 'GCA_028039145.1_PDT001582149.1' already exists. Skipping...
Folder 'GCA_028039165.1_PDT001582147.1' already exists. Skipping...
Folder 'GCA_028039235.1_PDT001582150.1' already exists. Skipping...
Folder 'GCA_028039295.1_PDT001582197.1' already exists. Skipping...
Folder 'GCA_028039355.1_PDT001582193.1' already exists. Skipping...
Folder 'GCA_028040235.1_PDT001582139.1' already exists. Skipping...
Folder 'GCA_028045415.1_PDT001581790.1' already exists. Skipping...
Folder 'GCA_028046235.1_PDT001579594.1' already exists. Skipping...
Folder 'GCA_028049035.1_PDT001582221.1' already exists. Skipping...
Folder 'GCA_028056375.1_PDT001562925.1' already exists. Skipping...
Folder 'GCA_028056435.1_PDT001538975.1' already exists. Skipping...
Folder 'GCA_028056455.1_PDT001538973.1' already exists. Skipping...
Folder 'GCA_028057895.1_PDT001582425.1' already exists. Skipping...
Folder 'GCA_028057915.1_PDT001582424.1' already exists. Skipping...
Folder 'GCA_028057955.1_PDT001582421.1' already exists. Skipping...
Folder 'GCA_028059015.1_PDT001582426.1' already exists. Skipping...
Folder 'GCA_028059115.1_PDT001582416.1' already exists. Skipping...
Folder 'GCA_028068455.1_PDT001582880.1' already exists. Skipping...
Folder 'GCA_028068475.1_PDT001582873.1' already exists. Skipping...
Folder 'GCA_028068635.1_PDT001582874.1' already exists. Skipping...
Folder 'GCA_028068655.1_PDT001582876.1' already exists. Skipping...
Folder 'GCA_028069515.1_PDT001582881.1' already exists. Skipping...
Folder 'GCA_028069855.1_PDT001582879.1' already exists. Skipping...
Folder 'GCA_028069875.1_PDT001582877.1' already exists. Skipping...
Folder 'GCA_028069895.1_PDT001582878.1' already exists. Skipping...
Folder 'GCA_028069915.1_PDT001582875.1' already exists. Skipping...
Folder 'GCA_028069975.1_PDT001582872.1' already exists. Skipping...
Folder 'GCA_028073315.1_PDT000949349.2' already exists. Skipping...
Folder 'GCA_028073805.1_PDT001583310.1' already exists. Skipping...
Folder 'GCA_028075055.1_PDT001583621.1' already exists. Skipping...
Folder 'GCA_028077995.1_PDT001583619.1' already exists. Skipping...
Folder 'GCA_028086305.1_PDT001585932.1' already exists. Skipping...
Folder 'GCA_028086455.1_PDT001585933.1' already exists. Skipping...
Folder 'GCA_028096895.1_PDT001585200.1' already exists. Skipping...
Folder 'GCA_028096985.1_PDT001585197.1' already exists. Skipping...
Folder 'GCA_028097005.1_PDT001585196.1' already exists. Skipping...
Folder 'GCA_028097025.1_PDT001585202.1' already exists. Skipping...
Folder 'GCA_028097075.1_PDT001585201.1' already exists. Skipping...
Folder 'GCA_028097105.1_PDT001585198.1' already exists. Skipping...
Folder 'GCA_028097185.1_PDT001585194.1' already exists. Skipping...
Folder 'GCA_028098635.1_PDT001583990.1' already exists. Skipping...
Folder 'GCA_028098695.1_PDT001583980.1' already exists. Skipping...
Folder 'GCA_028098725.1_PDT001583981.1' already exists. Skipping...
Folder 'GCA_028098755.1_PDT001583979.1' already exists. Skipping...
Folder 'GCA_028098785.1_PDT001583978.1' already exists. Skipping...
Folder 'GCA_028098965.1_PDT001583764.1' already exists. Skipping...
Folder 'GCA_028098995.1_PDT001583761.1' already exists. Skipping...
Folder 'GCA_028099025.1_PDT001583760.1' already exists. Skipping...
Folder 'GCA_028099045.1_PDT001583763.1' already exists. Skipping...
Folder 'GCA_028099065.1_PDT001583762.1' already exists. Skipping...
Folder 'GCA_028099145.1_PDT001583759.1' already exists. Skipping...
Folder 'GCA_028103405.1_PDT001586275.1' already exists. Skipping...
Folder 'GCA_028103535.1_PDT001586271.1' already exists. Skipping...
Folder 'GCA_028104585.1_PDT001586262.1' already exists. Skipping...
Folder 'GCA_028104655.1_PDT001586259.1' already exists. Skipping...
Folder 'GCA_028104765.1_PDT001586258.1' already exists. Skipping...
Folder 'GCA_028105925.1_PDT001586272.1' already exists. Skipping...
Folder 'GCA_028106025.1_PDT001586249.1' already exists. Skipping...
Folder 'GCA_028108105.1_PDT001586269.1' already exists. Skipping...
Folder 'GCA_028108155.1_PDT001586257.1' already exists. Skipping...
Folder 'GCA_028113125.1_PDT001586347.1' already exists. Skipping...
Folder 'GCA_028116065.1_PDT001589369.1' already exists. Skipping...
Folder 'GCA_028116145.1_PDT001589356.1' already exists. Skipping...
Folder 'GCA_028116165.1_PDT001589366.1' already exists. Skipping...
Folder 'GCA_028116805.1_PDT001589229.1' already exists. Skipping...
Folder 'GCA_028116865.1_PDT001589219.1' already exists. Skipping...
Folder 'GCA_028116945.1_PDT001589198.1' already exists. Skipping...
Folder 'GCA_028118985.1_PDT001589246.1' already exists. Skipping...
Folder 'GCA_028119145.1_PDT001589188.1' already exists. Skipping...
Folder 'GCA_028119225.1_PDT001589178.1' already exists. Skipping...
Folder 'GCA_028119305.1_PDT001589168.1' already exists. Skipping...
Folder 'GCA_028119325.1_PDT001589165.1' already exists. Skipping...
Folder 'GCA_028125195.1_PDT001589164.1' already exists. Skipping...
Folder 'GCA_028125885.1_PDT001589349.1' already exists. Skipping...
Folder 'GCA_028127075.1_PDT001589235.1' already exists. Skipping...
Folder 'GCA_028127195.1_PDT001589182.1' already exists. Skipping...
Folder 'GCA_028128125.1_PDT001589195.1' already exists. Skipping...
Folder 'GCA_028129375.1_PDT001589228.1' already exists. Skipping...
Folder 'GCA_028129665.1_PDT001589205.1' already exists. Skipping...
Folder 'GCA_028130735.1_PDT001589353.1' already exists. Skipping...
Folder 'GCA_028130955.1_PDT001589211.1' already exists. Skipping...
Folder 'GCA_028130975.1_PDT001589207.1' already exists. Skipping...
Folder 'GCA_028130995.1_PDT001589206.1' already exists. Skipping...
Folder 'GCA_028131035.1_PDT001589187.1' already exists. Skipping...
Folder 'GCA_028131255.1_PDT001589793.1' already exists. Skipping...
Folder 'GCA_028131525.1_PDT001589244.1' already exists. Skipping...
Folder 'GCA_028132795.1_PDT001589234.1' already exists. Skipping...
Folder 'GCA_028134045.1_PDT001589185.1' already exists. Skipping...
Folder 'GCA_028134165.1_PDT001589828.1' already exists. Skipping...
Folder 'GCA_028134185.1_PDT001589820.1' already exists. Skipping...
Folder 'GCA_028134215.1_PDT001589819.1' already exists. Skipping...
Folder 'GCA_028135295.1_PDT001589374.1' already exists. Skipping...
Folder 'GCA_028135565.1_PDT001589340.1' already exists. Skipping...
Folder 'GCA_028136735.1_PDT001589830.1' already exists. Skipping...
Folder 'GCA_028136765.1_PDT001589826.1' already exists. Skipping...
Folder 'GCA_028136785.1_PDT001589825.1' already exists. Skipping...
Folder 'GCA_028137555.1_PDT001589243.1' already exists. Skipping...
Folder 'GCA_028137575.1_PDT001589242.1' already exists. Skipping...
Folder 'GCA_028137625.1_PDT001589240.1' already exists. Skipping...
Folder 'GCA_028139005.1_PDT001589232.1' already exists. Skipping...
Folder 'GCA_028139025.1_PDT001589222.1' already exists. Skipping...
Folder 'GCA_028139055.1_PDT001589230.1' already exists. Skipping...
Folder 'GCA_028139205.1_PDT001589210.1' already exists. Skipping...
Folder 'GCA_028139305.1_PDT001589200.1' already exists. Skipping...
Folder 'GCA_028139495.1_PDT001589167.1' already exists. Skipping...
Folder 'GCA_028144245.1_PDT001589827.1' already exists. Skipping...
Folder 'GCA_028144345.1_PDT001589822.1' already exists. Skipping...
Folder 'GCA_028149925.1_PDT001590199.1' already exists. Skipping...
Folder 'GCA_028155925.1_PDT001586251.1' already exists. Skipping...
Folder 'GCA_028155965.1_PDT001586250.1' already exists. Skipping...
Folder 'GCA_028158045.1_PDT001352236.1' already exists. Skipping...
Folder 'GCA_028164045.1_PDT001352427.3' already exists. Skipping...
Folder 'GCA_028164425.1_PDT001347979.3' already exists. Skipping...
Folder 'GCA_028164445.1_PDT001347223.3' already exists. Skipping...
Folder 'GCA_028164465.1_PDT001347224.3' already exists. Skipping...
Folder 'GCA_028164485.1_PDT001347222.3' already exists. Skipping...
Folder 'GCA_028164525.1_PDT001347218.3' already exists. Skipping...
Folder 'GCA_028164665.1_PDT001338366.3' already exists. Skipping...
Folder 'GCA_028167705.1_PDT001368977.1' already exists. Skipping...
Folder 'GCA_028169185.1_PDT001338220.1' already exists. Skipping...
Folder 'GCA_028169205.1_PDT001338368.1' already exists. Skipping...
Folder 'GCA_028171125.1_PDT001590985.1' already exists. Skipping...
Folder 'GCA_028171185.1_PDT001590982.1' already exists. Skipping...
Folder 'GCA_028171765.1_PDT001590983.1' already exists. Skipping...
Folder 'GCA_028173525.1_PDT001591722.1' already exists. Skipping...
Folder 'GCA_028173765.1_PDT001591724.1' already exists. Skipping...
Folder 'GCA_028173845.1_PDT001591698.1' already exists. Skipping...
Folder 'GCA_028173865.1_PDT001591714.1' already exists. Skipping...
Folder 'GCA_028173965.1_PDT001591708.1' already exists. Skipping...
Folder 'GCA_028173985.1_PDT001591692.1' already exists. Skipping...
Folder 'GCA_028174005.1_PDT001591706.1' already exists. Skipping...
Folder 'GCA_028174125.1_PDT001591715.1' already exists. Skipping...
Folder 'GCA_028174165.1_PDT001591709.1' already exists. Skipping...
Folder 'GCA_028174185.1_PDT001591712.1' already exists. Skipping...
Folder 'GCA_028174205.1_PDT001591707.1' already exists. Skipping...
Folder 'GCA_028174225.1_PDT001591705.1' already exists. Skipping...
Folder 'GCA_028174265.1_PDT001591703.1' already exists. Skipping...
Folder 'GCA_028174305.1_PDT001591700.1' already exists. Skipping...
Folder 'GCA_028174325.1_PDT001591697.1' already exists. Skipping...
Folder 'GCA_028174375.1_PDT001591696.1' already exists. Skipping...
Folder 'GCA_028174425.1_PDT001591689.1' already exists. Skipping...
Folder 'GCA_028174505.1_PDT001591687.1' already exists. Skipping...
Folder 'GCA_028174525.1_PDT001591686.1' already exists. Skipping...
Folder 'GCA_028174605.1_PDT001591682.1' already exists. Skipping...
Folder 'GCA_028174665.1_PDT001591681.1' already exists. Skipping...
Folder 'GCA_028182785.1_PDT001592709.1' already exists. Skipping...
Folder 'GCA_028182805.1_PDT001592708.1' already exists. Skipping...
Folder 'GCA_028182825.1_PDT001592707.1' already exists. Skipping...
Folder 'GCA_028182865.1_PDT001592530.1' already exists. Skipping...
Folder 'GCA_028182885.1_PDT001592529.1' already exists. Skipping...
Folder 'GCA_028189885.1_PDT001592750.1' already exists. Skipping...
Folder 'GCA_028191565.1_PDT001592902.1' already exists. Skipping...
Folder 'GCA_028191585.1_PDT001592901.1' already exists. Skipping...
Folder 'GCA_028191865.1_PDT001593854.1' already exists. Skipping...
Folder 'GCA_028192005.1_PDT001593842.1' already exists. Skipping...
Folder 'GCA_028192025.1_PDT001593839.1' already exists. Skipping...
Folder 'GCA_028192065.1_PDT001593841.1' already exists. Skipping...
Folder 'GCA_028192085.1_PDT001593831.1' already exists. Skipping...
Folder 'GCA_028192125.1_PDT001593826.1' already exists. Skipping...
Folder 'GCA_028192245.1_PDT001593846.1' already exists. Skipping...
Folder 'GCA_028192265.1_PDT001593845.1' already exists. Skipping...
Folder 'GCA_028192325.1_PDT001593844.1' already exists. Skipping...
Folder 'GCA_028192345.1_PDT001593838.1' already exists. Skipping...
Folder 'GCA_028192465.1_PDT001593829.1' already exists. Skipping...
Folder 'GCA_028192485.1_PDT001593827.1' already exists. Skipping...
Folder 'GCA_028192505.1_PDT001593828.1' already exists. Skipping...
Folder 'GCA_028192525.1_PDT001593824.1' already exists. Skipping...
Folder 'GCA_028192605.1_PDT001593818.1' already exists. Skipping...
Folder 'GCA_028192625.1_PDT001593817.1' already exists. Skipping...
Folder 'GCA_028192665.1_PDT001593816.1' already exists. Skipping...
Folder 'GCA_028192825.1_PDT001593822.1' already exists. Skipping...
Folder 'GCA_028194925.1_PDT001594078.1' already exists. Skipping...
Folder 'GCA_028198025.1_PDT001594929.1' already exists. Skipping...
Folder 'GCA_028198065.1_PDT001594922.1' already exists. Skipping...
Folder 'GCA_028212035.1_PDT001596003.1' already exists. Skipping...
Folder 'GCA_028212055.1_PDT001596004.1' already exists. Skipping...
Folder 'GCA_028212095.1_PDT001596001.1' already exists. Skipping...
Folder 'GCA_028212155.1_PDT001596000.1' already exists. Skipping...
Folder 'GCA_028212175.1_PDT001595997.1' already exists. Skipping...
Folder 'GCA_028212255.1_PDT001595992.1' already exists. Skipping...
Folder 'GCA_028212275.1_PDT001595993.1' already exists. Skipping...
Folder 'GCA_028212375.1_PDT001595977.1' already exists. Skipping...
Folder 'GCA_028212415.1_PDT001595976.1' already exists. Skipping...
Folder 'GCA_028212435.1_PDT001595975.1' already exists. Skipping...
Folder 'GCA_028212535.1_PDT001595986.1' already exists. Skipping...
Folder 'GCA_028212555.1_PDT001595987.1' already exists. Skipping...
Folder 'GCA_028212595.1_PDT001595980.1' already exists. Skipping...
Folder 'GCA_028212615.1_PDT001595981.1' already exists. Skipping...
Folder 'GCA_028212625.1_PDT001595982.1' already exists. Skipping...
Folder 'GCA_028212675.1_PDT001595978.1' already exists. Skipping...
Folder 'GCA_028215315.1_PDT001595019.1' already exists. Skipping...
Folder 'GCA_028215795.1_PDT001595010.1' already exists. Skipping...
Folder 'GCA_028215835.1_PDT001595009.1' already exists. Skipping...
Folder 'GCA_028269605.1_PDT001596368.1' already exists. Skipping...
Folder 'GCA_028269665.1_PDT001596367.1' already exists. Skipping...
Folder 'GCA_028291165.1_PDT001596901.1' already exists. Skipping...
Folder 'GCA_028291185.1_PDT001596907.1' already exists. Skipping...
Folder 'GCA_028291225.1_PDT001596904.1' already exists. Skipping...
Folder 'GCA_028293935.1_PDT001597059.1' already exists. Skipping...
Folder 'GCA_028293955.1_PDT001597058.1' already exists. Skipping...
Folder 'GCA_028293975.1_PDT001597096.1' already exists. Skipping...
Folder 'GCA_028293995.1_PDT001597097.1' already exists. Skipping...
Folder 'GCA_028294015.1_PDT001597055.1' already exists. Skipping...
Folder 'GCA_028294055.1_PDT001596899.1' already exists. Skipping...
Folder 'GCA_028295235.1_PDT001597057.1' already exists. Skipping...
Folder 'GCA_028296825.1_PDT001596900.1' already exists. Skipping...
Folder 'GCA_028298605.1_PDT001596895.1' already exists. Skipping...
Folder 'GCA_028298625.1_PDT001596893.1' already exists. Skipping...
Folder 'GCA_028298665.1_PDT001596896.1' already exists. Skipping...
Folder 'GCA_028298825.1_PDT001597308.1' already exists. Skipping...
Folder 'GCA_028298885.1_PDT001597238.1' already exists. Skipping...
Folder 'GCA_028298945.1_PDT001597285.1' already exists. Skipping...
Folder 'GCA_028299885.1_PDT001597336.1' already exists. Skipping...
Folder 'GCA_028299905.1_PDT001597343.1' already exists. Skipping...
Folder 'GCA_028299925.1_PDT001597330.1' already exists. Skipping...
Folder 'GCA_028299945.1_PDT001597329.1' already exists. Skipping...
Folder 'GCA_028299965.1_PDT001597327.1' already exists. Skipping...
Folder 'GCA_028300005.1_PDT001597290.1' already exists. Skipping...
Folder 'GCA_028300085.1_PDT001597286.1' already exists. Skipping...

Retreiveing data: 89769it [00:14, 6654.88it/s]

Folder 'GCA_029396175.1_PDT001668732.1' already exists. Skipping...
Folder 'GCA_029396235.1_PDT001668729.1' already exists. Skipping...
Folder 'GCA_029396255.1_PDT001668728.1' already exists. Skipping...
Folder 'GCA_029396275.1_PDT001668735.1' already exists. Skipping...
Folder 'GCA_029396315.1_PDT001668725.1' already exists. Skipping...
Folder 'GCA_029396375.1_PDT001668723.1' already exists. Skipping...
Folder 'GCA_029396435.1_PDT001668716.1' already exists. Skipping...
Folder 'GCA_029396495.1_PDT001668717.1' already exists. Skipping...
Folder 'GCA_029396515.1_PDT001668715.1' already exists. Skipping...
Folder 'GCA_029396535.1_PDT001668714.1' already exists. Skipping...
Folder 'GCA_029396575.1_PDT001668712.1' already exists. Skipping...
Folder 'GCA_029399605.1_PDT001668583.1' already exists. Skipping...
Folder 'GCA_029408355.1_PDT001667678.1' already exists. Skipping...
Folder 'GCA_029408495.1_PDT001667674.1' already exists. Skipping...
Folder 'GCA_029408675.1_PDT001667666.1' already exists. Skipping...
Folder 'GCA_029408715.1_PDT001667664.1' already exists. Skipping...
Folder 'GCA_029408755.1_PDT001667662.1' already exists. Skipping...
Folder 'GCA_029408935.1_PDT001667653.1' already exists. Skipping...
Folder 'GCA_029409055.1_PDT001667644.1' already exists. Skipping...
Folder 'GCA_029409075.1_PDT001667643.1' already exists. Skipping...
Folder 'GCA_029409155.1_PDT001667638.1' already exists. Skipping...
Folder 'GCA_029409175.1_PDT001667637.1' already exists. Skipping...
Folder 'GCA_029413975.1_PDT001670062.1' already exists. Skipping...
Folder 'GCA_029413995.1_PDT001670066.1' already exists. Skipping...
Folder 'GCA_029414035.1_PDT001670054.1' already exists. Skipping...
Folder 'GCA_029417015.1_PDT001670068.1' already exists. Skipping...
Folder 'GCA_029417035.1_PDT001670057.1' already exists. Skipping...
Folder 'GCA_029417075.1_PDT001670049.1' already exists. Skipping...
Folder 'GCA_029417095.1_PDT001670047.1' already exists. Skipping...
Folder 'GCA_029417115.1_PDT001670046.1' already exists. Skipping...
Folder 'GCA_029418015.1_PDT001670127.1' already exists. Skipping...
Folder 'GCA_029418075.1_PDT001670074.1' already exists. Skipping...
Folder 'GCA_029418135.1_PDT001670116.1' already exists. Skipping...
Folder 'GCA_029418155.1_PDT001670114.1' already exists. Skipping...
Folder 'GCA_029418315.1_PDT001670102.1' already exists. Skipping...
Folder 'GCA_029418335.1_PDT001670077.1' already exists. Skipping...
Folder 'GCA_029418355.1_PDT001670101.1' already exists. Skipping...
Folder 'GCA_029418375.1_PDT001670076.1' already exists. Skipping...
Folder 'GCA_029418395.1_PDT001670075.1' already exists. Skipping...
Folder 'GCA_029418435.1_PDT001670071.1' already exists. Skipping...
Folder 'GCA_029418455.1_PDT001670069.1' already exists. Skipping...
Folder 'GCA_029419515.1_PDT001670120.1' already exists. Skipping...
Folder 'GCA_029419535.1_PDT001670112.1' already exists. Skipping...
Folder 'GCA_029419595.1_PDT001670107.1' already exists. Skipping...
Folder 'GCA_029419635.1_PDT001670104.1' already exists. Skipping...
Folder 'GCA_029419655.1_PDT001670078.1' already exists. Skipping...
Folder 'GCA_029419715.1_PDT001670158.1' already exists. Skipping...
Folder 'GCA_029419755.1_PDT001670122.1' already exists. Skipping...
Folder 'GCA_029419875.1_PDT001670156.1' already exists. Skipping...
Folder 'GCA_029419935.1_PDT001670152.1' already exists. Skipping...
Folder 'GCA_029419955.1_PDT001670151.1' already exists. Skipping...
Folder 'GCA_029420055.1_PDT001670145.1' already exists. Skipping...
Folder 'GCA_029420095.1_PDT001670142.1' already exists. Skipping...
Folder 'GCA_029420155.1_PDT001670135.1' already exists. Skipping...
Folder 'GCA_029420195.1_PDT001670138.1' already exists. Skipping...
Folder 'GCA_029420235.1_PDT001670128.1' already exists. Skipping...
Folder 'GCA_029420555.1_PDT001670119.1' already exists. Skipping...
Folder 'GCA_029420595.1_PDT001670153.1' already exists. Skipping...
Folder 'GCA_029420635.1_PDT001670137.1' already exists. Skipping...
Folder 'GCA_029420655.1_PDT001670140.1' already exists. Skipping...
Folder 'GCA_029420695.1_PDT001670133.1' already exists. Skipping...
Folder 'GCA_029421775.1_PDT001670121.1' already exists. Skipping...
Folder 'GCA_029423695.1_PDT001670130.1' already exists. Skipping...
Folder 'GCA_029424135.1_PDT001670346.1' already exists. Skipping...
Folder 'GCA_029424155.1_PDT001670345.1' already exists. Skipping...
Folder 'GCA_029424175.1_PDT001670917.1' already exists. Skipping...
Folder 'GCA_029424195.1_PDT001670922.1' already exists. Skipping...
Folder 'GCA_029424205.1_PDT001670921.1' already exists. Skipping...
Folder 'GCA_029424235.1_PDT001670919.1' already exists. Skipping...
Folder 'GCA_029424255.1_PDT001670665.1' already exists. Skipping...
Folder 'GCA_029424275.1_PDT001670915.1' already exists. Skipping...
Folder 'GCA_029424295.1_PDT001670925.1' already exists. Skipping...
Folder 'GCA_029424315.1_PDT001670916.1' already exists. Skipping...
Folder 'GCA_029424335.1_PDT001670362.1' already exists. Skipping...
Folder 'GCA_029424515.1_PDT001670914.1' already exists. Skipping...
Folder 'GCA_029424535.1_PDT001670920.1' already exists. Skipping...
Folder 'GCA_029424575.1_PDT001670918.1' already exists. Skipping...
Folder 'GCA_029424605.1_PDT001670923.1' already exists. Skipping...
Folder 'GCA_029424945.1_PDT001670926.1' already exists. Skipping...
Folder 'GCA_029427415.1_PDT001671301.1' already exists. Skipping...
Folder 'GCA_029429205.1_PDT001670924.1' already exists. Skipping...
Folder 'GCA_029429245.1_PDT001670913.1' already exists. Skipping...
Folder 'GCA_029465935.1_PDT001673179.1' already exists. Skipping...
Folder 'GCA_029465955.1_PDT001674098.1' already exists. Skipping...
Folder 'GCA_029466005.1_PDT001674367.1' already exists. Skipping...
Folder 'GCA_029466025.1_PDT001674103.1' already exists. Skipping...
Folder 'GCA_029466045.1_PDT001673163.1' already exists. Skipping...
Folder 'GCA_029466195.1_PDT001674104.1' already exists. Skipping...
Folder 'GCA_029466215.1_PDT001673178.1' already exists. Skipping...
Folder 'GCA_029474305.1_PDT001674729.1' already exists. Skipping...
Folder 'GCA_029476485.1_PDT001674716.1' already exists. Skipping...
Folder 'GCA_029477435.1_PDT001674728.1' already exists. Skipping...
Folder 'GCA_029481485.1_PDT001674649.1' already exists. Skipping...
Folder 'GCA_029482265.1_PDT001674102.1' already exists. Skipping...
Folder 'GCA_029482285.1_PDT001674100.1' already exists. Skipping...
Folder 'GCA_029482765.1_PDT001674368.1' already exists. Skipping...
Folder 'GCA_029482845.1_PDT001674363.1' already exists. Skipping...
Folder 'GCA_029482945.1_PDT001674099.1' already exists. Skipping...
Folder 'GCA_029483785.1_PDT001674880.1' already exists. Skipping...
Folder 'GCA_029503655.1_PDT001663616.1' already exists. Skipping...
Folder 'GCA_029503675.1_PDT001663615.1' already exists. Skipping...
Folder 'GCA_029507015.1_PDT001675291.1' already exists. Skipping...
Folder 'GCA_029507055.1_PDT001675289.1' already exists. Skipping...
Folder 'GCA_029508095.1_PDT001675362.1' already exists. Skipping...
Folder 'GCA_029517035.1_PDT001676091.1' already exists. Skipping...
Folder 'GCA_029517115.1_PDT001676070.1' already exists. Skipping...
Folder 'GCA_029517175.1_PDT001676067.1' already exists. Skipping...
Folder 'GCA_029517195.1_PDT001676066.1' already exists. Skipping...
Folder 'GCA_029517215.1_PDT001676058.1' already exists. Skipping...
Folder 'GCA_029517915.1_PDT001676094.1' already exists. Skipping...
Folder 'GCA_029517935.1_PDT001676095.1' already exists. Skipping...
Folder 'GCA_029518095.1_PDT001676073.1' already exists. Skipping...
Folder 'GCA_029518155.1_PDT001676081.1' already exists. Skipping...
Folder 'GCA_029518215.1_PDT001676061.1' already exists. Skipping...
Folder 'GCA_029518235.1_PDT001676062.1' already exists. Skipping...
Folder 'GCA_029518255.1_PDT001676060.1' already exists. Skipping...
Folder 'GCA_029518275.1_PDT001676057.1' already exists. Skipping...
Folder 'GCA_029518455.1_PDT001676076.1' already exists. Skipping...
Folder 'GCA_029518475.1_PDT001676059.1' already exists. Skipping...
Folder 'GCA_029518675.1_PDT001676064.1' already exists. Skipping...
Folder 'GCA_029518735.1_PDT001676083.1' already exists. Skipping...
Folder 'GCA_029518745.1_PDT001676063.1' already exists. Skipping...
Folder 'GCA_029518815.1_PDT001676127.1' already exists. Skipping...
Folder 'GCA_029519775.1_PDT001676241.1' already exists. Skipping...
Folder 'GCA_029519875.1_PDT001676149.1' already exists. Skipping...
Folder 'GCA_029519955.1_PDT001676143.1' already exists. Skipping...
Folder 'GCA_029519995.1_PDT001676136.1' already exists. Skipping...
Folder 'GCA_029520015.1_PDT001676134.1' already exists. Skipping...
Folder 'GCA_029520035.1_PDT001676133.1' already exists. Skipping...
Folder 'GCA_029520055.1_PDT001676131.1' already exists. Skipping...
Folder 'GCA_029520115.1_PDT001676129.1' already exists. Skipping...
Folder 'GCA_029520275.1_PDT001676240.1' already exists. Skipping...
Folder 'GCA_029520335.1_PDT001676236.1' already exists. Skipping...
Folder 'GCA_029520355.1_PDT001676148.1' already exists. Skipping...
Folder 'GCA_029520375.1_PDT001676141.1' already exists. Skipping...
Folder 'GCA_029520455.1_PDT001676135.1' already exists. Skipping...
Folder 'GCA_029520805.1_PDT001676243.1' already exists. Skipping...
Folder 'GCA_029520835.1_PDT001676150.1' already exists. Skipping...
Folder 'GCA_029521235.1_PDT001676144.1' already exists. Skipping...
Folder 'GCA_029521255.1_PDT001676132.1' already exists. Skipping...
Folder 'GCA_029530415.1_PDT001676251.1' already exists. Skipping...
Folder 'GCA_029530995.1_PDT001676130.1' already exists. Skipping...
Folder 'GCA_029533195.1_PDT001676859.1' already exists. Skipping...
Folder 'GCA_029533215.1_PDT001676865.1' already exists. Skipping...
Folder 'GCA_029533255.1_PDT001676860.1' already exists. Skipping...
Folder 'GCA_029535115.1_PDT001677158.1' already exists. Skipping...
Folder 'GCA_029535135.1_PDT001677128.1' already exists. Skipping...
Folder 'GCA_029535315.1_PDT001677155.1' already exists. Skipping...
Folder 'GCA_029538325.1_PDT001677282.1' already exists. Skipping...
Folder 'GCA_029538345.1_PDT001677275.1' already exists. Skipping...
Folder 'GCA_029538405.1_PDT001677368.1' already exists. Skipping...
Folder 'GCA_029538455.1_PDT001677370.1' already exists. Skipping...
Folder 'GCA_029538505.1_PDT001677361.1' already exists. Skipping...
Folder 'GCA_029538565.1_PDT001677354.1' already exists. Skipping...
Folder 'GCA_029538805.1_PDT001677374.1' already exists. Skipping...
Folder 'GCA_029538885.1_PDT001677369.1' already exists. Skipping...
Folder 'GCA_029538965.1_PDT001677362.1' already exists. Skipping...
Folder 'GCA_029539005.1_PDT001677360.1' already exists. Skipping...
Folder 'GCA_029539045.1_PDT001677356.1' already exists. Skipping...
Folder 'GCA_029539125.1_PDT001677350.1' already exists. Skipping...
Folder 'GCA_029539205.1_PDT001677349.1' already exists. Skipping...
Folder 'GCA_029539585.1_PDT001677279.1' already exists. Skipping...
Folder 'GCA_029559215.1_PDT001677806.1' already exists. Skipping...
Folder 'GCA_029559245.1_PDT001677800.1' already exists. Skipping...
Folder 'GCA_029559255.1_PDT001677803.1' already exists. Skipping...
Folder 'GCA_029559285.1_PDT001677798.1' already exists. Skipping...
Folder 'GCA_029559325.1_PDT001677799.1' already exists. Skipping...
Folder 'GCA_029559415.1_PDT001677797.1' already exists. Skipping...
Folder 'GCA_029562795.1_PDT001677805.1' already exists. Skipping...
Folder 'GCA_029570605.1_PDT001677863.1' already exists. Skipping...
Folder 'GCA_029572275.1_PDT001677839.1' already exists. Skipping...
Folder 'GCA_029574565.1_PDT001678016.1' already exists. Skipping...
Folder 'GCA_029575305.1_PDT001677914.1' already exists. Skipping...
Folder 'GCA_029575365.1_PDT001677919.1' already exists. Skipping...
Folder 'GCA_029575625.1_PDT001677915.1' already exists. Skipping...
Folder 'GCA_029576615.1_PDT001678017.1' already exists. Skipping...
Folder 'GCA_029576675.1_PDT001678015.1' already exists. Skipping...
Folder 'GCA_029576835.1_PDT001677912.1' already exists. Skipping...
Folder 'GCA_029579595.1_PDT001677913.1' already exists. Skipping...
Folder 'GCA_029582845.1_PDT001678487.1' already exists. Skipping...
Folder 'GCA_029582865.1_PDT001678756.1' already exists. Skipping...
Folder 'GCA_029582945.1_PDT001678759.1' already exists. Skipping...
Folder 'GCA_029584835.1_PDT001678753.1' already exists. Skipping...
Folder 'GCA_029585635.1_PDT001678757.1' already exists. Skipping...
Folder 'GCA_029599355.1_PDT001680253.1' already exists. Skipping...
Folder 'GCA_029599395.1_PDT001680269.1' already exists. Skipping...
Folder 'GCA_029599435.1_PDT001680267.1' already exists. Skipping...
Folder 'GCA_029601035.1_PDT001680360.1' already exists. Skipping...
Folder 'GCA_029601045.1_PDT001680359.1' already exists. Skipping...
Folder 'GCA_029601075.1_PDT001680362.1' already exists. Skipping...
Folder 'GCA_029601095.1_PDT001680363.1' already exists. Skipping...
Folder 'GCA_029601115.1_PDT001680365.1' already exists. Skipping...
Folder 'GCA_029601135.1_PDT001680358.1' already exists. Skipping...
Folder 'GCA_029601155.1_PDT001680353.1' already exists. Skipping...
Folder 'GCA_029601175.1_PDT001680352.1' already exists. Skipping...
Folder 'GCA_029601195.1_PDT001680340.1' already exists. Skipping...
Folder 'GCA_029601335.1_PDT001680346.1' already exists. Skipping...
Folder 'GCA_029601375.1_PDT001680371.1' already exists. Skipping...
Folder 'GCA_029601395.1_PDT001680354.1' already exists. Skipping...
Folder 'GCA_029601455.1_PDT001680348.1' already exists. Skipping...
Folder 'GCA_029607925.1_PDT001680993.1' already exists. Skipping...
Folder 'GCA_029607985.1_PDT001681012.1' already exists. Skipping...
Folder 'GCA_029608005.1_PDT001680994.1' already exists. Skipping...
Folder 'GCA_029608025.1_PDT001681015.1' already exists. Skipping...
Folder 'GCA_029608045.1_PDT001681011.1' already exists. Skipping...
Folder 'GCA_029608065.1_PDT001681010.1' already exists. Skipping...
Folder 'GCA_029608325.1_PDT001681013.1' already exists. Skipping...
Folder 'GCA_029608365.1_PDT001681014.1' already exists. Skipping...
Folder 'GCA_029612565.1_PDT001681153.1' already exists. Skipping...
Folder 'GCA_029612585.1_PDT001681150.1' already exists. Skipping...
Folder 'GCA_029612605.1_PDT001681130.1' already exists. Skipping...
Folder 'GCA_029612645.1_PDT001681127.1' already exists. Skipping...
Folder 'GCA_029612705.1_PDT001681120.1' already exists. Skipping...
Folder 'GCA_029612765.1_PDT001681103.1' already exists. Skipping...
Folder 'GCA_029612785.1_PDT001681095.1' already exists. Skipping...
Folder 'GCA_029612795.1_PDT001681096.1' already exists. Skipping...
Folder 'GCA_029612925.1_PDT001681082.1' already exists. Skipping...
Folder 'GCA_029612985.1_PDT001681072.1' already exists. Skipping...
Folder 'GCA_029613615.1_PDT001681101.1' already exists. Skipping...
Folder 'GCA_029613705.1_PDT001681092.1' already exists. Skipping...
Folder 'GCA_029613725.1_PDT001681086.1' already exists. Skipping...
Folder 'GCA_029613765.1_PDT001681083.1' already exists. Skipping...
Folder 'GCA_029614345.1_PDT001681079.1' already exists. Skipping...
Folder 'GCA_029614825.1_PDT001681131.1' already exists. Skipping...
Folder 'GCA_029615345.1_PDT001681152.1' already exists. Skipping...
Folder 'GCA_029615545.1_PDT001681081.1' already exists. Skipping...
Folder 'GCA_029615605.1_PDT001681078.1' already exists. Skipping...
Folder 'GCA_029616965.1_PDT001681849.1' already exists. Skipping...
Folder 'GCA_029617125.1_PDT001681832.1' already exists. Skipping...
Folder 'GCA_029617145.1_PDT001681833.1' already exists. Skipping...
Folder 'GCA_029617185.1_PDT001681828.1' already exists. Skipping...
Folder 'GCA_029617225.1_PDT001681823.1' already exists. Skipping...
Folder 'GCA_029617245.1_PDT001681825.1' already exists. Skipping...
Folder 'GCA_029618415.1_PDT001682675.1' already exists. Skipping...
Folder 'GCA_029618715.1_PDT001682666.1' already exists. Skipping...
Folder 'GCA_029618735.1_PDT001682667.1' already exists. Skipping...
Folder 'GCA_029618755.1_PDT001682670.1' already exists. Skipping...
Folder 'GCA_029619245.1_PDT001682701.1' already exists. Skipping...
Folder 'GCA_029623195.1_PDT001684061.1' already exists. Skipping...
Folder 'GCA_029626325.1_PDT001684076.1' already exists. Skipping...
Folder 'GCA_029626385.1_PDT001684067.1' already exists. Skipping...
Folder 'GCA_029626445.1_PDT001684064.1' already exists. Skipping...
Folder 'GCA_029626455.1_PDT001684066.1' already exists. Skipping...
Folder 'GCA_029626605.1_PDT001684020.1' already exists. Skipping...
Folder 'GCA_029632805.1_PDT001684216.1' already exists. Skipping...
Folder 'GCA_029632945.1_PDT001684211.1' already exists. Skipping...
Folder 'GCA_029633085.1_PDT001684206.1' already exists. Skipping...
Folder 'GCA_029633095.1_PDT001684208.1' already exists. Skipping...
Folder 'GCA_029633185.1_PDT001684202.1' already exists. Skipping...
Folder 'GCA_029633225.1_PDT001684200.1' already exists. Skipping...
Folder 'GCA_029633365.1_PDT001684194.1' already exists. Skipping...
Folder 'GCA_029633515.1_PDT001684189.1' already exists. Skipping...
Folder 'GCA_029633535.1_PDT001684188.1' already exists. Skipping...
Folder 'GCA_029635475.1_PDT001684072.1' already exists. Skipping...
Folder 'GCA_029635495.1_PDT001684077.1' already exists. Skipping...
Folder 'GCA_029635515.1_PDT001684071.1' already exists. Skipping...
Folder 'GCA_029635535.1_PDT001684075.1' already exists. Skipping...
Folder 'GCA_029635555.1_PDT001684070.1' already exists. Skipping...
Folder 'GCA_029635595.1_PDT001684069.1' already exists. Skipping...
Folder 'GCA_029635635.1_PDT001684062.1' already exists. Skipping...
Folder 'GCA_029641085.1_PDT001685511.1' already exists. Skipping...
Folder 'GCA_029641095.1_PDT001685506.1' already exists. Skipping...
Folder 'GCA_029641125.1_PDT001685501.1' already exists. Skipping...
Folder 'GCA_029641165.1_PDT001685509.1' already exists. Skipping...
Folder 'GCA_029641215.1_PDT001685496.1' already exists. Skipping...
Folder 'GCA_029641265.1_PDT001685495.1' already exists. Skipping...
Folder 'GCA_029643165.1_PDT001685503.1' already exists. Skipping...
Folder 'GCA_029643205.1_PDT001685497.1' already exists. Skipping...
Folder 'GCA_029643565.1_PDT001681834.1' already exists. Skipping...
Folder 'GCA_029643965.1_PDT001667646.1' already exists. Skipping...
Folder 'GCA_029644685.1_PDT001666562.1' already exists. Skipping...
Folder 'GCA_029644745.1_PDT001664343.1' already exists. Skipping...
Folder 'GCA_029645125.1_PDT001685498.1' already exists. Skipping...
Folder 'GCA_029645905.1_PDT001652181.1' already exists. Skipping...
Folder 'GCA_029647565.1_PDT001617130.1' already exists. Skipping...
Folder 'GCA_029648185.1_PDT001607515.1' already exists. Skipping...
Folder 'GCA_029648305.1_PDT001597255.1' already exists. Skipping...
Folder 'GCA_029655845.1_PDT001685953.1' already exists. Skipping...
Folder 'GCA_029662185.1_PDT001686188.1' already exists. Skipping...
Folder 'GCA_029662265.1_PDT001686183.1' already exists. Skipping...
Folder 'GCA_029662285.1_PDT001686180.1' already exists. Skipping...
Folder 'GCA_029662305.1_PDT001686168.1' already exists. Skipping...
Folder 'GCA_029662325.1_PDT001686162.1' already exists. Skipping...
Folder 'GCA_029662345.1_PDT001686143.1' already exists. Skipping...
Folder 'GCA_029662365.1_PDT001686164.1' already exists. Skipping...
Folder 'GCA_029662465.1_PDT001686191.1' already exists. Skipping...
Folder 'GCA_029662485.1_PDT001686192.1' already exists. Skipping...
Folder 'GCA_029662505.1_PDT001686169.1' already exists. Skipping...
Folder 'GCA_029662525.1_PDT001686185.1' already exists. Skipping...
Folder 'GCA_029662545.1_PDT001686190.1' already exists. Skipping...
Folder 'GCA_029662605.1_PDT001686087.1' already exists. Skipping...
Folder 'GCA_029677225.1_PDT001686551.1' already exists. Skipping...
Folder 'GCA_029677265.1_PDT001686553.1' already exists. Skipping...
Folder 'GCA_029677285.1_PDT001686548.1' already exists. Skipping...

Retreiveing data: 91104it [00:15, 6660.43it/s]

Folder 'GCA_031402735.1_PDT001794688.1' already exists. Skipping...
Folder 'GCA_031402775.1_PDT001794694.1' already exists. Skipping...
Folder 'GCA_031402815.1_PDT001794696.1' already exists. Skipping...
Folder 'GCA_031402835.1_PDT001794687.1' already exists. Skipping...
Folder 'GCA_031402995.1_PDT001794684.1' already exists. Skipping...
Folder 'GCA_031403015.1_PDT001794683.1' already exists. Skipping...
Folder 'GCA_031403035.1_PDT001794682.1' already exists. Skipping...
Folder 'GCA_031403075.1_PDT001794680.1' already exists. Skipping...
Folder 'GCA_031403115.1_PDT001794681.1' already exists. Skipping...
Folder 'GCA_031403135.1_PDT001794679.1' already exists. Skipping...
Folder 'GCA_031403215.1_PDT001794677.1' already exists. Skipping...
Folder 'GCA_031403235.1_PDT001794678.1' already exists. Skipping...
Folder 'GCA_031403255.1_PDT001794674.1' already exists. Skipping...
Folder 'GCA_031403275.1_PDT001794676.1' already exists. Skipping...
Folder 'GCA_031403395.1_PDT001794672.1' already exists. Skipping...
Folder 'GCA_031403415.1_PDT001794673.1' already exists. Skipping...
Folder 'GCA_031403435.1_PDT001794671.1' already exists. Skipping...
Folder 'GCA_031403475.1_PDT001794670.1' already exists. Skipping...
Folder 'GCA_031403535.1_PDT001794669.1' already exists. Skipping...
Folder 'GCA_031403595.1_PDT001794667.1' already exists. Skipping...
Folder 'GCA_031403635.1_PDT001794666.1' already exists. Skipping...
Folder 'GCA_031403655.1_PDT001794665.1' already exists. Skipping...
Folder 'GCA_031404915.1_PDT001794663.1' already exists. Skipping...
Folder 'GCA_031404935.1_PDT001794661.1' already exists. Skipping...
Folder 'GCA_031404955.1_PDT001794660.1' already exists. Skipping...
Folder 'GCA_031405015.1_PDT001794662.1' already exists. Skipping...
Folder 'GCA_031405055.1_PDT001794659.1' already exists. Skipping...
Folder 'GCA_031405115.1_PDT001794657.1' already exists. Skipping...
Folder 'GCA_031405175.1_PDT001794658.1' already exists. Skipping...
Folder 'GCA_031405195.1_PDT001794656.1' already exists. Skipping...
Folder 'GCA_031405215.1_PDT001794655.1' already exists. Skipping...
Folder 'GCA_031405235.1_PDT001794654.1' already exists. Skipping...
Folder 'GCA_031405315.1_PDT001794653.1' already exists. Skipping...
Folder 'GCA_031405325.1_PDT001794652.1' already exists. Skipping...
Folder 'GCA_031405375.1_PDT001794651.1' already exists. Skipping...
Folder 'GCA_031405435.1_PDT001794647.1' already exists. Skipping...
Folder 'GCA_031405495.1_PDT001794645.1' already exists. Skipping...
Folder 'GCA_031405555.1_PDT001794644.1' already exists. Skipping...
Folder 'GCA_031405595.1_PDT001794643.1' already exists. Skipping...
Folder 'GCA_031405635.1_PDT001794642.1' already exists. Skipping...
Folder 'GCA_031405675.1_PDT001794641.1' already exists. Skipping...
Folder 'GCA_031406665.1_PDT001794640.1' already exists. Skipping...
Folder 'GCA_031406705.1_PDT001794639.1' already exists. Skipping...
Folder 'GCA_031406735.1_PDT001794648.1' already exists. Skipping...
Folder 'GCA_031406785.1_PDT001794637.1' already exists. Skipping...
Folder 'GCA_031406825.1_PDT001794635.1' already exists. Skipping...
Folder 'GCA_031406855.1_PDT001794636.1' already exists. Skipping...
Folder 'GCA_031406875.1_PDT001794634.1' already exists. Skipping...
Folder 'GCA_031406925.1_PDT001794633.1' already exists. Skipping...
Folder 'GCA_031406965.1_PDT001794632.1' already exists. Skipping...
Folder 'GCA_031406995.1_PDT001794631.1' already exists. Skipping...
Folder 'GCA_031407015.1_PDT001794629.1' already exists. Skipping...
Folder 'GCA_031407045.1_PDT001794630.1' already exists. Skipping...
Folder 'GCA_031407065.1_PDT001794628.1' already exists. Skipping...
Folder 'GCA_031407085.1_PDT001794626.1' already exists. Skipping...
Folder 'GCA_031407105.1_PDT001794627.1' already exists. Skipping...
Folder 'GCA_031407215.1_PDT001794625.1' already exists. Skipping...
Folder 'GCA_031407235.1_PDT001794624.1' already exists. Skipping...
Folder 'GCA_031407255.1_PDT001794623.1' already exists. Skipping...
Folder 'GCA_031407275.1_PDT001794622.1' already exists. Skipping...
Folder 'GCA_031407295.1_PDT001794621.1' already exists. Skipping...
Folder 'GCA_031407325.1_PDT001794619.1' already exists. Skipping...
Folder 'GCA_031407375.1_PDT001794620.1' already exists. Skipping...
Folder 'GCA_031407425.1_PDT001794618.1' already exists. Skipping...
Folder 'GCA_031407475.1_PDT001794616.1' already exists. Skipping...
Folder 'GCA_031407495.1_PDT001794617.1' already exists. Skipping...
Folder 'GCA_031407515.1_PDT001794615.1' already exists. Skipping...
Folder 'GCA_031407595.1_PDT001794612.1' already exists. Skipping...
Folder 'GCA_031407625.1_PDT001794611.1' already exists. Skipping...
Folder 'GCA_031407665.1_PDT001794610.1' already exists. Skipping...
Folder 'GCA_031408415.1_PDT001794607.1' already exists. Skipping...
Folder 'GCA_031408475.1_PDT001794604.1' already exists. Skipping...
Folder 'GCA_031408535.1_PDT001794605.1' already exists. Skipping...
Folder 'GCA_031408555.1_PDT001794606.1' already exists. Skipping...
Folder 'GCA_031408615.1_PDT001794603.1' already exists. Skipping...
Folder 'GCA_031408695.1_PDT001794601.1' already exists. Skipping...
Folder 'GCA_031408735.1_PDT001794599.1' already exists. Skipping...
Folder 'GCA_031408795.1_PDT001794598.1' already exists. Skipping...
Folder 'GCA_031408825.1_PDT001794597.1' already exists. Skipping...
Folder 'GCA_031408855.1_PDT001794595.1' already exists. Skipping...
Folder 'GCA_031408875.1_PDT001794596.1' already exists. Skipping...
Folder 'GCA_031408895.1_PDT001794594.1' already exists. Skipping...
Folder 'GCA_031408915.1_PDT001794593.1' already exists. Skipping...
Folder 'GCA_031408935.1_PDT001794591.1' already exists. Skipping...
Folder 'GCA_031408955.1_PDT001794592.1' already exists. Skipping...
Folder 'GCA_031409015.1_PDT001794575.1' already exists. Skipping...
Folder 'GCA_031409055.1_PDT001794573.1' already exists. Skipping...
Folder 'GCA_031409115.1_PDT001794565.1' already exists. Skipping...
Folder 'GCA_031409235.1_PDT001794567.1' already exists. Skipping...
Folder 'GCA_031434405.1_PDT001882479.1' already exists. Skipping...
Folder 'GCA_031434465.1_PDT001882478.1' already exists. Skipping...
Folder 'GCA_031434485.1_PDT001882476.1' already exists. Skipping...
Folder 'GCA_031434525.1_PDT001882475.1' already exists. Skipping...
Folder 'GCA_031434545.1_PDT001882474.1' already exists. Skipping...
Folder 'GCA_031436385.1_PDT001882381.1' already exists. Skipping...
Folder 'GCA_031437885.1_PDT001882265.1' already exists. Skipping...
Folder 'GCA_031438385.1_PDT001882215.1' already exists. Skipping...
Folder 'GCA_031438565.1_PDT001794546.1' already exists. Skipping...
Folder 'GCA_031438665.1_PDT001794542.1' already exists. Skipping...
Folder 'GCA_031438745.1_PDT001794535.1' already exists. Skipping...
Folder 'GCA_031438785.1_PDT001794537.1' already exists. Skipping...
Folder 'GCA_031438825.1_PDT001794533.1' already exists. Skipping...
Folder 'GCA_031438845.1_PDT001794532.1' already exists. Skipping...
Folder 'GCA_031438865.1_PDT001794530.1' already exists. Skipping...
Folder 'GCA_031438905.1_PDT001794529.1' already exists. Skipping...
Folder 'GCA_031439245.1_PDT001794502.1' already exists. Skipping...
Folder 'GCA_031439285.1_PDT001794499.1' already exists. Skipping...
Folder 'GCA_031442685.1_PDT001794306.1' already exists. Skipping...
Folder 'GCA_031442725.1_PDT001794291.1' already exists. Skipping...
Folder 'GCA_031442745.1_PDT001794305.1' already exists. Skipping...
Folder 'GCA_031442765.1_PDT001794290.1' already exists. Skipping...
Folder 'GCA_031442785.1_PDT001794289.1' already exists. Skipping...
Folder 'GCA_031442825.1_PDT001794287.1' already exists. Skipping...
Folder 'GCA_031442865.1_PDT001794282.1' already exists. Skipping...
Folder 'GCA_031442905.1_PDT001794284.1' already exists. Skipping...
Folder 'GCA_031442925.1_PDT001794283.1' already exists. Skipping...
Folder 'GCA_031443625.1_PDT001794075.1' already exists. Skipping...
Folder 'GCA_031443685.1_PDT001794072.1' already exists. Skipping...
Folder 'GCA_031443825.1_PDT001794064.1' already exists. Skipping...
Folder 'GCA_031443885.1_PDT001794062.1' already exists. Skipping...
Folder 'GCA_031444005.1_PDT001794056.1' already exists. Skipping...
Folder 'GCA_031444165.1_PDT001794047.1' already exists. Skipping...
Folder 'GCA_031444385.1_PDT001794035.1' already exists. Skipping...
Folder 'GCA_031444505.1_PDT001794030.1' already exists. Skipping...
Folder 'GCA_031444585.1_PDT001794026.1' already exists. Skipping...
Folder 'GCA_031444625.1_PDT001794024.1' already exists. Skipping...
Folder 'GCA_031445145.1_PDT001793994.1' already exists. Skipping...
Folder 'GCA_031445165.1_PDT001793993.1' already exists. Skipping...
Folder 'GCA_031445185.1_PDT001793992.1' already exists. Skipping...
Folder 'GCA_031445205.1_PDT001793991.1' already exists. Skipping...
Folder 'GCA_031445225.1_PDT001793990.1' already exists. Skipping...
Folder 'GCA_031445285.1_PDT001793985.1' already exists. Skipping...
Folder 'GCA_031445305.1_PDT001793983.1' already exists. Skipping...
Folder 'GCA_031445325.1_PDT001793984.1' already exists. Skipping...
Folder 'GCA_031445905.1_PDT001793936.1' already exists. Skipping...
Folder 'GCA_031445925.1_PDT001793935.1' already exists. Skipping...
Folder 'GCA_031445985.1_PDT001793933.1' already exists. Skipping...
Folder 'GCA_031446065.1_PDT001793926.1' already exists. Skipping...
Folder 'GCA_031446345.1_PDT001793912.1' already exists. Skipping...
Folder 'GCA_031446385.1_PDT001793910.1' already exists. Skipping...
Folder 'GCA_031446425.1_PDT001793909.1' already exists. Skipping...
Folder 'GCA_031450135.1_PDT001793634.1' already exists. Skipping...
Folder 'GCA_031450155.1_PDT001793631.1' already exists. Skipping...
Folder 'GCA_031450255.1_PDT001793626.1' already exists. Skipping...
Folder 'GCA_031450355.1_PDT001793619.1' already exists. Skipping...
Folder 'GCA_031450455.1_PDT001793611.1' already exists. Skipping...
Folder 'GCA_031450575.1_PDT001793603.1' already exists. Skipping...
Folder 'GCA_031450715.1_PDT001793593.1' already exists. Skipping...
Folder 'GCA_031450735.1_PDT001793591.1' already exists. Skipping...
Folder 'GCA_031450905.1_PDT001793586.1' already exists. Skipping...
Folder 'GCA_031450955.1_PDT001793587.1' already exists. Skipping...
Folder 'GCA_031451035.1_PDT001793585.1' already exists. Skipping...
Folder 'GCA_031451155.1_PDT001793576.1' already exists. Skipping...
Folder 'GCA_031451335.1_PDT001793565.1' already exists. Skipping...
Folder 'GCA_031451375.1_PDT001793563.1' already exists. Skipping...
Folder 'GCA_031451485.1_PDT001793559.1' already exists. Skipping...
Folder 'GCA_031451545.1_PDT001793556.1' already exists. Skipping...
Folder 'GCA_031472065.1_PDT001882727.1' already exists. Skipping...
Folder 'GCA_031472085.1_PDT001882726.1' already exists. Skipping...
Folder 'GCA_031473555.1_PDT001709460.1' already exists. Skipping...
Folder 'GCA_031473595.1_PDT001709458.1' already exists. Skipping...
Folder 'GCA_031473615.1_PDT001709454.1' already exists. Skipping...
Folder 'GCA_031473625.1_PDT001709456.1' already exists. Skipping...
Folder 'GCA_031473655.1_PDT001709455.1' already exists. Skipping...
Folder 'GCA_031473675.1_PDT001709452.1' already exists. Skipping...
Folder 'GCA_031473715.1_PDT001709451.1' already exists. Skipping...
Folder 'GCA_031473855.1_PDT001709401.1' already exists. Skipping...
Folder 'GCA_031473925.1_PDT001709399.1' already exists. Skipping...
Folder 'GCA_031473995.1_PDT001709400.1' already exists. Skipping...
Folder 'GCA_031474155.1_PDT001709374.1' already exists. Skipping...
Folder 'GCA_031474175.1_PDT001709375.1' already exists. Skipping...
Folder 'GCA_031474295.1_PDT001709368.1' already exists. Skipping...
Folder 'GCA_031474315.1_PDT001709367.1' already exists. Skipping...
Folder 'GCA_031474915.1_PDT001709322.1' already exists. Skipping...
Folder 'GCA_031474935.1_PDT001709320.1' already exists. Skipping...
Folder 'GCA_031474975.1_PDT001709318.1' already exists. Skipping...
Folder 'GCA_031474995.1_PDT001709317.1' already exists. Skipping...
Folder 'GCA_031475015.1_PDT001709316.1' already exists. Skipping...
Folder 'GCA_031475095.1_PDT001709312.1' already exists. Skipping...
Folder 'GCA_031475135.1_PDT001709309.1' already exists. Skipping...
Folder 'GCA_031475155.1_PDT001709310.1' already exists. Skipping...
Folder 'GCA_031475175.1_PDT001709308.1' already exists. Skipping...
Folder 'GCA_031475235.1_PDT001709305.1' already exists. Skipping...
Folder 'GCA_031475295.1_PDT001709301.1' already exists. Skipping...
Folder 'GCA_031475335.1_PDT001709300.1' already exists. Skipping...
Folder 'GCA_031475515.1_PDT001709291.1' already exists. Skipping...
Folder 'GCA_031475555.1_PDT001709289.1' already exists. Skipping...
Folder 'GCA_031476155.1_PDT001709271.1' already exists. Skipping...
Folder 'GCA_031476535.1_PDT001768305.1' already exists. Skipping...
Folder 'GCA_031476555.1_PDT001768304.1' already exists. Skipping...
Folder 'GCA_031476575.1_PDT001768298.1' already exists. Skipping...
Folder 'GCA_031476595.1_PDT001768302.1' already exists. Skipping...
Folder 'GCA_031476615.1_PDT001768300.1' already exists. Skipping...
Folder 'GCA_031476635.1_PDT001768297.1' already exists. Skipping...
Folder 'GCA_031476655.1_PDT001768296.1' already exists. Skipping...
Folder 'GCA_031476675.1_PDT001768294.1' already exists. Skipping...
Folder 'GCA_031476695.1_PDT001768292.1' already exists. Skipping...
Folder 'GCA_031476715.1_PDT001768291.1' already exists. Skipping...
Folder 'GCA_031476735.1_PDT001768290.1' already exists. Skipping...
Folder 'GCA_031476755.1_PDT001768289.1' already exists. Skipping...
Folder 'GCA_031476775.1_PDT001768287.1' already exists. Skipping...
Folder 'GCA_031476795.1_PDT001768285.1' already exists. Skipping...
Folder 'GCA_031476805.1_PDT001768286.1' already exists. Skipping...
Folder 'GCA_031476835.1_PDT001768283.1' already exists. Skipping...
Folder 'GCA_031476855.1_PDT001768284.1' already exists. Skipping...
Folder 'GCA_031476875.1_PDT001768281.1' already exists. Skipping...
Folder 'GCA_031476895.1_PDT001768279.1' already exists. Skipping...
Folder 'GCA_031476915.1_PDT001768280.1' already exists. Skipping...
Folder 'GCA_031476935.1_PDT001768278.1' already exists. Skipping...
Folder 'GCA_031476955.1_PDT001768277.1' already exists. Skipping...
Folder 'GCA_031476975.1_PDT001768276.1' already exists. Skipping...
Folder 'GCA_031476995.1_PDT001768275.1' already exists. Skipping...
Folder 'GCA_031477015.1_PDT001768274.1' already exists. Skipping...
Folder 'GCA_031477035.1_PDT001768273.1' already exists. Skipping...
Folder 'GCA_031477055.1_PDT001768272.1' already exists. Skipping...
Folder 'GCA_031477075.1_PDT001768271.1' already exists. Skipping...
Folder 'GCA_031477095.1_PDT001768270.1' already exists. Skipping...
Folder 'GCA_031477115.1_PDT001768268.1' already exists. Skipping...
Folder 'GCA_031477135.1_PDT001768266.1' already exists. Skipping...
Folder 'GCA_031477155.1_PDT001768265.1' already exists. Skipping...
Folder 'GCA_031477175.1_PDT001768263.1' already exists. Skipping...
Folder 'GCA_031477195.1_PDT001768261.1' already exists. Skipping...
Folder 'GCA_031477215.1_PDT001768260.1' already exists. Skipping...
Folder 'GCA_031477235.1_PDT001768259.1' already exists. Skipping...
Folder 'GCA_031477255.1_PDT001768258.1' already exists. Skipping...
Folder 'GCA_031477275.1_PDT001768257.1' already exists. Skipping...
Folder 'GCA_031477295.1_PDT001768262.1' already exists. Skipping...
Folder 'GCA_031477315.1_PDT001768256.1' already exists. Skipping...
Folder 'GCA_031477335.1_PDT001768264.1' already exists. Skipping...
Folder 'GCA_031477355.1_PDT001768254.1' already exists. Skipping...
Folder 'GCA_031477365.1_PDT001768255.1' already exists. Skipping...
Folder 'GCA_031477415.1_PDT001768252.1' already exists. Skipping...
Folder 'GCA_031477435.1_PDT001768253.1' already exists. Skipping...
Folder 'GCA_031477455.1_PDT001768251.1' already exists. Skipping...
Folder 'GCA_031477475.1_PDT001768249.1' already exists. Skipping...
Folder 'GCA_031477495.1_PDT001768250.1' already exists. Skipping...
Folder 'GCA_031477515.1_PDT001768243.1' already exists. Skipping...
Folder 'GCA_031477535.1_PDT001768246.1' already exists. Skipping...
Folder 'GCA_031477555.1_PDT001768247.1' already exists. Skipping...
Folder 'GCA_031477575.1_PDT001768248.1' already exists. Skipping...
Folder 'GCA_031477595.1_PDT001768245.1' already exists. Skipping...
Folder 'GCA_031477615.1_PDT001768240.1' already exists. Skipping...
Folder 'GCA_031477635.1_PDT001768242.1' already exists. Skipping...
Folder 'GCA_031477655.1_PDT001768239.1' already exists. Skipping...
Folder 'GCA_031477675.1_PDT001768237.1' already exists. Skipping...
Folder 'GCA_031477695.1_PDT001768238.1' already exists. Skipping...
Folder 'GCA_031477715.1_PDT001768235.1' already exists. Skipping...
Folder 'GCA_031477735.1_PDT001768236.1' already exists. Skipping...
Folder 'GCA_031477755.1_PDT001768234.1' already exists. Skipping...
Folder 'GCA_031477775.1_PDT001768228.1' already exists. Skipping...
Folder 'GCA_031477795.1_PDT001768233.1' already exists. Skipping...
Folder 'GCA_031477815.1_PDT001768227.1' already exists. Skipping...
Folder 'GCA_031477835.1_PDT001768226.1' already exists. Skipping...
Folder 'GCA_031477855.1_PDT001768225.1' already exists. Skipping...
Folder 'GCA_031477875.1_PDT001768223.1' already exists. Skipping...
Folder 'GCA_031477895.1_PDT001768222.1' already exists. Skipping...
Folder 'GCA_031477915.1_PDT001768221.1' already exists. Skipping...
Folder 'GCA_031477935.1_PDT001768220.1' already exists. Skipping...
Folder 'GCA_031477955.1_PDT001768217.1' already exists. Skipping...
Folder 'GCA_031477975.1_PDT001768218.1' already exists. Skipping...
Folder 'GCA_031477995.1_PDT001768219.1' already exists. Skipping...
Folder 'GCA_031478015.1_PDT001768214.1' already exists. Skipping...
Folder 'GCA_031478035.1_PDT001768213.1' already exists. Skipping...
Folder 'GCA_031478055.1_PDT001768215.1' already exists. Skipping...
Folder 'GCA_031478075.1_PDT001768210.1' already exists. Skipping...
Folder 'GCA_031478095.1_PDT001768208.1' already exists. Skipping...
Folder 'GCA_031478115.1_PDT001768205.1' already exists. Skipping...
Folder 'GCA_031478135.1_PDT001768204.1' already exists. Skipping...
Folder 'GCA_031478155.1_PDT001768201.1' already exists. Skipping...
Folder 'GCA_031478175.1_PDT001768203.1' already exists. Skipping...
Folder 'GCA_031478195.1_PDT001768200.1' already exists. Skipping...
Folder 'GCA_031478215.1_PDT001768198.1' already exists. Skipping...
Folder 'GCA_031478235.1_PDT001768197.1' already exists. Skipping...
Folder 'GCA_031478255.1_PDT001768196.1' already exists. Skipping...
Folder 'GCA_031478275.1_PDT001768195.1' already exists. Skipping...
Folder 'GCA_031478295.1_PDT001768193.1' already exists. Skipping...
Folder 'GCA_031478315.1_PDT001768194.1' already exists. Skipping...
Folder 'GCA_031478335.1_PDT001768192.1' already exists. Skipping...
Folder 'GCA_031478365.1_PDT001768190.1' already exists. Skipping...
Folder 'GCA_031478395.1_PDT001768186.1' already exists. Skipping...
Folder 'GCA_031478415.1_PDT001768189.1' already exists. Skipping...
Folder 'GCA_031478435.1_PDT001768184.1' already exists. Skipping...
Folder 'GCA_031478455.1_PDT001768187.1' already exists. Skipping...
Folder 'GCA_031478475.1_PDT001768185.1' already exists. Skipping...
Folder 'GCA_031478495.1_PDT001768183.1' already exists. Skipping...
Folder 'GCA_031478515.1_PDT001768182.1' already exists. Skipping...
Folder 'GCA_031478535.1_PDT001768180.1' already exists. Skipping...
Folder 'GCA_031478555.1_PDT001768179.1' already exists. Skipping...
Folder 'GCA_031478575.1_PDT001768178.1' already exists. Skipping...
Folder 'GCA_031478595.1_PDT001768177.1' already exists. Skipping...
Folder 'GCA_031478615.1_PDT001768173.1' already exists. Skipping...
Folder 'GCA_031478635.1_PDT001768172.1' already exists. Skipping...
Folder 'GCA_031478655.1_PDT001768171.1' already exists. Skipping...
Folder 'GCA_031478675.1_PDT001768165.1' already exists. Skipping...

Retreiveing data: 92429it [00:15, 6499.67it/s]

Folder 'GCA_031931085.1_PDT001839839.1' already exists. Skipping...
Folder 'GCA_031931105.1_PDT001839841.1' already exists. Skipping...
Folder 'GCA_031931145.1_PDT001839840.1' already exists. Skipping...
Folder 'GCA_031932465.1_ASM3193246v1' already exists. Skipping...
Folder 'GCA_031932485.1_ASM3193248v1' already exists. Skipping...
Folder 'GCA_031932505.1_ASM3193250v1' already exists. Skipping...
Folder 'GCA_031933145.1_PDT001900136.1' already exists. Skipping...
Folder 'GCA_031933165.1_PDT001899994.1' already exists. Skipping...
Folder 'GCA_031933205.1_PDT001899989.1' already exists. Skipping...
Folder 'GCA_031933265.1_PDT001899235.1' already exists. Skipping...
Folder 'GCA_031936625.1_PDT001839633.1' already exists. Skipping...
Folder 'GCA_031937025.1_PDT001839514.1' already exists. Skipping...
Folder 'GCA_031937045.1_PDT001839515.1' already exists. Skipping...
Folder 'GCA_031937065.1_PDT001839513.1' already exists. Skipping...
Folder 'GCA_031937085.1_PDT001839512.1' already exists. Skipping...
Folder 'GCA_031937105.1_PDT001839511.1' already exists. Skipping...
Folder 'GCA_031937125.1_PDT001839509.1' already exists. Skipping...
Folder 'GCA_031937185.1_PDT001839510.1' already exists. Skipping...
Folder 'GCA_031937785.1_PDT001839431.1' already exists. Skipping...
Folder 'GCA_031939205.1_PDT001839353.1' already exists. Skipping...
Folder 'GCA_031939305.1_PDT001839352.1' already exists. Skipping...
Folder 'GCA_031939325.1_PDT001839350.1' already exists. Skipping...
Folder 'GCA_031939345.1_PDT001839351.1' already exists. Skipping...
Folder 'GCA_031942545.1_PDT001838887.1' already exists. Skipping...
Folder 'GCA_031942585.1_PDT001838886.1' already exists. Skipping...
Folder 'GCA_031942605.1_PDT001838885.1' already exists. Skipping...
Folder 'GCA_031942625.1_PDT001838884.1' already exists. Skipping...
Folder 'GCA_031942745.1_PDT001838827.1' already exists. Skipping...
Folder 'GCA_031942765.1_PDT001838829.1' already exists. Skipping...
Folder 'GCA_031942805.1_PDT001838824.1' already exists. Skipping...
Folder 'GCA_031942955.1_PDT001838821.1' already exists. Skipping...
Folder 'GCA_031943025.1_PDT001838813.1' already exists. Skipping...
Folder 'GCA_031944045.1_PDT001838717.1' already exists. Skipping...
Folder 'GCA_031944125.1_PDT001838713.1' already exists. Skipping...
Folder 'GCA_031956225.1_PDT001837947.1' already exists. Skipping...
Folder 'GCA_031956245.1_PDT001837946.1' already exists. Skipping...
Folder 'GCA_031956265.1_PDT001837945.1' already exists. Skipping...
Folder 'GCA_031956285.1_PDT001837944.1' already exists. Skipping...
Folder 'GCA_031958465.1_PDT001837854.1' already exists. Skipping...
Folder 'GCA_031959025.1_PDT001900145.1' already exists. Skipping...
Folder 'GCA_031959185.1_PDT001900134.1' already exists. Skipping...
Folder 'GCA_031959325.1_PDT001900123.1' already exists. Skipping...
Folder 'GCA_031959365.1_PDT001900122.1' already exists. Skipping...
Folder 'GCA_031959525.1_PDT001900109.1' already exists. Skipping...
Folder 'GCA_031960685.1_PDT001900020.1' already exists. Skipping...
Folder 'GCA_031960785.1_PDT001900014.1' already exists. Skipping...
Folder 'GCA_031960805.1_PDT001900012.1' already exists. Skipping...
Folder 'GCA_031961025.1_PDT001900006.1' already exists. Skipping...
Folder 'GCA_031961085.1_PDT001900002.1' already exists. Skipping...
Folder 'GCA_031961845.1_PDT001899977.1' already exists. Skipping...
Folder 'GCA_031962045.1_PDT001899971.1' already exists. Skipping...
Folder 'GCA_031962065.1_PDT001899973.1' already exists. Skipping...
Folder 'GCA_031962175.1_PDT001899964.1' already exists. Skipping...
Folder 'GCA_031962205.1_PDT001899961.1' already exists. Skipping...
Folder 'GCA_031962505.1_PDT001899942.1' already exists. Skipping...
Folder 'GCA_031962785.1_PDT001899934.1' already exists. Skipping...
Folder 'GCA_031963285.1_PDT001899898.1' already exists. Skipping...
Folder 'GCA_031966935.1_PDT001899880.1' already exists. Skipping...
Folder 'GCA_031967115.1_PDT001899871.1' already exists. Skipping...
Folder 'GCA_031967135.1_PDT001899869.1' already exists. Skipping...
Folder 'GCA_031967315.1_PDT001899861.1' already exists. Skipping...
Folder 'GCA_031967435.1_PDT001899854.1' already exists. Skipping...
Folder 'GCA_031967575.1_PDT001899847.1' already exists. Skipping...
Folder 'GCA_031967895.1_PDT001899837.1' already exists. Skipping...
Folder 'GCA_031967915.1_PDT001899828.1' already exists. Skipping...
Folder 'GCA_031968055.1_PDT001899824.1' already exists. Skipping...
Folder 'GCA_031968135.1_PDT001899817.1' already exists. Skipping...
Folder 'GCA_031968215.1_PDT001899814.1' already exists. Skipping...
Folder 'GCA_031978985.1_PDT001840138.1' already exists. Skipping...
Folder 'GCA_031979065.1_PDT001840139.1' already exists. Skipping...
Folder 'GCA_031979085.1_PDT001840137.1' already exists. Skipping...
Folder 'GCA_031985585.1_PDT001837304.1' already exists. Skipping...
Folder 'GCA_031985645.1_PDT001837303.1' already exists. Skipping...
Folder 'GCA_031985685.1_PDT001837302.1' already exists. Skipping...
Folder 'GCA_031985725.1_PDT001837301.1' already exists. Skipping...
Folder 'GCA_031987445.1_PDT001837215.1' already exists. Skipping...
Folder 'GCA_031997865.1_PDT001902098.1' already exists. Skipping...
Folder 'GCA_032009795.1_PDT001901803.1' already exists. Skipping...
Folder 'GCA_032010025.1_PDT001901799.1' already exists. Skipping...
Folder 'GCA_032010205.1_PDT001901131.1' already exists. Skipping...
Folder 'GCA_032010905.1_PDT001901101.1' already exists. Skipping...
Folder 'GCA_032011225.1_PDT001901093.1' already exists. Skipping...
Folder 'GCA_032013705.1_PDT001900192.1' already exists. Skipping...
Folder 'GCA_032014025.1_PDT001900177.1' already exists. Skipping...
Folder 'GCA_032015455.1_PDT001837213.1' already exists. Skipping...
Folder 'GCA_032015625.1_PDT001837205.1' already exists. Skipping...
Folder 'GCA_032016045.1_PDT001837193.1' already exists. Skipping...
Folder 'GCA_032016105.1_PDT001837192.1' already exists. Skipping...
Folder 'GCA_032016125.1_PDT001837191.1' already exists. Skipping...
Folder 'GCA_032016145.1_PDT001837189.1' already exists. Skipping...
Folder 'GCA_032016205.1_PDT001837190.1' already exists. Skipping...
Folder 'GCA_032016245.1_PDT001837188.1' already exists. Skipping...
Folder 'GCA_032016265.1_PDT001837186.1' already exists. Skipping...
Folder 'GCA_032016305.1_PDT001837187.1' already exists. Skipping...
Folder 'GCA_032016325.1_PDT001837185.1' already exists. Skipping...
Folder 'GCA_032017505.1_PDT001837075.1' already exists. Skipping...
Folder 'GCA_032019965.1_PDT001836869.1' already exists. Skipping...
Folder 'GCA_032019985.1_PDT001836868.1' already exists. Skipping...
Folder 'GCA_032020065.1_PDT001836860.1' already exists. Skipping...
Folder 'GCA_032020145.1_PDT001836856.1' already exists. Skipping...
Folder 'GCA_032020225.1_PDT001836853.1' already exists. Skipping...
Folder 'GCA_032020545.1_PDT001836835.1' already exists. Skipping...
Folder 'GCA_032020965.1_PDT001836798.1' already exists. Skipping...
Folder 'GCA_032021005.1_PDT001836805.1' already exists. Skipping...
Folder 'GCA_032021025.1_PDT001836797.1' already exists. Skipping...
Folder 'GCA_032021065.1_PDT001836796.1' already exists. Skipping...
Folder 'GCA_032021105.1_PDT001836791.1' already exists. Skipping...
Folder 'GCA_032021305.1_PDT001836773.1' already exists. Skipping...
Folder 'GCA_032022505.1_PDT001836695.1' already exists. Skipping...
Folder 'GCA_032023985.1_PDT001836415.1' already exists. Skipping...
Folder 'GCA_032024005.1_PDT001836414.1' already exists. Skipping...
Folder 'GCA_032024025.1_PDT001836412.1' already exists. Skipping...
Folder 'GCA_032024045.1_PDT001836413.1' already exists. Skipping...
Folder 'GCA_032024065.1_PDT001836411.1' already exists. Skipping...
Folder 'GCA_032024085.1_PDT001836410.1' already exists. Skipping...
Folder 'GCA_032024105.1_PDT001836409.1' already exists. Skipping...
Folder 'GCA_032024125.1_PDT001836408.1' already exists. Skipping...
Folder 'GCA_032024145.1_PDT001836407.1' already exists. Skipping...
Folder 'GCA_032034895.1_PDT001836037.1' already exists. Skipping...
Folder 'GCA_032034935.1_PDT001836035.1' already exists. Skipping...
Folder 'GCA_032034955.1_PDT001836034.1' already exists. Skipping...
Folder 'GCA_032034975.1_PDT001836032.1' already exists. Skipping...
Folder 'GCA_032035035.1_PDT001836031.1' already exists. Skipping...
Folder 'GCA_032038565.1_PDT001835485.1' already exists. Skipping...
Folder 'GCA_032040055.1_PDT001835361.1' already exists. Skipping...
Folder 'GCA_032040135.1_PDT001835357.1' already exists. Skipping...
Folder 'GCA_032040175.1_PDT001835352.1' already exists. Skipping...
Folder 'GCA_032040575.1_PDT001835287.1' already exists. Skipping...
Folder 'GCA_032040875.1_PDT001835260.1' already exists. Skipping...
Folder 'GCA_032040915.1_PDT001835252.1' already exists. Skipping...
Folder 'GCA_032041015.1_PDT001835243.1' already exists. Skipping...
Folder 'GCA_032041195.1_PDT001835226.1' already exists. Skipping...
Folder 'GCA_032046095.1_PDT001835087.1' already exists. Skipping...
Folder 'GCA_032046515.1_PDT001835083.1' already exists. Skipping...
Folder 'GCA_032047255.1_PDT001823852.1' already exists. Skipping...
Folder 'GCA_032088075.1_PDT001904272.1' already exists. Skipping...
Folder 'GCA_032089795.1_PDT001904228.1' already exists. Skipping...
Folder 'GCA_032089875.1_PDT001904226.1' already exists. Skipping...
Folder 'GCA_032089965.1_PDT001904225.1' already exists. Skipping...
Folder 'GCA_032089995.1_PDT001904224.1' already exists. Skipping...
Folder 'GCA_032091735.1_PDT001904179.1' already exists. Skipping...
Folder 'GCA_032091815.1_PDT001904175.1' already exists. Skipping...
Folder 'GCA_032091955.1_PDT001904171.1' already exists. Skipping...
Folder 'GCA_032092175.1_PDT001904166.1' already exists. Skipping...
Folder 'GCA_032092695.1_PDT001904150.1' already exists. Skipping...
Folder 'GCA_032092835.1_PDT001904147.1' already exists. Skipping...
Folder 'GCA_032100005.1_PDT001903927.1' already exists. Skipping...
Folder 'GCA_032101245.1_PDT001903921.1' already exists. Skipping...
Folder 'GCA_032127515.1_PDT001903491.1' already exists. Skipping...
Folder 'GCA_032147585.1_PDT001907069.1' already exists. Skipping...
Folder 'GCA_032147905.1_PDT001907038.1' already exists. Skipping...
Folder 'GCA_032147925.1_PDT001907040.1' already exists. Skipping...
Folder 'GCA_032147965.1_PDT001907041.1' already exists. Skipping...
Folder 'GCA_032147985.1_PDT001907039.1' already exists. Skipping...
Folder 'GCA_032148005.1_PDT001907037.1' already exists. Skipping...
Folder 'GCA_032148025.1_PDT001907036.1' already exists. Skipping...
Folder 'GCA_032148105.1_PDT001907033.1' already exists. Skipping...
Folder 'GCA_032148345.1_PDT001907027.1' already exists. Skipping...
Folder 'GCA_032148385.1_PDT001907026.1' already exists. Skipping...
Folder 'GCA_032148405.1_PDT001907025.1' already exists. Skipping...
Folder 'GCA_032148425.1_PDT001907024.1' already exists. Skipping...
Folder 'GCA_032148485.1_PDT001907021.1' already exists. Skipping...
Folder 'GCA_032148505.1_PDT001907020.1' already exists. Skipping...
Folder 'GCA_032148565.1_PDT001907018.1' already exists. Skipping...
Folder 'GCA_032149005.1_PDT001906996.1' already exists. Skipping...
Folder 'GCA_032149025.1_PDT001906994.1' already exists. Skipping...
Folder 'GCA_032149085.1_PDT001906991.1' already exists. Skipping...
Folder 'GCA_032150485.1_PDT001906915.1' already exists. Skipping...
Folder 'GCA_032150525.1_PDT001906914.1' already exists. Skipping...
Folder 'GCA_032150565.1_PDT001906912.1' already exists. Skipping...
Folder 'GCA_032150585.1_PDT001906911.1' already exists. Skipping...
Folder 'GCA_032150605.1_PDT001906910.1' already exists. Skipping...
Folder 'GCA_032150645.1_PDT001906909.1' already exists. Skipping...
Folder 'GCA_032150685.1_PDT001906907.1' already exists. Skipping...
Folder 'GCA_032150725.1_PDT001906903.1' already exists. Skipping...
Folder 'GCA_032150765.1_PDT001906902.1' already exists. Skipping...
Folder 'GCA_032151765.1_PDT001906796.1' already exists. Skipping...
Folder 'GCA_032153555.1_PDT001907696.1' already exists. Skipping...
Folder 'GCA_032153615.1_PDT001907694.1' already exists. Skipping...
Folder 'GCA_032153635.1_PDT001907693.1' already exists. Skipping...
Folder 'GCA_032156425.1_PDT001907695.1' already exists. Skipping...
Folder 'GCA_032157285.1_PDT001889060.1' already exists. Skipping...
Folder 'GCA_032157305.1_PDT001889057.1' already exists. Skipping...
Folder 'GCA_032157445.1_PDT001881625.1' already exists. Skipping...
Folder 'GCA_032176825.1_PDT001809758.1' already exists. Skipping...
Folder 'GCA_032176905.1_PDT001809756.1' already exists. Skipping...
Folder 'GCA_032176965.1_PDT001809750.1' already exists. Skipping...
Folder 'GCA_032180765.1_PDT001809439.1' already exists. Skipping...
Folder 'GCA_032181125.1_PDT001809437.1' already exists. Skipping...
Folder 'GCA_032181165.1_PDT001809435.1' already exists. Skipping...
Folder 'GCA_032181185.1_PDT001809434.1' already exists. Skipping...
Folder 'GCA_032181205.1_PDT001809432.1' already exists. Skipping...
Folder 'GCA_032181265.1_PDT001809433.1' already exists. Skipping...
Folder 'GCA_032182525.1_PDT001809401.1' already exists. Skipping...
Folder 'GCA_032182665.1_PDT001809400.1' already exists. Skipping...
Folder 'GCA_032182705.1_PDT001809399.1' already exists. Skipping...
Folder 'GCA_032182745.1_PDT001809397.1' already exists. Skipping...
Folder 'GCA_032182765.1_PDT001809395.1' already exists. Skipping...
Folder 'GCA_032182825.1_PDT001908022.1' already exists. Skipping...
Folder 'GCA_032182845.1_PDT001908021.1' already exists. Skipping...
Folder 'GCA_032182865.1_PDT001908020.1' already exists. Skipping...
Folder 'GCA_032182885.1_PDT001908019.1' already exists. Skipping...
Folder 'GCA_032182945.1_PDT001908013.1' already exists. Skipping...
Folder 'GCA_032182965.1_PDT001908016.1' already exists. Skipping...
Folder 'GCA_032183005.1_PDT001908004.1' already exists. Skipping...
Folder 'GCA_032183105.1_PDT001809392.1' already exists. Skipping...
Folder 'GCA_032183145.1_PDT001809391.1' already exists. Skipping...
Folder 'GCA_032183305.1_PDT001908012.1' already exists. Skipping...
Folder 'GCA_032183325.1_PDT001908011.1' already exists. Skipping...
Folder 'GCA_032183585.1_PDT001908005.1' already exists. Skipping...
Folder 'GCA_032184025.1_PDT001809342.1' already exists. Skipping...
Folder 'GCA_032193825.1_PDT001807537.1' already exists. Skipping...
Folder 'GCA_032193865.1_PDT001807480.1' already exists. Skipping...
Folder 'GCA_032194025.1_PDT001807475.1' already exists. Skipping...
Folder 'GCA_032195145.1_PDT001769899.1' already exists. Skipping...
Folder 'GCA_032195225.1_PDT001769898.1' already exists. Skipping...
Folder 'GCA_032195245.1_PDT001769897.1' already exists. Skipping...
Folder 'GCA_032195265.1_PDT001769896.1' already exists. Skipping...
Folder 'GCA_032195285.1_PDT001769893.1' already exists. Skipping...
Folder 'GCA_032195295.1_PDT001769892.1' already exists. Skipping...
Folder 'GCA_032195325.1_PDT001769891.1' already exists. Skipping...
Folder 'GCA_032195345.1_PDT001769889.1' already exists. Skipping...
Folder 'GCA_032195365.1_PDT001769888.1' already exists. Skipping...
Folder 'GCA_032195385.1_PDT001769887.1' already exists. Skipping...
Folder 'GCA_032195405.1_PDT001769883.1' already exists. Skipping...
Folder 'GCA_032195425.1_PDT001769877.1' already exists. Skipping...
Folder 'GCA_032195445.1_PDT001769881.1' already exists. Skipping...
Folder 'GCA_032195465.1_PDT001769873.1' already exists. Skipping...
Folder 'GCA_032195485.1_PDT001769882.1' already exists. Skipping...
Folder 'GCA_032195505.1_PDT001769879.1' already exists. Skipping...
Folder 'GCA_032195545.1_PDT001769872.1' already exists. Skipping...
Folder 'GCA_032195565.1_PDT001769871.1' already exists. Skipping...
Folder 'GCA_032195585.1_PDT001769870.1' already exists. Skipping...
Folder 'GCA_032195605.1_PDT001769869.1' already exists. Skipping...
Folder 'GCA_032195625.1_PDT001769868.1' already exists. Skipping...
Folder 'GCA_032195645.1_PDT001769867.1' already exists. Skipping...
Folder 'GCA_032195655.1_PDT001769866.1' already exists. Skipping...
Folder 'GCA_032195685.1_PDT001769861.1' already exists. Skipping...
Folder 'GCA_032195705.1_PDT001769862.1' already exists. Skipping...
Folder 'GCA_032195725.1_PDT001769859.1' already exists. Skipping...
Folder 'GCA_032195745.1_PDT001769858.1' already exists. Skipping...
Folder 'GCA_032195765.1_PDT001769857.1' already exists. Skipping...
Folder 'GCA_032195785.1_PDT001769856.1' already exists. Skipping...
Folder 'GCA_032195805.1_PDT001769854.1' already exists. Skipping...
Folder 'GCA_032195825.1_PDT001769855.1' already exists. Skipping...
Folder 'GCA_032195845.1_PDT001769852.1' already exists. Skipping...
Folder 'GCA_032195865.1_PDT001769849.1' already exists. Skipping...
Folder 'GCA_032195885.1_PDT001769846.1' already exists. Skipping...
Folder 'GCA_032195905.1_PDT001769847.1' already exists. Skipping...
Folder 'GCA_032195925.1_PDT001769843.1' already exists. Skipping...
Folder 'GCA_032195945.1_PDT001769842.1' already exists. Skipping...
Folder 'GCA_032195965.1_PDT001769839.1' already exists. Skipping...
Folder 'GCA_032195985.1_PDT001769836.1' already exists. Skipping...
Folder 'GCA_032196005.1_PDT001769837.1' already exists. Skipping...
Folder 'GCA_032196025.1_PDT001769835.1' already exists. Skipping...
Folder 'GCA_032196045.1_PDT001769834.1' already exists. Skipping...
Folder 'GCA_032196065.1_PDT001769832.1' already exists. Skipping...
Folder 'GCA_032196085.1_PDT001769828.1' already exists. Skipping...
Folder 'GCA_032196105.1_PDT001769826.1' already exists. Skipping...
Folder 'GCA_032196125.1_PDT001769824.1' already exists. Skipping...
Folder 'GCA_032196145.1_PDT001769823.1' already exists. Skipping...
Folder 'GCA_032196165.1_PDT001769821.1' already exists. Skipping...
Folder 'GCA_032196185.1_PDT001769820.1' already exists. Skipping...
Folder 'GCA_032196205.1_PDT001769817.1' already exists. Skipping...
Folder 'GCA_032196225.1_PDT001769816.1' already exists. Skipping...
Folder 'GCA_032196245.1_PDT001769814.1' already exists. Skipping...
Folder 'GCA_032196265.1_PDT001769815.1' already exists. Skipping...
Folder 'GCA_032196285.1_PDT001769812.1' already exists. Skipping...
Folder 'GCA_032196305.1_PDT001769811.1' already exists. Skipping...
Folder 'GCA_032196325.1_PDT001769805.1' already exists. Skipping...
Folder 'GCA_032196345.1_PDT001769807.1' already exists. Skipping...
Folder 'GCA_032196365.1_PDT001769810.1' already exists. Skipping...
Folder 'GCA_032196385.1_PDT001769806.1' already exists. Skipping...
Folder 'GCA_032196405.1_PDT001769804.1' already exists. Skipping...
Folder 'GCA_032196425.1_PDT001769802.1' already exists. Skipping...
Folder 'GCA_032196445.1_PDT001769801.1' already exists. Skipping...
Folder 'GCA_032196465.1_PDT001769796.1' already exists. Skipping...
Folder 'GCA_032196485.1_PDT001769800.1' already exists. Skipping...
Folder 'GCA_032196505.1_PDT001769797.1' already exists. Skipping...
Folder 'GCA_032196525.1_PDT001769795.1' already exists. Skipping...
Folder 'GCA_032196545.1_PDT001769794.1' already exists. Skipping...
Folder 'GCA_032196565.1_PDT001769792.1' already exists. Skipping...
Folder 'GCA_032196585.1_PDT001769791.1' already exists. Skipping...
Folder 'GCA_032196605.1_PDT001769790.1' already exists. Skipping...
Folder 'GCA_032196635.1_PDT001769785.1' already exists. Skipping...
Folder 'GCA_032196665.1_PDT001769787.1' already exists. Skipping...
Folder 'GCA_032196685.1_PDT001769784.1' already exists. Skipping...
Folder 'GCA_032196705.1_PDT001769783.1' already exists. Skipping...
Folder 'GCA_032196725.1_PDT001769781.1' already exists. Skipping...
Folder 'GCA_032196745.1_PDT001769782.1' already exists. Skipping...
Folder 'GCA_032196765.1_PDT001769780.1' already exists. Skipping...
Folder 'GCA_032196785.1_PDT001769779.1' already exists. Skipping...
Folder 'GCA_032196805.1_PDT001769775.1' already exists. Skipping...
Folder 'GCA_032196825.1_PDT001769776.1' already exists. Skipping...

Retreiveing data: 93726it [00:15, 6413.20it/s]

Folder 'GCA_032402345.1_PDT001755760.2' already exists. Skipping...
Folder 'GCA_032402365.1_PDT001755794.2' already exists. Skipping...
Folder 'GCA_032402405.1_PDT001755612.2' already exists. Skipping...
Folder 'GCA_032402445.1_PDT001755617.2' already exists. Skipping...
Folder 'GCA_032402485.1_PDT001755614.2' already exists. Skipping...
Folder 'GCA_032402525.1_PDT001755619.2' already exists. Skipping...
Folder 'GCA_032402565.1_PDT001755622.2' already exists. Skipping...
Folder 'GCA_032402605.1_PDT001755628.2' already exists. Skipping...
Folder 'GCA_032402625.1_PDT001755627.2' already exists. Skipping...
Folder 'GCA_032402645.1_PDT001755891.2' already exists. Skipping...
Folder 'GCA_032404465.1_PDT001756002.2' already exists. Skipping...
Folder 'GCA_032404485.1_PDT001756007.2' already exists. Skipping...
Folder 'GCA_032404505.1_PDT001756004.2' already exists. Skipping...
Folder 'GCA_032404525.1_PDT001756040.2' already exists. Skipping...
Folder 'GCA_032404545.1_PDT001756043.2' already exists. Skipping...
Folder 'GCA_032404605.1_PDT001756047.2' already exists. Skipping...
Folder 'GCA_032404625.1_PDT001756050.2' already exists. Skipping...
Folder 'GCA_032404645.1_PDT001756053.2' already exists. Skipping...
Folder 'GCA_032404665.1_PDT001756057.2' already exists. Skipping...
Folder 'GCA_032404685.1_PDT001756067.2' already exists. Skipping...
Folder 'GCA_032404705.1_PDT001756089.2' already exists. Skipping...
Folder 'GCA_032404745.1_PDT001756092.2' already exists. Skipping...
Folder 'GCA_032404765.1_PDT001756094.2' already exists. Skipping...
Folder 'GCA_032404785.1_PDT001756095.2' already exists. Skipping...
Folder 'GCA_032404805.1_PDT001756102.2' already exists. Skipping...
Folder 'GCA_032404825.1_PDT001755836.2' already exists. Skipping...
Folder 'GCA_032404865.1_PDT001756103.2' already exists. Skipping...
Folder 'GCA_032404925.1_PDT001756105.2' already exists. Skipping...
Folder 'GCA_032404945.1_PDT001755630.2' already exists. Skipping...
Folder 'GCA_032404965.1_PDT001755637.2' already exists. Skipping...
Folder 'GCA_032404985.1_PDT001755900.2' already exists. Skipping...
Folder 'GCA_032405005.1_PDT001755638.2' already exists. Skipping...
Folder 'GCA_032405025.1_PDT001755639.2' already exists. Skipping...
Folder 'GCA_032405045.1_PDT001755640.2' already exists. Skipping...
Folder 'GCA_032405065.1_PDT001755643.2' already exists. Skipping...
Folder 'GCA_032405085.1_PDT001755641.2' already exists. Skipping...
Folder 'GCA_032405105.1_PDT001755646.2' already exists. Skipping...
Folder 'GCA_032405135.1_PDT001755647.2' already exists. Skipping...
Folder 'GCA_032405155.1_PDT001755901.2' already exists. Skipping...
Folder 'GCA_032405185.1_PDT001755655.2' already exists. Skipping...
Folder 'GCA_032405205.1_PDT001755650.2' already exists. Skipping...
Folder 'GCA_032405225.1_PDT001755652.2' already exists. Skipping...
Folder 'GCA_032405245.1_PDT001755603.2' already exists. Skipping...
Folder 'GCA_032405265.1_PDT001755931.2' already exists. Skipping...
Folder 'GCA_032405305.1_PDT001755943.2' already exists. Skipping...
Folder 'GCA_032405345.1_PDT001756012.2' already exists. Skipping...
Folder 'GCA_032405365.1_PDT001755823.2' already exists. Skipping...
Folder 'GCA_032405385.1_PDT001756034.2' already exists. Skipping...
Folder 'GCA_032405405.1_PDT001756025.2' already exists. Skipping...
Folder 'GCA_032405445.1_PDT001755909.2' already exists. Skipping...
Folder 'GCA_032405485.1_PDT001755808.2' already exists. Skipping...
Folder 'GCA_032405525.1_PDT001755916.2' already exists. Skipping...
Folder 'GCA_032405545.1_PDT001755922.2' already exists. Skipping...
Folder 'GCA_032406045.1_PDT001755864.2' already exists. Skipping...
Folder 'GCA_032406065.1_PDT001755861.2' already exists. Skipping...
Folder 'GCA_032406085.1_PDT001755860.2' already exists. Skipping...
Folder 'GCA_032406125.1_PDT001755867.2' already exists. Skipping...
Folder 'GCA_032406165.1_PDT001755874.2' already exists. Skipping...
Folder 'GCA_032406185.1_PDT001755665.2' already exists. Skipping...
Folder 'GCA_032406225.1_PDT001755667.2' already exists. Skipping...
Folder 'GCA_032406245.1_PDT001755928.2' already exists. Skipping...
Folder 'GCA_032406265.1_PDT001755801.2' already exists. Skipping...
Folder 'GCA_032406285.1_PDT001755809.2' already exists. Skipping...
Folder 'GCA_032406305.1_PDT001755951.2' already exists. Skipping...
Folder 'GCA_032406325.1_PDT001755949.2' already exists. Skipping...
Folder 'GCA_032406345.1_PDT001755954.2' already exists. Skipping...
Folder 'GCA_032406365.1_PDT001755957.2' already exists. Skipping...
Folder 'GCA_032406385.1_PDT001755959.2' already exists. Skipping...
Folder 'GCA_032406405.1_PDT001755960.2' already exists. Skipping...
Folder 'GCA_032406425.1_PDT001755964.2' already exists. Skipping...
Folder 'GCA_032406445.1_PDT001755813.2' already exists. Skipping...
Folder 'GCA_032406465.1_PDT001755814.2' already exists. Skipping...
Folder 'GCA_032406485.1_PDT001755984.2' already exists. Skipping...
Folder 'GCA_032406505.1_PDT001755849.2' already exists. Skipping...
Folder 'GCA_032406525.1_PDT001755850.2' already exists. Skipping...
Folder 'GCA_032406535.1_PDT001755797.2' already exists. Skipping...
Folder 'GCA_032406565.1_PDT001755856.2' already exists. Skipping...
Folder 'GCA_032406575.1_PDT001755854.2' already exists. Skipping...
Folder 'GCA_032406605.1_PDT001755730.2' already exists. Skipping...
Folder 'GCA_032406625.1_PDT001755829.2' already exists. Skipping...
Folder 'GCA_032406685.1_PDT001755791.2' already exists. Skipping...
Folder 'GCA_032406705.1_PDT001755789.2' already exists. Skipping...
Folder 'GCA_032406725.1_PDT001755858.2' already exists. Skipping...
Folder 'GCA_032406745.1_PDT001755817.2' already exists. Skipping...
Folder 'GCA_032406765.1_PDT001755862.2' already exists. Skipping...
Folder 'GCA_032406825.1_PDT001755869.2' already exists. Skipping...
Folder 'GCA_032406845.1_PDT001755868.2' already exists. Skipping...
Folder 'GCA_032406885.1_PDT001755818.2' already exists. Skipping...
Folder 'GCA_032406905.1_PDT001755873.2' already exists. Skipping...
Folder 'GCA_032406965.1_PDT001755882.2' already exists. Skipping...
Folder 'GCA_032407005.1_PDT001755884.2' already exists. Skipping...
Folder 'GCA_032407045.1_PDT001755885.2' already exists. Skipping...
Folder 'GCA_032407065.1_PDT001755672.2' already exists. Skipping...
Folder 'GCA_032407085.1_PDT001755832.2' already exists. Skipping...
Folder 'GCA_032407105.1_PDT001755676.2' already exists. Skipping...
Folder 'GCA_032407125.1_PDT001755677.2' already exists. Skipping...
Folder 'GCA_032407145.1_PDT001755682.2' already exists. Skipping...
Folder 'GCA_032407165.1_PDT001755833.2' already exists. Skipping...
Folder 'GCA_032407185.1_PDT001755683.2' already exists. Skipping...
Folder 'GCA_032407205.1_PDT001755684.2' already exists. Skipping...
Folder 'GCA_032407225.1_PDT001755688.2' already exists. Skipping...
Folder 'GCA_032407245.1_PDT001755689.2' already exists. Skipping...
Folder 'GCA_032407255.1_PDT001755838.2' already exists. Skipping...
Folder 'GCA_032407285.1_PDT001756122.2' already exists. Skipping...
Folder 'GCA_032407295.1_PDT001756121.2' already exists. Skipping...
Folder 'GCA_032407325.1_PDT001755702.2' already exists. Skipping...
Folder 'GCA_032407345.1_PDT001756123.2' already exists. Skipping...
Folder 'GCA_032407365.1_PDT001755839.2' already exists. Skipping...
Folder 'GCA_032407385.1_PDT001755705.2' already exists. Skipping...
Folder 'GCA_032407425.1_PDT001755734.2' already exists. Skipping...
Folder 'GCA_032407505.1_PDT001755738.2' already exists. Skipping...
Folder 'GCA_032407525.1_PDT001755747.2' already exists. Skipping...
Folder 'GCA_032407545.1_PDT001755844.2' already exists. Skipping...
Folder 'GCA_032407565.1_PDT001755750.2' already exists. Skipping...
Folder 'GCA_032407585.1_PDT001755751.2' already exists. Skipping...
Folder 'GCA_032407605.1_PDT001755753.2' already exists. Skipping...
Folder 'GCA_032407625.1_PDT001755754.2' already exists. Skipping...
Folder 'GCA_032407645.1_PDT001755755.2' already exists. Skipping...
Folder 'GCA_032407665.1_PDT001755606.2' already exists. Skipping...
Folder 'GCA_032407685.1_PDT001755759.2' already exists. Skipping...
Folder 'GCA_032407705.1_PDT001755762.2' already exists. Skipping...
Folder 'GCA_032407725.1_PDT001755897.2' already exists. Skipping...
Folder 'GCA_032407745.1_PDT001755607.2' already exists. Skipping...
Folder 'GCA_032407785.1_PDT001755616.2' already exists. Skipping...
Folder 'GCA_032407805.1_PDT001755620.2' already exists. Skipping...
Folder 'GCA_032407825.1_PDT001755623.2' already exists. Skipping...
Folder 'GCA_032407865.1_PDT001755806.2' already exists. Skipping...
Folder 'GCA_032407885.1_PDT001755887.2' already exists. Skipping...
Folder 'GCA_032407925.1_PDT001755820.2' already exists. Skipping...
Folder 'GCA_032407945.1_PDT001755889.2' already exists. Skipping...
Folder 'GCA_032407965.1_PDT001755890.2' already exists. Skipping...
Folder 'GCA_032407985.1_PDT001755997.2' already exists. Skipping...
Folder 'GCA_032408005.1_PDT001755803.2' already exists. Skipping...
Folder 'GCA_032408025.1_PDT001755896.2' already exists. Skipping...
Folder 'GCA_032408045.1_PDT001756003.2' already exists. Skipping...
Folder 'GCA_032408065.1_PDT001756001.2' already exists. Skipping...
Folder 'GCA_032408085.1_PDT001755822.2' already exists. Skipping...
Folder 'GCA_032408105.1_PDT001756009.2' already exists. Skipping...
Folder 'GCA_032408125.1_PDT001756042.2' already exists. Skipping...
Folder 'GCA_032408135.1_PDT001756039.2' already exists. Skipping...
Folder 'GCA_032408165.1_PDT001755998.2' already exists. Skipping...
Folder 'GCA_032408185.1_PDT001756045.2' already exists. Skipping...
Folder 'GCA_032408205.1_PDT001756056.2' already exists. Skipping...
Folder 'GCA_032408225.1_PDT001755693.2' already exists. Skipping...
Folder 'GCA_032408265.1_PDT001755828.2' already exists. Skipping...
Folder 'GCA_032408285.1_PDT001755694.2' already exists. Skipping...
Folder 'GCA_032408305.1_PDT001755696.2' already exists. Skipping...
Folder 'GCA_032408325.1_PDT001756091.2' already exists. Skipping...
Folder 'GCA_032408345.1_PDT001755700.2' already exists. Skipping...
Folder 'GCA_032408365.1_PDT001755835.2' already exists. Skipping...
Folder 'GCA_032408385.1_PDT001756099.2' already exists. Skipping...
Folder 'GCA_032408405.1_PDT001756107.2' already exists. Skipping...
Folder 'GCA_032408425.1_PDT001755645.2' already exists. Skipping...
Folder 'GCA_032408445.1_PDT001755632.2' already exists. Skipping...
Folder 'GCA_032408465.1_PDT001755642.2' already exists. Skipping...
Folder 'GCA_032408485.1_PDT001755648.2' already exists. Skipping...
Folder 'GCA_032408505.1_PDT001755649.2' already exists. Skipping...
Folder 'GCA_032408545.1_PDT001755932.2' already exists. Skipping...
Folder 'GCA_032408565.1_PDT001755930.2' already exists. Skipping...
Folder 'GCA_032408585.1_PDT001756014.2' already exists. Skipping...
Folder 'GCA_032408605.1_PDT001755940.2' already exists. Skipping...
Folder 'GCA_032408625.1_PDT001756016.2' already exists. Skipping...
Folder 'GCA_032408645.1_PDT001756015.2' already exists. Skipping...
Folder 'GCA_032408665.1_PDT001756017.2' already exists. Skipping...
Folder 'GCA_032408685.1_PDT001756021.2' already exists. Skipping...
Folder 'GCA_032408705.1_PDT001756022.2' already exists. Skipping...
Folder 'GCA_032408725.1_PDT001756023.2' already exists. Skipping...
Folder 'GCA_032408745.1_PDT001756030.2' already exists. Skipping...
Folder 'GCA_032408785.1_PDT001756032.2' already exists. Skipping...
Folder 'GCA_032408805.1_PDT001755825.2' already exists. Skipping...
Folder 'GCA_032408825.1_PDT001755604.2' already exists. Skipping...
Folder 'GCA_032408845.1_PDT001755906.2' already exists. Skipping...
Folder 'GCA_032408865.1_PDT001755807.2' already exists. Skipping...
Folder 'GCA_032408885.1_PDT001755907.2' already exists. Skipping...
Folder 'GCA_032408905.1_PDT001755925.2' already exists. Skipping...
Folder 'GCA_032408915.1_PDT001755920.2' already exists. Skipping...
Folder 'GCA_032408965.1_PDT001755927.2' already exists. Skipping...
Folder 'GCA_032408985.1_PDT001755953.2' already exists. Skipping...
Folder 'GCA_032409005.1_PDT001755956.2' already exists. Skipping...
Folder 'GCA_032409015.1_PDT001755962.2' already exists. Skipping...
Folder 'GCA_032409065.1_PDT001755963.2' already exists. Skipping...
Folder 'GCA_032409085.1_PDT001755965.2' already exists. Skipping...
Folder 'GCA_032409125.1_PDT001755970.2' already exists. Skipping...
Folder 'GCA_032409145.1_PDT001755975.2' already exists. Skipping...
Folder 'GCA_032409165.1_PDT001755976.2' already exists. Skipping...
Folder 'GCA_032409185.1_PDT001755978.2' already exists. Skipping...
Folder 'GCA_032409205.1_PDT001755988.2' already exists. Skipping...
Folder 'GCA_032409225.1_PDT001755986.2' already exists. Skipping...
Folder 'GCA_032409245.1_PDT001755815.2' already exists. Skipping...
Folder 'GCA_032409265.1_PDT001755991.2' already exists. Skipping...
Folder 'GCA_032409285.1_PDT001755990.2' already exists. Skipping...
Folder 'GCA_032409305.1_PDT001755799.2' already exists. Skipping...
Folder 'GCA_032409325.1_PDT001755816.2' already exists. Skipping...
Folder 'GCA_032409345.1_PDT001755992.2' already exists. Skipping...
Folder 'GCA_032409365.1_PDT001755989.2' already exists. Skipping...
Folder 'GCA_032409385.1_PDT001755855.2' already exists. Skipping...
Folder 'GCA_032409405.1_PDT001755852.2' already exists. Skipping...
Folder 'GCA_032409425.1_PDT001756068.2' already exists. Skipping...
Folder 'GCA_032409465.1_PDT001756069.2' already exists. Skipping...
Folder 'GCA_032409505.1_PDT001756071.2' already exists. Skipping...
Folder 'GCA_032409525.1_PDT001756082.2' already exists. Skipping...
Folder 'GCA_032409545.1_PDT001756084.2' already exists. Skipping...
Folder 'GCA_032409585.1_PDT001756086.2' already exists. Skipping...
Folder 'GCA_032409625.1_PDT001755840.2' already exists. Skipping...
Folder 'GCA_032409665.1_PDT001755709.2' already exists. Skipping...
Folder 'GCA_032409685.1_PDT001755841.2' already exists. Skipping...
Folder 'GCA_032409705.1_PDT001755723.2' already exists. Skipping...
Folder 'GCA_032409725.1_PDT001755842.2' already exists. Skipping...
Folder 'GCA_032409825.1_PDT001755767.2' already exists. Skipping...
Folder 'GCA_032409865.1_PDT001755769.2' already exists. Skipping...
Folder 'GCA_032409885.1_PDT001755787.2' already exists. Skipping...
Folder 'GCA_032409905.1_PDT001756110.2' already exists. Skipping...
Folder 'GCA_032409945.1_PDT001756128.2' already exists. Skipping...
Folder 'GCA_032409965.1_PDT001756129.2' already exists. Skipping...
Folder 'GCA_032409985.1_PDT001755994.2' already exists. Skipping...
Folder 'GCA_032410005.1_PDT001756131.2' already exists. Skipping...
Folder 'GCA_032414145.1_PDT001824169.1' already exists. Skipping...
Folder 'GCA_032414185.1_PDT001824166.1' already exists. Skipping...
Folder 'GCA_032414265.1_PDT001824148.1' already exists. Skipping...
Folder 'GCA_032414345.1_PDT001824146.1' already exists. Skipping...
Folder 'GCA_032414465.1_PDT001824138.1' already exists. Skipping...
Folder 'GCA_032414525.1_PDT001824137.1' already exists. Skipping...
Folder 'GCA_032414585.1_PDT001824134.1' already exists. Skipping...
Folder 'GCA_032414605.1_PDT001824133.1' already exists. Skipping...
Folder 'GCA_032418815.1_PDT001824083.1' already exists. Skipping...
Folder 'GCA_032418935.1_PDT001823956.1' already exists. Skipping...
Folder 'GCA_032419035.1_PDT001823957.1' already exists. Skipping...
Folder 'GCA_032419095.1_PDT001823950.1' already exists. Skipping...
Folder 'GCA_032419155.1_PDT001823944.1' already exists. Skipping...
Folder 'GCA_032419205.1_PDT001823946.1' already exists. Skipping...
Folder 'GCA_032419235.1_PDT001823943.1' already exists. Skipping...
Folder 'GCA_032419255.1_PDT001823941.1' already exists. Skipping...
Folder 'GCA_032419555.1_PDT001823939.1' already exists. Skipping...
Folder 'GCA_032419595.1_PDT001823938.1' already exists. Skipping...
Folder 'GCA_032419635.1_PDT001823936.1' already exists. Skipping...
Folder 'GCA_032419665.1_PDT001823935.1' already exists. Skipping...
Folder 'GCA_032419715.1_PDT001823933.1' already exists. Skipping...
Folder 'GCA_032419735.1_PDT001823934.1' already exists. Skipping...
Folder 'GCA_032420545.1_PDT001823888.1' already exists. Skipping...
Folder 'GCA_032420765.1_PDT001823877.1' already exists. Skipping...
Folder 'GCA_032421225.1_PDT001823851.1' already exists. Skipping...
Folder 'GCA_032421405.1_PDT001823842.1' already exists. Skipping...
Folder 'GCA_032421445.1_PDT001823840.1' already exists. Skipping...
Folder 'GCA_032423185.1_PDT001823713.1' already exists. Skipping...
Folder 'GCA_032423275.1_PDT001823711.1' already exists. Skipping...
Folder 'GCA_032423295.1_PDT001823712.1' already exists. Skipping...
Folder 'GCA_032423325.1_PDT001823710.1' already exists. Skipping...
Folder 'GCA_032423335.1_PDT001823708.1' already exists. Skipping...
Folder 'GCA_032423375.1_PDT001823709.1' already exists. Skipping...
Folder 'GCA_032423415.1_PDT001823707.1' already exists. Skipping...
Folder 'GCA_032423435.1_PDT001823706.1' already exists. Skipping...
Folder 'GCA_032423455.1_PDT001823705.1' already exists. Skipping...
Folder 'GCA_032424015.1_ASM3242401v1' already exists. Skipping...
Folder 'GCA_032424035.1_ASM3242403v1' already exists. Skipping...
Folder 'GCA_032424085.1_ASM3242408v1' already exists. Skipping...
Folder 'GCA_032424195.1_ASM3242419v1' already exists. Skipping...
Folder 'GCA_032427175.1_PDT001823240.1' already exists. Skipping...
Folder 'GCA_032427295.1_PDT001823234.1' already exists. Skipping...
Folder 'GCA_032427315.1_PDT001823232.1' already exists. Skipping...
Folder 'GCA_032427375.1_PDT001823229.1' already exists. Skipping...
Folder 'GCA_032427415.1_PDT001823227.1' already exists. Skipping...
Folder 'GCA_032428415.1_PDT001822815.1' already exists. Skipping...
Folder 'GCA_032428435.1_PDT001822811.1' already exists. Skipping...
Folder 'GCA_032428475.1_PDT001822808.1' already exists. Skipping...
Folder 'GCA_032428495.1_PDT001822810.1' already exists. Skipping...
Folder 'GCA_032428635.1_PDT001822794.1' already exists. Skipping...
Folder 'GCA_032428675.1_PDT001822796.1' already exists. Skipping...
Folder 'GCA_032428695.1_PDT001822795.1' already exists. Skipping...
Folder 'GCA_032429295.1_PDT001822758.1' already exists. Skipping...
Folder 'GCA_032429355.1_PDT001822755.1' already exists. Skipping...
Folder 'GCA_032429375.1_PDT001822753.1' already exists. Skipping...
Folder 'GCA_032429435.1_PDT001822748.1' already exists. Skipping...
Folder 'GCA_032429475.1_PDT001822746.1' already exists. Skipping...
Folder 'GCA_032429495.1_PDT001822744.1' already exists. Skipping...
Folder 'GCA_032429575.1_PDT001822740.1' already exists. Skipping...
Folder 'GCA_032429615.1_PDT001822739.1' already exists. Skipping...
Folder 'GCA_032430035.1_PDT001822697.1' already exists. Skipping...
Folder 'GCA_032430055.1_PDT001822696.1' already exists. Skipping...
Folder 'GCA_032430155.1_PDT001822687.1' already exists. Skipping...
Folder 'GCA_032430355.1_PDT001822667.1' already exists. Skipping...
Folder 'GCA_032430595.1_PDT001822636.1' already exists. Skipping...
Folder 'GCA_032430635.1_PDT001822634.1' already exists. Skipping...
Folder 'GCA_032430735.1_PDT001822613.1' already exists. Skipping...
Folder 'GCA_032430755.1_PDT001822610.1' already exists. Skipping...
Folder 'GCA_032430775.1_PDT001822609.1' already exists. Skipping...
Folder 'GCA_032430875.1_PDT001822608.1' already exists. Skipping...
Folder 'GCA_032431235.1_PDT001822561.1' already exists. Skipping...
Folder 'GCA_032431255.1_PDT001822563.1' already exists. Skipping...
Folder 'GCA_032431275.1_PDT001822558.1' already exists. Skipping...
Folder 'GCA_032431315.1_PDT001822559.1' already exists. Skipping...
Folder 'GCA_032431395.1_PDT001822552.1' already exists. Skipping...
Folder 'GCA_032432195.1_PDT001822476.1' already exists. Skipping...
Folder 'GCA_032432255.1_PDT001822472.1' already exists. Skipping...
Folder 'GCA_032432275.1_PDT001822473.1' already exists. Skipping...

Retreiveing data: 95039it [00:15, 6452.40it/s]

Folder 'GCA_032748695.1_PDT001927220.1' already exists. Skipping...
Folder 'GCA_032748735.1_PDT001927169.1' already exists. Skipping...
Folder 'GCA_032749235.1_PDT001941130.1' already exists. Skipping...
Folder 'GCA_032750855.1_PDT001787857.1' already exists. Skipping...
Folder 'GCA_032750885.1_PDT001787858.1' already exists. Skipping...
Folder 'GCA_032750915.1_PDT001787856.1' already exists. Skipping...
Folder 'GCA_032750935.1_PDT001787855.1' already exists. Skipping...
Folder 'GCA_032750955.1_PDT001787854.1' already exists. Skipping...
Folder 'GCA_032750975.1_PDT001787852.1' already exists. Skipping...
Folder 'GCA_032750995.1_PDT001787853.1' already exists. Skipping...
Folder 'GCA_032751015.1_PDT001787851.1' already exists. Skipping...
Folder 'GCA_032751035.1_PDT001787850.1' already exists. Skipping...
Folder 'GCA_032751055.1_PDT001787849.1' already exists. Skipping...
Folder 'GCA_032751075.1_PDT001787848.1' already exists. Skipping...
Folder 'GCA_032751095.1_PDT001787847.1' already exists. Skipping...
Folder 'GCA_032751115.1_PDT001787846.1' already exists. Skipping...
Folder 'GCA_032751135.1_PDT001787845.1' already exists. Skipping...
Folder 'GCA_032751155.1_PDT001787844.1' already exists. Skipping...
Folder 'GCA_032751175.1_PDT001787843.1' already exists. Skipping...
Folder 'GCA_032751195.1_PDT001787842.1' already exists. Skipping...
Folder 'GCA_032751215.1_PDT001787840.1' already exists. Skipping...
Folder 'GCA_032751225.1_PDT001787841.1' already exists. Skipping...
Folder 'GCA_032751255.1_PDT001787839.1' already exists. Skipping...
Folder 'GCA_032751275.1_PDT001787838.1' already exists. Skipping...
Folder 'GCA_032751295.1_PDT001787837.1' already exists. Skipping...
Folder 'GCA_032751305.1_PDT001787824.1' already exists. Skipping...
Folder 'GCA_032751335.1_PDT001787836.1' already exists. Skipping...
Folder 'GCA_032751355.1_PDT001787819.1' already exists. Skipping...
Folder 'GCA_032751375.1_PDT001787818.1' already exists. Skipping...
Folder 'GCA_032751395.1_PDT001787816.1' already exists. Skipping...
Folder 'GCA_032751415.1_PDT001787817.1' already exists. Skipping...
Folder 'GCA_032751435.1_PDT001787815.1' already exists. Skipping...
Folder 'GCA_032751455.1_PDT001787814.1' already exists. Skipping...
Folder 'GCA_032751475.1_PDT001787813.1' already exists. Skipping...
Folder 'GCA_032751495.1_PDT001787811.1' already exists. Skipping...
Folder 'GCA_032751515.1_PDT001787812.1' already exists. Skipping...
Folder 'GCA_032751535.1_PDT001787809.1' already exists. Skipping...
Folder 'GCA_032751555.1_PDT001787810.1' already exists. Skipping...
Folder 'GCA_032751575.1_PDT001787807.1' already exists. Skipping...
Folder 'GCA_032751595.1_PDT001787808.1' already exists. Skipping...
Folder 'GCA_032751615.1_PDT001787805.1' already exists. Skipping...
Folder 'GCA_032751635.1_PDT001787806.1' already exists. Skipping...
Folder 'GCA_032752915.1_PDT001787707.1' already exists. Skipping...
Folder 'GCA_032752935.1_PDT001787705.1' already exists. Skipping...
Folder 'GCA_032753035.1_PDT001787700.1' already exists. Skipping...
Folder 'GCA_032753115.1_PDT001787684.1' already exists. Skipping...
Folder 'GCA_032753175.1_PDT001787695.1' already exists. Skipping...
Folder 'GCA_032753355.1_PDT001787687.1' already exists. Skipping...
Folder 'GCA_032754115.1_PDT001787610.1' already exists. Skipping...
Folder 'GCA_032754355.1_PDT001787460.1' already exists. Skipping...
Folder 'GCA_032754415.1_PDT001787440.1' already exists. Skipping...
Folder 'GCA_032754585.1_PDT001787432.1' already exists. Skipping...
Folder 'GCA_032754695.1_PDT001787424.1' already exists. Skipping...
Folder 'GCA_032754775.1_PDT001787415.1' already exists. Skipping...
Folder 'GCA_032754835.1_PDT001787414.1' already exists. Skipping...
Folder 'GCA_032754855.1_PDT001787411.1' already exists. Skipping...
Folder 'GCA_032754875.1_PDT001787410.1' already exists. Skipping...
Folder 'GCA_032754895.1_PDT001787413.1' already exists. Skipping...
Folder 'GCA_032754915.1_PDT001787409.1' already exists. Skipping...
Folder 'GCA_032754935.1_PDT001787407.1' already exists. Skipping...
Folder 'GCA_032754955.1_PDT001787408.1' already exists. Skipping...
Folder 'GCA_032754985.1_PDT001787404.1' already exists. Skipping...
Folder 'GCA_032755015.1_PDT001787402.1' already exists. Skipping...
Folder 'GCA_032755035.1_PDT001787403.1' already exists. Skipping...
Folder 'GCA_032755055.1_PDT001787400.1' already exists. Skipping...
Folder 'GCA_032755095.1_PDT001787398.1' already exists. Skipping...
Folder 'GCA_032755115.1_PDT001787396.1' already exists. Skipping...
Folder 'GCA_032755135.1_PDT001787395.1' already exists. Skipping...
Folder 'GCA_032755155.1_PDT001787394.1' already exists. Skipping...
Folder 'GCA_032755175.1_PDT001787393.1' already exists. Skipping...
Folder 'GCA_032755195.1_PDT001787391.1' already exists. Skipping...
Folder 'GCA_032755215.1_PDT001787392.1' already exists. Skipping...
Folder 'GCA_032755235.1_PDT001787390.1' already exists. Skipping...
Folder 'GCA_032755255.1_PDT001787389.1' already exists. Skipping...
Folder 'GCA_032755275.1_PDT001787387.1' already exists. Skipping...
Folder 'GCA_032755315.1_PDT001787385.1' already exists. Skipping...
Folder 'GCA_032755335.1_PDT001787384.1' already exists. Skipping...
Folder 'GCA_032755355.1_PDT001787383.1' already exists. Skipping...
Folder 'GCA_032755435.1_PDT001787378.1' already exists. Skipping...
Folder 'GCA_032755495.1_PDT001787377.1' already exists. Skipping...
Folder 'GCA_032755515.1_PDT001787376.1' already exists. Skipping...
Folder 'GCA_032755535.1_PDT001787372.1' already exists. Skipping...
Folder 'GCA_032755555.1_PDT001787272.1' already exists. Skipping...
Folder 'GCA_032755595.1_PDT001787293.1' already exists. Skipping...
Folder 'GCA_032755615.1_PDT001787271.1' already exists. Skipping...
Folder 'GCA_032755635.1_PDT001787269.1' already exists. Skipping...
Folder 'GCA_032755655.1_PDT001787266.1' already exists. Skipping...
Folder 'GCA_032755675.1_PDT001787268.1' already exists. Skipping...
Folder 'GCA_032755695.1_PDT001787264.1' already exists. Skipping...
Folder 'GCA_032755715.1_PDT001787265.1' already exists. Skipping...
Folder 'GCA_032755735.1_PDT001787262.1' already exists. Skipping...
Folder 'GCA_032755755.1_PDT001787261.1' already exists. Skipping...
Folder 'GCA_032755775.1_PDT001787260.1' already exists. Skipping...
Folder 'GCA_032755795.1_PDT001787259.1' already exists. Skipping...
Folder 'GCA_032755815.1_PDT001787258.1' already exists. Skipping...
Folder 'GCA_032755855.1_PDT001787256.1' already exists. Skipping...
Folder 'GCA_032755875.1_PDT001787253.1' already exists. Skipping...
Folder 'GCA_032756235.1_PDT001757818.1' already exists. Skipping...
Folder 'GCA_032756275.1_PDT001757821.1' already exists. Skipping...
Folder 'GCA_032756335.1_PDT001757817.1' already exists. Skipping...
Folder 'GCA_032756375.1_PDT001757815.1' already exists. Skipping...
Folder 'GCA_032756395.1_PDT001757814.1' already exists. Skipping...
Folder 'GCA_032756415.1_PDT001757813.1' already exists. Skipping...
Folder 'GCA_032756435.1_PDT001757810.1' already exists. Skipping...
Folder 'GCA_032756495.1_PDT001757807.1' already exists. Skipping...
Folder 'GCA_032756515.1_PDT001757808.1' already exists. Skipping...
Folder 'GCA_032756595.1_PDT001757803.1' already exists. Skipping...
Folder 'GCA_032756775.1_PDT001736947.1' already exists. Skipping...
Folder 'GCA_032756785.1_PDT001736815.1' already exists. Skipping...
Folder 'GCA_032756815.1_PDT001736690.1' already exists. Skipping...
Folder 'GCA_032756895.1_PDT001707664.1' already exists. Skipping...
Folder 'GCA_032759575.1_PDT001941407.1' already exists. Skipping...
Folder 'GCA_032759615.1_PDT001941397.1' already exists. Skipping...
Folder 'GCA_032759635.1_PDT001941395.1' already exists. Skipping...
Folder 'GCA_032759715.1_PDT001941403.1' already exists. Skipping...
Folder 'GCA_032759795.1_PDT001941401.1' already exists. Skipping...
Folder 'GCA_032759835.1_PDT001941399.1' already exists. Skipping...
Folder 'GCA_032759875.1_PDT001941393.1' already exists. Skipping...
Folder 'GCA_032759915.1_PDT001941390.1' already exists. Skipping...
Folder 'GCA_032759935.1_PDT001941389.1' already exists. Skipping...
Folder 'GCA_032759955.1_PDT001941388.1' already exists. Skipping...
Folder 'GCA_032760035.1_PDT001941384.1' already exists. Skipping...
Folder 'GCA_032760055.1_PDT001941383.1' already exists. Skipping...
Folder 'GCA_032760075.1_PDT001941382.1' already exists. Skipping...
Folder 'GCA_032760455.1_PDT001941365.1' already exists. Skipping...
Folder 'GCA_032760475.1_PDT001941362.1' already exists. Skipping...
Folder 'GCA_032760495.1_PDT001941363.1' already exists. Skipping...
Folder 'GCA_032760515.1_PDT001941364.1' already exists. Skipping...
Folder 'GCA_032760535.1_PDT001941361.1' already exists. Skipping...
Folder 'GCA_032760575.1_PDT001941359.1' already exists. Skipping...
Folder 'GCA_032760715.1_PDT001941351.1' already exists. Skipping...
Folder 'GCA_032760955.1_PDT001941337.1' already exists. Skipping...
Folder 'GCA_032760975.1_PDT001941333.1' already exists. Skipping...
Folder 'GCA_032761135.1_PDT001941319.1' already exists. Skipping...
Folder 'GCA_032761155.1_PDT001941317.1' already exists. Skipping...
Folder 'GCA_032764865.1_PDT001787462.1' already exists. Skipping...
Folder 'GCA_032764905.1_PDT001787461.1' already exists. Skipping...
Folder 'GCA_032764955.1_PDT001787458.1' already exists. Skipping...
Folder 'GCA_032764975.1_PDT001787459.1' already exists. Skipping...
Folder 'GCA_032764995.1_PDT001787457.1' already exists. Skipping...
Folder 'GCA_032765015.1_PDT001787455.1' already exists. Skipping...
Folder 'GCA_032765035.1_PDT001787456.1' already exists. Skipping...
Folder 'GCA_032765055.1_PDT001787454.1' already exists. Skipping...
Folder 'GCA_032765075.1_PDT001787453.1' already exists. Skipping...
Folder 'GCA_032765095.1_PDT001787452.1' already exists. Skipping...
Folder 'GCA_032765115.1_PDT001787450.1' already exists. Skipping...
Folder 'GCA_032765135.1_PDT001787451.1' already exists. Skipping...
Folder 'GCA_032765155.1_PDT001787448.1' already exists. Skipping...
Folder 'GCA_032765175.1_PDT001787449.1' already exists. Skipping...
Folder 'GCA_032765195.1_PDT001787447.1' already exists. Skipping...
Folder 'GCA_032765215.1_PDT001787445.1' already exists. Skipping...
Folder 'GCA_032765235.1_PDT001787446.1' already exists. Skipping...
Folder 'GCA_032765255.1_PDT001787444.1' already exists. Skipping...
Folder 'GCA_032765275.1_PDT001787443.1' already exists. Skipping...
Folder 'GCA_032765295.1_PDT001787442.1' already exists. Skipping...
Folder 'GCA_032765325.1_PDT001787441.1' already exists. Skipping...
Folder 'GCA_032765375.1_PDT001787421.1' already exists. Skipping...
Folder 'GCA_032765395.1_PDT001787417.1' already exists. Skipping...
Folder 'GCA_032765415.1_PDT001787416.1' already exists. Skipping...
Folder 'GCA_032765435.1_PDT001787412.1' already exists. Skipping...
Folder 'GCA_032765455.1_PDT001787406.1' already exists. Skipping...
Folder 'GCA_032765475.1_PDT001787401.1' already exists. Skipping...
Folder 'GCA_032765505.1_PDT001787397.1' already exists. Skipping...
Folder 'GCA_032765575.1_PDT001787332.1' already exists. Skipping...
Folder 'GCA_032765595.1_PDT001787330.1' already exists. Skipping...
Folder 'GCA_032765615.1_PDT001787328.1' already exists. Skipping...
Folder 'GCA_032765635.1_PDT001787329.1' already exists. Skipping...
Folder 'GCA_032765655.1_PDT001787327.1' already exists. Skipping...
Folder 'GCA_032765675.1_PDT001787326.1' already exists. Skipping...
Folder 'GCA_032765695.1_PDT001787325.1' already exists. Skipping...
Folder 'GCA_032765715.1_PDT001787324.1' already exists. Skipping...
Folder 'GCA_032765735.1_PDT001787323.1' already exists. Skipping...
Folder 'GCA_032765755.1_PDT001787321.1' already exists. Skipping...
Folder 'GCA_032765775.1_PDT001787319.1' already exists. Skipping...
Folder 'GCA_032765795.1_PDT001787320.1' already exists. Skipping...
Folder 'GCA_032765815.1_PDT001787322.1' already exists. Skipping...
Folder 'GCA_032765895.1_PDT001787316.1' already exists. Skipping...
Folder 'GCA_032766055.1_PDT001787305.1' already exists. Skipping...
Folder 'GCA_032766275.1_PDT001787294.1' already exists. Skipping...
Folder 'GCA_032766295.1_PDT001787270.1' already exists. Skipping...
Folder 'GCA_032766315.1_PDT001787267.1' already exists. Skipping...
Folder 'GCA_032766335.1_PDT001787263.1' already exists. Skipping...
Folder 'GCA_032766355.1_PDT001787255.1' already exists. Skipping...
Folder 'GCA_032766375.1_PDT001787254.1' already exists. Skipping...
Folder 'GCA_032766395.1_PDT001787257.1' already exists. Skipping...
Folder 'GCA_032766875.1_PDT001787073.1' already exists. Skipping...
Folder 'GCA_032769395.1_PDT001786769.1' already exists. Skipping...
Folder 'GCA_032769435.1_PDT001786767.1' already exists. Skipping...
Folder 'GCA_032769455.1_PDT001786763.1' already exists. Skipping...
Folder 'GCA_032769515.1_PDT001786762.1' already exists. Skipping...
Folder 'GCA_032769675.1_PDT001786739.1' already exists. Skipping...
Folder 'GCA_032769875.1_PDT001786727.1' already exists. Skipping...
Folder 'GCA_032769935.1_PDT001786725.1' already exists. Skipping...
Folder 'GCA_032772755.1_PDT001786499.1' already exists. Skipping...
Folder 'GCA_032772875.1_PDT001786468.1' already exists. Skipping...
Folder 'GCA_032773315.1_PDT001786434.1' already exists. Skipping...
Folder 'GCA_032774415.1_PDT001786223.1' already exists. Skipping...
Folder 'GCA_032774455.1_PDT001786220.1' already exists. Skipping...
Folder 'GCA_032774525.1_PDT001786215.1' already exists. Skipping...
Folder 'GCA_032774555.1_PDT001786219.1' already exists. Skipping...
Folder 'GCA_032774665.1_PDT001786214.1' already exists. Skipping...
Folder 'GCA_032774685.1_PDT001786213.1' already exists. Skipping...
Folder 'GCA_032774725.1_PDT001786212.1' already exists. Skipping...
Folder 'GCA_032774805.1_PDT001786203.1' already exists. Skipping...
Folder 'GCA_032775005.1_PDT001786177.1' already exists. Skipping...
Folder 'GCA_032775185.1_PDT001786168.1' already exists. Skipping...
Folder 'GCA_032775225.1_PDT001786163.1' already exists. Skipping...
Folder 'GCA_032775445.1_PDT001941513.1' already exists. Skipping...
Folder 'GCA_032775465.1_PDT001941512.1' already exists. Skipping...
Folder 'GCA_032775485.1_PDT001941510.1' already exists. Skipping...
Folder 'GCA_032775505.1_PDT001941511.1' already exists. Skipping...
Folder 'GCA_032775525.1_PDT001941507.1' already exists. Skipping...
Folder 'GCA_032775565.1_PDT001941505.1' already exists. Skipping...
Folder 'GCA_032775595.1_PDT001941506.1' already exists. Skipping...
Folder 'GCA_032775645.1_PDT001941502.1' already exists. Skipping...
Folder 'GCA_032775665.1_PDT001941500.1' already exists. Skipping...
Folder 'GCA_032775675.1_PDT001941501.1' already exists. Skipping...
Folder 'GCA_032775705.1_PDT001941499.1' already exists. Skipping...
Folder 'GCA_032775725.1_PDT001941497.1' already exists. Skipping...
Folder 'GCA_032775745.1_PDT001941495.1' already exists. Skipping...
Folder 'GCA_032775765.1_PDT001941494.1' already exists. Skipping...
Folder 'GCA_032775785.1_PDT001941492.1' already exists. Skipping...
Folder 'GCA_032775805.1_PDT001941493.1' already exists. Skipping...
Folder 'GCA_032776445.1_PDT001941508.1' already exists. Skipping...
Folder 'GCA_032776885.1_PDT001786095.1' already exists. Skipping...
Folder 'GCA_032776945.1_PDT001786094.1' already exists. Skipping...
Folder 'GCA_032776965.1_PDT001786093.1' already exists. Skipping...
Folder 'GCA_032776985.1_PDT001786092.1' already exists. Skipping...
Folder 'GCA_032777065.1_PDT001786089.1' already exists. Skipping...
Folder 'GCA_032777085.1_PDT001786082.1' already exists. Skipping...
Folder 'GCA_032777125.1_PDT001786081.1' already exists. Skipping...
Folder 'GCA_032777245.1_PDT001786072.1' already exists. Skipping...
Folder 'GCA_032777785.1_PDT001941496.1' already exists. Skipping...
Folder 'GCA_032777825.1_PDT001941498.1' already exists. Skipping...
Folder 'GCA_032777885.1_PDT001786057.1' already exists. Skipping...
Folder 'GCA_032778365.1_PDT001786023.1' already exists. Skipping...
Folder 'GCA_032780145.1_PDT001785989.1' already exists. Skipping...
Folder 'GCA_032780155.1_PDT001785988.1' already exists. Skipping...
Folder 'GCA_032780425.1_PDT001785967.1' already exists. Skipping...
Folder 'GCA_032781365.1_PDT001785966.1' already exists. Skipping...
Folder 'GCA_032781425.1_PDT001785954.1' already exists. Skipping...
Folder 'GCA_032781665.1_PDT001785945.1' already exists. Skipping...
Folder 'GCA_032782455.1_PDT001941890.1' already exists. Skipping...
Folder 'GCA_032782545.1_PDT001941878.1' already exists. Skipping...
Folder 'GCA_032782585.1_PDT001941879.1' already exists. Skipping...
Folder 'GCA_032782625.1_PDT001941774.1' already exists. Skipping...
Folder 'GCA_032783725.1_PDT001941886.1' already exists. Skipping...
Folder 'GCA_032783785.1_PDT001941876.1' already exists. Skipping...
Folder 'GCA_032784665.1_PDT001785798.1' already exists. Skipping...
Folder 'GCA_032785045.1_PDT001785778.1' already exists. Skipping...
Folder 'GCA_032785105.1_PDT001785775.1' already exists. Skipping...
Folder 'GCA_032785565.1_PDT001941877.1' already exists. Skipping...
Folder 'GCA_032785575.1_PDT001941888.1' already exists. Skipping...
Folder 'GCA_032787745.1_PDT001785728.1' already exists. Skipping...
Folder 'GCA_032787765.1_PDT001785729.1' already exists. Skipping...
Folder 'GCA_032788185.1_PDT001785706.1' already exists. Skipping...
Folder 'GCA_032789365.1_PDT001941775.1' already exists. Skipping...
Folder 'GCA_032790545.1_PDT001785656.1' already exists. Skipping...
Folder 'GCA_032790565.1_PDT001785657.1' already exists. Skipping...
Folder 'GCA_032790615.1_PDT001785655.1' already exists. Skipping...
Folder 'GCA_032790845.1_PDT001941896.1' already exists. Skipping...
Folder 'GCA_032790865.1_PDT001941897.1' already exists. Skipping...
Folder 'GCA_032790885.1_PDT001941898.1' already exists. Skipping...
Folder 'GCA_032790955.1_PDT001941893.1' already exists. Skipping...
Folder 'GCA_032791705.1_PDT001941907.1' already exists. Skipping...
Folder 'GCA_032792645.1_PDT001785546.1' already exists. Skipping...
Folder 'GCA_032794385.1_PDT001785507.1' already exists. Skipping...
Folder 'GCA_032794545.1_PDT001785493.1' already exists. Skipping...
Folder 'GCA_032794565.1_PDT001785491.1' already exists. Skipping...
Folder 'GCA_032794625.1_PDT001785488.1' already exists. Skipping...
Folder 'GCA_032794665.1_PDT001785489.1' already exists. Skipping...
Folder 'GCA_032794905.1_PDT001785484.1' already exists. Skipping...
Folder 'GCA_032794965.1_PDT001785479.1' already exists. Skipping...
Folder 'GCA_032795005.1_PDT001785477.1' already exists. Skipping...
Folder 'GCA_032795065.1_PDT001785474.1' already exists. Skipping...
Folder 'GCA_032795085.1_PDT001785473.1' already exists. Skipping...
Folder 'GCA_032795105.1_PDT001785471.1' already exists. Skipping...
Folder 'GCA_032795125.1_PDT001785469.1' already exists. Skipping...
Folder 'GCA_032795145.1_PDT001785476.1' already exists. Skipping...
Folder 'GCA_032795165.1_PDT001785470.1' already exists. Skipping...
Folder 'GCA_032795185.1_PDT001785465.1' already exists. Skipping...
Folder 'GCA_032795195.1_PDT001785466.1' already exists. Skipping...
Folder 'GCA_032795205.1_PDT001785464.1' already exists. Skipping...
Folder 'GCA_032795245.1_PDT001785468.1' already exists. Skipping...
Folder 'GCA_032795265.1_PDT001785467.1' already exists. Skipping...
Folder 'GCA_032795285.1_PDT001785462.1' already exists. Skipping...
Folder 'GCA_032795305.1_PDT001785463.1' already exists. Skipping...
Folder 'GCA_032795325.1_PDT001785461.1' already exists. Skipping...
Folder 'GCA_032795345.1_PDT001785459.1' already exists. Skipping...
Folder 'GCA_032795365.1_PDT001785460.1' already exists. Skipping...
Folder 'GCA_032795385.1_PDT001785457.1' already exists. Skipping...
Folder 'GCA_032795405.1_PDT001785458.1' already exists. Skipping...
Folder 'GCA_032795425.1_PDT001785456.1' already exists. Skipping...
Folder 'GCA_032795445.1_PDT001785454.1' already exists. Skipping...

Retreiveing data: 96379it [00:15, 6576.26it/s]

Folder 'GCA_032953395.1_PDT001774191.1' already exists. Skipping...
Folder 'GCA_032953415.1_PDT001774190.1' already exists. Skipping...
Folder 'GCA_032954375.1_PDT001774189.1' already exists. Skipping...
Folder 'GCA_032954395.1_PDT001774188.1' already exists. Skipping...
Folder 'GCA_032954415.1_PDT001774185.1' already exists. Skipping...
Folder 'GCA_032954435.1_PDT001774186.1' already exists. Skipping...
Folder 'GCA_032954455.1_PDT001774183.1' already exists. Skipping...
Folder 'GCA_032954475.1_PDT001774182.1' already exists. Skipping...
Folder 'GCA_032954495.1_PDT001774179.1' already exists. Skipping...
Folder 'GCA_032954515.1_PDT001774181.1' already exists. Skipping...
Folder 'GCA_032954575.1_PDT001774174.1' already exists. Skipping...
Folder 'GCA_032954595.1_PDT001774176.1' already exists. Skipping...
Folder 'GCA_032954615.1_PDT001774173.1' already exists. Skipping...
Folder 'GCA_032954635.1_PDT001774171.1' already exists. Skipping...
Folder 'GCA_032954655.1_PDT001774172.1' already exists. Skipping...
Folder 'GCA_032954695.1_PDT001774169.1' already exists. Skipping...
Folder 'GCA_032954715.1_PDT001774168.1' already exists. Skipping...
Folder 'GCA_032954735.1_PDT001774167.1' already exists. Skipping...
Folder 'GCA_032954775.1_PDT001774165.1' already exists. Skipping...
Folder 'GCA_032954795.1_PDT001774164.1' already exists. Skipping...
Folder 'GCA_032954835.1_PDT001774161.1' already exists. Skipping...
Folder 'GCA_032954855.1_PDT001774160.1' already exists. Skipping...
Folder 'GCA_032954975.1_PDT001774154.1' already exists. Skipping...
Folder 'GCA_032954995.1_PDT001774155.1' already exists. Skipping...
Folder 'GCA_032955035.1_PDT001774151.1' already exists. Skipping...
Folder 'GCA_032955075.1_PDT001774148.1' already exists. Skipping...
Folder 'GCA_032955095.1_PDT001774149.1' already exists. Skipping...
Folder 'GCA_032955115.1_PDT001774146.1' already exists. Skipping...
Folder 'GCA_032955135.1_PDT001774145.1' already exists. Skipping...
Folder 'GCA_032955155.1_PDT001774147.1' already exists. Skipping...
Folder 'GCA_032955195.1_PDT001774144.1' already exists. Skipping...
Folder 'GCA_032955215.1_PDT001774142.1' already exists. Skipping...
Folder 'GCA_032955235.1_PDT001774141.1' already exists. Skipping...
Folder 'GCA_032955275.1_PDT001951299.1' already exists. Skipping...
Folder 'GCA_032955315.1_PDT001774250.1' already exists. Skipping...
Folder 'GCA_032955335.1_PDT001774247.1' already exists. Skipping...
Folder 'GCA_032955375.1_PDT001774239.1' already exists. Skipping...
Folder 'GCA_032955395.1_PDT001774237.1' already exists. Skipping...
Folder 'GCA_032955455.1_PDT001774213.1' already exists. Skipping...
Folder 'GCA_032955475.1_PDT001774197.1' already exists. Skipping...
Folder 'GCA_032955495.1_PDT001774199.1' already exists. Skipping...
Folder 'GCA_032955515.1_PDT001774193.1' already exists. Skipping...
Folder 'GCA_032955555.1_PDT001774184.1' already exists. Skipping...
Folder 'GCA_032955575.1_PDT001774175.1' already exists. Skipping...
Folder 'GCA_032955595.1_PDT001774139.1' already exists. Skipping...
Folder 'GCA_032955635.1_PDT001774137.1' already exists. Skipping...
Folder 'GCA_032955655.1_PDT001774138.1' already exists. Skipping...
Folder 'GCA_032955695.1_PDT001774136.1' already exists. Skipping...
Folder 'GCA_032955715.1_PDT001774135.1' already exists. Skipping...
Folder 'GCA_032955775.1_PDT001774131.1' already exists. Skipping...
Folder 'GCA_032955795.1_PDT001774130.1' already exists. Skipping...
Folder 'GCA_032955815.1_PDT001774129.1' already exists. Skipping...
Folder 'GCA_032955835.1_PDT001774127.1' already exists. Skipping...
Folder 'GCA_032955855.1_PDT001774128.1' already exists. Skipping...
Folder 'GCA_032955875.1_PDT001774126.1' already exists. Skipping...
Folder 'GCA_032955895.1_PDT001774125.1' already exists. Skipping...
Folder 'GCA_032955915.1_PDT001774124.1' already exists. Skipping...
Folder 'GCA_032955935.1_PDT001774121.1' already exists. Skipping...
Folder 'GCA_032955955.1_PDT001774122.1' already exists. Skipping...
Folder 'GCA_032955975.1_PDT001774123.1' already exists. Skipping...
Folder 'GCA_032955995.1_PDT001774120.1' already exists. Skipping...
Folder 'GCA_032956015.1_PDT001774119.1' already exists. Skipping...
Folder 'GCA_032956035.1_PDT001774117.1' already exists. Skipping...
Folder 'GCA_032956055.1_PDT001774118.1' already exists. Skipping...
Folder 'GCA_032956075.1_PDT001774116.1' already exists. Skipping...
Folder 'GCA_032956095.1_PDT001774114.1' already exists. Skipping...
Folder 'GCA_032956115.1_PDT001774115.1' already exists. Skipping...
Folder 'GCA_032956155.1_PDT001774112.1' already exists. Skipping...
Folder 'GCA_032956175.1_PDT001774111.1' already exists. Skipping...
Folder 'GCA_032956185.1_PDT001774108.1' already exists. Skipping...
Folder 'GCA_032956215.1_PDT001774109.1' already exists. Skipping...
Folder 'GCA_032956235.1_PDT001774110.1' already exists. Skipping...
Folder 'GCA_032956615.1_PDT001774107.1' already exists. Skipping...
Folder 'GCA_032956635.1_PDT001774106.1' already exists. Skipping...
Folder 'GCA_032956655.1_PDT001774105.1' already exists. Skipping...
Folder 'GCA_032956695.1_PDT001774103.1' already exists. Skipping...
Folder 'GCA_032956735.1_PDT001774101.1' already exists. Skipping...
Folder 'GCA_032956755.1_PDT001774100.1' already exists. Skipping...
Folder 'GCA_032956775.1_PDT001774098.1' already exists. Skipping...
Folder 'GCA_032956795.1_PDT001774099.1' already exists. Skipping...
Folder 'GCA_032956835.1_PDT001774097.1' already exists. Skipping...
Folder 'GCA_032956855.1_PDT001774095.1' already exists. Skipping...
Folder 'GCA_032956875.1_PDT001774094.1' already exists. Skipping...
Folder 'GCA_032956895.1_PDT001774093.1' already exists. Skipping...
Folder 'GCA_032956915.1_PDT001774092.1' already exists. Skipping...
Folder 'GCA_032956935.1_PDT001774091.1' already exists. Skipping...
Folder 'GCA_032956995.1_PDT001774088.1' already exists. Skipping...
Folder 'GCA_032957035.1_PDT001774087.1' already exists. Skipping...
Folder 'GCA_032957075.1_PDT001774085.1' already exists. Skipping...
Folder 'GCA_032957115.1_PDT001774081.1' already exists. Skipping...
Folder 'GCA_032957135.1_PDT001774083.1' already exists. Skipping...
Folder 'GCA_032957155.1_PDT001774080.1' already exists. Skipping...
Folder 'GCA_032957165.1_PDT001774078.1' already exists. Skipping...
Folder 'GCA_032957195.1_PDT001774079.1' already exists. Skipping...
Folder 'GCA_032957215.1_PDT001774077.1' already exists. Skipping...
Folder 'GCA_032957235.1_PDT001774076.1' already exists. Skipping...
Folder 'GCA_032957475.1_PDT001774075.1' already exists. Skipping...
Folder 'GCA_032957495.1_PDT001774074.1' already exists. Skipping...
Folder 'GCA_032957515.1_PDT001774073.1' already exists. Skipping...
Folder 'GCA_032957545.1_PDT001774071.1' already exists. Skipping...
Folder 'GCA_032957565.1_PDT001774072.1' already exists. Skipping...
Folder 'GCA_032957585.1_PDT001774070.1' already exists. Skipping...
Folder 'GCA_032957625.1_PDT001774068.1' already exists. Skipping...
Folder 'GCA_032957645.1_PDT001774066.1' already exists. Skipping...
Folder 'GCA_032957665.1_PDT001774067.1' already exists. Skipping...
Folder 'GCA_032957685.1_PDT001774065.1' already exists. Skipping...
Folder 'GCA_032957705.1_PDT001774064.1' already exists. Skipping...
Folder 'GCA_032957725.1_PDT001774062.1' already exists. Skipping...
Folder 'GCA_032957745.1_PDT001774063.1' already exists. Skipping...
Folder 'GCA_032957765.1_PDT001774060.1' already exists. Skipping...
Folder 'GCA_032957785.1_PDT001774061.1' already exists. Skipping...
Folder 'GCA_032957805.1_PDT001774057.1' already exists. Skipping...
Folder 'GCA_032957825.1_PDT001774059.1' already exists. Skipping...
Folder 'GCA_032957835.1_PDT001774058.1' already exists. Skipping...
Folder 'GCA_032957865.1_PDT001774056.1' already exists. Skipping...
Folder 'GCA_032957905.1_PDT001774054.1' already exists. Skipping...
Folder 'GCA_032957925.1_PDT001774051.1' already exists. Skipping...
Folder 'GCA_032957965.1_PDT001774050.1' already exists. Skipping...
Folder 'GCA_032957985.1_PDT001774052.1' already exists. Skipping...
Folder 'GCA_032958005.1_PDT001774049.1' already exists. Skipping...
Folder 'GCA_032958025.1_PDT001774048.1' already exists. Skipping...
Folder 'GCA_032958045.1_PDT001774047.1' already exists. Skipping...
Folder 'GCA_032958065.1_PDT001774046.1' already exists. Skipping...
Folder 'GCA_032958085.1_PDT001774045.1' already exists. Skipping...
Folder 'GCA_032958105.1_PDT001774043.1' already exists. Skipping...
Folder 'GCA_032958125.1_PDT001774044.1' already exists. Skipping...
Folder 'GCA_032958145.1_PDT001774042.1' already exists. Skipping...
Folder 'GCA_032958165.1_PDT001774041.1' already exists. Skipping...
Folder 'GCA_032958185.1_PDT001774040.1' already exists. Skipping...
Folder 'GCA_032958205.1_PDT001774038.1' already exists. Skipping...
Folder 'GCA_032958215.1_PDT001774039.1' already exists. Skipping...
Folder 'GCA_032958245.1_PDT001774037.1' already exists. Skipping...
Folder 'GCA_032958265.1_PDT001774036.1' already exists. Skipping...
Folder 'GCA_032958345.1_PDT001774034.1' already exists. Skipping...
Folder 'GCA_032958365.1_PDT001774032.1' already exists. Skipping...
Folder 'GCA_032958385.1_PDT001774031.1' already exists. Skipping...
Folder 'GCA_032958445.1_PDT001774028.1' already exists. Skipping...
Folder 'GCA_032958465.1_PDT001774026.1' already exists. Skipping...
Folder 'GCA_032958525.1_PDT001774023.1' already exists. Skipping...
Folder 'GCA_032958535.1_PDT001774024.1' already exists. Skipping...
Folder 'GCA_032958605.1_PDT001774020.1' already exists. Skipping...
Folder 'GCA_032958625.1_PDT001774019.1' already exists. Skipping...
Folder 'GCA_032958665.1_PDT001774017.1' already exists. Skipping...
Folder 'GCA_032958685.1_PDT001774016.1' already exists. Skipping...
Folder 'GCA_032958705.1_PDT001774015.1' already exists. Skipping...
Folder 'GCA_032958725.1_PDT001774014.1' already exists. Skipping...
Folder 'GCA_032958745.1_PDT001774013.1' already exists. Skipping...
Folder 'GCA_032958765.1_PDT001774012.1' already exists. Skipping...
Folder 'GCA_032958785.1_PDT001774011.1' already exists. Skipping...
Folder 'GCA_032958805.1_PDT001774010.1' already exists. Skipping...
Folder 'GCA_032958825.1_PDT001774009.1' already exists. Skipping...
Folder 'GCA_032958845.1_PDT001774007.1' already exists. Skipping...
Folder 'GCA_032958865.1_PDT001774008.1' already exists. Skipping...
Folder 'GCA_032958885.1_PDT001774006.1' already exists. Skipping...
Folder 'GCA_032958945.1_PDT001774004.1' already exists. Skipping...
Folder 'GCA_032958985.1_PDT001774002.1' already exists. Skipping...
Folder 'GCA_032959005.1_PDT001773999.1' already exists. Skipping...
Folder 'GCA_032959065.1_PDT001773996.1' already exists. Skipping...
Folder 'GCA_032959075.1_PDT001773997.1' already exists. Skipping...
Folder 'GCA_032959105.1_PDT001773994.1' already exists. Skipping...
Folder 'GCA_032959145.1_PDT001773993.1' already exists. Skipping...
Folder 'GCA_032959165.1_PDT001773991.1' already exists. Skipping...
Folder 'GCA_032959185.1_PDT001773992.1' already exists. Skipping...
Folder 'GCA_032959225.1_PDT001773987.1' already exists. Skipping...
Folder 'GCA_032959245.1_PDT001773988.1' already exists. Skipping...
Folder 'GCA_032959305.1_PDT001773986.1' already exists. Skipping...
Folder 'GCA_032959365.1_PDT001773984.1' already exists. Skipping...
Folder 'GCA_032959385.1_PDT001773985.1' already exists. Skipping...
Folder 'GCA_032959425.1_PDT001773981.1' already exists. Skipping...
Folder 'GCA_032959465.1_PDT001773980.1' already exists. Skipping...
Folder 'GCA_032959485.1_PDT001773978.1' already exists. Skipping...
Folder 'GCA_032959505.1_PDT001773979.1' already exists. Skipping...
Folder 'GCA_032959525.1_PDT001773976.1' already exists. Skipping...
Folder 'GCA_032959545.1_PDT001773977.1' already exists. Skipping...
Folder 'GCA_032959565.1_PDT001773975.1' already exists. Skipping...
Folder 'GCA_032959585.1_PDT001773974.1' already exists. Skipping...
Folder 'GCA_032959605.1_PDT001773973.1' already exists. Skipping...
Folder 'GCA_032959645.1_PDT001773972.1' already exists. Skipping...
Folder 'GCA_032959665.1_PDT001773967.1' already exists. Skipping...
Folder 'GCA_032959685.1_PDT001773970.1' already exists. Skipping...
Folder 'GCA_032959695.1_PDT001773969.1' already exists. Skipping...
Folder 'GCA_032959745.1_PDT001773965.1' already exists. Skipping...
Folder 'GCA_032959765.1_PDT001773966.1' already exists. Skipping...
Folder 'GCA_032959785.1_PDT001773964.1' already exists. Skipping...
Folder 'GCA_032959805.1_PDT001773963.1' already exists. Skipping...
Folder 'GCA_032959825.1_PDT001773962.1' already exists. Skipping...
Folder 'GCA_032959865.1_PDT001773961.1' already exists. Skipping...
Folder 'GCA_032959885.1_PDT001773958.1' already exists. Skipping...
Folder 'GCA_032959905.1_PDT001773957.1' already exists. Skipping...
Folder 'GCA_032959925.1_PDT001773960.1' already exists. Skipping...
Folder 'GCA_032959945.1_PDT001773956.1' already exists. Skipping...
Folder 'GCA_032959965.1_PDT001773955.1' already exists. Skipping...
Folder 'GCA_032960005.1_PDT001773952.1' already exists. Skipping...
Folder 'GCA_032960025.1_PDT001773954.1' already exists. Skipping...
Folder 'GCA_032960045.1_PDT001773950.1' already exists. Skipping...
Folder 'GCA_032960065.1_PDT001773951.1' already exists. Skipping...
Folder 'GCA_032960085.1_PDT001773949.1' already exists. Skipping...
Folder 'GCA_032960105.1_PDT001773948.1' already exists. Skipping...
Folder 'GCA_032960125.1_PDT001773947.1' already exists. Skipping...
Folder 'GCA_032960145.1_PDT001773946.1' already exists. Skipping...
Folder 'GCA_032960165.1_PDT001773945.1' already exists. Skipping...
Folder 'GCA_032960225.1_PDT001773941.1' already exists. Skipping...
Folder 'GCA_032960325.1_PDT001773936.1' already exists. Skipping...
Folder 'GCA_032960345.1_PDT001773937.1' already exists. Skipping...
Folder 'GCA_032960385.1_PDT001773934.1' already exists. Skipping...
Folder 'GCA_032960405.1_PDT001773932.1' already exists. Skipping...
Folder 'GCA_032960415.1_PDT001773933.1' already exists. Skipping...
Folder 'GCA_032960445.1_PDT001773930.1' already exists. Skipping...
Folder 'GCA_032960485.1_PDT001773929.1' already exists. Skipping...
Folder 'GCA_032960525.1_PDT001773927.1' already exists. Skipping...
Folder 'GCA_032960565.1_PDT001773925.1' already exists. Skipping...
Folder 'GCA_032960585.1_PDT001773926.1' already exists. Skipping...
Folder 'GCA_032960605.1_PDT001773923.1' already exists. Skipping...
Folder 'GCA_032960625.1_PDT001773920.1' already exists. Skipping...
Folder 'GCA_032960645.1_PDT001773922.1' already exists. Skipping...
Folder 'GCA_032960665.1_PDT001773918.1' already exists. Skipping...
Folder 'GCA_032960685.1_PDT001773921.1' already exists. Skipping...
Folder 'GCA_032960705.1_PDT001773919.1' already exists. Skipping...
Folder 'GCA_032960725.1_PDT001773916.1' already exists. Skipping...
Folder 'GCA_032960745.1_PDT001773917.1' already exists. Skipping...
Folder 'GCA_032960765.1_PDT001773914.1' already exists. Skipping...
Folder 'GCA_032960785.1_PDT001773915.1' already exists. Skipping...
Folder 'GCA_032960805.1_PDT001773912.1' already exists. Skipping...
Folder 'GCA_032960825.1_PDT001773911.1' already exists. Skipping...
Folder 'GCA_032960845.1_PDT001773913.1' already exists. Skipping...
Folder 'GCA_032960865.1_PDT001773910.1' already exists. Skipping...
Folder 'GCA_032960885.1_PDT001773909.1' already exists. Skipping...
Folder 'GCA_032960925.1_PDT001773907.1' already exists. Skipping...
Folder 'GCA_032960945.1_PDT001773906.1' already exists. Skipping...
Folder 'GCA_032960965.1_PDT001773903.1' already exists. Skipping...
Folder 'GCA_032960985.1_PDT001773905.1' already exists. Skipping...
Folder 'GCA_032961005.1_PDT001773904.1' already exists. Skipping...
Folder 'GCA_032961045.1_PDT001773902.1' already exists. Skipping...
Folder 'GCA_032961065.1_PDT001773899.1' already exists. Skipping...
Folder 'GCA_032961085.1_PDT001773898.1' already exists. Skipping...
Folder 'GCA_032961105.1_PDT001773900.1' already exists. Skipping...
Folder 'GCA_032961145.1_PDT001773896.1' already exists. Skipping...
Folder 'GCA_032961165.1_PDT001773895.1' already exists. Skipping...
Folder 'GCA_032961185.1_PDT001773893.1' already exists. Skipping...
Folder 'GCA_032961205.1_PDT001773894.1' already exists. Skipping...
Folder 'GCA_032961225.1_PDT001773892.1' already exists. Skipping...
Folder 'GCA_032961245.1_PDT001773890.1' already exists. Skipping...
Folder 'GCA_032961265.1_PDT001773891.1' already exists. Skipping...
Folder 'GCA_032961285.1_PDT001773889.1' already exists. Skipping...
Folder 'GCA_032961305.1_PDT001773888.1' already exists. Skipping...
Folder 'GCA_032961325.1_PDT001773887.1' already exists. Skipping...
Folder 'GCA_032961345.1_PDT001773886.1' already exists. Skipping...
Folder 'GCA_032961365.1_PDT001773885.1' already exists. Skipping...
Folder 'GCA_032961405.1_PDT001773883.1' already exists. Skipping...
Folder 'GCA_032961425.1_PDT001773882.1' already exists. Skipping...
Folder 'GCA_032961445.1_PDT001773881.1' already exists. Skipping...
Folder 'GCA_032961465.1_PDT001773879.1' already exists. Skipping...
Folder 'GCA_032961485.1_PDT001773880.1' already exists. Skipping...
Folder 'GCA_032961505.1_PDT001773878.1' already exists. Skipping...
Folder 'GCA_032961525.1_PDT001773877.1' already exists. Skipping...
Folder 'GCA_032961545.1_PDT001773876.1' already exists. Skipping...
Folder 'GCA_032961585.1_PDT001773874.1' already exists. Skipping...
Folder 'GCA_032961625.1_PDT001773872.1' already exists. Skipping...
Folder 'GCA_032961645.1_PDT001773871.1' already exists. Skipping...
Folder 'GCA_032961665.1_PDT001773870.1' already exists. Skipping...
Folder 'GCA_032961685.1_PDT001773869.1' already exists. Skipping...
Folder 'GCA_032961745.1_PDT001773865.1' already exists. Skipping...
Folder 'GCA_032961765.1_PDT001773866.1' already exists. Skipping...
Folder 'GCA_032961785.1_PDT001773864.1' already exists. Skipping...
Folder 'GCA_032961805.1_PDT001773863.1' already exists. Skipping...
Folder 'GCA_032961825.1_PDT001773862.1' already exists. Skipping...
Folder 'GCA_032961865.1_PDT001773860.1' already exists. Skipping...
Folder 'GCA_032961885.1_PDT001773859.1' already exists. Skipping...
Folder 'GCA_032961905.1_PDT001773858.1' already exists. Skipping...
Folder 'GCA_032961925.1_PDT001773857.1' already exists. Skipping...
Folder 'GCA_032961945.1_PDT001773856.1' already exists. Skipping...
Folder 'GCA_032962005.1_PDT001773853.1' already exists. Skipping...
Folder 'GCA_032962025.1_PDT001773851.1' already exists. Skipping...
Folder 'GCA_032962045.1_PDT001773852.1' already exists. Skipping...
Folder 'GCA_032962065.1_PDT001773850.1' already exists. Skipping...
Folder 'GCA_032962085.1_PDT001773849.1' already exists. Skipping...
Folder 'GCA_032962105.1_PDT001773848.1' already exists. Skipping...
Folder 'GCA_032962125.1_PDT001773847.1' already exists. Skipping...
Folder 'GCA_032962145.1_PDT001773846.1' already exists. Skipping...
Folder 'GCA_032962165.1_PDT001773845.1' already exists. Skipping...
Folder 'GCA_032962185.1_PDT001773843.1' already exists. Skipping...
Folder 'GCA_032962205.1_PDT001773844.1' already exists. Skipping...
Folder 'GCA_032962225.1_PDT001773842.1' already exists. Skipping...
Folder 'GCA_032962265.1_PDT001773841.1' already exists. Skipping...
Folder 'GCA_032962365.1_PDT001773837.1' already exists. Skipping...
Folder 'GCA_032962375.1_PDT001773839.1' already exists. Skipping...
Folder 'GCA_032962425.1_PDT001773840.1' already exists. Skipping...
Folder 'GCA_032962565.1_PDT001773831.1' already exists. Skipping...
Folder 'GCA_032962585.1_PDT001773829.1' already exists. Skipping...
Folder 'GCA_032962605.1_PDT001773830.1' already exists. Skipping...
Folder 'GCA_032962625.1_PDT001773828.1' already exists. Skipping...
Folder 'GCA_032962645.1_PDT001773827.1' already exists. Skipping...
Folder 'GCA_032962665.1_PDT001773825.1' already exists. Skipping...
Folder 'GCA_032962685.1_PDT001773824.1' already exists. Skipping...

Retreiveing data: 97712it [00:16, 6622.81it/s]

Folder 'GCA_033063475.1_PDT001758063.1' already exists. Skipping...
Folder 'GCA_033063495.1_PDT001758064.1' already exists. Skipping...
Folder 'GCA_033063515.1_PDT001758062.1' already exists. Skipping...
Folder 'GCA_033063535.1_PDT001758061.1' already exists. Skipping...
Folder 'GCA_033063595.1_PDT001758060.1' already exists. Skipping...
Folder 'GCA_033063635.1_PDT001758059.1' already exists. Skipping...
Folder 'GCA_033063675.1_PDT001758056.1' already exists. Skipping...
Folder 'GCA_033063695.1_PDT001758057.1' already exists. Skipping...
Folder 'GCA_033063715.1_PDT001758055.1' already exists. Skipping...
Folder 'GCA_033063735.1_PDT001758054.1' already exists. Skipping...
Folder 'GCA_033063755.1_PDT001758052.1' already exists. Skipping...
Folder 'GCA_033063775.1_PDT001758051.1' already exists. Skipping...
Folder 'GCA_033063785.1_PDT001758049.1' already exists. Skipping...
Folder 'GCA_033063815.1_PDT001758050.1' already exists. Skipping...
Folder 'GCA_033063835.1_PDT001758048.1' already exists. Skipping...
Folder 'GCA_033063935.1_PDT001758042.1' already exists. Skipping...
Folder 'GCA_033063955.1_PDT001758041.1' already exists. Skipping...
Folder 'GCA_033063975.1_PDT001758043.1' already exists. Skipping...
Folder 'GCA_033063995.1_PDT001758040.1' already exists. Skipping...
Folder 'GCA_033064015.1_PDT001758039.1' already exists. Skipping...
Folder 'GCA_033064035.1_PDT001758038.1' already exists. Skipping...
Folder 'GCA_033064055.1_PDT001758037.1' already exists. Skipping...
Folder 'GCA_033064095.1_PDT001758035.1' already exists. Skipping...
Folder 'GCA_033064115.1_PDT001758034.1' already exists. Skipping...
Folder 'GCA_033064325.1_PDT001758023.1' already exists. Skipping...
Folder 'GCA_033064365.1_PDT001758022.1' already exists. Skipping...
Folder 'GCA_033064385.1_PDT001758021.1' already exists. Skipping...
Folder 'GCA_033064405.1_PDT001758020.1' already exists. Skipping...
Folder 'GCA_033064465.1_PDT001758017.1' already exists. Skipping...
Folder 'GCA_033064485.1_PDT001758016.1' already exists. Skipping...
Folder 'GCA_033064505.1_PDT001758014.1' already exists. Skipping...
Folder 'GCA_033064545.1_PDT001758015.1' already exists. Skipping...
Folder 'GCA_033064835.1_PDT001758004.1' already exists. Skipping...
Folder 'GCA_033064875.1_PDT001758003.1' already exists. Skipping...
Folder 'GCA_033064895.1_PDT001758002.1' already exists. Skipping...
Folder 'GCA_033064915.1_PDT001758001.1' already exists. Skipping...
Folder 'GCA_033064935.1_PDT001757999.1' already exists. Skipping...
Folder 'GCA_033064955.1_PDT001758000.1' already exists. Skipping...
Folder 'GCA_033064995.1_PDT001757997.1' already exists. Skipping...
Folder 'GCA_033065005.1_PDT001757998.1' already exists. Skipping...
Folder 'GCA_033065035.1_PDT001757996.1' already exists. Skipping...
Folder 'GCA_033065055.1_PDT001757995.1' already exists. Skipping...
Folder 'GCA_033065315.1_PDT001757981.1' already exists. Skipping...
Folder 'GCA_033065335.1_PDT001757980.1' already exists. Skipping...
Folder 'GCA_033065355.1_PDT001757979.1' already exists. Skipping...
Folder 'GCA_033065375.1_PDT001757977.1' already exists. Skipping...
Folder 'GCA_033065395.1_PDT001757976.1' already exists. Skipping...
Folder 'GCA_033065415.1_PDT001757978.1' already exists. Skipping...
Folder 'GCA_033065435.1_PDT001757975.1' already exists. Skipping...
Folder 'GCA_033065455.1_PDT001757974.1' already exists. Skipping...
Folder 'GCA_033065475.1_PDT001757973.1' already exists. Skipping...
Folder 'GCA_033065495.1_PDT001757972.1' already exists. Skipping...
Folder 'GCA_033065985.1_PDT001746450.1' already exists. Skipping...
Folder 'GCA_033066035.1_PDT001746449.1' already exists. Skipping...
Folder 'GCA_033066065.1_PDT001746448.1' already exists. Skipping...
Folder 'GCA_033066085.1_PDT001746446.1' already exists. Skipping...
Folder 'GCA_033066105.1_PDT001746447.1' already exists. Skipping...
Folder 'GCA_033066125.1_PDT001746445.1' already exists. Skipping...
Folder 'GCA_033066145.1_PDT001746444.1' already exists. Skipping...
Folder 'GCA_033066165.1_PDT001746442.1' already exists. Skipping...
Folder 'GCA_033066185.1_PDT001746440.1' already exists. Skipping...
Folder 'GCA_033066215.1_PDT001746439.1' already exists. Skipping...
Folder 'GCA_033066245.1_PDT001746437.1' already exists. Skipping...
Folder 'GCA_033066265.1_PDT001746438.1' already exists. Skipping...
Folder 'GCA_033066285.1_PDT001746436.1' already exists. Skipping...
Folder 'GCA_033066305.1_PDT001746434.1' already exists. Skipping...
Folder 'GCA_033066325.1_PDT001746432.1' already exists. Skipping...
Folder 'GCA_033066345.1_PDT001746435.1' already exists. Skipping...
Folder 'GCA_033066365.1_PDT001746430.1' already exists. Skipping...
Folder 'GCA_033066385.1_PDT001746431.1' already exists. Skipping...
Folder 'GCA_033066405.1_PDT001746429.1' already exists. Skipping...
Folder 'GCA_033066415.1_PDT001746428.1' already exists. Skipping...
Folder 'GCA_033066445.1_PDT001746427.1' already exists. Skipping...
Folder 'GCA_033066465.1_PDT001746426.1' already exists. Skipping...
Folder 'GCA_033066485.1_PDT001746425.1' already exists. Skipping...
Folder 'GCA_033066505.1_PDT001746422.1' already exists. Skipping...
Folder 'GCA_033066525.1_PDT001746424.1' already exists. Skipping...
Folder 'GCA_033066545.1_PDT001746423.1' already exists. Skipping...
Folder 'GCA_033066565.1_PDT001746421.1' already exists. Skipping...
Folder 'GCA_033066585.1_PDT001746420.1' already exists. Skipping...
Folder 'GCA_033066605.1_PDT001746418.1' already exists. Skipping...
Folder 'GCA_033066645.1_PDT001746419.1' already exists. Skipping...
Folder 'GCA_033066665.1_PDT001746417.1' already exists. Skipping...
Folder 'GCA_033066695.1_PDT001746415.1' already exists. Skipping...
Folder 'GCA_033066705.1_PDT001746412.1' already exists. Skipping...
Folder 'GCA_033066745.1_PDT001746413.1' already exists. Skipping...
Folder 'GCA_033066755.1_PDT001746416.1' already exists. Skipping...
Folder 'GCA_033066795.1_PDT001746410.1' already exists. Skipping...
Folder 'GCA_033066815.1_PDT001746408.1' already exists. Skipping...
Folder 'GCA_033066835.1_PDT001746409.1' already exists. Skipping...
Folder 'GCA_033066855.1_PDT001746407.1' already exists. Skipping...
Folder 'GCA_033066875.1_PDT001746406.1' already exists. Skipping...
Folder 'GCA_033066895.1_PDT001746405.1' already exists. Skipping...
Folder 'GCA_033066905.1_PDT001746404.1' already exists. Skipping...
Folder 'GCA_033066935.1_PDT001746403.1' already exists. Skipping...
Folder 'GCA_033066955.1_PDT001746402.1' already exists. Skipping...
Folder 'GCA_033066975.1_PDT001746400.1' already exists. Skipping...
Folder 'GCA_033066995.1_PDT001746398.1' already exists. Skipping...
Folder 'GCA_033067035.1_PDT001746397.1' already exists. Skipping...
Folder 'GCA_033067055.1_PDT001746396.1' already exists. Skipping...
Folder 'GCA_033067075.1_PDT001746395.1' already exists. Skipping...
Folder 'GCA_033067095.1_PDT001746394.1' already exists. Skipping...
Folder 'GCA_033067115.1_PDT001746392.1' already exists. Skipping...
Folder 'GCA_033067125.1_PDT001746393.1' already exists. Skipping...
Folder 'GCA_033067155.1_PDT001746391.1' already exists. Skipping...
Folder 'GCA_033067175.1_PDT001746390.1' already exists. Skipping...
Folder 'GCA_033067195.1_PDT001746389.1' already exists. Skipping...
Folder 'GCA_033067215.1_PDT001746388.1' already exists. Skipping...
Folder 'GCA_033067235.1_PDT001746387.1' already exists. Skipping...
Folder 'GCA_033067255.1_PDT001746385.1' already exists. Skipping...
Folder 'GCA_033067275.1_PDT001746384.1' already exists. Skipping...
Folder 'GCA_033067295.1_PDT001746383.1' already exists. Skipping...
Folder 'GCA_033067315.1_PDT001746382.1' already exists. Skipping...
Folder 'GCA_033067335.1_PDT001746381.1' already exists. Skipping...
Folder 'GCA_033067355.1_PDT001746379.1' already exists. Skipping...
Folder 'GCA_033067375.1_PDT001746378.1' already exists. Skipping...
Folder 'GCA_033067395.1_PDT001746380.1' already exists. Skipping...
Folder 'GCA_033067415.1_PDT001746375.1' already exists. Skipping...
Folder 'GCA_033067435.1_PDT001746377.1' already exists. Skipping...
Folder 'GCA_033067455.1_PDT001746374.1' already exists. Skipping...
Folder 'GCA_033067475.1_PDT001746372.1' already exists. Skipping...
Folder 'GCA_033067495.1_PDT001746370.1' already exists. Skipping...
Folder 'GCA_033067515.1_PDT001746371.1' already exists. Skipping...
Folder 'GCA_033067535.1_PDT001746369.1' already exists. Skipping...
Folder 'GCA_033067555.1_PDT001746367.1' already exists. Skipping...
Folder 'GCA_033067575.1_PDT001746368.1' already exists. Skipping...
Folder 'GCA_033067595.1_PDT001746364.1' already exists. Skipping...
Folder 'GCA_033067615.1_PDT001746365.1' already exists. Skipping...
Folder 'GCA_033067635.1_PDT001746363.1' already exists. Skipping...
Folder 'GCA_033067655.1_PDT001746361.1' already exists. Skipping...
Folder 'GCA_033067675.1_PDT001746362.1' already exists. Skipping...
Folder 'GCA_033067695.1_PDT001746359.1' already exists. Skipping...
Folder 'GCA_033067715.1_PDT001746360.1' already exists. Skipping...
Folder 'GCA_033067735.1_PDT001746357.1' already exists. Skipping...
Folder 'GCA_033067755.1_PDT001746355.1' already exists. Skipping...
Folder 'GCA_033067775.1_PDT001746358.1' already exists. Skipping...
Folder 'GCA_033067795.1_PDT001746354.1' already exists. Skipping...
Folder 'GCA_033067815.1_PDT001746353.1' already exists. Skipping...
Folder 'GCA_033067855.1_PDT001746351.1' already exists. Skipping...
Folder 'GCA_033067875.1_PDT001746350.1' already exists. Skipping...
Folder 'GCA_033067895.1_PDT001746347.1' already exists. Skipping...
Folder 'GCA_033067915.1_PDT001746349.1' already exists. Skipping...
Folder 'GCA_033067935.1_PDT001746348.1' already exists. Skipping...
Folder 'GCA_033067955.1_PDT001746345.1' already exists. Skipping...
Folder 'GCA_033067975.1_PDT001746344.1' already exists. Skipping...
Folder 'GCA_033067995.1_PDT001746342.1' already exists. Skipping...
Folder 'GCA_033068015.1_PDT001746343.1' already exists. Skipping...
Folder 'GCA_033068035.1_PDT001746341.1' already exists. Skipping...
Folder 'GCA_033068055.1_PDT001746340.1' already exists. Skipping...
Folder 'GCA_033068075.1_PDT001746339.1' already exists. Skipping...
Folder 'GCA_033068115.1_PDT001746338.1' already exists. Skipping...
Folder 'GCA_033068135.1_PDT001746334.1' already exists. Skipping...
Folder 'GCA_033068155.1_PDT001746335.1' already exists. Skipping...
Folder 'GCA_033068175.1_PDT001746333.1' already exists. Skipping...
Folder 'GCA_033068195.1_PDT001746331.1' already exists. Skipping...
Folder 'GCA_033068235.1_PDT001746330.1' already exists. Skipping...
Folder 'GCA_033068255.1_PDT001746329.1' already exists. Skipping...
Folder 'GCA_033068295.1_PDT001746327.1' already exists. Skipping...
Folder 'GCA_033068315.1_PDT001746323.1' already exists. Skipping...
Folder 'GCA_033068335.1_PDT001746325.1' already exists. Skipping...
Folder 'GCA_033068355.1_PDT001746321.1' already exists. Skipping...
Folder 'GCA_033068375.1_PDT001746317.1' already exists. Skipping...
Folder 'GCA_033068395.1_PDT001746322.1' already exists. Skipping...
Folder 'GCA_033068415.1_PDT001746318.1' already exists. Skipping...
Folder 'GCA_033068435.1_PDT001746320.1' already exists. Skipping...
Folder 'GCA_033068455.1_PDT001746319.1' already exists. Skipping...
Folder 'GCA_033068475.1_PDT001746315.1' already exists. Skipping...
Folder 'GCA_033068495.1_PDT001746316.1' already exists. Skipping...
Folder 'GCA_033068515.1_PDT001746314.1' already exists. Skipping...
Folder 'GCA_033068535.1_PDT001746313.1' already exists. Skipping...
Folder 'GCA_033068555.1_PDT001746312.1' already exists. Skipping...
Folder 'GCA_033068595.1_PDT001746308.1' already exists. Skipping...
Folder 'GCA_033068615.1_PDT001746309.1' already exists. Skipping...
Folder 'GCA_033068635.1_PDT001746306.1' already exists. Skipping...
Folder 'GCA_033068655.1_PDT001746307.1' already exists. Skipping...
Folder 'GCA_033068675.1_PDT001746305.1' already exists. Skipping...
Folder 'GCA_033068695.1_PDT001746304.1' already exists. Skipping...
Folder 'GCA_033068715.1_PDT001746303.1' already exists. Skipping...
Folder 'GCA_033068735.1_PDT001746299.1' already exists. Skipping...
Folder 'GCA_033068755.1_PDT001746298.1' already exists. Skipping...
Folder 'GCA_033068795.1_PDT001746295.1' already exists. Skipping...
Folder 'GCA_033068815.1_PDT001746296.1' already exists. Skipping...
Folder 'GCA_033068835.1_PDT001746294.1' already exists. Skipping...
Folder 'GCA_033068855.1_PDT001746292.1' already exists. Skipping...
Folder 'GCA_033068875.1_PDT001746293.1' already exists. Skipping...
Folder 'GCA_033068895.1_PDT001746291.1' already exists. Skipping...
Folder 'GCA_033068915.1_PDT001746290.1' already exists. Skipping...
Folder 'GCA_033068935.1_PDT001746289.1' already exists. Skipping...
Folder 'GCA_033068955.1_PDT001746287.1' already exists. Skipping...
Folder 'GCA_033068995.1_PDT001746286.1' already exists. Skipping...
Folder 'GCA_033069015.1_PDT001746284.1' already exists. Skipping...
Folder 'GCA_033069035.1_PDT001746285.1' already exists. Skipping...
Folder 'GCA_033069055.1_PDT001746283.1' already exists. Skipping...
Folder 'GCA_033069075.1_PDT001746281.1' already exists. Skipping...
Folder 'GCA_033069095.1_PDT001746282.1' already exists. Skipping...
Folder 'GCA_033069115.1_PDT001746278.1' already exists. Skipping...
Folder 'GCA_033069135.1_PDT001746280.1' already exists. Skipping...
Folder 'GCA_033069155.1_PDT001746277.1' already exists. Skipping...
Folder 'GCA_033069175.1_PDT001746276.1' already exists. Skipping...
Folder 'GCA_033069195.1_PDT001746274.1' already exists. Skipping...
Folder 'GCA_033069215.1_PDT001746275.1' already exists. Skipping...
Folder 'GCA_033069235.1_PDT001746273.1' already exists. Skipping...
Folder 'GCA_033069255.1_PDT001746272.1' already exists. Skipping...
Folder 'GCA_033069275.1_PDT001746271.1' already exists. Skipping...
Folder 'GCA_033069295.1_PDT001746268.1' already exists. Skipping...
Folder 'GCA_033069315.1_PDT001746270.1' already exists. Skipping...
Folder 'GCA_033069335.1_PDT001746267.1' already exists. Skipping...
Folder 'GCA_033069355.1_PDT001746265.1' already exists. Skipping...
Folder 'GCA_033069375.1_PDT001746266.1' already exists. Skipping...
Folder 'GCA_033069395.1_PDT001746263.1' already exists. Skipping...
Folder 'GCA_033069435.1_PDT001746261.1' already exists. Skipping...
Folder 'GCA_033069475.1_PDT001746260.1' already exists. Skipping...
Folder 'GCA_033069495.1_PDT001746259.1' already exists. Skipping...
Folder 'GCA_033069515.1_PDT001746258.1' already exists. Skipping...
Folder 'GCA_033069535.1_PDT001746257.1' already exists. Skipping...
Folder 'GCA_033069555.1_PDT001746256.1' already exists. Skipping...
Folder 'GCA_033069575.1_PDT001746255.1' already exists. Skipping...
Folder 'GCA_033069635.1_PDT001746254.1' already exists. Skipping...
Folder 'GCA_033069655.1_PDT001746251.1' already exists. Skipping...
Folder 'GCA_033069675.1_PDT001746253.1' already exists. Skipping...
Folder 'GCA_033069695.1_PDT001746252.1' already exists. Skipping...
Folder 'GCA_033069715.1_PDT001746250.1' already exists. Skipping...
Folder 'GCA_033069735.1_PDT001746247.1' already exists. Skipping...
Folder 'GCA_033069755.1_PDT001746248.1' already exists. Skipping...
Folder 'GCA_033069775.1_PDT001746246.1' already exists. Skipping...
Folder 'GCA_033069795.1_PDT001746245.1' already exists. Skipping...
Folder 'GCA_033069815.1_PDT001746244.1' already exists. Skipping...
Folder 'GCA_033069835.1_PDT001746243.1' already exists. Skipping...
Folder 'GCA_033069855.1_PDT001746242.1' already exists. Skipping...
Folder 'GCA_033069875.1_PDT001746241.1' already exists. Skipping...
Folder 'GCA_033069895.1_PDT001746240.1' already exists. Skipping...
Folder 'GCA_033069905.1_PDT001746239.1' already exists. Skipping...
Folder 'GCA_033069935.1_PDT001746238.1' already exists. Skipping...
Folder 'GCA_033069955.1_PDT001746237.1' already exists. Skipping...
Folder 'GCA_033069975.1_PDT001746235.1' already exists. Skipping...
Folder 'GCA_033069995.1_PDT001746236.1' already exists. Skipping...
Folder 'GCA_033070035.1_PDT001746232.1' already exists. Skipping...
Folder 'GCA_033070075.1_PDT001746231.1' already exists. Skipping...
Folder 'GCA_033070115.1_PDT001746234.1' already exists. Skipping...
Folder 'GCA_033070135.1_PDT001746229.1' already exists. Skipping...
Folder 'GCA_033070155.1_PDT001746230.1' already exists. Skipping...
Folder 'GCA_033070175.1_PDT001746228.1' already exists. Skipping...
Folder 'GCA_033070615.1_PDT001746203.1' already exists. Skipping...
Folder 'GCA_033070675.1_PDT001746200.1' already exists. Skipping...
Folder 'GCA_033070695.1_PDT001746198.1' already exists. Skipping...
Folder 'GCA_033070715.1_PDT001746195.1' already exists. Skipping...
Folder 'GCA_033070735.1_PDT001746196.1' already exists. Skipping...
Folder 'GCA_033070755.1_PDT001746197.1' already exists. Skipping...
Folder 'GCA_033070775.1_PDT001746193.1' already exists. Skipping...
Folder 'GCA_033070795.1_PDT001746190.1' already exists. Skipping...
Folder 'GCA_033070815.1_PDT001746191.1' already exists. Skipping...
Folder 'GCA_033070835.1_PDT001746188.1' already exists. Skipping...
Folder 'GCA_033070855.1_PDT001746189.1' already exists. Skipping...
Folder 'GCA_033070875.1_PDT001746187.1' already exists. Skipping...
Folder 'GCA_033070895.1_PDT001746185.1' already exists. Skipping...
Folder 'GCA_033070915.1_PDT001746181.1' already exists. Skipping...
Folder 'GCA_033070935.1_PDT001746183.1' already exists. Skipping...
Folder 'GCA_033070965.1_PDT001746184.1' already exists. Skipping...
Folder 'GCA_033070995.1_PDT001746179.1' already exists. Skipping...
Folder 'GCA_033071015.1_PDT001746180.1' already exists. Skipping...
Folder 'GCA_033071025.1_PDT001746178.1' already exists. Skipping...
Folder 'GCA_033071055.1_PDT001746176.1' already exists. Skipping...
Folder 'GCA_033071095.1_PDT001746177.1' already exists. Skipping...
Folder 'GCA_033071115.1_PDT001746173.1' already exists. Skipping...
Folder 'GCA_033071135.1_PDT001746174.1' already exists. Skipping...
Folder 'GCA_033071155.1_PDT001746172.1' already exists. Skipping...
Folder 'GCA_033071175.1_PDT001746171.1' already exists. Skipping...
Folder 'GCA_033071195.1_PDT001746170.1' already exists. Skipping...
Folder 'GCA_033071215.1_PDT001746169.1' already exists. Skipping...
Folder 'GCA_033071235.1_PDT001746167.1' already exists. Skipping...
Folder 'GCA_033071255.1_PDT001746166.1' already exists. Skipping...
Folder 'GCA_033071275.1_PDT001746168.1' already exists. Skipping...
Folder 'GCA_033071295.1_PDT001746165.1' already exists. Skipping...
Folder 'GCA_033071315.1_PDT001746164.1' already exists. Skipping...
Folder 'GCA_033071335.1_PDT001746161.1' already exists. Skipping...
Folder 'GCA_033071345.1_PDT001746162.1' already exists. Skipping...
Folder 'GCA_033071355.1_PDT001746160.1' already exists. Skipping...
Folder 'GCA_033071395.1_PDT001746158.1' already exists. Skipping...
Folder 'GCA_033071415.1_PDT001746159.1' already exists. Skipping...
Folder 'GCA_033071435.1_PDT001746156.1' already exists. Skipping...
Folder 'GCA_033071475.1_PDT001746154.1' already exists. Skipping...
Folder 'GCA_033071495.1_PDT001746152.1' already exists. Skipping...
Folder 'GCA_033071515.1_PDT001746153.1' already exists. Skipping...
Folder 'GCA_033071535.1_PDT001746151.1' already exists. Skipping...
Folder 'GCA_033071555.1_PDT001746150.1' already exists. Skipping...
Folder 'GCA_033071565.1_PDT001746149.1' already exists. Skipping...
Folder 'GCA_033071615.1_PDT001746146.1' already exists. Skipping...
Folder 'GCA_033071675.1_PDT001746145.1' already exists. Skipping...
Folder 'GCA_033071685.1_PDT001746143.1' already exists. Skipping...
Folder 'GCA_033071755.1_PDT001746142.1' already exists. Skipping...
Folder 'GCA_033071775.1_PDT001746141.1' already exists. Skipping...
Folder 'GCA_033071795.1_PDT001746139.1' already exists. Skipping...
Folder 'GCA_033071815.1_PDT001746138.1' already exists. Skipping...
Folder 'GCA_033071875.1_PDT001746135.1' already exists. Skipping...

Retreiveing data: 99041it [00:16, 6629.13it/s]

Folder 'GCA_033210175.1_PDT001757531.1' already exists. Skipping...
Folder 'GCA_033210195.1_PDT001757530.1' already exists. Skipping...
Folder 'GCA_033210215.1_PDT001757528.1' already exists. Skipping...
Folder 'GCA_033210235.1_PDT001757526.1' already exists. Skipping...
Folder 'GCA_033210255.1_PDT001757529.1' already exists. Skipping...
Folder 'GCA_033210275.1_PDT001757525.1' already exists. Skipping...
Folder 'GCA_033210295.1_PDT001757527.1' already exists. Skipping...
Folder 'GCA_033210315.1_PDT001757522.1' already exists. Skipping...
Folder 'GCA_033210335.1_PDT001757523.1' already exists. Skipping...
Folder 'GCA_033210355.1_PDT001757524.1' already exists. Skipping...
Folder 'GCA_033210395.1_PDT001757521.1' already exists. Skipping...
Folder 'GCA_033210415.1_PDT001757519.1' already exists. Skipping...
Folder 'GCA_033210435.1_PDT001757518.1' already exists. Skipping...
Folder 'GCA_033210455.1_PDT001757517.1' already exists. Skipping...
Folder 'GCA_033210475.1_PDT001757514.1' already exists. Skipping...
Folder 'GCA_033210535.1_PDT001757513.1' already exists. Skipping...
Folder 'GCA_033211035.1_PDT001757435.1' already exists. Skipping...
Folder 'GCA_033211075.1_PDT001757434.1' already exists. Skipping...
Folder 'GCA_033211095.1_PDT001757418.1' already exists. Skipping...
Folder 'GCA_033211115.1_PDT001757433.1' already exists. Skipping...
Folder 'GCA_033211135.1_PDT001757415.1' already exists. Skipping...
Folder 'GCA_033211275.1_PDT001757421.1' already exists. Skipping...
Folder 'GCA_033211295.1_PDT001757422.1' already exists. Skipping...
Folder 'GCA_033211315.1_PDT001757420.1' already exists. Skipping...
Folder 'GCA_033211335.1_PDT001757419.1' already exists. Skipping...
Folder 'GCA_033211355.1_PDT001757417.1' already exists. Skipping...
Folder 'GCA_033211375.1_PDT001757416.1' already exists. Skipping...
Folder 'GCA_033211395.1_PDT001757414.1' already exists. Skipping...
Folder 'GCA_033211415.1_PDT001757413.1' already exists. Skipping...
Folder 'GCA_033211435.1_PDT001757412.1' already exists. Skipping...
Folder 'GCA_033211455.1_PDT001757411.1' already exists. Skipping...
Folder 'GCA_033211475.1_PDT001757410.1' already exists. Skipping...
Folder 'GCA_033211495.1_PDT001757409.1' already exists. Skipping...
Folder 'GCA_033211515.1_PDT001757406.1' already exists. Skipping...
Folder 'GCA_033211555.1_PDT001757408.1' already exists. Skipping...
Folder 'GCA_033211575.1_PDT001757404.1' already exists. Skipping...
Folder 'GCA_033211615.1_PDT001757403.1' already exists. Skipping...
Folder 'GCA_033211655.1_PDT001757399.1' already exists. Skipping...
Folder 'GCA_033211675.1_PDT001757398.1' already exists. Skipping...
Folder 'GCA_033211695.1_PDT001757402.1' already exists. Skipping...
Folder 'GCA_033211715.1_PDT001757397.1' already exists. Skipping...
Folder 'GCA_033211735.1_PDT001757396.1' already exists. Skipping...
Folder 'GCA_033211755.1_PDT001757394.1' already exists. Skipping...
Folder 'GCA_033211775.1_PDT001757395.1' already exists. Skipping...
Folder 'GCA_033211795.1_PDT001757392.1' already exists. Skipping...
Folder 'GCA_033211815.1_PDT001757393.1' already exists. Skipping...
Folder 'GCA_033211835.1_PDT001757391.1' already exists. Skipping...
Folder 'GCA_033211855.1_PDT001757390.1' already exists. Skipping...
Folder 'GCA_033211875.1_PDT001757389.1' already exists. Skipping...
Folder 'GCA_033211895.1_PDT001757388.1' already exists. Skipping...
Folder 'GCA_033211915.1_PDT001757387.1' already exists. Skipping...
Folder 'GCA_033211935.1_PDT001757386.1' already exists. Skipping...
Folder 'GCA_033211955.1_PDT001757384.1' already exists. Skipping...
Folder 'GCA_033211995.1_PDT001757382.1' already exists. Skipping...
Folder 'GCA_033212015.1_PDT001757379.1' already exists. Skipping...
Folder 'GCA_033212035.1_PDT001757381.1' already exists. Skipping...
Folder 'GCA_033212055.1_PDT001757378.1' already exists. Skipping...
Folder 'GCA_033212075.1_PDT001757377.1' already exists. Skipping...
Folder 'GCA_033212095.1_PDT001757376.1' already exists. Skipping...
Folder 'GCA_033212115.1_PDT001757374.1' already exists. Skipping...
Folder 'GCA_033212135.1_PDT001757375.1' already exists. Skipping...
Folder 'GCA_033212155.1_PDT001757372.1' already exists. Skipping...
Folder 'GCA_033212175.1_PDT001757370.1' already exists. Skipping...
Folder 'GCA_033212195.1_PDT001757369.1' already exists. Skipping...
Folder 'GCA_033212215.1_PDT001757368.1' already exists. Skipping...
Folder 'GCA_033212255.1_PDT001757360.1' already exists. Skipping...
Folder 'GCA_033212275.1_PDT001757367.1' already exists. Skipping...
Folder 'GCA_033212295.1_PDT001757359.1' already exists. Skipping...
Folder 'GCA_033212315.1_PDT001757358.1' already exists. Skipping...
Folder 'GCA_033212335.1_PDT001757351.1' already exists. Skipping...
Folder 'GCA_033212355.1_PDT001757352.1' already exists. Skipping...
Folder 'GCA_033212375.1_PDT001757345.1' already exists. Skipping...
Folder 'GCA_033212395.1_PDT001757346.1' already exists. Skipping...
Folder 'GCA_033212415.1_PDT001757344.1' already exists. Skipping...
Folder 'GCA_033212435.1_PDT001757343.1' already exists. Skipping...
Folder 'GCA_033212455.1_PDT001757341.1' already exists. Skipping...
Folder 'GCA_033212495.1_PDT001757339.1' already exists. Skipping...
Folder 'GCA_033212515.1_PDT001757338.1' already exists. Skipping...
Folder 'GCA_033212555.1_PDT001757336.1' already exists. Skipping...
Folder 'GCA_033212595.1_PDT001757335.1' already exists. Skipping...
Folder 'GCA_033212615.1_PDT001757333.1' already exists. Skipping...
Folder 'GCA_033212635.1_PDT001757330.1' already exists. Skipping...
Folder 'GCA_033212655.1_PDT001757331.1' already exists. Skipping...
Folder 'GCA_033212675.1_PDT001757329.1' already exists. Skipping...
Folder 'GCA_033212695.1_PDT001757326.1' already exists. Skipping...
Folder 'GCA_033212715.1_PDT001757320.1' already exists. Skipping...
Folder 'GCA_033212735.1_PDT001757323.1' already exists. Skipping...
Folder 'GCA_033212755.1_PDT001757318.1' already exists. Skipping...
Folder 'GCA_033212775.1_PDT001757316.1' already exists. Skipping...
Folder 'GCA_033212795.1_PDT001757314.1' already exists. Skipping...
Folder 'GCA_033212815.1_PDT001757313.1' already exists. Skipping...
Folder 'GCA_033212835.1_PDT001757312.1' already exists. Skipping...
Folder 'GCA_033212855.1_PDT001757310.1' already exists. Skipping...
Folder 'GCA_033212875.1_PDT001757311.1' already exists. Skipping...
Folder 'GCA_033212895.1_PDT001757308.1' already exists. Skipping...
Folder 'GCA_033212915.1_PDT001757309.1' already exists. Skipping...
Folder 'GCA_033212935.1_PDT001757307.1' already exists. Skipping...
Folder 'GCA_033212955.1_PDT001757306.1' already exists. Skipping...
Folder 'GCA_033212975.1_PDT001757304.1' already exists. Skipping...
Folder 'GCA_033212995.1_PDT001757305.1' already exists. Skipping...
Folder 'GCA_033213015.1_PDT001757303.1' already exists. Skipping...
Folder 'GCA_033213035.1_PDT001757302.1' already exists. Skipping...
Folder 'GCA_033213055.1_PDT001757301.1' already exists. Skipping...
Folder 'GCA_033213075.1_PDT001757299.1' already exists. Skipping...
Folder 'GCA_033213095.1_PDT001757300.1' already exists. Skipping...
Folder 'GCA_033213115.1_PDT001757298.1' already exists. Skipping...
Folder 'GCA_033213135.1_PDT001757297.1' already exists. Skipping...
Folder 'GCA_033213155.1_PDT001757296.1' already exists. Skipping...
Folder 'GCA_033213215.1_PDT001757293.1' already exists. Skipping...
Folder 'GCA_033213235.1_PDT001757295.1' already exists. Skipping...
Folder 'GCA_033213255.1_PDT001757291.1' already exists. Skipping...
Folder 'GCA_033213275.1_PDT001757290.1' already exists. Skipping...
Folder 'GCA_033213295.1_PDT001757288.1' already exists. Skipping...
Folder 'GCA_033213315.1_PDT001757289.1' already exists. Skipping...
Folder 'GCA_033213335.1_PDT001757287.1' already exists. Skipping...
Folder 'GCA_033213375.1_PDT001757285.1' already exists. Skipping...
Folder 'GCA_033213395.1_PDT001757284.1' already exists. Skipping...
Folder 'GCA_033213415.1_PDT001757283.1' already exists. Skipping...
Folder 'GCA_033213435.1_PDT001757282.1' already exists. Skipping...
Folder 'GCA_033213455.1_PDT001757279.1' already exists. Skipping...
Folder 'GCA_033213465.1_PDT001757281.1' already exists. Skipping...
Folder 'GCA_033213495.1_PDT001757280.1' already exists. Skipping...
Folder 'GCA_033213515.1_PDT001757278.1' already exists. Skipping...
Folder 'GCA_033213535.1_PDT001757277.1' already exists. Skipping...
Folder 'GCA_033213555.1_PDT001757275.1' already exists. Skipping...
Folder 'GCA_033213575.1_PDT001757276.1' already exists. Skipping...
Folder 'GCA_033213595.1_PDT001757274.1' already exists. Skipping...
Folder 'GCA_033213615.1_PDT001757273.1' already exists. Skipping...
Folder 'GCA_033213635.1_PDT001757272.1' already exists. Skipping...
Folder 'GCA_033213655.1_PDT001757271.1' already exists. Skipping...
Folder 'GCA_033213675.1_PDT001757268.1' already exists. Skipping...
Folder 'GCA_033213685.1_PDT001757270.1' already exists. Skipping...
Folder 'GCA_033213715.1_PDT001757269.1' already exists. Skipping...
Folder 'GCA_033213735.1_PDT001757267.1' already exists. Skipping...
Folder 'GCA_033213755.1_PDT001757265.1' already exists. Skipping...
Folder 'GCA_033213765.1_PDT001757264.1' already exists. Skipping...
Folder 'GCA_033213795.1_PDT001757266.1' already exists. Skipping...
Folder 'GCA_033213815.1_PDT001757263.1' already exists. Skipping...
Folder 'GCA_033213835.1_PDT001757262.1' already exists. Skipping...
Folder 'GCA_033213855.1_PDT001757261.1' already exists. Skipping...
Folder 'GCA_033213875.1_PDT001757259.1' already exists. Skipping...
Folder 'GCA_033213895.1_PDT001757260.1' already exists. Skipping...
Folder 'GCA_033213915.1_PDT001757257.1' already exists. Skipping...
Folder 'GCA_033213935.1_PDT001757258.1' already exists. Skipping...
Folder 'GCA_033213955.1_PDT001757256.1' already exists. Skipping...
Folder 'GCA_033213975.1_PDT001757255.1' already exists. Skipping...
Folder 'GCA_033213995.1_PDT001757254.1' already exists. Skipping...
Folder 'GCA_033214005.1_PDT001757253.1' already exists. Skipping...
Folder 'GCA_033214035.1_PDT001757252.1' already exists. Skipping...
Folder 'GCA_033214055.1_PDT001757251.1' already exists. Skipping...
Folder 'GCA_033214075.1_PDT001757250.1' already exists. Skipping...
Folder 'GCA_033214095.1_PDT001757248.1' already exists. Skipping...
Folder 'GCA_033214115.1_PDT001757247.1' already exists. Skipping...
Folder 'GCA_033214135.1_PDT001757249.1' already exists. Skipping...
Folder 'GCA_033214155.1_PDT001757246.1' already exists. Skipping...
Folder 'GCA_033214215.1_PDT001757244.1' already exists. Skipping...
Folder 'GCA_033214235.1_PDT001757243.1' already exists. Skipping...
Folder 'GCA_033214255.1_PDT001757241.1' already exists. Skipping...
Folder 'GCA_033214295.1_PDT001757239.1' already exists. Skipping...
Folder 'GCA_033214315.1_PDT001757240.1' already exists. Skipping...
Folder 'GCA_033214335.1_PDT001757238.1' already exists. Skipping...
Folder 'GCA_033214355.1_PDT001757237.1' already exists. Skipping...
Folder 'GCA_033214375.1_PDT001757234.1' already exists. Skipping...
Folder 'GCA_033214395.1_PDT001757236.1' already exists. Skipping...
Folder 'GCA_033214415.1_PDT001757233.1' already exists. Skipping...
Folder 'GCA_033214435.1_PDT001757235.1' already exists. Skipping...
Folder 'GCA_033214455.1_PDT001757231.1' already exists. Skipping...
Folder 'GCA_033214475.1_PDT001757232.1' already exists. Skipping...
Folder 'GCA_033214495.1_PDT001757230.1' already exists. Skipping...
Folder 'GCA_033214515.1_PDT001757229.1' already exists. Skipping...
Folder 'GCA_033214535.1_PDT001757228.1' already exists. Skipping...
Folder 'GCA_033214555.1_PDT001757227.1' already exists. Skipping...
Folder 'GCA_033214575.1_PDT001757226.1' already exists. Skipping...
Folder 'GCA_033214595.1_PDT001757224.1' already exists. Skipping...
Folder 'GCA_033214615.1_PDT001757223.1' already exists. Skipping...
Folder 'GCA_033214635.1_PDT001757225.1' already exists. Skipping...
Folder 'GCA_033214655.1_PDT001757221.1' already exists. Skipping...
Folder 'GCA_033214665.1_PDT001757220.1' already exists. Skipping...
Folder 'GCA_033214675.1_PDT001757222.1' already exists. Skipping...
Folder 'GCA_033214715.1_PDT001757219.1' already exists. Skipping...
Folder 'GCA_033215135.1_PDT001965022.1' already exists. Skipping...
Folder 'GCA_033215205.1_PDT001965019.1' already exists. Skipping...
Folder 'GCA_033215335.1_PDT001965010.1' already exists. Skipping...
Folder 'GCA_033215355.1_PDT001965008.1' already exists. Skipping...
Folder 'GCA_033215595.1_PDT001757217.1' already exists. Skipping...
Folder 'GCA_033215635.1_PDT001757216.1' already exists. Skipping...
Folder 'GCA_033215655.1_PDT001757215.1' already exists. Skipping...
Folder 'GCA_033217435.1_PDT001757111.1' already exists. Skipping...
Folder 'GCA_033217455.1_PDT001757109.1' already exists. Skipping...
Folder 'GCA_033217475.1_PDT001757110.1' already exists. Skipping...
Folder 'GCA_033217495.1_PDT001757107.1' already exists. Skipping...
Folder 'GCA_033217515.1_PDT001757108.1' already exists. Skipping...
Folder 'GCA_033217535.1_PDT001757106.1' already exists. Skipping...
Folder 'GCA_033217555.1_PDT001757105.1' already exists. Skipping...
Folder 'GCA_033217575.1_PDT001757104.1' already exists. Skipping...
Folder 'GCA_033217595.1_PDT001757103.1' already exists. Skipping...
Folder 'GCA_033217615.1_PDT001757101.1' already exists. Skipping...
Folder 'GCA_033217635.1_PDT001757102.1' already exists. Skipping...
Folder 'GCA_033217655.1_PDT001757100.1' already exists. Skipping...
Folder 'GCA_033217675.1_PDT001757097.1' already exists. Skipping...
Folder 'GCA_033217695.1_PDT001757099.1' already exists. Skipping...
Folder 'GCA_033217735.1_PDT001757095.1' already exists. Skipping...
Folder 'GCA_033217775.1_PDT001757094.1' already exists. Skipping...
Folder 'GCA_033217795.1_PDT001757093.1' already exists. Skipping...
Folder 'GCA_033217815.1_PDT001757092.1' already exists. Skipping...
Folder 'GCA_033217835.1_PDT001757091.1' already exists. Skipping...
Folder 'GCA_033217855.1_PDT001757080.1' already exists. Skipping...
Folder 'GCA_033217875.1_PDT001757078.1' already exists. Skipping...
Folder 'GCA_033217915.1_PDT001757088.1' already exists. Skipping...
Folder 'GCA_033217935.1_PDT001757087.1' already exists. Skipping...
Folder 'GCA_033217945.1_PDT001757089.1' already exists. Skipping...
Folder 'GCA_033217975.1_PDT001757086.1' already exists. Skipping...
Folder 'GCA_033217995.1_PDT001757090.1' already exists. Skipping...
Folder 'GCA_033218015.1_PDT001757085.1' already exists. Skipping...
Folder 'GCA_033218035.1_PDT001757084.1' already exists. Skipping...
Folder 'GCA_033218055.1_PDT001757083.1' already exists. Skipping...
Folder 'GCA_033218075.1_PDT001757081.1' already exists. Skipping...
Folder 'GCA_033218095.1_PDT001757077.1' already exists. Skipping...
Folder 'GCA_033218115.1_PDT001757079.1' already exists. Skipping...
Folder 'GCA_033218155.1_PDT001757076.1' already exists. Skipping...
Folder 'GCA_033218175.1_PDT001757075.1' already exists. Skipping...
Folder 'GCA_033218195.1_PDT001757074.1' already exists. Skipping...
Folder 'GCA_033218215.1_PDT001757073.1' already exists. Skipping...
Folder 'GCA_033218235.1_PDT001757072.1' already exists. Skipping...
Folder 'GCA_033218255.1_PDT001757071.1' already exists. Skipping...
Folder 'GCA_033218275.1_PDT001757069.1' already exists. Skipping...
Folder 'GCA_033218295.1_PDT001757070.1' already exists. Skipping...
Folder 'GCA_033218315.1_PDT001757068.1' already exists. Skipping...
Folder 'GCA_033218335.1_PDT001757065.1' already exists. Skipping...
Folder 'GCA_033218355.1_PDT001757067.1' already exists. Skipping...
Folder 'GCA_033218375.1_PDT001757066.1' already exists. Skipping...
Folder 'GCA_033218395.1_PDT001757064.1' already exists. Skipping...
Folder 'GCA_033218415.1_PDT001757063.1' already exists. Skipping...
Folder 'GCA_033218435.1_PDT001757060.1' already exists. Skipping...
Folder 'GCA_033218455.1_PDT001757062.1' already exists. Skipping...
Folder 'GCA_033218495.1_PDT001757059.1' already exists. Skipping...
Folder 'GCA_033218515.1_PDT001757058.1' already exists. Skipping...
Folder 'GCA_033218535.1_PDT001757057.1' already exists. Skipping...
Folder 'GCA_033218555.1_PDT001757056.1' already exists. Skipping...
Folder 'GCA_033218575.1_PDT001757055.1' already exists. Skipping...
Folder 'GCA_033218595.1_PDT001757053.1' already exists. Skipping...
Folder 'GCA_033218615.1_PDT001757054.1' already exists. Skipping...
Folder 'GCA_033218635.1_PDT001757051.1' already exists. Skipping...
Folder 'GCA_033218655.1_PDT001757052.1' already exists. Skipping...
Folder 'GCA_033218675.1_PDT001757050.1' already exists. Skipping...
Folder 'GCA_033218695.1_PDT001757049.1' already exists. Skipping...
Folder 'GCA_033218715.1_PDT001757048.1' already exists. Skipping...
Folder 'GCA_033218735.1_PDT001757046.1' already exists. Skipping...
Folder 'GCA_033218755.1_PDT001780624.1' already exists. Skipping...
Folder 'GCA_033218775.1_PDT001780623.1' already exists. Skipping...
Folder 'GCA_033218795.1_PDT001780622.1' already exists. Skipping...
Folder 'GCA_033218815.1_PDT001780618.1' already exists. Skipping...
Folder 'GCA_033218835.1_PDT001780621.1' already exists. Skipping...
Folder 'GCA_033218855.1_PDT001780620.1' already exists. Skipping...
Folder 'GCA_033218875.1_PDT001780615.1' already exists. Skipping...
Folder 'GCA_033218895.1_PDT001780612.1' already exists. Skipping...
Folder 'GCA_033218915.1_PDT001780614.1' already exists. Skipping...
Folder 'GCA_033218935.1_PDT001780613.1' already exists. Skipping...
Folder 'GCA_033218955.1_PDT001780611.1' already exists. Skipping...
Folder 'GCA_033218975.1_PDT001780608.1' already exists. Skipping...
Folder 'GCA_033218995.1_PDT001780607.1' already exists. Skipping...
Folder 'GCA_033219015.1_PDT001780606.1' already exists. Skipping...
Folder 'GCA_033219035.1_PDT001780604.1' already exists. Skipping...
Folder 'GCA_033219095.1_PDT001757044.1' already exists. Skipping...
Folder 'GCA_033219115.1_PDT001757042.1' already exists. Skipping...
Folder 'GCA_033219135.1_PDT001757043.1' already exists. Skipping...
Folder 'GCA_033219155.1_PDT001757045.1' already exists. Skipping...
Folder 'GCA_033219175.1_PDT001757041.1' already exists. Skipping...
Folder 'GCA_033219195.1_PDT001757040.1' already exists. Skipping...
Folder 'GCA_033219215.1_PDT001757039.1' already exists. Skipping...
Folder 'GCA_033219235.1_PDT001757038.1' already exists. Skipping...
Folder 'GCA_033219255.1_PDT001757037.1' already exists. Skipping...
Folder 'GCA_033219275.1_PDT001757036.1' already exists. Skipping...
Folder 'GCA_033219295.1_PDT001757035.1' already exists. Skipping...
Folder 'GCA_033219315.1_PDT001757033.1' already exists. Skipping...
Folder 'GCA_033219335.1_PDT001757034.1' already exists. Skipping...
Folder 'GCA_033219355.1_PDT001757032.1' already exists. Skipping...
Folder 'GCA_033219375.1_PDT001757031.1' already exists. Skipping...
Folder 'GCA_033219395.1_PDT001757030.1' already exists. Skipping...
Folder 'GCA_033219455.1_PDT001757025.1' already exists. Skipping...
Folder 'GCA_033219475.1_PDT001757027.1' already exists. Skipping...
Folder 'GCA_033219495.1_PDT001757026.1' already exists. Skipping...
Folder 'GCA_033219515.1_PDT001757024.1' already exists. Skipping...
Folder 'GCA_033219535.1_PDT001757023.1' already exists. Skipping...
Folder 'GCA_033219555.1_PDT001757022.1' already exists. Skipping...
Folder 'GCA_033219575.1_PDT001757021.1' already exists. Skipping...
Folder 'GCA_033219595.1_PDT001757020.1' already exists. Skipping...
Folder 'GCA_033219615.1_PDT001757018.1' already exists. Skipping...
Folder 'GCA_033219635.1_PDT001757019.1' already exists. Skipping...
Folder 'GCA_033219655.1_PDT001757017.1' already exists. Skipping...
Folder 'GCA_033219695.1_PDT001757015.1' already exists. Skipping...
Folder 'GCA_033219715.1_PDT001757014.1' already exists. Skipping...
Folder 'GCA_033219755.1_PDT001757012.1' already exists. Skipping...
Folder 'GCA_033219775.1_PDT001757009.1' already exists. Skipping...

Retreiveing data: 100367it [00:16, 6620.38it/s]

Folder 'GCA_033251425.1_PDT001747838.1' already exists. Skipping...
Folder 'GCA_033251465.1_PDT001747830.1' already exists. Skipping...
Folder 'GCA_033251485.1_PDT001747825.1' already exists. Skipping...
Folder 'GCA_033251505.1_PDT001747828.1' already exists. Skipping...
Folder 'GCA_033251525.1_PDT001747815.1' already exists. Skipping...
Folder 'GCA_033251565.1_PDT001747808.1' already exists. Skipping...
Folder 'GCA_033251585.1_PDT001747810.1' already exists. Skipping...
Folder 'GCA_033251605.1_PDT001747805.1' already exists. Skipping...
Folder 'GCA_033251625.1_PDT001747800.1' already exists. Skipping...
Folder 'GCA_033251645.1_PDT001747795.1' already exists. Skipping...
Folder 'GCA_033251665.1_PDT001747790.1' already exists. Skipping...
Folder 'GCA_033251685.1_PDT001747785.1' already exists. Skipping...
Folder 'GCA_033251705.1_PDT001747781.1' already exists. Skipping...
Folder 'GCA_033251725.1_PDT001747783.1' already exists. Skipping...
Folder 'GCA_033251745.1_PDT001747780.1' already exists. Skipping...
Folder 'GCA_033251805.1_PDT001747773.1' already exists. Skipping...
Folder 'GCA_033251825.1_PDT001747771.1' already exists. Skipping...
Folder 'GCA_033251845.1_PDT001747770.1' already exists. Skipping...
Folder 'GCA_033251855.1_PDT001747768.1' already exists. Skipping...
Folder 'GCA_033251885.1_PDT001747765.1' already exists. Skipping...
Folder 'GCA_033251905.1_PDT001747761.1' already exists. Skipping...
Folder 'GCA_033251925.1_PDT001747763.1' already exists. Skipping...
Folder 'GCA_033251945.1_PDT001747760.1' already exists. Skipping...
Folder 'GCA_033251965.1_PDT001747758.1' already exists. Skipping...
Folder 'GCA_033251985.1_PDT001747753.1' already exists. Skipping...
Folder 'GCA_033252005.1_PDT001747751.1' already exists. Skipping...
Folder 'GCA_033252025.1_PDT001747748.1' already exists. Skipping...
Folder 'GCA_033252045.1_PDT001747743.1' already exists. Skipping...
Folder 'GCA_033252065.1_PDT001747738.1' already exists. Skipping...
Folder 'GCA_033252085.1_PDT001747733.1' already exists. Skipping...
Folder 'GCA_033252105.1_PDT001747728.1' already exists. Skipping...
Folder 'GCA_033252125.1_PDT001747726.1' already exists. Skipping...
Folder 'GCA_033252265.1_PDT001747703.1' already exists. Skipping...
Folder 'GCA_033252285.1_PDT001747696.1' already exists. Skipping...
Folder 'GCA_033252305.1_PDT001747698.1' already exists. Skipping...
Folder 'GCA_033252325.1_PDT001747693.1' already exists. Skipping...
Folder 'GCA_033252345.1_PDT001747694.1' already exists. Skipping...
Folder 'GCA_033252385.1_PDT001747684.1' already exists. Skipping...
Folder 'GCA_033252405.1_PDT001747686.1' already exists. Skipping...
Folder 'GCA_033252425.1_PDT001747678.1' already exists. Skipping...
Folder 'GCA_033252445.1_PDT001747683.1' already exists. Skipping...
Folder 'GCA_033252465.1_PDT001747676.1' already exists. Skipping...
Folder 'GCA_033252485.1_PDT001747674.1' already exists. Skipping...
Folder 'GCA_033252505.1_PDT001747673.1' already exists. Skipping...
Folder 'GCA_033252525.1_PDT001747666.1' already exists. Skipping...
Folder 'GCA_033252545.1_PDT001747668.1' already exists. Skipping...
Folder 'GCA_033252565.1_PDT001747663.1' already exists. Skipping...
Folder 'GCA_033252585.1_PDT001747661.1' already exists. Skipping...
Folder 'GCA_033252605.1_PDT001747658.1' already exists. Skipping...
Folder 'GCA_033252625.1_PDT001747653.1' already exists. Skipping...
Folder 'GCA_033252645.1_PDT001747651.1' already exists. Skipping...
Folder 'GCA_033252665.1_PDT001747656.1' already exists. Skipping...
Folder 'GCA_033252685.1_PDT001747648.1' already exists. Skipping...
Folder 'GCA_033252705.1_PDT001747643.1' already exists. Skipping...
Folder 'GCA_033252725.1_PDT001747646.1' already exists. Skipping...
Folder 'GCA_033252745.1_PDT001747641.1' already exists. Skipping...
Folder 'GCA_033252765.1_PDT001747638.1' already exists. Skipping...
Folder 'GCA_033252785.1_PDT001747636.1' already exists. Skipping...
Folder 'GCA_033252805.1_PDT001747631.1' already exists. Skipping...
Folder 'GCA_033252825.1_PDT001747626.1' already exists. Skipping...
Folder 'GCA_033252845.1_PDT001747621.1' already exists. Skipping...
Folder 'GCA_033252865.1_PDT001747619.1' already exists. Skipping...
Folder 'GCA_033252885.1_PDT001747616.1' already exists. Skipping...
Folder 'GCA_033252905.1_PDT001747611.1' already exists. Skipping...
Folder 'GCA_033252925.1_PDT001747609.1' already exists. Skipping...
Folder 'GCA_033252945.1_PDT001747601.1' already exists. Skipping...
Folder 'GCA_033252965.1_PDT001747606.1' already exists. Skipping...
Folder 'GCA_033252985.1_PDT001747599.1' already exists. Skipping...
Folder 'GCA_033253005.1_PDT001747591.1' already exists. Skipping...
Folder 'GCA_033253025.1_PDT001747596.1' already exists. Skipping...
Folder 'GCA_033253065.1_PDT001747571.1' already exists. Skipping...
Folder 'GCA_033253085.1_PDT001747589.1' already exists. Skipping...
Folder 'GCA_033253105.1_PDT001747581.1' already exists. Skipping...
Folder 'GCA_033253125.1_PDT001747586.1' already exists. Skipping...
Folder 'GCA_033253145.1_PDT001747576.1' already exists. Skipping...
Folder 'GCA_033253165.1_PDT001747561.1' already exists. Skipping...
Folder 'GCA_033253175.1_PDT001747566.1' already exists. Skipping...
Folder 'GCA_033253205.1_PDT001747557.1' already exists. Skipping...
Folder 'GCA_033253225.1_PDT001747556.1' already exists. Skipping...
Folder 'GCA_033253245.1_PDT001747551.1' already exists. Skipping...
Folder 'GCA_033253265.1_PDT001747546.1' already exists. Skipping...
Folder 'GCA_033253285.1_PDT001747547.1' already exists. Skipping...
Folder 'GCA_033253305.1_PDT001747542.1' already exists. Skipping...
Folder 'GCA_033253325.1_PDT001747544.1' already exists. Skipping...
Folder 'GCA_033253345.1_PDT001747541.1' already exists. Skipping...
Folder 'GCA_033253365.1_PDT001747539.1' already exists. Skipping...
Folder 'GCA_033253405.1_PDT001747534.1' already exists. Skipping...
Folder 'GCA_033253425.1_PDT001747531.1' already exists. Skipping...
Folder 'GCA_033253445.1_PDT001747532.1' already exists. Skipping...
Folder 'GCA_033253465.1_PDT001747529.1' already exists. Skipping...
Folder 'GCA_033253485.1_PDT001747522.1' already exists. Skipping...
Folder 'GCA_033253505.1_PDT001747524.1' already exists. Skipping...
Folder 'GCA_033253525.1_PDT001747521.1' already exists. Skipping...
Folder 'GCA_033253545.1_PDT001747519.1' already exists. Skipping...
Folder 'GCA_033253565.1_PDT001747514.1' already exists. Skipping...
Folder 'GCA_033253585.1_PDT001747516.1' already exists. Skipping...
Folder 'GCA_033253605.1_PDT001747512.1' already exists. Skipping...
Folder 'GCA_033253645.1_PDT001747497.1' already exists. Skipping...
Folder 'GCA_033253715.1_PDT001747492.1' already exists. Skipping...
Folder 'GCA_033253765.1_PDT001747484.1' already exists. Skipping...
Folder 'GCA_033253785.1_PDT001747489.1' already exists. Skipping...
Folder 'GCA_033253805.1_PDT001747482.1' already exists. Skipping...
Folder 'GCA_033253845.1_PDT001747474.1' already exists. Skipping...
Folder 'GCA_033253865.1_PDT001747472.1' already exists. Skipping...
Folder 'GCA_033253885.1_PDT001747469.1' already exists. Skipping...
Folder 'GCA_033253905.1_PDT001747467.1' already exists. Skipping...
Folder 'GCA_033253925.1_PDT001747459.1' already exists. Skipping...
Folder 'GCA_033253945.1_PDT001747464.1' already exists. Skipping...
Folder 'GCA_033254005.1_PDT001747450.1' already exists. Skipping...
Folder 'GCA_033254025.1_PDT001747449.1' already exists. Skipping...
Folder 'GCA_033254045.1_PDT001747447.1' already exists. Skipping...
Folder 'GCA_033254065.1_PDT001747445.1' already exists. Skipping...
Folder 'GCA_033254085.1_PDT001747444.1' already exists. Skipping...
Folder 'GCA_033254105.1_PDT001747442.1' already exists. Skipping...
Folder 'GCA_033254125.1_PDT001747439.1' already exists. Skipping...
Folder 'GCA_033254145.1_PDT001747437.1' already exists. Skipping...
Folder 'GCA_033254165.1_PDT001747440.1' already exists. Skipping...
Folder 'GCA_033254185.1_PDT001747435.1' already exists. Skipping...
Folder 'GCA_033254205.1_PDT001747434.1' already exists. Skipping...
Folder 'GCA_033254225.1_PDT001747432.1' already exists. Skipping...
Folder 'GCA_033254245.1_PDT001747430.1' already exists. Skipping...
Folder 'GCA_033254265.1_PDT001747429.1' already exists. Skipping...
Folder 'GCA_033254285.1_PDT001747425.1' already exists. Skipping...
Folder 'GCA_033254305.1_PDT001747424.1' already exists. Skipping...
Folder 'GCA_033254325.1_PDT001747419.1' already exists. Skipping...
Folder 'GCA_033254345.1_PDT001747417.1' already exists. Skipping...
Folder 'GCA_033254365.1_PDT001747420.1' already exists. Skipping...
Folder 'GCA_033254385.1_PDT001747414.1' already exists. Skipping...
Folder 'GCA_033254405.1_PDT001747415.1' already exists. Skipping...
Folder 'GCA_033254425.1_PDT001747412.1' already exists. Skipping...
Folder 'GCA_033254445.1_PDT001747407.1' already exists. Skipping...
Folder 'GCA_033254465.1_PDT001747409.1' already exists. Skipping...
Folder 'GCA_033254485.1_PDT001747404.1' already exists. Skipping...
Folder 'GCA_033254505.1_PDT001747402.1' already exists. Skipping...
Folder 'GCA_033254525.1_PDT001747400.1' already exists. Skipping...
Folder 'GCA_033254565.1_PDT001747387.1' already exists. Skipping...
Folder 'GCA_033254585.1_PDT001747399.1' already exists. Skipping...
Folder 'GCA_033254605.1_PDT001747392.1' already exists. Skipping...
Folder 'GCA_033254625.1_PDT001747394.1' already exists. Skipping...
Folder 'GCA_033254645.1_PDT001747397.1' already exists. Skipping...
Folder 'GCA_033254665.1_PDT001747390.1' already exists. Skipping...
Folder 'GCA_033254685.1_PDT001747382.1' already exists. Skipping...
Folder 'GCA_033254705.1_PDT001747380.1' already exists. Skipping...
Folder 'GCA_033254725.1_PDT001747372.1' already exists. Skipping...
Folder 'GCA_033254765.1_PDT001747370.1' already exists. Skipping...
Folder 'GCA_033254785.1_PDT001747367.1' already exists. Skipping...
Folder 'GCA_033254805.1_PDT001747365.1' already exists. Skipping...
Folder 'GCA_033254825.1_PDT001747360.1' already exists. Skipping...
Folder 'GCA_033254845.1_PDT001747362.1' already exists. Skipping...
Folder 'GCA_033254865.1_PDT001747357.1' already exists. Skipping...
Folder 'GCA_033254885.1_PDT001747350.1' already exists. Skipping...
Folder 'GCA_033254905.1_PDT001747352.1' already exists. Skipping...
Folder 'GCA_033254925.1_PDT001747345.1' already exists. Skipping...
Folder 'GCA_033254965.1_PDT001747342.1' already exists. Skipping...
Folder 'GCA_033254985.1_PDT001747335.1' already exists. Skipping...
Folder 'GCA_033255005.1_PDT001747337.1' already exists. Skipping...
Folder 'GCA_033255025.1_PDT001747332.1' already exists. Skipping...
Folder 'GCA_033255045.1_PDT001747330.1' already exists. Skipping...
Folder 'GCA_033255065.1_PDT001747328.1' already exists. Skipping...
Folder 'GCA_033255085.1_PDT001747323.1' already exists. Skipping...
Folder 'GCA_033255105.1_PDT001747327.1' already exists. Skipping...
Folder 'GCA_033255125.1_PDT001747325.1' already exists. Skipping...
Folder 'GCA_033255145.1_PDT001747322.1' already exists. Skipping...
Folder 'GCA_033255165.1_PDT001747320.1' already exists. Skipping...
Folder 'GCA_033255345.1_PDT001747317.1' already exists. Skipping...
Folder 'GCA_033255365.1_PDT001747313.1' already exists. Skipping...
Folder 'GCA_033255405.1_PDT001747312.1' already exists. Skipping...
Folder 'GCA_033255425.1_PDT001747310.1' already exists. Skipping...
Folder 'GCA_033255465.1_PDT001747307.1' already exists. Skipping...
Folder 'GCA_033255505.1_PDT001747308.1' already exists. Skipping...
Folder 'GCA_033255545.1_PDT001747302.1' already exists. Skipping...
Folder 'GCA_033255565.1_PDT001747298.1' already exists. Skipping...
Folder 'GCA_033255585.1_PDT001747300.1' already exists. Skipping...
Folder 'GCA_033255605.1_PDT001747292.1' already exists. Skipping...
Folder 'GCA_033255625.1_PDT001747293.1' already exists. Skipping...
Folder 'GCA_033255645.1_PDT001747297.1' already exists. Skipping...
Folder 'GCA_033255665.1_PDT001747290.1' already exists. Skipping...
Folder 'GCA_033255685.1_PDT001747288.1' already exists. Skipping...
Folder 'GCA_033255705.1_PDT001747285.1' already exists. Skipping...
Folder 'GCA_033255725.1_PDT001747287.1' already exists. Skipping...
Folder 'GCA_033255745.1_PDT001747283.1' already exists. Skipping...
Folder 'GCA_033255765.1_PDT001747282.1' already exists. Skipping...
Folder 'GCA_033255785.1_PDT001747280.1' already exists. Skipping...
Folder 'GCA_033255805.1_PDT001747277.1' already exists. Skipping...
Folder 'GCA_033255825.1_PDT001747278.1' already exists. Skipping...
Folder 'GCA_033255845.1_PDT001747273.1' already exists. Skipping...
Folder 'GCA_033255885.1_PDT001747272.1' already exists. Skipping...
Folder 'GCA_033255905.1_PDT001747270.1' already exists. Skipping...
Folder 'GCA_033255925.1_PDT001747268.1' already exists. Skipping...
Folder 'GCA_033255945.1_PDT001747265.1' already exists. Skipping...
Folder 'GCA_033255965.1_PDT001747263.1' already exists. Skipping...
Folder 'GCA_033255985.1_PDT001747255.1' already exists. Skipping...
Folder 'GCA_033256005.1_PDT001747253.1' already exists. Skipping...
Folder 'GCA_033256025.1_PDT001747250.1' already exists. Skipping...
Folder 'GCA_033256045.1_PDT001747248.1' already exists. Skipping...
Folder 'GCA_033256065.1_PDT001747243.1' already exists. Skipping...
Folder 'GCA_033256085.1_PDT001747245.1' already exists. Skipping...
Folder 'GCA_033256145.1_PDT001747240.1' already exists. Skipping...
Folder 'GCA_033256185.1_PDT001747235.1' already exists. Skipping...
Folder 'GCA_033256225.1_PDT001747233.1' already exists. Skipping...
Folder 'GCA_033256235.1_PDT001747230.1' already exists. Skipping...
Folder 'GCA_033256265.1_PDT001747223.1' already exists. Skipping...
Folder 'GCA_033256305.1_PDT001747225.1' already exists. Skipping...
Folder 'GCA_033256325.1_PDT001747220.1' already exists. Skipping...
Folder 'GCA_033256345.1_PDT001747218.1' already exists. Skipping...
Folder 'GCA_033256365.1_PDT001747215.1' already exists. Skipping...
Folder 'GCA_033256385.1_PDT001747213.1' already exists. Skipping...
Folder 'GCA_033256425.1_PDT001747208.1' already exists. Skipping...
Folder 'GCA_033256445.1_PDT001747205.1' already exists. Skipping...
Folder 'GCA_033256465.1_PDT001747206.1' already exists. Skipping...
Folder 'GCA_033256485.1_PDT001747201.1' already exists. Skipping...
Folder 'GCA_033256505.1_PDT001747200.1' already exists. Skipping...
Folder 'GCA_033256525.1_PDT001747203.1' already exists. Skipping...
Folder 'GCA_033256545.1_PDT001747198.1' already exists. Skipping...
Folder 'GCA_033256565.1_PDT001747195.1' already exists. Skipping...
Folder 'GCA_033256585.1_PDT001747193.1' already exists. Skipping...
Folder 'GCA_033256605.1_PDT001747196.1' already exists. Skipping...
Folder 'GCA_033256625.1_PDT001747191.1' already exists. Skipping...
Folder 'GCA_033256665.1_PDT001747186.1' already exists. Skipping...
Folder 'GCA_033256725.1_PDT001747180.1' already exists. Skipping...
Folder 'GCA_033256765.1_PDT001747178.1' already exists. Skipping...
Folder 'GCA_033256805.1_PDT001747175.1' already exists. Skipping...
Folder 'GCA_033256845.1_PDT001747171.1' already exists. Skipping...
Folder 'GCA_033256865.1_PDT001747170.1' already exists. Skipping...
Folder 'GCA_033256885.1_PDT001747168.1' already exists. Skipping...
Folder 'GCA_033256905.1_PDT001747166.1' already exists. Skipping...
Folder 'GCA_033256925.1_PDT001747165.1' already exists. Skipping...
Folder 'GCA_033256945.1_PDT001747163.1' already exists. Skipping...
Folder 'GCA_033256965.1_PDT001747160.1' already exists. Skipping...
Folder 'GCA_033256985.1_PDT001747158.1' already exists. Skipping...
Folder 'GCA_033257005.1_PDT001747156.1' already exists. Skipping...
Folder 'GCA_033257025.1_PDT001747155.1' already exists. Skipping...
Folder 'GCA_033257045.1_PDT001747153.1' already exists. Skipping...
Folder 'GCA_033257065.1_PDT001747143.1' already exists. Skipping...
Folder 'GCA_033257085.1_PDT001747146.1' already exists. Skipping...
Folder 'GCA_033257125.1_PDT001747151.1' already exists. Skipping...
Folder 'GCA_033257145.1_PDT001747148.1' already exists. Skipping...
Folder 'GCA_033257185.1_PDT001747138.1' already exists. Skipping...
Folder 'GCA_033257205.1_PDT001747141.1' already exists. Skipping...
Folder 'GCA_033257225.1_PDT001747136.1' already exists. Skipping...
Folder 'GCA_033257245.1_PDT001747131.1' already exists. Skipping...
Folder 'GCA_033257265.1_PDT001747133.1' already exists. Skipping...
Folder 'GCA_033257285.1_PDT001747126.1' already exists. Skipping...
Folder 'GCA_033257305.1_PDT001747128.1' already exists. Skipping...
Folder 'GCA_033257325.1_PDT001747118.1' already exists. Skipping...
Folder 'GCA_033257345.1_PDT001747113.1' already exists. Skipping...
Folder 'GCA_033257365.1_PDT001747123.1' already exists. Skipping...
Folder 'GCA_033257385.1_PDT001747108.1' already exists. Skipping...
Folder 'GCA_033257405.1_PDT001747111.1' already exists. Skipping...
Folder 'GCA_033257425.1_PDT001747103.1' already exists. Skipping...
Folder 'GCA_033257445.1_PDT001747098.1' already exists. Skipping...
Folder 'GCA_033257465.1_PDT001747101.1' already exists. Skipping...
Folder 'GCA_033257485.1_PDT001747093.1' already exists. Skipping...
Folder 'GCA_033257505.1_PDT001747091.1' already exists. Skipping...
Folder 'GCA_033257525.1_PDT001747088.1' already exists. Skipping...
Folder 'GCA_033257545.1_PDT001747084.1' already exists. Skipping...
Folder 'GCA_033257565.1_PDT001747086.1' already exists. Skipping...
Folder 'GCA_033257585.1_PDT001747083.1' already exists. Skipping...
Folder 'GCA_033257605.1_PDT001747081.1' already exists. Skipping...
Folder 'GCA_033257625.1_PDT001747079.1' already exists. Skipping...
Folder 'GCA_033257645.1_PDT001747076.1' already exists. Skipping...
Folder 'GCA_033257685.1_PDT001747074.1' already exists. Skipping...
Folder 'GCA_033257725.1_PDT001747071.1' already exists. Skipping...
Folder 'GCA_033257745.1_PDT001747069.1' already exists. Skipping...
Folder 'GCA_033257765.1_PDT001747068.1' already exists. Skipping...
Folder 'GCA_033257785.1_PDT001747066.1' already exists. Skipping...
Folder 'GCA_033257805.1_PDT001747063.1' already exists. Skipping...
Folder 'GCA_033257815.1_PDT001747064.1' already exists. Skipping...
Folder 'GCA_033257845.1_PDT001747059.1' already exists. Skipping...
Folder 'GCA_033257865.1_PDT001747061.1' already exists. Skipping...
Folder 'GCA_033257885.1_PDT001747058.1' already exists. Skipping...
Folder 'GCA_033257905.1_PDT001747054.1' already exists. Skipping...
Folder 'GCA_033257925.1_PDT001747056.1' already exists. Skipping...
Folder 'GCA_033257945.1_PDT001747053.1' already exists. Skipping...
Folder 'GCA_033257965.1_PDT001747046.1' already exists. Skipping...
Folder 'GCA_033258005.1_PDT001747051.1' already exists. Skipping...
Folder 'GCA_033258025.1_PDT001747048.1' already exists. Skipping...
Folder 'GCA_033258045.1_PDT001747049.1' already exists. Skipping...
Folder 'GCA_033258085.1_PDT001747043.1' already exists. Skipping...
Folder 'GCA_033258105.1_PDT001747039.1' already exists. Skipping...
Folder 'GCA_033258825.1_PDT001965273.1' already exists. Skipping...
Folder 'GCA_033259385.1_PDT001747038.1' already exists. Skipping...
Folder 'GCA_033259425.1_PDT001747036.1' already exists. Skipping...
Folder 'GCA_033259445.1_PDT001747034.1' already exists. Skipping...
Folder 'GCA_033259485.1_PDT001747033.1' already exists. Skipping...
Folder 'GCA_033259505.1_PDT001747031.1' already exists. Skipping...
Folder 'GCA_033259525.1_PDT001747028.1' already exists. Skipping...
Folder 'GCA_033259545.1_PDT001747026.1' already exists. Skipping...
Folder 'GCA_033259585.1_PDT001747021.1' already exists. Skipping...
Folder 'GCA_033259625.1_PDT001747011.1' already exists. Skipping...
Folder 'GCA_033259645.1_PDT001747014.1' already exists. Skipping...
Folder 'GCA_033259665.1_PDT001747009.1' already exists. Skipping...
Folder 'GCA_033259685.1_PDT001747006.1' already exists. Skipping...
Folder 'GCA_033259705.1_PDT001747004.1' already exists. Skipping...

Retreiveing data: 101694it [00:16, 6597.29it/s]

Folder 'GCA_033296105.1_PDT001743624.1' already exists. Skipping...
Folder 'GCA_033296125.1_PDT001743625.1' already exists. Skipping...
Folder 'GCA_033296145.1_PDT001743622.1' already exists. Skipping...
Folder 'GCA_033296165.1_PDT001743623.1' already exists. Skipping...
Folder 'GCA_033296185.1_PDT001743621.1' already exists. Skipping...
Folder 'GCA_033296205.1_PDT001743620.1' already exists. Skipping...
Folder 'GCA_033296225.1_PDT001743619.1' already exists. Skipping...
Folder 'GCA_033296245.1_PDT001743617.1' already exists. Skipping...
Folder 'GCA_033296265.1_PDT001743618.1' already exists. Skipping...
Folder 'GCA_033296285.1_PDT001743616.1' already exists. Skipping...
Folder 'GCA_033296305.1_PDT001743615.1' already exists. Skipping...
Folder 'GCA_033296325.1_PDT001743614.1' already exists. Skipping...
Folder 'GCA_033296345.1_PDT001743613.1' already exists. Skipping...
Folder 'GCA_033296365.1_PDT001743611.1' already exists. Skipping...
Folder 'GCA_033296385.1_PDT001743612.1' already exists. Skipping...
Folder 'GCA_033296405.1_PDT001743610.1' already exists. Skipping...
Folder 'GCA_033296425.1_PDT001743609.1' already exists. Skipping...
Folder 'GCA_033296445.1_PDT001743607.1' already exists. Skipping...
Folder 'GCA_033296465.1_PDT001743608.1' already exists. Skipping...
Folder 'GCA_033296485.1_PDT001743606.1' already exists. Skipping...
Folder 'GCA_033296525.1_PDT001743605.1' already exists. Skipping...
Folder 'GCA_033296555.1_PDT001743604.1' already exists. Skipping...
Folder 'GCA_033296575.1_PDT001743603.1' already exists. Skipping...
Folder 'GCA_033296595.1_PDT001743601.1' already exists. Skipping...
Folder 'GCA_033296615.1_PDT001743602.1' already exists. Skipping...
Folder 'GCA_033296645.1_PDT001743600.1' already exists. Skipping...
Folder 'GCA_033296655.1_PDT001743599.1' already exists. Skipping...
Folder 'GCA_033296735.1_PDT001743598.1' already exists. Skipping...
Folder 'GCA_033296785.1_PDT001743597.1' already exists. Skipping...
Folder 'GCA_033296795.1_PDT001743596.1' already exists. Skipping...
Folder 'GCA_033296835.1_PDT001743594.1' already exists. Skipping...
Folder 'GCA_033296855.1_PDT001743595.1' already exists. Skipping...
Folder 'GCA_033296925.1_PDT001743592.1' already exists. Skipping...
Folder 'GCA_033296945.1_PDT001743591.1' already exists. Skipping...
Folder 'GCA_033296965.1_PDT001743593.1' already exists. Skipping...
Folder 'GCA_033296995.1_PDT001743589.1' already exists. Skipping...
Folder 'GCA_033297055.1_PDT001743590.1' already exists. Skipping...
Folder 'GCA_033297085.1_PDT001743587.1' already exists. Skipping...
Folder 'GCA_033297105.1_PDT001743588.1' already exists. Skipping...
Folder 'GCA_033297135.1_PDT001743586.1' already exists. Skipping...
Folder 'GCA_033297155.1_PDT001743585.1' already exists. Skipping...
Folder 'GCA_033297185.1_PDT001743584.1' already exists. Skipping...
Folder 'GCA_033297285.1_PDT001743583.1' already exists. Skipping...
Folder 'GCA_033297295.1_PDT001743582.1' already exists. Skipping...
Folder 'GCA_033297335.1_PDT001743581.1' already exists. Skipping...
Folder 'GCA_033297355.1_PDT001743580.1' already exists. Skipping...
Folder 'GCA_033297375.1_PDT001743579.1' already exists. Skipping...
Folder 'GCA_033297415.1_PDT001743578.1' already exists. Skipping...
Folder 'GCA_033297435.1_PDT001743577.1' already exists. Skipping...
Folder 'GCA_033297475.1_PDT001743576.1' already exists. Skipping...
Folder 'GCA_033297495.1_PDT001743575.1' already exists. Skipping...
Folder 'GCA_033297515.1_PDT001743574.1' already exists. Skipping...
Folder 'GCA_033297575.1_PDT001743573.1' already exists. Skipping...
Folder 'GCA_033297595.1_PDT001743570.1' already exists. Skipping...
Folder 'GCA_033297615.1_PDT001743571.1' already exists. Skipping...
Folder 'GCA_033297635.1_PDT001743569.1' already exists. Skipping...
Folder 'GCA_033297655.1_PDT001743568.1' already exists. Skipping...
Folder 'GCA_033297675.1_PDT001743567.1' already exists. Skipping...
Folder 'GCA_033297695.1_PDT001743565.1' already exists. Skipping...
Folder 'GCA_033297715.1_PDT001743564.1' already exists. Skipping...
Folder 'GCA_033297735.1_PDT001743562.1' already exists. Skipping...
Folder 'GCA_033297755.1_PDT001743563.1' already exists. Skipping...
Folder 'GCA_033297775.1_PDT001743561.1' already exists. Skipping...
Folder 'GCA_033297795.1_PDT001743560.1' already exists. Skipping...
Folder 'GCA_033297815.1_PDT001743559.1' already exists. Skipping...
Folder 'GCA_033297835.1_PDT001743557.1' already exists. Skipping...
Folder 'GCA_033297855.1_PDT001743556.1' already exists. Skipping...
Folder 'GCA_033297875.1_PDT001743558.1' already exists. Skipping...
Folder 'GCA_033297895.1_PDT001743555.1' already exists. Skipping...
Folder 'GCA_033297915.1_PDT001743572.1' already exists. Skipping...
Folder 'GCA_033297935.1_PDT001743552.1' already exists. Skipping...
Folder 'GCA_033297955.1_PDT001743554.1' already exists. Skipping...
Folder 'GCA_033297975.1_PDT001743553.1' already exists. Skipping...
Folder 'GCA_033297995.1_PDT001743551.1' already exists. Skipping...
Folder 'GCA_033298015.1_PDT001743550.1' already exists. Skipping...
Folder 'GCA_033298035.1_PDT001743549.1' already exists. Skipping...
Folder 'GCA_033298055.1_PDT001743548.1' already exists. Skipping...
Folder 'GCA_033298075.1_PDT001743547.1' already exists. Skipping...
Folder 'GCA_033298095.1_PDT001743545.1' already exists. Skipping...
Folder 'GCA_033298115.1_PDT001743546.1' already exists. Skipping...
Folder 'GCA_033298135.1_PDT001743543.1' already exists. Skipping...
Folder 'GCA_033298155.1_PDT001743542.1' already exists. Skipping...
Folder 'GCA_033298175.1_PDT001743544.1' already exists. Skipping...
Folder 'GCA_033298195.1_PDT001743541.1' already exists. Skipping...
Folder 'GCA_033298215.1_PDT001743540.1' already exists. Skipping...
Folder 'GCA_033298235.1_PDT001743539.1' already exists. Skipping...
Folder 'GCA_033298255.1_PDT001743538.1' already exists. Skipping...
Folder 'GCA_033298275.1_PDT001743537.1' already exists. Skipping...
Folder 'GCA_033298295.1_PDT001743534.1' already exists. Skipping...
Folder 'GCA_033298315.1_PDT001743536.1' already exists. Skipping...
Folder 'GCA_033298335.1_PDT001743535.1' already exists. Skipping...
Folder 'GCA_033298355.1_PDT001743533.1' already exists. Skipping...
Folder 'GCA_033298375.1_PDT001743532.1' already exists. Skipping...
Folder 'GCA_033298395.1_PDT001743531.1' already exists. Skipping...
Folder 'GCA_033298415.1_PDT001743530.1' already exists. Skipping...
Folder 'GCA_033298435.1_PDT001743528.1' already exists. Skipping...
Folder 'GCA_033298455.1_PDT001743526.1' already exists. Skipping...
Folder 'GCA_033298475.1_PDT001743527.1' already exists. Skipping...
Folder 'GCA_033298495.1_PDT001743524.1' already exists. Skipping...
Folder 'GCA_033298515.1_PDT001743523.1' already exists. Skipping...
Folder 'GCA_033298535.1_PDT001743525.1' already exists. Skipping...
Folder 'GCA_033298555.1_PDT001743519.1' already exists. Skipping...
Folder 'GCA_033298575.1_PDT001743522.1' already exists. Skipping...
Folder 'GCA_033298595.1_PDT001743521.1' already exists. Skipping...
Folder 'GCA_033298615.1_PDT001743518.1' already exists. Skipping...
Folder 'GCA_033298635.1_PDT001743517.1' already exists. Skipping...
Folder 'GCA_033298655.1_PDT001743520.1' already exists. Skipping...
Folder 'GCA_033298675.1_PDT001743516.1' already exists. Skipping...
Folder 'GCA_033298695.1_PDT001743515.1' already exists. Skipping...
Folder 'GCA_033298715.1_PDT001743513.1' already exists. Skipping...
Folder 'GCA_033298735.1_PDT001743514.1' already exists. Skipping...
Folder 'GCA_033298755.1_PDT001743512.1' already exists. Skipping...
Folder 'GCA_033298775.1_PDT001743511.1' already exists. Skipping...
Folder 'GCA_033298795.1_PDT001743510.1' already exists. Skipping...
Folder 'GCA_033298815.1_PDT001743509.1' already exists. Skipping...
Folder 'GCA_033298835.1_PDT001743508.1' already exists. Skipping...
Folder 'GCA_033298855.1_PDT001743507.1' already exists. Skipping...
Folder 'GCA_033298875.1_PDT001743506.1' already exists. Skipping...
Folder 'GCA_033298895.1_PDT001743505.1' already exists. Skipping...
Folder 'GCA_033298915.1_PDT001743503.1' already exists. Skipping...
Folder 'GCA_033298935.1_PDT001743504.1' already exists. Skipping...
Folder 'GCA_033298955.1_PDT001743502.1' already exists. Skipping...
Folder 'GCA_033298975.1_PDT001743501.1' already exists. Skipping...
Folder 'GCA_033298995.1_PDT001743498.1' already exists. Skipping...
Folder 'GCA_033299015.1_PDT001743499.1' already exists. Skipping...
Folder 'GCA_033299035.1_PDT001743497.1' already exists. Skipping...
Folder 'GCA_033299055.1_PDT001743500.1' already exists. Skipping...
Folder 'GCA_033299075.1_PDT001743496.1' already exists. Skipping...
Folder 'GCA_033299095.1_PDT001743493.1' already exists. Skipping...
Folder 'GCA_033299115.1_PDT001743495.1' already exists. Skipping...
Folder 'GCA_033299135.1_PDT001743494.1' already exists. Skipping...
Folder 'GCA_033299155.1_PDT001743491.1' already exists. Skipping...
Folder 'GCA_033299175.1_PDT001743492.1' already exists. Skipping...
Folder 'GCA_033299195.1_PDT001743489.1' already exists. Skipping...
Folder 'GCA_033299215.1_PDT001743490.1' already exists. Skipping...
Folder 'GCA_033299235.1_PDT001743487.1' already exists. Skipping...
Folder 'GCA_033299245.1_PDT001743488.1' already exists. Skipping...
Folder 'GCA_033299275.1_PDT001743486.1' already exists. Skipping...
Folder 'GCA_033299295.1_PDT001743484.1' already exists. Skipping...
Folder 'GCA_033299315.1_PDT001743481.1' already exists. Skipping...
Folder 'GCA_033299335.1_PDT001743482.1' already exists. Skipping...
Folder 'GCA_033299355.1_PDT001743485.1' already exists. Skipping...
Folder 'GCA_033299365.1_PDT001743483.1' already exists. Skipping...
Folder 'GCA_033299395.1_PDT001743480.1' already exists. Skipping...
Folder 'GCA_033299415.1_PDT001743479.1' already exists. Skipping...
Folder 'GCA_033299435.1_PDT001743478.1' already exists. Skipping...
Folder 'GCA_033299455.1_PDT001743477.1' already exists. Skipping...
Folder 'GCA_033299475.1_PDT001743475.1' already exists. Skipping...
Folder 'GCA_033299495.1_PDT001743476.1' already exists. Skipping...
Folder 'GCA_033299515.1_PDT001743474.1' already exists. Skipping...
Folder 'GCA_033299535.1_PDT001743472.1' already exists. Skipping...
Folder 'GCA_033299555.1_PDT001743473.1' already exists. Skipping...
Folder 'GCA_033299575.1_PDT001743469.1' already exists. Skipping...
Folder 'GCA_033299595.1_PDT001743471.1' already exists. Skipping...
Folder 'GCA_033299615.1_PDT001743470.1' already exists. Skipping...
Folder 'GCA_033299635.1_PDT001743468.1' already exists. Skipping...
Folder 'GCA_033299655.1_PDT001743467.1' already exists. Skipping...
Folder 'GCA_033299675.1_PDT001743465.1' already exists. Skipping...
Folder 'GCA_033299695.1_PDT001743466.1' already exists. Skipping...
Folder 'GCA_033299715.1_PDT001743464.1' already exists. Skipping...
Folder 'GCA_033299735.1_PDT001743463.1' already exists. Skipping...
Folder 'GCA_033299755.1_PDT001743462.1' already exists. Skipping...
Folder 'GCA_033299775.1_PDT001743461.1' already exists. Skipping...
Folder 'GCA_033299795.1_PDT001743460.1' already exists. Skipping...
Folder 'GCA_033299815.1_PDT001743459.1' already exists. Skipping...
Folder 'GCA_033299835.1_PDT001743458.1' already exists. Skipping...
Folder 'GCA_033299855.1_PDT001743457.1' already exists. Skipping...
Folder 'GCA_033299875.1_PDT001743456.1' already exists. Skipping...
Folder 'GCA_033299895.1_PDT001743455.1' already exists. Skipping...
Folder 'GCA_033299915.1_PDT001743454.1' already exists. Skipping...
Folder 'GCA_033299935.1_PDT001743453.1' already exists. Skipping...
Folder 'GCA_033299955.1_PDT001743452.1' already exists. Skipping...
Folder 'GCA_033299975.1_PDT001743451.1' already exists. Skipping...
Folder 'GCA_033299995.1_PDT001743449.1' already exists. Skipping...
Folder 'GCA_033300015.1_PDT001743450.1' already exists. Skipping...
Folder 'GCA_033300035.1_PDT001743448.1' already exists. Skipping...
Folder 'GCA_033300055.1_PDT001743447.1' already exists. Skipping...
Folder 'GCA_033300075.1_PDT001743446.1' already exists. Skipping...
Folder 'GCA_033300095.1_PDT001743445.1' already exists. Skipping...
Folder 'GCA_033300115.1_PDT001743444.1' already exists. Skipping...
Folder 'GCA_033300135.1_PDT001743443.1' already exists. Skipping...
Folder 'GCA_033300155.1_PDT001743439.1' already exists. Skipping...
Folder 'GCA_033300175.1_PDT001743441.1' already exists. Skipping...
Folder 'GCA_033300195.1_PDT001743438.1' already exists. Skipping...
Folder 'GCA_033300215.1_PDT001743440.1' already exists. Skipping...
Folder 'GCA_033300235.1_PDT001743442.1' already exists. Skipping...
Folder 'GCA_033300255.1_PDT001743437.1' already exists. Skipping...
Folder 'GCA_033300265.1_PDT001743435.1' already exists. Skipping...
Folder 'GCA_033300295.1_PDT001743436.1' already exists. Skipping...
Folder 'GCA_033300315.1_PDT001743434.1' already exists. Skipping...
Folder 'GCA_033300335.1_PDT001743433.1' already exists. Skipping...
Folder 'GCA_033300355.1_PDT001743432.1' already exists. Skipping...
Folder 'GCA_033300375.1_PDT001743431.1' already exists. Skipping...
Folder 'GCA_033300395.1_PDT001743430.1' already exists. Skipping...
Folder 'GCA_033300415.1_PDT001743429.1' already exists. Skipping...
Folder 'GCA_033300435.1_PDT001743428.1' already exists. Skipping...
Folder 'GCA_033300455.1_PDT001743427.1' already exists. Skipping...
Folder 'GCA_033300475.1_PDT001743426.1' already exists. Skipping...
Folder 'GCA_033300495.1_PDT001743425.1' already exists. Skipping...
Folder 'GCA_033300515.1_PDT001743424.1' already exists. Skipping...
Folder 'GCA_033300535.1_PDT001743423.1' already exists. Skipping...
Folder 'GCA_033300555.1_PDT001743422.1' already exists. Skipping...
Folder 'GCA_033300575.1_PDT001743420.1' already exists. Skipping...
Folder 'GCA_033300595.1_PDT001743421.1' already exists. Skipping...
Folder 'GCA_033300615.1_PDT001743419.1' already exists. Skipping...
Folder 'GCA_033300635.1_PDT001743418.1' already exists. Skipping...
Folder 'GCA_033300655.1_PDT001743417.1' already exists. Skipping...
Folder 'GCA_033300675.1_PDT001743416.1' already exists. Skipping...
Folder 'GCA_033300695.1_PDT001743415.1' already exists. Skipping...
Folder 'GCA_033300715.1_PDT001743414.1' already exists. Skipping...
Folder 'GCA_033300735.1_PDT001743413.1' already exists. Skipping...
Folder 'GCA_033300755.1_PDT001743412.1' already exists. Skipping...
Folder 'GCA_033300775.1_PDT001743411.1' already exists. Skipping...
Folder 'GCA_033300795.1_PDT001743410.1' already exists. Skipping...
Folder 'GCA_033300815.1_PDT001743409.1' already exists. Skipping...
Folder 'GCA_033300835.1_PDT001743408.1' already exists. Skipping...
Folder 'GCA_033300855.1_PDT001743407.1' already exists. Skipping...
Folder 'GCA_033300875.1_PDT001743406.1' already exists. Skipping...
Folder 'GCA_033300895.1_PDT001743405.1' already exists. Skipping...
Folder 'GCA_033300915.1_PDT001743404.1' already exists. Skipping...
Folder 'GCA_033300935.1_PDT001743401.1' already exists. Skipping...
Folder 'GCA_033300955.1_PDT001743402.1' already exists. Skipping...
Folder 'GCA_033300975.1_PDT001743400.1' already exists. Skipping...
Folder 'GCA_033300995.1_PDT001743398.1' already exists. Skipping...
Folder 'GCA_033301015.1_PDT001743399.1' already exists. Skipping...
Folder 'GCA_033301035.1_PDT001743397.1' already exists. Skipping...
Folder 'GCA_033301055.1_PDT001743395.1' already exists. Skipping...
Folder 'GCA_033301075.1_PDT001743396.1' already exists. Skipping...
Folder 'GCA_033301095.1_PDT001743393.1' already exists. Skipping...
Folder 'GCA_033301115.1_PDT001743394.1' already exists. Skipping...
Folder 'GCA_033301135.1_PDT001743391.1' already exists. Skipping...
Folder 'GCA_033301155.1_PDT001743389.1' already exists. Skipping...
Folder 'GCA_033301175.1_PDT001743392.1' already exists. Skipping...
Folder 'GCA_033301195.1_PDT001743390.1' already exists. Skipping...
Folder 'GCA_033301215.1_PDT001743388.1' already exists. Skipping...
Folder 'GCA_033301235.1_PDT001743387.1' already exists. Skipping...
Folder 'GCA_033301255.1_PDT001743386.1' already exists. Skipping...
Folder 'GCA_033301275.1_PDT001743385.1' already exists. Skipping...
Folder 'GCA_033301295.1_PDT001743384.1' already exists. Skipping...
Folder 'GCA_033301315.1_PDT001743383.1' already exists. Skipping...
Folder 'GCA_033301335.1_PDT001743382.1' already exists. Skipping...
Folder 'GCA_033301355.1_PDT001743380.1' already exists. Skipping...
Folder 'GCA_033301375.1_PDT001743381.1' already exists. Skipping...
Folder 'GCA_033302115.1_PDT001966431.1' already exists. Skipping...
Folder 'GCA_033302155.1_PDT001966429.1' already exists. Skipping...
Folder 'GCA_033302315.1_PDT001743378.1' already exists. Skipping...
Folder 'GCA_033302335.1_PDT001743379.1' already exists. Skipping...
Folder 'GCA_033302355.1_PDT001743377.1' already exists. Skipping...
Folder 'GCA_033302375.1_PDT001743376.1' already exists. Skipping...
Folder 'GCA_033302575.1_PDT001966407.1' already exists. Skipping...
Folder 'GCA_033302615.1_PDT001966406.1' already exists. Skipping...
Folder 'GCA_033302855.1_PDT001966399.1' already exists. Skipping...
Folder 'GCA_033302875.1_PDT001966401.1' already exists. Skipping...
Folder 'GCA_033302895.1_PDT001966400.1' already exists. Skipping...
Folder 'GCA_033302915.1_PDT001966397.1' already exists. Skipping...
Folder 'GCA_033302935.1_PDT001966398.1' already exists. Skipping...
Folder 'GCA_033302955.1_PDT001966396.1' already exists. Skipping...
Folder 'GCA_033302995.1_PDT001966395.1' already exists. Skipping...
Folder 'GCA_033303015.1_PDT001966393.1' already exists. Skipping...
Folder 'GCA_033303035.1_PDT001966392.1' already exists. Skipping...
Folder 'GCA_033303075.1_PDT001966390.1' already exists. Skipping...
Folder 'GCA_033303095.1_PDT001966388.1' already exists. Skipping...
Folder 'GCA_033303135.1_PDT001966386.1' already exists. Skipping...
Folder 'GCA_033303155.1_PDT001966387.1' already exists. Skipping...
Folder 'GCA_033303235.1_PDT001966379.1' already exists. Skipping...
Folder 'GCA_033303435.1_PDT001966372.1' already exists. Skipping...
Folder 'GCA_033303455.1_PDT001966371.1' already exists. Skipping...
Folder 'GCA_033303475.1_PDT001966370.1' already exists. Skipping...
Folder 'GCA_033303515.1_PDT001966369.1' already exists. Skipping...
Folder 'GCA_033303535.1_PDT001966368.1' already exists. Skipping...
Folder 'GCA_033303575.1_PDT001966366.1' already exists. Skipping...
Folder 'GCA_033303595.1_PDT001966365.1' already exists. Skipping...
Folder 'GCA_033303615.1_PDT001966363.1' already exists. Skipping...
Folder 'GCA_033303735.1_PDT001966355.1' already exists. Skipping...
Folder 'GCA_033303775.1_PDT001966354.1' already exists. Skipping...
Folder 'GCA_033303795.1_PDT001966352.1' already exists. Skipping...
Folder 'GCA_033303835.1_PDT001966351.1' already exists. Skipping...
Folder 'GCA_033303855.1_PDT001966348.1' already exists. Skipping...
Folder 'GCA_033303895.1_PDT001966347.1' already exists. Skipping...
Folder 'GCA_033303935.1_PDT001966345.1' already exists. Skipping...
Folder 'GCA_033303975.1_PDT001966344.1' already exists. Skipping...
Folder 'GCA_033304035.1_PDT001966341.1' already exists. Skipping...
Folder 'GCA_033304055.1_PDT001966339.1' already exists. Skipping...
Folder 'GCA_033304075.1_PDT001966336.1' already exists. Skipping...
Folder 'GCA_033304155.1_PDT001966337.1' already exists. Skipping...
Folder 'GCA_033304215.1_PDT001966329.1' already exists. Skipping...
Folder 'GCA_033305295.1_PDT001743375.1' already exists. Skipping...
Folder 'GCA_033305315.1_PDT001743374.1' already exists. Skipping...
Folder 'GCA_033305335.1_PDT001743373.1' already exists. Skipping...
Folder 'GCA_033305355.1_PDT001743369.1' already exists. Skipping...
Folder 'GCA_033305375.1_PDT001743370.1' already exists. Skipping...
Folder 'GCA_033305395.1_PDT001743372.1' already exists. Skipping...
Folder 'GCA_033305415.1_PDT001743371.1' already exists. Skipping...
Folder 'GCA_033305435.1_PDT001743368.1' already exists. Skipping...

Retreiveing data: 103018it [00:16, 6601.35it/s]

Folder 'GCA_033382135.1_PDT001751019.1' already exists. Skipping...
Folder 'GCA_033382155.1_PDT001751017.1' already exists. Skipping...
Folder 'GCA_033382175.1_PDT001751015.1' already exists. Skipping...
Folder 'GCA_033382195.1_PDT001751016.1' already exists. Skipping...
Folder 'GCA_033382215.1_PDT001751014.1' already exists. Skipping...
Folder 'GCA_033382235.1_PDT001751013.1' already exists. Skipping...
Folder 'GCA_033382255.1_PDT001751012.1' already exists. Skipping...
Folder 'GCA_033382275.1_PDT001751011.1' already exists. Skipping...
Folder 'GCA_033382295.1_PDT001751010.1' already exists. Skipping...
Folder 'GCA_033382315.1_PDT001751009.1' already exists. Skipping...
Folder 'GCA_033382335.1_PDT001751008.1' already exists. Skipping...
Folder 'GCA_033382355.1_PDT001751007.1' already exists. Skipping...
Folder 'GCA_033382365.1_PDT001751006.1' already exists. Skipping...
Folder 'GCA_033382395.1_PDT001751005.1' already exists. Skipping...
Folder 'GCA_033382415.1_PDT001751004.1' already exists. Skipping...
Folder 'GCA_033382435.1_PDT001751002.1' already exists. Skipping...
Folder 'GCA_033382455.1_PDT001751003.1' already exists. Skipping...
Folder 'GCA_033382475.1_PDT001751000.1' already exists. Skipping...
Folder 'GCA_033382495.1_PDT001750999.1' already exists. Skipping...
Folder 'GCA_033382515.1_PDT001750998.1' already exists. Skipping...
Folder 'GCA_033382535.1_PDT001750996.1' already exists. Skipping...
Folder 'GCA_033382615.1_PDT001750991.1' already exists. Skipping...
Folder 'GCA_033382635.1_PDT001750990.1' already exists. Skipping...
Folder 'GCA_033382655.1_PDT001750989.1' already exists. Skipping...
Folder 'GCA_033382675.1_PDT001750985.1' already exists. Skipping...
Folder 'GCA_033382695.1_PDT001750986.1' already exists. Skipping...
Folder 'GCA_033382715.1_PDT001750988.1' already exists. Skipping...
Folder 'GCA_033382735.1_PDT001750987.1' already exists. Skipping...
Folder 'GCA_033382755.1_PDT001750984.1' already exists. Skipping...
Folder 'GCA_033382775.1_PDT001750983.1' already exists. Skipping...
Folder 'GCA_033382795.1_PDT001750981.1' already exists. Skipping...
Folder 'GCA_033382895.1_PDT001750977.1' already exists. Skipping...
Folder 'GCA_033382915.1_PDT001750976.1' already exists. Skipping...
Folder 'GCA_033382935.1_PDT001750974.1' already exists. Skipping...
Folder 'GCA_033382955.1_PDT001750973.1' already exists. Skipping...
Folder 'GCA_033382975.1_PDT001750972.1' already exists. Skipping...
Folder 'GCA_033382995.1_PDT001750970.1' already exists. Skipping...
Folder 'GCA_033383015.1_PDT001750971.1' already exists. Skipping...
Folder 'GCA_033383035.1_PDT001750969.1' already exists. Skipping...
Folder 'GCA_033383055.1_PDT001750968.1' already exists. Skipping...
Folder 'GCA_033383075.1_PDT001750967.1' already exists. Skipping...
Folder 'GCA_033383095.1_PDT001750966.1' already exists. Skipping...
Folder 'GCA_033383115.1_PDT001750965.1' already exists. Skipping...
Folder 'GCA_033383135.1_PDT001971106.1' already exists. Skipping...
Folder 'GCA_033383155.1_PDT001971103.1' already exists. Skipping...
Folder 'GCA_033383175.1_PDT001971102.1' already exists. Skipping...
Folder 'GCA_033383195.1_PDT001971099.1' already exists. Skipping...
Folder 'GCA_033383445.1_PDT001750964.1' already exists. Skipping...
Folder 'GCA_033383515.1_PDT001750963.1' already exists. Skipping...
Folder 'GCA_033383555.1_PDT001750962.1' already exists. Skipping...
Folder 'GCA_033383575.1_PDT001750960.1' already exists. Skipping...
Folder 'GCA_033383595.1_PDT001750959.1' already exists. Skipping...
Folder 'GCA_033383615.1_PDT001750958.1' already exists. Skipping...
Folder 'GCA_033383635.1_PDT001750957.1' already exists. Skipping...
Folder 'GCA_033383655.1_PDT001750956.1' already exists. Skipping...
Folder 'GCA_033383675.1_PDT001750954.1' already exists. Skipping...
Folder 'GCA_033383695.1_PDT001750955.1' already exists. Skipping...
Folder 'GCA_033383715.1_PDT001750953.1' already exists. Skipping...
Folder 'GCA_033383735.1_PDT001750952.1' already exists. Skipping...
Folder 'GCA_033383775.1_PDT001750949.1' already exists. Skipping...
Folder 'GCA_033383795.1_PDT001750948.1' already exists. Skipping...
Folder 'GCA_033383815.1_PDT001750946.1' already exists. Skipping...
Folder 'GCA_033383835.1_PDT001750945.1' already exists. Skipping...
Folder 'GCA_033383855.1_PDT001750947.1' already exists. Skipping...
Folder 'GCA_033383875.1_PDT001750944.1' already exists. Skipping...
Folder 'GCA_033383895.1_PDT001750943.1' already exists. Skipping...
Folder 'GCA_033383915.1_PDT001750942.1' already exists. Skipping...
Folder 'GCA_033383975.1_PDT001750938.1' already exists. Skipping...
Folder 'GCA_033384075.1_PDT001750933.1' already exists. Skipping...
Folder 'GCA_033384115.1_PDT001971105.1' already exists. Skipping...
Folder 'GCA_033384715.1_PDT001750932.1' already exists. Skipping...
Folder 'GCA_033385195.1_PDT001750926.1' already exists. Skipping...
Folder 'GCA_033385215.1_PDT001750928.1' already exists. Skipping...
Folder 'GCA_033385235.1_PDT001750925.1' already exists. Skipping...
Folder 'GCA_033385255.1_PDT001750927.1' already exists. Skipping...
Folder 'GCA_033385275.1_PDT001750923.1' already exists. Skipping...
Folder 'GCA_033385295.1_PDT001750924.1' already exists. Skipping...
Folder 'GCA_033385315.1_PDT001750922.1' already exists. Skipping...
Folder 'GCA_033385335.1_PDT001750921.1' already exists. Skipping...
Folder 'GCA_033385355.1_PDT001750920.1' already exists. Skipping...
Folder 'GCA_033385365.1_PDT001750919.1' already exists. Skipping...
Folder 'GCA_033385395.1_PDT001750918.1' already exists. Skipping...
Folder 'GCA_033385415.1_PDT001750917.1' already exists. Skipping...
Folder 'GCA_033385435.1_PDT001750915.1' already exists. Skipping...
Folder 'GCA_033385455.1_PDT001750914.1' already exists. Skipping...
Folder 'GCA_033385475.1_PDT001750916.1' already exists. Skipping...
Folder 'GCA_033385495.1_PDT001750912.1' already exists. Skipping...
Folder 'GCA_033385515.1_PDT001750913.1' already exists. Skipping...
Folder 'GCA_033385535.1_PDT001750911.1' already exists. Skipping...
Folder 'GCA_033385555.1_PDT001750910.1' already exists. Skipping...
Folder 'GCA_033385575.1_PDT001750909.1' already exists. Skipping...
Folder 'GCA_033385595.1_PDT001750907.1' already exists. Skipping...
Folder 'GCA_033385615.1_PDT001750908.1' already exists. Skipping...
Folder 'GCA_033385635.1_PDT001750905.1' already exists. Skipping...
Folder 'GCA_033385655.1_PDT001750904.1' already exists. Skipping...
Folder 'GCA_033385675.1_PDT001750903.1' already exists. Skipping...
Folder 'GCA_033385695.1_PDT001750902.1' already exists. Skipping...
Folder 'GCA_033385715.1_PDT001750900.1' already exists. Skipping...
Folder 'GCA_033385735.1_PDT001750901.1' already exists. Skipping...
Folder 'GCA_033385755.1_PDT001750899.1' already exists. Skipping...
Folder 'GCA_033385775.1_PDT001750898.1' already exists. Skipping...
Folder 'GCA_033385795.1_PDT001750896.1' already exists. Skipping...
Folder 'GCA_033385815.1_PDT001750894.1' already exists. Skipping...
Folder 'GCA_033385835.1_PDT001750891.1' already exists. Skipping...
Folder 'GCA_033385855.1_PDT001750893.1' already exists. Skipping...
Folder 'GCA_033385875.1_PDT001750889.1' already exists. Skipping...
Folder 'GCA_033385895.1_PDT001750890.1' already exists. Skipping...
Folder 'GCA_033385915.1_PDT001750888.1' already exists. Skipping...
Folder 'GCA_033385935.1_PDT001750886.1' already exists. Skipping...
Folder 'GCA_033385955.1_PDT001750885.1' already exists. Skipping...
Folder 'GCA_033385975.1_PDT001750884.1' already exists. Skipping...
Folder 'GCA_033385995.1_PDT001750883.1' already exists. Skipping...
Folder 'GCA_033386015.1_PDT001750882.1' already exists. Skipping...
Folder 'GCA_033386035.1_PDT001750881.1' already exists. Skipping...
Folder 'GCA_033386055.1_PDT001750880.1' already exists. Skipping...
Folder 'GCA_033386075.1_PDT001750879.1' already exists. Skipping...
Folder 'GCA_033386095.1_PDT001750877.1' already exists. Skipping...
Folder 'GCA_033386115.1_PDT001750876.1' already exists. Skipping...
Folder 'GCA_033386125.1_PDT001750878.1' already exists. Skipping...
Folder 'GCA_033386155.1_PDT001750874.1' already exists. Skipping...
Folder 'GCA_033386175.1_PDT001750875.1' already exists. Skipping...
Folder 'GCA_033386195.1_PDT001750873.1' already exists. Skipping...
Folder 'GCA_033386215.1_PDT001750871.1' already exists. Skipping...
Folder 'GCA_033386235.1_PDT001750872.1' already exists. Skipping...
Folder 'GCA_033386255.1_PDT001971744.1' already exists. Skipping...
Folder 'GCA_033386275.1_PDT001971739.1' already exists. Skipping...
Folder 'GCA_033386295.1_PDT001750870.1' already exists. Skipping...
Folder 'GCA_033386315.1_PDT001750864.1' already exists. Skipping...
Folder 'GCA_033386335.1_PDT001750865.1' already exists. Skipping...
Folder 'GCA_033386355.1_PDT001750869.1' already exists. Skipping...
Folder 'GCA_033386415.1_PDT001750863.1' already exists. Skipping...
Folder 'GCA_033386435.1_PDT001750862.1' already exists. Skipping...
Folder 'GCA_033386455.1_PDT001750860.1' already exists. Skipping...
Folder 'GCA_033386475.1_PDT001750861.1' already exists. Skipping...
Folder 'GCA_033386495.1_PDT001750859.1' already exists. Skipping...
Folder 'GCA_033386515.1_PDT001750858.1' already exists. Skipping...
Folder 'GCA_033386535.1_PDT001750857.1' already exists. Skipping...
Folder 'GCA_033386555.1_PDT001750852.1' already exists. Skipping...
Folder 'GCA_033386575.1_PDT001750854.1' already exists. Skipping...
Folder 'GCA_033386595.1_PDT001750855.1' already exists. Skipping...
Folder 'GCA_033386615.1_PDT001750847.1' already exists. Skipping...
Folder 'GCA_033386635.1_PDT001750846.1' already exists. Skipping...
Folder 'GCA_033386655.1_PDT001750845.1' already exists. Skipping...
Folder 'GCA_033386675.1_PDT001750844.1' already exists. Skipping...
Folder 'GCA_033386695.1_PDT001750843.1' already exists. Skipping...
Folder 'GCA_033386715.1_PDT001750837.1' already exists. Skipping...
Folder 'GCA_033386735.1_PDT001750838.1' already exists. Skipping...
Folder 'GCA_033386755.1_PDT001750835.1' already exists. Skipping...
Folder 'GCA_033386765.1_PDT001750832.1' already exists. Skipping...
Folder 'GCA_033386795.1_PDT001750834.1' already exists. Skipping...
Folder 'GCA_033386815.1_PDT001750830.1' already exists. Skipping...
Folder 'GCA_033386835.1_PDT001750831.1' already exists. Skipping...
Folder 'GCA_033386855.1_PDT001750828.1' already exists. Skipping...
Folder 'GCA_033386875.1_PDT001750829.1' already exists. Skipping...
Folder 'GCA_033386895.1_PDT001750827.1' already exists. Skipping...
Folder 'GCA_033386915.1_PDT001750825.1' already exists. Skipping...
Folder 'GCA_033386935.1_PDT001750826.1' already exists. Skipping...
Folder 'GCA_033386955.1_PDT001750824.1' already exists. Skipping...
Folder 'GCA_033386975.1_PDT001750823.1' already exists. Skipping...
Folder 'GCA_033386995.1_PDT001750822.1' already exists. Skipping...
Folder 'GCA_033387015.1_PDT001750820.1' already exists. Skipping...
Folder 'GCA_033387035.1_PDT001750821.1' already exists. Skipping...
Folder 'GCA_033387055.1_PDT001750818.1' already exists. Skipping...
Folder 'GCA_033387075.1_PDT001750817.1' already exists. Skipping...
Folder 'GCA_033387095.1_PDT001750816.1' already exists. Skipping...
Folder 'GCA_033387115.1_PDT001750866.1' already exists. Skipping...
Folder 'GCA_033387135.1_PDT001750868.1' already exists. Skipping...
Folder 'GCA_033387155.1_PDT001750815.1' already exists. Skipping...
Folder 'GCA_033387195.1_PDT001750813.1' already exists. Skipping...
Folder 'GCA_033387215.1_PDT001750814.1' already exists. Skipping...
Folder 'GCA_033387235.1_PDT001750811.1' already exists. Skipping...
Folder 'GCA_033387255.1_PDT001750812.1' already exists. Skipping...
Folder 'GCA_033387275.1_PDT001750809.1' already exists. Skipping...
Folder 'GCA_033387295.1_PDT001750810.1' already exists. Skipping...
Folder 'GCA_033387315.1_PDT001750808.1' already exists. Skipping...
Folder 'GCA_033387335.1_PDT001750807.1' already exists. Skipping...
Folder 'GCA_033387355.1_PDT001750806.1' already exists. Skipping...
Folder 'GCA_033387375.1_PDT001750805.1' already exists. Skipping...
Folder 'GCA_033387395.1_PDT001750804.1' already exists. Skipping...
Folder 'GCA_033387415.1_PDT001750803.1' already exists. Skipping...
Folder 'GCA_033387435.1_PDT001750802.1' already exists. Skipping...
Folder 'GCA_033387455.1_PDT001750801.1' already exists. Skipping...
Folder 'GCA_033387475.1_PDT001750800.1' already exists. Skipping...
Folder 'GCA_033387495.1_PDT001750799.1' already exists. Skipping...
Folder 'GCA_033387515.1_PDT001750798.1' already exists. Skipping...
Folder 'GCA_033387535.1_PDT001750797.1' already exists. Skipping...
Folder 'GCA_033387555.1_PDT001750796.1' already exists. Skipping...
Folder 'GCA_033387575.1_PDT001750794.1' already exists. Skipping...
Folder 'GCA_033387595.1_PDT001750795.1' already exists. Skipping...
Folder 'GCA_033387615.1_PDT001750793.1' already exists. Skipping...
Folder 'GCA_033387635.1_PDT001750791.1' already exists. Skipping...
Folder 'GCA_033387655.1_PDT001750792.1' already exists. Skipping...
Folder 'GCA_033387675.1_PDT001750790.1' already exists. Skipping...
Folder 'GCA_033387715.1_PDT001971748.1' already exists. Skipping...
Folder 'GCA_033387735.1_PDT001971740.1' already exists. Skipping...
Folder 'GCA_033387895.1_PDT001971719.1' already exists. Skipping...
Folder 'GCA_033388135.1_PDT001971599.1' already exists. Skipping...
Folder 'GCA_033388455.1_PDT001750774.1' already exists. Skipping...
Folder 'GCA_033388635.1_PDT001750763.1' already exists. Skipping...
Folder 'GCA_033389875.1_PDT001972185.1' already exists. Skipping...
Folder 'GCA_033394935.1_PDT001972305.1' already exists. Skipping...
Folder 'GCA_033394955.1_PDT001972304.1' already exists. Skipping...
Folder 'GCA_033394975.1_PDT001972303.1' already exists. Skipping...
Folder 'GCA_033394995.1_PDT001972302.1' already exists. Skipping...
Folder 'GCA_033395095.1_PDT001972296.1' already exists. Skipping...
Folder 'GCA_033395235.1_PDT001972291.1' already exists. Skipping...
Folder 'GCA_033395255.1_PDT001972290.1' already exists. Skipping...
Folder 'GCA_033395335.1_PDT001972286.1' already exists. Skipping...
Folder 'GCA_033395355.1_PDT001972285.1' already exists. Skipping...
Folder 'GCA_033396295.1_PDT001972243.1' already exists. Skipping...
Folder 'GCA_033396315.1_PDT001972242.1' already exists. Skipping...
Folder 'GCA_033396335.1_PDT001972239.1' already exists. Skipping...
Folder 'GCA_033396355.1_PDT001972238.1' already exists. Skipping...
Folder 'GCA_033396395.1_PDT001972235.1' already exists. Skipping...
Folder 'GCA_033396435.1_PDT001972236.1' already exists. Skipping...
Folder 'GCA_033396495.1_PDT001972231.1' already exists. Skipping...
Folder 'GCA_033397175.1_PDT001972198.1' already exists. Skipping...
Folder 'GCA_033397855.1_PDT001750892.1' already exists. Skipping...
Folder 'GCA_033398395.1_PDT001972196.1' already exists. Skipping...
Folder 'GCA_033398415.1_PDT001972197.1' already exists. Skipping...
Folder 'GCA_033398435.1_PDT001972195.1' already exists. Skipping...
Folder 'GCA_033398475.1_PDT001972193.1' already exists. Skipping...
Folder 'GCA_033398515.1_PDT001972191.1' already exists. Skipping...
Folder 'GCA_033398535.1_PDT001972190.1' already exists. Skipping...
Folder 'GCA_033398555.1_PDT001972189.1' already exists. Skipping...
Folder 'GCA_033398795.1_PDT001972175.1' already exists. Skipping...
Folder 'GCA_033398835.1_PDT001972174.1' already exists. Skipping...
Folder 'GCA_033398855.1_PDT001972172.1' already exists. Skipping...
Folder 'GCA_033398875.1_PDT001972170.1' already exists. Skipping...
Folder 'GCA_033398895.1_PDT001972171.1' already exists. Skipping...
Folder 'GCA_033398915.1_PDT001972173.1' already exists. Skipping...
Folder 'GCA_033398935.1_PDT001972168.1' already exists. Skipping...
Folder 'GCA_033398955.1_PDT001972167.1' already exists. Skipping...
Folder 'GCA_033399275.1_PDT001750887.1' already exists. Skipping...
Folder 'GCA_033399515.1_PDT001972116.1' already exists. Skipping...
Folder 'GCA_033399535.1_PDT001972115.1' already exists. Skipping...
Folder 'GCA_033399545.1_PDT001972114.1' already exists. Skipping...
Folder 'GCA_033399595.1_PDT001972113.1' already exists. Skipping...
Folder 'GCA_033400015.1_PDT001972088.1' already exists. Skipping...
Folder 'GCA_033401495.1_PDT001971598.1' already exists. Skipping...
Folder 'GCA_033401675.1_PDT001750678.1' already exists. Skipping...
Folder 'GCA_033401735.1_PDT001750677.1' already exists. Skipping...
Folder 'GCA_033401755.1_PDT001750676.1' already exists. Skipping...
Folder 'GCA_033401775.1_PDT001750675.1' already exists. Skipping...
Folder 'GCA_033401795.1_PDT001750673.1' already exists. Skipping...
Folder 'GCA_033401815.1_PDT001750674.1' already exists. Skipping...
Folder 'GCA_033401835.1_PDT001750672.1' already exists. Skipping...
Folder 'GCA_033401855.1_PDT001750670.1' already exists. Skipping...
Folder 'GCA_033401875.1_PDT001750671.1' already exists. Skipping...
Folder 'GCA_033401895.1_PDT001750669.1' already exists. Skipping...
Folder 'GCA_033401915.1_PDT001750667.1' already exists. Skipping...
Folder 'GCA_033401935.1_PDT001750666.1' already exists. Skipping...
Folder 'GCA_033401955.1_PDT001750668.1' already exists. Skipping...
Folder 'GCA_033401995.1_PDT001750664.1' already exists. Skipping...
Folder 'GCA_033402015.1_PDT001750665.1' already exists. Skipping...
Folder 'GCA_033402035.1_PDT001750661.1' already exists. Skipping...
Folder 'GCA_033402055.1_PDT001750662.1' already exists. Skipping...
Folder 'GCA_033402075.1_PDT001750660.1' already exists. Skipping...
Folder 'GCA_033402095.1_PDT001750659.1' already exists. Skipping...
Folder 'GCA_033402115.1_PDT001750658.1' already exists. Skipping...
Folder 'GCA_033402135.1_PDT001750657.1' already exists. Skipping...
Folder 'GCA_033402155.1_PDT001750656.1' already exists. Skipping...
Folder 'GCA_033402175.1_PDT001750655.1' already exists. Skipping...
Folder 'GCA_033402195.1_PDT001750654.1' already exists. Skipping...
Folder 'GCA_033402215.1_PDT001750653.1' already exists. Skipping...
Folder 'GCA_033402245.1_PDT001750652.1' already exists. Skipping...
Folder 'GCA_033402275.1_PDT001750636.1' already exists. Skipping...
Folder 'GCA_033402315.1_PDT001750651.1' already exists. Skipping...
Folder 'GCA_033402335.1_PDT001750633.1' already exists. Skipping...
Folder 'GCA_033402355.1_PDT001750632.1' already exists. Skipping...
Folder 'GCA_033402375.1_PDT001750631.1' already exists. Skipping...
Folder 'GCA_033402395.1_PDT001750646.1' already exists. Skipping...
Folder 'GCA_033402415.1_PDT001750649.1' already exists. Skipping...
Folder 'GCA_033402435.1_PDT001750647.1' already exists. Skipping...
Folder 'GCA_033402445.1_PDT001750648.1' already exists. Skipping...
Folder 'GCA_033402475.1_PDT001750650.1' already exists. Skipping...
Folder 'GCA_033402495.1_PDT001750643.1' already exists. Skipping...
Folder 'GCA_033402505.1_PDT001750639.1' already exists. Skipping...
Folder 'GCA_033402535.1_PDT001750642.1' already exists. Skipping...
Folder 'GCA_033402555.1_PDT001750622.1' already exists. Skipping...
Folder 'GCA_033402575.1_PDT001750628.1' already exists. Skipping...
Folder 'GCA_033402595.1_PDT001750620.1' already exists. Skipping...
Folder 'GCA_033402615.1_PDT001750623.1' already exists. Skipping...
Folder 'GCA_033402635.1_PDT001750621.1' already exists. Skipping...
Folder 'GCA_033402655.1_PDT001750619.1' already exists. Skipping...
Folder 'GCA_033402675.1_PDT001750617.1' already exists. Skipping...
Folder 'GCA_033402695.1_PDT001750618.1' already exists. Skipping...
Folder 'GCA_033402735.1_PDT001750616.1' already exists. Skipping...
Folder 'GCA_033402775.1_PDT001750606.1' already exists. Skipping...
Folder 'GCA_033402795.1_PDT001750607.1' already exists. Skipping...
Folder 'GCA_033402815.1_PDT001750603.1' already exists. Skipping...
Folder 'GCA_033402835.1_PDT001750605.1' already exists. Skipping...
Folder 'GCA_033402855.1_PDT001750604.1' already exists. Skipping...
Folder 'GCA_033402895.1_PDT001750599.1' already exists. Skipping...

Retreiveing data: 104345it [00:17, 6602.23it/s]

Folder 'GCA_033451085.1_PDT001974302.1' already exists. Skipping...
Folder 'GCA_033451105.1_PDT001974299.1' already exists. Skipping...
Folder 'GCA_033451125.1_PDT001974296.1' already exists. Skipping...
Folder 'GCA_033451145.1_PDT001974297.1' already exists. Skipping...
Folder 'GCA_033451225.1_PDT001974295.1' already exists. Skipping...
Folder 'GCA_033454205.1_PDT001952274.1' already exists. Skipping...
Folder 'GCA_033454885.1_PDT001927392.1' already exists. Skipping...
Folder 'GCA_033455365.1_PDT001748780.1' already exists. Skipping...
Folder 'GCA_033455425.1_PDT001748779.1' already exists. Skipping...
Folder 'GCA_033455445.1_PDT001748778.1' already exists. Skipping...
Folder 'GCA_033455465.1_PDT001748777.1' already exists. Skipping...
Folder 'GCA_033455485.1_PDT001748775.1' already exists. Skipping...
Folder 'GCA_033455545.1_PDT001748773.1' already exists. Skipping...
Folder 'GCA_033455565.1_PDT001748771.1' already exists. Skipping...
Folder 'GCA_033455585.1_PDT001748770.1' already exists. Skipping...
Folder 'GCA_033455605.1_PDT001748772.1' already exists. Skipping...
Folder 'GCA_033455625.1_PDT001748768.1' already exists. Skipping...
Folder 'GCA_033455645.1_PDT001748769.1' already exists. Skipping...
Folder 'GCA_033455665.1_PDT001748766.1' already exists. Skipping...
Folder 'GCA_033455685.1_PDT001748765.1' already exists. Skipping...
Folder 'GCA_033455705.1_PDT001748764.1' already exists. Skipping...
Folder 'GCA_033455745.1_PDT001748763.1' already exists. Skipping...
Folder 'GCA_033455765.1_PDT001748762.1' already exists. Skipping...
Folder 'GCA_033455785.1_PDT001748761.1' already exists. Skipping...
Folder 'GCA_033455805.1_PDT001748760.1' already exists. Skipping...
Folder 'GCA_033455845.1_PDT001748759.1' already exists. Skipping...
Folder 'GCA_033455865.1_PDT001748758.1' already exists. Skipping...
Folder 'GCA_033455885.1_PDT001748754.1' already exists. Skipping...
Folder 'GCA_033455905.1_PDT001748753.1' already exists. Skipping...
Folder 'GCA_033455925.1_PDT001748752.1' already exists. Skipping...
Folder 'GCA_033455945.1_PDT001748750.1' already exists. Skipping...
Folder 'GCA_033455985.1_PDT001748748.1' already exists. Skipping...
Folder 'GCA_033456005.1_PDT001748747.1' already exists. Skipping...
Folder 'GCA_033456025.1_PDT001748749.1' already exists. Skipping...
Folder 'GCA_033456045.1_PDT001748746.1' already exists. Skipping...
Folder 'GCA_033456065.1_PDT001748745.1' already exists. Skipping...
Folder 'GCA_033456085.1_PDT001748744.1' already exists. Skipping...
Folder 'GCA_033456125.1_PDT001748743.1' already exists. Skipping...
Folder 'GCA_033456145.1_PDT001748740.1' already exists. Skipping...
Folder 'GCA_033456165.1_PDT001748741.1' already exists. Skipping...
Folder 'GCA_033456185.1_PDT001748739.1' already exists. Skipping...
Folder 'GCA_033456205.1_PDT001748737.1' already exists. Skipping...
Folder 'GCA_033456225.1_PDT001748738.1' already exists. Skipping...
Folder 'GCA_033456245.1_PDT001748735.1' already exists. Skipping...
Folder 'GCA_033456265.1_PDT001748734.1' already exists. Skipping...
Folder 'GCA_033456285.1_PDT001748736.1' already exists. Skipping...
Folder 'GCA_033456305.1_PDT001748733.1' already exists. Skipping...
Folder 'GCA_033456325.1_PDT001748732.1' already exists. Skipping...
Folder 'GCA_033456345.1_PDT001748731.1' already exists. Skipping...
Folder 'GCA_033456365.1_PDT001748730.1' already exists. Skipping...
Folder 'GCA_033456405.1_PDT001748728.1' already exists. Skipping...
Folder 'GCA_033456425.1_PDT001748727.1' already exists. Skipping...
Folder 'GCA_033456465.1_PDT001748726.1' already exists. Skipping...
Folder 'GCA_033456485.1_PDT001748723.1' already exists. Skipping...
Folder 'GCA_033456505.1_PDT001748722.1' already exists. Skipping...
Folder 'GCA_033456525.1_PDT001748724.1' already exists. Skipping...
Folder 'GCA_033456545.1_PDT001748720.1' already exists. Skipping...
Folder 'GCA_033456565.1_PDT001748721.1' already exists. Skipping...
Folder 'GCA_033456585.1_PDT001748717.1' already exists. Skipping...
Folder 'GCA_033456605.1_PDT001748718.1' already exists. Skipping...
Folder 'GCA_033456645.1_PDT001748715.1' already exists. Skipping...
Folder 'GCA_033456665.1_PDT001748716.1' already exists. Skipping...
Folder 'GCA_033456685.1_PDT001748713.1' already exists. Skipping...
Folder 'GCA_033456705.1_PDT001748714.1' already exists. Skipping...
Folder 'GCA_033456725.1_PDT001748712.1' already exists. Skipping...
Folder 'GCA_033456745.1_PDT001748711.1' already exists. Skipping...
Folder 'GCA_033456785.1_PDT001748709.1' already exists. Skipping...
Folder 'GCA_033456795.1_PDT001748708.1' already exists. Skipping...
Folder 'GCA_033456825.1_PDT001748710.1' already exists. Skipping...
Folder 'GCA_033456845.1_PDT001748705.1' already exists. Skipping...
Folder 'GCA_033456865.1_PDT001748706.1' already exists. Skipping...
Folder 'GCA_033456885.1_PDT001748704.1' already exists. Skipping...
Folder 'GCA_033456905.1_PDT001748703.1' already exists. Skipping...
Folder 'GCA_033456925.1_PDT001748702.1' already exists. Skipping...
Folder 'GCA_033456965.1_PDT001748700.1' already exists. Skipping...
Folder 'GCA_033456985.1_PDT001748698.1' already exists. Skipping...
Folder 'GCA_033457005.1_PDT001748699.1' already exists. Skipping...
Folder 'GCA_033457025.1_PDT001748695.1' already exists. Skipping...
Folder 'GCA_033457045.1_PDT001748696.1' already exists. Skipping...
Folder 'GCA_033457065.1_PDT001748697.1' already exists. Skipping...
Folder 'GCA_033457085.1_PDT001748694.1' already exists. Skipping...
Folder 'GCA_033457105.1_PDT001748693.1' already exists. Skipping...
Folder 'GCA_033457125.1_PDT001748691.1' already exists. Skipping...
Folder 'GCA_033457145.1_PDT001748692.1' already exists. Skipping...
Folder 'GCA_033457165.1_PDT001748688.1' already exists. Skipping...
Folder 'GCA_033457185.1_PDT001748689.1' already exists. Skipping...
Folder 'GCA_033457205.1_PDT001748690.1' already exists. Skipping...
Folder 'GCA_033457225.1_PDT001748686.1' already exists. Skipping...
Folder 'GCA_033457245.1_PDT001748687.1' already exists. Skipping...
Folder 'GCA_033457265.1_PDT001748683.1' already exists. Skipping...
Folder 'GCA_033457285.1_PDT001748684.1' already exists. Skipping...
Folder 'GCA_033457305.1_PDT001748685.1' already exists. Skipping...
Folder 'GCA_033457325.1_PDT001748682.1' already exists. Skipping...
Folder 'GCA_033457345.1_PDT001748679.1' already exists. Skipping...
Folder 'GCA_033457405.1_PDT001748680.1' already exists. Skipping...
Folder 'GCA_033457425.1_PDT001748677.1' already exists. Skipping...
Folder 'GCA_033457445.1_PDT001748675.1' already exists. Skipping...
Folder 'GCA_033457465.1_PDT001748676.1' already exists. Skipping...
Folder 'GCA_033457485.1_PDT001748674.1' already exists. Skipping...
Folder 'GCA_033457505.1_PDT001748673.1' already exists. Skipping...
Folder 'GCA_033457535.1_PDT001748667.1' already exists. Skipping...
Folder 'GCA_033457555.1_PDT001748671.1' already exists. Skipping...
Folder 'GCA_033457575.1_PDT001748670.1' already exists. Skipping...
Folder 'GCA_033457595.1_PDT001748669.1' already exists. Skipping...
Folder 'GCA_033457635.1_PDT001748668.1' already exists. Skipping...
Folder 'GCA_033457675.1_PDT001748665.1' already exists. Skipping...
Folder 'GCA_033457695.1_PDT001748663.1' already exists. Skipping...
Folder 'GCA_033457715.1_PDT001748664.1' already exists. Skipping...
Folder 'GCA_033457755.1_PDT001748662.1' already exists. Skipping...
Folder 'GCA_033457775.1_PDT001748660.1' already exists. Skipping...
Folder 'GCA_033457795.1_PDT001748659.1' already exists. Skipping...
Folder 'GCA_033457815.1_PDT001748658.1' already exists. Skipping...
Folder 'GCA_033457835.1_PDT001748656.1' already exists. Skipping...
Folder 'GCA_033457855.1_PDT001748657.1' already exists. Skipping...
Folder 'GCA_033457875.1_PDT001748655.1' already exists. Skipping...
Folder 'GCA_033457895.1_PDT001748653.1' already exists. Skipping...
Folder 'GCA_033457935.1_PDT001748652.1' already exists. Skipping...
Folder 'GCA_033457955.1_PDT001748651.1' already exists. Skipping...
Folder 'GCA_033457975.1_PDT001748650.1' already exists. Skipping...
Folder 'GCA_033457995.1_PDT001748648.1' already exists. Skipping...
Folder 'GCA_033458015.1_PDT001748649.1' already exists. Skipping...
Folder 'GCA_033458035.1_PDT001748647.1' already exists. Skipping...
Folder 'GCA_033458055.1_PDT001748646.1' already exists. Skipping...
Folder 'GCA_033458075.1_PDT001748645.1' already exists. Skipping...
Folder 'GCA_033458095.1_PDT001748643.1' already exists. Skipping...
Folder 'GCA_033458115.1_PDT001748644.1' already exists. Skipping...
Folder 'GCA_033458135.1_PDT001748642.1' already exists. Skipping...
Folder 'GCA_033458155.1_PDT001748639.1' already exists. Skipping...
Folder 'GCA_033458175.1_PDT001748641.1' already exists. Skipping...
Folder 'GCA_033458195.1_PDT001748637.1' already exists. Skipping...
Folder 'GCA_033458215.1_PDT001748638.1' already exists. Skipping...
Folder 'GCA_033458235.1_PDT001748634.1' already exists. Skipping...
Folder 'GCA_033458255.1_PDT001748633.1' already exists. Skipping...
Folder 'GCA_033458275.1_PDT001748632.1' already exists. Skipping...
Folder 'GCA_033458295.1_PDT001748630.1' already exists. Skipping...
Folder 'GCA_033458315.1_PDT001748631.1' already exists. Skipping...
Folder 'GCA_033458385.1_PDT001748629.1' already exists. Skipping...
Folder 'GCA_033458405.1_PDT001748627.1' already exists. Skipping...
Folder 'GCA_033458435.1_PDT001748626.1' already exists. Skipping...
Folder 'GCA_033458455.1_PDT001748640.1' already exists. Skipping...
Folder 'GCA_033458475.1_PDT001748628.1' already exists. Skipping...
Folder 'GCA_033458495.1_PDT001748635.1' already exists. Skipping...
Folder 'GCA_033458515.1_PDT001748636.1' already exists. Skipping...
Folder 'GCA_033458535.1_PDT001748625.1' already exists. Skipping...
Folder 'GCA_033458565.1_PDT001748624.1' already exists. Skipping...
Folder 'GCA_033458605.1_PDT001748622.1' already exists. Skipping...
Folder 'GCA_033458625.1_PDT001748623.1' already exists. Skipping...
Folder 'GCA_033458645.1_PDT001748620.1' already exists. Skipping...
Folder 'GCA_033458665.1_PDT001748621.1' already exists. Skipping...
Folder 'GCA_033458685.1_PDT001748619.1' already exists. Skipping...
Folder 'GCA_033458705.1_PDT001748618.1' already exists. Skipping...
Folder 'GCA_033458745.1_PDT001748617.1' already exists. Skipping...
Folder 'GCA_033458765.1_PDT001748616.1' already exists. Skipping...
Folder 'GCA_033458865.1_PDT001748612.1' already exists. Skipping...
Folder 'GCA_033458885.1_PDT001748613.1' already exists. Skipping...
Folder 'GCA_033458935.1_PDT001748610.1' already exists. Skipping...
Folder 'GCA_033458965.1_PDT001748609.1' already exists. Skipping...
Folder 'GCA_033458985.1_PDT001748608.1' already exists. Skipping...
Folder 'GCA_033459005.1_PDT001748607.1' already exists. Skipping...
Folder 'GCA_033459025.1_PDT001748605.1' already exists. Skipping...
Folder 'GCA_033459045.1_PDT001748604.1' already exists. Skipping...
Folder 'GCA_033459065.1_PDT001748606.1' already exists. Skipping...
Folder 'GCA_033459085.1_PDT001748603.1' already exists. Skipping...
Folder 'GCA_033459105.1_PDT001748602.1' already exists. Skipping...
Folder 'GCA_033459125.1_PDT001748600.1' already exists. Skipping...
Folder 'GCA_033459165.1_PDT001748601.1' already exists. Skipping...
Folder 'GCA_033459185.1_PDT001748598.1' already exists. Skipping...
Folder 'GCA_033459225.1_PDT001748596.1' already exists. Skipping...
Folder 'GCA_033459265.1_PDT001748595.1' already exists. Skipping...
Folder 'GCA_033459305.1_PDT001748591.1' already exists. Skipping...
Folder 'GCA_033459335.1_PDT001748589.1' already exists. Skipping...
Folder 'GCA_033459355.1_PDT001748593.1' already exists. Skipping...
Folder 'GCA_033459375.1_PDT001748592.1' already exists. Skipping...
Folder 'GCA_033459435.1_PDT001748590.1' already exists. Skipping...
Folder 'GCA_033459455.1_PDT001748588.1' already exists. Skipping...
Folder 'GCA_033459475.1_PDT001748587.1' already exists. Skipping...
Folder 'GCA_033459495.1_PDT001748586.1' already exists. Skipping...
Folder 'GCA_033459525.1_PDT001748585.1' already exists. Skipping...
Folder 'GCA_033459545.1_PDT001748582.1' already exists. Skipping...
Folder 'GCA_033459565.1_PDT001748584.1' already exists. Skipping...
Folder 'GCA_033459575.1_PDT001748580.1' already exists. Skipping...
Folder 'GCA_033459605.1_PDT001748581.1' already exists. Skipping...
Folder 'GCA_033459645.1_PDT001748579.1' already exists. Skipping...
Folder 'GCA_033459675.1_PDT001748575.1' already exists. Skipping...
Folder 'GCA_033459705.1_PDT001748577.1' already exists. Skipping...
Folder 'GCA_033459725.1_PDT001748576.1' already exists. Skipping...
Folder 'GCA_033459745.1_PDT001748573.1' already exists. Skipping...
Folder 'GCA_033459785.1_PDT001748571.1' already exists. Skipping...
Folder 'GCA_033459805.1_PDT001748570.1' already exists. Skipping...
Folder 'GCA_033459825.1_PDT001748572.1' already exists. Skipping...
Folder 'GCA_033459845.1_PDT001748568.1' already exists. Skipping...
Folder 'GCA_033459885.1_PDT001748567.1' already exists. Skipping...
Folder 'GCA_033459905.1_PDT001748565.1' already exists. Skipping...
Folder 'GCA_033459945.1_PDT001748564.1' already exists. Skipping...
Folder 'GCA_033459965.1_PDT001748563.1' already exists. Skipping...
Folder 'GCA_033460005.1_PDT001748561.1' already exists. Skipping...
Folder 'GCA_033460025.1_PDT001748559.1' already exists. Skipping...
Folder 'GCA_033460045.1_PDT001748560.1' already exists. Skipping...
Folder 'GCA_033460065.1_PDT001748558.1' already exists. Skipping...
Folder 'GCA_033460075.1_PDT001748557.1' already exists. Skipping...
Folder 'GCA_033460105.1_PDT001748556.1' already exists. Skipping...
Folder 'GCA_033460125.1_PDT001748555.1' already exists. Skipping...
Folder 'GCA_033460185.1_PDT001748554.1' already exists. Skipping...
Folder 'GCA_033460205.1_PDT001748552.1' already exists. Skipping...
Folder 'GCA_033460225.1_PDT001748551.1' already exists. Skipping...
Folder 'GCA_033460245.1_PDT001748553.1' already exists. Skipping...
Folder 'GCA_033460265.1_PDT001748549.1' already exists. Skipping...
Folder 'GCA_033460285.1_PDT001748547.1' already exists. Skipping...
Folder 'GCA_033460305.1_PDT001748548.1' already exists. Skipping...
Folder 'GCA_033460325.1_PDT001748545.1' already exists. Skipping...
Folder 'GCA_033460345.1_PDT001748546.1' already exists. Skipping...
Folder 'GCA_033460365.1_PDT001748544.1' already exists. Skipping...
Folder 'GCA_033460385.1_PDT001748541.1' already exists. Skipping...
Folder 'GCA_033460405.1_PDT001748543.1' already exists. Skipping...
Folder 'GCA_033460425.1_PDT001748540.1' already exists. Skipping...
Folder 'GCA_033460445.1_PDT001748537.1' already exists. Skipping...
Folder 'GCA_033460465.1_PDT001748538.1' already exists. Skipping...
Folder 'GCA_033460525.1_PDT001748535.1' already exists. Skipping...
Folder 'GCA_033460545.1_PDT001748533.1' already exists. Skipping...
Folder 'GCA_033460565.1_PDT001748534.1' already exists. Skipping...
Folder 'GCA_033460585.1_PDT001748532.1' already exists. Skipping...
Folder 'GCA_033460625.1_PDT001748530.1' already exists. Skipping...
Folder 'GCA_033460665.1_PDT001748528.1' already exists. Skipping...
Folder 'GCA_033460845.1_PDT001748526.1' already exists. Skipping...
Folder 'GCA_033460885.1_PDT001748525.1' already exists. Skipping...
Folder 'GCA_033460905.1_PDT001748523.1' already exists. Skipping...
Folder 'GCA_033460925.1_PDT001748522.1' already exists. Skipping...
Folder 'GCA_033460965.1_PDT001748521.1' already exists. Skipping...
Folder 'GCA_033461005.1_PDT001748518.1' already exists. Skipping...
Folder 'GCA_033461065.1_PDT001748514.1' already exists. Skipping...
Folder 'GCA_033461085.1_PDT001748515.1' already exists. Skipping...
Folder 'GCA_033461105.1_PDT001748513.1' already exists. Skipping...
Folder 'GCA_033461145.1_PDT001748511.1' already exists. Skipping...
Folder 'GCA_033461185.1_PDT001748509.1' already exists. Skipping...
Folder 'GCA_033461205.1_PDT001748508.1' already exists. Skipping...
Folder 'GCA_033461245.1_PDT001748506.1' already exists. Skipping...
Folder 'GCA_033461265.1_PDT001748505.1' already exists. Skipping...
Folder 'GCA_033461305.1_PDT001748504.1' already exists. Skipping...
Folder 'GCA_033461325.1_PDT001748502.1' already exists. Skipping...
Folder 'GCA_033461345.1_PDT001748499.1' already exists. Skipping...
Folder 'GCA_033461405.1_PDT001748498.1' already exists. Skipping...
Folder 'GCA_033461425.1_PDT001748497.1' already exists. Skipping...
Folder 'GCA_033461445.1_PDT001748495.1' already exists. Skipping...
Folder 'GCA_033461485.1_PDT001748494.1' already exists. Skipping...
Folder 'GCA_033461505.1_PDT001748493.1' already exists. Skipping...
Folder 'GCA_033461545.1_PDT001748490.1' already exists. Skipping...
Folder 'GCA_033461565.1_PDT001748491.1' already exists. Skipping...
Folder 'GCA_033461585.1_PDT001748489.1' already exists. Skipping...
Folder 'GCA_033461625.1_PDT001748487.1' already exists. Skipping...
Folder 'GCA_033461645.1_PDT001748485.1' already exists. Skipping...
Folder 'GCA_033461875.1_PDT001748483.1' already exists. Skipping...
Folder 'GCA_033461895.1_PDT001748482.1' already exists. Skipping...
Folder 'GCA_033461915.1_PDT001748481.1' already exists. Skipping...
Folder 'GCA_033461925.1_PDT001748480.1' already exists. Skipping...
Folder 'GCA_033461985.1_PDT001748478.1' already exists. Skipping...
Folder 'GCA_033462045.1_PDT001748477.1' already exists. Skipping...
Folder 'GCA_033462065.1_PDT001748473.1' already exists. Skipping...
Folder 'GCA_033462085.1_PDT001748474.1' already exists. Skipping...
Folder 'GCA_033462105.1_PDT001748470.1' already exists. Skipping...
Folder 'GCA_033462145.1_PDT001748471.1' already exists. Skipping...
Folder 'GCA_033462185.1_PDT001748468.1' already exists. Skipping...
Folder 'GCA_033462205.1_PDT001748467.1' already exists. Skipping...
Folder 'GCA_033462225.1_PDT001748465.1' already exists. Skipping...
Folder 'GCA_033462285.1_PDT001748463.1' already exists. Skipping...
Folder 'GCA_033462305.1_PDT001748462.1' already exists. Skipping...
Folder 'GCA_033462345.1_PDT001748460.1' already exists. Skipping...
Folder 'GCA_033462365.1_PDT001748459.1' already exists. Skipping...
Folder 'GCA_033462385.1_PDT001748458.1' already exists. Skipping...
Folder 'GCA_033462405.1_PDT001748457.1' already exists. Skipping...
Folder 'GCA_033462425.1_PDT001748456.1' already exists. Skipping...
Folder 'GCA_033462445.1_PDT001748455.1' already exists. Skipping...
Folder 'GCA_033462465.1_PDT001748454.1' already exists. Skipping...
Folder 'GCA_033462485.1_PDT001748452.1' already exists. Skipping...
Folder 'GCA_033462525.1_PDT001748451.1' already exists. Skipping...
Folder 'GCA_033462545.1_PDT001748447.1' already exists. Skipping...
Folder 'GCA_033462565.1_PDT001748449.1' already exists. Skipping...
Folder 'GCA_033462625.1_PDT001748443.1' already exists. Skipping...
Folder 'GCA_033462645.1_PDT001748442.1' already exists. Skipping...
Folder 'GCA_033462665.1_PDT001748441.1' already exists. Skipping...
Folder 'GCA_033463005.1_PDT001748434.1' already exists. Skipping...
Folder 'GCA_033463025.1_PDT001748437.1' already exists. Skipping...
Folder 'GCA_033463065.1_PDT001748432.1' already exists. Skipping...
Folder 'GCA_033463085.1_PDT001748433.1' already exists. Skipping...
Folder 'GCA_033463125.1_PDT001748428.1' already exists. Skipping...
Folder 'GCA_033463145.1_PDT001748429.1' already exists. Skipping...
Folder 'GCA_033463165.1_PDT001748427.1' already exists. Skipping...
Folder 'GCA_033463185.1_PDT001748426.1' already exists. Skipping...
Folder 'GCA_033463205.1_PDT001748424.1' already exists. Skipping...
Folder 'GCA_033463265.1_PDT001748421.1' already exists. Skipping...
Folder 'GCA_033463285.1_PDT001748416.1' already exists. Skipping...
Folder 'GCA_033463305.1_PDT001748417.1' already exists. Skipping...
Folder 'GCA_033463325.1_PDT001748419.1' already exists. Skipping...
Folder 'GCA_033463345.1_PDT001748414.1' already exists. Skipping...
Folder 'GCA_033463365.1_PDT001748409.1' already exists. Skipping...

Retreiveing data: 105672it [00:17, 6612.16it/s]

Folder 'GCA_033501675.1_PDT001746475.1' already exists. Skipping...
Folder 'GCA_033501695.1_PDT001746467.1' already exists. Skipping...
Folder 'GCA_033501715.1_PDT001746470.1' already exists. Skipping...
Folder 'GCA_033501735.1_PDT001746460.1' already exists. Skipping...
Folder 'GCA_033501755.1_PDT001746465.1' already exists. Skipping...
Folder 'GCA_033501775.1_PDT001746462.1' already exists. Skipping...
Folder 'GCA_033501795.1_PDT001746457.1' already exists. Skipping...
Folder 'GCA_033501815.1_PDT001746459.1' already exists. Skipping...
Folder 'GCA_033501835.1_PDT001746455.1' already exists. Skipping...
Folder 'GCA_033501855.1_PDT001746452.1' already exists. Skipping...
Folder 'GCA_033501875.1_PDT001742375.1' already exists. Skipping...
Folder 'GCA_033501915.1_PDT001742373.1' already exists. Skipping...
Folder 'GCA_033501935.1_PDT001742372.1' already exists. Skipping...
Folder 'GCA_033502375.1_PDT001742289.1' already exists. Skipping...
Folder 'GCA_033502435.1_PDT001742284.1' already exists. Skipping...
Folder 'GCA_033502455.1_PDT001742281.1' already exists. Skipping...
Folder 'GCA_033502495.1_PDT001742280.1' already exists. Skipping...
Folder 'GCA_033502515.1_PDT001742262.1' already exists. Skipping...
Folder 'GCA_033502575.1_PDT001742263.1' already exists. Skipping...
Folder 'GCA_033502615.1_PDT001742259.1' already exists. Skipping...
Folder 'GCA_033502635.1_PDT001742260.1' already exists. Skipping...
Folder 'GCA_033502695.1_PDT001742258.1' already exists. Skipping...
Folder 'GCA_033502735.1_PDT001742247.1' already exists. Skipping...
Folder 'GCA_033502755.1_PDT001742245.1' already exists. Skipping...
Folder 'GCA_033502795.1_PDT001742242.1' already exists. Skipping...
Folder 'GCA_033502835.1_PDT001742240.1' already exists. Skipping...
Folder 'GCA_033502855.1_PDT001742239.1' already exists. Skipping...
Folder 'GCA_033502895.1_PDT001742238.1' already exists. Skipping...
Folder 'GCA_033502915.1_PDT001742237.1' already exists. Skipping...
Folder 'GCA_033503555.1_PDT001742196.1' already exists. Skipping...
Folder 'GCA_033503615.1_PDT001742195.1' already exists. Skipping...
Folder 'GCA_033503635.1_PDT001742194.1' already exists. Skipping...
Folder 'GCA_033503655.1_PDT001742193.1' already exists. Skipping...
Folder 'GCA_033504395.1_PDT001742153.1' already exists. Skipping...
Folder 'GCA_033504415.1_PDT001742152.1' already exists. Skipping...
Folder 'GCA_033504435.1_PDT001742151.1' already exists. Skipping...
Folder 'GCA_033505015.1_PDT001741853.1' already exists. Skipping...
Folder 'GCA_033505035.1_PDT001741854.1' already exists. Skipping...
Folder 'GCA_033505055.1_PDT001741851.1' already exists. Skipping...
Folder 'GCA_033505075.1_PDT001741852.1' already exists. Skipping...
Folder 'GCA_033505095.1_PDT001741850.1' already exists. Skipping...
Folder 'GCA_033505115.1_PDT001741849.1' already exists. Skipping...
Folder 'GCA_033505175.1_PDT001741840.1' already exists. Skipping...
Folder 'GCA_033505195.1_PDT001741835.1' already exists. Skipping...
Folder 'GCA_033505215.1_PDT001741826.1' already exists. Skipping...
Folder 'GCA_033505235.1_PDT001741829.1' already exists. Skipping...
Folder 'GCA_033505255.1_PDT001741827.1' already exists. Skipping...
Folder 'GCA_033505275.1_PDT001741825.1' already exists. Skipping...
Folder 'GCA_033505295.1_PDT001741824.1' already exists. Skipping...
Folder 'GCA_033505315.1_PDT001741823.1' already exists. Skipping...
Folder 'GCA_033505335.1_PDT001741822.1' already exists. Skipping...
Folder 'GCA_033505375.1_PDT001741818.1' already exists. Skipping...
Folder 'GCA_033505395.1_PDT001741815.1' already exists. Skipping...
Folder 'GCA_033505415.1_PDT001741816.1' already exists. Skipping...
Folder 'GCA_033505435.1_PDT001741803.1' already exists. Skipping...
Folder 'GCA_033505455.1_PDT001741810.1' already exists. Skipping...
Folder 'GCA_033505475.1_PDT001741790.1' already exists. Skipping...
Folder 'GCA_033505495.1_PDT001741778.1' already exists. Skipping...
Folder 'GCA_033505535.1_PDT001741775.1' already exists. Skipping...
Folder 'GCA_033505555.1_PDT001741768.1' already exists. Skipping...
Folder 'GCA_033505575.1_PDT001741759.1' already exists. Skipping...
Folder 'GCA_033505585.1_PDT001741755.1' already exists. Skipping...
Folder 'GCA_033505615.1_PDT001741754.1' already exists. Skipping...
Folder 'GCA_033505635.1_PDT001741751.1' already exists. Skipping...
Folder 'GCA_033505655.1_PDT001741747.1' already exists. Skipping...
Folder 'GCA_033505675.1_PDT001741742.1' already exists. Skipping...
Folder 'GCA_033505695.1_PDT001741740.1' already exists. Skipping...
Folder 'GCA_033505715.1_PDT001741744.1' already exists. Skipping...
Folder 'GCA_033505755.1_PDT001741731.1' already exists. Skipping...
Folder 'GCA_033505775.1_PDT001741728.1' already exists. Skipping...
Folder 'GCA_033505795.1_PDT001741724.1' already exists. Skipping...
Folder 'GCA_033505815.1_PDT001741718.1' already exists. Skipping...
Folder 'GCA_033505835.1_PDT001741716.1' already exists. Skipping...
Folder 'GCA_033505875.1_PDT001741715.1' already exists. Skipping...
Folder 'GCA_033505915.1_PDT001741710.1' already exists. Skipping...
Folder 'GCA_033505935.1_PDT001741707.1' already exists. Skipping...
Folder 'GCA_033505955.1_PDT001741703.1' already exists. Skipping...
Folder 'GCA_033506015.1_PDT001741692.1' already exists. Skipping...
Folder 'GCA_033506055.1_PDT001741684.1' already exists. Skipping...
Folder 'GCA_033506095.1_PDT001741691.1' already exists. Skipping...
Folder 'GCA_033506215.1_PDT001741632.1' already exists. Skipping...
Folder 'GCA_033506235.1_PDT001741629.1' already exists. Skipping...
Folder 'GCA_033506275.1_PDT001741672.1' already exists. Skipping...
Folder 'GCA_033506355.1_PDT001741641.1' already exists. Skipping...
Folder 'GCA_033506375.1_PDT001741652.1' already exists. Skipping...
Folder 'GCA_033506475.1_PDT001741635.1' already exists. Skipping...
Folder 'GCA_033506495.1_PDT001741627.1' already exists. Skipping...
Folder 'GCA_033506505.1_PDT001741633.1' already exists. Skipping...
Folder 'GCA_033506535.1_PDT001741628.1' already exists. Skipping...
Folder 'GCA_033506575.1_PDT001741620.1' already exists. Skipping...
Folder 'GCA_033506595.1_PDT001741615.1' already exists. Skipping...
Folder 'GCA_033506655.1_PDT001741609.1' already exists. Skipping...
Folder 'GCA_033506695.1_PDT001741608.1' already exists. Skipping...
Folder 'GCA_033506735.1_PDT001741605.1' already exists. Skipping...
Folder 'GCA_033506755.1_PDT001741603.1' already exists. Skipping...
Folder 'GCA_033506795.1_PDT001741602.1' already exists. Skipping...
Folder 'GCA_033506815.1_PDT001741600.1' already exists. Skipping...
Folder 'GCA_033506835.1_PDT001741599.1' already exists. Skipping...
Folder 'GCA_033506855.1_PDT001741598.1' already exists. Skipping...
Folder 'GCA_033506895.1_PDT001741597.1' already exists. Skipping...
Folder 'GCA_033506955.1_PDT001741580.1' already exists. Skipping...
Folder 'GCA_033506995.1_PDT001741579.1' already exists. Skipping...
Folder 'GCA_033507015.1_PDT001741578.1' already exists. Skipping...
Folder 'GCA_033507095.1_PDT001741542.1' already exists. Skipping...
Folder 'GCA_033507115.1_PDT001741544.1' already exists. Skipping...
Folder 'GCA_033507195.1_PDT001741533.1' already exists. Skipping...
Folder 'GCA_033507215.1_PDT001741534.1' already exists. Skipping...
Folder 'GCA_033507255.1_PDT001741531.1' already exists. Skipping...
Folder 'GCA_033507295.1_PDT001741529.1' already exists. Skipping...
Folder 'GCA_033507315.1_PDT001741527.1' already exists. Skipping...
Folder 'GCA_033507355.1_PDT001741521.1' already exists. Skipping...
Folder 'GCA_033507375.1_PDT001741524.1' already exists. Skipping...
Folder 'GCA_033507395.1_PDT001741519.1' already exists. Skipping...
Folder 'GCA_033507415.1_PDT001741516.1' already exists. Skipping...
Folder 'GCA_033507475.1_PDT001741510.1' already exists. Skipping...
Folder 'GCA_033507495.1_PDT001741506.1' already exists. Skipping...
Folder 'GCA_033507515.1_PDT001741505.1' already exists. Skipping...
Folder 'GCA_033507535.1_PDT001741504.1' already exists. Skipping...
Folder 'GCA_033507595.1_PDT001741495.1' already exists. Skipping...
Folder 'GCA_033507635.1_PDT001741491.1' already exists. Skipping...
Folder 'GCA_033507715.1_PDT001741488.1' already exists. Skipping...
Folder 'GCA_033507775.1_PDT001741487.1' already exists. Skipping...
Folder 'GCA_033507955.1_PDT001741003.1' already exists. Skipping...
Folder 'GCA_033507975.1_PDT001741004.1' already exists. Skipping...
Folder 'GCA_033508055.1_PDT001740999.1' already exists. Skipping...
Folder 'GCA_033508135.1_PDT001740994.1' already exists. Skipping...
Folder 'GCA_033508235.1_PDT001740989.1' already exists. Skipping...
Folder 'GCA_033508315.1_PDT001740985.1' already exists. Skipping...
Folder 'GCA_033508335.1_PDT001740986.1' already exists. Skipping...
Folder 'GCA_033508355.1_PDT001740984.1' already exists. Skipping...
Folder 'GCA_033508375.1_PDT001740982.1' already exists. Skipping...
Folder 'GCA_033508415.1_PDT001740980.1' already exists. Skipping...
Folder 'GCA_033508455.1_PDT001740981.1' already exists. Skipping...
Folder 'GCA_033508615.1_PDT001740972.1' already exists. Skipping...
Folder 'GCA_033510195.1_PDT001740871.1' already exists. Skipping...
Folder 'GCA_033510275.1_PDT001740870.1' already exists. Skipping...
Folder 'GCA_033510555.1_PDT001740849.1' already exists. Skipping...
Folder 'GCA_033510595.1_PDT001740848.1' already exists. Skipping...
Folder 'GCA_033510605.1_PDT001740850.1' already exists. Skipping...
Folder 'GCA_033510635.1_PDT001740847.1' already exists. Skipping...
Folder 'GCA_033510655.1_PDT001740845.1' already exists. Skipping...
Folder 'GCA_033510675.1_PDT001740846.1' already exists. Skipping...
Folder 'GCA_033510695.1_PDT001740844.1' already exists. Skipping...
Folder 'GCA_033510715.1_PDT001740842.1' already exists. Skipping...
Folder 'GCA_033510735.1_PDT001740843.1' already exists. Skipping...
Folder 'GCA_033510755.1_PDT001740840.1' already exists. Skipping...
Folder 'GCA_033510775.1_PDT001740841.1' already exists. Skipping...
Folder 'GCA_033510795.1_PDT001740839.1' already exists. Skipping...
Folder 'GCA_033510815.1_PDT001740837.1' already exists. Skipping...
Folder 'GCA_033510835.1_PDT001740838.1' already exists. Skipping...
Folder 'GCA_033510855.1_PDT001740836.1' already exists. Skipping...
Folder 'GCA_033510875.1_PDT001740835.1' already exists. Skipping...
Folder 'GCA_033510915.1_PDT001740833.1' already exists. Skipping...
Folder 'GCA_033510935.1_PDT001740832.1' already exists. Skipping...
Folder 'GCA_033510975.1_PDT001740829.1' already exists. Skipping...
Folder 'GCA_033510995.1_PDT001740827.1' already exists. Skipping...
Folder 'GCA_033511015.1_PDT001740826.1' already exists. Skipping...
Folder 'GCA_033511035.1_PDT001740828.1' already exists. Skipping...
Folder 'GCA_033511075.1_PDT001740825.1' already exists. Skipping...
Folder 'GCA_033511095.1_PDT001740823.1' already exists. Skipping...
Folder 'GCA_033511135.1_PDT001740821.1' already exists. Skipping...
Folder 'GCA_033511155.1_PDT001740819.1' already exists. Skipping...
Folder 'GCA_033511175.1_PDT001740817.1' already exists. Skipping...
Folder 'GCA_033511195.1_PDT001740818.1' already exists. Skipping...
Folder 'GCA_033511215.1_PDT001740816.1' already exists. Skipping...
Folder 'GCA_033511255.1_PDT001740815.1' already exists. Skipping...
Folder 'GCA_033511275.1_PDT001740813.1' already exists. Skipping...
Folder 'GCA_033511295.1_PDT001740812.1' already exists. Skipping...
Folder 'GCA_033511315.1_PDT001740811.1' already exists. Skipping...
Folder 'GCA_033511335.1_PDT001740810.1' already exists. Skipping...
Folder 'GCA_033511355.1_PDT001740808.1' already exists. Skipping...
Folder 'GCA_033511375.1_PDT001740806.1' already exists. Skipping...
Folder 'GCA_033511415.1_PDT001740807.1' already exists. Skipping...
Folder 'GCA_033511435.1_PDT001740805.1' already exists. Skipping...
Folder 'GCA_033511475.1_PDT001740802.1' already exists. Skipping...
Folder 'GCA_033511495.1_PDT001740803.1' already exists. Skipping...
Folder 'GCA_033511515.1_PDT001740801.1' already exists. Skipping...
Folder 'GCA_033511535.1_PDT001740800.1' already exists. Skipping...
Folder 'GCA_033511555.1_PDT001740798.1' already exists. Skipping...
Folder 'GCA_033511575.1_PDT001740797.1' already exists. Skipping...
Folder 'GCA_033511595.1_PDT001740795.1' already exists. Skipping...
Folder 'GCA_033511615.1_PDT001740794.1' already exists. Skipping...
Folder 'GCA_033511635.1_PDT001740796.1' already exists. Skipping...
Folder 'GCA_033511655.1_PDT001740793.1' already exists. Skipping...
Folder 'GCA_033511675.1_PDT001740792.1' already exists. Skipping...
Folder 'GCA_033511695.1_PDT001740791.1' already exists. Skipping...
Folder 'GCA_033511715.1_PDT001740789.1' already exists. Skipping...
Folder 'GCA_033511735.1_PDT001740790.1' already exists. Skipping...
Folder 'GCA_033511755.1_PDT001740787.1' already exists. Skipping...
Folder 'GCA_033511775.1_PDT001740786.1' already exists. Skipping...
Folder 'GCA_033511795.1_PDT001740785.1' already exists. Skipping...
Folder 'GCA_033511815.1_PDT001740784.1' already exists. Skipping...
Folder 'GCA_033511835.1_PDT001740783.1' already exists. Skipping...
Folder 'GCA_033511855.1_PDT001740782.1' already exists. Skipping...
Folder 'GCA_033511875.1_PDT001740780.1' already exists. Skipping...
Folder 'GCA_033511895.1_PDT001740781.1' already exists. Skipping...
Folder 'GCA_033511915.1_PDT001740778.1' already exists. Skipping...
Folder 'GCA_033511935.1_PDT001740779.1' already exists. Skipping...
Folder 'GCA_033511955.1_PDT001740776.1' already exists. Skipping...
Folder 'GCA_033511975.1_PDT001740775.1' already exists. Skipping...
Folder 'GCA_033511995.1_PDT001740774.1' already exists. Skipping...
Folder 'GCA_033512015.1_PDT001740772.1' already exists. Skipping...
Folder 'GCA_033512035.1_PDT001740773.1' already exists. Skipping...
Folder 'GCA_033512055.1_PDT001740771.1' already exists. Skipping...
Folder 'GCA_033512075.1_PDT001740770.1' already exists. Skipping...
Folder 'GCA_033512095.1_PDT001740768.1' already exists. Skipping...
Folder 'GCA_033512115.1_PDT001740767.1' already exists. Skipping...
Folder 'GCA_033512135.1_PDT001740765.1' already exists. Skipping...
Folder 'GCA_033512155.1_PDT001740763.1' already exists. Skipping...
Folder 'GCA_033512175.1_PDT001740761.1' already exists. Skipping...
Folder 'GCA_033512195.1_PDT001740764.1' already exists. Skipping...
Folder 'GCA_033512215.1_PDT001740762.1' already exists. Skipping...
Folder 'GCA_033512235.1_PDT001740760.1' already exists. Skipping...
Folder 'GCA_033512255.1_PDT001740758.1' already exists. Skipping...
Folder 'GCA_033512295.1_PDT001740757.1' already exists. Skipping...
Folder 'GCA_033512335.1_PDT001740754.1' already exists. Skipping...
Folder 'GCA_033512355.1_PDT001740752.1' already exists. Skipping...
Folder 'GCA_033512375.1_PDT001740751.1' already exists. Skipping...
Folder 'GCA_033512415.1_PDT001740750.1' already exists. Skipping...
Folder 'GCA_033512435.1_PDT001740749.1' already exists. Skipping...
Folder 'GCA_033512455.1_PDT001740748.1' already exists. Skipping...
Folder 'GCA_033512475.1_PDT001740746.1' already exists. Skipping...
Folder 'GCA_033512535.1_PDT001740743.1' already exists. Skipping...
Folder 'GCA_033512555.1_PDT001740742.1' already exists. Skipping...
Folder 'GCA_033512595.1_PDT001740741.1' already exists. Skipping...
Folder 'GCA_033512615.1_PDT001740739.1' already exists. Skipping...
Folder 'GCA_033512635.1_PDT001740737.1' already exists. Skipping...
Folder 'GCA_033512655.1_PDT001740738.1' already exists. Skipping...
Folder 'GCA_033512675.1_PDT001740736.1' already exists. Skipping...
Folder 'GCA_033512695.1_PDT001740735.1' already exists. Skipping...
Folder 'GCA_033512735.1_PDT001740732.1' already exists. Skipping...
Folder 'GCA_033512755.1_PDT001740733.1' already exists. Skipping...
Folder 'GCA_033512815.1_PDT001740730.1' already exists. Skipping...
Folder 'GCA_033512835.1_PDT001740728.1' already exists. Skipping...
Folder 'GCA_033512855.1_PDT001740725.1' already exists. Skipping...
Folder 'GCA_033512875.1_PDT001740727.1' already exists. Skipping...
Folder 'GCA_033512895.1_PDT001740724.1' already exists. Skipping...
Folder 'GCA_033512915.1_PDT001740723.1' already exists. Skipping...
Folder 'GCA_033512935.1_PDT001740656.1' already exists. Skipping...
Folder 'GCA_033512955.1_PDT001740654.1' already exists. Skipping...
Folder 'GCA_033512995.1_PDT001740657.1' already exists. Skipping...
Folder 'GCA_033513015.1_PDT001740722.1' already exists. Skipping...
Folder 'GCA_033513035.1_PDT001740652.1' already exists. Skipping...
Folder 'GCA_033513055.1_PDT001740651.1' already exists. Skipping...
Folder 'GCA_033513075.1_PDT001740653.1' already exists. Skipping...
Folder 'GCA_033513095.1_PDT001740650.1' already exists. Skipping...
Folder 'GCA_033513115.1_PDT001740649.1' already exists. Skipping...
Folder 'GCA_033513135.1_PDT001740646.1' already exists. Skipping...
Folder 'GCA_033513175.1_PDT001740645.1' already exists. Skipping...
Folder 'GCA_033513195.1_PDT001740644.1' already exists. Skipping...
Folder 'GCA_033513275.1_PDT001740640.1' already exists. Skipping...
Folder 'GCA_033513295.1_PDT001740639.1' already exists. Skipping...
Folder 'GCA_033513335.1_PDT001740638.1' already exists. Skipping...
Folder 'GCA_033513755.1_PDT001740133.1' already exists. Skipping...
Folder 'GCA_033515935.1_PDT001739997.1' already exists. Skipping...
Folder 'GCA_033515975.1_PDT001739996.1' already exists. Skipping...
Folder 'GCA_033516135.1_PDT001739951.1' already exists. Skipping...
Folder 'GCA_033516235.1_PDT001739948.1' already exists. Skipping...
Folder 'GCA_033517195.1_PDT001739947.1' already exists. Skipping...
Folder 'GCA_033517215.1_PDT001739945.1' already exists. Skipping...
Folder 'GCA_033536815.1_PDT001739943.1' already exists. Skipping...
Folder 'GCA_033537735.1_PDT001739829.1' already exists. Skipping...
Folder 'GCA_033538175.1_PDT001739789.1' already exists. Skipping...
Folder 'GCA_033538195.1_PDT001739787.1' already exists. Skipping...
Folder 'GCA_033538215.1_PDT001739786.1' already exists. Skipping...
Folder 'GCA_033538235.1_PDT001739785.1' already exists. Skipping...
Folder 'GCA_033538255.1_PDT001739783.1' already exists. Skipping...
Folder 'GCA_033538275.1_PDT001739784.1' already exists. Skipping...
Folder 'GCA_033564415.1_PDT001740120.1' already exists. Skipping...
Folder 'GCA_033566075.1_PDT001746942.1' already exists. Skipping...
Folder 'GCA_033569355.1_PDT001739575.1' already exists. Skipping...
Folder 'GCA_033569395.1_PDT001739574.1' already exists. Skipping...
Folder 'GCA_033569415.1_PDT001739573.1' already exists. Skipping...
Folder 'GCA_033569455.1_PDT001739572.1' already exists. Skipping...
Folder 'GCA_033569475.1_PDT001739571.1' already exists. Skipping...
Folder 'GCA_033569495.1_PDT001739569.1' already exists. Skipping...
Folder 'GCA_033569515.1_PDT001739570.1' already exists. Skipping...
Folder 'GCA_033569535.1_PDT001739568.1' already exists. Skipping...
Folder 'GCA_033569555.1_PDT001739567.1' already exists. Skipping...
Folder 'GCA_033569575.1_PDT001739566.1' already exists. Skipping...
Folder 'GCA_033569595.1_PDT001739565.1' already exists. Skipping...
Folder 'GCA_033569615.1_PDT001739564.1' already exists. Skipping...
Folder 'GCA_033569635.1_PDT001739562.1' already exists. Skipping...
Folder 'GCA_033569655.1_PDT001739563.1' already exists. Skipping...
Folder 'GCA_033569675.1_PDT001739560.1' already exists. Skipping...
Folder 'GCA_033569695.1_PDT001739561.1' already exists. Skipping...
Folder 'GCA_033569715.1_PDT001739559.1' already exists. Skipping...
Folder 'GCA_033569735.1_PDT001739558.1' already exists. Skipping...
Folder 'GCA_033569755.1_PDT001739557.1' already exists. Skipping...
Folder 'GCA_033569775.1_PDT001739556.1' already exists. Skipping...
Folder 'GCA_033569795.1_PDT001739555.1' already exists. Skipping...
Folder 'GCA_033569815.1_PDT001739553.1' already exists. Skipping...
Folder 'GCA_033569835.1_PDT001739554.1' already exists. Skipping...
Folder 'GCA_033569855.1_PDT001739552.1' already exists. Skipping...

Retreiveing data: 107002it [00:17, 6621.78it/s]

Folder 'GCA_033636065.1_PDT001730272.1' already exists. Skipping...
Folder 'GCA_033636085.1_PDT001730271.1' already exists. Skipping...
Folder 'GCA_033636245.1_PDT001730263.1' already exists. Skipping...
Folder 'GCA_033636305.1_PDT001730259.1' already exists. Skipping...
Folder 'GCA_033636365.1_PDT001730257.1' already exists. Skipping...
Folder 'GCA_033636425.1_PDT001730255.1' already exists. Skipping...
Folder 'GCA_033636465.1_PDT001730251.1' already exists. Skipping...
Folder 'GCA_033636545.1_PDT001730244.1' already exists. Skipping...
Folder 'GCA_033636565.1_PDT001730241.1' already exists. Skipping...
Folder 'GCA_033636585.1_PDT001730245.1' already exists. Skipping...
Folder 'GCA_033636605.1_PDT001730240.1' already exists. Skipping...
Folder 'GCA_033636645.1_PDT001730237.1' already exists. Skipping...
Folder 'GCA_033636665.1_PDT001730235.1' already exists. Skipping...
Folder 'GCA_033636765.1_PDT001730231.1' already exists. Skipping...
Folder 'GCA_033637005.1_PDT001730216.1' already exists. Skipping...
Folder 'GCA_033637105.1_PDT001730212.1' already exists. Skipping...
Folder 'GCA_033637375.1_PDT001730196.1' already exists. Skipping...
Folder 'GCA_033637405.1_PDT001730194.1' already exists. Skipping...
Folder 'GCA_033637445.1_PDT001730195.1' already exists. Skipping...
Folder 'GCA_033637585.1_PDT001730186.1' already exists. Skipping...
Folder 'GCA_033637645.1_PDT001730183.1' already exists. Skipping...
Folder 'GCA_033637665.1_PDT001730182.1' already exists. Skipping...
Folder 'GCA_033643365.1_PDT001729761.1' already exists. Skipping...
Folder 'GCA_033646705.1_PDT001984502.1' already exists. Skipping...
Folder 'GCA_033646745.1_PDT001984499.1' already exists. Skipping...
Folder 'GCA_033646765.1_PDT001984496.1' already exists. Skipping...
Folder 'GCA_033646785.1_PDT001984493.1' already exists. Skipping...
Folder 'GCA_033646845.1_PDT001984435.1' already exists. Skipping...
Folder 'GCA_033647685.1_PDT001984494.1' already exists. Skipping...
Folder 'GCA_033647725.1_PDT001984449.1' already exists. Skipping...
Folder 'GCA_033648165.1_PDT001729493.1' already exists. Skipping...
Folder 'GCA_033648225.1_PDT001729492.1' already exists. Skipping...
Folder 'GCA_033648245.1_PDT001729491.1' already exists. Skipping...
Folder 'GCA_033648265.1_PDT001729490.1' already exists. Skipping...
Folder 'GCA_033648685.1_PDT001984491.1' already exists. Skipping...
Folder 'GCA_033649805.1_PDT001984487.1' already exists. Skipping...
Folder 'GCA_033650105.1_PDT001984437.1' already exists. Skipping...
Folder 'GCA_033650905.1_PDT001984500.1' already exists. Skipping...
Folder 'GCA_033650925.1_PDT001984498.1' already exists. Skipping...
Folder 'GCA_033650945.1_PDT001984497.1' already exists. Skipping...
Folder 'GCA_033651325.1_PDT001984433.1' already exists. Skipping...
Folder 'GCA_033655685.1_PDT001984798.1' already exists. Skipping...
Folder 'GCA_033655705.1_PDT001984797.1' already exists. Skipping...
Folder 'GCA_033656085.1_PDT001984492.1' already exists. Skipping...
Folder 'GCA_033656105.1_PDT001984489.1' already exists. Skipping...
Folder 'GCA_033657945.1_PDT001729157.1' already exists. Skipping...
Folder 'GCA_033658045.1_PDT001984799.1' already exists. Skipping...
Folder 'GCA_033660675.1_PDT001729124.1' already exists. Skipping...
Folder 'GCA_033660715.1_PDT001729114.1' already exists. Skipping...
Folder 'GCA_033660785.1_PDT001729113.1' already exists. Skipping...
Folder 'GCA_033663985.1_PDT001984800.1' already exists. Skipping...
Folder 'GCA_033664605.1_PDT001729050.1' already exists. Skipping...
Folder 'GCA_033664645.1_PDT001729046.1' already exists. Skipping...
Folder 'GCA_033664665.1_PDT001729045.1' already exists. Skipping...
Folder 'GCA_033664905.1_PDT001728984.1' already exists. Skipping...
Folder 'GCA_033664925.1_PDT001728982.1' already exists. Skipping...
Folder 'GCA_033664935.1_PDT001728983.1' already exists. Skipping...
Folder 'GCA_033664985.1_PDT001728980.1' already exists. Skipping...
Folder 'GCA_033665005.1_PDT001728981.1' already exists. Skipping...
Folder 'GCA_033665025.1_PDT001728978.1' already exists. Skipping...
Folder 'GCA_033666865.1_PDT001728877.1' already exists. Skipping...
Folder 'GCA_033667085.1_PDT001728865.1' already exists. Skipping...
Folder 'GCA_033667685.1_PDT001728774.1' already exists. Skipping...
Folder 'GCA_033667705.1_PDT001728773.1' already exists. Skipping...
Folder 'GCA_033667745.1_PDT001728771.1' already exists. Skipping...
Folder 'GCA_033667775.1_PDT001728769.1' already exists. Skipping...
Folder 'GCA_033667805.1_PDT001728770.1' already exists. Skipping...
Folder 'GCA_033667825.1_PDT001728766.1' already exists. Skipping...
Folder 'GCA_033667845.1_PDT001728768.1' already exists. Skipping...
Folder 'GCA_033667865.1_PDT001728767.1' already exists. Skipping...
Folder 'GCA_033667885.1_PDT001728765.1' already exists. Skipping...
Folder 'GCA_033667905.1_PDT001728764.1' already exists. Skipping...
Folder 'GCA_033668005.1_PDT001728754.1' already exists. Skipping...
Folder 'GCA_033668045.1_PDT001728757.1' already exists. Skipping...
Folder 'GCA_033668065.1_PDT001728753.1' already exists. Skipping...
Folder 'GCA_033669085.1_PDT001728604.1' already exists. Skipping...
Folder 'GCA_033669105.1_PDT001728601.1' already exists. Skipping...
Folder 'GCA_033669185.1_PDT001728596.1' already exists. Skipping...
Folder 'GCA_033669205.1_PDT001728597.1' already exists. Skipping...
Folder 'GCA_033671325.1_PDT001728350.1' already exists. Skipping...
Folder 'GCA_033671365.1_PDT001728349.1' already exists. Skipping...
Folder 'GCA_033674565.1_PDT001728101.1' already exists. Skipping...
Folder 'GCA_033674605.1_PDT001728100.1' already exists. Skipping...
Folder 'GCA_033674625.1_PDT001728098.1' already exists. Skipping...
Folder 'GCA_033674635.1_PDT001728099.1' already exists. Skipping...
Folder 'GCA_033674785.1_PDT001728084.1' already exists. Skipping...
Folder 'GCA_033676785.1_PDT001984834.1' already exists. Skipping...
Folder 'GCA_033679025.1_PDT001728000.1' already exists. Skipping...
Folder 'GCA_033679065.1_PDT001727998.1' already exists. Skipping...
Folder 'GCA_033679085.1_PDT001727997.1' already exists. Skipping...
Folder 'GCA_033679125.1_PDT001727995.1' already exists. Skipping...
Folder 'GCA_033679145.1_PDT001727994.1' already exists. Skipping...
Folder 'GCA_033679385.1_PDT001727982.1' already exists. Skipping...
Folder 'GCA_033679425.1_PDT001727979.1' already exists. Skipping...
Folder 'GCA_033680365.1_PDT001727908.1' already exists. Skipping...
Folder 'GCA_033680465.1_PDT001727907.1' already exists. Skipping...
Folder 'GCA_033680485.1_PDT001727906.1' already exists. Skipping...
Folder 'GCA_033680865.1_PDT001727886.1' already exists. Skipping...
Folder 'GCA_033680965.1_PDT001727884.1' already exists. Skipping...
Folder 'GCA_033681065.1_PDT001727875.1' already exists. Skipping...
Folder 'GCA_033681085.1_PDT001727874.1' already exists. Skipping...
Folder 'GCA_033681125.1_PDT001727873.1' already exists. Skipping...
Folder 'GCA_033681265.1_PDT001727866.1' already exists. Skipping...
Folder 'GCA_033681345.1_PDT001727861.1' already exists. Skipping...
Folder 'GCA_033681385.1_PDT001727860.1' already exists. Skipping...
Folder 'GCA_033681405.1_PDT001727859.1' already exists. Skipping...
Folder 'GCA_033681425.1_PDT001727858.1' already exists. Skipping...
Folder 'GCA_033681545.1_PDT001727852.1' already exists. Skipping...
Folder 'GCA_033681565.1_PDT001727850.1' already exists. Skipping...
Folder 'GCA_033681585.1_PDT001727851.1' already exists. Skipping...
Folder 'GCA_033682765.1_PDT001727745.1' already exists. Skipping...
Folder 'GCA_033682965.1_PDT001727736.1' already exists. Skipping...
Folder 'GCA_033683025.1_PDT001727731.1' already exists. Skipping...
Folder 'GCA_033683045.1_PDT001727733.1' already exists. Skipping...
Folder 'GCA_033683105.1_PDT001727730.1' already exists. Skipping...
Folder 'GCA_033685265.1_PDT001727439.1' already exists. Skipping...
Folder 'GCA_033685405.1_PDT001727431.1' already exists. Skipping...
Folder 'GCA_033686405.1_PDT001726800.1' already exists. Skipping...
Folder 'GCA_033686825.1_PDT001726780.1' already exists. Skipping...
Folder 'GCA_033686845.1_PDT001726779.1' already exists. Skipping...
Folder 'GCA_033687585.1_PDT001726754.1' already exists. Skipping...
Folder 'GCA_033689435.1_PDT001726656.1' already exists. Skipping...
Folder 'GCA_033689695.1_PDT001726640.1' already exists. Skipping...
Folder 'GCA_033689715.1_PDT001726636.1' already exists. Skipping...
Folder 'GCA_033689735.1_PDT001726637.1' already exists. Skipping...
Folder 'GCA_033689795.1_PDT001726635.1' already exists. Skipping...
Folder 'GCA_033689815.1_PDT001726633.1' already exists. Skipping...
Folder 'GCA_033689875.1_PDT001726631.1' already exists. Skipping...
Folder 'GCA_033690415.1_PDT001726604.1' already exists. Skipping...
Folder 'GCA_033690455.1_PDT001726602.1' already exists. Skipping...
Folder 'GCA_033690535.1_PDT001726598.1' already exists. Skipping...
Folder 'GCA_033690555.1_PDT001726597.1' already exists. Skipping...
Folder 'GCA_033690615.1_PDT001726595.1' already exists. Skipping...
Folder 'GCA_033690635.1_PDT001726593.1' already exists. Skipping...
Folder 'GCA_033690675.1_PDT001726590.1' already exists. Skipping...
Folder 'GCA_033690685.1_PDT001726591.1' already exists. Skipping...
Folder 'GCA_033690715.1_PDT001726588.1' already exists. Skipping...
Folder 'GCA_033690735.1_PDT001726589.1' already exists. Skipping...
Folder 'GCA_033690775.1_PDT001726586.1' already exists. Skipping...
Folder 'GCA_033691755.1_PDT001726071.1' already exists. Skipping...
Folder 'GCA_033691795.1_PDT001726068.1' already exists. Skipping...
Folder 'GCA_033691815.1_PDT001726067.1' already exists. Skipping...
Folder 'GCA_033691835.1_PDT001726066.1' already exists. Skipping...
Folder 'GCA_033691855.1_PDT001726064.1' already exists. Skipping...
Folder 'GCA_033691935.1_PDT001726061.1' already exists. Skipping...
Folder 'GCA_033691955.1_PDT001726060.1' already exists. Skipping...
Folder 'GCA_033695625.1_PDT001725740.1' already exists. Skipping...
Folder 'GCA_033699235.1_PDT001721140.1' already exists. Skipping...
Folder 'GCA_033699255.1_PDT001721132.1' already exists. Skipping...
Folder 'GCA_033699595.1_PDT001721136.1' already exists. Skipping...
Folder 'GCA_033699815.1_PDT001721124.1' already exists. Skipping...
Folder 'GCA_033700455.1_PDT001721090.1' already exists. Skipping...
Folder 'GCA_033700495.1_PDT001721087.1' already exists. Skipping...
Folder 'GCA_033700605.1_PDT001721082.1' already exists. Skipping...
Folder 'GCA_033700735.1_PDT001721072.1' already exists. Skipping...
Folder 'GCA_033700775.1_PDT001721073.1' already exists. Skipping...
Folder 'GCA_033701175.1_PDT001721052.1' already exists. Skipping...
Folder 'GCA_033701195.1_PDT001721053.1' already exists. Skipping...
Folder 'GCA_033701215.1_PDT001721049.1' already exists. Skipping...
Folder 'GCA_033701235.1_PDT001721048.1' already exists. Skipping...
Folder 'GCA_033701295.1_PDT001721045.1' already exists. Skipping...
Folder 'GCA_033704835.1_PDT001720854.1' already exists. Skipping...
Folder 'GCA_033704895.1_PDT001720853.1' already exists. Skipping...
Folder 'GCA_033705115.1_PDT001985544.1' already exists. Skipping...
Folder 'GCA_033709755.1_PDT001720364.1' already exists. Skipping...
Folder 'GCA_033709775.1_PDT001720362.1' already exists. Skipping...
Folder 'GCA_033709875.1_PDT001720354.1' already exists. Skipping...
Folder 'GCA_033709915.1_PDT001720353.1' already exists. Skipping...
Folder 'GCA_033710455.1_PDT001719851.1' already exists. Skipping...
Folder 'GCA_033710555.1_PDT001719611.1' already exists. Skipping...
Folder 'GCA_033711055.1_PDT001738580.1' already exists. Skipping...
Folder 'GCA_033724335.1_PDT001986372.1' already exists. Skipping...
Folder 'GCA_033724495.1_PDT001986370.1' already exists. Skipping...
Folder 'GCA_033724515.1_PDT001986371.1' already exists. Skipping...
Folder 'GCA_033724535.1_PDT001986369.1' already exists. Skipping...
Folder 'GCA_033724595.1_PDT001986367.1' already exists. Skipping...
Folder 'GCA_033724655.1_PDT001986357.1' already exists. Skipping...
Folder 'GCA_033724715.1_PDT001986352.1' already exists. Skipping...
Folder 'GCA_033724735.1_PDT001986354.1' already exists. Skipping...
Folder 'GCA_033724775.1_PDT001986349.1' already exists. Skipping...
Folder 'GCA_033724815.1_PDT001986347.1' already exists. Skipping...
Folder 'GCA_033724855.1_PDT001986344.1' already exists. Skipping...
Folder 'GCA_033724865.1_PDT001986342.1' already exists. Skipping...
Folder 'GCA_033724915.1_PDT001986337.1' already exists. Skipping...
Folder 'GCA_033725195.1_PDT001986335.1' already exists. Skipping...
Folder 'GCA_033727175.1_PDT001985621.1' already exists. Skipping...
Folder 'GCA_033727195.1_PDT001985622.1' already exists. Skipping...
Folder 'GCA_033727215.1_PDT001985618.1' already exists. Skipping...
Folder 'GCA_033727235.1_PDT001985620.1' already exists. Skipping...
Folder 'GCA_033727255.1_PDT001985619.1' already exists. Skipping...
Folder 'GCA_033727275.1_PDT001985617.1' already exists. Skipping...
Folder 'GCA_033727295.1_PDT001985616.1' already exists. Skipping...
Folder 'GCA_033727315.1_PDT001985615.1' already exists. Skipping...
Folder 'GCA_033727335.1_PDT001985614.1' already exists. Skipping...
Folder 'GCA_033727355.1_PDT001985613.1' already exists. Skipping...
Folder 'GCA_033727375.1_PDT001985610.1' already exists. Skipping...
Folder 'GCA_033727395.1_PDT001985611.1' already exists. Skipping...
Folder 'GCA_033727415.1_PDT001985612.1' already exists. Skipping...
Folder 'GCA_033727435.1_PDT001985609.1' already exists. Skipping...
Folder 'GCA_033727475.1_PDT001985607.1' already exists. Skipping...
Folder 'GCA_033727495.1_PDT001985605.1' already exists. Skipping...
Folder 'GCA_033727505.1_PDT001985604.1' already exists. Skipping...
Folder 'GCA_033727535.1_PDT001985606.1' already exists. Skipping...
Folder 'GCA_033727715.1_PDT001719841.1' already exists. Skipping...
Folder 'GCA_033727755.1_PDT001719839.1' already exists. Skipping...
Folder 'GCA_033727795.1_PDT001719837.1' already exists. Skipping...
Folder 'GCA_033727875.1_PDT001719832.1' already exists. Skipping...
Folder 'GCA_033727915.1_PDT001719831.1' already exists. Skipping...
Folder 'GCA_033727975.1_PDT001719610.1' already exists. Skipping...
Folder 'GCA_033728015.1_PDT001719609.1' already exists. Skipping...
Folder 'GCA_033728035.1_PDT001719607.1' already exists. Skipping...
Folder 'GCA_033728055.1_PDT001719606.1' already exists. Skipping...
Folder 'GCA_033728075.1_PDT001719608.1' already exists. Skipping...
Folder 'GCA_033728095.1_PDT001719605.1' already exists. Skipping...
Folder 'GCA_033728115.1_PDT001719604.1' already exists. Skipping...
Folder 'GCA_033728135.1_PDT001719603.1' already exists. Skipping...
Folder 'GCA_033728375.1_PDT001719569.1' already exists. Skipping...
Folder 'GCA_033728395.1_PDT001719568.1' already exists. Skipping...
Folder 'GCA_033728415.1_PDT001719567.1' already exists. Skipping...
Folder 'GCA_033728435.1_PDT001719566.1' already exists. Skipping...
Folder 'GCA_033728515.1_PDT001719562.1' already exists. Skipping...
Folder 'GCA_033728535.1_PDT001719561.1' already exists. Skipping...
Folder 'GCA_033728595.1_PDT001719558.1' already exists. Skipping...
Folder 'GCA_033731915.1_PDT001719171.1' already exists. Skipping...
Folder 'GCA_033732115.1_PDT001719165.1' already exists. Skipping...
Folder 'GCA_033732175.1_PDT001719162.1' already exists. Skipping...
Folder 'GCA_033732275.1_PDT001719156.1' already exists. Skipping...
Folder 'GCA_033732295.1_PDT001719155.1' already exists. Skipping...
Folder 'GCA_033732355.1_PDT001719154.1' already exists. Skipping...
Folder 'GCA_033732775.1_PDT001719033.1' already exists. Skipping...
Folder 'GCA_033737155.1_PDT001727412.1' already exists. Skipping...
Folder 'GCA_033737175.1_PDT001727413.1' already exists. Skipping...
Folder 'GCA_033737195.1_PDT001727411.1' already exists. Skipping...
Folder 'GCA_033737215.1_PDT001727415.1' already exists. Skipping...
Folder 'GCA_033737235.1_PDT001727410.1' already exists. Skipping...
Folder 'GCA_033737275.1_PDT001727409.1' already exists. Skipping...
Folder 'GCA_033737295.1_PDT001727407.1' already exists. Skipping...
Folder 'GCA_033737335.1_PDT001727404.1' already exists. Skipping...
Folder 'GCA_033737355.1_PDT001727403.1' already exists. Skipping...
Folder 'GCA_033737395.1_PDT001727402.1' already exists. Skipping...
Folder 'GCA_033737415.1_PDT001727401.1' already exists. Skipping...
Folder 'GCA_033737435.1_PDT001727400.1' already exists. Skipping...
Folder 'GCA_033737455.1_PDT001727399.1' already exists. Skipping...
Folder 'GCA_033737495.1_PDT001727398.1' already exists. Skipping...
Folder 'GCA_033739335.1_PDT001718486.1' already exists. Skipping...
Folder 'GCA_033739375.1_PDT001718485.1' already exists. Skipping...
Folder 'GCA_033739415.1_PDT001718484.1' already exists. Skipping...
Folder 'GCA_033739435.1_PDT001718483.1' already exists. Skipping...
Folder 'GCA_033749835.1_PDT001717896.1' already exists. Skipping...
Folder 'GCA_033749875.1_PDT001717895.1' already exists. Skipping...
Folder 'GCA_033749915.1_PDT001717894.1' already exists. Skipping...
Folder 'GCA_033749935.1_PDT001717892.1' already exists. Skipping...
Folder 'GCA_033749975.1_PDT001717890.1' already exists. Skipping...
Folder 'GCA_033749995.1_PDT001717889.1' already exists. Skipping...
Folder 'GCA_033750015.1_PDT001717888.1' already exists. Skipping...
Folder 'GCA_033750035.1_PDT001717887.1' already exists. Skipping...
Folder 'GCA_033750095.1_PDT001717884.1' already exists. Skipping...
Folder 'GCA_033750115.1_PDT001717883.1' already exists. Skipping...
Folder 'GCA_033751415.1_PDT001717604.1' already exists. Skipping...
Folder 'GCA_033751435.1_PDT001717603.1' already exists. Skipping...
Folder 'GCA_033751455.1_PDT001717602.1' already exists. Skipping...
Folder 'GCA_033751475.1_PDT001717601.1' already exists. Skipping...
Folder 'GCA_033751495.1_PDT001717600.1' already exists. Skipping...
Folder 'GCA_033751515.1_PDT001717598.1' already exists. Skipping...
Folder 'GCA_033751535.1_PDT001717599.1' already exists. Skipping...
Folder 'GCA_033751555.1_PDT001717597.1' already exists. Skipping...
Folder 'GCA_033751575.1_PDT001717595.1' already exists. Skipping...
Folder 'GCA_033751615.1_PDT001717594.1' already exists. Skipping...
Folder 'GCA_033751635.1_PDT001717592.1' already exists. Skipping...
Folder 'GCA_033751655.1_PDT001717593.1' already exists. Skipping...
Folder 'GCA_033751675.1_PDT001717591.1' already exists. Skipping...
Folder 'GCA_033758155.1_PDT001717254.1' already exists. Skipping...
Folder 'GCA_033758175.1_PDT001717253.1' already exists. Skipping...
Folder 'GCA_033758955.1_PDT001717192.1' already exists. Skipping...
Folder 'GCA_033759755.1_PDT001717126.1' already exists. Skipping...
Folder 'GCA_033760495.1_PDT001717062.1' already exists. Skipping...
Folder 'GCA_033760895.1_PDT001717042.1' already exists. Skipping...
Folder 'GCA_033761095.1_PDT001717032.1' already exists. Skipping...
Folder 'GCA_033765195.1_PDT001716900.1' already exists. Skipping...
Folder 'GCA_033765265.1_PDT001716897.1' already exists. Skipping...
Folder 'GCA_033765405.1_PDT001716895.1' already exists. Skipping...
Folder 'GCA_033765475.1_PDT001716891.1' already exists. Skipping...
Folder 'GCA_033765495.1_PDT001716887.1' already exists. Skipping...
Folder 'GCA_033766535.1_PDT001716705.1' already exists. Skipping...
Folder 'GCA_033768755.1_PDT001716307.1' already exists. Skipping...
Folder 'GCA_033768815.1_PDT001716303.1' already exists. Skipping...
Folder 'GCA_033768835.1_PDT001716304.1' already exists. Skipping...
Folder 'GCA_033768855.1_PDT001716302.1' already exists. Skipping...
Folder 'GCA_033768875.1_PDT001716300.1' already exists. Skipping...
Folder 'GCA_033768955.1_PDT001716297.1' already exists. Skipping...
Folder 'GCA_033768975.1_PDT001716295.1' already exists. Skipping...
Folder 'GCA_033769375.1_PDT001716274.1' already exists. Skipping...
Folder 'GCA_033769395.1_PDT001716273.1' already exists. Skipping...
Folder 'GCA_033769555.1_PDT001716241.1' already exists. Skipping...

Retreiveing data: 108339it [00:17, 6655.74it/s]

Folder 'GCA_035370925.1_PDT002049380.1' already exists. Skipping...
Folder 'GCA_035370945.1_PDT002049360.1' already exists. Skipping...
Folder 'GCA_035373325.1_PDT002049083.1' already exists. Skipping...
Folder 'GCA_035373345.1_PDT002049086.1' already exists. Skipping...
Folder 'GCA_035373425.1_PDT002049074.1' already exists. Skipping...
Folder 'GCA_035373445.1_PDT002049071.1' already exists. Skipping...
Folder 'GCA_035374205.1_PDT002049383.1' already exists. Skipping...
Folder 'GCA_035374265.1_PDT002049370.1' already exists. Skipping...
Folder 'GCA_035374385.1_PDT002049066.1' already exists. Skipping...
Folder 'GCA_035374405.1_PDT002049138.1' already exists. Skipping...
Folder 'GCA_035374465.1_PDT002049065.1' already exists. Skipping...
Folder 'GCA_035376635.1_PDT002049588.1' already exists. Skipping...
Folder 'GCA_035376665.1_PDT002049055.1' already exists. Skipping...
Folder 'GCA_035376725.1_PDT002049140.1' already exists. Skipping...
Folder 'GCA_035383845.1_PDT002049080.1' already exists. Skipping...
Folder 'GCA_035422545.1_PDT002049379.1' already exists. Skipping...
Folder 'GCA_035422985.1_PDT002049203.1' already exists. Skipping...
Folder 'GCA_035423045.1_PDT002049202.1' already exists. Skipping...
Folder 'GCA_035423085.1_PDT002049201.1' already exists. Skipping...
Folder 'GCA_035423105.1_PDT002049199.1' already exists. Skipping...
Folder 'GCA_035423225.1_PDT002049188.1' already exists. Skipping...
Folder 'GCA_035423325.1_PDT002049185.1' already exists. Skipping...
Folder 'GCA_035423445.1_PDT002049182.1' already exists. Skipping...
Folder 'GCA_035423525.1_PDT002049180.1' already exists. Skipping...
Folder 'GCA_035423545.1_PDT002049179.1' already exists. Skipping...
Folder 'GCA_035423585.1_PDT002049178.1' already exists. Skipping...
Folder 'GCA_035423665.1_PDT002049175.1' already exists. Skipping...
Folder 'GCA_035423745.1_PDT002049174.1' already exists. Skipping...
Folder 'GCA_035423765.1_PDT002049173.1' already exists. Skipping...
Folder 'GCA_035423785.1_PDT002049172.1' already exists. Skipping...
Folder 'GCA_035423845.1_PDT002049171.1' already exists. Skipping...
Folder 'GCA_035423905.1_PDT002049164.1' already exists. Skipping...
Folder 'GCA_035423925.1_PDT002049157.1' already exists. Skipping...
Folder 'GCA_035423955.1_PDT002049161.1' already exists. Skipping...
Folder 'GCA_035424705.1_PDT002049153.1' already exists. Skipping...
Folder 'GCA_035424745.1_PDT002049150.1' already exists. Skipping...
Folder 'GCA_035424785.1_PDT002049149.1' already exists. Skipping...
Folder 'GCA_035428645.1_PDT002049190.1' already exists. Skipping...
Folder 'GCA_035459925.1_PDT002049139.1' already exists. Skipping...
Folder 'GCA_035467715.1_PDT002049141.1' already exists. Skipping...
Folder 'GCA_035469625.1_PDT002049082.1' already exists. Skipping...
Folder 'GCA_035469645.1_PDT002049073.1' already exists. Skipping...
Folder 'GCA_035469675.1_PDT002049078.1' already exists. Skipping...
Folder 'GCA_035469745.1_PDT002049072.1' already exists. Skipping...
Folder 'GCA_035469785.1_PDT002049067.1' already exists. Skipping...
Folder 'GCA_035471505.1_PDT002049076.1' already exists. Skipping...
Folder 'GCA_035471555.1_PDT002049075.1' already exists. Skipping...
Folder 'GCA_035475595.1_PDT002049090.1' already exists. Skipping...
Folder 'GCA_035475695.1_PDT002049089.1' already exists. Skipping...
Folder 'GCA_035475705.1_PDT002049063.1' already exists. Skipping...
Folder 'GCA_035475835.1_PDT002049061.1' already exists. Skipping...
Folder 'GCA_035475855.1_PDT002049062.1' already exists. Skipping...
Folder 'GCA_035482375.1_PDT002049145.1' already exists. Skipping...
Folder 'GCA_035482395.1_PDT002049081.1' already exists. Skipping...
Folder 'GCA_035493325.1_PDT002049827.1' already exists. Skipping...
Folder 'GCA_035518685.1_PDT002049959.1' already exists. Skipping...
Folder 'GCA_035520255.1_PDT002050044.1' already exists. Skipping...
Folder 'GCA_035523015.1_PDT002050047.1' already exists. Skipping...
Folder 'GCA_035561875.1_PDT002050707.1' already exists. Skipping...
Folder 'GCA_035570575.1_PDT002050556.1' already exists. Skipping...
Folder 'GCA_035571235.1_PDT002050525.1' already exists. Skipping...
Folder 'GCA_035575115.1_PDT002049956.1' already exists. Skipping...
Folder 'GCA_035597095.1_PDT002051233.1' already exists. Skipping...
Folder 'GCA_035597135.1_PDT002051231.1' already exists. Skipping...
Folder 'GCA_035597195.1_PDT002051208.1' already exists. Skipping...
Folder 'GCA_035597215.1_PDT002051205.1' already exists. Skipping...
Folder 'GCA_035597255.1_PDT002051200.1' already exists. Skipping...
Folder 'GCA_035597535.1_PDT002051225.1' already exists. Skipping...
Folder 'GCA_035597615.1_PDT002051211.1' already exists. Skipping...
Folder 'GCA_035597655.1_PDT002051198.1' already exists. Skipping...
Folder 'GCA_035597815.1_PDT002051209.1' already exists. Skipping...
Folder 'GCA_035597935.1_PDT002051232.1' already exists. Skipping...
Folder 'GCA_035598775.1_PDT002051223.1' already exists. Skipping...
Folder 'GCA_035598935.1_PDT002051197.1' already exists. Skipping...
Folder 'GCA_035598955.1_PDT002051240.1' already exists. Skipping...
Folder 'GCA_035598975.1_PDT002051236.1' already exists. Skipping...
Folder 'GCA_035599635.1_PDT002051237.1' already exists. Skipping...
Folder 'GCA_035609525.1_PDT001952281.1' already exists. Skipping...
Folder 'GCA_035609745.1_PDT001952270.1' already exists. Skipping...
Folder 'GCA_035609805.1_PDT001952240.1' already exists. Skipping...
Folder 'GCA_035610065.1_PDT001700952.1' already exists. Skipping...
Folder 'GCA_035610105.1_PDT001700951.1' already exists. Skipping...
Folder 'GCA_035610935.1_PDT002051201.1' already exists. Skipping...
Folder 'GCA_035657935.1_PDT002051970.1' already exists. Skipping...
Folder 'GCA_035657975.1_PDT002051954.1' already exists. Skipping...
Folder 'GCA_035658015.1_PDT002051935.1' already exists. Skipping...
Folder 'GCA_035658555.1_PDT002051953.1' already exists. Skipping...
Folder 'GCA_035776915.1_PDT002052995.1' already exists. Skipping...
Folder 'GCA_035779535.1_PDT002053944.1' already exists. Skipping...
Folder 'GCA_035779575.1_PDT002053939.1' already exists. Skipping...
Folder 'GCA_035779595.1_PDT002053929.1' already exists. Skipping...
Folder 'GCA_035779795.1_PDT002053877.1' already exists. Skipping...
Folder 'GCA_035781095.1_PDT002053650.1' already exists. Skipping...
Folder 'GCA_035781155.1_PDT002053607.1' already exists. Skipping...
Folder 'GCA_035821375.1_PDT002055917.1' already exists. Skipping...
Folder 'GCA_035830955.1_ASM3583095v1' already exists. Skipping...
Folder 'GCA_035830975.1_ASM3583097v1' already exists. Skipping...
Folder 'GCA_035851195.1_PDT002055192.1' already exists. Skipping...
Folder 'GCA_035851235.1_PDT002055197.1' already exists. Skipping...
Folder 'GCA_035851275.1_PDT002055191.1' already exists. Skipping...
Folder 'GCA_035853255.1_PDT002055196.1' already exists. Skipping...
Folder 'GCA_035853275.1_PDT002055194.1' already exists. Skipping...
Folder 'GCA_035853295.1_PDT002055193.1' already exists. Skipping...
Folder 'GCA_035855155.1_PDT002055195.1' already exists. Skipping...
Folder 'GCA_035879955.1_PDT002054546.1' already exists. Skipping...
Folder 'GCA_035879995.1_PDT002054536.1' already exists. Skipping...
Folder 'GCA_035880215.1_PDT002054097.1' already exists. Skipping...
Folder 'GCA_035880225.1_PDT002054095.1' already exists. Skipping...
Folder 'GCA_035880255.1_PDT002053942.1' already exists. Skipping...
Folder 'GCA_035880275.1_PDT002053943.1' already exists. Skipping...
Folder 'GCA_035880295.1_PDT002053936.1' already exists. Skipping...
Folder 'GCA_035881055.1_PDT002053982.1' already exists. Skipping...
Folder 'GCA_035881075.1_PDT002053935.1' already exists. Skipping...
Folder 'GCA_035881095.1_PDT002053951.1' already exists. Skipping...
Folder 'GCA_035881115.1_PDT002053885.1' already exists. Skipping...
Folder 'GCA_035881135.1_PDT002053933.1' already exists. Skipping...
Folder 'GCA_035883775.1_PDT002057125.1' already exists. Skipping...
Folder 'GCA_035884035.1_PDT002058229.1' already exists. Skipping...
Folder 'GCA_035884185.1_PDT002058224.1' already exists. Skipping...
Folder 'GCA_035884215.1_PDT002058225.1' already exists. Skipping...
Folder 'GCA_035884275.1_PDT002058219.1' already exists. Skipping...
Folder 'GCA_035884335.1_PDT002058217.1' already exists. Skipping...
Folder 'GCA_035884415.1_PDT002058214.1' already exists. Skipping...
Folder 'GCA_035884555.1_PDT002058207.1' already exists. Skipping...
Folder 'GCA_035884595.1_PDT002058205.1' already exists. Skipping...
Folder 'GCA_035884655.1_PDT002058203.1' already exists. Skipping...
Folder 'GCA_035884675.1_PDT002058200.1' already exists. Skipping...
Folder 'GCA_035884695.1_PDT002058201.1' already exists. Skipping...
Folder 'GCA_035884735.1_PDT002058198.1' already exists. Skipping...
Folder 'GCA_035884755.1_PDT002058197.1' already exists. Skipping...
Folder 'GCA_035884775.1_PDT002058196.1' already exists. Skipping...
Folder 'GCA_035884875.1_PDT002058189.1' already exists. Skipping...
Folder 'GCA_035885595.1_PDT002057846.1' already exists. Skipping...
Folder 'GCA_035885615.1_PDT002057847.1' already exists. Skipping...
Folder 'GCA_035885635.1_PDT002057843.1' already exists. Skipping...
Folder 'GCA_035887615.1_PDT002057126.1' already exists. Skipping...
Folder 'GCA_035888235.1_PDT002054521.1' already exists. Skipping...
Folder 'GCA_035891595.1_PDT002053983.1' already exists. Skipping...
Folder 'GCA_035892115.1_PDT002053950.1' already exists. Skipping...
Folder 'GCA_035892215.1_PDT002053946.1' already exists. Skipping...
Folder 'GCA_035892995.1_PDT002053652.1' already exists. Skipping...
Folder 'GCA_035893355.1_PDT002053654.1' already exists. Skipping...
Folder 'GCA_035893395.1_PDT002053644.1' already exists. Skipping...
Folder 'GCA_035893715.1_PDT002053610.1' already exists. Skipping...
Folder 'GCA_035893775.1_PDT002053609.1' already exists. Skipping...
Folder 'GCA_035894035.1_PDT002053604.1' already exists. Skipping...
Folder 'GCA_035894055.1_PDT002053603.1' already exists. Skipping...
Folder 'GCA_035894095.1_PDT002053601.1' already exists. Skipping...
Folder 'GCA_035894145.1_PDT002053602.1' already exists. Skipping...
Folder 'GCA_035894175.1_PDT002053458.1' already exists. Skipping...
Folder 'GCA_035894815.1_PDT002052996.1' already exists. Skipping...
Folder 'GCA_035895915.1_PDT002052310.1' already exists. Skipping...
Folder 'GCA_035895935.1_PDT002052229.1' already exists. Skipping...
Folder 'GCA_035898415.1_PDT002051988.1' already exists. Skipping...
Folder 'GCA_035898715.1_PDT002051951.1' already exists. Skipping...
Folder 'GCA_035898755.1_PDT002051931.1' already exists. Skipping...
Folder 'GCA_035898785.1_PDT002051930.1' already exists. Skipping...
Folder 'GCA_035899035.1_PDT002051830.1' already exists. Skipping...
Folder 'GCA_035899385.1_PDT002051829.1' already exists. Skipping...
Folder 'GCA_035922505.1_PDT002059425.1' already exists. Skipping...
Folder 'GCA_035922585.1_PDT002059411.1' already exists. Skipping...
Folder 'GCA_035925445.1_PDT002058890.1' already exists. Skipping...
Folder 'GCA_035925545.1_PDT002058886.1' already exists. Skipping...
Folder 'GCA_035925945.1_PDT002058859.1' already exists. Skipping...
Folder 'GCA_035926045.1_PDT002058854.1' already exists. Skipping...
Folder 'GCA_035927645.1_PDT002058603.1' already exists. Skipping...
Folder 'GCA_035927685.1_PDT002058600.1' already exists. Skipping...
Folder 'GCA_035927705.1_PDT002058598.1' already exists. Skipping...
Folder 'GCA_035927725.1_PDT002058602.1' already exists. Skipping...
Folder 'GCA_035927745.1_PDT002058601.1' already exists. Skipping...
Folder 'GCA_035927765.1_PDT002058597.1' already exists. Skipping...
Folder 'GCA_035927785.1_PDT002058599.1' already exists. Skipping...
Folder 'GCA_035927825.1_PDT002058595.1' already exists. Skipping...
Folder 'GCA_035927845.1_PDT002058596.1' already exists. Skipping...
Folder 'GCA_035927865.1_PDT002058594.1' already exists. Skipping...
Folder 'GCA_035931505.1_PDT002061047.1' already exists. Skipping...
Folder 'GCA_035931525.1_PDT002061046.1' already exists. Skipping...
Folder 'GCA_035931545.1_PDT002061043.1' already exists. Skipping...
Folder 'GCA_035931585.1_PDT002061041.1' already exists. Skipping...
Folder 'GCA_035933845.1_PDT002061048.1' already exists. Skipping...
Folder 'GCA_035937335.1_PDT002061042.1' already exists. Skipping...
Folder 'GCA_035938815.1_PDT002051961.1' already exists. Skipping...
Folder 'GCA_035938855.1_PDT002051959.1' already exists. Skipping...
Folder 'GCA_035938895.1_PDT002051958.1' already exists. Skipping...
Folder 'GCA_035938975.1_PDT002051956.1' already exists. Skipping...
Folder 'GCA_035939055.1_PDT002051957.1' already exists. Skipping...
Folder 'GCA_035939075.1_PDT002051968.1' already exists. Skipping...
Folder 'GCA_035939255.1_PDT002051964.1' already exists. Skipping...
Folder 'GCA_035939275.1_PDT002051963.1' already exists. Skipping...
Folder 'GCA_035940475.1_PDT002061081.1' already exists. Skipping...
Folder 'GCA_035940515.1_PDT002061080.1' already exists. Skipping...
Folder 'GCA_035959035.1_PDT002061258.1' already exists. Skipping...
Folder 'GCA_035959055.1_PDT002061267.1' already exists. Skipping...
Folder 'GCA_035959075.1_PDT002061189.1' already exists. Skipping...
Folder 'GCA_035959095.1_PDT002061185.1' already exists. Skipping...
Folder 'GCA_035959115.1_PDT002061184.1' already exists. Skipping...
Folder 'GCA_035959135.1_PDT002061151.1' already exists. Skipping...
Folder 'GCA_035959155.1_PDT002061150.1' already exists. Skipping...
Folder 'GCA_035959995.1_PDT002061148.1' already exists. Skipping...
Folder 'GCA_035960055.1_PDT002061149.1' already exists. Skipping...
Folder 'GCA_035974935.1_PDT002062292.1' already exists. Skipping...
Folder 'GCA_035975015.1_PDT002062283.1' already exists. Skipping...
Folder 'GCA_036015125.1_PDT002062489.1' already exists. Skipping...
Folder 'GCA_036023305.1_PDT002062685.1' already exists. Skipping...
Folder 'GCA_036023335.1_PDT002062684.1' already exists. Skipping...
Folder 'GCA_036023355.1_PDT002062681.1' already exists. Skipping...
Folder 'GCA_036026195.1_PDT002062682.1' already exists. Skipping...
Folder 'GCA_036060115.1_PDT002062728.1' already exists. Skipping...
Folder 'GCA_036060135.1_PDT002062723.1' already exists. Skipping...
Folder 'GCA_036085875.1_PDT002063460.1' already exists. Skipping...
Folder 'GCA_036086895.1_PDT002063465.1' already exists. Skipping...
Folder 'GCA_036087915.1_PDT002063457.1' already exists. Skipping...
Folder 'GCA_036110175.1_PDT002062573.1' already exists. Skipping...
Folder 'GCA_036110195.1_PDT002062571.1' already exists. Skipping...
Folder 'GCA_036180225.1_PDT002064012.1' already exists. Skipping...
Folder 'GCA_036180505.1_PDT002063991.1' already exists. Skipping...
Folder 'GCA_036239335.1_PDT002064453.1' already exists. Skipping...
Folder 'GCA_036239375.1_PDT002064452.1' already exists. Skipping...
Folder 'GCA_036240295.1_PDT002064664.1' already exists. Skipping...
Folder 'GCA_036240375.1_PDT002064661.1' already exists. Skipping...
Folder 'GCA_036240435.1_PDT002064658.1' already exists. Skipping...
Folder 'GCA_036240455.1_PDT002064657.1' already exists. Skipping...
Folder 'GCA_036240475.1_PDT002064656.1' already exists. Skipping...
Folder 'GCA_036240495.1_PDT002064654.1' already exists. Skipping...
Folder 'GCA_036240535.1_PDT002064652.1' already exists. Skipping...
Folder 'GCA_036240555.1_PDT002064653.1' already exists. Skipping...
Folder 'GCA_036240595.1_PDT002064650.1' already exists. Skipping...
Folder 'GCA_036240635.1_PDT002064647.1' already exists. Skipping...
Folder 'GCA_036240655.1_PDT002064648.1' already exists. Skipping...
Folder 'GCA_036240735.1_PDT002064645.1' already exists. Skipping...
Folder 'GCA_036240755.1_PDT002064643.1' already exists. Skipping...
Folder 'GCA_036240815.1_PDT002064640.1' already exists. Skipping...
Folder 'GCA_036240835.1_PDT002064639.1' already exists. Skipping...
Folder 'GCA_036240855.1_PDT002064638.1' already exists. Skipping...
Folder 'GCA_036240875.1_PDT002064630.1' already exists. Skipping...
Folder 'GCA_036240895.1_PDT002064631.1' already exists. Skipping...
Folder 'GCA_036240935.1_PDT002064628.1' already exists. Skipping...
Folder 'GCA_036241015.1_PDT002064624.1' already exists. Skipping...
Folder 'GCA_036241035.1_PDT002064627.1' already exists. Skipping...
Folder 'GCA_036241055.1_PDT002064625.1' already exists. Skipping...
Folder 'GCA_036241115.1_PDT002064621.1' already exists. Skipping...
Folder 'GCA_036241155.1_PDT002064619.1' already exists. Skipping...
Folder 'GCA_036241175.1_PDT002064618.1' already exists. Skipping...
Folder 'GCA_036241255.1_PDT002064614.1' already exists. Skipping...
Folder 'GCA_036241275.1_PDT002064612.1' already exists. Skipping...
Folder 'GCA_036241285.1_PDT002064613.1' already exists. Skipping...
Folder 'GCA_036241315.1_PDT002064611.1' already exists. Skipping...
Folder 'GCA_036241335.1_PDT002064610.1' already exists. Skipping...
Folder 'GCA_036241375.1_PDT002064609.1' already exists. Skipping...
Folder 'GCA_036241415.1_PDT002064602.1' already exists. Skipping...
Folder 'GCA_036241435.1_PDT002064605.1' already exists. Skipping...
Folder 'GCA_036241455.1_PDT002064600.1' already exists. Skipping...
Folder 'GCA_036241475.1_PDT002064601.1' already exists. Skipping...
Folder 'GCA_036241495.1_PDT002064599.1' already exists. Skipping...
Folder 'GCA_036241515.1_PDT002064603.1' already exists. Skipping...
Folder 'GCA_036242255.1_PDT002064555.1' already exists. Skipping...
Folder 'GCA_036242295.1_PDT002064556.1' already exists. Skipping...
Folder 'GCA_036242315.1_PDT002064554.1' already exists. Skipping...
Folder 'GCA_036242335.1_PDT002064553.1' already exists. Skipping...
Folder 'GCA_036242355.1_PDT002064551.1' already exists. Skipping...
Folder 'GCA_036242375.1_PDT002064552.1' already exists. Skipping...
Folder 'GCA_036242435.1_PDT002064550.1' already exists. Skipping...
Folder 'GCA_036242475.1_PDT002064549.1' already exists. Skipping...
Folder 'GCA_036242875.1_PDT002064526.1' already exists. Skipping...
Folder 'GCA_036242955.1_PDT002064522.1' already exists. Skipping...
Folder 'GCA_036243135.1_PDT002064513.1' already exists. Skipping...
Folder 'GCA_036243795.1_PDT002064456.1' already exists. Skipping...
Folder 'GCA_036288685.1_ASM3628868v1' already exists. Skipping...
Folder 'GCA_036288865.1_ASM3628886v1' already exists. Skipping...
Folder 'GCA_036325145.1_PDT002067139.1' already exists. Skipping...
Folder 'GCA_036325185.1_PDT002067134.1' already exists. Skipping...
Folder 'GCA_036328375.1_PDT002069947.1' already exists. Skipping...
Folder 'GCA_036355975.1_PDT002069939.1' already exists. Skipping...
Folder 'GCA_036356075.1_PDT002069904.1' already exists. Skipping...
Folder 'GCA_036356095.1_PDT002069905.1' already exists. Skipping...
Folder 'GCA_036356135.1_PDT002069902.1' already exists. Skipping...
Folder 'GCA_036356195.1_PDT002069898.1' already exists. Skipping...
Folder 'GCA_036356215.1_PDT002069896.1' already exists. Skipping...
Folder 'GCA_036356235.1_PDT002069897.1' already exists. Skipping...
Folder 'GCA_036356255.1_PDT002069895.1' already exists. Skipping...
Folder 'GCA_036356295.1_PDT002069893.1' already exists. Skipping...
Folder 'GCA_036356315.1_PDT002069892.1' already exists. Skipping...
Folder 'GCA_036356335.1_PDT002069890.1' already exists. Skipping...
Folder 'GCA_036356345.1_PDT002069891.1' already exists. Skipping...
Folder 'GCA_036356455.1_PDT002069885.1' already exists. Skipping...
Folder 'GCA_036356475.1_PDT002069884.1' already exists. Skipping...
Folder 'GCA_036357175.1_PDT002069805.1' already exists. Skipping...
Folder 'GCA_036357295.1_PDT002069799.1' already exists. Skipping...
Folder 'GCA_036357325.1_PDT002069796.1' already exists. Skipping...
Folder 'GCA_036357435.1_PDT002069792.1' already exists. Skipping...
Folder 'GCA_036357455.1_PDT002069788.1' already exists. Skipping...
Folder 'GCA_036357555.1_PDT002069786.1' already exists. Skipping...
Folder 'GCA_036357575.1_PDT002069785.1' already exists. Skipping...
Folder 'GCA_036357675.1_PDT002069779.1' already exists. Skipping...

Retreiveing data: 109679it [00:17, 6664.38it/s]

Folder 'GCA_037819275.1_PDT002124825.1' already exists. Skipping...
Folder 'GCA_037819295.1_PDT002124823.1' already exists. Skipping...
Folder 'GCA_037819315.1_PDT002124818.1' already exists. Skipping...
Folder 'GCA_037819375.1_PDT002124813.1' already exists. Skipping...
Folder 'GCA_037819435.1_PDT002124796.1' already exists. Skipping...
Folder 'GCA_037819475.1_PDT002124694.1' already exists. Skipping...
Folder 'GCA_037821255.1_PDT002124809.1' already exists. Skipping...
Folder 'GCA_037821295.1_PDT002124806.1' already exists. Skipping...
Folder 'GCA_037821375.1_PDT002124797.1' already exists. Skipping...
Folder 'GCA_037822285.1_PDT002124826.1' already exists. Skipping...
Folder 'GCA_037822305.1_PDT002124828.1' already exists. Skipping...
Folder 'GCA_037822345.1_PDT002124815.1' already exists. Skipping...
Folder 'GCA_037822405.1_PDT002124802.1' already exists. Skipping...
Folder 'GCA_037822425.1_PDT002124695.1' already exists. Skipping...
Folder 'GCA_037876585.1_PDT002125614.1' already exists. Skipping...
Folder 'GCA_037877595.1_PDT002125615.1' already exists. Skipping...
Folder 'GCA_037877615.1_PDT002125616.1' already exists. Skipping...
Folder 'GCA_037883715.1_PDT002125730.1' already exists. Skipping...
Folder 'GCA_037883735.1_PDT002125731.1' already exists. Skipping...
Folder 'GCA_037883775.1_PDT002125688.1' already exists. Skipping...
Folder 'GCA_037884745.1_PDT002125729.1' already exists. Skipping...
Folder 'GCA_037884765.1_PDT002125690.1' already exists. Skipping...
Folder 'GCA_037886735.1_PDT002125689.1' already exists. Skipping...
Folder 'GCA_037886745.1_PDT002125728.1' already exists. Skipping...
Folder 'GCA_037886775.1_PDT002125687.1' already exists. Skipping...
Folder 'GCA_037893125.1_PDT002127401.1' already exists. Skipping...
Folder 'GCA_037893275.1_PDT002127394.1' already exists. Skipping...
Folder 'GCA_037893405.1_PDT002127393.1' already exists. Skipping...
Folder 'GCA_037893635.1_PDT002127389.1' already exists. Skipping...
Folder 'GCA_037893745.1_PDT002127387.1' already exists. Skipping...
Folder 'GCA_037893765.1_PDT002127379.1' already exists. Skipping...
Folder 'GCA_037893815.1_PDT002127382.1' already exists. Skipping...
Folder 'GCA_037893845.1_PDT002127380.1' already exists. Skipping...
Folder 'GCA_037893935.1_PDT002127375.1' already exists. Skipping...
Folder 'GCA_037894015.1_PDT002127371.1' already exists. Skipping...
Folder 'GCA_037894135.1_PDT002127365.1' already exists. Skipping...
Folder 'GCA_037894195.1_PDT002127360.1' already exists. Skipping...
Folder 'GCA_037894275.1_PDT002127358.1' already exists. Skipping...
Folder 'GCA_037894355.1_PDT002127355.1' already exists. Skipping...
Folder 'GCA_037894395.1_PDT002127353.1' already exists. Skipping...
Folder 'GCA_037898565.1_PDT002128031.1' already exists. Skipping...
Folder 'GCA_037898625.1_PDT002128026.1' already exists. Skipping...
Folder 'GCA_037898645.1_PDT002128023.1' already exists. Skipping...
Folder 'GCA_037898655.1_PDT002128022.1' already exists. Skipping...
Folder 'GCA_037898915.1_PDT002128016.1' already exists. Skipping...
Folder 'GCA_037899205.1_PDT002128032.1' already exists. Skipping...
Folder 'GCA_037899985.1_PDT002128024.1' already exists. Skipping...
Folder 'GCA_037900805.1_PDT002128042.1' already exists. Skipping...
Folder 'GCA_037900825.1_PDT002128041.1' already exists. Skipping...
Folder 'GCA_037900835.1_PDT002128141.1' already exists. Skipping...
Folder 'GCA_037900875.1_PDT002128045.1' already exists. Skipping...
Folder 'GCA_037900965.1_PDT002128039.1' already exists. Skipping...
Folder 'GCA_037901865.1_PDT002128040.1' already exists. Skipping...
Folder 'GCA_037904895.1_PDT002128270.1' already exists. Skipping...
Folder 'GCA_037906045.1_PDT002128145.1' already exists. Skipping...
Folder 'GCA_037906145.1_PDT002128144.1' already exists. Skipping...
Folder 'GCA_037906285.1_PDT002128143.1' already exists. Skipping...
Folder 'GCA_037906305.1_PDT002128205.1' already exists. Skipping...
Folder 'GCA_037906375.1_PDT002128274.1' already exists. Skipping...
Folder 'GCA_037912035.1_PDT002128772.1' already exists. Skipping...
Folder 'GCA_037913475.1_PDT002128545.1' already exists. Skipping...
Folder 'GCA_037913865.1_PDT002128525.1' already exists. Skipping...
Folder 'GCA_037914405.1_PDT002128495.1' already exists. Skipping...
Folder 'GCA_037914485.1_PDT002128492.1' already exists. Skipping...
Folder 'GCA_037920495.1_PDT002129315.1' already exists. Skipping...
Folder 'GCA_037920505.1_PDT002129313.1' already exists. Skipping...
Folder 'GCA_037921045.1_PDT002129328.1' already exists. Skipping...
Folder 'GCA_037921055.1_PDT002129317.1' already exists. Skipping...
Folder 'GCA_037921065.1_PDT002129319.1' already exists. Skipping...
Folder 'GCA_037921085.1_PDT002129325.1' already exists. Skipping...
Folder 'GCA_037921105.1_PDT002129324.1' already exists. Skipping...
Folder 'GCA_037921185.1_PDT002129314.1' already exists. Skipping...
Folder 'GCA_037921405.1_PDT002129316.1' already exists. Skipping...
Folder 'GCA_037921435.1_PDT002129331.1' already exists. Skipping...
Folder 'GCA_037921445.1_PDT002129321.1' already exists. Skipping...
Folder 'GCA_037921475.1_PDT002129312.1' already exists. Skipping...
Folder 'GCA_037921495.1_PDT002129329.1' already exists. Skipping...
Folder 'GCA_037921745.1_PDT002129326.1' already exists. Skipping...
Folder 'GCA_037921785.1_PDT002129318.1' already exists. Skipping...
Folder 'GCA_037921805.1_PDT002129320.1' already exists. Skipping...
Folder 'GCA_037922755.1_PDT002129322.1' already exists. Skipping...
Folder 'GCA_037923805.1_PDT002129515.1' already exists. Skipping...
Folder 'GCA_037923855.1_PDT002129514.1' already exists. Skipping...
Folder 'GCA_037925935.1_PDT002129323.1' already exists. Skipping...
Folder 'GCA_037925955.1_PDT002129513.1' already exists. Skipping...
Folder 'GCA_037926015.1_PDT002129516.1' already exists. Skipping...
Folder 'GCA_037955545.1_PDT002130213.1' already exists. Skipping...
Folder 'GCA_037955565.1_PDT002130224.1' already exists. Skipping...
Folder 'GCA_037955585.1_PDT002130225.1' already exists. Skipping...
Folder 'GCA_037957405.1_PDT002130573.1' already exists. Skipping...
Folder 'GCA_037964985.1_PDT002130826.1' already exists. Skipping...
Folder 'GCA_037977065.1_PDT002131702.1' already exists. Skipping...
Folder 'GCA_037977105.1_PDT002131698.1' already exists. Skipping...
Folder 'GCA_037977125.1_PDT002131704.1' already exists. Skipping...
Folder 'GCA_037977165.1_PDT002131700.1' already exists. Skipping...
Folder 'GCA_037977185.1_PDT002131699.1' already exists. Skipping...
Folder 'GCA_037977215.1_PDT002131946.1' already exists. Skipping...
Folder 'GCA_037979035.1_PDT002132067.1' already exists. Skipping...
Folder 'GCA_037979085.1_PDT002132073.1' already exists. Skipping...
Folder 'GCA_037979135.1_PDT002132017.1' already exists. Skipping...
Folder 'GCA_037979145.1_PDT002132018.1' already exists. Skipping...
Folder 'GCA_037979175.1_PDT002132015.1' already exists. Skipping...
Folder 'GCA_037979185.1_PDT002132014.1' already exists. Skipping...
Folder 'GCA_037979215.1_PDT002132013.1' already exists. Skipping...
Folder 'GCA_037979975.1_PDT002132074.1' already exists. Skipping...
Folder 'GCA_037981735.1_PDT002131703.1' already exists. Skipping...
Folder 'GCA_037981775.1_PDT002132081.1' already exists. Skipping...
Folder 'GCA_038011175.1_PDT002132883.1' already exists. Skipping...
Folder 'GCA_038024415.1_PDT002134327.1' already exists. Skipping...
Folder 'GCA_038024435.1_PDT002134331.1' already exists. Skipping...
Folder 'GCA_038024455.1_PDT002134326.1' already exists. Skipping...
Folder 'GCA_038025165.1_PDT002134421.1' already exists. Skipping...
Folder 'GCA_038025205.1_PDT002134332.1' already exists. Skipping...
Folder 'GCA_038025285.1_PDT002134444.1' already exists. Skipping...
Folder 'GCA_038025305.1_PDT002134420.1' already exists. Skipping...
Folder 'GCA_038025325.1_PDT002134329.1' already exists. Skipping...
Folder 'GCA_038026005.1_PDT002135018.1' already exists. Skipping...
Folder 'GCA_038026045.1_PDT002135004.1' already exists. Skipping...
Folder 'GCA_038026105.1_PDT002134998.1' already exists. Skipping...
Folder 'GCA_038026125.1_PDT002135000.1' already exists. Skipping...
Folder 'GCA_038026145.1_PDT002134981.1' already exists. Skipping...
Folder 'GCA_038026165.1_PDT002135020.1' already exists. Skipping...
Folder 'GCA_038026185.1_PDT002134996.1' already exists. Skipping...
Folder 'GCA_038026205.1_PDT002135019.1' already exists. Skipping...
Folder 'GCA_038026225.1_PDT002134997.1' already exists. Skipping...
Folder 'GCA_038026245.1_PDT002134995.1' already exists. Skipping...
Folder 'GCA_038026285.1_PDT002134989.1' already exists. Skipping...
Folder 'GCA_038026345.1_PDT002134983.1' already exists. Skipping...
Folder 'GCA_038026545.1_PDT002134985.1' already exists. Skipping...
Folder 'GCA_038026565.1_PDT002135002.1' already exists. Skipping...
Folder 'GCA_038029845.1_PDT002135151.1' already exists. Skipping...
Folder 'GCA_038029865.1_PDT002135148.1' already exists. Skipping...
Folder 'GCA_038029885.1_PDT002135147.1' already exists. Skipping...
Folder 'GCA_038029905.1_PDT002135146.1' already exists. Skipping...
Folder 'GCA_038029925.1_PDT002135139.1' already exists. Skipping...
Folder 'GCA_038029945.1_PDT002135143.1' already exists. Skipping...
Folder 'GCA_038029965.1_PDT002135138.1' already exists. Skipping...
Folder 'GCA_038030005.1_PDT002135152.1' already exists. Skipping...
Folder 'GCA_038030025.1_PDT002135149.1' already exists. Skipping...
Folder 'GCA_038030045.1_PDT002135142.1' already exists. Skipping...
Folder 'GCA_038030065.1_PDT002135141.1' already exists. Skipping...
Folder 'GCA_038030085.1_PDT002135140.1' already exists. Skipping...
Folder 'GCA_038030105.1_PDT002135145.1' already exists. Skipping...
Folder 'GCA_038030125.1_PDT002135150.1' already exists. Skipping...
Folder 'GCA_038030185.1_PDT002135159.1' already exists. Skipping...
Folder 'GCA_038030225.1_PDT002135144.1' already exists. Skipping...
Folder 'GCA_038030245.1_PDT002135158.1' already exists. Skipping...
Folder 'GCA_038031125.1_PDT002135391.1' already exists. Skipping...
Folder 'GCA_038031145.1_PDT002135398.1' already exists. Skipping...
Folder 'GCA_038031165.1_PDT002135374.1' already exists. Skipping...
Folder 'GCA_038031185.1_PDT002135383.1' already exists. Skipping...
Folder 'GCA_038031205.1_PDT002135378.1' already exists. Skipping...
Folder 'GCA_038031225.1_PDT002135397.1' already exists. Skipping...
Folder 'GCA_038031245.1_PDT002135371.1' already exists. Skipping...
Folder 'GCA_038031265.1_PDT002135393.1' already exists. Skipping...
Folder 'GCA_038031425.1_PDT002111458.1' already exists. Skipping...
Folder 'GCA_038031545.1_PDT002134422.1' already exists. Skipping...
Folder 'GCA_038031645.1_PDT002134333.1' already exists. Skipping...
Folder 'GCA_038031665.1_PDT002134328.1' already exists. Skipping...
Folder 'GCA_038033725.1_PDT002134340.1' already exists. Skipping...
Folder 'GCA_038033985.1_PDT002134330.1' already exists. Skipping...
Folder 'GCA_038034445.1_PDT002134821.1' already exists. Skipping...
Folder 'GCA_038034465.1_PDT002134838.1' already exists. Skipping...
Folder 'GCA_038034485.1_PDT002134812.1' already exists. Skipping...
Folder 'GCA_038034505.1_PDT002134811.1' already exists. Skipping...
Folder 'GCA_038034545.1_PDT002134808.1' already exists. Skipping...
Folder 'GCA_038034945.1_PDT002134840.1' already exists. Skipping...
Folder 'GCA_038035005.1_PDT002134839.1' already exists. Skipping...
Folder 'GCA_038035065.1_PDT002134827.1' already exists. Skipping...
Folder 'GCA_038035085.1_PDT002134823.1' already exists. Skipping...
Folder 'GCA_038035105.1_PDT002134810.1' already exists. Skipping...
Folder 'GCA_038038145.1_PDT002135533.1' already exists. Skipping...
Folder 'GCA_038038185.1_PDT002135531.1' already exists. Skipping...
Folder 'GCA_038038205.1_PDT002135530.1' already exists. Skipping...
Folder 'GCA_038038225.1_PDT002135518.1' already exists. Skipping...
Folder 'GCA_038038245.1_PDT002135529.1' already exists. Skipping...
Folder 'GCA_038038525.1_PDT002135563.1' already exists. Skipping...
Folder 'GCA_038038585.1_PDT002135509.1' already exists. Skipping...
Folder 'GCA_038038605.1_PDT002135567.1' already exists. Skipping...
Folder 'GCA_038038625.1_PDT002135564.1' already exists. Skipping...
Folder 'GCA_038038685.1_PDT002135568.1' already exists. Skipping...
Folder 'GCA_038038725.1_PDT002135554.1' already exists. Skipping...
Folder 'GCA_038039425.1_PDT002135559.1' already exists. Skipping...
Folder 'GCA_038047745.1_PDT002135606.1' already exists. Skipping...
Folder 'GCA_038047785.1_PDT002135603.1' already exists. Skipping...
Folder 'GCA_038047825.1_PDT002135602.1' already exists. Skipping...
Folder 'GCA_038047905.1_PDT002135598.1' already exists. Skipping...
Folder 'GCA_038047965.1_PDT002135595.1' already exists. Skipping...
Folder 'GCA_038048005.1_PDT002135593.1' already exists. Skipping...
Folder 'GCA_038048025.1_PDT002135592.1' already exists. Skipping...
Folder 'GCA_038048045.1_PDT002135591.1' already exists. Skipping...
Folder 'GCA_038048065.1_PDT002135590.1' already exists. Skipping...
Folder 'GCA_038048105.1_PDT002135589.1' already exists. Skipping...
Folder 'GCA_038048125.1_PDT002135587.1' already exists. Skipping...
Folder 'GCA_038049025.1_PDT002135001.1' already exists. Skipping...
Folder 'GCA_038052095.1_PDT002135814.1' already exists. Skipping...
Folder 'GCA_038052575.1_PDT002136099.1' already exists. Skipping...
Folder 'GCA_038052595.1_PDT002136084.1' already exists. Skipping...
Folder 'GCA_038052635.1_PDT002136082.1' already exists. Skipping...
Folder 'GCA_038052655.1_PDT002136108.1' already exists. Skipping...
Folder 'GCA_038052675.1_PDT002136079.1' already exists. Skipping...
Folder 'GCA_038052695.1_PDT002136107.1' already exists. Skipping...
Folder 'GCA_038052715.1_PDT002136106.1' already exists. Skipping...
Folder 'GCA_038052735.1_PDT002136105.1' already exists. Skipping...
Folder 'GCA_038052755.1_PDT002136101.1' already exists. Skipping...
Folder 'GCA_038052775.1_PDT002136103.1' already exists. Skipping...
Folder 'GCA_038052795.1_PDT002136098.1' already exists. Skipping...
Folder 'GCA_038052815.1_PDT002136097.1' already exists. Skipping...
Folder 'GCA_038052845.1_PDT002136096.1' already exists. Skipping...
Folder 'GCA_038052875.1_PDT002136092.1' already exists. Skipping...
Folder 'GCA_038052895.1_PDT002136090.1' already exists. Skipping...
Folder 'GCA_038052915.1_PDT002136091.1' already exists. Skipping...
Folder 'GCA_038052935.1_PDT002136088.1' already exists. Skipping...
Folder 'GCA_038052955.1_PDT002136087.1' already exists. Skipping...
Folder 'GCA_038052975.1_PDT002136083.1' already exists. Skipping...
Folder 'GCA_038052995.1_PDT002136085.1' already exists. Skipping...
Folder 'GCA_038053015.1_PDT002136077.1' already exists. Skipping...
Folder 'GCA_038053075.1_PDT002136081.1' already exists. Skipping...
Folder 'GCA_038053095.1_PDT002136086.1' already exists. Skipping...
Folder 'GCA_038053115.1_PDT002136076.1' already exists. Skipping...
Folder 'GCA_038053135.1_PDT002136094.1' already exists. Skipping...
Folder 'GCA_038053175.1_PDT002136075.1' already exists. Skipping...
Folder 'GCA_038053255.1_PDT002136104.1' already exists. Skipping...
Folder 'GCA_038053295.1_PDT002136080.1' already exists. Skipping...
Folder 'GCA_038053475.1_PDT002136100.1' already exists. Skipping...
Folder 'GCA_038053545.1_PDT002136150.1' already exists. Skipping...
Folder 'GCA_038053735.1_PDT002136153.1' already exists. Skipping...
Folder 'GCA_038053755.1_PDT002136149.1' already exists. Skipping...
Folder 'GCA_038053765.1_PDT002136152.1' already exists. Skipping...
Folder 'GCA_038053855.1_PDT002136078.1' already exists. Skipping...
Folder 'GCA_038069015.1_PDT002136187.1' already exists. Skipping...
Folder 'GCA_038069075.1_PDT002136186.1' already exists. Skipping...
Folder 'GCA_038069135.1_PDT002136180.1' already exists. Skipping...
Folder 'GCA_038079575.1_PDT002136370.1' already exists. Skipping...
Folder 'GCA_038079595.1_PDT002136368.1' already exists. Skipping...
Folder 'GCA_038079615.1_PDT002136369.1' already exists. Skipping...
Folder 'GCA_038079635.1_PDT002136367.1' already exists. Skipping...
Folder 'GCA_038079655.1_PDT002136366.1' already exists. Skipping...
Folder 'GCA_038079675.1_PDT002136363.1' already exists. Skipping...
Folder 'GCA_038079715.1_PDT002136364.1' already exists. Skipping...
Folder 'GCA_038079735.1_PDT002136362.1' already exists. Skipping...
Folder 'GCA_038079755.1_PDT002136361.1' already exists. Skipping...
Folder 'GCA_038079775.1_PDT002136359.1' already exists. Skipping...
Folder 'GCA_038079795.1_PDT002136360.1' already exists. Skipping...
Folder 'GCA_038079815.1_PDT002136358.1' already exists. Skipping...
Folder 'GCA_038079835.1_PDT002136357.1' already exists. Skipping...
Folder 'GCA_038079855.1_PDT002136355.1' already exists. Skipping...
Folder 'GCA_038079875.1_PDT002136356.1' already exists. Skipping...
Folder 'GCA_038079895.1_PDT002136354.1' already exists. Skipping...
Folder 'GCA_038079935.1_PDT002136353.1' already exists. Skipping...
Folder 'GCA_038081355.1_PDT002136503.1' already exists. Skipping...
Folder 'GCA_038081375.1_PDT002136502.1' already exists. Skipping...
Folder 'GCA_038081495.1_PDT002136504.1' already exists. Skipping...
Folder 'GCA_038081575.1_PDT002136501.1' already exists. Skipping...
Folder 'GCA_038081595.1_PDT002136399.1' already exists. Skipping...
Folder 'GCA_038081635.1_PDT002136460.1' already exists. Skipping...
Folder 'GCA_038083635.1_PDT002136769.1' already exists. Skipping...
Folder 'GCA_038083675.1_PDT002136774.1' already exists. Skipping...
Folder 'GCA_038083695.1_PDT002136772.1' already exists. Skipping...
Folder 'GCA_038083815.1_PDT002136603.1' already exists. Skipping...
Folder 'GCA_038085115.1_PDT002136822.1' already exists. Skipping...
Folder 'GCA_038085195.1_PDT002136824.1' already exists. Skipping...
Folder 'GCA_038085215.1_PDT002136818.1' already exists. Skipping...
Folder 'GCA_038085355.1_PDT002136787.1' already exists. Skipping...
Folder 'GCA_038085385.1_PDT002136793.1' already exists. Skipping...
Folder 'GCA_038085575.1_PDT002136771.1' already exists. Skipping...
Folder 'GCA_038085635.1_PDT002136601.1' already exists. Skipping...
Folder 'GCA_038088165.1_PDT002135396.1' already exists. Skipping...
Folder 'GCA_038088185.1_PDT002135373.1' already exists. Skipping...
Folder 'GCA_038095175.1_PDT002137400.1' already exists. Skipping...
Folder 'GCA_038098685.1_PDT002137503.1' already exists. Skipping...
Folder 'GCA_038098705.1_PDT002137525.1' already exists. Skipping...
Folder 'GCA_038098765.1_PDT002137504.1' already exists. Skipping...
Folder 'GCA_038098865.1_PDT002137523.1' already exists. Skipping...
Folder 'GCA_038099245.1_PDT002137527.1' already exists. Skipping...
Folder 'GCA_038100375.1_PDT002137628.1' already exists. Skipping...
Folder 'GCA_038100515.1_PDT002137623.1' already exists. Skipping...
Folder 'GCA_038147835.1_PDT002138398.1' already exists. Skipping...
Folder 'GCA_038153705.1_PDT002138329.1' already exists. Skipping...
Folder 'GCA_038153785.1_PDT002138324.1' already exists. Skipping...
Folder 'GCA_038156155.1_PDT002138325.1' already exists. Skipping...
Folder 'GCA_038156295.1_PDT002138474.1' already exists. Skipping...
Folder 'GCA_038156335.1_PDT002138472.1' already exists. Skipping...
Folder 'GCA_038156355.1_PDT002138475.1' already exists. Skipping...
Folder 'GCA_038156375.1_PDT002138473.1' already exists. Skipping...
Folder 'GCA_038156395.1_PDT002138471.1' already exists. Skipping...
Folder 'GCA_038158475.1_PDT002138469.1' already exists. Skipping...
Folder 'GCA_038164525.1_PDT002138529.1' already exists. Skipping...
Folder 'GCA_038172395.1_PDT002138577.1' already exists. Skipping...
Folder 'GCA_038173515.1_PDT002138573.1' already exists. Skipping...
Folder 'GCA_038181065.1_ASM3818106v1' already exists. Skipping...
Folder 'GCA_038181085.1_ASM3818108v1' already exists. Skipping...
Folder 'GCA_038219545.1_PDT002138725.1' already exists. Skipping...
Folder 'GCA_038220055.1_PDT002138717.1' already exists. Skipping...

Retreiveing data: 111018it [00:18, 6674.36it/s]

Folder 'GCA_040284955.1_PDT002221305.1' already exists. Skipping...
Folder 'GCA_040284975.1_PDT002221303.1' already exists. Skipping...
Folder 'GCA_040284995.1_PDT002221304.1' already exists. Skipping...
Folder 'GCA_040285015.1_PDT002221302.1' already exists. Skipping...
Folder 'GCA_040286425.1_PDT002225231.1' already exists. Skipping...
Folder 'GCA_040286445.1_PDT002225227.1' already exists. Skipping...
Folder 'GCA_040286485.1_PDT002225226.1' already exists. Skipping...
Folder 'GCA_040288945.1_PDT002225395.1' already exists. Skipping...
Folder 'GCA_040288985.1_PDT002225396.1' already exists. Skipping...
Folder 'GCA_040289005.1_PDT002225403.1' already exists. Skipping...
Folder 'GCA_040305315.1_PDT002226602.1' already exists. Skipping...
Folder 'GCA_040305435.1_PDT002226683.1' already exists. Skipping...
Folder 'GCA_040306745.1_PDT002226706.1' already exists. Skipping...
Folder 'GCA_040308555.1_PDT002226710.1' already exists. Skipping...
Folder 'GCA_040308995.1_PDT002226700.1' already exists. Skipping...
Folder 'GCA_040309165.1_PDT002226685.1' already exists. Skipping...
Folder 'GCA_040309675.1_PDT002226638.1' already exists. Skipping...
Folder 'GCA_040311015.1_PDT002226684.1' already exists. Skipping...
Folder 'GCA_040311915.1_PDT002226812.1' already exists. Skipping...
Folder 'GCA_040311925.1_PDT002226701.1' already exists. Skipping...
Folder 'GCA_040311995.1_PDT002221313.1' already exists. Skipping...
Folder 'GCA_040312085.1_PDT002221311.1' already exists. Skipping...
Folder 'GCA_040312445.1_PDT002226804.1' already exists. Skipping...
Folder 'GCA_040312935.1_PDT002226896.1' already exists. Skipping...
Folder 'GCA_040313275.1_PDT002226895.1' already exists. Skipping...
Folder 'GCA_040313615.1_PDT002227016.1' already exists. Skipping...
Folder 'GCA_040314645.1_PDT002227100.1' already exists. Skipping...
Folder 'GCA_040314655.1_PDT002227108.1' already exists. Skipping...
Folder 'GCA_040314685.1_PDT002227106.1' already exists. Skipping...
Folder 'GCA_040314725.1_PDT002227020.1' already exists. Skipping...
Folder 'GCA_040314755.1_PDT002227019.1' already exists. Skipping...
Folder 'GCA_040314885.1_PDT002227032.1' already exists. Skipping...
Folder 'GCA_040314915.1_PDT002227037.1' already exists. Skipping...
Folder 'GCA_040315035.1_PDT002227110.1' already exists. Skipping...
Folder 'GCA_040315065.1_PDT002227028.1' already exists. Skipping...
Folder 'GCA_040315505.1_PDT002227034.1' already exists. Skipping...
Folder 'GCA_040316835.1_PDT002228021.1' already exists. Skipping...
Folder 'GCA_040316875.1_PDT002228001.1' already exists. Skipping...
Folder 'GCA_040316895.1_PDT002228215.1' already exists. Skipping...
Folder 'GCA_040316915.1_PDT002228213.1' already exists. Skipping...
Folder 'GCA_040316935.1_PDT002228211.1' already exists. Skipping...
Folder 'GCA_040316955.1_PDT002228212.1' already exists. Skipping...
Folder 'GCA_040316975.1_PDT002228207.1' already exists. Skipping...
Folder 'GCA_040316995.1_PDT002228209.1' already exists. Skipping...
Folder 'GCA_040317015.1_PDT002228208.1' already exists. Skipping...
Folder 'GCA_040317035.1_PDT002228206.1' already exists. Skipping...
Folder 'GCA_040317055.1_PDT002228204.1' already exists. Skipping...
Folder 'GCA_040317075.1_PDT002228205.1' already exists. Skipping...
Folder 'GCA_040317095.1_PDT002228203.1' already exists. Skipping...
Folder 'GCA_040317135.1_PDT002228155.1' already exists. Skipping...
Folder 'GCA_040317375.1_PDT002227993.1' already exists. Skipping...
Folder 'GCA_040317635.1_PDT002228216.1' already exists. Skipping...
Folder 'GCA_040317655.1_PDT002228222.1' already exists. Skipping...
Folder 'GCA_040317675.1_PDT002228224.1' already exists. Skipping...
Folder 'GCA_040317705.1_PDT002228210.1' already exists. Skipping...
Folder 'GCA_040324925.1_PDT002228219.1' already exists. Skipping...
Folder 'GCA_040330175.1_PDT002228342.1' already exists. Skipping...
Folder 'GCA_040332655.1_PDT002228840.1' already exists. Skipping...
Folder 'GCA_040332695.1_PDT002228839.1' already exists. Skipping...
Folder 'GCA_040332755.1_PDT002228835.1' already exists. Skipping...
Folder 'GCA_040332795.1_PDT002228834.1' already exists. Skipping...
Folder 'GCA_040332815.1_PDT002228767.1' already exists. Skipping...
Folder 'GCA_040332835.1_PDT002228723.1' already exists. Skipping...
Folder 'GCA_040332855.1_PDT002228722.1' already exists. Skipping...
Folder 'GCA_040332875.1_PDT002228721.1' already exists. Skipping...
Folder 'GCA_040332895.1_PDT002228705.1' already exists. Skipping...
Folder 'GCA_040335455.1_PDT002228906.1' already exists. Skipping...
Folder 'GCA_040335515.1_PDT002229163.1' already exists. Skipping...
Folder 'GCA_040335535.1_PDT002229161.1' already exists. Skipping...
Folder 'GCA_040335555.1_PDT002229160.1' already exists. Skipping...
Folder 'GCA_040335575.1_PDT002229154.1' already exists. Skipping...
Folder 'GCA_040335595.1_PDT002229159.1' already exists. Skipping...
Folder 'GCA_040335615.1_PDT002229151.1' already exists. Skipping...
Folder 'GCA_040335635.1_PDT002229153.1' already exists. Skipping...
Folder 'GCA_040335655.1_PDT002229152.1' already exists. Skipping...
Folder 'GCA_040335675.1_PDT002229132.1' already exists. Skipping...
Folder 'GCA_040335695.1_PDT002229099.1' already exists. Skipping...
Folder 'GCA_040335715.1_PDT002229127.1' already exists. Skipping...
Folder 'GCA_040335735.1_PDT002229097.1' already exists. Skipping...
Folder 'GCA_040335755.1_PDT002229130.1' already exists. Skipping...
Folder 'GCA_040335775.1_PDT002229088.1' already exists. Skipping...
Folder 'GCA_040337195.1_PDT002229164.1' already exists. Skipping...
Folder 'GCA_040337215.1_PDT002229165.1' already exists. Skipping...
Folder 'GCA_040340975.1_PDT002229347.1' already exists. Skipping...
Folder 'GCA_040340995.1_PDT002229346.1' already exists. Skipping...
Folder 'GCA_040345455.1_PDT002230134.1' already exists. Skipping...
Folder 'GCA_040345475.1_PDT002230132.1' already exists. Skipping...
Folder 'GCA_040345495.1_PDT002230135.1' already exists. Skipping...
Folder 'GCA_040345515.1_PDT002230131.1' already exists. Skipping...
Folder 'GCA_040345535.1_PDT002230227.1' already exists. Skipping...
Folder 'GCA_040345555.1_PDT002230106.1' already exists. Skipping...
Folder 'GCA_040345565.1_PDT002230113.1' already exists. Skipping...
Folder 'GCA_040345595.1_PDT002230097.1' already exists. Skipping...
Folder 'GCA_040345615.1_PDT002230226.1' already exists. Skipping...
Folder 'GCA_040346035.1_PDT002230224.1' already exists. Skipping...
Folder 'GCA_040346575.1_PDT002230447.1' already exists. Skipping...
Folder 'GCA_040346695.1_PDT002230445.1' already exists. Skipping...
Folder 'GCA_040346735.1_PDT002230645.1' already exists. Skipping...
Folder 'GCA_040352685.1_PDT002231214.1' already exists. Skipping...
Folder 'GCA_040352905.1_PDT002231197.1' already exists. Skipping...
Folder 'GCA_040352985.1_PDT002231194.1' already exists. Skipping...
Folder 'GCA_040353045.1_PDT002231188.1' already exists. Skipping...
Folder 'GCA_040353085.1_PDT002231187.1' already exists. Skipping...
Folder 'GCA_040353105.1_PDT002231185.1' already exists. Skipping...
Folder 'GCA_040353145.1_PDT002231184.1' already exists. Skipping...
Folder 'GCA_040353545.1_PDT002231162.1' already exists. Skipping...
Folder 'GCA_040354705.1_PDT002231981.1' already exists. Skipping...
Folder 'GCA_040355505.1_PDT002231982.1' already exists. Skipping...
Folder 'GCA_040355525.1_PDT002231901.1' already exists. Skipping...
Folder 'GCA_040355725.1_PDT002231610.1' already exists. Skipping...
Folder 'GCA_040355745.1_PDT002231585.1' already exists. Skipping...
Folder 'GCA_040355765.1_PDT002231582.1' already exists. Skipping...
Folder 'GCA_040355785.1_PDT002231583.1' already exists. Skipping...
Folder 'GCA_040355795.1_PDT002231540.1' already exists. Skipping...
Folder 'GCA_040355825.1_PDT002231579.1' already exists. Skipping...
Folder 'GCA_040357755.1_PDT002232064.1' already exists. Skipping...
Folder 'GCA_040358625.1_PDT002231980.1' already exists. Skipping...
Folder 'GCA_040358645.1_PDT002231979.1' already exists. Skipping...
Folder 'GCA_040358665.1_PDT002232059.1' already exists. Skipping...
Folder 'GCA_040358685.1_PDT002232068.1' already exists. Skipping...
Folder 'GCA_040359435.1_PDT002232067.1' already exists. Skipping...
Folder 'GCA_040359495.1_PDT002231977.1' already exists. Skipping...
Folder 'GCA_040359865.1_PDT002231631.1' already exists. Skipping...
Folder 'GCA_040359905.1_PDT002231626.1' already exists. Skipping...
Folder 'GCA_040359965.1_PDT002231608.1' already exists. Skipping...
Folder 'GCA_040360415.1_PDT002231612.1' already exists. Skipping...
Folder 'GCA_040360535.1_PDT002231587.1' already exists. Skipping...
Folder 'GCA_040360555.1_PDT002231542.1' already exists. Skipping...
Folder 'GCA_040360575.1_PDT002231586.1' already exists. Skipping...
Folder 'GCA_040360595.1_PDT002231541.1' already exists. Skipping...
Folder 'GCA_040360615.1_PDT002231584.1' already exists. Skipping...
Folder 'GCA_040360855.1_PDT002231539.1' already exists. Skipping...
Folder 'GCA_040368925.1_PDT002231628.1' already exists. Skipping...
Folder 'GCA_040401335.1_PDT002230096.1' already exists. Skipping...
Folder 'GCA_040404285.1_PDT002232395.1' already exists. Skipping...
Folder 'GCA_040404305.1_PDT002232389.1' already exists. Skipping...
Folder 'GCA_040405065.1_PDT002233016.1' already exists. Skipping...
Folder 'GCA_040405085.1_PDT002233012.1' already exists. Skipping...
Folder 'GCA_040405095.1_PDT002233015.1' already exists. Skipping...
Folder 'GCA_040405105.1_PDT002233014.1' already exists. Skipping...
Folder 'GCA_040405135.1_PDT002233013.1' already exists. Skipping...
Folder 'GCA_040405475.1_PDT002233112.1' already exists. Skipping...
Folder 'GCA_040409975.1_PDT002233345.1' already exists. Skipping...
Folder 'GCA_040410275.1_PDT002233324.1' already exists. Skipping...
Folder 'GCA_040410335.1_PDT002233323.1' already exists. Skipping...
Folder 'GCA_040410755.1_PDT002233298.1' already exists. Skipping...
Folder 'GCA_040410795.1_PDT002233294.1' already exists. Skipping...
Folder 'GCA_040410815.1_PDT002233292.1' already exists. Skipping...
Folder 'GCA_040411455.1_PDT002233234.1' already exists. Skipping...
Folder 'GCA_040412025.1_PDT002234133.1' already exists. Skipping...
Folder 'GCA_040412045.1_PDT002234113.1' already exists. Skipping...
Folder 'GCA_040412065.1_PDT002234022.1' already exists. Skipping...
Folder 'GCA_040412115.1_PDT002234028.1' already exists. Skipping...
Folder 'GCA_040412135.1_PDT002234039.1' already exists. Skipping...
Folder 'GCA_040412225.1_PDT002234135.1' already exists. Skipping...
Folder 'GCA_040412305.1_PDT002234130.1' already exists. Skipping...
Folder 'GCA_040412405.1_PDT002234132.1' already exists. Skipping...
Folder 'GCA_040421005.1_PDT002234326.1' already exists. Skipping...
Folder 'GCA_040421075.1_PDT002234294.1' already exists. Skipping...
Folder 'GCA_040421535.1_PDT002234297.1' already exists. Skipping...
Folder 'GCA_040422595.1_PDT002234387.1' already exists. Skipping...
Folder 'GCA_040423535.1_PDT002234416.1' already exists. Skipping...
Folder 'GCA_040424035.1_PDT002234481.1' already exists. Skipping...
Folder 'GCA_040424075.1_PDT002234479.1' already exists. Skipping...
Folder 'GCA_040425355.1_PDT002234572.1' already exists. Skipping...
Folder 'GCA_040434255.1_PDT002234707.1' already exists. Skipping...
Folder 'GCA_040434355.1_PDT002234703.1' already exists. Skipping...
Folder 'GCA_040435895.1_PDT002234573.1' already exists. Skipping...
Folder 'GCA_040439025.1_PDT002236811.1' already exists. Skipping...
Folder 'GCA_040439045.1_PDT002236863.1' already exists. Skipping...
Folder 'GCA_040439065.1_PDT002236879.1' already exists. Skipping...
Folder 'GCA_040439085.1_PDT002236857.1' already exists. Skipping...
Folder 'GCA_040439105.1_PDT002236900.1' already exists. Skipping...
Folder 'GCA_040439165.1_PDT002236858.1' already exists. Skipping...
Folder 'GCA_040439185.1_PDT002236806.1' already exists. Skipping...
Folder 'GCA_040439285.1_PDT002236895.1' already exists. Skipping...
Folder 'GCA_040440425.1_PDT002236829.1' already exists. Skipping...
Folder 'GCA_040440565.1_PDT002237237.1' already exists. Skipping...
Folder 'GCA_040440585.1_PDT002236926.1' already exists. Skipping...
Folder 'GCA_040441425.1_PDT002237253.1' already exists. Skipping...
Folder 'GCA_040441525.1_PDT002237250.1' already exists. Skipping...
Folder 'GCA_040441605.1_PDT002236925.1' already exists. Skipping...
Folder 'GCA_040441745.1_PDT002237238.1' already exists. Skipping...
Folder 'GCA_040441985.1_PDT002237246.1' already exists. Skipping...
Folder 'GCA_040442945.1_PDT002237548.1' already exists. Skipping...
Folder 'GCA_040442965.1_PDT002237630.1' already exists. Skipping...
Folder 'GCA_040442975.1_PDT002237632.1' already exists. Skipping...
Folder 'GCA_040443025.1_PDT002237549.1' already exists. Skipping...
Folder 'GCA_040447625.1_PDT002237776.1' already exists. Skipping...
Folder 'GCA_040447645.1_PDT002237943.1' already exists. Skipping...
Folder 'GCA_040448875.1_PDT002238119.1' already exists. Skipping...
Folder 'GCA_040448905.1_PDT002238120.1' already exists. Skipping...
Folder 'GCA_040448935.1_PDT002238173.1' already exists. Skipping...
Folder 'GCA_040448975.1_PDT002238165.1' already exists. Skipping...
Folder 'GCA_040448995.1_PDT002238171.1' already exists. Skipping...
Folder 'GCA_040449055.1_PDT002238168.1' already exists. Skipping...
Folder 'GCA_040449115.1_PDT002238164.1' already exists. Skipping...
Folder 'GCA_040449135.1_PDT002238162.1' already exists. Skipping...
Folder 'GCA_040450595.1_PDT002238139.1' already exists. Skipping...
Folder 'GCA_040450615.1_PDT002238138.1' already exists. Skipping...
Folder 'GCA_040451475.1_PDT002238137.1' already exists. Skipping...
Folder 'GCA_040452075.1_PDT002238413.1' already exists. Skipping...
Folder 'GCA_040452095.1_PDT002238405.1' already exists. Skipping...
Folder 'GCA_040452115.1_PDT002238194.1' already exists. Skipping...
Folder 'GCA_040452155.1_PDT002238223.1' already exists. Skipping...
Folder 'GCA_040452175.1_PDT002238193.1' already exists. Skipping...
Folder 'GCA_040452195.1_PDT002238192.1' already exists. Skipping...
Folder 'GCA_040452215.1_PDT002238184.1' already exists. Skipping...
Folder 'GCA_040452235.1_PDT002238183.1' already exists. Skipping...
Folder 'GCA_040452515.1_PDT002238589.1' already exists. Skipping...
Folder 'GCA_040452535.1_PDT002238584.1' already exists. Skipping...
Folder 'GCA_040452555.1_PDT002238582.1' already exists. Skipping...
Folder 'GCA_040452575.1_PDT002238579.1' already exists. Skipping...
Folder 'GCA_040452595.1_PDT002238581.1' already exists. Skipping...
Folder 'GCA_040452615.1_PDT002238577.1' already exists. Skipping...
Folder 'GCA_040453255.1_PDT002238580.1' already exists. Skipping...
Folder 'GCA_040453275.1_PDT002238585.1' already exists. Skipping...
Folder 'GCA_040453315.1_PDT002238576.1' already exists. Skipping...
Folder 'GCA_040453595.1_PDT002238583.1' already exists. Skipping...
Folder 'GCA_040453635.1_PDT002238588.1' already exists. Skipping...
Folder 'GCA_040453655.1_PDT002238578.1' already exists. Skipping...
Folder 'GCA_040454135.1_PDT002238586.1' already exists. Skipping...
Folder 'GCA_040454595.1_PDT002238587.1' already exists. Skipping...
Folder 'GCA_040500045.1_PDT002238394.1' already exists. Skipping...
Folder 'GCA_040500075.1_PDT002238182.1' already exists. Skipping...
Folder 'GCA_040500595.1_PDT002239186.1' already exists. Skipping...
Folder 'GCA_040500695.1_PDT002239341.1' already exists. Skipping...
Folder 'GCA_040502725.1_PDT002239342.1' already exists. Skipping...
Folder 'GCA_040503875.1_PDT002239793.1' already exists. Skipping...
Folder 'GCA_040503895.1_PDT002239796.1' already exists. Skipping...
Folder 'GCA_040503915.1_PDT002239783.1' already exists. Skipping...
Folder 'GCA_040503935.1_PDT002239788.1' already exists. Skipping...
Folder 'GCA_040503955.1_PDT002239809.1' already exists. Skipping...
Folder 'GCA_040504035.1_PDT002239736.1' already exists. Skipping...
Folder 'GCA_040504055.1_PDT002239732.1' already exists. Skipping...
Folder 'GCA_040504075.1_PDT002239739.1' already exists. Skipping...
Folder 'GCA_040504175.1_PDT002239775.1' already exists. Skipping...
Folder 'GCA_040504195.1_PDT002239765.1' already exists. Skipping...
Folder 'GCA_040504575.1_PDT002239834.1' already exists. Skipping...
Folder 'GCA_040504615.1_PDT002239830.1' already exists. Skipping...
Folder 'GCA_040504635.1_PDT002239824.1' already exists. Skipping...
Folder 'GCA_040504685.1_PDT002239827.1' already exists. Skipping...
Folder 'GCA_040504875.1_PDT002239735.1' already exists. Skipping...
Folder 'GCA_040504995.1_PDT002239847.1' already exists. Skipping...
Folder 'GCA_040505015.1_PDT002239848.1' already exists. Skipping...
Folder 'GCA_040505035.1_PDT002239842.1' already exists. Skipping...
Folder 'GCA_040505055.1_PDT002239844.1' already exists. Skipping...
Folder 'GCA_040505075.1_PDT002239845.1' already exists. Skipping...
Folder 'GCA_040505095.1_PDT002239841.1' already exists. Skipping...
Folder 'GCA_040505115.1_PDT002239840.1' already exists. Skipping...
Folder 'GCA_040505135.1_PDT002239839.1' already exists. Skipping...
Folder 'GCA_040505155.1_PDT002239837.1' already exists. Skipping...
Folder 'GCA_040505175.1_PDT002239833.1' already exists. Skipping...
Folder 'GCA_040505195.1_PDT002239823.1' already exists. Skipping...
Folder 'GCA_040505215.1_PDT002239835.1' already exists. Skipping...
Folder 'GCA_040505415.1_PDT002239826.1' already exists. Skipping...
Folder 'GCA_040505435.1_PDT002239838.1' already exists. Skipping...
Folder 'GCA_040505455.1_PDT002239836.1' already exists. Skipping...
Folder 'GCA_040505495.1_PDT002239832.1' already exists. Skipping...
Folder 'GCA_040505515.1_PDT002239825.1' already exists. Skipping...
Folder 'GCA_040505535.1_PDT002239815.1' already exists. Skipping...
Folder 'GCA_040514585.1_PDT002239914.1' already exists. Skipping...
Folder 'GCA_040514695.1_PDT002239912.1' already exists. Skipping...
Folder 'GCA_040514815.1_PDT002239903.1' already exists. Skipping...
Folder 'GCA_040514895.1_PDT002239901.1' already exists. Skipping...
Folder 'GCA_040514975.1_PDT002239895.1' already exists. Skipping...
Folder 'GCA_040514995.1_PDT002239894.1' already exists. Skipping...
Folder 'GCA_040515655.1_PDT002239846.1' already exists. Skipping...
Folder 'GCA_040515665.1_PDT002239843.1' already exists. Skipping...
Folder 'GCA_040515715.1_PDT002239831.1' already exists. Skipping...
Folder 'GCA_040515735.1_PDT002239828.1' already exists. Skipping...
Folder 'GCA_040515795.1_PDT002239820.1' already exists. Skipping...
Folder 'GCA_040515805.1_PDT002239817.1' already exists. Skipping...
Folder 'GCA_040515835.1_PDT002239812.1' already exists. Skipping...
Folder 'GCA_040516065.1_PDT002239909.1' already exists. Skipping...
Folder 'GCA_040517545.1_PDT002239781.1' already exists. Skipping...
Folder 'GCA_040517565.1_PDT002239810.1' already exists. Skipping...
Folder 'GCA_040517585.1_PDT002239813.1' already exists. Skipping...
Folder 'GCA_040517605.1_PDT002239822.1' already exists. Skipping...
Folder 'GCA_040517625.1_PDT002239814.1' already exists. Skipping...
Folder 'GCA_040518065.1_PDT002239816.1' already exists. Skipping...
Folder 'GCA_040518425.1_PDT002240239.1' already exists. Skipping...
Folder 'GCA_040518445.1_PDT002240327.1' already exists. Skipping...
Folder 'GCA_040518485.1_PDT002240258.1' already exists. Skipping...
Folder 'GCA_040520705.1_PDT002240442.1' already exists. Skipping...
Folder 'GCA_040520715.1_PDT002240471.1' already exists. Skipping...
Folder 'GCA_040520745.1_PDT002240437.1' already exists. Skipping...
Folder 'GCA_040520785.1_PDT002240428.1' already exists. Skipping...
Folder 'GCA_040520805.1_PDT002240435.1' already exists. Skipping...
Folder 'GCA_040520825.1_PDT002240445.1' already exists. Skipping...
Folder 'GCA_040520845.1_PDT002240441.1' already exists. Skipping...
Folder 'GCA_040521225.1_PDT002240436.1' already exists. Skipping...
Folder 'GCA_040521245.1_PDT002240440.1' already exists. Skipping...
Folder 'GCA_040521805.1_PDT002240448.1' already exists. Skipping...

Retreiveing data: 112359it [00:18, 6666.55it/s]

Folder 'GCA_041723845.1_PDT002352012.1' already exists. Skipping...
Folder 'GCA_041724105.1_PDT002352001.1' already exists. Skipping...
Folder 'GCA_041724945.1_PDT002351933.1' already exists. Skipping...
Folder 'GCA_041724955.1_PDT002351932.1' already exists. Skipping...
Folder 'GCA_041731575.1_PDT002361872.1' already exists. Skipping...
Folder 'GCA_041731585.1_PDT002361641.1' already exists. Skipping...
Folder 'GCA_041731615.1_PDT002361848.1' already exists. Skipping...
Folder 'GCA_041731635.1_PDT002361870.1' already exists. Skipping...
Folder 'GCA_041731755.1_PDT002361820.1' already exists. Skipping...
Folder 'GCA_041731765.1_PDT002361850.1' already exists. Skipping...
Folder 'GCA_041731795.1_PDT002361673.1' already exists. Skipping...
Folder 'GCA_041732495.1_PDT002361782.1' already exists. Skipping...
Folder 'GCA_041734245.1_PDT002361885.1' already exists. Skipping...
Folder 'GCA_041734255.1_PDT002361882.1' already exists. Skipping...
Folder 'GCA_041734265.1_PDT002361692.1' already exists. Skipping...
Folder 'GCA_041734325.1_PDT002361875.1' already exists. Skipping...
Folder 'GCA_041734355.1_PDT002361504.1' already exists. Skipping...
Folder 'GCA_041734375.1_PDT002361516.1' already exists. Skipping...
Folder 'GCA_041734395.1_PDT002361904.1' already exists. Skipping...
Folder 'GCA_041734415.1_PDT002361539.1' already exists. Skipping...
Folder 'GCA_041734435.1_PDT002361538.1' already exists. Skipping...
Folder 'GCA_041734455.1_PDT002361498.1' already exists. Skipping...
Folder 'GCA_041734485.1_PDT002361944.1' already exists. Skipping...
Folder 'GCA_041734505.1_PDT002361878.1' already exists. Skipping...
Folder 'GCA_041734525.1_PDT002361893.1' already exists. Skipping...
Folder 'GCA_041734545.1_PDT002361889.1' already exists. Skipping...
Folder 'GCA_041734565.1_PDT002361877.1' already exists. Skipping...
Folder 'GCA_041734585.1_PDT002361943.1' already exists. Skipping...
Folder 'GCA_041734605.1_PDT002361741.1' already exists. Skipping...
Folder 'GCA_041734625.1_PDT002361876.1' already exists. Skipping...
Folder 'GCA_041734655.1_PDT002361716.1' already exists. Skipping...
Folder 'GCA_041734675.1_PDT002361532.1' already exists. Skipping...
Folder 'GCA_041734705.1_PDT002361500.1' already exists. Skipping...
Folder 'GCA_041734795.1_PDT002361787.1' already exists. Skipping...
Folder 'GCA_041734815.1_PDT002361828.1' already exists. Skipping...
Folder 'GCA_041735715.1_PDT002361891.1' already exists. Skipping...
Folder 'GCA_041735735.1_PDT002361890.1' already exists. Skipping...
Folder 'GCA_041735755.1_PDT002361663.1' already exists. Skipping...
Folder 'GCA_041736115.1_PDT002361879.1' already exists. Skipping...
Folder 'GCA_041736135.1_PDT002361792.1' already exists. Skipping...
Folder 'GCA_041756455.1_PDT002363115.1' already exists. Skipping...
Folder 'GCA_041756715.1_PDT002363636.1' already exists. Skipping...
Folder 'GCA_041762725.1_PDT002362414.1' already exists. Skipping...
Folder 'GCA_041764615.1_PDT002362309.1' already exists. Skipping...
Folder 'GCA_041764635.1_PDT002362308.1' already exists. Skipping...
Folder 'GCA_041768845.1_PDT002361861.1' already exists. Skipping...
Folder 'GCA_041768935.1_PDT002361831.1' already exists. Skipping...
Folder 'GCA_041769195.1_PDT002361764.1' already exists. Skipping...
Folder 'GCA_041769325.1_PDT002361697.1' already exists. Skipping...
Folder 'GCA_041769335.1_PDT002361739.1' already exists. Skipping...
Folder 'GCA_041769645.1_PDT002361649.1' already exists. Skipping...
Folder 'GCA_041769665.1_PDT002361644.1' already exists. Skipping...
Folder 'GCA_041769765.1_PDT002361639.1' already exists. Skipping...
Folder 'GCA_041769825.1_PDT002361637.1' already exists. Skipping...
Folder 'GCA_041769865.1_PDT002361634.1' already exists. Skipping...
Folder 'GCA_041769965.1_PDT002361629.1' already exists. Skipping...
Folder 'GCA_041771605.1_PDT002364730.1' already exists. Skipping...
Folder 'GCA_041771645.1_PDT002364726.1' already exists. Skipping...
Folder 'GCA_041771725.1_PDT002364725.1' already exists. Skipping...
Folder 'GCA_041779995.1_PDT002365099.1' already exists. Skipping...
Folder 'GCA_041784365.1_PDT002364886.1' already exists. Skipping...
Folder 'GCA_041784445.1_PDT002364883.1' already exists. Skipping...
Folder 'GCA_041785535.1_PDT002364872.1' already exists. Skipping...
Folder 'GCA_041790305.1_PDT002361869.1' already exists. Skipping...
Folder 'GCA_041790385.1_PDT002361862.1' already exists. Skipping...
Folder 'GCA_041790505.1_PDT002361823.1' already exists. Skipping...
Folder 'GCA_041790945.1_PDT002361829.1' already exists. Skipping...
Folder 'GCA_041791205.1_PDT002361809.1' already exists. Skipping...
Folder 'GCA_041791475.1_PDT002361780.1' already exists. Skipping...
Folder 'GCA_041791675.1_PDT002361775.1' already exists. Skipping...
Folder 'GCA_041791895.1_PDT002361763.1' already exists. Skipping...
Folder 'GCA_041791915.1_PDT002361758.1' already exists. Skipping...
Folder 'GCA_041792035.1_PDT002361730.1' already exists. Skipping...
Folder 'GCA_041792195.1_PDT002361725.1' already exists. Skipping...
Folder 'GCA_041792375.1_PDT002361710.1' already exists. Skipping...
Folder 'GCA_041792665.1_PDT002361680.1' already exists. Skipping...
Folder 'GCA_041792845.1_PDT002361670.1' already exists. Skipping...
Folder 'GCA_041792915.1_PDT002361661.1' already exists. Skipping...
Folder 'GCA_041793155.1_PDT002361651.1' already exists. Skipping...
Folder 'GCA_041793275.1_PDT002361648.1' already exists. Skipping...
Folder 'GCA_041793315.1_PDT002361647.1' already exists. Skipping...
Folder 'GCA_041793445.1_PDT002361642.1' already exists. Skipping...
Folder 'GCA_041793475.1_PDT002361635.1' already exists. Skipping...
Folder 'GCA_041793575.1_PDT002361633.1' already exists. Skipping...
Folder 'GCA_041793655.1_PDT002361630.1' already exists. Skipping...
Folder 'GCA_041818775.1_PDT002362415.1' already exists. Skipping...
Folder 'GCA_041857155.1_PDT002366136.1' already exists. Skipping...
Folder 'GCA_041857165.1_PDT002366138.1' already exists. Skipping...
Folder 'GCA_041858145.1_PDT002366155.1' already exists. Skipping...
Folder 'GCA_041864305.1_PDT002366845.1' already exists. Skipping...
Folder 'GCA_041864345.1_PDT002366846.1' already exists. Skipping...
Folder 'GCA_041864365.1_PDT002366844.1' already exists. Skipping...
Folder 'GCA_041864385.1_PDT002366843.1' already exists. Skipping...
Folder 'GCA_041865195.1_PDT002366842.1' already exists. Skipping...
Folder 'GCA_041865235.1_PDT002366841.1' already exists. Skipping...
Folder 'GCA_041865675.1_PDT002366807.1' already exists. Skipping...
Folder 'GCA_041865695.1_PDT002366806.1' already exists. Skipping...
Folder 'GCA_041865725.1_PDT002366805.1' already exists. Skipping...
Folder 'GCA_041865785.1_PDT002366804.1' already exists. Skipping...
Folder 'GCA_041866125.1_PDT002366550.1' already exists. Skipping...
Folder 'GCA_041866165.1_PDT002366800.1' already exists. Skipping...
Folder 'GCA_041868935.1_PDT002353476.1' already exists. Skipping...
Folder 'GCA_041869305.1_PDT002371104.1' already exists. Skipping...
Folder 'GCA_041869325.1_PDT002371103.1' already exists. Skipping...
Folder 'GCA_041869365.1_PDT002371099.1' already exists. Skipping...
Folder 'GCA_041869445.1_PDT002371107.1' already exists. Skipping...
Folder 'GCA_041874495.1_PDT002372677.1' already exists. Skipping...
Folder 'GCA_041874525.1_PDT002372672.1' already exists. Skipping...
Folder 'GCA_041874615.1_PDT002372667.1' already exists. Skipping...
Folder 'GCA_041874645.1_PDT002372670.1' already exists. Skipping...
Folder 'GCA_041875135.1_PDT002372674.1' already exists. Skipping...
Folder 'GCA_041875885.1_PDT002372833.1' already exists. Skipping...
Folder 'GCA_041875905.1_PDT002372832.1' already exists. Skipping...
Folder 'GCA_041876065.1_PDT002372668.1' already exists. Skipping...
Folder 'GCA_041876135.1_PDT002372664.1' already exists. Skipping...
Folder 'GCA_041876785.1_PDT002372666.1' already exists. Skipping...
Folder 'GCA_041882285.1_PDT002373659.1' already exists. Skipping...
Folder 'GCA_041883645.1_PDT002373615.1' already exists. Skipping...
Folder 'GCA_041883795.1_PDT002373607.1' already exists. Skipping...
Folder 'GCA_041883855.1_PDT002373608.1' already exists. Skipping...
Folder 'GCA_041884325.1_PDT002373566.1' already exists. Skipping...
Folder 'GCA_041884345.1_PDT002373564.1' already exists. Skipping...
Folder 'GCA_041884365.1_PDT002373562.1' already exists. Skipping...
Folder 'GCA_041884465.1_PDT002373561.1' already exists. Skipping...
Folder 'GCA_041884785.1_PDT002373548.1' already exists. Skipping...
Folder 'GCA_041884995.1_PDT002373532.1' already exists. Skipping...
Folder 'GCA_041885135.1_PDT002373525.1' already exists. Skipping...
Folder 'GCA_041885455.1_PDT002373500.1' already exists. Skipping...
Folder 'GCA_041885785.1_PDT002373479.1' already exists. Skipping...
Folder 'GCA_041886715.1_PDT002373361.1' already exists. Skipping...
Folder 'GCA_041886755.1_PDT002373355.1' already exists. Skipping...
Folder 'GCA_041886795.1_PDT002373344.1' already exists. Skipping...
Folder 'GCA_041887775.1_PDT002373334.1' already exists. Skipping...
Folder 'GCA_041887795.1_PDT002373331.1' already exists. Skipping...
Folder 'GCA_041887815.1_PDT002373330.1' already exists. Skipping...
Folder 'GCA_041889475.1_PDT002344952.1' already exists. Skipping...
Folder 'GCA_041889495.1_PDT002344971.1' already exists. Skipping...
Folder 'GCA_041890125.1_PDT002374787.1' already exists. Skipping...
Folder 'GCA_041890315.1_PDT002374786.1' already exists. Skipping...
Folder 'GCA_041890325.1_PDT002374849.1' already exists. Skipping...
Folder 'GCA_041894865.1_PDT002376957.1' already exists. Skipping...
Folder 'GCA_041895485.1_PDT002376923.1' already exists. Skipping...
Folder 'GCA_041895505.1_PDT002376921.1' already exists. Skipping...
Folder 'GCA_041895525.1_PDT002376919.1' already exists. Skipping...
Folder 'GCA_041895545.1_PDT002376918.1' already exists. Skipping...
Folder 'GCA_041897115.1_PDT002376956.1' already exists. Skipping...
Folder 'GCA_041897285.1_PDT002376958.1' already exists. Skipping...
Folder 'GCA_041900505.1_PDT002378692.1' already exists. Skipping...
Folder 'GCA_041904685.1_ASM4190468v1' already exists. Skipping...
Folder 'GCA_041904785.1_ASM4190478v1' already exists. Skipping...
Folder 'GCA_041904805.1_ASM4190480v1' already exists. Skipping...
Folder 'GCA_041904825.1_ASM4190482v1' already exists. Skipping...
Folder 'GCA_042140545.1_PDT002389375.1' already exists. Skipping...
Folder 'GCA_042140595.1_PDT002389387.1' already exists. Skipping...
Folder 'GCA_042140615.1_PDT002389385.1' already exists. Skipping...
Folder 'GCA_042140635.1_PDT002388940.1' already exists. Skipping...
Folder 'GCA_042140675.1_PDT002388894.1' already exists. Skipping...
Folder 'GCA_042140695.1_PDT002388939.1' already exists. Skipping...
Folder 'GCA_042140715.1_PDT002388914.1' already exists. Skipping...
Folder 'GCA_042140735.1_PDT002389369.1' already exists. Skipping...
Folder 'GCA_042140795.1_PDT002388890.1' already exists. Skipping...
Folder 'GCA_042140815.1_PDT002388891.1' already exists. Skipping...
Folder 'GCA_042140855.1_PDT002388888.1' already exists. Skipping...
Folder 'GCA_042140975.1_PDT002388880.1' already exists. Skipping...
Folder 'GCA_042141075.1_PDT002388865.1' already exists. Skipping...
Folder 'GCA_042141225.1_PDT002388869.1' already exists. Skipping...
Folder 'GCA_042142085.1_PDT002389377.1' already exists. Skipping...
Folder 'GCA_042142125.1_PDT002389376.1' already exists. Skipping...
Folder 'GCA_042142145.1_PDT002389370.1' already exists. Skipping...
Folder 'GCA_042142375.1_PDT002388842.1' already exists. Skipping...
Folder 'GCA_042146275.1_PDT002388877.1' already exists. Skipping...
Folder 'GCA_042146585.1_PDT002388856.1' already exists. Skipping...
Folder 'GCA_042147085.1_PDT002388851.1' already exists. Skipping...
Folder 'GCA_042147205.1_PDT002388846.1' already exists. Skipping...
Folder 'GCA_042147275.1_PDT002388839.1' already exists. Skipping...
Folder 'GCA_042147295.1_PDT002388841.1' already exists. Skipping...
Folder 'GCA_042147515.1_PDT002388824.1' already exists. Skipping...
Folder 'GCA_042147615.1_PDT002388820.1' already exists. Skipping...
Folder 'GCA_042150275.1_PDT002388425.1' already exists. Skipping...
Folder 'GCA_042150285.1_PDT002388424.1' already exists. Skipping...
Folder 'GCA_042150315.1_PDT002388415.1' already exists. Skipping...
Folder 'GCA_042150345.1_PDT002388407.1' already exists. Skipping...
Folder 'GCA_042150355.1_PDT002388423.1' already exists. Skipping...
Folder 'GCA_042150805.1_PDT002390362.1' already exists. Skipping...
Folder 'GCA_042151785.1_PDT002390356.1' already exists. Skipping...
Folder 'GCA_042151825.1_PDT002390347.1' already exists. Skipping...
Folder 'GCA_042152835.1_PDT002390348.1' already exists. Skipping...
Folder 'GCA_042152855.1_PDT002390326.1' already exists. Skipping...
Folder 'GCA_042152895.1_PDT002390322.1' already exists. Skipping...
Folder 'GCA_042152955.1_PDT002390315.1' already exists. Skipping...
Folder 'GCA_042153065.1_PDT002390298.1' already exists. Skipping...
Folder 'GCA_042160555.1_PDT002388231.1' already exists. Skipping...
Folder 'GCA_042160685.1_PDT002388225.1' already exists. Skipping...
Folder 'GCA_042160725.1_PDT002388223.1' already exists. Skipping...
Folder 'GCA_042161185.1_PDT002388198.1' already exists. Skipping...
Folder 'GCA_042161265.1_PDT002388195.1' already exists. Skipping...
Folder 'GCA_042161305.1_PDT002388194.1' already exists. Skipping...
Folder 'GCA_042161325.1_PDT002388188.1' already exists. Skipping...
Folder 'GCA_042161345.1_PDT002388186.1' already exists. Skipping...
Folder 'GCA_042161405.1_PDT002388183.1' already exists. Skipping...
Folder 'GCA_042161475.1_PDT002388177.1' already exists. Skipping...
Folder 'GCA_042161575.1_PDT002388170.1' already exists. Skipping...
Folder 'GCA_042161615.1_PDT002388166.1' already exists. Skipping...
Folder 'GCA_042161625.1_PDT002388168.1' already exists. Skipping...
Folder 'GCA_042161775.1_PDT002388154.1' already exists. Skipping...
Folder 'GCA_042161895.1_PDT002388150.1' already exists. Skipping...
Folder 'GCA_042161915.1_PDT002388139.1' already exists. Skipping...
Folder 'GCA_042161935.1_PDT002388138.1' already exists. Skipping...
Folder 'GCA_042161995.1_PDT002388140.1' already exists. Skipping...
Folder 'GCA_042162015.1_PDT002388137.1' already exists. Skipping...
Folder 'GCA_042163535.1_PDT002388077.1' already exists. Skipping...
Folder 'GCA_042163555.1_PDT002388075.1' already exists. Skipping...
Folder 'GCA_042163575.1_PDT002388076.1' already exists. Skipping...
Folder 'GCA_042164435.1_PDT002387791.1' already exists. Skipping...
Folder 'GCA_042164495.1_PDT002387788.1' already exists. Skipping...
Folder 'GCA_042164515.1_PDT002387786.1' already exists. Skipping...
Folder 'GCA_042164595.1_PDT002387779.1' already exists. Skipping...
Folder 'GCA_042164625.1_PDT002387782.1' already exists. Skipping...
Folder 'GCA_042164735.1_PDT002387774.1' already exists. Skipping...
Folder 'GCA_042164785.1_PDT002387773.1' already exists. Skipping...
Folder 'GCA_042164935.1_PDT002387764.1' already exists. Skipping...
Folder 'GCA_042164955.1_PDT002387765.1' already exists. Skipping...
Folder 'GCA_042165015.1_PDT002387761.1' already exists. Skipping...
Folder 'GCA_042166395.1_PDT002387682.1' already exists. Skipping...
Folder 'GCA_042166555.1_PDT002387544.1' already exists. Skipping...
Folder 'GCA_042166695.1_PDT002387488.1' already exists. Skipping...
Folder 'GCA_042166715.1_PDT002387487.1' already exists. Skipping...
Folder 'GCA_042166755.1_PDT002387482.1' already exists. Skipping...
Folder 'GCA_042166775.1_PDT002387485.1' already exists. Skipping...
Folder 'GCA_042166835.1_PDT002387480.1' already exists. Skipping...
Folder 'GCA_042166875.1_PDT002387476.1' already exists. Skipping...
Folder 'GCA_042167135.1_PDT002387462.1' already exists. Skipping...
Folder 'GCA_042167745.1_PDT002387448.1' already exists. Skipping...
Folder 'GCA_042168085.1_PDT002387420.1' already exists. Skipping...
Folder 'GCA_042168105.1_PDT002387419.1' already exists. Skipping...
Folder 'GCA_042168205.1_PDT002387413.1' already exists. Skipping...
Folder 'GCA_042168245.1_PDT002387412.1' already exists. Skipping...
Folder 'GCA_042168265.1_PDT002387411.1' already exists. Skipping...
Folder 'GCA_042168285.1_PDT002390521.1' already exists. Skipping...
Folder 'GCA_042168365.1_PDT002387408.1' already exists. Skipping...
Folder 'GCA_042168425.1_PDT002387407.1' already exists. Skipping...
Folder 'GCA_042168455.1_PDT002387405.1' already exists. Skipping...
Folder 'GCA_042168505.1_PDT002387404.1' already exists. Skipping...
Folder 'GCA_042168545.1_PDT002387401.1' already exists. Skipping...
Folder 'GCA_042168565.1_PDT002387400.1' already exists. Skipping...
Folder 'GCA_042168625.1_PDT002387396.1' already exists. Skipping...
Folder 'GCA_042168725.1_PDT002387393.1' already exists. Skipping...
Folder 'GCA_042168765.1_PDT002387388.1' already exists. Skipping...
Folder 'GCA_042168785.1_PDT002387389.1' already exists. Skipping...
Folder 'GCA_042168825.1_PDT002387387.1' already exists. Skipping...
Folder 'GCA_042168845.1_PDT002387385.1' already exists. Skipping...
Folder 'GCA_042168925.1_PDT002387383.1' already exists. Skipping...
Folder 'GCA_042168945.1_PDT002387382.1' already exists. Skipping...
Folder 'GCA_042168985.1_PDT002387379.1' already exists. Skipping...
Folder 'GCA_042169065.1_PDT002387375.1' already exists. Skipping...
Folder 'GCA_042169125.1_PDT002387374.1' already exists. Skipping...
Folder 'GCA_042169225.1_PDT002387367.1' already exists. Skipping...
Folder 'GCA_042169245.1_PDT002387366.1' already exists. Skipping...
Folder 'GCA_042169285.1_PDT002390655.1' already exists. Skipping...
Folder 'GCA_042169305.1_PDT002390654.1' already exists. Skipping...
Folder 'GCA_042169345.1_PDT002390647.1' already exists. Skipping...
Folder 'GCA_042169365.1_PDT002390646.1' already exists. Skipping...
Folder 'GCA_042169445.1_PDT002390635.1' already exists. Skipping...
Folder 'GCA_042169505.1_PDT002390630.1' already exists. Skipping...
Folder 'GCA_042169525.1_PDT002390628.1' already exists. Skipping...
Folder 'GCA_042169545.1_PDT002390627.1' already exists. Skipping...
Folder 'GCA_042169625.1_PDT002390624.1' already exists. Skipping...
Folder 'GCA_042169645.1_PDT002390622.1' already exists. Skipping...
Folder 'GCA_042169665.1_PDT002390621.1' already exists. Skipping...
Folder 'GCA_042169685.1_PDT002390618.1' already exists. Skipping...
Folder 'GCA_042169705.1_PDT002390607.1' already exists. Skipping...
Folder 'GCA_042169715.1_PDT002390609.1' already exists. Skipping...
Folder 'GCA_042169885.1_PDT002390587.1' already exists. Skipping...
Folder 'GCA_042169905.1_PDT002390543.1' already exists. Skipping...
Folder 'GCA_042169945.1_PDT002390537.1' already exists. Skipping...
Folder 'GCA_042170025.1_PDT002390532.1' already exists. Skipping...
Folder 'GCA_042170045.1_PDT002390530.1' already exists. Skipping...
Folder 'GCA_042170145.1_PDT002390526.1' already exists. Skipping...
Folder 'GCA_042170165.1_PDT002390525.1' already exists. Skipping...
Folder 'GCA_042170185.1_PDT002390524.1' already exists. Skipping...
Folder 'GCA_042170265.1_PDT002390519.1' already exists. Skipping...
Folder 'GCA_042170305.1_PDT002390518.1' already exists. Skipping...
Folder 'GCA_042170325.1_PDT002390516.1' already exists. Skipping...
Folder 'GCA_042170355.1_PDT002390497.1' already exists. Skipping...
Folder 'GCA_042170405.1_PDT002390492.1' already exists. Skipping...
Folder 'GCA_042174725.1_PDT002390796.1' already exists. Skipping...
Folder 'GCA_042181705.1_PDT002386374.1' already exists. Skipping...
Folder 'GCA_042181745.1_PDT002386371.1' already exists. Skipping...
Folder 'GCA_042181985.1_PDT002386362.1' already exists. Skipping...
Folder 'GCA_042182045.1_PDT002386359.1' already exists. Skipping...
Folder 'GCA_042182145.1_PDT002386353.1' already exists. Skipping...
Folder 'GCA_042182205.1_PDT002386348.1' already exists. Skipping...
Folder 'GCA_042182275.1_PDT002386346.1' already exists. Skipping...
Folder 'GCA_042182295.1_PDT002386343.1' already exists. Skipping...

Retreiveing data: 113696it [00:18, 6658.47it/s]

Folder 'GCA_043659135.1_ASM4365913v1' already exists. Skipping...
Folder 'GCA_043659155.1_ASM4365915v1' already exists. Skipping...
Folder 'GCA_043659175.1_ASM4365917v1' already exists. Skipping...
Folder 'GCA_043659185.1_ASM4365918v1' already exists. Skipping...
Folder 'GCA_043659195.1_ASM4365919v1' already exists. Skipping...
Folder 'GCA_043659215.1_ASM4365921v1' already exists. Skipping...
Folder 'GCA_043659355.1_ASM4365935v1' already exists. Skipping...
Folder 'GCA_043659375.1_ASM4365937v1' already exists. Skipping...
Folder 'GCA_043659395.1_ASM4365939v1' already exists. Skipping...
Folder 'GCA_043659405.1_ASM4365940v1' already exists. Skipping...
Folder 'GCA_043659415.1_ASM4365941v1' already exists. Skipping...
Folder 'GCA_043660755.1_ASM4366075v1' already exists. Skipping...
Folder 'GCA_043660815.1_ASM4366081v1' already exists. Skipping...
Folder 'GCA_043660835.1_ASM4366083v1' already exists. Skipping...
Folder 'GCA_043706545.1_PDT002256030.1' already exists. Skipping...
Folder 'GCA_043706565.1_PDT002301297.1' already exists. Skipping...
Folder 'GCA_043706585.1_PDT002256029.1' already exists. Skipping...
Folder 'GCA_043706625.1_PDT002256033.1' already exists. Skipping...
Folder 'GCA_043706645.1_PDT002256026.1' already exists. Skipping...
Folder 'GCA_043706665.1_PDT002256027.1' already exists. Skipping...
Folder 'GCA_043706685.1_PDT002256025.1' already exists. Skipping...
Folder 'GCA_043706705.1_PDT002256023.1' already exists. Skipping...
Folder 'GCA_043706725.1_PDT002256019.1' already exists. Skipping...
Folder 'GCA_043706745.1_PDT002256022.1' already exists. Skipping...
Folder 'GCA_043706755.1_PDT002256024.1' already exists. Skipping...
Folder 'GCA_043780415.1_PDT002301288.1' already exists. Skipping...
Folder 'GCA_043793225.1_PDT002427544.1' already exists. Skipping...
Folder 'GCA_043793635.1_PDT002427303.1' already exists. Skipping...
Folder 'GCA_043793655.1_PDT002427302.1' already exists. Skipping...
Folder 'GCA_043793675.1_PDT002426942.1' already exists. Skipping...
Folder 'GCA_043793745.1_PDT002426936.1' already exists. Skipping...
Folder 'GCA_043793785.1_PDT002426928.1' already exists. Skipping...
Folder 'GCA_043793845.1_PDT002426925.1' already exists. Skipping...
Folder 'GCA_043796455.1_PDT002427549.1' already exists. Skipping...
Folder 'GCA_043796475.1_PDT002427548.1' already exists. Skipping...
Folder 'GCA_043870835.1_PDT002427703.1' already exists. Skipping...
Folder 'GCA_043876915.1_PDT002301296.1' already exists. Skipping...
Folder 'GCA_043890645.1_PDT002301438.1' already exists. Skipping...
Folder 'GCA_043890665.1_PDT002301440.1' already exists. Skipping...
Folder 'GCA_043890705.1_PDT002301436.1' already exists. Skipping...
Folder 'GCA_043890725.1_PDT002301439.1' already exists. Skipping...
Folder 'GCA_043890745.1_PDT002301433.1' already exists. Skipping...
Folder 'GCA_043898065.1_PDT002428478.1' already exists. Skipping...
Folder 'GCA_043898085.1_PDT002428455.1' already exists. Skipping...
Folder 'GCA_043898105.1_PDT002428467.1' already exists. Skipping...
Folder 'GCA_043898145.1_PDT002428453.1' already exists. Skipping...
Folder 'GCA_043898165.1_PDT002428109.1' already exists. Skipping...
Folder 'GCA_043898185.1_PDT002428116.1' already exists. Skipping...
Folder 'GCA_043898205.1_PDT002428106.1' already exists. Skipping...
Folder 'GCA_043898225.1_PDT002428102.1' already exists. Skipping...
Folder 'GCA_043898305.1_PDT002428097.1' already exists. Skipping...
Folder 'GCA_043911225.1_PDT002429304.1' already exists. Skipping...
Folder 'GCA_043911325.1_PDT002429288.1' already exists. Skipping...
Folder 'GCA_043911345.1_PDT002429295.1' already exists. Skipping...
Folder 'GCA_043911445.1_PDT002429291.1' already exists. Skipping...
Folder 'GCA_043911465.1_PDT002429293.1' already exists. Skipping...
Folder 'GCA_043911525.1_PDT002429289.1' already exists. Skipping...
Folder 'GCA_043911545.1_PDT002429286.1' already exists. Skipping...
Folder 'GCA_043911665.1_PDT002429279.1' already exists. Skipping...
Folder 'GCA_043911685.1_PDT002429278.1' already exists. Skipping...
Folder 'GCA_043920715.1_PDT002301306.1' already exists. Skipping...
Folder 'GCA_043920745.1_PDT002301302.1' already exists. Skipping...
Folder 'GCA_043920775.1_PDT002301301.1' already exists. Skipping...
Folder 'GCA_043923415.1_PDT002301338.1' already exists. Skipping...
Folder 'GCA_043923435.1_PDT002301336.1' already exists. Skipping...
Folder 'GCA_043923455.1_PDT002301333.1' already exists. Skipping...
Folder 'GCA_043923475.1_PDT002301332.1' already exists. Skipping...
Folder 'GCA_043923495.1_PDT002301335.1' already exists. Skipping...
Folder 'GCA_043923515.1_PDT002301331.1' already exists. Skipping...
Folder 'GCA_043923535.1_PDT002301326.1' already exists. Skipping...
Folder 'GCA_043923555.1_PDT002301328.1' already exists. Skipping...
Folder 'GCA_043923575.1_PDT002301325.1' already exists. Skipping...
Folder 'GCA_043923595.1_PDT002301323.1' already exists. Skipping...
Folder 'GCA_043923615.1_PDT002301322.1' already exists. Skipping...
Folder 'GCA_043923635.1_PDT002301321.1' already exists. Skipping...
Folder 'GCA_043923655.1_PDT002301316.1' already exists. Skipping...
Folder 'GCA_043923665.1_PDT002301318.1' already exists. Skipping...
Folder 'GCA_043923695.1_PDT002301312.1' already exists. Skipping...
Folder 'GCA_043923775.1_PDT002301311.1' already exists. Skipping...
Folder 'GCA_043923795.1_PDT002429868.1' already exists. Skipping...
Folder 'GCA_043923815.1_PDT002429820.1' already exists. Skipping...
Folder 'GCA_043923895.1_PDT002429832.1' already exists. Skipping...
Folder 'GCA_043923975.1_PDT002429823.1' already exists. Skipping...
Folder 'GCA_043927435.1_PDT002429876.1' already exists. Skipping...
Folder 'GCA_043931855.1_PDT002429880.1' already exists. Skipping...
Folder 'GCA_043933845.1_PDT002430115.1' already exists. Skipping...
Folder 'GCA_043933885.1_PDT002430118.1' already exists. Skipping...
Folder 'GCA_043933905.1_PDT002430114.1' already exists. Skipping...
Folder 'GCA_043933945.1_PDT002430109.1' already exists. Skipping...
Folder 'GCA_043934025.1_PDT002430113.1' already exists. Skipping...
Folder 'GCA_043934815.1_PDT002430110.1' already exists. Skipping...
Folder 'GCA_043934855.1_PDT002430145.1' already exists. Skipping...
Folder 'GCA_043944235.1_ASM4394423v1' already exists. Skipping...
Folder 'GCA_043944245.1_ASM4394424v1' already exists. Skipping...
Folder 'GCA_043944265.1_ASM4394426v1' already exists. Skipping...
Folder 'GCA_043944315.1_ASM4394431v1' already exists. Skipping...
Folder 'GCA_043944325.1_ASM4394432v1' already exists. Skipping...
Folder 'GCA_043944335.1_ASM4394433v1' already exists. Skipping...
Folder 'GCA_043944375.1_ASM4394437v1' already exists. Skipping...
Folder 'GCA_043944395.1_ASM4394439v1' already exists. Skipping...
Folder 'GCA_043944415.1_ASM4394441v1' already exists. Skipping...
Folder 'GCA_043944475.1_ASM4394447v1' already exists. Skipping...
Folder 'GCA_043944525.1_ASM4394452v1' already exists. Skipping...
Folder 'GCA_043944555.1_ASM4394455v1' already exists. Skipping...
Folder 'GCA_043944565.1_ASM4394456v1' already exists. Skipping...
Folder 'GCA_043944675.1_ASM4394467v1' already exists. Skipping...
Folder 'GCA_043944765.1_ASM4394476v1' already exists. Skipping...
Folder 'GCA_043944805.1_ASM4394480v1' already exists. Skipping...
Folder 'GCA_043944835.1_ASM4394483v1' already exists. Skipping...
Folder 'GCA_043944865.1_ASM4394486v1' already exists. Skipping...
Folder 'GCA_043944895.1_ASM4394489v1' already exists. Skipping...
Folder 'GCA_043944955.1_ASM4394495v1' already exists. Skipping...
Folder 'GCA_043945005.1_ASM4394500v1' already exists. Skipping...
Folder 'GCA_043945615.1_ASM4394561v1' already exists. Skipping...
Folder 'GCA_043945625.1_ASM4394562v1' already exists. Skipping...
Folder 'GCA_043945635.1_ASM4394563v1' already exists. Skipping...
Folder 'GCA_043945655.1_ASM4394565v1' already exists. Skipping...
Folder 'GCA_043945705.1_ASM4394570v1' already exists. Skipping...
Folder 'GCA_043945735.1_ASM4394573v1' already exists. Skipping...
Folder 'GCA_043945745.1_ASM4394574v1' already exists. Skipping...
Folder 'GCA_043945775.1_ASM4394577v1' already exists. Skipping...
Folder 'GCA_043945785.1_ASM4394578v1' already exists. Skipping...
Folder 'GCA_043945795.1_ASM4394579v1' already exists. Skipping...
Folder 'GCA_043945835.1_ASM4394583v1' already exists. Skipping...
Folder 'GCA_043945855.1_ASM4394585v1' already exists. Skipping...
Folder 'GCA_043945865.1_ASM4394586v1' already exists. Skipping...
Folder 'GCA_043945895.1_ASM4394589v1' already exists. Skipping...
Folder 'GCA_043945915.1_ASM4394591v1' already exists. Skipping...
Folder 'GCA_043945935.1_ASM4394593v1' already exists. Skipping...
Folder 'GCA_043946465.1_ASM4394646v1' already exists. Skipping...
Folder 'GCA_043946475.1_ASM4394647v1' already exists. Skipping...
Folder 'GCA_043946505.1_ASM4394650v1' already exists. Skipping...
Folder 'GCA_043946515.1_ASM4394651v1' already exists. Skipping...
Folder 'GCA_043946555.1_ASM4394655v1' already exists. Skipping...
Folder 'GCA_043946595.1_ASM4394659v1' already exists. Skipping...
Folder 'GCA_043946615.1_ASM4394661v1' already exists. Skipping...
Folder 'GCA_043946635.1_ASM4394663v1' already exists. Skipping...
Folder 'GCA_043946655.1_ASM4394665v1' already exists. Skipping...
Folder 'GCA_043946675.1_ASM4394667v1' already exists. Skipping...
Folder 'GCA_043946695.1_ASM4394669v1' already exists. Skipping...
Folder 'GCA_043946715.1_ASM4394671v1' already exists. Skipping...
Folder 'GCA_043946735.1_ASM4394673v1' already exists. Skipping...
Folder 'GCA_043946755.1_ASM4394675v1' already exists. Skipping...
Folder 'GCA_043946775.1_ASM4394677v1' already exists. Skipping...
Folder 'GCA_043946795.1_ASM4394679v1' already exists. Skipping...
Folder 'GCA_043957875.1_PDT002432303.1' already exists. Skipping...
Folder 'GCA_043957895.1_PDT002432304.1' already exists. Skipping...
Folder 'GCA_043957975.1_PDT002432298.1' already exists. Skipping...
Folder 'GCA_043957995.1_PDT002432300.1' already exists. Skipping...
Folder 'GCA_043958235.1_PDT002432197.1' already exists. Skipping...
Folder 'GCA_043958635.1_PDT002432170.1' already exists. Skipping...
Folder 'GCA_043958715.1_PDT002432167.1' already exists. Skipping...
Folder 'GCA_043958815.1_PDT002432164.1' already exists. Skipping...
Folder 'GCA_043958855.1_PDT002432161.1' already exists. Skipping...
Folder 'GCA_043958915.1_PDT002432159.1' already exists. Skipping...
Folder 'GCA_043958995.1_PDT002432156.1' already exists. Skipping...
Folder 'GCA_043959755.1_PDT002432108.1' already exists. Skipping...
Folder 'GCA_043959855.1_PDT002431699.1' already exists. Skipping...
Folder 'GCA_043960015.1_PDT002430580.1' already exists. Skipping...
Folder 'GCA_043960045.1_PDT002430593.1' already exists. Skipping...
Folder 'GCA_043960075.1_PDT002430582.1' already exists. Skipping...
Folder 'GCA_043960455.1_PDT002430554.1' already exists. Skipping...
Folder 'GCA_043960515.1_PDT002430534.1' already exists. Skipping...
Folder 'GCA_043960615.1_PDT002430525.1' already exists. Skipping...
Folder 'GCA_043960695.1_PDT002430521.1' already exists. Skipping...
Folder 'GCA_043987215.1_PDT002407095.1' already exists. Skipping...
Folder 'GCA_043987375.1_PDT002403945.1' already exists. Skipping...
Folder 'GCA_043999255.1_PDT002347345.1' already exists. Skipping...
Folder 'GCA_043999275.1_PDT002347442.1' already exists. Skipping...
Folder 'GCA_044005965.1_PDT002439333.1' already exists. Skipping...
Folder 'GCA_044006115.1_PDT002439290.1' already exists. Skipping...
Folder 'GCA_044006135.1_PDT002439315.1' already exists. Skipping...
Folder 'GCA_044008095.1_PDT002439457.1' already exists. Skipping...
Folder 'GCA_044008135.1_PDT002439425.1' already exists. Skipping...
Folder 'GCA_044008155.1_PDT002439387.1' already exists. Skipping...
Folder 'GCA_044008175.1_PDT002439338.1' already exists. Skipping...
Folder 'GCA_044008195.1_PDT002439360.1' already exists. Skipping...
Folder 'GCA_044008215.1_PDT002439327.1' already exists. Skipping...
Folder 'GCA_044008235.1_PDT002439325.1' already exists. Skipping...
Folder 'GCA_044008255.1_PDT002439310.1' already exists. Skipping...
Folder 'GCA_044009135.1_PDT002439431.1' already exists. Skipping...
Folder 'GCA_044009175.1_PDT002439399.1' already exists. Skipping...
Folder 'GCA_044009195.1_PDT002439391.1' already exists. Skipping...
Folder 'GCA_044009235.1_PDT002439363.1' already exists. Skipping...
Folder 'GCA_044009255.1_PDT002439351.1' already exists. Skipping...
Folder 'GCA_044009275.1_PDT002439346.1' already exists. Skipping...
Folder 'GCA_044009295.1_PDT002439331.1' already exists. Skipping...
Folder 'GCA_044009375.1_PDT002439305.1' already exists. Skipping...
Folder 'GCA_044009385.1_PDT002439297.1' already exists. Skipping...
Folder 'GCA_044009395.1_PDT002439307.1' already exists. Skipping...
Folder 'GCA_044009435.1_PDT002439296.1' already exists. Skipping...
Folder 'GCA_044009455.1_PDT002439295.1' already exists. Skipping...
Folder 'GCA_044009475.1_PDT002439289.1' already exists. Skipping...
Folder 'GCA_044009495.1_PDT002439291.1' already exists. Skipping...
Folder 'GCA_044009515.1_PDT002439294.1' already exists. Skipping...
Folder 'GCA_044009535.1_PDT002439286.1' already exists. Skipping...
Folder 'GCA_044010175.1_PDT002439367.1' already exists. Skipping...
Folder 'GCA_044010195.1_PDT002439335.1' already exists. Skipping...
Folder 'GCA_044011185.1_PDT002439359.1' already exists. Skipping...
Folder 'GCA_044011275.1_PDT002439311.1' already exists. Skipping...
Folder 'GCA_044014175.1_PDT002439579.1' already exists. Skipping...
Folder 'GCA_044023155.1_PDT002439788.1' already exists. Skipping...
Folder 'GCA_044023195.1_PDT002439766.1' already exists. Skipping...
Folder 'GCA_044023215.1_PDT002439756.1' already exists. Skipping...
Folder 'GCA_044023235.1_PDT002439770.1' already exists. Skipping...
Folder 'GCA_044023255.1_PDT002439781.1' already exists. Skipping...
Folder 'GCA_044024175.1_PDT002439784.1' already exists. Skipping...
Folder 'GCA_044024235.1_PDT002439798.1' already exists. Skipping...
Folder 'GCA_044024255.1_PDT002439779.1' already exists. Skipping...
Folder 'GCA_044032635.1_PDT002442121.1' already exists. Skipping...
Folder 'GCA_044032675.1_PDT002442116.1' already exists. Skipping...
Folder 'GCA_044032715.1_PDT002442094.1' already exists. Skipping...
Folder 'GCA_044032765.1_PDT002442076.1' already exists. Skipping...
Folder 'GCA_044032825.1_PDT002442069.1' already exists. Skipping...
Folder 'GCA_044032845.1_PDT002442024.1' already exists. Skipping...
Folder 'GCA_044033145.1_PDT002332102.1' already exists. Skipping...
Folder 'GCA_044033165.1_PDT002332103.1' already exists. Skipping...
Folder 'GCA_044033745.1_PDT002442148.1' already exists. Skipping...
Folder 'GCA_044033885.1_PDT002442138.1' already exists. Skipping...
Folder 'GCA_044033945.1_PDT002442137.1' already exists. Skipping...
Folder 'GCA_044034025.1_PDT002442132.1' already exists. Skipping...
Folder 'GCA_044034045.1_PDT002442130.1' already exists. Skipping...
Folder 'GCA_044034085.1_PDT002442128.1' already exists. Skipping...
Folder 'GCA_044034105.1_PDT002442124.1' already exists. Skipping...
Folder 'GCA_044034125.1_PDT002442123.1' already exists. Skipping...
Folder 'GCA_044034165.1_PDT002442126.1' already exists. Skipping...
Folder 'GCA_044034245.1_PDT002442118.1' already exists. Skipping...
Folder 'GCA_044034265.1_PDT002442112.1' already exists. Skipping...
Folder 'GCA_044034285.1_PDT002442107.1' already exists. Skipping...
Folder 'GCA_044034545.1_PDT002442088.1' already exists. Skipping...
Folder 'GCA_044034565.1_PDT002442095.1' already exists. Skipping...
Folder 'GCA_044034605.1_PDT002332101.1' already exists. Skipping...
Folder 'GCA_044034625.1_PDT002332100.1' already exists. Skipping...
Folder 'GCA_044034645.1_PDT002332099.1' already exists. Skipping...
Folder 'GCA_044034685.1_PDT002332097.1' already exists. Skipping...
Folder 'GCA_044034705.1_PDT002332096.1' already exists. Skipping...
Folder 'GCA_044034725.1_PDT002332094.1' already exists. Skipping...
Folder 'GCA_044034745.1_PDT002332095.1' already exists. Skipping...
Folder 'GCA_044034765.1_PDT002332091.1' already exists. Skipping...
Folder 'GCA_044034785.1_PDT002332090.1' already exists. Skipping...
Folder 'GCA_044034805.1_PDT002332092.1' already exists. Skipping...
Folder 'GCA_044036175.1_PDT002331535.1' already exists. Skipping...
Folder 'GCA_044036195.1_PDT002331534.1' already exists. Skipping...
Folder 'GCA_044036215.1_PDT002331533.1' already exists. Skipping...
Folder 'GCA_044036295.1_PDT002442109.1' already exists. Skipping...
Folder 'GCA_044036335.1_PDT002442085.1' already exists. Skipping...
Folder 'GCA_044036395.1_PDT002442078.1' already exists. Skipping...
Folder 'GCA_044036435.1_PDT002442075.1' already exists. Skipping...
Folder 'GCA_044036575.1_PDT002442062.1' already exists. Skipping...
Folder 'GCA_044036615.1_PDT002442057.1' already exists. Skipping...
Folder 'GCA_044036675.1_PDT002442031.1' already exists. Skipping...
Folder 'GCA_044036695.1_PDT002442032.1' already exists. Skipping...
Folder 'GCA_044036755.1_PDT002442028.1' already exists. Skipping...
Folder 'GCA_044036795.1_PDT002442022.1' already exists. Skipping...
Folder 'GCA_044036835.1_PDT002442023.1' already exists. Skipping...
Folder 'GCA_044036915.1_PDT002442018.1' already exists. Skipping...
Folder 'GCA_044038355.1_PDT002330304.1' already exists. Skipping...
Folder 'GCA_044038375.1_PDT002330305.1' already exists. Skipping...
Folder 'GCA_044038415.1_PDT002330303.1' already exists. Skipping...
Folder 'GCA_044038435.1_PDT002330302.1' already exists. Skipping...
Folder 'GCA_044039195.1_PDT002329693.1' already exists. Skipping...
Folder 'GCA_044039235.1_PDT002329692.1' already exists. Skipping...
Folder 'GCA_044039255.1_PDT002329690.1' already exists. Skipping...
Folder 'GCA_044039275.1_PDT002329691.1' already exists. Skipping...
Folder 'GCA_044039295.1_PDT002329689.1' already exists. Skipping...
Folder 'GCA_044039785.1_PDT002329650.1' already exists. Skipping...
Folder 'GCA_044039805.1_PDT002329649.1' already exists. Skipping...
Folder 'GCA_044039825.1_PDT002329648.1' already exists. Skipping...
Folder 'GCA_044039845.1_PDT002329647.1' already exists. Skipping...
Folder 'GCA_044039865.1_PDT002329645.1' already exists. Skipping...
Folder 'GCA_044039905.1_PDT002329644.1' already exists. Skipping...
Folder 'GCA_044041305.1_PDT002329556.1' already exists. Skipping...
Folder 'GCA_044041325.1_PDT002329557.1' already exists. Skipping...
Folder 'GCA_044041345.1_PDT002329558.1' already exists. Skipping...
Folder 'GCA_044041365.1_PDT002329554.1' already exists. Skipping...
Folder 'GCA_044041385.1_PDT002329555.1' already exists. Skipping...
Folder 'GCA_044041395.1_PDT002329553.1' already exists. Skipping...
Folder 'GCA_044041425.1_PDT002329552.1' already exists. Skipping...
Folder 'GCA_044041445.1_PDT002329550.1' already exists. Skipping...
Folder 'GCA_044041465.1_PDT002329549.1' already exists. Skipping...
Folder 'GCA_044041475.1_PDT002329551.1' already exists. Skipping...
Folder 'GCA_044041515.1_PDT002329547.1' already exists. Skipping...
Folder 'GCA_044041535.1_PDT002329544.1' already exists. Skipping...
Folder 'GCA_044041555.1_PDT002329545.1' already exists. Skipping...
Folder 'GCA_044041575.1_PDT002329546.1' already exists. Skipping...
Folder 'GCA_044042215.1_PDT002329459.1' already exists. Skipping...
Folder 'GCA_044042275.1_PDT002329458.1' already exists. Skipping...
Folder 'GCA_044042435.1_PDT002329457.1' already exists. Skipping...
Folder 'GCA_044042455.1_PDT002329456.1' already exists. Skipping...
Folder 'GCA_044042475.1_PDT002329454.1' already exists. Skipping...
Folder 'GCA_044042495.1_PDT002329455.1' already exists. Skipping...
Folder 'GCA_044042515.1_PDT002329452.1' already exists. Skipping...
Folder 'GCA_044042555.1_PDT002329450.1' already exists. Skipping...
Folder 'GCA_044045745.1_PDT002442080.1' already exists. Skipping...
Folder 'GCA_044046015.1_PDT002329122.1' already exists. Skipping...
Folder 'GCA_044047435.1_PDT002329121.1' already exists. Skipping...

Retreiveing data: 115035it [00:18, 6636.99it/s]

Folder 'GCA_045062625.1_PDT002477583.1' already exists. Skipping...
Folder 'GCA_045062645.1_PDT002477581.1' already exists. Skipping...
Folder 'GCA_045062665.1_PDT002477587.1' already exists. Skipping...
Folder 'GCA_045062905.1_PDT002477669.1' already exists. Skipping...
Folder 'GCA_045062975.1_PDT002477578.1' already exists. Skipping...
Folder 'GCA_045063025.1_PDT002477577.1' already exists. Skipping...
Folder 'GCA_045063045.1_PDT002477579.1' already exists. Skipping...
Folder 'GCA_045063065.1_PDT002477575.1' already exists. Skipping...
Folder 'GCA_045063145.1_PDT002477570.1' already exists. Skipping...
Folder 'GCA_045063205.1_PDT002477574.1' already exists. Skipping...
Folder 'GCA_045063225.1_PDT002477573.1' already exists. Skipping...
Folder 'GCA_045063265.1_PDT002477569.1' already exists. Skipping...
Folder 'GCA_045063305.1_PDT002477568.1' already exists. Skipping...
Folder 'GCA_045063325.1_PDT002477565.1' already exists. Skipping...
Folder 'GCA_045063345.1_PDT002477566.1' already exists. Skipping...
Folder 'GCA_045063465.1_PDT002477560.1' already exists. Skipping...
Folder 'GCA_045063485.1_PDT002477559.1' already exists. Skipping...
Folder 'GCA_045063505.1_PDT002477564.1' already exists. Skipping...
Folder 'GCA_045063545.1_PDT002477558.1' already exists. Skipping...
Folder 'GCA_045063595.1_PDT002477557.1' already exists. Skipping...
Folder 'GCA_045063675.1_PDT002477555.1' already exists. Skipping...
Folder 'GCA_045063705.1_PDT002477556.1' already exists. Skipping...
Folder 'GCA_045063765.1_PDT002477554.1' already exists. Skipping...
Folder 'GCA_045063835.1_PDT002477553.1' already exists. Skipping...
Folder 'GCA_045063865.1_PDT002477552.1' already exists. Skipping...
Folder 'GCA_045063995.1_PDT002477551.1' already exists. Skipping...
Folder 'GCA_045064005.1_PDT002477549.1' already exists. Skipping...
Folder 'GCA_045064015.1_PDT002477550.1' already exists. Skipping...
Folder 'GCA_045064075.1_PDT002477548.1' already exists. Skipping...
Folder 'GCA_045064245.1_PDT002477545.1' already exists. Skipping...
Folder 'GCA_045064655.1_PDT002477534.1' already exists. Skipping...
Folder 'GCA_045064755.1_PDT002477533.1' already exists. Skipping...
Folder 'GCA_045064765.1_PDT002477532.1' already exists. Skipping...
Folder 'GCA_045064785.1_PDT002477531.1' already exists. Skipping...
Folder 'GCA_045064855.1_PDT002477529.1' already exists. Skipping...
Folder 'GCA_045064895.1_PDT002477530.1' already exists. Skipping...
Folder 'GCA_045065195.1_PDT002477528.1' already exists. Skipping...
Folder 'GCA_045065415.1_PDT002477522.1' already exists. Skipping...
Folder 'GCA_045065455.1_PDT002477521.1' already exists. Skipping...
Folder 'GCA_045065465.1_PDT002477520.1' already exists. Skipping...
Folder 'GCA_045065515.1_PDT002477519.1' already exists. Skipping...
Folder 'GCA_045065575.1_PDT002477518.1' already exists. Skipping...
Folder 'GCA_045065655.1_PDT002477514.1' already exists. Skipping...
Folder 'GCA_045065665.1_PDT002477517.1' already exists. Skipping...
Folder 'GCA_045065675.1_PDT002477515.1' already exists. Skipping...
Folder 'GCA_045065775.1_PDT002477513.1' already exists. Skipping...
Folder 'GCA_045065805.1_PDT002477512.1' already exists. Skipping...
Folder 'GCA_045065845.1_PDT002477510.1' already exists. Skipping...
Folder 'GCA_045065875.1_PDT002477511.1' already exists. Skipping...
Folder 'GCA_045065895.1_PDT002477509.1' already exists. Skipping...
Folder 'GCA_045065995.1_PDT002477507.1' already exists. Skipping...
Folder 'GCA_045066035.1_PDT002477508.1' already exists. Skipping...
Folder 'GCA_045066055.1_PDT002477506.1' already exists. Skipping...
Folder 'GCA_045066115.1_PDT002477505.1' already exists. Skipping...
Folder 'GCA_045066135.1_PDT002477503.1' already exists. Skipping...
Folder 'GCA_045066195.1_PDT002477504.1' already exists. Skipping...
Folder 'GCA_045066235.1_PDT002477502.1' already exists. Skipping...
Folder 'GCA_045066295.1_PDT002477501.1' already exists. Skipping...
Folder 'GCA_045066315.1_PDT002477499.1' already exists. Skipping...
Folder 'GCA_045066375.1_PDT002477498.1' already exists. Skipping...
Folder 'GCA_045066435.1_PDT002477500.1' already exists. Skipping...
Folder 'GCA_045066475.1_PDT002477497.1' already exists. Skipping...
Folder 'GCA_045066495.1_PDT002477496.1' already exists. Skipping...
Folder 'GCA_045066535.1_PDT002477493.1' already exists. Skipping...
Folder 'GCA_045066595.1_PDT002477495.1' already exists. Skipping...
Folder 'GCA_045066635.1_PDT002477494.1' already exists. Skipping...
Folder 'GCA_045066695.1_PDT002477492.1' already exists. Skipping...
Folder 'GCA_045066715.1_PDT002477491.1' already exists. Skipping...
Folder 'GCA_045066755.1_PDT002477485.1' already exists. Skipping...
Folder 'GCA_045066765.1_PDT002477483.1' already exists. Skipping...
Folder 'GCA_045066795.1_PDT002477488.1' already exists. Skipping...
Folder 'GCA_045066815.1_PDT002477480.1' already exists. Skipping...
Folder 'GCA_045066835.1_PDT002477484.1' already exists. Skipping...
Folder 'GCA_045066855.1_PDT002477481.1' already exists. Skipping...
Folder 'GCA_045066875.1_PDT002477478.1' already exists. Skipping...
Folder 'GCA_045066885.1_PDT002477479.1' already exists. Skipping...
Folder 'GCA_045066955.1_PDT002477477.1' already exists. Skipping...
Folder 'GCA_045067135.1_PDT002477475.1' already exists. Skipping...
Folder 'GCA_045067155.1_PDT002477476.1' already exists. Skipping...
Folder 'GCA_045067195.1_PDT002477469.1' already exists. Skipping...
Folder 'GCA_045067215.1_PDT002477471.1' already exists. Skipping...
Folder 'GCA_045067335.1_PDT002477459.1' already exists. Skipping...
Folder 'GCA_045067355.1_PDT002477458.1' already exists. Skipping...
Folder 'GCA_045067375.1_PDT002477455.1' already exists. Skipping...
Folder 'GCA_045067395.1_PDT002477457.1' already exists. Skipping...
Folder 'GCA_045067415.1_PDT002477454.1' already exists. Skipping...
Folder 'GCA_045067435.1_PDT002477449.1' already exists. Skipping...
Folder 'GCA_045067455.1_PDT002477453.1' already exists. Skipping...
Folder 'GCA_045067475.1_PDT002477450.1' already exists. Skipping...
Folder 'GCA_045067485.1_PDT002477447.1' already exists. Skipping...
Folder 'GCA_045067515.1_PDT002477446.1' already exists. Skipping...
Folder 'GCA_045067535.1_PDT002477444.1' already exists. Skipping...
Folder 'GCA_045067545.1_PDT002477445.1' already exists. Skipping...
Folder 'GCA_045067575.1_PDT002477440.1' already exists. Skipping...
Folder 'GCA_045067585.1_PDT002477441.1' already exists. Skipping...
Folder 'GCA_045067615.1_PDT002477442.1' already exists. Skipping...
Folder 'GCA_045067635.1_PDT002477437.1' already exists. Skipping...
Folder 'GCA_045067655.1_PDT002477436.1' already exists. Skipping...
Folder 'GCA_045067675.1_PDT002477435.1' already exists. Skipping...
Folder 'GCA_045067695.1_PDT002477434.1' already exists. Skipping...
Folder 'GCA_045067715.1_PDT002477433.1' already exists. Skipping...
Folder 'GCA_045067735.1_PDT002477431.1' already exists. Skipping...
Folder 'GCA_045067745.1_PDT002477432.1' already exists. Skipping...
Folder 'GCA_045067775.1_PDT002477430.1' already exists. Skipping...
Folder 'GCA_045067795.1_PDT002477429.1' already exists. Skipping...
Folder 'GCA_045067935.1_PDT002477422.1' already exists. Skipping...
Folder 'GCA_045068095.1_PDT002477411.1' already exists. Skipping...
Folder 'GCA_045068195.1_PDT002477407.1' already exists. Skipping...
Folder 'GCA_045068215.1_PDT002477408.1' already exists. Skipping...
Folder 'GCA_045068235.1_PDT002477406.1' already exists. Skipping...
Folder 'GCA_045068255.1_PDT002477405.1' already exists. Skipping...
Folder 'GCA_045068275.1_PDT002477402.1' already exists. Skipping...
Folder 'GCA_045068295.1_PDT002477404.1' already exists. Skipping...
Folder 'GCA_045068315.1_PDT002477401.1' already exists. Skipping...
Folder 'GCA_045068335.1_PDT002477403.1' already exists. Skipping...
Folder 'GCA_045068355.1_PDT002477400.1' already exists. Skipping...
Folder 'GCA_045068375.1_PDT002477399.1' already exists. Skipping...
Folder 'GCA_045068395.1_PDT002477398.1' already exists. Skipping...
Folder 'GCA_045068415.1_PDT002477397.1' already exists. Skipping...
Folder 'GCA_045068435.1_PDT002477392.1' already exists. Skipping...
Folder 'GCA_045068455.1_PDT002477395.1' already exists. Skipping...
Folder 'GCA_045068475.1_PDT002477391.1' already exists. Skipping...
Folder 'GCA_045068495.1_PDT002477394.1' already exists. Skipping...
Folder 'GCA_045068515.1_PDT002477393.1' already exists. Skipping...
Folder 'GCA_045068535.1_PDT002477390.1' already exists. Skipping...
Folder 'GCA_045068555.1_PDT002477389.1' already exists. Skipping...
Folder 'GCA_045068565.1_PDT002477388.1' already exists. Skipping...
Folder 'GCA_045068595.1_PDT002477387.1' already exists. Skipping...
Folder 'GCA_045068715.1_PDT002477380.1' already exists. Skipping...
Folder 'GCA_045068795.1_PDT002477376.1' already exists. Skipping...
Folder 'GCA_045068945.1_PDT002477370.1' already exists. Skipping...
Folder 'GCA_045069755.1_PDT002477369.1' already exists. Skipping...
Folder 'GCA_045069815.1_PDT002477367.1' already exists. Skipping...
Folder 'GCA_045069825.1_PDT002477366.1' already exists. Skipping...
Folder 'GCA_045069855.1_PDT002477364.1' already exists. Skipping...
Folder 'GCA_045069875.1_PDT002477362.1' already exists. Skipping...
Folder 'GCA_045069895.1_PDT002477365.1' already exists. Skipping...
Folder 'GCA_045069935.1_PDT002477361.1' already exists. Skipping...
Folder 'GCA_045070135.1_PDT002477349.1' already exists. Skipping...
Folder 'GCA_045070155.1_PDT002477350.1' already exists. Skipping...
Folder 'GCA_045070175.1_PDT002477348.1' already exists. Skipping...
Folder 'GCA_045070195.1_PDT002477347.1' already exists. Skipping...
Folder 'GCA_045070215.1_PDT002477345.1' already exists. Skipping...
Folder 'GCA_045070235.1_PDT002477346.1' already exists. Skipping...
Folder 'GCA_045070255.1_PDT002477344.1' already exists. Skipping...
Folder 'GCA_045070275.1_PDT002477343.1' already exists. Skipping...
Folder 'GCA_045070285.1_PDT002477342.1' already exists. Skipping...
Folder 'GCA_045070315.1_PDT002477340.1' already exists. Skipping...
Folder 'GCA_045070325.1_PDT002477341.1' already exists. Skipping...
Folder 'GCA_045070375.1_PDT002477338.1' already exists. Skipping...
Folder 'GCA_045070415.1_PDT002477339.1' already exists. Skipping...
Folder 'GCA_045070425.1_PDT002477337.1' already exists. Skipping...
Folder 'GCA_045070475.1_PDT002477332.1' already exists. Skipping...
Folder 'GCA_045070535.1_PDT002477331.1' already exists. Skipping...
Folder 'GCA_045070565.1_PDT002477330.1' already exists. Skipping...
Folder 'GCA_045070585.1_PDT002477329.1' already exists. Skipping...
Folder 'GCA_045070605.1_PDT002477328.1' already exists. Skipping...
Folder 'GCA_045070625.1_PDT002477327.1' already exists. Skipping...
Folder 'GCA_045070645.1_PDT002477326.1' already exists. Skipping...
Folder 'GCA_045070665.1_PDT002477325.1' already exists. Skipping...
Folder 'GCA_045070685.1_PDT002477324.1' already exists. Skipping...
Folder 'GCA_045070705.1_PDT002477323.1' already exists. Skipping...
Folder 'GCA_045070725.1_PDT002477319.1' already exists. Skipping...
Folder 'GCA_045070745.1_PDT002477321.1' already exists. Skipping...
Folder 'GCA_045070765.1_PDT002477320.1' already exists. Skipping...
Folder 'GCA_045070785.1_PDT002477317.1' already exists. Skipping...
Folder 'GCA_045070805.1_PDT002477318.1' already exists. Skipping...
Folder 'GCA_045070825.1_PDT002477322.1' already exists. Skipping...
Folder 'GCA_045070845.1_PDT002477315.1' already exists. Skipping...
Folder 'GCA_045070865.1_PDT002477316.1' already exists. Skipping...
Folder 'GCA_045070885.1_PDT002477314.1' already exists. Skipping...
Folder 'GCA_045070905.1_PDT002477313.1' already exists. Skipping...
Folder 'GCA_045070935.1_PDT002477310.1' already exists. Skipping...
Folder 'GCA_045070965.1_PDT002477311.1' already exists. Skipping...
Folder 'GCA_045070985.1_PDT002477309.1' already exists. Skipping...
Folder 'GCA_045071005.1_PDT002477308.1' already exists. Skipping...
Folder 'GCA_045071045.1_PDT002477305.1' already exists. Skipping...
Folder 'GCA_045071105.1_PDT002477303.1' already exists. Skipping...
Folder 'GCA_045071145.1_PDT002477301.1' already exists. Skipping...
Folder 'GCA_045071165.1_PDT002477299.1' already exists. Skipping...
Folder 'GCA_045071185.1_PDT002477298.1' already exists. Skipping...
Folder 'GCA_045071205.1_PDT002477300.1' already exists. Skipping...
Folder 'GCA_045071225.1_PDT002477297.1' already exists. Skipping...
Folder 'GCA_045071245.1_PDT002477296.1' already exists. Skipping...
Folder 'GCA_045071265.1_PDT002477295.1' already exists. Skipping...
Folder 'GCA_045071285.1_PDT002477293.1' already exists. Skipping...
Folder 'GCA_045071295.1_PDT002477292.1' already exists. Skipping...
Folder 'GCA_045071325.1_PDT002477290.1' already exists. Skipping...
Folder 'GCA_045071335.1_PDT002477288.1' already exists. Skipping...
Folder 'GCA_045071345.1_PDT002477289.1' already exists. Skipping...
Folder 'GCA_045071355.1_PDT002477291.1' already exists. Skipping...
Folder 'GCA_045071405.1_PDT002477286.1' already exists. Skipping...
Folder 'GCA_045071425.1_PDT002477285.1' already exists. Skipping...
Folder 'GCA_045071465.1_PDT002477287.1' already exists. Skipping...
Folder 'GCA_045071505.1_PDT002477282.1' already exists. Skipping...
Folder 'GCA_045071565.1_PDT002477278.1' already exists. Skipping...
Folder 'GCA_045071585.1_PDT002477276.1' already exists. Skipping...
Folder 'GCA_045071605.1_PDT002477279.1' already exists. Skipping...
Folder 'GCA_045071615.1_PDT002477277.1' already exists. Skipping...
Folder 'GCA_045071645.1_PDT002477275.1' already exists. Skipping...
Folder 'GCA_045071665.1_PDT002477274.1' already exists. Skipping...
Folder 'GCA_045071685.1_PDT002477273.1' already exists. Skipping...
Folder 'GCA_045071705.1_PDT002477271.1' already exists. Skipping...
Folder 'GCA_045071715.1_PDT002477269.1' already exists. Skipping...
Folder 'GCA_045071725.1_PDT002477272.1' already exists. Skipping...
Folder 'GCA_045071765.1_PDT002477270.1' already exists. Skipping...
Folder 'GCA_045138895.1_PDT002480154.1' already exists. Skipping...
Folder 'GCA_045138935.1_PDT002480151.1' already exists. Skipping...
Folder 'GCA_045139015.1_PDT002480147.1' already exists. Skipping...
Folder 'GCA_045139075.1_PDT002480148.1' already exists. Skipping...
Folder 'GCA_045139095.1_PDT002480144.1' already exists. Skipping...
Folder 'GCA_045172125.1_PDT002139281.1' already exists. Skipping...
Folder 'GCA_045172145.1_PDT002139282.1' already exists. Skipping...
Folder 'GCA_045172165.1_PDT002139280.1' already exists. Skipping...
Folder 'GCA_045172185.1_PDT002139279.1' already exists. Skipping...
Folder 'GCA_045172205.1_PDT002139277.1' already exists. Skipping...
Folder 'GCA_045172225.1_PDT002139276.1' already exists. Skipping...
Folder 'GCA_045172245.1_PDT002139270.1' already exists. Skipping...
Folder 'GCA_045172265.1_PDT002139274.1' already exists. Skipping...
Folder 'GCA_045172305.1_PDT002139272.1' already exists. Skipping...
Folder 'GCA_045172325.1_PDT002139269.1' already exists. Skipping...
Folder 'GCA_045172345.1_PDT002139268.1' already exists. Skipping...
Folder 'GCA_045172365.1_PDT002139267.1' already exists. Skipping...
Folder 'GCA_045172385.1_PDT002139264.1' already exists. Skipping...
Folder 'GCA_045172445.1_PDT002139265.1' already exists. Skipping...
Folder 'GCA_045172485.1_PDT002139262.1' already exists. Skipping...
Folder 'GCA_045172505.1_PDT002139261.1' already exists. Skipping...
Folder 'GCA_045172525.1_PDT002139263.1' already exists. Skipping...
Folder 'GCA_045172545.1_PDT002139257.1' already exists. Skipping...
Folder 'GCA_045172565.1_PDT002139256.1' already exists. Skipping...
Folder 'GCA_045172585.1_PDT002139260.1' already exists. Skipping...
Folder 'GCA_045172625.1_PDT002139251.1' already exists. Skipping...
Folder 'GCA_045172665.1_PDT002139254.1' already exists. Skipping...
Folder 'GCA_045173525.1_PDT002481065.1' already exists. Skipping...
Folder 'GCA_045175665.1_PDT002481073.1' already exists. Skipping...
Folder 'GCA_045176785.1_PDT002481076.1' already exists. Skipping...
Folder 'GCA_045176845.1_PDT002481068.1' already exists. Skipping...
Folder 'GCA_045177845.1_PDT002481074.1' already exists. Skipping...
Folder 'GCA_045177865.1_PDT002481077.1' already exists. Skipping...
Folder 'GCA_045178885.1_PDT002481075.1' already exists. Skipping...
Folder 'GCA_045178905.1_PDT002481067.1' already exists. Skipping...
Folder 'GCA_045179925.1_PDT002481117.1' already exists. Skipping...
Folder 'GCA_045180965.1_PDT002481116.1' already exists. Skipping...
Folder 'GCA_045180985.1_PDT002481120.1' already exists. Skipping...
Folder 'GCA_045181005.1_PDT002481079.1' already exists. Skipping...
Folder 'GCA_045181165.1_PDT002481119.1' already exists. Skipping...
Folder 'GCA_045187085.1_PDT002482110.1' already exists. Skipping...
Folder 'GCA_045187105.1_PDT002482101.1' already exists. Skipping...
Folder 'GCA_045187145.1_PDT002482099.1' already exists. Skipping...
Folder 'GCA_045190705.1_PDT002482058.1' already exists. Skipping...
Folder 'GCA_045191445.1_PDT002482857.1' already exists. Skipping...
Folder 'GCA_045195445.1_PDT002483009.1' already exists. Skipping...
Folder 'GCA_045195465.1_PDT002483006.1' already exists. Skipping...
Folder 'GCA_045195485.1_PDT002483002.1' already exists. Skipping...
Folder 'GCA_045196505.1_PDT002483032.1' already exists. Skipping...
Folder 'GCA_045196615.1_PDT002483027.1' already exists. Skipping...
Folder 'GCA_045197085.1_PDT002477981.1' already exists. Skipping...
Folder 'GCA_045197105.1_PDT002477983.1' already exists. Skipping...
Folder 'GCA_045197125.1_PDT002477986.1' already exists. Skipping...
Folder 'GCA_045197145.1_PDT002477993.1' already exists. Skipping...
Folder 'GCA_045197165.1_PDT002477974.1' already exists. Skipping...
Folder 'GCA_045197185.1_PDT002477971.1' already exists. Skipping...
Folder 'GCA_045197205.1_PDT002477966.1' already exists. Skipping...
Folder 'GCA_045197215.1_PDT002477968.1' already exists. Skipping...
Folder 'GCA_045197245.1_PDT002477961.1' already exists. Skipping...
Folder 'GCA_045197285.1_PDT002477881.1' already exists. Skipping...
Folder 'GCA_045197305.1_PDT002477886.1' already exists. Skipping...
Folder 'GCA_045197325.1_PDT002477879.1' already exists. Skipping...
Folder 'GCA_045197345.1_PDT002477872.1' already exists. Skipping...
Folder 'GCA_045197365.1_PDT002477748.1' already exists. Skipping...
Folder 'GCA_045197385.1_PDT002477869.1' already exists. Skipping...
Folder 'GCA_045197405.1_PDT002477745.1' already exists. Skipping...
Folder 'GCA_045197425.1_PDT002477743.1' already exists. Skipping...
Folder 'GCA_045197445.1_PDT002477741.1' already exists. Skipping...
Folder 'GCA_045197465.1_PDT002477738.1' already exists. Skipping...
Folder 'GCA_045197485.1_PDT002477731.1' already exists. Skipping...
Folder 'GCA_045197505.1_PDT002477728.1' already exists. Skipping...
Folder 'GCA_045197545.1_PDT002477716.1' already exists. Skipping...
Folder 'GCA_045197555.1_PDT002477718.1' already exists. Skipping...
Folder 'GCA_045197605.1_PDT002477706.1' already exists. Skipping...
Folder 'GCA_045226935.1_PDT002483397.1' already exists. Skipping...
Folder 'GCA_045226955.1_PDT002483390.1' already exists. Skipping...
Folder 'GCA_045226975.1_PDT002483371.1' already exists. Skipping...
Folder 'GCA_045226995.1_PDT002483370.1' already exists. Skipping...
Folder 'GCA_045227015.1_PDT002483350.1' already exists. Skipping...
Folder 'GCA_045227055.1_PDT002483358.1' already exists. Skipping...
Folder 'GCA_045229915.1_PDT002483389.1' already exists. Skipping...
Folder 'GCA_045233935.1_PDT002483355.1' already exists. Skipping...
Folder 'GCA_045237975.1_PDT002484339.1' already exists. Skipping...
Folder 'GCA_045240175.1_PDT002484346.1' already exists. Skipping...
Folder 'GCA_045245335.1_PDT002484452.1' already exists. Skipping...
Folder 'GCA_045245395.1_PDT002484351.1' already exists. Skipping...
Folder 'GCA_045249235.1_PDT002484353.1' already exists. Skipping...
Folder 'GCA_045262105.1_PDT002492707.1' already exists. Skipping...

Retreiveing data: 129519it [11:16:49,  3.08s/it]

Error downloading the file: ('Connection broken: IncompleteRead(81920 bytes read, 1906619 more expected)', IncompleteRead(81920 bytes read, 1906619 more expected))

Retreiveing data: 138288it [18:48:32,  2.43s/it]

In [ ]:
# END